### ISSUE TITLE
Compiler crash with decorator and two "export default"s

### ISSUE THREAD

**Issue by dangoor** [Microsoft/TypeScript#10193]
**TypeScript Version:**  nightly (2.1.0-dev.20160806)

**Code**

Here's package.json to show the dependencies for this example:

```json
{
  "name": "compiler-bug",
  "version": "1.0.0",
  "description": "",
  "main": "test.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "mobx": "^2.4.2",
    "mobx-react": "^3.5.4",
    "react": "^15.3.0",
    "react-dom": "^15.3.0"
  }
}
```

Here is `test.tsx`:

```ts
import {observer} from "mobx-react";

@observer
export default class Foo {
	render() {
		return <div>Hi</div>;
	}
}

export default {
	uhoh: "another default",
};
```

**Expected behavior:**

An error for repeated `export default`

**Actual behavior:** 

`tsc --jsx react --experimentalDecorators test.tsx`

The following exception:

```
/usr/local/lib/node_modules/typescript/lib/tsc.js:37458
                throw e;
                ^

TypeError: Cannot read property 'kind' of undefined
    at getTypeForVariableLikeDeclaration (/usr/local/lib/node_modules/typescript/lib/tsc.js:15468:42)
    at getWidenedTypeForVariableLikeDeclaration (/usr/local/lib/node_modules/typescript/lib/tsc.js:15570:24)
    at getTypeOfVariableOrParameterOrProperty (/usr/local/lib/node_modules/typescript/lib/tsc.js:15621:28)
    at getTypeOfSymbol (/usr/local/lib/node_modules/typescript/lib/tsc.js:15748:24)
    at getEffectiveDecoratorFirstArgumentType (/usr/local/lib/node_modules/typescript/lib/tsc.js:21923:24)
    at getEffectiveDecoratorArgumentType (/usr/local/lib/node_modules/typescript/lib/tsc.js:22001:24)
    at getEffectiveArgumentType (/usr/local/lib/node_modules/typescript/lib/tsc.js:22014:24)
    at inferTypeArguments (/usr/local/lib/node_modules/typescript/lib/tsc.js:21795:35)
    at chooseOverload (/usr/local/lib/node_modules/typescript/lib/tsc.js:22147:33)
    at resolveCall (/usr/local/lib/node_modules/typescript/lib/tsc.js:22073:26)
```

**Comment by yuit** [comment]
Confirm repo on release-2.0 and master
