### ISSUE TITLE
1.8.10: TypeError: Cannot read property 'typeArguments' of undefined

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/TypeScript#10322]
**TypeScript Version:**  1.8.10 

Update: This **does not** occur under Version 2.1.0-dev.20160813, so it may be moot.

In the midst of a TypeScript conversion for existing JavaScript code, I'm running into a tsc compiler failure generating this message: **TypeError: Cannot read property 'typeArguments' of undefined**

**Code**

I don't have this issue isolated to simple code, but a snapshot of the full project available at https://github.com/BurtHarris/antlr4/tree/tscError, be sure to use branch tscError.   From the `antlr4\runtime\TypeScript\src\antlr4` directory, run the `tsc` command to reproduce the error.

**Expected behavior:**

Error message leading me to correct a mistake in the codebase.

**Actual behavior:** 
```
C:\code\antlr4\runtime\TypeScript\src\antlr4>tsc
C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:33078
                throw e;
                ^

TypeError: Cannot read property 'typeArguments' of undefined
    at resolveCallExpression (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:19354:111)
    at getResolvedSignature (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:19477:47)
    at checkCallExpression (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:19503:29)
    at checkExpressionWorker (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:20399:28)
    at checkExpression (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:20349:42)
    at checkExpressionStatement (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:21609:13)
    at checkSourceElement (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:22973:28)
    at Object.forEach (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:98:30)
    at checkBlock (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:21370:16)
    at checkSourceElement (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:22969:28)
```

**Comment by RyanCavanaugh** [comment]
> This does not occur under Version 2.1.0-dev.20160813

Tagging as fixed. Thanks!

**Comment by BurtHarris** [comment]
Cool, thanks.
