### ISSUE TITLE
[TSServer] Server crash when tsconfig.json file has comments

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#10525]
TS: Version 2.1.0-dev.20160824
VSCode:  Version 1.5.0-insider (1.5.0-insider) c4f365235906cd689e55376e44cc106003ac06b3

This is the project that worked before.  `tsc -p .` works fine

```
[Info  - 4:53:54 PM] Using tsserver from location: /Users/*********/.nvm/versions/node/v4.2.2/lib/node_modules/typescript/lib/tsserver.js
[Error - 4:54:15 PM] 'navto' request failed with error.
Error processing request. Cannot set property 'defaultProject' of undefined
TypeError: Cannot set property 'defaultProject' of undefined
    at ProjectService.findReferencingProjects (/Users/*********/.nvm/versions/node/v4.2.2/lib/node_modules/typescript/lib/tsserver.js:52481:37)
    at IOSession.Session.getNavigateToItems (/Users/*********/.nvm/versions/node/v4.2.2/lib/node_modules/typescript/lib/tsserver.js:51554:52)
    at Session.handlers.ts.createMap._a.(anonymous function) (/Users/*********/.nvm/versions/node/v4.2.2/lib/node_modules/typescript/lib/tsserver.js:50857:50)
    at IOSession.Session.executeCommand (/Users/*********/.nvm/versions/node/v4.2.2/lib/node_modules/typescript/lib/tsserver.js:51673:28)
    at IOSession.Session.onMessage (/Users/*********/.nvm/versions/node/v4.2.2/lib/node_modules/typescript/lib/tsserver.js:51690:35)
    at Interface.<anonymous> (/Users/*********/.nvm/versions/node/v4.2.2/lib/node_modules/typescript/lib/tsserver.js:53884:27)
    at emitOne (events.js:90:13)
    at Interface.emit (events.js:182:7)
    at Interface._onLine (readline.js:211:10)
    at Interface.<anonymous> (readline.js:341:12)
[Error - 4:54:15 PM] 'navto' request failed with error.
Error processing request. Cannot set property 'defaultProject' of undefined
TypeError: Cannot set property 'defaultProject' of undefined
    at ProjectService.findReferencingProjects (/Users/*********/.nvm/versions/node/v4.2.2/lib/node_modules/typescript/lib/tsserver.js:52481:37)
    at IOSession.Session.getNavigateToItems (/Users/*********/.nvm/versions/node/v4.2.2/lib/node_modules/typescript/lib/tsserver.js:51554:52)
    at Session.handlers.ts.createMap._a.(anonymous function) (/Users/*********/.nvm/versions/node/v4.2.2/lib/node_modules/typescript/lib/tsserver.js:50857:50)
    at IOSession.Session.executeCommand (/Users/*********/.nvm/versions/node/v4.2.2/lib/node_modules/typescript/lib/tsserver.js:51673:28)
    at IOSession.Session.onMessage (/Users/*********/.nvm/versions/node/v4.2.2/lib/node_modules/typescript/lib/tsserver.js:51690:35)
    at Interface.<anonymous> (/Users/*********/.nvm/versions/node/v4.2.2/lib/node_modules/typescript/lib/tsserver.js:53884:27)
    at emitOne (events.js:90:13)
    at Interface.emit (events.js:182:7)
    at Interface._onLine (readline.js:211:10)
    at Interface.<anonymous> (readline.js:341:12)

```

**Comment by wallverb** [comment]
`typescript@2.1.0-dev.20160822` is the latest one that works fine

**Comment by mhegazy** [comment]
@zhengbli looks related to recent changes, can you take a look.

**Comment by zhengbli** [comment]
@wallverb can you share the project or have a sample project for reproing the issue? Navto works for me on the compiler code base. I think the bug is related to the project setup.

**Comment by wallverb** [comment]
@zhengbli I will try to create sample project 

In the meantime some more errors:

```
[Info  - 7:34:53 PM] Using tsserver from location: typescript/lib/tsserver.js
[Error - 7:34:54 PM] 'quickinfo' request failed with error.
Error processing request. No Project.
Error: No Project.
    at Errors (typescript/lib/tsserver.js:50737:32)
    at ts.server.ts.server (typescript/lib/tsserver.js:50739:11)
    at ts (typescript/lib/tsserver.js:51719:7)
    at Object.<anonymous> (typescript/lib/tsserver.js:51720:3)
    ...
[Error - 7:35:24 PM] 'occurrences' request failed with error.
Error processing request. No Project.
Error: No Project.
    at Errors (typescript/lib/tsserver.js:50737:32)
    at ts.server.ts.server (typescript/lib/tsserver.js:50739:11)
    at ts (typescript/lib/tsserver.js:51719:7)
    at Object.<anonymous> (typescript/lib/tsserver.js:51720:3)
    ...
```

**Comment by zhengbli** [comment]
Thanks, I suspect these errors may come from the same source, that somehow the server cannot find a file matching the file name. Though I would know better with the sample.

**Comment by wallverb** [comment]
Could it be an issue with VSCode ? I tried stable version (non-insiders one) and it does not have this problem

**Comment by zhengbli** [comment]
But you said with `typescript@2.1.0-dev.20160822` even the insider build of VSCode works fine? That sounds like our problem as well.

**Comment by wallverb** [comment]
Yea, ok, narrowing it down, 1s :)

**Comment by wallverb** [comment]
Ok, so found the issue - after doing divide and conquer (deleting half of files each time and retesting) - I was left with just one file: `tsconfig.json` :D - and it turned out that the issue is because there was a comment in that file - yea apparently vscode is using comments in a lot of their json files and one can do `CMD+/` to comment out things in `.json` files - apparently I did something like that in the past - and seems like it worked until `vscode-insiders + TS2.1.0-dev.20160824` combo :)

So user error - but would be nice to show some error that json can't be parsed or something. Thanks :)

**Comment by zhengbli** [comment]
Wait that should be handled correctly, because the change I made recently is supposed to be more tolerating regarding tsconfig.json files. Can you share the content of your tsconfig.json file?

**Comment by wallverb** [comment]
Sure, here is tsconfig.json

```
{
    "compilerOptions": {
        "outDir": "./dist",
        "sourceMap": true,
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "isolatedModules": false,
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declaration": false,
        "noImplicitAny": true,
        "noImplicitThis": true,
        "noImplicitUseStrict": false,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true,
        // test
        "allowJs": false
    },
    "exclude": [
        "dist",
        "node_modules",
        ".vscode"
    ],
    "compileOnSave": false,
    "buildOnSave": false
}
```

I also have one more empty `test.ts` because it seems that TS kicks in when that file is open. Then I try to open `CMD+P` to go to some file and then `'navto' request failed with error`

**Comment by zhengbli** [comment]
Aha I see the problem. This is because we use TypeScript parser to parse and re-emit the file as .js file, and comments are allowed in js file, so the re-emitted js file didn't strip comments by default. They when we feed `JSON.parse` with that, things break. Will fix soon. Thanks!
