### ISSUE TITLE
TSServer error on lineNumberToInfo

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#10546]
TSC version: Version 2.1.0-dev.20160825

There is a _very specific order to this repro_ and it might be in VS Code.
- Start out with the following two files.

`./src/foo.ts`

``` ts
class Logger {
  public logLevel = Logger.LogLevel.Info;
}

namespace Logger {
  export enum LogLevel {
    Verbose,
    Info
  }
}

export { Logger as default };
```

`./tsconfig.json`

``` ts
{
  "compilerOptions": {
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,

    "moduleResolution": "node",
    "target": "es2015",
    "module": "commonjs",
    "inlineSourceMap": true,
    "declaration": true,

    "rootDir": "src",
    "outDir": "dist"
  },

  "include": [
    "src/**/*"
  ]
}
```
- Now create a new file with `Ctrl+N`.
- Save it as `./src/bar.ts`
- Enter the following into `./src/bar.ts`

``` ts
import x from "./foo"

x
```
- Get quick info on `x`.

Now I get a TSServer error:

```
Response received: quickinfo (27). Request took 4 ms. Success: false . Message: Error processing request. Cannot read property 'lineNumberToInfo' of undefined
TypeError: Cannot read property 'lineNumberToInfo' of undefined
    at LSHost.lineOffsetToPosition (C:\Users\drosen\TypeScript2\built\local\tsserver.js:62192:37)
    at IOSession.Session.getQuickInfo (C:\Users\drosen\TypeScript2\built\local\tsserver.js:61484:53)
    at Session.handlers.ts.createMap._a.(anonymous function) (C:\Users\drosen\TypeScript2\built\local\tsserver.js:60967:50)
    at IOSession.Session.executeCommand (C:\Users\drosen\TypeScript2\built\local\tsserver.js:61870:28)
    at IOSession.Session.onMessage (C:\Users\drosen\TypeScript2\built\local\tsserver.js:61887:35)
    at Interface.<anonymous> (C:\Users\drosen\TypeScript2\built\local\tsserver.js:64262:27)
    at emitOne (events.js:90:13)
    at Interface.emit (events.js:182:7)
    at Interface._onLine (readline.js:211:10)
    at Interface.<anonymous> (readline.js:341:12)
```

**Comment by andy-ms** [comment]
I can't reproduce this with vscode insiders and `typescript@next`. Maybe you'll have to show me in person.
