### ISSUE TITLE
Degradation: Maximum call stack size exceeded on version 2+ (not on 1.8.10)

### ISSUE THREAD

**Issue by ronzeidman** [Microsoft/TypeScript#10629]
**TypeScript Version:**  2.0.0, 2.0.2, 2.1.0-dev.20160831

**Code**
This happened on a large codebase that is currently compiling correctly in 1.8.10, 
I couldn't find what was causing the issue and since I don't know to pinpoint the issue I couldn't replicate it on a smaller scale.
Nothing in the code has changed from the 1.8.10 only the typescript version.
This is a node+express code.

**Expected behavior:**
Compile correctly

**Actual behavior:** 
Callstack of compiling with version 2.0.0
```
RangeError: Maximum call stack size exceeded
    at instantiateSignature (server\node_modules\typescript\lib\tsc.js:17369:38)
    at instantiateList (server\node_modules\typescript\lib\tsc.js:17288:33)
    at resolveObjectTypeMembers (server\node_modules\typescript\lib\tsc.js:16016:34)
    at resolveTypeReferenceMembers (server\node_modules\typescript\lib\tsc.js:16047:13)
    at resolveStructuredTypeMembers (server\node_modules\typescript\lib\tsc.js:16248:21)
    at getPropertiesOfObjectType (server\node_modules\typescript\lib\tsc.js:16270:24)
    at inferFromProperties (server\node_modules\typescript\lib\tsc.js:18856:34)
    at inferFromTypes server\node_modules\typescript\lib\tsc.js:18847:25)
    at inferFromSignature (server\node_modules\typescript\lib\tsc.js:18881:21)
    at inferFromSignatures (server\node_modules\typescript\lib\tsc.js:18872:21)
```

Callstack of compiling with version 2.0.2 or 2.1.0-dev.20160831
```
RangeError: Maximum call stack size exceeded
    at couldContainTypeParameters (server\node_modules\typescript\lib\tsc.js:19193:44)
    at Object.forEach (server\node_modules\typescript\lib\tsc.js:185:30)
    at couldContainTypeParameters (server\node_modules\typescript\lib\tsc.js:19195:43)
    at Object.forEach (server\node_modules\typescript\lib\tsc.js:185:30)
    at couldContainTypeParameters (server\node_modules\typescript\lib\tsc.js:19195:43)
    at Object.forEach (server\node_modules\typescript\lib\tsc.js:185:30)
    at couldContainTypeParameters (server\node_modules\typescript\lib\tsc.js:19195:43)
    at Object.forEach (server\node_modules\typescript\lib\tsc.js:185:30)
    at couldContainTypeParameters (server\node_modules\typescript\lib\tsc.js:19195:43)
    at Object.forEach (server\node_modules\typescript\lib\tsc.js:185:30)
    at couldContainTypeParameters (server\node_modules\typescript\lib\tsc.js:19195:43)
```

Same behavior on Windows and on "Bash on Ubuntu on Windows"

What does types flag 131072 say? I guess its some kind of recursive generic type maybe I could try and find the specific one that causes the issue.

**Comment by ronzeidman** [comment]
[test.zip](https://github.com/Microsoft/TypeScript/files/449196/test.zip)
I've attached the custom definitions that were identified to be the culprit (I've removed all generics from them and the code that used them and everything worked fine) but a trivial usage of these definitions doesn't cause issues, I'll try creating a more complex code that will maybe reproduce the issue. Currently I cannot give access to the full source code, maybe if I couldn't create a smaller reproduction I could send a snapshot of a part of the code specifically to you.
Currently it's not a burning issue for me since I can manage without the generics in these definitions since in the code they gave little value and had to be explicitly written about everywhere and still in most situations you'd have to explicitly cast the result anyway.

**Comment by mhegazy** [comment]
We would love to get to the bottom of the issue. and we would appreciate your help identifying the problem. feel free to email me directly, `mhegazy` at `microsoft` dot `com`

**Comment by mhegazy** [comment]
@ronzeidman would it be possible to share a larger repro project? the samples provided are not enough to reproduce the issue.

**Comment by mhegazy** [comment]
Without more information this issue is unactionable for us at the moment. closing. please reopen if there is more information you can share.
