### ISSUE TITLE
Visual Studio still crashes with TS2.0-rc

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#10626]
Compiling is passed, but VS is crashed. I captured the event log. Where can I send that?

**TypeScript Version:**  2.0-rc

**Code**

https://github.com/falsandtru/spica

**Comment by falsandtru** [comment]
Main log:

```
ソース ".NET Runtime" からのイベント ID 1025 の説明が見つかりません。このイベントを発生させるコンポーネントがローカル コンピューターにインストールされていないか、インストールが壊れています。ローカル コンピューターにコンポーネントをインストールするか、コンポーネントを修復してください。

イベントが別のコンピューターから発生している場合、イベントと共に表示情報を保存する必要があります。

イベントには次の情報が含まれています: 

アプリケーション:devenv.exe
フレームワークのバージョン:v4.0.30319
説明: アプリケーションは System.Environment.FailFast (文字列メッセージ) を使用してプロセスの終了を要求しました。
メッセージ:System.AggregateException: One or more errors occurred. ---> System.IO.IOException: このコマンドを実行するための十分な記憶域がありません。

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, Int64 offset, Int64 size)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewStream(Int64 offset, Int64 size, MemoryMappedFileAccess access)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.MemoryMappedInfo.CreateWritableStream()
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.WriteText(SourceText text, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.<>c__DisplayClass8_0.<WriteTextAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: このコマンドを実行するための十分な記憶域がありません。

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, Int64 offset, Int64 size)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewStream(Int64 offset, Int64 size, MemoryMappedFileAccess access)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.MemoryMappedInfo.CreateWritableStream()
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.WriteText(SourceText text, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.<>c__DisplayClass8_0.<WriteTextAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

スタック:
   場所 System.Environment.FailFast(System.String, System.Exception)
   場所 Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   場所 Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   場所 Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   場所 Roslyn.Utilities.TaskExtensions.ReportFatalErrorWorker(System.Threading.Tasks.Task, System.Object)
   場所 System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   場所 System.Threading.Tasks.Task.Execute()
   場所 System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   場所 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   場所 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   場所 System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   場所 System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   場所 System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
   場所 System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean)
   場所 System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(System.Threading.Tasks.Task, Boolean)
   場所 System.Threading.Tasks.StandardTaskContinuation.Run(System.Threading.Tasks.Task, Boolean)
   場所 System.Threading.Tasks.Task.FinishContinuations()
   場所 System.Threading.Tasks.Task.FinishStageThree()
   場所 System.Threading.Tasks.Task.FinishStageTwo()
   場所 System.Threading.Tasks.Task.Finish(Boolean)
   場所 System.Threading.Tasks.Task`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   場所 System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetFromTask(System.Threading.Tasks.Task, Boolean)
   場所 System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeCore(System.Threading.Tasks.Task)
   場所 System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.TaskExtensions+VoidResult, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Threading.Tasks.Task)
   場所 System.Threading.Tasks.Task.FinishContinuations()
   場所 System.Threading.Tasks.Task.FinishStageThree()
   場所 System.Threading.Tasks.Task.FinishStageTwo()
   場所 System.Threading.Tasks.Task.Finish(Boolean)
   場所 System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   場所 System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   場所 System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   場所 System.Threading.ThreadPoolWorkQueue.Dispatch()
   場所 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


要素が見つかりません。
```

**Comment by mhegazy** [comment]
can you share the output of `--diagnostics` of your compilation.

**Comment by falsandtru** [comment]
Seems like there is no problem in compilation.

```
$ node_modules/.bin/tsc --noEmit -t es5 -m amd --moduleResolution node --lib es6,dom --strictNullChecks --noImplicitAny --noImplicitReturns --noImplicitThis --noU
nusedParameters --noUnusedLocals --suppressImplicitAnyIndexErrors --allowSyntheticDefaultImports --diagnostics *.ts src/**/*.ts
Files:             110
Lines:           25567
Nodes:          146342
Identifiers:     53272
Symbols:        607698
Types:          645298
Memory used:   577531K
I/O read:        0.04s
I/O write:       0.00s
Parse time:      1.55s
Bind time:       1.07s
Check time:     19.84s
Emit time:       0.00s
Total time:     22.46s
```

**Comment by vladima** [comment]
duplicate of #https://github.com/dotnet/roslyn/issues/6802?

**Comment by mhegazy** [comment]
@heejaechang do you know which VS release includes the fix for https://github.com/dotnet/roslyn/issues/6802?

**Comment by falsandtru** [comment]
@vladima Sorry, I don't know that well. I feel this is related to #10431 or #9052.

**Comment by heejaechang** [comment]
@mhegazy I can't remember exactly which micro-update but latest dev14 microupdate should have it. do you need exactly which microupdate has it?

**Comment by mhegazy** [comment]
@falsandtru can you try again with the latest Update 3: https://msdn.microsoft.com/en-us/library/mt752379.aspx

**Comment by falsandtru** [comment]
@mhegazy I tried now, but VS crashed again after update. And I'm already using latest VS before update.

Microsoft Visual Studio Community 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01038

**Comment by heejaechang** [comment]
@mhegazy you probably need to get dump from users when OOM happened and see what objects are consuming most of memory. @dotnet/roslyn-perf

**Comment by falsandtru** [comment]
I found the main process of repro.

0. clone https://github.com/falsandtru/spica
0. open the project using VS by double click `spica.csproj`
0. open `src/lib/monad/sequence/core.ts` by double click from the solution explorer
0. wait colorization
0. increase memory usage
0. open `src/lib/monad/sequence.ts` by double click from the solution explorer
0. change code `compose(...)` to `export class C<a, z> extends compose(...)<a, z> {}`
0. increase memory usage
0. undo changes by `Ctrl+z`
0. increase memory usage
0. redo changes by `Ctrl+Shift+z`
0. increase memory usage
0. repeat these steps
0. VS uses too much memory over 3GB

Can you repro?

**Comment by falsandtru** [comment]
@mhegazy @DanielRosenwasser can you confirm this bug?

**Comment by falsandtru** [comment]
Seems like this bug is fixed.
