### ISSUE TITLE
`gulp runtests --test ge` fails

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#10683]
This also happens with `runtests-browser`, so I was able to get a sample error:

The first failing test is `tests/cases/fourslash/shims/getEmitOutput.ts`.
Error: `The baseline file getEmitOutput.baseline has changed.`

expected:

```
EmitSkipped: false
FileName : tests/cases/fourslash/shims/inputFile1.js
var x = 5;
var Bar = (function () {
    function Bar() {
    }
    return Bar;
}());
FileName : tests/cases/fourslash/shims/inputFile1.d.ts
declare var x: number;
declare class Bar {
    x: string;
    y: number;
}

EmitSkipped: false
FileName : tests/cases/fourslash/shims/inputFile2.js
var x1 = "hello world";
var Foo = (function () {
    function Foo() {
    }
    return Foo;
}());
FileName : tests/cases/fourslash/shims/inputFile2.d.ts
declare var x1: string;
declare class Foo {
    x: string;
    y: number;
}
```

Actual:

```
EmitSkipped: false
FileName : tests/cases/fourslash/inputFile1.js
var x = 5;
var Bar = (function () {
    function Bar() {
    }
    return Bar;
}());
FileName : tests/cases/fourslash/inputFile1.d.ts
declare var x: number;
declare class Bar {
    x: string;
    y: number;
}

EmitSkipped: false
FileName : tests/cases/fourslash/inputFile2.js
var x1 = "hello world";
var Foo = (function () {
    function Foo() {
    }
    return Foo;
}());
FileName : tests/cases/fourslash/inputFile2.d.ts
declare var x1: string;
declare class Foo {
    x: string;
    y: number;
}
```

Apparently the "shims" directory is disappearing from the output when we run the tests in this order.

**Comment by andy-ms** [comment]
We also get test errors from running `gulp runtests --test Resolution`. Such as:
```
  618) Projects tests Compiling project for Visibility of type used across modules - 2: testcase tests/cases/project/visibilityOfTypeUsedAcrossModules2.json Resolution information of (amd): tests/cases/project/visibilityOfTypeUsedAcrossModules2.json:
     TypeError: Cannot read property 'moduleKind' of undefined
      at Context.<anonymous> (projectsRunner.ts:469:86)
```

**Comment by andy-ms** [comment]
`gulp runtests --t format` also results in a lot of errors.
```
...
  632) Projects tests Compiling project for Visibility of type used across modules - 2: testcase tests/cases/project/visibilityOfTypeUsedAcrossModules2.json Resolution information of (amd): tests/cases/project/visibilityOfTypeUsedAcrossModules2.json:
     TypeError: Cannot read property 'moduleKind' of undefined
      at Context.<anonymous> (src/harness/projectsRunner.ts:468:86)
```

**Comment by andy-ms** [comment]
@RyanCavanaugh There's a recent example of this -- running `jake runtests t=ode` fails in a `tsbuild` test which is apparently stateful.

**Comment by weswigham** [comment]
None of the given examples cause failures anymore ❤️
