### ISSUE TITLE
Nightly error

### ISSUE THREAD

**Issue by jods4** [Microsoft/TypeScript#10778]
After @mhegazy's [comment](https://github.com/Microsoft/TypeScript/issues/1664#issuecomment-245340547) I wanted to give the new codegen a try and downloaded `2.1.0-dev.20160907` (I am currently using Babel js).

The result on my codebase is a compiler crash:
```
TypeError: Cannot read property 'text' of undefined
    at addExportMemberAssignmentsForBindingName (D:\****\node_modules\typescript\lib\typescript.js:45135:95)
    at addExportMemberAssignmentsForBindingName (D:\****\node_modules\typescript\lib\typescript.js:45131:21)
    at visitVariableStatement (D:\****\node_modules\typescript\lib\typescript.js:45119:17)
    at visitor (D:\****\node_modules\typescript\lib\typescript.js:44882:28)
    at Object.visitNodes (D:\****\node_modules\typescript\lib\typescript.js:40012:48)
    at transformAsynchronousModuleBody (D:\****\node_modules\typescript\lib\typescript.js:44836:40)
    at transformAsynchronousModule (D:\****\node_modules\typescript\lib\typescript.js:44822:41)
    at transformAMDModule (D:\****\node_modules\typescript\lib\typescript.js:44757:20)
    at transformSourceFile (D:\****\node_modules\typescript\lib\typescript.js:44719:31)
    at D:\****\node_modules\typescript\lib\typescript.js:51196:89
```

I am sorry but I can't put up a repro our codebase is large and confidential :(

**Comment by rbuckton** [comment]
I found a simple repro. This issue occurs when you have a top level variable declaration with an array binding pattern that has a missing element and also have export specifiers in the same file:

```ts
const [a, , b] = [1, 2, 3];
export { a, b };
```

We parse the missing element as an `OmittedExpression` but incorrectly cast it to a `BindingElement` which always expects to have a valid `name` property.

I have a fix I will be pushing up shortly, and should be available in the next nightly build.

**Comment by jods4** [comment]
@rbuckton We definitely have this pattern somehwere in our code. I know because it was introduced very recently, like during the past week ;) So I guess that's it!

**Comment by DanielRosenwasser** [comment]
@rbuckton sent out a fix. Keep an eye out for the next nightly (~2-3 hours).

**Comment by jods4** [comment]
@rbuckton @DanielRosenwasser Will test again with our codebase on Monday.

**Comment by jods4** [comment]
Tested today with `dev.20160912`, the compiler crash is gone. Thanks.
