### ISSUE TITLE
Unable to compile with gulp on windows

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#10823]
```
$ gulp local
[03:58:44] Requiring external module ts-node/register

.\node_modules\ts-node\src\index.ts:255
          throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript
Gulpfile.ts (42,7): Property 'stackTraceLimit' does not exist on type 'ErrorConstructor'. (2339)
    at getOutput (.\node_modules\ts-node\src\index.ts:255:17)
    at .\node_modules\ts-node\src\index.ts:264:16
    at Object.compile (.\node_modules\ts-node\src\index.ts:425:17)
    at loader (.\node_modules\ts-node\src\index.ts:286:33)
    at Object.require.extensions.(anonymous function) [as .ts] (.\node_modules\ts-node\src\index.ts:303:14)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

**Comment by mhegazy** [comment]
i am not seeing this locally after nuking my repo and doing npm install.

**Comment by falsandtru** [comment]
The compilation is succeeded after running `rm -rf node_modules/` and `npm i` (i already updated dependencies by `npm i` before compiling). Seems like something was wrong in dependencies. Thanks.

**Comment by falsandtru** [comment]
As a note, some version of dependencies probably needs to update for force updating of old dependencies.
