### ISSUE TITLE
Code format fails in VSCode, TypeScript server fails

### ISSUE THREAD

**Issue by oshalygin** [Microsoft/TypeScript#10948]
Code formatting stopped working in VSCode lately and it looks like its related to the TSServer.  Wish I knew the root cause but right now I'm at a loss.  I turned on verbose tracing in the settings and I'm seeing the following failure.  

I want to say this starts happening after I open up a `.jsx` file and try to format it, after that I can't format anything else. 

**TypeScript Version:**  1.8.0

**Code**

```
[Trace - 4:13:55 AM] Sending request: format (91). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "c:/dev/Dashboard/client/reducers/initialState.js",
    "line": 1,
    "offset": 1,
    "endLine": 13,
    "endOffset": 3
}
[Trace - 4:13:55 AM] Response received: format (91). Request took 1 ms. Success: false . Message: Error processing request. Debug Failure. False expression: 
[Error - 4:13:55 AM] 'format' request failed with error.
Error processing request. Debug Failure. False expression: 
```

**Expected behavior:**
Ability to format code
**Actual behavior:** 
No dice

**Comment by mhegazy** [comment]
do you see the same behavior on later TS builds<sup>*</sup>? 

<sup>*</sup> See https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions for how to use TS 2.0 in VSCode

**Comment by mhegazy** [comment]
Also it would be great if you can share the content of one of the files where this happens on. we just need the file where it fails and not the whole project.

**Comment by oshalygin** [comment]
disaster strikes in this file:

```jsx

import React, { PropTypes } from "react";

const LoginForm = ({onChange, login}) => {
    return (
                    <form className="m-t">
                        <div className="form-group">
                            <input
                                type = "email"
                                name = "email"
                                className = "form-control"
                                placeholder = "Username"
                                onChange = {onChange}
                                required />
                        </div>
                    <div className="form-group">
                            <input
                                type = "password"
                                name = "password"
                                className = "form-control"
                                placeholder = "Password"
                                onChange = {onChange}
                                required />
                        </div>
                        <button
                            type = "submit"
                            className = "btn btn-primary block full-width m-b"
                            onClick = {login}
                            onSubmit = {login}>Login</button>

                        <a href="#"><small>Forgot password?</small></a>
                        <p className="text-muted text-center"><small>Don't have an account?</small></p>
                        <a className="btn btn-sm btn-white btn-block" href="#">Create an account</a>
                    </form>
    );
};

LoginForm.propTypes = {
    onChange: PropTypes.func.isRequired,
    login: PropTypes.func.isRequired
};

export default LoginForm;
````

so after trying to perform a code format in the above file, it'll require a hard reset of VSCode to reset the TSServer.

I'll try that suggestion for TypeScript 2.0 and report back

**Comment by oshalygin** [comment]
Installed TypeScript 2.0.0 globally(doesn't make sense for local installs) via `npm install typescript@2.0.0 -g`.

Then went to the settings.json and added the following entry:
`"typescript.tsdk": "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib",`

bottom right corner: **2.0.0**

Same result:
```
[Error - 10:30:15 PM] 'format' request failed with error.
Error processing request. Debug Failure. False expression: 
Error: Debug Failure. False expression: 
    at Object.assert (C:\Users\Admin\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:1120:23)
    at Object.getFormattingScanner (C:\Users\Admin\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:41471:22)
    at formatSpan (C:\Users\Admin\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:42810:48)
    at Object.formatSelection (C:\Users\Admin\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:42685:20)
    at Object.getFormattingEditsForRange (C:\Users\Admin\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:48979:34)
    at IOSession.Session.getFormattingEditsForRange (C:\Users\Admin\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:50386:61)
    at Session.handlers._a.(anonymous function) (C:\Users\Admin\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:49860:50)
    at IOSession.Session.executeCommand (C:\Users\Admin\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:50732:28)
    at IOSession.Session.onMessage (C:\Users\Admin\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:50749:35)
    at Interface.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:52928:27)
```

**Comment by mhegazy** [comment]
The file above works fine for me. can you give `typescript@next` a try?

**Comment by oshalygin** [comment]
@mhegazy let me give that a whirl, thanks!

**Comment by mhegazy** [comment]
> Any thoughts on what was going on, possibly package installation issue?

No. without debugging through it it i hard to tell what is going on. possibly an issue that was fixed.

**Comment by mhegazy** [comment]
closing for now. please reopen if you run into other issues.
