### ISSUE TITLE
export default after missing closing curly brace throws an error in typescript compiler

### ISSUE THREAD

**Issue by G0A** [Microsoft/TypeScript#11059]
**TypeScript Version:**  1.8.10 / Version 2.1.0-dev.20160922

**Code**

```ts
const foo = () => {
    if (0) {
        return;

};

const bar = 'bar';

export default bar;

```

**Expected behavior:**

tserror.ts(10,20): error TS1005: '}' expected.

**Actual behavior:** 

tserror.ts(10,20): error TS1005: '}' expected.
c:\npm-global\node_modules\typescript\lib\tsc.js:33078
                throw e;
                ^

TypeError: Cannot read property 'export=' of undefined
    at checkExternalModuleExports (c:\npm-global\node_modules\typescript\lib\tsc.js:22882:62)
    at checkExportAssignment (c:\npm-global\node_modules\typescript\lib\tsc.js:22860:13)
    at checkSourceElement (c:\npm-global\node_modules\typescript\lib\tsc.js:23022:28)
    at Object.forEach (c:\npm-global\node_modules\typescript\lib\tsc.js:98:30)
    at checkBlock (c:\npm-global\node_modules\typescript\lib\tsc.js:21370:16)
    at checkSourceElement (c:\npm-global\node_modules\typescript\lib\tsc.js:22969:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (c:\npm-global\node_modules\typescript\lib\tsc.js:19787:21)
    at checkDeferredNodes (c:\npm-global\node_modules\typescript\lib\tsc.js:23046:25)
    at checkSourceFileWorker (c:\npm-global\node_modules\typescript\lib\tsc.js:23075:17)
    at checkSourceFile (c:\npm-global\node_modules\typescript\lib\tsc.js:23060:13)

**Comment by sheetalkamat** [comment]
This doesn't repro on TypeScript@next or release-2.0.5 branch
