### ISSUE TITLE
TypeError: Cannot read property 'export=' of undefined from ./node_modules\typescript\lib\tsc.js

### ISSUE THREAD

**Issue by georgeedwards** [Microsoft/TypeScript#11211]
**TypeScript Version:**  2.0.3

**Code**

When building any project I have started getting th following warning on my windows machine:
```
C:\Users\George\Source\Repos\docs\node_modules\typescript\lib\tsc.js:37701
[0]                 throw e;
[0]                 ^
[0]
[0] TypeError: Cannot read property 'export=' of undefined
[0]     at checkExternalModuleExports (C:\Users\George\Source\Repos\docs\node_modules\typescript\lib\tsc.js:26496:62)
[0]     at checkExportAssignment (C:\Users\George\Source\Repos\docs\node_modules\typescript\lib\tsc.js:26474:13)
[0]     at checkSourceElement (C:\Users\George\Source\Repos\docs\node_modules\typescript\lib\tsc.js:26642:28)
[0]     at Object.forEach (C:\Users\George\Source\Repos\docs\node_modules\typescript\lib\tsc.js:185:30)
[0]     at checkBlock (C:\Users\George\Source\Repos\docs\node_modules\typescript\lib\tsc.js:24881:16)
[0]     at checkSourceElement (C:\Users\George\Source\Repos\docs\node_modules\typescript\lib\tsc.js:26589:28)
[0]     at checkFunctionExpressionOrObjectLiteralMethodDeferred (C:\Users\George\Source\Repos\docs\node_modules\typescript\lib\tsc.js:22975:21)
[0]     at checkDeferredNodes (C:\Users\George\Source\Repos\docs\node_modules\typescript\lib\tsc.js:26666:25)
[0]     at checkSourceFileWorker (C:\Users\George\Source\Repos\docs\node_modules\typescript\lib\tsc.js:26695:17)
[0]     at checkSourceFile (C:\Users\George\Source\Repos\docs\node_modules\typescript\lib\tsc.js:26680:13)
[0] tsc -w -p ./server exited with code 1
```
This doesn't seem to have anything to do with my project? Or if it does, the error message isn't helpful. 

**Expected behavior:**
Clean compile, without throwing this error. 

This seems to have occurred since I upgraded to node v6.7.0 however, on downgrade the problem remains. To replicate you can clone [this](https://github.com/georgeedwards/docs/tree/0615dc4c97db4cfc2f7516cc0afe51d23cee166c) repo. and then run `npm i`

**Comment by mhegazy** [comment]
@andy-ms can you take a look at this one? we should take this for 2.0.5

**Comment by georgeedwards** [comment]
Thanks - would be great to sort. If you just ignore it, it doesn't actually seem to matter locally (compile completes file and with `-w` set, subsequent recompiles aren't affected) , but this is killing my Heroku builds.

**Comment by andy-ms** [comment]
FYI, [`server/routes/plugins.ts`](https://github.com/georgeedwards/docs/blob/0615dc4c97db4cfc2f7516cc0afe51d23cee166c/server/routes/plugins.ts) is missing `}` at the end of `router.post('/', function (req, res, next) {`.

**Comment by georgeedwards** [comment]
@andy-ms Thanks!

**Comment by andy-ms** [comment]
@georgeedwards If you're really curious you could see the pull request linked above. We were accidentally skipping past the error and trying to fetch the exports of a non-module entity (assuming that the parent of an `export =` statement would be a module). Testing for all the possible malformed programs is hard!
