### ISSUE TITLE
Language Server fails in VS Code on QuickInfo Query 

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#11282]
**TypeScript Version:**  master branch -- commit 631ab0abab
** OS Version**: Ubuntu 16.04

1) Install vscode, either stable or development (master branch -- commit c96822698c )
2) build tsserver (jake local)
3) Set vscode to use built tsserver.js
4) Open a blank .ts file, write a function, eg,

```
function foo() {}
```

5) mouse over function, request quickinfo.
6) observe error.

**Expected behavior:**

Get quickinfo.

**Actual behavior:** 

Error.

----------------------------------
Log from output window in vscode:

[Info  - 10:13:39 AM] Using tsserver from location: /home/arthur/TypeScript/built/local/tsserver.js
[Info  - 10:13:39 AM] TSServer started in debug mode using port 5859
[Error - 10:13:42 AM] 'quickinfo' request failed with error.
Error processing request. Cannot read property 'path' of undefined
TypeError: Cannot read property 'path' of undefined
    at ModuleBuilder.ensureProjectDependencyGraphUpToDate (/home/arthur/TypeScript/built/local/tsserver.js:75699:75)
    at ModuleBuilder.onProjectUpdateGraph (/home/arthur/TypeScript/built/local/tsserver.js:75691:22)
    at ConfiguredProject.Project.updateGraphWorker (/home/arthur/TypeScript/built/local/tsserver.js:76109:30)
    at ConfiguredProject.Project.updateGraph (/home/arthur/TypeScript/built/local/tsserver.js:76068:39)
    at ConfiguredProject.Project.getLanguageService (/home/arthur/TypeScript/built/local/tsserver.js:75897:26)
    at IOSession.Session.getQuickInfoWorker (/home/arthur/TypeScript/built/local/tsserver.js:78531:41)
    at Session.handlers.ts.createMap._a.(anonymous function) (/home/arthur/TypeScript/built/local/tsserver.js:77825:61)
    at IOSession.Session.executeCommand (/home/arthur/TypeScript/built/local/tsserver.js:78957:28)
    at IOSession.Session.onMessage (/home/arthur/TypeScript/built/local/tsserver.js:78977:35)
    at Interface.<anonymous> (/home/arthur/TypeScript/built/local/tsserver.js:80073:27)

**Comment by aozgaa** [comment]
Could not reproduce following the same steps on Win10.

**Comment by vladima** [comment]
can repro this on Ubuntu
