### ISSUE TITLE
Using Rewire with TypeScript

### ISSUE THREAD

**Issue by oargaruna** [Microsoft/TypeScript#11525]
I am working on a React-Native project using TypeScript. To write my unit tests I would like to use the [babel-plugin-rewire](https://github.com/speedskater/babel-plugin-rewire) to mock my module imports. However, TypeScript adds a `_1` suffix at the end of imports while converting from ES6 to ES5, and this breaks my test code.

Consider the following:

```
import Test from 'test-file';
```

this might be converted by TypeScript to:

```
var test_file_1 = require('test-file');
```

To mock the Test class using the Rewire plugin I would have to write:

```
ComponentToTest.__Rewire__('Test', TestMock);
```

but since the import has been renamed this will break.

Though this is [by design](https://github.com/Microsoft/TypeScript/issues/6264), I would love to know if there are any workarounds.

Thanks.

**Comment by mhegazy** [comment]
If you are using babel to transform the code, then use `--target ES6` and not ES5. this way you have full control on how the code is transformed.

**Comment by oargaruna** [comment]
I did try that. But somehow TypeScript is not able to resolve my module dependencies.

**Comment by aluanhaddad** [comment]
@oargaruna looks like you are using `"module": "commonjs"`, so specify `"allowSyntheticDefaultImports": true`, to resolve compile time type errors.

**Comment by oargaruna** [comment]
I'm still getting the same errors. Below is my tsconfig.json:

```
{
    "compilerOptions": {
        "jsx": "react",
        "target": "es6",
        "allowSyntheticDefaultImports": true,
        "watch": false,
        "outDir": "ui/js/",        
        "allowJs": true,
        "sourceMap": true
    },
    "include": [
        "ui/ts/**/*"
    ]
}
```

**Comment by aluanhaddad** [comment]
You are getting TypeScript errors you say? What are they?

**Comment by oargaruna** [comment]
Below are the errors after running tsc:

```
node_modules/@types/react-native/index.d.ts(19,24): error TS2307: Cannot find module 'react'.
node_modules/@types/react-native/index.d.ts(222,28): error TS2304: Cannot find name 'Component'.
node_modules/@types/react-native/index.d.ts(1017,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(1405,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(1600,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(1679,16): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(1825,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(1867,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(1923,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(2026,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(2082,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(2093,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(2125,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(2197,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(2240,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(2262,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(2293,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(2308,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(2353,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(2480,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(2810,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(2975,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(3758,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(3791,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(4275,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(4279,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(5367,15): error TS2304: Cannot find name 'Ref'.
node_modules/@types/react-native/index.d.ts(5394,15): error TS2304: Cannot find name 'Ref'.
ui/ts/source/cards/BaseCard.tsx(5,24): error TS2307: Cannot find module 'react'.
ui/ts/source/cards/BaseCard.tsx(12,8): error TS2307: Cannot find module 'react-native'.
ui/ts/source/cards/BaseCard.tsx(42,26): error TS2339: Property 'props' does not exist on type 'BaseCard<P, S>'.
ui/ts/source/cards/BaseCard.tsx(43,26): error TS2339: Property 'props' does not exist on type 'BaseCard<P, S>'.
ui/ts/source/cards/BaseCard.tsx(51,30): error TS2339: Property 'props' does not exist on type 'BaseCard<P, S>'.
ui/ts/source/cards/BaseCard.tsx(54,32): error TS2339: Property 'props' does not exist on type 'BaseCard<P, S>'.
ui/ts/source/cards/BaseCard.tsx(65,32): error TS2339: Property 'props' does not exist on type 'BaseCard<P, S>'.
ui/ts/source/cards/BaseCard.tsx(69,32): error TS2339: Property 'props' does not exist on type 'BaseCard<P, S>'.
ui/ts/source/cards/TextMessageCard.tsx(5,24): error TS2307: Cannot find module 'react'.
ui/ts/source/cards/TextMessageCard.tsx(9,8): error TS2307: Cannot find module 'react-native'.
ui/ts/source/cards/TextMessageCard.tsx(26,24): error TS2339: Property 'props' does not exist on type 'TextMessageCard'.
ui/ts/source/components/InvertedVerticalListView.tsx(11,24): error TS2307: Cannot find module 'react'.
ui/ts/source/components/InvertedVerticalListView.tsx(17,8): error TS2307: Cannot find module 'react-native'.
ui/ts/source/components/InvertedVerticalListView.tsx(30,26): error TS2339: Property 'props' does not exist on type 'InvertedVerticalListView'.
ui/ts/source/components/InvertedVerticalListView.tsx(32,32): error TS2339: Property 'props' does not exist on type 'InvertedVerticalListView'.
ui/ts/source/components/InvertedVerticalListView.tsx(40,18): error TS2339: Property 'props' does not exist on type 'InvertedVerticalListView'.
ui/ts/source/components/InvertedVerticalListView.tsx(44,28): error TS2339: Property 'props' does not exist on type 'InvertedVerticalListView'.
ui/ts/source/components/RepeatingImageBackground.tsx(6,24): error TS2307: Cannot find module 'react'.
ui/ts/source/components/RepeatingImageBackground.tsx(13,8): error TS2307: Cannot find module 'react-native'.
ui/ts/source/components/RepeatingImageBackground.tsx(14,36): error TS2307: Cannot find module 'resolveAssetSource'.
ui/ts/source/components/RepeatingImageBackground.tsx(41,19): error TS2339: Property 'props' does not exist on type 'RepeatingImageBackground'.
ui/ts/source/components/RepeatingImageBackground.tsx(46,53): error TS2339: Property 'props' does not exist on type 'RepeatingImageBackground'.
ui/ts/source/components/RepeatingImageBackground.tsx(48,40): error TS2339: Property 'props' does not exist on type 'RepeatingImageBackground'.
ui/ts/source/components/RepeatingImageBackground.tsx(48,67): error TS2339: Property 'props' does not exist on type 'RepeatingImageBackground'.
ui/ts/source/components/RepeatingImageBackground.tsx(49,39): error TS2339: Property 'props' does not exist on type 'RepeatingImageBackground'.
ui/ts/source/components/RepeatingImageBackground.tsx(49,65): error TS2339: Property 'props' does not exist on type 'RepeatingImageBackground'.
ui/ts/source/components/RepeatingImageBackground.tsx(70,39): error TS2339: Property 'props' does not exist on type 'RepeatingImageBackground'.
ui/ts/source/components/RepeatingImageBackground.tsx(97,28): error TS2339: Property 'props' does not exist on type 'RepeatingImageBackground'.
ui/ts/source/models/TextMessageModel.tsx(5,24): error TS2307: Cannot find module 'react'.
ui/ts/source/models/TextMessageModel.tsx(22,13): error TS2605: JSX element type 'TextMessageCard' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'TextMessageCard'.
ui/ts/source/models/TextMessageModel.tsx(22,13): error TS2607: JSX element class does not support attributes because it does not have a 'props' property
ui/ts/source/styles/cards/BaseCardStyles.ts(4,8): error TS2307: Cannot find module 'react-native'.
ui/ts/source/styles/components/InvertedVerticalListViewStyles.ts(4,8): error TS2307: Cannot find module 'react-native'.
ui/ts/source/styles/components/RepeatingImageBackgroundStyles.ts(4,8): error TS2307: Cannot find module 'react-native'.
ui/ts/source/styles/views/ChatViewStyles.ts(4,8): error TS2307: Cannot find module 'react-native'.
ui/ts/source/utils/ScreenUtils.ts(7,8): error TS2307: Cannot find module 'react-native'.
ui/ts/source/utils/TimestampUtils.ts(5,25): error TS2307: Cannot find module 'moment'.
ui/ts/source/views/BaseView.tsx(6,24): error TS2307: Cannot find module 'react'.
ui/ts/source/views/BaseView.tsx(10,34): error TS2307: Cannot find module 'react-native'.
ui/ts/source/views/ChatView.tsx(8,24): error TS2307: Cannot find module 'react'.
ui/ts/source/views/ChatView.tsx(21,8): error TS2307: Cannot find module 'react-native'.
ui/ts/source/views/ChatView.tsx(22,28): error TS2307: Cannot find module 'react-native-keyboard-spacer'.
ui/ts/source/views/ChatView.tsx(77,14): error TS2339: Property 'state' does not exist on type 'ChatView'.
ui/ts/source/views/ChatView.tsx(94,13): error TS2605: JSX element type 'RepeatingImageBackground' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'RepeatingImageBackground'.
ui/ts/source/views/ChatView.tsx(94,13): error TS2607: JSX element class does not support attributes because it does not have a 'props' property
ui/ts/source/views/ChatView.tsx(96,17): error TS2605: JSX element type 'InvertedVerticalListView' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'InvertedVerticalListView'.
ui/ts/source/views/ChatView.tsx(96,17): error TS2607: JSX element class does not support attributes because it does not have a 'props' property
ui/ts/source/views/ChatView.tsx(98,39): error TS2339: Property 'state' does not exist on type 'ChatView'.
ui/ts/source/views/ChatView.tsx(114,46): error TS2339: Property 'state' does not exist on type 'ChatView'.
ui/ts/source/views/ChatView.tsx(149,14): error TS2339: Property 'setState' does not exist on type 'ChatView'.
ui/ts/source/views/ChatView.tsx(164,14): error TS2339: Property 'setState' does not exist on type 'ChatView'.
ui/ts/source/views/ChatView.tsx(182,14): error TS2339: Property 'setState' does not exist on type 'ChatView'.
ui/ts/source/views/ChatView.tsx(188,18): error TS2339: Property 'state' does not exist on type 'ChatView'.
ui/ts/source/views/ChatView.tsx(189,36): error TS2339: Property 'state' does not exist on type 'ChatView'.
ui/ts/source/views/ChatView.tsx(191,43): error TS2339: Property 'state' does not exist on type 'ChatView'.
ui/ts/source/views/ChatView.tsx(193,22): error TS2339: Property 'setState' does not exist on type 'ChatView'.
```

**Comment by aluanhaddad** [comment]
What version of TypeScript are you running? 
Have you set `tsconfig.compilerOptions.module`? 
Have you set `"moduleResolution": "node"`?
Can you provide a repo?

**Comment by oargaruna** [comment]
Shouldn't `module` be equal to `es6` by default if the `target` is `es6`? That's what I got from the tsconfig documentation.

**Comment by aluanhaddad** [comment]
I believe the default is "commonjs"

**Comment by oargaruna** [comment]
From the [tsconfig](http://www.typescriptlang.org/docs/handbook/compiler-options.html) documentation:

Option|Type|Default
-------|----|------
--module|string|target === 'ES6' ? 'ES6' : 'commonjs'

**Comment by oargaruna** [comment]
I'll setup a repo and share the link in some time.

**Comment by cescoferraro** [comment]
`yarn add @types/react`

**Comment by petrgazarov** [comment]
Hi, I have the same problem but a different error message.

I'm using a mocha test setup with `babel-plugin-rewire` and `ts-node` as my typescript compiler.

My test command looks like this:

```
"test": "./node_modules/mocha/bin/mocha --require ts-node/register --require babel-register ./test/index.test.js"
```

From what I understand, if I get typescript compiler to emit es6, then rewire could work because then babel would fully controls the transpilation.

So, I try with these settings:
```
"module": "ES6",
"target": "ES6",
```

The error message:
```
export { something };
^^^^^^
SyntaxError: Unexpected token export
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Module.m._compile (/Users/petrgazarov/workspace/typescript-rewire-babel-plugin-example/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/petrgazarov/workspace/typescript-rewire-babel-plugin-example/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/petrgazarov/workspace/typescript-rewire-babel-plugin-example/test/index.test.js:1:1)
    at Module._compile (module.js:541:32)
error Command failed with exit code 1.
```

I've setup a repo to reproduce the issue, if someone has time to look at it, would be great: https://github.com/petrgazarov/typescript-rewire-babel-plugin-example

**Comment by petrgazarov** [comment]
When using `--require babel-register`, there is currently no way to specify extensions, because extensions [are not managed from .babelrc file](https://github.com/babel/babel/issues/3741).

See https://github.com/TypeStrong/ts-node/issues/387#issuecomment-315576724

**Comment by filipsuk** [comment]
Hey guys, I'm trying to use rewire with TypeScript for testing internal functions of modules with jest.

@oargaruna @petrgazarov have you managed to get it working? Thanks

**Comment by petrgazarov** [comment]
Hey @filipsuk, sorry I haven't combined jest and rewire. Did you look into using jest [built-in mock functions](https://facebook.github.io/jest/docs/en/manual-mocks.html)?

**Comment by filipsuk** [comment]
@petrgazarov I want to test module functions which are not exported. As far as I know, jest does not support that :/
