### ISSUE TITLE
tsc.transpileModule throws "Cannot read property 'resolvedModule' of undefined" when using imports

### ISSUE THREAD

**Issue by avanderhoorn** [Microsoft/TypeScript#11662]
**TypeScript Version:**  1.8.10

**Code**

```ts
// index.js
var tsc = require('typescript');

// DOESN'T work
var src = "import _ from 'lodash'; console.log('Hello World');";

// DOESN'T work
//var src = "import * as _ from 'lodash'; console.log('Hello World');";

// DOES work
//var src = "var _ = require('lodash'); console.log('Hello World');";

var result = tsc.transpileModule(
    src,
    {
        "compilerOptions": {
            "module": "es6",
            "target": "es6",
            "moduleResolution": "node",
            "allowSyntheticDefaultImports": true,
            "jsx": "preserve",
            "sourceMap": true,
            "outDir": "./dist/"
        }
    }
);

console.log(result);
```

**Expected behavior:**
I expect that the `import`s described above would be "parsed" correctly. It seems to be able to handle `require`s of modules but not imports. 

**Actual behavior:** 
Throws "Cannot read property 'resolvedModule' of undefined" exception:
```
➜  TypeScript.TranspileModule: node index.js
/Users/avanderhoorn/Projects/_repro/TypeScript.TranspileModule/node_modules/typescript/lib/typescript.js:39678
                        resolvedName = resolveModuleName(moduleName, containingFile, options, host).resolvedModule;
                                                                                                   ^

TypeError: Cannot read property 'resolvedModule' of undefined
    at resolveModuleNamesWorker (/Users/avanderhoorn/Projects/_repro/TypeScript.TranspileModule/node_modules/typescript/lib/typescript.js:39678:100)
    at processImportedModules (/Users/avanderhoorn/Projects/_repro/TypeScript.TranspileModule/node_modules/typescript/lib/typescript.js:40376:35)
    at findSourceFile (/Users/avanderhoorn/Projects/_repro/TypeScript.TranspileModule/node_modules/typescript/lib/typescript.js:40352:17)
    at processSourceFile (/Users/avanderhoorn/Projects/_repro/TypeScript.TranspileModule/node_modules/typescript/lib/typescript.js:40251:27)
    at processRootFile (/Users/avanderhoorn/Projects/_repro/TypeScript.TranspileModule/node_modules/typescript/lib/typescript.js:40161:13)
    at /Users/avanderhoorn/Projects/_repro/TypeScript.TranspileModule/node_modules/typescript/lib/typescript.js:39704:60
    at Object.forEach (/Users/avanderhoorn/Projects/_repro/TypeScript.TranspileModule/node_modules/typescript/lib/typescript.js:956:30)
    at Object.createProgram (/Users/avanderhoorn/Projects/_repro/TypeScript.TranspileModule/node_modules/typescript/lib/typescript.js:39704:16)
    at Object.transpileModule (/Users/avanderhoorn/Projects/_repro/TypeScript.TranspileModule/node_modules/typescript/lib/typescript.js:48169:26)
    at Object.<anonymous> (/Users/avanderhoorn/Projects/_repro/TypeScript.TranspileModule/index.js:12:18)
```

// @DanielRosenwasser, @mhegazy

**Comment by vladima** [comment]
I can repro it in 1.8 and it seems to be fixed in 2.0 and master. Can you give a try to `typescript@2.0` or `typescript@next` on npm?

**Comment by avanderhoorn** [comment]
Happy to give it a go but we have a large code base and switching isn't
really possible at this point. Any chance that if this is a bug it can be
fixed in 1.8.11?

**Comment by vladima** [comment]
TS 1.8 did not support passing compiler options as strings, this was added only in 2.0. For 1.8 you should fix your code to use enums when specifying compiler options:

```js
// index.js
var tsc = require('typescript');

// DOESN'T work
var src = "import _ from 'lodash'; console.log('Hello World');";


var result = tsc.transpileModule(
    src,
    {
        "compilerOptions": {
            "module": tsc.ModuleKind.ES6,
            "target": tsc.ScriptTarget.ES6,
            "moduleResolution": tsc.ModuleResolutionKind.Node,
            "allowSyntheticDefaultImports": true,
            "jsx": tsc.JsxEmit.Preserve,
            "sourceMap": true,
            "outDir": "./dist/"
        }
    }
);

console.log(result);

```

**Comment by mhegazy** [comment]
Supporting strings in options to transpileModule/transpile has been reported in https://github.com/Microsoft/TypeScript/issues/7980 and fixed in https://github.com/Microsoft/TypeScript/pull/8988 in TypeScript 2.0. 

also worth noting that calling the TS compiler on the call for transpileModule should have flagged options passed as errors.

**Comment by avanderhoorn** [comment]
Thanks for spotting that! I was using the same setting from `ts-loader` and didn't notice the difference when running `tsc` directly.
