### ISSUE TITLE
Error: Debug Failure. False expression: Cannot serialize unexpected type node.

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/TypeScript#11789]
Experientially adding `"emitDecoratorMetadata": true,` to my current's project's tsconfig resulted in `tsc` generating an exception (shown below).   Nothing in the message provides any help isolating what source-code triggers it, the project has nearly 31 kloc:

**TypeScript Version:**  2.0.3 

**Code**
Sorry, I haven't yet isolated the code that triggers this.   If the cause isn't known to the devs based on the message and stack trace, I'll put in some more effort to do so.

**Expected behavior:**
More detail in message to help me understand why this is happening...

**Actual behavior:** 
```
C:\code\antlr4ts\test\tool>tsc
C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:37701
                throw e;
                ^

Error: Debug Failure. False expression: Cannot serialize unexpected type node.
    at Object.assert (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:1289:23)
    at Object.fail (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:1294:19)
    at emitSerializedTypeNode (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:34723:38)
    at emitSerializedReturnTypeOfNode (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:34823:25)
    at emitSerializedTypeMetadata (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:34862:25)
    at emitDecoratorsOfMembers (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:34590:21)
    at emitDecoratorsOfClass (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:34513:17)
    at emitClassLikeDeclarationForES6AndHigher (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:34399:21)
    at emitClassLikeDeclaration (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:34300:21)
    at emitClassDeclaration (C:\Users\Burt_\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:34293:24)
```

**Comment by mhegazy** [comment]
do you see the same error on `typescript@next`?

**Comment by BurtHarris** [comment]
`npm i -G typescript@next` generated a message saying 

`-- typescript@2.1.0-dev.20161021  invalid`

**Comment by mhegazy** [comment]
Thanks for the confirmation. This function has been rewrote.
