### ISSUE TITLE
[2.0.6] Problem with completion "from" path 

### ISSUE THREAD

**Issue by angelozerr** [Microsoft/TypeScript#11854]
With **TypeScript Version:**  2.0.6 (same problem with 2.0.3) when I open completion for "from":

```
import {} from " // Ctrl+Space to open completion
```

I have this error:

```
TypeError: Cannot read property 'length' of undefined
    at getCompletionEntriesFromTypings (...\node_modules\typescript\lib\tsserver.js:48159:79)
    at getCompletionEntriesForNonRelativeModules (...\node_modules\typescript\lib\tsserver.js:48038:17)
    at getStringLiteralCompletionEntriesFromModuleNames (...\node_modules\typescript\lib\tsserver.js:47929:31)
    at getStringLiteralCompletionEntries (...\node_modules\typescript\lib\tsserver.js:47833:28)
    at Object.getCompletionsAtPosition (...\node_modules\typescript\lib\tsserver.js:47717:24)
    at IOSession.Session.getCompletions (...\node_modules\typescript\lib\tsserver.js:54911:64)
    at Session.handlers.ts.createMap._a.(anonymous function) (...\\node_modules\typescript\lib\tsserver.js:54156:61)
    at IOSession.Session.executeCommand (...\node_modules\typescript\lib\tsserver.js:55223:28)
    at IOSession.Session.onMessage (...\node_modules\typescript\lib\tsserver.js:55243:35)
    at Interface.<anonymous> (...\node_modules\typescript\lib\tsserver.js:56300:27)
```

With **TypeScript 2.1.0-dev.20161012**, I have not this error.

More, when I write with **TypeScript Version:**  2.0.6

```
import {} from "./ // Ctrl+Space to open completion
```

completion shows only `directory` entries and not `script` files.

With **TypeScript 2.1.0-dev.20161012**,  completion shows `directory` entries and `script` files both.

**Comment by mhegazy** [comment]
@angelozerr can you give tonight's drop a try?

**Comment by angelozerr** [comment]
@mhegazy you wish that I test with TypeScript that I install with "npm install typescript@next", is that?

**Comment by mhegazy** [comment]
Yes. That would be appreciated.

**Comment by angelozerr** [comment]
@mhegazy worls like a charm with 2.2.0-dev.20161120. Completion shows files and directories both:

![typescriptcompletionfrom](https://cloud.githubusercontent.com/assets/1932211/20463490/99d91344-af34-11e6-880d-94920408890b.png)

**Comment by mhegazy** [comment]
thanks for confirming.
