### ISSUE TITLE
TypeScript 2.0.6 breaks formatter

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/TypeScript#11852]
**TypeScript Version:**  2.0.6

The formatter no longer works in 2.0.6. It worked fine in 2.0.3.

**Code**

Put the following in `script.js` and test it with both 2.0.3 and 2.0.6. Run it with `node script.js`:

```es6
const ts = require('typescript');
const assert = require('assert');

function format(text) {
	let options = getDefaultOptions();

	// Parse the source text
	let sourceFile = ts.createSourceFile('file.ts', text, ts.ScriptTarget.Latest, /*setParentPointers*/ true);

	// Get the formatting edits on the input sources
	let edits = ts.formatting.formatDocument(sourceFile, getRuleProvider(options), options);

	// Apply the edits on the input code
	return applyEdits(text, edits);

	function getRuleProvider(options) {
		// Share this between multiple formatters using the same options.
		// This represents the bulk of the space the formatter uses.
		let ruleProvider = new ts.formatting.RulesProvider();
		ruleProvider.ensureUpToDate(options);
		return ruleProvider;
	}

	function applyEdits(text, edits) {
				// Apply edits in reverse on the existing text
				let result = text;
		for (let i = edits.length - 1; i >= 0; i--) {
			let change = edits[i];
			let head = result.slice(0, change.span.start);
			let tail = result.slice(change.span.start + change.span.length);
			result = head + change.newText + tail;
		}
		return result;
	}

	function getDefaultOptions() {
		return {
			IndentSize: 4,
			TabSize: 4,
			NewLineCharacter: '\n',
			ConvertTabsToSpaces: false,
			IndentStyle: ts.IndentStyle.Block,
			InsertSpaceAfterCommaDelimiter: true,
			InsertSpaceAfterSemicolonInForStatements: true,
			InsertSpaceBeforeAndAfterBinaryOperators: true,
			InsertSpaceAfterKeywordsInControlFlowStatements: true,
			InsertSpaceAfterFunctionKeywordForAnonymousFunctions: false,
			InsertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis: false,
			InsertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets: false,
			InsertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces: true,
			PlaceOpenBraceOnNewLineForFunctions: false,
			PlaceOpenBraceOnNewLineForControlBlocks: false,
		};
	}
}

const src = 'function foo() {\nreturn 1;\n}';
const expected = 'function foo() {\n\treturn 1;\n}';
const formatted = format(src);
assert.equal(formatted, expected);
```

**Expected behavior:**

In version 2.0.3 it returns 0 and no output.

**Actual behavior:** 

In version 2.0.6 it returns 1 with following output:

```
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: 'function foo() {\nreturn 1;\n}' == 'function foo() {\n\treturn 1;\n}'
    at Object.<anonymous> (/Users/joao/Work/vscode/bug.js:65:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

As you can see, the source is no longer formatted correctly.

**Comment by joaomoreno** [comment]
This broke VS Code's builds: Microsoft/vscode#14519

**Comment by vladima** [comment]
I would argue that this bug since `ts.formatting` is does not belong to our supported public API - we don't expose it from the `.d.ts` file so effectively code here was using undocumented internal functionality that can be changed at any poing in time. Previously we used to have two shapes of editor settings - one with camel cased properties used by tsserver and one with Pascal cased names - to be used in VS. In 2.0.6 we started to remove the latter one and now internally we always use camel cased names. In this case fix should be to changes names in format options:

```js
const ts = require('typescript');
const assert = require('assert');

function format(text) {
    let options = getDefaultOptions();

    // Parse the source text
    let sourceFile = ts.createSourceFile('file.ts', text, ts.ScriptTarget.Latest, /*setParentPointers*/ true);

    // Get the formatting edits on the input sources
    let edits = ts.formatting.formatDocument(sourceFile, getRuleProvider(options), options);

    // Apply the edits on the input code
    return applyEdits(text, edits);

    function getRuleProvider(options) {
        // Share this between multiple formatters using the same options.
        // This represents the bulk of the space the formatter uses.
        let ruleProvider = new ts.formatting.RulesProvider();
        ruleProvider.ensureUpToDate(options);
        return ruleProvider;
    }

    function applyEdits(text, edits) {
                // Apply edits in reverse on the existing text
                let result = text;
        for (let i = edits.length - 1; i >= 0; i--) {
            let change = edits[i];
            let head = result.slice(0, change.span.start);
            let tail = result.slice(change.span.start + change.span.length);
            result = head + change.newText + tail;
        }
        return result;
    }

    function getDefaultOptions() {
        return {
            indentSize: 4,
            tabSize: 4,
            newLineCharacter: '\n',
            convertTabsToSpaces: false,
            indentStyle: ts.IndentStyle.Block,
            insertSpaceAfterCommaDelimiter: true,
            insertSpaceAfterSemicolonInForStatements: true,
            insertSpaceBeforeAndAfterBinaryOperators: true,
            insertSpaceAfterKeywordsInControlFlowStatements: true,
            insertSpaceAfterFunctionKeywordForAnonymousFunctions: false,
            insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis: false,
            insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets: false,
            insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces: true,
            placeOpenBraceOnNewLineForFunctions: false,
            placeOpenBraceOnNewLineForControlBlocks: false,
        };
    }
}

const src = 'function foo() {\nreturn 1;\n}';
const expected = 'function foo() {\n\treturn 1;\n}';
const formatted = format(src);
assert.equal(formatted, expected);
```

**Comment by mhegazy** [comment]
looks like this breaks typescript-formatter as well. see https://github.com/vvakame/typescript-formatter/issues/65. We need to fix this.

**Comment by alexandrudima** [comment]
To be fair, I lifted the code snippet that does formatting of `monaco.d.ts` from https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API-(TypeScript-1.4)#pretty-printer-using-the-ls-formatter

and `ts.FormatCodeOptions` appears to be in the `.d.ts`, so perhaps a minor version bump would be suitable for this change (`2.1.x`)

**Comment by vladima** [comment]
`ts.FormatOptions` are still in `.d.ts` file but the only way it can be consumed is by being passed to `format*` function on the `LanguageService` object.
