### ISSUE TITLE
Error introduced into 10/28 @next build

### ISSUE THREAD

**Issue by ntilwalli** [Microsoft/TypeScript#11937]
Some change between `typescript@2.1.0-dev.20161027` and `typescript@2.1.0-dev.20161028` introduced this error into my build.  This issue also exists in `typescript@2.1.0-dev.20161029` 

```
/Users/ntilwalli/dev/spotlight/node_modules/typescript/lib/typescript.js:23590
            result.declarations = symbol.declarations.slice(0);
                                                     ^

TypeError: Cannot read property 'slice' of undefined
    at cloneSymbol (/Users/ntilwalli/dev/spotlight/node_modules/typescript/lib/typescript.js:23590:54)
    at mergeModuleAugmentation (/Users/ntilwalli/dev/spotlight/node_modules/typescript/lib/typescript.js:23683:90)
    at initializeTypeChecker (/Users/ntilwalli/dev/spotlight/node_modules/typescript/lib/typescript.js:41037:25)
    at Object.createTypeChecker (/Users/ntilwalli/dev/spotlight/node_modules/typescript/lib/typescript.js:23527:9)
    at getDiagnosticsProducingTypeChecker (/Users/ntilwalli/dev/spotlight/node_modules/typescript/lib/typescript.js:60181:93)
    at Object.getGlobalDiagnostics (/Users/ntilwalli/dev/spotlight/node_modules/typescript/lib/typescript.js:60490:41)
    at Tsifier.checkSemantics (/Users/ntilwalli/dev/spotlight/node_modules/tsify/lib/Tsifier.js:219:37)
    at Tsifier.compile (/Users/ntilwalli/dev/spotlight/node_modules/tsify/lib/Tsifier.js:179:34)
    at Tsifier.generateCache (/Users/ntilwalli/dev/spotlight/node_modules/tsify/lib/Tsifier.js:156:8)
    at DestroyableTransform.flush [as _flush] (/Users/ntilwalli/dev/spotlight/node_modules/tsify/index.js:73:12)
```

**Comment by aluanhaddad** [comment]
Same here it is blowing up in VS Code as soon as it tries to resolve any imports.

**Comment by vladima** [comment]
@aluanhaddad can you share a repro?

**Comment by vladima** [comment]
I've reproed it: https://github.com/vladima/repro-11937
@andy-ms it seems to be related to your change with untyped modules, can you take a look?

**Comment by aluanhaddad** [comment]
@vladima Sorry, I can't reproduce it any longer. I was running with a global install using VS Code `typescript.tsdk`. I swapped versions to 2.1.0-dev.20161027 afterwards and I no longer observe the issue on reinstallation of 20161028 or 20161029.

**Comment by mhegazy** [comment]
@ntilwalli and @aluanhaddad the fix should be in tonight's `typescript@next`. please give it a try and let us know if you are still running into issues.
