### ISSUE TITLE
JS file with JSDoc comments with `@typedef` with array `@property` fails typescript parsing

### ISSUE THREAD

**Issue by kruszczynski** [Microsoft/TypeScript#12025]
**TypeScript Version:**  2.0.3

At [codebeat](https://codebeat.co) we use TypeScript's parser to provide static code analysis. Since TS is a superset of JS we expect (perhaps wrongly) TS parser to not fail for correct JS files.

We've ran into [a file](https://github.com/nodejs/node/blob/master/tools/eslint/lib/rule-context.js) in node for which `ts.createSourceFile` fails. Its JSDoc comment has a `@typedef` with an array `@property`.

I'm not an expert of JSDoc - is it expected behavior? Is the file incorrect? Or perhaps it's an intricate bug in the parser?

Thanks for taking a look

**Code**

```javascript
//------------------------------------------------------------------------------
// Typedefs
//------------------------------------------------------------------------------

/**
 * An error message description
 * @typedef {Object} MessageDescriptor
 * ...
 * @property {Object} [data] Optional data to use to fill in placeholders in the
 *      message.
 */

function whatever() {
    // If there's no code in the file it doesn't fail
}
```

**Expected behavior:**
`ts.createSourceFile` creates an instance of `SourceFile`
**Actual behavior:** 
```
/node_modules/typescript/lib/typescript.js:8866
                if (n.parent !== parent) {
                     ^

TypeError: Cannot read property 'parent' of undefined
    at visitNode (/node_modules/typescript/lib/typescript.js:8866:22)
    at visitEachNode (/node_modules/typescript/lib/typescript.js:8251:30)
    at forEachChild (/node_modules/typescript/lib/typescript.js:8623:24)
    at visitNode (/node_modules/typescript/lib/typescript.js:8870:21)
    at visitNode (/node_modules/typescript/lib/typescript.js:8239:20)
    at forEachChild (/node_modules/typescript/lib/typescript.js:8621:21)
    at visitNode (/node_modules/typescript/lib/typescript.js:8870:21)
    at visitEachNode (/node_modules/typescript/lib/typescript.js:8251:30)
    at forEachChild (/node_modules/typescript/lib/typescript.js:8607:24)
    at visitNode (/node_modules/typescript/lib/typescript.js:8876:29)
```

**Comment by aluanhaddad** [comment]
> Since TS is a superset of JS we expect (perhaps wrongly) TS parser to not fail for correct JS files.

Yes, but that means standard JS files and any extended formats, such as `JSX`, it decides to support. These are just comments, they can contain arbitrary unstructured and semi-structured text. It is not guaranteed to support all of JSDoc as there are a number of all too popular variants in wide use.

**Comment by kruszczynski** [comment]
@aluanhaddad That's exactly what I mean. Since those are "just comments" it sucks that a file with such comments fails parsing. In my example its JS but I guess a TS file with such comment would not parse either. That's why I think it's a bug, don't you?

**Comment by aluanhaddad** [comment]
A TS or a JS should definitely parse, but I don't know how you are invoking the compiler. There are a lot of options, and I am not that familiar invoking it programmatically. I just tried with the latest nightly using the command line compiler. I tried a JS and a TS version of the file and both were correctly parsed and emitted.

**Comment by kruszczynski** [comment]
For us the `ts.createSourceFile` method fails. I'll try on nightly build and get back to you.

**Comment by aluanhaddad** [comment]
```js
> var ts = require('typescript')
undefined
> ts.version
'2.0.7'
> var jf = ts.createSourceFile('./dist/fromts/fx.js', fs.readFileSync('./test/src/jsd.js').toString(), 'ES5')
undefined
> jf
SourceFileObject {
  pos: 0,
  end: 542,
  flags: 134217728,
  parent: undefined,
  kind: 256,
  text: '//------------------------------------------------------------------------------\r\n// Typedefs\r\n//------------------------------------------------------------------------------\r\n\r\n/**\r\n * An error message description\r\n * @typedef {Object} MessageDescriptor\r\n * ...\r\n * @property {Object} [data] Optional data to use to fill in placeholders in the\r\n *      message.\r\n */\r\n\r\n/**\r\n *@param m {MessageDescriptor} a message descriptor\r\n */\r\nfunction whatever(m) {\r\n    m.data().toString()\r\n    // If there\'s no code in the file it doesn\'t fail\r\n}\r\n',
  bindDiagnostics: [],
  languageVersion: 'ES5',
  fileName: 'dist/fromts/fx.js',
  languageVariant: 1,
  isDeclarationFile: false,
  scriptKind: 1,
  referencedFiles: [],
  typeReferenceDirectives: [],
  amdDependencies: [],
  moduleName: undefined,
  statements:
   [ NodeObject {
       pos: 0,
       end: 540,
       flags: 134217728,
       parent: undefined,
       kind: 220,
       decorators: undefined,
       asteriskToken: undefined,
       name: [Object],
       typeParameters: undefined,
       parameters: [Object],
       body: [Object],
       jsDocComments: [Object] },
     pos: 0,
     end: 540 ],
  endOfFileToken:
   TokenObject {
     pos: 540,
     end: 542,
     flags: 134217728,
     parent: undefined,
     kind: 1 },
  externalModuleIndicator: undefined,
  nodeCount: 39,
  identifierCount: 8,
  identifiers:
   { whatever: 'whatever',
     m: 'm',
     data: 'data',
     toString: 'toString',
     Object: 'Object',
     MessageDescriptor: 'MessageDescriptor' },
  parseDiagnostics: [] }
>
```

**Comment by kruszczynski** [comment]
We use `ES6` as script target. When I switched it to ES5 it did create a source file but trying to iterate over nodes resulted in errors as some nodes were parent-less so the problem persists, but elsewhere.

**Comment by mhegazy** [comment]
how are you creating the source file?

**Comment by kruszczynski** [comment]
```
this.sourceFileAast = ts.createSourceFile(path, content, ts.ScriptTarget.ES6)
```

**Comment by RyanCavanaugh** [comment]
@kruszczynski a self-contained repro would be extremely useful, if possible

**Comment by kruszczynski** [comment]
@RyanCavanaugh I'll try to get you one over the holidays. Will also check if the problem persists in `2.1`.
