### ISSUE TITLE
Language service crash in 'displayPartKind'

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#12166]
In Version 2.1.0-dev.20161110

```ts
TypeError: Cannot read property 'flags' of undefined
    at displayPartKind (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:51437:31)
    at symbolPart (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:51435:34)
    at Object.writeSymbol (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:51422:31)
    at buildBindingElementDisplay (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:22476:28)
    at C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:22457:110
    at buildDisplayForCommaSeparatedList (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:22503:21)
    at buildBindingPatternDisplay (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:22457:21)
    at buildParameterDisplay (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:22442:21)
    at buildDisplayForParametersAndDelimiters (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:22531:21)
    at buildSignatureDisplay (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:22575:17)
```

**Comment by ahejlsberg** [comment]
@DanielRosenwasser Repro?

**Comment by DanielRosenwasser** [comment]
@mhegazy told me to just file this and we'll discuss offline.

**Comment by nickytonline** [comment]
I'm able to produce this error by destructuring arguments two levels deep, e.g. 

```
import * as React from 'react';

interface SomeInterface {
	someBoolean: boolean,
	someString: string;
}

interface SomeProps {
  someProp: SomeInterface;
}

export const SomeStatelessComponent = ({someProp: { someBoolean, someString}}: SomeProps) => (<div>{`${someBoolean}${someString}`});
```

but if I destruct just the top level, e.g. `someProp`, it works

```
export const SomeStatelessComponent = ({someProp}: SomeProps) => (<div>{`${someProp.someBoolean}${someProp.someString}`});
```
