### ISSUE TITLE
Cannot extend native type Error

### ISSUE THREAD

**Issue by brodeuralexis** [Microsoft/TypeScript#12279]
**TypeScript Version:**  2.1.1

**Code**

```ts
"use strict";

class Exception extends Error {

    public constructor(public status: number = 500, reason: string) {
        super(reason);

        if (!this.isValidStatus(status)) {
            this.status = 500;
        }
    }

    isValidStatus(status: number): boolean {
        return status >= 100 && status <= 599;
    }

}

const exception = new Exception(401, "Invalid API Key");
```

**Expected behavior:**
To see the program run to completion with any errors.

**Actual behavior:** 
```
C:\Users\Consultant\issue.js:13
        if (!_this.isValidStatus(status)) {
                   ^

TypeError: _this.isValidStatus is not a function
    at new Exception (C:\Users\Consultant\issue.js:13:20)
    at Object.<anonymous> (C:\Users\Consultant\issue.js:23:17)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
```

**Additional Information:**
This problem is only present in the release candidate (TypeScript@2.1.1).

Compiled JavaScript for TypeScript@2.1.1
```js
"use strict";
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var Exception = (function (_super) {
    __extends(Exception, _super);
    function Exception(status, reason) {
        if (status === void 0) { status = 500; }
        var _this = _super.call(this, reason) || this;
        _this.status = status;
        if (!_this.isValidStatus(status)) {
            _this.status = 500;
        }
        return _this;
    }
    Exception.prototype.isValidStatus = function (status) {
        return status >= 100 && status <= 599;
    };
    return Exception;
}(Error));
var exception = new Exception(401, "Invalid API Key");
```
Compiled JavaScript for TypeScript@2.0.9:
```js
"use strict";
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var Exception = (function (_super) {
    __extends(Exception, _super);
    function Exception(status, reason) {
        if (status === void 0) { status = 500; }
        _super.call(this, reason);
        this.status = status;
        if (!this.isValidStatus(status)) {
            this.status = 500;
        }
    }
    Exception.prototype.isValidStatus = function (status) {
        return status >= 100 && status <= 599;
    };
    return Exception;
}(Error));
var exception = new Exception(401, "Invalid API Key");
```

**Comment by aluanhaddad** [comment]
Please see #12123

**Comment by brodeuralexis** [comment]
Yep, that better describes it.
Thanks.

**Comment by DanielRosenwasser** [comment]
This is an intentional breaking change and [documented here](https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work).
