### ISSUE TITLE
writeReferencePath typo issue

### ISSUE THREAD

**Issue by Delagen** [Microsoft/TypeScript#12297]
**TypeScript Version:**  2.0.10

**Expected behavior:**
No errors

**Actual behavior:** 
```
Module build failed: TypeError: Cannot read property 'replace' of undefined
```

Cause L37224 of lib/typescript.js file of npm package
```
function writeReferencePath(referencedFile, addBundledFileReference, emitOnlyDtsFiles) {
...
if (declFileName) {
                declFileName = ts.getRelativePathToDirectoryOrUrl(ts.getDirectoryPath(ts.normalizeSlashes(declarationFilePath)), declFileName, host.getCurrentDirectory(), host.getCanonicalFileName, 
                /*isAbsolutePathAnUrl*/ false);
                referencesOutput += "/// <reference path=\"" + declFileName + "\" />" + newLine;
            }
...
}
```
L37236: `declarationFilePath` is missing and must be replaced with `declFileName` or something related

**Comment by RyanCavanaugh** [comment]
Can we see a complete call stack? Or some way to reproduce this?

**Comment by Delagen** [comment]
```
Module build failed: TypeError: Cannot read property 'replace' of undefined
    at Object.normalizeSlashes (...\node_modules\typescript\lib\typescript.js:1771:20)
    at writeReferencePath (...\node_modules\typescript\lib\typescript.js:37236:90)
    at ...\node_modules\typescript\lib\typescript.js:35750:29
    at Object.forEach (...\node_modules\typescript\lib\typescript.js:1115:30)
    at ...\node_modules\typescript\lib\typescript.js:35742:20
    at Object.forEach (...\node_modules\typescript\lib\typescript.js:1115:30)
    at emitDeclarations (...\node_modules\typescript\lib\typescript.js:35735:12)
    at getDeclarationDiagnosticsFromFile (...\node_modules\typescript\lib\typescript.js:35699:13)
    at onSingleFileEmit (...\node_modules\typescript\lib\typescript.js:7569:13)
    at Object.forEachExpectedEmitFile (...\node_modules\typescript\lib\typescript.js:7542:21)
    at Object.getDeclarationDiagnostics (...\node_modules\typescript\lib\typescript.js:35695:12)
    at ...\node_modules\typescript\lib\typescript.js:45673:27
    at runWithCancellationToken (...\node_modules\typescript\lib\typescript.js:45468:24)
    at getDeclarationDiagnosticsWorker (...\node_modules\typescript\lib\typescript.js:45669:20)
    at Object.getDeclarationDiagnostics (...\node_modules\typescript\lib\typescript.js:45457:24)
    at _transpile (...\node_modules\@ngtools\webpack\src\loader.js:92:29)
    at ...\node_modules\@ngtools\webpack\src\loader.js:128:26
```

The main cause error that declarationFilePath is undefined and `normalizeSlashes` call replace as method of undefined

**Comment by yuit** [comment]
@Delagen Sorry for delay here. Could you share with us the repo (like code/setting) of this scenario? I am able to find the fix but would like to ensure that the fix will unblock the scenario.

**Comment by Delagen** [comment]
Sorry. But have no reproduction. After update of webpack loader and typescript to latest versions error have gone. I think loader changed the way of using typescript core.

**Comment by mhegazy** [comment]
thanks. closing.
