### ISSUE TITLE
Project does not compile on Android (Termux)

### ISSUE THREAD

**Issue by andraaspar** [microsoft/TypeScript#12403]
**TypeScript Version:**  master branch 2016-11-21

**Code**

```
$ gulp local
```

**Expected behavior:**
Project to compile successfully.

**Actual behavior:**
```
...
[08:37:07] 'src/compiler/diagnosticInformationMap.generated.ts' errored after 74 ms
[08:37:07] Error: spawn /bin/sh ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
...
```
And no js files are generated, only .d.ts.

**Workaround**
Edit Gulpfile.ts and replace ```/bin/sh``` with ```sh``` on line 74:
```
const ex = cp.spawn(isWin ? "cmd" : "/bin/sh", [subshellFlag, ...command], { stdio: "inherit", windowsVerbatimArguments: true } as any);
```
Becomes:
```
const ex = cp.spawn(isWin ? "cmd" : "sh", [subshellFlag, ...command], { stdio: "inherit", windowsVerbatimArguments: true } as any);
```
This is because Termux does not have access to the root folder, and uses a different path to sh.

Please note that I have not tested the effects of the above change on Linux or MacOS. If this change clashes with those systems, then Android could be detected by checking ```process.platform === 'android'```.

**Comment by RyanCavanaugh** [comment]
Accepting PRs if anyone wants to get this working and can test on the existing platforms

**Comment by mhegazy** [comment]
dose `jake local` work?

**Comment by andraaspar** [comment]
No, it fails similarly:

```
$ jake local --trace
node lib/tsc.js --noImplicitAny --noImplicitThis --noEmitOnError --types  --pretty --preserveConstEnums --module commonjs -sourcemap -mapRoot file:////data/data/com.termux/files/home/a/p/TypeScript/scripts --target es5 --noUnusedLocals --noUnusedParameters scripts/buildProtocol.ts
jake aborted.
Error: spawn /bin/sh ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by jakebailey** [comment]
The offending code here is gone; the build system hasn't called `sh` in some time.
