### ISSUE TITLE
Error “Node 136 (UndefinedKeyword) was unexpected” after upgrading from 2.0.10 to 2.1.1

### ISSUE THREAD

**Issue by juergenzimmermann** [Microsoft/TypeScript#12464]
TypeScript Version:  2.1.1

After upgrading from 2.0.10 to 2.1.1 I'm getting the following error. I've no idea which one of my source files is causing the trouble.

```
[10:30:50] Error: Debug Failure. False expression: Unexpected node.
Verbose Debug Information: Node 136 (UndefinedKeyword) was unexpected.
    at Object.assert (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:3001:23)
    at Object.Debug.failBadSyntaxKind (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:42746:55)
    at serializeTypeNode (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:44666:30)
    at serializeTypeNode (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:44637:56)
    at serializeReturnTypeOfNode (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:44563:24)
    at addOldTypeMetadata (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:44428:136)
    at addTypeMetadata (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:44416:17)
    at transformAllDecoratorsOfDeclaration (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:44241:13)
    at generateClassElementDecorationExpression (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:44288:40)
    at generateClassElementDecorationExpressions (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:44268:34)
[10:30:50] 'ts' errored after 4.37 s
```

**Comment by juergenzimmermann** [comment]
The problem was in `tsconfig.json` where I was having these two lines:
```
"inlineSources": true,
"emitDecoratorMetadata": true,
```

**Comment by mhegazy** [comment]
The stack suggests it is happening while emitting the `__metadata` decorator. That is why setting `emitDecoratorMetadata` to `false` avoids the issue. We will need some source information to be able to get this figured-out. can you also try `typescript@next` and see if the issue still persist.

**Comment by juergenzimmermann** [comment]
The issue still exists with 2.1.4. Basically the code base is a web app with Angular 2.3.0, Chart.js 2.4.0, Moment 2.17.1, lodash 4.17.2 (and Bootstrap 4.0.0-alpha.5, Font Awesome 4.7.0 for CSS).

I'll try to extract a subset of the whole web app, and try to reduce the 3rd party software. This may take some days because I've to work for this web project ;-) and we went back to TS 2.0.10

**Comment by mhegazy** [comment]
@juergenzimmermann if you can try `typescript@next` as well, that would be helpful. we made a couple of changes to the emit of meta data, though nothing with this call stack.

also if you can call [`node --inspect tsc.js`](http://www.mattzeunert.com/2016/06/01/node-v8-inspector-inspect.html), you should be able to get `ts.getSourceFileOfNode(node)` should tell you which file is actually causing the crash, we only need that file, or a snippet of it.
