### ISSUE TITLE
Debug Failure. False expression: on nightly

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#12631]
**TypeScript Version:**  nightly (2.2.0-dev.20161201)

Tried to run `tsc -p . --watch` on Windows 10

**Expected behavior:**

Build the project

**Actual behavior:**

```
C:\nodejs\node_modules\typescript\lib\tsc.js:1794
                throw new Error("Debug Failure. False expression: " + (message || "") + verboseDebugString);
                ^
Error: Debug Failure. False expression: 
    at Object.assert (C:\nodejs\node_modules\typescript\lib\tsc.js:1794:23)
    at resolveExternalModule (C:\nodejs\node_modules\typescript\lib\tsc.js:20568:30)
    at resolveExternalModuleNameWorker (C:\nodejs\node_modules\typescript\lib\tsc.js:20535:20)
    at mergeModuleAugmentation (C:\nodejs\node_modules\typescript\lib\tsc.js:19892:34)
    at initializeTypeChecker (C:\nodejs\node_modules\typescript\lib\tsc.js:35226:25)
    at Object.createTypeChecker (C:\nodejs\node_modules\typescript\lib\tsc.js:19739:9)
    at getDiagnosticsProducingTypeChecker (C:\nodejs\node_modules\typescript\lib\tsc.js:49600:93)
    at Object.getGlobalDiagnostics (C:\nodejs\node_modules\typescript\lib\tsc.js:49877:41)
    at compileProgram (C:\nodejs\node_modules\typescript\lib\tsc.js:51958:78)
    at compile (C:\nodejs\node_modules\typescript\lib\tsc.js:51917:26)
```

**Comment by mhegazy** [comment]
An you share a project we can debug against?

**Comment by pocesar** [comment]
After adding this `generic.d.ts` file to the location defined in `rootDir`:

```ts
import React from 'react'

declare module 'react' {
  interface NavigatorProperties {
    style?: React.ViewStyle
  }
}

declare module 'react-native-material-kit' {
  interface MKColor {
    Red: string;
    Pink: string;
    Purple: string;
    DeepPurple: string;
    Indigo: string;
    Blue: string;
    LightBlue: string;
    Cyan: string;
    Teal: string;
    Green: string;
    LightGreen: string;
    Lime: string;
    Yellow: string;
    Amber: string;
    Orange: string;
    DeepOrange: string;
    Brown: string;
    Grey: string;
    BlueGrey: string;
    Transparent: string;
    Silver: string;  // opacity plain button background
    RGBIndigo: string;
    RGBPink: string;
    RGBPurple: string;
    RGBTeal: string;
    palette_blue_400: string;
    palette_red_500: string;
    palette_yellow_600: string;
    palette_green_500: string;
  }
}
```

excluding the file, the compiler works

tsconfig.json:

```json
{
    "compilerOptions": {
        "module": "es2015",
        "target": "es2015",
        "sourceMap": true,
        "jsx": "react",
        "declaration": false,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noImplicitAny": false,
        "allowJs": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noImplicitUseStrict": true,
        "noEmitHelpers": true,
        "noEmitOnError": false,
        "allowSyntheticDefaultImports": true,
        "preserveConstEnums": true,
        "moduleResolution": "node",
        "rootDir": "src",
        "outDir": "lib"
    },
    "exclude": [
        "node_modules",
        "ios",
        "android",
        "typings",
        ".vscode/**/*.ts"
    ]
}
```

**Comment by pocesar** [comment]
Doesn't seem to be a problem with TS, I've copy and pasted the text directly from http://www.xinthink.com/react-native-material-kit/docs/lib/MKColor.html to the generic.d.ts file, removed the weird characters (I'm using vscode), but it seems that a non printable character was inside the .d.ts. copy and pasted to the notepad and back again to the .d.ts file, and it worked.

**Comment by pocesar** [comment]
It seems that the faulty definition by me is making it choke. the correct declaration should be: 

```ts
declare module 'react-native-material-kit' {
  namespace MKColor {
    export const Red: string;
    export const Pink: string;
    export const Purple: string;
    export const DeepPurple: string;
    export const Indigo: string;
    export const Blue: string;
    export const LightBlue: string;
    export const Cyan: string;
    export const Teal: string;
    export const Green: string;
    export const LightGreen: string;
    export const Lime: string;
    export const Yellow: string;
    export const Amber: string;
    export const Orange: string;
    export const DeepOrange: string;
    export const Brown: string;
    export const Grey: string;
    export const BlueGrey: string;
    export const Transparent: string;
    export const Silver: string;
    export const RGBIndigo: string;
    export const RGBPink: string;
    export const RGBPurple: string;
    export const RGBTeal: string;
    export const palette_blue_400: string;
    export const palette_red_500: string;
    export const palette_yellow_600: string;
    export const palette_green_500: string;
  }
}
```

**Comment by DanielRosenwasser** [comment]
I'm not clear on whether you've been able to reproduce the issue or not. Would you be able to upload a repro to a Github repository so we could easily clone it and try it out?

**Comment by pocesar** [comment]
I'll try to do a minimum repro, it's pretty consistently reproducible for me, if the both declarations go in the same file, build fails

**Comment by pocesar** [comment]
this isn't happening anymore in newer versions of nightly
