### ISSUE TITLE
`completionEntryDetails` Should Not Return Parameters In Assignment Contexts

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#12677]
**TypeScript Version:**  2.1.4-insiders

From https://github.com/Microsoft/vscode/issues/2092, with the code:

```js
const a = {
    func(x) {}
}

let {f} = a;
```

Trying to complete the `f` in `let {f}` results in an expansion to `let {func(x)} = a;`

I have a workaround fix implemented on the VSCode side (https://github.com/Microsoft/vscode/pull/16415) but @dbaeumer suggested that it would be better if fixed this on the TypeScript side. The `completionEntryDetails` call we make for the expansion should not return parameter completion details inside of assignment or import contexts.

**Comment by mjbvz** [comment]
@dbaeumer Suggested an alternative design: have `completionEntryDetails` return some sort of additional context info so that we can determine where the completion is being performed and use this information when expanding. I believe this would be similar to what our current workaround (https://github.com/Microsoft/vscode/pull/16415) does

**Comment by pocesar** [comment]
```
[Error  - 01:41:14] 'completionEntryDetails' request failed with error.
Error processing request. Cannot read property 'target' of undefined
TypeError: Cannot read property 'target' of undefined
    at Object.getSymbolDisplayPartsDocumentationAndSymbolKind (C:\nodejs\node_modules\typescript\lib\tsserver.js:70097:62)
    at Object.getCompletionEntryDetails (C:\nodejs\node_modules\typescript\lib\tsserver.js:63990:47)
    at Object.getCompletionEntryDetails (C:\nodejs\node_modules\typescript\lib\tsserver.js:77359:35)
    at C:\nodejs\node_modules\typescript\lib\tsserver.js:83468:57
    at Object.mapDefined (C:\nodejs\node_modules\typescript\lib\tsserver.js:1586:30)
    at IOSession.Session.getCompletionEntryDetails (C:\nodejs\node_modules\typescript\lib\tsserver.js:83467:27)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\nodejs\node_modules\typescript\lib\tsserver.js:82562:61)
    at C:\nodejs\node_modules\typescript\lib\tsserver.js:83895:88
    at IOSession.Session.executeWithRequestId (C:\nodejs\node_modules\typescript\lib\tsserver.js:83886:28)
    at IOSession.Session.executeCommand (C:\nodejs\node_modules\typescript\lib\tsserver.js:83895:33)
    at IOSession.Session.onMessage (C:\nodejs\node_modules\typescript\lib\tsserver.js:83915:35)
    at Interface.<anonymous> (C:\nodejs\node_modules\typescript\lib\tsserver.js:85062:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

not sure how to reproduce
