### ISSUE TITLE
Since TypeScript 2.1.4 the Angular 2 ng-xi18n tool does not work anymore: TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by Martin-Wegner** [Microsoft/TypeScript#12760]
**TypeScript Version:**  2.1.4

Since TypeScript 2.1.4 the Angular 2 `ng-xi18n` tool does not work anymore:

```
TypeError: Cannot read property 'text' of undefined
    at NodeObject.getText (/work/client/node_modules/typescript/lib/typescript.js:78080:30)
    at Evaluator.evaluateNode (/work/client/node_modules/@angular/tsc-wrapped/src/evaluator.js:495:66)
    at _loop_1 (/work/client/node_modules/@angular/tsc-wrapped/src/collector.js:306:54)
    at /work/client/node_modules/@angular/tsc-wrapped/src/collector.js:365:25
    at visitEachNode (/work/client/node_modules/typescript/lib/typescript.js:13907:30)
    at Object.forEachChild (/work/client/node_modules/typescript/lib/typescript.js:14078:24)
    at MetadataCollector.getMetadata (/work/client/node_modules/@angular/tsc-wrapped/src/collector.js:204:12)
    at MetadataWriterHost.writeMetadata (/work/client/node_modules/@angular/tsc-wrapped/src/compiler_host.js:111:51)
    at MetadataWriterHost.writeFile (/work/client/node_modules/@angular/tsc-wrapped/src/compiler_host.js:103:19)
    at Object.writeFile (/work/client/node_modules/typescript/lib/typescript.js:62522:132)
Extraction failed
```

https://github.com/angular/angular/issues/13305

**Comment by Martin-Wegner** [comment]
I think it is an Angular 2 issue -> close...
