### ISSUE TITLE
Error: Debug Failure. False expression: File normalize.css/normalize.css has unknown extension.

### ISSUE THREAD

**Issue by sarod** [Microsoft/TypeScript#13004]
**TypeScript Version:**  2.1.4 and nightly (2.2.0-dev.201xxxxx)

**Code**
```ts
import 'normalize.css';
```

**tsconfig**
```json
{
  "compilerOptions": {
    "moduleResolution": "node"
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Expected behavior:**
Tsc should compile without error as ts 2.0.10 does.
This kind of import are handled by webpack that injects the css at runtime. 

**Actual behavior:**
Running tsc 2.1.4 fails with the following error
```
Error: Debug Failure. False expression: File /home/sarod/dev/git/tsloader-ts2-1/node_modules/normalize.css/normalize.css has unknown extension.
    at Object.assert (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:1796:23)
    at Object.fail (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:1801:19)
    at Object.extensionFromPath (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:1912:15)
    at resolvedFromAnyFile (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:18928:44)
    at loadNodeModuleFromDirectory (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:19382:28)
    at loadModuleFromNodeModulesFolder (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:19411:13)
    at loadModuleFromNodeModulesOneLevel (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:19428:53)
    at /home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:19422:24
    at forEachAncestorDirectory (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:19480:26)
    at loadModuleFromNodeModulesWorker (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:19420:16)
```

I initially thought it was a ts-loader issue that fails with another error on the same code (see https://github.com/TypeStrong/ts-loader/issues/416)

This public repro can be used to reproduce https://github.com/sarod/ts-loader-issue416

**Comment by sarod** [comment]
The code also compiles using typescript 2.1.1.

**Comment by vladima** [comment]
@andy-ms can you please take a look?

**Comment by roypeled** [comment]
I'm getting:
```
Error: Debug Failure. False expression: File  has unknown extension.
    at Object.assert (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:3177:23)
    at Object.fail (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:3182:19)
    at Object.extensionFromPath (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:3324:15)
    at /Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:62182:46
    at Array.map (native)
    at resolveModuleNamesWorker (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:62176:141)
    at resolveModuleNamesReusingOldState (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:62300:24)
    at processImportedModules (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:63152:35)
    at findSourceFile (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:63062:17)
    at processImportedModules (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:63181:25)
    at findSourceFile (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:63062:17)
    at processImportedModules (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:63181:25)
    at findSourceFile (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:63062:17)
    at processImportedModules (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:63181:25)
    at findSourceFile (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:63062:17)
    at processImportedModules (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:63181:25)
    at findSourceFile (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:63062:17)
    at processSourceFile (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:62965:27)
    at processRootFile (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:62852:13)
    at /Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:62203:60
    at Object.forEach (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:1294:30)
    at Object.createProgram (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:62203:16)
    at synchronizeHostData (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:78867:33)
    at Object.getProgram (/Users/roypeled/src/folloze/node_modules/typescript/lib/typescript.js:78967:13)
    at State.updateProgram (/Users/roypeled/src/folloze/node_modules/awesome-typescript-loader/dist.babel/host.js:241:42)
    at /Users/roypeled/src/folloze/node_modules/awesome-typescript-loader/dist.babel/instance.js:333:27
    at Compiler.<anonymous> (/Users/roypeled/src/folloze/node_modules/awesome-typescript-loader/dist.babel/instance.js:354:15)
    at Compiler.next (/Users/roypeled/src/folloze/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/Users/roypeled/src/folloze/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/roypeled/src/folloze/node_modules/tapable/lib/Tapable.js:71:13)
```
Also on version 2.1.4.

Downgrading solved the issue.

**Comment by DomiR** [comment]
Quickfix, as typescript can't import other filetypes at the moment: 
```diff
-import 'normalize.css';
+declare var require;
+require('normalize.css');
```

**Comment by mhegazy** [comment]
@sarod, @DomiR and @roypeled can you give `typescript@2.2.0-dev.20161221` tomorrow.

**Comment by sarod** [comment]
It seems to work using typescript@2.2.0-dev.20161221
tsc logs a message but does not raise errors.

Thanks !
-Seb
