### ISSUE TITLE
Webpack project fails with false expression file  has an unknown extension on 'optimize assets' phase

### ISSUE THREAD

**Issue by alexproca** [Microsoft/TypeScript#13256]
I have a webpack project failing with "false expression" error. The error was introduced after typescript 2.1.1 (if I revert back to typescript 2.1.1 the error dissapears) 

My project with a breaking branch can be found here https://gitlab.com/incremental.community/declaratii-web/tree/breaking

**TypeScript Version:**  2.1.4 

**Code**
```
NODE_ENV=production webpack -p --progress --color --optimize-minimize --optimize-dedupe --optimize-occurence-order
```
```bash
npm run build

```

**Expected behavior:**

Build ok

**Actual behavior:**

```
> NODE_ENV=production webpack -p --progress --color --optimize-minimize --optimize-dedupe --optimize-occurence-order

90% optimize assetsError: Debug Failure. False expression: File  has unknown extension.
    at Object.assert (/Absolute/path/node_modules/typescript/lib/typescript.js:3177:23)
    at Object.fail (/Absolute/path/node_modules/typescript/lib/typescript.js:3182:19)
    at Object.extensionFromPath (/Absolute/path/node_modules/typescript/lib/typescript.js:3324:15)
    at /Absolute/path/node_modules/typescript/lib/typescript.js:62182:46
    at Array.map (native)
    at resolveModuleNamesWorker (/Absolute/path/node_modules/typescript/lib/typescript.js:62176:141)
    at resolveModuleNamesReusingOldState (/Absolute/path/node_modules/typescript/lib/typescript.js:62300:24)
    at processImportedModules (/Absolute/path/node_modules/typescript/lib/typescript.js:63152:35)
    at findSourceFile (/Absolute/path/node_modules/typescript/lib/typescript.js:63062:17)
    at processSourceFile (/Absolute/path/node_modules/typescript/lib/typescript.js:62965:27)
    at processRootFile (/Absolute/path/node_modules/typescript/lib/typescript.js:62852:13)
    at /Absolute/path/node_modules/typescript/lib/typescript.js:62203:60
    at Object.forEach (/Absolute/path/node_modules/typescript/lib/typescript.js:1294:30)
    at Object.createProgram (/Absolute/path/node_modules/typescript/lib/typescript.js:62203:16)
    at synchronizeHostData (/Absolute/path/node_modules/typescript/lib/typescript.js:78867:33)
    at Object.getProgram (/Absolute/path/node_modules/typescript/lib/typescript.js:78967:13)
    at State.updateProgram (/Absolute/path/node_modules/awesome-typescript-loader/dist.babel/host.js:241:42)
    at /Absolute/path/node_modules/awesome-typescript-loader/dist.babel/instance.js:333:27
    at Compiler.<anonymous> (/Absolute/path/node_modules/awesome-typescript-loader/dist.babel/instance.js:354:15)
    at Compiler.next (/Absolute/path/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/Absolute/path/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Absolute/path/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Absolute/path/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Absolute/path/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.next (/Absolute/path/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (/Absolute/path/node_modules/webpack/lib/ProgressPlugin.js:69:5)
    at Compilation.applyPluginsAsync (/Absolute/path/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Absolute/path/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.next (/Absolute/path/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (/Absolute/path/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:140:4)
```

**Comment by webm0nk3y** [comment]
Getting the same error myself in another project.

**Comment by mhegazy** [comment]
do you see the same behaviour on `typescript@next`?

**Comment by mhegazy** [comment]
Debugging through the repro, it seems to be caused by awesome-typescript-loader returning an empty string instead of undefined in https://github.com/s-panferov/awesome-typescript-loader/blob/dc7c216f509cf198a9412b3cd2c98b06786b3560/src/host.ts#L183, if instead the  code returned an `undefined` for resolvedModule, it works as expected. 

Also this seems to be a fairly old version of awesome-typescript-loader, `awesome-typescript-loader@1.1.1`, upgrading to `awesome-typescript-loader@latest` changing nothing else seems to address the issue as well.

**Comment by JulianoLMarinho** [comment]
I solved this problem changing version of typescript to 2.0.0 on package.json.
`"typescript": "~2.0.0"`

**Comment by alexproca** [comment]
I solved the problem too by using `awesome-typescript-loader@3.0.0-beta.10` and `typescript@2.1.4`
