### ISSUE TITLE
Fail when JSX.IntrinsicElements is an intersection type

### ISSUE THREAD

**Issue by Knagis** [microsoft/TypeScript#13345]
**TypeScript Version:**  2.1.4, 2.2.1, 3.6.3, 4.0.3

The compiler does not support JSX.IntrinsicElements that are intersections. It even fails with an exception instead of an error message.

The reason why I think I require this behavior is that I want the IntrinsicElements to be something like:
`{ [P in keyof HTMLElementTagNameMap]: Partial<HTMLElementTagNameMap[P]> } & { [P: string]: Partial<HTMLElement> }`

## **Code**

*intrinsic.jsx.d.ts*
```ts
declare namespace JSX {
    // change the alias to use the different versions
    type IntrinsicElements = IntrinsicElements4;

    // works
    type IntrinsicElements1 = {
        a: Partial<HTMLAnchorElement>;
    }

    // works
    type IntrinsicElements2 = {
        [P: string]: Partial<HTMLElement>;
    }

    // works
    type IntrinsicElements3 = {
        a: Partial<HTMLAnchorElement>;
        [P: string]: Partial<HTMLElement>;
    }

    // does not work
    type IntrinsicElements4 = IntrinsicElements1 & IntrinsicElements2;

}
```

*intrinsic.tsx*
```ts
/// <reference path="intrinsic.jsx.d.ts" />
function jsxCreate() {}

let a = <a href="about:blank">foo</a>;
let b = <foo>bar</foo>;
```

*tsconfig.json*
```json
{
    "compilerOptions": {
        "jsx": "react",
        "jsxFactory": "jsxCreate"
    },
    "files": ["intrinsic.tsx"]
}
```

## **Expected behavior:**

`IntrinsicElements4` variation should work the same as `IntrinsicElements3` which is semantically the same.

## **Actual behavior:**

The code does not compile, the compiler fails with an exception:

```
npm\node_modules\typescript\lib\tsc.js:49700
                throw e;
                ^

TypeError: Cannot read property 'members' of undefined
    at getIndexSymbol (npm\node_modules\typescript\lib\tsc.js:23635:26)
    at getIndexDeclarationOfSymbol (npm\node_modules\typescript\lib\tsc.js:23639:31)
    at getIndexInfoOfSymbol (npm\node_modules\typescript\lib\tsc.js:23658:31)
    at getJsxElementAttributesType (npm\node_modules\typescript\lib\tsc.js:28965:56)
    at checkJsxOpeningLikeElement (npm\node_modules\typescript\lib\tsc.js:29015:40)
    at checkJsxElement (npm\node_modules\typescript\lib\tsc.js:28708:13)
    at checkExpressionWorker (npm\node_modules\typescript\lib\tsc.js:31266:28)
    at checkExpression (npm\node_modules\typescript\lib\tsc.js:31182:42)
    at checkExpressionCached (npm\node_modules\typescript\lib\tsc.js:31105:38)
    at checkDeclarationInitializer (npm\node_modules\typescript\lib\tsc.js:31115:24)
```

**Comment by Knagis** [comment]
Is there any update on this issue?

**Comment by Knagis** [comment]
This issue is still present in 2.2.1 - the compiler still crashes with an unhandled exception.

**Comment by Knagis** [comment]
This is still actual in 3.6.3.

**Comment by Knagis** [comment]
Still actual in 4.0.3 though the message changed a bit

```
Cannot read property 'flags' of undefined
```

**Comment by Knagis** [comment]
Full stack on 4.0.3

```
node_modules\typescript\lib\tsc.js:84774
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at tryGetDeclaredTypeOfSymbol (node_modules\typescript\lib\tsc.js:41525:24)
    at getDeclaredTypeOfSymbol (node_modules\typescript\lib\tsc.js:41522:20)
    at getIntrinsicAttributesTypeFromJsxOpeningLikeElement (node_modules\typescript\lib\tsc.js:53880:44)
    at resolveJsxOpeningLikeElement (bug\node_modules\typescript\lib\tsc.js:55928:30)
    at resolveSignature (node_modules\typescript\lib\tsc.js:55967:28)
    at getResolvedSignature (node_modules\typescript\lib\tsc.js:55978:26)
    at checkJsxOpeningLikeElementOrOpeningFragment (node_modules\typescript\lib\tsc.js:53938:27)
    at checkJsxElementDeferred (node_modules\typescript\lib\tsc.js:53562:13)
    at checkDeferredNode (node_modules\typescript\lib\tsc.js:62644:21)
    at Map.forEach **(<anonymous>)**
```

**Comment by Knagis** [comment]
Compiler no longer crashes on this example, starting from version 4.3. Seems the issue has been fixed.
