### ISSUE TITLE
Can't Build: Cannot find module './built/local/typescript.js'

### ISSUE THREAD

**Issue by timsuchanek** [Microsoft/TypeScript#13352]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**
```sh
~/c/ $ git clone https://github.com/Microsoft/TypeScript.git
~/c/ $ cd TypeScript
~/c/ $ npm install
~/c/ $ npm install -g gulp
~/c/TypeScript $ node --version
v7.4.0
~/c/TypeScript $ tsc --version
Version 2.2.0-dev.20161206
~/c/TypeScript $ gulp --version
[17:57:16] Requiring external module ts-node/register
[17:57:16] CLI version 3.9.1
[17:57:16] Local version 3.9.1
~/c/TypeScript $ gulp local
```

**Expected behavior:**
Correct build of the TypeScript compiler.

**Actual behavior:**
```sh
[17:54:11] Error: Cannot find module './built/local/typescript.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at getCompilerSettings (/Users/tim/code/TypeScript/gulpfile.ts:263:27)
    at Gulp.<anonymous> (/Users/tim/code/TypeScript/gulpfile.ts:379:82)
    at module.exports (/Users/tim/code/TypeScript/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/tim/code/TypeScript/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/tim/code/TypeScript/node_modules/orchestrator/index.js:214:10)
    at /Users/tim/code/TypeScript/node_modules/orchestrator/index.js:279:18
    at finish (/Users/tim/code/TypeScript/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/tim/code/TypeScript/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/tim/code/TypeScript/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/Users/tim/code/TypeScript/node_modules/end-of-stream/index.js:31:18)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:185:7)
    at /Users/tim/code/TypeScript/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by andy-ms** [comment]
Probably related to #13335. It may have been built to some ancestor directory.
