### ISSUE TITLE
ReferenceError: __awaiter is not defined with "noEmitHelpers: true"

### ISSUE THREAD

**Issue by kevincaradant** [Microsoft/TypeScript#13495]
Hi 
I get this error: `ReferenceError: __awaiter is not defined. `
IF I remove or write `"noEmitHelpers: false"`, that solved my problem why ? 
Thank you for your help :)

**TypeScript Version:**  2.1.5
**Node Version** 7.4.0
**Operating System**: Ubuntu 16.10 64 bits

**Code**
My tsconfig.json
```
{
    "compilerOptions": {
        "rootDir": "./src",
        "outDir": "./bin",
        "allowJs": true,
        "typeRoots": ["node_modules/@types"],
        "types": ["node", "promise", "cli-color", "yargs"],
        "lib": ["es5", "es2017", "dom", "es2015.promise", "es2016.array.include"],
        "target": "es5",
        "noImplicitAny": true,
        "noEmit": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "allowSyntheticDefaultImports": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "noUnusedLocals": true,
        "strictNullChecks": false,
        "noUnusedParameters": true,
        "sourceMap": true
    },

    "include": [
        "src/**/*"
    ],

    "exclude": [
        "./node_modules",
        "./bin",
        "./coverage",
        "./img",
        "./tests",
        "./tmpTests"
    ]
}
```

**Expected behavior:**
To execute my script without this error

**Actual behavior:**
```
ReferenceError: __awaiter is not defined
    at /home/bin/md5.js:38:16
    at Object.exports.generate (/home/bin/md5.js:135:7)
    at Object.<anonymous> (/home/bin/index.js:4:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

**Comment by aluanhaddad** [comment]
You need to add `"importHelpers": true`

**Comment by kevincaradant** [comment]
Ah yes it's why I thought that lib was here for something: https://github.com/Microsoft/tslib
I added your line and then this lib and it's good :).
Thank you @aluanhaddad
