### ISSUE TITLE
Crash for `getTypeAtLocation(sourceFile)`

### ISSUE THREAD

**Issue by andy-hanson** [microsoft/TypeScript#13503]
**TypeScript Version:**  nightly (2.2.0-dev.20170115)

**Code**

```js
const fs = require("fs"); const path = require("path"); const ts = require("typescript");

const tsconfigPath = "sample-code/tsconfig.json";

const { config, error } = ts.readConfigFile(tsconfigPath, path => fs.readFileSync(path, "utf-8"))
if (error) throw error;

const parsedOptions = ts.parseJsonConfigFileContent(config, ts.sys, path.dirname(tsconfigPath));
if (parsedOptions.errors.length) throw new Error("!")

const program = ts.createProgram(parsedOptions.fileNames, parsedOptions.options)
const file = program.getSourceFiles()[0];

program.getTypeChecker().getTypeAtLocation(file);
```

**Expected behavior:**

No crash

**Actual behavior:**

```
/home/andy/ts-services/node_modules/typescript/lib/typescript.js:42358
            while (nodeOnRightSide.parent.kind === 142 /* QualifiedName */) {
                                         ^

TypeError: Cannot read property 'kind' of undefined
    at getLeftSideOfImportEqualsOrExportAssignment (/home/andy/ts-services/node_modules/typescript/lib/typescript.js:42358:42)
    at isInRightSideOfImportOrExportAssignment (/home/andy/ts-services/node_modules/typescript/lib/typescript.js:42370:20)
    at Object.getTypeOfNode [as getTypeAtLocation] (/home/andy/ts-services/node_modules/typescript/lib/typescript.js:42590:17)
    at Object.<anonymous> (/home/andy/ts-services/repro.js:14:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

`sample-code/tsconfig.json` is `{}` and `sample-code/sample.ts` is empty.

**Comment by mhegazy** [comment]
We should handle SourceFile specially and return immediately if it is not a module. PRs welcomed.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
