### ISSUE TITLE
compiler crash (tsc --watch)

### ISSUE THREAD

**Issue by benny-medflyt** [Microsoft/TypeScript#13544]
**TypeScript Version:**  2.1.4

```
$ ./node_modules/.bin/tsc --version
Version 2.1.4
$ ./node_modules/.bin/tsc --project src --watch
...
11:09:19 PM - Compilation complete. Watching for file changes.
11:09:37 PM - File change detected. Starting incremental compilation...
/Users/benny/proj/node_modules/typescript/lib/tsc.js:49700
                throw e;
                ^

TypeError: Cannot read property 'emitNode' of undefined
    at Object.getEmitFlags (/Users/benny/proj/node_modules/typescript/lib/tsc.js:10680:28)
    at emitPropertyAssignment (/Users/benny/proj/node_modules/typescript/lib/tsc.js:48490:21)
    at pipelineEmitInUnspecifiedContext (/Users/benny/proj/node_modules/typescript/lib/tsc.js:47413:28)
    at pipelineEmitForContext (/Users/benny/proj/node_modules/typescript/lib/tsc.js:47176:32)
    at emitNodeWithSubstitution (/Users/benny/proj/node_modules/typescript/lib/tsc.js:44882:17)
    at pipelineEmitWithSubstitution (/Users/benny/proj/node_modules/typescript/lib/tsc.js:47170:13)
    at emitNodeWithSourceMap (/Users/benny/proj/node_modules/typescript/lib/tsc.js:45157:21)
    at pipelineEmitWithSourceMap (/Users/benny/proj/node_modules/typescript/lib/tsc.js:47167:13)
    at emitNodeWithComments (/Users/benny/proj/node_modules/typescript/lib/tsc.js:45296:25)
    at pipelineEmitWithComments (/Users/benny/proj/node_modules/typescript/lib/tsc.js:47159:13)
```

**Comment by RyanCavanaugh** [comment]
Duplicate #12994
