### ISSUE TITLE
Cannot read property 'charCount' of undefined in getNavigationTree 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#13571]
**TypeScript Version:**  2.1.5

I don't have an exact repo here.

Editing an invalid file that looked like this:

```ts
[''

'']
```

I cleared all the content and saved the file. 

After doing so, I sometimes see this crash:

```
TypeError: Cannot read property 'charCount' of undefined
    at LineNode.charOffsetToLineNumberAndPos (/Users/matb/projects/sand/node_modules/typescript/lib/tsserver.js:69372:75)
    at LineIndex.charOffsetToLineNumberAndPos (/Users/matb/projects/sand/node_modules/typescript/lib/tsserver.js:69093:34)
    at TextStorage.positionToLineOffset (/Users/matb/projects/sand/node_modules/typescript/lib/tsserver.js:64596:40)
    at ScriptInfo.positionToLineOffset (/Users/matb/projects/sand/node_modules/typescript/lib/tsserver.js:64785:41)
    at IOSession.Session.decorateSpan (/Users/matb/projects/sand/node_modules/typescript/lib/tsserver.js:68471:39)
    at /Users/matb/projects/sand/node_modules/typescript/lib/tsserver.js:68465:74
    at Array.map (native)
    at IOSession.Session.decorateNavigationTree (/Users/matb/projects/sand/node_modules/typescript/lib/tsserver.js:68465:39)
    at IOSession.Session.getNavigationTree (/Users/matb/projects/sand/node_modules/typescript/lib/tsserver.js:68481:32)
    at Session.handlers.ts.createMap._a.(anonymous function) (/Users/matb/projects/sand/node_modules/typescript/lib/tsserver.js:67598:61)", source: file:////Users/matb/projects/vscode/out/vs/workbench/electron-browser/shell.js (235)
```

I'll update this issue if I find a reliable repo in VSCode. Looks like some null checks are needed on the TSServer side

**Comment by mjbvz** [comment]
Hitting this again on branch checkout with TS 2.2:

```
ypeError: Cannot read property 'charCount' of undefined
    at LineNode.charOffsetToLineNumberAndPos (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:74016:75)
    at LineIndex.charOffsetToLineNumberAndPos (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:73737:34)
    at TextStorage.positionToLineOffset (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:69010:40)
    at ScriptInfo.positionToLineOffset (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:69199:41)
    at IOSession.Session.decorateSpan (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:73096:39)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:73090:74
    at Array.map (native)
    at IOSession.Session.decorateNavigationTree (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:73090:39)
    at IOSession.Session.getNavigationTree (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:73106:32)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:72213:61)",
```

**Comment by mhegazy** [comment]
looks fixed in latest.
