### ISSUE TITLE
Type annotations for default export

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#13626]
**TypeScript Version:**  2.1.1 

**Code**

```ts
import * as webpack from 'webpack';
export default: webpack.Configuration {
};
```

**Expected behavior:**
No error

**Actual behavior:**

`[ts] Expression expected.` error at `default:`

I couldn't find an issue for this but it's very likely it's a duplicate

**Comment by mhegazy** [comment]
Would not this be sufficient?

```ts
const config: webpack.Configuration  = { 

}
export default config;
```

**Comment by mohsen1** [comment]
Yes, that's what I do now but I wish I didn't have to.

**Comment by mhegazy** [comment]
related to https://github.com/Microsoft/TypeScript/issues/3792. we have tried to keep the module export as simple as possible on the syntax side.

**Comment by DanielRosenwasser** [comment]
I think it's a little more related to to the following scenario regarding function declarations.

if I want to write a decorator that is verified against the `PropertyDecorator` type in `lib.d.ts`, I can't write it easily. I have to use a function *expression*.

```ts
export let Encrypt: PropertyDecorator = function (obj, propName) {
};

which is case of friction whenever I want to actually implement a decorator without making a mistake.

**Comment by barakbd** [comment]
I am trying to use a default export  in the following way
``` typescript

readdirSync(join(__dirname, "../controllers/box"))

  .filter(f => f !== "*.spec.ts")
  .forEach(controllerFile => {
    const controllerBaseName = basename(controllerFile, ".js")
    import(`../controllers/box/${controllerBaseName}`).then((controller)=>{
      appRouter.use(
        `/box/${controllerBaseName}`, controller.default(boxServiceAccountClient))
    }).catch(error=>{
      console.log(error)
    })
  }); //end forEach
``` 

I get an error: 

`TypeError: controller.default is not a function
    at fs_1.readdirSync.filter.forEach.Promise.resolve.then.then.controller (/Users/bbendavi/Documents/cdt-box/dist/server/config/routes.js:16:71)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3`


I asked this on SO with a full file examples:
[https://stackoverflow.com/questions/48696327/how-to-define-a-module-default-export-type-in-typescript](url)


Would much appreciate your help!

**Comment by IgorGee** [comment]
```
import * as webpack from 'webpack'

export default {
...
} as webpack.Configuration
```

**Comment by jlouazel** [comment]
@IgorGee That's the proper way of doing it IMHO

**Comment by pelotom** [comment]
The problem with

```ts
export default ... as X
```

is that it's a cast, so it purposely loses type safety.

**Comment by jlouazel** [comment]
@pelotom As a general matter of fact, you're completely right, I'd avoid putting this in my codebase. For the scope of this thread where this is about webpack configuration, I think we're just fine

**Comment by pelotom** [comment]
@jlouazel leaving aside whether type safety is any less important in a webpack config... the issue is not specific to webpack, it's about annotating the type of the default export in general.

**Comment by oli-laban** [comment]
@IgorGee That's forbidden in `@typescript-eslint/recommended`.

**Comment by yarnaimo** [comment]
```ts
const as = <T>(value: T) => value

export default as<webpack.Configuration>({
    // ...
})
```

**Comment by thethomaseffect** [comment]
Would love to see this feature for nice succinct code

**Comment by mccallofthewild** [comment]
Tip: If you're exporting a function, put it in parenthesis before the `as`.

e.g.
```typescript
export default ((req, res) => {
   return 'Hello World!';
}) as RequestHandler;
```

**Comment by Mukhametvaleev** [comment]
I have the same problem too

**Comment by white-room** [comment]
could also use an iife so that the type is at the beginning of the export rather than the end

```js
export default ((): MyType => ({
  k: v
})();
```

**Comment by ackvf** [comment]
While this gives me type hints inside the function (thanks @mccallofthewild )
```
export default (({ withIcon, children }) => {
  return <SomeJSX withIcon={withIcon}>{children}</SomeJSX>
} as React.FC<{withIcon: boolean}>
```
I would still prefer to have the type declared up front _(not sure about the syntax here though)_
```
export default: React.FC<{withIcon: boolean}> (({ withIcon, children }) => {
  return <SomeJSX withIcon={withIcon}>{children}</SomeJSX>
}
```

**Comment by LongTengDao** [comment]
Maybe `export const default :Type = value;` `export type default = Type;` could bring us more uniformity, avoid to introduce a new set of grammars just for default?

**Comment by soullivaneuh** [comment]
The solution proposed by @IgorGee but is not fully reliable for type checking.

My default export is a `ResourceProps` where the property `name` is required.

If I try with a typed constant (the actual only solution):

```typescript
const resourceProps: ResourceProps = {};
export default resourceProps;
```

I will have:

```
Property 'name' is missing in type '{}' but required in type 'ResourceProps'.  TS2741
```

But nothing if I do it like this:

```typescript
export default {} as ResourceProps;
```

This make things harder to debug if something goes wrong because of this missing property. And we are using Typescript for that, right? :-)

However, I also understand the need to type the default export. On some cases, we just return a configuration object like that:

```typescript
const resourceProps: ResourceProps = {
  name:"users",
  icon: UserIcon,
  list: UserList,
  create: UserCreate,
  edit: UserEdit,
  options:{
    label: 'Utilisateurs',
  },
};

export default resourceProps;
```

It's a bit cumbersome to be forced to declare a new variable just to take benefit of typing.

That was my two cents. I wanted to illustrate with some samples because I was myself a bit confused as a TypeScript beginner when I saw the lot of down votes on the previous solutions.

**Comment by francois-gsk** [comment]
what about:
```
export default <MyType>{
  prop: 'value',
};
```
?

**Comment by bingtsingw** [comment]
> what about:
> 
> ```
> export default <MyType>{
>   prop: 'value',
> };
> ```
> 
> ?

Great way, works for me, save me some typing

**Comment by zaverden** [comment]
> what about:
> 
> ```
> export default <MyType>{
>   prop: 'value',
> };
> ```
> 
> ?

```
interface MyType {
  prop: string;
  prop2: string;
}

const toExport: MyType = {
  prop: "value",
}

export default <MyType>{
  prop: "value",
};
```
in this example TS fails on toExport variable (`Property 'prop2' is missing...`) and passes on `export default <MyType>{...}`, but should fail too

**Comment by richard-ejem** [comment]
> what about:
> 
> ```
> export default <MyType>{
>   prop: 'value',
> };
> ```
> 
> ?

It is not a type declaration but a type assertion.
In other words, literally the same as `as MyType`, just another syntax. It was already discussed and discouraged here.

**Comment by francois-gsk** [comment]
@richard-ejem I fully disagree, it's not a type assertion at all!

```
interface MyType {
  hello: string;
}

export default <MyType>{ hello: false }; // 👉 Type Error

export default <MyType>{ hello: 'world!' }; // 👉 Type Checked
```

**Comment by francois-gsk** [comment]
@zaverden that's indeed strange… It looks like an in-between check

**Comment by richard-ejem** [comment]
> @richard-ejem I fully disagree, it's not a type assertion:
> 
> ```
> interface MyType {
>   hello: string;
> }
> 
> export default <MyType>{ hello: false }; // 👉 Type Error
> 
> export default <MyType>{ hello: 'world!' }; // 👉 Type Checked
> ```

Yes, it is an assertion, replace it with `as` and you get the same result.
```
interface MyType {
  hello: string;
}

export default { hello: false } as MyType; // 👉 Type Error

export default { hello: 'world!' } as MyType; // 👉 Type Checked
```

The type error is there because assertions between completely incompatible types are illegal, please read the TS error message you get.

see https://www.tutorialsteacher.com/typescript/type-assertion , `<TYPE>` is old syntax for assertions, now rarely used because its syntax conflicts with JSX.

**Comment by francois-gsk** [comment]
@richard-ejem Yes, I edited my initial comment to reflect that it's not a valid notation 😉 Thanks.

**Comment by a-tarasyuk** [comment]
I think using semantics `export default: Type Expression` might add some restrictions, for instance, array definition with spaces between type and `[]`. Using spaces between type and `[]` is allowed to define array type 

```ts
const a: number         [];
```

How this case should be handled in `export default`? Should spaces between type and `[]` be forbidden? For the following example I expect an error that `array` is not assignable to `number`;
```ts
export default: number [];
```

--- 

It seems that the main concern with using the `as` operator is that it simply casts to a type without checking for type compatibility.

There is a draft proposal for adding the new `satisfies` operator that might fix this issue - https://github.com/microsoft/TypeScript/pull/46827. 

It allows checking type like so

```ts
interface Foo {
  a: number;
}
export default {} satisfies Foo; 
                            ^^^
Type '{}' does not satisfy the expected type 'Foo'.
  Property 'a' is missing in type '{}' but required in type 'Foo'.(1360)
```

[Example](https://www.staging-typescript.org/play?ts=4.6.0-pr-46827-10#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHJwBcyIArgLYBG0A3LgL664QAeADulGMgCYR45ADa9sjZAGc4YYJJjAIktJjpA) 

@RyanCavanaugh @DanielRosenwasser What do you think? Can we add this case to https://github.com/microsoft/TypeScript/pull/46827 proposal?

**Comment by mohsen1** [comment]
@a-tarasyuk I don't think syntax is ambiguous. 

```ts
export default: number[]
// same as 
type Default = number[];
export default Default;
```  

```ts
export default: number[] = []
// same as 
const Default: number = [];
export default Default;
```
```

**Comment by jchook** [comment]
Another wacky suggestion, maybe allow `const default = ...` 😝

```typescript
export const default: MyType = {}
```

**Comment by shtse8** [comment]
I am confusing about this too. any suggestion about typing the default export function?

**Comment by dobesv** [comment]
The use case I'm looking at for this is to type and name a function that's a default export, without repeating the function name:

```
export interface MyComponentProps {
   yes: boolean;
}
export default function MyComponent(props) {

} satisfies SFC<MyComponentProps>;
```

**Comment by jchook** [comment]
@ackvf's syntax [suggestion](https://github.com/microsoft/TypeScript/issues/13626#issuecomment-605458082) seems like the best proposed so far.

> ```ts
> export default: React.FC<{withIcon: boolean}> (({ withIcon, children }) => {
>   return <SomeJSX withIcon={withIcon}>{children}</SomeJSX>
> })
> ```

Would that be difficult to implement?

```ts
export default: {type} {value}
```

**Comment by dobesv** [comment]
I guess another option could be to allow "default" as a variable name.

`export function default (...)`
`export const default: Type = function (...)`

**Comment by NikolaRHristov** [comment]
This is type checked

```ts
import type { Config } from "package";

export default (): Config => {
	return {
		properties: true
	};
};
```

**Comment by soullivaneuh** [comment]
@NikolaRHristov Yes, but this works only if you export a function, you are typing its return type.

**Comment by NikolaRHristov** [comment]
I need to have a typed default export, so yeah I'm exporting a function. @soullivaneuh

**Comment by NikolaRHristov** [comment]
Also, I'm returning an object, so everything's fine.

**Comment by NikolaRHristov** [comment]
@soullivaneuh Actually, TypeScript does this by default. Here's a compiled version of a similar object.

```ts
import type { BuildOptions } from "esbuild";
declare const _default: () => BuildOptions;
export default _default;
```

**Comment by sidvishnoi** [comment]
@dobesv https://github.com/microsoft/TypeScript/issues/13626#issuecomment-1409060244


```ts
type RequestHandler = (req: string, res: number) => string;

export default ((req, res) => {
   return 1;
}) as RequestHandler;
// Conversion of type '(req: string, res: number) => number' to type 'RequestHandler' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
//   Type 'number' is not comparable to type 'string'.(2352)
// and the whole block is highlighted as error.

export default ((req, res) => {
   return 1;
}) satisfies RequestHandler;
// Type '(req: string, res: number) => number' does not satisfy the expected type 'RequestHandler'.
//  Type 'number' is not assignable to type 'string'.(1360)
// but "RequestHandler" is highlighted as error (I would expect the return value to be highlighted).
```

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAShCOBXCBnYAJAhgOwCYBsIAnKAXigAoiEAuKNIgS2wHMAaKalO7RAWwBGxAJRkAfPWBNWAbgBQciAA8wAeyLAouCADNMifJopUEHLqNISA3nKh3qwREWxQAjPIC+olJmCMUOoyosAjIaFh4hETycgD0sVDKahpauvqGlCbwZqgW1nEJdpwQjs5u8vFQXlCYKCFIqBg4BMQxSeqaAMaq2GhQOqqqdHAN4c1RZJnU2cUoeVA2RQ5OLu5yXvJAA)

**Comment by mon-jai** [comment]
@Sid Vishnoi It works on function declarations too.

```ts
export default (function (req, res)  {
   return 1;
}) satisfies RequestHandler;
```

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAShCOBXCBnYAJAhgOwCYBsIAnKAXigAoiEAuKNIgS2wHMAaKalO7RAWwBGxAJRkAfPWBNWAbgBQciAA8wAeyLAouCADNMifJoo7E2AMbBGq7JWrwOXUVADecqO+rBERGwEZ5AL6iKJiWKDqMqLAIyGhYeIRE8nIA9ClQymoaWrr6hpRUCA6ooqQSrmnuHhBePlD+qelBUJgo0UioGDgExMmZ6ppm1mhQOqqqdHAdcd2JZAV2xSil5W7VtX6BwvJAA)

**Comment by dragomirtitian** [comment]
Just want to point out that using both `as` and `satisfies` might actually be the best solution here until we get actual syntax. `satisfies` checks that the value conforms to the type, `as` forces the type instead of allowing TS infer its own type

```ts
type Union = { v: 1 | 2 }
export default { v: 1 } satisfies Union as Union; // Checked against Union and Union is preserved as the type of the export.
```
[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgdgSwPZygXigbygNwFxQCMUAPlAExQC+AsAFAQAeYSATsFACYQBmAhgFcANh2z4i1KAGc+wBFJ4IIU2IhRQ+K+MjgBuKEA)

**Comment by rampion** [comment]
Another workaround is to pass the export value to an identity function to check its value:

```typescript
function verify<T>(t: T): T { return t }

export default verify<React.FC<IProps>>(function(props) {
  // ...
})
```

I'm not sure if there's a canonical identity function that'd avoid introducing your own.

**Comment by dobesv** [comment]
> satisfies is a type assertion. It does not type the variable

Oh, too bad.  I thought an earlier commenter said that it did type it.  We haven't upgraded to the version of typescript with this yet, but this was one thing I was looking forward to.

**Comment by mccallofthewild** [comment]
You can also declare a typed variable and assign it in your export. 

```typescript 
type Union = { v: 1 | 2 };

let d: Union;

export default d = {
  v: 1,
};
```

**Comment by mon-jai** [comment]
@mccallofthewild Then it could be reassigned.

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh What are your thoughts on including this issue in the **`[Feature Updates]`** discussion list?

**Comment by mccallofthewild** [comment]
@mon-jai No. 😁 That's not how assignment works. 

```typescript
let a;
let b = a = 1;
a = 2;
console.log(b == a);
// `false`
```

**Comment by mon-jai** [comment]
Shouldn't the following code work?

```js
// d.js
let d: number;
export default d = 1:

// Other files
import d from "d.js";
d = 2;
```

**Comment by MacroMan** [comment]
`satisfies T as T` doesn't reduce boilerplate in all circumstances. eg using a type from a value doesn't work at all:
```
export default {some:'value'} satisfies SomeType<typeof SomeValue> as SomeType<typeof SomeValue>
```
and even if it did work, I'm repeating my type declaration twice.

Doing `export default: SomeType<typeof SomeValue> {some:'value'}` would be great for reducing boilerplate

**Comment by nandorojo** [comment]
I'm using the new `satisfies` in our case.

```tsx
import * as webpack from 'webpack';

export default {

} satisfies webpack.Configuration
```

[Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAKjgQwM5wO4FMBGZkDGA1nAGZQQhwDk2ehR1A3AFAtYAekscAJlqWQBXADbwA3izhwWAXzipkMYKlLAs6OvmIA6AMIQAdmoDmQqEuBGgA)

**Comment by MrBns** [comment]
from  2017 -> 2024... Still this issue is open. wow.

**Comment by a-tarasyuk** [comment]
@MrBns Some time ago, @RyanCavanaugh proposed an initiative to deal with persistent issues - https://github.com/microsoft/TypeScript/issues/54923. You might want to ask @RyanCavanaugh to add this issue to the list for upcoming discussions.

**Comment by saltman424** [comment]
@a-tarasyuk unfortunately, in the announcement of that initiative they include:
> ### Requesting Feature Updates
> For the foreseeable future, we'll be working off the "most-upvoted" suggestion list. Please don't post comments in issues or iteration plans asking for feature updates. Once the top suggestions have been cleared out, we might change this policy, possibly by having a survey or something.

I don't see anything indicating that has changed, but it's possible I missed it

With that being said, if this issue is considered for a Feature Update, whoever is considering it, please note that https://github.com/microsoft/TypeScript/issues/56235#issuecomment-2025651824 (`export default ... satisfies as T`) is a possible solution to this issue and many others

**Comment by jklnakdsjnfw4124** [comment]
Use casting with `<>`:

```typescript
import * as webpack from 'webpack';

export default <webpack.Configuration> {};
```

In my case, the types are safe.

**Comment by rampion** [comment]
@eevloeev [this approach was discussed previously](https://github.com/microsoft/TypeScript/issues/13626#issuecomment-972514158) and dismissed as being equivalent to casting.
