### ISSUE TITLE
"Debug Failure. False expression:" when destructuring

### ISSUE THREAD

**Issue by gcanti** [Microsoft/TypeScript#13864]
**TypeScript Version:**  2.1.5

**Code**

```ts
const o = {
  f: ({ ['a']: b }) => b
}
```

**Expected behavior:**

No error.

**Actual behavior:**

```
node_modules/typescript/lib/tsc.js:50061
                throw e;
                ^

Error: Debug Failure. False expression: 
    at Object.assert (node_modules/typescript/lib/tsc.js:1796:23)
    at visitObjectLiteralExpression (node_modules/typescript/lib/tsc.js:41279:22)
    at visitJavaScript (node_modules/typescript/lib/tsc.js:40474:28)
    at visitorWorker (node_modules/typescript/lib/tsc.js:40398:24)
    at dispatcher (node_modules/typescript/lib/tsc.js:40319:19)
    at saveStateAndInvoke (node_modules/typescript/lib/tsc.js:40337:27)
    at visitor (node_modules/typescript/lib/tsc.js:40314:20)
    at visitNode (node_modules/typescript/lib/tsc.js:36996:23)
    at Object.visitEachChild (node_modules/typescript/lib/tsc.js:37219:160)
    at visitVariableDeclaration (node_modules/typescript/lib/tsc.js:41166:23)
```

**Comment by RyanCavanaugh** [comment]
Can't repro in master. Can you try with `typescript@next` to confirm?

**Comment by gcanti** [comment]
With `typescript@next` works as expected, thanks for the quick response
