### ISSUE TITLE
TSServer References Exception for Exported Default Class

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#14103]
TS Version: 2.2.1-insiders.20170209

```ts
export default class Xyz { 
     
}
```

Execute `references` at position `22` in the file

**Expected**
```
[Trace - 4:52:08 PM] Sending request: references (14). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/bar.ts",
    "line": 1,
    "offset": 22
}
[Trace - 4:52:08 PM] Response received: references (14). Request took 81 ms. Success: true 
Result: {
    "refs": [
        {
            "file": "/Users/matb/projects/sand/bar.ts",
            "start": {
                "line": 1,
                "offset": 22
            },
            "lineText": "export default class Xyz { ",
            "end": {
                "line": 1,
                "offset": 25
            },
            "isWriteAccess": true,
            "isDefinition": true
        }
    ],
    "symbolName": "Xyz",
    "symbolStartOffset": 22,
    "symbolDisplayString": "class Xyz"
}
```

**Actual**
```
[Trace - 4:52:33 PM] Sending request: references (31). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/bar.ts",
    "line": 1,
    "offset": 22
}
[Trace - 4:52:33 PM] Response received: references (31). Request took 20 ms. Success: false . Message: Error processing request. Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at Object.getSymbolAtLocation (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:35547:21)
    at getDefaultImportName (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:57428:80)
    at getReferencedSymbolsForNode (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:57370:51)
    at Object.findReferencedSymbols (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:57324:20)
    at findReferencedSymbols (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:65846:41)
    at Object.getReferencesAtPosition (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:65837:37)
    at /Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:70784:71
    at /Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:68882:105
    at Array.reduce (native)
    at Object.combineProjectOutput (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:68882:35)
```

**Comment by mjbvz** [comment]
This impacts the references code lens feature in VSCode and is a regression from TypeScript 2.1.x

//cc @mhegazy

**Comment by mhegazy** [comment]
@andy-ms can you take a look.
