### ISSUE TITLE
Error thrown when providing only transformers to emit()

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#14176]
**TypeScript Version:**   2.3.0-dev.20170218

**Code**

**`example.ts`**
```ts
var a = 1;
console.log(a);
```

**`compiler.ts`**
```ts
// Code is mostly from https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API
import * as ts from "typescript";

const transformers: ts.CustomTransformers = {
    before: [
        (context) => (node) =>  {
            function visitor(node: ts.Node) {
                console.log({node});
                ts.forEachChild(node, visitor);
                return node;
            }
            ts.forEachChild(node, visitor);
            return node;
        }
    ]
}

function compile(fileNames: string[], options: ts.CompilerOptions): void {
    let program = ts.createProgram(fileNames, options);
    let emitResult = program.emit(null, null, null, null, transformers);
    // let emitResult = program.emit();

    let allDiagnostics = ts.getPreEmitDiagnostics(program).concat(emitResult.diagnostics);

    allDiagnostics.forEach(diagnostic => {
        let { line, character } = diagnostic.file.getLineAndCharacterOfPosition(diagnostic.start);
        let message = ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n');
        console.log(`${diagnostic.file.fileName} (${line + 1},${character + 1}): ${message}`);
    });

    let exitCode = emitResult.emitSkipped ? 1 : 0;
    console.log(`Process exiting with code '${exitCode}'.`);
    process.exit(exitCode);
}

compile(process.argv.slice(2), {
    noEmitOnError: true,
    noImplicitAny: true,
    target: ts.ScriptTarget.ES5,
    module: ts.ModuleKind.CommonJS
});
```

**Error**

```
TypeScript version 2.3.0-dev.20170218

./node_modules/typescript/lib/typescript.js:7155
        return file.isDeclarationFile;
                   ^
TypeError: Cannot read property 'isDeclarationFile' of null
    at isDeclarationFile (./node_modules/typescript/lib/typescript.js:7155:20)
    at sourceFileMayBeEmitted (./node_modules/typescript/lib/typescript.js:9041:86)
    at ./node_modules/typescript/lib/typescript.js:9035:74
    at Object.filter (./node_modules/typescript/lib/typescript.js:1531:31)
    at Object.getSourceFilesToEmit (./node_modules/typescript/lib/typescript.js:9035:23)
    at Object.emitFiles (./node_modules/typescript/lib/typescript.js:62545:30)
    at emitWorker (./node_modules/typescript/lib/typescript.js:65724:33)
    at ./node_modules/typescript/lib/typescript.js:65686:66
    at runWithCancellationToken (./node_modules/typescript/lib/typescript.js:65777:24)
    at Object.emit (./node_modules/typescript/lib/typescript.js:65686:20)
````

**Comment by mohsen1** [comment]
This is still happening at `2.3.0-dev.20170226`. 

@rbuckton am I doing something wrong? What's the simplest way of using the new transformers API?

**Comment by mohsen1** [comment]
ok I figured. I need to pass `undefined` instead of `null` for not providing options to `emit`.

**Comment by basarat** [comment]
> . I need to pass undefined instead of null for not providing options to emit.

Always `undefined` https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined :rose:
