### ISSUE TITLE
TSServer Exception in tryAddSignature on definition request

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#14299]
Discovered while investigating https://github.com/Microsoft/vscode/issues/21356

**TypeScript Version:**  2.2.1

**Code**
In the JavaScript:

```js
import { observer } from 'mobx-react';

observer()
```

Trigger go to definition on `observer ` in `observer()`

**Bug**

```
[Trace - 12:40:26 PM] Sending request: definition (12). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/config.js",
    "line": 3,
    "offset": 5
}
[Trace - 12:40:26 PM] Response received: definition (12). Request took 2 ms. Success: false . Message: Error processing request. Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at tryAddSignature (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:60129:111)
    at tryAddCallSignature (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:60122:28)
    at getDefinitionFromSymbol (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:60100:18)
    at Object.getDefinitionAtPosition (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:60064:20)
    at Object.getDefinitionAtPosition (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:67552:38)
    at IOSession.Session.getDefinition (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:72472:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:72051:61)
    at /Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:73305:88
    at IOSession.Session.executeWithRequestId (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:73296:28)
    at IOSession.Session.executeCommand (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:73305:33)```

**Comment by mjbvz** [comment]
This seems like a regression from TS 2.1.6
