### ISSUE TITLE
Maximum call stack size exceeded for getTypeAtFlowNode in Large File

### ISSUE THREAD

**Issue by mattbierner** [Microsoft/TypeScript#14314]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**
Discovered while trying to work around https://github.com/facebook/react-native/issues/12590

For a large TS file that looks like:

```ts
const data = {} as any

data["a"] = "AH0";
data["a(1)"] = "EY1";
data["a's"] = "EY1 Z";
data["a."] = "EY1";
data["a.'s"] = "EY1 Z";
data["a.s"] = "EY1 Z";
... 100,000 + lines
```

Compile the file on its own with `tsc`

Here's the complete file: https://gist.githubusercontent.com/mattbierner/34dbc249be0ebddedcc275d0ff40281b/raw/985dbbfba9a5db89f9cea618ce3c885ccc46ef8b/cmu.js

**Bug**

```
/XXX/node_modules/typescript/lib/tsc.js:51296
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at isMatchingReference (/XXX/node_modules/typescript/lib/tsc.js:27613:37)
    at getTypeAtFlowAssignment (/XXX/node_modules/typescript/lib/tsc.js:28150:21)
    at getTypeAtFlowNode (/XXX/node_modules/typescript/lib/tsc.js:28101:32)
    at getTypeAtFlowArrayMutation (/XXX/node_modules/typescript/lib/tsc.js:28178:36)
    at getTypeAtFlowNode (/XXX/node_modules/typescript/lib/tsc.js:28123:32)
    at getTypeAtFlowArrayMutation (/XXX/node_modules/typescript/lib/tsc.js:28178:36)
    at getTypeAtFlowNode (/XXX/node_modules/typescript/lib/tsc.js:28123:32)
    at getTypeAtFlowArrayMutation (/XXX/node_modules/typescript/lib/tsc.js:28178:36)
    at getTypeAtFlowNode (/XXX/node_modules/typescript/lib/tsc.js:28123:32)
    at getTypeAtFlowArrayMutation (/XXX/node_modules/typescript/lib/tsc.js:28178:36)
```

**Comment by mhegazy** [comment]
Every statement is considered a "narrowing" expression, and that triggers more analysis, if the compiler goes far enough in the statement list, it runs out of stack space. 

have you considered writing it as an object literal?

```ts

const data = {
    "a": "AH0",
    "a(1)": "EY1",
    "a's": "EY1 Z",
    "a.": "EY1",
    "a.'s": "EY1 Z",
    "a.s": "EY1 Z",
    ...
}
```

or adding a type annotation with an index signature, e.g. `: { [x:string}: string }`

**Comment by mjbvz** [comment]
Thanks @mhegazy. I actually started with a json object but ran into some problems with react-native, which is why I tried to convert it to this format. Obviously the code is not terribly practical, but I also wasn't trying to break typescript or anything when doing this. 

Adding an index signiture like so:

```
const data: { [index: string]: string} = {}
...
```

Does not fix things. I still see exceptions such as:

```
Error - 8:57:45 PM] 'quickinfo' request failed with error.
Error processing request. Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Object.isBindingPattern (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:8117:30)
    at walkUpBindingElementsAndPatterns (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:8700:49)
    at Object.getCombinedNodeFlags (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:8722:16)
    at Object.isBlockOrCatchScoped (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:5394:20)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:21992:88
    at Object.forEach (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:1220:30)
    at checkResolvedBlockScopedVariable (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:21992:34)
    at resolveName (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:21909:25)
    at getResolvedSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:28697:67)
    at isMatchingReference (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:28743:80)
```

and 

```
[Error - 8:58:14 PM] 'completions' request failed with error.
Error processing request. Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Object.isBindingPattern (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:8117:30)
    at walkUpBindingElementsAndPatterns (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:8700:49)
    at Object.getCombinedNodeFlags (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:8722:16)
    at Object.isBlockOrCatchScoped (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:5394:20)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:21992:88
    at Object.forEach (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:1220:30)
    at checkResolvedBlockScopedVariable (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:21992:34)
    at resolveName (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:21909:25)
    at getResolvedSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:28697:67)
    at isMatchingReference (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:28743:80)
```

**Comment by atifsyedali** [comment]
This is particularly problematic because it tends to break long locale files in large projects.

**Comment by endel** [comment]
Still occurring on `typescript@2.4.2`. 

As @atifsyedali said, this is quite problematic. I'm working with legacy code that has +5000 lines of assignments to a dictionary.

```
/XXX/node_modules/typescript/lib/tsc.js:55776
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at isMatchingReference (/XXX/node_modules/typescript/lib/tsc.js:30445:37)
    at isMatchingReference (/XXX/node_modules/typescript/lib/tsc.js:30458:25)
    at getTypeAtFlowArrayMutation (/XXX/node_modules/typescript/lib/tsc.js:31030:21)
    at getTypeAtFlowNode (/XXX/node_modules/typescript/lib/tsc.js:30976:32)
    at getTypeAtFlowArrayMutation (/XXX/node_modules/typescript/lib/tsc.js:31031:36)
    at getTypeAtFlowNode (/XXX/node_modules/typescript/lib/tsc.js:30976:32)
    at getTypeAtFlowArrayMutation (/XXX/node_modules/typescript/lib/tsc.js:31031:36)
    at getTypeAtFlowNode (/XXX/node_modules/typescript/lib/tsc.js:30976:32)
    at getTypeAtFlowArrayMutation (/XXX/node_modules/typescript/lib/tsc.js:31031:36)
    at getTypeAtFlowNode (/XXX/node_modules/typescript/lib/tsc.js:30976:32)
```

**Comment by endel** [comment]
As a workaround, I'm using arrays and assigning later to the dictionary:

```typescript
let dict: any = {};

let values = [
  ["key", "value"],
  ["key", "value"],
  // ... 5000+ entries
];

for (let i=0; i<values.length; i++) {
  dict[ values[i][0] ] = values[i][1];
}
```
