### ISSUE TITLE
Maximum call stack size exceeded on complex typing

### ISSUE THREAD

**Issue by ajeffrey** [Microsoft/TypeScript#14458]
**TypeScript Version:** 2.2.1, also nightly (2.3.0-dev.20170303)

**Code**

I've pared down the code a lot from what it originally was, but beyond this point it's hard to find what to take out without fixing the bug:

```ts
export interface Schema {
  [key: string]: any;
};

export interface SchemaMap {
  [key: string]: Schema;
};

export interface IModel<S extends Schema> {
   get<K extends keyof S>(key: K): S[K];
};

export interface ICollection<S extends Schema, M extends IModel<S>> {
  all: M[];
  length: number;
  filter(filter: (item: M) => boolean): M[];
};

export type IModelCtor<S extends Schema, M extends IModel<S>> = {
  new(data: S, dependencies: IModelDependencies<S>): M;
  prototype: M;
};

export interface ICollectionCtor<S extends Schema, M extends IModel<S>, C extends ICollection<S, M>> {
  new (data: S[]): C;
  prototype: C;
};

export interface IModelFactory<S extends Schema, M> {
  (data: S): M;
};

export type IModelDependencies<S extends Schema> = {
  [K in keyof S]?: IModel<S>|ICollection<S, any>;
};

export type ModelMap<S extends SchemaMap> = {
  [K in keyof S]: IModelCtor<S[K], IModel<S[K]>>;
};

export type CollectionMap<S extends SchemaMap> = {
  [K in keyof S]?: ICollectionCtor<S[K], IModel<S[K]>, ICollection<S[K], IModel<S[K]>>>;
};

export type CollectionData<S extends SchemaMap> = {
  [key: string]: Array<S[any]>;
};

export type CollectionType<S extends SchemaMap, CD extends CollectionData<S>> = {
  [K in keyof CD]: keyof S;
};

export type CollectionSchema<S extends SchemaMap, CD extends CollectionData<S>> = {
  data: CD;
  types: CollectionType<S, CD>;
};

export type CollectionRuntime
<S extends SchemaMap, CM extends CollectionMap<S>, CD extends CollectionData<S>, CT extends CollectionType<S, CD>> = {
  [K in keyof CD]: CM[CT[K]]['prototype'];
};

export type Mapped<T, U> = {
  [K in keyof T]: U;
};

function ObjectMap<T, U>(data: T, fn: <K extends keyof T>(val: T[K]) => U): Mapped<T, U> {
  const mappedData = Object.keys(data).map(<K extends keyof T>(key: K) => [key as string, fn<K>(data[key])] as [string, U]);
  return mappedData.reduce((prev, [key, val]) => Object.assign(prev, {[key]: val}), {}) as Mapped<T, U>;
};

export class test<S extends SchemaMap, MM extends ModelMap<S>, CM extends CollectionMap<S>> {
  private _models: MM;
  private _collections: CM|null;

  constructor({
    models,
    collections,
  }: {models: MM, collections?: CM}) {
    this._models = models;
    this._collections = collections || null;
  }

  compile<
    CD extends CollectionData<S>,
    CS extends CollectionSchema<S, CD>
  >(collection_schema?: CS) {
    const collections = collection_schema ? this.compileCollections(collection_schema.data, collection_schema.types): null;
    return collections;
  }

  private compileCollections
  <CD extends CollectionData<S>, CT extends CollectionType<S, CD>>
  (data: CD, types: CT): CollectionRuntime<S, CM, CD, CT> {
    return ObjectMap<CD, CollectionRuntime<S, CM, CD, CT>[any]>(data, <K extends keyof CD>(key: K): CM[CT[K]]['prototype'] => {
      const type: keyof S = types[key];
      const datum = data[key];
      return new this._collections[type](datum);
    });
  }

};
```

**Expected behavior:**
compiles correctly (or doesn't, as long as the compilation actually proceeds to the finish).

**Actual behavior:**

(copied from the nightly build's execution run):

```
               throw e;
                ^

RangeError: Maximum call stack size exceeded
    at isSimpleTypeRelatedTo (/Users/alexjeffrey/.nvm/versions/node/v5.8.0/lib/node_modules/typescript/lib/tsc.js:26482:39)
    at isRelatedTo (/Users/alexjeffrey/.nvm/versions/node/v5.8.0/lib/node_modules/typescript/lib/tsc.js:26628:21)
    at isRelatedTo (/Users/alexjeffrey/.nvm/versions/node/v5.8.0/lib/node_modules/typescript/lib/tsc.js:26733:38)
    at isRelatedTo (/Users/alexjeffrey/.nvm/versions/node/v5.8.0/lib/node_modules/typescript/lib/tsc.js:26700:38)
    at typeArgumentsRelatedTo (/Users/alexjeffrey/.nvm/versions/node/v5.8.0/lib/node_modules/typescript/lib/tsc.js:26939:35)
    at isRelatedTo (/Users/alexjeffrey/.nvm/versions/node/v5.8.0/lib/node_modules/typescript/lib/tsc.js:26741:38)
    at isRelatedTo (/Users/alexjeffrey/.nvm/versions/node/v5.8.0/lib/node_modules/typescript/lib/tsc.js:26733:38)
    at isRelatedTo (/Users/alexjeffrey/.nvm/versions/node/v5.8.0/lib/node_modules/typescript/lib/tsc.js:26700:38)
    at typeArgumentsRelatedTo (/Users/alexjeffrey/.nvm/versions/node/v5.8.0/lib/node_modules/typescript/lib/tsc.js:26939:35)
    at isRelatedTo (/Users/alexjeffrey/.nvm/versions/node/v5.8.0/lib/node_modules/typescript/lib/tsc.js:26741:38)
```

**Comment by ajeffrey** [comment]
If I take out compileCollections(), then tsc will run successfully, so I believe that the issue is related to the CollectionRuntime type.

**Comment by sandersn** [comment]
I got this to repro but needed `"noImplicitAny": true, "strictNullChecks": false`

**Comment by sandersn** [comment]
Actually, now that I pulled from master again, it no longer repros. #14723 was recently fixed and looks a lot like this issue. Can you try again tomorrow (6 April) with `typescript@next`?

**Comment by ajeffrey** [comment]
sure thing, I'll take a look - thanks

**Comment by mhegazy** [comment]
@ajeffrey any updates on this issue?

**Comment by ajeffrey** [comment]
@mhegazy the issue appears to be solved, thanks

**Comment by mhegazy** [comment]
thanks!
