### ISSUE TITLE
Running `tsc -w -p .` with TSC_NONPOLLING_WATCHER = true leads to an fs.watch error

### ISSUE THREAD

**Issue by Que3216** [Microsoft/TypeScript#14559]
**TypeScript Version:**  2.2.1.

Tried with Node v6.0.0 and Node v7.7.2.

**Code**

Create a directory called "my-project" with two files:

tsconfig.json containing "{}"
index.ts containing "console.log('Hello');"

Run `tsc -p .`. It'll execute correctly.

Run `TSC_NONPOLLING_WATCHER=true tsc -p . -w`, and it'll give the error:

```
fs.js:1425
    throw error;
    ^

Error: watch  ENOENT
    at exports._errnoException (util.js:896:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at addDirWatcher (/usr/local/lib/node_modules/typescript/lib/tsc.js:2197:35)
    at Object.addFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:2207:21)
    at Object.nodeSystem.watchFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:2348:60)
    at Object.executeCommandLine (/usr/local/lib/node_modules/typescript/lib/tsc.js:53351:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsc.js:53712:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

Run `cd .. && TSC_NONPOLLING_WATCHER=true tsc -p ./my-project -w`, and the watch will run fine.

The problem seems to be that the function:

```
function addFile(fileName, callback) {
                    addFileWatcherCallback(fileName, callback);
                    addDirWatcher(ts.getDirectoryPath(fileName));
                    return { fileName: fileName, callback: callback };
                }
```

Is called with the fileName "tsconfig.json".

This in term calls addDirWatcher with "", which calls fs.watch with "", which throws the error.

**Comment by Que3216** [comment]
May be duplicate of https://github.com/Microsoft/TypeScript/issues/5913

**Comment by mhegazy** [comment]
PRs welcomed
