### ISSUE TITLE
TSServer Error for quickInfo on invalid namespace export

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#14574]
TS 2.2.1

```ts
namespace X {
    export =
}
X.add
```

Send a `quickInfo` request for `add`:

```
[Trace - 10:46:05 PM] Sending request: quickinfo (527). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/x.ts",
    "line": 4,
    "offset": 5
}
[Trace - 10:46:05 PM] Response received: quickinfo (527). Request took 2 ms. Success: false . Message: Error processing request. Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at getNamedMembers (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:22476:20)
    at setStructuredTypeMembers (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:22489:31)
    at resolveAnonymousTypeMembers (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:24891:17)
    at resolveStructuredTypeMembers (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:24989:25)
    at getPropertyOfType (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:25204:32)
    at checkPropertyAccessExpressionOrQualifiedName (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:31274:24)
    at checkPropertyAccessExpression (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:31224:20)
    at getSymbolOfEntityNameOrPropertyAccessExpression (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:36811:25)
    at Object.getSymbolAtLocation (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:36866:28)
    at Object.getQuickInfoAtPosition (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:67519:38)
[Error - 10:46:05 PM] 'quickinfo' request failed with error.
```

I also see this error for `references` on `add`: 

```
Trace - 10:47:46 PM] Sending request: references (531). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sany/x.ts",
    "line": 4,
    "offset": 5
}
[Trace - 10:47:46 PM] Response received: references (531). Request took 1 ms. Success: false . Message: Error processing request. Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at getNamedMembers (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:22476:20)
    at setStructuredTypeMembers (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:22489:31)
    at resolveAnonymousTypeMembers (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:24891:17)
    at resolveStructuredTypeMembers (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:24989:25)
    at getPropertyOfType (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:25204:32)
    at checkPropertyAccessExpressionOrQualifiedName (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:31274:24)
    at checkPropertyAccessExpression (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:31224:20)
    at getSymbolOfEntityNameOrPropertyAccessExpression (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:36811:25)
    at Object.getSymbolAtLocation (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:36866:28)
    at Object.getQuickInfoAtPosition (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:67519:38)
[Error - 10:47:46 PM] 'references' request failed with error.
```

**Comment by weswigham** [comment]
I've added a test for this to our regression suite, as it no longer seems to repro on master.
