### ISSUE TITLE
Using the compiler API - typescript module experiences internal error

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#14722]
On TS 2.2.1

I am following the instructions here:
https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API

I am getting this error which is occurring within the TS source:

```
alexamil$ ./dev-server2.js 
/Users/alexamil/WebstormProjects/oresoftware/speedy-tsc/node_modules/typescript/lib/typescript.js:24044
                var resolvedFileName = result.resolvedModule && result.resolvedModule.resolvedFileName;
                                             ^

TypeError: Cannot read property 'resolvedModule' of undefined
    at Object.set (/Users/alexamil/WebstormProjects/oresoftware/speedy-tsc/node_modules/typescript/lib/typescript.js:24044:46)
    at Object.resolveModuleName (/Users/alexamil/WebstormProjects/oresoftware/speedy-tsc/node_modules/typescript/lib/typescript.js:24122:40)
    at loader_1 (/Users/alexamil/WebstormProjects/oresoftware/speedy-tsc/node_modules/typescript/lib/typescript.js:63903:78)
    at loadWithLocalCache (/Users/alexamil/WebstormProjects/oresoftware/speedy-tsc/node_modules/typescript/lib/typescript.js:63851:42)
    at resolveModuleNamesWorker (/Users/alexamil/WebstormProjects/oresoftware/speedy-tsc/node_modules/typescript/lib/typescript.js:63904:88)
    at resolveModuleNamesReusingOldState (/Users/alexamil/WebstormProjects/oresoftware/speedy-tsc/node_modules/typescript/lib/typescript.js:64018:24)
    at processImportedModules (/Users/alexamil/WebstormProjects/oresoftware/speedy-tsc/node_modules/typescript/lib/typescript.js:64869:35)
    at findSourceFile (/Users/alexamil/WebstormProjects/oresoftware/speedy-tsc/node_modules/typescript/lib/typescript.js:64779:17)
    at processSourceFile (/Users/alexamil/WebstormProjects/oresoftware/speedy-tsc/node_modules/typescript/lib/typescript.js:64682:27)
    at processRootFile (/Users/alexamil/WebstormProjects/oresoftware/speedy-tsc/node_modules/typescript/lib/typescript.js:64570:13)
```

also as an aside, why isn't there any error handling here:

```ts
/// <reference path="typings/node/node.d.ts" />

import * as ts from "typescript";

function compile(fileNames: string[], options: ts.CompilerOptions): void {
    let program = ts.createProgram(fileNames, options);
    let emitResult = program.emit();

    let allDiagnostics = ts.getPreEmitDiagnostics(program).concat(emitResult.diagnostics);

    allDiagnostics.forEach(diagnostic => {
        let { line, character } = diagnostic.file.getLineAndCharacterOfPosition(diagnostic.start);
        let message = ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n');
        console.log(`${diagnostic.file.fileName} (${line + 1},${character + 1}): ${message}`);
    });

    let exitCode = emitResult.emitSkipped ? 1 : 0;
    console.log(`Process exiting with code '${exitCode}'.`);
    process.exit(exitCode);
}

compile(process.argv.slice(2), {
    noEmitOnError: true, noImplicitAny: true,
    target: ts.ScriptTarget.ES5, module: ts.ModuleKind.CommonJS
});
```

in other words - why do I not see either a try / catch or an error-first callback in your example code?

thanks

**Comment by ORESoftware** [comment]
Seems like a bug within the typescript module, or perhaps the examples are outdated. It doesn't look like I am passing bad input, but if I were, it shouldn't crash like that.

**Comment by ORESoftware** [comment]
What I am trying to do: Normally tsc -w would be OK, but I need to hook into tsc -w to know when it starts transpiling and when it's done transpiling. I can do string matching on stdout from tsc -w but I am looking for something more robust, so was going to implement something myself.

**Comment by ORESoftware** [comment]
looking to bump this one, thanks

**Comment by RyanCavanaugh** [comment]
moduleNameResolver.ts line 458 needs to check if `result` isn't `undefined`

**Comment by mhegazy** [comment]
PRs appreciated.

**Comment by andy-ms** [comment]
Actually, `result` should always be defined. (We *really* need `--strictNullChecks`.) Both `nodeModuleNameResolver` and `classicNameResolver` seem to always define it, so there may have been a bad `moduleResolution`.

**Comment by ORESoftware** [comment]
Hey all, I am really looking for answers to this related questiion

https://github.com/Microsoft/TypeScript/issues/16602

any help appreciated

**Comment by andy-ms** [comment]
Hi @ORESoftware, can you still reproduce the original issue?

**Comment by ORESoftware** [comment]
@andy-ms let me try it again, I have tried to get this to work in a month - however if there were a solution to this:

https://github.com/Microsoft/TypeScript/issues/16602

then this issue would be obviated.

**Comment by andy-ms** [comment]
@ORESoftware friendly ping

**Comment by the1mills** [comment]
Give me two days, let me try to reproduce again, thanks

**Comment by the1mills** [comment]
I am OREsoftware döppelgãngêr

**Comment by andy-ms** [comment]
@ORESoftware ping

**Comment by ORESoftware** [comment]
ah yes, I haven't gotten to this, I probably won't anytime soon, can you keep open? if not pls close as needed

**Comment by mhegazy** [comment]
closing for house keeping purposes. please reopen if issue still exists.
