### ISSUE TITLE
[bug] TS 2.1.4 throws an exception while generating AMD module def from an invalid es6 import statement

### ISSUE THREAD

**Issue by loicraux** [Microsoft/TypeScript#14870]
**TypeScript Version:**  2.1.4

**tsconfig.json**
```json
{
  "compilerOptions": {
      "module": "amd",
      "sourceMap": true,
      "target": "ES5",
      "suppressExcessPropertyErrors": true,
      "noFallthroughCasesInSwitch": true,
      "jsx": "react",
      "declaration": true,
      "outDir": "dist"
  },
  "include": [ "src" ],
  "exclude": [
    "*/.bundle",
    "*/.sass-cache",
    "*/.tscache",
    "*/dist",
    "*/node_modules",
    "*/ruby_gems"
  ]
}
```

While migrating a large codebase from `import xyz = require('path/to/module/xyz');` import statements in favor of es6 import statements such as `import xyz from 'path/to/module/xyz';`, `import * as foo from 'path/to/module/baz';` or `import { a, b, c } from 'path/to/module/bar';`, TS compiler throws such a TypeError :
```
<project>\node_modules\typescript\lib\tsc.js:49700
                throw e;
                ^

TypeError: Cannot read property 'kind' of undefined
    at skipPartiallyEmittedExpressions (<project>\node_modules\typescript\lib\tsc.js:10608:20)
    at parenthesizeExpressionForList (<project>\node_modules\typescript\lib\tsc.js:10507:33)
    at parenthesizeListElements (<project>\node_modules\typescript\lib\tsc.js:10493:27)
    at Object.createArrayLiteral (<project>\node_modules\typescript\lib\tsc.js:8815:25)
    at transformAsynchronousModule (<project>\node_modules\typescript\lib\tsc.js:44221:24)
    at transformAMDModule (<project>\node_modules\typescript\lib\tsc.js:44211:20)
    at transformSourceFile (<project>\node_modules\typescript\lib\tsc.js:44189:27)
    at <project>\node_modules\typescript\lib\tsc.js:965:86
    at reduceLeft (<project>\node_modules\typescript\lib\tsc.js:710:30)
    at <project>\node_modules\typescript\lib\tsc.js:965:42
```
I added some `console.dir/log` statement to `tsc.js` code and determined that the issue was because I had a wrong import statement such as : 
```ts
import * from alias from 'someLib'; // instead of import * AS alias from 'someLib';
```

**Expected behavior:**
TypeScript compiler outputs a compilation syntax error w/ filename, line number , ....

**Actual behavior:**
TypeScript compiler throws an error.

**Comment by mhegazy** [comment]
The error is triggered while transforming a sourceFile, can you share the contents of that file?

**Comment by yuit** [comment]
@mhegazy  the repo happens just having that invalid import. Getting the fix up
