### ISSUE TITLE
TypeScript.ScriptServices.TSServerProxyFactory throws NullReferenceException

### ISSUE THREAD

**Issue by lukaseckert** [Microsoft/TypeScript#14932]
**TypeScript Version:**  2.1.5
**Visual Studio Version:**  2017 / 15.0.0+26228.10

After the installation of VS2017, every try to open a .ts file results in an error message from Visual Studio: An exception has been encountered. This may be caused by an extension. 

**Code**
This happens with any TypeScript file.

**Expected behavior:**
Open the TypeScript editor as usual.

**Actual behavior:**
After dismissing the error message, the .ts file is displayed like a normal text file - no syntax highlighting, no IntelliSense.

I have attached the ActivityLog.xml, which shows that there is a NullReferenceException being thrown in Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ExternalWebToolsService.EnsureOptionsService():
[ActivityLog.zip](https://github.com/Microsoft/TypeScript/files/882330/ActivityLog.zip)
```
	A MEF Component threw an exception at runtime: Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.TSServerProxyFactory". ---> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
	   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ExternalWebToolsService.EnsureOptionsService()
	   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ExternalWebToolsService.<EnsureOptionsServiceAsync>d__9.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ExternalWebToolsService.<GetValueForPathEnvironmentVariableAsync>d__6.MoveNext()
	   --- End of inner exception stack trace ---
	   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.TSServerProxyFactory.GetWebToolsExtNodePath()
	   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.TSServerProxyFactory..ctor(IUserSettingsProvider userSettingsProvider, Lazy`1 requestProjectRefresh, ITypeScriptProjectHost projectHost, FileExtensionService fileExtensionService, ITelemetry telemetry, IExternalWebToolsService externalToolService)
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
	   --- End of inner exception stack trace ---
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
	   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
	   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
	   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)
	   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
	   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
	   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
	   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
	   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.SatisfyImports()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)
	   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
	   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
	   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
	   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
	   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
	   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
	   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
	   at System.Lazy`1.CreateValue()
	   at System.Lazy`1.LazyInitValue()
	   at System.Lazy`1.get_Value()
	   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.SatisfyImports()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
	   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
```

**Comment by lukaseckert** [comment]
I think I found the cause for this issue, which seems to be the lack of the VS2017 extension "Microsoft Azure App Service Tools" which in turn causes the "ASP.NET and Web Tools" extension to fail on loading. TypeScript seems to require that second extension as I guess from the Stack Trace above (this "ExternalWebToolsService").
 I'm not sure if this is an issue of the TypeScript language service or Visual Studio, so I created a second issue on the VS Dev Community:
https://developercommunity.visualstudio.com/content/problem/41346/typescript-editor-crashes-on-opening-any-ts-file.html

So for me the "work-around" is to just don't disable the Azure App Service Tools although I'm not working with Azure at all. However it would be nice if Typescript would work without that VS extension without crashing the editor window.

**Comment by mhegazy** [comment]
@jramsay any idea what is going on here?

**Comment by james-poulose** [comment]
My `Microsoft Azure App Service Tools` was disabled. Once i enabled it, everything looked clean - Thanks!

**Comment by krk** [comment]
Can repro the bug and the fix with:

VS 15.2.26430.16
TS 2.2.2.0

**Comment by mhegazy** [comment]
Tracked by https://developercommunity.visualstudio.com/content/problem/41346/typescript-editor-crashes-on-opening-any-ts-file.html
