### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined in getDefinitionAtPosition()

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/TypeScript#15219]
**TypeScript Version:** 2.3.0

Getting this constantly when iterating over AST and calling getDefinitionAtPosition() on all Identifier nodes:
```
TypeError: Cannot read property 'length' of undefined
   at Object.getDefinitionAtPosition (/Users/felix/git/javascript-typescript-langserver/node_modules/typescript/lib/typescript.js:75540:97)
   at Object.getDefinitionAtPosition (/Users/felix/git/javascript-typescript-langserver/node_modules/typescript/lib/typescript.js:85288:38)
   at MergeMapSubscriber.rxjs_1.Observable.from.filter.mergeMap.node [as project] (/Users/felix/git/javascript-typescript-langserver/src/typescript-service.ts:518:53)
```

**Comment by felixfbecker** [comment]
Snippet that throws the error:
```ts
// If the current location we want to find its definition is in an object literal, try to get the contextual type for the
            // object literal, lookup the property symbol in the contextual type, and use this for goto-definition.
            // For example
            //      interface Props{
            //          /*first*/prop1: number
            //          prop2: boolean
            //      }
            //      function Foo(arg: Props) {}
            //      Foo( { pr/*1*/op1: 10, prop2: true })
            var element = ts.getContainingObjectLiteralElement(node);
            if (element) {
                if (typeChecker.getContextualType(element.parent)) {
                    var result = [];
                    var propertySymbols = ts.getPropertySymbolsFromContextualType(typeChecker, element);
                    for (var _i = 0, propertySymbols_1 = propertySymbols; _i < propertySymbols_1.length; _i++) {
                        var propertySymbol = propertySymbols_1[_i];
                        result.push.apply(result, getDefinitionFromSymbol(typeChecker, propertySymbol, node));
                    }
                    return result;
                }
            }
            return getDefinitionFromSymbol(typeChecker, symbol, node);
```
`ts.getPropertySymbolsFromContextualType(typeChecker, element);` returns `undefined`.

**Comment by RyanCavanaugh** [comment]
We'll need the code being iterated on + the setup code you use to call `getDefinitionAtPosition`

**Comment by felixfbecker** [comment]
The "setup code" is open source: https://sourcegraph.com/github.com/sourcegraph/javascript-typescript-langserver@fix-references/-/blob/src/typescript-service.ts#L518:1-519:1

`workspace/xreferences` is in this case called on that repository itself.
Here is a log with all the errors which includes the filename and offset:
```
ERROR workspace/xreferences: Error getting definition for /src/connection.ts at offset 6911 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 945 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 961 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 968 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 1160 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 1176 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 1183 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 1622 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 1638 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 1645 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 1898 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 1914 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 1921 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 2490 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 2506 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 2513 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 2838 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 2854 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 2861 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 3189 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 3205 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 3212 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 3678 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 3694 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 3701 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 3721 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 4274 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 4290 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 4921 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 4937 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 4944 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 5269 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 5285 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 5292 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 5948 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 5964 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 5971 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 6959 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 6975 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 6982 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 7307 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 7323 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 7330 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 7867 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 7883 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 7890 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 8215 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 8231 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 8238 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 8884 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 8900 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 8907 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 9100 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 9116 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 9143 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 9374 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 9390 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 9397 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 9881 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 9897 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 9904 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 9926 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 10961 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 10977 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 10984 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 11004 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 11526 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 11542 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 11999 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/connection.test.ts at offset 12015 TypeError: Cannot read property 'length' of undefined
ERROR workspace/xreferences: Error getting definition for /src/test/typescript-service-helpers.ts at offset 7502 TypeError: Cannot read property 'length' of undefined
```

These are all offsets of `Identifier` nodes given by the compiler (as you can see in the linked code)

**Comment by felixfbecker** [comment]
Shouldn't this be considered a bug? I am passing correct parameters to the function and it is trying to iterate over something `undefined`.

**Comment by RyanCavanaugh** [comment]
I'm really skeptical this language service is set up correctly - can you provide a minimal repro? I don't think it's ever happened that we'd throw an error on *every* identifier on a file. Certainly everyone would notice if the language service just stopped working entirely.

**Comment by felixfbecker** [comment]
It's not on every Identifier, it seems to be related to object literal keys.
What kind of misconfiguration could cause this? I have no idea what could be wrong here.
To me, this issue sounds very similar to https://github.com/Microsoft/TypeScript/issues/14299, which was caused by a missing `undefined` check.
Is the compiler itself using strictNullChecks?

**Comment by felixfbecker** [comment]
Maybe not that many people iterate over ASTs and call getDefinition() for every single Identifier, so these edge cases are rarely met in the language service?

**Comment by RyanCavanaugh** [comment]
Could be - if this is only on object keys, then I agree it's a bug.

For real though, a small repro would be extremely useful.

**Comment by felixfbecker** [comment]
It's hard to artificially create the exact state as in the server, but I will try to get one

**Comment by felixfbecker** [comment]
@RyanCavanaugh I am unsure how to create a self-contained repro (without adding all the code of the language server). Do you have any template/pattern/example for this (bugs in the LanguageService)? Would it help if I added a failing test on a branch for you to check out and step through?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
