### ISSUE TITLE
Corner case resulting in invalid parsing of string template literals

### ISSUE THREAD

**Issue by sandlerr** [Microsoft/TypeScript#15288]
**TypeScript Version:**  2.2.1

**Code**

```ts
String.raw`Hello, World!\`;

```

**Expected behavior:**

Successful compilation similarly to this:

```ts
String.raw`\Hello, World!`;
```

**Actual behavior:**
error TS1160: Unterminated template literal.

**Comment by RyanCavanaugh** [comment]
?
```
C:\Throwaway>type a.js
String.raw`Hello, World!\`;

C:\Throwaway>node a.js
C:\Throwaway\a.js:1
(function (exports, require, module, __filename, __dirname) { String.raw`Hello, World!\`;
                                                                     ^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unterminated template literal
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
```

**Comment by mhegazy** [comment]
This issue seems to have been already addressed or is unactionable at the moment. I am auto-closing it for now.
