### ISSUE TITLE
Random typescript errors with the latest typescript version

### ISSUE THREAD

**Issue by pitAlex** [Microsoft/TypeScript#15304]
Hello,
I have the latest stable version of typescript (2.2.2) on my mac sierra system and I keep getting random errors. The following are examples of what it trows:

```
Error - 6:00:53 PM] 'definition' request failed with error.
Error processing request. Cannot read property 'charCount' of undefined
TypeError: Cannot read property 'charCount' of undefined
at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:73968:43)
at LineIndex.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:73767:27)
at LineIndex.getText (/usr/local/lib/node_modules/typescript/lib/tsserver.js:73772:26)
at LineIndexSnapshot.getText (/usr/local/lib/node_modules/typescript/lib/tsserver.js:73694:35)
at Object.updateLanguageServiceSourceFile (/usr/local/lib/node_modules/typescript/lib/tsserver.js:67269:58)
at acquireOrUpdateDocument (/usr/local/lib/node_modules/typescript/lib/tsserver.js:58915:43)
at Object.updateDocumentWithKey (/usr/local/lib/node_modules/typescript/lib/tsserver.js:58898:20)
at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (/usr/local/lib/node_modules/typescript/lib/tsserver.js:67435:49)
at tryReuseStructureFromOldProgram (/usr/local/lib/node_modules/typescript/lib/tsserver.js:52454:28)
at Object.createProgram (/usr/local/lib/node_modules/typescript/lib/tsserver.js:52278:14)
```

```
[Error - 6:15:08 PM] 'quickinfo' request failed with error.
Error processing request. Debug Failure. False expression:
Error: Debug Failure. False expression:
at Object.assert (/usr/local/lib/node_modules/typescript/lib/tsserver.js:2844:23)
at Object.computePositionOfLineAndCharacter (/usr/local/lib/node_modules/typescript/lib/tsserver.js:9028:18)
at TextStorage.lineOffsetToPosition (/usr/local/lib/node_modules/typescript/lib/tsserver.js:68999:31)
at ScriptInfo.lineOffsetToPosition (/usr/local/lib/node_modules/typescript/lib/tsserver.js:69197:41)
at IOSession.Session.getPosition (/usr/local/lib/node_modules/typescript/lib/tsserver.js:72771:81)
at IOSession.Session.getQuickInfoWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:72828:96)
at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/local/lib/node_modules/typescript/lib/tsserver.js:72086:61)
at /usr/local/lib/node_modules/typescript/lib/tsserver.js:73306:88
at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:73297:28)
at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:73306:33)
```

<img width="1023" alt="screen shot 2017-04-21 at 6 16 09 pm" src="https://cloud.githubusercontent.com/assets/17630336/25284256/221eceea-26bf-11e7-9648-1950f8f40316.png">

<img width="791" alt="screen shot 2017-04-21 at 6 10 40 pm" src="https://cloud.githubusercontent.com/assets/17630336/25284266/2960f7fa-26bf-11e7-902b-12946b02c2e9.png">

It usually happens after I copy paste some piece of code or when a type error occurs on multiple lines. This stuff is preventing me from actually doing any work, and note that vscode works well when it doesn't have ts file opened.

**Comment by atomdmac** [comment]
+1 Also on Mac Sierra.

**Comment by mhegazy** [comment]
looks like the same symptoms as https://github.com/Microsoft/TypeScript/issues/16456
