### ISSUE TITLE
`tsc --watch` is not supported on Windows 10 WSL

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#15328]
```
--> tsc --watch
fs.js:1445
    throw error;
    ^

Error: watch /mnt/d/Code/app EPERM
    at exports._errnoException (util.js:1018:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at Object.watchDirectory (/usr/lib/node_modules/typescript/lib/tsc.js:2231:32)
    at Object.executeCommandLine (/usr/lib/node_modules/typescript/lib/tsc.js:51180:43)
    at Object.<anonymous> (/usr/lib/node_modules/typescript/lib/tsc.js:51540:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

```
tsc --version
Version 2.2.0-dev.20161116
```

**Comment by SaschaNaz** [comment]
If this works on original Ubuntu I think this should be on [BashOnWindows](https://github.com/Microsoft/) side.

**Comment by DanielRosenwasser** [comment]
Probably related to https://github.com/Microsoft/BashOnWindows/issues/216 (found through https://github.com/webpack/webpack/issues/2949).

**Comment by DanielRosenwasser** [comment]
Sounds like this should be fixed. Can you ensure you're running the most up-to-date version of Windows + WSL?

**Comment by whitecolor** [comment]
Yes it works on insiders preview, checked it today. So issue think maybe closed, or wait until oficial release of the update.
