### ISSUE TITLE
TypeError: Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#15456]
```ts
import {Component } from "react";

interface MapProps {
    prop1: string;
}

export class MyMap<P = MapProps, E = number> extends Component<P, E> { }


let x = <Map prop1="hi" />
```

Put your cursor on `Map`

```
TypeError: Cannot read property 'flags' of undefined
    at Object.resolveAlias [as getAliasedSymbol] (C:\ls\tsserver.js:26702:36)
    at Object.getCodeActions (C:\ls\tsserver.js:85017:42)
    at C:\ls\tsserver.js:84359:33
    at Object.forEach (C:\ls\tsserver.js:1428:30)
    at Object.getFixes (C:\ls\tsserver.js:84358:16)
    at C:\ls\tsserver.js:87080:40
    at Object.forEach (C:\ls\tsserver.js:1428:30)
    at Object.getCodeFixesAtPosition (C:\ls\tsserver.js:87068:16)
    at IOSession.Session.getCodeFixes (C:\ls\tsserver.js:93345:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\ls\tsserver.js:92338:61)
```

**Comment by andy-ms** [comment]
I'm seeing a related error:
```json
{"seq":0,"type":"response","command":"getCodeFixes","request_seq":7,"success":false,"message":"Error processing request. Debug Failure. False expression: Should only get Alias here.\nError: Debug Failure. False expression: Should only get Alias here.\n    at Object.assert (/home/andy/.nvm/versions/node/v7.10.0/lib/node_modules/typescript/lib/tsserver.js:2959:23)\n    at Object.resolveAlias [as getAliasedSymbol] (/home/andy/.nvm/versions/node/v7.10.0/lib/node_modules/typescript/lib/tsserver.js:23331:22)\n    at Object.getImportCodeActions [as getCodeActions] (/home/andy/.nvm/versions/node/v7.10.0/lib/node_modules/typescript/lib/tsserver.js:71302:38)\n    at /home/andy/.nvm/versions/node/v7.10.0/lib/node_modules/typescript/lib/tsserver.js:70603:33\n    at Object.forEach (/home/andy/.nvm/versions/node/v7.10.0/lib/node_modules/typescript/lib/tsserver.js:1286:30)\n    at Object.getFixes (/home/andy/.nvm/versions/node/v7.10.0/lib/node_modules/typescript/lib/tsserver.js:70602:16)\n    at /home/andy/.nvm/versions/node/v7.10.0/lib/node_modules/typescript/lib/tsserver.js:73252:40\n    at Object.forEach (/home/andy/.nvm/versions/node/v7.10.0/lib/node_modules/typescript/lib/tsserver.js:1286:30)\n    at Object.getCodeFixesAtPosition (/home/andy/.nvm/versions/node/v7.10.0/lib/node_modules/typescript/lib/tsserver.js:73240:16)\n    at IOSession.Session.getCodeFixes (/home/andy/.nvm/versions/node/v7.10.0/lib/node_modules/typescript/lib/tsserver.js:78933:64)"}
```
