### ISSUE TITLE
typescript 2.3 crashing on a JS project

### ISSUE THREAD

**Issue by trodrigues** [Microsoft/TypeScript#15551]
**TypeScript Version:**  2.3.2

I've recently added TypeScript to the webpack toolchain of a project I currently work on, with the intent of migrating some files to TS in an upcoming refactor. So far there are no `.ts` files in the project at all, just `.js` files with no type hints at all.

The config shown below worked fine with version 2.2.2 but now with version 2.3.2 I get the following stack trace:

```
Project is running at http://0.0.0.0:3010/
webpack output is served from /build/js/

[at-loader] Using typescript@2.3.2 from typescript and "tsconfig.json" from /Users/trodrigues/laterpay/connector-ui/tsconfig.json.

[at-loader]: Child process failed to process the request:  RangeError: Maximum call stack size exceeded
    at narrowType (/Users/trodrigues/laterpay/connector-ui/node_modules/typescript/lib/typescript.js:36055:32)
    at narrowType (/Users/trodrigues/laterpay/connector-ui/node_modules/typescript/lib/typescript.js:36065:32)
    at narrowType (/Users/trodrigues/laterpay/connector-ui/node_modules/typescript/lib/typescript.js:36070:36)
    at getTypeAtFlowCondition (/Users/trodrigues/laterpay/connector-ui/node_modules/typescript/lib/typescript.js:35666:36)
    at getTypeAtFlowNode (/Users/trodrigues/laterpay/connector-ui/node_modules/typescript/lib/typescript.js:35547:32)
    at getFlowTypeOfReference (/Users/trodrigues/laterpay/connector-ui/node_modules/typescript/lib/typescript.js:35503:51)
    at checkIdentifier (/Users/trodrigues/laterpay/connector-ui/node_modules/typescript/lib/typescript.js:36256:28)
    at checkExpressionWorker (/Users/trodrigues/laterpay/connector-ui/node_modules/typescript/lib/typescript.js:41135:28)
    at checkExpression (/Users/trodrigues/laterpay/connector-ui/node_modules/typescript/lib/typescript.js:41115:42)
    at checkExpressionWithContextualType (/Users/trodrigues/laterpay/connector-ui/node_modules/typescript/lib/typescript.js:40983:26)
{
[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.444 sec.
Child

    ERROR in ./~/sockjs-client/lib/main.js
    Module build failed: Error: Final loader didn't return a Buffer or String
        at runLoaders (/Users/trodrigues/laterpay/connector-ui/node_modules/webpack/lib/NormalModule.js:201:46)
        at /Users/trodrigues/laterpay/connector-ui/node_modules/loader-runner/lib/LoaderRunner.js:370:3
        at iterateNormalLoaders (/Users/trodrigues/laterpay/connector-ui/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
        at iterateNormalLoaders (/Users/trodrigues/laterpay/connector-ui/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
        at /Users/trodrigues/laterpay/connector-ui/node_modules/loader-runner/lib/LoaderRunner.js:233:3
        at context.callback (/Users/trodrigues/laterpay/connector-ui/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
        at runMicrotasksCallback (internal/process/next_tick.js:64:5)
        at _combinedTickCallback (internal/process/next_tick.js:73:7)
        at process._tickCallback (internal/process/next_tick.js:104:9)
     @ ./~/sockjs-client/lib/entry.js 3:17-34
     @ (webpack)-dev-server/client/socket.js
     @ (webpack)-dev-server/client?http://0.0.0.0:3010
     @ multi (webpack)-dev-server/client?http://0.0.0.0:3010 ./src/utils/loader.js
webpack: Failed to compile.
```

I have no idea what, if any code at all would be causing this.

This is running on Node 7.9.0. Config details follow.

tsconfig.json:
```json
{
    "compilerOptions": {
        "outDir": "./build/",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "es2015",
        "target": "es2015",
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "allowUnreachableCode": true,
        "jsx": "react"
    },
    "include": [
        "./src/**/*",
        "./tests/**/*",
        "./locales/**/*"
    ]
}
```

rules section of webpack.config.js
```js
    module: {
      rules: [
        {
          test: /(\.js|\.ts|\.tsx)?$/,
          loader: 'awesome-typescript-loader'
        },
        {
          enforce: 'pre',
          test: /\.js$/,
          exclude: /(node_modules\/intl-.*)/,
          loader: 'source-map-loader'
        },
        {
          enforce: 'post',
          test: /\.js?$/,
          exclude: /(node_modules|bower_components|dist)/,
          loader: 'babel-loader'
        }
      ]
    }
```

**Expected behavior:**

Code compiles with no crashes.

**Actual behavior:**

Typescript crashes while compiling the code.

**Comment by mhegazy** [comment]
Can you share the sources?

**Comment by trodrigues** [comment]
Not exactly. The sources are, well, the whole project, and it's not an open source project. If I knew what more particular thing caused the issue I could share that file or section.

**Comment by kitsonk** [comment]
Sometimes `awesome-typescript-loader` has been known to interfere... Does the `tsc` by itself cause an error?

**Comment by trodrigues** [comment]
@kitsonk right, so I tried it with just `tsc` and it does indeed work. I've opened an issue in the awesome-typescript-loader repo with a reduced test case that reproduces the bug.
