### ISSUE TITLE
Typescript crashes while parsing JS 

### ISSUE THREAD

**Issue by chrisleck** [Microsoft/TypeScript#15619]
**TypeScript Version:**  2.3.2

Typescript compiler crashes with the following stacktrace while loading a large codebase of mostly .js files with `allowJs: true`.
```
/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:43781
                if (propDeclaration && (propDeclaration.name.kind === 144 /* ComputedPropertyName */ || prop.parent === containingType.symbol)) {
                                                            ^
TypeError: Cannot read property 'kind' of undefined
    at checkIndexConstraintForProperty (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:43781:61)
    at /Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:43739:21
    at Object.forEach (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:1443:30)
    at checkIndexConstraints (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:43737:20)
    at checkClassLikeDeclaration (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:44001:17)
    at checkClassDeclaration (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:43914:13)
    at checkSourceElement (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:44963:28)
    at Object.forEach (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:1443:30)
    at checkSourceFileWorker (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:45046:20)
    at checkSourceFile (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:45026:13)
    at getDiagnosticsWorker (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:45090:17)
    at getDiagnostics (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:45076:24)
    at Object.getEmitResolver (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:25836:13)
    at emitWorker (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:67198:69)
    at /Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:67163:66
    at runWithCancellationToken (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:67254:24)
    at Object.emit (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:67163:20)
    at Object.getEmitOutput (/Users/chris/src/experimental/node_modules/typescript/lib/typescript.js:86262:38)
    at getOutput (/Users/chris/src/experimental/node_modules/ts-node/src/index.ts:292:30)
    at /Users/chris/src/experimental/node_modules/ts-node/src/index.ts:333:16
    at Object.compile (/Users/chris/src/experimental/node_modules/ts-node/src/index.ts:492:17)
    at Module.m._compile (/Users/chris/src/experimental/node_modules/ts-node/src/index.ts:385:43)
```

**Code**
Not sure where to start to get a standalone repro.  In one case, loading a dependent file with the following content triggers the issue, but doesn't seem to trigger if I isolate it on its own.  Via console logging, it looks like typescript is exploding when checking member properties `events` and `value` of the `ImmutableHappy` class.  If I don't subclass `EventEmitter` from `ImmutableHappy`, the issue goes away.

```
'use strict';
const testHelper = require('../test_helper');
const {EventEmitter} = require('events');
const {createUpdatingProxy} = require('../src/updating_proxy');

describe('UpdatingProxy', () => {
  const updateEventName = 'update';

  class ImmutableHappy extends EventEmitter {
    constructor(emitter, val) {
      super();
      this.events = emitter;
      this.value = val;
    }

    updateMe() {
      this.events.emit(updateEventName, new ImmutableHappy(this.events, this.value + 1));
    }

    get valueProp() {
      return this.value;
    }

    getValueProp() {
      return this.value;
    }
  }

  it('forwards', () => {
    const happy = new ImmutableHappy(new EventEmitter(), 123);
    const proxy = createUpdatingProxy(happy, updateEventName);

    assert.equal(123, proxy.value);
    assert.equal(123, proxy.valueProp);
    assert.equal(123, proxy.getValueProp());
  });

  it('updates', () => {
    const happy = new ImmutableHappy(new EventEmitter(), 1);
    const proxy = createUpdatingProxy(happy, updateEventName);
    assert.equal(1, proxy.value);

    happy.updateMe();
    assert.equal(2, proxy.value);

    proxy.updateMe();
    assert.equal(3, proxy.value);
  });
});
```

**Expected behavior:**
Compiler doesn't crash

**Actual behavior:**
Compiler crashes

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/15525

**Comment by chrisleck** [comment]
Indeed.  And it appears fixed in the latest nightly build.  Thanks!

**Comment by chrisleck** [comment]
I may have spoken too soon.  Seeing a related crash with latest nightly, but with a slightly different stack.  I'll open a new issue.

**Comment by chrisleck** [comment]
Ah - the new stack is the same as reported in https://github.com/Microsoft/TypeScript/issues/15616.
