### ISSUE TITLE
Error when type-checking js project when maxNodeModuleJsDepth > 0

### ISSUE THREAD

**Issue by Wenzil** [Microsoft/TypeScript#15611]
**TypeScript Version:**  2.3.2

**Steps to reproduce:**

- Add the following `tsconfig.json` file to a project with many npm package dependencies (including typescript@2.3.2 as a dev dependency).

```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "allowJs": true,
        "checkJs": true,
        "noEmit": true,
        "maxNodeModuleJsDepth": 1
    },
    "exclude": [
        "node_modules"
    ]
}
```

- Run `node_modules/.bin/tsc`

**Expected behavior:** 

Typescript successfully type-checks my javascript project

**Actual behavior:** 

Typescript fails to type-check my javascript project with the following error

```sh
TypeError: Cannot read property 'kind' of undefined
    at /Users/<my-user>/projects/<my-project>/node_modules/typescript/lib/tsc.js:36141:21
    at Object.forEach (/Users/<my-user>/projects/<my-project>/node_modules/typescript/lib/tsc.js:288:30)
    at checkIndexConstraints (/Users/<my-user>/projects/<my-project>/node_modules/typescript/lib/tsc.js:36139:20)
    at checkClassLikeDeclaration (/Users/<my-user>/projects/<my-project>/node_modules/typescript/lib/tsc.js:36374:17)
    at checkClassExpression (/Users/<my-user>/projects/<my-project>/node_modules/typescript/lib/tsc.js:36280:13)
    at checkExpressionWorker (/Users/<my-user>/projects/<my-project>/node_modules/typescript/lib/tsc.js:34062:28)
    at checkExpression (/Users/<my-user>/projects/<my-project>/node_modules/typescript/lib/tsc.js:34012:42)
    at checkExpressionCached (/Users/<my-user>/projects/<my-project>/node_modules/typescript/lib/tsc.js:33928:38)
    at getTypeOfExpression (/Users/<my-user>/projects/<my-project>/node_modules/typescript/lib/tsc.js:33997:28)
    at checkDeclarationInitializer (/Users/<my-user>/projects/<my-project>/node_modules/typescript/lib/tsc.js:33938:24)

```

**Comment by mhegazy** [comment]
` "maxNodeModuleJsDepth": 1` means if you see `require("foo")` go load, parse and check `node_modules\foo\*.js`.

Can you narrow down what package in your node_modules that is causing this issue?

**Comment by mhegazy** [comment]
also if you are using `checkJs`, i would not recommend using `maxNodeModuleJsDepth`, since it will give you errors in files you do not own or care about.

**Comment by Wenzil** [comment]
I've tried to reproduce this in a bare bones project with only one npm package dependency. The problem didn't occur, so it's definitely some node module not playing well with typescript. I'll try to narrow down which one it is.

The reason I'm setting `"maxNodeModuleJsDepth: 1"` is to enable type inference on module exports of node modules. My hope was that in conjunction with `"exclude": ["node_modules"]`, I would get type inference *from* installed node modules, but wouldn't get type-checking errors *in* them.

It's worth noting that type-checking works as expected in VS Code, and that the error only occurs when I run the command `node_modules/.bin/tsc` in a shell (on OS X)

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
