### ISSUE TITLE
Recursive default generic causes Maximum call stack size exceeded

### ISSUE THREAD

**Issue by fathyb** [microsoft/TypeScript#15926]
**TypeScript Version:**  2.3.2

**Code**

```ts
type PrimitiveValue<T = PrimitiveValue> = null|string|boolean|number|T[]
```

**Expected behavior:**
Show an error that says recursive generics are not permitted

**Actual behavior:**
```
RangeError: Maximum call stack size exceeded
    at resolveEntityName (node_modules/typescript/lib/tsc.js:21829:35)
    at getTypeFromTypeReference (node_modules/typescript/lib/tsc.js:26048:54)
    at getTypeFromTypeNode (node_modules/typescript/lib/tsc.js:26832:28)
    at getDefaultFromTypeParameter (node_modules/typescript/lib/tsc.js:25286:66)
    at getMinTypeArgumentCount (node_modules/typescript/lib/tsc.js:25538:26)
    at getTypeFromTypeAliasReference (node_modules/typescript/lib/tsc.js:25939:44)
    at getTypeFromTypeReference (node_modules/typescript/lib/tsc.js:26051:53)
    at getTypeFromTypeNode (node_modules/typescript/lib/tsc.js:26832:28)
    at getDefaultFromTypeParameter (node_modules/typescript/lib/tsc.js:25286:66)
    at getMinTypeArgumentCount (node_modules/typescript/lib/tsc.js:25538:26)
```

It seems to cause VS Code language service to crash too, and it gives no information about which line causes the problem.

**Comment by athasach** [comment]
Similarly, an interface declaration can cause this error too. In Version 3.3.0-dev.20181201:
```ts
interface Item<N extends Item = Item> {
}
```
```ts
RangeError: Maximum call stack size exceeded
    at Object.assert (node_modules/typescript/lib/tsc.js:1244:24)
    at getSymbol (node_modules/typescript/lib/tsc.js:25926:30)
    at resolveNameHelper (node_modules/typescript/lib/tsc.js:26225:30)
    at resolveName (node_modules/typescript/lib/tsc.js:26034:20)
    at resolveEntityName (node_modules/typescript/lib/tsc.js:26727:26)
    at resolveTypeReferenceName (node_modules/typescript/lib/tsc.js:31884:20)
    at getTypeFromTypeReference (node_modules/typescript/lib/tsc.js:32060:30)
    at getTypeFromTypeNode (node_modules/typescript/lib/tsc.js:33420:28)
    at getConstraintFromTypeParameter (node_modules/typescript/lib/tsc.js:31746:72)
    at fillMissingTypeArguments (node_modules/typescript/lib/tsc.js:31336:49)```

**Comment by DerZyklop** [comment]
This can be closed. It is not an issue any more. 
Error nowadays is this: `Type parameter 'T' has a circular default.`
https://www.typescriptlang.org/play?ts=4.7.4#code/C4TwDgpgBACgTgSwLYOAgbhAagQwDYCuEAPACpQC8siKamuhEAfJVAHYF54A+AzsIjYBzbgCMA9uLwQcbbhySiIcbqQDaAXQBQQA
