### ISSUE TITLE
compiler/importDeclTypes test fails on Windows 10.0.15063

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#15977]
**TypeScript Version:**  master

**Code**

```
>jake runtests t=importDeclTypes

>mocha -R mocha-fivemat-progress-reporter -g "importDeclTypes" --colors -t 20000 built\local\run.js

    compiler tests

Test failure:
Correct errors for tests/cases/compiler/importDeclTypes.ts                         [...................................]

  5 passing (4s)
  1 failing

  1) compiler tests compiler tests for tests/cases/compiler/importDeclTypes.ts Correct errors for tests/cases/compiler/i
mportDeclTypes.ts:
     Error: The baseline file importDeclTypes.errors.txt has changed.
      at writeComparison (src\harness\harness.ts:1959:23)
      at Object.runBaseline (src\harness\harness.ts:1967:13)
      at Object.doErrorBaseline (src\harness\harness.ts:1388:30)
      at Context.<anonymous> (src\harness\compilerRunner.ts:139:35)
```

**Expected behavior:** importDeclTypes should succeed regardless of OS

**Actual behavior:** importDeclTypes fails on Windows with an additional unexpected error TS2307:

```
tests/cases/compiler/a.ts(1,21): error TS2307: Cannot find module '@types/foo-bar'.
tests/cases/compiler/a.ts(1,21): error TS6137: Cannot import type declaration files. Consider importing 'foo-bar' instead of '@types/foo-bar'.


==== /node_modules/@types/foo-bar/index.d.ts (0 errors) ====
    export interface Foo {
        bar: string;
    }
    
    // This should error
==== tests/cases/compiler/a.ts (2 errors) ====
    import { Foo } from "@types/foo-bar";
                        ~~~~~~~~~~~~~~~~
!!! error TS2307: Cannot find module '@types/foo-bar'.
                        ~~~~~~~~~~~~~~~~
!!! error TS6137: Cannot import type declaration files. Consider importing 'foo-bar' instead of '@types/foo-bar'.
```

**Comment by mhegazy** [comment]
fixed by https://github.com/Microsoft/TypeScript/pull/15992
