### ISSUE TITLE
exception when a @types definition coult not be found

### ISSUE THREAD

**Issue by p3root** [Microsoft/TypeScript#15989]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts


```

**Expected behavior:**
print out a human readable and understandable error message!

**Actual behavior:**
PS <dir>> ng s
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (<dir>\node_modules\typescript\lib\typescript.js:14876:109)
    at parseSourceFileWorker (<dir>\node_modules\typescript\lib\typescript.js:14808:26)
    at Object.parseSourceFile (<dir>\node_modules\typescript\lib\typescript.js:14757:26)
    at Object.createSourceFile (<dir>\node_modules\typescript\lib\typescript.js:14612:29)
    at WebpackCompilerHost.getSourceFile (<dir>\node_modules\@ngtools\webpack\src\compiler_host.js:210:27)
    at findSourceFile (<dir>\node_modules\typescript\lib\typescript.js:64751:29)
    at processSourceFile (<dir>\node_modules\typescript\lib\typescript.js:64682:27)
    at <dir>\node_modules\typescript\lib\typescript.js:64792:17
    at Object.forEach (<dir>\node_modules\typescript\lib\typescript.js:1398:30)
    at processReferencedFiles (<dir>\node_modules\typescript\lib\typescript.js:64790:16)
    at findSourceFile (<dir>\node_modules\typescript\lib\typescript.js:64775:21)
    at processImportedModules (<dir>\node_modules\typescript\lib\typescript.js:64898:25)
    at findSourceFile (<dir>\node_modules\typescript\lib\typescript.js:64779:17)
    at processImportedModules (<dir>\node_modules\typescript\lib\typescript.js:64898:25)
    at findSourceFile (<dir>\node_modules\typescript\lib\typescript.js:64779:17)
    at processImportedModules (<dir>\node_modules\typescript\lib\typescript.js:64898:25)

**Comment by mhegazy** [comment]
Please provide a self-contained repro for the issue.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by julienbiaussat** [comment]
same problem :
o	TypeError: Cannot read property 'length' of undefined : at createSourceFile (C:_DATA\RENAULT\CADRAGE\GIT\Cadrage\node_modules\typescript\lib\typescript.js:14876:109)
I just played with environment.ts adding a baseURL :
export const env = {
production: false,
baseUrl: 'http://localhost:8080/api'
};
but the file was not found in my login service :
import { env } from '../environments/environment';
so I moved it one directory up to test, and it was ok
import { env } from '../environment';

I don't see relation with the bug ???

**Comment by julienbiaussat** [comment]
main.ts -> wrong path : import { environment } from './environments/environment';  
because I moved environment.ts.... pfff

**Comment by itsanicool** [comment]
Hi @julienbiaussat, I am facing this issue while doing **npm test**, Can you please provide more details on how to resolve this.

Thanks

**Comment by julienbiaussat** [comment]
In my main.ts, my path to envoronment.ts was wrong !

**Comment by itsanicool** [comment]
Hi @julienbiaussat, Below is the error I am getting-
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (node_modules\typescr
ipt\lib\typescript.js:14876:109) 

my main.ts path is right, is there anything we need to look into?
