### ISSUE TITLE
getRootLength - Cannot read property 'charCodeAt' of undefined

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16048]
**TypeScript Version:**  2.4.0-dev.20170523

While executing a `getApplicableRefactors` request, I see this error on the tsserver:

```ts
Info 1948 request: {"seq":607,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/Users/matb/projects/san/z.d.ts","startLine":1,"startOffset":1,"endLine":1,"endOffset":7}}
Err 1949  Exception on executing command {"seq":607,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/Users/matb/projects/san/z.d.ts","startLine":1,"startOffset":1,"endLine":1,"endOffset":7}}:
Cannot read property 'charCodeAt' of undefined
TypeError: Cannot read property 'charCodeAt' of undefined
    at getRootLength (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:2290:17)
    at Object.isRootedDiskPath (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:2400:16)
    at moduleHasNonRelativeName (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:4407:21)
    at tryLoadModuleUsingOptionalResolutionSettings (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:4711:13)
    at tryResolve (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:4846:28)
    at nodeModuleNameResolverWorker (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:4838:68)
    at nodeModuleNameResolver (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:4823:16)
    at Object.resolveModuleName (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:4683:30)
    at LSHost.resolveModuleName (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:74742:44)
    at LSHost.resolveNamesWithLocalCache (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:74779:42)
Info 1950 response: {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":607,"success":false,"message":"Error processing request. Cannot read property 'charCodeAt' of undefined\nTypeError: Cannot read property 'charCodeAt' of undefined\n    at getRootLength (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:2290:17)\n    at Object.isRootedDiskPath (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:2400:16)\n    at moduleHasNonRelativeName (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:4407:21)\n    at tryLoadModuleUsingOptionalResolutionSettings (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:4711:13)\n    at tryResolve (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:4846:28)\n    at nodeModuleNameResolverWorker (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:4838:68)\n    at nodeModuleNameResolver (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:4823:16)\n    at Object.resolveModuleName (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:4683:30)\n    at LSHost.resolveModuleName (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:74742:44)\n    at LSHost.resolveNamesWithLocalCache (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:74779:42)"}
```

**Comment by mhegazy** [comment]
@mjbvz can you share a specific code that you were invoking this on, or at least a deeper stack?

**Comment by mjbvz** [comment]
I've uploaded the full log: 

[tsserver.txt](https://github.com/Microsoft/TypeScript/files/1023930/tsserver.txt)

I'm not sure of the exact repo steps. I was working in a JS project with a `jsconfig.json` and had create a new `d.ts` file called `z.d.ts`. The contents of z.d.ts were:

```ts
declare var FOO = 123;
```

**Comment by andy-ms** [comment]
Hi @mjbvz, it's hard to tell what's going on without a deeper stack -- all of the functions in the stack expect to receive and array of non-`undefined` inputs, and just pass it down to the next one. I added an assertion in #17124 to make an error happen a little earlier, so could you try again once that's in?

**Comment by mhegazy** [comment]
closing for now. please reopen if you run into this crash again.
