### ISSUE TITLE
Exception with namespace containing 'default export class {}'

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#16300]
**TypeScript Version:**  2.3.4 and current playground

**Code**

```ts
namespace ns {
    export default class { } // no error shown
}
```

**Expected behavior:**

Error that default exports are only allowed in ECMAScript modules.

**Actual behavior:**

No error in IDE and exception during compile:

```
TypeError: Cannot read property 'pos' of undefined
    at addExportMemberAssignment (/home/klaus/code/tsutils/node_modules/typescript/lib/tsc.js:41973:70)
    at visitClassDeclaration (/home/klaus/code/tsutils/node_modules/typescript/lib/tsc.js:40894:17)
    at visitTypeScript (/home/klaus/code/tsutils/node_modules/typescript/lib/tsc.js:40810:28)
    at namespaceElementVisitorWorker (/home/klaus/code/tsutils/node_modules/typescript/lib/tsc.js:40725:24)
    at saveStateAndInvoke (/home/klaus/code/tsutils/node_modules/typescript/lib/tsc.js:40659:27)
    at namespaceElementVisitor (/home/klaus/code/tsutils/node_modules/typescript/lib/tsc.js:40714:20)
    at Object.visitNodes (/home/klaus/code/tsutils/node_modules/typescript/lib/tsc.js:39514:48)
    at /home/klaus/code/tsutils/node_modules/typescript/lib/tsc.js:41845:94
    at saveStateAndInvoke (/home/klaus/code/tsutils/node_modules/typescript/lib/tsc.js:40659:27)
    at transformModuleBody (/home/klaus/code/tsutils/node_modules/typescript/lib/tsc.js:41845:17)
```

Same applies to `export default function(){}`

**Comment by mhegazy** [comment]
A PR would be welcomed.

**Comment by charlespierce** [comment]
PR opened to address this issue: #16704

**Comment by DanielRosenwasser** [comment]
Thanks @charlespierce!
