### ISSUE TITLE
Emulating constraint circularity with generic parameter default crashes compiler

### ISSUE THREAD

**Issue by Oblosys** [Microsoft/TypeScript#16328]
**TypeScript Version:**  2.3.0 up to nightly (2.4.0-dev.20170607)

When using a generic parameter default as an equality constraint to establish a constraint circularity, the compiler crashes on the code below.

**Code**

```ts
function assertTypeEquality<A extends B, B extends C, C = A>() {}
assertTypeEquality<{a : number, b : number}, {a : number}>(); // crashes type checker
```

**Expected behavior:**
A type error:
```
Type '{ a: number; }' does not satisfy the constraint '{ a: number; b: number; }'.
   Property 'b' is missing in type '{ a: number; }'.
```

Flipping the arguments gives the expected type error:
```ts
assertTypeEquality<{a : number}, {a : number, b : number}>(); // gives expected type error
```
**Actual behavior:**
Compiler exception:
```
/usr/local/lib/node_modules/typescript/lib/tsc.js:53737
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at getObjectFlags (/usr/local/lib/node_modules/typescript/lib/tsc.js:21214:24)
    at getTypeWithThisArgument (/usr/local/lib/node_modules/typescript/lib/tsc.js:24763:17)
    at checkTypeArguments (/usr/local/lib/node_modules/typescript/lib/tsc.js:32163:90)
    at resolveCall (/usr/local/lib/node_modules/typescript/lib/tsc.js:32462:21)
    at resolveCallExpression (/usr/local/lib/node_modules/typescript/lib/tsc.js:32594:20)
    at resolveSignature (/usr/local/lib/node_modules/typescript/lib/tsc.js:32772:28)
    at getResolvedSignature (/usr/local/lib/node_modules/typescript/lib/tsc.js:32792:26)
    at checkCallExpression (/usr/local/lib/node_modules/typescript/lib/tsc.js:32808:29)
    at checkExpressionWorker (/usr/local/lib/node_modules/typescript/lib/tsc.js:34056:28)
    at checkExpression (/usr/local/lib/node_modules/typescript/lib/tsc.js:34012:42)
```

**Context:**

Another option would be to disallow the definition because of the circularity, but the version below, which uses proxy objects to provide the types, works just fine, so it seems that the type checker is able to handle these kinds of constraints.

```ts
function assertTypeEqProxy<A extends B, B extends C, C = A>(proxyA : A, proxyB : B) {}
assertTypeEqProxy({a: 1, b: 2}, {a: 3}); // gives expected type error
assertTypeEqProxy({a: 1}, {a: 3, b: 2}); // gives expected type error
```

**Comment by Oblosys** [comment]
This got fixed somewhere along the way. (works as expected in 2.7)
