### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#16331]
Using 2.4.0-dev.20170607
The project is big and it will take time to find out what exactly caused this problem.
Perhaps this will be enough to understand the issue.

```
test\node_modules\typescript\lib\typescript.js:69700
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at mapper (test\node_modules\typescript\lib\typescript.js:33886:35)
    at mapper (test\node_modules\typescript\lib\typescript.js:33886:64)
    at instantiateTypeNoAlias (test\node_modules\typescript\lib\typescript.js:34104:24)
    at instantiateType (test\node_modules\typescript\lib\typescript.js:34098:24)
    at mapper (test\node_modules\typescript\lib\typescript.js:33886:48)
    at mapper (test\node_modules\typescript\lib\typescript.js:33886:64)
    at instantiateTypeNoAlias (test\node_modules\typescript\lib\typescript.js:34104:24)
    at instantiateType (test\node_modules\typescript\lib\typescript.js:34098:24)
    at mapper (test\node_modules\typescript\lib\typescript.js:33886:48)
    at mapper (test\node_modules\typescript\lib\typescript.js:33886:64)
    at instantiateTypeNoAlias (test\node_modules\typescript\lib\typescript.js:34104:24)
    at instantiateType (test\node_modules\typescript\lib\typescript.js:34098:24)
    at mapper (test\node_modules\typescript\lib\typescript.js:33886:48)
    at mapper (test\node_modules\typescript\lib\typescript.js:33886:64)
    at instantiateTypeNoAlias (test\node_modules\typescript\lib\typescript.js:34104:24)
    at instantiateType (test\node_modules\typescript\lib\typescript.js:34098:24)
```

**Comment by mhegazy** [comment]
We will need some sample cod to debug further. we would be happy to sign any NDA as needed.

**Comment by egandro** [comment]
My wild guess - node 8.0.0?

Got this issue - 10min ago, too after upgrading ;)

**Comment by NN---** [comment]
@mhegazy Sure, next week I have time to find out the piece of code which makes the problem.
@egandro Actually Node 7. Still waiting for libraries to be compatible with Node 8 and for Node 8 to revert breaking changes :).

**Comment by mhegazy** [comment]
thanks! appreciate the help.

**Comment by egandro** [comment]
@NN--- thx you saved my day... after upgrading to 8.0.0 my build pipline goes red ;)

**Comment by egandro** [comment]
The NPM guys have a similar issue:

https://github.com/npm/npm/issues/17056


npm5 - which comes with node 8 - now creates links instead of doing a copy (<---- for local modules)

**Comment by twoeo** [comment]
E:\Codes\Xiaohatu\frontend>node_modules\.bin\tsc -w
C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:53887
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at Object.binarySearch (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:773:26)
    at computeLineAndCharacterOfPosition (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:3537:29)
    at Object.getLineAndCharacterOfPosition (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:3549:16)
    at getLineOfLocalPosition (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:7200:19)
    at positionsAreOnSameLine (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:7806:13)
    at Object.rangeEndIsOnSameLineAsRangeStart (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:7801:16)
    at needsIndentation (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:53039:24)
    at emitBinaryExpression (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:51966:40)
    at pipelineEmitExpression (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:51552:28)
    at pipelineEmitWithHint (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:51280:32)
    at emitNodeWithSourceMap (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:48997:21)


node 7.2.2

**Comment by egandro** [comment]
Do you have Modules in node_modules that are linked?

**Comment by twoeo** [comment]
@egandro yes. `typescript` and `webpack` are linked.

**Comment by egandro** [comment]
Node 8.0.0 and NPM 5 changed my 

"foo": "file://../../lib/foo" from copies to links

So the "foo" link inherits the node_modules folder form it's location - it also brings the developent modules to the main project.

Here the issues started :(

However -  simple "Hello World" projects - using this new links - has no issues when using pure Javascript.

I guess it's a TypeScript problem.

**Comment by mhegazy** [comment]
if you have a sample that reproduces the issue we would be happy to investigate.

**Comment by egandro** [comment]
I try creating one. Give me a cuple of days. I'll reverted from Node 8 to 7 and i'll need a VM with 8 for that.

**Comment by twoeo** [comment]
Okay~ I will up a sample later~

**Comment by NN---** [comment]
Found it !
This compiles well with TypeScript 2.3.4 but not with 2.4.0:

Smallest sample (this code doesn't make sense cause I leaved only relevant part):
```ts
function clone<T>(obj: T, cloneFunc = clone): T {
    let i: number;
	let retArray: Array<T>;
	return cloneFunc(retArray[i], cloneFunc);
}
```

http://www.typescriptlang.org/play/#src=function clone<T>(obj%3A T%2C cloneFunc %3D clone)%3A T {%0D%0A let i%3A number%3B%0D%0A%09let retArray%3A Array<T>%3B%0D%0A%09return cloneFunc(retArray[i]%2C cloneFunc)%3B%0D%0A}%0D%0A

**Comment by NN---** [comment]
Please fix this.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
