### ISSUE TITLE
Maximum call stack size exceeded when compile

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#16388]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)
2.3.4

Node 7.2.2

**Code**
A large project.
TypeScript 2.2 will compile successfully

tsconfig.json: 
```ts
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "lib": [
            "DOM",
            "ES6",
            "DOM.Iterable",
            "ScriptHost"
        ],
        "noImplicitAny": false,
        "sourceMap": true,
        "jsx": "react",
        "outDir": "dist",
        "moduleResolution": "node",
        "strictNullChecks": true,
        "baseUrl": "./",
        "allowJs": true,
        "paths": {
            "*": [
                "*",
                "./libs/*",
                "../shared/*",
                "../shared/libs/*"
            ]
        },
        "typeRoots": [
            "./typings", "./node_modules/@types", "typings", "node_modules/@types"
        ]
    },
    "exclude": [
        "dist",
        "node_modules",
        "libs",
        "*.test.ts",
        "libs/**/*.d.ts"
    ]
}
```

**Expected behavior:**
Compile succ.

**Actual behavior:**
> E:\Codes\Xiaohatu\frontend>tsc
C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:53887
                throw e;
                ^
RangeError: Maximum call stack size exceeded
    at emitBinaryExpression (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:51964:38)
    at pipelineEmitExpression (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:51552:28)
    at pipelineEmitWithHint (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:51280:32)
    at emitNodeWithSourceMap (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:48997:21)
    at pipelineEmitWithSourceMap (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:51270:17)
    at emitNodeWithNestedComments (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:49237:17)
    at emitNodeWithSynthesizedComments (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:49187:13)
    at emitNodeWithComments (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:49160:21)
    at pipelineEmitWithComments (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:51262:17)
    at emitNodeWithNotification (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:48716:21)
    at pipelineEmitWithNotification (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:51253:17)
    at emitExpression (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:51249:13)

**If `sourceMap: false`, still compile error:**

> E:\Codes\Xiaohatu\frontend>node_modules\.bin\tsc
C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:53887
                throw e;
                ^
RangeError: Maximum call stack size exceeded
    at Object.binarySearch (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:773:26)
    at computeLineAndCharacterOfPosition (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:3537:29)
    at Object.getLineAndCharacterOfPosition (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:3549:16)
    at getLineOfLocalPosition (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:7200:19)
    at positionsAreOnSameLine (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:7806:13)
    at Object.rangeEndIsOnSameLineAsRangeStart (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:7801:16)
    at needsIndentation (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:53039:24)
    at emitBinaryExpression (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:51966:40)
    at pipelineEmitExpression (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:51552:28)
    at pipelineEmitWithHint (C:\Users\longsheng\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:51280:32)

**Comment by mhegazy** [comment]
Can you share the sources that triggered the stack over flow?

**Comment by mhegazy** [comment]
Also can you give typescript@next a try? We have made a recent change for emitting comm expressions that have similar semptoms.

**Comment by twoeo** [comment]
@mhegazy 2.4.0 have no problem.
And compile speed is faster.

**Comment by twoeo** [comment]
Well, actually compile speed is 2x slower.
3min30s before
8min30s after

**Comment by mhegazy** [comment]
> Well, actually compile speed is 2x slower.

can you share the output of your `tsc --diagnostics` on TS 2.4 and TS 2.3?
