### ISSUE TITLE
Debug Failure when enabling --noImplicitAny

### ISSUE THREAD

**Issue by alex3165** [Microsoft/TypeScript#16483]
**TypeScript Version:**  2.4.0

When I turn `noImplicitAny` to true in tsconfig.json I get a Debug Failure error. I have turned the flag off, fixed an issue, the project was compiling fine then turned the flag back on and got the same error

**Code**

```ts
// tsconfig.json
{
  "compilerOptions": {
    "outDir": "lib",
    "module": "commonjs",
    "target": "es5",
    "lib": ["es7", "dom"],
    "sourceMap": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "declaration": true,
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "types": ["node"]
  },
  "exclude": [
    "node_modules",
    "lib",
    "build",
    "**/*.test.*",
    "**/*.stories.tsx"
  ]
}
```

**Expected behavior:**
Project compiling.

**Actual behavior:**
```
/usr/local/lib/node_modules/typescript/lib/tsc.js:55708
                throw e;
                ^

Error: Debug Failure.
    at reportError (/usr/local/lib/node_modules/typescript/lib/tsc.js:28773:26)
    at hasExcessProperties (/usr/local/lib/node_modules/typescript/lib/tsc.js:28931:37)
    at isRelatedTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:28838:25)
    at eachTypeRelatedToType (/usr/local/lib/node_modules/typescript/lib/tsc.js:29021:35)
    at isRelatedTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:28868:25)
    at checkTypeRelatedTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:28761:26)
    at checkApplicableSignature (/usr/local/lib/node_modules/typescript/lib/tsc.js:33652:26)
    at resolveCall (/usr/local/lib/node_modules/typescript/lib/tsc.js:33884:17)
    at resolveNewExpression (/usr/local/lib/node_modules/typescript/lib/tsc.js:34091:24)
    at resolveSignature (/usr/local/lib/node_modules/typescript/lib/tsc.js:34223:28)
```

**Comment by alex3165** [comment]
Sorry I will close this issue it is not very explicit, I managed to fix it by removing a reference to an interface that was using `_` as a key in a file but I am not entirely sure about the issue I didn't manage to isolate it.

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/16292
