### ISSUE TITLE
Runtime error with inheritance + decorator + static members in TS 2.4.0

### ISSUE THREAD

**Issue by ahagelstein** [Microsoft/TypeScript#16516]
**TypeScript Version:**  2.4.0

**Code**

```ts
function test(): any {
}

export class Test01 {

}

@test()
export class Test02 extends Test01 {

    public static statics = "Hello";

    public test() {

        const value = Test02.statics;
    }
}

```

**Expected behavior:**

compiles and runs without error.

**Actual behavior:**

compiles without error but generates runtime error:

$ node sample01.js
D:\Temp\Code\test\sample01.js:7
        extendStatics(d, b);
        ^

TypeError: Object.setPrototypeOf called on null or undefined
    at setPrototypeOf (native)
    at __extends (D:\Temp\Code\test\sample01.js:7:9)
    at D:\Temp\Code\test\sample01.js:28:5
    at Object.<anonymous> (D:\Temp\Code\test\sample01.js:41:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)

With typescript@2.3.4 and typescript@2.5.0-dev.20170614 it works.

**Comment by ahagelstein** [comment]
Duplicate #16506
