### ISSUE TITLE
Compile-time interface checking

### ISSUE THREAD

**Issue by kol-93** [Microsoft/TypeScript#16510]
How can I check if object implements is implementation of some interface?

Please, add some instructions for compile-time interface checks.

**TypeScript Version:**  2.4.0

**Code**

```
interface IFirst {
	f1(): void;
}

interface ISecond {
	f2(): void;
}

interface IThird {
	f3(): void;
}


class Implementation implements IFirst, ISecond, IThird {
	f1() {
		console.info('+f1');
	}
	
	f2() {
		console.info('+f2');
	}
	
	f3() {
		console.info('+f3');
	}
}

class Incorrect implements ISecond {
	f1(x: number): void {
		console.info('!f1(' + x + ')')
	}
	
	f2() {
		console.info('+f2');
	}
	
	f3: number = 10;
}

function testObject(obj: IFirst | ISecond | IThird) {
	try {
		let x1: IFirst  = <IFirst> obj;
		x1.f1();
	} catch (e) {
		console.error(e);
	}
	
	try {
		let x2: ISecond  = <ISecond> obj;
		x2.f2();
	} catch (e) {
		console.error(e);
	}
	
	try {
		let x3: IThird  = <IThird> obj;
		x3.f3();
	} catch (e) {
		console.error(e);
	}
}

testObject(new Implementation());
testObject(new Incorrect());

```

**Expected behavior:**

Usual static type checks does not work to check if object implements one of multiple interfaces. Also we such code leads to runtime error, but it's an only single way to make overloaded functions and methods.

```
+f1
+f2
+f3
!f1(undefined)
+f2
TypeError: x3.f3 is not a function
    at testObject (/home/kol/WebstormProjects/ts-test/src/main.ts:227:6)
    at Object.<anonymous> (/home/kol/WebstormProjects/ts-test/src/main.ts:234:1)
    at Module._compile (module.js:569:30)
    at loader (/usr/lib/node_modules/ts-node/src/index.ts:288:14)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/lib/node_modules/ts-node/src/index.ts:305:14)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/usr/lib/node_modules/ts-node/src/_bin.ts:179:12)
```

**Comment by RyanCavanaugh** [comment]
https://stackoverflow.com/questions/14425568/interface-type-check-with-typescript
https://stackoverflow.com/questions/37543588/typescript-check-if-class-implements-an-interface
https://stackoverflow.com/questions/33800497/check-if-an-object-implements-an-interface-at-runtime-with-typescript
etc
