### ISSUE TITLE
TSlint: Fatal error: Cannot read property 'flags' of undefined tslint after upgrade to 2.4/2.3

### ISSUE THREAD

**Issue by ashubham** [Microsoft/TypeScript#16576]
**TypeScript Version:**  2.4.0 / 2.3.4

When running tslint I get the following error:
```
TypeError: Cannot read property 'flags' of undefined
    at Object.isExternalModuleSymbol (/home/ashish.shubham/thoughtspot/blink/node_modules/typescript/lib/typescript.js:71207:40)
    at getExportInfo (/home/ashish.shubham/thoughtspot/blink/node_modules/typescript/lib/typescript.js:75122:23)
    at exportInfo (/home/ashish.shubham/thoughtspot/blink/node_modules/typescript/lib/typescript.js:75082:34)
    at getExport (/home/ashish.shubham/thoughtspot/blink/node_modules/typescript/lib/typescript.js:75031:36)
    at Object.getImportOrExportSymbol (/home/ashish.shubham/thoughtspot/blink/node_modules/typescript/lib/typescript.js:75002:53)
    at getImportOrExportReferences (/home/ashish.shubham/thoughtspot/blink/node_modules/typescript/lib/typescript.js:75859:56)
    at getReferencesAtLocation (/home/ashish.shubham/thoughtspot/blink/node_modules/typescript/lib/typescript.js:75800:17)
    at getReferencesInContainer (/home/ashish.shubham/thoughtspot/blink/node_modules/typescript/lib/typescript.js:75754:21)
    at getReferencedSymbolsForSymbol (/home/ashish.shubham/thoughtspot/blink/node_modules/typescript/lib/typescript.js:75454:21)
    at Object.getReferencedSymbolsForNode (/home/ashish.shubham/thoughtspot/blink/node_modules/typescript/lib/typescript.js:75413:24)
```

It used to run fine with Typescript 2.2. I updated to tslint 5.4.x as mentioned in the #15436. But no luck.

**Comment by ashubham** [comment]
Sorry false alarm. `npm` did not update my tslint. Anyone here, please update tslint/grunt-tslint to resolve.
