### ISSUE TITLE
Convert to ES6 Class Refactoring: Debug Failure In consumeTokenAndAdvanceScanner

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16634]
**TypeScript Version:**  2.4.1-insiders.20170615

**Code**

```ts
function Wagon(numberOxen, occupants) {
    this.numberOxen = numberOxen
    this.occupants = occupants
    this.names = occupants.map(x => x.name)
}

new Wagon(1, []);
```

Trigger the `convert to es6 class` refactoring on `Wagon`

**Bug:**
Debug failure in `consumeTokenAndAdvanceScanner`. Here's the TSServer communications from VSCode

```
[Trace  - 5:55:29 PM] Sending request: getApplicableRefactors (11). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/zoo/src/ox.js",
    "startLine": 1,
    "startOffset": 10,
    "endLine": 1,
    "endOffset": 15
}
[Trace  - 5:55:29 PM] Response received: getApplicableRefactors (11). Request took 1 ms. Success: true 
Result: [
    {
        "name": "Convert to ES2015 class",
        "description": "Convert function to an ES2015 class",
        "actions": [
            {
                "description": "Convert function to an ES2015 class",
                "name": "convert"
            }
        ]
    }
]
[Trace  - 5:55:30 PM] Sending request: getEditsForRefactor (12). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/zoo/src/ox.js",
    "refactor": "Convert to ES2015 class",
    "action": "convert",
    "startLine": 1,
    "startOffset": 10,
    "endLine": 1,
    "endOffset": 15
}
[Trace  - 5:55:30 PM] Response received: getEditsForRefactor (12). Request took 37 ms. Success: false . Message: Error processing request. Debug Failure. 
Error: Debug Failure. 
    at consumeTokenAndAdvanceScanner (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70667:30)
    at processChildNodes (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70648:33)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70573:21
    at visitNodeArray (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:14903:20)
    at Object.forEachChild (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:14979:21)
    at processNode (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70570:20)
    at processChildNode (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70623:21)
    at processChildNodes (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70655:48)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70573:21
    at visitNodeArray (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:14903:20)
[Error  - 5:55:30 PM] 'getEditsForRefactor' request failed with error.
Error processing request. Debug Failure. 
Error: Debug Failure. 
    at consumeTokenAndAdvanceScanner (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70667:30)
    at processChildNodes (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70648:33)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70573:21
    at visitNodeArray (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:14903:20)
    at Object.forEachChild (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:14979:21)
    at processNode (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70570:20)
    at processChildNode (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70623:21)
    at processChildNodes (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70655:48)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:70573:21
    at visitNodeArray (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:14903:20)
[Trace  - 5:55:30 PM] Sending request: getApplicableRefactors (13). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/zoo/src/ox.js",
    "startLine": 1,
    "startOffset": 10,
    "endLine": 1,
    "endOffset": 15
}
[Trace  - 5:55:30 PM] Response received: getApplicableRefactors (13). Request took 10 ms. Success: true 
Result: [
    {
        "name": "Convert to ES2015 class",
        "description": "Convert function to an ES2015 class",
        "actions": [
            {
                "description": "Convert function to an ES2015 class",
                "name": "convert"
            }
        ]
    }
]
```

This seems to be caused by the line `this.names = occupants.map(x => x.name)`. After removing it, I can apply the refactor

**Comment by andy-ms** [comment]
That TypeScript version is `2.4.1-insiders.20170615`, latest is `2.7.0-dev.20171203`. Can't reproduce this in latest.
