### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by balazserdos** [Microsoft/TypeScript#16681]
**TypeScript Version:**  2.3.4

**Code**

```
\node_modules\typescript\lib\tsc.js:55708
                throw e;
                ^

TypeError: Cannot read property 'text' of undefined
    at Object.collectExternalModuleInfo (D:\Repositories\myProject\node_modules\typescript\lib\tsc.js:12923:56)
    at transformSourceFile (D:\Repositories\myProject\node_modules\typescript\lib\tsc.js:48632:36)
    at D:\Repositories\myProject\node_modules\typescript\lib\tsc.js:1148:86
    at reduceLeft (D:\Repositories\myProject\node_modules\typescript\lib\tsc.js:881:30)
    at D:\Repositories\myProject\node_modules\typescript\lib\tsc.js:1148:42
    at transformRoot (D:\Repositories\myProject\node_modules\typescript\lib\tsc.js:50318:82)
    at Object.map (D:\Repositories\myProject\node_modules\typescript\lib\tsc.js:477:29)
    at Object.transformNodes (D:\Repositories\myProject\node_modules\typescript\lib\tsc.js:50307:30)
    at Object.emitFiles (D:\Repositories\myProject\node_modules\typescript\lib\tsc.js:52665:28)
    at emitWorker (D:\Repositories\myProject\node_modules\typescript\lib\tsc.js:55650:33)
```

TS config
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "ES2015",
        "noImplicitAny": false,
        "sourceMap": true
    },
    "exclude": [
        "node_modules/*",
        "documents/*"
    ]
}

```

**Actual behavior:**
when I'm running the transpilation nodejs throws an error.

**Expected behavior:**
some readable error messages to the output if I'm doing something wrong

**Comment by balazserdos** [comment]
it was caused because the code generator created a class with no name. 
name "default" has the same effect

**Comment by balazserdos** [comment]
try to compile this, it shouldn't throw nodejs exception

> export class {
>     private foo: string;
> }
