### ISSUE TITLE
gulp local fails

### ISSUE THREAD

**Issue by tmkn** [Microsoft/TypeScript#16775]
I tried to follow the build instructions and upon entering `gulp local` it errors with
```
C:\Users\dev\TypeScript>gulp local
[22:18:03] Requiring external module ts-node/register

C:\Users\dev\TypeScript\node_modules\ts-node\src\index.ts:296
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
gulpfile.ts (1040,30): Type 'string[]' has no properties in common with type 'WatchOptions'. (2559)
    at getOutput (C:\Users\dev\TypeScript\node_modules\ts-node\src\index.ts:296:15)
    at C:\Users\dev\TypeScript\node_modules\ts-node\src\index.ts:325:16
    at Object.compile (C:\Users\dev\TypeScript\node_modules\ts-node\src\index.ts:479:11)
    at Module.m._compile (C:\Users\dev\TypeScript\node_modules\ts-node\src\index.ts:379:43)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\dev\TypeScript\node_modules\ts-node\src\index.ts:382:12)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```
**gulpfile.ts (1040,30)** refers to this:
`gulp.watch("src/**/*.*", ["runtests-parallel"]);`

This happens on master so I checked out tag v2.3.1 and I get the same error there as well.
If I overrule the compiler it runs through, with tests working:
`gulp.watch("src/**/*.*", ["runtests-parallel"] as any);`
So I guess the definition file is wrong ¯\\_(ツ)_/¯

**Comment by DanielRosenwasser** [comment]
@weswigham has #16775 out to fix this.
