### ISSUE TITLE
Question: How to build and debug tsc?

### ISSUE THREAD

**Issue by ifle** [Microsoft/TypeScript#16901]
How to build and debug tsc? 
I not found any documentation about build

**Comment by olegdunkan** [comment]
https://github.com/Microsoft/TypeScript#building

**Comment by olegdunkan** [comment]
Debug https://code.visualstudio.com/docs/editor/debugging

**Comment by ifle** [comment]
Thanks.
I tried to compile and got a lot of errors
```ts
D:\Dev\GitHub\TypeScript\TypeScript>gulp local
[17:48:25] Requiring external module ts-node/register

D:\Dev\GitHub\TypeScript\TypeScript\node_modules\ts-node\src\index.ts:300
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset)
)
              ^
TSError: ? Unable to compile TypeScript
Cannot find type definition file for 'browserify'. (2688)
Cannot find type definition file for 'chai'. (2688)
Cannot find type definition file for 'chokidar'. (2688)
Cannot find type definition file for 'convert-source-map'. (2688)
Cannot find type definition file for 'del'. (2688)
Cannot find type definition file for 'glob'. (2688)
Cannot find type definition file for 'glob-stream'. (2688)
Cannot find type definition file for 'gulp'. (2688)
Cannot find type definition file for 'gulp-concat'. (2688)
Cannot find type definition file for 'gulp-help'. (2688)
Cannot find type definition file for 'gulp-newer'. (2688)
Cannot find type definition file for 'gulp-sourcemaps'. (2688)
Cannot find type definition file for 'insert-module-globals'. (2688)
Cannot find type definition file for 'merge2'. (2688)
Cannot find type definition file for 'minimatch'. (2688)
Cannot find type definition file for 'minimist'. (2688)
Cannot find type definition file for 'mkdirp'. (2688)
Cannot find type definition file for 'mocha'. (2688)
Cannot find type definition file for 'node'. (2688)
Cannot find type definition file for 'orchestrator'. (2688)
Cannot find type definition file for 'q'. (2688)
Cannot find type definition file for 'run-sequence'. (2688)
Cannot find type definition file for 'through2'. (2688)
Cannot find type definition file for 'undertaker'. (2688)
Cannot find type definition file for 'undertaker-registry'. (2688)
Cannot find type definition file for 'vinyl'. (2688)
Cannot find type definition file for 'vinyl-fs'. (2688)
gulpfile.ts (2,21): Cannot find module 'child_process'. (2307)
gulpfile.ts (3,23): Cannot find module 'path'. (2307)
gulpfile.ts (4,21): Cannot find module 'fs'. (2307)
gulpfile.ts (5,32): Cannot find module 'child_process'. (2307)
gulpfile.ts (6,31): Cannot find module 'gulp'. (2307)
gulpfile.ts (7,28): Cannot find module 'gulp-help'. (2307)
gulpfile.ts (8,30): Cannot find module 'run-sequence'. (2307)
gulpfile.ts (9,25): Cannot find module 'gulp-concat'. (2307)
gulpfile.ts (11,24): Cannot find module 'gulp-newer'. (2307)
gulpfile.ts (12,22): Cannot find module 'gulp-typescript'. (2307)
gulpfile.ts (13,16): Invalid module name in augmentation, module 'gulp-typescrip
t' cannot be found. (2664)
gulpfile.ts (23,29): Cannot find module 'gulp-sourcemaps'. (2307)
gulpfile.ts (24,20): Cannot find module 'q'. (2307)
gulpfile.ts (25,22): Cannot find module 'del'. (2307)
gulpfile.ts (26,25): Cannot find module 'mkdirp'. (2307)
gulpfile.ts (27,27): Cannot find module 'minimist'. (2307)
gulpfile.ts (28,29): Cannot find module 'browserify'. (2307)
gulpfile.ts (29,27): Cannot find module 'through2'. (2307)
gulpfile.ts (30,25): Cannot find module 'merge2'. (2307)
gulpfile.ts (32,21): Cannot find module 'os'. (2307)
gulpfile.ts (35,23): Cannot find name 'require'. (2304)
gulpfile.ts (38,7): Property 'stackTraceLimit' does not exist on type 'ErrorCons
tructor'. (2339)
gulpfile.ts (40,33): Cannot find name 'process'. (2304)
gulpfile.ts (55,17): Cannot find name 'process'. (2304)
gulpfile.ts (55,39): Cannot find name 'process'. (2304)
gulpfile.ts (56,16): Cannot find name 'process'. (2304)
gulpfile.ts (56,37): Cannot find name 'process'. (2304)
gulpfile.ts (56,65): Cannot find name 'process'. (2304)
gulpfile.ts (57,18): Cannot find name 'process'. (2304)
gulpfile.ts (57,41): Cannot find name 'process'. (2304)
gulpfile.ts (57,71): Cannot find name 'process'. (2304)
gulpfile.ts (58,15): Cannot find name 'process'. (2304)
gulpfile.ts (58,46): Cannot find name 'process'. (2304)
gulpfile.ts (59,18): Cannot find name 'process'. (2304)
gulpfile.ts (59,41): Cannot find name 'process'. (2304)
gulpfile.ts (60,18): Cannot find name 'process'. (2304)
gulpfile.ts (61,16): Cannot find name 'process'. (2304)
gulpfile.ts (61,36): Cannot find name 'process'. (2304)
gulpfile.ts (61,57): Cannot find name 'process'. (2304)
gulpfile.ts (62,16): Cannot find name 'process'. (2304)
gulpfile.ts (63,19): Cannot find name 'process'. (2304)
gulpfile.ts (63,43): Cannot find name 'process'. (2304)
gulpfile.ts (64,15): Cannot find name 'process'. (2304)
gulpfile.ts (65,16): Cannot find name 'process'. (2304)
gulpfile.ts (65,33): Cannot find name 'process'. (2304)
gulpfile.ts (65,53): Cannot find name 'process'. (2304)
gulpfile.ts (66,18): Cannot find name 'process'. (2304)
gulpfile.ts (105,27): Cannot find name 'process'. (2304)
gulpfile.ts (275,27): Cannot find name 'require'. (2304)
gulpfile.ts (278,27): Cannot find name 'require'. (2304)
gulpfile.ts (478,28): Cannot find namespace 'NodeJS'. (2503)
gulpfile.ts (478,56): Cannot find namespace 'NodeJS'. (2503)
gulpfile.ts (589,20): Cannot find name 'process'. (2304)
gulpfile.ts (590,5): Cannot find name 'process'. (2304)
gulpfile.ts (594,5): Cannot find name 'process'. (2304)
gulpfile.ts (697,9): Cannot find name 'process'. (2304)
gulpfile.ts (744,29): Cannot find module 'convert-source-map'. (2307)
gulpfile.ts (746,16): Invalid module name in augmentation, module 'convert-sourc
e-map' cannot be found. (2664)
gulpfile.ts (747,72): Cannot find name 'SourceMapConverter'. (2304)
gulpfile.ts (771,41): Cannot find name 'Buffer'. (2304)
gulpfile.ts (819,51): Cannot find name 'process'. (2304)
gulpfile.ts (849,21): Cannot find name 'process'. (2304)
gulpfile.ts (852,9): Cannot find name 'process'. (2304)
gulpfile.ts (941,51): Cannot find name 'process'. (2304)
    at getOutput (D:\Dev\GitHub\TypeScript\TypeScript\node_modules\ts-node\src\i
ndex.ts:300:15)
    at D:\Dev\GitHub\TypeScript\TypeScript\node_modules\ts-node\src\index.ts:330
:16
    at Object.compile (D:\Dev\GitHub\TypeScript\TypeScript\node_modules\ts-node\
src\index.ts:489:17)
    at Module.m._compile (D:\Dev\GitHub\TypeScript\TypeScript\node_modules\ts-no
de\src\index.ts:382:43)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\Dev\GitHub\Ty
peScript\TypeScript\node_modules\ts-node\src\index.ts:385:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by samvv** [comment]
Did you run `npm install`?

**Comment by ifle** [comment]
Yes,
I've cloned the release-2.4 branch.
Run npm install -g gulp and npm install on Typescript folder

**Comment by ifle** [comment]
I've cloned again the and now have not errors
