### ISSUE TITLE
"Maximum call stack size exceeded" with recursive type parameter default

### ISSUE THREAD

**Issue by WasabiFan** [Microsoft/TypeScript#17049]
**TypeScript Version:**  2.3.4, 2.4.1

**Code**

```ts
class TestClass<T = TestClass> {

}
```

**Expected behavior:**

The code compiles such that I could reference the type in any of the following ways:

```ts
TestClass
TestClass<TestClass>
TestClass<MyOtherTestClassImplementation>
```

**Actual behavior (`v2.3.4`):**

```
C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:53887
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at Map.get (native)
    at getSymbol (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:21268:38)
    at resolveName (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:21453:38)
    at resolveEntityName (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:21881:26)
    at getTypeFromTypeReference (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:26096:54)
    at getTypeFromTypeNode (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:26880:28)
    at getDefaultFromTypeParameter (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:25333:66)
    at getMinTypeArgumentCount (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:25585:26)
    at getTypeFromClassOrInterfaceReference (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:25955:44)
    at getTypeFromTypeReference (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:26098:52)
```

Presumably this was introduced in #13487.

**Comment by ikatyang** [comment]
It seems duplicate of https://github.com/Microsoft/TypeScript/issues/16533.

**Comment by WasabiFan** [comment]
Good catch. My searches for "generic" and "generics" didn't match up with the terms used over in that issue.
