### ISSUE TITLE
specified ITextSnapshot doesn't belong to the correct TextBuffer

### ISSUE THREAD

**Issue by DickvdBrink** [Microsoft/TypeScript#1710]
Visual Studio 2013 version: 12.0.31101.0 and TS1.4

>System.ArgumentException: The specified ITextSnapshot doesn't belong to the correct TextBuffer.
       at Microsoft.VisualStudio.Text.SnapshotSpan.TranslateTo(ITextSnapshot targetSnapshot, SpanTrackingMode spanTrackingMode)
       at TypeScriptLanguageService.Features.HighlightReferences.HighlightReferencesController.&lt;GetTags&gt;d__7.MoveNext()
       at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__5.MoveNext()

Not really sure what I was doing, but I was editing some TypeScript file using the Virtual Project method (so without a solution), the below activity log **is edited** because it is really big.. if you want I can send the full one by email or somethhing :)

```
    <?xml version="1.0" encoding="utf-16"?>
    <?xml-stylesheet type="text/xsl" href="ActivityLog.xsl"?>
    <activity>
        <entry>
            <record>1</record>
            <time>2015/01/17 18:40:50.210</time>
            <type>Information</type>
            <source>VisualStudio</source>
            <description>Microsoft Visual Studio 2013 version: 12.0.31101.0</description>
        </entry>
        <entry>
            <record>2</record>
            <time>2015/01/17 18:40:50.210</time>
            <type>Information</type>
            <source>VisualStudio</source>
            <description>Running in User Groups: Users</description>
        </entry>
        <entry>
            <record>3</record>
            <time>2015/01/17 18:40:50.210</time>
            <type>Information</type>
            <source>VisualStudio</source>
            <description>Available Drive Space: C:\ drive has 11509719040 bytes</description>
        </entry>
        <entry>
            <record>4</record>
            <time>2015/01/17 18:40:50.213</time>
            <type>Information</type>
            <source>VisualStudio</source>
            <description>Internet Explorer Version: 11.0.9600.17496</description>
        </entry>
        <entry>
            <record>5</record>
            <time>2015/01/17 18:40:50.215</time>
            <type>Information</type>
            <source>VisualStudio</source>
            <description>.NET Framework Version: 6.3.9600.16384</description>
        </entry>
        <entry>
            <record>6</record>
            <time>2015/01/17 18:40:50.217</time>
            <type>Information</type>
            <source>VisualStudio</source>
            <description>MSXML Version: 6.30.9600.17415</description>
        </entry>
        <entry>
            <record>7</record>
            <time>2015/01/17 18:40:50.242</time>
            <type>Information</type>
            <source>Microsoft Visual Studio Appid Stub</source>
            <description>Application launch on system with DPI X/Y: 144/144</description>
        </entry>
        <entry>
            <record>8</record>
            <time>2015/01/17 18:40:50.453</time>
            <type>Information</type>
            <source>VisualStudio</source>
            <description>Entering function CVsPackageInfo::HrInstantiatePackage</description>
            <guid>{00CD9DDA-7350-457C-A240-71BD667FC4DE}</guid>
        </entry>
        <entry>
            <record>9</record>
            <time>2015/01/17 18:40:50.453</time>
            <type>Information</type>
            <source>VisualStudio</source>
            <description>Begin package load [Task Scheduler Package]</description>
            <guid>{00CD9DDA-7350-457C-A240-71BD667FC4DE}</guid>
        </entry>
        <entry>
            <record>10</record>
            <time>2015/01/17 18:40:50.468</time>
            <type>Information</type>
            <source>Package Framework</source>
            <description>Initialized ServiceProvider.GlobalProvider from SetSite.</description>
        </entry>
        <entry>
            <record>720</record>
            <time>2015/01/17 18:41:00.638</time>
            <type>Information</type>
            <source>VisualStudio</source>
            <description>Entering function VBDispatch::GetTypeLib</description>
        </entry>
        <entry>
            <record>721</record>
            <time>2015/01/17 18:41:00.638</time>
            <type>Information</type>
            <source>VisualStudio</source>
            <description>Leaving function VBDispatch::GetTypeLib</description>
        <entry>
            <record>819</record>
            <time>2015/01/17 18:43:19.099</time>
            <type>Error</type>
            <source>Editor or Editor Extension</source>
            <description>System.ArgumentException: The specified ITextSnapshot doesn't belong to the correct TextBuffer.
       at Microsoft.VisualStudio.Text.SnapshotSpan.TranslateTo(ITextSnapshot targetSnapshot, SpanTrackingMode spanTrackingMode)
       at TypeScriptLanguageService.Features.HighlightReferences.HighlightReferencesController.&lt;GetTags&gt;d__7.MoveNext()
       at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__5.MoveNext()</description>
        </entry>
    </activity>
```

**Comment by NoelAbrahams** [comment]
Same error as #1153

**Comment by DickvdBrink** [comment]
@NoelAbrahams, thanks!
Closing
