### ISSUE TITLE
Cannot read `kind` of undefined in getOccurrencesAtPosition

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#17245]
From: https://github.com/Microsoft/vscode/issues/30774

**TypeScript Version:**  2.4.1
**Code**

For a js/ts file:

```ts
// Comment.
```

Call `getOccurrencesAtPosition` on a tsLanguageService instance for a position within the comment

**Bug:**

```
Exception has occurred: Error
TypeError: Cannot read property 'kind' of undefined
    at Object.isJsxOpeningElement (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/typescript.js:11058:20)
    at Object.getDocumentHighlights (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/typescript.js:76604:20)
    at getDocumentHighlights (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/typescript.js:89401:42)
    at getOccurrencesAtPositionCore (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/typescript.js:89404:46)
    at Object.getOccurrencesAtPosition (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/typescript.js:89388:27)
    at Object.findDocumentHighlight (/Users/matb/projects/vscode/extensions/html/server/out/modes/javascriptMode.js:163:49)
    at /Users/matb/projects/vscode/extensions/html/server/out/htmlServerMain.js:180:21
    at handleRequest (/Users/matb/projects/vscode/extensions/html/server/node_modules/vscode-jsonrpc/lib/main.js:235:37)
    at process.callback (/Users/matb/projects/vscode/extensions/html/server/node_modules/vscode-jsonrpc/lib/main.js:471:13)
    at emitTwo (events.js:106:13)
```

**Comment by andy-ms** [comment]
I can reproduce this in `typescript@2.4`, but not in `typescript@next`.
