### ISSUE TITLE
Exception for spelling suggestions thrown while editing

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#17460]
It's a bit difficult to repro this, but here's the stack trace

```
TypeError: Cannot read property 'length' of undefined
    at Object.unescapeLeadingUnderscores (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:8552:18)
    at Object.getSuggestionForNonexistentProperty (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:19514:84)
    at Object.getActionsForCorrectSpelling [as getCodeActions] (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:72770:38)
    at C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:72526:33
    at Object.forEach (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:1291:30)
    at Object.getFixes (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:72525:16)
    at C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:75371:35
    at Object.flatMap (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:1524:25)
    at Object.getCodeFixesAtPosition (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:75369:23)
    at IOSession.Session.getCodeFixes (C:\Users\drosen\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:81264:64)
```

**Comment by weswigham** [comment]
`getSuggestionForNonexistentProperty` can return `undefined`, but `unescapeLeadingUnderscores` and `escapeLeadingUnderscores` (previously `unescapeIdentifier` and `escapeIdentifier`) are not `undefined`-propagating functions. The services layer will handle the `undefined` return just fine, so I've opened #17465 to make them `undefined`-propagating.
