### ISSUE TITLE
TSServer exited with code: 3 from VS Code

### ISSUE THREAD

**Issue by jackhorton** [Microsoft/TypeScript#17605]
**TypeScript Version:**  2.3.4, 2.4.2, possibly others (hard to repro), both built-in to VS Code and manually set with `"typescript.tsdk"`

**Code**: I have only seen this happen on https://github.com/Microsoft/node-diagnostic-channel

**Expected behavior:** TypeScript Language Server doesn't continually crash

**Actual behavior:** TypeScript Language Server crashes about once per minute after an indeterminate time (usually at least an hour) of running just fine, regardless of whether or not I am actively editing any code. Resetting the tsdk seems to help a bit, but relaunching VS Code does not. Restarting the computer does help.

Sometimes stack traces are printed, but they're never particularly useful. Here's some sample output:

```
[Info  - 6:14:17 PM] Using tsserver from: C:\Users\jahorto\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js
[Info  - 6:14:17 PM] Forking TSServer
PATH: undefined
[Error  - 6:15:03 PM] TSServer exited with code: 3
[Error  - 6:15:03 PM] 'signatureHelp' request failed with error.
Error: Service died.
    at TypeScriptServiceClient.serviceExited (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:650:32)
    at ChildProcess.childProcess.on (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:454:34)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 6:15:03 PM] Using tsserver from: C:\Users\jahorto\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js
[Info  - 6:15:03 PM] Forking TSServer
PATH: undefined
[Error  - 6:16:01 PM] TSServer exited with code: 3
[Info  - 6:16:01 PM] Using tsserver from: C:\Users\jahorto\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js
[Info  - 6:16:01 PM] Forking TSServer
PATH: undefined
[Error  - 6:16:55 PM] TSServer exited with code: 3
[Info  - 6:16:55 PM] Using tsserver from: C:\Users\jahorto\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js
[Info  - 6:16:55 PM] Forking TSServer
PATH: undefined
[Error  - 6:17:46 PM] TSServer exited with code: 3
[Info  - 6:17:46 PM] Using tsserver from: C:\Users\jahorto\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js
[Info  - 6:17:46 PM] Forking TSServer
PATH: undefined
[Error  - 6:18:43 PM] TSServer exited with code: 3
[Info  - 6:18:43 PM] Using tsserver from: C:\Users\jahorto\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js
[Info  - 6:18:43 PM] Forking TSServer
PATH: undefined
[Error  - 6:19:40 PM] TSServer exited with code: 3
[Info  - 6:19:40 PM] Using tsserver from: C:\Users\jahorto\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js
[Info  - 6:19:40 PM] Forking TSServer
PATH: undefined
[Error  - 6:20:40 PM] TSServer exited with code: 3
[Info  - 6:20:40 PM] Using tsserver from: C:\Users\jahorto\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js
[Info  - 6:20:40 PM] Forking TSServer
PATH: undefined
[Error  - 6:21:26 PM] TSServer exited with code: 3
[Info  - 6:21:26 PM] Using tsserver from: C:\Users\jahorto\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js
[Info  - 6:21:26 PM] Forking TSServer
PATH: undefined

```

**Comment by mhegazy** [comment]
Can you share the full server log please? (VSCode command "Open TS server log" should get you to it).

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
