### ISSUE TITLE
Exception when compiling weird JS: TypeError: Cannot read property 'modifiers' of undefined

### ISSUE THREAD

**Issue by Rob-ot** [Microsoft/TypeScript#17666]
**TypeScript Version:**  2.4.2 / nightly (2.5.0-dev.20170807)

**Code**

```ts

class Parent {
  initialize() {
    super.initialize(...arguments)
    return this.asdf = ''
  }
}

class Child extends Parent {
  initialize() {
  }
}
```
I run this command to compile: `tsc --allowjs ./File.js  --outDir ../`

**Expected behavior:**
Code should compile successfully.

**Actual behavior:**
An exception is thrown and the compiler fails. Message:
```
C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:56045
                throw e;
                ^

TypeError: Cannot read property 'modifiers' of undefined
    at symbolToParameterDeclaration (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:20398:53)
    at C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:20357:89
    at Array.map (native)
    at signatureToSignatureDeclarationHelper (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:20357:55)
    at createTypeNodeFromObjectType (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:20176:49)
    at createAnonymousTypeNode (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:20144:42)
    at typeToTypeNodeHelper (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:20099:28)
    at Object.typeToTypeNode (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:19979:41)
    at typeToString (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:19939:40)
    at reportRelationError (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:25312:34)
    at isRelatedTo (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:25429:21)
    at propertiesRelatedTo (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:25833:43)
    at structuredTypeRelatedTo (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:25739:38)
    at recursiveTypeRelatedTo (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:25629:53)
    at isRelatedTo (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:25416:38)
    at checkTypeRelatedTo (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:25295:26)
    at checkTypeAssignableTo (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:25034:20)
    at checkClassLikeDeclaration (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:34540:21)
    at checkClassDeclaration (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:34494:13)
    at checkSourceElement (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35428:28)
    at Object.forEach (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:267:30)
    at checkSourceFileWorker (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35497:20)
    at checkSourceFile (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35482:13)
    at Object.forEach (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:267:30)
    at getDiagnosticsWorker (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35547:16)
    at getDiagnostics (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35524:24)
    at Object.getEmitResolver (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:18567:13)
    at emitWorker (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:55984:69)
    at C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:55960:66
    at runWithCancellationToken (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:56038:24)
    at Object.emit (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:55960:20)
    at compileProgram (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:58968:38)
    at compile (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:58922:26)
    at performCompilation (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:58811:33)
    at Object.executeCommandLine (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:58754:9)
    at Object.<anonymous> (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:59112:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\rob\AppData\Roaming\npm\node_modules\typescript\bin\tsc:2:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

This exception came up when trying TS on an existing JS codebase. I reduced the project down to this repro. I am able to work around the bug but I wanted to report the issue anyway. Thanks!

**Comment by psachs21** [comment]
This looks likely to be the issue that I've run into. I'll close #17661 because this issue has more details for reproduction steps.
