### ISSUE TITLE
tsc fails for unknown reason

### ISSUE THREAD

**Issue by psachs21** [Microsoft/TypeScript#17661]
**TypeScript Version:**  2.4.2

**Code**

My code base is too large to provide a reasonable reproduction steps, I do not know where the issue is so it's difficult to narrow the code.

**Expected behavior:**

Running compiler should output code.

**Actual behavior:**

Exception is thrown:

```
~/project/node_modules/typescript/lib/tsc.js:55776
                throw e;
                ^

TypeError: Cannot read property 'modifiers' of undefined
    at symbolToParameterDeclaration (~/project/node_modules/typescript/lib/tsc.js:23985:53)
    at ~/project/node_modules/typescript/lib/tsc.js:23944:89
    at Array.map (native)
    at signatureToSignatureDeclarationHelper (~/project/node_modules/typescript/lib/tsc.js:23944:55)
    at createTypeNodeFromObjectType (~/project/node_modules/typescript/lib/tsc.js:23764:49)
    at createAnonymousTypeNode (~/project/node_modules/typescript/lib/tsc.js:23730:42)
    at typeToTypeNodeHelper (~/project/node_modules/typescript/lib/tsc.js:23685:28)
    at Object.typeToTypeNode (~/project/node_modules/typescript/lib/tsc.js:23565:41)
    at typeToString (~/project/node_modules/typescript/lib/tsc.js:23525:40)
    at reportRelationError (~/project/node_modules/typescript/lib/tsc.js:28854:34)
```

**Comment by gcnew** [comment]
https://github.com/Microsoft/TypeScript/issues/17666 has the same error.

**Comment by psachs21** [comment]
#17666 has more details. Closing in preference for an issue with better reproduction steps.
