### ISSUE TITLE
Error: Debug Failure. False expression: should always get typenode

### ISSUE THREAD

**Issue by ktalebian** [Microsoft/TypeScript#17865]
When I build my application with webpack, I get the following error:

```
94% asset optimization/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:69795
                throw e;
                ^

Error: Debug Failure. False expression: should always get typenode
    at typeToString (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:28777:22)
    at reportRelationError (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:34714:34)
    at isRelatedTo (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:34860:21)
    at checkTypeRelatedTo (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:34697:26)
    at checkTypeAssignableTo (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:34398:20)
    at checkVariableLikeDeclaration (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:44884:21)
    at checkPropertyDeclaration (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:43383:13)
    at checkSourceElement (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:46700:28)
    at Object.forEach (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:1506:30)
    at checkClassDeclaration (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:45765:16)
    at checkSourceElement (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:46779:28)
    at Object.forEach (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:1506:30)
    at checkSourceFileWorker (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:46862:20)
    at checkSourceFile (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:46842:13)
    at getDiagnosticsWorker (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:46906:17)
    at Object.getDiagnostics (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:46892:24)
    at /Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:69814:85
    at runWithCancellationToken (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:69779:24)
    at getSemanticDiagnosticsForFileNoCache (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:69802:20)
    at getAndCacheDiagnostics (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:70033:26)
    at getSemanticDiagnosticsForFile (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:69799:20)
    at getDiagnosticsHelper (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:69738:24)
    at Object.getSemanticDiagnostics (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:69751:20)
    at Object.getSemanticDiagnostics (/Users/ktalebian/Projects/react/console-debugger/node_modules/typescript/lib/typescript.js:89302:47)
    at /Users/ktalebian/Projects/react/console-debugger/node_modules/ts-loader/dist/after-compile.js:93:95
    at Array.forEach (native)
    at provideErrorsToWebpack (/Users/ktalebian/Projects/react/console-debugger/node_modules/ts-loader/dist/after-compile.js:92:10)
    at Compiler.<anonymous> (/Users/ktalebian/Projects/react/console-debugger/node_modules/ts-loader/dist/after-compile.js:22:9)
    at next (/Users/ktalebian/Projects/react/console-debugger/node_modules/tapable/lib/Tapable.js:204:14)
    at Compiler.<anonymous> (/Users/ktalebian/Projects/react/console-debugger/node_modules/webpack/lib/CachePlugin.js:62:5)
```

TSConfig is

```json
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": true,
    "module": "es6",
    "target": "es5",
    "jsx": "react",
    "allowJs": true,
    "preserveConstEnums": true,
    "removeComments": true,
    "noImplicitAny": false,
    "moduleResolution": "node",
    "noUnusedParameters": true
  },
  "include": [
    "./src/**/*"
  ],
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts",
    "typings/index.d.ts"
  ],
  "paths": {
    "react": ["node_modules/@types/react"]
  }
}
```

And here is my webpack config

```js
{ entry: { myApp: './src/js/index.tsx' },
  output:
   { path: '/path/to/myApp/dist/js',
     filename: '[name].js',
     publicPath: '/' },
  module:
   { loaders:
      [ { test: /(\.jsx|\.js)$/,
          include: '/path/to/myApp/src',
          loader: 'babel-loader' },
        { test: /\.json$/, loader: 'json-loader' },
        { test: /\.module.(less|css)$/,
          loader: 'style-loader!css-loader?modules&camelCase=dashes&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!less-loader' },
        { test: /^((?!\.module).)*(less|css)$/,
          loader: 'style-loader!css-loader!less-loader' },
        { test: /\.tsx?$/,
          loader: 'ts-loader',
          exclude: [ 'node_modules' ] } ] },
  externals:
   { lodash: 'lodash',
     moment: 'moment',
     urijs: 'urijs',
     log4js: 'log4js' },
  resolve:
   { extensions: [ '.js', '.jsx', '.json', '.less', '.css', '.ts', '.tsx', '.json' ],
     alias:
      { react: '/path/to/myApp/node_modules/react',
        React: '/path/to/myApp/node_modules/react',
        ReactDom: '/path/to/myApp/node_modules/react-dom',
        ReactDOM: '/path/to/myApp/node_modules/react-dom',
        'react-dom': '/path/to/myApp/node_modules/react-dom',
        sinon: '/path/to/myApp/node_modules/sinon/pkg/sinon' },
     modules:
      [ '/path/to/myApp',
        'node_modules' ] },
  plugins:
   [ DefinePlugin {
       definitions:
        { ENV_DEV: 'false',
          ENV_PROD: 'true',
          'process.env.NODE_ENV': '"production"' } },
     LoaderOptionsPlugin {
       options:
        { minimize: true,
          debug: false,
          test: { test: [Function: test] } } },
     [Function] ],
  devServer: {},
  bail: true }
```

This happened after I updated Tyepscript to 2.4.2

**Comment by ktalebian** [comment]
I fixed the problem as commented on https://github.com/Microsoft/TypeScript/issues/17365#issuecomment-323161716
