### ISSUE TITLE
Convert To ES6 Class Refactoring fails when one of the methods contains a conditional operator

### ISSUE THREAD

**Issue by hbenl** [Microsoft/TypeScript#17946]
**TypeScript Version:**  nightly (2.6.0-dev.20170819)

**Code**

```ts
function MyClass() {
}
MyClass.prototype.myMethod = function(x) {
    return (x === 'foo') ? 'bar' : 'baz';
}
```
Open this in VS Code and try to apply the "Convert function to an ES2015 class" refactoring

**Expected behavior:**
The code is refactored into an ES6 class.

**Actual behavior:**
Nothing happens in the editor.
The Typescript output viewlet in VS Code shows this error:
```
[Error  - 6:11:38 PM] 'getEditsForRefactor' request failed with error.
Error processing request. Debug Failure. 
Error: Debug Failure. 
    at processChildNode (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:70626:34)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:70580:21
    at visitNode (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:14898:20)
    at Object.forEachChild (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:15067:21)
    at processNode (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:70579:20)
    at processChildNode (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:70632:21)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:70580:21
    at visitNode (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:14898:20)
    at Object.forEachChild (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:15115:24)
    at processNode (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:70579:20)
```

For completeness, here's my tsconfig.json:
```
{
    "compilerOptions": {
        "outDir": "out",
        "allowJs": true
    },
    "files": [
        "index.js"
    ]
}
```

**Comment by amcasey** [comment]
Hey @hbenl, sorry for the delay.  I can repro this issue with TS SDK 2.5, but not in master, so it appears to have been fixed.  I'll try to pin it down so we can be more precise about when the fix will be available.

**Comment by amcasey** [comment]
More specifically, it repros in tag `v2.5.2` but not in branch `release-2.5`.  So a fix is coming. :)

**Comment by amcasey** [comment]
Let me know if having a particular commit number is important to you and I'll look deeper.

**Comment by amcasey** [comment]
For the sake of completeness, I've confirmed that this has also been fixed in `master` (i.e. 2.6).
