### ISSUE TITLE
TypeError with JSDoc return annotation

### ISSUE THREAD

**Issue by tsvetomir** [Microsoft/TypeScript#18011]
**TypeScript Version:**  2.4.2

**Code**

Note that this is compiled with `--alowJs`:

```js
'use strict';

/**
 * @return {function(...params: *): void}
 */
function create(func, selector, scheduler) {
    return function () {
        var args = arguments;
    };
}
```

**Expected behavior:**
No errors.

**Actual behavior:**
The compiler outputs the following error:

```
/tmp/ts-rxjs/node_modules/typescript/lib/tsc.js:55776
                throw e;
                ^

TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (/tmp/ts-rxjs/node_modules/typescript/lib/tsc.js:7350:17)
    at assignContextualParameterTypes (/tmp/ts-rxjs/node_modules/typescript/lib/tsc.js:34465:25)
    at checkFunctionExpressionOrObjectLiteralMethod (/tmp/ts-rxjs/node_modules/typescript/lib/tsc.js:34717:29)
    at checkExpressionWorker (/tmp/ts-rxjs/node_modules/typescript/lib/tsc.js:35590:28)
    at checkExpression (/tmp/ts-rxjs/node_modules/typescript/lib/tsc.js:35534:42)
    at checkExpressionCached (/tmp/ts-rxjs/node_modules/typescript/lib/tsc.js:35450:38)
    at checkReturnStatement (/tmp/ts-rxjs/node_modules/typescript/lib/tsc.js:37556:54)
    at checkSourceElement (/tmp/ts-rxjs/node_modules/typescript/lib/tsc.js:38751:28)
    at Object.forEach (/tmp/ts-rxjs/node_modules/typescript/lib/tsc.js:298:30)
    at checkBlock (/tmp/ts-rxjs/node_modules/typescript/lib/tsc.js:36918:16)
```

Removing either the `return` JSDoc annotation or the reference to arguments solves the issue.

**Comment by mhegazy** [comment]
seems fixed in latest.

```sh
c:\test\18011>type a.js
'use strict';

/**
 * @return {function(...params: *): void}
 */
function create(func, selector, scheduler) {
    return function () {
        var args = arguments;
    };
}

c:\test\18011>tsc --v
Version 2.5.0-dev.20170816

c:\test\18011>tsc --allowjs a.js --outDir ./out

c:\test\18011>type out\a.js
'use strict';
/**
 * @return {function(...params: *): void}
 */
function create(func, selector, scheduler) {
    return function () {
        var args = arguments;
    };
}

```
