### ISSUE TITLE
tslib_1 is not defined

### ISSUE THREAD

**Issue by rohmanhm** [Microsoft/TypeScript#18039]
**TypeScript Version:**  nightly (2.5.0-dev.201xxxxx)

**Code**
tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": [
      "dom",
      "dom.iterable",
      "es6"
    ],
    "importHelpers": true,
    "noUnusedLocals": true,
    "declaration": true,
    "sourceMap": true,
    "outDir": "./lib",
    "rootDir": "./src",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitReturns": true,
    "typeRoots": [
      "node_modules/@types",
      "typings"
    ],
    "experimentalDecorators": true
  }
}

```

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
Code run without error.

**Actual behavior:**
I got an error `Error: Error: Evaluation failed: ReferenceError: tslib_1 is not defined`. I don't have reproduction code, But I think it's because of tslib. I have install `tslib` and set `"importHelpers": true` to `tsconfig.json` file. Am I missing something?

The Error
```bash
Exception has occurred: Error
Error: Error: Evaluation failed: ReferenceError: tslib_1 is not defined
    at <anonymous>:1:16
    at <anonymous>:24:35
    at <anonymous>:1:16
    at <anonymous>:24:35
    at Shopee.<anonymous> (path/index.ts:51:13)
    at step (path/node_modules/tslib/tslib.js:122:27)
    at Object.throw (path/node_modules/tslib/tslib.js:103:57)
    at rejected (path/node_modules/tslib/tslib.js:94:69)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ikatyang** [comment]
Maybe related #17192.

**Comment by mhegazy** [comment]
@rohmanhm please provide **self-contained** reproduction of the issue.

**Comment by rohmanhm** [comment]
@mhegazy I don't get any error when running `tsc`. The error just appears when runtime or debugging.

Should I import `tslib` package into my `.ts` file?

Before I got this error, I got error undefined `__awaiter` then I enable `importHelpers` to `true` after that I got error `tslib_1 is not defined`. I have installed `tslib` package as dependencies, but nothing happens.

**Comment by mhegazy** [comment]
> Should I import tslib package into my .ts file?

No, an import should be generated for you.

see `var tslib_1 = require("tslib");` below.

```sh

c:\test\18039>type a.ts
export async function f() {
    return 0;
}

c:\test\18039>type tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": [
      "dom",
      "dom.iterable",
      "es6"
    ],
    "importHelpers": true,
    "noUnusedLocals": true,
    "declaration": true,
    "sourceMap": true,
    "outDir": "./lib",
    "rootDir": "./",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitReturns": true,
    "typeRoots": [
      "node_modules/@types",
      "typings"
    ],
    "experimentalDecorators": true
  }
}

c:\test\18039>tsc --v
Version 2.5.1-insiders.20170825

c:\test\18039>tsc

c:\test\18039>type lib\a.js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
function f() {
    return tslib_1.__awaiter(this, void 0, void 0, function () {
        return tslib_1.__generator(this, function (_a) {
            return [2 /*return*/, 0];
        });
    });
}
exports.f = f;
//# sourceMappingURL=a.js.map
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
