### ISSUE TITLE
Cannot extends from Array<T> in es5 (can in es6)

### ISSUE THREAD

**Issue by k8w** [Microsoft/TypeScript#18035]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)
2.4.2
**Code**

```ts
class Test extends Array<any>{
    constructor(...arr: any[]) {
        super(...arr)
    }

    getFirst() {
        return this[0];
    }
}

let t: Test = new Test(1, 2, 3, 4, 5)
console.log(t.getFirst())
```

**Expected behavior:**
Works well both in es5 and es6

**Actual behavior:**
It works well when target is es6.
Throw error in es5: 
> console.log(t.getFirst())
              ^
TypeError: t.getFirst is not a function
    at Object.<anonymous> (E:\test\test9\index.ts:12:15)
    at Module._compile (module.js:569:30)
    at Module.m._compile (C:\Users\King\AppData\Local\Yarn\config\global\node_modules\ts-node\src\index.ts:392:23)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\King\AppData\Local\Yarn\config\global\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (C:\Users\King\AppData\Local\Yarn\config\global\node_modules\ts-node\src\_bin.ts:182:12)

**Comment by HerringtonDarkholme** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
