### ISSUE TITLE
JSDoc quick fix causes TSServer error

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#18068]
Likely related to any fix to #18066.

```ts
var x = function x(lol: string?) {  
}
```

Put your cursor on `string?` and request a quick fix (`Ctrl`+.``)

```
TypeError: Cannot read property 'getStart' of undefined
    at createAction (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:73496:59)
    at Object.getActionsForJSDocTypes [as getCodeActions] (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:73483:28)
    at c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72821:33
    at Object.forEach (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1292:30)
    at Object.getFixes (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72820:16)
    at c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:76566:35
    at Object.flatMap (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1524:25)
    at Object.getCodeFixesAtPosition (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:76564:23)
    at IOSession.Session.getCodeFixes (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82535:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:81457:61)
    at c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82679:88
    at IOSession.Session.executeWithRequestId (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82670:28)
    at IOSession.Session.executeCommand (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82679:33)
    at IOSession.Session.onMessage (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82699:35)
    at Interface.<anonymous> (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:83785:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by sandersn** [comment]
This happens because the codefix currently doesn't look for parameters, just for variable declarations. It walks up past `lol: string?` to `var x = function ...`, looks for a type annotation on `var x` and doesn't find it.

This is fixed by #18096
