### ISSUE TITLE
Printer fails when encountering RegularExpressionLiteral

### ISSUE THREAD

**Issue by fwouts** [Microsoft/TypeScript#18071]
**TypeScript Version:**  2.4.2

**Code**

```ts
import * as ts from "typescript";
let sourceCode = "let a = /regexp/";
let tsSourceFile = ts.createSourceFile(
  "script.js",
  sourceCode,
  ts.ScriptTarget.Latest
);
console.log(
  ts.createPrinter().printFile(tsSourceFile)
);
```

**Expected behavior:**
The script should output `let a = /regexp/;`

**Actual behavior:**
The script crashes with the following stack trace:
```
.../node_modules/typescript/lib/typescript.js:3495
            throw e;
            ^
Error: Debug Failure.
    at Object.getLiteralText (/Users/work/GitHub/sample-js-selfparsing/node_modules/typescript/lib/typescript.js:7077:18)
    at getLiteralTextOfNode (/Users/work/GitHub/sample-js-selfparsing/node_modules/typescript/lib/typescript.js:68597:23)
    at emitLiteral (/Users/work/GitHub/sample-js-selfparsing/node_modules/typescript/lib/typescript.js:66918:24)
    at pipelineEmitExpression (/Users/work/GitHub/sample-js-selfparsing/node_modules/typescript/lib/typescript.js:66816:28)
    at pipelineEmitWithHint (/Users/work/GitHub/sample-js-selfparsing/node_modules/typescript/lib/typescript.js:66565:49)
    at pipelineEmitWithSourceMap (/Users/work/GitHub/sample-js-selfparsing/node_modules/typescript/lib/typescript.js:66558:17)
    at emitNodeWithNestedComments (/Users/work/GitHub/sample-js-selfparsing/node_modules/typescript/lib/typescript.js:64324:17)
    at emitNodeWithSynthesizedComments (/Users/work/GitHub/sample-js-selfparsing/node_modules/typescript/lib/typescript.js:64274:13)
    at emitNodeWithComments (/Users/work/GitHub/sample-js-selfparsing/node_modules/typescript/lib/typescript.js:64244:21)
    at pipelineEmitWithComments (/Users/work/GitHub/sample-js-selfparsing/node_modules/typescript/lib/typescript.js:66547:17)
error Command failed with exit code 1.
```

**Proposed fix:**
https://github.com/fwouts/TypeScript/commit/884cadf0a3b5682e8f3b03a7c0ab11f4504957d0

Where would be a good place to add tests for this?

**Comment by ikatyang** [comment]
https://github.com/microsoft/TypeScript/blob/master/src/harness/unittests/printer.ts

**Comment by fwouts** [comment]
Thanks @ikatyang, I've added a test in https://github.com/fwouts/TypeScript/commit/170bc6f519ca7e44b522cdf6ce8d7ccc95231736.

Happy to send a PR once the Community milestone is added to this issue.

**Comment by DanielRosenwasser** [comment]
Send! Thanks for looking into this @fwouts
