### ISSUE TITLE
Tracking invalid type assertions

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#18217]
Before we had `no-object-literal-type-assertion` applied, there were a lot of suspicious casts.
These have all been labeled with comments containing the text `GH#18217`.

**Comment by WORMSS** [comment]
So.. I kinda hit this today on
https://github.com/microsoft/TypeScript/blob/master/src/services/services.ts#L265

**Comment by edsrzf** [comment]
I've run into an exception thrown by this line, which has a comment referencing this issue: https://github.com/microsoft/TypeScript/blob/6bcb6bb36917cf8f89d0f58f1a96ee236ca76eb4/src/services/codefixes/fixCannotFindModule.ts#L55

What's the best way to proceed? It looks like it would be relatively straightforward to add a check, but do I need to create a repro case to show it's a real issue? Should I open another issue and link to this one? Please advise.

**Comment by RyanCavanaugh** [comment]
This issue was a catch-all for eventually removing every postfix `!`. Please open a new issue outlining how to repro the problem you encountered. Thanks!

**Comment by mjz19910** [comment]
got an undefined in tsserver version 4.5.20210901


getTypeParametersForTypeReference returns an undefined, that then causes this error

Cannot read property '1' of undefined
TypeError: Cannot read property '1' of undefined
    at getTypeArgumentConstraint (c:\Users\matth\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20210901\node_modules\typescript\lib\tsserver.js:76890:73)
    at Object.getTypeArgumentConstraint (c:\Users\matth\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20210901\node_modules\typescript\lib\tsserver.js:46205:32)
    at getStringLiteralCompletionEntries (c:\Users\matth\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20210901\node_modules\typescript\lib\tsserver.js:125267:108)
    at Object.getStringLiteralCompletions (c:\Users\matth\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20210901\node_modules\typescript\lib\tsserver.js:125173:35)

**Comment by dannymcgee** [comment]
It looks like custom transformers (at least those hooked into the `before` phase) can't successfully create new get/set accessor nodes due to an invalid non-null assertion at the very top of `compiler > checker > createTypeChecker > createResolver > getAllAccessorDeclarations`. Reproduced in 4.8.4, but the assertion is still there on `main` currently.

**Comment by jakebailey** [comment]
@dannymcgee Would you mind filing a new issue for that, especially if you have a simple transformer that shows the bug? We can add those as unit tests.

(As with https://github.com/microsoft/TypeScript/issues/18217#issuecomment-744561166 this issue isn't really the right place to report isuses.)
