### ISSUE TITLE
Unbalanced curly brackets crashes the compiler

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#18216]
**TypeScript Version:**  2.5.2

If you try to compile source with unbalanced curlies, e.g.

```ts
if (true) {
```

it hard-crashes the compiler with:

```
/Users/tom/code/console/node_modules/typescript/lib/tsc.js:2062
            throw e;
            ^

Error: Debug Failure. False expression.
    at computePositionOfLineAndCharacter (/Users/tom/code/console/node_modules/typescript/lib/tsc.js:3752:22)
    at Object.getPositionOfLineAndCharacter (/Users/tom/code/console/node_modules/typescript/lib/tsc.js:3742:16)
    at Object.formatDiagnosticsWithColorAndContext (/Users/tom/code/console/node_modules/typescript/lib/tsc.js:55574:40)
    at reportDiagnosticWithColorAndContext (/Users/tom/code/console/node_modules/typescript/lib/tsc.js:58771:25)
    at reportDiagnostic (/Users/tom/code/console/node_modules/typescript/lib/tsc.js:58733:9)
    at reportDiagnostics (/Users/tom/code/console/node_modules/typescript/lib/tsc.js:58738:13)
    at compileProgram (/Users/tom/code/console/node_modules/typescript/lib/tsc.js:59099:13)
    at compile (/Users/tom/code/console/node_modules/typescript/lib/tsc.js:59051:26)
    at performCompilation (/Users/tom/code/console/node_modules/typescript/lib/tsc.js:58940:33)
    at Timeout.recompile [as _onTimeout] (/Users/tom/code/console/node_modules/typescript/lib/tsc.js:59039:13)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

This is a regression from 2.4.2, where it would instead gracefully report

```
src/example.ts(105,1): error TS1005: '}' expected.
```

This is particularly bothersome because it crashes out of `--watch` mode.

**Comment by RyanCavanaugh** [comment]
Not seeing this at 2.5.2. Can you provide an exact repro?

**Comment by pelotom** [comment]
Ah, it seems to only happen in my (private repo) project. I'll see if I can come up with a minimal repro.

**Comment by pelotom** [comment]
Ok, so the specific conditions required to produce it seem to be that:
- the `--pretty` flag is used, AND
- there is a newline at the end of a file

**Comment by pelotom** [comment]
I did a quick bisect and it looks like it was first broken as of the `2.5.0-dev.20170719` release.
