### ISSUE TITLE
TypeError: Cannot read property 'externalModuleIndicator' of undefined

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#18377]
**TypeScript Version:**  typescript@2.6.0-dev.20170910

There were no code changes, but compile now fails after upgrading to latest nightly. Same as #15725 but with different stacktrace

**Expected behavior:**

Works

**Actual behavior:**

Fails with:

```
C:\nodejs\node_modules\typescript\lib\tsc.js:56500
                throw e;
                ^

TypeError: Cannot read property 'externalModuleIndicator' of undefined
    at Object.isExternalModule (C:\nodejs\node_modules\typescript\lib\tsc.js:10106:20)
    at C:\nodejs\node_modules\typescript\lib\tsc.js:20104:77
    at Object.forEachEntry (C:\nodejs\node_modules\typescript\lib\tsc.js:967:26)
    at trySymbolTable (C:\nodejs\node_modules\typescript\lib\tsc.js:20100:27)
    at getAccessibleSymbolChainFromSymbolTable (C:\nodejs\node_modules\typescript\lib\tsc.js:20080:30)
    at forEachSymbolTableInScope (C:\nodejs\node_modules\typescript\lib\tsc.js:20065:20)
    at getAccessibleSymbolChain (C:\nodejs\node_modules\typescript\lib\tsc.js:20075:20)
    at getSymbolChain (C:\nodejs\node_modules\typescript\lib\tsc.js:20791:49)
    at symbolToName (C:\nodejs\node_modules\typescript\lib\tsc.js:20756:29)
    at typeToTypeNodeHelper (C:\nodejs\node_modules\typescript\lib\tsc.js:20402:32)
    at Object.typeToTypeNode (C:\nodejs\node_modules\typescript\lib\tsc.js:20307:41)
    at typeToString (C:\nodejs\node_modules\typescript\lib\tsc.js:20267:40)
    at reportRelationError (C:\nodejs\node_modules\typescript\lib\tsc.js:25594:34)
    at isRelatedTo (C:\nodejs\node_modules\typescript\lib\tsc.js:25719:21)
    at checkTypeRelatedTo (C:\nodejs\node_modules\typescript\lib\tsc.js:25575:26)
    at checkApplicableSignature (C:\nodejs\node_modules\typescript\lib\tsc.js:30617:26)
    at resolveCall (C:\nodejs\node_modules\typescript\lib\tsc.js:30848:17)
    at resolveCallExpression (C:\nodejs\node_modules\typescript\lib\tsc.js:31020:20)
    at resolveSignature (C:\nodejs\node_modules\typescript\lib\tsc.js:31196:28)
    at getResolvedSignature (C:\nodejs\node_modules\typescript\lib\tsc.js:31216:26)
    at checkCallExpression (C:\nodejs\node_modules\typescript\lib\tsc.js:31259:29)
    at checkExpressionWorker (C:\nodejs\node_modules\typescript\lib\tsc.js:32548:28)
    at checkExpression (C:\nodejs\node_modules\typescript\lib\tsc.js:32488:42)
    at checkExpressionWithContextualType (C:\nodejs\node_modules\typescript\lib\tsc.js:32394:26)
    at inferTypeArguments (C:\nodejs\node_modules\typescript\lib\tsc.js:30536:35)
    at chooseOverload (C:\nodejs\node_modules\typescript\lib\tsc.js:30944:53)
    at resolveCall (C:\nodejs\node_modules\typescript\lib\tsc.js:30836:26)
    at resolveCallExpression (C:\nodejs\node_modules\typescript\lib\tsc.js:31020:20)
    at resolveSignature (C:\nodejs\node_modules\typescript\lib\tsc.js:31196:28)
    at getResolvedSignature (C:\nodejs\node_modules\typescript\lib\tsc.js:31216:26)
    at checkCallExpression (C:\nodejs\node_modules\typescript\lib\tsc.js:31259:29)
    at checkExpressionWorker (C:\nodejs\node_modules\typescript\lib\tsc.js:32548:28)
    at checkExpression (C:\nodejs\node_modules\typescript\lib\tsc.js:32488:42)
    at checkNonNullExpression (C:\nodejs\node_modules\typescript\lib\tsc.js:30041:37)
    at checkPropertyAccessExpressionOrQualifiedName (C:\nodejs\node_modules\typescript\lib\tsc.js:30062:24)
    at checkPropertyAccessExpression (C:\nodejs\node_modules\typescript\lib\tsc.js:30056:20)
    at checkExpressionWorker (C:\nodejs\node_modules\typescript\lib\tsc.js:32540:28)
    at checkExpression (C:\nodejs\node_modules\typescript\lib\tsc.js:32488:42)
    at checkNonNullExpression (C:\nodejs\node_modules\typescript\lib\tsc.js:30041:37)
    at resolveCallExpression (C:\nodejs\node_modules\typescript\lib\tsc.js:30995:28)
    at resolveSignature (C:\nodejs\node_modules\typescript\lib\tsc.js:31196:28)
    at getResolvedSignature (C:\nodejs\node_modules\typescript\lib\tsc.js:31216:26)
    at checkCallExpression (C:\nodejs\node_modules\typescript\lib\tsc.js:31259:29)
    at checkExpressionWorker (C:\nodejs\node_modules\typescript\lib\tsc.js:32548:28)
    at checkExpression (C:\nodejs\node_modules\typescript\lib\tsc.js:32488:42)
    at checkExpressionStatement (C:\nodejs\node_modules\typescript\lib\tsc.js:34245:13)
    at checkSourceElement (C:\nodejs\node_modules\typescript\lib\tsc.js:35770:28)
    at Object.forEach (C:\nodejs\node_modules\typescript\lib\tsc.js:281:30)
    at checkBlock (C:\nodejs\node_modules\typescript\lib\tsc.js:33921:16)
    at checkSourceElement (C:\nodejs\node_modules\typescript\lib\tsc.js:35766:28)
    at checkIfStatement (C:\nodejs\node_modules\typescript\lib\tsc.js:34250:13)
    at checkSourceElement (C:\nodejs\node_modules\typescript\lib\tsc.js:35772:28)
    at Object.forEach (C:\nodejs\node_modules\typescript\lib\tsc.js:281:30)
    at checkBlock (C:\nodejs\node_modules\typescript\lib\tsc.js:33921:16)
    at checkSourceElement (C:\nodejs\node_modules\typescript\lib\tsc.js:35766:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (C:\nodejs\node_modules\typescript\lib\tsc.js:31727:21)
    at checkDeferredNodes (C:\nodejs\node_modules\typescript\lib\tsc.js:35843:25)
    at checkSourceFileWorker (C:\nodejs\node_modules\typescript\lib\tsc.js:35873:17)
    at checkSourceFile (C:\nodejs\node_modules\typescript\lib\tsc.js:35857:13)
    at getDiagnosticsWorker (C:\nodejs\node_modules\typescript\lib\tsc.js:35910:17)
    at Object.getDiagnostics (C:\nodejs\node_modules\typescript\lib\tsc.js:35899:24)
    at C:\nodejs\node_modules\typescript\lib\tsc.js:56515:85
    at runWithCancellationToken (C:\nodejs\node_modules\typescript\lib\tsc.js:56493:24)
    at getSemanticDiagnosticsForFileNoCache (C:\nodejs\node_modules\typescript\lib\tsc.js:56507:20)
    at getAndCacheDiagnostics (C:\nodejs\node_modules\typescript\lib\tsc.js:56715:26)
    at getSemanticDiagnosticsForFile (C:\nodejs\node_modules\typescript\lib\tsc.js:56504:20)
    at C:\nodejs\node_modules\typescript\lib\tsc.js:56461:24
    at Object.flatMap (C:\nodejs\node_modules\typescript\lib\tsc.js:513:25)
    at getDiagnosticsHelper (C:\nodejs\node_modules\typescript\lib\tsc.js:56457:56)
    at Object.getSemanticDiagnostics (C:\nodejs\node_modules\typescript\lib\tsc.js:56468:20)
    at compileProgram (C:\nodejs\node_modules\typescript\lib\tsc.js:59481:43)
    at compile (C:\nodejs\node_modules\typescript\lib\tsc.js:59438:26)
    at performCompilation (C:\nodejs\node_modules\typescript\lib\tsc.js:59327:33)
    at Object.executeCommandLine (C:\nodejs\node_modules\typescript\lib\tsc.js:59270:9)
    at Object.<anonymous> (C:\nodejs\node_modules\typescript\lib\tsc.js:59628:4)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\nodejs\node_modules\typescript\bin\tsc:2:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
The terminal process terminated with exit code: 1
```

**Comment by mhegazy** [comment]
@pocesar can you share more context here? we would be happy to sign any required NDA to get access to the sources.

**Comment by harangue** [comment]
I also have this problem @mhegazy. Having a little bit of trouble reproducing with a smaller example, but I'd be happy to share my code with you all.

**Comment by pocesar** [comment]
@mhegazy I couldn't pin down the problem, because it was crashing before showing any TS coded errors. I tried to compile using TS 2.5 and it showed me the errors. It was related to a missing required property in a function call (like using `Data` and `ExtraData` which extended `Data` but had some required fields), but 2.6 was choking before the compile time error showed up.

**Comment by mhegazy** [comment]
@pocesar can you give `typescript@next` a try tomorrow and let us know if it did address the issue or not?

**Comment by pocesar** [comment]
sure thing!

**Comment by pocesar** [comment]
@mhegazy it seems to be fine now
