### ISSUE TITLE
Crash when performing a compilation

### ISSUE THREAD

**Issue by hobbes78** [Microsoft/TypeScript#18511]
**TypeScript Version:**  2.5.2

**Code**

```tsc```

**Expected behavior:**

Compilation without crashing.

**Actual behavior:**

Invoking the TypeScript compiler `tsc` on a specific codebase produces a crash. The codebase is proprietary, hence I can't make it available for reproducibility sake.

This is the stack trace produced:

```C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:56136
                throw e;
                ^

TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:7422:17)
    at assignContextualParameterTypes (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:31098:25)
    at checkFunctionExpressionOrObjectLiteralMethod (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:31351:29)
    at checkExpressionWorker (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32227:28)
    at checkExpression (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32162:42)
    at checkBinaryLikeExpression (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:31814:29)
    at checkBinaryExpression (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:31806:20)
    at checkExpressionWorker (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32248:28)
    at checkExpression (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32162:42)
    at checkExpressionStatement (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:33912:13)
    at checkSourceElement (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35434:28)
    at Object.forEach (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:275:30)
    at checkBlock (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:33588:16)
    at checkSourceElement (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35430:28)
    at checkIfStatement (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:33917:13)
    at checkSourceElement (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35436:28)
    at Object.forEach (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:275:30)
    at checkBlock (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:33588:16)
    at checkSourceElement (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35430:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:31387:21)
    at checkDeferredNodes (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35507:25)
    at checkSourceFileWorker (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35537:17)
    at checkSourceFile (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35521:13)
    at Object.forEach (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:275:30)
    at getDiagnosticsWorker (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35586:16)
    at getDiagnostics (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35563:24)
    at Object.getEmitResolver (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:18561:13)
    at emitWorker (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:56075:69)
    at C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:56051:66
    at runWithCancellationToken (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:56129:24)
    at Object.emit (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:56051:20)
    at compileProgram (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:59097:38)
    at compile (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:59051:26)
    at performCompilation (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:58940:33)
    at Object.executeCommandLine (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:58883:9)
    at Object.<anonymous> (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:59241:4)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\bin\tsc:2:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3```

**Comment by RyanCavanaugh** [comment]
It's going to be very difficult for us to fix this without a repro. Can you try to derive an isolated example? If you attach a debugger you should be able to see which function expression is being checked in `checkFunctionExpressionOrObjectLiteralMethod` - call `node.getText()` in the console and that will give you the text of the function, which I think will be enough for us to understand the repro

**Comment by hobbes78** [comment]
If in the debugger repl I type `node` I get:
```{ id: 14484,
  kind: 186,
  pos: 1712,
  end: 1775,
  flags: 65664,
  ... }
```
But if I type `node.getText()` I get:
```TypeError: node.getText is not a function
    at eval (eval at checkFunctionExpressionOrObjectLiteralMethod (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:31351:29), <anonymous>:1:6)
    at checkFunctionExpressionOrObjectLiteralMethod (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:31351:29)
    at checkExpressionWorker (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32228:28)
    at checkExpression (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32163:42)
    at checkExpressionWithContextualType (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32069:26)
    at checkApplicableSignature (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:30268:25)
    at chooseOverload (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:30602:30)
    at resolveCall (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:30490:26)
    at resolveCallExpression (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:30674:20)
    at resolveSignature (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:30850:28)
    at getResolvedSignature (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:30870:26)
    at checkCallExpression (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:30913:29)
    at checkExpressionWorker (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32219:28)
    at checkExpression (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32163:42)
    at checkExpressionStatement (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:33913:13)
    at checkSourceElement (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35435:28)
    at Object.forEach (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:275:30)
    at checkBlock (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:33589:16)
    at checkSourceElement (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35431:28)
    at checkIfStatement (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:33922:13)
    at checkSourceElement (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35437:28)
    at Object.forEach (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:275:30)
    at checkBlock (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:33589:16)
    at checkSourceElement (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35431:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:31388:21)
    at checkDeferredNodes (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35508:25)
    at checkSourceFileWorker (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35538:17)
    at checkSourceFile (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35522:13)
    at Object.forEach (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:275:30)
    at getDiagnosticsWorker (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35587:16)
    at getDiagnostics (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35564:24)
    at Object.getEmitResolver (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:18561:13)
    at emitWorker (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:56076:69)
    at C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:56052:66
    at runWithCancellationToken (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:56130:24)
    at Object.emit (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:56052:20)
    at compileProgram (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:59098:38)
    at compile (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:59052:26)
    at performCompilation (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:58941:33)
    at Object.executeCommandLine (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:58884:9)
    at Object.<anonymous> (C:\Users\jarodrigues\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:59242:4)
    at Module._compile (module.js:570:14)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

Is it possible to at least know which file from my codebase was being processed when the crash happened? Maybe then I might be able to derive an isolated example.

**Comment by RyanCavanaugh** [comment]
Sorry, `ts.getTextOfNode(node)`

> Is it possible to at least know which file from my codebase was being processed when the crash happened? 

`getSourceFileOfNode(node).fileName`

**Comment by hobbes78** [comment]
This the text of the function:
```
> ts.getTextOfNode(node)
'function () {\r\n\t\t\t\t\t\t\tdef.resolve(results, viewModel);\r\n\t\t\t\t\t\t}'
```
With the name of the filename, I might be able to derive an isolated example, but with the current backlog I have, only in a few days...

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
