### ISSUE TITLE
Verbose error message for lint failure

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#18597]
When I have a lint error the error message is extremely verbose.

```
~\work\TypeScript [master ≡ +1 ~1 -0 !]> gulp runtests-parallel
[08:07:23] Requiring external module ts-node/register
[08:07:23] Using gulpfile ~\work\TypeScript\gulpfile.ts
[08:07:23] Starting 'build-rules'...
[08:07:23] Starting 'built\local\lib.dom.d.ts'...
[08:07:23] Starting 'built\local\lib.dom.iterable.d.ts'...
[08:07:23] Starting 'built\local\lib.webworker.d.ts'...
[08:07:23] Starting 'built\local\lib.scripthost.d.ts'...
[08:07:23] Starting 'built\local\lib.es5.d.ts'...
[08:07:23] Starting 'built\local\lib.es2015.d.ts'...
[08:07:23] Starting 'built\local\lib.es2016.d.ts'...
[08:07:23] Starting 'built\local\lib.es2017.d.ts'...
[08:07:23] Starting 'built\local\lib.esnext.d.ts'...
[08:07:23] Starting 'built\local\lib.d.ts'...
[08:07:23] Starting 'built\local\lib.es6.d.ts'...
[08:07:23] Starting 'built\local\lib.es2016.full.d.ts'...
[08:07:23] Starting 'built\local\lib.es2017.full.d.ts'...
[08:07:23] Starting 'built\local\lib.esnext.full.d.ts'...
[08:07:23] Starting 'built\local\lib.es2015.core.d.ts'...
[08:07:23] Starting 'built\local\lib.es2015.collection.d.ts'...
[08:07:23] Starting 'built\local\lib.es2015.generator.d.ts'...
[08:07:23] Starting 'built\local\lib.es2015.iterable.d.ts'...
[08:07:23] Starting 'built\local\lib.es2015.promise.d.ts'...
[08:07:23] Starting 'built\local\lib.es2015.proxy.d.ts'...
[08:07:23] Starting 'built\local\lib.es2015.reflect.d.ts'...
[08:07:23] Starting 'built\local\lib.es2015.symbol.d.ts'...
[08:07:23] Starting 'built\local\lib.es2015.symbol.wellknown.d.ts'...
[08:07:23] Starting 'built\local\lib.es2016.array.include.d.ts'...
[08:07:23] Starting 'built\local\lib.es2017.object.d.ts'...
[08:07:23] Starting 'built\local\lib.es2017.sharedmemory.d.ts'...
[08:07:24] Starting 'built\local\lib.es2017.string.d.ts'...
[08:07:24] Starting 'built\local\lib.es2017.intl.d.ts'...
[08:07:24] Starting 'built\local\lib.esnext.asynciterable.d.ts'...
[08:07:24] Starting 'scripts\processDiagnosticMessages.js'...
[08:07:24] Finished 'scripts\processDiagnosticMessages.js' after 43 ms
[08:07:24] Starting 'src\compiler\diagnosticInformationMap.generated.ts'...
[08:07:24] Finished 'src\compiler\diagnosticInformationMap.generated.ts' after 482 μs
[08:07:24] Starting 'generate-diagnostics'...
[08:07:24] Finished 'generate-diagnostics' after 22 μs
[08:07:24] Finished 'built\local\lib.dom.iterable.d.ts' after 120 ms
[08:07:24] Finished 'built\local\lib.es2016.d.ts' after 113 ms
[08:07:24] Finished 'built\local\lib.es2015.d.ts' after 116 ms
[08:07:24] Finished 'built\local\lib.esnext.d.ts' after 113 ms
[08:07:24] Finished 'built\local\lib.scripthost.d.ts' after 122 ms
[08:07:24] Finished 'built\local\lib.es2017.d.ts' after 117 ms
[08:07:24] Finished 'built\local\lib.webworker.d.ts' after 132 ms
[08:07:24] Finished 'built\local\lib.es5.d.ts' after 138 ms
[08:07:24] Finished 'built\local\lib.es2015.collection.d.ts' after 112 ms
[08:07:24] Finished 'built\local\lib.es2015.core.d.ts' after 117 ms
[08:07:24] Finished 'built\local\lib.es2015.generator.d.ts' after 122 ms
[08:07:24] Finished 'built\local\lib.es2015.promise.d.ts' after 122 ms
[08:07:24] Finished 'built\local\lib.es2015.reflect.d.ts' after 120 ms
[08:07:24] Finished 'built\local\lib.es2015.proxy.d.ts' after 123 ms
[08:07:24] Finished 'built\local\lib.es2015.iterable.d.ts' after 127 ms
[08:07:24] Finished 'built\local\lib.es2015.symbol.wellknown.d.ts' after 119 ms
[08:07:24] Finished 'built\local\lib.es2015.symbol.d.ts' after 122 ms
[08:07:24] Finished 'built\local\lib.es2016.array.include.d.ts' after 120 ms
[08:07:24] Finished 'built\local\lib.es2017.sharedmemory.d.ts' after 118 ms
[08:07:24] Finished 'built\local\lib.es2017.string.d.ts' after 117 ms
[08:07:24] Finished 'built\local\lib.es2017.object.d.ts' after 122 ms
[08:07:24] Finished 'built\local\lib.es2017.intl.d.ts' after 119 ms
[08:07:24] Finished 'built\local\lib.dom.d.ts' after 178 ms
[08:07:24] Finished 'built\local\lib.esnext.asynciterable.d.ts' after 113 ms
[08:07:24] Finished 'built\local\lib.d.ts' after 172 ms
[08:07:24] Finished 'build-rules' after 355 ms
[08:07:24] Finished 'built\local\lib.es2016.full.d.ts' after 184 ms
[08:07:24] Finished 'built\local\lib.es2017.full.d.ts' after 180 ms
[08:07:24] Finished 'built\local\lib.esnext.full.d.ts' after 179 ms
[08:07:24] Finished 'built\local\lib.es6.d.ts' after 195 ms
[08:07:24] Starting 'lib'...
[08:07:24] Finished 'lib' after 3.23 μs
[08:07:24] Starting 'built\local\typescriptServices.js'...
Compiler option 'compileOnSave' requires a value of type boolean.
[08:07:24] Finished 'built\local\typescriptServices.js' after 111 ms
[08:07:24] Starting 'built\local\run.js'...
[08:07:24] Finished 'built\local\run.js' after 257 ms
[08:07:24] Starting 'tests'...
[08:07:24] Finished 'tests' after 4.11 μs
[08:07:24] Starting 'runtests-parallel'...
Running tests with config: {"light":false,"workerCount":8,"taskConfigsFolder":"C:\\Users\\anhans\\AppData\\Local\\Temp/ts-tests142","noColor":false}
node built\local\run.js
Discovering tests...
Discovered 11201 test files in 1048ms.
Starting to run tests using 8 threads...
Batching initial test lists...
Batched into 8 groups with approximate total file sizes of 752084 bytes in each group.

  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬] √ 57024 passing (3m)


  57024 passing (3m)

[08:09:57] Starting 'build-rules'...
[08:09:57] Finished 'build-rules' after 58 ms
[08:09:57] Starting 'lint'...
Linting: node node_modules/tslint/bin/tslint Gulpfile.ts 'scripts/tslint/*.ts' 'src/**/*.ts' --exclude src/lib/es5.d.ts --exclude 'src/lib/*.generated.d.ts' --format stylish
src/services/formatting/formattingScanner.ts
ERROR: 128:27  comment-format  comment must start with a space

[08:10:07] 'lint' errored after 9.81 s
[08:10:07] Error: Command failed: node node_modules/tslint/bin/tslint Gulpfile.ts 'scripts/tslint/*.ts' 'src/**/*.ts' --exclude src/lib/es5.d.ts --exclude 'src/lib/*.generated.d.ts' --format stylish
    at checkExecSyncError (child_process.js:591:13)
    at Object.execSync (child_process.js:631:13)
    at Gulp.<anonymous> (C:\Users\anhans\work\TypeScript\gulpfile.ts:1057:19)
    at module.exports (C:\Users\anhans\work\TypeScript\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\anhans\work\TypeScript\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\anhans\work\TypeScript\node_modules\orchestrator\index.js:214:10)
    at C:\Users\anhans\work\TypeScript\node_modules\orchestrator\index.js:279:18
    at finish (C:\Users\anhans\work\TypeScript\node_modules\orchestrator\lib\runTask.js:21:8)
    at C:\Users\anhans\work\TypeScript\node_modules\orchestrator\lib\runTask.js:52:4
    at f (C:\Users\anhans\work\TypeScript\node_modules\end-of-stream\node_modules\once\once.js:17:25)
    at DestroyableTransform.onend (C:\Users\anhans\work\TypeScript\node_modules\end-of-stream\index.js:31:18)
    at emitNone (events.js:110:20)
    at DestroyableTransform.emit (events.js:207:7)
    at C:\Users\anhans\work\TypeScript\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
{ Error: Command failed: node node_modules/tslint/bin/tslint Gulpfile.ts 'scripts/tslint/*.ts' 'src/**/*.ts' --exclude src/lib/es5.d.ts --exclude 'src/lib/*.generated.d.ts' --format stylish
    at checkExecSyncError (child_process.js:591:13)
    at Object.execSync (child_process.js:631:13)
    at Gulp.<anonymous> (C:\Users\anhans\work\TypeScript\gulpfile.ts:1057:19)
    at module.exports (C:\Users\anhans\work\TypeScript\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\anhans\work\TypeScript\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\anhans\work\TypeScript\node_modules\orchestrator\index.js:214:10)
    at C:\Users\anhans\work\TypeScript\node_modules\orchestrator\index.js:279:18
    at finish (C:\Users\anhans\work\TypeScript\node_modules\orchestrator\lib\runTask.js:21:8)
    at C:\Users\anhans\work\TypeScript\node_modules\orchestrator\lib\runTask.js:52:4
    at f (C:\Users\anhans\work\TypeScript\node_modules\end-of-stream\node_modules\once\once.js:17:25)
    at DestroyableTransform.onend (C:\Users\anhans\work\TypeScript\node_modules\end-of-stream\index.js:31:18)
    at emitNone (events.js:110:20)
    at DestroyableTransform.emit (events.js:207:7)
    at C:\Users\anhans\work\TypeScript\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  error: null,
  cmd: 'node node_modules/tslint/bin/tslint Gulpfile.ts \'scripts/tslint/*.ts\' \'src/**/*.ts\' --exclude src/lib/es5.d.ts --exclude \'src/lib/*.generated.d.ts\' --format stylish',
  file: 'C:\\WINDOWS\\system32\\cmd.exe',
  args:
   [ 'C:\\WINDOWS\\system32\\cmd.exe',
     '/d',
     '/s',
     '/c',
     '"node node_modules/tslint/bin/tslint Gulpfile.ts \'scripts/tslint/*.ts\' \'src/**/*.ts\' --exclude src/lib/es5.d.ts --exclude \'src/lib/*.generated.d.ts\' --format stylish"' ],
  options:
   { stdio: [ [Object], [Object], [Object] ],
     shell: true,
     windowsVerbatimArguments: true,
     file: 'C:\\WINDOWS\\system32\\cmd.exe',
     args:
      [ 'C:\\WINDOWS\\system32\\cmd.exe',
        '/d',
        '/s',
        '/c',
        '"node node_modules/tslint/bin/tslint Gulpfile.ts \'scripts/tslint/*.ts\' \'src/**/*.ts\' --exclude src/lib/es5.d.ts --exclude \'src/lib/*.generated.d.ts\' --format stylish"' ],
     envPairs:
      [ ...censored... ],
     killSignal: undefined },
  envPairs:
   [ ...censored... ],
  stderr: null,
  stdout: null,
  pid: 12364,
  output: [ null, null, null ],
  signal: null,
  status: 2,
  name: 'Error',
  message: 'Command failed: node node_modules/tslint/bin/tslint Gulpfile.ts \'scripts/tslint/*.ts\' \'src/**/*.ts\' --exclude src/lib/es5.d.ts --exclude \'src/lib/*.generated.d.ts\' --format stylish',
  stack: 'Error: Command failed: node node_modules/tslint/bin/tslint Gulpfile.ts \'scripts/tslint/*.ts\' \'src/**/*.ts\' --exclude src/lib/es5.d.ts --exclude \'src/lib/*.generated.d.ts\' --format stylish\n    at checkExecSyncError (child_process.js:591:13)\n    at Object.execSync (child_process.js:631:13)\n    at Gulp.<anonymous> (C:\\Users\\anhans\\work\\TypeScript\\gulpfile.ts:1057:19)\n    at module.exports (C:\\Users\\anhans\\work\\TypeScript\\node_modules\\orchestrator\\lib\\runTask.js:34:7)\n    at Gulp.Orchestrator._runTask (C:\\Users\\anhans\\work\\TypeScript\\node_modules\\orchestrator\\index.js:273:3)\n    at Gulp.Orchestrator._runStep (C:\\Users\\anhans\\work\\TypeScript\\node_modules\\orchestrator\\index.js:214:10)\n    at C:\\Users\\anhans\\work\\TypeScript\\node_modules\\orchestrator\\index.js:279:18\n    at finish (C:\\Users\\anhans\\work\\TypeScript\\node_modules\\orchestrator\\lib\\runTask.js:21:8)\n    at C:\\Users\\anhans\\work\\TypeScript\\node_modules\\orchestrator\\lib\\runTask.js:52:4\n    at f (C:\\Users\\anhans\\work\\TypeScript\\node_modules\\end-of-stream\\node_modules\\once\\once.js:17:25)\n    at DestroyableTransform.onend (C:\\Users\\anhans\\work\\TypeScript\\node_modules\\end-of-stream\\index.js:31:18)\n    at emitNone (events.js:110:20)\n    at DestroyableTransform.emit (events.js:207:7)\n    at C:\\Users\\anhans\\work\\TypeScript\\node_modules\\vinyl-fs\\node_modules\\readable-stream\\lib\\_stream_readable.js:965:16\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)',
  showStack: true,
  showProperties: true,
  plugin: 'run-sequence(lint)' }
[08:10:08] 'runtests-parallel' errored after 2.72 min
[08:10:08] Error in plugin 'run-sequence(lint)'
Message:
    Command failed: node node_modules/tslint/bin/tslint Gulpfile.ts 'scripts/tslint/*.ts' 'src/**/*.ts' --exclude src/lib/es5.d.ts --exclude 'src/lib/*.generated.d.ts' --format stylish
Details:
    error: null
    cmd: node node_modules/tslint/bin/tslint Gulpfile.ts 'scripts/tslint/*.ts' 'src/**/*.ts' --exclude src/lib/es5.d.ts --exclude 'src/lib/*.generated.d.ts' --format stylish
    file: C:\WINDOWS\system32\cmd.exe
    args: C:\WINDOWS\system32\cmd.exe,/d,/s,/c,"node node_modules/tslint/bin/tslint Gulpfile.ts 'scripts/tslint/*.ts' 'src/**/*.ts' --exclude src/lib/es5.d.ts --exclude 'src/lib/*.generated.d.ts' --format stylish"
    options: [object Object]
    envPairs: ...censored...
    stderr: null
    stdout: null
    pid: 12364
    output: ,,
    signal: null
    status: 2
Stack:
Error: Command failed: node node_modules/tslint/bin/tslint Gulpfile.ts 'scripts/tslint/*.ts' 'src/**/*.ts' --exclude src/lib/es5.d.ts --exclude 'src/lib/*.generated.d.ts' --format stylish
    at checkExecSyncError (child_process.js:591:13)
    at Object.execSync (child_process.js:631:13)
    at Gulp.<anonymous> (C:\Users\anhans\work\TypeScript\gulpfile.ts:1057:19)
    at module.exports (C:\Users\anhans\work\TypeScript\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\anhans\work\TypeScript\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\anhans\work\TypeScript\node_modules\orchestrator\index.js:214:10)
    at C:\Users\anhans\work\TypeScript\node_modules\orchestrator\index.js:279:18
    at finish (C:\Users\anhans\work\TypeScript\node_modules\orchestrator\lib\runTask.js:21:8)
    at C:\Users\anhans\work\TypeScript\node_modules\orchestrator\lib\runTask.js:52:4
    at f (C:\Users\anhans\work\TypeScript\node_modules\end-of-stream\node_modules\once\once.js:17:25)
    at DestroyableTransform.onend (C:\Users\anhans\work\TypeScript\node_modules\end-of-stream\index.js:31:18)
    at emitNone (events.js:110:20)
    at DestroyableTransform.emit (events.js:207:7)
    at C:\Users\anhans\work\TypeScript\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

It's even longer when you include printing out my environment variables three times, which I've omitted here.
Probably related to #18462. CC @weswigham

**Comment by weswigham** [comment]
I didn't change how we lint at all with that PR (other than making it so gulp could actually run the lint, as before it was exiting because it tried to RM the config tmpdir without force specified); so this is unrelated - it's probably been like this for awhile, but the other bug preventing the lint from running at all was masking it. I'll take a look at it anyway, as that error is awful.
