### ISSUE TITLE
TSServer plugins pointing to relative paths are not loaded in 2.5

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18623]
**Steps to Reproduce:**

1. Create a `tsconfig.json`

```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "plugins": [
      { "name": "./lib" }
    ]
  }
}
```

Where a typescript server plugin in installed at `lib`.

2. Open the workspace in an editor

**Bug**
Plugin is not loaded. This works in TS 2.4.2 but is broken in TS 2.5.x

This is a useful configuration for testing a plugin

**Comment by mhegazy** [comment]
@andy-ms can you take a look at this?

**Comment by mhegazy** [comment]
if we can get a fix for it we should put it in 2.5.3

**Comment by andy-ms** [comment]
This doesn't seem to work for me in 2.4.2? Here's the relevant tsserver log output:
```
Info 11   Loading ./lib from C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js/../../.. (resolved to C:/Users/anhans/AppData/Roaming/npm/node_modules/node_modules)
Info 12   Failed to load module: {}
Info 13   Loading ./lib from  (resolved to c:/Users/anhans/work/sample/zzz/node_modules)
Info 14   Failed to load module: {}
Info 15   Couldn't find ./lib anywhere in paths: C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js/../../..,
```
The plugin is in `./lib` relative to your project's `tsconfig.json`, right? It looks like it's looking relative to its installation directory instead.

The tsserver log in `typescript@next` fails in the same way, although with a different error message:
```
Info 11   [7:41:53.402] Enabling plugin ./lib from candidate paths: C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js/../../..
Info 12   [7:41:53.402] Loading ./lib from C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js/../../.. (resolved to C:/Users/anhans/AppData/Roaming/npm/node_modules/node_modules)
Info 13   [7:41:53.412] Failed to load module './lib': Error: Could not resolve JS module './lib' starting at 'C:/Users/anhans/AppData/Roaming/npm/node_modules/node_modules'. Looked in: C:/Users/anhans/AppData/Roaming/npm/node_modules/node_modules/lib.js, C:/Users/anhans/AppData/Roaming/npm/node_modules/node_modules/lib.jsx, C:/Users/anhans/AppData/Roaming/npm/node_modules/node_modules/lib/package.json, C:/Users/anhans/AppData/Roaming/npm/node_modules/node_modules/lib/index.js, C:/Users/anhans/AppData/Roaming/npm/node_modules/node_modules/lib/index.jsx
    at Object.resolveJavaScriptModule (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:5058:19)
    at Object.sys.require (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:85025:45)
    at Function.Project.resolveModule (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:79747:35)
    at ConfiguredProject.enablePlugin (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:80409:50)
    at ConfiguredProject.enablePlugins (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:80382:30)
    at new ConfiguredProject (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:80360:23)
    at ProjectService.createAndAddConfiguredProject (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:81366:31)
    at ProjectService.openConfigFile (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:81410:36)
    at ProjectService.openOrUpdateConfiguredProjectForFile (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:81178:35)
    at ProjectService.openClientFileWithNormalizedPath (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:81690:32)
    at IOSession.Session.openClientFile (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:83010:46)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:82238:31)
    at C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:83626:88
    at IOSession.Session.executeWithRequestId (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:83617:28)
    at IOSession.Session.executeCommand (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:83626:33)
    at IOSession.Session.onMessage (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:83646:35)
    at Interface.<anonymous> (C:\Users\anhans\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:84793:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
Info 14   [7:41:53.412] Couldn't find ./lib
```

@weswigham may know something about whether this was ever intended to work.

**Comment by mjbvz** [comment]
Here's an example that was using the config: https://github.com/Quramy/ts-graphql-plugin/blob/master/e2e/project-fixture/tsconfig.json 

I'm not sure if that path is relative to the tsconfig or to the typescript install

**Comment by weswigham** [comment]
@mjbvz Since each member of the `plugins` map is not a top-level element or compiler flag marked as a file path; it is going to get resolved relative to the base directory of the compilation, similarly to how the `paths`, or `typeRoots` arguments' members should.

Regarding the loading of the plugin, cc @RyanCavanaugh, who should know more on the behavior of the loader.

**Comment by mjbvz** [comment]
I was able to work around this in my plugin tests by creating a npm install of a local package. Not sure restoring the path based plugin loading behavior is correct

**Comment by manuth** [comment]
Honestly I think it is not.
I'm having exactly the same issue and if you ask yourself what is at `${workspaceFolder}/node_modules` and why plugins are loaded relatively to this directory you might come to the conclusion: It makes no sense.

Actually I think it might be cause of a faulty way to resolve paths:

> ```
>Info 9    [18:41:39.207] Enabling plugin ./lib from candidate paths: c:/Projects/my-plugin/node_modules/typescript/lib/tsserver.js/../../..,c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features,C:\Users\manuth\.vscode\extensions\ms-vscode.vscode-typescript-tslint-plugin-1.2.3
> [...]
> Info 13   [18:41:39.262] Failed to load module './lib' from c:/Projects/my-plugin/node_modules/node_modules: Error: Could not resolve JS module './lib' starting at 'c:/Projects/my-plugin/node_modules/node_modules'. Looked in: c:/Projects/my-plugin/node_modules/node_modules/lib.js, c:/Projects/my-plugin/node_modules/node_modules/lib.jsx, c:/Projects/my-plugin/node_modules/node_modules/lib/package.json, c:/Projects/my-plugin/node_modules/node_modules/lib/index.js, c:/Projects/my-plugin/node_modules/node_modules/lib/index.jsx
>```

Shouldn't the candidate path be `c:/Projects/my-plugin/node_modules/typescript/lib/../../..` rather than `c:/Projects/my-plugin/node_modules/typescript/lib/tsserver.js/../../..`?

`c:/Projects/my-plugin/node_modules/typescript/lib/../../..` resolves to:
`c:/Projects/my-plugin`
while `c:/Projects/my-plugin/node_modules/typescript/lib/tsserver.js/../../..` resolves to:
`c:/Projects/my-plugin/node_modules/`

But my project doesn't live in `c:/Projects/my-plugin/node_modules/`. It lives in `c:/Projects/my-plugin`.

If we look at the paths it tries to look for the plugin `./lib` it becomes quite obvious:
* `c:/Projects/my-plugin/node_modules/node_modules/lib.js`
* `c:/Projects/my-plugin/node_modules/node_modules/lib.jsx`
* `c:/Projects/my-plugin/node_modules/node_modules/lib/package.json`
* `c:/Projects/my-plugin/node_modules/node_modules/lib/index.js`
* `c:/Projects/my-plugin/node_modules/node_modules/lib/index.jsx`

TypeScript is acting as if `c:/Projects/my-plugin/node_modules/node_modules` is my project-root.

@mjbvz could you please reopen this issue?
Looks like I don't have the permission to do so.

**Comment by mjbvz** [comment]
@manuth I think it'd be better if you opened a new issue that explains your use case. That way it will get new attention

**Comment by JonathanLorimer** [comment]
Was there a new issue opened for this? I am running into this issue as well.

**Comment by TomasHubelbauer** [comment]
@manuth I looked through the issues and it looks like you did not end up creating a new one?

@mjbvz could you please elaborate on what this means?

> creating a npm install of a local package

I looked at the diff you closed the linked issue with and I did not get it. I tried using this https://docs.npmjs.com/cli/v7/configuring-npm/package-json#local-paths to add a new module to my `package.json` and point it to the source file for the plugin, but according to the TS Server output, it doesn't check my `package.json` at all because its working directory is the `node_modules` directory from where `tsserver` is used from. I am using stock TypeScript in my workspace configuration because I do not need a fork of TypeScript, I just want VS Code to load the right plugin for it. Does this mean I have to load TypeScript from within my project and cannot use the global install or is there a way to use the global install in the workspace configuration and load a project-local plugin to it?
