### ISSUE TITLE
Intellisense and symbol search stops working in large Javascript project

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18847]
_From @markus-brt on September 27, 2017 8:47_

- VSCode Version: 1.16.1
- OS Version: Win10

We have a large JS project with approx. 8000 files. Since one of the latest releases the Intellisense (for all kinds of symbols, also DOM) stops working and also Symbol search (Ctrl-Shift-O). It will work for a few minutes, then it will only show "Loading..." or the loading animation of the search bar.
I noticed that the vscode process will allocate memory up to 1,2 GB and then go down to 500 MB again, (see the screenshot) and consumes 25-30% CPU. This continues for 1/2 hour. When "finished" the features works again, but only a few times until it starts over with "Loading..." and again the same CPU and memory usage.
It is also strange that my colleagues who use the same project are not affected by this issue.

![vscode_memory2](https://user-images.githubusercontent.com/18584269/30904072-19c251e8-a371-11e7-9a95-a0bf7526f27d.PNG)

Steps to Reproduce: ?
Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#35212_

**Comment by mjbvz** [comment]
_From @markus-brt on September 29, 2017 10:44_

This is the Typescript output/logs:
`[Info  - 10:34:31] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 10:34:31] Forking TSServer
PATH:...
[Error  - 10:44:39] TSServer exited with code: 3
[Info  - 10:44:39] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 10:44:39] Forking TSServer
PATH:...
[Error  - 10:44:39] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:405:32)
	at ChildProcess.childProcess.on (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:316:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Error  - 11:38:25] TSServer exited with code: 3
[Info  - 11:38:25] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 11:38:25] Forking TSServer
PATH:...
[Error  - 11:38:25] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:405:32)
	at ChildProcess.childProcess.on (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:316:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)`

**Comment by mjbvz** [comment]
@markus-brt Thank you for the logs. Does your project have a `jsconfig.json`?

Can you also try looking at the TypeScript server logs to see why it is crashing:

1. In VSCode, set `"typescript.tsserver.log": "verbose"`
2. Restart vscode and reproduce the issue
3. Open the VS Code output panel and go to the `TypeScript` section.
4. At the top of this output, there should be a message that looks like:

    ```
    [Info  - 10:54:24] Using tsserver from: /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib
    [Info  - 10:54:24] TSServer log file: /var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/vscode-tsserver-log-N4iPEB/tsserver.log
    ```
5. Open the TSServer log file at that path

Look for any errors or stack traces in this log file. The file also should have lists of all files that are being included in the project. Glance through these lists and see if any unexpected files are being included

**Comment by markus-brt** [comment]
Yes, we have jsconfig.json in two folders which exclude 3 sub-folders, which seems to work.
The log file contains all included files, but I did not find any traces of any errors (not even the one that is shown in the output (TypeScriptServiceClient)

**Comment by mhegazy** [comment]
@markus-brt  can you share more information? can you share your project? we would be happy to sign any required NDAs. Do you see the same results on a clean copy of your project (i.e. no tmp files, extra npm packages)? can you give it a try on `typescript@next` ? (VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.)

**Comment by markus-brt** [comment]
Solved - kind of:
The cause of the problem was the jsconfig.json files in two of the subfolders. Which is also the reason why colleages with the same project were not affected. Since I deleted them everything works as before.

I have no idea how these two files were created, including an "exclude" entry in one of them. I did not do this manually... are there any circumstances in which vscode will create these files?

**Comment by fenglu09** [comment]
Face the same problem.
I only have on `jsconfig.json` file in top-level.
```
[Error  - 22:42:58] 'getApplicableRefactors' request failed with error.
Error processing request. Cannot read property 'getMissingFilePaths' of undefined
TypeError: Cannot read property 'getMissingFilePaths' of undefined
    at ConfiguredProject.Project.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:79310:56)
    at ConfiguredProject.Project.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:79254:39)
    at ConfiguredProject.Project.getLanguageService (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:78994:26)
    at IOSession.Session.getApplicableRefactors (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82616:32)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:81586:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82799:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82790:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82799:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82819:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83945:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[Error  - 22:42:58] 'occurrences' request failed with error.
Error processing request. Cannot read property 'getMissingFilePaths' of undefined
TypeError: Cannot read property 'getMissingFilePaths' of undefined
    at ConfiguredProject.Project.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:79310:56)
    at ConfiguredProject.Project.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:79254:39)
    at ConfiguredProject.Project.getLanguageService (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:78994:26)
    at IOSession.Session.getOccurrences (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:81937:43)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:81557:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82799:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82790:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82799:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82819:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83945:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
[Error  - 22:42:59] 'getApplicableRefactors' request failed with error.
Error processing request. Cannot read property 'getMissingFilePaths' of undefined
TypeError: Cannot read property 'getMissingFilePaths' of undefined
    at ConfiguredProject.Project.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:79310:56)
    at ConfiguredProject.Project.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:79254:39)
    at ConfiguredProject.Project.getLanguageService (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:78994:26)
    at IOSession.Session.getApplicableRefactors (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82616:32)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:81586:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82799:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82790:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82799:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82819:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83945:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

```

**Comment by mhegazy** [comment]
@fenglu09  please file a new issue, and give us some context to be able to reproduce the issue. for instance, the version of the compiler you are using, the source project that triggered the error.. etc..
