### ISSUE TITLE
Cannot read property 'startRecordingFilesWithChangedResolutions' of undefined at InferredProject.Project.updateGraph

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#18928]
**TypeScript Version:**  nightly (2.5.0-dev.201xxxxx)

**Request**

getApplicableRefactors

**Stack**
```
TypeError: Cannot   read property 'startRecordingFilesWithChangedResolutions' of undefined
         at InferredProject.Project.updateGraph (c:\Program Files\Microsoft VS Code   Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:79253:28)
         at InferredProject.Project.getLanguageService (c:\Program Files\Microsoft VS   Code   Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:78994:26)
         at IOSession.Session.getApplicableRefactors (c:\Program Files\Microsoft VS Code   Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82616:32)
         at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program   Files\Microsoft VS Code   Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:81586:61)
         at c:\Program Files\Microsoft VS   Code   Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82799:88
         at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code   Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82790:28)
         at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code   Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82799:33)
         at IOSession.Session.onMessage   (c:\Program Files\Microsoft VS Code   Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82819:35)
         at Interface.<anonymous>   (c:\Program Files\Microsoft VS Code   Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:83945:27)
         at emitOne   (events.js:96:13)
         at Interface.emit   (events.js:191:7) 
         at Interface._onLine   (readline.js:241:10)
         at Interface._normalWrite   (readline.js:384:12)
         at Socket.ondata   (readline.js:101:10)
         at emitOne (events.js:96:13) 
         at Socket.emit   (events.js:191:7)
         at readableAddChunk   (_stream_readable.js:178:18)
         at Socket.Readable.push (_stream_readable.js:136:10)
         at Pipe.onread (net.js:560:20)

```

**Comment by sheetalkamat** [comment]
Fixed by PR #19053
