### ISSUE TITLE
Error when recovering files, breaks language service functionality

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#1895]
Upon recovering four `.ts` files (3 temporaries, 1 known saved file), I received an error from Visual Studio. From my Roaming `ActivityLog.xml` file, this seemed relevant:

```
  <entry>
    <record>393</record>
    <time>2015/02/02 20:50:45.200</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [Microsoft.VisualStudio.LanguageServices.TypeScript.TypeScriptPackage, Microsoft.VisualStudio.LanguageServices.TypeScript, Version=14.0.0.0, Culture=neutral]</description>
    <guid>{2FFE45C4-5C73-493C-B187-F2E955FF875E}</guid>
  </entry>
  <entry>
    <record>394</record>
    <time>2015/02/02 20:50:45.685</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Runtime.InteropServices.COMException (0x80020101): Exception from HRESULT: 0x80020101
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.IJavaScriptExecutionEngine.AddScript(String name, String text, Int32 textLength)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.ReinitializeEngineAndFactoryIfNeeded()
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.CreateOrUpdateShim(String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.CreateOrUpdateShim(String caption, String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.AbstractProxy`1.InvokeShimMethod[T](String methodName, Object[] arguments)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.ClassifierProxy.GetClassificationsForLine(String text, Int32 lexState)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.BufferClassifier.GetClassificationsForLine(ClassifierProxy classifier, String text, Int32 lineNum)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetClassifications(NormalizedSnapshotSpanCollection spans, List`1 classifications)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetTags(NormalizedSnapshotSpanCollection spans)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__1.MoveNext()</description>
  </entry>
  <entry>
    <record>395</record>
    <time>2015/02/02 20:50:45.716</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Runtime.InteropServices.COMException (0x80020101): Exception from HRESULT: 0x80020101
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.IJavaScriptExecutionEngine.AddScript(String name, String text, Int32 textLength)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.ReinitializeEngineAndFactoryIfNeeded()
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.CreateOrUpdateShim(String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.CreateOrUpdateShim(String caption, String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.AbstractProxy`1.InvokeShimMethod[T](String methodName, Object[] arguments)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.ClassifierProxy.GetClassificationsForLine(String text, Int32 lexState)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.BufferClassifier.GetClassificationsForLine(ClassifierProxy classifier, String text, Int32 lineNum)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetClassifications(NormalizedSnapshotSpanCollection spans, List`1 classifications)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetTags(NormalizedSnapshotSpanCollection spans)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__1.MoveNext()</description>
  </entry>
  <entry>
    <record>396</record>
    <time>2015/02/02 20:50:45.888</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Runtime.InteropServices.COMException (0x80020101): Exception from HRESULT: 0x80020101
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.IJavaScriptExecutionEngine.AddScript(String name, String text, Int32 textLength)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.ReinitializeEngineAndFactoryIfNeeded()
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.CreateOrUpdateShim(String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.CreateOrUpdateShim(String caption, String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.AbstractProxy`1.InvokeShimMethod[T](String methodName, Object[] arguments)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.ClassifierProxy.GetClassificationsForLine(String text, Int32 lexState)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.BufferClassifier.GetClassificationsForLine(ClassifierProxy classifier, String text, Int32 lineNum)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetClassifications(NormalizedSnapshotSpanCollection spans, List`1 classifications)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetTags(NormalizedSnapshotSpanCollection spans)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__1.MoveNext()</description>
  </entry>
  <entry>
    <record>397</record>
    <time>2015/02/02 20:50:45.903</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Runtime.InteropServices.COMException (0x80020101): Exception from HRESULT: 0x80020101
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.IJavaScriptExecutionEngine.AddScript(String name, String text, Int32 textLength)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.ReinitializeEngineAndFactoryIfNeeded()
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.CreateOrUpdateShim(String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.CreateOrUpdateShim(String caption, String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.AbstractProxy`1.InvokeShimMethod[T](String methodName, Object[] arguments)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.ClassifierProxy.GetClassificationsForLine(String text, Int32 lexState)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.BufferClassifier.GetClassificationsForLine(ClassifierProxy classifier, String text, Int32 lineNum)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetClassifications(NormalizedSnapshotSpanCollection spans, List`1 classifications)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetTags(NormalizedSnapshotSpanCollection spans)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__1.MoveNext()</description>
  </entry>
  <entry>
    <record>398</record>
    <time>2015/02/02 20:50:45.950</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Runtime.InteropServices.COMException (0x80020101): Exception from HRESULT: 0x80020101
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.IJavaScriptExecutionEngine.AddScript(String name, String text, Int32 textLength)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.ReinitializeEngineAndFactoryIfNeeded()
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.CreateOrUpdateShim(String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.CreateOrUpdateShim(String caption, String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.AbstractProxy`1.InvokeShimMethod[T](String methodName, Object[] arguments)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.ClassifierProxy.GetClassificationsForLine(String text, Int32 lexState)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.BufferClassifier.GetClassificationsForLine(ClassifierProxy classifier, String text, Int32 lineNum)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetClassifications(NormalizedSnapshotSpanCollection spans, List`1 classifications)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetTags(NormalizedSnapshotSpanCollection spans)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__1.MoveNext()</description>
  </entry>
  <entry>
    <record>399</record>
    <time>2015/02/02 20:50:45.981</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Runtime.InteropServices.COMException (0x80020101): Exception from HRESULT: 0x80020101
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.IJavaScriptExecutionEngine.AddScript(String name, String text, Int32 textLength)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.ReinitializeEngineAndFactoryIfNeeded()
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.CreateOrUpdateShim(String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.CreateOrUpdateShim(String caption, String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.AbstractProxy`1.InvokeShimMethod[T](String methodName, Object[] arguments)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.ClassifierProxy.GetClassificationsForLine(String text, Int32 lexState)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.BufferClassifier.GetClassificationsForLine(ClassifierProxy classifier, String text, Int32 lineNum)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetClassifications(NormalizedSnapshotSpanCollection spans, List`1 classifications)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetTags(NormalizedSnapshotSpanCollection spans)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__1.MoveNext()</description>
  </entry>
  <entry>
    <record>400</record>
    <time>2015/02/02 20:50:46.044</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Runtime.InteropServices.COMException (0x80020101): Exception from HRESULT: 0x80020101
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.IJavaScriptExecutionEngine.AddScript(String name, String text, Int32 textLength)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.ReinitializeEngineAndFactoryIfNeeded()
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.CreateOrUpdateShim(String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.CreateOrUpdateShim(String caption, String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.AbstractProxy`1.InvokeShimMethod[T](String methodName, Object[] arguments)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.ClassifierProxy.GetClassificationsForLine(String text, Int32 lexState)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.BufferClassifier.GetClassificationsForLine(ClassifierProxy classifier, String text, Int32 lineNum)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetClassifications(NormalizedSnapshotSpanCollection spans, List`1 classifications)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetTags(NormalizedSnapshotSpanCollection spans)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__1.MoveNext()</description>
  </entry>
  <entry>
    <record>401</record>
    <time>2015/02/02 20:50:46.106</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Runtime.InteropServices.COMException (0x80020101): Exception from HRESULT: 0x80020101
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.IJavaScriptExecutionEngine.AddScript(String name, String text, Int32 textLength)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.ReinitializeEngineAndFactoryIfNeeded()
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.CreateOrUpdateShim(String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.CreateOrUpdateShim(String caption, String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.AbstractProxy`1.InvokeShimMethod[T](String methodName, Object[] arguments)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.ClassifierProxy.GetClassificationsForLine(String text, Int32 lexState)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.BufferClassifier.GetClassificationsForLine(ClassifierProxy classifier, String text, Int32 lineNum)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetClassifications(NormalizedSnapshotSpanCollection spans, List`1 classifications)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetTags(NormalizedSnapshotSpanCollection spans)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__1.MoveNext()</description>
  </entry>
```

**Comment by DanielRosenwasser** [comment]
Turned out to be an error caused by an alternate LS path.

**Comment by Eshva** [comment]
to @DanielRosenwasser 
I have the same problem but can't understand your "alternate LS path". What and where have you changed?
