### ISSUE TITLE
Crash on unexpected undefined when getting suggestions for nonexistent symbol

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#19002]
**TypeScript Version**:
2.5.3-insiders.20170919
**VSCode Version**
1.17.0-insider
**command requested**
getCodeFixes
**hit count**
13128
**stack**
```
at Object.unescapeLeadingUnderscores in tsserver.js (line: 8560, column: 18)
at Object.getSuggestionForNonexistentSymbol in tsserver.js (line: 19551, column: 95)
at Object.getActionsForCorrectSpelling [as getCodeActions] in tsserver.js (line: 73149, column: 38)
at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:72873:3 in  (line: undefined, column: )
at Object.forEach in tsserver.js (line: 1294, column: 30)
at Object.getFixes in tsserver.js (line: 72872, column: 16)
at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76664:3 in  (line: undefined, column: )
at Object.flatMap in tsserver.js (line: 1526, column: 25)
at Object.getCodeFixesAtPosition in tsserver.js (line: 76662, column: 23)
at IOSession.Session.getCodeFixes in tsserver.js (line: 82655, column: 64)
at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) in tsserver.js (line: 81577, column: 61)
at IOSession.Session.executeWithRequestId in tsserver.js (line: 82790, column: 28)
at IOSession.Session.executeCommand in tsserver.js (line: 82799, column: 33)
at IOSession.Session.onMessage in tsserver.js (line: 82819, column: 35)
at Interface.<anonymous> in tsserver.js (line: 83945, column: 27)
at emitOne in events.js (line: 96, column: 13)
at Interface.emit in events.js (line: 191, column: 7)
at Interface._onLine in readline.js (line: 241, column: 10)
at Interface._normalWrite in readline.js (line: 384, column: 12)
at Socket.ondata in readline.js (line: 101, column: 10)
at emitOne in events.js (line: 96, column: 13)
at Socket.emit in events.js (line: 191, column: 7)
at readableAddChunk in _stream_readable.js (line: 178, column: 18)
at Socket.Readable.push in _stream_readable.js (line: 136, column: 10)
at Pipe.onread in net.js (line: 560, column: 20)
```

**Comment by aozgaa** [comment]
This is still showing up in 2.6.1-insiders20171019 and 2.7.0 (version marker for internal builds). For the insiders build, here is the stack we get:

```
TypeError: Cannot read property 'length' of undefined
    at Object.unescapeLeadingUnderscores (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:8560:18)
    at Object.getSuggestionForNonexistentSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:19551:95)
    at Object.getActionsForCorrectSpelling [as getCodeActions] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:73149:38)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:72873:33
    at Object.forEach (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:1294:30)
    at Object.getFixes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:72872:16)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76664:35
    at Object.flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:1526:25)
    at Object.getCodeFixesAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76662:23)
    at IOSession.Session.getCodeFixes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82655:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:81577:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82799:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82790:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82799:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82819:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83945:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment]
@sandersn we will need to put a defensive check here, or at least more logging to allow us to know what is going on.
