### ISSUE TITLE
ts service 2.6 doesn't work for projects without configs

### ISSUE THREAD

**Issue by anstarovoyt** [Microsoft/TypeScript#19216]
On open request:

ENOENT: no such file or directory, stat '/Users/anstarovoyt/WebstormProjects/untitled329/tsconfig.json'
Err 14    Exception on executing command 
```
{"sessionId":1508169937196,"seq":0,"type":"request","command":"open","arguments":{"file":"/Users/anstarovoyt/WebstormProjects/untitled329/etsts.ts"}}:
Error: ENOENT: no such file or directory, stat '/Users/anstarovoyt/WebstormProjects/untitled329/tsconfig.json'
    at Object.fs.statSync (fs.js:968:11)
    at getModifiedTime (/Users/anstarovoyt/idea/IDEA/out/classes/production/JavaScriptLanguage/jsLanguageServicesImpl/typescript/ts-plugin.js:151:19)
    at Object.addFile (/Users/anstarovoyt/idea/IDEA/out/classes/production/JavaScriptLanguage/jsLanguageServicesImpl/typescript/ts-plugin.js:194:20)
    at Object.ts_impl.sys.watchFile (/Users/anstarovoyt/idea/IDEA/out/classes/production/JavaScriptLanguage/jsLanguageServicesImpl/typescript/ts-plugin.js:81:53)
    at addFileWatcher (evalmachine.<anonymous>:98584:21)
    at createWatcherWithLogging (evalmachine.<anonymous>:98614:23)
    at Object.addFileWatcherWithLogging (evalmachine.<anonymous>:98589:16)
    at ProjectService.watchFile (evalmachine.<anonymous>:100621:96)
    at ProjectService.createConfigFileWatcherOfConfigFileExistence (evalmachine.<anonymous>:101212:90)
    at evalmachine.<anonymous>:101280:31
```

**Comment by anstarovoyt** [comment]
please note that the problem is critical for JetBrains IDEs

**Comment by anstarovoyt** [comment]
ok, I see I can handle the problem on our side by processing non-existing files.
