### ISSUE TITLE
TSServer crash with strict: true

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#19257]
TypeScript Version: 2.6.0-dev.20171015

```ts
function wat(b) {
    b();
}
```

```json
{
    "compilerOptions": {
        "strict": true
    }
}
```

```
'getCodeFixes' request failed with error.
Error processing request. Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at isFunctionExpressionOrArrowFunction (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:30997:24)
    at getContextualSignatureForFunctionLikeDeclaration (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:31000:20)
    at getReturnTypeFromBody (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:33412:39)
    at getReturnTypeOfSignature (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:25461:28)
    at buildReturnTypeDisplay (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:23140:34)
    at buildSignatureDisplay (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:23171:17)
    at writeLiteralType (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:22899:29)
    at writeAnonymousType (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:22834:25)
    at writeType (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:22686:25)
    at Object.buildTypeDisplay (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:22649:24)
    at typeToString (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:76419:51)
    at C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:76310:42
    at Object.zipWith (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:1339:25)
    at getCodeActionForParameters (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:76308:38)
    at Object.getActionsForAddExplicitTypeAnnotation [as getCodeActions] (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:76265:28)
    at C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:74743:33
    at Object.forEach (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:1312:30)
    at Object.getFixes (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:74742:16)
    at C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:79739:35
    at Object.flatMap (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:1530:25)
    at Object.getCodeFixesAtPosition (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:79737:23)
    at IOSession.Session.getCodeFixes (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:86044:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:84976:61)
    at C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:86189:88
    at IOSession.Session.executeWithRequestId (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:86180:28)
    at IOSession.Session.executeCommand (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:86189:33)
    at IOSession.Session.onMessage (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:86209:35)
    at Interface.<anonymous> (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:87344:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment]
fix up in https://github.com/Microsoft/TypeScript/pull/19264
