### ISSUE TITLE
Error: Debug Failure. False expression at computePositionOfLineAndCharacter

### ISSUE THREAD

**Issue by ikokostya** [Microsoft/TypeScript#19292]
**TypeScript Version:**  2.5.3

**Code**

Demo repo: https://github.com/ikokostya/ts-bug-debug-expr 

```ts
import * as exrepss from 'express';
//import * as express from 'express';

export default <express.RequestHandler>(() => {});
```

`tsconfig.json`: 

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "target": "es2017",
        "lib": ["es2017"],
        "noImplicitAny": true,
        "noImplicitThis": true,
        "sourceMap": false,
        "strictNullChecks": true,
        "alwaysStrict": true,
        "noEmitOnError": true,
        "baseUrl": ".",
        "types": ["node"],
        "pretty": true,
        "strict": true
    }
}
```

**Expected behavior:**

Compile error.

**Actual behavior:**

Internal `tsc` assert error:

```
$ ./node_modules/.bin/tsc -p tsconfig.json 
/home/kostya/tmp/ts-test/node_modules/typescript/lib/tsc.js:2062
            throw e;
            ^

Error: Debug Failure. False expression.
    at computePositionOfLineAndCharacter (/home/kostya/tmp/ts-test/node_modules/typescript/lib/tsc.js:3754:22)
    at Object.getPositionOfLineAndCharacter (/home/kostya/tmp/ts-test/node_modules/typescript/lib/tsc.js:3744:16)
    at Object.formatDiagnosticsWithColorAndContext (/home/kostya/tmp/ts-test/node_modules/typescript/lib/tsc.js:55612:59)
    at reportDiagnosticWithColorAndContext (/home/kostya/tmp/ts-test/node_modules/typescript/lib/tsc.js:58808:25)
    at reportDiagnostic (/home/kostya/tmp/ts-test/node_modules/typescript/lib/tsc.js:58770:9)
    at reportDiagnostics (/home/kostya/tmp/ts-test/node_modules/typescript/lib/tsc.js:58775:13)
    at compileProgram (/home/kostya/tmp/ts-test/node_modules/typescript/lib/tsc.js:59136:13)
    at compile (/home/kostya/tmp/ts-test/node_modules/typescript/lib/tsc.js:59088:26)
    at performCompilation (/home/kostya/tmp/ts-test/node_modules/typescript/lib/tsc.js:58977:33)
    at Object.executeCommandLine (/home/kostya/tmp/ts-test/node_modules/typescript/lib/tsc.js:58920:9)
    at Object.<anonymous> (/home/kostya/tmp/ts-test/node_modules/typescript/lib/tsc.js:59278:4)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/kostya/tmp/ts-test/node_modules/typescript/bin/tsc:2:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

If uncomment second line and comment the first `tsc` works without error:

```ts
//import * as exrepss from 'express';
import * as express from 'express';

export default <express.RequestHandler>(() => {});
```

**Comment by ikokostya** [comment]
Looks like error fixed in `typescript@next`:

```
t$ npm i typescript@next
npm WARN ts-test No description
npm WARN ts-test No repository field.
npm WARN ts-test No license field.

+ typescript@2.6.0-dev.20171018
updated 1 package in 4.768s
$ ./node_modules/.bin/tsc -p tsconfig.json 

t.ts(4,17): error TS2503: Cannot find namespace 'express'.

4 export default <express.RequestHandler>(() => {});
```
