### ISSUE TITLE
getEditsForRefactor failed: Cannot read property 'externalModuleIndicator' of undefined

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19395]
**TypeScript Version:**  2.6.1-insiders.20171019

**Bug**

I'm seeing this error thrown while trying to extract some code to a method:

```
[Error  - 4:09:15 PM] 'getEditsForRefactor' request failed with error.
Error processing request. Cannot read property 'externalModuleIndicator' of undefined
TypeError: Cannot read property 'externalModuleIndicator' of undefined
    at Object.isExternalModule (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:12466:20)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:21856:101
    at Object.forEachEntry (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2044:26)
    at trySymbolTable (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:21852:27)
    at getAccessibleSymbolChainFromSymbolTable (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:21832:30)
    at forEachSymbolTableInScope (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:21817:20)
    at getAccessibleSymbolChain (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:21827:20)
    at getSymbolChain (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:22543:49)
    at symbolToName (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:22508:29)
    at symbolToTypeReferenceName (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:22276:103)
    at typeReferenceToTypeNode (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:22331:46)
    at typeToTypeNodeHelper (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:22151:28)
    at typeReferenceToTypeNode (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:22286:43)
    at typeToTypeNodeHelper (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:22151:28)
    at Object.typeToTypeNode (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:22059:41)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77965:44
    at Map.forEach (native)
    at extractFunctionInScope (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77960:31)
    at getFunctionExtractionAtIndex (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77834:24)
    at Object.getEditsForAction (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77538:28)
    at Object.getEditsForRefactor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:74989:41)
    at Object.getEditsForRefactor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:80201:32)
    at IOSession.Session.getEditsForRefactor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86457:59)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85418:61)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86645:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86636:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86645:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86665:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:87857:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

I'll try to come up with a small repo. Right now I've only see this while working in the vscode codebase

**Comment by mhegazy** [comment]
@amcasey can you take a look.

**Comment by amcasey** [comment]
That stack appears to indicate that some node lacks a containing `SourceFile`.  Normally, I would assume that I'd passed a synthesized node somewhere I shouldn't have, but (a) the refactoring is calling `typeToTypeNode` (i.e. I'm passing a Type) and (b) this only happens some of the time.

A repro would be very helpful.

**Comment by mjbvz** [comment]
Here's a project that reproduces this: 
[test-workspace.zip](https://github.com/Microsoft/TypeScript/files/1423673/test-workspace.zip)

To repo:

1. Run `npm install`
2. Open in vscode
3. In index.ts, select the entire line `  const notification = req.body.payload ? JSON.parse(req.body.payload) : req.body;` and try to `extract to function in module scope`

This example appears to be fixed in typescript@next

**Comment by amcasey** [comment]
fd8980830ca35f07d838de5457504b95e6974d3c hides the failure.  I'll debug without it.

**Comment by amcasey** [comment]
`extractFunctionInScope` is passing a synthesized block to `checker.typeToTypeNode`.

**Comment by amcasey** [comment]
Probably just copy-paste - every other call passes `scope`.

**Comment by amcasey** [comment]
I'm confident in my local fix, but it'll take me a little while to come up with a standalone repro (i.e. not tonight :wink:).
