### ISSUE TITLE
TSServer error thrown when requesting any completion entry details for JSDoc

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#19442]
```ts
/**
 * @typedef {object} Wat
 * 
 */

var x;
```

Request a completion at the end of the line following the `typedef`, in either a TypeScript or JavaScript file.

```
TypeError: Cannot read property 'length' of undefined
    at Object.find (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:1376:34)
    at Object.getCompletionEntryDetails (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:65293:33)
    at Object.getCompletionEntryDetails (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:79796:35)
    at C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:86249:64
    at Object.mapDefined (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:1611:30)
    at IOSession.Session.getCompletionEntryDetails (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:86248:27)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:85346:61)
    at C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:86695:88
    at IOSession.Session.executeWithRequestId (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:86686:28)
    at IOSession.Session.executeCommand (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:86695:33)
    at IOSession.Session.onMessage (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:86715:35)
    at Interface.<anonymous> (C:\Users\drosen\AppData\Local\nvs\node\8.6.0\x64\node_modules\typescript\lib\tsserver.js:87907:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

```

**Comment by andy-ms** [comment]
@DanielRosenwasser I can't reproduce this, could you try writing a fourslash test?

**Comment by DanielRosenwasser** [comment]
Here

```ts
/// <reference path="fourslash.ts" />

/////**
//// * @typedef {object} Wat
//// * /**/
//// */

goTo.marker();
verify.completionEntryDetailIs("@property", "Completion details for the property tag.");
```

**Comment by DanielRosenwasser** [comment]
Since we do this for keywords, the correct behavior is probably to return `@` + the same text as the tag itself.

**Comment by DanielRosenwasser** [comment]
And note the same behavior reproducing for if you have an existing `@`, which is important to note because it takes a different code path:

```ts
/**
 * @typedef {object} Wat
 * @/*MARKERHERE*/
 */
```

**Comment by DanielRosenwasser** [comment]
In fact, all the completion entry details for JSDoc are busted...

```ts
/**
 * @param {/*MARKER_HERE*/}
 */
function foo(x, y) {

}
```
