### ISSUE TITLE
Logging output from intellisense crash in VS 2017

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#19532]
**TypeScript Version:**  2.6 RC
**Visual Studion:** 2017 15.4 

The log file has a number of occurrences of the following errors around the time the intellisense crashes.

Exception on executing command :
* documentHighlights-full 
* getApplicableRefactors 
* compileOnSaveAffectedFileList 
* encodedSemanticClassifications-full 
* synchronizeProjectList 
* applyChangedToOpenFiles 
* syntacticDiagnosticsSync

I'm following up with @mhegazy offline. Just posting them here.

**Stack traces**

```
Starting updateGraphWorker: Project: B:/foo.globals/tsconfig.json
Err 69471 [17:16:39.530] Exception on executing command unknown:
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.startCachingPerDirectoryResolution (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:80416:22)
    at ConfiguredProject.Project.updateGraphWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81412:38)
    at ConfiguredProject.Project.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81365:39)
    at ConfiguredProject.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81658:53)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:82141:33
    at ThrottledOperations.run (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:79706:17)
    at ontimeout [as _onTimeout] (timers.js:202:24)
    at Timer.listOnTimeout (timers.js:92:15)



Err 69475 [17:16:39.539] Exception on executing command {"seq":34189,"command":"documentHighlights-full","arguments":{"file":"b:\relations.d.ts","position":561,"filesToSearch":["b:\relations.d.ts"]}}:
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.startCachingPerDirectoryResolution (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:80416:22)
    at ConfiguredProject.Project.updateGraphWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81412:38)
    at ConfiguredProject.Project.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81365:39)
    at ConfiguredProject.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81658:53)
    at ConfiguredProject.Project.getLanguageService (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81095:26)
    at IOSession.Session.getDocumentHighlights (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:84181:50)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:83780:61)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85013:88
    at IOSession.Session.executeWithRequestId (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85004:28)
    at IOSession.Session.executeCommand (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85013:33)
    at IOSession.Session.onMessage (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85033:35)
    at Interface.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:86168:27)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface.<anonymous> (readline.js:340:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:339:11)
    at Socket.ondata (readline.js:86:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)


Err 69477 [17:16:39.709] Exception on executing command {"seq":34243,"command":"getApplicableRefactors","arguments":{"file":"b:\\relations.d.ts","startPosition":561,"endPosition":561}}:
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.startCachingPerDirectoryResolution (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:80416:22)
    at ConfiguredProject.Project.updateGraphWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81412:38)
    at ConfiguredProject.Project.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81365:39)
    at ConfiguredProject.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81658:53)
    at ConfiguredProject.Project.getLanguageService (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81095:26)
    at IOSession.Session.getApplicableRefactors (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:84829:32)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:83803:61)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85013:88
    at IOSession.Session.executeWithRequestId (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85004:28)
    at IOSession.Session.executeCommand (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85013:33)
    at IOSession.Session.onMessage (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85033:35)
    at Interface.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:86168:27)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface.<anonymous> (readline.js:340:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:339:11)
    at Socket.ondata (readline.js:86:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)


Err 69479 [17:16:39.890] Exception on executing command {"seq":34255,"command":"compileOnSaveAffectedFileList","arguments":{"file":"b:\\persistent.d.ts","projectFileName":"b:/tsconfig.json"}}:
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.startCachingPerDirectoryResolution (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:80416:22)
    at ConfiguredProject.Project.updateGraphWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81412:38)
    at ConfiguredProject.Project.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81365:39)
    at ConfiguredProject.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81658:53)
    at ProjectService.updateProjectGraphs (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:82267:28)
    at ProjectService.ensureProjectStructuresUptoDate (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:82233:26)
    at ProjectService.getScriptInfoEnsuringProjectsUptoDate (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:82216:22)
    at IOSession.Session.getCompileOnSaveAffectedFileList (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:84589:48)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:83691:61)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85013:88
    at IOSession.Session.executeWithRequestId (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85004:28)
    at IOSession.Session.executeCommand (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85013:33)
    at IOSession.Session.onMessage (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85033:35)
    at Interface.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:86168:27)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface.<anonymous> (readline.js:340:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:339:11)
    at Socket.ondata (readline.js:86:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)




Err 69485 [17:16:40.629] Exception on executing command {"seq":34414,"command":"encodedSemanticClassifications-full","arguments":{"file":"b:\\relations.d.ts","start":0,"length":562}}:
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.startCachingPerDirectoryResolution (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:80416:22)
    at ConfiguredProject.Project.updateGraphWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81412:38)
    at ConfiguredProject.Project.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81365:39)
    at ConfiguredProject.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81658:53)
    at ConfiguredProject.Project.getLanguageService (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81095:26)
    at IOSession.Session.getEncodedSemanticClassifications (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:84020:32)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:83706:61)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85013:88
    at IOSession.Session.executeWithRequestId (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85004:28)
    at IOSession.Session.executeCommand (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85013:33)
    at IOSession.Session.onMessage (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85033:35)
    at Interface.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:86168:27)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface.<anonymous> (readline.js:340:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:339:11)
    at Socket.ondata (readline.js:86:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)



Err 69551 [17:16:42.449] Exception on executing command {"seq":34621,"command":"synchronizeProjectList","arguments":{"knownProjects":[{"projectName":<Omitted>}}:
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.startCachingPerDirectoryResolution (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:80416:22)
    at ConfiguredProject.Project.updateGraphWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81412:38)
    at ConfiguredProject.Project.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81365:39)
    at ConfiguredProject.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81658:53)
    at ConfiguredProject.Project.getChangesSinceVersion (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81516:22)
    at _loop_10 (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:83111:38)
    at ProjectService.collectChanges (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:83115:21)
    at ProjectService.synchronizeProjectList (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:83121:22)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:83576:59)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85013:88
    at IOSession.Session.executeWithRequestId (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85004:28)
    at IOSession.Session.executeCommand (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85013:33)
    at IOSession.Session.onMessage (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85033:35)
    at Interface.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:86168:27)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface.<anonymous> (readline.js:340:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:339:11)
    at Socket.ondata (readline.js:86:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)


Err 69559 [17:16:43.310] Exception on executing command {"seq":34624,"command":"applyChangedToOpenFiles","arguments":{"closedFiles":["b:\\relations.d.ts"]}}:
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.startCachingPerDirectoryResolution (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:80416:22)
    at ConfiguredProject.Project.updateGraphWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81412:38)
    at ConfiguredProject.Project.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81365:39)
    at ConfiguredProject.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81658:53)
    at ProjectService.updateProjectGraphs (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:82267:28)
    at ProjectService.ensureProjectStructuresUptoDate (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:82233:26)
    at ProjectService.applyChangesInOpenFiles (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:83150:26)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:83595:46)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85013:88
    at IOSession.Session.executeWithRequestId (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85004:28)
    at IOSession.Session.executeCommand (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85013:33)
    at IOSession.Session.onMessage (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85033:35)
    at Interface.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:86168:27)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface.<anonymous> (readline.js:340:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:339:11)
    at Socket.ondata (readline.js:86:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)


Err 69561 [17:16:43.311] Exception on executing command {"seq":34625,"command":"syntacticDiagnosticsSync","arguments":{"file":"b:\\relations.d.ts","includeLinePosition":true}}:
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.startCachingPerDirectoryResolution (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:80416:22)
    at ConfiguredProject.Project.updateGraphWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81412:38)
    at ConfiguredProject.Project.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81365:39)
    at ConfiguredProject.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81658:53)
    at ConfiguredProject.Project.getLanguageService (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:81095:26)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:84169:105
    at IOSession.Session.getDiagnosticsWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:84076:35)
    at IOSession.Session.getSyntacticDiagnosticsSync (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:84169:29)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:83716:61)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85013:88
    at IOSession.Session.executeWithRequestId (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85004:28)
    at IOSession.Session.executeCommand (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85013:33)
    at IOSession.Session.onMessage (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:85033:35)
    at Interface.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js:86168:27)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface.<anonymous> (readline.js:340:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:339:11)
    at Socket.ondata (readline.js:86:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

**Comment by eminence** [comment]
I might be seeing something similar in IntelliJ, using both TypeScript 2.6.1 and 2.7-DEV.

```
Process: Error processing message: Debug Failure. False expression. Error: Debug Failure. False expression.
    at ProjectService.getOrCreateScriptInfoForNormalizedPath (evalmachine.<anonymous>:103605:30)
    at ProjectService.getOrCreateScriptInfoOpenedByClientForNormalizedPath (evalmachine.<anonymous>:103577:29)
    at ProjectService.openClientFileWithNormalizedPath (evalmachine.<anonymous>:103777:33)
    at IDESession.changeFileEx (C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2017.1\plugins\JavaScriptLanguage\jsLanguageServicesImpl\typescript\ts-session-new.js:341:42)
    at IDESession.updateFilesEx (C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2017.1\plugins\JavaScriptLanguage\jsLanguageServicesImpl\typescript\ts-session.js:204:30)
    at IDESession.executeCommand (C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2017.1\plugins\JavaScriptLanguage\jsLanguageServicesImpl\typescript\ts-session-new.js:247:33)
    at IDESession.Session.onMessage (evalmachine.<anonymous>:99108:35)
    at IDESession.onMessage (C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2017.1\plugins\JavaScriptLanguage\jsLanguageServicesImpl\typescript\ts-session.js:43:40)
    at TypeScriptLanguagePlugin.onMessage (C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2017.1\plugins\JavaScriptLanguage\jsLanguageServicesImpl\typescript\ts-plugin.js:130:23)
    at Interface.<anonymous> (C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2017.1\plugins\JavaScriptLanguage\jsLanguageServicesImpl\js-language-service.js:105:39)

```

Interestingly, running `tsc -p .` from the command line doesn't yield any errors.  (And if I downgrade to TypeScript 2.5.3, there are no problems)

Could my issue be related to your issue?

**Comment by NoelAbrahams** [comment]
@eminence, I would say your error `Error processing message` is different to mine  `Exception on executing command`. Also I'm pretty sure the problems I'm having are related to Visual Studio compile-on-save.

**Comment by NoelAbrahams** [comment]
Renaming a folder causes TypeScript intellisense to crash predictably. Reported via "Report a Problem".

[Renaming a folder in a VS 2017 project causes TypeScript intellisense to crash](https://developercommunity.visualstudio.com/content/problem/143055/renaming-a-folder-in-a-vs-2017-project-causes-type.html)

**Comment by dploeger** [comment]
@eminence This seems to be a Jetbrains-Bug. I downgraded to Typescript < 2.6 and created an [issue on YouTrack](https://youtrack.jetbrains.com/issue/IDEA-181763).

**Comment by dploeger** [comment]
@eminence It's already fixed in 2017.2.6, which should be out in a few days.

**Comment by eminence** [comment]
@dploeger thank you very much!

**Comment by mhegazy** [comment]
you can find more documentation in https://billti.github.io/jsdocs/articles/troubleshooting/index.html#enable-detailed-language-service-logging
