### ISSUE TITLE
@ts-ignore make new errors wrongly

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#19952]
I think my change shouldn't make the following errors.

https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/301046625#L2867

related?: #19951

**TypeScript Version:**  2.7.0-dev.20171112

**Code**

```diff
 declare global {
     interface Set<T> { }
     interface Map<K, V> { }
+    // @ts-ignore
     interface WeakSet<T> { }
     interface WeakMap<K extends object, V> { }
 }
```

**Expected behavior:**

pass

**Actual behavior:**

```
ERROR: 11893:9  expect  TypeScript@next compile error: 
Type 'PartialDeep<TResult>' is not assignable to type 'Pick<TResult, "a" | "b">'.
  Types of property 'a' are incompatible.
    Type 'number | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'.
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:74:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
Testing lodash
	Running: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js --onlyTestTsNext
	Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/lodash/lodash-tests.ts
ERROR: 11893:9  expect  TypeScript@next compile error: 
Type 'PartialDeep<TResult>' is not assignable to type 'Pick<TResult, "a" | "b">'.
  Types of property 'a' are incompatible.
    Type 'number | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'.
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:74:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
...
```

**Comment by RyanCavanaugh** [comment]
`ts-ignore` is a use-at-your-own-risk feature. If you ignore an error in a *declaration* (😱), or other places where type inference is dependent on a result of an error expression, we really can't guarantee any behavior from there.

**Comment by mhegazy** [comment]
what @RyanCavanaugh said. also please note that `@ts-ignore` should not be used in a .d.ts ever..

**Comment by falsandtru** [comment]
I see.
