### ISSUE TITLE
SourceFile.ambientModuleNames is undefined after transform()

### ISSUE THREAD

**Issue by dherges** [microsoft/TypeScript#19950]
**TypeScript Version:**  2.4.2 (stuck to this TypeScript version because of Angular 5.0.1)

**Code**

```ts
import * as ts from 'typescript';

  // transform typescript AST prior to compilation
  const transformationResult: ts.TransformationResult<ts.SourceFile> = ts.transform(
    tsProgram.getSourceFiles(),
    [ /* customTransformers */ ],
    options
  );

  // Wraps a CompilerHost reading SourceFile's from the previous TransformationResult
  function wrapCompilerHost({transformation, options}): ts.CompilerHost {
    const wrapped = ts.createCompilerHost(options);

    return {
      ...wrapped,
      getSourceFile: (fileName, version) => {
        const inTransformation = transformation.transformed.find((file) => file.fileName === fileName);

        if (inTransformation) {
          return inTransformation;
        } else {
          return wrapped.getSourceFile(fileName, version);
        }
      }
    }
  }

  // then, do another compilation
  const wrappingCompilerHost = wrapCompilerHost(transformationResult, options);
  ts.createProgram(/*..*/, wrappingCompilerHost).emit(/* .. */);
```

**Expected behavior:**

Should "ambientModuleNames" not be copied/applied to the transformed `SourceFile`?

**Actual behavior:**

After `ts.transform(..)`, the "ambientModuleNames" of `SourceFile` is undefined, resulting in the following error:

```
"TypeError: Cannot read property 'length' of undefined
    at resolveModuleNamesReusingOldState (~ng-packagr/node_modules/typescript/lib/typescript.js:69409:80)
    at processImportedModules (~ng-packagr/node_modules/typescript/lib/typescript.js:70364:35)
    at findSourceFile (~ng-packagr/node_modules/typescript/lib/typescript.js:70274:17)
    at processImportedModules (~ng-packagr/node_modules/typescript/lib/typescript.js:70393:25)
    at findSourceFile (~ng-packagr/node_modules/typescript/lib/typescript.js:70274:17)
    at args (~ng-packagr/node_modules/typescript/lib/typescript.js:70200:85)
    at getSourceFileFromReferenceWorker (~ng-packagr/node_modules/typescript/lib/typescript.js:70173:34)
    at processSourceFile (~ng-packagr/node_modules/typescript/lib/typescript.js:70200:13)
    at processRootFile (~ng-packagr/node_modules/typescript/lib/typescript.js:70055:13)
    at ~ng-packagr/node_modules/typescript/lib/typescript.js:69312:60"
```

Original `SourceFile` has `ambientModuleName`. The transformed source file hasn't:

![screen shot 2017-11-12 at 21 27 38](https://user-images.githubusercontent.com/901354/32703146-f2fe979c-c7f1-11e7-8d43-6cacf20aec5c.png)

**Comment by dherges** [comment]
Current workaround is:

```ts
          // FIX see https://github.com/Microsoft/TypeScript/issues/19950
          if (!inTransformation['ambientModuleNames']) {
            inTransformation['ambientModuleNames'] = inTransformation['original']['ambientModuleNames'];
          }

```

**Comment by mhegazy** [comment]
A PR would be appreciated.

**Comment by Yogu** [comment]
So does this error occur in a regular Angular application for you or just when you write custom transformations? I get exactly this error at the same location when using `@ViewChild` with the definite assignment operator (`!` after the property name).

**Comment by dherges** [comment]
@Yogu Don't think so.

It happened due to custom transformations in the build process but it didn't seem to be related to a particular code expression in the source file. It seemed that any source file with a transformation ran into that issue. If there was no transformation on the source file, no issue.

It was either resolved in a TypeScript version newer than 2.4.x or the Angular compiler newer than 5.x ... or the code branch in question is no longer being hit in the newer version of Angular compiler / ng-packagr.

Do you have a repro in the latest TypeScript version?

**Comment by RyanCavanaugh** [comment]
The requested behavior is part of the pre-TypeScript-7 JavaScript Compiler API. That API, including the `SourceFile` objects returned by `ts.transform` and reused through a custom `CompilerHost`, is no longer being developed; it has been superseded by the TypeScript 7 API.
