### ISSUE TITLE
API: exception caused by invalid(?) JSDoc

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#20030]
**TypeScript Version:**  2.7.0-dev.20171115
**Code**

Trying to get the JsDocTags from the method signature below (`signature.getJsDocTags()`) crashes with the following exception:

```
TypeError: Cannot read property 'getText' of undefined
    at withNode (/Users/klaus/code/tslint/node_modules/typescript/lib/typescript.js:83916:29)
    at getCommentText (/Users/klaus/code/tslint/node_modules/typescript/lib/typescript.js:83906:28)
    at /Users/klaus/code/tslint/node_modules/typescript/lib/typescript.js:83892:63
    at forEachUnique (/Users/klaus/code/tslint/node_modules/typescript/lib/typescript.js:83931:38)
    at Object.getJsDocTagsFromDeclarations (/Users/klaus/code/tslint/node_modules/typescript/lib/typescript.js:83889:13)
    at SignatureObject.getJsDocTags (/Users/klaus/code/tslint/node_modules/typescript/lib/typescript.js:95615:62)
```

```ts
// from @types/chai@3.5.2
interface Assert {
        /**
         * Asserts that actual is deeply equal to expected.
         * 
         * @type T   Type of the objects.
         * @param actual   Actual value.
         * @param expected   Potential expected value.
         * @param message   Message to display on error.
         */
        deepEqual<T>(actual: T, expected: T, message?: string): void;
}
```

**Expected behavior:**

No exception

**Actual behavior:**

Exception, because `JSDocTypeTag.typeExpression` is undefined.

**Comment by ajafff** [comment]
This should be fixed by the `strictNullChecks` PR. Also the relevant code was refactored a lot recently so the call stack is no longer accurate.
Closing because this is no longer an issue for me.
