### ISSUE TITLE
tsserver Died

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#20286]
_From @DrYSG on November 17, 2017 15:51_

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-npm|fkn|3.3.0
status-bar-tasks|Gua|0.2.1
typings-autoinstaller|jvi|1.2.0
csharp|ms-|1.13.1
PowerShell|ms-|1.5.1
debugger-for-chrome|msj|3.5.0
partial-diff|ryu|0.5.0

---

Steps to Reproduce:

I am working a project that is purely Javascript. I don't know why this message pops up (I am not even running WebPack, just native es6 for Chrome v61
.

Reproduces without extensions: Yes/No

_Copied from original issue: Microsoft/vscode#38634_

**Comment by mjbvz** [comment]
Does this reproduce if you disable all extensions? 

Also, please open the output panel and go to the `TypeScript` section. Are there any error messages in there?

**Comment by mjbvz** [comment]
_From @DrYSG on November 20, 2017 17:48_

I will try to do more tomorrow (sponsors are here today). But this is what I get when I open the console:


A few more details. I do not have any TypeScript code in my project (folder tree). I did install a good number of NPM projects, but I do not have that code opened. 

I also have a few very large JSON files, that are actually with the .js extension (so that I can import them). I know they are over 20K lines, so the colorization and formatting is turned off. Could that be the issue?


Warn: The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

```
[Info  - 12:41:39 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:41:39 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Info  - 12:41:39 PM] Started TSServer
[Error  - 12:42:11 PM] TSServer exited with code: 3
[Info  - 12:42:12 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:42:12 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Error  - 12:42:12 PM] 'getSupportedCodeFixes' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:388:32)
	at ChildProcess.childProcess.on (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:291:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 12:42:12 PM] Started TSServer
[Error  - 12:42:43 PM] TSServer exited with code: 3
[Info  - 12:42:43 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:42:43 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Error  - 12:42:43 PM] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:388:32)
	at ChildProcess.childProcess.on (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:291:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 12:42:43 PM] Started TSServer
[Error  - 12:43:14 PM] TSServer exited with code: 3
[Info  - 12:43:14 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:43:14 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Info  - 12:43:14 PM] Started TSServer
[Error  - 12:43:45 PM] TSServer exited with code: 3
[Info  - 12:43:45 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:43:45 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Info  - 12:43:45 PM] Started TSServer
[Error  - 12:44:17 PM] TSServer exited with code: 3
[Info  - 12:44:17 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:44:17 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Info  - 12:44:17 PM] Started TSServer
[Error  - 12:44:48 PM] TSServer exited with code: 3
[Info  - 12:44:48 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:44:48 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Error  - 12:44:48 PM] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:388:32)
	at ChildProcess.childProcess.on (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:291:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 12:44:48 PM] Started TSServer
[Error  - 12:45:20 PM] TSServer exited with code: 3
[Info  - 12:45:20 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:45:20 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Error  - 12:45:20 PM] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:388:32)
	at ChildProcess.childProcess.on (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:291:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 12:45:20 PM] Started TSServer
[Error  - 12:45:51 PM] TSServer exited with code: 3
[Info  - 12:45:51 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:45:51 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Error  - 12:45:51 PM] 'docCommentTemplate' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:388:32)
	at ChildProcess.childProcess.on (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:291:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 12:45:51 PM] Started TSServer
[Error  - 12:46:23 PM] TSServer exited with code: 3
[Info  - 12:46:23 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:46:23 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Error  - 12:46:23 PM] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:388:32)
	at ChildProcess.childProcess.on (d:\Program Files\Microsoft VS Code\resources\app\extensions\typescript\out\typescriptServiceClient.js:291:30)
	at emitTwo (events.js:111:20)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Info  - 12:46:23 PM] Started TSServer
[Error  - 12:46:55 PM] TSServer exited with code: 3
[Info  - 12:46:55 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:46:55 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Info  - 12:46:55 PM] Started TSServer
[Error  - 12:47:26 PM] TSServer exited with code: 3
[Info  - 12:47:26 PM] Using tsserver from: d:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:47:26 PM] Forking TSServer
PATH: D:\MAK\makRti4.4.2\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\PFPS\system;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\ysg4206\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\program files\MATLAB\R2017a\runtime\win64;c:\program files\MATLAB\R2017a\bin;D:\Program Files\FME\;D:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;D:\MAK\makRti4.4.2\bin;C:\Users\ysg4206\AppData\Local\Microsoft\WindowsApps;C:\Users\ysg4206\AppData\Local\Programs\Fiddler;C:\Users\ysg4206\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
[Info  - 12:47:26 PM] Started TSServer

```

**Comment by mjbvz** [comment]
Thanks. Looks like the TSServer is indeed crashing. Can you please try looking in the TS Server logs to see if there are any error messages or stack traces that indicate what is causing the crash:

Please try collecting the TypeScript server logs to see if that has any leads:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Now go to the `TypeScript` section of the output window again and look for a line that looks:

```ts
[Info  - 3:17:45 PM] TSServer log file: /var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/vscode-tsserver-log-xdcYW1/tsserver.log
```

4. Open the TServer log at that path

 If you are able to share the logs, I can also look through them to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by mjbvz** [comment]
_From @DrYSG on November 22, 2017 20:32_

enclosed are the log files directly after the WARN.
[tsserver.log](https://github.com/Microsoft/vscode/files/1497394/tsserver.log)
[ti-25676.log](https://github.com/Microsoft/vscode/files/1497395/ti-25676.log)

**Comment by mjbvz** [comment]
@DrYSG Thanks!  I don't see anything obvious in those logs but someone on the TypeScript team may know more.

I suspect that the large js/json files may be to blame here. Can you please try excluding them temporarily to see if that fixes the problem. Two ways to do this:

1. Rename them to `*.json`
2. Exclude them from your javascript project. To do this, close all active editors and then create a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) file at the root of your project with the contents:

```
{
    "compilerOptions": {
        "target": "ES6"
    },
    "include": [
        "./src/good/files/**/*.js"
    ],
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

**Comment by RyanCavanaugh** [comment]
Checking the server log for clues

**Comment by RyanCavanaugh** [comment]
I agree the larges file are likely the culprit. Does the server process grow quickly to about 1.2 GB of memory used and then crash?

A directory listing that includes file sizes would be very useful to us as well.

**Comment by DrYSG** [comment]
I am out of town at a conference in Orlando, and I don't have access here to my work computer. Can you wait a day or two till I can answer?

**Comment by DrYSG** [comment]
Yes, they are big files, and I load all of them (this is still a prototype, we are testing out, in the end we will probably provide the JSON from a Cloud DB, but for now we wanted to test out the data as an "embedded resource" using a VS-Studio term.  Even so, I agree it should not be a .JS file (I only did that since I wanted to use import).

Now I see that RollupJS has a plugin that can embed the JSON, so that is probably what I will do.

Still it is odd that TypeScript is running over these JS files, since there is no TypeScript in the program.

Here are the file sizes:

![image](https://user-images.githubusercontent.com/2865368/33444363-19ef6c9e-d5c8-11e7-8235-69a789060857.png)

**Comment by mhegazy** [comment]
> Still it is odd that TypeScript is running over these JS files, since there is no TypeScript in the program.

TypeScript is what drives the JavaScript experience in VSCode, your completion, go to def, find all refs, format, colorize... etc.. so it runs on any .js or .ts file. it needs to load *all* files in the project to be able to provide these features for you.

consider adding `data` to your `excludes` in `jsconfig.json` as a workaround.

**Comment by DrYSG** [comment]
Done, and thank you for looking at this. It really helps to know there are people behind this!

**Comment by mjbvz** [comment]
Closing as out of date. If you still see crashes using the latest typescript@next in VS Code, please open a new issue
