### ISSUE TITLE
Error: Debug Failure. False expression:

### ISSUE THREAD

**Issue by juni381** [Microsoft/TypeScript#20388]
**TypeScript Version:**  2.0.3

Error: Debug Failure. False expression:
    at Object.assert (F:\DigiRep\Frontend-Digirep\theme\node_modules\typescript\lib\tsc.js:1316:23)
    at emitModuleDeclaration (F:\DigiRep\Frontend-Digirep\theme\node_modules\typescript\lib\tsc.js:35577:26)
    at emitJavaScriptWorker (F:\DigiRep\Frontend-Digirep\theme\node_modules\typescript\lib\tsc.js:36984:32)
    at emitNodeWithoutSourceMap (F:\DigiRep\Frontend-Digirep\theme\node_modules\typescript\lib\tsc.js:36782:21)
    at emitNodeWithSourceMap (F:\DigiRep\Frontend-Digirep\theme\node_modules\typescript\lib\tsc.js:36776:21)
    at emitNodeConsideringCommentsOption (F:\DigiRep\Frontend-Digirep\theme\node_modules\typescript\lib\tsc.js:36767:21)
    at emit (F:\DigiRep\Frontend-Digirep\theme\node_modules\typescript\lib\tsc.js:36750:17)
    at emitLinesStartingAt (F:\DigiRep\Frontend-Digirep\theme\node_modules\typescript\lib\tsc.js:31503:21)
    at emitCommonJSModule (F:\DigiRep\Frontend-Digirep\theme\node_modules\typescript\lib\tsc.js:36508:17)
    at emitSourceFileNode (F:\DigiRep\Frontend-Digirep\theme\node_modules\typescript\lib\tsc.js:36730:25)

**Comment by juni381** [comment]
i clone the project ... then give the command npm install then npm start !!! then this error came out

**Comment by mhegazy** [comment]
You will need to share the sources that caused the issue, and you should also give `typescript@2.6` a try.
