### ISSUE TITLE
Debug Failure. False expression: Script info with relative file name can only be open script info

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#20476]
Hits / Session : 62.2

Stack:
```
Error: Debug Failure. False expression: Script info with relative file name can only be open script info
    at ProjectService.getOrCreateScriptInfoWorker (tsserver.js:84869:30)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClientForNormalizedPath (tsserver.js:84856:29)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClient (tsserver.js:84836:29)
    at InferredProject.Project.getOrCreateScriptInfoAndAttachToProject (tsserver.js:82909:54)
    at InferredProject.Project.getScriptSnapshot (tsserver.js:82929:39)
    at HostCache.createEntry (tsserver.js:79730:44)
    at new HostCache (tsserver.js:79721:22)
    at synchronizeHostData (tsserver.js:79934:29)
    at Object.getProgram (tsserver.js:80017:13)
    at InferredProject.Project.updateGraphWorker (tsserver.js:83319:53)
    at InferredProject.Project.updateGraph (tsserver.js:83269:39)
    at InferredProject.Project.getLanguageService (tsserver.js:83005:26)
    at IOSession.Session.getCompletions (tsserver.js:86552:43)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:85661:61)
    at tsserver.js:87022:88
    at IOSession.Session.executeWithRequestId (tsserver.js:87013:28)
    at IOSession.Session.executeCommand (tsserver.js:87022:33)
    at IOSession.Session.onMessage (tsserver.js:87042:35)
    at Interface.<anonymous> (tsserver.js:88234:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment]
The `Source: Telemetry` have limited information. we only have the call stack from the crash report. We need to either mitigate the crash, or add additional asserts to get more information in future crash reports.

**Comment by sheetalkamat** [comment]
#21282 adds more information in the assert to help investigate this further.

**Comment by amcasey** [comment]
Customer reports a new occurrence, presumably with the enhanced asserts.

https://developercommunity.visualstudio.com/content/problem/372072/typescript-intellisenseformatting-is-lost-once-a-b.html

**Comment by amcasey** [comment]
@sheetalkamat Can you help?

**Comment by InduPrakash** [comment]
We are noticing a potentially related issue when using TypeScript 3.0. I originally reported the issue in [VS Form](https://developercommunity.visualstudio.com/content/problem/372072/typescript-intellisenseformatting-is-lost-once-a-b.html?childToView=376721#comment-376721) and was suggested to post one of the errors (from tss logging) here.


Err 6993  [16:39:13.823] Exception on executing command {"seq":1241,"command":"applyChangedToOpenFiles","arguments":{"openFiles":[{"fileName":"^ScriptDocument274 TurboGridDemo.ts","scriptKind":3,"content":"/** ...

	    
    Debug Failure. False expression: 
Verbose Debug Information: {"fileName":"../../../../../../typings/@epic/Core.d.ts","currentDirectory":"C:/EpicSource/8.6/App St1/HSWeb/Solutions/Fnd","hostCurrentDirectory":"C:/EpicSource/8.6/App St1/HSWeb/Solutions/Fnd","openKeys":[]}
Script info with non-dynamic relative file name can only be open script info

    Error: Debug Failure. False expression: 
Verbose Debug Information: {"fileName":"../../../../../../typings/@epic/Core.d.ts","currentDirectory":"C:/EpicSource/8.6/App St1/HSWeb/Solutions/Fnd","hostCurrentDirectory":"C:/EpicSource/8.6/App St1/HSWeb/Solutions/Fnd","openKeys":[]}
Script info with non-dynamic relative file name can only be open script info
    at ProjectService.getOrCreateScriptInfoWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:117058:30)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClientForNormalizedPath (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:117043:29)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClient (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:116980:29)
    at InferredProject.Project.getOrCreateScriptInfoAndAttachToProject (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:114963:54)
    at InferredProject.Project.getScriptSnapshot (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:114983:39)
    at HostCache.createEntry (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:110979:44)
    at HostCache.getOrCreateEntryByPath (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:111002:58)
    at getOrCreateSourceFileByPath (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:111312:66)
    at Object.getOrCreateSourceFile [as getSourceFile] (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:111305:24)
    at findSourceFile (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:83824:29)
    at args (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:83736:85)
    at getSourceFileFromReferenceWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:83703:34)
    at processSourceFile (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:83736:13)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:83906:17
    at Object.forEach (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:206:30)
    at processReferencedFiles (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:83904:16)
    at findSourceFile (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:83872:21)
    at args (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:83736:85)
    at getSourceFileFromReferenceWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:83703:34)
    at processSourceFile (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:83736:13)
    at processRootFile (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:83576:13)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:82615:60
    at Object.forEach (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:206:30)
    at Object.createProgram (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:82615:16)
    at synchronizeHostData (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:111279:26)
    at Object.getProgram (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:111362:13)
    at InferredProject.Project.updateGraphWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:115417:53)
    at InferredProject.Project.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:115365:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:116398:25)
    at ProjectService.openClientFileWithNormalizedPath (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:117243:26)
    at ProjectService.applyChangesInOpenFiles (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:117305:30)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:117974:46)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:119480:88
    at IOSession.Session.executeWithRequestId (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:119471:28)
    at IOSession.Session.executeCommand (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:119480:33)
    at IOSession.Session.onMessage (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:119500:35)
    at Interface.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsserver.js:120754:27)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface.<anonymous> (readline.js:340:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:339:11)
    at Socket.ondata (readline.js:86:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
Info 6994 [16:39:13.823] response:
    {"seq":0,"type":"response","command":"applyChangedToOpenFiles","request_seq":1241,"success":false,"message":"Error processing request. Debug Failure. False expression: \r\nVerbose Debug Information: {\"fileName\":\"../../../../../../typings/@epic/Core.d.ts\",\"currentDirectory\":\"C:/EpicSource/8.6/App St1/HSWeb/Solutions/Fnd\",\"hostCurrentDirectory\":\"C:/EpicSource/8.6/App St1/HSWeb/Solutions/Fnd\",\"openKeys\":[]}\nScript info with non-dynamic relative file name can only be open script info\nError: Debug Failure. False expression: \r\nVerbose Debug Information: {\"fileName\":\"../../../../../../typings/@epic/Core.d.ts\",\"currentDirectory\":\"C:/EpicSource/8.6/App St1/HSWeb/Solutions/Fnd\",\"hostCurrentDirectory\":\"C:/EpicSource/8.6/App St1/HSWeb/Solutions/Fnd\",\"openKeys\":[]}\nScript info with non-dynamic relative file name can only be open script info\n    at ProjectService.getOrCreateScriptInfoWorker (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:117058:30)\n    at ProjectService.getOrCreateScriptInfoNotOpenedByClientForNormalizedPath (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:117043:29)\n    at ProjectService.getOrCreateScriptInfoNotOpenedByClient (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:116980:29)\n    at InferredProject.Project.getOrCreateScriptInfoAndAttachToProject (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:114963:54)\n    at InferredProject.Project.getScriptSnapshot (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:114983:39)\n    at HostCache.createEntry (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:110979:44)\n    at HostCache.getOrCreateEntryByPath (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:111002:58)\n    at getOrCreateSourceFileByPath (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:111312:66)\n    at Object.getOrCreateSourceFile [as getSourceFile] (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:111305:24)\n    at findSourceFile (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:83824:29)\n    at args (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:83736:85)\n    at getSourceFileFromReferenceWorker (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:83703:34)\n    at processSourceFile (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:83736:13)\n    at C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:83906:17\n    at Object.forEach (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:206:30)\n    at processReferencedFiles (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:83904:16)\n    at findSourceFile (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:83872:21)\n    at args (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:83736:85)\n    at getSourceFileFromReferenceWorker (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:83703:34)\n    at processSourceFile (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:83736:13)\n    at processRootFile (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:83576:13)\n    at C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:82615:60\n    at Object.forEach (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:206:30)\n    at Object.createProgram (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:82615:16)\n    at synchronizeHostData (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:111279:26)\n    at Object.getProgram (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:111362:13)\n    at InferredProject.Project.updateGraphWorker (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:115417:53)\n    at InferredProject.Project.updateGraph (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:115365:42)\n    at ProjectService.assignOrphanScriptInfoToInferredProject (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:116398:25)\n    at ProjectService.openClientFileWithNormalizedPath (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:117243:26)\n    at ProjectService.applyChangesInOpenFiles (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:117305:30)\n    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:117974:46)\n    at C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:119480:88\n    at IOSession.Session.executeWithRequestId (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:119471:28)\n    at IOSession.Session.executeCommand (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:119480:33)\n    at IOSession.Session.onMessage (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:119500:35)\n    at Interface.<anonymous> (C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\tsserver.js:120754:27)\n    at emitOne (events.js:77:13)\n    at Interface.emit (events.js:169:7)\n    at Interface._onLine (readline.js:210:10)\n    at Interface.<anonymous> (readline.js:340:12)\n    at Array.forEach (native)\n    at Interface._normalWrite (readline.js:339:11)\n    at Socket.ondata (readline.js:86:10)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:146:16)\n    at Socket.Readable.push (_stream_readable.js:110:10)\n    at Pipe.onread (net.js:523:20)"}
Info 6995 [16:39:13.824] request:
    {"seq":1242,"command":"syntacticDiagnosticsSync","arguments":{"file":"C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\3.0\\lib.es2015.promise.d.ts","includeLinePosition":true}}
Info 6996 [16:39:13.824] Starting updateGraphWorker: Project: C:/EpicSource/8.6/App St1/HSWeb/HyperspaceWeb/Shell/Scripts/tsconfig.json
Info 6997 [16:39:13.824] Finishing updateGraphWorker: Project: C:/EpicSource/8.6/App St1/HSWeb/HyperspaceWeb/Shell/Scripts/tsconfig.json Version: 1 structureChanged: false Elapsed: 0ms
Perf 6998 [16:39:13.824] 1242::syntacticDiagnosticsSync: elapsed time (in milliseconds) 0.2131
Info 6999 [16:39:13.824] response:
    {"seq":0,"type":"response","command":"syntacticDiagnosticsSync","request_seq":1242,"success":true,"body":[]}
Perf 7000 [16:39:15.319] GC::before 250836976, after 250359436
Info 7001 [16:39:15.319] Running: *ensureProjectForOpenFiles*
Info 7002 [16:39:15.320] Structure before ensureProjectForOpenFiles:
Info 7003 [16:39:15.320] Project 'C:/EpicSource/8.6/App St1/HSWeb/HyperspaceWeb/Shell/Scripts/tsconfig.json' (Configured) 0
Info 7003 [16:39:15.320] 	Files (57)

**Comment by sheetalkamat** [comment]
@InduPrakash Can you share complete tsserver log for us to be able to investigate this further. Thanks.  I think the issue is that the file you have opened has triple slash relative reference ? But as far as I can see the referenced files are normalized so this should not happen so I would like to get more info. Also are you able to the issue by using typescript@next?

**Comment by mjbvz** [comment]
Also seems reported here: https://github.com/Microsoft/vscode/issues/62702

```
  Debug Failure. False expression.

    Error: Debug Failure. False expression.
    at ProjectService.getOrCreateScriptInfoWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120623:30)
    at ProjectService.getOrCreateScriptInfoOpenedByClientForNormalizedPath (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120587:29)
    at ProjectService.openClientFileWithNormalizedPath (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120786:33)
    at IOSession.Session.openClientFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122426:37)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121613:31)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123077:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123086:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123106:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

Linked issue includes full logs

**Comment by sheetalkamat** [comment]
@mjbvz  Microsoft/vscode#62702  is completely different. The issue here is that vscode already has file open with `c:/Main/Source/server/src/Session.ts` and then its opening file since it was listed in definitions: `c:/Main/Source/server/src/session.ts`

**Comment by InduPrakash** [comment]
The log lines prior to the exception indicating the source file are:

Info 39573[6:37:26.769] request:
    {"seq":7114,"command":"applyChangedToOpenFiles","arguments":{"openFiles":[{"fileName":"^ScriptDocument561 TurboGridDemo.ts","scriptKind":3,"content":"/**\r\n * @copyright Copyright 2014-2018 Epic Systems Corpo
Info 39574[6:37:26.778] Search path: 
Info 39575[6:37:26.786] ConfigFilePresence:: Current Watches: :: File: tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: ^ScriptDocument561 TurboGridDemo.ts Status: File added 
Info 39576[6:37:26.787] ConfigFilePresence:: Current Watches: :: File: jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: ^ScriptDocument561 TurboGridDemo.ts Status: File added 
Info 39577[6:37:26.787] For info: ^ScriptDocument561 TurboGridDemo.ts :: No config files found.
Info 39578[6:37:26.811] ConfigFilePresence:: Current Watches: :: File: tsconfig.json Currently impacted open files: RootsOfInferredProjects: ^ScriptDocument561 TurboGridDemo.ts OtherOpenFiles:  Status: Open file w
Info 39579[6:37:26.811] FileWatcher:: Added:: WatchInfo: tsconfig.json 2000 Project:  WatchType: Config file for the inferred project root
Info 39580[6:37:26.812] ConfigFilePresence:: Current Watches: Config file for the inferred project root:: File: tsconfig.json Currently impacted open files: RootsOfInferredProjects: ^ScriptDocument561 TurboGridDem
Info 39581[6:37:26.813] ConfigFilePresence:: Current Watches: :: File: jsconfig.json Currently impacted open files: RootsOfInferredProjects: ^ScriptDocument561 TurboGridDemo.ts OtherOpenFiles:  Status: Open file w
Info 39582[6:37:26.813] FileWatcher:: Added:: WatchInfo: jsconfig.json 2000 Project:  WatchType: Config file for the inferred project root
Info 39583[6:37:26.813] ConfigFilePresence:: Current Watches: Config file for the inferred project root:: File: jsconfig.json Currently impacted open files: RootsOfInferredProjects: ^ScriptDocument561 TurboGridDem
Info 39584[6:37:26.813] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Err 39585 [6:37:26.892] Exception on executing command {"seq":7114,"command":"applyChangedToOpenFiles","arguments":{"openFiles":[{"fileName":"^ScriptDocument561 TurboGridDemo.ts","scriptKind":3,"content":"/**\r\n 

    Debug Failure. False expression: 
Verbose Debug Information: {"fileName":"../../../../../../typings/@epic/Core.d.ts","currentDirectory":"C:/Windows/system32","hostCurrentDirectory":"C:/Windows/system32","openKeys":[]}
Script info with non-dynamic relative file name can only be open script info


And that file has 2 reference elements:
/// <reference path="../../../../../../typings/@epic/Core.d.ts" />
/// <reference path="../../../../../../typings/@epic/Shell.d.ts" />

**Comment by sheetalkamat** [comment]
@InduPrakash Thank you for the repro. Will look into this.
