### ISSUE TITLE
RangeError: Maximum call stack size exceeded in `LineNode.walk`

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#20477]
tsserver version: starts with 2.7.0

Hits: 1283

stack:
```
RangeError: Maximum call stack size exceeded
    at fresh (/usr/local/lib/node_modules/typescript/lib/tsserver.js:86924:32)
    at EditWalker.pre (/usr/local/lib/node_modules/typescript/lib/tsserver.js:86945:37)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87304:29)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
    at LineNode.execWalk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87307:47)
    at LineNode.walk (/usr/local/lib/node_modules/typescript/lib/tsserver.js:87334:30)
```

**Comment by RyanCavanaugh** [comment]
Going to need a repro for this one, or a very long day of staring at the code figuring out how this happened

**Comment by mhegazy** [comment]
@aozgaa can we increase the stack depth in the error reports?
