### ISSUE TITLE
TypeScript compiler failed with exit code 1

### ISSUE THREAD

**Issue by narayansikarwar** [Microsoft/TypeScript#20490]
Hi can you please explain about the following error.

C:\MyProjects\demoNativescript\node_modules\typescript\lib\tsc.js:1755
            basePaths: getBasePaths(path
                                    ^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by andy-ms** [comment]
You're getting an error because your installed `tsc.js` isn't syntactically valid JavaScript -- does the file just end there? Could you try reinstalling?
