### ISSUE TITLE
Assert in getCodeActionForParameters when typing incomplete function call

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#20523]
Code (noImplicitAny on):
```ts
function f(x) { }
f(
```

Stack:
```ts
     Error: Debug Failure. False expression.
      at Object.zipWith (src\compiler\core.ts:218:15)
      at getCodeActionForParameters (src\services\codefixes\inferFromUsage.ts:130:47)
      at Object.getActionsForAddExplicitTypeAnnotation [as getCodeActions] (src\services\codefixes\inferFromUsage.ts:67:24)
      at src\services\codeFixProvider.ts:40:35
      at Object.forEach (src\compiler\core.ts:174:32)
      at Object.getFixes (src\services\codeFixProvider.ts:39:13)
      at src\services\services.ts:1893:32
      at Object.flatMap (src\compiler\core.ts:463:27)
      at Object.getCodeFixesAtPosition (src\services\services.ts:1891:20)
      at Object.proxy.(anonymous function) [as getCodeFixesAtPosition] (src\harness\fourslash.ts:397:66)
      at src\harness\fourslash.ts:2499:45
      at Object.flatMap (src\compiler\core.ts:463:27)
      at TestState.getCodeFixActions (src\harness\fourslash.ts:2494:23)
      at TestState.verifyCodeFix (src\harness\fourslash.ts:2448:34)
      at VerifyNegatable.codeFix (src\harness\fourslash.ts:3906:24)
      at eval (eval at runCode (src\harness\fourslash.ts:3231:23), <anonymous>:7:8)
      at runCode (src\harness\fourslash.ts:3232:13)
      at runFourSlashTestContent (src\harness\fourslash.ts:3214:9)
      at Object.runFourSlashTest (src\harness\fourslash.ts:3199:9)
```

**Comment by RyanCavanaugh** [comment]
Fix available
