### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined in `Object.find` during `Object.getCompletionEntryDetails`

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#20563]
tsserver version: 2.6.1
hits: at least 151188 in the past week
stack:
```
TypeError: Cannot read property 'length' of undefined
    at Object.find (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:1375:34)
    at getSymbolCompletionFromEntryId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:65272:29)
    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:65280:36)
    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:79782:35)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86221:64
    at Object.mapDefined (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:1610:30)
    at IOSession.Session.getCompletionEntryDetails (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86219:27)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85317:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86660:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86669:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86689:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by aozgaa** [comment]
Another stack with possible the same issue (1685 hitting sessions):
```
TypeError: Cannot read property 'length' of undefined
    at Object.find (tsserver.js:1375:34)
    at recordUsagebySymbol (tsserver.js:78664:41)
    at recordUsage (tsserver.js:78633:36)
    at collectUsages (tsserver.js:78626:25)
    at visitNodes (tsserver.js:12073:30)
    at Object.forEachChild (tsserver.js:12191:21)
    at collectUsages (tsserver.js:78629:28)
    at visitNode (tsserver.js:12064:24)
    at Object.forEachChild (tsserver.js:12276:24)
    at collectUsages (tsserver.js:78629:28)
    at visitNodes (tsserver.js:12073:30)
    at Object.forEachChild (tsserver.js:12236:24)
    at collectUsages (tsserver.js:78629:28)
    at visitNode (tsserver.js:12064:24)
    at Object.forEachChild (tsserver.js:12143:21)
    at collectUsages (tsserver.js:78629:28)
    at visitNode (tsserver.js:12064:24)
    at Object.forEachChild (tsserver.js:12115:21)
    at collectUsages (tsserver.js:78629:28)
    at visitNodes (tsserver.js:12073:30)
    at Object.forEachChild (tsserver.js:12180:24)
    at collectUsages (tsserver.js:78629:28)
    at visitNode (tsserver.js:12064:24)
    at Object.forEachChild (tsserver.js:12115:21)
    at collectUsages (tsserver.js:78629:28)
    at visitNodes (tsserver.js:12073:30)
    at Object.forEachChild (tsserver.js:12180:24)
    at collectUsages (tsserver.js:78629:28)
    at visitNodes (tsserver.js:12073:30)
    at Object.forEachChild (tsserver.js:12191:21)
    at collectUsages (tsserver.js:78629:28)
    at visitNode (tsserver.js:12064:24)
    at Object.forEachChild (tsserver.js:12115:21)
    at collectUsages (tsserver.js:78629:28)
    at visitNodes (tsserver.js:12073:30)
    at Object.forEachChild (tsserver.js:12245:24)
    at collectUsages (tsserver.js:78629:28)
    at visitNode (tsserver.js:12064:24)
    at Object.forEachChild (tsserver.js:12243:21)
    at collectUsages (tsserver.js:78629:28)
    at visitNodes (tsserver.js:12073:30)
    at Object.forEachChild (tsserver.js:12236:24)
    at collectUsages (tsserver.js:78629:28)
    at collectReadsAndWrites (tsserver.js:78502:17)
    at getPossibleExtractionsWorker (tsserver.js:77924:38)
    at getPossibleExtractions (tsserver.js:77881:26)
    at Object.getAvailableActions (tsserver.js:77514:35)
    at tsserver.js:75017:128
    at Object.flatMapIter (tsserver.js:1570:23)
    at Object.getApplicableRefactors (tsserver.js:75016:23)
    at Object.getApplicableRefactors (tsserver.js:80232:32)
    at IOSession.Session.getApplicableRefactors (tsserver.js:86474:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:85436:61)
    at tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (tsserver.js:86660:28)
    at IOSession.Session.executeCommand (tsserver.js:86669:33)
    at IOSession.Session.onMessage (tsserver.js:86689:35)
    at Interface.<anonymous> (tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment]
The `Source: Telemetry` have limited information. we only have the call stack from the crash report. We need to either mitigate the crash, or add additional asserts to get more information in future crash reports.
