### ISSUE TITLE
Debug Failure. False expression: `JsxText` tokens should not be the first child of `JsxElement | JsxSelfClosingElement` in `findRightmostChildNodeWithTokens`  during `getQuickInfoAtPosition`

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#20788]
tsserver version: 2.6.1
hitting sessions: 6483
stack:
```
Error: Debug Failure. False expression: `JsxText` tokens should not be the first child of `JsxElement | JsxSelfClosingElement`
    at findRightmostChildNodeWithTokens (tsserver.js:62901:30)
    at find (tsserver.js:62893:33)
    at findPrecedingToken (tsserver.js:62859:22)
    at getTokenAtPositionWorker (tsserver.js:62822:41)
    at getTouchingToken (tsserver.js:62794:16)
    at Object.getTouchingPropertyName (tsserver.js:62790:16)
    at Object.getQuickInfoAtPosition (tsserver.js:79791:27)
    at IOSession.Session.getQuickInfoWorker (tsserver.js:86102:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:85266:61)
    at tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (tsserver.js:86660:28)
    at IOSession.Session.executeCommand (tsserver.js:86669:33)
    at IOSession.Session.onMessage (tsserver.js:86689:35)
    at Interface.<anonymous> (tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment]
The `Source: Telemetry` have limited information. we only have the call stack from the crash report. We need to either mitigate the crash, or add additional asserts to get more information in future crash reports.

**Comment by andy-ms** [comment]
The assertion was added in #16385. Since then we've added JSX fragment syntax (#19249), so that might have to do with the error. The first child of some node is a `JSXText` with `containsOnlyWhiteSpaces` set --
 the error message assumes its parent is `JsxElement | JsxSelfClosingElement` but it may be a `JsxFragment`.

@uniqueiniquity Do you think this might have been fixed by #20912?

If it helps, I wrote this helper method in `fourslash.ts` to look for errors:
```ts
public verifyPreceding() {
    for (const fileName of this.getProgram().getRootFileNames()) {
        const file = this.getProgram().getSourceFile(fileName);
        for (let i = 0; i < file.text.length; i++) {
            ts.findPrecedingToken(i, file);
        }
    };
}
```

**Comment by uniqueiniquity** [comment]
@andy-ms I doubt #20912 would have fixed this since it was just related to behavior on format.

**Comment by uniqueiniquity** [comment]
I am looking into this further.

**Comment by uniqueiniquity** [comment]
@andy-ms your helper function will not behave the same as the case in the stack trace; the caller of `findPrecedingToken` provides a third argument.

**Comment by uniqueiniquity** [comment]
Worked on this with @RyanCavanaugh and could not find a case that would locally repro. 
Might be worth adding additional asserts as @mhegazy suggests.

**Comment by andy-ms** [comment]
Maybe add the assert in the parser -- on finishing a jsx node, assert that the first child is not whitespace-only?

**Comment by mhegazy** [comment]
Asserts in the parser would be bad. if they fail nothing will work in the program. at least with this assert, *some* operations work.

**Comment by andy-ms** [comment]
@mhegazy Can we have informational-only asserts? We don't necessarily need to throw an exception, just report in telemetry that there was an error.

**Comment by mhegazy** [comment]
but we have no way of getting the info really.. we log the failures, but the info can go to the log, and we have no way on getting that afterwards.

**Comment by uniqueiniquity** [comment]
We've been unable to generate a repro of this, so adding "Needs More Info".
