### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined in `getCompletionEntryDisplayNameForSymbol` during `getCompletionEntryDetails`

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#20787]
tsserver version: 2.6.1
hits: 14161
stack
```
TypeError: Cannot read property 'name' of undefined
    at getCompletionEntryDisplayNameForSymbol (tsserver.js:66233:30)
    at tsserver.js:65273:24
    at Object.find (tsserver.js:1377:17)
    at getSymbolCompletionFromEntryId (tsserver.js:65272:29)
    at Object.getCompletionEntryDetails (tsserver.js:65280:36)
    at Object.getCompletionEntryDetails (tsserver.js:79782:35)
    at tsserver.js:86221:64
    at Object.mapDefined (tsserver.js:1610:30)
    at IOSession.Session.getCompletionEntryDetails (tsserver.js:86219:27)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:85317:61)
    at tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (tsserver.js:86660:28)
    at IOSession.Session.executeCommand (tsserver.js:86669:33)
    at IOSession.Session.onMessage (tsserver.js:86689:35)
    at Interface.<anonymous> (tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment]
The `Source: Telemetry` have limited information. we only have the call stack from the crash report. We need to either mitigate the crash, or add additional asserts to get more information in future crash reports.
