### ISSUE TITLE
TypeError: Cannot read property 'globalExports' of undefined in `getImportersForExport` during `getOccurrences`

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#20793]
tsserver version: 2.6.1
hitting sessions: 4399
stack:
```
TypeError: Cannot read property 'globalExports' of undefined
    at getImportersForExport tsserver.js:66964:67)
    at State.importTracker tsserver.js:66943:26)
    at State.getImportSearches tsserver.js:67788:33)
    at searchForImportsOfExport tsserver.js:67824:32)
    at getReferencedSymbolsForSymbol tsserver.js:67742:21)
    at Object.getReferencedSymbolsForNode tsserver.js:67664:24)
    at Object.getReferenceEntriesForNode tsserver.js:67502:58)
    at getSemanticDocumentHighlights tsserver.js:66388:57)
    at Object.getDocumentHighlights tsserver.js:66377:20)
    at getDocumentHighlights tsserver.js:79870:42)
    at getOccurrencesAtPositionCore tsserver.js:79873:46)
    at Object.getOccurrencesAtPosition tsserver.js:79859:27)
    at IOSession.Session.getOccurrences tsserver.js:85781:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) tsserver.js:85403:61)
    at tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId tsserver.js:86660:28)
    at IOSession.Session.executeCommand tsserver.js:86669:33)
    at IOSession.Session.onMessage tsserver.js:86689:35)
    at Interface.<anonymous> tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by andy-ms** [comment]
We'll have to see if #21340 gives us a better repro for this.
