### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined in `unescapeLeadingUnderscores` during `getCompletions`

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#20792]
tsserver version: 2.6.1
hitting sessions: 4639
stack:
```
TypeError: Cannot read property 'length' of undefined
    at unescapeLeadingUnderscores (tsserver.js:9007:18)
    at Object.idText (tsserver.js:9011:16)
    at IdentifierObject.get [as text] (tsserver.js:79132:27)
    at tryGetGlobalSymbols (tsserver.js:65594:126)
    at getCompletionData (tsserver.js:65478:22)
    at Object.getCompletionsAtPosition (tsserver.js:65060:34)
    at Object.getCompletionsAtPosition (tsserver.js:79777:35)
    at IOSession.Session.getCompletions (tsserver.js:86199:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:85311:61)
    at tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (tsserver.js:86660:28)
    at IOSession.Session.executeCommand (tsserver.js:86669:33)
    at IOSession.Session.onMessage (tsserver.js:86689:35)
    at Interface.<anonymous> (tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

```

**Comment by mhegazy** [comment]
The `Source: Telemetry` have limited information. we only have the call stack from the crash report. We need to either mitigate the crash, or add additional asserts to get more information in future crash reports.
