### ISSUE TITLE
TypeError: Cannot read property 'flags' of undefined in `getActionsForAddMissingMember` during `getCodeFixesAtPosition`

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#20791]
tsserver version:
hits: 4938
stack:
```
TypeError: Cannot read property 'flags' of undefined
    at Object.getActionsForAddMissingMember [as getCodeActions] (tsserver.js:75172:31)
    at tsserver.js:74988:33
    at Object.forEach (tsserver.js:1312:30)
    at Object.getFixes (tsserver.js:74987:16)
    at tsserver.js:80109:35
    at Object.flatMap (tsserver.js:1550:25)
    at Object.getCodeFixesAtPosition (tsserver.js:80107:23)
    at IOSession.Session.getCodeFixes (tsserver.js:86515:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:85423:61)
    at tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (tsserver.js:86660:28)
    at IOSession.Session.executeCommand (tsserver.js:86669:33)
    at IOSession.Session.onMessage (tsserver.js:86689:35)
    at Interface.<anonymous> (tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment]
The `Source: Telemetry` have limited information. we only have the call stack from the crash report. We need to either mitigate the crash, or add additional asserts to get more information in future crash reports.

**Comment by mhegazy** [comment]
code has changed since this issue was reported making the issue outdated. closing as won't fix for now.
