### ISSUE TITLE
RangeError: Maximum call stack size exceeded in `isAccessible`

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#20808]
tsserver version: 2.6.1
hitting sessions: 1062
stack:
```
RangeError: Maximum call stack size exceeded
    at Map.get (native)
    at tsserver.js:21889:57
    at forEachSymbolTableInScope (tsserver.js:21817:34)
    at needsQualification (tsserver.js:21888:13)
    at canQualifySymbol (tsserver.js:21853:25)
    at isAccessible (tsserver.js:21859:21)
    at tsserver.js:21875:29
    at Object.forEachEntry (tsserver.js:2044:26)
    at trySymbolTable (tsserver.js:21868:27)
    at getAccessibleSymbolChainFromSymbolTable (tsserver.js:21848:30)
    at forEachSymbolTableInScope (tsserver.js:21833:20)
    at getAccessibleSymbolChain (tsserver.js:21843:20)
    at canQualifySymbol (tsserver.js:21854:23)
    at isAccessible (tsserver.js:21859:21)
    at tsserver.js:21875:29
    at Object.forEachEntry (tsserver.js:2044:26)
    at trySymbolTable (tsserver.js:21868:27)
    at getAccessibleSymbolChainFromSymbolTable (tsserver.js:21848:30)
    at forEachSymbolTableInScope (tsserver.js:21833:20)
    at getAccessibleSymbolChain (tsserver.js:21843:20)
    at canQualifySymbol (tsserver.js:21854:23)
    at isAccessible (tsserver.js:21859:21)
    at tsserver.js:21875:29
    at Object.forEachEntry (tsserver.js:2044:26)
    at trySymbolTable (tsserver.js:21868:27)
    at getAccessibleSymbolChainFromSymbolTable (tsserver.js:21848:30)
    at forEachSymbolTableInScope (tsserver.js:21833:20)
    at getAccessibleSymbolChain (tsserver.js:21843:20)
    at canQualifySymbol (tsserver.js:21854:23)
    at isAccessible (tsserver.js:21859:21)
    at tsserver.js:21875:29
    at Object.forEachEntry (tsserver.js:2044:26)
    at trySymbolTable (tsserver.js:21868:27)
    at getAccessibleSymbolChainFromSymbolTable (tsserver.js:21848:30)
    at forEachSymbolTableInScope (tsserver.js:21833:20)
    at getAccessibleSymbolChain (tsserver.js:21843:20)
    at canQualifySymbol (tsserver.js:21854:23)
    at isAccessible (tsserver.js:21859:21)
    at tsserver.js:21875:29
    at Object.forEachEntry (tsserver.js:2044:26)
    at trySymbolTable (tsserver.js:21868:27)
    at getAccessibleSymbolChainFromSymbolTable (tsserver.js:21848:30)
    at forEachSymbolTableInScope (tsserver.js:21833:20)
    at getAccessibleSymbolChain (tsserver.js:21843:20)
    at canQualifySymbol (tsserver.js:21854:23)
    at isAccessible (tsserver.js:21859:21)
    at tsserver.js:21875:29
    at Object.forEachEntry (tsserver.js:2044:26)
    at trySymbolTable (tsserver.js:21868:27)
    at getAccessibleSymbolChainFromSymbolTable (tsserver.js:21848:30)
    at forEachSymbolTableInScope (tsserver.js:21833:20)
    at getAccessibleSymbolChain (tsserver.js:21843:20)
    at canQualifySymbol (tsserver.js:21854:23)
    at isAccessible (tsserver.js:21859:21)
    at tsserver.js:21875:29
    at Object.forEachEntry (tsserver.js:2044:26)
    at trySymbolTable (tsserver.js:21868:27)
    at getAccessibleSymbolChainFromSymbolTable (tsserver.js:21848:30)
    at forEachSymbolTableInScope (tsserver.js:21833:20)
    at getAccessibleSymbolChain (tsserver.js:21843:20)
    at canQualifySymbol (tsserver.js:21854:23)
    at isAccessible (tsserver.js:21859:21)
    at tsserver.js:21875:29
    at Object.forEachEntry (tsserver.js:2044:26)
    at trySymbolTable (tsserver.js:21868:27)
    at getAccessibleSymbolChainFromSymbolTable (tsserver.js:21848:30)
    at forEachSymbolTableInScope (tsserver.js:21833:20)
    at getAccessibleSymbolChain (tsserver.js:21843:20)
    at canQualifySymbol (tsserver.js:21854:23)
    at isAccessible (tsserver.js:21859:21)
    at tsserver.js:21875:29
    at Object.forEachEntry (tsserver.js:2044:26)
    at trySymbolTable (tsserver.js:21868:27)
    at getAccessibleSymbolChainFromSymbolTable (tsserver.js:21848:30)
    at forEachSymbolTableInScope (tsserver.js:21833:20)
    at getAccessibleSymbolChain (tsserver.js:21843:20)
    at canQualifySymbol (tsserver.js:21854:23)
    at isAccessible (tsserver.js:21859:21)
    at tsserver.js:21875:29
    at Object.forEachEntry (tsserver.js:2044:26)
    at trySymbolTable (tsserver.js:21868:27)
    at getAccessibleSymbolChainFromSymbolTable (tsserver.js:21848:30)
    at forEachSymbolTableInScope (tsserver.js:21833:20)
    at getAccessibleSymbolChain (tsserver.js:21843:20)
    at canQualifySymbol (tsserver.js:21854:23)
    at isAccessible (tsserver.js:21859:21)
    at tsserver.js:21875:29
    at Object.forEachEntry (tsserver.js:2044:26)
    at trySymbolTable (tsserver.js:21868:27)
    at getAccessibleSymbolChainFromSymbolTable (tsserver.js:21848:30)
    at forEachSymbolTableInScope (tsserver.js:21833:20)
    at getAccessibleSymbolChain (tsserver.js:21843:20)
    at canQualifySymbol (tsserver.js:21854:23)
    at isAccessible (tsserver.js:21859:21)
    at tsserver.js:21875:29
    at Object.forEachEntry (tsserver.js:2044:26)
    at trySymbolTable (tsserver.js:21868:27)
    at getAccessibleSymbolChainFromSymbolTable (tsserver.js:21848:30)
    at forEachSymbolTableInScope (tsserver.js:21833:20)
    at getAccessibleSymbolChain (tsserver.js:21843:20)
```

**Comment by mhegazy** [comment]
The `Source: Telemetry` have limited information. we only have the call stack from the crash report. We need to either mitigate the crash, or add additional asserts to get more information in future crash reports.

**Comment by mhegazy** [comment]
Closing for now.
