### ISSUE TITLE
Error: Debug Failure. False expression. in `getDeclarationName` during `bindSourceFile`

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#20800]
tsserver version: 2.6.1
hitting sessions: 1933
stack:
```
Error: Debug Failure. False expression.
    at getDeclarationName (tsserver.js:17566:30)
    at declareSymbol (tsserver.js:17581:64)
    at declareSymbolAndAddToSymbolTable (tsserver.js:18545:28)
    at bindParameter (tsserver.js:19262:17)
    at bindWorker (tsserver.js:18936:28)
    at bind (tsserver.js:18815:13)
    at bindEach (tsserver.js:17762:21)
    at visitNodes (tsserver.js:12069:24)
    at Object.forEachChild (tsserver.js:12140:21)
    at bindEachChild (tsserver.js:17770:16)
    at bindChildrenWorker (tsserver.js:17859:21)
    at bindChildren (tsserver.js:17745:17)
    at bindContainer (tsserver.js:17698:17)
    at bind (tsserver.js:18824:21)
    at visitNode (tsserver.js:12064:24)
    at Object.forEachChild (tsserver.js:12115:21)
    at bindEachChild (tsserver.js:17770:16)
    at bindChildrenWorker (tsserver.js:17859:21)
    at bindChildren (tsserver.js:17745:17)
    at bind (tsserver.js:18821:21)
    at bindEach (tsserver.js:17762:21)
    at visitNodes (tsserver.js:12069:24)
    at Object.forEachChild (tsserver.js:12180:24)
    at bindEachChild (tsserver.js:17770:16)
    at bindChildrenWorker (tsserver.js:17859:21)
    at bindChildren (tsserver.js:17745:17)
    at bindContainer (tsserver.js:17727:17)
    at bind (tsserver.js:18824:21)
    at visitNode (tsserver.js:12064:24)
    at Object.forEachChild (tsserver.js:12115:21)
    at bindEachChild (tsserver.js:17770:16)
    at bindVariableDeclarationFlow (tsserver.js:18414:13)
    at bindChildrenWorker (tsserver.js:17847:21)
    at bindChildren (tsserver.js:17745:17)
    at bind (tsserver.js:18821:21)
    at bindEach (tsserver.js:17762:21)
    at visitNodes (tsserver.js:12069:24)
    at Object.forEachChild (tsserver.js:12245:24)
    at bindEachChild (tsserver.js:17770:16)
    at bindChildrenWorker (tsserver.js:17859:21)
    at bindChildren (tsserver.js:17745:17)
    at bind (tsserver.js:18821:21)
    at visitNode (tsserver.js:12064:24)
    at Object.forEachChild (tsserver.js:12243:21)
    at bindEachChild (tsserver.js:17770:16)
    at bindChildrenWorker (tsserver.js:17859:21)
    at bindChildren (tsserver.js:17745:17)
    at bind (tsserver.js:18821:21)
    at bindEach (tsserver.js:17762:21)
    at visitNodes (tsserver.js:12069:24)
    at Object.forEachChild (tsserver.js:12236:24)
    at bindEachChild (tsserver.js:17770:16)
    at bindChildrenWorker (tsserver.js:17859:21)
    at bindChildren (tsserver.js:17745:17)
    at bind (tsserver.js:18821:21)
    at visitNode (tsserver.js:12064:24)
    at Object.forEachChild (tsserver.js:12143:21)
    at bindEachChild (tsserver.js:17770:16)
    at bindChildrenWorker (tsserver.js:17859:21)
    at bindChildren (tsserver.js:17745:17)
    at bindContainer (tsserver.js:17698:17)
    at bind (tsserver.js:18824:21)
    at visitNode (tsserver.js:12064:24)
    at Object.forEachChild (tsserver.js:12199:24)
    at bindEachChild (tsserver.js:17770:16)
    at bindChildrenWorker (tsserver.js:17859:21)
    at bindChildren (tsserver.js:17745:17)
    at bind (tsserver.js:18821:21)
    at bindCallExpressionFlow (tsserver.js:18442:17)
    at bindChildrenWorker (tsserver.js:17850:21)
    at bindChildren (tsserver.js:17745:17)
    at bind (tsserver.js:18821:21)
    at visitNode (tsserver.js:12064:24)
    at Object.forEachChild (tsserver.js:12247:24)
    at bindEachChild (tsserver.js:17770:16)
    at bindChildrenWorker (tsserver.js:17859:21)
    at bindChildren (tsserver.js:17745:17)
    at bind (tsserver.js:18821:21)
    at bindEach (tsserver.js:17762:21)
    at visitNodes (tsserver.js:12069:24)
    at Object.forEachChild (tsserver.js:12238:24)
    at bindEachChild (tsserver.js:17770:16)
    at bindChildrenWorker (tsserver.js:17859:21)
    at bindChildren (tsserver.js:17745:17)
    at bindContainer (tsserver.js:17698:17)
    at bind (tsserver.js:18824:21)
    at bindSourceFile (tsserver.js:17462:17)
    at Object.bindSourceFile (tsserver.js:17417:9)
    at initializeTypeChecker (tsserver.js:38915:20)
    at Object.createTypeChecker (tsserver.js:20623:9)
    at Object.getTypeChecker (tsserver.js:59312:79)
    at synchronizeHostData (tsserver.js:79709:21)
    at Object.getProgram (tsserver.js:79742:13)
    at InferredProject.Project.updateGraphWorker (tsserver.js:83016:53)
    at InferredProject.Project.updateGraph (tsserver.js:82966:39)
    at InferredProject.Project.getLanguageService (tsserver.js:82702:26)
    at IOSession.Session.getQuickInfoWorker (tsserver.js:86102:41)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:85266:61)
    at tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (tsserver.js:86660:28)
```

**Comment by mhegazy** [comment]
The `Source: Telemetry` have limited information. we only have the call stack from the crash report. We need to either mitigate the crash, or add additional asserts to get more information in future crash reports.

**Comment by minestarks** [comment]
@weswigham I was looking through VS fault telemetry and was surprised to see we have a lot of hits for this assert still. Weird that we never got any bugs filed here - it means you're unlikely to hit it in VS Code. This is usually because VS tends to build a lot of large js-only projects, where VS Code looks at open files only, so not so much.

Anyway the parent kinds we see are:

FunctionExpression 
FunctionDeclaration
MethodDeclaration
FunctionType
ArrowFunction
MethodSignature
CallSignature
Constructor

These are in order of hit count, with FunctionExpression highest by far.

3 years later, any obvious cause stand out to you?

**Comment by DanielRosenwasser** [comment]
I think that it's gone. https://github.com/microsoft/TypeScript/issues/43531 is the closest thing I can find and it hasn't shown up in any of the 4.4 releases..
