### ISSUE TITLE
Error: length < 0 in `createTextSpan` during `getApplicableRefactors`

### ISSUE THREAD

**Issue by aozgaa** [microsoft/TypeScript#20809]
tsserver version: 2.6.1
Error: length < 0
    at createTextSpan (tsserver.js:8817:19)
    at Object.createTextSpanFromBounds (tsserver.js:8823:16)
    at getErrorSpanForNode (tsserver.js:6264:19)
    at createDiagnosticForNodeInSourceFile (tsserver.js:6195:20)
    at Object.createDiagnosticForNode (tsserver.js:6191:16)
    at checkNode (tsserver.js:77699:36)
    at getRangeToExtract (tsserver.js:77655:54)
    at Object.getAvailableActions (tsserver.js:77509:38)
    at tsserver.js:75017:128
    at Object.flatMapIter (tsserver.js:1570:23)
    at Object.getApplicableRefactors (tsserver.js:75016:23)
    at Object.getApplicableRefactors (tsserver.js:80232:32)
    at IOSession.Session.getApplicableRefactors (tsserver.js:86474:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:85436:61)
    at tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (tsserver.js:86660:28)
    at IOSession.Session.executeCommand (tsserver.js:86669:33)
    at IOSession.Session.onMessage (tsserver.js:86689:35)
    at Interface.<anonymous> (tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

**Comment by mhegazy** [comment]
The `Source: Telemetry` have limited information. we only have the call stack from the crash report. We need to either mitigate the crash, or add additional asserts to get more information in future crash reports.

**Comment by amcasey** [comment]
@aozgaa Can I assume this is from 2.6.1, like the others?

**Comment by amcasey** [comment]
```ts
        var pos = nodeIsMissing(errorNode)
            ? errorNode.pos
            : ts.skipTrivia(sourceFile.text, errorNode.pos);
        return ts.createTextSpanFromBounds(pos, errorNode.end);
```

It seems plausible that `skipTrivia` might advance past `errorNode.end`.

**Comment by amcasey** [comment]
This is the diagnostic we're trying to create:
```ts
            if (!isStatement(nodeToCheck) && !(isExpressionNode(nodeToCheck) && isExtractableExpression(nodeToCheck))) {
                return [createDiagnosticForNode(nodeToCheck, Messages.statementOrExpressionExpected)];
            }
```

**Comment by amcasey** [comment]
`nodeIsMissing` will only return true if `errorNode` is `undefined` (not the case, since we're accessing properties) or if `errorNode.pos === errorNode.end`.  Therefore, if we take that branch, length is guaranteed to be 0 (i.e. no assert).

**Comment by aozgaa** [comment]
Yes. All reported issues so far are from 2.6.1. I've updated the description to reflect this.

**Comment by amcasey** [comment]
Waiting for asserts to be hit (not yet shipped).

**Comment by amcasey** [comment]
We had a telemetry hit in VS Code 1.28.1 with TS 3.1.1:

```
Error processing request. Debug Failure. False expression: This failure could trigger https://github.com/Microsoft/TypeScript/issues/20809
Error: Debug Failure. False expression: This failure could trigger https://github.com/Microsoft/TypeScript/issues/20809
    at getErrorSpanForNode (tsserver.js:8839:22)
    at createDiagnosticForNodeInSourceFile (tsserver.js:8752:20)
    at Object.createDiagnosticForNode (tsserver.js:8743:16)
    at checkNode (tsserver.js:111533:36)
    at getRangeToExtract (tsserver.js:111452:53)
    at Object.getAvailableActions (tsserver.js:111260:38)
    at tsserver.js:106434:128
    at getIterator (tsserver.js:535:23)
    at Object.next (tsserver.js:530:35)
    at Object.arrayFrom (tsserver.js:1135:32)
    at Object.getApplicableRefactors (tsserver.js:106433:23)
    at Object.getApplicableRefactors (tsserver.js:115353:32)
    at IOSession.Session.getApplicableRefactors (tsserver.js:122853:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:121787:61)
    at tsserver.js:123061:88
    at IOSession.Session.executeWithRequestId (tsserver.js:123052:28)
    at IOSession.Session.executeCommand (tsserver.js:123061:33)
    at IOSession.Session.onMessage (tsserver.js:123081:35)
    at Interface.<anonymous> (tsserver.js:124344:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by RyanCavanaugh** [comment]
Closing in the absence of a concrete repro
