### ISSUE TITLE
Assigning enum value to class static member before it is declared crashes tsc

### ISSUE THREAD

**Issue by tomb-pss** [Microsoft/TypeScript#20925]
**TypeScript Version:**  2.6.2

**Code**

```ts
class Foo {
    public static bar = Bar.A;
}

export enum Bar {
    A
}
```

**Expected behavior:**
I should receive an appropriate error about the enum being used before its declaration.

**Actual behavior:**
tsc crashes with the following output:
```
tsc.js:58192
                throw e;
                ^

Error: Debug Failure. type must be class or interface
    at getBaseTypes (tsc.js:23024:30)
    at getSuperClass (tsc.js:31005:21)
    at isPropertyDeclaredInAncestorClass (tsc.js:30994:29)
    at checkPropertyNotUsedBeforeDeclaration (tsc.js:30969:21)
    at checkPropertyAccessExpressionOrQualifiedName (tsc.js:30942:13)
    at checkPropertyAccessExpression (tsc.js:30914:20)
    at checkExpressionWorker (tsc.js:33427:28)
    at checkExpression (tsc.js:33378:42)
    at checkExpressionCached (tsc.js:33290:38)
    at getTypeOfExpression (tsc.js:33363:28)
```

Additionally, if I replace the enum with just a similarly-structured object, I get a slightly different error:
```ts
const Bar = {
    A: 0
};
```

```
tsc.js:58192
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at getBaseTypes (tsc.js:23015:37)
    at getSuperClass (tsc.js:31005:21)
    at isPropertyDeclaredInAncestorClass (tsc.js:30994:29)
    at checkPropertyNotUsedBeforeDeclaration (tsc.js:30969:21)
    at checkPropertyAccessExpressionOrQualifiedName (tsc.js:30942:13)
    at checkPropertyAccessExpression (tsc.js:30914:20)
    at checkExpressionWorker (tsc.js:33427:28)
    at checkExpression (tsc.js:33378:42)
    at checkExpressionCached (tsc.js:33290:38)
    at getTypeOfExpression (tsc.js:33363:28)
```

**Comment by DanielRosenwasser** [comment]
Should be fixed in our nightlies, thanks!
