### ISSUE TITLE
VSCode dev build: Debug Failure. False expression: Script info with relative file name can only be open script info

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#21040]
**TypeScript Version:**  2.7.0-insiders-20171214 / 2.7.0-dev-20180105

**Repo**
1. Running a dev build of vscode using `./scripts/code.sh`
1. Open empty workspace.
1. Create single js file. Make a few edits in it

**Bug**
In [tsserver.log](https://github.com/Microsoft/TypeScript/files/1608001/tsserver.log):

```
Err 436   [13:50:24.365] Exception on executing command unknown:

    Debug Failure. False expression: Script info with relative file name can only be open script info

    Error: Debug Failure. False expression: Script info with relative file name can only be open script info
    at ProjectService.getOrCreateScriptInfoWorker (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:86632:30)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClientForNormalizedPath (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:86619:29)
    at ProjectService.getOrCreateScriptInfoNotOpenedByClient (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:86599:29)
    at InferredProject.Project.getOrCreateScriptInfoAndAttachToProject (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:84633:54)
    at InferredProject.Project.getScriptSnapshot (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:84653:39)
    at HostCache.createEntry (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:81443:44)
    at new HostCache (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:81434:22)
    at synchronizeHostData (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:81642:29)
    at Object.getProgram (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:81726:13)
    at InferredProject.Project.updateGraphWorker (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:85057:53)
    at InferredProject.Project.updateGraph (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:85020:43)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:85807:33
    at Timeout.ThrottledOperations.run [as _onTimeout] (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:83243:17)
    at ontimeout (timers.js:396:18)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

I believe this is caused by `.d.ts` file being somehow picked up from vscode's `typings`.
[ti-10883.log](https://github.com/Microsoft/TypeScript/files/1608010/ti-10883.log):

```
...
"node_modules/big-integer/BigInteger.d.ts
...
```

In the typings installer logs, you can see here that the typings picked up in the empty `san2` workspace are actually coming from vscode

Please let me know what other information would be helpful

**Comment by mjbvz** [comment]
Creating a jsconfig or tsconfig in the project seems to fix the issue.

Also repos when using a workspace version on typescript. Does not repo with typescript@2.6

**Comment by mhegazy** [comment]
@sheetalkamat can you take a look
