### ISSUE TITLE
What does this mean?: ERROR in : TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by maks187** [Microsoft/TypeScript#21063]
**TypeScript Version:**  2.4.2

**Code**

ERROR in : TypeError: Cannot read property 'text' of undefined
    at Object.collectExternalModuleInfo (C:\development\nodejs\node_modules\typescript\lib\typescript.js:15869:57)
    at transformSourceFile (C:\development\nodejs\node_modules\typescript\lib\typescript.js:60804:36)
    at C:\development\nodejs\node_modules\typescript\lib\typescript.js:2492:86
    at reduceLeft (C:\development\nodejs\node_modules\typescript\lib\typescript.js:2188:30)
    at C:\development\nodejs\node_modules\typescript\lib\typescript.js:2492:42
    at transformRoot (C:\development\nodejs\node_modules\typescript\lib\typescript.js:63602:82)
    at Object.map (C:\development\nodejs\node_modules\typescript\lib\typescript.js:1696:29)
    at Object.transformNodes (C:\development\nodejs\node_modules\typescript\lib\typescript.js:63590:30)
    at Object.emitFiles (C:\development\nodejs\node_modules\typescript\lib\typescript.js:66273:28)
    at emitWorker (C:\development\nodejs\node_modules\typescript\lib\typescript.js:69725:33)
    at C:\development\nodejs\node_modules\typescript\lib\typescript.js:69687:66
    at runWithCancellationToken (C:\development\nodejs\node_modules\typescript\lib\typescript.js:69779:24)
    at Object.emit (C:\development\nodejs\node_modules\typescript\lib\typescript.js:69687:20)
    at sourceFiles.forEach (C:\development\nodejs\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:713:48)
    at Array.forEach (<anonymous>)
    at AngularCompilerPlugin._emit (C:\development\nodejs\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:710:33)

**Expected behavior:**

Should compile. 

**Actual behavior:**

Does not compile. 

**I'm only a user of Angular(5) which does use your compiler.
I've no deep knowledge of you compiler. This is the default case when someone do compile code in other languages like c++ or java. This error message explains nothing!
See it on my position, the default case.
What should I do, when I see such error message?
This is absolutely generic. What is if I am in some production state and see such message? Do I always have to report that? What is when there is no time to do that? Am I lost then? Think about it.. What would you do? :(**

**Comment by j-oliveras** [comment]
This is a bug into the typescript compiler.

**Comment by maks187** [comment]
Ok and what should I do now?
There is no more information about that error..
So I am lost then? ;)

**Comment by ajafff** [comment]
@maks187 I guess you have the wrong expectations. It seems like you never had a bug in your own code... This is not magically fixed immediately after opening the issue.

You could debug the compiler yourself to see what's causing the error. Or you can provide a minimal reproduction (that doesn't rely on the Angular compiler) and wait until the TypeScript devs can figure it out and fix it.

Note that you are using an older version of TypeScript that is no longer actively maintained. You should try to upgrade first. This is most likely already fixed in a newer version.

**Comment by maks187** [comment]
@ajafff I would never expect that the bug is fixed immediately. But how about to extend the error processing to help to work out that bug? For this bug I would have to ask in at least three different projects to possible get an answer (angular, webpack and typescript), because such generic error message is absolutely worth nothing. There were no changes in code, before that error appears.. And upgrading the whole typescript version could produce new errors. I'm only asking for the future ;)
@ajafff I would never expect that the bug is fixed immediately. But how about to extend the error processing to help to work out that bug? For this bug I would have to ask in at least three different projects to possible get an answer (angular, webpack and typescript), because such generic error message is absolutely worth nothing. There were no changes in code, before that error appears.. And upgrading the whole typescript version could produce new errors. I'm only asking for the future ;)

**Comment by maks187** [comment]
@ajafff I would never expect that the bug is fixed immediately. But how about to extend the error processing to help to work out that bug? For this bug I would have to ask in at least three different projects to possible get an answer (angular, webpack and typescript), because such generic error message is absolutely worth nothing. There were no changes in code, before that error appears.. And upgrading the whole typescript version could produce new errors. I'm only asking for the future ;)
