### ISSUE TITLE
Where to start? => Error: Debug Failure. False expression: Too many nodes written to output.

### ISSUE THREAD

**Issue by chadbr** [Microsoft/TypeScript#21098]
"typescript": "2.6.2" / Mac (latest OSX)

I was adding a new function to a class today and all the sudden I started getting the error `Error: Debug Failure. False expression: Too many nodes written to output.`

Some things I tried:
-backed out changes until the last known good state
-Upgraded all packages
-Rebooted the machine (you never know!)
-Commented random sections of code (there aren't many dependencies... )

Any advice on how to diagnose the issue? Maybe I need to strip everything and re-add until I get it again? Is there a cache I don't know about somewhere I should delete?

Several other projects still working fine so I don't think it's an environment issue (and I wasn't fiddling with anything like that today...)

**Expected behavior:**
I expect not to get this error :)

**Actual behavior:**
```
Chads-MacBook-Pro:kinetix-code-gen chadbr$ tsc -p tsconfig.json
/Users/chadbr/dev/vsts/kinetix-code-gen/node_modules/typescript/lib/tsc.js:58192
                throw e;
                ^

Error: Debug Failure. False expression: Too many nodes written to output.
    at extractSingleNode (/Users/chadbr/dev/vsts/kinetix-code-gen/node_modules/typescript/lib/tsc.js:42794:18)
    at Object.visitNode (/Users/chadbr/dev/vsts/kinetix-code-gen/node_modules/typescript/lib/tsc.js:42452:54)
    at transformCommonJSModule (/Users/chadbr/dev/vsts/kinetix-code-gen/node_modules/typescript/lib/tsc.js:50411:38)
    at transformSourceFile (/Users/chadbr/dev/vsts/kinetix-code-gen/node_modules/typescript/lib/tsc.js:50391:27)
    at /Users/chadbr/dev/vsts/kinetix-code-gen/node_modules/typescript/lib/tsc.js:1233:86
    at reduceLeft (/Users/chadbr/dev/vsts/kinetix-code-gen/node_modules/typescript/lib/tsc.js:938:30)
    at /Users/chadbr/dev/vsts/kinetix-code-gen/node_modules/typescript/lib/tsc.js:1233:42
    at transformRoot (/Users/chadbr/dev/vsts/kinetix-code-gen/node_modules/typescript/lib/tsc.js:52119:82)
    at Object.map (/Users/chadbr/dev/vsts/kinetix-code-gen/node_modules/typescript/lib/tsc.js:469:29)
    at Object.transformNodes (/Users/chadbr/dev/vsts/kinetix-code-gen/node_modules/typescript/lib/tsc.js:52108:30)
Chads-MacBook-Pro:kinetix-code-gen chadbr$

```

**Comment by mhegazy** [comment]
Can you share the sources causing the issue?

We only need the file where the emitter fails. you can do that by starting `tsc.js` under `node -inspect-brk` and connecting to it in chrome dev tools. when the exception occurs, look at `transformSourceFile` on the stack, the first parameter (`node`) should have a `fileName` property that tells you the name of the file it was emitting.  share that with us and your config options as well.

It is also helpful to try `typescript@next` and verify that it repros the issue.

**Comment by chadbr** [comment]
hah - this is just a silly one - I'm not sure if it's worth looking at more.

I have a code gen project that uses mustache -- one of the mustache files I had named .ts so I could get syntax highlighting in vscode. Something is better than nothing...

Well - that file is the one causing the compile to fail.

Unfortunately if I copy just that file to a new project -- I get a spew of error messages - not a failure.

I can spend more time looking if it's useful? I'll close this for now...


This is the file... not that is helps.
```

import { {{type.type.typePlural}}Logic } from './{{{typePluralKebabCase}}}.logic';
import { suite, test } from 'mocha-typescript';
import { assert, expect } from 'chai';
import { I{{type.type.type}}, TestUtils, {{type.type.type}}Models } from '@kinetix/kinetix-core';
import { {{type.type.type}}Logic } from './test-data.logic';

@suite('{{type.type.type}}Logic test')
export class {{type.type.type}}LogicTest {

  private {{{typePluralCamelCase}}}: I{{type.type.type}}[];
  private wellId: string;
  private rowId0: string;
  private rowId1: string;

  public constructor() {
    this.{{{typePluralCamelCase}}} = {{type.type.type}}Models.get{{type.type.type}}();
    this.wellId = this.{{{typePluralCamelCase}}}[0].wellId;
    this.rowId0 = this.{{{typePluralCamelCase}}}[0].testDataId;
    this.rowId1 = this.{{{typePluralCamelCase}}}[1].testDataId;
  }

  @test('testData should be undefined')
  public async testEmpty{{type.type.type}}(): Promise<void> {
    const logic = new {{type.type.type}}Logic();
    const result = await logic.get{{type.type.type}}('a', 'a');
    expect(undefined).to.equal(result);
  }

  @test('should post and get testData')
  public async testCreateAndGet{{type.type.type}}(): Promise<void> {
    const logic = new {{type.type.type}}Logic();
    await logic.post{{type.type.type}}('en-US', TestUtils.testUser, this.{{{typePluralCamelCase}}}[0]);
    let result = await logic.get{{type.type.type}}(this.wellId, this.rowId0);

    if (result) {
      expect(result.aBool).to.equal(this.{{{typePluralCamelCase}}}[0].aBool);
      expect(result.aDuration).to.equal(this.{{{typePluralCamelCase}}}[0].aDuration);
      expect(result.aNumberOneDecimal).to.equal(this.{{{typePluralCamelCase}}}[0].aNumberOneDecimal);
    } else {
      assert.fail('I/O failed');
    }

    await logic.post{{type.type.type}}('en-US', TestUtils.testUser, this.{{{typePluralCamelCase}}}[1]);
    result = await logic.get{{type.type.type}}(this.wellId, this.rowId1);
    if (result) {
      expect(result.aBool).to.equal(this.{{{typePluralCamelCase}}}[1].aBool);
      expect(result.aDuration).to.equal(this.{{{typePluralCamelCase}}}[1].aDuration);
      expect(result.aNumberOneDecimal).to.equal(this.{{{typePluralCamelCase}}}[1].aNumberOneDecimal);
    } else {
      assert.fail('I/O failed');
    }
  }

  @test('should delete testData')
  public async testDelete{{type.type.type}}(): Promise<void> {
    const logic = new {{type.type.type}}Logic();
    await logic.post{{type.type.type}}('en-US', TestUtils.testUser, this.{{{typePluralCamelCase}}}[0]);
    const result0 = await logic.get{{type.type.type}}(this.wellId, this.rowId0);
    if (result0) {
      expect(result0.aNumberOneDecimal).to.equal(this.{{{typePluralCamelCase}}}[0].aNumberOneDecimal);
    } else {
      assert.fail('I/O failed');
    }

    await logic.post{{type.type.type}}('en-US', TestUtils.testUser, this.{{{typePluralCamelCase}}}[1]);
    const result1 = await logic.get{{type.type.type}}(this.wellId, this.rowId1);
    if (result1) {
      expect(result1.aNumberOneDecimal).to.equal(this.{{{typePluralCamelCase}}}[1].aNumberOneDecimal);
    } else {
      assert.fail('I/O failed');
    }

    if (result0) {
      await logic.delete{{type.type.type}}(TestUtils.testUser, result0);
      const emptyResult0 = await logic.get{{type.type.type}}(this.wellId, this.rowId0);
      expect(emptyResult0).to.equal(undefined);
    }

    const logics = new {{type.type.typePlural}}Logic();
    let results = await logics.get{{type.type.typePlural}}(this.wellId);
    expect(results.length).to.equal(1);

    if (result1) {
      await logic.delete{{type.type.type}}(TestUtils.testUser, result1);
      const emptyResult1 = await logic.get{{type.type.type}}(this.wellId, this.rowId1);
      expect(emptyResult1).to.equal(undefined);
    }

    results = await logics.get{{type.type.typePlural}}(this.wellId);
    expect(results.length).to.equal(0);

  }

}


```
