### ISSUE TITLE
Cannot read property 243 of undefined

### ISSUE THREAD

**Issue by Skn0tt** [Microsoft/TypeScript#21173]
**TypeScript Version:**  2.7.0-dev.201xxxxx

Compiling throws error without providing a meaningful message.

**Code**
```ts
import WeeklySummary from './WeeklySummary';
export const WeeklySummary = WeeklySummary;
```

**Expected behavior:**
Show some kind of error description so I can fix my typo

**Actual behavior:**
```sh
/Users/skn0tt/.config/yarn/global/node_modules/typescript/lib/tsc.js:58192
                throw e;
                ^

TypeError: Cannot read property '243' of undefined
    at getDeclarationSpaces (/Users/skn0tt/.config/yarn/global/node_modules/typescript/lib/tsc.js:34317:52)
    at /Users/skn0tt/.config/yarn/global/node_modules/typescript/lib/tsc.js:34309:84
    at Object.forEach (/Users/skn0tt/.config/yarn/global/node_modules/typescript/lib/tsc.js:281:30)
    at getDeclarationSpaces (/Users/skn0tt/.config/yarn/global/node_modules/typescript/lib/tsc.js:34309:28)
    at checkExportsOnMergedDeclarations (/Users/skn0tt/.config/yarn/global/node_modules/typescript/lib/tsc.js:34261:41)
    at checkVariableLikeDeclaration (/Users/skn0tt/.config/yarn/global/node_modules/typescript/lib/tsc.js:35123:17)
    at checkVariableDeclaration (/Users/skn0tt/.config/yarn/global/node_modules/typescript/lib/tsc.js:35152:20)
    at checkSourceElement (/Users/skn0tt/.config/yarn/global/node_modules/typescript/lib/tsc.js:36741:28)
    at Object.forEach (/Users/skn0tt/.config/yarn/global/node_modules/typescript/lib/tsc.js:281:30)
    at checkVariableStatement (/Users/skn0tt/.config/yarn/global/node_modules/typescript/lib/tsc.js:35160:16)
```

**Related:**

**Comment by DanielRosenwasser** [comment]
What version of TypeScript are you seeing this in?

**Comment by Skn0tt** [comment]
It happens both on the newest one (2.16 I think) as well as on @next. Tried both.

**Comment by mhegazy** [comment]
Can you share the sources that caused the issue?

**Comment by Skn0tt** [comment]
See above. Pretty simple code, only problem is in line 2 with duplicate identifier.

**Comment by mhegazy** [comment]
not getting it locally..
```sh
c:\test\21173>type tsconfig.json
{
    "compilerOptions": {
        "target": "es5"
    }
}

c:\test\21173>type a.ts
import WeeklySummary from './WeeklySummary';
export const WeeklySummary = WeeklySummary;

c:\test\21173>tsc --v
Version 2.7.0-dev.20180116

c:\test\21173>tsc
a.ts(1,8): error TS2395: Individual declarations in merged declaration 'WeeklySummary' must be all exported or all local.
a.ts(1,8): error TS2440: Import declaration conflicts with local declaration of 'WeeklySummary'.
a.ts(2,14): error TS2395: Individual declarations in merged declaration 'WeeklySummary' must be all exported or all local.
a.ts(2,30): error TS2448: Block-scoped variable 'WeeklySummary' used before its declaration.
```

**Comment by cscleison** [comment]
it happened to me in 2.7.2
I was using the same name in same file:

```
import * as PropTypes from "prop-types";
interface PropTypes {}
```

**Comment by mhegazy** [comment]
@cscleison can you share a more detailed repro? i can note reproduce this locally with the sample you provided.
