### ISSUE TITLE
Formatter error if renaming receiver variable of destructuring rest

### ISSUE THREAD

**Issue by t-cst** [Microsoft/TypeScript#21265]
**TypeScript Version:** Version 2.7.0-dev.20180118

**Search Terms:** destructuring, rest, formatter

**Code**

```ts
// test.ts file
const values = { a: "1", b: "2", c: "3", d: "4" };
const { a: xa, b: xb, ...other: xother } = values;
```

**Expected behavior:**
`tsfmt --verify test.ts` should not fail.

it doesn't fail without renaming: `const { a: xa, b: xb, ...other } = values;`

**Actual behavior:**
Code works fine, see [Playground](https://www.typescriptlang.org/play/#src=const%20values%20%3D%20%7B%20a%3A%20%221%22%2C%20b%3A%20%222%22%2C%20c%3A%20%223%22%2C%20d%3A%20%224%22%20%7D%3B%0D%0A%0D%0Aconst%20%7B%20a%3A%20va%2C%20b%3A%20vb%2C%20...vother%20%7D%20%3D%20values%3B%0D%0A%0D%0Aconsole.log(va%2C%20vb%2C%20vother)%3B%0D%0A%0D%0Aconsole.log(%22----%22)%3B%0D%0A%0D%0Aconst%20%7B%20a%3A%20xa%2C%20b%3A%20xb%2C%20...other%3A%20xother%20%7D%20%3D%20values%3B%0D%0A%0D%0Aconsole.log(xa%2C%20xb%2C%20xother)%3B%0D%0A), but formatter fails. 
```
> tsfmt --verify
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (/home/user/dev/test-app/node_modules/typescript/lib/typescript.js:91047:34)
    at /home/user/dev/test-app/node_modules/typescript/lib/typescript.js:90994:21
    at visitNode (/home/user/dev/test-app/node_modules/typescript/lib/typescript.js:13425:24)
    at Object.forEachChild (/home/user/dev/test-app/node_modules/typescript/lib/typescript.js:13516:21)
    at processNode (/home/user/dev/test-app/node_modules/typescript/lib/typescript.js:90993:20)
    at processChildNode (/home/user/dev/test-app/node_modules/typescript/lib/typescript.js:91053:21)
    at processChildNodes (/home/user/dev/test-app/node_modules/typescript/lib/typescript.js:91094:48)
    at /home/user/dev/test-app/node_modules/typescript/lib/typescript.js:90996:21
    at visitNodes (/home/user/dev/test-app/node_modules/typescript/lib/typescript.js:13430:24)
    at Object.forEachChild (/home/user/dev/test-app/node_modules/typescript/lib/typescript.js:13579:24)

```

**Comment by andy-ms** [comment]
We shouldn't crash in the formatter, but first, that example ought to be a parse error. `...other: xother` isn't valid JS.

**Comment by t-cst** [comment]
I was not sure about that. I opened a [stackoverflow question](https://stackoverflow.com/questions/48318640/renaming-remaining-properties-variable-when-object-destructuring-in-typescript/48320103#48320103) about about it. Then It should not even compile, right?

**Comment by andy-ms** [comment]
Right. Keep in mind this isn't a TypeScript feature but a JavaScript feature, so if JS runtimes do not allow it we shouldn't either.

**Comment by t-cst** [comment]
Ok. Thanks for the clarification.
