### ISSUE TITLE
Assertion failure from requesting refactors on import keyword of non-existent modules

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#21514]
```ts
import * as florb from 'glorb';

florb.
```

Request a refactor on the `import` keyword.

```
[Error  - 12:26:32 PM] 'getApplicableRefactors' request failed with error.
Error processing request. Cannot read property 'resolvedFileName' of undefined
TypeError: Cannot read property 'resolvedFileName' of undefined
    at Object.getAvailableActions (C:\Users\Daniel\TypeScript\built\local\tsserver.js:97412:64)
    at C:\Users\Daniel\TypeScript\built\local\tsserver.js:92791:128
    at getIterator (C:\Users\Daniel\TypeScript\built\local\tsserver.js:1869:23)
    at Object.next (C:\Users\Daniel\TypeScript\built\local\tsserver.js:1864:35)
    at Object.arrayFrom (C:\Users\Daniel\TypeScript\built\local\tsserver.js:2509:32)
    at Object.getApplicableRefactors (C:\Users\Daniel\TypeScript\built\local\tsserver.js:92790:23)
    at Object.getApplicableRefactors (C:\Users\Daniel\TypeScript\built\local\tsserver.js:99206:32)
    at IOSession.Session.getApplicableRefactors (C:\Users\Daniel\TypeScript\built\local\tsserver.js:106565:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Users\Daniel\TypeScript\built\local\tsserver.js:105500:61)
    at C:\Users\Daniel\TypeScript\built\local\tsserver.js:106771:88
    at IOSession.Session.executeWithRequestId (C:\Users\Daniel\TypeScript\built\local\tsserver.js:106762:28)
    at IOSession.Session.executeCommand (C:\Users\Daniel\TypeScript\built\local\tsserver.js:106771:33)
    at IOSession.Session.onMessage (C:\Users\Daniel\TypeScript\built\local\tsserver.js:106791:35)
    at Interface.<anonymous> (C:\Users\Daniel\TypeScript\built\local\tsserver.js:108052:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by andy-ms** [comment]
I'm having trouble reproducing this -- could you try writing a fourslash test? What is the TypeScript version you're testing with?

**Comment by andy-ms** [comment]
Talked to @DanielRosenwasser and we can't reproduce this any more.
