### ISSUE TITLE
noUnusedLocals with allowJS and checkJS causes error

### ISSUE THREAD

**Issue by natedanner** [Microsoft/TypeScript#21533]
TypeScript Version: 2.7.1

Search Terms:
checkJS, unusedlocals, tsc.js:59841

Code

Run: tsc test.js --noUnusedLocals --checkJS --allowJS --noEmit
With 

```js 
class MyClass {

	doSomething() {
	};
}
```

Expected behavior:
No errors introduced

Actual behavior:
/usr/local/lib/node_modules/typescript/lib/tsc.js:59841
                throw e;
                ^

Error: Debug Failure.
    at checkUnusedClassMembers (/usr/local/lib/node_modules/typescript/lib/tsc.js:35757:38)
    at checkUnusedIdentifiers (/usr/local/lib/node_modules/typescript/lib/tsc.js:35643:29)
    at checkSourceFileWorker (/usr/local/lib/node_modules/typescript/lib/tsc.js:37913:21)
    at checkSourceFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:37891:13)
    at getDiagnosticsWorker (/usr/local/lib/node_modules/typescript/lib/tsc.js:37945:17)
    at Object.getDiagnostics (/usr/local/lib/node_modules/typescript/lib/tsc.js:37934:24)
    at /usr/local/lib/node_modules/typescript/lib/tsc.js:59858:85
    at runWithCancellationToken (/usr/local/lib/node_modules/typescript/lib/tsc.js:59834:24)
    at getSemanticDiagnosticsForFileNoCache (/usr/local/lib/node_modules/typescript/lib/tsc.js:59848:20)
    at getAndCacheDiagnostics (/usr/local/lib/node_modules/typescript/lib/tsc.js:60059:26)

Additional info: 
If I remove the semi-colon from the `doSomething` method or don't pass the `--noUnusedLocals` flag  the error does not appear. I don't get the error in either case on TypeScript version `2.6.2`. We are using allowJS/checkJS feature on our legacy JS at my shop and ran into this bug after `2.7.1` upgrade

**Comment by ajafff** [comment]
Fixed by #21343?

**Comment by natedanner** [comment]
Yep! Test with latest. Closing out.

**Comment by ajafff** [comment]
@sandersn might be a good candidate for backporting

**Comment by sandersn** [comment]
Good point @ajafff. It's too late for the official 2.7 release, but it could go into 2.7.2. What do you think, @mhegazy?

**Comment by mhegazy** [comment]
It is already ported. should be released with 2.7.2

**Comment by closca** [comment]
When will be 2.7.2 be released?

**Comment by mhegazy** [comment]
No specific ETA at the moment. but we plan it to go out sometime in the next two weeks.

**Comment by Spongman** [comment]
i think a new release containing _just_ this bug fix would have been a good move.

**Comment by mhegazy** [comment]
2.7.2 should be live now.

**Comment by sebsto** [comment]
I have the same problem with 2.8.1
```
$ tsc --version
Version 2.8.1
```

```
/usr/local/lib/node_modules/typescript/lib/tsc.js:61464
                throw e;
                ^

Error: Debug Failure. False expression: Target symbol and symbol do not have the same name
    at getLiteralTypeFromPropertyName (/usr/local/lib/node_modules/typescript/lib/tsc.js:26752:30)
    at eachPropertyRelatedTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:28844:36)
    at indexTypesRelatedTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:28893:36)
    at structuredTypeRelatedTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:28593:51)
    at recursiveTypeRelatedTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:28423:53)
    at isRelatedTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:28139:38)
    at checkTypeRelatedTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:27990:26)
    at checkTypeComparableTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:27717:20)
    at checkAssertionWorker (/usr/local/lib/node_modules/typescript/lib/tsc.js:34558:21)
    at checkAssertion (/usr/local/lib/node_modules/typescript/lib/tsc.js:34549:20)
```

**Comment by RyanCavanaugh** [comment]
@sebsto looks like a completely different call stack - can you open a new issue with repro steps? Thanks!

**Comment by sebsto** [comment]
I realized that after posting, new issue and steps to reproduce is here. https://github.com/Microsoft/TypeScript/issues/23461
