### ISSUE TITLE
Crash with `esModuleInterop`

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#21554]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 

**Code**
Compile `http-errors` from `dt` with `esModuleInterop`:
```
E:\Github\TypeScript\src\compiler\checker.ts:17606
                        synthType.syntheticType = (type.flags & TypeFlags.StructuredType && type.symbol.flags & (SymbolFlags.Module | SymbolFlags.Variable)) ? getSpreadType(type, defaultContainingObject, anonymousSymbol, /*propegatedFlags*/ 0) : defaultContainingObject;
                                                                                                        ^
TypeError: Cannot read property 'flags' of undefined
    at getTypeWithSyntheticDefaultImportType (E:\Github\TypeScript\src\compiler\checker.ts:17606:105)
    at resolveESModuleSymbol (E:\Github\TypeScript\src\compiler\checker.ts:2126:48)
    at getTargetOfNamespaceImport (E:\Github\TypeScript\src\compiler\checker.ts:1718:20)
    at getTargetOfAliasDeclaration (E:\Github\TypeScript\src\compiler\checker.ts:1831:28)
    at resolveAlias (E:\Github\TypeScript\src\compiler\checker.ts:1862:32)
    at checkAliasSymbol (E:\Github\TypeScript\src\compiler\checker.ts:23352:28)
    at checkImportBinding (E:\Github\TypeScript\src\compiler\checker.ts:23385:13)
    at checkImportDeclaration (E:\Github\TypeScript\src\compiler\checker.ts:23404:29)
    at checkSourceElement (E:\Github\TypeScript\src\compiler\checker.ts:23762:28)
    at Object.forEach (E:\Github\TypeScript\src\compiler\core.ts:179:32)
```

**Expected behavior:**
No crash.
**Actual behavior:**
Crash.

**Comment by weswigham** [comment]
Also in `uniqid`.
