### ISSUE TITLE
Exception from convertToImportCodeFixContext

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/TypeScript#21607]
**TypeScript Version:**  2.7.0-insiders.20180117
**VSCode Version:** 1.20.0-insider

Exception in `convertToImportCodeFixContext` when the TS extension runs `getCodeFixes`.

**Repro Steps:**

1. Open a new TS file with the following content:
  ```ts
  const x = y;
  ```
1. Ensure the Output Pane is open with the TypeScript extension output selected.
1. Select the contents of the entire file (e.g. Ctrl+A on Windows)
1. Comment the selected range (e.g. Ctrl+/ on Windows)

**Expected Behavior:**
No output to extension log.

**Actual Behavior:**
The following is output to the extension log:

```
Error: Debug Failure. Invalid cast. The supplied value did not pass the test 'isIdentifier'.
    at Object.cast (c:\dev\TypeScript\built\local\tsserver.js:2445:15)
    at convertToImportCodeFixContext (c:\dev\TypeScript\built\local\tsserver.js:78598:34)
    at Object.getImportCodeActions [as getCodeActions] (c:\dev\TypeScript\built\local\tsserver.js:79002:36)
    at c:\dev\TypeScript\built\local\tsserver.js:77474:33
    at Object.forEach (c:\dev\TypeScript\built\local\tsserver.js:1430:30)
    at Object.getFixes (c:\dev\TypeScript\built\local\tsserver.js:77473:16)
    at c:\dev\TypeScript\built\local\tsserver.js:83621:35
    at Object.flatMap (c:\dev\TypeScript\built\local\tsserver.js:1700:25)
    at Object.getCodeFixesAtPosition (c:\dev\TypeScript\built\local\tsserver.js:83619:23)
    at IOSession.Session.getCodeFixes (c:\dev\TypeScript\built\local\tsserver.js:90643:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\dev\TypeScript\built\local\tsserver.js:89547:61)
    at c:\dev\TypeScript\built\local\tsserver.js:90808:88
    at IOSession.Session.executeWithRequestId (c:\dev\TypeScript\built\local\tsserver.js:90799:28)
    at IOSession.Session.executeCommand (c:\dev\TypeScript\built\local\tsserver.js:90808:33)
    at IOSession.Session.onMessage (c:\dev\TypeScript\built\local\tsserver.js:90828:35)
    at Interface.<anonymous> (c:\dev\TypeScript\built\local\tsserver.js:92029:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by andy-ms** [comment]
Reminds me of #21499. Now that #21539 is in, I see: `Debug Failure. Invalid cast. The supplied EndOfFileToken did not pass the test 'isIdentifier'.`.
I think this may be a vscode bug. It shouldn't be calling `getCodeFixes` on a file that's commented-out and thus has no errors. It may be failing to refresh the error list when inserting comments. @mjbvz

**Comment by mjbvz** [comment]
@andy-ms I believe we make the call because after the edit the new errors are returned async. Here's the order things happen in:

1. Comment code
1. We update document and send a `change` message to TSServer
1. We still have the old error around so we request `codeActions`. This request fails
1. Immediately after (or before) the previous step, we  request the new diagnostics for the file 

Not sure what the fix would be on our side. Perhaps adding a debounce. How painful is handling this on the TS side?

**Comment by andy-ms** [comment]
Looks fixed in master. There are likely similar bugs though. @mjbvz Could you look into not requesting codefixes if the errors are invalid (meaning, there has been a text change since the errors last came in)?
