### ISSUE TITLE
tsc -w does not correctly compile file imports

### ISSUE THREAD

**Issue by phillipb** [Microsoft/TypeScript#21612]
When running `tsc -w`, the compiler is incorrectly removing certain module imports. It would appear this bug happens when the imported module's only usage is in a `promise`. If used outside of the promise, the compiler does import the file correctly.  This only happens when running the compiler in watch mode.

**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 
tsc tsc-w import missing promise

**Code**

```ts
import * as MyService from '../service/MyService';
export function find() {
  return new Promise((resolve, reject) => {
        MyService.find()  
  })
}
```

**Expected tsc output:**
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const MyService = require("../service/MyService");
function find() {
    return new Promise((resolve, reject) => {
            MyService.findNext();
    });
}
exports.find = find;
```

**Actual tsc output:**
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
function find() {
    return new Promise((resolve, reject) => {
            MyService.findNext();
    });
}
exports.find = find;
```

**Playground Link:** Cant really replicate here because I can't import from disk

**Related Issues:** none that I've found

**Comment by unional** [comment]
Also encountered this.

First pass it is compiled correctly.
Second pass have some import missing.

This is the source file: https://github.com/unional/komondor/blob/ts-2.7-compile-error/src/spec.ts

In first pass, line 45-52:
```ts
Object.defineProperty(exports, "__esModule", { value: true });
var assertron_1 = require("assertron");
var tersify_1 = require("tersify");
var unpartial_1 = require("unpartial");
var io_1 = require("./io");
var SpecOptions_1 = require("./SpecOptions");
var specStore_1 = require("./specStore");
var plugin_1 = require("./plugin");
```

Second pass (after making some change elsewhere):
```ts
Object.defineProperty(exports, "__esModule", { value: true });
var assertron_1 = require("assertron");
var tersify_1 = require("tersify");
var io_1 = require("./io");
var specStore_1 = require("./specStore");
var plugin_1 = require("./plugin");
```


First pass full content:
```ts
"use strict";
var __assign = (this && this.__assign) || Object.assign || function(t) {
    for (var s, i = 1, n = arguments.length; i < n; i++) {
        s = arguments[i];
        for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
            t[p] = s[p];
    }
    return t;
};
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (_) try {
            if (f = 1, y && (t = y[op[0] & 2 ? "return" : op[0] ? "throw" : "next"]) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [0, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
var assertron_1 = require("assertron");
var tersify_1 = require("tersify");
var unpartial_1 = require("unpartial");
var io_1 = require("./io");
var SpecOptions_1 = require("./SpecOptions");
var specStore_1 = require("./specStore");
var plugin_1 = require("./plugin");
function makeErrorSerializable(actions) {
    actions.forEach(function (a) {
        if (isRejectErrorPromiseReturnAction(a) ||
            isErrorThrowAction(a)) {
            a.payload = __assign({ message: a.payload.message }, a.payload);
        }
    });
}
exports.makeErrorSerializable = makeErrorSerializable;
function isErrorThrowAction(action) {
    return /\/throw/.test(action.type) && action.payload instanceof Error;
}
function isRejectErrorPromiseReturnAction(action) {
    return action.type === 'promise' && action.meta.status === 'reject' && action.payload instanceof Error;
}
exports.spec = Object.assign(function spec(id, subject) {
    return __awaiter(this, void 0, void 0, function () {
        var opt, mode;
        return __generator(this, function (_a) {
            opt = unpartial_1.unpartial(SpecOptions_1.defaultSpecOptions, { id: id, mode: 'verify' });
            mode = SpecOptions_1.getMode(opt);
            return [2 /*return*/, createSpec(opt.id, subject, mode)];
        });
    });
}, {
    save: function (id, subject) {
        return __awaiter(this, void 0, void 0, function () {
            var mode;
            return __generator(this, function (_a) {
                mode = SpecOptions_1.getMode({ id: id, mode: 'save' });
                return [2 /*return*/, createSpec(id, subject, mode)];
            });
        });
    },
    simulate: function (id, subject) {
        return __awaiter(this, void 0, void 0, function () {
            var mode;
            return __generator(this, function (_a) {
                mode = SpecOptions_1.getMode({ id: id, mode: 'simulate' });
                return [2 /*return*/, createSpec(id, subject, mode)];
            });
        });
    }
});
function createSpec(id, subject, mode) {
    return __awaiter(this, void 0, void 0, function () {
        var store, context;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    store = specStore_1.createSpecStore();
                    context = store;
                    context.mode = mode;
                    context.id = id;
                    if (!(mode === 'simulate')) return [3 /*break*/, 2];
                    return [4 /*yield*/, store.load(id)];
                case 1:
                    _a.sent();
                    context.subject = plugin_1.komondorUtil.getStub(context, subject, id);
                    return [3 /*break*/, 3];
                case 2:
                    context.subject = plugin_1.komondorUtil.getSpy(context, subject);
                    _a.label = 3;
                case 3: return [2 /*return*/, Object.assign(context, {
                        satisfy: function (expectation) {
                            return Promise.resolve().then(function () {
                                var actions = store.actions;
                                assertron_1.satisfy(actions, expectation);
                                if (mode === 'save') {
                                    // istanbul ignore next
                                    if (!id)
                                        throw new Error('Cannot save spec without options.id.');
                                    makeErrorSerializable(actions);
                                    return io_1.io.writeSpec(id, {
                                        expectation: tersify_1.tersify(expectation, { maxLength: Infinity, raw: true }),
                                        actions: actions
                                    });
                                }
                            });
                        }
                    })];
            }
        });
    });
}
//# sourceMappingURL=spec.js.map
```

Second pass full content:
```ts
"use strict";
var __assign = (this && this.__assign) || Object.assign || function(t) {
    for (var s, i = 1, n = arguments.length; i < n; i++) {
        s = arguments[i];
        for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
            t[p] = s[p];
    }
    return t;
};
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (_) try {
            if (f = 1, y && (t = y[op[0] & 2 ? "return" : op[0] ? "throw" : "next"]) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [0, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
var assertron_1 = require("assertron");
var tersify_1 = require("tersify");
var io_1 = require("./io");
var specStore_1 = require("./specStore");
var plugin_1 = require("./plugin");
function makeErrorSerializable(actions) {
    actions.forEach(function (a) {
        if (isRejectErrorPromiseReturnAction(a) ||
            isErrorThrowAction(a)) {
            a.payload = __assign({ message: a.payload.message }, a.payload);
        }
    });
}
exports.makeErrorSerializable = makeErrorSerializable;
function isErrorThrowAction(action) {
    return /\/throw/.test(action.type) && action.payload instanceof Error;
}
function isRejectErrorPromiseReturnAction(action) {
    return action.type === 'promise' && action.meta.status === 'reject' && action.payload instanceof Error;
}
exports.spec = Object.assign(function spec(id, subject) {
    return __awaiter(this, void 0, void 0, function () {
        var opt, mode;
        return __generator(this, function (_a) {
            opt = unpartial_1.unpartial(SpecOptions_1.defaultSpecOptions, { id: id, mode: 'verify' });
            mode = SpecOptions_1.getMode(opt);
            return [2 /*return*/, createSpec(opt.id, subject, mode)];
        });
    });
}, {
    save: function (id, subject) {
        return __awaiter(this, void 0, void 0, function () {
            var mode;
            return __generator(this, function (_a) {
                mode = SpecOptions_1.getMode({ id: id, mode: 'save' });
                return [2 /*return*/, createSpec(id, subject, mode)];
            });
        });
    },
    simulate: function (id, subject) {
        return __awaiter(this, void 0, void 0, function () {
            var mode;
            return __generator(this, function (_a) {
                mode = SpecOptions_1.getMode({ id: id, mode: 'simulate' });
                return [2 /*return*/, createSpec(id, subject, mode)];
            });
        });
    }
});
function createSpec(id, subject, mode) {
    return __awaiter(this, void 0, void 0, function () {
        var store, context;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    store = specStore_1.createSpecStore();
                    context = store;
                    context.mode = mode;
                    context.id = id;
                    if (!(mode === 'simulate')) return [3 /*break*/, 2];
                    return [4 /*yield*/, store.load(id)];
                case 1:
                    _a.sent();
                    context.subject = plugin_1.komondorUtil.getStub(context, subject, id);
                    return [3 /*break*/, 3];
                case 2:
                    context.subject = plugin_1.komondorUtil.getSpy(context, subject);
                    _a.label = 3;
                case 3: return [2 /*return*/, Object.assign(context, {
                        satisfy: function (expectation) {
                            return Promise.resolve().then(function () {
                                var actions = store.actions;
                                assertron_1.satisfy(actions, expectation);
                                if (mode === 'save') {
                                    // istanbul ignore next
                                    if (!id)
                                        throw new Error('Cannot save spec without options.id.');
                                    makeErrorSerializable(actions);
                                    return io_1.io.writeSpec(id, {
                                        expectation: tersify_1.tersify(expectation, { maxLength: Infinity, raw: true }),
                                        actions: actions
                                    });
                                }
                            });
                        }
                    })];
            }
        });
    });
}
//# sourceMappingURL=spec.js.map
```

**Comment by jwbay** [comment]
Probably same as https://github.com/Microsoft/TypeScript/issues/21478

**Comment by RyanCavanaugh** [comment]
@phillipb can you try with `typescript@latest` and see if this has been fixed? Thanks!

**Comment by unional** [comment]
I encountered this on 2.7.1

Also, not only promise. Seems like something with `Object.assign()` also doesn't work.

**Comment by phillipb** [comment]
@RyanCavanaugh tried this on `typescript@latest` which appears to be `2.7.1`, and yes, I do still have this issue. Is there another version I should try?

**Comment by RyanCavanaugh** [comment]
Sorry, I meant `typescript@next`

**Comment by unional** [comment]
Yes, also tried that. The case above seems to be gone in `next`, but the `Object.assign()` one still exists.

**Comment by mhegazy** [comment]
@unional can you elaborate on what the `object.assign` issue is?

**Comment by unional** [comment]
Here is the repro: https://github.com/unional/komondor/blob/ts-2.7-obj.assign/src/environment.ts#L60

I'm not sure if it is the `Object.assign()` in the line above or the source (https://github.com/unional/komondor/blob/ts-2.7-obj.assign/src/spec.ts#L87) which causes the issue.

If you take out that line (and change the next line from `{ ...spec: simSpec }` to `{ ...spec }`, it compiles. 

And this occurs in the first pass in watch more (instead of second pass).
Running `tsc` without `-w` does not have this issue.

**Comment by sheetalkamat** [comment]
@unional I am trying to repro this
This is what i did:
- ```node node_modules/typescript/lib/tsc -p tsconfig.es5.json --w  --pretty```
- I see 
```
[11:25:41] Starting compilation in watch mode...


[11:25:44] Compilation complete. Watching for file changes.
```
- Copied the ```dist-es5``` folder for all the outputs to (```v1\dist-es5```)
- Change https://github.com/unional/komondor/blob/ts-2.7-obj.assign/src/environment.ts#L60 from 
```typescript
const simSpec = Object.assign(spec.simulate, { save: spec.save, simulate: spec.simulate })
const simulateContext = { mode: 'simulate', spec: simSpec } as any
```
to 
```typescript
const simulateContext = { mode: 'simulate', ...spec } as any
```
- I see this 
```
[11:25:58] File change detected. Starting incremental compilation...


[11:25:58] Compilation complete. Watching for file changes.

```
- Copied the folder ```dist-es5``` folder for all the outputs to (```v2\dist-es5```)
- The diff between v1 and v2 is only in ```spec.js``` and is:
```typescript
var simSpec = Object.assign(spec_1.spec.simulate, { save: spec_1.spec.save, simulate: spec_1.spec.simulate });
var simulateContext = { mode: 'simulate', spec: simSpec };
```
to 
```typescript
var simulateContext = __assign({ mode: 'simulate' }, spec_1.spec);
```
- Then i closed that process and did and started watch mode again no errors again:
- The output copied to folder ```v3\dist-es5```
- there is no diff between ```v2\dist-es5``` and  ```v3\dist-es5``` at alll
- After this i closed that process and just ran tsc without watch (````node node_modules/typescript/lib/tsc -p tsconfig.es5.json  --pretty```)
- output copied to ```v4\dist-es5``` and there is no diff again between v2/v3 version output.

Did I miss any repro steps?

**Comment by unional** [comment]
Please run `npm run watch`. The compliation actually passes, but the emitted code does not (don't know why you didn't see the diff in the output. 

```sh
2:00:17 - Starting compilation in watch mode...


12:00:20 - Compilation complete. Watching for file changes.



> komondor@0.0.0-development lint /Users/hwong/code/unional/komondor
> tslint -p tsconfig.json 'src/**/*.ts'

/Users/hwong/code/unional/komondor/dist-es5/environment.js:113
var simSpec = Object.assign(spec_1.spec.simulate, { save: spec_1.spec.save, simulate: spec_1.spec.simulate });
                                        ^

TypeError: Cannot read property 'simulate' of undefined
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/environment.ts:60:36)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/index.ts:2:1)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
 komondor  Cannot load saved record for spec 'class/notExist'.
 komondor  No record for 'constructor'. Spying instead
 komondor  The current action 'constructor' does not match with saved record of class/extendToSpy. Spying instead.
 komondor  { errno: -2, code: 'ENOENT', syscall: 'open', path: '/Users/hwong/code/unional/komondor/__komondor__/specs/class/no... }
/Users/hwong/code/unional/komondor/dist-es5/environment.js:113
var simSpec = Object.assign(spec_1.spec.simulate, { save: spec_1.spec.save, simulate: spec_1.spec.simulate });
                                        ^

TypeError: Cannot read property 'simulate' of undefined
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/environment.ts:60:36)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/index.ts:2:1)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
/Users/hwong/code/unional/komondor/dist-es5/environment.js:113
var simSpec = Object.assign(spec_1.spec.simulate, { save: spec_1.spec.save, simulate: spec_1.spec.simulate });
                                        ^

TypeError: Cannot read property 'simulate' of undefined
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/environment.ts:60:36)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/index.ts:2:1)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
/Users/hwong/code/unional/komondor/dist-es5/environment.js:113
var simSpec = Object.assign(spec_1.spec.simulate, { save: spec_1.spec.save, simulate: spec_1.spec.simulate });
                                        ^

TypeError: Cannot read property 'simulate' of undefined
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/environment.ts:60:36)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/index.ts:2:1)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
 komondor  Cannot load saved record for spec 'ws/echo/notExist'.
 komondor  { errno: -2, code: 'ENOENT', syscall: 'open', path: '/Users/hwong/code/unional/komondor/__komondor__/specs/ws/echo/... }
 komondor  The current action 'constructor' does not match with saved record of ws/echo/notExist. Spying instead.
...
```

**Comment by unional** [comment]
Also using the same tsc:
```sh
SJCMACL09WHTDG:komondor hwong$ node node_modules/typescript/lib/tsc -version
Version 2.8.0-dev.20180204
```

**Comment by unional** [comment]
```ts
const simSpec = Object.assign(spec.simulate, { save: spec.save, simulate: spec.simulate })
const simulateContext = { mode: 'simulate', spec: simSpec } as any

// to

const simulateContext = { mode: 'simulate', ...spec } as any
```

Seems like something wrong in your step. It should be:
```ts
// to

const simulateContext = { mode: 'simulate', spec } as any
```

**Comment by unional** [comment]
Just take a deeper look into it. It seems like the code compiled by ts@2.7 and 2.8 encounter some runtime issue on Node@9.4.0.

I added a line `console.log('spec.simulate', spec.simulate)` before that line and i got:

```sh
/Users/hwong/code/unional/komondor/dist-es5/environment.js:112
console.log('spec.simulate', spec_1.spec.simulate);
                                         ^

TypeError: Cannot read property 'simulate' of undefined
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/environment.ts:58:35)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/index.ts:2:1)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
spec.simulate function (id, subject) {
        return __awaiter(this, void 0, void 0, function () {
            var mode;
            return __generator(this, function (_a) {
                mode = getMode(id, 'simulate');
                return [2 /*return*/, createSpec(id, subject, mode)];
            });
        });
    }
 komondor  Cannot load saved record for spec 'class/notExist'.
 komondor  { errno: -2, code: 'ENOENT', syscall: 'open', path: '/Users/hwong/code/unional/komondor/__komondor__/specs/class/no... }
 komondor  No record for 'constructor'. Spying instead
 komondor  The current action 'constructor' does not match with saved record of class/extendToSpy. Spying instead.
spec.simulate function (id, subject) {
        return __awaiter(this, void 0, void 0, function () {
            var mode;
            return __generator(this, function (_a) {
                mode = getMode(id, 'simulate');
                return [2 /*return*/, createSpec(id, subject, mode)];
            });
        });
    }
spec.simulate function (id, subject) {
        return __awaiter(this, void 0, void 0, function () {
            var mode;
            return __generator(this, function (_a) {
                mode = getMode(id, 'simulate');
                return [2 /*return*/, createSpec(id, subject, mode)];
            });
        });
    }
/Users/hwong/code/unional/komondor/dist-es5/environment.js:112
console.log('spec.simulate', spec_1.spec.simulate);
                                         ^

TypeError: Cannot read property 'simulate' of undefined
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/environment.ts:58:35)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/index.ts:2:1)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
/Users/hwong/code/unional/komondor/dist-es5/environment.js:112
console.log('spec.simulate', spec_1.spec.simulate);
                                         ^

TypeError: Cannot read property 'simulate' of undefined
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/environment.ts:58:35)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/index.ts:2:1)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
/Users/hwong/code/unional/komondor/dist-es5/environment.js:112
console.log('spec.simulate', spec_1.spec.simulate);
                                         ^

TypeError: Cannot read property 'simulate' of undefined
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/environment.ts:58:35)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/index.ts:2:1)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at extensions.(anonymous function) (/Users/hwong/code/unional/komondor/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hwong/code/unional/komondor/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:573:32)
spec.simulate function (id, subject) {
        return __awaiter(this, void 0, void 0, function () {
            var mode;
            return __generator(this, function (_a) {
                mode = getMode(id, 'simulate');
                return [2 /*return*/, createSpec(id, subject, mode)];
            });
        });
    }
 komondor  Cannot load saved record for spec 'ws/echo/notExist'.
 komondor  { errno: -2, code: 'ENOENT', syscall: 'open', path: '/Users/hwong/code/unional/komondor/__komondor__/specs/ws/echo/... }
 komondor  The current action 'constructor' does not match with saved record of ws/echo/notExist. Spying instead.
spec.simulate function (id, subject) {
        return __awaiter(this, void 0, void 0, function () {
            var mode;
            return __generator(this, function (_a) {
                mode = getMode(id, 'simulate');
                return [2 /*return*/, createSpec(id, subject, mode)];
            });
        });
    }
 komondor  Cannot load saved record for spec 'specStore/notExist'.
 komondor  { errno: -2, code: 'ENOENT', syscall: 'open', path: '/Users/hwong/code/unional/komondor/__komondor__/specs/specStor... }
```

So it works some times but not others.

**Comment by RyanCavanaugh** [comment]
@sheetalkamat I have a reliable repro if you need it

**Comment by sheetalkamat** [comment]
@unional but the error you are seeing is not going to be there in second one anyways since the output changed from 
```javascript
var simSpec = Object.assign(spec_1.spec.simulate, { save: spec_1.spec.save, simulate: spec_1.spec.simulate });
var simulateContext = { mode: 'simulate', spec: simSpec };
```
to
```javascript
var simulateContext = { mode: 'simulate', spec: spec_1.spec };
```

wherein in the second pass you are not accessing ```spec_1.spec.simulate``` right? 

Since the v1 output (after modifying the change as you suggested in https://github.com/Microsoft/TypeScript/issues/21612#issuecomment-363204971) is if i ran the tsc without --watch mode (without any change) if you run that code, arent you going to get same result ?

**Comment by unional** [comment]
^ opened an issue for node@9.4.0

**Comment by unional** [comment]
@sheetalkamat please see https://github.com/Microsoft/TypeScript/issues/21612#issuecomment-363207983

Seems like the compiled output is the same in this case either with or without `-w`.
The current problem I have is the compiled output does not work consistently in Node 9.4.0.
(don't know if it works on other node versions).

If you want, I can open another issue. The OP issue seems to be fixed in 2.8.

**Comment by unional** [comment]
https://github.com/nodejs/node/issues/18586#issuecomment-363212766

> This is probably due to cyclic dependencies, i.e. this is expected

**Comment by sheetalkamat** [comment]
@unional Yes please open another issue to track output not working correctly. The original issue reported (with incorrect output files with edits in --watch) i believe has been fixed by #21478. The issue should be fixed in typescript@next and in the upcoming typescript@2.7.2 release.

**Comment by unional** [comment]
Created https://github.com/Microsoft/TypeScript/issues/21645

**Comment by x22x22** [comment]
2.7.1 miss import(tsc-w)
2.6.2 no problem
