### ISSUE TITLE
2.7.1 emit output that works intermittently in Node@9.4.0

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#21645]
From https://github.com/Microsoft/TypeScript/issues/21612#issuecomment-363185697

Repro: https://github.com/unional/komondor/tree/node-9.4.0-require

These lines https://github.com/unional/komondor/tree/node-9.4.0-require produces:

(trimmed log)
```sh
direct get ./spec {}
/Users/hwong/code/unional/komondor/dist-es5/environment.js:114
console.log('spec.simulate', spec_1.spec.simulate);
                                         ^
TypeError: Cannot read property 'simulate' of undefined
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/environment.ts:60:35)
    ....
direct get ./spec { makeErrorSerializable: [Function: makeErrorSerializable],
  spec: { [Function: spec] save: [Function: save], simulate: [Function: simulate] } }
spec.simulate function (id, subject) {
        return __awaiter(this, void 0, void 0, function () {
            var mode;
            return __generator(this, function (_a) {
                mode = getMode(id, 'simulate');
                return [2 /*return*/, createSpec(id, subject, mode)];
            });
        });
    }
direct get ./spec { makeErrorSerializable: [Function: makeErrorSerializable],
  spec: { [Function: spec] save: [Function: save], simulate: [Function: simulate] } }
spec.simulate function (id, subject) {
        return __awaiter(this, void 0, void 0, function () {
            var mode;
            return __generator(this, function (_a) {
                mode = getMode(id, 'simulate');
                return [2 /*return*/, createSpec(id, subject, mode)];
            });
        });
    }
direct get ./spec { makeErrorSerializable: [Function: makeErrorSerializable],
  spec: { [Function: spec] save: [Function: save], simulate: [Function: simulate] } }
spec.simulate function (id, subject) {
        return __awaiter(this, void 0, void 0, function () {
            var mode;
            return __generator(this, function (_a) {
                mode = getMode(id, 'simulate');
                return [2 /*return*/, createSpec(id, subject, mode)];
            });
        });
    }
direct get ./spec {}
/Users/hwong/code/unional/komondor/dist-es5/environment.js:114
console.log('spec.simulate', spec_1.spec.simulate);

TypeError: Cannot read property 'simulate' of undefined
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/environment.ts:60:35)
    ...
direct get ./spec {}
/Users/hwong/code/unional/komondor/dist-es5/environment.js:114
console.log('spec.simulate', spec_1.spec.simulate);
                                         ^
TypeError: Cannot read property 'simulate' of undefined
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/environment.ts:60:35)
    ...
direct get ./spec {}
/Users/hwong/code/unional/komondor/dist-es5/environment.js:114
console.log('spec.simulate', spec_1.spec.simulate);
                                         ^
TypeError: Cannot read property 'simulate' of undefined
    at Object.<anonymous> (/Users/hwong/code/unional/komondor/src/environment.ts:60:35)
    ...
direct get ./spec { makeErrorSerializable: [Function: makeErrorSerializable],
  spec: { [Function: spec] save: [Function: save], simulate: [Function: simulate] } }
spec.simulate function (id, subject) {
        return __awaiter(this, void 0, void 0, function () {
            var mode;
            return __generator(this, function (_a) {
                mode = getMode(id, 'simulate');
                return [2 /*return*/, createSpec(id, subject, mode)];
            });
        });
    }
direct get ./spec { makeErrorSerializable: [Function: makeErrorSerializable],
  spec: { [Function: spec] save: [Function: save], simulate: [Function: simulate] } }
spec.simulate function (id, subject) {
        return __awaiter(this, void 0, void 0, function () {
            var mode;
            return __generator(this, function (_a) {
                mode = getMode(id, 'simulate');
                return [2 /*return*/, createSpec(id, subject, mode)];
            });
        });
    }
```

i.e. `var spec = require('./spec')` sometime produce an empty object `{}`.

https://github.com/nodejs/node/issues/18586#issuecomment-363212766
mentions it could be a cyclic dependencies issue.

But I check the code and there should be no cyclic dependencies in the source.

**Comment by unional** [comment]
Can be reproduced by running `npm run test` or `npm run watch`.

**Comment by unional** [comment]
https://github.com/Microsoft/TypeScript/issues/21612#issuecomment-363209182

@RyanCavanaugh have another repro. 🌷 

I'll try to sort out mine.

**Comment by unional** [comment]
It is due to cyclic dependencies.

I have some folders in this project references the top `../index` because I design these as a plugin.
Once I remove the cyclic dependencies the issue goes away.

So my repro is not valid.

@RyanCavanaugh, is your case still stands?

**Comment by sheetalkamat** [comment]
Marking this unassigned so that this can be triaged
