### ISSUE TITLE
Very deep ASTs crash the compiler

### ISSUE THREAD

**Issue by pepve** [Microsoft/TypeScript#21720]
Very deep ASTs crash the compiler. Illustrated in this issue by an impressively long chain of functions calls. (Actually happened in our code base.) Bug #13549 talks about this but related to many successive addition operators. I would like to suggest that instead of crashing, the AST depth is measured and a descriptive error is displayed when it exceeds a limit. In this example on my environment the limit is 235 chained function calls.

**TypeScript Version:**  2.8.0-dev.20180206

**Search Terms:** Maximum call stack size exceeded, chained, method chaining, function chaining

**Code**
```ts
class Example {
    public chained(): Example {
        return this;
    }
}

const instance = new Example();

instance
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained() // 64
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained() // 128
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained() // 192
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained();// 256
```

**Expected behavior:**
It compiles.

**Actual behavior:**
Compiler crashes:
```
$ tsc chains.ts 
/.../typescript/lib/tsc.js:60398
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at emitNodeWithNotification (/.../typescript/lib/tsc.js:54158:42)
    at pipelineEmitWithNotification (/.../typescript/lib/tsc.js:56913:17)
    at emitExpression (/.../typescript/lib/tsc.js:56909:13)
    at emitCallExpression (/.../typescript/lib/tsc.js:57660:13)
    at pipelineEmitExpression (/.../typescript/lib/tsc.js:57219:28)
    at pipelineEmitWithHint (/.../typescript/lib/tsc.js:56940:32)
    at emitNodeWithSourceMap (/.../typescript/lib/tsc.js:54432:24)
    at pipelineEmitWithSourceMap (/.../typescript/lib/tsc.js:56930:17)
    at emitNodeWithNestedComments (/.../typescript/lib/tsc.js:54702:17)
    at emitNodeWithSynthesizedComments (/.../typescript/lib/tsc.js:54652:13)
```

**Playground Link:** Does not reproduce at https://www.typescriptlang.org/play/

**Related Issues:** #13549 describes the same problem but caused by successive addition operators and suggesting a different solution.

**Comment by mhegazy** [comment]
@rbuckton thoughts?

**Comment by rbuckton** [comment]
@mhegazy the deep stacks issue affects performance as well. I'd like to dig into this further to see what we can do to reduce overall stack depth, though I'm concerned some changes might necessitate breaking changes to the transformation API. 

@pepve In the mean time, you can work around this by running tsc.js with node directly and increasing the stack size to something like `--stack_size=1200`

**Comment by rbuckton** [comment]
@pepve I have a PR for a fix that reduces our overall stack depth during emit. Its still possible to exhaust the call stack, but I was able to expand upon your example to 743 nested calls to `.chained()` without a problem. At 744 nested calls we actually ran out of stack space in the checker instead.

**Comment by pepve** [comment]
@rbuckton Thank you, that's awesome!
