### ISSUE TITLE
TypeError: Cannot read property 'isOrphan' of undefined

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#21738]
```log
Info 0    [15:23:20.300] Starting TS Server
Info 1    [15:23:20.301] Version: 2.7.1
Info 2    [15:23:20.301] Arguments: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/v9/pvvhngx90yv2g6j8t1chtpzm0000gn/T/vscode-tscancellation-79df1c2e10671b51b560.sock* --logVerbosity verbose --logFile /Users/tferullo/Library/Application Support/Code/logs/20180207T151146/vscode.typescript_1/tsserver-log-IjCghx/tsserver.log --locale en
Info 3    [15:23:20.301] Platform: darwin NodeVersion: 7 CaseSensitive: false
Info 4    [15:23:20.303] Provided types map file "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js/../typesMap.json" doesn't exist
Info 5    [15:23:20.303] Binding...
Info 6    [15:23:20.310] event:
    {"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":41733}}
Info 7    [15:23:20.311] request:
    {"seq":0,"type":"request","command":"configure","arguments":{"hostInfo":"vscode"}}
Info 8    [15:23:20.311] Host information vscode
Info 9    [15:23:20.312] response:
    {"seq":0,"type":"response","command":"configure","request_seq":0,"success":true}
Perf 10   [15:23:20.312] 0::configure: async elapsed time (in milliseconds) 0.6800
Info 11   [15:23:20.312] request:
    {"seq":1,"type":"request","command":"compilerOptionsForInferredProjects","arguments":{"options":{"module":"commonjs","target":"es2016","jsx":"preserve","allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true}}}
Info 12   [15:23:20.313] Scheduled: *refreshInferredProjects*
Perf 13   [15:23:20.313] 1::compilerOptionsForInferredProjects: elapsed time (in milliseconds) 0.9034
Info 14   [15:23:20.313] response:
    {"seq":0,"type":"response","command":"compilerOptionsForInferredProjects","request_seq":1,"success":true,"body":true}
Info 15   [15:23:20.313] request:
    {"seq":2,"type":"request","command":"geterr","arguments":{"delay":0,"files":["/.........................._events.js","/...................hl7_process.js"]}}
Err 16    [15:23:20.324] Exception on executing command delayed processing of request 2:

    Cannot read property 'isOrphan' of undefined

    TypeError: Cannot read property 'isOrphan' of undefined
    at ProjectService.getDefaultProjectForFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:87391:63)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:90005:74
    at Object.mapDefined (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:1776:30)
    at IOSession.Session.createCheckList (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:90003:27)
    at IOSession.Session.getDiagnostics (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:90010:38)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:89057:82
    at MultistepOperation.executeAction (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:88829:25)
    at MultistepOperation.startNew (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:88794:22)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:89057:42)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:90393:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:90384:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:90393:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:90413:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:91614:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
Info 17   [15:23:20.324] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":2}}
Perf 18   [15:23:20.324] 2::geterr: async elapsed time (in milliseconds) 10.9988
Info 19   [15:23:20.567] Running: *refreshInferredProjects*
Info 20   [15:23:20.567] refreshInferredProjects: updating project structure from ...
Info 21   [15:23:20.567] Open files: 
Info 21   [15:23:20.567] refreshInferredProjects: updated project structure ...
Info 22   [15:23:20.567] Open files: 
Info 22   [15:23:20.568] got projects updated in background, updating diagnostics for 
Info 23   [15:23:20.635] Exiting...
```

**Comment by mhegazy** [comment]
The original issue seems like a bug in VSCode, we are getting an error request before an open request. @mjbvz thoughts?

regardless of that, we should not throw an exception.

**Comment by mjbvz** [comment]
Does the `open` request ever come in? Any idea what state the workspace started in / do you have repo steps?

**Comment by mhegazy** [comment]
I was looking at crash report, so the server does crash at the end of the log above.. so i am afraid i can not answer this one.
