### ISSUE TITLE
TypeError: Cannot read property 'escapedName' of undefined in 'symbolName' during 'occurrences'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#21792]
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.1
**VSCode Version** 1.19.3
**command requested**: occurrences
**hitting sessions**: 3356
**proportion of all sessions**: 0.01252832498982727
**stack**
```
TypeError: Cannot read property 'escapedName' of undefined
    at symbolName (tsserver.js:69409:23)
    at getImport (tsserver.js:69349:36)
    at Object.getImportOrExportSymbol (tsserver.js:69276:68)
    at getImportOrExportReferences (tsserver.js:70123:56)
    at getReferencesAtLocation (tsserver.js:70071:17)
    at getReferencesInContainer (tsserver.js:70026:21)
    at getReferencedSymbolsForSymbol (tsserver.js:69744:25)
    at Object.getReferencedSymbolsForNode (tsserver.js:69660:24)
    at Object.getReferenceEntriesForNode (tsserver.js:69500:58)
    at getSemanticDocumentHighlights (tsserver.js:68440:57)
    at Object.getDocumentHighlights (tsserver.js:68429:20)
    at getDocumentHighlights (tsserver.js:82973:42)
    at getOccurrencesAtPositionCore (tsserver.js:82976:46)
    at Object.getOccurrencesAtPosition (tsserver.js:82962:27)
    at IOSession.Session.getOccurrences (tsserver.js:89496:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89112:61)
    at unknown (tsserver.js:90393:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90384:28)
    at IOSession.Session.executeCommand (tsserver.js:90393:33)
    at IOSession.Session.onMessage (tsserver.js:90413:35)
    at Interface.<anonymous> (tsserver.js:91614:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by aozgaa** [comment]
This issue reproduced in the following context:
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.21.0-insider
**command requested**: occurrences
**hitting sessions**: 536
**proportion of all sessions**: 0.011004126547455296
**stack**
```
TypeError: Cannot read property 'escapedName' of undefined
    at symbolName (tsserver.js:69569:23)
    at getImport (tsserver.js:69509:36)
    at Object.getImportOrExportSymbol (tsserver.js:69436:68)
    at getImportOrExportReferences (tsserver.js:70283:56)
    at getReferencesAtLocation (tsserver.js:70231:17)
    at getReferencesInContainer (tsserver.js:70186:21)
    at getReferencedSymbolsForSymbol (tsserver.js:69904:25)
    at Object.getReferencedSymbolsForNode (tsserver.js:69820:24)
    at Object.getReferenceEntriesForNode (tsserver.js:69660:58)
    at getSemanticDocumentHighlights (tsserver.js:68595:57)
    at Object.getDocumentHighlights (tsserver.js:68584:20)
    at getDocumentHighlights (tsserver.js:83133:42)
    at getOccurrencesAtPositionCore (tsserver.js:83136:46)
    at Object.getOccurrencesAtPosition (tsserver.js:83122:27)
    at IOSession.Session.getOccurrences (tsserver.js:89656:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89272:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```
