### ISSUE TITLE
Error: Debug Failure. False expression. in 'getNodes' during 'getCodeFixes'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#21812]
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.1
**VSCode Version** 1.19.3
**command requested**: getCodeFixes
**hitting sessions**: 519
**proportion of all sessions**: 0.0019374853008701884
**stack**
```
Error: Debug Failure. False expression.
    at getNodes (tsserver.js:77598:22)
    at Object.getCodeActions (tsserver.js:77570:29)
    at unknown (tsserver.js:77059:33)
    at Object.forEach (tsserver.js:1430:30)
    at Object.getFixes (tsserver.js:77058:16)
    at unknown (tsserver.js:83206:35)
    at Object.flatMap (tsserver.js:1697:25)
    at Object.getCodeFixesAtPosition (tsserver.js:83204:23)
    at IOSession.Session.getCodeFixes (tsserver.js:90228:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89132:61)
    at unknown (tsserver.js:90393:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90384:28)
    at IOSession.Session.executeCommand (tsserver.js:90393:33)
    at IOSession.Session.onMessage (tsserver.js:90413:35)
    at Interface.<anonymous> (tsserver.js:91614:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by aozgaa** [comment]
This issue reproduced in the following context:
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.19.2
**command requested**: getCodeFixes
**hitting sessions**: 112
**proportion of all sessions**: 0.01188076800678901
**stack**
```
Error: Debug Failure. False expression.
    at getNodes (tsserver.js:77758:22)
    at Object.getCodeActions (tsserver.js:77730:29)
    at unknown (tsserver.js:77219:33)
    at Object.forEach (tsserver.js:1431:30)
    at Object.getFixes (tsserver.js:77218:16)
    at unknown (tsserver.js:83366:35)
    at Object.flatMap (tsserver.js:1698:25)
    at Object.getCodeFixesAtPosition (tsserver.js:83364:23)
    at IOSession.Session.getCodeFixes (tsserver.js:90388:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89292:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```
