### ISSUE TITLE
Error: Debug Failure. False expression. in 'getClass' during 'getCodeFixes'

### ISSUE THREAD

**Issue by aozgaa** [microsoft/TypeScript#22078]
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.20.0
**command requested**: getCodeFixes
**hitting sessions**: 105
**proportion of all sessions**: 0.023627362736273628
**five line hash**: 7697045ae834e19561114275f982bb8f
**stack**
```
Error: Debug Failure. False expression.
    at getClass (tsserver.js:77705:22)
    at unknown (tsserver.js:77693:46)
    at Function.ChangeTracker.with (tsserver.js:76585:17)
    at Object.getCodeActions (tsserver.js:77692:64)
    at unknown (tsserver.js:77219:33)
    at Object.forEach (tsserver.js:1431:30)
    at Object.getFixes (tsserver.js:77218:16)
    at unknown (tsserver.js:83366:35)
    at Object.flatMap (tsserver.js:1698:25)
    at Object.getCodeFixesAtPosition (tsserver.js:83364:23)
    at Object.proxy.getCodeFixesAtPosition (index.js:334:31)
    at IOSession.Session.getCodeFixes (tsserver.js:90388:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89292:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by andy-ms** [comment]
Probably related to https://github.com/Microsoft/TypeScript/issues/21607#issuecomment-363988238

**Comment by nicolashenry** [comment]
https://github.com/angelozerr/tslint-language-service/issues/60 ?
