### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#22140]
**TypeScript Version:**  2.7.2, 2.8.0-dev.20180222

**Search Terms:** "RangeError", "Maximum call stack size exceeded"

Unfortunately I can't share the code because it's a private repo, but a segment of the repeating stack trace looks like this:

```
at typeToTypeNodeHelper (node_modules/typescript/lib/typescript.js:27065:28)
at createTypeNodesFromResolvedType (node_modules/typescript/lib/typescript.js:27333:67)
at createTypeNodeFromObjectType (node_modules/typescript/lib/typescript.js:27167:35)
at createAnonymousTypeNode (node_modules/typescript/lib/typescript.js:27120:46)
at typeToTypeNodeHelper (node_modules/typescript/lib/typescript.js:27065:28)
at Object.typeToTypeNode (node_modules/typescript/lib/typescript.js:26895:41)
at typeToString (node_modules/typescript/lib/typescript.js:26874:40)
at reportNonexistentProperty (node_modules/typescript/lib/typescript.js:38843:172)
at checkPropertyAccessExpressionOrQualifiedName (node_modules/typescript/lib/typescript.js:38720:25)
at checkPropertyAccessExpression (node_modules/typescript/lib/typescript.js:38695:20)
at checkExpressionWorker (node_modules/typescript/lib/typescript.js:41992:28)
at checkExpression (node_modules/typescript/lib/typescript.js:41938:42)
at checkNonNullExpression (node_modules/typescript/lib/typescript.js:38680:37)
at resolveCallExpression (node_modules/typescript/lib/typescript.js:40057:28)
at resolveSignature (node_modules/typescript/lib/typescript.js:40353:28)
at getResolvedSignature (node_modules/typescript/lib/typescript.js:40385:26)
at checkCallExpression (node_modules/typescript/lib/typescript.js:40443:29)
at checkExpressionWorker (node_modules/typescript/lib/typescript.js:42001:28)
at checkExpression (node_modules/typescript/lib/typescript.js:41938:42)
at checkExpressionCached (node_modules/typescript/lib/typescript.js:41805:38)
at node_modules/typescript/lib/typescript.js:40870:32
at traverse (node_modules/typescript/lib/typescript.js:8462:28)
at visitNodes (node_modules/typescript/lib/typescript.js:13272:30)
at Object.forEachChild (node_modules/typescript/lib/typescript.js:13477:24)
at traverse (node_modules/typescript/lib/typescript.js:8478:31)
at Object.forEachReturnStatement (node_modules/typescript/lib/typescript.js:8458:16)
at checkAndAggregateReturnExpressionTypes (node_modules/typescript/lib/typescript.js:40867:16)
at getReturnTypeFromBody (node_modules/typescript/lib/typescript.js:40749:29)
at getReturnTypeOfSignature (node_modules/typescript/lib/typescript.js:30585:28)
at signatureToSignatureDeclarationHelper (node_modules/typescript/lib/typescript.js:27396:38)
at createTypeNodeFromObjectType (node_modules/typescript/lib/typescript.js:27156:49)
at createAnonymousTypeNode (node_modules/typescript/lib/typescript.js:27120:46)
<start back at the top, rinse and repeat>
```

The circumstances under which this happens are fairly particular but very consistent: It only happens when `npm link`ing a certain other package (also private) and attempting to run Jest tests. The other package is written in TypeScript but compiled to ES5, and moreover Jest should only be transpiling the code, not type checking, so I'm doubly confused why the stack trace seems to indicate the loop is happening in type checking code.

**Comment by mhegazy** [comment]
We are trying to write a type out seems like it, and then running into the issue.. it would help if you can compile your project under the debugger, that should at least tell you which type is causing the issue, and may help creating a sample repro outside your project.

**Comment by pelotom** [comment]
It looks like things start to go off the rails in `checkFunctionExpressionOrObjectLiteralMethodDeferred`, when it calls `getReturnTypeOfSignature`:

```ts
if (!returnTypeNode) {
    // There are some checks that are only performed in getReturnTypeFromBody, that may produce errors
    // we need. An example is the noImplicitAny errors resulting from widening the return expression
    // of a function. Because checking of function expression bodies is deferred, there was never an
    // appropriate time to do this during the main walk of the file (see the comment at the top of
    // checkFunctionExpressionBodies). So it must be done now.
    getReturnTypeOfSignature(getSignatureFromDeclaration(node));
}
```

from that point, the stack just repeats the following until it blows:

```
// ... to infinity and beyond!
signatureToSignatureDeclarationHelper (typescript.js:27405)
createTypeNodeFromObjectType (typescript.js:27162)
createAnonymousTypeNode (typescript.js:27120)
typeToTypeNodeHelper (typescript.js:27065)
createTypeNodesFromResolvedType (typescript.js:27342)
createTypeNodeFromObjectType (typescript.js:27173)
createAnonymousTypeNode (typescript.js:27120)
typeToTypeNodeHelper (typescript.js:27065)
typeToTypeNode (typescript.js:26895)
typeToString (typescript.js:26874)
reportNonexistentProperty (typescript.js:38852)
checkPropertyAccessExpressionOrQualifiedName (typescript.js:38729)
checkPropertyAccessExpression (typescript.js:38704)
checkExpressionWorker (typescript.js:42001)
checkExpression (typescript.js:41947)
checkNonNullExpression (typescript.js:38689)
resolveCallExpression (typescript.js:40066)
resolveSignature (typescript.js:40362)
getResolvedSignature (typescript.js:40394)
checkCallExpression (typescript.js:40452)
checkExpressionWorker (typescript.js:42010)
checkExpression (typescript.js:41947)
checkExpressionCached (typescript.js:41814)
(anonymous) (typescript.js:40879)
traverse (typescript.js:8462)
visitNodes (typescript.js:13272)
forEachChild (typescript.js:13477)
traverse (typescript.js:8478)
forEachReturnStatement (typescript.js:8458)
checkAndAggregateReturnExpressionTypes (typescript.js:40876)
getReturnTypeFromBody (typescript.js:40758)
getReturnTypeOfSignature (typescript.js:30594)
```

I'm inspecting this in the debugger @mhegazy, can you tell me how to obtain the problematic type?

**Comment by pelotom** [comment]
It looks like it's failing while processing a JS module. Again, I'm not sure why it's trying to check a return type, since it should just be transpiling. In fact, the JS module it's checking is _already_ ES5 compiled through TypeScript, so the transpilation should be a no-op in this case. I tried setting `checkJs: false` to no avail.

**Comment by mhegazy** [comment]
> It looks like things start to go off the rails in checkFunctionExpressionOrObjectLiteralMethodDeferred, when it calls getReturnTypeOfSignature:

Can you share the JS function/ file it is looking at when it crashes?

>  Again, I'm not sure why it's trying to check a return type, since it should just be transpiling.

All files are checked.

>  In fact, the JS module it's checking is already ES5 compiled through TypeScript

Why are you passing it to TS again then?

> so the transpilation should be a no-op in this case.

no, it is not. it is a full typecheck and transpile. you pay the memory and processing cost every time for it.

> I tried setting checkJs: false to no avail.

this just reports the errors. checking is needed by the emitter to emit the file correctly.
