### ISSUE TITLE
Declaration files causes Resolver.resolveModule error at runtime

### ISSUE THREAD

**Issue by jy95** [Microsoft/TypeScript#22171]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 

Resolver.resolveModule , declaration files , module

**Problem**

I reproduced the problem on this branch of my repo  : https://github.com/jy95/mediaScan/tree/dropBabel

In order to have clear types for the users, I created a index.d.ts that show the exported class : 
```ts
// another types in another declaration file
import MediaScanTypes = require('./src/custom_types')

declare class MediaScan extends NodeJS.EventEmitter {

    // instance properties
    protected defaultPath: string; // Default path , if paths is empty
    protected parser: MediaScanTypes.ParseFunction; // the parser to extract the useful data from name
    protected whichCategory: MediaScanTypes.WhichCategoryFunction; // Function that tell us what is the category of the TPN
    protected paths: string[]; // all the paths that will be explored
    protected categoryForFile: Map<string, MediaScanTypes.Category>; // the mapping between file and Category
    protected stores: MediaScanTypes.MapSet<MediaScanTypes.TPN | MediaScanTypes.TPN_Extended>; // where I keep the result of Category

    // static properties
    static readonly MOVIES_TYPE : MediaScanTypes.Category.MOVIES_TYPE;
    static readonly TV_SERIES_TYPE : MediaScanTypes.Category.TV_SERIES_TYPE;

    // getters
    allMovies(): Set<MediaScanTypes.TPN_Extended>;
    allTvSeries(): Map<string, Set<MediaScanTypes.TPN_Extended>>;
    allFilesWithCategory(): Map<string, string>;

    // constructor
    constructor(dataParameters?: MediaScanTypes.DataParameters, customConfig?: MediaScanTypes.CustomFunctionsConfig);

    // static methods
    static listVideosExtension(): string[];
    createFromJSON(json: MediaScanTypes.LibAsJson, customConfig?: MediaScanTypes.CustomFunctionsConfig): MediaScan;

    // instance methods

    private addNewFiles(files: string[]): Promise<any>;
    addNewPath(...paths: string[]): Promise<any>;
    hasPathsProvidedByUser(): boolean;
    scan(): Promise<any>;
    removeOldFiles(...files: string[]): Promise<any>;
    toJSON(): string;
    toJSONObject(looseMode? : boolean) : MediaScanTypes.LibAsJson;

    // filtering methods
    filterMovies(searchParameters: MediaScanTypes.SearchParameters);
    filterTvSeries(searchParameters: MediaScanTypes.SearchParameters)
}

export = MediaScan;
```

And in a separate file (/src/custom_types), the types I used in other files of my library : 

```ts
declare namespace MediaScan {

    export interface TPN {
        title: string;
        year?: number;
        resolution?: string;
        extended?: boolean;
        unrated?: boolean;
        proper?: boolean;
        repack?: boolean;
        convert?: boolean;
        hardcoded?: boolean;
        retail?: boolean;
        remastered?: boolean;
        region?: string;
        container?: string;
        source?: string;
        codec?: string;
        audio?: string;
        group?: string;
        season?: number;
        episode?: number;
        language?: string;
    }

// extended by my own purpose
    export interface TPN_Extended extends TPN {
        filePath: string;
    }

// A parsing function to be used with this lib
    export interface ParseFunction {
        (title: string): TPN | TPN_Extended;
    }

// the media files categories
    export const enum Category {
        MOVIES_TYPE = 'MOVIES',
        TV_SERIES_TYPE = 'TV_SERIES'
    }

// which category is this file
    export interface WhichCategoryFunction {
        (object: TPN): Category
    }

// The sub way to store all kind of media files found in paths
    export type MappedType<T> = Map<string, Set<T>>;
    export type MapSet<T> = Map<Category, MappedType<T> | Set<T>>;

// example '<=25'
    export type NumberSearchSyntax = string;

// to handle number operations
    export interface NumberExpressionObject {
        operator: "==" | ">" | "<" | ">=" | "<=",
        number: number
    }

    export const enum AdditionalPropertiesType {
        STRING = 'string',
        NUMBER = 'number',
        BOOLEAN = 'boolean'
    }

// additional Properties
    export interface AdditionalProperties {
        type: AdditionalPropertiesType,
        name: string,
        value: boolean | string | string[] | number | NumberSearchSyntax
    }

    export interface MinimalSearchParameters {
        additionalProperties?: AdditionalProperties[]
    }

    export interface DefaultSearchParameters extends MinimalSearchParameters {
        extended?: boolean,
        unrated?: boolean,
        proper?: boolean,
        repack?: boolean,
        convert?: boolean,
        hardcoded?: boolean,
        retail?: boolean,
        remastered?: boolean,
        season?: number | NumberSearchSyntax,
        episode?: number | NumberSearchSyntax,
        year?: number | NumberSearchSyntax,
        title?: string | string[],
        resolution?: string | string[],
        codec?: string | string[],
        audio?: string | string[],
        group?: string | string[],
        region?: string | string[],
        container?: string | string[],
        language?: string | string[],
        source?: string | string[],
    }

    // search parameters for filter functions
    export type SearchParameters = Partial<DefaultSearchParameters | MinimalSearchParameters>;

    // for filtering tuples inside SearchParameters
    type filterTuple<T> = [string, T];

    // for optimized filtering function
    export type filterFunctionTuple = [{(set: Set<TPN>, propertiesMap: Map<string, any>)}, Map<string, any>];

    // for tuples inside json in createFromJSON
    type mappingStringAndCategory = [string, Category];
    type mappingStringAndTPNArray = [string, TPN[]];

    // json result to be used in createFromJSON
    export interface LibAsJson {
        allFilesWithCategory?: mappingStringAndCategory[],
        movies?: TPN[],
        series?: mappingStringAndTPNArray[],
        paths?: string[]
    }

    // the data parameters for constructor (aka first argument)
    export interface DataParameters {
        defaultPath?: string, // Default path , if paths is empty
        paths?: string[], // all the paths that will be explored
        allFilesWithCategory?: Map<string, Category>, // the mapping between file and Category
        movies?: Set<TPN | TPN_Extended>, // all the movies
        series?: Map<string, Set<TPN | TPN_Extended>>
    }

    // the custom functions (in order to have a different behaviour) for constructor (aka second argument)
    export interface CustomFunctionsConfig {
        parser?: ParseFunction,
        whichCategory?: WhichCategoryFunction
    }
}

export = MediaScan;
```

The compilation is working : 
```
> mediascan@1.1.1 compile D:\workspaceNodeJs\mediaScan
> tsc
Process finished with exit code 0
```

With this config : 
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2015",
    "lib": ["ES6","ES2017"],
    "outDir": "./lib",
    "removeComments": true,
    "sourceMap": true
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "src/**/*"
  ],
  "strict": true
}
```

**Expected behavior:**

It should work.

**Actual behavior:**

In Node REPL : 

```
> var test = require('./lib/MediaScan');
Error: Cannot find module '../index'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\workspaceNodeJs\mediaScan\lib\MediaScan.js:11:33)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at repl:1:12
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
```

Same way for the Jest tests 

```
Test suite failed to run

    Cannot find module '../index' from 'MediaScan.js'

       9 | const filterProperties_1 = require("./filters/filterProperties");
      10 | const utils_functions_1 = require("./utils/utils_functions");
    > 11 | const MediaScanClassInterface = require("../index");
      12 | module.exports = (_a = class MediaScan extends MediaScanClassInterface {
      13 |         constructor({ defaultPath = process.cwd(), paths = [], allFilesWithCategory = new Map(), movies = new Set(), series = new Map(), } = {}, { parser = nameParser, whichCategory = utils_functions_1.defaultWhichCategoryFunction, } = {}) {
      14 |             super();
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:194:17)
      at Object.<anonymous> (lib/MediaScan.js:11:83)
```

**Comment by jy95** [comment]
The problem is how to reuse the declared types from these files inside ts files. I found ugly the [Triple-Slash Directives
](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html)

**Comment by andy-ms** [comment]
The problem is that `class` doesn't just declare a type, it declares a value. If you just want to declare a type, use `interface`.

**Comment by jy95** [comment]
Ok, I hope I can keep the `extends NodeJS.EventEmitter ` in the declaration file. Inside the ts file, can I use "extends ClassInterface" with eventsEmitter ?

**Comment by andy-ms** [comment]
A class can't extend an interface. Learn more in the handbook: http://www.typescriptlang.org/docs/handbook/interfaces.html

**Comment by jy95** [comment]
Oups sorry, thanks for the correction : I will test and see if the @types of my lib are published when I fixed this
