### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/TypeScript#22224]
**TypeScript Version:**  2.8.0-dev.20180228

**Search Terms:** `Maximum call stack size exceeded`

**Code:** https://github.com/mysticatea/regexpp/tree/wip/src (I'm not sure where is the cause.)

1. `git clone https://github.com/mysticatea/regexpp.git`
2. `git checkout wip`
3. `npm install`
4. `npm run build`

**Expected behavior:** Success or compile error

**Actual behavior:** `tsc` crashed.

```
C:\Users\starc\Documents\GitHub\regexpp\node_modules\typescript\lib\tsc.js:59957
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at identity (C:\Users\starc\Documents\GitHub\regexpp\node_modules\typescript\lib\tsc.js:1281:22)
    at Object.binarySearch (C:\Users\starc\Documents\GitHub\regexpp\node_modules\typescript\lib\tsc.js:1024:19)
    at computeLineAndCharacterOfPosition (C:\Users\starc\Documents\GitHub\regexpp\node_modules\typescript\lib\tsc.js:4180:29)
    at Object.getLineAndCharacterOfPosition (C:\Users\starc\Documents\GitHub\regexpp\node_modules\typescript\lib\tsc.js:4192:16)
    at emitPos (C:\Users\starc\Documents\GitHub\regexpp\node_modules\typescript\lib\tsc.js:54003:36)
    at emitNodeWithSourceMap (C:\Users\starc\Documents\GitHub\regexpp\node_modules\typescript\lib\tsc.js:54051:21)
    at pipelineEmitWithSourceMap (C:\Users\starc\Documents\GitHub\regexpp\node_modules\typescript\lib\tsc.js:56513:17)
    at emitNodeWithComments (C:\Users\starc\Documents\GitHub\regexpp\node_modules\typescript\lib\tsc.js:54192:17)
    at pipelineEmitWithComments (C:\Users\starc\Documents\GitHub\regexpp\node_modules\typescript\lib\tsc.js:56505:17)
    at emitNodeWithNotification (C:\Users\starc\Documents\GitHub\regexpp\node_modules\typescript\lib\tsc.js:53768:21)
```

**Comment by weswigham** [comment]
[This right here is your problem.](https://github.com/mysticatea/regexpp/blob/wip/src/unicode/ids.ts#L6) We run out of stack space during the emit for that expression, since it's thousands of levels nested deep, and we probably push ~7 frames onto the stack for each level of nesting right now. And node's max stack size is around 11k, if I remember right.

**Comment by mysticatea** [comment]
Thank you for pointed out.
I will try another strategy to check Unicode properties ID_Start/ID_Continue.

**Comment by weswigham** [comment]
Wrapping parenthesis around halves of the check to balance the expression tree _may_ also work to reduce nesting.
