### ISSUE TITLE
Error: Debug Failure. Invalid cast. The supplied value did not pass the test 'isClassLike'. in 'Object.cast' during 'getCodeFixes'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#22479]
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.20.1
**command requested**: getCodeFixes
**hitting sessions**: 162
**proportion of all sessions**: 0.007555617741709809
**stack**
```
Error: Debug Failure. Invalid cast. The supplied value did not pass the test 'isClassLike'.
    at Object.cast (tsserver.js:2443:15)
    at getClassAndMakeStatic (tsserver.js:77502:43)
    at getInfo (tsserver.js:77473:38)
    at Object.getCodeActions (tsserver.js:77431:28)
    at unknown (tsserver.js:77219:33)
    at Object.forEach (tsserver.js:1431:30)
    at Object.getFixes (tsserver.js:77218:16)
    at unknown (tsserver.js:83366:35)
    at Object.flatMap (tsserver.js:1698:25)
    at Object.getCodeFixesAtPosition (tsserver.js:83364:23)
    at IOSession.Session.getCodeFixes (tsserver.js:90388:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89292:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by aozgaa** [comment]
This issue reproduced in the following context:
**TypeScript Version Prefix**: 2.8.1
**VSCode Version** 1.20.1
**command requested**: getCodeFixes
**hitting sessions**: 15
**proportion of all sessions**: 0.023923444976076555
**five line hash**: 7a3d485836b4b5324a3ea0da35e1493f
**stack**
```
Error: Debug Failure. Invalid cast. The supplied ModuleDeclaration did not pass the test 'isClassLike'.
    at Object.cast (tsserver.js:2545:19)
    at getClassAndMakeStatic (tsserver.js:79967:43)
    at getInfo (tsserver.js:79938:38)
    at Object.getCodeActions (tsserver.js:79896:28)
    at unknown (tsserver.js:78982:33)
    at Object.forEach (tsserver.js:1502:30)
    at Object.getFixes (tsserver.js:78981:16)
    at unknown (tsserver.js:84871:35)
    at Object.flatMap (tsserver.js:1772:25)
    at Object.getCodeFixesAtPosition (tsserver.js:84869:23)
    at IOSession.Session.getCodeFixes (tsserver.js:91902:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:90763:61)
    at unknown (tsserver.js:92067:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:92058:28)
    at IOSession.Session.executeCommand (tsserver.js:92067:33)
    at IOSession.Session.onMessage (tsserver.js:92087:35)
    at Interface.<anonymous> (tsserver.js:93288:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```
