### ISSUE TITLE
Debug failure in registerForUnusedIdentifiersCheck

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/TypeScript#22578]
Reporting from https://github.com/Microsoft/TypeScript/issues/21140#issuecomment-373070682
Reported by @aldendaniels 

```
8:47:12 AM - Starting compilation in watch mode...


/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:61401
                throw e;
                ^

Error: Debug Failure. False expression: Deferring unused identifier check twice
    at registerForUnusedIdentifiersCheck (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:36999:26)
    at checkFunctionOrMethodDeclaration (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:36995:13)
    at checkMethodDeclaration (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:36110:13)
    at checkSourceElement (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:39110:28)
    at Object.forEach (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:306:30)
    at checkClassExpressionDeferred (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:38165:16)
    at checkDeferredNodes (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:39293:25)
    at checkSourceFileWorker (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:39317:17)
    at checkSourceFile (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:39300:13)
    at getDiagnosticsWorker (/Users/alden/Projects/krypton/node_modules/typescript/lib/tsc.js:39355:17)
```

**Comment by falsandtru** [comment]
I saw this on almost all my projects.
