### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by bildja** [Microsoft/TypeScript#22948]
**TypeScript Version:**  2.9.0-dev.20180328

**Code**

```ts
import * as React from 'react';

const Test123 = () => <div/>;

function testComponent(props) {
    return <Test123 {...props}/>;
}
```

**Expected behavior:**
No errors

**Actual behavior:**
Exceptions:
```
TypeError: Cannot read property 'length' of undefined
    at Object.unescapeLeadingUnderscores (/node_modules/typescript/lib/typescript.js:12280:19)
    at checkJsxAttributesAssignableToTagNameAttributes (/typescript/lib/typescript.js:40117:146)
    at checkJsxOpeningLikeElementOrOpeningFragment (/node_modules/typescript/lib/typescript.js:40052:17)
    at checkJsxSelfClosingElement (/node_modules/typescript/lib/typescript.js:39449:13)
    at checkExpressionWorker (/node_modules/typescript/lib/typescript.js:43637:28)
    at checkExpression (/node_modules/typescript/lib/typescript.js:43530:42)
    at checkExpressionCached (/node_modules/typescript/lib/typescript.js:43396:38)
    at getReturnTypeFromBody (/node_modules/typescript/lib/typescript.js:42348:24)
    at getReturnTypeOfSignature (/node_modules/typescript/lib/typescript.js:31762:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (/node_modules/typescript/lib/typescript.js:42632:21)
```

**Comment by jaydh** [comment]
You're not giving props a type definition so it could be undefined and here the typeerror is coming from the spread operator because typescript can't be sure what you're passing in can be spread

**Comment by bildja** [comment]
@jaydh that's right, it anyway should not raise an exception on compile time. And it used to work prior to 2.8.0
