### ISSUE TITLE
Compiler throws unhandled exception 

### ISSUE THREAD

**Issue by dfilatov** [Microsoft/TypeScript#23025]
**TypeScript Version:**  2.8.1

**Code**

```ts
interface FunctionComponent {
    (): VElement;
}

interface FunctionComponentElement<TFunctionComponent extends FunctionComponent = FunctionComponent> {}

type VElement = FunctionComponentElement;
```

**Expected behavior:**
Code is compiled.

**Actual behavior:**
Unhandled exception:
```
node_modules/typescript/lib/tsc.js:61464
                throw e;
                ^

TypeError: Cannot read property 'length' of undefined
    at signaturesIdenticalTo (/home/dfilatov/www/nmaps/node_modules/typescript/lib/tsc.js:28824:37)
    at signaturesRelatedTo (/home/dfilatov/www/nmaps/node_modules/typescript/lib/tsc.js:28763:28)
    at structuredTypeRelatedTo (/home/dfilatov/www/nmaps/node_modules/typescript/lib/tsc.js:28589:43)
    at recursiveTypeRelatedTo (/home/dfilatov/www/nmaps/node_modules/typescript/lib/tsc.js:28423:53)
    at isIdenticalTo (/home/dfilatov/www/nmaps/node_modules/typescript/lib/tsc.js:28160:28)
    at isRelatedTo (/home/dfilatov/www/nmaps/node_modules/typescript/lib/tsc.js:28080:28)
    at checkTypeRelatedTo (/home/dfilatov/www/nmaps/node_modules/typescript/lib/tsc.js:27990:26)
    at isTypeRelatedTo (/home/dfilatov/www/nmaps/node_modules/typescript/lib/tsc.js:27972:24)
    at isTypeIdenticalTo (/home/dfilatov/www/nmaps/node_modules/typescript/lib/tsc.js:27686:20)
    at fillMissingTypeArguments (/home/dfilatov/www/nmaps/node_modules/typescript/lib/tsc.js:25634:44)
```
**Playground Link:** https://www.typescriptlang.org/play/index.html#src=interface%20FunctionComponent%20%7B%0D%0A%20%20%20%20()%3A%20VElement%3B%0D%0A%7D%0D%0A%0D%0Aclass%20FunctionComponentElement%3C%0D%0A%20%20%20%20TFunctionComponent%20extends%20FunctionComponent%20%3D%20FunctionComponent%0D%0A%3E%20%7B%0D%0A%20%20%20%20readonly%20component%3A%20TFunctionComponent%3B%20%20%0D%0A%7D%0D%0A%0D%0Atype%20VElement%20%3D%20FunctionComponentElement%3B

What's interesting, if I get rid of default value for the generic param `TFunctionComponent`:
```ts
interface FunctionComponent {
    (): VElement;
}

interface FunctionComponentElement<TFunctionComponent extends FunctionComponent> {}

type VElement = FunctionComponentElement<FunctionComponent>;
```
then code will be compiled without any error.

**Comment by sandersn** [comment]
Fix is up at #23950
