### ISSUE TITLE
TS analysis throws exception on ngconf-2015demo solution

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#2317]
I decided to collect sources from https://github.com/Microsoft/ngconfdemo into a solution:
https://www.dropbox.com/s/zvuplcnttmn9dgd/TypeScriptHTMLApp1.zip?dl=0

Fetched the last TS sources from github, compiled, turned VS to DevMode using provided script.
After I open VS with this solution and wait for a while, VS crashes.

Stack trace from Event Viewer:
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.ProjectDataCache.TryGetSourceText(String fileName, SourceText& sourceText)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.JsonHelpers.<>c__DisplayClass37.<ParseDiagnostics>b__38(JToken t)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.JsonHelpers.ParseDiagnostics(String jsonText, Document documentOpt, ProjectDataCache cache)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.LanguageServiceProxy.GetCompilerOptionsDiagnostics(ProjectDataCache project, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Diagnostics.TypeScriptProjectDiagnosticAnalyzer.<>c__DisplayClass0.<AnalyzeProjectAsync>b__1(LanguageServiceProxy proxy, ProjectDataCache cache, ScriptContext context)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.ComputeValue[T](ProjectDataCache cache, LanguageServiceOperation`1 operation)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.<>c__DisplayClass0`1.<PerformOperation>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.<PerformSemanticOperationAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Diagnostics.TypeScriptProjectDiagnosticAnalyzer.<AnalyzeProjectAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerDriver.<GetProjectDiagnosticsWorkerAsync>d__1.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerDriver.CatchAnalyzerException(System.Exception, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer, Boolean)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerDriver+<GetProjectDiagnosticsWorkerAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerDriver+<GetProjectDiagnosticsWorkerAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(System.Exception)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Diagnostics.TypeScriptProjectDiagnosticAnalyzer+<AnalyzeProjectAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(System.Exception)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler+<PerformSemanticOperationAsync>d__1`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by vladima** [comment]
Can you try to install [Visual Studio 2014 CTP6](https://www.visualstudio.com/en-us/news/vs2015-vs.aspx) and see if the problem still exists?

**Comment by zhuravlikjb** [comment]
It's fixed in CTP6, thanks.

**Comment by zhuravlikjb** [comment]
Whoops, I was too fast to close this, sorry.
http://i.imgur.com/Z663A4J.png

**Comment by zhuravlikjb** [comment]
By the way, it's still here, and even on smaller solutions:
http://i.imgur.com/PBq8U9m.png?1

**Comment by mhegazy** [comment]
most of the pieces are either in 1.5 alpha or in master now. we should be updating the ngconf demo soon with more up-to-date bits. if you are still seeing these issues with 1.5 alpha please let us know.

**Comment by mhegazy** [comment]
I have updated the ngconf demo repo with latest from master: https://github.com/Microsoft/ngconf2015demo/pull/21
