### ISSUE TITLE
getCodeFixes: 'Debug failure Changes overlap' in getTextChangesFromChanges

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23235]
**TypeScript Version:**  2.9.0-dev.20180406

**Search Terms:** 
- getCodeFixes
- quick fixes
- code actions
- getTextChangesFromChanges
 
**Code**
For the js:

```js
/**
 * sfasdfafdsa
 */
var Foo = function () {
   this.x= 1;
}

new Foo();
```

Trigger the `Convert to es6 class` code action on `var Foo`

**Bug:**
Error:

```
[Error  - 3:23:29 PM] 'getCodeFixes' request failed with error.
Error processing request. Debug Failure. False expression: Changes overlap
Verbose Debug Information: {"pos":0,"end":63} and {"pos":62,"end":62}
Error: Debug Failure. False expression: Changes overlap
Verbose Debug Information: {"pos":0,"end":63} and {"pos":62,"end":62}
    at _loop_13 (/Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:79038:34)
    at /Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:79043:25
    at Array.map (<anonymous>)
    at Object.getTextChangesFromChanges (/Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:79034:86)
    at ChangeTracker.getChanges (/Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:79026:38)
    at Function.ChangeTracker.with (/Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:78727:32)
    at Object.getCodeActions (/Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:79595:64)
    at /Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:79336:33
    at Object.forEach (/Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:1510:30)
    at Object.getFixes (/Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:79335:16)
    at /Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:85488:35
    at Object.flatMap (/Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:1780:25)
    at Object.getCodeFixesAtPosition (/Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:85486:23)
    at IOSession.Session.getCodeFixes (/Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:92541:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:91395:61)
    at /Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:92708:88
    at IOSession.Session.executeWithRequestId (/Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:92699:28)
    at IOSession.Session.executeCommand (/Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:92708:33)
    at IOSession.Session.onMessage (/Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:92728:35)
    at Interface.<anonymous> (/Users/matb/Downloads/k388w8mmpo/node_modules/typescript/lib/tsserver.js:93937:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by mhegazy** [comment]
@andy-ms can you take a look for 2.8.2
