### ISSUE TITLE
Error: Debug Failure. False expression. in 'unknown' during 'occurrences'

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#23294]
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.8.1
**VSCode Version** 1.19.1
**command requested**: occurrences
**hitting sessions**: 109
**proportion of all sessions**: 0.17384370015948963
**five line hash**: dcb374244976b24ee33485523925d8bf
**stack**
```
Error: Debug Failure. False expression.
    at unknown (tsserver.js:84673:26)
    at Array.map (native)
    at unknown (tsserver.js:84672:133)
    at Object.flatMap (tsserver.js:1772:25)
    at Object.getOccurrencesAtPosition (tsserver.js:84672:23)
    at IOSession.Session.getOccurrences (tsserver.js:91137:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:90743:61)
    at unknown (tsserver.js:92067:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:92058:28)
    at IOSession.Session.executeCommand (tsserver.js:92067:33)
    at IOSession.Session.onMessage (tsserver.js:92087:35)
    at Interface.<anonymous> (tsserver.js:93288:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by DanielRosenwasser** [comment]
What editor that we manage still uses getOccurrences? I'd think we were all on documentHighlights.
