### ISSUE TITLE
Code Does not transpiles

### ISSUE THREAD

**Issue by guptaamol** [Microsoft/TypeScript#23426]
TypeError: Cannot read property '244' of undefined
    at getDeclarationSpaces (/usr/local/lib/node_modules/typescript/lib/tsc.js:35312:52)
    at /usr/local/lib/node_modules/typescript/lib/tsc.js:35304:84
    at Object.forEach (/usr/local/lib/node_modules/typescript/lib/tsc.js:260:30)
    at getDeclarationSpaces (/usr/local/lib/node_modules/typescript/lib/tsc.js:35304:28)
    at checkExportsOnMergedDeclarations (/usr/local/lib/node_modules/typescript/lib/tsc.js:35256:41)
    at checkInterfaceDeclaration (/usr/local/lib/node_modules/typescript/lib/tsc.js:37101:17)
    at checkSourceElement (/usr/local/lib/node_modules/typescript/lib/tsc.js:37865:28)
    at Object.forEach (/usr/local/lib/node_modules/typescript/lib/tsc.js:260:30)
    at checkSourceFileWorker (/usr/local/lib/node_modules/typescript/lib/tsc.js:37975:20)
    at checkSourceFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:37959:13)

**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 
Cannot read property '244' of undefined

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**
 Cannot read property '244' of undefined. The Code Does not transpiles.

**Playground Link:**  

**Related Issues:**

**Comment by MartinJohns** [comment]
Compiles fine here on Windows with version 2.7.2. May I ask why you're still using a dev version of a 2.7.x, when 2.7.2 was released over 2 months ago already?

**Comment by guptaamol** [comment]
Hey hi,
I am new to typescript and trying to learn some new skills.
Was not aware of the new release I do update vs code on a regular basis.
I did update to 2.9.0-dev.
It turns out I had a few botched up imports fixing the same solved the
issue.

**Comment by RyanCavanaugh** [comment]
Duplicate #21928 and others

Pro tip - search for the function name at the top of the call stack as this is more likely to find related issues

**Comment by guptaamol** [comment]
Sure, thanks guys appreciate it.
