### ISSUE TITLE
`gulp runtests` and `jake runtests` fail: `ts is not defined`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#23442]
To reproduce:
* `git pull`
* `git clean -xfd`
* `npm install`
* `gulp runtests` causes:
```
/home/andy/TypeScript_1/TypeScript/scripts/processDiagnosticMessages.js:2
    var sys = ts.sys;
              ^

ReferenceError: ts is not defined
    at main (/home/andy/TypeScript_1/TypeScript/scripts/processDiagnosticMessages.js:2:15)
    at Object.<anonymous> (/home/andy/TypeScript_1/TypeScript/scripts/processDiagnosticMessages.js:86:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```
* `jake runtests` causes an identical stacktrace.

Appears to be due to #23354 -- fails in the merge commit for that. Succeeds (after another `git clean -xfd`) in the merge commit for  #22127. @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
@andy-ms not reproing for me. More info?

**Comment by RyanCavanaugh** [comment]
Specific to `gulp` not `jake` (though running `gulp` first causes `jake` to fail)
