### ISSUE TITLE
TSC compiler 2.8.1 crashes on type casting from loaded JSON file

### ISSUE THREAD

**Issue by sebsto** [Microsoft/TypeScript#23461]
**TypeScript Version:**  2.8.1

**Search Terms:**  2.8.1, 2.8, throw e, "Debug Failure. False expression: Target symbol and symbol do not have the same name" 

**Code**

3 files are needed 

1. json-loader.d.ts

```ts
declare module "*.json" {
    const value: any;
    export default value;
}
```

2. test.json 

```json
{
    "fr-FR" :
    [
        "test"
    ]
}
```

3. test.ts

```ts
interface Test {
    [locale: string] : Array<string>;
}
import * as f from './test.json';
const problem: Test = <Test>f
```

**Expected behavior:**
tsc compiles without error (this is the behaviour with 2.7.x)

**Actual behavior:**
```bash
$ tsc *.ts
/usr/local/lib/node_modules/typescript/lib/tsc.js:61464
                throw e;
                ^

Error: Debug Failure. False expression: Target symbol and symbol do not have the same name
    at getLiteralTypeFromPropertyName (/usr/local/lib/node_modules/typescript/lib/tsc.js:26752:30)
    at eachPropertyRelatedTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:28844:36)
    at indexTypesRelatedTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:28893:36)
    at structuredTypeRelatedTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:28593:51)
    at recursiveTypeRelatedTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:28423:53)
    at isRelatedTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:28139:38)
    at checkTypeRelatedTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:27990:26)
    at checkTypeComparableTo (/usr/local/lib/node_modules/typescript/lib/tsc.js:27717:20)
    at checkAssertionWorker (/usr/local/lib/node_modules/typescript/lib/tsc.js:34558:21)
    at checkAssertion (/usr/local/lib/node_modules/typescript/lib/tsc.js:34549:20)
```

**Playground Link:**  
n/a

**Related Issues:**
n/a

**Comment by j-oliveras** [comment]
Duplicate of #22403?

Seems it will be solved into version 2.8.3. You can try a [nightly build](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md).

In case of compiler crashes, is better search for the name of the name of the last function in call stack.

**Comment by sebsto** [comment]
Works on 2.9.0

```bash
$ ./node_modules/typescript/bin/tsc --version
Version 2.9.0-dev.20180414

$ ./node_modules/typescript/bin/tsc *.ts
$
```

**Comment by RyanCavanaugh** [comment]
@sebsto thanks for testing on latest
