### ISSUE TITLE
ts-node release v6.0.0 breaks local builds

### ISSUE THREAD

**Issue by zombie** [Microsoft/TypeScript#23479]
**Code**

Followed instructions to clone and build locally from the README, and the `gulp local` step throws:

**Actual behavior:**

```
[20:43:24] Requiring external module ts-node/register

D:\git\TypeScript\node_modules\typescript\lib\typescript.js:12525
        return id.length >= 3 && id.charCodeAt(0) === 95 /* _ */ && id.charCodeAt(1) === 95 /* _ */ && id.charCodeAt(2) === 95 /* _ */ ? id.substr(1) : id;
                  ^
TypeError: Cannot read property 'length' of undefined
    at Object.unescapeLeadingUnderscores (D:\git\TypeScript\node_modules\typescript\lib\typescript.js:12525:19)
    at getDisplayName (D:\git\TypeScript\node_modules\typescript\lib\typescript.js:21426:93)
    at D:\git\TypeScript\node_modules\typescript\lib\typescript.js:21519:143
    at Object.forEach (D:\git\TypeScript\node_modules\typescript\lib\typescript.js:1768:30)
    at declareSymbol (D:\git\TypeScript\node_modules\typescript\lib\typescript.js:21518:28)
    at declareModuleMember (D:\git\TypeScript\node_modules\typescript\lib\typescript.js:21569:42)
    at bindBlockScopedDeclaration (D:\git\TypeScript\node_modules\typescript\lib\typescript.js:22743:25)
    at bindClassLikeDeclaration (D:\git\TypeScript\node_modules\typescript\lib\typescript.js:23457:17)
    at bindWorker (D:\git\TypeScript\node_modules\typescript\lib\typescript.js:23117:28)
    at bind (D:\git\TypeScript\node_modules\typescript\lib\typescript.js:22920:13)
```

**Possible Cause**

Looks like `ts-node` switched to type check by default in [v6.0.0 release](/TypeStrong/ts-node/releases/tag/v6.0.0), which is probably wrong for test cases.

**Comment by zombie** [comment]
**Possible Fix**

Affixing `"ts-node": "5.x"` in `package.json` works for me, I can PR that if you think that's good enough as a stop-gap?

**Comment by mhegazy** [comment]
@weswigham thoughts?

**Comment by weswigham** [comment]
I can't repro the issue in the OP...
![image](https://user-images.githubusercontent.com/2932786/38893509-5868e58e-423f-11e8-9d13-a5ad3a427a98.png)
Because I experience a hard crash instead.

**Comment by weswigham** [comment]
You can also work around the issue by setting the `TS_NODE_TRANSPILE_ONLY` environment variable, to get the fast-transpile behavior back.

**Comment by weswigham** [comment]
TBQH, I think this should probably get fixed in the `gulp` register plugin, so that it just always does a fast transpile.
