### ISSUE TITLE
Debug Failure. 248

### ISSUE THREAD

**Issue by 0xDE11A** [Microsoft/TypeScript#23559]
Hi! Sorry, but I cannot find my problem in issues.
Issue was reproduced in typescript@2.8.3, typescript@next and even in typescript@2.6.2!
So, i got this error:

```
~/node_modules/typescript/lib/tsc.js:62157
                throw e;
                ^

Error: Debug Failure. 248
    at getDeclarationSpaces (~/node_modules/typescript/lib/tsc.js:37409:34)
    at ~/node_modules/typescript/lib/tsc.js:37401:84
    at Object.forEach (~/node_modules/typescript/lib/tsc.js:310:30)
    at getDeclarationSpaces (~/node_modules/typescript/lib/tsc.js:37401:28)
    at checkExportsOnMergedDeclarations (~/node_modules/typescript/lib/tsc.js:37351:41)
    at checkVariableLikeDeclaration (~/node_modules/typescript/lib/tsc.js:38265:17)
    at checkVariableDeclaration (~/node_modules/typescript/lib/tsc.js:38298:20)
    at checkSourceElement (~/node_modules/typescript/lib/tsc.js:39969:28)
    at Object.forEach (~/node_modules/typescript/lib/tsc.js:310:30)
    at checkVariableStatement (~/node_modules/typescript/lib/tsc.js:38307:16)

where ~ is long and boring path to project's dir.
```

**Comment by j-oliveras** [comment]
Related to #23426, #21928 and others.

In case of compiler crashes or debug failures, is better search for the name of the top function in call stack.

**Comment by andy-ms** [comment]
@0xDE11A Could you provide sample code that reproduces the error?

**Comment by 0xDE11A** [comment]
@andy-ms, I tried to find out what was going on, but I'm not sure that I did it.
As it seems to me, the failure occurs approximately in such situations:
```typescript
import ConstNameA from 'module-name'

export const ConstNameA = ...
```

**Comment by andy-ms** [comment]
I can't reproduce it with that ... the syntax kind in the error message is for ExportAssignment (do you have `allowSyntheticDefaultImports` or `esModuleInterop` enabled by any chance?), so that must be involved somehow, but I can't find a situation that causes an error in `typescript@next`.

**Comment by 0xDE11A** [comment]
I apologize for the delay. I recreated the error in a simple example and put it in this repository:
https://github.com/0xDE11A/typescript-bug
