### ISSUE TITLE
Crash when using "export *"

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#2383]
```ts
export *;
```

TypeError: Cannot read property 'exports' of undefined
    at visit (c:\ts\built\local\tsc.js:8889:59)
    at c:\ts\built\local\tsc.js:8894:29
    at Object.forEach (c:\ts\built\local\tsc.js:602:30)
    at visit (c:\ts\built\local\tsc.js:8893:28)
    at getExportsForModule (c:\ts\built\local\tsc.js:8880:13)
    at getExportsOfModule (c:\ts\built\local\tsc.js:8860:70)
    at getExportsOfSymbol (c:\ts\built\local\tsc.js:8856:42)
    at resolveAnonymousTypeMembers (c:\ts\built\local\tsc.js:10378:31)
    at resolveObjectOrUnionTypeMembers (c:\ts\built\local\tsc.js:10405:21)
    at getPropertyOfType (c:\ts\built\local\tsc.js:10530:28)

**Comment by mhegazy** [comment]
Can not get it this to repro on latest bits.
