### ISSUE TITLE
Assert failure in forEachIdentifierInEntityName with prototype assignment + prototype property assignment

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#24111]
**TypeScript Version:** master

**Search Terms:** forEachIdentifierInEntityName

**Code**

file1.js
```ts
C.prototype = {};
C.prototype.bar = { };
C.prototype.bar.foo = { };
```

file2.d.ts
```ts
declare class C {
    static x: C;
    bar(): { m: C };
}
```

**Expected behavior:**

**Actual behavior:**
```
C:\github\TypeScript\built\local\tsc.js:4213
            throw e;
            ^

Error: Debug Failure. False expression.
    at forEachIdentifierInEntityName (C:\github\TypeScript\built\local\tsc.js:23034:26)
    at bindPropertyAssignment (C:\github\TypeScript\built\local\tsc.js:22993:17)
    at bindStaticPropertyAssignment (C:\github\TypeScript\built\local\tsc.js:22976:13)
    at bindSpecialPropertyAssignment (C:\github\TypeScript\built\local\tsc.js:22967:17)
    at bindWorker (C:\github\TypeScript\built\local\tsc.js:22645:29)
    at bind (C:\github\TypeScript\built\local\tsc.js:22533:13)
    at visitNode (C:\github\TypeScript\built\local\tsc.js:13972:24)
    at Object.forEachChild (C:\github\TypeScript\built\local\tsc.js:14204:24)
    at bindEachChild (C:\github\TypeScript\built\local\tsc.js:21346:16)
    at bindChildrenWorker (C:\github\TypeScript\built\local\tsc.js:21438:21)
```

**Playground Link:** N/A

**Related Issues:** Another offshoot of #24015

**Comment by sandersn** [comment]
#24367 fixes this assert by substantially simplifying the code in `bindPropertyAssignment`.
