### ISSUE TITLE
Compiler crash when specifying outFile and declaration

### ISSUE THREAD

**Issue by michaelaird** [Microsoft/TypeScript#24199]
**TypeScript Version:**  2.9.0-rc

**Search Terms:** 

getFileReferenceForTypeName
emitSourceFileOrBundle
Cannot read property 'length' of undefined
outFile

**Issue**

Typescript compiler crashes when I specify an outFile

**Expected behavior:**

Build was successful in 2.7.2.

**Actual behavior:**

Build fails with the following stack trace:

> \node_modules\typescript\lib\typescript.js:78638
                throw e;
                ^
TypeError: Cannot read property 'length' of undefined
    at getFileReferenceForTypeName (\node_modules\typescript\lib\typescript.js:71957:90)
    at Object.mapDefined (\node_modules\typescript\lib\typescript.js:2157:30)
    at getFileReferencesForUsedTypeReferences (\node_modules\typescript\lib\typescript.js:71953:52)
    at transformRoot (\node_modules\typescript\lib\typescript.js:71919:50)
    at \node_modules\typescript\lib\typescript.js:3063:42
    at transformRoot (\node_modules\typescript\lib\typescript.js:72974:82)
    at Object.map (\node_modules\typescript\lib\typescript.js:2010:29)
    at Object.transformNodes (\node_modules\typescript\lib\typescript.js:72961:30)
    at emitDeclarationFileOrBundle (\node_modules\typescript\lib\typescript.js:74089:43)
    at emitSourceFileOrBundle (\node_modules\typescript\lib\typescript.js:74035:13)
 The terminal process terminated with exit code: 1

I can share a repro project privately.

**Comment by michaelaird** [comment]
Sent. Let me know if you don't receive it (I attached the repro as a zip file)

**Comment by mhegazy** [comment]
Thanks @michaelaird for sharing the repro. fix should be in the `typescript@next` tomorrow, and in `typescript@2.9.1`.

**Comment by michaelaird** [comment]
Amazing turn around! Thanks for the great work, I'm really looking forward to this release.

**Comment by mhegazy** [comment]
I should calrify, `typescript@2.9.1` will be available in two weeks.

**Comment by michaelaird** [comment]
Understood. Is there any chance of another RC before then?

**Comment by mhegazy** [comment]
no, but there will be `2.9.1-insider` drops coming out regularly.
