### ISSUE TITLE
Assert finding all references on json file import

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#24341]
**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
// settings.json
{
}
```
```ts
// a.ts
import settings from "./settings.json";
settings;
```
```ts
// tsconfig.json

{
    "compilerOptions": {
        "module": "commonjs",
        "resolveJsonModule": true,
        "esModuleInterop": true
    }
}
```
Find all references on settings

**Expected behavior:**

**Actual behavior:**
```txt
[Error  - 3:45:19 PM] 'references' request failed with error.
Error processing request. Debug Failure.
Error: Debug Failure.
    at getExportEqualsLocalSymbol (C:\ls\tsserver.js:90311:29)
    at getImport (C:\ls\tsserver.js:90280:38)
    at Object.getImportOrExportSymbol (C:\ls\tsserver.js:90193:68)
    at getImportOrExportReferences (C:\ls\tsserver.js:91221:56)
    at getReferencesAtLocation (C:\ls\tsserver.js:91156:17)
    at getReferencesInContainer (C:\ls\tsserver.js:91100:21)
    at getReferencedSymbolsForSymbol (C:\ls\tsserver.js:90703:25)
    at Object.getReferencedSymbolsForNode (C:\ls\tsserver.js:90616:57)
    at Object.findReferencedEntries (C:\ls\tsserver.js:90443:65)
    at getReferences (C:\ls\tsserver.js:107412:41)
    at Object.getReferencesAtPosition (C:\ls\tsserver.js:107395:20)
    at C:\ls\tsserver.js:114770:71
    at C:\ls\tsserver.js:113857:124
    at Object.flatMap (C:\ls\tsserver.js:2078:25)
    at combineProjectOutput (C:\ls\tsserver.js:113857:30)
    at IOSession.Session.getReferences (C:\ls\tsserver.js:114769:32)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\ls\tsserver.js:113943:61)
    at C:\ls\tsserver.js:115521:88
    at IOSession.Session.executeWithRequestId (C:\ls\tsserver.js:115512:28)
    at IOSession.Session.executeCommand (C:\ls\tsserver.js:115521:33)
    at IOSession.Session.onMessage (C:\ls\tsserver.js:115541:35)
    at Interface.<anonymous> (C:\ls\tsserver.js:116800:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```
**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
@sheetalkamat can you take a look.
