### ISSUE TITLE
In JS, crash on incorrect type reference of a module.exports property assignment

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#24492]
```js
module.exports.D = class { }
new D()
```

**Expected behavior:**
Can't find name 'D'

**Actual behavior:**
Crash:

```
TypeError: Cannot read property 'flags' of undefined
    at resolveNameHelper (/home/nathansa/ts/built/local/tsc.js:27869:45)
    at resolveName (/home/nathansa/ts/built/local/tsc.js:27559:20)
    at getResolvedSymbol (/home/nathansa/ts/built/local/tsc.js:38384:21)
    at checkIdentifier (/home/nathansa/ts/built/local/tsc.js:39700:26)
    at checkExpressionWorker (/home/nathansa/ts/built/local/tsc.js:45551:28)
    at checkExpression (/home/nathansa/ts/built/local/tsc.js:45523:42)
    at checkNonNullExpression (/home/nathansa/ts/built/local/tsc.js:42188:37)
    at resolveNewExpression (/home/nathansa/ts/built/local/tsc.js:43635:34)
    at resolveSignature (/home/nathansa/ts/built/local/tsc.js:43855:28)
    at getResolvedSignature (/home/nathansa/ts/built/local/tsc.js:43896:26)
```

**Comment by mhegazy** [comment]
@sandersn does this happen in 2.9.1 as well?

**Comment by sandersn** [comment]
Yes, the bug happens in a combination of resolveName code for handling ModuleExports and then issuing errors for block-scoped variables.

It doesn't repro in 2.8 though.

**Comment by sandersn** [comment]
Introduced in #23152 probably

**Comment by sandersn** [comment]
Well, never mind, that change made the erronous line MORE restrictive, not less. Probably the reason this succeeds in 2.8 is that `module.exports.D=` binding was not fully functional at that point.
