### ISSUE TITLE
Move-to-File throws when the originating file is in multiple projects

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#24613]
```
Err 1550  [10:37:48.785] Exception on executing command {"seq":179,"type":"request","command":"getEditsForRefactor","arguments":{"file":"c:/Users/acasey/source/repos/NodejsConsoleApp57/NodejsConsoleApp57/a.ts","startLine":3,"startOffset":1,"endLine":5,"endOffset":2,"refactor":"Move to a new file","action":"Move to a new file"}}:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
    at IOSession.Session.mapTextChangesToCodeEditsUsingScriptinfo (E:\ts_gh\built\local\tsserver.js:115839:26)
    at E:\ts_gh\built\local\tsserver.js:115835:73
    at Array.map (native)
    at IOSession.Session.mapTextChangesToCodeEdits (E:\ts_gh\built\local\tsserver.js:115835:36)
    at IOSession.Session.getEditsForRefactor (E:\ts_gh\built\local\tsserver.js:115751:112)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (E:\ts_gh\built\local\tsserver.js:114587:61)
    at E:\ts_gh\built\local\tsserver.js:115960:88
    at IOSession.Session.executeWithRequestId (E:\ts_gh\built\local\tsserver.js:115951:28)
    at IOSession.Session.executeCommand (E:\ts_gh\built\local\tsserver.js:115960:33)
    at IOSession.Session.onMessage (E:\ts_gh\built\local\tsserver.js:115980:35)
    at Interface.<anonymous> (E:\ts_gh\built\local\tsserver.js:117241:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by amcasey** [comment]
My setup was roughly:
./a.ts
./tsconfig.json with a.ts in files
./other/tsconfig.json with ../a.ts in files
