### ISSUE TITLE
Unexpected token, expected ";" in correct code

### ISSUE THREAD

**Issue by CloudRex** [Microsoft/TypeScript#24676]
**TypeScript Version:**  2.9.1

**Search Terms:** 

**Code**

```ts
import {NetworkListenerEvent} from "../listeners/network-listener";

export enum NetworkControllerEnvironment {
    Unicast,
    Multicast,
    Broadcast,
    All
}

export default interface NetworkController {
    readonly endpoint: string;
    readonly environment: NetworkControllerEnvironment;
    readonly handle: (event: NetworkListenerEvent) => void;
}
```

**Expected behavior:**
compile successfully without error

**Actual behavior:**
compilation fails

**Playground Link:**  

**Related Issues:** 

Stack trace:

```$ tsc --emitDeclarationOnly && babel src --out-dir lib --extensions ".ts,.tsx"
{ SyntaxError: D:\Projects\local-network\src\core\network-controller.ts: Unexpected token, expected ";" (10:25)

   8 | }
   9 |
> 10 | export default interface NetworkController {
     |                          ^
  11 |     readonly endpoint: string;
  12 |     readonly environment: NetworkControllerEnvironment;
  13 |     readonly handle: (event: NetworkListenerEvent) => void;
    at _class.raise (D:\Projects\local-network\node_modules\@babel\parser\lib\index.js:3861:15)
    at _class.unexpected (D:\Projects\local-network\node_modules\@babel\parser\lib\index.js:5190:16)
...
```

**Comment by mhegazy** [comment]
What version of the compiler are you using? my guess is you are using an older compiler version.

**Comment by CloudRex** [comment]
I wrote v2.9.1 in the top (output of tsc -v), if that's not the compiler version, how would I find it?

**Comment by mhegazy** [comment]
Sorry, did not notice the babel stack. this should be filed under https://github.com/babel/babel/issues
