### ISSUE TITLE
runtests-browser cause heap out of memory error

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#24697]
**TypeScript Version:**  master

**Code**

```
gulp runtests-browser
```

**Expected behavior:**

Not to crash

**Actual behavior:**

```
Saving sourcemaps for /home/andy/TypeScript_1/TypeScript/built/local/bundle.js
Fixing sourcemaps for /home/andy/TypeScript_1/TypeScript/built/local/bundle.js

<--- Last few GCs --->

[20271:0x2d46180]   101105 ms: Mark-sweep 1363.0 (1447.8) -> 1363.0 (1447.8) MB, 798.2 / 0.0 ms  allocation failure GC in old space requested
[20271:0x2d46180]   101788 ms: Mark-sweep 1363.0 (1447.8) -> 1363.0 (1431.8) MB, 683.1 / 0.0 ms  last resort GC in old space requested
[20271:0x2d46180]   102440 ms: Mark-sweep 1363.0 (1431.8) -> 1363.0 (1431.8) MB, 651.8 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xe3b2ec0427d]
Security context: 0x7ee065206a9 <JSObject>
    1: apply [/home/andy/TypeScript_1/TypeScript/node_modules/sorcery/dist/sorcery.cjs.js:~543] [pc=0xe3b2fa1a764](this=0x1313fed2bc1 <Chain map = 0x1189be8cd111>,options=0x4ae2bf022e1 <undefined>)
    2: arguments adaptor frame: 0->1
    3: /* anonymous */ [/home/andy/TypeScript_1/TypeScript/Gulpfile.js:841] [bytecode=0x250c53542c39 offset=359](this=0x143bd38...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [gulp]
 2: 0x876afc [gulp]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [gulp]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [gulp]
 5: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [gulp]
 6: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
 7: 0xe3b2ec0427d
Aborted (core dumped)
```

**Comment by andy-ms** [comment]
@rbuckton this was working in the commit before #23893 (c43740476367f044d4b1848cde525831f0f030cf)

**Comment by andy-ms** [comment]
`gulp` no longer works at all, but `jake runtests-browser` now fails immediately with no message:
```
> jake runtests-browser
jake aborted.
Error: Process exited with code 1
    at api.fail (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/jake/lib/api.js:336:18)
    at Exec.<anonymous> (/home/andy/TypeScript_1/TypeScript/Jakefile.js:749:13)
(See full trace by running task with --trace)
```

CC @RyanCavanaugh

**Comment by sheetalkamat** [comment]
@andy-ms You might want to use to debug in the mean time
```
node --inspect-brk node_modules\mocha\bin\_mocha -R mocha-fivemat-progress-reporter -g "sometest" --colors -t 40000 built\local\run.js
```

**Comment by weswigham** [comment]
@andy-ms @rbuckton has been working on a patched `gulp-typescript` that works with project references; hopefully it'll be good to use soon.

**Comment by andy-ms** [comment]
@sheetalkamat Thanks, but I've noticed a lot of segfaults / illegal instruction errors when running that -- running through a browser seems to be a lot more reliable. Hopefully we get  `gulp runtests-browser` working again soon (looks like that task was deleted from the jakefile).

**Comment by RyanCavanaugh** [comment]
`runtests-browser` was not carried forward to `gulp`
