### ISSUE TITLE
Move file: getEditsForRefactor debug failure in mapTextChangesToCodeEditsUsingScriptinfo

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24757]
From https://github.com/Microsoft/vscode/issues/51366

**TypeScript Version:**  3.0.0-dev.20180607

**Search Terms:** 
- move file refactoring
- getEditsForRefactor

**Code**
1. Clone https://github.com/ivanvoznyakovsky/ts-refactoring-issue
1. Open `service1.ts`
1. Try running `move to new file` on `Service2` in the file

**Bug**

```
[Trace  - 10:27:08 AM] Response received: getEditsForRefactor (103). Request took 33 ms. Success: false . Message: Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at IOSession.Session.mapTextChangesToCodeEditsUsingScriptinfo (/Users/matb/projects/scratch/ts-refactoring-issue/node_modules/typescript/lib/tsserver.js:97967:26)
    at /Users/matb/projects/scratch/ts-refactoring-issue/node_modules/typescript/lib/tsserver.js:97963:73
    at Array.map (native)
    at IOSession.Session.mapTextChangesToCodeEdits (/Users/matb/projects/scratch/ts-refactoring-issue/node_modules/typescript/lib/tsserver.js:97963:36)
    at IOSession.Session.getEditsForRefactor (/Users/matb/projects/scratch/ts-refactoring-issue/node_modules/typescript/lib/tsserver.js:97880:112)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/projects/scratch/ts-refactoring-issue/node_modules/typescript/lib/tsserver.js:96757:61)
    at /Users/matb/projects/scratch/ts-refactoring-issue/node_modules/typescript/lib/tsserver.js:98084:88
    at IOSession.Session.executeWithRequestId (/Users/matb/projects/scratch/ts-refactoring-issue/node_modules/typescript/lib/tsserver.js:98075:28)
    at IOSession.Session.executeCommand (/Users/matb/projects/scratch/ts-refactoring-issue/node_modules/typescript/lib/tsserver.js:98084:33)
    at IOSession.Session.onMessage (/Users/matb/projects/scratch/ts-refactoring-issue/node_modules/typescript/lib/tsserver.js:98104:35)
    at Interface.<anonymous> (/Users/matb/projects/scratch/ts-refactoring-issue/node_modules/typescript/lib/tsserver.js:99310:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/24613.

**Comment by mjbvz** [comment]
Yep, thanks
