### ISSUE TITLE
Question: Compiler API reject my node (Token end is child end; Node must have a real position for this operation)

### ISSUE THREAD

**Issue by Jack-Works** [Microsoft/TypeScript#24751]
I make some changes to the AST and I'm getting textChange back, but I get this.
```
Error: Debug Failure. False expression: Token end is child end
      at processChildNode (built\local\run.js:98799:34)
      ...... ignore some irrelavant details.
      at ChangeTracker.getChanges (built\local\run.js:100405:45)
      at transformComponentToSFC (https://github.com/Microsoft/TypeScript/pull/24518/files#diff-195c9482ed99d46952200f9fed3bffb4R273)
```

And If I ignore this assert, I get this

```
     Error: Debug Failure. False expression: Node must have a real position for this operation
      at NodeObject.assertHasRealPosition (built\local\run.js:107509:22)
      at NodeObject.getStart (built\local\run.js:107515:18)
      at processChildNode (built\local\run.js:98759:47)
      ......
      at Object.getTextChangesFromChanges (built\local\run.js:100428:86)
      at ChangeTracker.getChanges (built\local\run.js:100405:45)
      at transformComponentToSFC (https://github.com/Microsoft/TypeScript/pull/24518/files#diff-195c9482ed99d46952200f9fed3bffb4R273)
```

The code fails at `changeTracker.getChanges()`, ( https://github.com/Microsoft/TypeScript/pull/24518/files#diff-195c9482ed99d46952200f9fed3bffb4R344 ), and by the second Error, it seemed I've got some node wrong. But I can't figure out which node is corrupted.

**Comment by mhegazy** [comment]
@andy-ms can you help answering this one.

**Comment by tavurth** [comment]
Having this issue now also.

**Comment by Kingwl** [comment]
It's usually caused by overlap text range when you are editing. (Includes replace between child node and parent node).

There's some workaround(hijack the textChanges api and drop some changes, and than do the next round), but It' might should be done case by case.

**Comment by tavurth** [comment]
For me it seemed to be because I had a class without a type, which had public methods returning a type

```ts
interface SomeType<T> {}

class MyClass {
  myMethod<T>(): SomeType<T> {}
}
```

Removing the types fixes this  🤷
