### ISSUE TITLE
"rename file" and "move to new file" refactors do not work when using `files`

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#24857]
**TypeScript Version:**  2.9.1

**Search Terms:** 
files "move to new file" "rename file"

**Code**

```json
// tsconfig.json
{
  "files": ["./src/index.ts"]
}
```

``` ts
// ./src/index.ts
import foo from './other';
```

``` ts
// ./src/other.ts
export default {}

const bar = {};
```

**Expected behavior:**
- When renaming the file `./src/other.ts`, I expect TypeScript/VSCode to prompt me to update the import in `./src/index.ts`.
- When selecting `bar` in `./src/other.ts`, TypeScript/VSCode offers to move this to a new file. When actioning this, I expect this to work.

(TypeScript knows that `./src/other.ts` is in the project because it is part of the traced dependency graph from the entry file `./src/index.ts`.)

**Actual behavior:**
- When renaming the file `./src/other.ts`, there is no prompt to update the import.
- When selecting `bar` in `./src/other.ts`, TypeScript/VSCode offers to move this to a new file. When actioning this, nothing happens.

**Playground Link:**  

**Related Issues:** 
https://github.com/Microsoft/vscode/issues/51366
https://github.com/Microsoft/TypeScript/pull/23573
https://github.com/Microsoft/TypeScript/pull/23726

---

A known workaround is to use the `include` option instead of `files`. However, I am curious why this is necessary. I prefer to list the entry file and let TypeScript work the rest out. This is especially helpful when a folder has a combination of source and test files—TypeScript automatically knows not to include the test files because they are not part of the dependency graph.

If there is a good reason why these commands/refactors can't work with `files`, could we make the experience clearer? Why is the "move to new file" command suggested in VSCode when it leads to nothing? If so, perhaps this is an issue for VSCode.

**Comment by mhegazy** [comment]
Can you share the log from your tsserver? i suspect it is a duplicate of https://github.com/Microsoft/TypeScript/issues/24613

**Comment by OliverJAsh** [comment]
@mhegazy Does this help? [tsserver.log](https://github.com/Microsoft/TypeScript/files/2093558/tsserver.log)

**Comment by mhegazy** [comment]
This looks different.

**Comment by sheetalkamat** [comment]
@mjbvz this seems like there are 2 open requests on same file. Can you check why? We do not expect open on same file without closing it first. Thats the assert that raised error [in the log](https://github.com/Microsoft/TypeScript/files/2093558/tsserver.log).
Interesting open requests:
```
Info 7    [11:4:3.833] request:
    {"seq":0,"type":"request","command":"open","arguments":{"file":"/Users/OliverJAsh/Development/temp/typescript-files-refactors-test/src/index.ts","fileContent":"// ./src/index.ts\nimport foo from './other';"}}

nfo 52   [11:4:7.163] request:
    {"seq":6,"type":"request","command":"open","arguments":{"file":"/Users/OliverJAsh/Development/temp/typescript-files-refactors-test/src/index.ts","fileContent":"// ./src/index.ts\nimport foo from './other';","scriptKindName":"TS","projectRootPath":"/Users/OliverJAsh/Development/temp/typescript-files-refactors-test"}}
```

**Comment by mjbvz** [comment]
@OliverJAsh Can you please try collecting the TS Server log again in the latest VS Code insiders build. I made some changes to how we track opened files and haven't been able to reproduce the duplicate open requests in recent VS Code builds

**Comment by OliverJAsh** [comment]
@mjbvz In this log I attempt to use the "move to new file" command as described in my original post. 
[tsserver.log](https://github.com/Microsoft/TypeScript/files/2144655/tsserver.log)

@mjbvz Are you able to reproduce the issue as I described?

**Comment by mhegazy** [comment]
@OliverJAsh looks like this log is using `typescript@2.9.1` can you try with `typescript@next`?

**Comment by sheetalkamat** [comment]
@OliverJAsh The error you are seeing in the log, i think is fixed by #24613. Please try typescript@next and let us know if you still see the issue. Thank you.

**Comment by OliverJAsh** [comment]
I can still reproduce this issue using Code Insiders with `@next`. Attached logs. 
[tsserver.log](https://github.com/Microsoft/TypeScript/files/2156571/tsserver.log)

**Comment by OliverJAsh** [comment]
> Selecting and moving const bar = {}; to new file does create bar.ts and if files entry is present it adds to it.

This doesn't match the behaviour I'm seeing. When I create to move it to a new file, nothing happens. I've attached a TS server log in which I try to do this. 
[tsserver.log](https://github.com/Microsoft/TypeScript/files/2158270/tsserver.log)

**Comment by sheetalkamat** [comment]
@andy-ms Can you please take a look. The tsserver log shows assert:
```
Err 265   [9:10:53.930] Exception on executing command {"seq":41,"type":"request","command":"getEditsForRefactor","arguments":{"file":"/Users/OliverJAsh/Development/typescript-playground/src/other.ts","startLine":4,"startOffset":1,"endLine":4,"endOffset":16,"refactor":"Move to a new file","action":"Move to a new file"}}:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
    at mapTextChangesToCodeEdits (/Users/OliverJAsh/Development/typescript-playground/node_modules/typescript/lib/tsserver.js:118361:22)
    at IOSession.Session.mapTextChangeToCodeEdit (/Users/OliverJAsh/Development/typescript-playground/node_modules/typescript/lib/tsserver.js:118197:24)
    at /Users/OliverJAsh/Development/typescript-playground/node_modules/typescript/lib/tsserver.js:118192:73
    at Array.map (native)
    at IOSession.Session.mapTextChangesToCodeEdits (/Users/OliverJAsh/Development/typescript-playground/node_modules/typescript/lib/tsserver.js:118192:36)
    at IOSession.Session.getEditsForRefactor (/Users/OliverJAsh/Development/typescript-playground/node_modules/typescript/lib/tsserver.js:118092:112)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/OliverJAsh/Development/typescript-playground/node_modules/typescript/lib/tsserver.js:116962:61)
    at /Users/OliverJAsh/Development/typescript-playground/node_modules/typescript/lib/tsserver.js:118299:88
    at IOSession.Session.executeWithRequestId (/Users/OliverJAsh/Development/typescript-playground/node_modules/typescript/lib/tsserver.js:118290:28)
    at IOSession.Session.executeCommand (/Users/OliverJAsh/Development/typescript-playground/node_modules/typescript/lib/tsserver.js:118299:33)
    at IOSession.Session.onMessage (/Users/OliverJAsh/Development/typescript-playground/node_modules/typescript/lib/tsserver.js:118319:35)
    at Interface.<anonymous> (/Users/OliverJAsh/Development/typescript-playground/node_modules/typescript/lib/tsserver.js:119574:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by andy-ms** [comment]
I can't reproduce the assert, but I have noticed that sometimes there is no change. I have noticed that renaming `other.ts` sometimes produces no change, probably because it is in its own project. We need to aggregate results from all projects like in #25283.

**Comment by OliverJAsh** [comment]
> We need to aggregate results from all projects like in #25283.

Unrelated, but will this address https://github.com/Microsoft/TypeScript/issues/20185?

**Comment by mhegazy** [comment]
no.

**Comment by andy-ms** [comment]
@OliverJAsh Could you test again now that #25522 is in?

**Comment by OliverJAsh** [comment]
@andy-ms Unfortunately not 
[tsserver.log](https://github.com/Microsoft/TypeScript/files/2183704/tsserver.log)

**Comment by andy-ms** [comment]
Fixed by #25586.

**Comment by OliverJAsh** [comment]
I can still reproduce with the latest `next` (3.0.0-dev.20180712) and `rc` (3.0.0-rc), although not sure if this fixed made it into either of those releases?

**Comment by andy-ms** [comment]
@OliverJAsh The fix should indeed be in `@next`. Are you still seeing `Error: Debug Failure. False expression.` in the logs?

**Comment by OliverJAsh** [comment]
I believe so [tsserver.log](https://github.com/Microsoft/TypeScript/files/2198600/tsserver.log)

**Comment by andy-ms** [comment]
That may be #25623, let's see if that fixes it.

**Comment by OliverJAsh** [comment]
Mind if we reopen?

**Comment by OliverJAsh** [comment]
I still can reproduce with 3.1.0-dev.20180721

[tsserver.log](https://github.com/Microsoft/TypeScript/files/2219115/tsserver.log)

**Comment by andy-ms** [comment]
I can reproduce the issue if I open `other.ts` but not `index.ts`. That way the project in `tsconfig.json` is never opened and we don't update it. So this may be #25867.

**Comment by OliverJAsh** [comment]
I am opening Code, then opening `index.ts`, and then navigating to `other.ts` via the import (go to reference).

**Comment by andy-ms** [comment]
Could you try adding this to your vscode settings?
```json
"workbench.editor.enablePreview": false,
```

Without that, vscode may automatically be closing `index.ts` when you navigate to `other.ts`.

**Comment by OliverJAsh** [comment]
That does fix the issue with "rename file", but "move to new file" still does not work.

**Comment by andy-ms** [comment]
@OliverJAsh Is that with `typescript@next`? What operating system are you on?

In `session.ts` there is `JSON.stringify({ isNewFile: !!textChanges.isNewFile, hasScriptInfo: !!scriptInfo })` for printing debug info. 
For privacy reasons we can't include the file path in an error message. But maybe you could change it to `JSON.stringify({ isNewFile: !!textChanges.isNewFile, hasScriptInfo: !!scriptInfo, fileName: textChanges.fileName }))`; and build locally and test against that?

**Comment by OliverJAsh** [comment]
> Is that with typescript@next?

Yes. Just tried with 3.1.0-dev.20180801.



> What operating system are you on?

macOS 10.13.5.

> build locally and test against that

I'm not completely familiar with how to do that. Is there a guide somewhere I can follow?

@andy-ms Are you able to reproduce the problem on your end?

**Comment by rosieks** [comment]
I'm trying to use move to new file in JavaScript but it doesn't work (no proposition to move function to another file). Should it work in JavaScript or only in TypeScript? I have created new projected using React +Redux template from ASP.NET Core 2.1

**Comment by andy-ms** [comment]
@rosieks Please make a new issue. It should work in JavaScript. Be sure to test with `typescript@next`.

**Comment by rosieks** [comment]
Ok - I will create separate issue - could you just tell me where should I have `typescript@next` and my projects doesn't have typescript at all - I'm using VS 15.8.1

**Comment by minestarks** [comment]
@rosieks move to file isn't yet supported in Visual Studio 15.8, so unfortunately even a new build of TypeScript won't help you in this case. We're working on adding VS support for this soon.

**Comment by sheetalkamat** [comment]
@OliverJAsh Sorry for getting back but can you please try your repro with typescript@next and see if it repros. Providing log if it repros will help. Thanks.

**Comment by OliverJAsh** [comment]
Testing "move to new file", unfortunately that doesn't seem to help.

[tsserver.log](https://github.com/Microsoft/TypeScript/files/2729560/tsserver.log)

**Comment by sheetalkamat** [comment]
@OliverJAsh Thank you for the log. Will investigate.

**Comment by OliverJAsh** [comment]
It fixes the problem! One small thing though: it adds the new file to `files` even though it doesn't need to be if (when it's included via the dependency graph of existing `files`).

**Comment by sheetalkamat** [comment]
@OliverJAsh can you please share tsserver log where your newFile gets added to the files list? I don't see that when I do it with typescript@next
