### ISSUE TITLE
Crash with project references: TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#24864]
**TypeScript Version:**  3.0.0-dev.20180609

**Code**

Checkout https://github.com/RyanCavanaugh/project-references-outfile and run `tsc`.

**Expected behavior:**

No crash.

**Actual behavior:**

```
TypeError: Cannot read property 'push' of undefined
    at findSourceFile (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:64602:42)
    at /home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:64483:85
    at getSourceFileFromReferenceWorker (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:64451:34)
    at processSourceFile (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:64483:13)
    at /home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:64624:17
    at Object.forEach (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:324:30)
    at processReferencedFiles (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:64622:16)
    at findSourceFile (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:64593:21)
    at /home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:64483:85
    at getSourceFileFromReferenceWorker (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/typescript/lib/tsc.js:64451:34)
```

@RyanCavanaugh

**Comment by andy-ms** [comment]
Yep, fixed in `master`. Verified that I could still reproduce it with `3.0.0-dev.20180609`.
