### ISSUE TITLE
TS Server errors for javascript containing invalid jsdoc type

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24913]
From https://github.com/Microsoft/vscode/issues/51626#issuecomment-396723426

**TypeScript Version:**  3.0.0-dev.20180609

**Search Terms:** 
- jsdoc

**Code**
For the js:

```ts
/**
 * @param {<Array<number>} arr
 */
function foo(arr) {} 
```

**Bug**
Notice a lot of TS Server request start failing now:

```
[Error  - 2:45:30 PM] 'getCodeFixes' request failed with error.
Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at tryDeleteIdentifier (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:86017:34)
    at tryDeleteDeclaration (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:85971:21)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:85864:97
    at Function.ChangeTracker.with (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:83381:17)
    at Object.getCodeActions (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:85864:65)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:84065:121
    at Object.flatMap (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:1820:25)
    at Object.getFixes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:84065:23)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:91271:35
    at Object.flatMap (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:1820:25)
    at Object.getCodeFixesAtPosition (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:91269:23)
    at IOSession.Session.getCodeFixes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:97969:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:96793:61)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:98126:88
    at IOSession.Session.executeWithRequestId (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:98117:28)
    at IOSession.Session.executeCommand (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:98126:33)
    at IOSession.Session.onMessage (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:98146:35)
    at Interface.<anonymous> (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:99377:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by andy-ms** [comment]
I've reproduced this:
```ts
/// <reference path='fourslash.ts' />

// @allowJs: true

// @Filename: /a.js
/////**
//// * @param {<Array<number>} arr
//// */
////function foo(arr) {}

verify.codeFix({
    index: 1,
    description: "Remove declaration for: 'arr'",
    newFileContent:
`???`,
});
```

This only reproduces this way in recent builds, so I can't fix this now due to #24697.
