### ISSUE TITLE
tsc crashes when a .js file uses `export.modules = {...}` and `export function...`

### ISSUE THREAD

**Issue by dimfeld** [Microsoft/TypeScript#24934]
The Typescript compiler crashes when a .js file exports functions like below and then something attempts to import and call the function. The JS code is likely invalid since it's mixing module export styles so I don't see this as a high priority.

**Code**

```ts
file_1.js: 
export function abc(a, b, c) { return 5; }
module.exports = { abc };

file_2.js:
import { abc } from './file_1';
abc(1, 2, 3);
```

The bug doesn't occur if any of the following are true:

* One or both of the files are `.ts` files.
* `import * as f from './file_1'; f.abc(1,2 ,3);` is used instead.
* Either of the redundant export statements is removed.

I'm not sure if it matters for this case, but my tsconfig.json can be found in the Gist linked at the bottom.

**Expected behavior:**

Either compile normally like TS 2.8 did, or maybe emit an error since exporting in both ES6 fashion and CommonJS fashion from a single file isn't really valid.

**Actual behavior:**

Typescript crashes:

```
/usr/local/lib/node_modules/typescript/lib/tsc.js:64086
                throw e;
                ^

TypeError: Cannot read property 'kind' of undefined
    at getRootDeclaration (/usr/local/lib/node_modules/typescript/lib/tsc.js:8617:21)
    at Object.isCatchClauseVariableDeclarationOrBindingElement (/usr/local/lib/node_modules/typescript/lib/tsc.js:6862:20)
    at getTypeOfVariableOrParameterOrProperty (/usr/local/lib/node_modules/typescript/lib/tsc.js:25422:24)
    at getTypeOfSymbol (/usr/local/lib/node_modules/typescript/lib/tsc.js:25657:24)
    at getTypeOfAlias (/usr/local/lib/node_modules/typescript/lib/tsc.js:25612:23)
    at getTypeOfSymbol (/usr/local/lib/node_modules/typescript/lib/tsc.js:25669:24)
    at checkIdentifier (/usr/local/lib/node_modules/typescript/lib/tsc.js:33221:49)
    at checkExpressionWorker (/usr/local/lib/node_modules/typescript/lib/tsc.js:37803:28)
    at checkExpression (/usr/local/lib/node_modules/typescript/lib/tsc.js:37779:42)
    at checkNonNullExpression (/usr/local/lib/node_modules/typescript/lib/tsc.js:35117:37)
```

**Playground Link:** 

Since this needs multiple files to reproduce, I don't think I could use the TS playground, but I've posted a small project here that will reproduce it: https://gist.github.com/dimfeld/8acaa89e17de3028cb69d6c75ae39bb3

**Related Issues:**
I was tracking https://github.com/Microsoft/TypeScript/issues/24565 since the error message was similar, but this appears to have a different root cause.

**Comment by sandersn** [comment]
The problem is that the symbol doesn't have a value declaration, but the `module.exports` assignment adds flags that make the checker think that it does. The binder should check whether it's in a ES2015 module before binding any commonjs `module.exports` assignments.
