### ISSUE TITLE
TSServer slow when editing a webpacked file

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24999]
From https://github.com/Microsoft/vscode/issues/51361

**TypeScript Version:**  3.0.0-dev.20180609

**Search Terms:** 

**Code**
Open this file in VS Code: [index.js.txt](https://github.com/Microsoft/TypeScript/files/2107199/index.js.txt)

**Bug:**
Intellisense stops working properly

Possible root cause is a `getJSDocTags`:

```
Err 463   [11:54:25.865] Exception on executing command delayed processing of request 15:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
    at getJSDocTags (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:11705:22)
    at getFirstJSDocTag (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:11712:24)
    at Object.getJSDocType (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:11689:19)
    at getContextualSignature (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:35577:32)
    at checkFunctionExpressionOrObjectLiteralMethod (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:38366:43)
    at checkExpressionWorker (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:39292:28)
    at checkExpression (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:39225:42)
    at checkBinaryLikeExpression (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:38839:29)
    at checkBinaryExpression (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:38831:20)
    at checkExpressionWorker (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:39313:28)
    at checkExpression (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:39225:42)
    at checkExpressionCached (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:39111:38)
    at getTypeOfExpression (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:39207:28)
    at checkDeclarationInitializer (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:39122:24)
    at getTypeForVariableLikeDeclaration (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:26638:28)
    at getWidenedTypeForVariableLikeDeclaration (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:26829:24)
    at getTypeOfVariableOrParameterOrProperty (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:26918:28)
    at getTypeOfSymbol (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:27103:24)
    at checkVariableLikeDeclaration (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:41092:41)
    at checkVariableDeclaration (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:41149:20)
    at checkSourceElement (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:42841:28)
    at Object.forEach (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:1541:30)
    at checkVariableStatement (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:41158:16)
    at checkSourceElement (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:42810:28)
    at Object.forEach (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:1541:30)
    at checkBlock (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:40853:20)
    at checkSourceElement (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:42808:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:38409:21)
    at checkDeferredNodes (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:42935:25)
    at checkSourceFileWorker (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:42977:17)
    at checkSourceFile (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:42949:13)
    at Object.getSuggestionDiagnostics (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:23134:21)
    at /Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:65776:61
    at runWithCancellationToken (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:65732:24)
    at Object.getSuggestionDiagnostics (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:65775:20)
    at Object.computeSuggestionDiagnostics (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:80302:36)
    at Object.getSuggestionDiagnostics (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:90856:23)
    at IOSession.Session.suggestionCheck (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:96975:87)
    at /Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:97020:39
    at MultistepOperation.executeAction (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:96480:25)
    at /Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:96461:100
    at IOSession.Session.executeWithRequestId (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:98117:28)
    at Object.executeWithRequestId (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:96846:87)
    at Immediate.<anonymous> (/Users/matb/Downloads/interface-example/node_modules/typescript/lib/tsserver.js:96461:41)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by sheetalkamat** [comment]
@sandersn can you please take a look

**Comment by sandersn** [comment]
#24973 should have fixed this yesterday. 

However, I can't get this assert to repro to confirm whether it's fixed. @mjbvz do you mind trying with a newer build of typescript? We don't have an up-to-date typescript@next, but I can update this issue when we fix that problem.

**Comment by sandersn** [comment]
Does this assert (and the previous assert) occur with a call to tsc? I guess that it should but I could be wrong.

**Comment by sandersn** [comment]
Also, the assert happens when merging module augmentations, which means that the program has (or the compiler thinks it has) syntax like `declare module "foo" { ... }` or `declare global { ... }`. This seems unlikely for a JS file -- maybe you have some typescript?

**Comment by mjbvz** [comment]
Upgraded to 3.0@201806016. Fixed the assertion failures and errors it seems but I still see this file causing problems

**Comment by sandersn** [comment]
What kind of problems?

**Comment by mjbvz** [comment]
Mainly that requests take a long to process, especially after any file edits

**Comment by sandersn** [comment]
Do you mind sending the server logs exhibiting the slowness? When I compile, I see compile times around 2 1/2 seconds, and responsiveness in emacs is not great but feels like it's less than a second to produce quick info, parameter help, etc.

**Comment by mjbvz** [comment]
Log from VS Code with 3.0.0-201806016 
[tsserver.log.zip](https://github.com/Microsoft/TypeScript/files/2116382/tsserver.log.zip)

I believe the problem is the absurdly large navtree response

**Comment by mhegazy** [comment]
@andy-ms can you take a look at the navtree issue..
