### ISSUE TITLE
Jakefile requires globally installed mocha

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#24998]
**TypeScript Version:**  master

**Code**

```
jake runtests
```

**Expected behavior:**

No error.

**Actual behavior:**

```
node lib/tsc.js -b scripts
node scripts/processDiagnosticMessages.js src/compiler/diagnosticMessages.json
Reading diagnostics from src/compiler/diagnosticMessages.json
node lib/tsc.js -b src
node built/local/tsc.js -b built/local/typescriptServices.tsconfig.json
node lib/tsc.js -b src/testRunner
mocha -R mocha-fivemat-progress-reporter -g "API" --colors -t 40000 built/local/run.js
/bin/sh: 1: mocha: not found
jake aborted.
Error: Process exited with code 127
    at api.fail (/home/andy/.nvm/versions/node/v10.1.0/lib/node_modules/jake/lib/api.js:336:18)
    at finish (/home/andy/TypeScript_2/Jakefile.js:476:13)
(See full trace by running task with --trace)
```

Could reference the one in `node_modules` instead. @RyanCavanaugh This is probably due to a recent change.

**Comment by weswigham** [comment]
@andy-ms should be fixed by #25008
