### ISSUE TITLE
Missing error for a destructuring pattern inside a rest binding element / rest parameter

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2519]
The following is not allowed by the ES6 grammar:
```ts
function foo(...[a]) { }
var [...[b, c]] = [0, 1, 2];
```

The relevant grammar production is:
```
BindingRestElement[Yield, GeneratorParameter] :
    [+GeneratorParameter] ... BindingIdentifier[Yield]
    [~GeneratorParameter] ... BindingIdentifier[?Yield]
```

And a BindingIdentifier does not include a binding pattern.

**Comment by yuit** [comment]
Following code:
```ts
function a(...{a, b}) { }
function a1(...[a, b]) { }
```
causes crash when compiling:

D:\TS\built\local\tsc.js:26338
                          emitDestructuring(p, false, tempParameters[tempIndex
                                                                    ^
TypeError: Cannot read property '0' of undefined
    at D:\TS\built\local\tsc.js:26338:71
    at Object.forEach (D:\TS\built\local\tsc.js:693:30)
    at emitDefaultValueAssignments (D:\TS\built\local\tsc.js:26334:24)
    at emitFunctionBodyPreamble (D:\TS\built\local\tsc.js:26521:17)
    at emitBlockFunctionBody (D:\TS\built\local\tsc.js:26588:17)
    at emitSignatureAndBody (D:\TS\built\local\tsc.js:26506:21)
    at emitFunctionDeclaration (D:\TS\built\local\tsc.js:26450:17)
    at emitJavaScriptWorker (D:\TS\built\local\tsc.js:28256:32)
    at emitNodeWithoutSourceMap (D:\TS\built\local\tsc.js:28146:17)
    at emitLinesStartingAt (D:\TS\built\local\tsc.js:24527:21)

**Comment by rauschma** [comment]
ES7/ES2016 will allow this pattern again: https://tc39.github.io/ecma262/#sec-destructuring-binding-patterns

It was inconsistent with destructuring assignment that has always allowed it: http://www.ecma-international.org/ecma-262/6.0/#sec-destructuring-assignment

**Comment by DanielRosenwasser** [comment]
Thanks for the heads up @rauschma! I've filed #6275.
