### ISSUE TITLE
Debug failure on labeled class declaration

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#25326]
Write `input.ts`

```
foo: class C {}
```

Run

```sh
tsc input.ts
```

**Expected**: `Declarations cannot be labeled`

**Actual**:

```
Error: Debug Failure. False expression: Too many nodes written to output.
    at extractSingleNode (C:\Users\Daniel\AppData\Local\nvs\node\9.4.0\x64\node_modules\typescript\lib\tsc.js:50459:18)
    at Object.visitNode (C:\Users\Daniel\AppData\Local\nvs\node\9.4.0\x64\node_modules\typescript\lib\tsc.js:50107:54)
    at visitLabeledStatement (C:\Users\Daniel\AppData\Local\nvs\node\9.4.0\x64\node_modules\typescript\lib\tsc.js:55963:47)
    at visitJavaScript (C:\Users\Daniel\AppData\Local\nvs\node\9.4.0\x64\node_modules\typescript\lib\tsc.js:55087:28)
    at visitor (C:\Users\Daniel\AppData\Local\nvs\node\9.4.0\x64\node_modules\typescript\lib\tsc.js:55037:24)
    at Object.visitNodes (C:\Users\Daniel\AppData\Local\nvs\node\9.4.0\x64\node_modules\typescript\lib\tsc.js:50135:48)
    at visitSourceFile (C:\Users\Daniel\AppData\Local\nvs\node\9.4.0\x64\node_modules\typescript\lib\tsc.js:55160:40)
    at transformSourceFile (C:\Users\Daniel\AppData\Local\nvs\node\9.4.0\x64\node_modules\typescript\lib\tsc.js:55007:27)
    at transformSourceFileOrBundle (C:\Users\Daniel\AppData\Local\nvs\node\9.4.0\x64\node_modules\typescript\lib\tsc.js:51252:40)    at C:\Users\Daniel\AppData\Local\nvs\node\9.4.0\x64\node_modules\typescript\lib\tsc.js:1167:86
```

**Comment by Kingwl** [comment]
i'd like try to support more labeled declaration check, maybe i can try to fix it together
