### ISSUE TITLE
Maximum call stack size exceeded with recursive index access type

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#25379]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
import { Map } from "immutable";

export type ImmutableTypes = IImmutableMap<any>;

export type ImmutableModel<T> = { [K in keyof T]: T[K] extends ImmutableTypes ? T[K] : never };

// type isImmutableType<T> = T extends ImmutableTypes ? T : never
// export type ImmutableModel<T> = { [K in keyof T]: isImmutableType<T[K]> };

export interface IImmutableMap<T extends ImmutableModel<T>> extends Map<string, any> {
  set<K extends keyof T>(key: K, value: T[K]): IImmutableMap<T>;
}
```

**Expected behavior:**

No error

**Actual behavior:**
```txt
RangeError: Maximum call stack size exceeded
    at getConstraintOfDistributiveConditionalType (C:\Users\mhegazy\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:28907:60)
    at getConstraintOfConditionalType (C:\Users\mhegazy\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:28921:20)
    at computeBaseConstraint (C:\Users\mhegazy\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:29028:38)
    at getBaseConstraint (C:\Users\mhegazy\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:28990:30)
    at computeBaseConstraint (C:\Users\mhegazy\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:29009:40)
    at getBaseConstraint (C:\Users\mhegazy\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:28990:30)
    at computeBaseConstraint (C:\Users\mhegazy\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:29029:42)
    at getBaseConstraint (C:\Users\mhegazy\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:28990:30)
    at computeBaseConstraint (C:\Users\mhegazy\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:29009:40)
    at getBaseConstraint (C:\Users\mhegazy\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:28990:30)
```
**Playground Link:**  

**Related Issues:**

**Comment by xbtsw** [comment]
Just want to add that 
```ts
type isImmutableType<T> = [T] extends [ImmutableTypes] ? T : never;
export type ImmutableModel<T> = { [K in keyof T]: isImmutableType<T[K]> };
```
will also crash on 2.9.2 with
```
RangeError: Maximum call stack size exceeded
    at pushTypeResolution (C:\r\M365Admin\node_modules\typescript\lib\tsc.js:24773:36)
    at getBaseConstraint (C:\r\M365Admin\node_modules\typescript\lib\tsc.js:26810:22)
    at computeBaseConstraint (C:\r\M365Admin\node_modules\typescript\lib\tsc.js:26833:40)
    at getBaseConstraint (C:\r\M365Admin\node_modules\typescript\lib\tsc.js:26814:30)
    at computeBaseConstraint (C:\r\M365Admin\node_modules\typescript\lib\tsc.js:26833:40)
    at getBaseConstraint (C:\r\M365Admin\node_modules\typescript\lib\tsc.js:26814:30)
    at computeBaseConstraint (C:\r\M365Admin\node_modules\typescript\lib\tsc.js:26853:42)
    at getBaseConstraint (C:\r\M365Admin\node_modules\typescript\lib\tsc.js:26814:30)
    at computeBaseConstraint (C:\r\M365Admin\node_modules\typescript\lib\tsc.js:26833:40)
    at getBaseConstraint (C:\r\M365Admin\node_modules\typescript\lib\tsc.js:26814:30)
```
