### ISSUE TITLE
Crash when trying to merge global augmentation

### ISSUE THREAD

**Issue by timocov** [Microsoft/TypeScript#25410]
**TypeScript Version:**  3.0.0-dev.20180703

**Search Terms:** Global augmentation

**Code**

1. `mkdir src && echo "import * as React from 'react';console.log(React);" > src/index.ts`
1. `mkdir tests && echo "import * as React from 'react';console.log(React);" > tests/index.ts`
1. `npm init -y && npm install --save-dev typescript@next @types/react`
1. `cd tests && npm init -y && npm install --save-dev @types/react && cd ../`
1. `./node_modules/.bin/tsc --init`
1. `./node_modules/.bin/tsc --noEmit`

**Expected behavior:**

Compiled without errors

**Actual behavior:**

```
Error: Debug Failure. False expression.
    at mergeSymbol (E:\git\ts-bug\node_modules\typescript\lib\tsc.js:24252:26)
    at E:\git\ts-bug\node_modules\typescript\lib\tsc.js:24344:49
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (E:\git\ts-bug\node_modules\typescript\lib\tsc.js:24343:20)
    at mergeModuleAugmentation (E:\git\ts-bug\node_modules\typescript\lib\tsc.js:24354:17)
    at initializeTypeChecker (E:\git\ts-bug\node_modules\typescript\lib\tsc.js:45114:25)
    at Object.createTypeChecker (E:\git\ts-bug\node_modules\typescript\lib\tsc.js:24102:9)
    at getDiagnosticsProducingTypeChecker (E:\git\ts-bug\node_modules\typescript\lib\tsc.js:66941:93)
    at Object.getGlobalDiagnostics (E:\git\ts-bug\node_modules\typescript\lib\tsc.js:67286:53)
    at Object.emitFilesAndReportErrors (E:\git\ts-bug\node_modules\typescript\lib\tsc.js:69563:46)
```

**Comment by RyanCavanaugh** [comment]
@sandersn probably a better repro for #25339

**Comment by sandersn** [comment]
Thanks @timocov for the excellent repro -- all I had to do was make it work in our test harness. Your fix was exactly right too.
