### ISSUE TITLE
After rename any dir in the project tsserver throws an error

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#25466]
**TypeScript Version:**  3.0.0-dev.20180626

**Search Terms:** 

**Code**

```
Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/usr/local/lib/node_modules/typescript/lib/tsserver.js:112973:23)
    at IOSession.Session.getFileAndLanguageServiceForSyntacticOperation (/usr/local/lib/node_modules/typescript/lib/tsserver.js:117665:42)
    at IOSession.Session.getNavigationTree (/usr/local/lib/node_modules/typescript/lib/tsserver.js:118012:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/local/lib/node_modules/typescript/lib/tsserver.js:116956:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:118343:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:118334:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:118343:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:118363:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119618:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
Can you share your tsserver log?

**Comment by cevek** [comment]
[tsserver.log.zip](https://github.com/Microsoft/TypeScript/files/2170367/tsserver.log.zip)

**Comment by andy-ms** [comment]
@cevek It looks like you're testing this out on a sample project `fooa`, so would you mind sharing it?

**Comment by cevek** [comment]
Here it is
[test.zip](https://github.com/Microsoft/TypeScript/files/2180199/test.zip)

**Comment by andy-ms** [comment]
@mjbvz Looks like vscode is asking for the navtree for a directory?
```
Info 353  [16:52:25.554] Open files: 
Info 353  [16:52:25.554] 	FileName: /Users/cody/Downloads/test/fooa/a.ts ProjectRootPath: /Users/cody/Downloads/test
Info 353  [16:52:25.554] 		Projects: /Users/cody/Downloads/test/tsconfig.json
Perf 353  [16:52:25.554] 42::open: async elapsed time (in milliseconds) 11.2322
Info 354  [16:52:25.554] request:
    {"seq":43,"type":"request","command":"navtree","arguments":{"file":"/Users/cody/Downloads/test/fooa"}}
```

**Comment by mjbvz** [comment]
Should be fixed in the next VS Code insiders build
