### ISSUE TITLE
TSServer: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#25484]
**TypeScript Version:**  3.0.0-dev.20180706

**Search Terms:** 

**Code**

```ts
TypeError: Cannot read property 'forEach' of undefined
    at visitSymbol (/usr/local/lib/node_modules/typescript/lib/tsserver.js:29086:35)
    at visitSignature (/usr/local/lib/node_modules/typescript/lib/tsserver.js:29040:21)
    at visitObjectType (/usr/local/lib/node_modules/typescript/lib/tsserver.js:29060:21)
    at visitType (/usr/local/lib/node_modules/typescript/lib/tsserver.js:28992:25)
    at visitSymbol (/usr/local/lib/node_modules/typescript/lib/tsserver.js:29084:17)
    at visitObjectType (/usr/local/lib/node_modules/typescript/lib/tsserver.js:29068:21)
    at visitInterfaceType (/usr/local/lib/node_modules/typescript/lib/tsserver.js:29046:17)
    at visitType (/usr/local/lib/node_modules/typescript/lib/tsserver.js:28989:25)
    at visitTypeReference (/usr/local/lib/node_modules/typescript/lib/tsserver.js:29009:17)
    at visitType (/usr/local/lib/node_modules/typescript/lib/tsserver.js:28983:25)
    at visitSignature (/usr/local/lib/node_modules/typescript/lib/tsserver.js:29043:17)
    at visitObjectType (/usr/local/lib/node_modules/typescript/lib/tsserver.js:29060:21)
    at visitInterfaceType (/usr/local/lib/node_modules/typescript/lib/tsserver.js:29046:17)
    at visitType (/usr/local/lib/node_modules/typescript/lib/tsserver.js:28989:25)
    at visitSymbol (/usr/local/lib/node_modules/typescript/lib/tsserver.js:29084:17)
    at visitType (/usr/local/lib/node_modules/typescript/lib/tsserver.js:28975:34)
    at Object.walkType (/usr/local/lib/node_modules/typescript/lib/tsserver.js:28946:25)
    at recordTypeParameterUsages (/usr/local/lib/node_modules/typescript/lib/tsserver.js:108636:53)
    at collectUsages (/usr/local/lib/node_modules/typescript/lib/tsserver.js:108648:25)
    at visitNode (/usr/local/lib/node_modules/typescript/lib/tsserver.js:15101:24)
    at Object.forEachChild (/usr/local/lib/node_modules/typescript/lib/tsserver.js:15368:21)
    at collectUsages (/usr/local/lib/node_modules/typescript/lib/tsserver.js:108678:28)
    at visitNodes (/usr/local/lib/node_modules/typescript/lib/tsserver.js:15110:30)
    at Object.forEachChild (/usr/local/lib/node_modules/typescript/lib/tsserver.js:15334:24)
    at collectUsages (/usr/local/lib/node_modules/typescript/lib/tsserver.js:108678:28)
    at collectReadsAndWrites (/usr/local/lib/node_modules/typescript/lib/tsserver.js:108542:17)
    at getPossibleExtractionsWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:107917:38)
    at getPossibleExtractions (/usr/local/lib/node_modules/typescript/lib/tsserver.js:107872:26)
    at Object.getAvailableActions (/usr/local/lib/node_modules/typescript/lib/tsserver.js:107383:35)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:103417:128
    at getIterator (/usr/local/lib/node_modules/typescript/lib/tsserver.js:534:23)
    at Object.next (/usr/local/lib/node_modules/typescript/lib/tsserver.js:529:35)
    at Object.arrayFrom (/usr/local/lib/node_modules/typescript/lib/tsserver.js:1128:32)
    at Object.getApplicableRefactors (/usr/local/lib/node_modules/typescript/lib/tsserver.js:103416:23)
    at Object.getApplicableRefactors (/usr/local/lib/node_modules/typescript/lib/tsserver.js:111461:32)
    at IOSession.Session.getApplicableRefactors (/usr/local/lib/node_modules/typescript/lib/tsserver.js:118719:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/local/lib/node_modules/typescript/lib/tsserver.js:117667:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:118945:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:118936:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:118945:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:118965:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:120223:27)
```
tsserver logs id: 3556371867

**Comment by andy-ms** [comment]
@cevek Do you have any example code I can use to reproduce the issue?

**Comment by cevek** [comment]
@andy-ms Sorry, I don't know how I get this one

**Comment by cevek** [comment]
But in my project it happens every 5 mins

**Comment by cevek** [comment]
Maybe you should to investigate it from tsserver logs?
