### ISSUE TITLE
3.0.0-dev: Compiler crash elaborating assignability error to mapped type

### ISSUE THREAD

**Issue by mattmccutchen** [Microsoft/TypeScript#25498]
**TypeScript Version:**  master (10b174a)

**Search Terms:** elaborateElementwise cannot read property 0 of undefined mapped type

**Code**

```ts
function test(): {[A in "foo"]: A} {
  return {foo: "bar"};
}
```

**Expected behavior:**
Compile error because the `foo` property should have type `"foo"`, not `"bar"`.

**Actual behavior:**
Compiler crash:
```
REDACTED/typescript/built/local/tsc.js:83038
                throw e;
                ^

TypeError: Cannot read property '0' of undefined
    at elaborateElementwise (REDACTED/typescript/built/local/tsc.js:38591:125)
    at elaborateObjectLiteral (REDACTED/typescript/built/local/tsc.js:38710:20)
    at elaborateError (REDACTED/typescript/built/local/tsc.js:38541:28)
    at checkTypeAssignableToAndOptionallyElaborate (REDACTED/typescript/built/local/tsc.js:38521:18)
    at checkReturnStatement (REDACTED/typescript/built/local/tsc.js:51708:25)
    at checkSourceElement (REDACTED/typescript/built/local/tsc.js:53182:28)
    at Object.forEach (REDACTED/typescript/built/local/tsc.js:181:30)
    at checkBlock (REDACTED/typescript/built/local/tsc.js:50816:20)
    at checkSourceElement (REDACTED/typescript/built/local/tsc.js:53161:28)
    at checkFunctionOrMethodDeclaration (REDACTED/typescript/built/local/tsc.js:50540:13)
```

**Playground Link:** The problem does not reproduce on the playground, presumably because it isn't using a new enough version of TypeScript.

**Related Issues:** none found

**Comment by mattmccutchen** [comment]
How did this make it past `strictNullChecks`?

https://github.com/Microsoft/TypeScript/blob/10b174abc16228a921b339f0d5a413e3b8e46b30/src/compiler/utilities.ts#L6670-L6678

`undefined!` looks bad, though I don't know all of the considerations that went into this design.
