### ISSUE TITLE
composite: true breaks quick info

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#25527]
```ts
// src/client/index.ts
import {  } from "../shared";

export function client() {
    shared()
}
```

```json5
// src/client/tsconfig.json
{
    "compilerOptions": {
        "strict": true,
        "module": "esnext",
        "moduleResolution": "node",
        "outDir": "../../lib/foo",
        "composite": true
    }
}
```

```ts
// src/shared/index.ts
export function shared() {

}
```

1. Restart your editor entirely.
2. Try getting quick info.

```
TypeError: Cannot read property 'getSourceFile' of undefined
    at getValidSourceFile (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsserver.js:110815:37)
    at Object.getQuickInfoAtPosition (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsserver.js:111051:30)
    at IOSession.Session.getQuickInfoWorker (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsserver.js:118479:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsserver.js:117602:61)
    at C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsserver.js:119072:88
    at IOSession.Session.executeWithRequestId (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsserver.js:119063:28)
    at IOSession.Session.executeCommand (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsserver.js:119072:33)
    at IOSession.Session.onMessage (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsserver.js:119092:35)
    at Interface.<anonymous> (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsserver.js:120350:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by RyanCavanaugh** [comment]
The quickinfo failure is due to us failing to create a program because we previously threw an exception while trying to issue a warning (oops) about the `shared/index.ts` file existing outside the (implicit) `rootDir`
