### ISSUE TITLE
Assertion failure on minimal project

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#25530]
[fullstack.zip](https://github.com/Microsoft/TypeScript/files/2178196/fullstack.zip)

```ts
// src/client/index.ts
import { shared } from "../shared";

export function client() {
    shared()
}
```

```json5
// src/client/tsconfig.json
{
    "compilerOptions": {
        "strict": true,
        "module": "esnext",
        "moduleResolution": "node",
        "outDir": "../../lib/foo"
    }
}
```

```ts
// src/shared/index.ts
export function shared() {

}
```

```sh
tsc -p src/client
```

Debug assertion:

```
Error: Debug Failure.
    at Object.assertDefined (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsc.js:1266:24)
    at C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsc.js:11009:84
    at String.replace (<anonymous>)
    at formatStringFromArgs (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsc.js:11009:21)
    at Object.createCompilerDiagnostic (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsc.js:11049:20)
    at checkSourceFilesBelongToPath (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsc.js:68088:55)
    at getCommonSourceDirectory (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsc.js:66964:21)
    at verifyCompilerOptions (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsc.js:68281:27)
    at Object.createProgram (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsc.js:66931:9)
    at performCompilation (C:\Users\Daniel\AppData\Local\nvs\node\10.4.1\x64\node_modules\typescript\lib\tsc.js:71566:26)
```

**Comment by RyanCavanaugh** [comment]
Same as #25527
