### ISSUE TITLE
Error: Debug Failure. at Object.assertDefined

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#25726]
**TypeScript Version:**  3.0.0-dev.20180712

**Search Terms:**

**Code**

```ts
Error: Debug Failure.
    at Object.assertDefined (/usr/local/lib/node_modules/typescript/lib/tsserver.js:1435:24)
    at deleteNodeInList (/usr/local/lib/node_modules/typescript/lib/tsserver.js:103759:43)
    at Object.deleteDeclaration (/usr/local/lib/node_modules/typescript/lib/tsserver.js:103657:29)
    at _loop_10 (/usr/local/lib/node_modules/typescript/lib/tsserver.js:103277:43)
    at ChangeTracker.finishDeleteDeclarations (/usr/local/lib/node_modules/typescript/lib/tsserver.js:103283:21)
    at ChangeTracker.getChanges (/usr/local/lib/node_modules/typescript/lib/tsserver.js:103303:22)
    at Function.ChangeTracker.with (/usr/local/lib/node_modules/typescript/lib/tsserver.js:102881:32)
    at Object.getCodeActions (/usr/local/lib/node_modules/typescript/lib/tsserver.js:105918:65)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:103819:121
    at Object.flatMap (/usr/local/lib/node_modules/typescript/lib/tsserver.js:498:25)
    at Object.getFixes (/usr/local/lib/node_modules/typescript/lib/tsserver.js:103819:23)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:111665:35
    at Object.flatMap (/usr/local/lib/node_modules/typescript/lib/tsserver.js:498:25)
    at Object.getCodeFixesAtPosition (/usr/local/lib/node_modules/typescript/lib/tsserver.js:111663:23)
    at IOSession.Session.getCodeFixes (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119225:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/local/lib/node_modules/typescript/lib/tsserver.js:118099:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:119389:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119380:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119389:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119409:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:120676:27)
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:** 

tsserver log id: 3897983895

**Comment by sheetalkamat** [comment]
@cevek You shared the wrong log id? From the log it seems like the stack is as following indicating this is  #27877
```
Debug Failure. Did not expect JsxSelfClosingElement to have an Identifier in its trivia

    Error: Debug Failure. Did not expect JsxSelfClosingElement to have an Identifier in its trivia
    at addSyntheticNodes (/usr/local/lib/node_modules/typescript/lib/tsserver.js:110374:30)
    at createChildren (/usr/local/lib/node_modules/typescript/lib/tsserver.js:110363:9)
    at NodeObject.getChildren (/usr/local/lib/node_modules/typescript/lib/tsserver.js:110307:56)
    at getTokenAtPositionWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:88776:43)
    at Object.getTokenAtPosition (/usr/local/lib/node_modules/typescript/lib/tsserver.js:88768:16)
    at Object.getRangeOfEnclosingComment (/usr/local/lib/node_modules/typescript/lib/tsserver.js:102097:68)
    at isInComment (/usr/local/lib/node_modules/typescript/lib/tsserver.js:89089:30)
    at isInReferenceCommentWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:89206:21)
    at Object.isInReferenceComment (/usr/local/lib/node_modules/typescript/lib/tsserver.js:89198:16)
    at Object.getCompletionsAtPosition (/usr/local/lib/node_modules/typescript/lib/tsserver.js:91242:20)
    at Object.getCompletionsAtPosition (/usr/local/lib/node_modules/typescript/lib/tsserver.js:111346:35)
    at IOSession.Session.getCompletions (/usr/local/lib/node_modules/typescript/lib/tsserver.js:118900:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/local/lib/node_modules/typescript/lib/tsserver.js:117978:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:119389:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119380:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119389:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119409:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:120676:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```
