### ISSUE TITLE
Cannot read property 'length' of undefined  at Object.unescapeLeadingUnderscores

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#25764]
**TypeScript Version:**  3.0.0-dev.20180712

**Search Terms:**

**Code**

```ts
TypeError: Cannot read property 'length' of undefined
    at Object.unescapeLeadingUnderscores (/usr/local/lib/node_modules/typescript/lib/tsserver.js:12000:18)
    at getDisplayName (/usr/local/lib/node_modules/typescript/lib/tsserver.js:25801:93)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:25894:143
    at Object.forEach (/usr/local/lib/node_modules/typescript/lib/tsserver.js:222:30)
    at declareSymbol (/usr/local/lib/node_modules/typescript/lib/tsserver.js:25893:28)
    at bindExportAssignment (/usr/local/lib/node_modules/typescript/lib/tsserver.js:27606:17)
    at bindWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:27541:28)
    at bind (/usr/local/lib/node_modules/typescript/lib/tsserver.js:27315:13)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:26075:94
    at bindEach (/usr/local/lib/node_modules/typescript/lib/tsserver.js:26091:21)
    at bindEachFunctionsFirst (/usr/local/lib/node_modules/typescript/lib/tsserver.js:26075:13)
    at bindChildrenWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:26173:21)
    at bindChildren (/usr/local/lib/node_modules/typescript/lib/tsserver.js:26069:17)
    at bindContainer (/usr/local/lib/node_modules/typescript/lib/tsserver.js:26017:17)
    at bind (/usr/local/lib/node_modules/typescript/lib/tsserver.js:27329:21)
    at bindSourceFile (/usr/local/lib/node_modules/typescript/lib/tsserver.js:25682:17)
    at Object.bindSourceFile (/usr/local/lib/node_modules/typescript/lib/tsserver.js:25623:9)
    at initializeTypeChecker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:54796:20)
    at Object.createTypeChecker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:29763:9)
    at Object.getTypeChecker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:83171:79)
    at synchronizeHostData (/usr/local/lib/node_modules/typescript/lib/tsserver.js:111223:21)
    at Object.getProgram (/usr/local/lib/node_modules/typescript/lib/tsserver.js:111296:13)
    at ConfiguredProject.Project.updateGraphWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:115351:53)
    at ConfiguredProject.Project.updateGraph (/usr/local/lib/node_modules/typescript/lib/tsserver.js:115299:42)
    at ConfiguredProject.updateGraph (/usr/local/lib/node_modules/typescript/lib/tsserver.js:115669:61)
    at ConfiguredProject.Project.getLanguageService (/usr/local/lib/node_modules/typescript/lib/tsserver.js:115005:26)
    at IOSession.Session.getApplicableRefactors (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119171:32)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/local/lib/node_modules/typescript/lib/tsserver.js:118117:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:119389:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119380:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119389:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119409:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:120676:27)
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by cevek** [comment]
Oh, yeah, that happens occasionally
