### ISSUE TITLE
Cannot read property 'length' of undefined at Object.unescapeLeadingUnderscores 

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#25762]
**TypeScript Version:**  3.0.0-dev.20180712

**Search Terms:**

**Code**

```ts
export { name1, name2 };
export { variable1 as name1, variable2 as name2 };
export let name1, name2, nameN; 
export let name1 = 1, name2 = 2, nameN; 
export function FunctionName(){}
export class ClassName {}

export default expression;
export default function () { } 
export default function name1() {  } 
export { name1 as default };

export * from "a";
export { name1, name2, nameN } from "from";
export { import1 as name1, import2 as name2, nameN } from "Fa";
export { default } from "f";
```

Stack trace: 
```
TypeError: Cannot read property 'length' of undefined
    at Object.unescapeLeadingUnderscores (/usr/local/lib/node_modules/typescript/lib/tsserver.js:12000:18)
    at getDisplayName (/usr/local/lib/node_modules/typescript/lib/tsserver.js:25801:93)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:25894:143
    at Object.forEach (/usr/local/lib/node_modules/typescript/lib/tsserver.js:222:30)
    at declareSymbol (/usr/local/lib/node_modules/typescript/lib/tsserver.js:25893:28)
    at bindExportAssignment (/usr/local/lib/node_modules/typescript/lib/tsserver.js:27606:17)
    at bindWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:27541:28)
    at bind (/usr/local/lib/node_modules/typescript/lib/tsserver.js:27315:13)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:26075:94
    at bindEach (/usr/local/lib/node_modules/typescript/lib/tsserver.js:26091:21)
    at bindEachFunctionsFirst (/usr/local/lib/node_modules/typescript/lib/tsserver.js:26075:13)
    at bindChildrenWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:26173:21)
    at bindChildren (/usr/local/lib/node_modules/typescript/lib/tsserver.js:26069:17)
    at bindContainer (/usr/local/lib/node_modules/typescript/lib/tsserver.js:26017:17)
    at bind (/usr/local/lib/node_modules/typescript/lib/tsserver.js:27329:21)
    at bindSourceFile (/usr/local/lib/node_modules/typescript/lib/tsserver.js:25682:17)
    at Object.bindSourceFile (/usr/local/lib/node_modules/typescript/lib/tsserver.js:25623:9)
    at initializeTypeChecker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:54796:20)
    at Object.createTypeChecker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:29763:9)
    at Object.getTypeChecker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:83171:79)
    at synchronizeHostData (/usr/local/lib/node_modules/typescript/lib/tsserver.js:111223:21)
    at Object.getProgram (/usr/local/lib/node_modules/typescript/lib/tsserver.js:111296:13)
    at ConfiguredProject.Project.updateGraphWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:115351:53)
    at ConfiguredProject.Project.updateGraph (/usr/local/lib/node_modules/typescript/lib/tsserver.js:115299:42)
    at ConfiguredProject.updateGraph (/usr/local/lib/node_modules/typescript/lib/tsserver.js:115669:61)
    at ConfiguredProject.Project.getLanguageService (/usr/local/lib/node_modules/typescript/lib/tsserver.js:115005:26)
    at IOSession.Session.getApplicableRefactors (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119171:32)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/local/lib/node_modules/typescript/lib/tsserver.js:118117:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:119389:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119380:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119389:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119409:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:120676:27)
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:** 

Reproduce
![ezgif-5-ff197edcf3](https://user-images.githubusercontent.com/3171573/42884117-ea83b1dc-8ab6-11e8-966a-29f0cbbde860.gif)

**Comment by seansfkelley** [comment]
Seeing this on 3.0.0-rc as well. It appears to [repro on the playground as well](https://www.typescriptlang.org/play/index.html#src=export%20%7B%20name1%2C%20name2%20%7D%3B%0D%0Aexport%20%7B%20variable1%20as%20name1%2C%20variable2%20as%20name2%20%7D%3B%0D%0Aexport%20let%20name1%2C%20name2%2C%20nameN%3B%20%0D%0Aexport%20let%20name1%20%3D%201%2C%20name2%20%3D%202%2C%20nameN%3B%20%0D%0Aexport%20function%20FunctionName()%7B%7D%0D%0Aexport%20class%20ClassName%20%7B%7D%0D%0A%0D%0Aexport%20default%20expression%3B%0D%0Aexport%20default%20function%20()%20%7B%20%7D%20%0D%0Aexport%20default%20function%20name1()%20%7B%20%20%7D%20%0D%0Aexport%20%7B%20name1%20as%20default%20%7D%3B%0D%0A%0D%0Aexport%20*%20from%20%22a%22%3B%0D%0Aexport%20%7B%20name1%2C%20name2%2C%20nameN%20%7D%20from%20%22from%22%3B%0D%0Aexport%20%7B%20import1%20as%20name1%2C%20import2%20as%20name2%2C%20nameN%20%7D%20from%20%22Fa%22%3B%0D%0Aexport%20%7B%20default%20%7D%20from%20%22f%22%3B), which is running `2.9.1-insiders.20180525` as of this writing.
