### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined when mixing --strictFunctionTypes, Promises and parameter spread types

### ISSUE THREAD

**Issue by seansfkelley** [Microsoft/TypeScript#25775]
**TypeScript Version:**  3.1.0-dev.20180717

**Search Terms:** strict

**Code**

```ts
export function wrapFunction<T extends any[], U>(fn: (...args: T) => Promise<U>): ((...args: T) => Promise<U>) {
  return null as any;
}

const wrapped = wrapFunction(null as any as () => Promise<any>);
Promise.resolve().then(wrapped);
```

Run with `tsc <filename>.ts --strictFunctionTypes --target es6`

**Expected behavior:**

No compiler crash.

**Actual behavior:**

Crash with the following stack trace:

```
TypeError: Cannot read property 'length' of undefined
    at Object.unescapeLeadingUnderscores (/Users/seankelley/.config/yarn/global/node_modules/typescript/lib/tsc.js:9371:19)
    at compareSignaturesRelated (/Users/seankelley/.config/yarn/global/node_modules/typescript/lib/tsc.js:32274:103)
    at signatureRelatedTo (/Users/seankelley/.config/yarn/global/node_modules/typescript/lib/tsc.js:33393:24)
    at signaturesRelatedTo (/Users/seankelley/.config/yarn/global/node_modules/typescript/lib/tsc.js:33368:30)
    at structuredTypeRelatedTo (/Users/seankelley/.config/yarn/global/node_modules/typescript/lib/tsc.js:33135:43)
    at recursiveTypeRelatedTo (/Users/seankelley/.config/yarn/global/node_modules/typescript/lib/tsc.js:32966:53)
    at isRelatedTo (/Users/seankelley/.config/yarn/global/node_modules/typescript/lib/tsc.js:32646:38)
    at checkTypeRelatedTo (/Users/seankelley/.config/yarn/global/node_modules/typescript/lib/tsc.js:32477:26)
    at checkApplicableSignature (/Users/seankelley/.config/yarn/global/node_modules/typescript/lib/tsc.js:38478:30)
    at resolveCall (/Users/seankelley/.config/yarn/global/node_modules/typescript/lib/tsc.js:38776:17)
```

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html#src=export%20function%20wrapFunction%3CT%20extends%20any%5B%5D%2C%20U%3E(fn%3A%20(...args%3A%20T)%20%3D%3E%20Promise%3CU%3E)%3A%20((...args%3A%20T)%20%3D%3E%20Promise%3CU%3E)%20%7B%0D%0A%20%20return%20null%20as%20any%3B%0D%0A%7D%0D%0A%0D%0Aconst%20wrapped%20%3D%20wrapFunction(null%20as%20any%20as%20()%20%3D%3E%20Promise%3Cany%3E)%3B%0D%0APromise.resolve().then(wrapped)%3B); be sure to enable `strictFunctionTypes` and to examine the browser console.

**Related Issues:** #25762, but the stack and repro there appear very different.

**Comment by Nimelrian** [comment]
Can confirm this issue, happened to me when using a function utilizing parameter spread types.

The example in the OP now "works" in the playground as well, activating all "strictifying" options and then doing a compile of the code throws the error in the console.

**Comment by hamczu** [comment]
which worker are you using? I had very similar (or the same) issue but it only happens on awesome-typescript-loader, after trying ts-loader everything works nicely

**Comment by seansfkelley** [comment]
@hamczu could be a configuration/version difference or a different bug entirely; hard to say with the information you gave. It repros on the compiler itself independent of the bundler/loader so changing your loader is a red herring.

**Comment by weswigham** [comment]
This seems to be fixed on `master`, or at least I can't repro anymore with the code in the OP.

**Comment by seansfkelley** [comment]
Alright; feel free to close. If it comes back when I upgrade compiler versions I'll reopen the ticket.
