### ISSUE TITLE
Cannot read property 'kind' of undefined at Object.isParameter

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#25790]
**TypeScript Version:**  3.0.0-dev.20180712

**Search Terms:**

**Code**

```ts
TypeError: Cannot read property 'kind' of undefined
    at Object.isParameter (/usr/local/lib/node_modules/typescript/lib/tsserver.js:12342:20)
    at tryDeleteDeclarationWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:106022:20)
    at tryDeleteDeclaration (/usr/local/lib/node_modules/typescript/lib/tsserver.js:106007:13)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:105919:28
    at Function.ChangeTracker.with (/usr/local/lib/node_modules/typescript/lib/tsserver.js:102880:17)
    at Object.getCodeActions (/usr/local/lib/node_modules/typescript/lib/tsserver.js:105918:65)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:103819:121
    at Object.flatMap (/usr/local/lib/node_modules/typescript/lib/tsserver.js:498:25)
    at Object.getFixes (/usr/local/lib/node_modules/typescript/lib/tsserver.js:103819:23)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:111665:35
    at Object.flatMap (/usr/local/lib/node_modules/typescript/lib/tsserver.js:498:25)
    at Object.getCodeFixesAtPosition (/usr/local/lib/node_modules/typescript/lib/tsserver.js:111663:23)
    at IOSession.Session.getCodeFixes (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119225:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/local/lib/node_modules/typescript/lib/tsserver.js:118099:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:119389:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119380:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119389:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119409:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:120676:27)
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by andy-ms** [comment]
This should only happen if `token` is a `SourceFile`, which should only happen if the position in the `getCodeFixes` request is wrong. That should have been fixed by Microsoft/vscode#45785. @cevek What version of vscode are you using? And what code did you use to produce this error?

**Comment by cevek** [comment]
@andy-ms I don't know. After that I've updated to the new version of vscode: 1.25.1
