### ISSUE TITLE
Cannot read property 'getCallSignatures' of undefined at getPossibleGenericSignatures 

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#25836]
**TypeScript Version:**  3.1.0-dev.20180717

**Search Terms:**

**Code**

```ts
TypeError: Cannot read property 'getCallSignatures' of undefined
    at Object.getPossibleGenericSignatures (/usr/local/lib/node_modules/typescript/lib/tsserver.js:89015:98)
    at getCandidateInfo (/usr/local/lib/node_modules/typescript/lib/tsserver.js:98823:37)
    at Object.getSignatureHelpItems (/usr/local/lib/node_modules/typescript/lib/tsserver.js:98771:33)
    at Object.getSignatureHelpItems (/usr/local/lib/node_modules/typescript/lib/tsserver.js:111549:37)
    at IOSession.Session.getSignatureHelpItems (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119021:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/local/lib/node_modules/typescript/lib/tsserver.js:118049:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:119442:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119433:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119442:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119462:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:120735:27)
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by andy-ms** [comment]
Looks like this is because `getTypeAtLocation` returned undefined. I had a PR ready to fix that but need to get #25626 in first to avoid big baseline changes.
