### ISSUE TITLE
Cannot read property 'kind' of undefined at Object.parenthesizeArrayTypeMember

### ISSUE THREAD

**Issue by victorwelling** [Microsoft/TypeScript#26153]
**TypeScript Version:**  3.1.0-dev.20180802

**Search Terms:**
* Cannot read property 'kind' of undefined
* Optional element in tuple
* ReadonlyArray
* Strict mode

**Code**

```ts
type Foo = [object, object?];

(): ReadonlyArray<Foo> => [{}, {}];
```

**Expected behavior:**
An error along the lines of:
```
Type '{}[]' is not assignable to type '[object, (object | undefined)?][]
```

**Actual behavior:**
```
./node_modules/typescript/lib/tsc.js:67968
                throw e;
                ^

TypeError: Cannot read property 'kind' of undefined
    at Object.parenthesizeArrayTypeMember (./node_modules/typescript/lib/tsc.js:50576:24)
    at Object.createOptionalTypeNode (./node_modules/typescript/lib/tsc.js:47850:24)
    at typeReferenceToTypeNode (./node_modules/typescript/lib/tsc.js:26572:44)
    at typeToTypeNodeHelper (./node_modules/typescript/lib/tsc.js:26383:28)
    at typeReferenceToTypeNode (./node_modules/typescript/lib/tsc.js:26560:43)
    at typeToTypeNodeHelper (./node_modules/typescript/lib/tsc.js:26383:28)
    at signatureToSignatureDeclarationHelper (./node_modules/typescript/lib/tsc.js:26827:52)
    at createTypeNodesFromResolvedType (./node_modules/typescript/lib/tsc.js:26666:43)
    at createTypeNodeFromObjectType (./node_modules/typescript/lib/tsc.js:26547:35)
    at createAnonymousTypeNode (./node_modules/typescript/lib/tsc.js:26502:42)
```

**Conditions**
It seems this bug is only triggered if:
* a `ReadonlyArray` is used – `Array` doesn't seem to trigger it
* strict mode is enabled
* the last element of the tuple is optional

**Playground Link:**
[Playground](https://www.typescriptlang.org/play/#src=type%20Foo%20%3D%20%5Bobject%2C%20object%3F%5D%3B%0D%0A%0D%0A()%3A%20ReadonlyArray%3CFoo%3E%20%3D%3E%20%5B%7B%7D%2C%20%7B%7D%5D%3B%0D%0A). Be sure to enable strictNullChecks to replicate.

**Comment by timkendrick** [comment]
FYI I am experiencing this error in the current release version (3.0.3).

Any idea whether it is likely to be fixed any time soon, or should I refactor my code to work around it?

**Comment by jonaskello** [comment]
I'm using using tsc 3.0.3 and I got this error when doing a rather large merge  I'm not sure how to find which file is causing it. Are there any tricks to find the offending file?

**Comment by yortus** [comment]
I just hit this too. My repro is quite different to OP's, but the PR at #26433 fixes it. Hope it gets merged soon.
