### ISSUE TITLE
Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#26288]
**TypeScript Version:**  3.1.0-dev.20180807

**Code**

```ts
import {} from ".";
export const a = 0;
```

No tsconfig needed.
Put cursor after the `.` in `from ".";` and type `/`. vscode should request completions.

**Expected behavior:**

No error.

**Actual behavior:**

```
TypeError: Cannot read property 'close' of undefined
at Object.close (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:82515:25)
at /home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:85949:37
at Map.forEach (<anonymous>)
at Object.finishCachingPerDirectoryResolution (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:85946:45)
at InferredProject.Project.updateGraphWorker (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:116014:38)
at InferredProject.Project.updateGraph (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:115960:42)
at Object.updateProjectIfDirty (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:116619:45)
at InferredProject.Project.getLanguageService (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:115657:28)
at IOSession.Session.getCompletions (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:119647:43)
at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:118717:61)
at /home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:120125:88
at IOSession.Session.executeWithRequestId (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:120116:28)
at IOSession.Session.executeCommand (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:120125:33)
at IOSession.Session.onMessage (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:120145:35)
at Interface.<anonymous> (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:121399:27)
at emitOne (events.js:116:13)
at Interface.emit (events.js:211:7)
at Interface._onLine (readline.js:282:10)
at Interface._normalWrite (readline.js:424:12)
at Socket.ondata (readline.js:141:10)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at Pipe.onread (net.js:594:20)
```

**Comment by andy-ms** [comment]
I wrote a test to try reproducing the error but it seems to pass. (And I verified that the error still reproduces in vscode when using a local build.)

```
describe("tsserverProjectSystem NAMEME", () => {
    it("NAMEME", () => {
        const aTs: File = { path: "/a.ts", content: 'import {} from ".";\nexport const a = 0;' };
        const session = createSession(createServerHost([aTs]));
        openFilesForSession([aTs], session);
        const offset = 'import {} from ".'.length;

        executeSessionRequestNoResponse<protocol.ChangeRequest>(session, protocol.CommandTypes.Change, {
            file: aTs.path,
            line: 1,
            offset: offset + 1, //+1 because 1-based
            endLine: 1,
            endOffset: offset + 1,
            insertString: "/",
        });

        const response = executeSessionRequest<protocol.CompletionsRequest, protocol.CompletionInfoResponse>(session, protocol.CommandTypes.CompletionInfo, {
            file: aTs.path,
            line: 1,
            offset: offset + 2, //+1 because 1-based, another +1 because of the '/' we just typed
            triggerCharacter: "/",
        });
        assert.deepEqual<protocol.CompletionInfo | undefined>(response, {
            entries: [],
            isGlobalCompletion: false,
            isMemberCompletion: false,
            isNewIdentifierLocation: true,
        });
    });
});
```
