### ISSUE TITLE
tsc crashes resolving a type of computed property in destructiring assignment

### ISSUE THREAD

**Issue by r00ger** [Microsoft/TypeScript#26321]
**TypeScript Version:**  3.1.0-dev.20180809, 3.0.1

**Search Terms:**
Cannot read property 'charCodeAt' of undefined

**Code**

```ts
interface Limit1 {
    propName: { min: number; max: number };
}
interface Limit2 {
    propName: { min: number; max: number };
}

type Limit = Limit1 | Limit2; // should be Union type

export interface Meta {
    propName: "propName";
}

function foo (meta: Meta, limits: Limit): void {
    const {
        [`propName`]: { min: minBonus, max: maxBonus }, // should be computed
    } = limits;
}

```

**Expected behavior:**
No crash, code compiled

**Actual behavior:**

<details>
  <summary><code>Cannot read property 'charCodeAt' of undefined</code></summary>
  <pre>
.../node_modules/typescript/lib/tsc.js:68035
                throw e;
                ^

TypeError: Cannot read property 'charCodeAt' of undefined
    at isLateBoundName (.../node_modules/typescript/lib/tsc.js:28756:25)
    at createUnionOrIntersectionProperty (.../node_modules/typescript/lib/tsc.js:29638:38)
    at getUnionOrIntersectionProperty (.../node_modules/typescript/lib/tsc.js:29699:28)
    at getPropertyOfUnionOrIntersectionType (.../node_modules/typescript/lib/tsc.js:29707:28)
    at getPropertyOfType (.../node_modules/typescript/lib/tsc.js:29727:24)
    at checkVariableLikeDeclaration (.../node_modules/typescript/lib/tsc.js:43025:36)
    at checkBindingElement (.../node_modules/typescript/lib/tsc.js:43123:20)
    at checkSourceElement (.../node_modules/typescript/lib/tsc.js:44827:28)
    at Object.forEach (.../node_modules/typescript/lib/tsc.js:168:30)
    at checkVariableLikeDeclaration (.../node_modules/typescript/lib/tsc.js:43036:20)

</pre>
</details>

[**Playground Link:**](https://www.typescriptlang.org/play/index.html#src=interface%20Limit1%20%7B%0A%20%20%20%20propName%3A%20number%3B%0A%7D%0Ainterface%20Limit2%20%7B%0A%20%20%20%20propName%3A%20number%3B%0A%7D%0A%0Atype%20Limit%20%3D%20Limit1%20%7C%20Limit2%3B%20%2F%2F%20should%20be%20Union%20type%0A%0Aexport%20interface%20Meta%20%7B%0A%20%20%20%20propName%3A%20%22propName%22%3B%0A%7D%0A%0Afunction%20foo%20(limits%3A%20Limit)%3A%20void%20%7B%0A%20%20%20%20const%20%7B%0A%20%20%20%20%20%20%20%20%5B%60propName%60%5D%3A%20minBonus%2C%20%2F%2F%20should%20be%20computed%0A%20%20%20%20%7D%20%3D%20limits%3B%0A%7D%0A)

_Note, that the code is not compiled_

**Comment by andy-ms** [comment]
```ts
declare const ab: { n: number } | { n: string };
const { [`n`]: n } = ab;
```

**Comment by andy-ms** [comment]
`checkVariableLikeDeclaration` calls `getPropertyOfType` using `getTextOfPropertyName(name)`, but that is undefined for a computed name. (See #18217 comment in `getTextOfPropertyName`.) To do this properly we need a function that can find a *property* for an indexed access. That could also fix #26328.

**Comment by KeitIG** [comment]
@andy-ms Has it been released yet?

**Comment by andy-ms** [comment]
Yes, should be released in `typescript@next`.
