### ISSUE TITLE
Debug Failure when using --build

### ISSUE THREAD

**Issue by markboyall** [Microsoft/TypeScript#26363]
```
1>EXEC : error : Debug Failure.
1>      at Object.assertDefined (C:\dev\epro\packages\Microsoft.TypeScript.MSBuild.3.0.0\tools\tsc\tsc.js:1394:24)
1>      at C:\dev\epro\packages\Microsoft.TypeScript.MSBuild.3.0.0\tools\tsc\tsc.js:13822:84
1>      at String.replace (<anonymous>)
1>      at formatStringFromArgs (C:\dev\epro\packages\Microsoft.TypeScript.MSBuild.3.0.0\tools\tsc\tsc.js:13822:21)
1>      at Object.createCompilerDiagnostic (C:\dev\epro\packages\Microsoft.TypeScript.MSBuild.3.0.0\tools\tsc\tsc.js:13863:20)
1>      at checkSourceFilesBelongToPath (C:\dev\epro\packages\Microsoft.TypeScript.MSBuild.3.0.0\tools\tsc\tsc.js:83705:55)
1>      at Object.getCommonSourceDirectory (C:\dev\epro\packages\Microsoft.TypeScript.MSBuild.3.0.0\tools\tsc\tsc.js:82379:21)
1>      at Object.getExternalModuleNameFromPath (C:\dev\epro\packages\Microsoft.TypeScript.MSBuild.3.0.0\tools\tsc\tsc.js:10438:84)
1>      at Object.tryGetModuleNameFromFile (C:\dev\epro\packages\Microsoft.TypeScript.MSBuild.3.0.0\tools\tsc\tsc.js:59905:40)
1>      at transformAMDModule (C:\dev\epro\packages\Microsoft.TypeScript.MSBuild.3.0.0\tools\tsc\tsc.js:72674:33)
1>  
1>  [18:16:08] 'build-typescript' errored after 2.65 s
1>  [18:16:08] Error: Command failed: node "../packages/Microsoft.TypeScript.MSBuild.3.0.0/tools/tsc/tsc.js" -b --verbose Framework/Framework.tsconfig.json
1>  C:\dev\epro\packages\Microsoft.TypeScript.MSBuild.3.0.0\tools\tsc\tsc.js:82937
1>                  throw e;
1>                  ^
```

I'm experimenting with trying to upgrade our solution (25 seconds build time) to --build. I've started with one specific module, looking to pull that out of our monolith.

Here are the three tsconfig files involved:

base.tsconfig
```
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "module": "amd",
        "moduleResolution": "node",
        "noEmitOnError": true,
        "noImplicitAny": true,
        "outFile": "build/typescript.js",
        "removeComments": false,
        "sourceMap": true,
        "target": "es5",
        "allowUnreachableCode": false,
        "noImplicitReturns": true,
        "baseUrl": "./",
        //"strictNullChecks": true,
        "noImplicitThis": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        //"skipLibCheck": true,
        "lib": [ "dom", "es5", "es2015.promise" ]
    },
    "compileOnSave": false,
    "exclude": [ "node_modules" ]
}
```

tsconfig
```
{
    "extends": "./base.tsconfig.json",
    "include": [
        "App/Require.ts",
        "**/*.ts",
        "**/*.d.ts"
    ],
    "exclude": [
        "Framework/*.ts"
    ],
    "references": [
        {
            "path": "Framework/Framework.tsconfig.json"
        }
    ]
}
```

Framework.tsconfig.json
```
{
  "extends": "../base.tsconfig.json",
  "exclude": [
      "../node_modules",
      "../Framework/AsyncResponse.ts",
      "../Framework/DispatchPromise.ts",
      "../Framework/Framework.ts",
      "../Framework/Cache.ts",
      "../Framework/CacheContent.ts",
      "../Framework/CacheReducer.ts",
      "../Framework/Component.ts",
      "../Framework/Connection.ts",
      "../Framework/ConnectionBuilder.ts",
      "../Framework/Editor.ts",
      "../Framework/LoadingProps.ts",
      "../Framework/TextInsertionFormatting.ts",
      "../Specs/Framework/CacheReducerTests.ts",
      "../Specs/Framework/CacheTests.ts",
      "../Specs/Framework/ColumnMatcherTests.ts",
      "../Specs/Framework/ConnectionTests.ts",
      "../Specs/Framework/ConnectionBuilderTests.ts",
      "../Specs/Framework/DispatchPromiseTests.ts",
      "../Specs/Framework/LoadingPropsTests.ts"
  ],
    "include": [
        "../redux.ts",
        "../react-redux.ts",
        "../Specs/Helpers/MockClock.ts",
        "../Framework/*.ts",
        "../Specs/Framework/*.ts",
        "../Dependencies/moment.d.ts",
        "../Dependencies/jquery.cookie.d.ts",
        "../Dependencies/rangy-core.d.ts",
        "../Dependencies/jquery.d.ts",
        "../Dependencies/underscore.string.d.ts",
        "../Dependencies/underscore.d.ts",
        "../Dependencies/jasmine.d.ts",
        "../Dependencies/JasmineAddons.d.ts",
        "../Dependencies/react.d.ts",
        "../Dependencies/redux.d.ts",
        "../Dependencies/react-redux.d.ts",
        "../Dependencies/react-dom.d.ts"
    ],
    "compilerOptions": {
        "experimentalDecorators": true,
        "strictNullChecks": true,
        "composite": true,
        "declaration": true,
        "outFile": "../build/framework.js"
    }
}
```

Not sure what further information is needed, let me know in a comment and I'll try to provide.

**Comment by markboyall** [comment]
Based on my debugging, this occurs if the rootDir option is not set. Also, it seems really dumb how the string formatting function can crash the compiler this way due to a terrible API.

**Comment by sheetalkamat** [comment]
@markboyall can you please share small repro?
Need source structure (apart from tsconfig what do source files look like)
Which project are you trying to build that causes this exception?

**Comment by sheetalkamat** [comment]
Closing this since there is no further information. Please update if you have more details. Thank you.
