### ISSUE TITLE
Formatting failure (regression)

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#26513]
**TypeScript Version:**  3.1.0-dev.20180817

**Search Terms:**

**Code**

```
[Error  - 11:38:58 PM] 'format' request failed with error.
Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.readTokenInfo (...\node_modules\typescript\lib\tsserver.js:101184:26)
    at processChildNodes (...\node_modules\typescript\lib\tsserver.js:102616:59)
    at ...\node_modules\typescript\lib\tsserver.js:102512:21
    at visitNodes (...\node_modules\typescript\lib\tsserver.js:15300:24)
    at Object.forEachChild (...\node_modules\typescript\lib\tsserver.js:15482:21)
    at processNode (...\node_modules\typescript\lib\tsserver.js:102509:20)
    at processChildNode (...\node_modules\typescript\lib\tsserver.js:102569:21)
    at processChildNodes (...\node_modules\typescript\lib\tsserver.js:102609:48)
    at ...\node_modules\typescript\lib\tsserver.js:102512:21
    at visitNodes (...\node_modules\typescript\lib\tsserver.js:15300:24)
    at Object.forEachChild (...\node_modules\typescript\lib\tsserver.js:15482:21)
    at processNode (...\node_modules\typescript\lib\tsserver.js:102509:20)
    at processChildNode (...\node_modules\typescript\lib\tsserver.js:102569:21)
    at ...\node_modules\typescript\lib\tsserver.js:102510:21
    at visitNode (...\node_modules\typescript\lib\tsserver.js:15295:24)
    at Object.forEachChild (...\node_modules\typescript\lib\tsserver.js:15480:24)
    at processNode (...\node_modules\typescript\lib\tsserver.js:102509:20)
    at processChildNode (...\node_modules\typescript\lib\tsserver.js:102569:21)
    at ...\node_modules\typescript\lib\tsserver.js:102510:21
    at visitNode (...\node_modules\typescript\lib\tsserver.js:15295:24)
    at Object.forEachChild (...\node_modules\typescript\lib\tsserver.js:15568:24)
    at processNode (...\node_modules\typescript\lib\tsserver.js:102509:20)
    at processChildNode (...\node_modules\typescript\lib\tsserver.js:102569:21)
    at processChildNodes (...\node_modules\typescript\lib\tsserver.js:102609:48)
    at ...\node_modules\typescript\lib\tsserver.js:102512:21
    at visitNodes (...\node_modules\typescript\lib\tsserver.js:15300:24)
    at Object.forEachChild (...\node_modules\typescript\lib\tsserver.js:15528:24)
    at processNode (...\node_modules\typescript\lib\tsserver.js:102509:20)
    at formatSpanWorker (...\node_modules\typescript\lib\tsserver.js:102336:17)
    at ...\node_modules\typescript\lib\tsserver.js:102317:208
    at Object.getFormattingScanner (...\node_modules\typescript\lib\tsserver.js:101105:23)
    at formatSpan (...\node_modules\typescript\lib\tsserver.js:102317:31)
    at Object.formatSelection (...\node_modules\typescript\lib\tsserver.js:102134:20)
    at Object.getFormattingEditsForRange (...\node_modules\typescript\lib\tsserver.js:112970:34)
    at IOSession.Session.getFormattingEditsForRange (...\node_modules\typescript\lib\tsserver.js:120302:45)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (...\node_modules\typescript\lib\tsserver.js:119422:61)
    at ...\node_modules\typescript\lib\tsserver.js:120849:88
    at IOSession.Session.executeWithRequestId (...\node_modules\typescript\lib\tsserver.js:120840:28)
    at IOSession.Session.executeCommand (...\node_modules\typescript\lib\tsserver.js:120849:33)
    at IOSession.Session.onMessage (...\node_modules\typescript\lib\tsserver.js:120869:35)
    at Interface.<anonymous> (...\node_modules\typescript\lib\tsserver.js:122123:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Repro steps?

**Comment by falsandtru** [comment]
Select the following line and format that **range**, not document. I've not found a snippet to repro this error yet.

https://github.com/falsandtru/securemark/blob/v0.78.0/src/parser/inline/strong.ts#L7

**Comment by falsandtru** [comment]
This is a very popular case for vimmers. To cause the error, install VSCodeVim extension and just type `==`.
