### ISSUE TITLE
getCodeFixes error with TS3.0.1 and VSCode 1.26.1 when expecting an import suggestion

### ISSUE THREAD

**Issue by xaviergonz** [Microsoft/TypeScript#26562]
**TypeScript Version:**  3.0.1

**Search Terms:** getCodeFixes

When running VSCode I get the following error in the TS console, which results in no code fixes being available. In this case, the expected codefix would be a suggestion for a missing import.

```
[Info  - 11:43:19 PM] Started TSServer
[Error  - 11:43:29 PM] 'getCodeFixes' request failed with error.
Error processing request. Debug Failure.
Error: Debug Failure.
    at Object.assertDefined (XXX\node_modules\typescript\lib\tsserver.js:1435:24)
    at getDefaultExportInfo (XXX\node_modules\typescript\lib\tsserver.js:105189:63)
    at XXX\node_modules\typescript\lib\tsserver.js:105166:32
    at XXX\node_modules\typescript\lib\tsserver.js:105287:21
    at forEachExternalModule (XXX\node_modules\typescript\lib\tsserver.js:105300:21)
    at forEachExternalModuleToImportFrom (XXX\node_modules\typescript\lib\tsserver.js:105285:13)
    at getExportInfos (XXX\node_modules\typescript\lib\tsserver.js:105161:13)
    at getFixesInfoForNonUMDImport (XXX\node_modules\typescript\lib\tsserver.js:105147:57)
    at getFixesInfo (XXX\node_modules\typescript\lib\tsserver.js:105085:19)
    at Object.getCodeActions (XXX\node_modules\typescript\lib\tsserver.js:104870:28)
    at XXX\node_modules\typescript\lib\tsserver.js:103896:121
    at Object.flatMap (XXX\node_modules\typescript\lib\tsserver.js:498:25)
    at Object.getFixes (XXX\node_modules\typescript\lib\tsserver.js:103896:23)
    at XXX\node_modules\typescript\lib\tsserver.js:111747:35
    at Object.flatMap (XXX\node_modules\typescript\lib\tsserver.js:498:25)
    at Object.getCodeFixesAtPosition (XXX\node_modules\typescript\lib\tsserver.js:111745:23)
    at IOSession.Session.getCodeFixes (XXX\node_modules\typescript\lib\tsserver.js:119339:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (XXX\node_modules\typescript\lib\tsserver.js:118213:61)
    at XXX\node_modules\typescript\lib\tsserver.js:119496:88
    at IOSession.Session.executeWithRequestId (XXX\node_modules\typescript\lib\tsserver.js:119487:28)
    at IOSession.Session.executeCommand (XXX\node_modules\typescript\lib\tsserver.js:119496:33)
    at IOSession.Session.onMessage (XXX\node_modules\typescript\lib\tsserver.js:119516:35)
    at Interface.<anonymous> (XXX\node_modules\typescript\lib\tsserver.js:120770:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
[Error  - 11:43:29 PM] 'getCodeFixes' request failed with error.
Error processing request. Debug Failure.
Error: Debug Failure.
    at Object.assertDefined (XXX\node_modules\typescript\lib\tsserver.js:1435:24)
    at getDefaultExportInfo (XXX\node_modules\typescript\lib\tsserver.js:105189:63)
    at XXX\node_modules\typescript\lib\tsserver.js:105166:32
    at XXX\node_modules\typescript\lib\tsserver.js:105287:21
    at forEachExternalModule (XXX\node_modules\typescript\lib\tsserver.js:105300:21)
    at forEachExternalModuleToImportFrom (XXX\node_modules\typescript\lib\tsserver.js:105285:13)
    at getExportInfos (XXX\node_modules\typescript\lib\tsserver.js:105161:13)
    at getFixesInfoForNonUMDImport (XXX\node_modules\typescript\lib\tsserver.js:105147:57)
    at getFixesInfo (XXX\node_modules\typescript\lib\tsserver.js:105085:19)
    at Object.getCodeActions (XXX\node_modules\typescript\lib\tsserver.js:104870:28)
    at XXX\node_modules\typescript\lib\tsserver.js:103896:121
    at Object.flatMap (XXX\node_modules\typescript\lib\tsserver.js:498:25)
    at Object.getFixes (XXX\node_modules\typescript\lib\tsserver.js:103896:23)
    at XXX\node_modules\typescript\lib\tsserver.js:111747:35
    at Object.flatMap (XXX\node_modules\typescript\lib\tsserver.js:498:25)
    at Object.getCodeFixesAtPosition (XXX\node_modules\typescript\lib\tsserver.js:111745:23)
    at IOSession.Session.getCodeFixes (XXX\node_modules\typescript\lib\tsserver.js:119339:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (XXX\node_modules\typescript\lib\tsserver.js:118213:61)
    at XXX\node_modules\typescript\lib\tsserver.js:119496:88
    at IOSession.Session.executeWithRequestId (XXX\node_modules\typescript\lib\tsserver.js:119487:28)
    at IOSession.Session.executeCommand (XXX\node_modules\typescript\lib\tsserver.js:119496:33)
    at IOSession.Session.onMessage (XXX\node_modules\typescript\lib\tsserver.js:119516:35)
    at Interface.<anonymous> (XXX\node_modules\typescript\lib\tsserver.js:120770:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by xaviergonz** [comment]
nevermind, apparently it is fixed in 3.1.0-dev
