### ISSUE TITLE
OOM crash in tsserver when getting type of expression

### ISSUE THREAD

**Issue by minestarks** [Microsoft/TypeScript#26584]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:** out of memory, oom, crash, tsserver, vscode, vs

**Repro**
1. `git clone https://github.com/marktext/marktext.git`
2. Open repro in VSCode
3. Open file `src\muya\lib\contentState\formatCtrl.js`
4. Hover over `token` in line 107 column 35 to get its type 
5. Note tsserver process (code.exe) process gradually blowing up in memory usage and then dying

Partial stack trace before process is terminated (not vscode, it's from a standalone repro app compiling the same project)

```
    at getWidenedTypeWithContext (tsserverlibrary.js:40923:132)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at sameMap (tsserverlibrary.js:447:29)
    at getWidenedTypeWithContext (tsserverlibrary.js:40926:63)
    at getWidenedProperty (tsserverlibrary.js:40875:26)
    at getWidenedTypeOfObjectLiteral (tsserverlibrary.js:40892:46)
    at getWidenedTypeWithContext (tsserverlibrary.js:40915:27)
    at (anonymous) (tsserverlibrary.js:40919:121)
    at sameMap (tsserverlibrary.js:452:36)
    at getWidenedTypeWithContext (tsserverlibrary.js:40919:42)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at sameMap (tsserverlibrary.js:447:29)
    at getWidenedTypeWithContext (tsserverlibrary.js:40926:63)
    at getWidenedProperty (tsserverlibrary.js:40875:26)
    at getWidenedTypeOfObjectLiteral (tsserverlibrary.js:40892:46)
    at getWidenedTypeWithContext (tsserverlibrary.js:40915:27)
    at (anonymous) (tsserverlibrary.js:40919:121)
    at sameMap (tsserverlibrary.js:452:36)
    at getWidenedTypeWithContext (tsserverlibrary.js:40919:42)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at sameMap (tsserverlibrary.js:447:29)
    at getWidenedTypeWithContext (tsserverlibrary.js:40926:63)
    at getWidenedProperty (tsserverlibrary.js:40875:26)
    at getWidenedTypeOfObjectLiteral (tsserverlibrary.js:40892:46)
    at getWidenedTypeWithContext (tsserverlibrary.js:40915:27)
    at (anonymous) (tsserverlibrary.js:40919:121)
    at sameMap (tsserverlibrary.js:452:36)
    at getWidenedTypeWithContext (tsserverlibrary.js:40919:42)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at sameMap (tsserverlibrary.js:447:29)
    at getWidenedTypeWithContext (tsserverlibrary.js:40926:63)
    at getWidenedProperty (tsserverlibrary.js:40875:26)
    at getWidenedTypeOfObjectLiteral (tsserverlibrary.js:40892:46)
    at getWidenedTypeWithContext (tsserverlibrary.js:40915:27)
    at (anonymous) (tsserverlibrary.js:40919:121)
    at sameMap (tsserverlibrary.js:452:36)
    at getWidenedTypeWithContext (tsserverlibrary.js:40919:42)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at sameMap (tsserverlibrary.js:447:29)
    at getWidenedTypeWithContext (tsserverlibrary.js:40926:63)
    at getWidenedProperty (tsserverlibrary.js:40875:26)
    at getWidenedTypeOfObjectLiteral (tsserverlibrary.js:40892:46)
    at getWidenedTypeWithContext (tsserverlibrary.js:40915:27)
    at (anonymous) (tsserverlibrary.js:40919:121)
    at sameMap (tsserverlibrary.js:452:36)
    at getWidenedTypeWithContext (tsserverlibrary.js:40919:42)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at sameMap (tsserverlibrary.js:447:29)
    at getWidenedTypeWithContext (tsserverlibrary.js:40926:63)
    at getWidenedProperty (tsserverlibrary.js:40875:26)
    at getWidenedTypeOfObjectLiteral (tsserverlibrary.js:40892:46)
    at getWidenedTypeWithContext (tsserverlibrary.js:40915:27)
    at (anonymous) (tsserverlibrary.js:40919:121)
    at sameMap (tsserverlibrary.js:452:36)
    at getWidenedTypeWithContext (tsserverlibrary.js:40919:42)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at sameMap (tsserverlibrary.js:447:29)
    at getWidenedTypeWithContext (tsserverlibrary.js:40926:63)
    at getWidenedProperty (tsserverlibrary.js:40875:26)
    at getWidenedTypeOfObjectLiteral (tsserverlibrary.js:40892:46)
    at getWidenedTypeWithContext (tsserverlibrary.js:40915:27)
    at (anonymous) (tsserverlibrary.js:40919:121)
    at sameMap (tsserverlibrary.js:452:36)
    at getWidenedTypeWithContext (tsserverlibrary.js:40919:42)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at sameMap (tsserverlibrary.js:447:29)
    at getWidenedTypeWithContext (tsserverlibrary.js:40926:63)
    at getWidenedProperty (tsserverlibrary.js:40875:26)
    at getWidenedTypeOfObjectLiteral (tsserverlibrary.js:40892:46)
    at getWidenedTypeWithContext (tsserverlibrary.js:40915:27)
    at (anonymous) (tsserverlibrary.js:40919:121)
    at sameMap (tsserverlibrary.js:452:36)
    at getWidenedTypeWithContext (tsserverlibrary.js:40919:42)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at sameMap (tsserverlibrary.js:447:29)
    at getWidenedTypeWithContext (tsserverlibrary.js:40926:63)
    at getWidenedProperty (tsserverlibrary.js:40875:26)
    at getWidenedTypeOfObjectLiteral (tsserverlibrary.js:40892:46)
    at getWidenedTypeWithContext (tsserverlibrary.js:40915:27)
    at (anonymous) (tsserverlibrary.js:40919:121)
    at sameMap (tsserverlibrary.js:452:36)
    at getWidenedTypeWithContext (tsserverlibrary.js:40919:42)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at sameMap (tsserverlibrary.js:447:29)
    at getWidenedTypeWithContext (tsserverlibrary.js:40926:63)
    at getWidenedProperty (tsserverlibrary.js:40875:26)
    at getWidenedTypeOfObjectLiteral (tsserverlibrary.js:40892:46)
    at getWidenedTypeWithContext (tsserverlibrary.js:40915:27)
    at (anonymous) (tsserverlibrary.js:40919:121)
    at sameMap (tsserverlibrary.js:452:36)
    at getWidenedTypeWithContext (tsserverlibrary.js:40919:42)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at sameMap (tsserverlibrary.js:447:29)
    at getWidenedTypeWithContext (tsserverlibrary.js:40926:63)
    at getWidenedProperty (tsserverlibrary.js:40875:26)
    at getWidenedTypeOfObjectLiteral (tsserverlibrary.js:40892:46)
    at getWidenedTypeWithContext (tsserverlibrary.js:40915:27)
    at (anonymous) (tsserverlibrary.js:40919:121)
    at sameMap (tsserverlibrary.js:452:36)
    at getWidenedTypeWithContext (tsserverlibrary.js:40919:42)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at sameMap (tsserverlibrary.js:447:29)
    at getWidenedTypeWithContext (tsserverlibrary.js:40926:63)
    at getWidenedProperty (tsserverlibrary.js:40875:26)
    at getWidenedTypeOfObjectLiteral (tsserverlibrary.js:40892:46)
    at getWidenedTypeWithContext (tsserverlibrary.js:40915:27)
    at (anonymous) (tsserverlibrary.js:40919:121)
    at sameMap (tsserverlibrary.js:452:36)
    at getWidenedTypeWithContext (tsserverlibrary.js:40919:42)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at sameMap (tsserverlibrary.js:447:29)
    at getWidenedTypeWithContext (tsserverlibrary.js:40926:63)
    at getWidenedProperty (tsserverlibrary.js:40875:26)
    at getWidenedTypeOfObjectLiteral (tsserverlibrary.js:40892:46)
    at getWidenedTypeWithContext (tsserverlibrary.js:40915:27)
    at (anonymous) (tsserverlibrary.js:40919:121)
    at sameMap (tsserverlibrary.js:452:36)
    at getWidenedTypeWithContext (tsserverlibrary.js:40919:42)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at sameMap (tsserverlibrary.js:447:29)
    at getWidenedTypeWithContext (tsserverlibrary.js:40926:63)
    at getWidenedProperty (tsserverlibrary.js:40875:26)
    at getWidenedTypeOfObjectLiteral (tsserverlibrary.js:40892:46)
    at getWidenedTypeWithContext (tsserverlibrary.js:40915:27)
    at (anonymous) (tsserverlibrary.js:40919:121)
    at sameMap (tsserverlibrary.js:452:36)
    at getWidenedTypeWithContext (tsserverlibrary.js:40919:42)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at sameMap (tsserverlibrary.js:447:29)
    at getWidenedTypeWithContext (tsserverlibrary.js:40926:63)
    at getWidenedType (tsserverlibrary.js:40907:19)
    at getReturnTypeFromBody (tsserverlibrary.js:47906:30)
    at getReturnTypeOfSignature (tsserverlibrary.js:36237:27)
    at getTypeOfExpression (tsserverlibrary.js:49070:27)
    at checkDeclarationInitializer (tsserverlibrary.js:48968:23)
    at getTypeForVariableLikeDeclaration (tsserverlibrary.js:33458:27)
    at getWidenedTypeForVariableLikeDeclaration (tsserverlibrary.js:33684:55)
    at getJSSpecialType (tsserverlibrary.js:33819:20)
    at getTypeOfVariableOrParameterOrProperty (tsserverlibrary.js:33746:27)
    at getTypeOfSymbol (tsserverlibrary.js:34024:23)
    at checkIdentifier (tsserverlibrary.js:43055:48)
    at checkExpressionWorker (tsserverlibrary.js:49136:27)
    at checkExpression (tsserverlibrary.js:49108:41)
    at checkExpressionCached (tsserverlibrary.js:48957:37)
    at (anonymous) (tsserverlibrary.js:47970:31)
    at traverse (tsserverlibrary.js:8521:27)
    at visitNodes (tsserverlibrary.js:15132:29)
    at forEachChild (tsserverlibrary.js:15356:23)
    at traverse (tsserverlibrary.js:8537:30)
    at forEachReturnStatement (tsserverlibrary.js:8517:15)
    at checkAndAggregateReturnExpressionTypes (tsserverlibrary.js:47967:15)
    at getReturnTypeFromBody (tsserverlibrary.js:47853:28)
    at getReturnTypeOfSignature (tsserverlibrary.js:36237:27)
    at getTypeOfExpression (tsserverlibrary.js:49070:27)
    at getAssignedTypeOfBinaryExpression (tsserverlibrary.js:41965:16)
    at getAssignedType (tsserverlibrary.js:41991:27)
    at getInitialOrAssignedType (tsserverlibrary.js:42042:16)
    at getTypeAtFlowAssignment (tsserverlibrary.js:42393:68)
    at getTypeAtFlowNode (tsserverlibrary.js:42327:31)
    at getFlowTypeOfReference (tsserverlibrary.js:42280:50)
    at checkIdentifier (tsserverlibrary.js:43113:27)
    at checkExpressionWorker (tsserverlibrary.js:49136:27)
    at checkExpression (tsserverlibrary.js:49108:41)
    at getContextuallyTypedParameterType (tsserverlibrary.js:43638:42)
    at getTypeForVariableLikeDeclaration (tsserverlibrary.js:33451:110)
    at getWidenedTypeForVariableLikeDeclaration (tsserverlibrary.js:33684:55)
    at getJSSpecialType (tsserverlibrary.js:33819:20)
    at getTypeOfVariableOrParameterOrProperty (tsserverlibrary.js:33746:27)
    at getTypeOfSymbol (tsserverlibrary.js:34024:23)
    at checkIdentifier (tsserverlibrary.js:43055:48)
    at checkExpressionWorker (tsserverlibrary.js:49136:27)
    at checkExpression (tsserverlibrary.js:49108:41)
    at checkNonNullExpression (tsserverlibrary.js:45508:36)
    at checkRightHandSideOfForOf (tsserverlibrary.js:51594:33)
    at getTypeForVariableLikeDeclaration (tsserverlibrary.js:33407:23)
    at getWidenedTypeForVariableLikeDeclaration (tsserverlibrary.js:33684:55)
    at getJSSpecialType (tsserverlibrary.js:33819:20)
    at getTypeOfVariableOrParameterOrProperty (tsserverlibrary.js:33746:27)
    at getTypeOfSymbol (tsserverlibrary.js:34024:23)
    at checkIdentifier (tsserverlibrary.js:43055:48)
    at checkExpressionWorker (tsserverlibrary.js:49136:27)
    at checkExpression (tsserverlibrary.js:49108:41)
    at getTypeOfExpression (tsserverlibrary.js:49076:57)
    at getRegularTypeOfExpression (tsserverlibrary.js:54156:47)
    at getTypeOfNode (tsserverlibrary.js:54067:23)
    at getTypeAtLocation (tsserverlibrary.js:29313:30)
    at getTypeNameForPythia (e:\src\Pythia4TypeScript\usagedatabuilder\typeName.js:13:25)
    at processPropertyAccessExpression (e:\src\Pythia4TypeScript\usagedatabuilder\builder.js:118:36)
    at processNode (e:\src\Pythia4TypeScript\usagedatabuilder\builder.js:102:12)
    at visitNodes (tsserverlibrary.js:15132:29)
    at forEachChild (tsserverlibrary.js:15310:20)
    at NodeObject.forEachChild (tsserverlibrary.js:110781:22)
    at processNode (e:\src\Pythia4TypeScript\usagedatabuilder\builder.js:110:17)
    at visitNode (tsserverlibrary.js:15123:23)
    at forEachChild (tsserverlibrary.js:15336:23)
    at NodeObject.forEachChild (tsserverlibrary.js:110781:22)
    at processNode (e:\src\Pythia4TypeScript\usagedatabuilder\builder.js:110:17)
    at visitNode (tsserverlibrary.js:15123:23)
    at forEachChild (tsserverlibrary.js:15336:23)

```

**Comment by weswigham** [comment]
@RyanCavanaugh `getJSSpecialType` is a red herring - this is just caused by an-almost-circularly referential object type being put through `getWidenedType`. Specifically, in the linked repo, the evolving array type in `marktext\src\muya\lib\parser\parse.js` in `tokenizerFac` produces an array with ~13 members in its union that each look roughly like `type TokenDesc = { type: string, ... fields that don't matter ..., parent: TokenDesc[] }` except because `parent` is a reference to the unwidened evolving array type we also need to widen it, and because we locked in a different type within each literal thanks to CFA, we have ~13 unique views on what the overall array type is (each with 1-13 members), all of which need to be recurred into and reconciled! And widened types aren't cached at all, to whit, so we produce a ton of types (some very similar/identical to one another) during this process, leading to the OOM.
