### ISSUE TITLE
Debug failure: Found typedef tag attached to node which it should not be! at nameForNamelessJSDocTypedef 

### ISSUE THREAD

**Issue by minestarks** [Microsoft/TypeScript#26693]
**TypeScript Version**: 3.0.3

**Repro**

1. `git clone https://github.com/SVG-Edit/svgedit.git`
2. `tsc --init` to create a project file
3. Set `allowJs` and `checkJs` in `tsconfig.json`
4. `tsc`

```
Error: Debug Failure. Found typedef tag attached to node which it should not be!
    at nameForNamelessJSDocTypedef (tsc.js:10163:26)
    at getNameOfJSDocTypedef (tsc.js:10171:36)
    at Object.getNameOfDeclaration (tsc.js:10214:24)
    at Object.hasDynamicName (tsc.js:8395:23)
    at declareSymbol (tsc.js:17648:33)
    at declareModuleMember (tsc.js:17728:33)
    at bindBlockScopedDeclaration (tsc.js:18750:25)
    at delayedBindJSDocTypedefTag (tsc.js:18783:21)
    at bindSourceFile (tsc.js:17539:17)
    at Object.bindSourceFile (tsc.js:17489:9)
```

**Comment by sandersn** [comment]
The problem is that parsing of a typedef's type fails, causing the parser to treat jsdoc as the name. Later, the binder assumes that the parser never gets confused and has an assert to prove it. 

The assert is over-optimistic and should be removed until we can parse every possible thing that people might put in a JSDoc type position. Which will never happen. For one thing, the unicode committee keeps adding new emoji all the time!

Here's an example:

```js
/** @typedef {GenericArray.<module:locale.LocaleStrings>} module:locale.LocaleArray */
```

We don't parse `module:locale.LocaleStrings` as a valid type. The resulting typedef has 

```js
{ 
  type: "GenericArray<module>", 
  name: undefined, 
  comment: ":locale.LocaleStrings>} module:locale.LocaleArray" 
}
```
