### ISSUE TITLE
Signature help crash "Cannot read property 'kind' of undefined"

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#26832]
**TypeScript Version:**  3.1.0-dev.20180901

**Search Terms:** none

**Code**
The code I worked on when this happened is a file with some variant of the types mentioned in #26155. Not entirely sure how the file looked like at that point.

```
[Error  - 9:55:51 AM] 'signatureHelp' request failed with error.
Error processing request. Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at pipelineEmitWithHint (_redacted_\node_modules\typescript\lib\tsserver.js:79673:39)
    at emitNodeWithComments (_redacted_\node_modules\typescript\lib\tsserver.js:78820:17)
    at pipelineEmitWithComments (_redacted_\node_modules\typescript\lib\tsserver.js:79655:13)
    at print (_redacted_\node_modules\typescript\lib\tsserver.js:79582:13)
    at Object.writeNode (_redacted_\node_modules\typescript\lib\tsserver.js:79515:13)
    at _redacted_\node_modules\typescript\lib\tsserver.js:100108:25
    at Object.mapToDisplayParts (_redacted_\node_modules\typescript\lib\tsserver.js:90510:13)
    at createSignatureHelpParameterForTypeParameter (_redacted_\node_modules\typescript\lib\tsserver.js:100106:35)
    at _redacted_\node_modules\typescript\lib\tsserver.js:100046:71
    at Array.map (<anonymous>)
    at getTypeHelpItem (_redacted_\node_modules\typescript\lib\tsserver.js:100046:45)
    at createTypeHelpItems (_redacted_\node_modules\typescript\lib\tsserver.js:100040:26)
    at _redacted_\node_modules\typescript\lib\tsserver.js:99633:23
    at Object.runWithCancellationToken (_redacted_\node_modules\typescript\lib\tsserver.js:29892:28)
    at Object.getSignatureHelpItems (_redacted_\node_modules\typescript\lib\tsserver.js:99630:32)
    at Object.getSignatureHelpItems (_redacted_\node_modules\typescript\lib\tsserver.js:113010:37)
    at IOSession.Session.getSignatureHelpItems (_redacted_\node_modules\typescript\lib\tsserver.js:120682:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (_redacted_\node_modules\typescript\lib\tsserver.js:119698:61)
    at _redacted_\node_modules\typescript\lib\tsserver.js:121093:88
    at IOSession.Session.executeWithRequestId (_redacted_\node_modules\typescript\lib\tsserver.js:121084:28)
    at IOSession.Session.executeCommand (_redacted_\node_modules\typescript\lib\tsserver.js:121093:33)
    at IOSession.Session.onMessage (_redacted_\node_modules\typescript\lib\tsserver.js:121113:35)
    at Interface.<anonymous> (_redacted_\node_modules\typescript\lib\tsserver.js:122367:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by RyanCavanaugh** [comment]
No repro provided
