### ISSUE TITLE
getApplicableRefactors on file with recursive types freezes TSServer

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/TypeScript#26833]
**TypeScript Version:**  3.1.0-dev.20180901

**Search Terms:** none

When working on a file with several recursive types, the TSServer process got stuck in an endless loop and continued building up memory. Later this error showed up in the error console in VSCode:
```
[Info  - 10:12:55 AM] Using tsserver from: c:\Users\domin\Documents\Visual Studio 2017\Repositories\shared-utils\node_modules\typescript\lib
[Error  - 10:12:55 AM] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (c:\Users\domin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\out\typescriptServiceClient.js:413:32)
	at ChildProcess.handle.onExit (c:\Users\domin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\out\typescriptServiceClient.js:326:30)
	at emitTwo (events.js:131:20)
	at ChildProcess.emit (events.js:214:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

**Related Issues:** #26155

**Comment by AlCalzone** [comment]
Cannot reproduce atm, closing for now.
