### ISSUE TITLE
"'quickinfo' request failed with error." and "'completionInfo' request failed with error."

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#27025]
**TypeScript Version:**  3.1.0-dev.20180907

**Search Terms:** TypeError, suggestions, quickinfo, completionInfo, kind

```
[Error  - 7:29:09 AM] 'quickinfo' request failed with error.
Error processing request. Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at getRootDeclaration (C:\nodejs\node_modules\typescript\lib\tsserver.js:10176:21)
    at Object.isCatchClauseVariableDeclarationOrBindingElement (C:\nodejs\node_modules\typescript\lib\tsserver.js:8146:20)
    at getTypeOfVariableOrParameterOrPropertyWorker (C:\nodejs\node_modules\typescript\lib\tsserver.js:34333:20)
    at getTypeOfVariableOrParameterOrProperty (C:\nodejs\node_modules\typescript\lib\tsserver.js:34314:48)
    at getTypeOfSymbol (C:\nodejs\node_modules\typescript\lib\tsserver.js:34597:24)
    at resolveExternalModuleTypeByLiteral (C:\nodejs\node_modules\typescript\lib\tsserver.js:36765:28)
    at checkCallExpression (C:\nodejs\node_modules\typescript\lib\tsserver.js:48244:24)
    at checkExpressionWorker (C:\nodejs\node_modules\typescript\lib\tsserver.js:50035:28)
    at checkExpression (C:\nodejs\node_modules\typescript\lib\tsserver.js:49972:42)
    at checkExpressionCached (C:\nodejs\node_modules\typescript\lib\tsserver.js:49816:38)
    at getTypeOfExpression (C:\nodejs\node_modules\typescript\lib\tsserver.js:49939:28)
    at checkDeclarationInitializer (C:\nodejs\node_modules\typescript\lib\tsserver.js:49827:24)
    at getTypeForVariableLikeDeclaration (C:\nodejs\node_modules\typescript\lib\tsserver.js:34017:28)
    at getWidenedTypeForVariableLikeDeclaration (C:\nodejs\node_modules\typescript\lib\tsserver.js:34278:56)
    at getTypeOfVariableOrParameterOrPropertyWorker (C:\nodejs\node_modules\typescript\lib\tsserver.js:34392:24)
    at getTypeOfVariableOrParameterOrProperty (C:\nodejs\node_modules\typescript\lib\tsserver.js:34314:48)
    at getTypeOfSymbol (C:\nodejs\node_modules\typescript\lib\tsserver.js:34597:24)
    at checkIdentifier (C:\nodejs\node_modules\typescript\lib\tsserver.js:43987:49)
    at checkExpressionWorker (C:\nodejs\node_modules\typescript\lib\tsserver.js:50000:28)
    at checkExpression (C:\nodejs\node_modules\typescript\lib\tsserver.js:49972:42)
    at checkExpressionForMutableLocation (C:\nodejs\node_modules\typescript\lib\tsserver.js:49876:24)
    at checkPropertyAssignment (C:\nodejs\node_modules\typescript\lib\tsserver.js:49887:20)
    at checkObjectLiteral (C:\nodejs\node_modules\typescript\lib\tsserver.js:45440:83)
    at checkExpressionWorker (C:\nodejs\node_modules\typescript\lib\tsserver.js:50024:28)
    at checkExpression (C:\nodejs\node_modules\typescript\lib\tsserver.js:49972:42)
    at checkExpressionWithContextualType (C:\nodejs\node_modules\typescript\lib\tsserver.js:49800:26)
    at checkApplicableSignature (C:\nodejs\node_modules\typescript\lib\tsserver.js:47261:35)
    at chooseOverload (C:\nodejs\node_modules\typescript\lib\tsserver.js:47566:26)
    at resolveCall (C:\nodejs\node_modules\typescript\lib\tsserver.js:47516:26)
    at resolveCallExpression (C:\nodejs\node_modules\typescript\lib\tsserver.js:47812:20)
    at resolveSignature (C:\nodejs\node_modules\typescript\lib\tsserver.js:48077:28)
    at getResolvedSignature (C:\nodejs\node_modules\typescript\lib\tsserver.js:48121:26)
    at getContextualTypeForArgumentAtIndex (C:\nodejs\node_modules\typescript\lib\tsserver.js:44701:118)
    at getContextualTypeForArgument (C:\nodejs\node_modules\typescript\lib\tsserver.js:44696:50)
    at getContextualType (C:\nodejs\node_modules\typescript\lib\tsserver.js:44993:28)
    at Object.getContextualType (C:\nodejs\node_modules\typescript\lib\tsserver.js:29828:31)
    at getSymbolAtLocationForQuickInfo (C:\nodejs\node_modules\typescript\lib\tsserver.js:113983:42)
    at Object.getQuickInfoAtPosition (C:\nodejs\node_modules\typescript\lib\tsserver.js:113332:26)
    at IOSession.Session.getQuickInfoWorker (C:\nodejs\node_modules\typescript\lib\tsserver.js:120968:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\nodejs\node_modules\typescript\lib\tsserver.js:120078:61)
    at C:\nodejs\node_modules\typescript\lib\tsserver.js:121542:88
    at IOSession.Session.executeWithRequestId (C:\nodejs\node_modules\typescript\lib\tsserver.js:121533:28)
    at IOSession.Session.executeCommand (C:\nodejs\node_modules\typescript\lib\tsserver.js:121542:33)
    at IOSession.Session.onMessage (C:\nodejs\node_modules\typescript\lib\tsserver.js:121562:35)
    at Interface.<anonymous> (C:\nodejs\node_modules\typescript\lib\tsserver.js:122816:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Code**

```ts
// the code is in a plain JS file, but I'm using jsconfig.json
const Joi = require('joi'); // returns any
```

`jsconfig.json`
```json
{
  "compilerOptions": {
    "checkJs": true,
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitAny": false,
    "module": "commonjs",
    "target": "es2017",
    "alwaysStrict": false,
    "moduleResolution": "node",
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitUseStrict": true,
    "strictNullChecks": false,
    "baseUrl": "./",
    "rootDir": "./",
    "allowSyntheticDefaultImports": true,
    "paths": {
      "*": [
        "./namespaces/*.d.ts",
        "./node_modules/@types/*",
        "*"
      ]
    }
  }
}
```

Trying to type `Joi.` gives:

```
[Error  - 7:31:56 AM] 'completionInfo' request failed with error.
Error processing request. Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at getRootDeclaration (C:\nodejs\node_modules\typescript\lib\tsserver.js:10176:21)
    at Object.isCatchClauseVariableDeclarationOrBindingElement (C:\nodejs\node_modules\typescript\lib\tsserver.js:8146:20)
    at getTypeOfVariableOrParameterOrPropertyWorker (C:\nodejs\node_modules\typescript\lib\tsserver.js:34333:20)
    at getTypeOfVariableOrParameterOrProperty (C:\nodejs\node_modules\typescript\lib\tsserver.js:34314:48)
    at getTypeOfSymbol (C:\nodejs\node_modules\typescript\lib\tsserver.js:34597:24)
    at resolveExternalModuleTypeByLiteral (C:\nodejs\node_modules\typescript\lib\tsserver.js:36765:28)
    at checkCallExpression (C:\nodejs\node_modules\typescript\lib\tsserver.js:48244:24)
    at checkExpressionWorker (C:\nodejs\node_modules\typescript\lib\tsserver.js:50035:28)
    at checkExpression (C:\nodejs\node_modules\typescript\lib\tsserver.js:49972:42)
    at checkExpressionCached (C:\nodejs\node_modules\typescript\lib\tsserver.js:49816:38)
    at getTypeOfExpression (C:\nodejs\node_modules\typescript\lib\tsserver.js:49939:28)
    at checkDeclarationInitializer (C:\nodejs\node_modules\typescript\lib\tsserver.js:49827:24)
    at getTypeForVariableLikeDeclaration (C:\nodejs\node_modules\typescript\lib\tsserver.js:34017:28)
    at getWidenedTypeForVariableLikeDeclaration (C:\nodejs\node_modules\typescript\lib\tsserver.js:34278:56)
    at getTypeOfVariableOrParameterOrPropertyWorker (C:\nodejs\node_modules\typescript\lib\tsserver.js:34392:24)
    at getTypeOfVariableOrParameterOrProperty (C:\nodejs\node_modules\typescript\lib\tsserver.js:34314:48)
    at getTypeOfSymbol (C:\nodejs\node_modules\typescript\lib\tsserver.js:34597:24)
    at checkIdentifier (C:\nodejs\node_modules\typescript\lib\tsserver.js:43987:49)
    at checkExpressionWorker (C:\nodejs\node_modules\typescript\lib\tsserver.js:50000:28)
    at checkExpression (C:\nodejs\node_modules\typescript\lib\tsserver.js:49972:42)
    at getTypeOfExpression (C:\nodejs\node_modules\typescript\lib\tsserver.js:49939:58)
    at getRegularTypeOfExpression (C:\nodejs\node_modules\typescript\lib\tsserver.js:55063:48)
    at getTypeOfNode (C:\nodejs\node_modules\typescript\lib\tsserver.js:54972:24)
    at Object.getTypeAtLocation (C:\nodejs\node_modules\typescript\lib\tsserver.js:29794:31)
    at getTypeScriptMemberSymbols (C:\nodejs\node_modules\typescript\lib\tsserver.js:93359:51)
    at getCompletionData (C:\nodejs\node_modules\typescript\lib\tsserver.js:93269:17)
    at Object.getCompletionsAtPosition (C:\nodejs\node_modules\typescript\lib\tsserver.js:92494:34)
    at Object.getCompletionsAtPosition (C:\nodejs\node_modules\typescript\lib\tsserver.js:113311:35)
    at IOSession.Session.getCompletions (C:\nodejs\node_modules\typescript\lib\tsserver.js:121064:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\nodejs\node_modules\typescript\lib\tsserver.js:120126:61)
    at C:\nodejs\node_modules\typescript\lib\tsserver.js:121542:88
    at IOSession.Session.executeWithRequestId (C:\nodejs\node_modules\typescript\lib\tsserver.js:121533:28)
    at IOSession.Session.executeCommand (C:\nodejs\node_modules\typescript\lib\tsserver.js:121542:33)
    at IOSession.Session.onMessage (C:\nodejs\node_modules\typescript\lib\tsserver.js:121562:35)
    at Interface.<anonymous> (C:\nodejs\node_modules\typescript\lib\tsserver.js:122816:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

```

**Expected behavior:**

Return `joi.Root` (in this case)

**Actual behavior:**

Typed library is returning `any`

**Comment by minestarks** [comment]
I have a couple more repros of this if it helps

```
git clone --depth=1 https://github.com/ajaxorg/ace
cd ace
tsc --init
tsc --allowJs --checkJs
```

```

TypeError: Cannot read property 'kind' of undefined
    at getRootDeclaration (node_modules\typescript\lib\tsc.js:8144:21)
    at Object.isCatchClauseVariableDeclarationOrBindingElement (node_modules\typescript\lib\tsc.js:6314:20)
    at getTypeOfVariableOrParameterOrPropertyWorker (node_modules\typescript\lib\tsc.js:28741:20)
    at getTypeOfVariableOrParameterOrProperty (node_modules\typescript\lib\tsc.js:28725:48)
    at getTypeOfSymbol (node_modules\typescript\lib\tsc.js:28990:24)
    at getInitializerTypeFromAssignmentDeclaration (node_modules\typescript\lib\tsc.js:28566:41)
    at getWidenedTypeFromAssignmentDeclaration (node_modules\typescript\lib\tsc.js:28507:86)
    at getTypeOfFuncClassEnumModuleWorker (node_modules\typescript\lib\tsc.js:28928:34)
    at getTypeOfFuncClassEnumModule (node_modules\typescript\lib\tsc.js:28908:51)
    at getTypeOfSymbol (node_modules\typescript\lib\tsc.js:28993:24)
```

**Comment by RyanCavanaugh** [comment]
Regression from 3.0; confirmed call stack on master

Files in this repo have syntax errors.

**Comment by RyanCavanaugh** [comment]
Minimal repro (js):
```js
module.exports = window.nonprop;
exports.foo = bar;
```
Root cause seems to be that we're trying to walk up the `unknown` symbol to find a declaration to attach `.foo` to

**Comment by sandersn** [comment]
I'm surprised we haven't seen more of this; I suspect it's because the mixed `module.exports=` + `export.foo=` pattern isn't that common. However, it'll happen any time that the exported symbol is unknown; getCommonJsExportEquals blithely clones unknownSymbol and proceeds to stick the `exports.foo=` properties onto it.

This causes problems later, because the compiler checks for unknownSymbol with `===`. The fix is to not stick properties onto a clone of unknownSymbol. This makes the correct errors appear and removes the crash.
