### ISSUE TITLE
Debug Failure. False expression. at getChildListThatStartsWithOpenerToken

### ISSUE THREAD

**Issue by cevek** [microsoft/TypeScript#27058]
**TypeScript Version:**  3.1.0-dev.20180901

**Search Terms:**

**Code**

```
Error: Debug Failure. False expression.
    at getChildListThatStartsWithOpenerToken (/usr/local/lib/node_modules/typescript/lib/tsserver.js:100012:22)
    at getArgumentOrParameterListAndIndex (/usr/local/lib/node_modules/typescript/lib/tsserver.js:99730:32)
    at getArgumentOrParameterListInfo (/usr/local/lib/node_modules/typescript/lib/tsserver.js:99715:24)
    at getImmediatelyContainingArgumentInfo (/usr/local/lib/node_modules/typescript/lib/tsserver.js:99765:28)
    at getImmediatelyContainingArgumentOrContextualParameterInfo (/usr/local/lib/node_modules/typescript/lib/tsserver.js:99826:80)
    at _loop_6 (/usr/local/lib/node_modules/typescript/lib/tsserver.js:99997:36)
    at getContainingArgumentInfo (/usr/local/lib/node_modules/typescript/lib/tsserver.js:100003:31)
    at Object.getSignatureHelpItems (/usr/local/lib/node_modules/typescript/lib/tsserver.js:99618:32)
    at Object.getSignatureHelpItems (/usr/local/lib/node_modules/typescript/lib/tsserver.js:113010:37)
    at IOSession.Session.getSignatureHelpItems (/usr/local/lib/node_modules/typescript/lib/tsserver.js:120682:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119698:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:121093:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:121084:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:121093:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:121113:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:122367:27)```
```

**Comment by cevek** [comment]
After landing https://github.com/Microsoft/TypeScript/pull/27006

**Comment by RyanCavanaugh** [comment]
No repro provided
