### ISSUE TITLE
tsc dependencies not included

### ISSUE THREAD

**Issue by AMDphreak** [Microsoft/TypeScript#27116]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**
Cython

**Code**

```ts
$ pip3 install tsc
Collecting tsc
  Using cached https://files.pythonhosted.org/packages/21/13/0884f45d204d6ee46e59cbf6cedd78b5e7ad0f7b7532a0734cf72ea8705b/tsc-0.3.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\rjamd\AppData\Local\Temp\pip-install-64gx7iea\tsc\setup.py", line 3, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\rjamd\AppData\Local\Temp\pip-install-64gx7iea\tsc\
```
```
$ pip3 install tsc
Collecting tsc
  Using cached https://files.pythonhosted.org/packages/21/13/0884f45d204d6ee46e59cbf6cedd78b5e7ad0f7b7532a0734cf72ea8705b/tsc-0.3.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\rjamd\AppData\Local\Temp\pip-install-s4iw4aow\tsc\setup.py", line 4, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\rjamd\AppData\Local\Temp\pip-install-s4iw4aow\tsc\
```

**Expected behavior:**
pip installer automatically downloads dependencies:
1. Cython
2. numpy

**Actual behavior:**
Fails to call modules and exits with errors.

**Playground Link:** 

**Related Issues:** 
https://github.com/Microsoft/vscode/issues/58728

**Comment by mattmccutchen** [comment]
You have the wrong `tsc`.  Go [here](https://github.com/observerss/tsc) to file an issue.

**Comment by AMDphreak** [comment]
> You have the wrong `tsc`. Go [here](https://github.com/observerss/tsc) to file an issue.

Thanks. Not sure how I got onto installing that while following a TypeScript install tutorial.
