### ISSUE TITLE
Compiler (still) crashes with "Declaration to checkResolvedBlockScopedVariable is undefined"

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/TypeScript#27134]
Similar/same as https://github.com/Microsoft/TypeScript/issues/27061, but still happening in `3.1.0-dev.20180915`.

Introduced in `3.1.0-dev.20180906`, last working version was `3.1.0-dev.20180905`.

Stack trace:
```
Debug Failure. Declaration to checkResolvedBlockScopedVariable is undefined

    at checkResolvedBlockScopedVariable (node_modules/typescript/lib/typescript.js:31697:33)
    at resolveNameHelper (node_modules/typescript/lib/typescript.js:31538:25)
    at resolveName (node_modules/typescript/lib/typescript.js:31219:20)
    at getResolvedSymbol (node_modules/typescript/lib/typescript.js:43026:21)
    at checkIdentifier (node_modules/typescript/lib/typescript.js:44474:26)
    at checkExpressionWorker (node_modules/typescript/lib/typescript.js:50599:28)
    at checkExpression (node_modules/typescript/lib/typescript.js:50571:42)
    at checkNonNullExpression (node_modules/typescript/lib/typescript.js:47062:37)
    at checkPropertyAccessExpressionOrQualifiedName (node_modules/typescript/lib/typescript.js:47088:28)
    at checkPropertyAccessExpression (node_modules/typescript/lib/typescript.js:47081:20)
```

**TypeScript Version:**  3.1.0-dev.20180915

**Comment by felixfbecker** [comment]
@Kingwl I am not saying that code triggers it. I don't know what triggers this, it's a codebase with thousands of lines of code, it could be anything. But the stack trace is real

**Comment by minestarks** [comment]
@RyanCavanaugh I have a quite a few repros of this

Version 3.1.0-dev.20180925

```
git clone --depth=1 https://github.com/adobe/brackets
cd brackets
tsc --init
tsc --allowJs --checkJs
```
```
Error: Debug Failure. Declaration to checkResolvedBlockScopedVariable is undefined
    at checkResolvedBlockScopedVariable (node_modules\typescript\lib\tsc.js:25937:33)
    at resolveNameHelper (node_modules\typescript\lib\tsc.js:25788:25)
    at resolveName (node_modules\typescript\lib\tsc.js:25555:20)
    at resolveEntityName (node_modules\typescript\lib\tsc.js:26243:26)
    at resolveTypeReferenceName (node_modules\typescript\lib\tsc.js:31245:20)
    at getTypeFromTypeReference (node_modules\typescript\lib\tsc.js:31412:30)
    at checkTypeReferenceNode (node_modules\typescript\lib\tsc.js:42928:24)
    at checkSourceElement (node_modules\typescript\lib\tsc.js:45932:28)
    at Object.forEach (node_modules\typescript\lib\tsc.js:169:30)
    at checkUnionOrIntersectionType (node_modules\typescript\lib\tsc.js:42993:16)
```

**Comment by RyanCavanaugh** [comment]
Validated 3.1 call stack. Regression from 3.0.
