### ISSUE TITLE
Callstack exceeded in typescript @ next

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#27142]
I haven't been able to reproduce using a small repro, but when I remove the jsdoc-s from all of our enums the issue goes away. Further this started happening when I removed an invalid type from the jsdocs.

original code:
````
    /**
     * @enum {String} Renderer2dEnums.LineEndCapStyle
     * Indicates how the end points of every line are drawn.
     * See *[CanvasRendering2dContext.lineCap property][1]* for more.
     *
     * [1]: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D.lineCap
     */
    export const enum LineEndCapStyle
    {
        /** Ends of lines are squared off at endpoints */
        BUTT,

        /** Ends of lines are rounded */
        ROUND,

        /** Ends of lines are squared off by adding a box with an equal
         * width and half the height of the line's thickness */
        SQUARE
    }
````
Fix invalid type, which causes callstack issue:
````
    /**
     * @enum Renderer2dEnums.LineEndCapStyle
     * Indicates how the end points of every line are drawn.
     * See *[CanvasRendering2dContext.lineCap property][1]* for more.
     *
     * [1]: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D.lineCap
     */
    export const enum LineEndCapStyle
    {
        /** Ends of lines are squared off at endpoints */
        BUTT,

        /** Ends of lines are rounded */
        ROUND,

        /** Ends of lines are squared off by adding a box with an equal
         * width and half the height of the line's thickness */
        SQUARE
    }
````

Code that compiles without issue:
````
    /**
     * Indicates how the end points of every line are drawn.
     * See *[CanvasRendering2dContext.lineCap property][1]* for more.
     *
     * [1]: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D.lineCap
     */
    export const enum LineEndCapStyle
    {
        /** Ends of lines are squared off at endpoints */
        BUTT,

        /** Ends of lines are rounded */
        ROUND,

        /** Ends of lines are squared off by adding a box with an equal
         * width and half the height of the line's thickness */
        SQUARE
    }
````
Stack:
````
Using tsc v3.1.0-dev.20180915
c:\src\oven\node_modules\typescript\lib\tsc.js:69191
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at isSelfReferenceLocation (c:\src\oven\node_modules\typescript\lib\tsc.js:25741:41)
    at resolveNameHelper (c:\src\oven\node_modules\typescript\lib\tsc.js:25664:21)
    at resolveName (c:\src\oven\node_modules\typescript\lib\tsc.js:25496:20)
    at resolveEntityName (c:\src\oven\node_modules\typescript\lib\tsc.js:26184:26)
    at resolveEntityName (c:\src\oven\node_modules\typescript\lib\tsc.js:26192:33)
    at resolveTypeReferenceName (c:\src\oven\node_modules\typescript\lib\tsc.js:31180:20)
    at getTypeFromTypeReference (c:\src\oven\node_modules\typescript\lib\tsc.js:31338:30)
    at getTypeFromTypeNode (c:\src\oven\node_modules\typescript\lib\tsc.js:32602:28)
    at getTypeFromTypeNode (c:\src\oven\node_modules\typescript\lib\tsc.js:32627:28)
    at getTypeReferenceType (c:\src\oven\node_modules\typescript\lib\tsc.js:31193:49)
````

**Comment by andy-ms** [comment]
@paulvanbrenk Any chance you could reproduce using `node --stack-trace-limit=100 path/to/tsc.js`? Hard to tell what the recursion is here.
#27076 Should have made it so the `@enum` tag has no effect in TS, but there may be other locations we forgot about. CC @sandersn

**Comment by paulvanbrenk** [comment]
sure thing.... I cut of the output after the 4rd repetition:

````
RangeError: Maximum call stack size exceeded
    at resolveNameHelper (tsc.js:25569:38)
    at resolveName (tsc.js:25496:20)
    at resolveEntityName (tsc.js:26184:26)
    at resolveEntityName (tsc.js:26192:33)
    at resolveTypeReferenceName (tsc.js:31180:20)
    at getTypeFromTypeReference (tsc.js:31338:30)
    at getTypeFromTypeNode (tsc.js:32602:28)
    at getTypeFromTypeNode (tsc.js:32627:28)
    at getTypeReferenceType (tsc.js:31193:49)
    at getTypeFromTypeReference (tsc.js:31339:28)
    at getTypeFromTypeNode (tsc.js:32602:28)
    at getTypeFromTypeNode (tsc.js:32627:28)
    at getTypeReferenceType (tsc.js:31193:49)
    at getTypeFromTypeReference (tsc.js:31339:28)
    at getTypeFromTypeNode (tsc.js:32602:28)
    at getTypeFromTypeNode (tsc.js:32627:28)
    at getTypeReferenceType (tsc.js:31193:49)
    at getTypeFromTypeReference (tsc.js:31339:28)
    at getTypeFromTypeNode (tsc.js:32602:28)
    at getTypeFromTypeNode (tsc.js:32627:28)
    at getTypeReferenceType (tsc.js:31193:49)
    at getTypeFromTypeReference (tsc.js:31339:28)
    at getTypeFromTypeNode (tsc.js:32602:28)
    at getTypeFromTypeNode (tsc.js:32627:28)
    at getTypeReferenceType (tsc.js:31193:49)
````

**Comment by andy-ms** [comment]
Thanks, I can reproduce this with:
```js
/** @enum {E} */
const E = { x: 0 };
```

**Comment by paulvanbrenk** [comment]
Thanks for the quick investigation @andy-ms, as this would block us from adapting TS 3.1.

**Comment by sandersn** [comment]
I have a fix, although it seems like it's abusing our existing circularity detection infrastructure. I'll send it out after I add a new error message.

**Comment by sandersn** [comment]
Note that with `checkJs` on, my fix will add a new error "Enum type 'LineEndCapStyle' circularly references itself", because `@enum`'s format is `/** @enum {typeOfMembers} */`, not `/** @enum {EnumsNameAgain} */`

**Comment by paulvanbrenk** [comment]
Thanks @andy-ms and @sandersn this fixes my issue.
