### ISSUE TITLE
Error: Debug Failure. at Object.assertDefined at Object.getJSDocHost

### ISSUE THREAD

**Issue by minestarks** [Microsoft/TypeScript#27341]
**TypeScript Version:**  3.1.0-dev.20180925

```
git clone --depth=1 https://github.com/chemzqm/wept
cd wept
tsc --init
tsc --allowJs --checkJs
```

Compiler crashes with the callstack:

```
Error: Debug Failure.
    at Object.assertDefined (node_modules\typescript\lib\tsc.js:1268:24)
    at getJSDocHost (node_modules\typescript\lib\tsc.js:7723:25)
    at getHostSignatureFromJSDoc (node_modules\typescript\lib\tsc.js:7709:46)
    at Object.getParameterSymbolFromJSDoc (node_modules\typescript\lib\tsc.js:7700:20)
    at checkJSDocParameterTag (node_modules\typescript\lib\tsc.js:43646:21)
    at checkSourceElement (node_modules\typescript\lib\tsc.js:45970:28)
    at Object.forEach (node_modules\typescript\lib\tsc.js:169:30)
    at node_modules\typescript\lib\tsc.js:45896:31
    at Object.forEach (node_modules\typescript\lib\tsc.js:169:30)
    at checkSourceElement (node_modules\typescript\lib\tsc.js:45894:20)
```

**Comment by RyanCavanaugh** [comment]
Also repros on 3.0

**Comment by RyanCavanaugh** [comment]
Minimal repro
```js
if (false) {
	/**
	 * @param {string} s
	 */
	const x = function (s) {
	};
}
```
The `if` expression has to be `false` 🤷‍♂️

**Comment by sandersn** [comment]
Parent pointers aren't filled in. Pretty sure this is supposed to happen in the parser.

**Comment by sandersn** [comment]
Introduced in 2.9

**Comment by sandersn** [comment]
Specifically, bisecting leads to #23947, which was a fairly large change that added `@callback` and corrected handling of `@template` in conjunction with jsdoc type aliases.

**Comment by sandersn** [comment]
In the binder, unreachable code mistakenly skips the `bindJSDoc` call in `bindChildrenWorker`, which sets parent pointers. That's why it has to be `if (false)` and not `if (!!false)`, for example.

**Comment by andy-ms** [comment]
@sandersn Should this be closed?

**Comment by sandersn** [comment]
Yes, not sure why github didn't catch it.
