### ISSUE TITLE
TypeError: Cannot read property 'parent' of undefined at getAssignedJSPrototype

### ISSUE THREAD

**Issue by minestarks** [Microsoft/TypeScript#27344]
**TypeScript Version:**  3.1.0-dev.20180925

```
git clone --depth=1 https://github.com/TeamFleet/WhoCallsTheFleet
cd WhoCallsTheFleet
tsc --init
tsc --allowJs --checkJs
```

Compiler crashes with the callstack:

```
TypeError: Cannot read property 'parent' of undefined
    at getAssignedJSPrototype (node_modules\typescript\lib\tsc.js:40752:23)
    at getAssignedClassType (node_modules\typescript\lib\tsc.js:40748:37)
    at getJSClassType (node_modules\typescript\lib\tsc.js:40732:28)
    at checkCallExpression (node_modules\typescript\lib\tsc.js:40794:46)
    at checkExpressionWorker (node_modules\typescript\lib\tsc.js:42392:28)
    at checkExpression (node_modules\typescript\lib\tsc.js:42334:42)
    at checkNonNullExpression (node_modules\typescript\lib\tsc.js:39352:37)
    at checkPropertyAccessExpressionOrQualifiedName (node_modules\typescript\lib\tsc.js:39378:28)
    at checkPropertyAccessExpression (node_modules\typescript\lib\tsc.js:39371:20)
    at checkExpressionWorker (node_modules\typescript\lib\tsc.js:42384:28)
```

**Comment by RyanCavanaugh** [comment]
Confirmed call stack on master; regression from 3.0

**Comment by RyanCavanaugh** [comment]
Repro requires two files *in this order*:

```js
var SomeClass = function () {
    this.otherProp = 0;
};

new SomeClass();
```

```js
class SomeClass { }
SomeClass.prop = 0
```
