### ISSUE TITLE
Error: Debug Failure. False expression: Should only get Alias here. at resolveAlias

### ISSUE THREAD

**Issue by minestarks** [microsoft/TypeScript#27342]
**TypeScript Version:**  3.1.0-dev.20180925

```
git clone --depth=1 https://github.com/cocos2d/cocos2d-html5
cd cocos2d-html5
tsc --init
tsc --allowJs --checkJs
```

Compiler crashes with the callstack:

```
Error: Debug Failure. False expression: Should only get Alias here.
    at resolveAlias (node_modules\typescript\lib\tsc.js:26170:22)
    at resolveEntityName (node_modules\typescript\lib\tsc.js:26285:76)
    at resolveTypeReferenceName (node_modules\typescript\lib\tsc.js:31245:20)
    at getTypeReferenceType (node_modules\typescript\lib\tsc.js:31282:13)
    at getTypeFromTypeReference (node_modules\typescript\lib\tsc.js:31413:28)
    at checkTypeReferenceNode (node_modules\typescript\lib\tsc.js:42928:24)
    at checkSourceElement (node_modules\typescript\lib\tsc.js:45932:28)
    at Object.forEach (node_modules\typescript\lib\tsc.js:169:30)
    at checkUnionOrIntersectionType (node_modules\typescript\lib\tsc.js:42993:16)
    at checkSourceElement (node_modules\typescript\lib\tsc.js:45945:28)
```

**Comment by RyanCavanaugh** [comment]
Also repros on 3.0

**Comment by RyanCavanaugh** [comment]
```js
/**
 * @type {exports}
 */
module.exports = {};
```

**Comment by sandersn** [comment]
And

```js
module.exports = {}
/** @type {exports} */
var x
```

You can also say `exports.foo = {}` instead of `module.exports = {}`.
