### ISSUE TITLE
TypeError: Cannot read property 'flags' of undefined at isRelatedTo

### ISSUE THREAD

**Issue by minestarks** [Microsoft/TypeScript#27345]
**TypeScript Version:**  3.1.0-dev.20180925

```
git clone --depth=1 https://github.com/0xfe/vexflow
cd vexflow
tsc --init
tsc --allowJs --checkJs
```

Compiler crashes with the callstack:

```
TypeError: Cannot read property 'flags' of undefined
    at isRelatedTo (node_modules\typescript\lib\tsc.js:33794:28)
    at compareSignaturesRelated (node_modules\typescript\lib\tsc.js:33533:25)
    at signatureRelatedTo (node_modules\typescript\lib\tsc.js:34639:24)
    at signaturesRelatedTo (node_modules\typescript\lib\tsc.js:34614:30)
    at structuredTypeRelatedTo (node_modules\typescript\lib\tsc.js:34403:43)
    at recursiveTypeRelatedTo (node_modules\typescript\lib\tsc.js:34190:53)
    at isRelatedTo (node_modules\typescript\lib\tsc.js:33875:38)
    at checkTypeRelatedTo (node_modules\typescript\lib\tsc.js:33709:26)
    at isTypeRelatedTo (node_modules\typescript\lib\tsc.js:33691:24)
    at isTypeSubtypeOf (node_modules\typescript\lib\tsc.js:33172:20)
```

**Comment by RyanCavanaugh** [comment]
Confirmed call stack on master; regression from 3.0

**Comment by RyanCavanaugh** [comment]
Minimal repro:
```js
export class Alpha { }
export class Beta {
  /**
   * @constructor
   */
  constructor() {
  }
}

const arr = [Alpha, Beta];
```
Note that the JS Doc comment matters

**Comment by sandersn** [comment]
`@constructor` put on *anything* incorrectly makes it a JS constructor. This is a problem for actual constructors, because getJSClassType doesn't work on actual classes.
