### ISSUE TITLE
Error: Debug Failure. Unhandled declaration kind! 241 at getTypeOfVariableOrParameterOrPropertyWorker 

### ISSUE THREAD

**Issue by minestarks** [Microsoft/TypeScript#27352]
**TypeScript Version:**  3.1.0-dev.20180925

```
git clone --depth=1 https://github.com/google/lovefield.git
cd lovefield
tsc --init
tsc --allowJs --checkJs
```

Compiler crashes with the callstack:

```
Error: Debug Failure. Unhandled declaration kind! 241 for { flags: 100665092; declarations: 241,187,187,71 }
    at getTypeOfVariableOrParameterOrPropertyWorker (node_modules\typescript\lib\tsc.js:28800:33)
    at getTypeOfVariableOrParameterOrProperty (node_modules\typescript\lib\tsc.js:28725:48)
    at getTypeOfSymbol (node_modules\typescript\lib\tsc.js:28990:24)
    at checkPropertyAccessExpressionOrQualifiedName (node_modules\typescript\lib\tsc.js:39419:53)
    at checkPropertyAccessExpression (node_modules\typescript\lib\tsc.js:39371:20)
    at checkExpressionWorker (node_modules\typescript\lib\tsc.js:42384:28)
    at checkExpression (node_modules\typescript\lib\tsc.js:42334:42)
    at checkNonNullExpression (node_modules\typescript\lib\tsc.js:39352:37)
    at checkPropertyAccessExpressionOrQualifiedName (node_modules\typescript\lib\tsc.js:39378:28)
    at checkPropertyAccessExpression (node_modules\typescript\lib\tsc.js:39371:20)
```

**Comment by weswigham** [comment]
That'd be an `EnumDeclaration` merged with 2x `PropertyAccessExpression` and 1x `Identifier`, I'd assume one of their enums in their [handwritten .d.ts](https://github.com/google/lovefield/blob/6e6cc7cae1421a8da6d5e55ffecb0cdedf6b29a6/dist/lovefield.d.ts) is merging with the js source of itself.

**Comment by sandersn** [comment]
Yes, there are 3 merges for nearly everything:

1. d.ts
2. Closure-style externs.js
3. Implementation JS file.

This project is a gold mine of bugs beyond the OP's crash:

1. Crash when merging enum with expando.
2. Crash when merging enum *member* with expando.
3. Crash when merging interface-declared method declaration with prototype-property-assignment method.

**Comment by fijiwebdesign** [comment]
I got this error: "Error: Debug Failure. Unhandled declaration kind! GetAccessor" which is same as  #27989 due to declaring a getter/setter of an existing property.

**Comment by sandersn** [comment]
@fijiwebdesign Can you open a new bug? Unless you are using TS 3.1 then it is unlikely to be the same one.
