### ISSUE TITLE
Error: Debug Failure. False expression. at mergeSymbol

### ISSUE THREAD

**Issue by minestarks** [Microsoft/TypeScript#27365]
**TypeScript Version:**  3.1.0-dev.20180925

```
git clone --depth=1 https://github.com/marijnh/Eloquent-JavaScript
cd Eloquent-JavaScript
tsc --init
tsc --allowJs --checkJs
```

Compiler crashes with the callstack:

```
Error: Debug Failure. False expression.
    at mergeSymbol (node_modules\typescript\lib\tsc.js:25294:26)
    at node_modules\typescript\lib\tsc.js:26450:69
    at Map.forEach (<anonymous>)
    at getCommonJsExportEquals (node_modules\typescript\lib\tsc.js:26447:34)
    at resolveExternalModuleSymbol (node_modules\typescript\lib\tsc.js:26436:52)
    at getTypeOfFuncClassEnumModuleWorker (node_modules\typescript\lib\tsc.js:28922:38)
    at getTypeOfFuncClassEnumModule (node_modules\typescript\lib\tsc.js:28908:51)
    at getTypeOfSymbol (node_modules\typescript\lib\tsc.js:28993:24)
    at checkIdentifier (node_modules\typescript\lib\tsc.js:37340:49)
    at checkExpressionWorker (node_modules\typescript\lib\tsc.js:42358:28)
```

**Comment by sandersn** [comment]
When you assign `module.exports = exports` inside a toplevel IIFE, the `export=` resolves to an alias that is itself. Here's a small repro:

```js
(function() {
exports.bigOak = 1
exports.everywhere = 2
module.exports = exports
})()
```
