### ISSUE TITLE
Visual Studio crash

### ISSUE THREAD

**Issue by jbondc** [Microsoft/TypeScript#2744]
Log Name:      Application
Source:        .NET Runtime
Date:          4/13/2015 1:06:59 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Description:
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
Stack:
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.ThrowIfInvalid()
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.get_TextWidth()
   at Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.MapXCoordinate(Microsoft.VisualStudio.Text.Formatting.ITextViewLine, Double, Boolean)
   at Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.MoveTo(Microsoft.VisualStudio.Text.Formatting.ITextViewLine, Double, Boolean)
   at Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.MoveTo(Microsoft.VisualStudio.Text.Formatting.ITextViewLine, Double)
   at Microsoft.VisualStudio.Text.Operations.Implementation.EditorOperations.MoveCaret(Microsoft.VisualStudio.Text.Formatting.ITextViewLine, Double, Boolean)
   at Microsoft.VisualStudio.Text.Editor.Implementation.MasterMouseProcessor.HandleMouseLeftButtonDown(Boolean, Boolean, System.Windows.Point)
   at Microsoft.VisualStudio.Text.Editor.Implementation.MasterMouseProcessor.DefaultMouseLeftButtonDownHandler(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at Microsoft.VisualStudio.Text.Utilities.WpfMouseProcessor.UIElement_MouseLeftButtonDown(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseDownThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by mhegazy** [comment]
@jbondc I do not see typescript anywhere on the stack. so we will need some more information to be able to diagnose the issue.

**Comment by jbondc** [comment]
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Error processing work item: 



   at TypeScriptLanguageService.Threading.BackgroundThreadQueue.<>c__DisplayClass8.<ExecuteOneTask>b__5(Exception ex)

   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)

   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)

   a......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------



Log Name:      Application
Source:        Windows Error Reporting
Date:          4/13/2015 2:02:15 PM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Description:
Fault bucket 91566012236, type 5
Event Name: Dev11NonFatalError
Response: Not available
Cab Id: 0

Problem signature:
P1: devenv.exe
P2: 12.0.31101.0
P3: 54548724
P4: System
P5: 4.0.30319.34239
P6: 53e4531e
P7: d0f
P8: c7
P9: Debugger.Break
P10: TypeScriptLanguageService

**Comment by jbondc** [comment]
@mhegazy I see now, it happens when I run 'jake' and have Visual Studio in 'dev mode'. If the compilation fails, it fails to find the service file:
```
  <entry>
    <record>882</record>
    <time>2015/04/13 18:06:01.498</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.IO.FileNotFoundException: Could not find file &apos;F:\Jonathan\GitHub\TypeScript\built\local\typescriptServices.js&apos;.&#x000D;&#x000A;File name: &apos;F:\Jonathan\GitHub\TypeScript\built\local\typescriptServices.js&apos;&#x000D;&#x000A;   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)&#x000D;&#x000A;   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)&#x000D;&#x000A;   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)&#x000D;&#x000A;   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)&#x000D;&#x000A;   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)&#x000D;&#x000A;   at System.IO.File.ReadAllText(String path)&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesFactoryProxy.InitializeEngine()&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesFactoryProxy.InitializeJavaScriptEngineIfNecessary()&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesFactoryProxy.GetFactoryObject(Int32&amp; fileVersion)&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptClassifierServicesAccessor.CreateProxy(Int32&amp; servicesFileVersion)&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesAccessorBase.get_Proxy()&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptClassifierServicesProxy.GetClassificationsForLine(String text, Int32 lexState)&#x000D;&#x000A;   at TypeScriptLanguageService.Features.Classifier.BufferClassifier.GetClassificationsForLine(ITypeScriptClassifierServicesProxy classifier, String text, Int32 lineNum)&#x000D;&#x000A;   at TypeScriptLanguageService.Features.Classifier.TypeScriptClassifier.GetClassificationSpans(SnapshotSpan span)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.&lt;GetTags&gt;d__0.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__5.MoveNext()</description>
  </entry>
  <entry>
    <record>883</record>
    <time>2015/04/13 18:06:01.499</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.IO.FileNotFoundException: Could not find file &apos;F:\Jonathan\GitHub\TypeScript\built\local\typescriptServices.js&apos;.&#x000D;&#x000A;File name: &apos;F:\Jonathan\GitHub\TypeScript\built\local\typescriptServices.js&apos;&#x000D;&#x000A;   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)&#x000D;&#x000A;   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)&#x000D;&#x000A;   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)&#x000D;&#x000A;   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)&#x000D;&#x000A;   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)&#x000D;&#x000A;   at System.IO.File.ReadAllText(String path)&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesFactoryProxy.InitializeEngine()&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesFactoryProxy.InitializeJavaScriptEngineIfNecessary()&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesFactoryProxy.GetFactoryObject(Int32&amp; fileVersion)&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptClassifierServicesAccessor.CreateProxy(Int32&amp; servicesFileVersion)&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesAccessorBase.get_Proxy()&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptClassifierServicesProxy.GetClassificationsForLine(String text, Int32 lexState)&#x000D;&#x000A;   at TypeScriptLanguageService.Features.Classifier.BufferClassifier.GetClassificationsForLine(ITypeScriptClassifierServicesProxy classifier, String text, Int32 lineNum)&#x000D;&#x000A;   at TypeScriptLanguageService.Features.Classifier.TypeScriptClassifier.GetClassificationSpans(SnapshotSpan span)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.&lt;GetTags&gt;d__0.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__5.MoveNext()</description>
  </entry>
  <entry>
    <record>884</record>
    <time>2015/04/13 18:06:01.500</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.IO.FileNotFoundException: Could not find file &apos;F:\Jonathan\GitHub\TypeScript\built\local\typescriptServices.js&apos;.&#x000D;&#x000A;File name: &apos;F:\Jonathan\GitHub\TypeScript\built\local\typescriptServices.js&apos;&#x000D;&#x000A;   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)&#x000D;&#x000A;   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)&#x000D;&#x000A;   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)&#x000D;&#x000A;   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)&#x000D;&#x000A;   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)&#x000D;&#x000A;   at System.IO.File.ReadAllText(String path)&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesFactoryProxy.InitializeEngine()&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesFactoryProxy.InitializeJavaScriptEngineIfNecessary()&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesFactoryProxy.GetFactoryObject(Int32&amp; fileVersion)&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptClassifierServicesAccessor.CreateProxy(Int32&amp; servicesFileVersion)&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesAccessorBase.get_Proxy()&#x000D;&#x000A;   at TypeScriptLanguageService.CompilerServices.TypeScriptClassifierServicesProxy.GetClassificationsForLine(String text, Int32 lexState)&#x000D;&#x000A;   at TypeScriptLanguageService.Features.Classifier.BufferClassifier.GetClassificationsForLine(ITypeScriptClassifierServicesProxy classifier, String text, Int32 lineNum)&#x000D;&#x000A;   at TypeScriptLanguageService.Features.Classifier.TypeScriptClassifier.GetClassificationSpans(SnapshotSpan span)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.&lt;GetTags&gt;d__0.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__5.MoveNext()</description>
  </entry>
</activity>
```
Ideally the plugin could just re-use the 'last-known' good service file.

**Comment by jbondc** [comment]
The first crash seems unrelated.

**Comment by CyrusNajmabadi** [comment]
Hey @jbondc, if you look in your event viewer, there will often be another log entry after these crashes with the source being "Windows Error Reporter".  At the top of this entry will be a line like:

Fault bucket <SomeLongNumber>

if you can provide that, then i can take a look at what the crash data indicates in our system.

Note: make sure you're picking the write "Windows Error Reporter" log.  It should list the same crashing assembly as the crash you're reporting.

Thanks!

**Comment by mhegazy** [comment]
@jbondc are you still running into this with 1.5-beta?

**Comment by jbondc** [comment]
I'm not sure, here are steps to reproduce the most frustrating one:

Installed:
https://visualstudiogallery.msdn.microsoft.com/107f89a0-a542-4264-b0a9-eb91037cf7af

![ts](https://cloud.githubusercontent.com/assets/199519/7501734/5e2ced58-f404-11e4-987c-539c43e8e15b.png)

Visual Studio goes nutty looking for 'typescriptServices.js' which no longer exists.

**Comment by mhegazy** [comment]
This looks specific to dev mode. resolving this as won't fix.
