### ISSUE TITLE
`let foo = new Foo(); export = foo;` has fewer type errors than `export = new Foo();`

### ISSUE THREAD

**Issue by dgoldstein0** [microsoft/TypeScript#27511]
**TypeScript Version:**  3.1.1 and 2.8.4

**Search Terms:** export = new instance

**Code**

store.ts:
```ts
class SetupStore {
  private _screenAfterScaleMitigation: string;

  constructor() {
    this._screenAfterScaleMitigation = 'FOO';
  }

  screenAfterScaleMitigation() {
    return this._screenAfterScaleMitigation;
  }
}
const setupStore = new SetupStore();
export = setupStore;
```
a.ts:
```
import * as SetupStore from './store';

console.log(SetupStore.screenAfterScaleMitigation());
```

tsconfig.json
```json
{
    "compilerOptions": {
        "allowJs": false,
        "moduleResolution": "node",
        "target": "es5",
        "importHelpers": false,
        "experimentalDecorators": true,
        "jsx": "react",
        "lib": ["dom", "es2015.promise", "es5"],
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "noUnusedLocals": true,
        "noEmitOnError": true,
        "outDir": "./compiled",
        "preserveConstEnums": true,
        "rootDir": "./",
        "strictNullChecks": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "noImplicitThis": true
    }
}
```

**Expected behavior:**

an error like
```
a.ts:1:29 - error TS2497: Module '"/home/dgoldstein/tmp4/store"' resolves to a non-module entity and cannot be imported using this construct.

1 import * as SetupStore from './store';
```

**Actual behavior:**
This code typechecks, yet fails at runtime:

```
$ node compiled/a.js
/home/dgoldstein/tmp4/compiled/a.js:11
console.log(SetupStore.screenAfterScaleMitigation());
                       ^

TypeError: SetupStore.screenAfterScaleMitigation is not a function
    at Object.<anonymous> (/home/dgoldstein/tmp4/compiled/a.js:11:24)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

if the last two lines of `store.ts` are replaced with

```
export = new SetupStore();
```

then the expected error shows up.

**Playground Link:** requires multiple modules and --esModuleInterop so this isn't reproable in the playground

**Related Issues:** couldn't find any

**Comment by andy-ms** [comment]
Simplified repro:
```ts
// @Filename: /a.ts
class C {}
export = new C();

// @Filename: /b.ts
class C {}
const c = new C();
export = c;

// @Filename: /c.ts
import * as a from "./a"; // Error
import * as b from "./b"; // Not an error
```

**Comment by dgoldstein0** [comment]
yeah.  IMO the `--esModuleInterop` variation of this is worse because not only is the type error missing, but the code is actually broken at runtime.  without esModuleInterop, the generated code will function as expected.

**Comment by dgoldstein0** [comment]
with esModuleInterop, the `__importStar` helper will be inserted for any `import *`; and it's effect on `export = new Foo()` and similar patterns is that it'll create a new object and copy own properties onto a new object.  Probably the intent of an `export = new Foo()` module is that the exported object is a singleton, but with the __importStar helper moving the objects properties onto a new object, every import will end up using a different copy of the same object.  And also, the copy won't have a working prototype chain.

Anyhow I'm not arguing so much that the emitted code is wrong, but that there should be a type error.  Without esModuleInterop the type error is more of a formality; with it, the type error is necessary because the emitted code almost certainly doesn't do what's expected.  My original example shows this pretty well.  I suppose using the `.default` property of the `import *` result would work, but it's easy to forget to do that.

**Comment by hamiltop** [comment]
I have a similar example:
`exportLiteral.d.ts`
```
declare var X: number;
export = X
```
`exportLiteral.js`
```
module.exports = 5
```
`index.ts`
```
import * as x from "./exportLiteral"
console.log(x)
```
With `esModuleInterop`, the output is `{ default: 5 }`
Without `esModuleInterop`, the output is `5`

In both cases, the type checker claims `x` is a number.

**Comment by RyanCavanaugh** [comment]
Not sure what changed, but this runs without error now
