### ISSUE TITLE
Unhandled exception - could not find user file

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#27875]
From 3.1.3:

```
Error processing request. Could not find file: 'd:/pai/src/rest-server/src/config/throttle.js'.
Error: Could not find file: 'USERS_FILE'.
    at getValidSourceFile (tsserver.js:114593:23)
    at Object.getCompletionsAtPosition (tsserver.js:114818:80)
    at IOSession.Session.getCompletions (tsserver.js:122608:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:121665:61)
    at tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (tsserver.js:123077:28)
    at IOSession.Session.executeCommand (tsserver.js:123086:33)
    at IOSession.Session.onMessage (tsserver.js:123106:35)
    at Interface.<anonymous> (tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by amcasey** [comment]
Command was `completionInfo`.

**Comment by sheetalkamat** [comment]
This wouldn't have been first exception. I think there would be exception preceding this which is why its not able to find the sourceFile in the project. For this to investigate we need repro and cant just work it out with stack.
