### ISSUE TITLE
assertDefined getDocumentHighlights

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#27879]
From 3.1.3 (occurrences)
```
Error: Debug Failure.
    at Object.assertDefined (tsserver.js:1446:24)
    at tsserver.js:114911:92
    at Object.map (tsserver.js:442:29)
    at getDocumentHighlights (tsserver.js:114911:42)
    at Object.getOccurrencesAtPosition (tsserver.js:114899:31)
    at IOSession.Session.getOccurrences (tsserver.js:122233:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:121766:61)
    at tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (tsserver.js:123077:28)
    at IOSession.Session.executeCommand (tsserver.js:123086:33)
    at IOSession.Session.onMessage (tsserver.js:123106:35)
    at Interface.<anonymous> (tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by andy-ms** [comment]
This is failing at `Debug.assertDefined(program.getSourceFile(f))` in `getDocumentHighlights`. This  indicates that there was a `getOccurrencesAtPosition` request for a file that was not in the program. It would help to know if there was previously an open request on that file.

**Comment by sheetalkamat** [comment]
Closing this so that we can reopen when there is stack with change #28242 to investigate this further.
