### ISSUE TITLE
assertDefined getDefaultExportInfoWorker

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#27878]
From 3.1.3 (getCodeFixes)

```
Error processing request. Debug Failure.
Error: Debug Failure.
    at Object.assertDefined (tsserver.js:1446:24)
    at getDefaultExportInfoWorker (tsserver.js:108210:80)
    at getDefaultLikeExportInfo (tsserver.js:108191:24)
    at tsserver.js:108174:35
    at tsserver.js:108318:21
    at forEachExternalModule (tsserver.js:108331:21)
    at forEachExternalModuleToImportFrom (tsserver.js:108316:13)
    at getExportInfos (tsserver.js:108172:13)
    at getFixesInfoForNonUMDImport (tsserver.js:108158:57)
    at getFixesInfo (tsserver.js:108099:50)
    at Object.getCodeActions (tsserver.js:107861:28)
    at tsserver.js:106400:121
    at Object.flatMap (tsserver.js:499:25)
    at Object.getFixes (tsserver.js:106400:23)
    at tsserver.js:115125:35
    at Object.flatMap (tsserver.js:499:25)
    at Object.getCodeFixesAtPosition (tsserver.js:115123:23)
    at Object.getCodeFixesAtPosition (/Users/james/.vscode-insiders/extensions/jpoissonnier.vscode-styled-components-0.0.22/node_modules/typescript-template-language-service-decorator/lib/template-language-service-decorator.js:163:20)
    at IOSession.Session.getCodeFixes (tsserver.js:122929:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:121789:61)
    at tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (tsserver.js:123077:28)
    at IOSession.Session.executeCommand (tsserver.js:123086:33)
    at IOSession.Session.onMessage (tsserver.js:123106:35)
    at Interface.<anonymous> (tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by amcasey** [comment]
Probably part of https://github.com/Microsoft/TypeScript/issues/27640

**Comment by mjbvz** [comment]
VS Code users are reporting this with 3.1.3, see: https://github.com/Microsoft/vscode/issues/60745 

@andy-ms or @amcasey Please try following up some of the people in that thread if you need repo steps

**Comment by andy-ms** [comment]
We have a repro in #27857
