### ISSUE TITLE
Assert getImportCompletionAction 

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#27880]
From 3.1.3 (completionEntryDetails)
```
Error: Debug Failure. False expression.
    at Object.getImportCompletionAction (tsserver.js:107970:22)
    at getCompletionEntryCodeActionsAndSourceDisplay (tsserver.js:94059:33)
    at Object.getCompletionEntryDetails (tsserver.js:94009:30)
    at Object.getCompletionEntryDetails (tsserver.js:114823:35)
    at tsserver.js:122634:57
    at Object.mapDefined (tsserver.js:578:30)
    at IOSession.Session.getCompletionEntryDetails (tsserver.js:122632:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:121674:61)
    at tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (tsserver.js:123077:28)
    at IOSession.Session.executeCommand (tsserver.js:123086:33)
    at IOSession.Session.onMessage (tsserver.js:123106:35)
    at Interface.<anonymous> (tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by amcasey** [comment]
Possibly part of https://github.com/Microsoft/TypeScript/issues/27640

**Comment by DanielRosenwasser** [comment]
Looks like this might've been fixed by #27338

**Comment by andy-ms** [comment]
I don't think this is a duplicate of #27640 or #27338. Those failed in `completions.ts`, this is failing in `getImportCompletionAction` in `importFixes.ts` at `Debug.assert(exportInfos.some(info => info.moduleSymbol === moduleSymbol));`.

**Comment by sheetalkamat** [comment]
@amcasey Does this still repro?

**Comment by amcasey** [comment]
@sheetalkamat ~22 hits in the last 3 days from 3.3.3 and 3.3.4000.
