### ISSUE TITLE
Typescript: Update Imports On File Move does not show prompt, gets error from tsserver.

### ISSUE THREAD

**Issue by arvidboivie** [Microsoft/TypeScript#28628]
- VSCode Version: 1.29.1 / 1.31.0-insider
- OS Version: macOS Mojave 10.14.1

Does this issue occur when all extensions are disabled?: Yes

I'm not able to get the update on file move working properly for my project. I can set up a simple test project with two folders and move files between them, and vscode will prompt me for refactoring. But on my current, bigger project it never prompts me. This is my tsserver.log

[tsserver.log](https://github.com/Microsoft/vscode/files/2588928/tsserver.log)

I assume it has something to do with this, but it really doesn't tell me much: 
```
Exception on executing command {"seq":16,"type":"request","command":"getEditsForFileRename","arguments":{"file":"/Users/arbo/repos/graphql/src/auth/access.helper.ts","oldFilePath":"/Users/arbo/repos/graphql/src/helpers/access.helper.ts","newFilePath":"/Users/arbo/repos/graphql/src/auth/access.helper.ts"}}:

    Debug Failure. False expression.
```

**Comment by mjbvz** [comment]
Full error stack from logs:

```
Err 29    [11:38:51.10] Exception on executing command {"seq":16,"type":"request","command":"getEditsForFileRename","arguments":{"file":"/Users/arbo/repos/graphql/src/auth/access.helper.ts","oldFilePath":"/Users/arbo/repos/graphql/src/helpers/access.helper.ts","newFilePath":"/Users/arbo/repos/graphql/src/auth/access.helper.ts"}}:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at computePositionOfLineAndCharacter (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:6429:22)
        at Object.getPositionOfLineAndCharacter (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:6419:16)
        at processMapping (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:64837:26)
        at Object.arrayFrom (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:1172:31)
        at getDecodedMappings (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:64851:35)
        at getGeneratedMappings (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:64883:39)
        at Object.getSourcePosition (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:64910:37)
        at Object.tryGetSourcePosition (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:103733:63)
        at /Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:100079:61
        at _loop_3 (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:100171:30)
        at updateImports (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:100202:13)
        at /Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:100071:13
        at Function.ChangeTracker.with (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:107457:17)
        at Object.getEditsForFileRename (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:100069:49)
        at Object.getEditsForFileRename (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:117509:23)
        at /Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:125354:146
        at /Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:123757:36
        at /Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:122055:25
        at Map.forEach (<anonymous>)
        at ProjectService.forEachProject (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:122049:41)
        at ProjectService.forEachEnabledProject (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:122053:22)
        at combineProjectOutputFromEveryProject (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:123756:28)
        at IOSession.Session.getEditsForFileRename (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:125354:31)
        at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:124199:61)
        at /Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:125531:88
        at IOSession.Session.executeWithRequestId (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:125522:28)
        at IOSession.Session.executeCommand (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:125531:33)
        at IOSession.Session.onMessage (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:125553:35)
        at Interface.<anonymous> (/Users/arbo/repos/graphql/node_modules/typescript/lib/tsserver.js:126811:27)
        at emitOne (events.js:116:13)
        at Interface.emit (events.js:211:7)
        at Interface._onLine (readline.js:282:10)
        at Interface._normalWrite (readline.js:424:12)
        at Socket.ondata (readline.js:141:10)
        at emitOne (events.js:116:13)
        at Socket.emit (events.js:211:7)
        at addChunk (_stream_readable.js:263:12)
        at readableAddChunk (_stream_readable.js:250:11)
        at Socket.Readable.push (_stream_readable.js:208:10)
        at Pipe.onread (net.js:594:20)
```

Somewhat similar looking to #25844. @weswigham can you please take a look

**Comment by mjbvz** [comment]
Also @arvidboivie, are you able to share a project that reproduces this issue?

**Comment by weswigham** [comment]
(Also, does it still repro using the `@next` language service?)

**Comment by arvidboivie** [comment]
@mjbvz @weswigham 
Wen't back today to try to reproduce, and now I can't reproduce at all. Problem solved. Annoying to not understand why.
