### ISSUE TITLE
Typescript compiler crashes when an interface member property is encountered which is a generic function with a type parameter that extends an unknown type

### ISSUE THREAD

**Issue by lorefnon** [Microsoft/TypeScript#28728]
**TypeScript Version:**  "3.3.0-dev.20181129"

**Search Terms:**

- This is unknown parent for type parameter
- 163

**Code**

```ts
export interface Foo {
    preFetch: <T1 extends T2> (c: T1) => void; // Type T2 is not defined 
}
```

```json
// tsconfig.json
{
    "compilerOptions": {
        "moduleResolution": "node",
        "target": "es6",
        "strict": true,
        "sourceMap": true,
        "declaration": true,
        "declarationDir": "lib",
        "outDir": "lib"
    }
}

```

**Expected behavior:**

Compiler reports an error about the type T2 not being defined

**Actual behavior:**

Compiler crashes and does not provide any information on what needs to be done to resolve the issue.

```
$ tsc
C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:71037
                throw e;
                ^

Error: Debug Failure. This is unknown parent for type parameter: 165
    at getTypeParameterConstraintVisibilityError (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:64630:37)
    at handleSymbolAccessibilityError (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:64756:33)
    at checkEntityNameVisibility (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:65080:13)
    at visitDeclarationSubtree (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:65226:25)
    at visitNode (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:53392:23)
    at Object.visitEachChild (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:53502:112)
    at visitDeclarationSubtree (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:65278:43)
    at Object.visitNodes (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:53429:48)
    at visitDeclarationSubtree (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:65291:76)
    at Object.visitNode (C:\Users\loref\Projects\ts-test\node_modules\typescript\lib\tsc.js:53392:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Playground Link:** 

[Not reproducible](http://www.typescriptlang.org/play/#src=export%20interface%20Foo%20%7B%0D%0A%20%20%20%20preFetch%3A%20%3CT1%20extends%20Dict%2C%20T2%3E%20(c%3A%20T1)%20%3D%3E%20T2%3B%0D%0A%7D)

**Related Issues:** 

https://github.com/Microsoft/TypeScript/issues/25456

**Comment by lorefnon** [comment]
A reproducer can be found in this repo: https://github.com/lorefnon/ts-issue-28728
