### ISSUE TITLE
Cannot read property 'flags' of undefined(3.2.x)

### ISSUE THREAD

**Issue by xiaocaibird** [Microsoft/TypeScript#28935]
**TypeScript Version:**  3.2.x

**Search Terms:** Cannot read property 'flags' of undefined

**Code**

First of all, I am sorry. This is an internal project of our company, I can't provide a git url. 
And because of the large amount of code, I still can't find the wrong code snippet.
Our project is still working in the previous version(3.1.x).
I found this problem in 3.2.1,and I found some related issues at the time.
I was hoping it could be fixed together, but no.

**Expected behavior:** Compile

**Actual behavior:**
TypeError: Cannot read property 'flags' of undefined
    at isFreshLiteralType (/project/news-manage/node_modules/typescript/lib/tsc.js:33326:28)
    at isTypeRelatedTo (/project/news-manage/node_modules/typescript/lib/tsc.js:34425:17)
    at isTypeComparableTo (/project/news-manage/node_modules/typescript/lib/tsc.js:33930:20)
    at /project/news-manage/node_modules/typescript/lib/tsc.js:37851:102
    at Object.filter (/project/news-manage/node_modules/typescript/lib/tsc.js:340:31)
    at filterType (/project/news-manage/node_modules/typescript/lib/tsc.js:37422:35)
    at narrowTypeByDiscriminant (/project/news-manage/node_modules/typescript/lib/tsc.js:37851:63)
    at narrowTypeByTruthiness (/project/news-manage/node_modules/typescript/lib/tsc.js:37858:28)
    at narrowType (/project/news-manage/node_modules/typescript/lib/tsc.js:38161:32)
    at getTypeAtFlowCondition (/project/news-manage/node_modules/typescript/lib/tsc.js:37730:36)

**Playground Link:** 

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
`narrowTypeByDiscriminant` is the call that has two type assertions

https://github.com/Microsoft/TypeScript/blob/c2898db9dd58c9b0681d6131ed6076d71d89e6b5/src/compiler/checker.ts#L15655-L15656:

```ts
return propType === narrowedPropType ? type : filterType(type, t => isTypeComparableTo(getTypeOfPropertyOfType(t, propName)!, narrowedPropType!));
```

**Comment by xiaocaibird** [comment]
> `narrowTypeByDiscriminant` is the call that has two type assertions
> 
> https://github.com/Microsoft/TypeScript/blob/c2898db9dd58c9b0681d6131ed6076d71d89e6b5/src/compiler/checker.ts#L15656
> 
> ```ts
> return propType === narrowedPropType ? type : filterType(type, t => isTypeComparableTo(getTypeOfPropertyOfType(t, propName)!, narrowedPropType!));
> ```

thanks.  but How can I solve this problem

**Comment by xiaocaibird** [comment]
@DanielRosenwasser  
Thanks.
But, how can I solve this problem.

**Comment by DanielRosenwasser** [comment]
This is meant more for anyone who ends up assigned to this issue :smiley:

**Comment by ahejlsberg** [comment]
@xiaocaibird Just merged what I think is a fix to your issue. Try pulling the next nightly build and let us know what you find.

**Comment by vocoWone** [comment]
+1 same issue here

**Comment by DanielRosenwasser** [comment]
Have you tried the nightly build? `npm install typescript@next`

**Comment by vocoWone** [comment]
> Have you tried the nightly build? `npm install typescript@next`

Fix. Thanks!!

**Comment by DanielRosenwasser** [comment]
Great! Glad we could fix it quickly.
