### ISSUE TITLE
exception Cannot read property 'escapedText' of undefined

### ISSUE THREAD

**Issue by captain-igloo** [Microsoft/TypeScript#29101]
**TypeScript Version:**  ^3.3.0-dev.20181219

**Search Terms:** escapedText of undefined

**Code**

```ts
interface Greeter {
    getGreeting(): string;
}

interface GreeterConstructor {
    new (): Greeter;
}

class A {
    getGreeting() {
        return 'hello';
    }
}

const getGreeterBase = (): GreeterConstructor => A;

export default class extends getGreeterBase() {

}
```

**Expected behavior:** I expect the above to compile without error.

**Actual behavior:** An exception is thrown:
TypeError: Cannot read property 'escapedText' of undefined
    at transformTopLevelDeclaration (/XXX/node_modules/typescript/lib/tsc.js:65556:110)
    at visitDeclarationStatements (/XXX/node_modules/typescript/lib/tsc.js:65444:26)
    at Object.visitNodes (/XXX/node_modules/typescript/lib/tsc.js:53510:48)
    at transformRoot (/XXX/node_modules/typescript/lib/tsc.js:64945:33)
    at /XXX/node_modules/typescript/lib/tsc.js:1229:42
    at transformRoot (/XXX/node_modules/typescript/lib/tsc.js:65930:82)
    at Object.map (/XXX/node_modules/typescript/lib/tsc.js:378:29)
    at Object.transformNodes (/XXX/node_modules/typescript/lib/tsc.js:65918:30)
    at emitDeclarationFileOrBundle (/XXX/node_modules/typescript/lib/tsc.js:66229:43)
    at emitSourceFileOrBundle (/XXX/node_modules/typescript/lib/tsc.js:66169:13)

The code above is mostly borrowed from https://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-6.html .  But when I attempt to export a class without a name that extends an expression I get the error above.  Exporting with a name works fine, ie:
```
export default class B extends getGreeterBase() {
}
```

**Comment by DanielRosenwasser** [comment]
I'm not getting the same error you are. How are you compiling this today?

**Comment by captain-igloo** [comment]
tsc --declaration --outDir lib

my tsconfig.json:

`{
    "compilerOptions": {
        "target": "es6",
        "moduleResolution": "node",
        "strict": true,
        "allowSyntheticDefaultImports": true,
        "sourceMap": true,
        "module": "commonjs"
    },
    "include": [
        "src/index.ts"
    ]
}
`

**Comment by DanielRosenwasser** [comment]
Should be fixed in the next nightly. Thanks!
