### ISSUE TITLE
Debug Failure. False expression. at ProjectService.setConfigFileExistenceByNewConfiguredProject

### ISSUE THREAD

**Issue by uniqueiniquity** [Microsoft/TypeScript#29191]
**TypeScript Version:**  3.1.6 (This repro came from an automated test run. If needed, I can try to repro manually with a newer version of TS)

**Search Terms:**
openExternalProjects, configFileExistenceCache, Visual Studio

**Repro steps**

1. Create new ASP.NET Web application
2. Add a JS file
3. Add a jsconfig.json file
4. Start typing into the JS file

**Expected behavior:**
No error thrown

**Actual behavior:**
Language service put in bad state with following error trace:
```
Info 239  [0:7:34.530] request:
    {"seq":19,"command":"openExternalProjects","arguments":{"projects":[{"projectFileName":"C:/school/ApexSolutions/TestCase2/ASPNet_1/ASPNet_1.csproj","rootFiles":[{"fileName":"C:\\school\\ApexSolutions\\TestCase2\\ASPNet_1\\jsconfig.json","scriptKind":0},{"fileName":"C:\\school\\ApexSolutions\\TestCase2\\ASPNet_1\\file1.js","scriptKind":1}],"options":{"allowJs":false,"allowNonTsExtensions":true,"allowSyntheticDefaultImports":false,"allowUnreachableCode":false,"allowUnusedLabels":false,"alwaysStrict":false,"checkJs":false,"compileOnSave":true,"declaration":false,"downlevelIteration":false,"emitBOM":false,"emitDecoratorMetadata":false,"experimentalAsyncFunctions":false,"experimentalDecorators":false,"forceConsistentCasingInFileNames":false,"importHelpers":false,"inlineSourceMap":false,"inlineSources":false,"isolatedModules":false,"jsx":2,"noEmit":false,"noEmitHelpers":false,"noEmitOnError":true,"noFallthroughCasesInSwitch":false,"noImplicitAny":false,"noImplicitReturns":false,"noImplicitThis":false,"noImplicitUseStrict":false,"noLib":false,"noResolve":false,"noUnusedLocals":false,"noUnusedParameters":false,"preserveConstEnums":false,"removeComments":false,"skipDefaultLibCheck":false,"skipLibCheck":false,"sourceMap":true,"strict":false,"strictNullChecks":false,"stripInternal":false,"suppressExcessPropertyErrors":false,"suppressImplicitAnyIndexErrors":false,"target":1}}]}}
Info 240  [0:7:34.536] Opened configuration file C:/school/ApexSolutions/TestCase2/ASPNet_1/jsconfig.json
Info 241  [0:7:34.537] FileWatcher:: Added:: WatchInfo: C:/school/ApexSolutions/TestCase2/ASPNet_1/jsconfig.json 2000 Project: C:/school/ApexSolutions/TestCase2/ASPNet_1/jsconfig.json WatchType: Config file for the program
Err 242   [0:7:34.558] Exception on executing command {"seq":19,"command":"openExternalProjects","arguments":{"projects":[{"projectFileName":"C:/school/ApexSolutions/TestCase2/ASPNet_1/ASPNet_1.csproj","rootFiles":[{"fileName":"C:\\school\\ApexSolutions\\TestCase2\\ASPNet_1\\jsconfig.json","scriptKind":0},{"fileName":"C:\\school\\ApexSolutions\\TestCase2\\ASPNet_1\\file1.js","scriptKind":1}],"options":{"allowJs":false,"allowNonTsExtensions":true,"allowSyntheticDefaultImports":false,"allowUnreachableCode":false,"allowUnusedLabels":false,"alwaysStrict":false,"checkJs":false,"compileOnSave":true,"declaration":false,"downlevelIteration":false,"emitBOM":false,"emitDecoratorMetadata":false,"experimentalAsyncFunctions":false,"experimentalDecorators":false,"forceConsistentCasingInFileNames":false,"importHelpers":false,"inlineSourceMap":false,"inlineSources":false,"isolatedModules":false,"jsx":2,"noEmit":false,"noEmitHelpers":false,"noEmitOnError":true,"noFallthroughCasesInSwitch":false,"noImplicitAny":false,"noImplicitReturns":false,"noImplicitThis":false,"noImplicitUseStrict":false,"noLib":false,"noResolve":false,"noUnusedLocals":false,"noUnusedParameters":false,"preserveConstEnums":false,"removeComments":false,"skipDefaultLibCheck":false,"skipLibCheck":false,"sourceMap":true,"strict":false,"strictNullChecks":false,"stripInternal":false,"suppressExcessPropertyErrors":false,"suppressImplicitAnyIndexErrors":false,"target":1}}]}}:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
    at ProjectService.setConfigFileExistenceByNewConfiguredProject (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:119892:30)
    at ProjectService.createConfiguredProject (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:120203:22)
    at ProjectService.createAndLoadConfiguredProject (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:120212:36)
    at ProjectService.createLoadAndUpdateConfiguredProject (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:120217:36)
    at ProjectService.openExternalProject (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:121113:38)
    at ProjectService.openExternalProjects (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:120907:26)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:121492:46)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:123046:88
    at IOSession.Session.executeWithRequestId (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:123037:28)
    at IOSession.Session.executeCommand (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:123046:33)
    at IOSession.Session.onMessage (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:123066:35)
    at Interface.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:124329:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:638:20)
```

**Comment by sheetalkamat** [comment]
@uniqueiniquity tried this and seems to work fine
[tsserver6680.log](https://github.com/Microsoft/TypeScript/files/2715698/tsserver6680.log)

**Comment by uniqueiniquity** [comment]
I was worried that would happen; these automated test bugs can be fairly inconsistent. I'll keep monitoring our test results to see how frequently it repros.

**Comment by uniqueiniquity** [comment]
@sheetalkamat I was able to reproduce manually with a local build of tsserver at 799656a03757975c83deae53ce5d6be54131fd93. It certainly doesn't happen every time, but it's definitely reproducible.

**Comment by minestarks** [comment]
@sheetalkamat a failure in `openExternalProjects` blocks the language service entirely so this is especially severe for VS. Would we be able to take this into 3.2?

**Comment by minestarks** [comment]
Thanks for the fix! I can work with @DanielRosenwasser to see if/how we can take this into 3.2.
