### ISSUE TITLE
bug: the wrong context in the switch scope

### ISSUE THREAD

**Issue by zhmushan** [Microsoft/TypeScript#29205]
**TypeScript Version:**  3.3.0-dev.201xxxxx

**Code**

```ts
let type = 1;
switch (type) {
  case 0:
    let foo = "foo";
    break;
  case 1:
    foo = "foo"; // I think `ts` should output an error, `let foo = "foo"` is the correct way.
    console.log(foo);
    break;
}
// @ts-ignore
console.log(foo)
```

Now, `foo` is already a global variable, and `ts` doesn't output any errors.

**Comment by j-oliveras** [comment]
Tested on `node 8.11.1`. With your code:
```
    foo = "foo";
        ^

ReferenceError: foo is not defined
    at Object.<anonymous> (C:\code\test\index.js:7:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
}
// @ts-ignore
console.log(foo)
```

With your proposed change:
```
    let foo = "foo";
        ^

SyntaxError: Identifier 'foo' has already been declared
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
so it seems that neither are correct. Anyway, the last `console.log` are incorrect because `foo` declaration is not in scope. Remember that a `let` and `const` variables has as scope the block code where are declared (starting on declaration), so in your code `foo` has inside switch code scope.

As a workaround: declare foo before switch:
```ts
let type = 1;
let foo;
switch (type) {
  case 0:
    foo = "foo";
    break;
  case 1:
    foo = "foo";
    console.log(foo);
    break;
}
console.log(foo)
```

**Comment by zhmushan** [comment]
@j-oliveras Hi, thanks for your attention.
I just tried again and modify this issue.

I used to set the wrong target, causing the `let` to be compiled into `var`, let us ignore the previous mistakes.
The problem is that after I set `target: esnext`, this code obviously cannot run in node, but `ts` did not report any errors.

**Comment by zhmushan** [comment]
@ajafff thank you
