### ISSUE TITLE
Code formatting silently fails when certain JS characters included in JSX

### ISSUE THREAD

**Issue by x0a** [Microsoft/TypeScript#29233]
Issue Type: <b>Bug</b>
Steps to reproduce:
1. Create a new file and set language to "Javascript React".
2. Enter the following unformatted code:

```jsx
function test(){
    return <div>
        <span>//test</span>
  <div>
                    <span>hello</span>
<div>
                world
   </div>
        </div>
    </div>
}
```
3. Right click and click "Format Document", or press Ctrl+Shift+I. 

The code wont format, no errors will be thrown, and editor gives no indication of any formatting issues. 

The expected behavior is that anything inside JSX tags be treated as text and not javascript unless enclosed by brackets.
If you change the above code to:
```jsx
function test(){
    return <div>
        <span>{'//'}test</span>
  <div>
                    <span>hello</span>
<div>
                world
   </div>
        </div>
    </div>
}
```
It correctly formats to:
```jsx
function test() {
    return <div>
        <span>{'//'}test</span>
        <div>
            <span>hello</span>
            <div>
                world
            </div>
        </div>
    </div>
}
```
VS Code version: Code - Insiders 1.31.0-insider (e02e44464c02d617b98d0a3265bf5efef7794436, 2018-12-21T06:15:51.434Z)
OS version: Linux x64 4.18.0-13-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-3530MX APU with Radeon(tm) HD Graphics (4 x 975)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.28GB (0.95GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
code-beautifier|mic|2.1.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Tested with typescript@3.3.0-dev.20190101

TSServer error:

```
[Error  - 11:16:44 AM] 'format' request failed with error.
Error processing request. Debug Failure. False expression: Token end is child end
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106780:34)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106727:21
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16198:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16609:24)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106726:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106786:21)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106727:21
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16198:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16588:21)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106726:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106786:21)
    at processChildNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106837:48)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106729:21
    at visitNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16203:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16587:21)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106726:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106786:21)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106727:21
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16198:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16473:24)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106726:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106786:21)
    at processChildNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106837:48)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106729:21
    at visitNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16203:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16433:24)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106726:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106786:21)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106727:21
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16198:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16328:21)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106726:20)
    at formatSpanWorker (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106544:17)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106525:208
    at Object.getFormattingScanner (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:105314:23)
    at formatSpan (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106525:31)
    at Object.formatSelection (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:106343:20)
    at Object.getFormattingEditsForRange (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:118009:34)
    at Proxy.<anonymous> (/Users/matb/.vscode-insiders/extensions/bierner.lit-html-1.11.0/node_modules/typescript-template-language-service-decorator/lib/template-language-service-decorator.js:120:20)
    at IOSession.Session.getFormattingEditsForRange (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:125797:45)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:124855:61)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:126357:88
    at IOSession.Session.executeWithRequestId (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:126348:28)
    at IOSession.Session.executeCommand (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:126357:33)
    at IOSession.Session.onMessage (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:126379:35)
    at Interface.<anonymous> (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:127640:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
```

**Comment by timrobinson33** [comment]
I think my problem is a duplicate of this because my stack trace looks similar, but I thought I'd post it just in case because my repro looks quite different. It seems to be triggered by the string template.
```
import React from 'react';
export default function Foo() {
    return (<>Hello "{3}"</>)
}
```
if I try to reformat the above code. I see the "TypeScript Server Error" message appear in the bottom-right hand corner of VS code. I'm using typescript 3.9.2 and my VS code about box says:
```
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:10:24.511Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic
```

**Comment by chybisov** [comment]
Same here. In JSX I have single quote in text like this:

`<SomeComponent>Text with ' in it.</SomeComponent>`

I have to enclose this text by curly brackets to avoid "Token end is child end" error when formatting.

`<SomeComponent>{"Text with ' in it."}</SomeComponent>`
