### ISSUE TITLE
getCodeFixes — Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#29358]
**TypeScript Version:** 3.3.0-dev.20190101

In the VS Code error telemetry, we're seeing this error hit a few times:

```
Error processing request. Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createTransformedStatement (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:110504:61)
    at transformPromiseCall (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:110496:24)
    at transformExpression (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:110420:24)
    at transformExpression (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:110417:24)
    at transformThen (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:110485:20)
    at transformExpression (/Applications/Visual Studio Code - Insiders.app/Contents/Resources
```

No repo steps currently.

**Comment by weswigham** [comment]
Looks like a bug in the promise -> async/await quickfix

**Comment by mjbvz** [comment]
Tested with TS 3.4.3

**repo**
- Open this file in the vscode source: https://github.com/microsoft/vscode/blob/0b4d49b59eaac8b7f254347b57ea91d8bfd1c7eb/src/vs/workbench/services/extensions/electron-browser/extensionHost.ts#L380
- Notice the `...` suggestion on `_createExtHostInitData`
- Trigger code actions for this suggestion.
- Crash!


Here's a more complete trace:

```
[Trace  - 11:37:27 AM] Response received: getCodeFixes (1908). Request took 23 ms. Success: false . Message: Error processing request. Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createTransformedStatement (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113147:61)
    at transformPromiseCall (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113139:24)
    at transformExpression (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113063:24)
    at transformExpression (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113060:24)
    at transformThen (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113128:20)
    at transformExpression (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113054:24)
    at startTransformation (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:112874:32)
    at visit (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:112880:25)
    at visitNode (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:16515:24)
    at Object.forEachChild (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:16790:24)
    at _loop_11 (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:112878:20)
    at convertToAsyncFunction (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:112889:17)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:112838:96
    at Function.ChangeTracker.with (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:110603:17)
    at Object.getCodeActions (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:112838:64)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:111589:121
    at Object.flatMap (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:571:25)
    at Object.getFixes (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:111589:23)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121238:35
    at Object.flatMap (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:571:25)
    at Object.getCodeFixesAtPosition (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121236:23)
    at Proxy.<anonymous> (/Users/matb/.vscode-insiders/extensions/bierner.lit-html-1.11.0/node_modules/typescript-template-language-service-decorator/lib/template-language-service-decorator.js:144:20)
    at Proxy.<anonymous> (/Users/matb/.vscode-insiders/extensions/bierner.lit-html-1.11.0/node_modules/typescript-template-language-service-decorator/lib/template-language-service-decorator.js:144:20)
    at TSLintPlugin.getCodeFixesAtPosition (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.0.0/node_modules/typescript-tslint-plugin/out/plugin.js:143:34)
    at Proxy.intercept.getCodeFixesAtPosition.args (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.0.0/node_modules/typescript-tslint-plugin/out/plugin.js:75:25)
    at IOSession.Session.getCodeFixes (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:130280:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:129036:61)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:130454:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:130445:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:130454:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:130476:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:131773:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
```

**Comment by andrewbranch** [comment]
Turns out binding patterns in a `.then` or `.catch` were never supported! 😮
