### ISSUE TITLE
Signature HelpCannot read property 'pos' of undefined

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#29355]
**TypeScript Version:**  3.3.0-dev.20190108

**Search Terms:**
- signaturehelp

**Code**
For a TS file
```ts
console.log()


```

Manually request signature help on the last (empty) line of the file

**Bug**

````
[Trace  - 3:45:55 PM] Sending request: signatureHelp (9). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/x.ts",
    "line": 4,
    "offset": 4,
    "triggerReason": {
        "kind": "invoked"
    }
}
[Trace  - 3:45:55 PM] Response received: signatureHelp (9). Request took 20 ms. Success: false . Message: Error processing request. Cannot read property 'pos' of undefined
TypeError: Cannot read property 'pos' of undefined
    at Object.rangeContainsRange (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:93151:41)
    at _loop_6 (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:104026:36)
    at getContainingArgumentInfo (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:104033:31)
    at Object.getSignatureHelpItems (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:103648:32)
    at Object.getSignatureHelpItems (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:117894:37)
    at IOSession.Session.getSignatureHelpItems (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:125948:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:124903:61)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:126369:88
    at IOSession.Session.executeWithRequestId (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:126360:28)
    at IOSession.Session.executeCommand (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:126369:33)
    at IOSession.Session.onMessage (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:126391:35)
    at Interface.<anonymous> (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:127652:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
```

**Comment by RyanCavanaugh** [comment]
@rbuckton Can you take a look? We'd like this in 3.3 if practical

**Comment by rbuckton** [comment]
It looks like this is because passing `true` for `isManuallyInvoked` when calling `getContainingArgumentInfo` is shortcutting the `isSourceFile` check. Both the `rangeContainsRange` check and the following call to `getImmediatelyContainingArgumentOrContextualParameterInfo` require a node with a valid `parent`, and a `SourceFile` does not have a `parent`. 

A fix for this will be posted shortly.
