### ISSUE TITLE
Crash in Class Incorrectly Implements Interface codefix

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#29515]
**TypeScript Version:**  3.3.0-dev.20190118

**Search Terms:**

**Code**
Open this TS file in VS Code and make some random edits:

```ts
interface IFoo {
    /**
     * Does stuff 
     * 
     * @param x An argument
     */
    bar(x): void
}

class Foo implements IFoo
```

**Bug**

```
log.ts:173   ERR TypeScript Server Error (3.3.0-dev.20190118)
Error processing request. Cannot read property 'end' of undefined
TypeError: Cannot read property 'end' of undefined
    at getClassOrObjectBraceEnds (tsserver.js:108892:81)
    at ChangeTracker.getInsertNodeAtStartPrefixSuffix (tsserver.js:108622:84)
    at ChangeTracker.insertNodeAtStartWorker (tsserver.js:108615:136)
    at ChangeTracker.insertNodeAtClassStart (tsserver.js:108606:22)
    at tsserver.js:111666:175
    at outputMethod (tsserver.js:113648:21)
    at addNewNodeForMemberSymbol (tsserver.js:113627:25)
    at Object.createMissingMemberNodes (tsserver.js:113563:21)
    at addMissingDeclarations (tsserver.js:111666:21)
    at tsserver.js:111627:100
    at Function.ChangeTracker.with (tsserver.js:108416:17)
    at tsserver.js:111627:68
    at Object.mapDefined (tsserver.js:601:30)
    at Object.getCodeActions (tsserver.js:111626:27)
    at tsserver.js:109402:121
    at Object.flatMap (tsserver.js:504:25)
    at Object.getFixes (tsserver.js:109402:23)
    at tsserver.js:118606:35
    at Object.flatMap (tsserver.js:504:25)
    at Object.getCodeFixesAtPosition (tsserver.js:118604:23)
    at IOSession.Session.getCodeFixes (tsserver.js:126757:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:125562:61)
    at tsserver.js:126926:88
    at IOSession.Session.executeWithRequestId (tsserver.js:126917:28)
    at IOSession.Session.executeCommand (tsserver.js:126926:33)
    at IOSession.Session.onMessage (tsserver.js:126948:35)
    at Interface.<anonymous> (tsserver.js:128209:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20): Error: TypeScript Server Error (3.3.0-dev.20190118)
```

**Playground Link:** 

**Related Issues:**

**Comment by sandersn** [comment]
I can't repro this on typescript@next or 3.3.0-dev.20190118. Is there some context I'm missing, or some particular edits?

**Comment by mjbvz** [comment]
Just hit this again with TS 3.7.2. Repo:

1. Open the TS in VS Code:

```
interface IFoo {
    /**
     * Does stuff 
     * 
     * @param x An argument
     */
    bar(x): void   
}

class Foo implements IFoo  
```

1. Now select all

**Bug**
See the error:

```
  ERR <semantic> TypeScript Server Error (3.7.2)
Cannot read property 'end' of undefined
TypeError: Cannot read property 'end' of undefined
    at getClassOrObjectBraceEnds (tsserver.js:119817:81)
    at ChangeTracker.getInsertNodeAtStartPrefixSuffix (tsserver.js:119544:99)
    at ChangeTracker.insertNodeAtStartWorker (tsserver.js:119537:136)
    at ChangeTracker.insertNodeAtClassStart (tsserver.js:119528:22)
    at tsserver.js:123290:175
    at outputMethod (tsserver.js:125433:21)
    at addNewNodeForMemberSymbol (tsserver.js:125410:25)
    at Object.createMissingMemberNodes (tsserver.js:125324:21)
    at addMissingDeclarations (tsserver.js:123290:21)
    at tsserver.js:123251:100
    at Function.ChangeTracker.with (tsserver.js:119320:17)
    at tsserver.js:123251:68
    at Object.mapDefined (tsserver.js:565:30)
    at Object.getCodeActions (tsserver.js:123250:27)
```

**Comment by amcasey** [comment]
I believe [this user](https://developercommunity.visualstudio.com/content/problem/832049/extranodearguments-is-not-applied-to-second-langua.html) is hitting it in 3.7.2.

**Comment by sandersn** [comment]
The codefix for "Class incorrectly implements interface" crashes because some code expects to be able to find a begin and end brace for a class. It's general code, but I think it's only called from this codefix. Here's a repro for fourslash:

```
/// <reference path="fourslash.ts" />

//// interface I {
////    m(): void
//// }
//// class C/*c*/ implements I

verify.errorExistsBeforeMarker("c")
goTo.marker("c")
verify.codeFixAvailable()
```
