### ISSUE TITLE
Error: Debug Failure getDisplayName for babel project while getting program.getTypeChecker()

### ISSUE THREAD

**Issue by abhijitparkhi1983** [microsoft/TypeScript#29622]
**TypeScript Version:** : "typescript": "^3.0.3"

**Search Terms**:
getTypeChecker()
Error: Debug Failure
Object.assertDefined
getDisplayName
bable

**Code**
```
var options: ts.CompilerOptions = {
                noEmitOnError: true
                , strict: true
                , target: ts.ScriptTarget.Latest
                , module: ts.ModuleKind.CommonJS
                , skipLibCheck: true
                , experimentalDecorators: true
                , emitDecoratorMetadata : true
                , allowJs: true
                , noErrorTruncation : false
              };
        
            var compilerHost = ts.createCompilerHost(options);
            this.program = ts.createProgram(this.sourceFilesToParse, options, compilerHost);
            this.typeChecker = this.program.getTypeChecker();
```

**Expected behavior:**
Typecheker should return successfully without throwing the above exception.

**Actual behavior:**
When we give https://github.com/rolftimmermans/babel.git as input code (for this.sourceFilesToParse in the above code), we get following exception while creating the type checker object using this.program.getTypeChecker().

```
"Error: Debug Failure.
    at Object.assertDefined (..\node_modules\typescript\lib\typescript.js:1469:24)
    at getDisplayName (..\node_modules\typescript\lib\typescript.js:27251:129)
    at addError (..\node_modules\typescript\lib\typescript.js:27349:150)
    at Object.forEach (..\node_modules\typescript\lib\typescript.js:210:30)
    at declareSymbol (..\node_modules\typescript\lib\typescript.js:27351:28)
    at declareModuleMember (..\node_modules\typescript\lib\typescript.js:27370:28)
    at declareSourceFileMember (..\node_modules\typescript\lib\typescript.js:28414:19)
    at declareSymbolAndAddToSymbolTable (..\node_modules\typescript\lib\typescript.js:28362:28)
    at bindWorker (..\node_modules\typescript\lib\typescript.js:29021:28)
    at bind (..\node_modules\typescript\lib\typescript.js:28781:13)"
```

Note: The same program works well with other sample projects.

**Comment by RyanCavanaugh** [comment]
This crash is fixed in the current compiler. I reproduced it with TypeScript 3.0.3 and reduced the Babel input to:

```js
export default function () {}
export { foo as default } from "foo";
export { foo as default, bar } from "foo";
```

Running `tsc --allowJs repro.js` on TypeScript 3.0.3 throws `Error: Debug Failure` from `getDisplayName`. The same command on TypeScript `7.1.0-dev.20260818.1` no longer crashes and reports the intended diagnostics instead:

```text
repro.js(1,1): error TS2528: A module cannot have multiple default exports.
repro.js(2,17): error TS2528: A module cannot have multiple default exports.
repro.js(3,17): error TS2528: A module cannot have multiple default exports.
```
