### ISSUE TITLE
tsc --watch error: Diagnostic emitted without context

### ISSUE THREAD

**Issue by kidcosmic** [Microsoft/TypeScript#29814]
**TypeScript Version:**  3.4.0-dev.201xxxxx and @latest

**Search Terms:** watch diagnostic emitted without context

tsc works, but tsc --watch errors out

```
tsc --watch
```

**Expected behavior:**
Successful compilation, or at the very least, a better error message. Note, again, tsc works without --watch

**Actual behavior:**
```
[1:08:45 PM] Starting compilation in watch mode...

/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:71703
                throw e;
                ^

Error: Debug Failure. Diagnostic emitted without context
    at throwDiagnostic (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:65341:61)
    at handleSymbolAccessibilityError (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:65407:33)
    at Object.trackSymbol (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:65426:13)
    at lookupSymbolChain (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:28449:33)
    at symbolToTypeNode (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:28582:29)
    at createAnonymousTypeNode (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:27995:36)
    at typeToTypeNodeHelper (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:27935:28)
    at addPropertyToElementList (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:28277:59)
    at createTypeNodesFromResolvedType (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:28228:25)
    at createTypeNodeFromObjectType (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:28065:35)
```

Has something to do with my project, because error doesn't happen on other projects.

Copy of tsconfig.json

```js
{
  "compilerOptions": {
    /* Basic Options */
    "target": "esnext" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */,
    "module": "esnext" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */,
    "lib": [
      "es2017",
      "esnext"
    ] /* Specify library files to be included in the compilation. */,
    // "allowJs": true,                       /* Allow javascript files to be compiled. */
    // "checkJs": true,                       /* Report errors in .js files. */
    "jsx": "react-native" /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */,
    // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    // "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
    // "sourceMap": true,                     /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    // "outDir": "./",                        /* Redirect output structure to the directory. */
    // "rootDir": "./",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    // "composite": true,                     /* Enable project compilation */
    // "removeComments": true,                /* Do not emit comments to output. */
    "noEmit": true /* Do not emit outputs. */,
    // "importHelpers": true /* Import emit helpers from 'tslib'. */,
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */

    /* Strict Type-Checking Options */
    "strict": true /* Enable all strict type-checking options. */,
    // "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    // "strictNullChecks": true,              /* Enable strict null checks. */
    // "strictFunctionTypes": true,           /* Enable strict checking of function types. */
    // "strictPropertyInitialization": true,  /* Enable strict checking of property initialization in classes. */
    // "noImplicitThis": true,                /* Raise error on 'this' expressions with an implied 'any' type. */
    // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */

    /* Additional Checks */
    // "noUnusedLocals": true,                /* Report errors on unused locals. */
    // "noUnusedParameters": true,            /* Report errors on unused parameters. */
    // "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    // "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */

    /* Module Resolution Options */
    "moduleResolution": "node" /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */,
    // "baseUrl": "." /* Base directory to resolve non-absolute module names. */,
    // "paths": {
    //   "@assets/*": ["assets"]
    // } /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */,
    // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    // "typeRoots": ["node_modules", "node_modules/@types", "./s"],                       /* List of folders to include type definitions from. */
    // "types": [],                           /* Type declaration files to be included in compilation. */
    "allowSyntheticDefaultImports": true /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */,
    "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,
    // "preserveSymlinks": true,              /* Do not resolve the real path of symlinks. */

    /* Source Map Options */
    // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    // "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */
    "skipLibCheck": true
    // "importHelpers": true
  }
}
```

**Comment by kidcosmic** [comment]
Pretty big pure React native/TS project. Can NDA and send over to you guys

**Comment by weswigham** [comment]
Honestly, the stack depth here should be pretty shallow since that error can only happen when we never began a diagnostic context in the declaration emitter. If you can drop a `Error.stackTraceLimit = Infinity;` at the top of whichever typescript bundle you build with after the `use strict` (looks like `/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js`) and rerun the watch to get a bigger stacktrace and report that, it's _probably_ all I need.

**Comment by kidcosmic** [comment]
Your full stack:

```
Error: Debug Failure. Diagnostic emitted without context
    at throwDiagnostic (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:64692:61)
    at handleSymbolAccessibilityError (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:64758:33)
    at Object.trackSymbol (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:64777:13)
    at lookupSymbolChain (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:28296:33)
    at symbolToTypeNode (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:28429:29)
    at createAnonymousTypeNode (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:27845:36)
    at typeToTypeNodeHelper (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:27785:28)
    at addPropertyToElementList (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:28124:59)
    at createTypeNodesFromResolvedType (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:28075:25)
    at createTypeNodeFromObjectType (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:27915:35)
    at createAnonymousTypeNode (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:27869:42)
    at typeToTypeNodeHelper (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:27785:28)
    at /Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:27579:106
    at withContext (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:27619:37)
    at Object.typeToTypeNode (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:27579:28)
    at Object.createTypeOfDeclaration (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:48025:32)
    at /Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:65406:49
    at Object.mapDefined (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:532:30)
    at transformTopLevelDeclaration (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:65402:47)
    at visitDeclarationStatements (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:65363:26)
    at Object.visitNodes (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:53431:48)
    at transformRoot (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:64864:33)
    at /Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:1230:42
    at transformRoot (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:65849:82)
    at Object.map (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:379:29)
    at Object.transformNodes (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:65837:30)
    at emitDeclarationFileOrBundle (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:66148:43)
    at emitSourceFileOrBundle (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:66088:13)
    at forEachEmittedFile (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:66006:30)
    at Object.emitFiles (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:66076:9)
    at emitWorker (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:70984:33)
    at /Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:70955:66
    at runWithCancellationToken (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:71032:24)
    at Object.emit (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:70955:20)
    at Object.getFileEmitOutput (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:72270:34)
    at updateShapeSignature (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:72442:37)
    at getFilesAffectedByUpdatedShapeWhenModuleEmit (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:72589:46)
    at Object.getFilesAffectedBy (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:72409:144)
    at getNextAffectedFile (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:72697:51)
    at emitNextAffectedFile (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:72870:28)
    at Object.emit (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:72885:49)
    at emitFilesAndReportErrors (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:73954:26)
    at emitFilesAndReportErrorUsingBuilder (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:74046:13)
    at Object.watchCompilerHost.afterProgramCreate (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:75785:13)
    at synchronizeProgram (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:74213:22)
    at Object.createWatchProgram (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:74182:9)
    at createWatchOfConfigFile (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:75796:12)
    at Object.executeCommandLine (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:75681:17)
    at Object.<anonymous> (/Users/z/.config/yarn/global/node_modules/typescript/lib/tsc.js:75895:4)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/z/.config/yarn/global/node_modules/typescript/bin/tsc:2:1)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by weswigham** [comment]
Neat. Looks like our `ExpandoFunctionDeclaration` declaration emit is attempting to issue a visibility error without entering a diagnostic context (the `cleanup` call before it on the function declaration ended the context we made for the function itself).

Should be an easy fix.
