### ISSUE TITLE
Re-exporting JSX namespace causes Typescript to crash

### ISSUE THREAD

**Issue by just-boris** [Microsoft/TypeScript#30153]
**Search Terms:**

* Cannot read property 'get' of undefined
* getJsxLibraryManagedAttributes
* getJsxManagedAttributesFromLocatedAttributes

**Code**

**index.tsx**

```ts
import * as MyLib from "./library";

const content = <my-element/>;
```

**library.ts**

```ts
function createElement(element: string, props: any, ...children: any[]): any {}

namespace JSX {
  export interface IntrinsicElements {
    [key: string]: Record<string, any>;
  }
}

export { createElement, JSX };

```

**Expected behavior:**

The following code should compile

**Actual behavior:**

Compilation fails with the following error in the console:

```
$ ./node_modules/.bin/tsc -p tsconfig.json
/Users/serdiuk/coding/test/node_modules/typescript/lib/tsc.js:71803
                throw e;
                ^

TypeError: Cannot read property 'get' of undefined
    at getSymbol (/Users/serdiuk/coding/test/node_modules/typescript/lib/tsc.js:26100:38)
    at getJsxLibraryManagedAttributes (/Users/serdiuk/coding/test/node_modules/typescript/lib/tsc.js:40495:36)
    at getJsxManagedAttributesFromLocatedAttributes (/Users/serdiuk/coding/test/node_modules/typescript/lib/tsc.js:39854:30)
    at getJsxPropsTypeFromCallSignature (/Users/serdiuk/coding/test/node_modules/typescript/lib/tsc.js:39809:25)
    at getEffectiveFirstArgumentForJsxSignature (/Users/serdiuk/coding/test/node_modules/typescript/lib/tsc.js:39805:54)
    at resolveJsxOpeningLikeElement (/Users/serdiuk/coding/test/node_modules/typescript/lib/tsc.js:42133:112)
    at resolveSignature (/Users/serdiuk/coding/test/node_modules/typescript/lib/tsc.js:42170:28)
    at getResolvedSignature (/Users/serdiuk/coding/test/node_modules/typescript/lib/tsc.js:42182:26)
    at checkJsxOpeningLikeElementOrOpeningFragment (/Users/serdiuk/coding/test/node_modules/typescript/lib/tsc.js:40630:27)
    at checkJsxSelfClosingElementDeferred (/Users/serdiuk/coding/test/node_modules/typescript/lib/tsc.js:40274:13)
```

Tested on both v3.3.3333 and 3.4.0-dev

**Playground Link:** 

Not possible to reproduce in playground, since it requires multiple files interaction.
However, I have a simple reproduction here: https://github.com/just-boris/typescript-30153

**Related Issues:** 

* https://github.com/Microsoft/TypeScript/issues/8757

**Comment by RyanCavanaugh** [comment]
Definitely a bug, but I'm curious why you're doing this

**Comment by just-boris** [comment]
In my case, that was a re-export initially:

```js
export { createElement, JSX } from 'some-vdom-lib';
```

This code caused Typescript to crash, while wildcard export `export * from 'some-vdom-lib';` works fine

**Comment by pmkroeker** [comment]
This issue cropped up on me in https://github.com/preactjs/preact/pull/1703.

**Comment by pmkroeker** [comment]
SOLVED. My global install of TS was incorrect! Fixed when I updated my global install.
