### ISSUE TITLE
getApplicableRefactors Could not find file

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#30180]
Previously: #20785 (with dups #21791, #22553, #22554)

Stack for TS 3.3.3333
```
Error: Could not find file: '%PATH%'.
    at getValidSourceFile (tsserver.js:118280:23)
    at Object.getApplicableRefactors (tsserver.js:119058:24)
    at IOSession.Session.getApplicableRefactors (tsserver.js:126912:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:125785:61)
    at tsserver.js:127131:88
    at IOSession.Session.executeWithRequestId (tsserver.js:127122:28)
    at IOSession.Session.executeCommand (tsserver.js:127131:33)
    at IOSession.Session.onMessage (tsserver.js:127153:35)
    at Interface.<anonymous> (tsserver.js:128414:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
```

For the last 24 hours:

TSVersion | Distinct Paths
--- | ---
3.3.3333 | 43
3.3.3 | 142
3.3.1 | 16103
3.3.0-rc | 15
3.3.0-dev.20190101 | 2
3.2.4 | 11
3.2.2 | 1820
3.2.1-insiders.20181127 | 1
3.2.0-rc | 1
3.1.6 | 5
3.1.4 | 238
3.1.3 | 154
3.1.1 | 18
3.0.3 | 216
3.0.1 | 426
2.9.2 | 659
2.9.1 | 412
2.8.4 | 3
2.8.3-insiders.20180407 | 1
2.8.3 | 392
2.8.1 | 236
2.8.0-dev.20180321 | 1
2.7.2 | 243
2.6.2 | 5

Note: Telemetry is from VS Code.

**Comment by amcasey** [comment]
@RyanCavanaugh This seems to be a frequent and longstanding problem.

**Comment by sheetalkamat** [comment]
@amcasey @RyanCavanaugh I am not sure how to add more log to this but this call wouldn't fail unless there was another exception in some other command and project and ls are in bad state and their truth don't match as before doing calling LS for any semantic operation, we always get the project ensuring that file belongs to project.

May be we can throw special exception from getValidSourceFile and add more information like program.getSourceFiles().map(f => f.fileName) and projectService's script infos and project's scriptInfos.

**Comment by sheetalkamat** [comment]
I have merged #30437 to get more information to be able to diagnose this further. We can investigate once we have that information.

**Comment by Siegrift** [comment]
Hi,

I already commented on #39513 on the issue generated by TS bot, but I am not sure if anyone noticed the comment.

I can reproduce this issue locally with [tsetse language plugin](https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsetse/language_service_plugin.ts). If you have troubles reproducing this issue I can provide you with details how to reproduce this problem locally.

**Comment by Siegrift** [comment]
**Update:** 

This issue for tsetse language plugin can be fixed using this patch: https://github.com/bazelbuild/rules_typescript/pull/506?fbclid=IwAR1lEwjPEhG41w-Vfecn30eFK_6r9IrbmWlIRcYMuoRfrPcKxUkLbzBflHQ

Others experiencing this issue might have the same problem.
