### ISSUE TITLE
convertTypeAcquisition Cannot read property 'enable' of undefined

### ISSUE THREAD

**Issue by svipas** [microsoft/TypeScript#30213]
- VSCode Version: 1.31.1
- OS Version: macOS latest

Settings:
```
  "editor.tabCompletion": "on",
  "editor.quickSuggestions": false,
  "editor.suggestOnTriggerCharacters": false
```

It happens sometimes, I can't reproduce it 100%. It happens on a new Untitled file, or in an existing project. For e.g. create a new Untitled file, select language mode to JavaScript and try to autocomplete `constructor` in `class` by writing only a few letters and pressing `tab` since we are using `"editor.tabCompletion": "on"`, you will get a popup with `Loading...` message and this error below:

```
[2019-03-04 09:41:40.718] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2019-03-04 09:41:40.720] [exthost] [error] Error: TypeScript Server Error (3.3.1)
Error processing request. Cannot read property 'enable' of undefined
TypeError: Cannot read property 'enable' of undefined
    at convertTypeAcquisition (tsserver.js:124003:37)
    at ProjectService.sendProjectTelemetry (tsserver.js:123984:38)
    at ConfiguredProject.updateGraph (tsserver.js:122863:37)
    at updateProjectIfDirty (tsserver.js:123158:45)
    at updateGraph (tsserver.js:123466:34)
    at Map.forEach (<anonymous>)
    at ProjectService.ensureProjectStructuresUptoDate (tsserver.js:123469:41)
    at ProjectService.doEnsureDefaultProjectForFile (tsserver.js:123454:22)
    at ProjectService.ensureDefaultProjectForFile (tsserver.js:123451:75)
    at IOSession.Session.getFileAndProjectWorker (tsserver.js:126459:87)
    at IOSession.Session.getFileAndProject (tsserver.js:126444:29)
    at IOSession.Session.getApplicableRefactors (tsserver.js:126886:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:125761:61)
    at tsserver.js:127107:88
    at IOSession.Session.executeWithRequestId (tsserver.js:127098:28)
    at IOSession.Session.executeCommand (tsserver.js:127107:33)
    at IOSession.Session.onMessage (tsserver.js:127129:35)
    at Interface.<anonymous> (tsserver.js:128390:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
	at v.dispatchResponse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:178103)
	at v.dispatchMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:176857)
	at constructor._reader.onData.e (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:176213)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:113)
	at t.Reader.onLengthData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:182286)
	at Socket.t.Reader.constructor.e.on.e (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:181934)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

Also, sometimes autocomplete doesn't work and I get this error:

```
[2019-03-04 09:50:17.898] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2019-03-04 09:50:17.898] [exthost] [error] {"label":"Acquiring typings...","detail":"Acquiring typings definitions for IntelliSense."}
```

But after several try it starts to work again. Watch this gif below till the end you will see how to reproduce one of the problems.

![kapture 2019-03-04 at 9 52 55](https://user-images.githubusercontent.com/10441177/53718373-b02e0080-3e63-11e9-8f81-45e5feab2db6.gif)

**Comment by mjbvz** [comment]
Looks like a TS Server error. Can you please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions). 

Do you still see this error when using the newer TS version?

**Comment by svipas** [comment]
I can't reproduce it on my PC, but I will try to do the same at work and I will say if newer version of TS helps.

**Comment by svipas** [comment]
I was able to reproduce it one more time with `"typescript": "^3.4.0-dev.20190306"` and I got:

```
[2019-03-06 10:37:54.463] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2019-03-06 10:37:54.463] [exthost] [error] {"label":"Acquiring typings...","detail":"Acquiring typings definitions for IntelliSense."}
```

**Comment by sheetalkamat** [comment]
@svipas can you please provide complete tsserver and typing installer log when you are able to reproduce this issue. We would need that to be able to investigate this.
You can upload logs by following these steps:
1. With "typescript.tsserver.log": "verbose" enabled
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. You can share the logs using
    - either by sharing logs in the folder that gets opened by running `open tsserver log` from command palette 
    or
    - Run ```code --upload-logs``` on the command line (or ```code-insiders --upload-logs``` if using vscode insiders) and follow instructions and Then share the log file ID

**Comment by svipas** [comment]
[tsserver.log](https://github.com/Microsoft/TypeScript/files/2940208/tsserver.log)

@sheetalkamat Thanks for the info, I managed to reproduce it and I'm sharing logs with you. I hope it helps!

**Comment by sheetalkamat** [comment]
@svipas I don't see the exception you mentioned in the issue in the log. Can you please make sure if you are sharing tsserver log from correct session? Also please share ti log as well. Thanks.

**Comment by svipas** [comment]
@sheetalkamat But this is a log from that moment when I got that error, I opened a VS Code Log (Extension Host) and saw it after that I uploaded log here. What is `ti` log?

**Comment by sheetalkamat** [comment]
@svipas I do not see any exception in the new logs provided as well. @mjbvz Do you know where might the exception coming from since I don't see anything wrong in the server.

**Comment by sheetalkamat** [comment]
@mjbvz I am assinging this issue to you since i dont see any error or anything wrong in tsserver and ti log shared at the timestamp when @svipas sees error

**Comment by mjbvz** [comment]
@svipas Are those logs from sessions where you saw the error with `convertTypeAcquisition` in the stack printed in the console?

**Comment by svipas** [comment]
@mjbvz yes

**Comment by RyanCavanaugh** [comment]
@svipas are you still seeing this?

**Comment by svipas** [comment]
@RyanCavanaugh Tried to reproduce it right now, but seems no. And honestly I forgot about this issue so I believe it doesn't exist anymore and can be closed :)
