### ISSUE TITLE
"updateOpen" debug failure in getConfigFileNameForFile

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#30266]
**TypeScript Version:**  3.4.0-dev.20190306

**Repo**
1. In the VS Code code base using TS 3.4+ (Note that you must be using a version of VS Code that has this pr merged in: https://github.com/Microsoft/vscode/pull/69931)
1. Search for `copyright` under `./src/vs/**/*.ts` and replace it with `copyright2`

**Bug:**
This generates a large `updateOpen` request to updates multiple files. For this request, I see the following error in the TS Server log:

```
    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at ProjectService.getConfigFileNameForFile (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:124402:30)
        at ProjectService.assignProjectToOpenedScriptInfo (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:125212:43)
        at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:125398:76
        at Array.forEach (<anonymous>)
        at ProjectService.applyChangesInOpenFiles (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:125398:37)
        at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:126071:46)
        at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:127674:88
        at IOSession.Session.executeWithRequestId (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:127665:28)
        at IOSession.Session.executeCommand (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:127674:33)
        at IOSession.Session.onMessage (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:127696:35)
        at Interface.<anonymous> (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:128957:27)
        at Interface.emit (events.js:182:13)
        at Interface._onLine (readline.js:290:10)
        at Interface._normalWrite (readline.js:433:12)
        at Socket.ondata (readline.js:149:10)
        at Socket.emit (events.js:182:13)
        at addChunk (_stream_readable.js:279:12)
        at readableAddChunk (_stream_readable.js:264:11)
        at Socket.Readable.push (_stream_readable.js:219:10)
        at Pipe.onread (net.js:636:20)
```

Attached TS Server log: [tsserver.log.zip](https://github.com/Microsoft/TypeScript/files/2943931/tsserver.log.zip)

**Comment by sheetalkamat** [comment]
That seems valid assert. In the request, file opened is same as closed: `/Users/matb/projects/vscode/src/vs/editor/browser/editorExtensions.ts`

```
{"seq":28,"type":"request","command":"updateOpen","arguments":{"openFiles":[{"file":"/Users/matb/projects/vscode/src/vs/editor/browser/editorExtensions.ts","fileContent":"/*---------------------------------------------------------------------------------------------\n *  Copyright (c) Microsoft Corporation. All rights reserved.\n *  Licensed under the MIT License. See License.txt in the project root for license information.\n *--------------------------------------------------------------------------------------------*/\n\nimport { IPosition } from 'vs/base/browser/ui/contextview/contextview';\nimport { illegalArgument } from 'vs/base/common/errors';\nimport { URI } from 'vs/base/common/uri';\nimport { ICodeEditor } from 'vs/editor/browser/editorBrowser';\nimport { ICodeEditorService } from 'vs/editor/browser/services/codeEditorService';\nimport { Position } from 'vs/editor/common/core/position';\nimport { IEditorContribution } from 'vs/editor/common/editorCommon';\nimport { ITextModel } from 'vs/editor/common/model';\nimport { IModelService } from 'vs/editor/common/services/modelService';\nimport { ITextModelService } from 'vs/editor/common/services/resolverService';\nimport { MenuId, MenuRegistry } from 'vs/platform/actions/common/actions';\nimport { CommandsRegistry, ICommandHandlerDescription } from 'vs/platform/commands/common/commands';\nimport { ContextKeyExpr, IContextKeyService } from 'vs/platform/contextkey/common/contextkey';\nimport { IConstructorSignature1, ServicesAccessor } from 'vs/platform/instantiation/common/instantiation';\nimport { IKeybindings, KeybindingsRegistry } from 'vs/platform/keybinding/common/keybindingsRegistry';\nimport { Registry } from 'vs/platform/registry/common/platform';\nimport { ITelemetryService } from 'vs/platform/telemetry/common/telemetry';\n\nexport type ServicesAccessor = ServicesAccessor;\nexport type IEditorContributionCtor = IConstructorSignature1<ICodeEditor, IEditorContribution>;\n\n//#region Command\n\nexport interface ICommandKeybindingsOptions extends IKeybindings {\n\tkbExpr?: ContextKeyExpr | null;\n\tweight: number;\n}\nexport interface ICommandMenubarOptions {\n\tmenuId: MenuId;\n\tgroup: string;\n\torder: number;\n\twhen?: ContextKeyExpr;\n\ttitle: string;\n}\nexport interface ICommandOptions {\n\tid: string;\n\tprecondition: ContextKeyExpr | null;\n\tkbOpts?: ICommandKeybindingsOptions | null;\n\tdescription?: ICommandHandlerDescription;\n\tmenubarOpts?: ICommandMenubarOptions;\n}\nexport abstract class Command {\n\tpublic readonly id: string;\n\tpublic readonly precondition: ContextKeyExpr | null;\n\tprivate readonly _kbOpts: ICommandKeybindingsOptions | null | undefined;\n\tprivate readonly _menubarOpts: ICommandMenubarOptions | null | undefined;\n\tprivate readonly _description: ICommandHandlerDescription | null | undefined;\n\n\tconstructor(opts: ICommandOptions) {\n\t\tthis.id = opts.id;\n\t\tthis.precondition = opts.precondition;\n\t\tthis._kbOpts = opts.kbOpts;\n\t\tthis._menubarOpts = opts.menubarOpts;\n\t\tthis._description = opts.description;\n\t}\n\n\tpublic register(): void {\n\n\t\tif (this._menubarOpts) {\n\t\t\tMenuRegistry.appendMenuItem(this._menubarOpts.menuId, {\n\t\t\t\tgroup: this._menubarOpts.group,\n\t\t\t\tcommand: {\n\t\t\t\t\tid: this.id,\n\t\t\t\t\ttitle: this._menubarOpts.title,\n\t\t\t\t\t// precondition: this.precondition\n\t\t\t\t},\n\t\t\t\twhen: this._menubarOpts.when,\n\t\t\t\torder: this._menubarOpts.order\n\t\t\t});\n\t\t}\n\n\t\tif (this._kbOpts) {\n\t\t\tlet kbWhen = this._kbOpts.kbExpr;\n\t\t\tif (this.precondition) {\n\t\t\t\tif (kbWhen) {\n\t\t\t\t\tkbWhen = ContextKeyExpr.and(kbWhen, this.precondition);\n\t\t\t\t} else {\n\t\t\t\t\tkbWhen = this.precondition;\n\t\t\t\t}\n\t\t\t}\n\n\t\t\tKeybindingsRegistry.registerCommandAndKeybindingRule({\n\t\t\t\tid: this.id,\n\t\t\t\thandler: (accessor, args) => this.runCommand(accessor, args),\n\t\t\t\tweight: this._kbOpts.weight,\n\t\t\t\twhen: kbWhen || null,\n\t\t\t\tprimary: this._kbOpts.primary,\n\t\t\t\tsecondary: this._kbOpts.secondary,\n\t\t\t\twin: this._kbOpts.win,\n\t\t\t\tlinux: this._kbOpts.linux,\n\t\t\t\tmac: this._kbOpts.mac,\n\t\t\t\tdescription: this._description\n\t\t\t});\n\n\t\t} else {\n\n\t\t\tCommandsRegistry.registerCommand({\n\t\t\t\tid: this.id,\n\t\t\t\thandler: (accessor, args) => this.runCommand(accessor, args),\n\t\t\t\tdescription: this._description\n\t\t\t});\n\t\t}\n\t}\n\n\tpublic abstract runCommand(accessor: ServicesAccessor, args: any): void | Promise<void>;\n}\n\n//#endregion Command\n\n//#region EditorCommand\n\nexport interface IContributionCommandOptions<T> extends ICommandOptions {\n\thandler: (controller: T, args: any) => void;\n}\nexport interface EditorControllerCommand<T extends IEditorContribution> {\n\tnew(opts: IContributionCommandOptions<T>): EditorCommand;\n}\nexport abstract class EditorCommand extends Command {\n\n\t/**\n\t * Create a command class that is bound to a certain editor contribution.\n\t */\n\tpublic static bindToContribution<T extends IEditorContribution>(controllerGetter: (editor: ICodeEditor) => T): EditorControllerCommand<T> {\n\t\treturn class EditorControllerCommandImpl extends EditorCommand {\n\t\t\tprivate readonly _callback: (controller: T, args: any) => void;\n\n\t\t\tconstructor(opts: IContributionCommandOptions<T>) {\n\t\t\t\tsuper(opts);\n\n\t\t\t\tthis._callback = opts.handler;\n\t\t\t}\n\n\t\t\tpublic runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor, args: any): void {\n\t\t\t\tconst controller = controllerGetter(editor);\n\t\t\t\tif (controller) {\n\t\t\t\t\tthis._callback(controllerGetter(editor), args);\n\t\t\t\t}\n\t\t\t}\n\t\t};\n\t}\n\n\tpublic runCommand(accessor: ServicesAccessor, args: any): void | Promise<void> {\n\t\tconst codeEditorService = accessor.get(ICodeEditorService);\n\n\t\t// Find the editor with text focus or active\n\t\tconst editor = codeEditorService.getFocusedCodeEditor() || codeEditorService.getActiveCodeEditor();\n\t\tif (!editor) {\n\t\t\t// well, at least we tried...\n\t\t\treturn;\n\t\t}\n\n\t\treturn editor.invokeWithinContext((editorAccessor) => {\n\t\t\tconst kbService = editorAccessor.get(IContextKeyService);\n\t\t\tif (!kbService.contextMatchesRules(this.precondition)) {\n\t\t\t\t// precondition does not hold\n\t\t\t\treturn;\n\t\t\t}\n\n\t\t\treturn this.runEditorCommand(editorAccessor, editor!, args);\n\t\t});\n\t}\n\n\tpublic abstract runEditorCommand(accessor: ServicesAccessor | null, editor: ICodeEditor, args: any): void | Promise<void>;\n}\n\n//#endregion EditorCommand\n\n//#region EditorAction\n\nexport interface IEditorCommandMenuOptions {\n\tgroup: string;\n\torder: number;\n\twhen?: ContextKeyExpr;\n}\nexport interface IActionOptions extends ICommandOptions {\n\tlabel: string;\n\talias: string;\n\tmenuOpts?: IEditorCommandMenuOptions;\n}\nexport abstract class EditorAction extends EditorCommand {\n\n\tpublic readonly label: string;\n\tpublic readonly alias: string;\n\tprivate readonly menuOpts: IEditorCommandMenuOptions | undefined;\n\n\tconstructor(opts: IActionOptions) {\n\t\tsuper(opts);\n\t\tthis.label = opts.label;\n\t\tthis.alias = opts.alias;\n\t\tthis.menuOpts = opts.menuOpts;\n\t}\n\n\tpublic register(): void {\n\n\t\tif (this.menuOpts) {\n\t\t\tMenuRegistry.appendMenuItem(MenuId.EditorContext, {\n\t\t\t\tcommand: {\n\t\t\t\t\tid: this.id,\n\t\t\t\t\ttitle: this.label\n\t\t\t\t},\n\t\t\t\twhen: ContextKeyExpr.and(this.precondition, this.menuOpts.when),\n\t\t\t\tgroup: this.menuOpts.group,\n\t\t\t\torder: this.menuOpts.order\n\t\t\t});\n\t\t}\n\n\t\tsuper.register();\n\t}\n\n\tpublic runEditorCommand(accessor: ServicesAccessor, editor: ICodeEditor, args: any): void | Promise<void> {\n\t\tthis.reportTelemetry(accessor, editor);\n\t\treturn this.run(accessor, editor, args || {});\n\t}\n\n\tprotected reportTelemetry(accessor: ServicesAccessor, editor: ICodeEditor) {\n\t\t/* __GDPR__\n\t\t\t\"editorActionInvoked\" : {\n\t\t\t\t\"name\" : { \"classification\": \"SystemMetaData\", \"purpose\": \"FeatureInsight\" },\n\t\t\t\t\"id\": { \"classification\": \"SystemMetaData\", \"purpose\": \"FeatureInsight\" },\n\t\t\t\t\"${include}\": [\n\t\t\t\t\t\"${EditorTelemetryData}\"\n\t\t\t\t]\n\t\t\t}\n\t\t*/\n\t\taccessor.get(ITelemetryService).publicLog('editorActionInvoked', { name: this.label, id: this.id, ...editor.getTelemetryData() });\n\t}\n\n\tpublic abstract run(accessor: ServicesAccessor, editor: ICodeEditor, args: any): void | Promise<void>;\n}\n\n//#endregion EditorAction\n\n// --- Registration of commands and actions\n\nexport function registerLanguageCommand(id: string, handler: (accessor: ServicesAccessor, args: { [n: string]: any }) => any) {\n\tCommandsRegistry.registerCommand(id, (accessor, args) => handler(accessor, args || {}));\n}\n\ninterface IDefaultArgs {\n\tresource: URI;\n\tposition: IPosition;\n\t[name: string]: any;\n}\n\nexport function registerDefaultLanguageCommand(id: string, handler: (model: ITextModel, position: Position, args: IDefaultArgs) => any) {\n\tregisterLanguageCommand(id, function (accessor, args: IDefaultArgs) {\n\n\t\tconst { resource, position } = args;\n\t\tif (!(resource instanceof URI)) {\n\t\t\tthrow illegalArgument('resource');\n\t\t}\n\t\tif (!Position.isIPosition(position)) {\n\t\t\tthrow illegalArgument('position');\n\t\t}\n\n\t\tconst model = accessor.get(IModelService).getModel(resource);\n\t\tif (model) {\n\t\t\tconst editorPosition = Position.lift(position);\n\t\t\treturn handler(model, editorPosition, args);\n\t\t}\n\n\t\treturn accessor.get(ITextModelService).createModelReference(resource).then(reference => {\n\t\t\treturn new Promise((resolve, reject) => {\n\t\t\t\ttry {\n\t\t\t\t\tconst result = handler(reference.object.textEditorModel, Position.lift(position), args);\n\t\t\t\t\tresolve(result);\n\t\t\t\t} catch (err) {\n\t\t\t\t\treject(err);\n\t\t\t\t}\n\t\t\t}).finally(() => {\n\t\t\t\treference.dispose();\n\t\t\t});\n\t\t});\n\t});\n}\n\nexport function registerEditorCommand<T extends EditorCommand>(editorCommand: T): T {\n\tEditorContributionRegistry.INSTANCE.registerEditorCommand(editorCommand);\n\treturn editorCommand;\n}\n\nexport function registerEditorAction(ctor: { new(): EditorAction; }): void {\n\tEditorContributionRegistry.INSTANCE.registerEditorAction(new ctor());\n}\n\nexport function registerInstantiatedEditorAction(editorAction: EditorAction): void {\n\tEditorContributionRegistry.INSTANCE.registerEditorAction(editorAction);\n}\n\nexport function registerEditorContribution(ctor: IEditorContributionCtor): void {\n\tEditorContributionRegistry.INSTANCE.registerEditorContribution(ctor);\n}\n\nexport namespace EditorExtensionsRegistry {\n\n\texport function getEditorCommand(commandId: string): EditorCommand {\n\t\treturn EditorContributionRegistry.INSTANCE.getEditorCommand(commandId);\n\t}\n\n\texport function getEditorActions(): EditorAction[] {\n\t\treturn EditorContributionRegistry.INSTANCE.getEditorActions();\n\t}\n\n\texport function getEditorContributions(): IEditorContributionCtor[] {\n\t\treturn EditorContributionRegistry.INSTANCE.getEditorContributions();\n\t}\n}\n\n// Editor extension points\nconst Extensions = {\n\tEditorCommonContributions: 'editor.contributions'\n};\n\nclass EditorContributionRegistry {\n\n\tpublic static readonly INSTANCE = new EditorContributionRegistry();\n\n\tprivate readonly editorContributions: IEditorContributionCtor[];\n\tprivate readonly editorActions: EditorAction[];\n\tprivate readonly editorCommands: { [commandId: string]: EditorCommand; };\n\n\tconstructor() {\n\t\tthis.editorContributions = [];\n\t\tthis.editorActions = [];\n\t\tthis.editorCommands = Object.create(null);\n\t}\n\n\tpublic registerEditorContribution(ctor: IEditorContributionCtor): void {\n\t\tthis.editorContributions.push(ctor);\n\t}\n\n\tpublic registerEditorAction(action: EditorAction) {\n\t\taction.register();\n\t\tthis.editorActions.push(action);\n\t}\n\n\tpublic getEditorContributions(): IEditorContributionCtor[] {\n\t\treturn this.editorContributions.slice(0);\n\t}\n\n\tpublic getEditorActions(): EditorAction[] {\n\t\treturn this.editorActions.slice(0);\n\t}\n\n\tpublic registerEditorCommand(editorCommand: EditorCommand) {\n\t\teditorCommand.register();\n\t\tthis.editorCommands[editorCommand.id] = editorCommand;\n\t}\n\n\tpublic getEditorCommand(commandId: string): EditorCommand {\n\t\treturn (this.editorCommands[commandId] || null);\n\t}\n\n}\nRegistry.add(Extensions.EditorCommonContributions, EditorContributionRegistry.INSTANCE);\n","scriptKindName":"TS","projectRootPath":"/Users/matb/projects/vscode"}],"closedFiles":["/Users/matb/projects/vscode/src/vs/editor/browser/editorExtensions.ts"]}}
```

**Comment by jruddell** [comment]
I'm getting this exact error, my tsserver is hogging 100% cpu and I was looking into what is causing it. Are these related possibly?
