### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by pocesar** [microsoft/TypeScript#30269]
**TypeScript Version:**  3.4.0-dev.20190307

**Search Terms:** typeerror, language server

**Code**

```tsx
// Was renaming  a React component from GymForm to GymAddForm, removed the props from the interface, then the error appeared

// form.tsx
export interface FormProps {
 // had 
 // mode: 'add' | 'edit' 
 // here
}

export const GymAddForm: React.FunctionComponent<FormProps> = (props) => {
} // was GymForm, was editing another file that included this one

/*********************************/

// index.tsx
import { GymAddForm } from './form' // was GymForm
//...
    '/add': route({
      view: <GymAddForm /> // was <GymForm mode="add" />
    })
//...
```

```
[2019-03-08 04:35:12.667] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2019-03-08 04:35:12.668] [exthost] [error] Error: TypeScript Server Error (3.4.0-dev.20190307)
Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at pipelineEmitWithHint (tsserver.js:82991:39)
    at print (tsserver.js:82893:13)
    at Object.writeNode (tsserver.js:82826:13)
    at tsserver.js:105353:25
    at Object.mapToDisplayParts (tsserver.js:95290:13)
    at createSignatureHelpParameterForTypeParameter (tsserver.js:105351:35)
    at tsserver.js:105322:90
    at Array.map (<anonymous>)
    at itemInfoForTypeParameters (tsserver.js:105322:64)
    at getSignatureHelpItem (tsserver.js:105299:95)
    at tsserver.js:105272:79
    at Array.map (<anonymous>)
    at createSignatureHelpItems (tsserver.js:105272:36)
    at tsserver.js:104877:23
    at Object.runWithCancellationToken (tsserver.js:31334:28)
    at Object.getSignatureHelpItems (tsserver.js:104875:32)
    at Proxy.getSignatureHelpItems (tsserver.js:119615:37)
    at IOSession.Session.getSignatureHelpItems (tsserver.js:127702:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:126661:61)
    at tsserver.js:128123:88
    at IOSession.Session.executeWithRequestId (tsserver.js:128114:28)
    at IOSession.Session.executeCommand (tsserver.js:128123:33)
    at IOSession.Session.onMessage (tsserver.js:128145:35)
    at Interface.<anonymous> (tsserver.js:129406:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
	at Function.create (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:173227)
	at v.dispatchResponse (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:178533)
	at v.dispatchMessage (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:177285)
	at constructor._reader.onData.e (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:176641)
	at u.fire (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:43:416)
	at t.Reader.onLengthData (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:182501)
	at Socket.t.Reader.constructor.e.on.e (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:182149)
	at Socket.emit (events.js:182:13)
	at Socket.EventEmitter.emit (domain.js:442:20)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

**Playground Link:** 

**Related Issues:**  
#6497 #15865 #27214 #27092 #28810

**Comment by RyanCavanaugh** [comment]
The pasted example does not include the `route` declaration, the React declarations, the `tsconfig.json` settings, or the exact editor position where signature help was requested. With TypeScript 3.4.0-dev.20190307, the pasted `index.tsx` returns “No content available” for signature help; after supplying the missing React and `route` declarations, signature help completes normally.

Please provide the complete `route` declaration (including all referenced types), the relevant React type declarations or package version, `tsconfig.json`, and the complete before-and-after contents of the file that changed. Also include the cursor location and editor action that requests signature help when the server crashes.
