### ISSUE TITLE
`gulp LKG` fails after `git checkout -- lib`

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#30346]
Steps

```sh
gulp clean
gulp LKG
vim src/compiler/core.ts # this is any edit
git checkout -- lib
gulp LKG
```

Output

```
~/TypeScript$ gulp LKG
[14:37:57] Using gulpfile ~/TypeScript/Gulpfile.js
[14:37:57] Starting 'LKG'...
[14:37:57] Starting 'generateLibs'...
[14:37:57] Starting 'buildScripts'...
[14:37:57] Finished 'generateLibs' after 208 ms
[14:37:57] Finished 'buildScripts' after 330 ms
[14:37:57] Starting 'generateDiagnostics'...
[14:37:57] Finished 'generateDiagnostics' after 542 μs
[14:37:57] Starting 'localize'...
[14:37:57] Starting 'buildTsc'...
[14:37:57] Starting 'buildServer'...
[14:37:57] Starting 'buildReleaseTsc'...
[14:37:57] Starting 'buildTypescriptServicesOut'...
[14:37:57] Starting 'buildServerLibraryOut'...
[14:37:57] Starting 'buildCancellationToken'...
[14:37:57] Starting 'buildTypingsInstaller'...
[14:37:57] Starting 'buildWatchGuard'...
[14:37:57] Starting 'generateTypesMap'...
[14:37:57] Finished 'localize' after 4.73 ms
[14:37:57] Finished 'generateTypesMap' after 6.16 ms
/home/daniel/shared/TypeScript3/lib/tsc.js:1360
            throw e;
            ^

Error: Debug Failure.
    at Object.assertDefined (/home/daniel/shared/TypeScript3/lib/tsc.js:1365:24)
    at Object.emitUsingBuildInfo (/home/daniel/shared/TypeScript3/lib/tsc.js:67687:52)
    at updateBundle (/home/daniel/shared/TypeScript3/lib/tsc.js:77384:34)
    at Object.buildAllProjects (/home/daniel/shared/TypeScript3/lib/tsc.js:77536:21)
    at performBuild (/home/daniel/shared/TypeScript3/lib/tsc.js:77968:36)
    at Object.executeCommandLine (/home/daniel/shared/TypeScript3/lib/tsc.js:77820:24)
    at Object.<anonymous> (/home/daniel/shared/TypeScript3/lib/tsc.js:78143:4)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
[14:38:28] 'buildTsc' errored after 30 s
[14:38:28] Error: Process exited with code: 1
    at ChildProcess.proc.on.exitCode (/home/daniel/shared/TypeScript3/scripts/build/utils.js:52:24)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:460:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
[14:38:28] 'LKG' errored after 31 s
[14:38:28] The following tasks did not complete: buildServer, <series>, <series>, <parallel>, buildReleaseTsc, buildTypescriptServicesOut, buildServerLibraryOut, buildCancellationToken, buildTypingsInstaller, buildWatchGuard
[14:38:28] Did you forget to signal async completion?
```

**Comment by weswigham** [comment]
@sheetalkamat this looks like a crash in the bundle info code?

**Comment by sheetalkamat** [comment]
Looking.

**Comment by sheetalkamat** [comment]
Marking it as also a bug as this is happening because `tsc/tsconfig.release.json` doesn't have incremental true yet we queue up incremental build when there is no .d.ts change in `compiler.release.json` build
