### ISSUE TITLE
No intellisense to implement TypeScript interface when there is a negative number type union

### ISSUE THREAD

**Issue by Cerlancism** [microsoft/TypeScript#30431]
Version: 1.32.1 (system setup)
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date: 2019-03-08T00:51:49.278Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Create a TypeScript interface with a property of negative number union type
2. Create a class to implement that interface
3. Alt enter the class name to see intellisense to auto fill required implmentations

Without negative number type union works
![Works](https://user-images.githubusercontent.com/28769707/54174864-96279a00-44c3-11e9-9a86-40ed016a95e7.png)

With negative number type union will not work
![Not working](https://user-images.githubusercontent.com/28769707/54174872-9b84e480-44c3-11e9-8eda-2cc571a10f5b.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
Tested on typescript@3.4.0-dev.20190315

Code:

```ts
interface X {
    value: -1 | 0 | 1;

}

class Y implements X {

}
```

I see the following debug failure:

```
[Trace  - 10:13:21 AM] Response received: getCodeFixes (18). Request took 2 ms. Success: false . Message: Error processing request. Debug Failure. False expression: Token end is child end
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:109272:34)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:109219:21
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16515:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16686:24)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:109218:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:109278:21)
    at processChildNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:109329:48)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:109221:21
    at visitNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16520:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16662:24)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:109218:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:109278:21)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:109219:21
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16515:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:16588:21)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:109218:20)
    at formatSpanWorker (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:109036:17)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:109000:140
    at Object.getFormattingScanner (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:107806:23)
    at Object.formatNodeGivenIndentation (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:109000:31)
    at getFormattedTextOfNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:111004:45)
    at format (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:110982:52)
    at computeNewText (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:110985:23)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:110955:89
    at Array.map (<anonymous>)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:110954:50
    at Array.map (<anonymous>)
    at Object.getTextChangesFromChanges (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:110940:86)
    at ChangeTracker.getChanges (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:110910:45)
    at Function.ChangeTracker.with (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:110453:32)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:113649:68
    at Object.mapDefined (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:668:30)
    at Object.getCodeActions (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:113648:27)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:111438:121
    at Object.flatMap (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:571:25)
    at Object.getFixes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:111438:23)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:121038:35
    at Object.flatMap (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:571:25)
    at Object.getCodeFixesAtPosition (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:121036:23)
    at IOSession.Session.getCodeFixes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:130062:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:128834:61)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:130236:88
    at IOSession.Session.executeWithRequestId (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:130227:28)
    at IOSession.Session.executeCommand (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:130236:33)
    at IOSession.Session.onMessage (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:130258:35)
    at Interface.<anonymous> (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131555:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
```

**Comment by Kingwl** [comment]
Related: #29330 ?
A pr here: https://github.com/Microsoft/TypeScript/pull/29492

**Comment by Cerlancism** [comment]
Looks like its fixed. Thanks for the work!
