### ISSUE TITLE
Error on globalThis type extension

### ISSUE THREAD

**Issue by vvakame** [Microsoft/TypeScript#30459]
**TypeScript Version:**  Version 3.4.0-dev.20190316

**Search Terms:**
`globalThis` `Cannot read property 'length' of undefined`

**Code**

```extension.d.ts
declare global {
    namespace globalThis  {
        var test: string;
    }

    namespace foo {
        var bar: string;
    }
}

export {}
```

```index.ts
import "./extention";

globalThis.test = "a-b";
console.log(globalThis.test.split("-"));
```

**Expected behavior:**
compile succeed.

**Actual behavior:**
raise error by tsc

```
/Users/vvakame/.nodebrew/node/v11.10.1/lib/node_modules/typescript/lib/tsc.js:72951
                throw e;
                ^

TypeError: Cannot read property 'length' of undefined
    at checkModuleDeclaration (/Users/vvakame/.nodebrew/node/v11.10.1/lib/node_modules/typescript/lib/tsc.js:47547:44)
    at checkSourceElementWorker (/Users/vvakame/.nodebrew/node/v11.10.1/lib/node_modules/typescript/lib/tsc.js:48062:28)
    at checkSourceElement (/Users/vvakame/.nodebrew/node/v11.10.1/lib/node_modules/typescript/lib/tsc.js:47911:17)
    at Object.forEach (/Users/vvakame/.nodebrew/node/v11.10.1/lib/node_modules/typescript/lib/tsc.js:217:30)
    at checkBlock (/Users/vvakame/.nodebrew/node/v11.10.1/lib/node_modules/typescript/lib/tsc.js:46001:20)
    at checkSourceElementWorker (/Users/vvakame/.nodebrew/node/v11.10.1/lib/node_modules/typescript/lib/tsc.js:48017:28)
    at checkSourceElement (/Users/vvakame/.nodebrew/node/v11.10.1/lib/node_modules/typescript/lib/tsc.js:47911:17)
    at checkModuleDeclaration (/Users/vvakame/.nodebrew/node/v11.10.1/lib/node_modules/typescript/lib/tsc.js:47594:17)
    at checkSourceElementWorker (/Users/vvakame/.nodebrew/node/v11.10.1/lib/node_modules/typescript/lib/tsc.js:48062:28)
    at checkSourceElement (/Users/vvakame/.nodebrew/node/v11.10.1/lib/node_modules/typescript/lib/tsc.js:47911:17)
```

**Playground Link:** 
none.

**Related Issues:** 
none.

**Comment by proteria** [comment]
I can still reproduce this error with a top level `namespace globalThis`. This fixed for me:

```diff
diff --git a/node_modules/typescript/lib/tsc.js b/node_modules/typescript/lib/tsc.js
index 0218944..457df9d 100644
--- a/node_modules/typescript/lib/tsc.js
+++ b/node_modules/typescript/lib/tsc.js
@@ -48282,6 +48282,7 @@ var ts;
                 var symbol = getSymbolOfNode(node);
                 if (symbol.flags & 512
                     && !inAmbientContext
+                    && symbol.declarations
                     && symbol.declarations.length > 1
                     && isInstantiatedModule(node, !!compilerOptions.preserveConstEnums || !!compilerOptions.isolatedModules)) {
                     var firstNonAmbientClassOrFunc = getFirstNonAmbientClassOrFunctionDeclaration(symbol);

```
