### ISSUE TITLE
Maximum call stack size exceeded on Object.getPathFromPathComponents

### ISSUE THREAD

**Issue by pocesar** [microsoft/TypeScript#30583]
**TypeScript Version:**  3.4.0-dev.20190323

**Search Terms:** maximum call stack size exceeded getPathFromPathComponents

I'm trying to edit a definitelytyped typings for binary-parser, since the error is cryptic, I'm not sure if it's caused by the sheer amount of files in the cloned repo or it's my code

**Code**

```
[2019-03-25 17:51:52.724] [exthost] [error] Error: TypeScript Server Error (3.4.0-dev.20190323)
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Array.join (native)
    at Object.getPathFromPathComponents (tsserver.js:15481:47)
    at Object.resolvePath (tsserver.js:15588:29)
    at Object.normalizePath (tsserver.js:15347:19)
    at Object.toPath (tsserver.js:8425:18)
    at toPath (tsserver.js:88497:23)
    at Object.getSourceFile (tsserver.js:89004:40)
    at resolveExternalModule (tsserver.js:33240:78)
    at resolveExternalModuleNameWorker (tsserver.js:33220:19)
    at resolveExternalModuleName (tsserver.js:33215:20)
    at getAlternativeContainingModules (tsserver.js:33523:42)
    at getContainersOfSymbol (tsserver.js:33561:66)
    at getSymbolChain (tsserver.js:34853:41)
    at lookupSymbolChain (tsserver.js:34839:52)
    at symbolToTypeNode (tsserver.js:34986:29)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
	at Function.create (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:174478)
	at v.dispatchResponse (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:179784)
	at v.dispatchMessage (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:178536)
	at constructor._reader.onData.e (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:177892)
	at u.fire (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at t.Reader.onLengthData (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:183752)
	at Socket.t.Reader.constructor.e.on.e (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:183400)
	at Socket.emit (events.js:182:13)
	at Socket.EventEmitter.emit (domain.js:442:20)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

**Expected behavior:**

Works

**Actual behavior:**

VSCode logs the error in "Log (Extension host)" 

**Playground Link:** 

**Related Issues:**

**Comment by pocesar** [comment]
Same error, different stack trace:

```
[2019-03-25 23:07:37.902] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2019-03-25 23:07:37.902] [exthost] [error] Error: TypeScript Server Error (3.4.0-dev.20190323)
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Object.mapDefined (tsserver.js:668:30)
    at getContainersOfSymbol (tsserver.js:33560:47)
    at getSymbolChain (tsserver.js:34853:41)
    at lookupSymbolChain (tsserver.js:34839:52)
    at symbolToTypeNode (tsserver.js:34986:29)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
    at lookupTypeParameterNodes (tsserver.js:34927:46)
    at createAccessFromSymbolChain (tsserver.js:35032:101)
    at createAccessFromSymbolChain (tsserver.js:35056:35)
    at symbolToTypeNode (tsserver.js:35018:34)
    at typeToTypeNodeHelper (tsserver.js:34269:28)
    at typeParameterToDeclaration (tsserver.js:34778:52)
    at tsserver.js:34911:152
    at Object.map (tsserver.js:509:29)
    at typeParametersToTypeParameterDeclarations (tsserver.js:34911:64)
	at Function.create (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:174478)
	at v.dispatchResponse (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:179784)
	at v.dispatchMessage (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:178536)
	at constructor._reader.onData.e (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:177892)
	at u.fire (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at t.Reader.onLengthData (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:183752)
	at Socket.t.Reader.constructor.e.on.e (f:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:183400)
	at Socket.emit (events.js:182:13)
	at Socket.EventEmitter.emit (domain.js:442:20)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

**Comment by andrewbranch** [comment]
Perf measuring the language service caught this on the package `amap-js-api`, and I repro’d successfully in VS Code. Hovering `.Data` (requesting quick info) here causes the error: 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3159ea0560409b5393bd57884c7c9a3dc1a9d6ae/types/amap-js-api/amap-js-api-tests.ts#L1618
