### ISSUE TITLE
Regression in TypeScript version 3.4.1 with redux saga 0.16.2

### ISSUE THREAD

**Issue by clentfort** [Microsoft/TypeScript#30747]
**TypeScript Version:**  3.4.1

**Search Terms:**

Debug Failure, Regression, Generator, Saga, Redux Saga

**Code**

```ts
interface CallEffectFactory<R> {
  (
    a1: any,
    a2: any
   ): any;
}

export const call: CallEffectFactory<any>;  

export function* fn() {
  yield call(1, ...spread);
}
```

This typing originates from [redux-saga 0.16.2](https://github.com/redux-saga/redux-saga/blob/v0.16.2/effects.d.ts#L160-L203)

**Expected behavior:**

TypeScript 3.4.1 to not have regressed.

**Actual behavior:**

TypeScript crashes

```
/home/work/code/node_modules/typescript/lib/tsc.js:72970
                throw e;
                ^
Error: Debug Failure. False expression.
    at Object.first (/home/work/code/node_modules/typescript/lib/tsc.js:951:15)
    at getArgumentArityError (/home/work/code/node_modules/typescript/lib/tsc.js:41933:32)
    at resolveCall (/home/work/code/node_modules/typescript/lib/tsc.js:42020:41)
    at resolveCallExpression (/home/work/code/node_modules/typescript/lib/tsc.js:42252:20)
    at resolveSignature (/home/work/code/node_modules/typescript/lib/tsc.js:42491:28)
    at getResolvedSignature (/home/work/code/node_modules/typescript/lib/tsc.js:42511:26)
    at checkCallExpression (/home/work/code/node_modules/typescript/lib/tsc.js:42582:29)
    at checkExpressionWorker (/home/work/code/node_modules/typescript/lib/tsc.js:44390:28)
    at checkExpression (/home/work/code/node_modules/typescript/lib/tsc.js:44317:38)
    at getYieldedTypeOfYieldExpression (/home/work/code/node_modules/typescript/lib/tsc.js:43094:52)
error Command failed with exit code 1.
```

**Playground Link:** 

http://www.typescriptlang.org/play/#src=interface%20CallEffectFactory%3CR%3E%20%7B%0D%0A%20%20(%0D%0A%20%20%20%20a1%3A%20any%2C%0D%0A%20%20%20%20a2%3A%20any%2C%0D%0A%20%20%20%20...rest%3A%20any%5B%5D%0D%0A%20%20%20)%3A%20any%3B%0D%0A%7D%0D%0A%0D%0Aexport%20const%20call%3A%20CallEffectFactory%3Cany%3E%3B%20%20%0D%0A%0D%0Aexport%20function*%20fn()%20%7B%0D%0A%20%20yield%20call(1%2C%20...spread)%3B%0D%0A%7D

**Related Issues:**

**Comment by JKillian** [comment]
I believe this duplicates https://github.com/Microsoft/TypeScript/issues/30647
