### ISSUE TITLE
[TSServer] getDocumentHighlights — TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#30896]
**TypeScript Version:**  3.4.3

**Error**
We're seeing the following error stack fairly often in VS Code with TS 3.4.3:

```
TypeError: Cannot read property 'length' of undefined
	    at Object.find (tsserver.js:375:35)
	    at getReferencedSymbolsForModuleIfDeclaredBySourceFile (tsserver.js:101861:78)
	    at Object.getReferencedSymbolsForNode (tsserver.js:101839:40)
	    at Object.getReferenceEntriesForNode (tsserver.js:101581:58)
	    at getSemanticDocumentHighlights (tsserver.js:100395:57)
	    at Object.getDocumentHighlights (tsserver.js:100383:20)
	    at Object.getDocumentHighlights (tsserver.js:121028:42)
	    at IOSession.Session.getDocumentHighlights (tsserver.js:129609:71)
	    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:129016:61)
	    at tsserver.js:130454:88
	    at IOSession.Session.executeWithRequestId (tsserver.js:130445:28)
	    at IOSession.Session.executeCommand (tsserver.js:130454:33)
	    at IOSession.Session.onMessage (tsserver.js:130476:35)
	    at Interface.<anonymous> (tsserver.js:131773:27)
	    at Interface.emit (events.js:182:13)
	    at Interface._onLine (readline.js:290:10)
	    at Interface._normalWrite (readline.js:433:12)
	    at Socket.ondata (readline.js:149:10)
	    at Socket.emit (events.js:182:13)
	    at addChunk (_stream_readable.js:279:12)
	    at readableAddChunk (_stream_readable.js:264:11)
	    at Socket.Readable.push (_stream_readable.js:219:10)
	    at Pipe.onread (net.js:636:20),
```

Sorry, no repo steps since this just came from telemetry

**Comment by mjbvz** [comment]
Still a top hitter in `3.7.0-dev.20191015`

```
TypeError: Cannot read property 'length' of undefined
	    at Object.find (tsserver.js:270:35)
	    at getReferencedSymbolsForModuleIfDeclaredBySourceFile (tsserver.js:109689:78)
	    at Object.getReferencedSymbolsForNode (tsserver.js:109667:40)
	    at Object.getReferenceEntriesForNode (tsserver.js:109401:58)
	    at getSemanticDocumentHighlights (tsserver.js:108091:57)
	    at Object.getDocumentHighlights (tsserver.js:108079:20)
	    at Proxy.getDocumentHighlights (tsserver.js:130690:42)
	    at IOSession.Session.getDocumentHighlights (tsserver.js:139794:71)
	    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:139216:61)
	    at tsserver.js:140644:88
	    at IOSession.Session.executeWithRequestId (tsserver.js:140635:28)
	    at IOSession.Session.executeCommand (tsserver.js:140644:33)
	    at IOSession.Session.onMessage (tsserver.js:140667:35)
	    at Interface.<anonymous> (tsserver.js:141982:27)
	    at Interface.emit (events.js:182:13)
	    at Interface._onLine (readline.js:290:10)
	    at Interface._normalWrite (readline.js:433:12)
	    at Socket.ondata (readline.js:149:10)
	    at Socket.emit (events.js:182:13)
	    at addChunk (_stream_readable.js:283:12)
	    at readableAddChunk (_stream_readable.js:264:11)
	    at Socket.Readable.push (_stream_readable.js:219:10)
	    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by mjbvz** [comment]
Tracked by #32858
