### ISSUE TITLE
Compile crashes on invalid structure definition.

### ISSUE THREAD

**Issue by NStal** [Microsoft/TypeScript#30997]
**TypeScript Version:**  3.4.3 ~ 3.5.0-dev.20190417
**Code**

```ts
/// <reference path="./type.d.ts"/>
export class Environment {
    //// definitions
    entities: {
        [name: Type.Present.EntityName]
    } = {}
}
```
```ts
// type.d.ts
declare namespace Type {
    namespace Present {
        type EntityName = string
    }
}
```
**Expected behavior:** Report syntax error

**Actual behavior:** Crash
```
TypeError: Cannot read property 'kind' of undefined
    at getTypeFromTypeNode (/home/wuminghan/temp/abc/node_modules/typescript/lib/tsc.js:34108:26)
    at checkGrammarIndexSignatureParameters (/home/wuminghan/temp/abc/node_modules/typescript/lib/tsc.js:50009:246)
    at checkGrammarIndexSignature (/home/wuminghan/temp/abc/node_modules/typescript/lib/tsc.js:50022:64)
    at checkSignatureDeclaration (/home/wuminghan/temp/abc/node_modules/typescript/lib/tsc.js:44716:17)
    at checkSourceElementWorker (/home/wuminghan/temp/abc/node_modules/typescript/lib/tsc.js:48103:28)
    at checkSourceElement (/home/wuminghan/temp/abc/node_modules/typescript/lib/tsc.js:48069:17)
    at Object.forEach (/home/wuminghan/temp/abc/node_modules/typescript/lib/tsc.js:217:30)
    at checkTypeLiteral (/home/wuminghan/temp/abc/node_modules/typescript/lib/tsc.js:45099:16)
    at checkSourceElementWorker (/home/wuminghan/temp/abc/node_modules/typescript/lib/tsc.js:48119:28)
    at checkSourceElement (/home/wuminghan/temp/abc/node_modules/typescript/lib/tsc.js:48069:17)
```

**Comment by andrewbranch** [comment]
Minimal repro:

```ts
type Key = string

type X = {
  [key: Key]
}
```
