### ISSUE TITLE
Cannot install TypeScript: "ERR_INVALID_OPT_VALUE" (re readableHighWaterMark)

### ISSUE THREAD

**Issue by kylegoetz** [Microsoft/TypeScript#31004]
**TypeScript Version:**  typescript@next

**Search Terms:** readableHighWaterMark, ERR_INVALID_OPT_VALUE

```
mkdir foobar
cd foobar
npm init
npm i typescript@next
```

**Expected behavior:** Typescript module installs.

**Actual behavior:** Typescript module fails to install with the following error:
```
npm ERR! code ERR_INVALID_OPT_VALUE
npm ERR! The value "false" is invalid for option "readableHighWaterMark"
npm ERR! A complete log [snip]
```

**Playground Link:** n/a

**Related Issues:** n/a

**Full log**:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   'typescript',
1 verbose cli   '--registry=https://registry.npmjs.org' ]
2 info using npm@6.7.0
3 info using node@v9.4.0
4 verbose npm-session cec8809c3c3fbaf5
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/typescript 448ms
8 silly pacote tag manifest for typescript@latest fetched in 518ms
9 timing stage:loadCurrentTree Completed in 585ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 12ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule typescript@3.4.3 checking installable status
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 7ms
18 timing stage:loadIdealTree Completed in 22ms
19 silly currentTree tt@1.0.0
19 silly currentTree ├── ansi-font@0.0.2
19 silly currentTree └── test@0.6.0
20 silly idealTree tt@1.0.0
20 silly idealTree ├── ansi-font@0.0.2
20 silly idealTree ├── test@0.6.0
20 silly idealTree └── typescript@3.4.3
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 5ms
23 silly diffTrees action count 1
24 silly diffTrees add typescript@3.4.3
25 silly decomposeActions action count 8
26 silly decomposeActions fetch typescript@3.4.3
27 silly decomposeActions extract typescript@3.4.3
28 silly decomposeActions preinstall typescript@3.4.3
29 silly decomposeActions build typescript@3.4.3
30 silly decomposeActions install typescript@3.4.3
31 silly decomposeActions postinstall typescript@3.4.3
32 silly decomposeActions finalize typescript@3.4.3
33 silly decomposeActions refresh-package-json typescript@3.4.3
34 silly install executeActions
35 silly doSerial global-install 8
36 verbose correctMkdir /Users/kylegoetz/.npm/_locks correctMkdir not in flight; initializing
37 verbose lock using /Users/kylegoetz/.npm/_locks/staging-7a690c8c1f0a95bf.lock for /Users/kylegoetz/tt/node_modules/.staging
38 silly doParallel extract 1
39 silly extract typescript@3.4.3
40 silly tarball trying typescript@latest by hash: sha512-FFgHdPt4T/duxx6Ndf7hwgMZZjZpB+U0nMNGVCYPq0rEzWKjEDobm4J6yb3CS7naZ0yURFqdw9Gwc7UOh/P9oQ==
41 silly tarball no local data for typescript@latest. Extracting by manifest.
42 timing audit submit Completed in 330ms
43 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 330ms
44 timing audit body Completed in 0ms
45 timing action:extract Completed in 1151ms
46 verbose unlock done using /Users/kylegoetz/.npm/_locks/staging-7a690c8c1f0a95bf.lock for /Users/kylegoetz/tt/node_modules/.staging
47 timing stage:rollbackFailedOptional Completed in 0ms
48 timing stage:runTopLevelLifecycles Completed in 1783ms
49 silly saveTree tt@1.0.0
49 silly saveTree ├─┬ test@0.6.0
49 silly saveTree │ └── ansi-font@0.0.2
49 silly saveTree └── typescript@3.4.3
50 warn tt@1.0.0 No description
51 warn tt@1.0.0 No repository field.
52 verbose stack TypeError: The value "false" is invalid for option "readableHighWaterMark"
52 verbose stack     at getHighWaterMark (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/internal/streams/state.js:15:13)
52 verbose stack     at new ReadableState (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:122:24)
52 verbose stack     at DestroyableTransform.Readable (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:173:25)
52 verbose stack     at DestroyableTransform.Duplex (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_duplex.js:60:12)
52 verbose stack     at DestroyableTransform.Transform (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_transform.js:100:10)
52 verbose stack     at new DestroyableTransform (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/through2/through2.js:6:13)
52 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/through2/through2.js:53:12
52 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/through2/through2.js:46:12
52 verbose stack     at Cache.put (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/cache.js:176:21)
52 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/index.js:352:40)
52 verbose stack     at <anonymous>
52 verbose stack     at process._tickCallback (internal/process/next_tick.js:160:7)
53 verbose cwd /Users/kylegoetz/tt
54 verbose Darwin 18.2.0
55 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "typescript" "--registry=https://registry.npmjs.org"
56 verbose node v9.4.0
57 verbose npm  v6.7.0
58 error code ERR_INVALID_OPT_VALUE
59 error The value "false" is invalid for option "readableHighWaterMark"
60 verbose exit [ 1, true ]
 kylegoetz@Kyles-MBP  ~/tt  npm i typescript@3.0.0                                                                                                                                                                                         ✔  515  17:23:46
npm ERR! code ETARGET
npm ERR! notarget No matching version found for typescript@3.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kylegoetz/.npm/_logs/2019-04-17T22_24_29_308Z-debug.log
 kylegoetz@Kyles-MBP  ~/tt  npm i typescript@next                                                                                                                                                                                        1 ↵  516  17:24:29
npm WARN tt@1.0.0 No description
npm WARN tt@1.0.0 No repository field.

npm ERR! code ERR_INVALID_OPT_VALUE
npm ERR! The value "false" is invalid for option "readableHighWaterMark"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kylegoetz/.npm/_logs/2019-04-17T22_25_31_442Z-debug.log
```

**Comment by JavedKhanUI** [comment]
Localhost Server 
 
1) edit .htaccess files

Disabled

#RewriteCond %{HTTPS} off
#RewriteCond %{HTTP:X-Forwarded-Proto} !https
#RewriteRule ^(.*)$  https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

Live Server  - Enable and install valid cetificate

**Comment by chesterm8** [comment]
In case anyone else finds this, it appears to be an NPM bug: https://npm.community/t/npm-install-g-typescript-fails-with-npm-err-the-value-false-is-invalid-for-option-readablehighwatermark/8668
