### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by shawnlewis** [microsoft/TypeScript#31082]
**TypeScript Version:**  I tested 3.4.1 and some other newer versions through 3.5.0-dev.20190423, the problem occurs on all the versions I tested.

The problem does not exist on 3.3.3

**Search Terms:**
RangeError: Maximum call stack size exceeded

**Code**

I don't have a simple case to reproduce this yet.

**Actual behavior:**
```
$ /Users/shawn/go/src/github.com/wandb/core/frontends/app/node_modules/.bin/tsc
/Users/shawn/go/src/github.com/wandb/core/frontends/app/node_modules/typescript/lib/tsc.js:72973
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at Object.createSymbolTable (/Users/shawn/go/src/github.com/wandb/core/frontends/app/node_modules/typescript/lib/tsc.js:6121:31)
    at resolveMappedTypeMembers (/Users/shawn/go/src/github.com/wandb/core/frontends/app/node_modules/typescript/lib/tsc.js:31199:30)
    at resolveStructuredTypeMembers (/Users/shawn/go/src/github.com/wandb/core/frontends/app/node_modules/typescript/lib/tsc.js:31326:25)
    at getPropertiesOfObjectType (/Users/shawn/go/src/github.com/wandb/core/frontends/app/node_modules/typescript/lib/tsc.js:31340:24)
    at propertiesIdenticalTo (/Users/shawn/go/src/github.com/wandb/core/frontends/app/node_modules/typescript/lib/tsc.js:36138:40)
    at propertiesRelatedTo (/Users/shawn/go/src/github.com/wandb/core/frontends/app/node_modules/typescript/lib/tsc.js:36001:28)
    at structuredTypeRelatedTo (/Users/shawn/go/src/github.com/wandb/core/frontends/app/node_modules/typescript/lib/tsc.js:35944:34)
    at recursiveTypeRelatedTo (/Users/shawn/go/src/github.com/wandb/core/frontends/app/node_modules/typescript/lib/tsc.js:35723:53)
    at isIdenticalTo (/Users/shawn/go/src/github.com/wandb/core/frontends/app/node_modules/typescript/lib/tsc.js:35433:28)
    at isRelatedTo (/Users/shawn/go/src/github.com/wandb/core/frontends/app/node_modules/typescript/lib/tsc.js:35335:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What are my options for getting more information about this? I haven't been able to get tsc to tell me what part of our codebase it's choking on.

I could potentially try to bisect our codebase somehow? Or are there compiler options that will produce a useful trace?

**Comment by RyanCavanaugh** [comment]
#18511 has some debugging tips

**Comment by shawnlewis** [comment]
OK, I attached a debugger to tsc and found that it was choking on our file `views.test.ts` (at the bottom below). I found that if I add "as any" to a specific line, the issue goes away. There's a comment inline below that shows what I changed.

I've tried to include the relevant dependent code here. Sorry there's so much. I haven't tried to reduce this down to a simple reproducible case, so it's understandable if you just want to close this issue.

We're using redux version `4.0.1` and typesafe-actions `2.0.4`. I found that if I update typesafe-actions to latest (`4.1.2`) the issue still exists.

actions/viewSimple.ts
```
// Raw redux actions for views.
import {createAction} from 'typesafe-actions';
import {ViewApi} from '../graphql/viewApi';
import {JSONObject} from '../types/json';
import * as Views from '../util/view';

// Replace all the views for a given viewType
export const initAll = createAction('view/INIT_ALL', resolve => {
  return (
    viewApi: ViewApi,
    viewer:
      | {
          id: string;
          username: string;
          photoUrl: string;
          admin: boolean;
        }
      | undefined,
    requestedView: Views.View | undefined,
    viewerView: Views.View,
    defaultSpec: any,
    views: Views.View[]
  ) =>
    resolve({
      viewApi,
      viewer,
      requestedView,
      viewerView,
      defaultSpec,
      views,
    });
});

export const loadView = createAction('view/LOAD_VIEW', resolve => {
  return (viewId: string) => resolve({viewId});
});

export const updateCurrentView = createAction(
  'view/UPDATE_CURRENT_VIEW',
  resolve => {
    return (spec: JSONObject) => resolve({spec});
  }
);

export const serverViewUpsert = createAction(
  'view/SERVER_UPSERT_VIEW',
  resolve => {
    return (name: string, spec: JSONObject) => resolve({name, spec});
  }
);

export const undo = createAction('view/UNDO');

export const redo = createAction('view/REDO');
```

reducers/views2
```
import * as _ from 'lodash';
import {ActionType, getType, StateType} from 'typesafe-actions';
import * as Actions from '../actions/viewSimple';
import {ViewApi} from '../graphql/viewApi';
import {JSONObject} from '../types/json';
import * as Views from '../util/view';

export type ViewAction = ActionType<typeof Actions>;

const ID = () => {
  // Math.random should be unique because of its seeding algorithm.
  // Convert it to base 36 (numbers + letters), and grab the first 9 characters
  // after the decimal.
  return Math.random()
    .toString(36)
    .substr(2, 9);
};

interface ViewReducerState {
  // Used to update the server
  viewApi?: ViewApi;

  // Todo: we should store the viewerId elsewhere in redux.
  viewer?: {
    id: string;
    photoUrl: string;
    username: string;
    admin: boolean;
  };

  // A mirror of the server view state, we maintain this cached copy
  // in parallel with sending updates to the server, as users make changes.
  views: {[id: string]: Views.View};

  // What we clear to when the user clears
  defaultSpec?: any;

  // The original view loaded by the user. Updates are stored in
  // currentViewHistory.
  // This is guaranteed to be a valid view after initAll is called.
  //   TODO: it would be nice to enforce this with the type system.
  loadedView?: Views.View;

  // View spec change history, for supporting undo/redo. This is only tracked
  // for the viewer's view, since the user can't modify any other views
  currentViewIndex: number;
  currentViewHistory: JSONObject[]; // spec history
}

export default function views2(
  state: ViewReducerState = {
    views: {},
    currentViewIndex: 0,
    currentViewHistory: [],
  },
  action: ViewAction
): ViewReducerState {
  switch (action.type) {
    case getType(Actions.initAll): {
      const payload = action.payload;
      const initialView = payload.requestedView || payload.viewerView;
      Views.setUrl(initialView);
      return {
        ...state,
        viewApi: payload.viewApi,
        viewer: payload.viewer,
        views: _.fromPairs(payload.views.map(v => [v.id, v])),
        loadedView: initialView,
        defaultSpec: payload.defaultSpec,
        currentViewIndex: 0,
        currentViewHistory: [payload.viewerView.spec],
      };
    }
    case getType(Actions.loadView): {
      const payload = action.payload;
      const view = state.views[payload.viewId];
      if (view == null) {
        console.warn('Invalid view state');
        return state;
      }
      Views.setUrl(view);
      return {
        ...state,
        loadedView: view,
      };
    }
    case getType(Actions.updateCurrentView): {
      const payload = action.payload;
      const currentView = state.loadedView;
      if (currentView == null) {
        console.warn('Invalid view state');
        return state;
      }
      // Truncate the history at our currentIndex and append the spec
      const result = {
        ...state,
        currentViewIndex: state.currentViewIndex + 1,
        currentViewHistory: state.currentViewHistory
          .slice(0, state.currentViewIndex + 1)
          .concat([payload.spec]),
      };
      return result;
    }
    case getType(Actions.serverViewUpsert): {
      if (!state.viewer) {
        return state;
      }
      const payload = action.payload;
      const foundView = _.values(state.views).find(
        v => v.name === payload.name && v.user.id === state.viewer!.id
      );
      const saveView = {
        ...state.loadedView,
        id: ID(),
        description: '',
        name: payload.name,
        saving: false,
        spec: payload.spec,
        user: state.viewer,
        updatedAt: new Date().toString(),
      };
      if (foundView) {
        saveView.id = foundView.id;
      }
      return {
        ...state,
        views: {
          ...state.views,
          [saveView.id]: saveView,
        },
      };
    }
    case getType(Actions.undo): {
      if (state.currentViewIndex === 0) {
        return state;
      }
      return {
        ...state,
        currentViewIndex: state.currentViewIndex - 1,
      };
    }
    case getType(Actions.redo): {
      if (state.currentViewIndex === state.currentViewHistory.length - 1) {
        return state;
      }
      return {
        ...state,
        currentViewIndex: state.currentViewIndex + 1,
      };
    }

    default:
      // Initialization
      return state;
  }
}

export type ViewState = StateType<typeof views2>;

export function getCurrentView(viewState: ViewState): Views.View | undefined {
  return viewState.loadedView
    ? {
        ...viewState.loadedView,
        spec:
          viewState.viewer &&
          viewState.loadedView.name === 'workspace' &&
          viewState.loadedView.user.username === viewState.viewer.username
            ? viewState.currentViewHistory[viewState.currentViewIndex]
            : viewState.loadedView.spec,
      }
    : undefined;
}
```

redux.ts
```
import {ThunkAction} from 'redux-thunk';
import * as AppReducer from '../reducers/app';
import * as ReportReducer from '../reducers/report';
import * as ViewReducer from '../reducers/views2';

export interface RootState {
  report: ReportReducer.ReportState;
  views2: ViewReducer.ViewState;
  app: AppReducer.AppState;
}

export type RootAction =
  | ReportReducer.ReportAction
  | ViewReducer.ViewAction
  | AppReducer.AppAction;

export type ThunkResult<R> = ThunkAction<R, RootState, undefined, RootAction>;
```

views.test.ts
```
import {applyMiddleware, combineReducers, createStore} from 'redux';
import thunk, {ThunkMiddleware} from 'redux-thunk';
import {RootAction, RootState} from '../types/redux';
import reducer, {ViewState} from './views2';

const getStore = (initial?: Partial<ViewState>) => {
  return createStore(
    combineReducers({views2: reducer}),
    {views2: initial} as any, /* TypeScript Issue#31082 note: adding "as any" here fixes the issue
    applyMiddleware(thunk as ThunkMiddleware<RootState, RootAction>)
  );
};
...
```
