### ISSUE TITLE
[TSC fails] RangeError: Maximum call stack size exceeded [with repro repo]

### ISSUE THREAD

**Issue by nodkz** [microsoft/TypeScript#31230]
**TypeScript Version:**  Version 3.5.0-dev.20190503

**Search Terms:**

tsc, RangeError, Maximum call stack size exceeded

**Code**

```ts
import { ObjectTypeComposer } from 'graphql-compose';
declare const User: ObjectTypeComposer<any, any>;
User.addResolver({ type: User });
```

Dramatically simplified `graphql-compose.d.ts`:

```ts

export type ObjMapReadOnly<T> = Readonly<{ [key: string]: Readonly<T> }>;
export type Thunk<T> = (() => T) | T;

export type ComposeOutputTypeDefinition = Readonly<ObjectTypeComposer<any, any> | EnumTypeComposer>;

export class EnumTypeComposer {
  public setFields(fields: { [name: string]: { [key: string]: any } }): this;
}

export class ObjectTypeComposer<TSource, TContext> {
  public setFields(fields: ObjMapReadOnly<Resolver>): this;

  public addResolver<TResolverSource>(opts: { type?: Thunk<ComposeOutputTypeDefinition> }): this;
}

export class Resolver {
  public wrapArgs<NewContext>(
    cb: () => {
      [argName: string]: Thunk<Readonly<EnumTypeComposer>>;
    }
  ): void;

  public wrapType(cb: () => ComposeOutputTypeDefinition): void;
}
```

**Expected behavior:**

Do not fall with `Maximum call stack size exceeded` error.

**Actual behavior:**

```txt
> ts-max-call-stack@1.0.0 tsc /Users/nodkz/www/_sandbox/nodkz-tsc-problem
> tsc

/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:72973
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at __generator (/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:30:13)
    at getUnmatchedProperties (/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:37203:20)
    at getUnmatchedProperty (/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:37237:20)
    at typesDefinitelyUnrelated (/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:37245:19)
    at inferFromObjectTypes (/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:37544:22)
    at inferFromTypes (/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:37456:29)
    at inferFromContravariantTypes (/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:37475:21)
    at applyToParameterTypes (/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:37047:17)
    at inferFromSignature (/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:37603:21)
    at inferFromSignatures (/Users/nodkz/www/_sandbox/nodkz-tsc-problem/node_modules/typescript/lib/tsc.js:37595:21)
```

**Playground Link:** 

Simplified repro repo: https://github.com/nodkz/tsc-problem

```bash
git clone https://github.com/nodkz/tsc-problem ./nodkz-tsc-problem \
  && cd nodkz-tsc-problem \
  && npm install \
  && npm run tsc
```

**Comment by antoniopresto** [comment]
for someone with an error like this, I'm bypassing it wrapping the type with a function
```js
     TC.setField (key, () => ({
       type: () => TheType, // <-- this
     }));

**Comment by antoniopresto** [comment]
The error happens when trying to access the "ofType" property of the Proxy

![Screen Shot 2019-06-13 at 14 57 44](https://user-images.githubusercontent.com/6221799/59456089-f7754700-8deb-11e9-82af-1c3e93c2c596.png)

**Comment by nodkz** [comment]
@orta, please help to fix this issue. It blocks me from upgrading Gatsby and other small projects.

Thanks.

**Comment by RobinTail** [comment]
I have the same issue on TypeScript v3.6.4

**Comment by IgorSzymanski** [comment]
Same issue on TS 3.7.2.

**Comment by nodkz** [comment]
As a workaround I simplified checks in my lib:

```diff
export type ObjMapReadOnly<T> = Readonly<{ [key: string]: Readonly<T> }>;
- export type Thunk<T> = (() => T) | T;
+ export type Thunk<T> = (() => any) | T;

export type ComposeOutputTypeDefinition = Readonly<ObjectTypeComposer<any, any> | EnumTypeComposer>;

export class EnumTypeComposer {
  public setFields(fields: { [name: string]: { [key: string]: any } }): this;
}

export class ObjectTypeComposer<TSource, TContext> {
  public setFields(fields: ObjMapReadOnly<Resolver>): this;

  public addResolver<TResolverSource>(opts: { type?: Thunk<ComposeOutputTypeDefinition> }): this;
}

export class Resolver {
  public wrapArgs<NewContext>(
    cb: () => {
      [argName: string]: Thunk<Readonly<EnumTypeComposer>>;
    }
  ): void;

  public wrapType(cb: () => ComposeOutputTypeDefinition): void;
}
```

**It's better than ~~nothing~~ "maximum call stack size exceeded"**

![photo_2019-11-25 12 21 30](https://user-images.githubusercontent.com/1946920/69517171-22a8b880-0f7e-11ea-8172-ab7780e35d9b.jpeg)

**Comment by RyanCavanaugh** [comment]
Possible alternative repro #35804
