### ISSUE TITLE
express broken on typescript@next

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#31558]
Found in DT's overnight run.

**Code**

```
Error in express-handlebars
Error: /home/vsts/work/1/s/DefinitelyTyped/types/express-handlebars/express-handlebars-tests.ts:7:26
ERROR: 7:26  expect  TypeScript@next compile error: 
Argument of type 'Function' is not assignable to parameter of type '(path: string, options: object, callback: (e: any, rendered: string) => void) => void'.
  Type 'Function' provides no match for the signature '(path: string, options: object, callback: (e: any, rendered: string) => void): void'.

    at /home/vsts/work/1/s/node_modules/dtslint/bin/index.js:189:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/vsts/work/1/s/node_modules/dtslint/bin/index.js:5:58)


Error in i18n
Error: /home/vsts/work/1/s/DefinitelyTyped/types/i18n/i18n-tests.ts:108:5
ERROR: 108:5  expect  TypeScript@next compile error: 
Property 'configure' does not exist on type 'Express'.

    at /home/vsts/work/1/s/node_modules/dtslint/bin/index.js:189:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/vsts/work/1/s/node_modules/dtslint/bin/index.js:5:58)

Error in passport
Error: /home/vsts/work/1/s/DefinitelyTyped/types/passport/passport-tests.ts:70:5
ERROR: 70:5  expect  TypeScript@next compile error: 
Property 'configure' does not exist on type 'Express'.

    at /home/vsts/work/1/s/node_modules/dtslint/bin/index.js:189:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/vsts/work/1/s/node_modules/dtslint/bin/index.js:5:58)
The following packages had errors: express-handlebars, i18n, opossum, passport
```

i18n and passport have the same error, it looks like. express hasn't changed since 22 Feb so this is almost certainly our change from the last 24 hours.

**Comment by sandersn** [comment]
False alarm: These breaks are from cleanup in express-serve-static-core. 
types-publisher failed to find the transitive dependencies of express-serve-static-core when running tests.
