### ISSUE TITLE
TSServer organizeImports should work on --syntax server

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#32120]
**TypeScript Version:**  3.6.0-dev.20190626

**Search Terms:**
- tsserver
- organizeImports organize Imports

**Repo**
Start a syntax only tsserver and try to run the `organizeImports` against it

I see this reliably when testing in the VS Code repo

**Bug**
```
Error: Debug Failure. False expression.
    at synchronizeHostData (/Users/matb/projects/TypeScript/src/services/services.ts:1167:19)
    at Object.organizeImports (/Users/matb/projects/TypeScript/src/services/services.ts:1835:13)
    at IOSession.Session.organizeImports (/Users/matb/projects/TypeScript/src/server/session.ts:1886:58)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/projects/TypeScript/src/server/session.ts:2424:51)
    at /Users/matb/projects/TypeScript/src/server/session.ts:2480:69
    at IOSession.Session.executeWithRequestId (/Users/matb/projects/TypeScript/src/server/session.ts:2470:24)
    at IOSession.Session.executeCommand (/Users/matb/projects/TypeScript/src/server/session.ts:2480:29)
    at IOSession.Session.onMessage (/Users/matb/projects/TypeScript/src/server/session.ts:2504:23)
    at Interface.<anonymous> (/Users/matb/projects/TypeScript/src/tsserver/server.ts:565:22)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17): Error: <syntax> TypeScript Server Error (3.6.0)
```

/cc @amcasey

**Comment by amcasey** [comment]
Wait, why would that work?  Surely that requires semantic information.

**Comment by DanielRosenwasser** [comment]
I mean, it **could** be, but right now isn't it an alphabetical ordering that's just syntactic?

**Comment by amcasey** [comment]
@DanielRosenwasser it also removes unused imports.  I don't know how you could determine which are used syntactically.

**Comment by mjbvz** [comment]
Yes good point, forgot about removing unused. That means it is closer to a quickfix

**Comment by amcasey** [comment]
FWIW, these are the commands VS sends to the syntax server
```csharp
                    case CommandNames.Indentation:
                    case CommandNames.BraceCompletion:
                    case CommandNames.GetSpanOfEnclosingComment:
                    case CommandNames.DocCommentTemplate:
                    case CommandNames.FormatonkeyFull:
                    case CommandNames.FormatRangeFull:
                    case CommandNames.NameOrDottedNameSpan: // Blocks UI in script block quick info
                    case CommandNames.FormatFull:
                    case CommandNames.BraceFull:
```
