### ISSUE TITLE
tsc crashes with TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by hazolsky** [microsoft/TypeScript#32358]
**TypeScript Version:** 3.6.0-dev.20190711 (also checked on stable 3.5.2)

**Search Terms:**
* TypeError: Cannot read property 'text' of undefined at emitPropertyAccessExpression

**Code**

**test.ts:**
```ts
const fn = (param: string) => undefined;

const foo = {bar: 'a'};
fn(({[foo.bar]: c}) => undefined);
```

```
$ tsc test.ts
```

**Expected behavior:**
`tsc` exits with error `TS2345: Argument of type '({[foo.bar]: c}: any) => void' is not assignable to parameter of type 'string'.` on line 4.

**Actual behavior:**
`tsc` crashes with error:
```
node_modules/typescript/lib/tsc.js:74862
                throw e;
                ^

TypeError: Cannot read property 'text' of undefined
    at emitPropertyAccessExpression (node_modules/typescript/lib/tsc.js:71027:77)
    at pipelineEmitWithHint (node_modules/typescript/lib/tsc.js:70478:32)
    at emitExpression (node_modules/typescript/lib/tsc.js:70140:13)
    at emitComputedPropertyName (node_modules/typescript/lib/tsc.js:70684:13)
    at pipelineEmitWithHint (node_modules/typescript/lib/tsc.js:70207:32)
    at emit (node_modules/typescript/lib/tsc.js:70127:13)
    at emitBindingElement (node_modules/typescript/lib/tsc.js:70999:17)
    at pipelineEmitWithHint (node_modules/typescript/lib/tsc.js:70297:32)
    at emit (node_modules/typescript/lib/tsc.js:70127:13)
    at emitNodeList (node_modules/typescript/lib/tsc.js:72467:21)
```

**Playground Link:** 

http://www.typescriptlang.org/play/#code/MYewdgzgLgBAZmGBeGAKADgQwE6YLYBcM02AlmAOYCUyAfDAK5gAmApnOa8wNwBQvoSLDggQyGAG8ARjiIByTHIC+fBKlQSA2iJAA6GdgC6RYEppJ6TNhzBcqfIA

**Related Issues:** 
Not found.

Original issue: https://github.com/palantir/tslint/issues/4791

**Comment by sandersn** [comment]
Fails from 2.5 onward, which is the earliest version I tested.

**Comment by butchler** [comment]
I'm also getting this error while trying to make TypeScript process `.js` files in a project, using TypeScript 3.4.5

I'm not sure if it helps, but I messed around with playground example a little bit and found some other cases where this crashes and doesn't crash:

Crashes:

```
const foo = {bar: 'a'};
const x: string = ({[foo.bar]: c}) => undefined;
```

Doesn't crash:

```
const foo = {bar: 'a'};
const x: Function = ({[foo.bar]: c}) => undefined;
const y: unknown = ({[foo.bar]: c}) => undefined;
const z = ({[foo.bar]: c}) => undefined;
```

Replacing `const foo = {bar: 'a'}` with `enum foo { bar = 'a' }` also has the same behavior

**Comment by silicakes** [comment]
I was able to reproduce it again on v3.7.2 with the following example:

### Link to Playground
http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=33&pc=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocpAD0ljiQDsBXPAMQEkBRAGQBEAynADe5AJBsA8pLgBeApggR8AGnEAhAIII5BAEYoo+cgF9KwRjCRRM6JHACyATw6XrttEgA8AFQB8IuIA9EEMAG5M8GgojHB69ihwAM4wUBYA5ipwMXAQegBWSBgMMGgAdMGhHHAA1khg8MDwKElwAk6WABZIMMBoXBGWcBa5UAAm1nAwEHBoEIyKUHgA7k2dcEToMPitSIPwADbAKUyTc4z7wPPinTFjB0gCzHogTQBccAAUe5EfyFtldpdHp9AaRXx+ACUcgCYQgwDGFDMVFo0HgMCcYHsAAUcGBWvJ-mN5gcnF5nK4rDY7F4MViIJg4JxeII-H4KOQ0AcWq0nnoAMK4SCMSIMahWRhjVr-DBlQXgebgmJOAKiMRESXWT7QtXqnrMKCxLxjYBhOBBPziMzImh0eATWzMA5RblJVoOFAWeXC0U0CVSxDEGByoWKyxeXEQfGq8RJZ6vGAACTuDyguhaHTQX11AG1mfwBGUpJIALofRQQNRiMR57gFspaBBluKGKsmaGyVVwEwcvWaqDawLV84pERwW6Sh58hPd3QwTrHMpgPFJCjVogwA1GvnesPweb8o5oGqyYQT+6PeNNT7zxdxl5NZOT6yQkzmy1ia3kIA

Results with 
```
TypeError: Cannot read property 'text' of undefined
    at Kn (tsWorker.js:7)
    at tsWorker.js:7
    at se (tsWorker.js:7)
    at Rn (tsWorker.js:7)
    at On (tsWorker.js:7)
    at se (tsWorker.js:7)
    at Rn (tsWorker.js:7)
    at Mn (tsWorker.js:7)
    at tsWorker.js:7
    at se (tsWorker.js:7)
```

### index.tsx
```
import React from 'react';

export enum FIELDS {
	FOO = 'foo',
	BAR = 'bar'
}

interface MyInterface<T> {
	// event can be a string, an object etc.
	// I kept it as SyntheticEvent in order to conform with react's event listener convention
	handleSubmit: (event: React.SyntheticEvent<T>) => void;
}

export type Props = Readonly<MyInterface<typeof FIELDS>>;

class SubComponent extends React.Component<any> {
	render() {
		return <div />
	}
}

export default class MainComponent extends React.Component<Props> {
	submitHandler = async ({
		[FIELDS.FOO]: foo,
		[FIELDS.BAR]: bar,
	}) => { };

	render() {
		const { handleSubmit } = this.props;
		return <SubComponent onClick={handleSubmit(this.submitHandler)} />
	}
}

```

### tsconfig.json

```
{
  "compilerOptions": {
    "lib": [
      "es6",
    ],
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
  },
  "files": [
    "index.tsx"
  ]
}
```

### package.json

```
{
  "name": "ts-text-error",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@types/react": "^16.9.13",
    "typescript": "^3.7.2"
  },
  "dependencies": {
    "react": "^16.12.0"
  }
}

```

### Full error output:

```
$ yarn tsc
yarn run v1.16.0
$ /Users/michael.katz/dev/ts-text-error/node_modules/.bin/tsc
/Users/michael.katz/dev/ts-text-error/node_modules/typescript/lib/tsc.js:78566
                throw e;
                ^

TypeError: Cannot read property 'text' of undefined
    at emitTokenWithComment (/Users/michael.katz/dev/ts-text-error/node_modules/typescript/lib/tsc.js:75010:55)
    at emitPropertyAccessExpression (/Users/michael.katz/dev/ts-text-error/node_modules/typescript/lib/tsc.js:74698:13)
    at pipelineEmitWithHint (/Users/michael.katz/dev/ts-text-error/node_modules/typescript/lib/tsc.js:74131:32)
    at pipelineEmit (/Users/michael.katz/dev/ts-text-error/node_modules/typescript/lib/tsc.js:73785:13)
    at emitExpression (/Users/michael.katz/dev/ts-text-error/node_modules/typescript/lib/tsc.js:73777:20)
    at emitComputedPropertyName (/Users/michael.katz/dev/ts-text-error/node_modules/typescript/lib/tsc.js:74340:13)
    at pipelineEmitWithHint (/Users/michael.katz/dev/ts-text-error/node_modules/typescript/lib/tsc.js:73860:32)
    at pipelineEmit (/Users/michael.katz/dev/ts-text-error/node_modules/typescript/lib/tsc.js:73785:13)
    at emit (/Users/michael.katz/dev/ts-text-error/node_modules/typescript/lib/tsc.js:73765:30)
    at emitBindingElement (/Users/michael.katz/dev/ts-text-error/node_modules/typescript/lib/tsc.js:74660:17)
```


The error stems from this line where `currentSourceFile` is actually empty.
https://github.com/microsoft/TypeScript/blob/d02531f650111b98269ed5b08d497156677cb1b1/src/compiler/emitter.ts#L2661

**Comment by sandersn** [comment]
Original example looks like it still crashes in the 3.7.2 playground too.

**Comment by 3cL1p5e7** [comment]
it still crashes in the 3.8.3 playground when:
Crashes here
```jsx
// some/file.tsx
import Alert, {AlertTheme as AT} from 'components/Alert';
export * from 'components/Alert';
...
```

Source file
```tsx
// src/components/Alert.tsx
import * as React from 'react';
import * as block from 'bem-cn';

import './index.sass';
import {IClassName} from 'typings/props';
import Icon from 'components/Icon';

export enum AlertTheme {
  common = 'common',
  warning = 'warning'
}

interface IProps extends IClassName {
  title: string;
  text: string;
  icon?: string;
  theme?: AlertTheme;
  onClick?(e: React.MouseEvent<HTMLDivElement>): void;
}

const b = block('alert');
const Alert: React.FC<IProps> = ({
  className = '',
  title,
  theme = AlertTheme.common,
  text,
  icon,
  onClick
}) => (
  <div
    className={b.mix([className])({theme, icon: !!icon})()}
    onClick={onClick}
  >
    {
      !!icon &&
        <Icon
          className={b('icon')()}
          icon={icon}
          width={40}
          height={40}
        />
    }
    <div className={b('info')()}>
      <div>{title}</div>
      <div dangerouslySetInnerHTML={{__html: text}}/>
    </div>
  </div>
);

export default Alert;
```

Tsconfig.json
```
// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "lib": ["dom", "es2015", "es2016", "esnext"],
    "jsx": "react",
    "outDir": "./lib",
    "rootDir": "./src",
    "baseUrl": "./src",
    "paths": {
      "components/*": ["./components/*"]
    },
    "skipLibCheck": true,
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": true,
    "resolveJsonModule": true,
    "strictBindCallApply": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictNullChecks": true
  }
}
```

**Comment by sandersn** [comment]
@3cL1p5e7 can you open a new bug and give the stack when it crashes? I don't see a property access in a computed property in your repro, so it's likely a different bug.
