### ISSUE TITLE
tsserver does not support NetBSD

### ISSUE THREAD

**Issue by mudcovered** [microsoft/TypeScript#32396]
**TypeScript Version:**  3.5.2

**Search Terms:** tsserver, netbsd

**Code**

No code required

**Expected behavior:**

tsserver should run on NetBSD as it is a unix like operating system just like FreeBSD, OpenBSD and Linux

**Actual behavior:**
tsserver fails to start as it does not recognise the platform:
```
$ yarn tsserver
yarn run v1.17.3
$ /home/mpumford/src/rrdmonitorjs/node_modules/.bin/tsserver
/home/mpumford/src/rrdmonitorjs/node_modules/typescript/lib/tsserver.js:2075
            throw e;
            ^

Error: Debug Failure. unsupported platform 'netbsd'
    at getGlobalTypingsCacheLocation (/home/mpumford/src/rrdmonitorjs/node_modules/typescript/lib/tsserver.js:132566:37)
    at new IOSession (/home/mpumford/src/rrdmonitorjs/node_modules/typescript/lib/tsserver.js:132917:80)
    at ts.server.ts.server (/home/mpumford/src/rrdmonitorjs/node_modules/typescript/lib/tsserver.js:133334:25)
    at ts (/home/mpumford/src/rrdmonitorjs/node_modules/typescript/lib/tsserver.js:133349:7)
    at Object.<anonymous> (/home/mpumford/src/rrdmonitorjs/node_modules/typescript/lib/tsserver.js:133350:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/mpumford/src/rrdmonitorjs/node_modules/typescript/bin/tsserver:2:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
```
Adding netbsd to the platform switch on line 132558 stops the exception and allows tsserver to function normally. Tested with typescript mode on emacs 26.2 on NetBSD and Linux with no obvious difference in behaviour.

**Playground Link:** N/A No code required

**Related Issues:**  None

**Comment by iquiw** [comment]
`@types/node` now has `netbsd` as platform type.

So adding `case "netbsd":` [here (under freebsd)](https://github.com/microsoft/TypeScript/blob/6f04f526d4802fbb0860991b5719192014aa67b9/src/tsserver/server.ts#L22) could solve this?
