### ISSUE TITLE
Debug Failure. False expression: Token end is child end

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#32515]
From https://github.com/microsoft/vscode/issues/76848

**TypeScript Version:**  3.6.0-dev.20190720

**Search Terms:**
- quick fix
- refactoring

**Repo**
1. In the VS Code codebase
1. Open the `snippetController2.ts` file
1. Go to the `insert` method
1. Trigger the `convert to de-structured parameters` refactoring on the `insert` method

**Bug**
TS Server error:

```
Debug Failure. False expression: Token end is child end
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (tsserver.js:112600:34)
    at tsserver.js:112547:21
    at visitNode (tsserver.js:16711:24)
    at Object.forEachChild (tsserver.js:16798:21)
    at processNode (tsserver.js:112546:20)
    at processChildNode (tsserver.js:112606:21)
    at processChildNodes (tsserver.js:112657:48)
    at tsserver.js:112549:21
    at visitNodes (tsserver.js:16716:24)
    at Object.forEachChild (tsserver.js:16889:24)
    at processNode (tsserver.js:112546:20)
    at formatSpanWorker (tsserver.js:112361:17)
    at tsserver.js:112325:140
    at Object.getFormattingScanner (tsserver.js:111118:23)
    at Object.formatNodeGivenIndentation (tsserver.js:112325:31)
    at getFormattedTextOfNode (tsserver.js:114361:45)
    at format (tsserver.js:114339:52)
    at computeNewText (tsserver.js:114342:23)
    at tsserver.js:114312:89
    at Array.map (<anonymous>)
    at tsserver.js:114311:50
    at Array.map (<anonymous>)
    at Object.getTextChangesFromChanges (tsserver.js:114297:86)
    at ChangeTracker.getChanges (tsserver.js:114267:45)
    at Function.ChangeTracker.with (tsserver.js:113802:32)
    at Object.getEditsForAction (tsserver.js:122880:66)
    at Object.getEditsForRefactor (tsserver.js:114877:41)
    at Proxy.getEditsForRefactor (tsserver.js:125006:32)
    at IOSession.Session.getEditsForRefactor (tsserver.js:133879:59)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:132739:61)
    at tsserver.js:134117:88
    at IOSession.Session.executeWithRequestId (tsserver.js:134108:28)
    at IOSession.Session.executeCommand (tsserver.js:134117:33)
    at IOSession.Session.onMessage (tsserver.js:134139:35)
    at Interface.<anonymous> (tsserver.js:135439:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
	at Function.create (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:63463)
	at h.dispatchResponse (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:56618)
	at h.dispatchMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:55516)
	at constructor._reader.onData.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:54992)
	at u.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:49:306)
	at t.Reader.onLengthData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:61683)
	at Socket.t.Reader.constructor.e.on.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:61331)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by andrewbranch** [comment]
Interesting; if you name the function anything other than `insert` or declare it as private, it works 😅
