### ISSUE TITLE
Maximum call stack size exceeded when transpiling  specified .js file using `transpileModule`

### ISSUE THREAD

**Issue by xuld** [microsoft/TypeScript#32603]
**TypeScript Version:** Version 3.6.0-dev.20190727
**Search Terms:** Maximum call stack size exceeded

**Code**

```ts
var ts = require('typescript')

var input = `/**
 * @class
 * @constructor
 */
vjs.CoreObject = vjs['CoreObject'] = function () { };

vjs.CoreObject.extend = function (props) { };
`

ts.transpileModule(input, {"fileName": "any.js"})
```

**Expected behavior:**
...

**Actual behavior:**

```
D:\App\Node\node_modules\typescript\lib\typescript.js:91491
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at getNodeLinks (D:\App\Node\node_modules\[4mtypescript[24m\lib\typescript.js:32573:30)
    at getResolvedSymbol (D:\App\Node\node_modules\[4mtypescript[24m\lib\typescript.js:46468:25)
    at checkIdentifier (D:\App\Node\node_modules\[4mtypescript[24m\lib\typescript.js:48003:26)
    at checkExpressionWorker (D:\App\Node\node_modules\[4mtypescript[24m\lib\typescript.js:54706:28)
    at checkExpression (D:\App\Node\node_modules\[4mtypescript[24m\lib\typescript.js:54668:38)
    at checkNonNullExpression (D:\App\Node\node_modules\[4mtypescript[24m\lib\typescript.js:50479:37)
    at checkIndexedAccess (D:\App\Node\node_modules\[4mtypescript[24m\lib\typescript.js:50899:28)
    at checkExpressionWorker (D:\App\Node\node_modules\[4mtypescript[24m\lib\typescript.js:54739:28)
    at checkExpression (D:\App\Node\node_modules\[4mtypescript[24m\lib\typescript.js:54668:38)
    at checkBinaryLikeExpression (D:\App\Node\node_modules\[4mtypescript[24m\lib\typescript.js:53968:28)
	
```

When I omit `fileName` or set `fileName` to non-js file, the bug goes away

Maybe the bug is caused by `vjs.CoreObject = vjs['CoreObject']` and `
vjs.CoreObject.extend = ...` statement

**Comment by orta** [comment]
This is fixed in master - 👍
