### ISSUE TITLE
Error: Debug Failure. False expression. when using an empty generic on a non generic function

### ISSUE THREAD

**Issue by pvandam** [microsoft/TypeScript#33041]
**TypeScript Version:**  Version 3.7.0-dev.20190823

**Search Terms:**
Error: Debug Failure. False expression.

**Code**

```ts
function test() { }
test<>()
```

**Expected behavior:**
A normal compiler error.

**Actual behavior:**
A debug failure error:

```
node_modules/typescript/lib/tsc.js:75724
                throw e;
                ^

Error: Debug Failure. False expression.
    at Object.first (/home/paul/tstest/node_modules/typescript/lib/tsc.js:956:18)
    at getArgumentArityError (/home/paul/tstest/node_modules/typescript/lib/tsc.js:43559:32)
    at resolveCall (/home/paul/tstest/node_modules/typescript/lib/tsc.js:43704:41)
    at resolveCallExpression (/home/paul/tstest/node_modules/typescript/lib/tsc.js:43932:20)
    at resolveSignature (/home/paul/tstest/node_modules/typescript/lib/tsc.js:44234:28)
    at getResolvedSignature (/home/paul/tstest/node_modules/typescript/lib/tsc.js:44254:26)
    at checkCallExpression (/home/paul/tstest/node_modules/typescript/lib/tsc.js:44320:29)
    at checkExpressionWorker (/home/paul/tstest/node_modules/typescript/lib/tsc.js:46297:28)
    at checkExpression (/home/paul/tstest/node_modules/typescript/lib/tsc.js:46214:38)
    at checkExpressionStatement (/home/paul/tstest/node_modules/typescript/lib/tsc.js:48228:13)
```

**Playground Link:** 
http://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABFApgZygCgJSIN4BQAvgQahgDwB8OBQA

**Comment by RyanCavanaugh** [comment]
An actual crash with a short repro - easily the best bug report I'll see today. Thank you 🙂
