### ISSUE TITLE
Cannot read property 'getStart' of undefined — For invalid JavaScript

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#33102]
From https://github.com/microsoft/vscode-html-languageservice/issues/70

**TypeScript Version:**  3.6.0-rc

**Search Terms:**
- getOutliningSpans

**Repo**
Paste the following JavaScript into VS Code:

```ts
  try {
    var x = [
      {% try %}{% except %} // <-- breaks code folding support
    ]
  } catch (e) {
  }
```

**Expected behavior:**
I know this code is invalid since it contains an html template directive, but the ts server should not produce an exception on it.

**Actual behavior:**
```
TypeError: Cannot read property 'getStart' of undefined
    at Object.createTextSpanFromNode (tsserver.js:99663:49)
    at spanBetweenTokens (tsserver.js:109165:72)
    at spanForNode (tsserver.js:109151:51)
    at getOutliningSpanForNode (tsserver.js:109092:40)
    at visitNonImportNode (tsserver.js:108964:28)
    at visitNode (tsserver.js:17016:24)
    at Object.forEachChild (tsserver.js:17313:21)
    at NodeObject.forEachChild (tsserver.js:124434:23)
    at visitNonImportNode (tsserver.js:108977:23)
    at addNodeOutliningSpans (tsserver.js:108939:21)
    at Object.collectElements (tsserver.js:108927:13)
    at Object.getOutliningSpans (tsserver.js:125729:50)
```

**Playground Link:** 

**Related Issues:**

**Comment by orta** [comment]
Interesting, this only seems to happen when you embed the JS inside a script within a HTML file

```html
<script type="text/javascript">
  try {
    var x = [
      {% try %}{% except %} 
    ]
  } catch (e) {
  }
</script>
```

Crashes tsserver, but 

```ts
// #33102

class MyThing {
  thing() {
  }

  thingTwo() {

    const thing = ""
    try {
      var x = [
        {% try %}{% except %} // <-- breaks code folding support
      ]
    } catch (e) {
    }
    MyT
  }
}
```

Is fine.
