### ISSUE TITLE
Unexpected multiple outputs

### ISSUE THREAD

**Issue by olmobrutall** [microsoft/TypeScript#33184]
**TypeScript Version:**  3.6.2
After upgrating to TS 3.6.2, everithing else the same, webpack + ts-loader is not able to generate code anymore. Without **transpileOnly:true** works, but it's a big performance panalty. 

Note: I'm using transpileOnly:true for webpack generation and transpileOnly:false + noEmit in MsBuild/VisualStudio. 

**Code**
https://github.com/signumsoftware/southwind/tree/TS36/Southwind.React
https://github.com/signumsoftware/southwind/blob/TS36/Southwind.React/tsconfig.json

**Expected behavior:**
Generates javascript with webpack, ts-loader and with **transpileOnly:true**

**Actual behavior:**
```
=== undefined. Unexpected multiple outputs, file: D:/Signum/southwind/Southwind.React/ts_out/tsconfig.tsbuildinfo
    at Object.assertEqual (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:2056:17)
    at Object.writeFile (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:112241:30)
    at Object.__assign.writeFile (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:92029:210)
    at Object.writeFile (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:12098:14)
    at emitBuildInfo (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:86238:16)
    at emitSourceFileOrBundle (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:86205:13)
    at forEachEmittedFile (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:85999:28)
    at Object.emitFiles (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:86184:9)
    at emitWorker (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:92134:33)
    at D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:92095:66
    at runWithCancellationToken (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:92185:24)
    at Object.emit (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:92095:20)
    at Object.transpileModule (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:112261:17)
    at getTranspilationEmit (D:\Signum\southwind\Southwind.React\node_modules\ts-loader\dist\index.js:283:74)
    at successLoader (D:\Signum\southwind\Southwind.React\node_modules\ts-loader\dist\index.js:66:15)
    at Object.loader (D:\Signum\southwind\Southwind.React\node_modules\ts-loader\dist\index.js:22:12)
```

**Comment by VitProg** [comment]
We have the same problem on our project after updating to 3.6.2(
