### ISSUE TITLE
getAvailableActions - Debug Failure. False expression when selecting jsdoc comment

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#33332]
**TypeScript Version:**  3.7.0-dev.20190907

**Search Terms:**
- getAvailableActions
- getApplicableRefactors
- refactor
- quick fix

**Code**

```ts
/** @type {number} */ const foo = 1;
```

1. Select just the jsdoc comment and request refactorings / quick fixes

![Screen Shot 2019-09-09 at 4 59 43 PM](https://user-images.githubusercontent.com/12821956/64574198-55e68e80-d323-11e9-8e5d-6a72b29c493d.png)

**Bug:**

```
Debug Failure. False expression: This failure could trigger https://github.com/Microsoft/TypeScript/issues/20809
Error: Debug Failure. False expression: This failure could trigger https://github.com/Microsoft/TypeScript/issues/20809
    at getErrorSpanForNode (tsserver.js:9718:22)
    at createDiagnosticForNodeInSourceFile (tsserver.js:9631:20)
    at Object.createDiagnosticForNode (tsserver.js:9622:16)
    at checkNode (tsserver.js:122271:36)
    at getRangeToExtract (tsserver.js:122190:53)
    at Object.getAvailableActions (tsserver.js:121998:38)
    at tsserver.js:116434:128
    at getIterator (tsserver.js:637:23)
    at Object.next (tsserver.js:632:35)
    at Object.arrayFrom (tsserver.js:1276:40)
    at Object.getApplicableRefactors (tsserver.js:116433:23)
    at Proxy.getApplicableRefactors (tsserver.js:126809:32)
    at IOSession.Session.getApplicableRefactors (tsserver.js:135721:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:134576:61)
    at tsserver.js:135964:88
```

**Comment by amcasey** [comment]
This appears to be a repro for #20809.

**Comment by amcasey** [comment]
The extractSymbol refactoring is (correctly) reporting that that range can't be extracted (in particular, because it's neither a statement nor an expression).

My guess would be that `getErrorSpanForNode` doesn't handle trivia.
