### ISSUE TITLE
Error: Could not find source file: '%PATH%'. in 'getValidSourceFile' during 'getApplicableRefactors'

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#33331]
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript version prefix**: 3.6.2
**VSCode version**: 1.38.0
**Command requested**: getApplicableRefactors
**Hitting sessions**: 2686
**Five line hash**: ce34a40bb6b6c746cd68be8b7520e335
**Stack**:
```
Error: Could not find source file: '%PATH%'.
    at getValidSourceFile (tsserver.js:125241:29)
    at Proxy.getApplicableRefactors (tsserver.js:126022:24)
    at IOSession.Session.getApplicableRefactors (tsserver.js:134935:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:133790:61)
    at unknown (tsserver.js:135178:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:135169:28)
    at IOSession.Session.executeCommand (tsserver.js:135178:33)
    at IOSession.Session.onMessage (tsserver.js:135201:35)
    at Interface.<anonymous> (tsserver.js:136516:27)
    at suppressed_frame()
    at suppressed_frame()
    at suppressed_frame()
    at suppressed_frame()
    at suppressed_frame()
    at suppressed_frame()
    at suppressed_frame()
    at suppressed_frame()
    at suppressed_frame()
```

**Comment by sheetalkamat** [comment]
This seems like getApplicableRefactors was called with filename = %PATH% which seems to be wrong ?

**Comment by amcasey** [comment]
Note that `%path%` is a placeholder in this context.  The original was a fully-qualified path to a js file.

**Comment by sheetalkamat** [comment]
If that's the case then I am not sure we can understand what went wrong without actual repro.. Its most likely that some other command had exception before this resulting in bad state..
