### ISSUE TITLE
Type Checker creation fails when declare global is present

### ISSUE THREAD

**Issue by j-f1** [microsoft/TypeScript#33348]
**TypeScript Version:**  typescript@3.7.0-dev.20190910

**Search Terms:** `declare global` false expression

**Code**

```ts
// example.js
const ts = require('typescript')
const sourceFile = ts.createSourceFile("foo.ts", "declare global {}", ts.ScriptTarget.ESNext)
const program = ts.createProgram({
  rootNames: ["foo.ts"],
  options: { module: "esnext" },
  host: {
    getSourceFile: () => sourceFile,
    getDefaultLibFileName: () => "lib.esnext.d.ts",
    getCurrentDirectory: () => "/",
    getCanonicalFileName: f => f,
    useCaseSensitiveFileNames: () => true,
    fileExists: name => name === pathname,
  },
})
const typeChecker = program.getTypeChecker()
```

```shellsession
$ mkdir example
$ cd example
$ npm init -y
$ npm i typescript@3.7.0-dev.20190910
$ node example.js
```

**Expected behavior:**

A `TypeChecker` is successfully created.

**Actual behavior:**

```
Error: Debug Failure. False expression.
    at mergeSymbol (.../node_modules/typescript/lib/typescript.js:32889:26)
    at .../node_modules/typescript/lib/typescript.js:33000:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (.../node_modules/typescript/lib/typescript.js:32998:20)
    at initializeTypeChecker (.../node_modules/typescript/lib/typescript.js:61476:21)
    at Object.createTypeChecker (.../node_modules/typescript/lib/typescript.js:32736:9)
    at Object.getTypeChecker (.../node_modules/typescript/lib/typescript.js:92289:79)
```

**Playground Link:** N/A
**Related Issues:** <!-- Did you find other bugs that looked similar? -→
I did not find any similar bugs.

**Comment by j-f1** [comment]
Thanks, that worked!

```js
const ts = require('typescript')
const esNextLibPath = require.resolve('typescript/lib/lib.esnext.d.ts')
const esNextLib = require('fs').readFileSync(esNextLibPath, 'utf8')
const sourceFile = ts.createSourceFile("foo.ts", "declare global {}", ts.ScriptTarget.ESNext)
const sourceFiles = {
  "foo.ts": sourceFile,
  "lib.esnext.d.ts": ts.createSourceFile("lib.esnext.d.ts", esNextLib, ts.ScriptTarget.ESNext),
}
const program = ts.createProgram({
  rootNames: ["foo.ts"],
  options: { module: "esnext" },
  host: {
    getSourceFile: name => sourceFiles[name],
    getDefaultLibFileName: () => "lib.esnext.d.ts",
    getCurrentDirectory: () => "/",
    getCanonicalFileName: f => f,
    useCaseSensitiveFileNames: () => true,
    fileExists: name => name === "foo.ts",
  },
})
const typeChecker = program.getTypeChecker()
```
