### ISSUE TITLE
When was constraintDepth added?

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#33541]
I was testing some of my code in TS 3.6 and TS 3.7

Code that worked fine in TS 3.5.1 now got the `Type_instantiation_is_excessively_deep_and_possibly_infinite` error instead.

I decided to do a little investigation and noticed that there was this thing called `constraintDepth` with a limit of `50`. This was what was triggering the error.

I tried to disable the check for this `constraintDepth` and, predictably, got the error,
```
                return mapper(type);
                       ^
RangeError: Maximum call stack size exceeded
    at instantiateTypeWorker (/home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:42582:24)
    at instantiateType (/home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:42575:26)
    at /home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:42274:42
    at Object.map (/home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:507:29)
    at getConditionalTypeInstantiation (/home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:42537:40)
    at instantiateTypeWorker (/home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:42620:24)
    at instantiateType (/home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:42575:26)
    at /home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:42274:42
    at Object.map (/home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:507:29)
    at getConditionalTypeInstantiation (/home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:42537:40)
    at instantiateTypeWorker (/home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:42620:24)
    at instantiateType (/home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:42575:26)
    at /home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:42274:42
    at Object.map (/home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:507:29)
    at getConditionalTypeInstantiation (/home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:42537:40)
    at instantiateTypeWorker (/home/anyhowstep/node-projects/tsql/tsql/node_modules/typescript/lib/typescript.js:42620:24)
```

However, if the code I wrote really was the problem, it shouldn't have run fine in 3.5.1. It should have also exceeded the max call stack size.

-----

I don't have a minimal repro but I noticed something weird.
The following exceeds the constraint depth on 3.6 and 3.7,
![image](https://user-images.githubusercontent.com/5655961/65386400-4266fa80-dd09-11e9-8fd7-be597d8ea05e.png)

However, the following **does not**,
![image](https://user-images.githubusercontent.com/5655961/65386406-5f9bc900-dd09-11e9-8b81-7fb7806a189e.png)

Trying to nest function calls directly triggers the constraint depth error. But assigning it to a temporary variable is OK.

-----

I'm a bit at a loss here and out of my depth (haha, depth).

+ When was `constraintDepth` added?
+ Why was it added?
+ What problem was it trying to solve?

Code that worked fine in TS 3.5.1 now hits this `constraintDepth` error.
Removing the limit causes the max call stack size to be exceeded.

So, it looks to me like there's a bug with the code surrounding the `constraintDepth` implementation. Hopefully, the answers to my questions can help me refactor my code to not hit the depth limit. Or maybe it'll expose a bug that needs fixing in the TS code base.

**Comment by AnyhowStep** [comment]
The file with the problem may be found here,
https://github.com/AnyhowStep/tsql/commit/c413c1152ae7b65eb2e2a18ee985d6dbb8b31295#diff-dfb1d0c2f356726e8bd4741b3ba718daR12-R29

1. Clone https://github.com/AnyhowStep/tsql
2. `cd tsql`
2. Checkout `c413c1152ae7b65eb2e2a18ee985d6dbb8b31295`
3. `npm install`
4. `npm run test ./test/run-time/input/expr-library/double/acos/double.ts`

I'd like to again stress that this runs fine on TS 3.5.1 =(

**Comment by jack-williams** [comment]
https://github.com/microsoft/TypeScript/commit/44ada08e0204ed747e8bbab4c565c3588fb0119e

**Comment by AnyhowStep** [comment]
Also, further proof the functions in question are fine on TS 3.5.1,

https://github.com/AnyhowStep/tsql/commit/f9b73b2820d0f5f5e83db5b4393694d8a75a7342#diff-39b2092b0dd378cba12e94f7af61aba7R11-R573
In the above linked file, I've nested `acos()` and `coalesce()` calls 100+ times.

The emit of that giant file is here,
https://github.com/AnyhowStep/tsql/commit/f9b73b2820d0f5f5e83db5b4393694d8a75a7342#diff-925d183e2fe29d7d151e0add12f6e4eeR2-R36

That file and 500+ others only take 27s to compile with TS 3.5.1,
![image](https://user-images.githubusercontent.com/5655961/65386563-70e5d500-dd0b-11e9-8b11-bdad992a65f5.png)

**Comment by AnyhowStep** [comment]
Thanks, @jack-williams , I'll start looking from there.

**Comment by AnyhowStep** [comment]
Instead of trying to figure out which commit broke my `TypeOfCoalesce<>` recursive type, I decided to just convert it into a trampoline.

https://github.com/AnyhowStep/tsql/pull/65

https://github.com/AnyhowStep/tsql/pull/65/files#diff-0214b2fefabaf1617e690660683db775R226-R237
