### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#33617]
@ahejlsberg 

**TypeScript Version:**  3.4.0-dev.20190926

**Search Terms:**

**Code**

1. clone https://github.com/falsandtru/typed-dom
1. checkout 89f285b
1. run `npm i`
1. change src/dom/proxy.ts as follows
1. run `node_modules/.bin/tsc -p . --noEmit`

```diff
-  export interface Collection extends ReadonlyArray<El> { }
+  export type Collection = readonly El[];
```

**Expected behavior:**

no error

**Actual behavior:**

```
$ node_modules/.bin/tsc -p . --noEmit
...\typed-dom\node_modules\typescript\lib\tsc.js:76329
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at Object.some (...\typed-dom\node_modules\typescript\lib\tsc.js:668:18)
    at couldUnionOrIntersectionContainTypeVariables (...\typed-dom\node_modules\typescript\lib\tsc.js:38898:53)
    at couldContainTypeVariables (...\typed-dom\node_modules\typescript\lib\tsc.js:38894:65)
    at Object.forEach (...\typed-dom\node_modules\typescript\lib\tsc.js:225:30)
    at couldContainTypeVariables (...\typed-dom\node_modules\typescript\lib\tsc.js:38891:39)
    at Object.forEach (...\typed-dom\node_modules\typescript\lib\tsc.js:225:30)
    at couldContainTypeVariables (...\typed-dom\node_modules\typescript\lib\tsc.js:38891:39)
    at Object.some (...\typed-dom\node_modules\typescript\lib\tsc.js:673:25)
    at couldUnionOrIntersectionContainTypeVariables (...\typed-dom\node_modules\typescript\lib\tsc.js:38898:53)
    at couldContainTypeVariables (...\typed-dom\node_modules\typescript\lib\tsc.js:38894:65)
```

**Playground Link:** 

**Related Issues:**

**Comment by falsandtru** [comment]
Seems like the problem is realized at https://github.com/falsandtru/typed-dom/blob/89f285b452d1bd2fd90c9bcf193ba30179a49278/src/dom/proxy.ts#L200-L232

**Comment by falsandtru** [comment]
Caused by https://github.com/falsandtru/typed-dom/blob/89f285b452d1bd2fd90c9bcf193ba30179a49278/src/dom/proxy.ts#L227. Probably recursive type reference broke CFA.

**Comment by falsandtru** [comment]
I found another simpler case.

```ts
type Tree = [HTMLHeadingElement, Tree][];

function parse(node: Tree, index: number[] = []): HTMLUListElement {
  return html('ul', node.map(([el, children], i) => {
    const idx = [...index, i + 1];
    return html('li', [
      html('a', { href: `#${el.id}`, rel: 'noopener', 'data-index': idx.join('.') }, el.textContent!),
      children.length > 0 ? parse(children, idx) : frag()
    ]);
  }));
}

function cons(hs: HTMLHeadingElement[]): Tree {
  return hs
    .reduce<HTMLHeadingElement[][]>((hss, h) => {
      const hs = hss.pop()!;
      return hs.length === 0 || level(h) > level(hs[0])
        ? concat(hss, [concat(hs, [h])])
        : concat(hss, [hs, [h]]);
    }, [[]])
    .reduce<Tree>((node, hs) =>
      hs.length === 0
        ? node
        : concat<Tree[number]>(node, [[hs.shift()!, cons(hs)]])
    , []);
}

function level(h: HTMLHeadingElement): number {
  assert(isFinite(+h.tagName[1]));
  return +h.tagName[1];
}
```

```
$ node built/local/tsc.js --noEmit index.ts
...\TypeScript\built\local\tsc.js:94648
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at getTypeArguments (...\TypeScript\built\local\tsc.js:41991:34)
    at couldContainTypeVariables (...\TypeScript\built\local\tsc.js:48090:63)
    at Object.forEach (...\TypeScript\built\local\tsc.js:260:30)
    at couldContainTypeVariables (...\TypeScript\built\local\tsc.js:48090:55)
    at Object.forEach (...\TypeScript\built\local\tsc.js:260:30)
    at couldContainTypeVariables (...\TypeScript\built\local\tsc.js:48090:55)
    at Object.forEach (...\TypeScript\built\local\tsc.js:260:30)
    at couldContainTypeVariables (...\TypeScript\built\local\tsc.js:48090:55)
    at Object.forEach (...t\TypeScript\built\local\tsc.js:260:30)
    at couldContainTypeVariables (...\TypeScript\built\local\tsc.js:48090:55)
```

**Comment by falsandtru** [comment]
@ahejlsberg Still broken.

**Comment by ahejlsberg** [comment]
Simple repros that blow up in different places:

```ts
type RecArray1<T> = T | RecArray1<T>[];
type RecArray2<T> = T | RecArray2<T>[];

declare function foo<T>(a: RecArray1<T>): T;
declare let ra: RecArray2<string>;

let x = foo(ra);  // Boom!
```

```ts
type RecArray1<T> = number | RecArray1<T>[];
type RecArray2<T> = number | RecArray2<T>[];

declare function foo<T>(a: RecArray1<T>): T;
declare let ra: RecArray2<string>;

let x = foo(ra);  // Boom!
```

It's a pretty simple fix, will have a PR up shortly.
