### ISSUE TITLE
Compiler crashes with TypeError: Cannot read property 'kind' of undefined     at Object.isIdentifier 

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/TypeScript#33731]
**TypeScript Version:**  3.7.0-beta

**Search Terms:** kind undefined

**Code**

It happens only in https://github.com/sourcegraph/sourcegraph/tree/typescript-3.7/shared (the browser/ and the web/ project compile fine)

**Expected behavior:**

No error

**Actual behavior:**

Compiler crashes with

```
/Users/felix/git/sourcegraph/node_modules/typescript/lib/tsc.js:11300
                    ^

TypeError: Cannot read property 'kind' of undefined
    at Object.isIdentifier (/Users/felix/git/sourcegraph/node_modules/typescript/lib/tsc.js:11300:21)
    at lookupSymbolForPropertyAccess (/Users/felix/git/sourcegraph/node_modules/typescript/lib/tsc.js:25812:20)
    at lookupSymbolForPropertyAccess (/Users/felix/git/sourcegraph/node_modules/typescript/lib/tsc.js:25816:30)
    at lookupSymbolForPropertyAccess (/Users/felix/git/sourcegraph/node_modules/typescript/lib/tsc.js:25816:30)
    at bindObjectDefinePropertyAssignment (/Users/felix/git/sourcegraph/node_modules/typescript/lib/tsc.js:25687:35)
    at bindWorker (/Users/felix/git/sourcegraph/node_modules/typescript/lib/tsc.js:25406:36)
    at bind (/Users/felix/git/sourcegraph/node_modules/typescript/lib/tsc.js:25221:13)
    at bindExpressionStatement (/Users/felix/git/sourcegraph/node_modules/typescript/lib/tsc.js:24552:13)
    at bindChildrenWorker (/Users/felix/git/sourcegraph/node_modules/typescript/lib/tsc.js:24054:21)
    at bindChildren (/Users/felix/git/sourcegraph/node_modules/typescript/lib/tsc.js:23975:17)
```

**Playground Link:** 

Sorry for not having a minimal example, don't know how to narrow it down, but I hope that the open source project helps as a repro!

**Related Issues:** 
Bunch of similar errors but no idea if they are related

**Comment by sandersn** [comment]
I can't get the code to build, but from looking at the code, it looks like an Object.defineProperty with no arguments.

**Comment by sandersn** [comment]
@felixfbecker how did you get that stack? Running `tsc` inside `shared/` does not crash for me. I tried 3.6 and the nightly build. Basically, here's what I tried:

```
$ npm install
$ cd shared
$ npm install
$ tsc
```

I also tried `npm run all:typecheck` but has a bunch of errors in `web` and never gets past that.

**Comment by sandersn** [comment]
Assuming that I can't get this to build, you could add this line in tsc.js:lookupSymbolForPropertyAccess: `              ts.Debug.assert(!!node.expression, getTextOfNode(node))` so that it looks like this:

```ts
        function lookupSymbolForPropertyAccess(node: BindableStaticNameExpression, lookupContainer: Node = container): Symbol | undefined {
            if (isIdentifier(node)) {
                return lookupSymbolForNameWorker(lookupContainer, node.escapedText);
            }
            else {
                ts.Debug.assert(!!node.expression, getTextOfNode(node) + "\n" + getTextOfNode(lookupContainer))
                const symbol = lookupSymbolForPropertyAccess(node.expression);
                return symbol && symbol.exports && symbol.exports.get(getElementOrPropertyAccessName(node));
            }
        }
```

That will at least give you some text to grep for.

If the rest of the function *doesn't* look that, that's useful information too -- it's possible that we fixed this already.

**Comment by felixfbecker** [comment]
Ahh sorry, I had force pushed the branch to only include the migration changes and no actual update, so that I could merge it and have Renovate update continuously on top of the migrated master. The build is green now in the latest nightly update, so it must be fixed already! https://github.com/sourcegraph/sourcegraph/pull/6021
