### ISSUE TITLE
Assertion failure with `globalThis` in `declare global` block

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#33756]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

Click global.

```ts
// global.ts
declare global {
  export { globalThis as global };
}
```

**Expected behavior:**
pass
**Actual behavior:**
```
[2019-10-03 00:18:14.549] [renderer1] [error] <semantic> TypeScript Server Error (3.7.0-dev.20191001)
Debug Failure.
Error: Debug Failure.
    at Object.assertDefined (tsserver.js:2148:24)
    at getReferencesAtExportSpecifier (tsserver.js:110276:47)
    at getReferencesAtLocation (tsserver.js:110217:21)
    at getReferencesInContainer (tsserver.js:110183:21)
    at getReferencesInSourceFile (tsserver.js:110170:24)
    at searchForName (tsserver.js:109973:21)
    at getReferencesInContainerOrFiles (tsserver.js:109749:25)
    at getReferencedSymbolsForSymbol (tsserver.js:109733:21)
    at Object.getReferencedSymbolsForNode (tsserver.js:109536:34)
    at Object.getReferenceEntriesForNode (tsserver.js:109263:58)
    at getSemanticDocumentHighlights (tsserver.js:107953:57)
    at Object.getDocumentHighlights (tsserver.js:107941:20)
    at Object.getDocumentHighlights (tsserver.js:130505:42)
    at IOSession.Session.getDocumentHighlights (tsserver.js:139582:71)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:139004:61)
    at tsserver.js:140432:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140423:28)
    at IOSession.Session.executeCommand (tsserver.js:140432:33)
    at IOSession.Session.onMessage (tsserver.js:140455:35)
    at Interface.<anonymous> (tsserver.js:141770:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17): Error: <semantic> TypeScript Server Error (3.7.0-dev.20191001)
```
**Playground Link:** 

**Related Issues:**

**Comment by sandersn** [comment]
I can't repro this on latest, and when I check the playground for 3.6.3, it seems fine as well. I'll have to wait until tomorrow when I get to my desktop to find out when this started failing.

**Comment by falsandtru** [comment]
Did you click `global` alias after `as`? I can repro this error even on the playground.

http://www.typescriptlang.org/play/index.html#code/CYUwxgNghgTiAEBzCB7ARlC8DeAoe8IAHgA4owAuOSqGEAKgBYCWAzvFO8upvAL4BuXHyA

```
Uncaught Error: Debug Failure.

Error: Debug Failure.
    at Object.o [as assertDefined] (tsWorker.js:7)
    at R (tsWorker.js:7)
    at l (tsWorker.js:7)
    at c (tsWorker.js:7)
    at M (tsWorker.js:7)
    at k (tsWorker.js:7)
    at L (tsWorker.js:7)
    at x (tsWorker.js:7)
    at Object.e.getReferencedSymbolsForNode (tsWorker.js:7)
    at Object.u [as getReferenceEntriesForNode] (tsWorker.js:7)
    at errors.ts:22
(anonymous) @ errors.ts:22
setTimeout (async)
unexpectedErrorHandler @ errors.ts:20
e.onUnexpectedExternalError @ errors.ts:43
t.onUnexpectedExternalError @ errors.ts:60
Promise.then (async)
(anonymous) @ wordHighlighter.ts:49
r @ async.ts:181
t.first @ async.ts:192
b @ wordHighlighter.ts:47
t._compute @ wordHighlighter.ts:109
(anonymous) @ wordHighlighter.ts:66
r @ async.ts:21
e @ wordHighlighter.ts:66
t @ wordHighlighter.ts:107
(anonymous) @ wordHighlighter.ts:154
e._run @ wordHighlighter.ts:374
e._onPositionChanged @ wordHighlighter.ts:313
(anonymous) @ wordHighlighter.ts:199
e.fire @ event.ts:563
(anonymous) @ codeEditorWidget.ts:1280
e.fire @ event.ts:563
t._emitStateChangedIfNecessary @ cursor.ts:540
t.setStates @ cursor.ts:291
t.runCoreEditorCommand @ coreCommands.ts:290
executeEditorCommand @ codeEditorWidget.ts:1343
e._execMouseCommand @ viewController.ts:67
e.moveTo @ viewController.ts:218
e.dispatchMouse @ viewController.ts:203
t._dispatchMouse @ mouseHandler.ts:513
t.start @ mouseHandler.ts:381
t._onMouseDown @ mouseHandler.ts:242
(anonymous) @ mouseHandler.ts:109
(anonymous) @ editorDom.ts:116
```

**Comment by sandersn** [comment]
Thanks, I got it once I stopped and made a fourslash test.
