### ISSUE TITLE
Crash when writing `import global = globalThis;`

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#33755]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

Click globalThis.

```ts
// global.d.ts
import global = globalThis;
```

**Expected behavior:**
pass
**Actual behavior:**
```
[2019-10-03 00:07:31.278] [renderer1] [error] <semantic> TypeScript Server Error (3.7.0-dev.20191001)
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.find (tsserver.js:400:35)
    at getReferencedSymbolsForModuleIfDeclaredBySourceFile (tsserver.js:109551:78)
    at Object.getReferencedSymbolsForNode (tsserver.js:109529:40)
    at Object.getReferenceEntriesForNode (tsserver.js:109263:58)
    at getSemanticDocumentHighlights (tsserver.js:107953:57)
    at Object.getDocumentHighlights (tsserver.js:107941:20)
    at Object.getDocumentHighlights (tsserver.js:130505:42)
    at IOSession.Session.getDocumentHighlights (tsserver.js:139582:71)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:139004:61)
    at tsserver.js:140432:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140423:28)
    at IOSession.Session.executeCommand (tsserver.js:140432:33)
    at IOSession.Session.onMessage (tsserver.js:140455:35)
    at Interface.<anonymous> (tsserver.js:141770:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17): Error: <semantic> TypeScript Server Error (3.7.0-dev.20191001
```
**Playground Link:** 

**Related Issues:**

**Comment by falsandtru** [comment]
@sandersn Can you also take a look at this?

**Comment by jakebailey** [comment]
This crash was fixed back in https://github.com/microsoft/TypeScript/commit/590fd3f2a28, though it could probably use a real test if possible.

**Comment by RyanCavanaugh** [comment]
Fixed
