### ISSUE TITLE
`getSignaturesOfType` throws `Cannot read property 'flags' of undefined`

### ISSUE THREAD

**Issue by ark120202** [microsoft/TypeScript#33829]
**TypeScript Version:**  3.7.0-dev.20191005

**Search Terms:** conditional, infer, mapped

**Code**

```ts
declare interface Foo {
    a(): boolean;
    b(): void;
    c(argument: boolean): void;
    d(argument: number): void;
}

declare const Foo: Mapped<Foo>;
type Mapped<T> = {
  [K in keyof T]: T[K] extends (...args: infer Args) => infer R
    ? (...args: Args) => R
    : never;
};

function foo(key: 'a' | 'b' | 'c' | 'd') {
  Foo[key]();
}
```

Note: removing any infer declaration or method from `Foo` makes it valid.

**Expected behavior:**

No errors

**Actual behavior:**

```
TypeError: Cannot read property 'flags' of undefined
    at Object.getCheckFlags (typescript/lib/tsc.js:10461:23)
    at getTypeOfSymbol (typescript/lib/tsc.js:32706:20)
    at getParameterCount (typescript/lib/tsc.js:46831:32)
    at combineUnionParameters (typescript/lib/tsc.js:33697:29)
    at combineSignaturesOfUnionMembers (typescript/lib/tsc.js:33730:26)
    at typescript/lib/tsc.js:33673:181
    at Object.map (typescript/lib/tsc.js:446:29)
    at _loop_7 (typescript/lib/tsc.js:33673:144)
    at getUnionSignatures (typescript/lib/tsc.js:33681:35)
    at resolveUnionTypeMembers (typescript/lib/tsc.js:33754:34)
    at resolveStructuredTypeMembers (typescript/lib/tsc.js:34078:21)
    at getSignaturesOfStructuredType (typescript/lib/tsc.js:34573:32)
    at getSignaturesOfType (typescript/lib/tsc.js:34579:20)
```

**Playground Link:** https://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=1&ssc=1&pln=18&pc=2#code/CYUwxgNghgTiAEBLAdgFxDAZlMCBiA9gfAN4CwAUPNfFABQCUAXPAEZEQhTIDclNbRiwBuBRMD5UaYOrADmAVwC2INC3YFO3ZvFHjJA4LJiKVa+MmWsMOvRMoBfSpVCRYCMAWQBnVPEIELACyUAAOoSDAADwBAHySqACeEfAh4ZFRACqx8AC8pPzwANoA0kjI8ADWIIkEmPCZALosmaWN8CAAHujIwN7wdAB0w-LeLCiYGPAAgibeDHk5E1MASoXUAPwDw4OjLLNy84vwa1LULMggwhiSDpKUmArIYKiIXvCYRHTViSwA5FA-vAAD7wP6sIGgv5gSFg4B-BbkKQBIo-RqMW5AA

**Related Issues:**

**Comment by jasonk** [comment]
I ran into this issue and after fighting with it for a while managed to boil it down to a minimal reproduction: https://github.com/jasonk/repro-ts-33829

What I've managed to determine is that `combineUnionParameters` is getting called to merge the parameter types of some functions.  To do that it starts by calling `getParameterCount` on the signatures of the two functions:

```js
        function getParameterCount(signature) {
            var length = signature.parameters.length;
            if (signatureHasRestParameter(signature)) {
                var restType = getTypeOfSymbol(signature.parameters[length - 1]);
                if (isTupleType(restType)) {
                    return length + restType.target.fixedLength - (restType.target.hasRestElement ? 0 : 1);
                }
            }
            return length;
        }
```

In all of the examples I've seen what happens here is that `signatureHasRestParameter(signature)` returns true while `signature.parameters` is an empty array.  So then it ends up calling `getTypeOfSymbol( undefined )` which then throws the `Cannot read properties of undefined` error.

I'm not all that familiar with the internals of TypeScript but from what I found while trying to narrow it down to a reproduction I suspect that the problem is that if you have circular imports you can end up in a situation where it's trying to merge function parameter types at a point where it's already determined that one ore more of those functions have a rest parameter, but hasn't yet populated the parameters list in that signature object..

**Comment by Yesterday17** [comment]
I managed to make the example work with the following workaround ([Playground][playground]):

```diff
declare interface Foo {
    a(): boolean;
    b(): void;
    c(argument: boolean): void;
    d(argument: number): void;
}

declare const Foo: Mapped<Foo>;
type Mapped<T> = {
  [K in keyof T]: T[K] extends (...args: infer Args) => infer R
-   ? (...args: Args) => R
+   ? Args extends [any, ...any[]]
+      ? (...args: Args) => R
+      : () => R
    : never;
};

function foo(key: 'a' | 'b' | 'c' | 'd') {
  Foo[key]();
}
```

[playground]: https://www.typescriptlang.org/play?ts=4.7.4#code/CYUwxgNghgTiAEBLAdgFxDAZlMCBiA9gfAN4CwAUPNfFABQCUAXPAEZEQhTIDclNbRiwBuBRMD5UaYOrADmAVwC2INC3YFO3ZvFHjJA4LJiKVa+MmWsMOvRMoBfSpVCRYCMAWQBnVPEIELACyUAAOoSDAADwBAHySqACeEfAh4ZFRACqx8AC8pPzwANoA0kjI8ADWIIkEmPCZALosmaWN8CAAHujIwN7wdAB0w-LeLCiYGPAAgibeDHk5E1MASoXUAPwzcx3dqn3F3IkANPDDg0dFjY3rNFtDI3Mss3Lzi-BrUgIsjO+f3xYQMIMJIHJJKJgFMgwKhEF54JgiHRqokWAByKBo+AAH3gaNYWNxaLAhLxwDRC3IUgCRRRjUYoKAA

It seems that TypeScript compiler can not expand inferred arguments correctly on functions which does not have parameters at all.

**Comment by uid11** [comment]
Here is another instance of this error from the `combineIntersectionParameters` function (in TypeScript 5.6.3):
```
> tsc --noEmit

.../node_modules/typescript/lib/tsc.js:120986
      throw e;
      ^

TypeError: Cannot read properties of undefined (reading 'flags')
    at getCheckFlags (/home/uid11/JS/e2ed/node_modules/typescript/lib/tsc.js:17083:17)
    at getTypeOfSymbol (/home/uid11/JS/e2ed/node_modules/typescript/lib/tsc.js:55429:24)
    at getParameterCount (/home/uid11/JS/e2ed/node_modules/typescript/lib/tsc.js:76368:24)
    at combineIntersectionParameters (/home/uid11/JS/e2ed/node_modules/typescript/lib/tsc.js:71929:23)
    at combineSignaturesOfIntersectionMembers (/home/uid11/JS/e2ed/node_modules/typescript/lib/tsc.js:71976:20)
    at /home/uid11/JS/e2ed/node_modules/typescript/lib/tsc.js:71918:133
    at reduceLeft (/home/uid11/JS/e2ed/node_modules/typescript/lib/tsc.js:662:18)
    at getIntersectedSignatures (/home/uid11/JS/e2ed/node_modules/typescript/lib/tsc.js:71916:69)
    at getContextualCallSignature (/home/uid11/JS/e2ed/node_modules/typescript/lib/tsc.js:72001:68)
    at getContextualSignature (/home/uid11/JS/e2ed/node_modules/typescript/lib/tsc.js:72035:25)

Node.js v20.16.0
```

Unfortunately, I couldn't create a minimal reproduction example, but the error can be reproduced by checking out the https://github.com/joomcode/e2ed/tree/ts-error-example branch from the https://github.com/joomcode/e2ed repository, installing dependencies (`npm ci`), and running the `npm run lint:types:base` command.

The error can also be seen in the GitHub Actions logs for this branch when trying to run the type-checking command `tsc`: https://github.com/joomcode/e2ed/actions/runs/11413108560/job/31760164826.

The error occurs when working with the following complex generic: https://github.com/joomcode/e2ed/blob/ts-error-example/src/types/selectors.ts#L7-L42.

As far as I can see, the proposed [fix](https://github.com/microsoft/TypeScript/pull/52472) will fix this bug.

**Comment by LaamGinghong** [comment]
get the same error in version `5.6.3` but not in `5.5.4`

**Comment by RyanCavanaugh** [comment]
No longer repros
