### ISSUE TITLE
Debug Failure. Did not expect PropertyDeclaration to have an Identifier in its trivia

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#33935]
We can see via telemetry this happens a fair amount. The invalid parse tree indicated by this assertion may be the root cause of a VS crash @uniqueiniquity was investigating, but we haven’t been able to reproduce. Posting this issue in the hopes that someone will search for this and provide us with more clues.

(Note: I’m specifically interested in _PropertyDeclaration_ errors—this happens more often with JSX-related nodes.)

```
Debug Failure. Did not expect PropertyDeclaration to have an Identifier in its trivia
        at addSyntheticNodes (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:117479:30)
        at processNode (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:117452:13)
        at Object.forEach (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:207:30)
        at createChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:117462:12)
        at NodeObject.getChildren (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:117412:56)
        at getTokenAtPositionWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:93879:43)
        at Object.getTokenAtPosition (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:93871:16)
        at Object.getCodeActions (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:113197:32)
        at C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:109567:121
        at Object.flatMap (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:488:25)
        at Object.getFixes (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:109567:23)
        at C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:118771:35
        at Object.flatMap (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:488:25)
        at Object.getCodeFixesAtPosition (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:118769:23)
        at IOSession.Session.getCodeFixes (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:126922:64)
        at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:125730:61)
        at C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:127091:88
        at IOSession.Session.executeWithRequestId (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:127082:28)
        at IOSession.Session.executeCommand (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:127091:33)
        at IOSession.Session.onMessage (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:127113:35)
        at Interface.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.3\tsserver.js:128374:27)
        at Interface.emit (events.js:182:13)
        at Interface._onLine (readline.js:290:10)
        at Interface._normalWrite (readline.js:433:12)
        at Socket.ondata (readline.js:149:10)
        at Socket.emit (events.js:182:13)
        at addChunk (_stream_readable.js:283:12)
        at readableAddChunk (_stream_readable.js:264:11)
        at Socket.Readable.push (_stream_readable.js:219:10)
        at Pipe.onread (net.js:638:20)
```

**Comment by DanielRosenwasser** [comment]
FWIW there's https://github.com/microsoft/TypeScript/issues/44154 if that gives you any clues.

**Comment by andrewbranch** [comment]
I don’t think anything JSX-related helps with this one.

**Comment by RyanCavanaugh** [comment]
The TypeScript 3.3 stack trace identifies a `getCodeFixes` request, but it does not include the source file, position or range, or the requested code fix. The linked classifier change and the later JSX reports do not contain a PropertyDeclaration example for this crash.

Please provide the source file and the cursor position or diagnostic range used for `getCodeFixes`, together with the exact request or an archived tsserver log that includes it. That is needed to reproduce this specific PropertyDeclaration failure.

**Comment by andrewbranch** [comment]
We can probably assume this code path is no longer quite the same, and will show up differently in TS 7 telemetry if it's still a problem.
