### ISSUE TITLE
Crash when calling a JS function tagged `@constructor` but no properties

### ISSUE THREAD

**Issue by brasten** [microsoft/TypeScript#34346]
**TypeScript Version:**  3.7.0-dev.20191014

**Search Terms:**
Cannot read property 'parent' of undefined

**Code**

```ts
// src/Dependency.js
/**
 * Some dependency.
 *
 * @param {object} opts
 * @constructor
 */
function Dependency(opts) {
  // we're tagged as a constructor but obviously not used that way.
  return Object.assign({}, opts);
}

module.exports = Dependency;
```
```ts
// src/index.ts
const Dependency = require('./Dependency');
const deps = Dependency({});
```

**GitHub repo:**
https://github.com/brasten/ts-jsdoc-constructor-error

**Expected behavior:**
Successful compilation (as under previous versions)
OR
a compilation error/warning pointing to the issue (`@constructor` does not match up with usage in this case). It took a while to track down which files in my project were causing the issue, and then more time to figure out what the specific issue was.

**Actual behavior:**
```
> tsc -b

/Users/brasten/Projects/Scratch/BugReports/ts-top-level-jsdoc/node_modules/typescript/lib/tsc.js:78446
                throw e;
                ^

TypeError: Cannot read property 'parent' of undefined
    at getOuterTypeParameters (/Users/brasten/Projects/Scratch/BugReports/ts-top-level-jsdoc/node_modules/typescript/lib/tsc.js:32718:29)
    at getOuterTypeParametersOfClassOrInterface (/Users/brasten/Projects/Scratch/BugReports/ts-top-level-jsdoc/node_modules/typescript/lib/tsc.js:32769:20)
    at getDeclaredTypeOfClassOrInterface (/Users/brasten/Projects/Scratch/BugReports/ts-top-level-jsdoc/node_modules/typescript/lib/tsc.js:33003:43)
    at createAnonymousTypeNode (/Users/brasten/Projects/Scratch/BugReports/ts-top-level-jsdoc/node_modules/typescript/lib/tsc.js:29876:59)
    at typeToTypeNodeHelper (/Users/brasten/Projects/Scratch/BugReports/ts-top-level-jsdoc/node_modules/typescript/lib/tsc.js:29825:28)
    at /Users/brasten/Projects/Scratch/BugReports/ts-top-level-jsdoc/node_modules/typescript/lib/tsc.js:29617:106
    at withContext (/Users/brasten/Projects/Scratch/BugReports/ts-top-level-jsdoc/node_modules/typescript/lib/tsc.js:29661:37)
    at Object.typeToTypeNode (/Users/brasten/Projects/Scratch/BugReports/ts-top-level-jsdoc/node_modules/typescript/lib/tsc.js:29617:28)
    at typeToString (/Users/brasten/Projects/Scratch/BugReports/ts-top-level-jsdoc/node_modules/typescript/lib/tsc.js:29584:40)
    at resolveCallExpression (/Users/brasten/Projects/Scratch/BugReports/ts-top-level-jsdoc/node_modules/typescript/lib/tsc.js:46142:105)
```

**Playground Link:** None, not sure how to set up issue in Playground. See Github link above.

**Comment by Knagis** [comment]
This same issue happens when using TS 3.7.0 to transpile BabylonJS es6 code.

```
    TypeError: node_modules/@babylonjs/core/Engines/Processors/shaderCodeCursor.js: Cannot read property 'parent' of undefined

      at getOuterTypeParameters (../../node_modules/typescript/lib/typescript.js:39622:29)
      at getOuterTypeParametersOfClassOrInterface (../../node_modules/typescript/lib/typescript.js:39675:20)
      at getDeclaredTypeOfClassOrInterface (../../node_modules/typescript/lib/typescript.js:39948:43)
      at createAnonymousTypeNode (../../node_modules/typescript/lib/typescript.js:36343:59)
      at typeToTypeNodeHelper (../../node_modules/typescript/lib/typescript.js:36289:28)
      at ../../node_modules/typescript/lib/typescript.js:36078:106
      at withContext (../../node_modules/typescript/lib/typescript.js:36123:37)
      at Object.typeToTypeNode (../../node_modules/typescript/lib/typescript.js:36078:28)
      at typeToString (../../node_modules/typescript/lib/typescript.js:36045:40)
      at reportNonexistentProperty (../../node_modules/typescript/lib/typescript.js:53822:165)
```

**Comment by sandersn** [comment]
Smaller repro:

```js
// @filename: dependency.js
/**
 * @constructor
 */
function Dependency(j) {
  return j
}
Dependency({})
```

**Comment by sandersn** [comment]
The crash is in the error reporting code, which is why we didn't issue a nice error for the mismatch.
