### ISSUE TITLE
Definitions stop working after a while

### ISSUE THREAD

**Issue by MuTLY** [microsoft/TypeScript#34404]
*Template info added by @mjbvz*

**TypeScript Version**: 3.7.0-dev.20191013

**Search Terms**
- go to definition
- react

---

Issue Type: <b>Bug</b>

Open VSCode, open a React file (JS or JSX), and on hovering a class or any other element on the code, a definition popup shows up correctly.

After a while (it can be minutes, or just by editing a file), it stops working and all it shows up on hovering is a small "Loading..." tooltip.

![image](https://user-images.githubusercontent.com/777006/66348399-d7ced500-e92c-11e9-8fb7-297de0104239.png)

And I was able to grab this from the app's console:

```
/C:/Users/MuTLY/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3579 [Extension Host] debugger listening on port 58674
log.ts:173   ERR <semantic> TypeScript Server Error (3.6.2)
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.find (tsserver.js:385:35)
    at getReferencedSymbolsForModuleIfDeclaredBySourceFile (tsserver.js:105629:78)
    at Object.getReferencedSymbolsForNode (tsserver.js:105607:40)
    at Object.getReferenceEntriesForNode (tsserver.js:105341:58)
    at getSemanticDocumentHighlights (tsserver.js:104031:57)
    at Object.getDocumentHighlights (tsserver.js:104019:20)
    at Object.getDocumentHighlights (tsserver.js:125577:42)
    at IOSession.Session.getDocumentHighlights (tsserver.js:134328:71)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:133752:61)
    at tsserver.js:135178:88
    at IOSession.Session.executeWithRequestId (tsserver.js:135169:28)
    at IOSession.Session.executeCommand (tsserver.js:135178:33)
    at IOSession.Session.onMessage (tsserver.js:135201:35)
    at Interface.<anonymous> (tsserver.js:136516:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17): Error: <semantic> TypeScript Server Error (3.6.2)
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.find (tsserver.js:385:35)
    at getReferencedSymbolsForModuleIfDeclaredBySourceFile (tsserver.js:105629:78)
    at Object.getReferencedSymbolsForNode (tsserver.js:105607:40)
    at Object.getReferenceEntriesForNode (tsserver.js:105341:58)
    at getSemanticDocumentHighlights (tsserver.js:104031:57)
    at Object.getDocumentHighlights (tsserver.js:104019:20)
    at Object.getDocumentHighlights (tsserver.js:125577:42)
    at IOSession.Session.getDocumentHighlights (tsserver.js:134328:71)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:133752:61)
    at tsserver.js:135178:88
    at IOSession.Session.executeWithRequestId (tsserver.js:135169:28)
    at IOSession.Session.executeCommand (tsserver.js:135178:33)
    at IOSession.Session.onMessage (tsserver.js:135201:35)
    at Interface.<anonymous> (tsserver.js:136516:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
	at Function.create (c:\Users\MuTLY\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:63463)
	at h.dispatchResponse (c:\Users\MuTLY\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:56618)
	at h.dispatchMessage (c:\Users\MuTLY\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:55516)
	at constructor._reader.onData.e (c:\Users\MuTLY\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:54992)
	at u.fire (c:\Users\MuTLY\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at t.Reader.onLengthData (c:\Users\MuTLY\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:61683)
	at Socket.t.Reader.constructor.e.on.e (c:\Users\MuTLY\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:61331)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

I have to mention I already uninstalled and reinstalled VSCode a few times, even going thru the lengths of manually deleting folders and Registry keys as explained in several other issues here.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.5.0
subtle-brackets|raf|3.0.0
highlight-matching-tag|vin|0.9.5

</details>

**Comment by mjbvz** [comment]
Thanks for the logs. Moved upstream to TS. The project updating in the logs looks suspicious but someone on the TS team should be able to confirm

As a work around, you can try creating a [jsconfig](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson) file

**Comment by amcasey** [comment]
It seems like there might be multiple issues:
 1) The `getReferencedSymbolsForModuleIfDeclaredBySourceFile` exception looks the same as #30896, #33755, and #32858.
 2) The `unescapeLeadingUnderscores` looks similar to a family of exceptions that have shown up in telemetry bugs since ~2.6.
 3) The log shows some responsiveness issues during initialization, but I don't see anything related to either (1) or (2).

@MuTLY any chance you could grab a log for a session is which exceptions are written to the console?

**Comment by MuTLY** [comment]
@amcasey here's a full verbose log of a session where the issue occured.

[-1571690885284.log](https://github.com/microsoft/TypeScript/files/3752854/-1571690885284.log)

**Comment by amcasey** [comment]
Sorry, I should have been clearer - do you have a _server_ log for that session?

**Comment by MuTLY** [comment]
I'm not sure. How can I capture that?

**Comment by amcasey** [comment]
If you still have `typescript.tsserver.log` enabled (from above), you should be able to just `TypeScript: Open TS Server log`.

**Comment by MuTLY** [comment]
Here we go.

[ts-server-log.log](https://github.com/microsoft/TypeScript/files/3752932/ts-server-log.log)

**Comment by amcasey** [comment]
Weird - it still doesn't show the errors you're seeing in the console, even though the console errors are from the component doing the logging.  I'll see if I can figure out why that might be happening.  Thanks for your patience!

**Comment by MuTLY** [comment]
Oh wait, that's from a new session! Let me upload the dev tools log too.

**Comment by MuTLY** [comment]
[-1571693573977.log](https://github.com/microsoft/TypeScript/files/3752988/-1571693573977.log)

**Comment by MuTLY** [comment]
@amcasey the above log is from the same session of the TS log up there.

**Comment by amcasey** [comment]
@MuTLY I think I've pinned down exact steps.  If you navigate to the Output panel and select "TypeScript" from the dropdown, it will show both exceptions and the paths to the corresponding log files.  Next time you see an exception in the TypeScript Output, please grab the corresponding log(s).  If you've had VS Code open for a while, there may already be occurrences in the TypeScript Output.  Again, thanks for your patience - I'm used to collecting logs from VS, rather than VS Code.

**Comment by MuTLY** [comment]
Here's what I've found by looking at the output panel. I've zipped the whole log folder. Hope it helps.

[vscode.typescript-language-features.zip](https://github.com/microsoft/TypeScript/files/3753017/vscode.typescript-language-features.zip)

**Comment by amcasey** [comment]
Still nothing. 😢 Investigating should still be possible without those logs - just harder.  I'll see what I can figure out and let you know if I have questions.

**Comment by amcasey** [comment]
This appears to be an easy repro for the unescapeLeadingUnderscores issues:
```ts
function F(key, value) {
    return {
        [key]: value,
        "prop": true
    }
}
```

**Comment by amcasey** [comment]
The fix for (2) is merged and the fix for (1) is in PR.  I think (3) is too broad to cover in the same GH issue, so I'm inclined to close this once the second PR merges.  @MuTLY?

**Comment by MuTLY** [comment]
I'm good with that. Thank you @amcasey and @mjbvz so much for looking into this.

**Comment by amcasey** [comment]
I'm not sure what time we snap for the nightly build, but the fixes should be reflected in `typescript@next` tomorrow or the next day.
