### ISSUE TITLE
--allowJs: Cannot update prototype of imported class (3.7.0 regression)

### ISSUE THREAD

**Issue by Knagis** [microsoft/TypeScript#34493]
**TypeScript Version:**  3.7.0-dev.20191015

**Code**
Initial source:
`lodash-es/lodash.default.js` file from lodash-es@4.17.15

Minimum repro:
```
import A from 'A';
A.prototype.foo = 0;
```

**Expected behavior:**
Code transpiles without errors

**Actual behavior:**

```
node_modules\typescript\lib\tsc.js:23676
            node.symbol = symbol;

    TypeError: node_modules\lodash-es\lodash.default.js: Cannot set property 'symbol' of undefined

      at addDeclarationToSymbol (node_modules/typescript/lib/typescript.js:29235:25)
      at bindPotentiallyMissingNamespaces (node_modules/typescript/lib/typescript.js:31604:17)
      at bindPropertyAssignment (node_modules/typescript/lib/typescript.js:31656:31)
      at bindPrototypePropertyAssignment (node_modules/typescript/lib/typescript.js:31544:13)
      at bindWorker (node_modules/typescript/lib/typescript.js:31139:29)
      at bind (node_modules/typescript/lib/typescript.js:31027:13)
      at bindExpressionStatement (node_modules/typescript/lib/typescript.js:30235:13)
      at bindChildrenWorker (node_modules/typescript/lib/typescript.js:29693:21)
      at bindChildren (node_modules/typescript/lib/typescript.js:29614:17)
      at bind (node_modules/typescript/lib/typescript.js:31038:21)
```

 

**Playground Link:**
http://www.typescriptlang.org/play/?target=1&ts=3.7-Beta&useJavaScript=true#code/JYWwDg9gTgLgBAQTgMyhEcDkDMG4BQCAdGGjBDAJ5gCmRyEEcAvHAAy5A (see error in browser console)

**Comment by Knagis** [comment]
Minimum repro:

```ts
import A from './A.js';

A.prototype.foo = function() {
  return new A();
};
```

**Comment by sandersn** [comment]
`A` is an alias symbol, which doesn't get a valueDeclaration, but the expando binding assumes that the original symbol has a valueDeclaration.

I'm not sure whether the right fix is to not skip expando binding when the original symbol doesn't have a valueDeclaration, or to rebind the alias' declaration as a valueDeclaration. I'll try both and see which behaves better.

**Comment by sandersn** [comment]
Since the RC snaps at 2 PM today, I'm going to fix the crash (option 1 above) and investigate the follow-on crash from option 2 afterward. Option 2 should restore the pre-3.7 behaviour when it works.

**Comment by sandersn** [comment]
My historical repro was set up wrong -- now that I've fixed it, I can see that this *never* worked, so I will probably leave it at fixing the crash.
