### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined in 'Object.forEachChild' during "ng build --prod"

### ISSUE THREAD

**Issue by dnyaneshwar-amazatic** [microsoft/TypeScript#34512]
My Angular CLI version is (7.3.9), 
Node 10.16.3, 
Typescript 3.1.6

When I run:- ng build --prod It fails with the following Error.
`Date: 2019-10-16T10:51:09.356Z
Hash: 5e96b3d4506b7e0309e2
Time: 33576ms
---------------------------------------------------------------------------------------------------------------

chunk {0} common.1c16b66e2dc9707a3b58.js (common) 15.9 kB [rendered]
chunk {1} runtime.bcd245d37dfc345066e0.js (runtime) 2.33 kB [entry] [rendered]
chunk {2} 2.68b747abb47eb68d0533.js () 830 kB [rendered]
chunk {3} main.beeb15859443d2425509.js (main) 2.26 MB [initial] [rendered]
chunk {4} polyfills.c6e355a6d69372a21900.js (polyfills) 41 kB [initial] [rendered]
chunk {5} styles.1f662db96d381bd4672f.css (styles) 188 kB [initial] [rendered]
chunk {6} 6.f86474f62f6e0801aebb.js () 106 kB [rendered]
chunk {7} 7.776c1f6c1132d75799b3.js () 3.73 kB [rendered]
chunk {8} 8.dc79e1074e7fa12fbc60.js () 134 kB [rendered]
chunk {9} 9.b07a3235bd266d8a4cca.js () 163 kB [rendered]
chunk {10} 10.10df86d42d2d0c674b10.js () 234 kB [rendered]
chunk {11} 11.8e7b16f672f75856651e.js () 76 kB [rendered]
chunk {scripts} scripts.091d3f4f3258ad6e9f29.js (scripts) 161 kB [entry] [rendered]

ERROR in ./node_modules/ng2-material-dropdown/fesm5/ng2-material-dropdown.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
at isAngularDecoratorMetadataExpression (/home/vaibhav/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
at checkNodeForDecorators (/home/vaibhav/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
at visitNodes (/home/vaibhav/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16144:30)
at Object.forEachChild (/home/vaibhav/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16370:24)
at checkNodeForDecorators (/home/vaibhav/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
at visitNode (/home/vaibhavnode_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
at Object.forEachChild (/home/vaibhav/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16265:21)
at checkNodeForDecorators (/home/vaibhav/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
at visitNode (/home/vaibhav/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
at Object.forEachChild (/home/vaibhav/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16322:24)
at checkNodeForDecorators (/home/vaibhav/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
at visitNode (/home/vaibhav/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
at Object.forEachChild (/home/vaibhav/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16333:24)
at checkNodeForDecorators (/home/vaibhav/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
at visitNode (/home/vaibhav/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
at Object.forEachChild (/home/vaibhav/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16229:21)

But ng serve works fine

**Comment by j-oliveras** [comment]
This is an error with angular wrapper of typescript. The function that throws (`isAngularDecoratorMetadataExpression`) is declared inside the package `@angular-devkit/build-optimizer`.

Please follow the issue template.

**Comment by RyanCavanaugh** [comment]
The callstack here is like 30 frames deep in Angular's code. We are not the authors of Angular.
