### ISSUE TITLE
TS 3.7 getApplicableRefactors — Error: Debug Failure. Should find a statement

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#34580]
**TypeScript Version:**  3.7.0-dev.20191016

**Search terms**
- getApplicableRefactors

From VS Code error telemetry, we're seeing at least 50 unique machines hitting the following error on  3.7.0-dev.20191016 specifically:

```
Error: Debug Failure. Should find a statement
	    at Object.assertDefined (tsserver.js:2004:24)
	    at getRangeToExtract (tsserver.js:127851:43)
	    at Object.getAvailableActions (tsserver.js:127803:28)
	    at tsserver.js:120275:128
	    at getIterator (tsserver.js:522:23)
	    at Object.next (tsserver.js:517:35)
	    at Object.arrayFrom (tsserver.js:1162:88)
	    at Object.getApplicableRefactors (tsserver.js:120274:23)
	    at Object.getApplicableRefactors (tsserver.js:131141:32)
	    at IOSession.Session.getApplicableRefactors (tsserver.js:140406:53)
	    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:139259:61)
	    at tsserver.js:140649:88
	    at IOSession.Session.executeWithRequestId (tsserver.js:140640:28)
	    at IOSession.Session.executeCommand (tsserver.js:140649:33)
	    at IOSession.Session.onMessage (tsserver.js:140672:35)
	    at Interface.<anonymous> (tsserver.js:141987:27)
	    at Interface.emit (events.js:182:13)
	    at Interface._onLine (readline.js:290:10)
	    at Interface._normalWrite (readline.js:433:12)
	    at Socket.ondata (readline.js:149:10)
	    at Socket.emit (events.js:182:13)
	    at addChunk (_stream_readable.js:283:12)
	    at readableAddChunk (_stream_readable.js:264:11)
	    at Socket.Readable.push (_stream_readable.js:219:10)
	    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by andrewbranch** [comment]
👍 This is in the "Extract type" refactor
