### ISSUE TITLE
Failure to LKG doesn't block nightly publish

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#34582]
Last night's publish to `typescript@next` actually failed to update the LKG (Last Known Good) version of the compiler in lib, and instead published whatever the last LKG was. Here's the error:

```
src/tsc/tsc.ts(2,4): error TS2339: Property 'executeCommandLine' does not exist on type 'typeof ts'.
[06:05:47] 'buildTsc' errored after 1 min
[06:05:47] Error: Process exited with code: 2
    at ChildProcess.proc.on.exitCode (/home/vsts/work/1/s/scripts/build/utils.js:54:28)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:466:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

See more at https://typescript.visualstudio.com/TypeScript/_build/results?buildId=49613

**Comment by weswigham** [comment]
Just added `trap "exit \$?" ERR` to the nightly publish script, just like what the tarball packer has. It aughta now fail.

**Comment by DanielRosenwasser** [comment]
So fixed?

**Comment by fatcerberus** [comment]
> last LKG

Redundant much? 😄
