### ISSUE TITLE
TS3.7 regression: crash with defineProperty and assignment into window property

### ISSUE THREAD

**Issue by mprobst** [microsoft/TypeScript#34640]
**TypeScript Version:**  3.7.0-beta

**Search Terms:** Object defineProperty constructor crash

**Code**

```ts
window.HTMLElement = function() {
  function MyConstructor() {}
  Object.defineProperty(MyConstructor.prototype, 'banana', {});
  return MyConstructor
}();
```

**Expected behavior:**

Checks.

**Actual behavior:**

Crashes:

```
$ ./node_modules/.bin/tsc 
node_modules/typescript/lib/tsc.js:78397
                throw e;
                ^

TypeError: Cannot read property 'parent' of undefined
    at getOuterTypeParameters (node_modules/typescript/lib/tsc.js:32741:29)
    at getOuterTypeParametersOfClassOrInterface (node_modules/typescript/lib/tsc.js:32792:20)
    at getDeclaredTypeOfClassOrInterface (node_modules/typescript/lib/tsc.js:33026:43)
    at compareSignaturesRelated (node_modules/typescript/lib/tsc.js:37906:83)
    at signatureRelatedTo (node_modules/typescript/lib/tsc.js:39515:24)
    at signaturesRelatedTo (node_modules/typescript/lib/tsc.js:39478:30)
    at structuredTypeRelatedTo (node_modules/typescript/lib/tsc.js:39057:43)
    at recursiveTypeRelatedTo (node_modules/typescript/lib/tsc.js:38806:53)
    at isRelatedTo (node_modules/typescript/lib/tsc.js:38428:38)
    at checkTypeRelatedTo (node_modules/typescript/lib/tsc.js:38112:26)
```

It appears this code is called assuming the node is either a Class or Interface, but it's just a function declaration.

**Comment by sandersn** [comment]
This is fixed in nightly and should be in 3.7.1-rc when we manage to publish that. @mprobst can you test with that instead?

**Comment by mprobst** [comment]
I cannot find a `3.7.1-rc` on NPM. I've tried with 3.8 nightly and 3.7.0-dev.20191021, and I can confirm this issue is fixed in both.

**Comment by sandersn** [comment]
Yikes, that's because we haven't published it yet! @DanielRosenwasser can you update this thread when it's out?
