### ISSUE TITLE
TS3.7 regression: crash when transforming modules

### ISSUE THREAD

**Issue by mprobst** [microsoft/TypeScript#34644]
**TypeScript Version:**  3.7.0-beta (also on latest master)

**Search Terms:** ModuleDeclaration ModuleBody transform

**Code**

See test case in https://github.com/microsoft/TypeScript/pull/34513. TypeScript crashes when transforming any node within a `module Foo { }` block.

**Expected behavior:**

No crash.

**Actual behavior:**

```
  1) unittests:: TransformAPI
       transformUpdateModuleMember:
     TypeError: Cannot read property 'emitNode' of undefined
      at getOrCreateEmitNode (src/compiler/factory.ts:3336:19)
      at getOrCreateEmitNode (src/compiler/factory.ts:3346:17)
      at Object.setEmitFlags (src/compiler/factory.ts:3379:9)
      at visitParameter (src/compiler/transformers/ts.ts:2140:17)
      at visitTypeScript (src/compiler/transformers/ts.ts:500:28)
      at visitorWorker (src/compiler/transformers/ts.ts:209:24)
      at saveStateAndInvoke (src/compiler/transformers/ts.ts:139:29)
      at visitor (src/compiler/transformers/ts.ts:199:20)
      at visitNodes (src/compiler/visitor.ts:110:50)
      at Object.visitParameterList (src/compiler/visitor.ts:154:25)
      at visitFunctionDeclaration (src/compiler/transformers/ts.ts:2077:17)
      at visitTypeScript (src/compiler/transformers/ts.ts:481:28)
      at namespaceElementVisitorWorker (src/compiler/transformers/ts.ts:292:24)
```

See discussion in https://github.com/microsoft/TypeScript/pull/34513. This appears to be caused by a `setParentPointers` call in this stack:

```
    at setParentPointers (src/compiler/binder.ts:4253:21)
    at src/compiler/binder.ts:4254:43
    at visitNodes (src/compiler/parser.ts:41:32)
    at Object.forEachChild (src/compiler/parser.ts:273:24)
    at setParentPointers (src/compiler/binder.ts:4254:9)
    at Object.getModuleInstanceState (src/compiler/binder.ts:19:13)
    at Object.isInstantiatedModule (src/compiler/checker.ts:254:29)
    at shouldEmitModuleDeclaration (src/compiler/transformers/ts.ts:2456:20)
    at visitModuleDeclaration (src/compiler/transformers/ts.ts:2574:18)
    at visitTypeScript (src/compiler/transformers/ts.ts:538:28)
```

**Comment by vikene** [comment]
@RyanCavanaugh can I take this up and work on it ?

**Comment by RyanCavanaugh** [comment]
@vikene we have a tighter deadline on this one, so I'm going to have a TS engineer work on it. Thanks for offering, though!

**Comment by sparebytes** [comment]
I received a similar error while using a transformer with Typescript 3.7.2:
```
TypeError: Cannot read property 'emitNode' of undefined
    at getOrCreateEmitNode (C:\ginamic\api\node_modules\typescript\lib\typescript.js:69017:19)
    at getOrCreateEmitNode (C:\ginamic\api\node_modules\typescript\lib\typescript.js:69026:17)
    at Object.setEmitFlags (C:\ginamic\api\node_modules\typescript\lib\typescript.js:69057:9)
    at visitParameter (C:\ginamic\api\node_modules\typescript\lib\typescript.js:75010:20)
    at visitTypeScript (C:\ginamic\api\node_modules\typescript\lib\typescript.js:73684:28)
    at visitorWorker (C:\ginamic\api\node_modules\typescript\lib\typescript.js:73427:24)
    at saveStateAndInvoke (C:\ginamic\api\node_modules\typescript\lib\typescript.js:73365:27)
    at visitor (C:\ginamic\api\node_modules\typescript\lib\typescript.js:73418:20)
    at visitNodes (C:\ginamic\api\node_modules\typescript\lib\typescript.js:70955:48)
    at Object.visitParameterList (C:\ginamic\api\node_modules\typescript\lib\typescript.js:71001:23)
```

after digging deeper I narrowed it to this line:
```
getOrCreateEmitNode (c:\ginamic\api\node_modules\typescript\lib\typescript.js:69017)
getOrCreateEmitNode (c:\ginamic\api\node_modules\typescript\lib\typescript.js:69026)
setEmitFlags (c:\ginamic\api\node_modules\typescript\lib\typescript.js:69057)
visitParameter (c:\ginamic\api\node_modules\typescript\lib\typescript.js:75010)
visitTypeScript (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73684)
visitorWorker (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73427)
saveStateAndInvoke (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73365)
visitor (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73418)
visitNodes (c:\ginamic\api\node_modules\typescript\lib\typescript.js:70955)
visitParameterList (c:\ginamic\api\node_modules\typescript\lib\typescript.js:71001)
visitFunctionDeclaration (c:\ginamic\api\node_modules\typescript\lib\typescript.js:74971)
visitTypeScript (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73668)
namespaceElementVisitorWorker (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73505)
saveStateAndInvoke (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73365)
namespaceElementVisitor (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73488)
visitNodes (c:\ginamic\api\node_modules\typescript\lib\typescript.js:70955)
(anonymous function) (c:\ginamic\api\node_modules\typescript\lib\typescript.js:75408)
saveStateAndInvoke (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73365)
transformModuleBody (c:\ginamic\api\node_modules\typescript\lib\typescript.js:75408)
visitModuleDeclaration (c:\ginamic\api\node_modules\typescript\lib\typescript.js:75374)
visitTypeScript (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73712)
visitorWorker (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73427)
sourceElementVisitorWorker (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73452)
saveStateAndInvoke (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73365)
sourceElementVisitor (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73437)
visitNodes (c:\ginamic\api\node_modules\typescript\lib\typescript.js:70955)
visitLexicalEnvironment (c:\ginamic\api\node_modules\typescript\lib\typescript.js:70988)
visitSourceFile (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73725)
saveStateAndInvoke (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73365)
transformSourceFile (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73347)
transformSourceFileOrBundle (c:\ginamic\api\node_modules\typescript\lib\typescript.js:73327)
transformation (c:\ginamic\api\node_modules\typescript\lib\typescript.js:89262)
transformRoot (c:\ginamic\api\node_modules\typescript\lib\typescript.js:89282)
map (c:\ginamic\api\node_modules\typescript\lib\typescript.js:543)
transformNodes (c:\ginamic\api\node_modules\typescript\lib\typescript.js:89269)
emitJsFileOrBundle (c:\ginamic\api\node_modules\typescript\lib\typescript.js:89802)
emitSourceFileOrBundle (c:\ginamic\api\node_modules\typescript\lib\typescript.js:89755)
forEachEmittedFile (c:\ginamic\api\node_modules\typescript\lib\typescript.js:89508)
emitFiles (c:\ginamic\api\node_modules\typescript\lib\typescript.js:89736)
emitWorker (c:\ginamic\api\node_modules\typescript\lib\typescript.js:95755)
(anonymous function) (c:\ginamic\api\node_modules\typescript\lib\typescript.js:95716)
runWithCancellationToken (c:\ginamic\api\node_modules\typescript\lib\typescript.js:95807)
emit (c:\ginamic\api\node_modules\typescript\lib\typescript.js:95716)
newEmit (c:\ginamic\api\node_modules\ttypescript\lib\patchCreateProgram.js:70)
emitFilesAndReportErrors (c:\ginamic\api\node_modules\typescript\lib\typescript.js:99911)
emitFilesAndReportErrorsAndGetExitStatus (c:\ginamic\api\node_modules\typescript\lib\typescript.js:99933)
performCompilation (c:\ginamic\api\node_modules\typescript\lib\tsc.js:355)
executeCommandLineWorker (c:\ginamic\api\node_modules\typescript\lib\tsc.js:223)
executeCommandLine (c:\ginamic\api\node_modules\typescript\lib\tsc.js:263)
(anonymous function) (c:\ginamic\api\node_modules\typescript\lib\tsc.js:516)
(anonymous function) (c:\ginamic\api\node_modules\ttypescript\lib\tsc.js:17)
Module._compile (loader.js:953)
Module._extensions..js (loader.js:973)
Module.load (loader.js:812)
Module._load (loader.js:724)
Module.runMain (loader.js:1025)
(anonymous function) (run_main_module.js:17)
```
