### ISSUE TITLE
TS3.7 regression: crash checking JS assigning properties in array literal

### ISSUE THREAD

**Issue by mprobst** [microsoft/TypeScript#34642]
**TypeScript Version:**  3.7.0-beta

**Code**

```ts
function fun() {
  var arr = [];
  var mean = [
    arr[0].prop[0] = 1,
  ];
}
```

**Expected behavior:**

Pass.

**Actual behavior:**

Crash:

```
node_modules/typescript/lib/tsc.js:1808
            throw e;
            ^

Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isBindableStaticAccessExpression'.
    at Object.cast (node_modules/typescript/lib/tsc.js:1268:25)
    at bindSpecialPropertyAssignment (node_modules/typescript/lib/tsc.js:25709:53)
    at bindWorker (node_modules/typescript/lib/tsc.js:25329:29)
    at bind (node_modules/typescript/lib/tsc.js:25221:13)
    at bindEach (node_modules/typescript/lib/tsc.js:23997:21)
    at visitNodes (node_modules/typescript/lib/tsc.js:14079:24)
    at Object.forEachChild (node_modules/typescript/lib/tsc.js:14237:24)
    at bindEachChild (node_modules/typescript/lib/tsc.js:24005:16)
    at bindChildrenWorker (node_modules/typescript/lib/tsc.js:24102:21)
    at bindChildren (node_modules/typescript/lib/tsc.js:23975:17)
```

**Comment by mprobst** [comment]
(also repros in 3.8 nightly)

**Comment by sandersn** [comment]
Even smaller:

```js
var arr = [];
arr[0].prop[0] = 1;
```

**Comment by sandersn** [comment]
I think it's a mismatch between getAssignmentDeclarationKind, the initial classifier for assignments-as-declarations, and subsequent code. I think it is too-permissively classifying `arr[0].prop[0]` as a potential declaration.

**Comment by sandersn** [comment]
Yep. `getAssignmentDeclarationKind` proves that `arr[0].prop isBindableStaticAccessExpression` but `bindSpecialPropertyAssignment` assumes that `arr[0].prop[0] isBindableStaticAccessExpression` .
