### ISSUE TITLE
--allowJs (3.7.0 regression): Cannot reference `this` when extending imported function prototype

### ISSUE THREAD

**Issue by Knagis** [microsoft/TypeScript#34647]
**TypeScript Version:**  3.7.x-dev.20191021

**Search Terms:**
* Cannot set property 'symbol' of undefined

**Code**
Originally encountered when transpiling BabylonJS ES6 code (`@babylonjs/core/Animations/animatable.js`)

Minimum repro:

```ts
import { A } from "./a";

A.prototype.foo = function () {
    this.bar = 0;
};
```

**Expected behavior:**
Code is transpiled.

**Actual behavior:**

```
node_modules\typescript\lib\tsc.js:23641
            node.symbol = symbol;
                        ^

TypeError: Cannot set property 'symbol' of undefined
    at addDeclarationToSymbol (node_modules\typescript\lib\tsc.js:23641:25)
    at bindThisPropertyAssignment (node_modules\typescript\lib\tsc.js:25564:25)
    at bindWorker (node_modules\typescript\lib\tsc.js:25270:29)
    at bind (node_modules\typescript\lib\tsc.js:25165:13)
    at bindExpressionStatement (node_modules\typescript\lib\tsc.js:24496:13)
    at bindChildrenWorker (node_modules\typescript\lib\tsc.js:24002:21)
    at bindChildren (node_modules\typescript\lib\tsc.js:23923:17)
    at bind (node_modules\typescript\lib\tsc.js:25171:21)
    at node_modules\typescript\lib\tsc.js:23929:68
    at bindEach (node_modules\typescript\lib\tsc.js:23945:21)
error Command failed with exit code 1.
```

**Playground Link:** 

http://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=3&ssc=2&pln=1&pc=1#code/JYWwDg9gTgLgBAbzgQTgXzgMyhEcBEAdAPQCG+A3AFBXKFg4wQwCeYApoZhBHALxYArgDsAxjGARhcABQBKRFTjK4MABbAAzoQBGpKPzgAGamgpA (see errors in browser console)

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/34493

**Comment by Knagis** [comment]
@sandersn - you seem to be the person looking into the similar issues.

**Comment by Knagis** [comment]
Created a PR https://github.com/microsoft/TypeScript/pull/34650 with a fix that follows the same approach as https://github.com/microsoft/TypeScript/pull/34566.
