### ISSUE TITLE
Error: Debug Failure in format

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#34740]
**TypeScript Version:**  3.8.0-dev.20191025

**Search Terms:**
- format
- tsserver

**Code**
In VS Code, run format  on the following code:

```ts
function f<T>(...x: T){}

const a = ({
    a: f<
        Pick<any, 'allIds' | 'rowsById'>
    >(
        (acc, {}) => { return acc; }
    )
});

```

**Bug:**

```
[Trace  - 11:04:35 AM] <syntax> Response received: format (209). Request took 3 ms. Success: false . Message: Error processing request. Debug Failure.
Error: Debug Failure.
    at Object.assertDefined (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:2004:24)
    at Object.argumentStartsOnSameLineAsPreviousArgument (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:118833:48)
    at computeIndentation (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117841:55)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:118033:44)
    at processChildNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:118085:48)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117971:21
    at visitNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17608:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17795:21)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117968:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:118034:21)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117969:21
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17603:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17690:21)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117968:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:118034:21)
    at processChildNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:118085:48)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117971:21
    at visitNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17608:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17782:24)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117968:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:118034:21)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117969:21
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17603:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17806:24)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117968:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:118034:21)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117969:21
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17603:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17697:21)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117968:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:118034:21)
    at processChildNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:118085:48)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117971:21
    at visitNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17608:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17852:24)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117968:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:118034:21)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117969:21
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17603:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17850:21)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117968:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:118034:21)
    at processChildNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:118085:48)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117971:21
    at visitNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17608:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:17845:24)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117968:20)
    at formatSpanWorker (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117783:17)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117764:208
    at Object.getFormattingScanner (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:116414:23)
    at formatSpan (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117764:31)
    at Object.formatSelection (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:117582:20)
    at Object.getFormattingEditsForRange (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:130946:34)
    at IOSession.Session.getFormattingEditsForRange (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:140135:45)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:139175:61)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:140725:88
    at IOSession.Session.executeWithRequestId (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:140716:28)
    at IOSession.Session.executeCommand (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:140725:33)
    at IOSession.Session.onMessage (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:140748:35)
    at Interface.<anonymous> (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:142063:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by glasser** [comment]
Seeing something like this.

**Comment by elibarzilay** [comment]
@mjbvz I tried a few things, but couldn't reproduce it, can you verify that it still happens?

**Comment by RyanCavanaugh** [comment]
I can't repro either

**Comment by mjbvz** [comment]
Also can't repo in 3.8.0-dev.20200108

**Comment by RyanCavanaugh** [comment]
Assuming fixed then. Thanks for checking!
