### ISSUE TITLE
Max Call Stack Exceeded w/ recursive circular reference via property access

### ISSUE THREAD

**Issue by G-Rath** [microsoft/TypeScript#34744]
**TypeScript Version:**  3.8.0-dev.20191024

**Search Terms:**
Max call stack exceeded, getEffectiveTypeArguments, getTypeFromLiteralTypeNode
**Code**

```ts
type Mxs = Mx<'list', Mxs['p1']>;

interface Mx<T, K> {
  p1: T;
  p2: K;
}
```

**Expected behavior:**
~Ideally, it would work 😉 but if it won't,~ a circular reference error.

**Actual behavior:**
`RangeError: Maximum call stack size exceeded`

I've not included the stacktrace, b/c it changes depending on everything from the number of lines in the file to the property names.

**Playground Link:** https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191024#code/C4TwDgpgBAsgHgZygXlnAPAcgDYEsHCYA0aCA2pmAIyYC6AfANwCwAUG7gHbAQBOAZgEMAxtHjoAKiQDS9KAG82UKNQBcUCS1bKwAJnXStAXyA

**Related Issues:** 

#25379
#17049

**Comment by sandersn** [comment]
Regression in 3.7

**Comment by sandersn** [comment]
Here's a couple of times around the loop:

```
    at Object.getObjectFlags (/home/nathansa/ts/built/local/tsserver.js:14073:28)
    at isGenericMappedType (/home/nathansa/ts/built/local/tsserver.js:41205:26)
    at isStringIndexSignatureOnlyType (/home/nathansa/ts/built/local/tsserver.js:45640:57)
    at getIndexedAccessTypeOrUndefined (/home/nathansa/ts/built/local/tsserver.js:43871:17)
    at getIndexedAccessType (/home/nathansa/ts/built/local/tsserver.js:43862:20)
    at getTypeFromIndexedAccessTypeNode (/home/nathansa/ts/built/local/tsserver.js:43925:32)
    at getTypeFromTypeNode (/home/nathansa/ts/built/local/tsserver.js:44458:28)
    at Object.map (/home/nathansa/ts/built/local/tsserver.js:388:29)
    at getEffectiveTypeArguments (/home/nathansa/ts/built/local/tsserver.js:58669:48)
    at getTypeArguments (/home/nathansa/ts/built/local/tsserver.js:42472:109)
    at resolveTypeReferenceMembers (/home/nathansa/ts/built/local/tsserver.js:40612:33)
    at resolveStructuredTypeMembers (/home/nathansa/ts/built/local/tsserver.js:41211:25)
    at getPropertiesOfObjectType (/home/nathansa/ts/built/local/tsserver.js:41238:24)
    at getPropertiesOfType (/home/nathansa/ts/built/local/tsserver.js:41302:17)
    at isStringIndexSignatureOnlyType (/home/nathansa/ts/built/local/tsserver.js:45640:86)
    at getIndexedAccessTypeOrUndefined (/home/nathansa/ts/built/local/tsserver.js:43871:17)
    at getIndexedAccessType (/home/nathansa/ts/built/local/tsserver.js:43862:20)
    at getTypeFromIndexedAccessTypeNode (/home/nathansa/ts/built/local/tsserver.js:43925:32)
    at getTypeFromTypeNode (/home/nathansa/ts/built/local/tsserver.js:44458:28)
    at Object.map (/home/nathansa/ts/built/local/tsserver.js:388:29)
    at getEffectiveTypeArguments (/home/nathansa/ts/built/local/tsserver.js:58669:48)
    at getTypeArguments (/home/nathansa/ts/built/local/tsserver.js:42472:109)
    at resolveTypeReferenceMembers (/home/nathansa/ts/built/local/tsserver.js:40612:33)
    at resolveStructuredTypeMembers (/home/nathansa/ts/built/local/tsserver.js:41211:25)
    at getPropertiesOfObjectType (/home/nathansa/ts/built/local/tsserver.js:41238:24)
    at getPropertiesOfType (/home/nathansa/ts/built/local/tsserver.js:41302:17)
    at isStringIndexSignatureOnlyType (/home/nathansa/ts/built/local/tsserver.js:45640:86)
```
