### ISSUE TITLE
Error: Debug Failure. False expression.

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#34857]
tsserver throws a lot of errors this week.

**TypeScript Version:**  3.7.x-dev.20191031

**Search Terms:**

**Code**

```
[2019-11-01 06:57:26.025] [renderer1] [error] <semantic> TypeScript Server Error (3.8.0-dev.20191031)
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.computePositionOfLineAndCharacter (tsserver.js:7815:22)
    at TextStorage.lineOffsetToPosition (tsserver.js:133827:31)
    at ScriptInfo.lineOffsetToPosition (tsserver.js:134173:41)
    at IOSession.Session.getPosition (tsserver.js:140205:81)
    at IOSession.Session.getQuickInfoWorker (tsserver.js:140289:96)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:139324:61)
    at tsserver.js:140907:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140898:28)
    at IOSession.Session.executeCommand (tsserver.js:140907:33)
    at IOSession.Session.onMessage (tsserver.js:140930:35)
    at Interface.<anonymous> (tsserver.js:142245:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17): Error: <semantic> 
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
This is a distressingly normal call stack frame - any ideas on repro code?

**Comment by falsandtru** [comment]
This has filed to supplement the other related telemetry.
