### ISSUE TITLE
Find all references doesn't find all results and crashes tsserver if `type S = import().S` syntax is used

### ISSUE THREAD

**Issue by InExtremaRes** [microsoft/TypeScript#34908]
**TypeScript Version:**  3.8.0-dev.20191102, 3.7.1-rc1, 3.6.3

**Search Terms:** Find all references crash tsserver reexport

**Code**

[Reproduction repo](https://github.com/InExtremaRes/find-references-ts-bug/tree/bug1)

file1.ts
```ts
export class Foo {}
export class Bar {}
```

file2.ts
```ts
import * as f1 from './file1';

export class Container {
    readonly classes = f1;
}

declare const c: Container;
c.classes.Foo;

// Uncommenting this line make 'Find all references' work again
// export { f1 };
```

file3.ts
```ts
import { Container } from './file2';

declare const c: Container;
// 'Go to definition' works from here but 'Find all references' doesn't show this line
c.classes.Foo;
```

**Expected behavior:**
All three references to `Foo` are shown, in `file1.ts`, `file2.ts` and `file3.ts`.

**Actual behavior:**

Reference in `file3.ts` is not shown.

**Workaround?:**

Uncommenting `// export { f1 };` in `file2.ts` makes all references to be found, even if no other file import `f1`.

In the same repo, but [another branch](https://github.com/InExtremaRes/find-references-ts-bug/tree/bug2) it is shown that with a new file:

file4.ts
```ts
type S = import('./file3').S;
```

find all references on `Foo` crashes tsserver. Changing file4 to:

```ts
import { S } from './file3';
```

avoid the crash. The [tsserver.log](https://github.com/InExtremaRes/find-references-ts-bug/blob/bug2/tsserver.log) shows:

```plain
    {"seq":11,"type":"request","command":"references","arguments":{"file":"/tmp/find-references-ts-bug/file3.ts","line":5,"offset":12}}
Err 109   [19:9:26.28] Exception on executing command {"seq":11,"type":"request","command":"references","arguments":{"file":"/tmp/find-references-ts-bug/file3.ts","line":5,"offset":12}}:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at getSourceFileLikeForImportDeclaration (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:109406:22)
        at addIndirectUsers (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:108990:42)
        at addIndirectUsers (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:108990:25)
        at handleNamespaceImport (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:108964:25)
        at handleDirectImports (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:108929:37)
        at getImportersForExport (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:108878:13)
        at State.importTracker (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:108854:26)
        at State.getImportSearches (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:110199:33)
        at searchForImportsOfExport (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:110248:32)
        at getImportOrExportReferences (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:110672:21)
        at getReferencesAtLocation (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:110592:17)
        at getReferencesInContainer (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:110536:21)
        at getReferencesInContainerOrFiles (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:110095:21)
        at getReferencedSymbolsForSymbol (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:110086:21)
        at Object.getReferencedSymbolsForNode (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:109889:34)
        at Object.findReferencedSymbols (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:109567:60)
        at Proxy.findReferences (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:130935:41)
        at /tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:139099:68
        at callbackProjectAndLocation (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:139180:13)
        at /tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:139127:24
        at forEachProjectInProjects (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:139109:17)
        at combineProjectOutputWorker (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:139124:13)
        at combineProjectOutputForReferences (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:139080:13)
        at IOSession.Session.getReferences (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:140208:34)
        at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:139339:61)
        at /tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:140942:88
        at IOSession.Session.executeWithRequestId (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:140933:28)
        at IOSession.Session.executeCommand (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:140942:33)
        at IOSession.Session.onMessage (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:140965:35)
        at Interface.<anonymous> (/tmp/find-references-ts-bug/node_modules/typescript/lib/tsserver.js:142280:27)
        at Interface.emit (events.js:182:13)
        at Interface._onLine (readline.js:290:10)
        at Interface._normalWrite (readline.js:433:12)
        at Socket.ondata (readline.js:149:10)
        at Socket.emit (events.js:182:13)
        at addChunk (_stream_readable.js:283:12)
        at readableAddChunk (_stream_readable.js:264:11)
        at Socket.Readable.push (_stream_readable.js:219:10)
        at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

File text of /tmp/find-references-ts-bug/file3.ts:
    import { Container } from './file2';
    
    declare const c: Container;
    // 'Go to definition' works from here but 'Find all references' doesn't
    c.classes.Foo;
    
    export type S = {};
```
**Related Issues:** 

Maybe #28680

**Comment by InExtremaRes** [comment]
I tested this with TS 3.8.2 and the crash (the second part of the issue) doesn't happened (:confetti_ball:). I edited the issue message to hide that section.

However the first part still happened in TS 3.9.0-dev.20200223. The references are no properly found unless I uncomment the export. I've updated the dependencies of the reproduction repo (branch bug1) to prove this.
