### ISSUE TITLE
JS: Maximum call stack size exceeded at getTypeFromJSDocValueReference in 3.7.2

### ISSUE THREAD

**Issue by brendankenny** [microsoft/TypeScript#34926]
**TypeScript Version:**  3.7.2, 3.8.0-dev.20191105

**Search Terms:**
JSDoc Type reference Maximum call stack size exceeded getTypeFromJSDocValueReference

**Code**
Unfortunately I don't have a small case test case yet. The easiest steps I have so far:
- `git clone https://github.com/GoogleChrome/lighthouse.git`
- `cd lighthouse`
- `yarn`
- `yarn add -D typescript@3.7.2`
- `yarn tsc`

**Expected behavior:**
Complete `tsc` run

**Actual behavior:**
```
~/lighthouse/node_modules/typescript/lib/tsc.js:78629
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at getTypeFromJSDocValueReference (~/lighthouse/node_modules/typescript/lib/tsc.js:35334:48)
    at getTypeReferenceType (~/lighthouse/node_modules/typescript/lib/tsc.js:35323:33)
    at getTypeFromJSDocValueReference (~/lighthouse/node_modules/typescript/lib/tsc.js:35348:32)
    at getTypeReferenceType (~/lighthouse/node_modules/typescript/lib/tsc.js:35323:33)
    at getTypeFromJSDocValueReference (~/lighthouse/node_modules/typescript/lib/tsc.js:35348:32)
    at getTypeReferenceType (~/lighthouse/node_modules/typescript/lib/tsc.js:35323:33)
    at getTypeFromJSDocValueReference (~/lighthouse/node_modules/typescript/lib/tsc.js:35348:32)
    at getTypeReferenceType (~/lighthouse/node_modules/typescript/lib/tsc.js:35323:33)
    at getTypeFromJSDocValueReference (~/lighthouse/node_modules/typescript/lib/tsc.js:35348:32)
    at getTypeReferenceType (~/lighthouse/node_modules/typescript/lib/tsc.js:35323:33)
error Command failed with exit code 1.
```

In `3.7.1-rc` there were many of the `Property 'methodName' does not exist on type 'typeof ClassName'` errors that were being worked on in #34671, but it looks like the fix(es) struggles with something in our dependency graph and/or styles of declarations.

No issues or compilation errors using typescript@3.6.3 (though we're fine if there are new errors exposed by 3.7 that will need to be fixed in our code :)

**Related Issues:** 
This seems very related to the cluster of issues @sandersn was working on in #34671, #34707, #34685, and #34802

**Comment by ksmithut** [comment]
I was able to reproduce with this code:

```js
/**
 * @param {import('aws-sdk')} aws
 */
function test (aws) {}
```

Something in the typings in aws-sdk (and others I assume) is causing this

**Comment by voxpelli** [comment]
Experiencing similar, with slightly different callstack:

```
RangeError: Maximum call stack size exceeded
    at getSymbolLinks (/my-project/node_modules/typescript/lib/tsc.js:27740:32)
    at getTypeOfFuncClassEnumModule (/my-project/node_modules/typescript/lib/tsc.js:32593:25)
    at getTypeOfSymbol (/my-project/node_modules/typescript/lib/tsc.js:32702:24)
    at getTypeFromJSDocValueReference (/my-project/node_modules/typescript/lib/tsc.js:35295:29)
    at getTypeReferenceType (/my-project/node_modules/typescript/lib/tsc.js:35283:33)
    at getTypeFromJSDocValueReference (/my-project/node_modules/typescript/lib/tsc.js:35309:32)
    at getTypeReferenceType (/my-project/node_modules/typescript/lib/tsc.js:35283:33)
    at getTypeFromJSDocValueReference (/my-project/node_modules/typescript/lib/tsc.js:35309:32)
    at getTypeReferenceType (/my-project/node_modules/typescript/lib/tsc.js:35283:33)
    at getTypeFromJSDocValueReference (/my-project/node_modules/typescript/lib/tsc.js:35309:32)
```

**Comment by voxpelli** [comment]
Digging into the code, it seems to be related to the change made in #34683

More specifically the `node.kind === SyntaxKind.ImportType` check in https://github.com/microsoft/TypeScript/commit/8223c0752773ed6d4d42934adadd3d2cb15d5c3d, which seems to in some cases make `getTypeReferenceType()` and `getTypeFromJSDocValueReference()` call each other in at least a near circular way.

**Comment by sandersn** [comment]
@RyanCavanaugh let's take this one for 3.7.3 too. Sounds like it breaks lighthouse and aws-sdk.

**Comment by sandersn** [comment]
Here's a self-contained repro:

```js
/** @param {import('./ex')} a */
function test(a) { }
```

```ts
export var crash: {};
```

Notably, this does not crash:

```ts
declare var nocrash: {}
export = nocrash;
```

**Comment by sandersn** [comment]
My previous fix for import types was too eager. The jsdoc-value-as-type fallback is only needed for import types followed by qualified names.
