### ISSUE TITLE
ProjectService.updateNonInferredProjectFiles - Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#35001]
**TypeScript Version:**  3.8.0-dev-2019-11-05 and 3.7.2

**Search Terms:**
- Untitled file / buffer

**Repo**
(Tested on windows)

1. Open the VS Code repo. 
1. Have a single file `refactor.ts` open: https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/features/refactor.ts
1. Reload window to make sure you are in a clean state
1. Wait for TS to finish loading in `refactor.ts`
1. Now create an untitled file (ctrl+n)
1. Change the language mode of the new file to `Typescript` (without saving it)

**Bug**

```
Cannot read property 'path' of undefined
TypeError: Cannot read property 'path' of undefined
    at ProjectService.updateNonInferredProjectFiles (tsserver.js:137488:43)
    at ProjectService.addFilesToNonInferredProject (tsserver.js:137378:22)
    at ProjectService.updateRootAndOptionsOfNonInferredProject (tsserver.js:137526:22)
    at ProjectService.loadConfiguredProject (tsserver.js:137462:22)
    at ProjectService.createAndLoadConfiguredProject (tsserver.js:137402:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (tsserver.js:137407:36)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:138230:44)
    at tsserver.js:138461:107
    at Object.mapDefined (tsserver.js:565:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:138461:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139315:46)
    at tsserver.js:140973:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140964:28)
    at IOSession.Session.executeCommand (tsserver.js:140973:33)
    at IOSession.Session.onMessage (tsserver.js:140996:35)
    at Interface.<anonymous> (tsserver.js:142311:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
```

This seems to be caused by the line https://github.com/microsoft/TypeScript/blob/35a6426a79176f047a93f69f76e8b9410cf16654/src/server/editorServices.ts#L1854

**related issues**
- #18217

/cc @sheetalkamat

**Comment by mjbvz** [comment]
@RyanCavanaugh Candidate for 3.7.3.

VS Code now treats errors that happen during `updateOpen` as non-recoverable, which means we restart the server in this case

**Comment by sheetalkamat** [comment]
@mjbvz I don't seem to be able to repro ([tsserver.log](https://github.com/microsoft/TypeScript/files/3832468/tsserver.log)) with insiders and 3.7.2 or with 3.8 and vscode ([tsserver.log](https://github.com/microsoft/TypeScript/files/3832476/tsserver.log))

**Comment by mjbvz** [comment]
This is triggered by the tslint extension. A pr came in that changes the working directory using `process.chdir` (https://github.com/microsoft/typescript-tslint-plugin/pull/39)


When the new file is created, TS Server then ends calling `fileExists('tsconfig.json')` as part of `getConfigFileNameForFile`. Normally this normally returns false but now it returns true since the working directory is different (the default working directory for me is `"/Users/matb"`).However in the error case, the working directory is now `"/Users/matb/projects/vscode/extensions/typescript-language-features"`

This likely has been happening silently for a while but the new strictness I added means that we now restart the server in this case. I'll look into a fix on the TSlint side.

@sheetalkamat I don't understand why `fileExists('tsconfig.json')` is called in the first place. It seems like in this case, we always want it to return `false`?

**Comment by sheetalkamat** [comment]
@mjbvz We need to get the config file for the file being opened, so its walking up the directories to find it...

**Comment by mjbvz** [comment]
But why do we check the relative path `tsconfig.json`?  For on disk files, all calls to this function I saw seem to check absolute paths. For in memory files, do we want to put them into a real tsconfig if possible, meaning their config should be resolved relative to the workspace root?
