### ISSUE TITLE
tsc crash for TypeScript 1.5

### ISSUE THREAD

**Issue by img** [Microsoft/TypeScript#3504]
Hi. this (ill-formed) source file crashes tsc 1.5.0-beta

    class VariableDeclarations {
      public {[name:string]:VariableDeclaration};
    }

$ tsc t.ts
here's the o/p:

    /usr/local/lib/node_modules/typescript/bin/tsc.js:654
		    throw new Error("Debug Failure. False expression: " + (message
			  ^
    Error: Debug Failure. False expression: Should not have attempted to parse class member declaration.
	at Object.assert (/usr/local/lib/node_modules/typescript/bin/tsc.js:654:23)
	at Object.fail (/usr/local/lib/node_modules/typescript/bin/tsc.js:659:19)
	at parseClassElement (/usr/local/lib/node_modules/typescript/bin/tsc.js:7674:22)
	at parseListElement (/usr/local/lib/node_modules/typescript/bin/tsc.js:5646:20)
	at parseList (/usr/local/lib/node_modules/typescript/bin/tsc.js:5612:35)
	at parseClassMembers (/usr/local/lib/node_modules/typescript/bin/tsc.js:7741:20)
	at parseClassDeclarationOrExpression (/usr/local/lib/node_modules/typescript/bin/tsc.js:7695:23)
	at parseClassDeclaration (/usr/local/lib/node_modules/typescript/bin/tsc.js:7680:20)
	at parseDeclaration (/usr/local/lib/node_modules/typescript/bin/tsc.js:8053:28)
	at parseSourceElementOrModuleElement (/usr/local/lib/node_modules/typescript/bin/tsc.js:8086:19)

**Comment by DanielRosenwasser** [comment]
Note this occurs for the minimal object binding pattern with an accessibility modifier:

```TypeScript
class C { 
    public {};
}
```

It does not work for an array binding pattern because that is viewed as an index signature.
