### ISSUE TITLE
Cannot re-export global symbol - circular definition of import alias

### ISSUE THREAD

**Issue by mprobst** [Microsoft/TypeScript#3514]
Assuming these two files:

`a.d.ts`:

```ts
declare class X {}
```

`b.ts`:

```
/// <reference path="a.d.ts"/>
export {X};
```

Gives this error:

```
b.ts (2,9): Circular definition of import alias 'X'.
```

The use case for this is moving from internal modules to external modules by re-exporting symbols.

/cc @mhegazy & @rbuckton

**Comment by JsonFreeman** [comment]
Just an update. I have been thinking about this for a day or so, and it raises an interesting language design question that we have not considered before. I was trying to make a decision on that, but I am leaning towards opening a separate issue for it, and trying to fix this bug without changing the current design yet.

**Comment by mhegazy** [comment]
@mprobst can you give this a try, and see if you are still running into issues.

**Comment by mprobst** [comment]
@mhegazy @JsonFreeman confirmed, this fixes our issue.

**Comment by mprobst** [comment]
Declaring success here might have been premature. With the latest LKG from `release-1.5` I get this stack trace:

```
~/src/angular (master)> gulp build.js.cjs
Dart SDK detected
[21:59:08] Using gulpfile ~/src/angular/gulpfile.js
[21:59:08] Starting 'build/clean.tools'...
[21:59:08] Finished 'build/clean.tools' after 4.03 ms
[21:59:08] Starting 'build.tools'...
[21:59:08] Starting '!build.tools'...
[21:59:12] Finished '!build.tools' after 3.87 s
[21:59:12] Finished 'build.tools' after 3.87 s
[21:59:12] Starting 'build.js.cjs'...
[21:59:12] Starting '!build.js.cjs'...
[21:59:24] '!build.js.cjs' errored after 12 s
[21:59:24] Error: [DiffingTSCompiler]: Debug Failure. False expression: isDeclarationVisible unknown: SyntaxKind: 218
    at Object.assert (/Users/martinprobst/src/angular/node_modules/typescript/bin/typescript.js:1418:23)
    at Object.fail (/Users/martinprobst/src/angular/node_modules/typescript/bin/typescript.js:1423:19)
    at determineIfDeclarationIsVisible (/Users/martinprobst/src/angular/node_modules/typescript/bin/typescript.js:12614:34)
    at isDeclarationVisible (/Users/martinprobst/src/angular/node_modules/typescript/bin/typescript.js:12620:41)
    at getIsDeclarationVisible (/Users/martinprobst/src/angular/node_modules/typescript/bin/typescript.js:11969:22)
    at /Users/martinprobst/src/angular/node_modules/typescript/bin/typescript.js:11964:82
    at Object.forEach (/Users/martinprobst/src/angular/node_modules/typescript/bin/typescript.js:748:30)
    at hasVisibleDeclarations (/Users/martinprobst/src/angular/node_modules/typescript/bin/typescript.js:11964:20)
    at Object.isSymbolAccessible (/Users/martinprobst/src/angular/node_modules/typescript/bin/typescript.js:11904:57)
    at Object.trackSymbol (/Users/martinprobst/src/angular/node_modules/typescript/bin/typescript.js:23053:53)
[21:59:24] 'build.js.cjs' errored after 12 s
[21:59:24] Error: build sequence failed
```

Repro:
* check out https://github.com/angular/angular/pull/2715
* npm install
* gulp build.js.cjs

I haven't worked on the branch in a while, so I'm not sure when this happened, and I only confirmed with a synthetic example (mea culpa).

**Comment by JsonFreeman** [comment]
I think we just have a non-exhaustive switch because when we added syntax kinds, we didn't know to update this function. I'm surprised that doesn't happen more often, as our language has no way of catching such things.

**Comment by mhegazy** [comment]
Sorry for the delay. this looks like a different issue. I have logged issue #3640 to track it.

**Comment by mhegazy** [comment]
@mprobst can you give PR #3641 a try.
