### ISSUE TITLE
TypeScript language service crashes because of wrong setting in tsconfig.json

### ISSUE THREAD

**Issue by drzamich** [microsoft/TypeScript#35171]
*TS template added by @mjbvz*

**Confirmed TypeScript version**: 3.8.0-dev-20191116

**Search terms**:
- debug failure
- crash 

---

- VSCode Version: 1.40.1
- OS Version: macOS Mojave 10.14.6

While working on my TypeScript project I wanted to define something in `baseUrl` and `paths` fields of `compilerOptions` in `tsconfig.json` to avoid `../../../` hell. I did it for the first time so I did not do it correctly. Here's what I added:

```
    "baseUrl": "./src",               
    "paths": {
      "@interface/**/*" : ["./src/interface/*"],
      "@service/**/*": ["./src/service/**/*"],
      "@controller/**/*": ["./src/controller/**/*"],
    },  
```

after I did that, the built-in TypeScript language service crashed and did not want to start under no circumstances. It only started working again when I removed the new code from `tsconfig.json`

Steps to Reproduce:

1. Clone the drzamich/bot.ts@b4c97fb765be8e76cf6d6d8bb7a648e319545df8
2. Open the cloned project in VSCode and watch the TypeScript language service crash

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Call stack of crash:

```
 Exception on executing command {"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"/Users/matb/projects/san/bot.ts/src/controller/index.ts","fileContent":"import { ScrapeContoller } from './ScrapeController';\n\nexport {\n  ScrapeContoller,\n};\n","projectRootPath":"/Users/matb/projects/san/bot.ts","scriptKindName":"TS"}]}}:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at tryParsePattern (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:17326:18)
        at Object.matchPatternOrExact (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:17383:27)
        at tryLoadModuleUsingPaths (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:28738:33)
        at tryLoadModuleUsingPathsIfEligible (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:28245:20)
        at tryLoadModuleUsingOptionalResolutionSettings (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:28228:24)
        at tryResolve (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:28373:28)
        at /Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:28365:69
        at Object.forEach (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:170:30)
        at nodeModuleNameResolverWorker (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:28365:25)
        at nodeModuleNameResolver (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:28358:16)
        at Object.resolveModuleName (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:28132:30)
        at resolveModuleName (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:98842:36)
        at resolveNamesWithLocalCache (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:98894:38)
        at Object.resolveModuleNames (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:98944:20)
        at ConfiguredProject.Project.resolveModuleNames (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:134683:45)
        at Object.compilerHost.resolveModuleNames (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:130675:52)
        at resolveModuleNamesWorker (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:94958:127)
        at resolveModuleNamesReusingOldState (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:95230:24)
        at processImportedModules (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:96656:35)
        at findSourceFile (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:96405:17)
        at /Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:96239:85
        at getSourceFileFromReferenceWorker (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:96206:34)
        at processSourceFile (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:96239:13)
        at processRootFile (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:96062:13)
        at /Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:95054:60
        at Object.forEach (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:170:30)
        at Object.createProgram (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:95054:16)
        at synchronizeHostData (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:130701:26)
        at Proxy.getProgram (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:130793:13)
        at ConfiguredProject.Project.updateGraphWorker (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:135144:53)
        at ConfiguredProject.Project.updateGraph (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:135087:42)
        at ConfiguredProject.updateGraph (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:135924:63)
        at ProjectService.createLoadAndUpdateConfiguredProject (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:137417:25)
        at ProjectService.assignProjectToOpenedScriptInfo (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:138241:44)
        at /Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:138472:107
        at Object.mapDefined (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:565:30)
        at ProjectService.applyChangesInOpenFiles (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:138472:48)
        at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:139326:46)
        at /Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:140984:88
        at IOSession.Session.executeWithRequestId (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:140975:28)
        at IOSession.Session.executeCommand (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:140984:33)
        at IOSession.Session.onMessage (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:141007:35)
        at Interface.<anonymous> (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191116/node_modules/typescript/lib/tsserver.js:142322:27)
        at Interface.emit (events.js:200:13)
        at Interface._onLine (readline.js:314:10)
        at Interface._normalWrite (readline.js:459:12)
        at Socket.ondata (readline.js:170:10)
        at Socket.emit (events.js:200:13)
        at addChunk (_stream_readable.js:294:12)
        at readableAddChunk (_stream_readable.js:275:11)
        at Socket.Readable.push (_stream_readable.js:210:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

/cc @RyanCavanaugh @sheetalkamat This is a potential candidate for a 3.7 recovery . I don't expect users to hit this error that often but when they do it completely breaks VS Code's JS/TS support

**Comment by fatcerberus** [comment]
In my experience you don't need to do `@alias/**/*` - `@alias/*` is enough.

But quick heads up: tsc emits import specifiers verbatim so unless the `@` aliases are recognized at runtime, `paths` won't save you from `../../../` hell.
