### ISSUE TITLE
charCount of undefined error in LineNode.walk causing invalid errors in editor

### ISSUE THREAD

**Issue by joefiorini** [microsoft/TypeScript#35194]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
- charCount
- Cannot read property 'charCount' of undefined

**Expected behavior:**

Reliable responses from tsserver

**Actual behavior:**

tsserver returns errors that aren't accurate. Sometimes the errors use mangled versions of my identifiers (I have an identifier `addresses` and got an incorrect type error for `addresseses` on the same line). I do see an exception in tsserver:

```
[Trace  - 9:54:40 AM] Sending request: navtree (205). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/src/the-pill-club/web-infrastructure-2/sites/dashboard/src/account-renew/index.tsx"
}
[Trace  - 9:54:40 AM] Response received: navtree (205). Request took 1 ms. Success: false . Message: Error processing request. Cannot read property 'charCount' of undefined
TypeError: Cannot read property 'charCount' of undefined
    at LineNode.walk (/src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:141571:68)
    at LineIndex.edit (/src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:141452:31)
    at ScriptVersionCache._getSnapshot (/src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:141242:47)
    at ScriptVersionCache.getSnapshot (/src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:141235:82)
    at TextStorage.getSnapshot (/src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:133768:32)
    at ScriptInfo.getSnapshot (/src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:133928:41)
    at ConfiguredProject.Project.getScriptSnapshot (/src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:134542:39)
    at SyntaxTreeCache.getCurrentSourceFile (/src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:130325:44)
    at Object.getNavigationTree (/src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:130952:71)
    at IOSession.Session.getNavigationTree (/src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:140539:44)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:139433:61)
    at /src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:140870:88
    at IOSession.Session.executeWithRequestId (/src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:140861:28)
    at IOSession.Session.executeCommand (/src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:140870:33)
    at IOSession.Session.onMessage (/src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:140893:35)
    at Interface.<anonymous> (/src/the-pill-club/web-infrastructure-2/node_modules/typescript/lib/tsserver.js:142208:27)
    at Interface.emit (events.js:193:13)
    at Interface._onLine (readline.js:308:10)
    at Interface._normalWrite (readline.js:449:12)
    at Socket.ondata (readline.js:165:10)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:150:17)
[Trace  - 9:54:43 AM] Event received: projectsUpdatedInBackground (0).
Data: {
    "openFiles": [
        "/src/the-pill-club/web-infrastructure-2/sites/dashboard/src/components/Greeting.tsx",
        "/src/the-pill-club/web-infrastructure-2/sites/dashboard/src/account-renew/index.tsx"
    ]
}
[Trace  - 9:54:44 AM] Sending request: geterr (206). Response expected: yes. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "/src/the-pill-club/web-infrastructure-2/sites/dashboard/src/components/Greeting.tsx",
        "/src/the-pill-club/web-infrastructure-2/sites/dashboard/src/account-renew/index.tsx"
    ]
}
[Trace  - 9:54:44 AM] Event received: syntaxDiag (0).
Data: {
    "file": "/src/the-pill-club/web-infrastructure-2/sites/dashboard/src/components/Greeting.tsx",
    "diagnostics": []
}
[Trace  - 9:54:44 AM] Event received: semanticDiag (0).
Data: {
    "file": "/src/the-pill-club/web-infrastructure-2/sites/dashboard/src/components/Greeting.tsx",
    "diagnostics": []
}
```

I notice it is returning an empty diagnostics list after this, is it possible the exception is a red herring and coc-tsserver is not responding properly in this case?

**Playground Link:** 

**Related Issues:** 

This issue has come up before. #21818, #16456, #20799.

**Comment by sheetalkamat** [comment]
Can you please share tsserver log when the error reproduces for us to be able to investigate this.
Is there sample code and edits that follow that cause this.

You can upload logs by following these steps:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. In vscode or vscode insiders, run the `TypeScript: Open TS Server log` command
5. This should open a large file called `tsserver.log`. Please share this file. Additionally you can also share file `ti.log` created next to it.
