### ISSUE TITLE
--allowJs: Object.defineProperty on imported alias crashes compiler

### ISSUE THREAD

**Issue by Knagis** [microsoft/TypeScript#35196]
**TypeScript Version:**  3.7.2, 3.8.0-dev-20191119, master

**Search Terms:**  bindObjectDefinePrototypeProperty

**Code**

```ts
import A from "./a";

Object.defineProperty(A.prototype, "foo", {
    value: 0
});
```

**Expected behavior:**
Code transpiles without errors.

**Actual behavior:**
```
TypeError: Cannot set property 'symbol' of undefined
    at addDeclarationToSymbol (node_modules\typescript\lib\tsc.js:23649:25)
    at bindObjectDefinePrototypeProperty (node_modules\typescript\lib\tsc.js:25640:17)
    at bindWorker (node_modules\typescript\lib\tsc.js:25370:36)
    at bind (node_modules\typescript\lib\tsc.js:25179:13)
    at bindExpressionStatement (node_modules\typescript\lib\tsc.js:24503:13)
    at bindChildrenWorker (node_modules\typescript\lib\tsc.js:24010:21)
    at bindChildren (node_modules\typescript\lib\tsc.js:23931:17)
    at bind (node_modules\typescript\lib\tsc.js:25185:21)
    at node_modules\typescript\lib\tsc.js:23937:68
    at bindEach (node_modules\typescript\lib\tsc.js:23953:21)
```

**Playground Link:** 
http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=5&pc=4#code/JYWwDg9gTgLgBAQTgMyhEcBEA6A9AQ0wG4AoEgeQCMArAUwGMZsATW5YAO1oAU0xbYATwAUCbGDQwIMQfwA0WZBAiYFAbxJwtcAG74ANgFdaALjgAGEgF8AlESA

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/34647
https://github.com/microsoft/TypeScript/issues/34493

**Comment by Knagis** [comment]
@sandersn - pinging you since you handled the related issues. The linked PR follows the same approach as the previous two.

**Comment by Knagis** [comment]
Any chance this could also be added to 3.7.3?

**Comment by sandersn** [comment]
It's a simple fix for a crash, so I think it's a good fit for 3.7.3.
