### ISSUE TITLE
RangeError: Maximum call stack size exceeded (with await nested promises)

### ISSUE THREAD

**Issue by kzok** [microsoft/TypeScript#35289]
**TypeScript Version:** 3.8.0-dev.20191122

**Code**

- source code
```ts
interface PromiseAction extends Promise<Action> {}
type Action = {type: string} | PromiseAction;
const createFooAction = async (): Promise<Action> => {type: "foo"};
```
- tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es2017",
    "allowSyntheticDefaultImports": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strictNullChecks": true,
  },
  "include": ["src/**/*"]
}
```

**Expected behavior:**

succeed type check or raise some error

**Actual behavior:**

tsc crashes with `RangeError: Maximum call stack size exceeded`

```
$ npm run check

> @ check /Users/okamoto-k/sandbox
> tsc --noEmit

/Users/okamoto-k/sandbox/node_modules/typescript/lib/tsc.js:78686
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at getPromisedTypeOfPromise (/Users/okamoto-k/sandbox/node_modules/typescript/lib/tsc.js:49700:42)
    at getAwaitedType (/Users/okamoto-k/sandbox/node_modules/typescript/lib/tsc.js:49758:32)
    at getAwaitedType (/Users/okamoto-k/sandbox/node_modules/typescript/lib/tsc.js:49751:46)
    at getAwaitedType (/Users/okamoto-k/sandbox/node_modules/typescript/lib/tsc.js:49767:35)
    at getAwaitedType (/Users/okamoto-k/sandbox/node_modules/typescript/lib/tsc.js:49751:46)
    at getAwaitedType (/Users/okamoto-k/sandbox/node_modules/typescript/lib/tsc.js:49767:35)
    at getAwaitedType (/Users/okamoto-k/sandbox/node_modules/typescript/lib/tsc.js:49751:46)
    at getAwaitedType (/Users/okamoto-k/sandbox/node_modules/typescript/lib/tsc.js:49767:35)
    at getAwaitedType (/Users/okamoto-k/sandbox/node_modules/typescript/lib/tsc.js:49751:46)
    at getAwaitedType (/Users/okamoto-k/sandbox/node_modules/typescript/lib/tsc.js:49767:35)

```

**Playground Link:** 
http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgApQPYFtgGcICCCYwGIyEAHpCACa5qY74A8RJZAfMgN4C+AKDABPAA4p2pcgF5eI8QC5kuMFFABzPsgA+jbHkLEpAbgEIyK5AigQ4kAGIYMkssllxcwkAmQAKAJRK6PqsLiDc0tw8yPIQSgBEME7xyHymQA

**Related Issues:** 

I couldn't find it.

**Comment by enisdenjo** [comment]
You made an infinite type loop with your definition:
```ts
interface PromiseAction extends Promise<Action> {}
type Action = {type: string} | PromiseAction;
```
`PromiseAction` needs the `Action`, while the `Action` needs the `PromiseAction`.

**Comment by jcalz** [comment]
Search terms: promise, recursive, crash, async ?

> You made an infinite type loop

Yes, but the compiler shouldn't crash as a result.  And recursive types are generally acceptable depending on the form such recursion takes.  This one looks harmless enough.  

I guess the problem is with how `async` functions are evaluated by the compiler.

```ts
type Action = { type: string } | Promise<Action>; // okay TS3.7
function acceptAction(action: Action) { } 
acceptAction({ type: "" }); // okay
acceptAction(new Promise(res => res({ type: "" }))); // okay
acceptAction(Promise.resolve(Promise.resolve(Promise.resolve({ type: "" })))); // okay

function f(): Promise<Action> { return Promise.resolve({ type: "" }) }; // okay
async function g(): Promise<Action> { return Promise.resolve({ type: "" }) }; // kablooey
```

**Comment by RyanCavanaugh** [comment]
We now get an error
```
error TS1062: Type is referenced directly or indirectly in the fulfillment callback of its own 'then' method.
```
