### ISSUE TITLE
INTERNAL error : Debug Failure. False expression: Containing file should be a module.

### ISSUE THREAD

**Issue by bdely** [microsoft/TypeScript#35528]
I am getting the following error in version `3.6.3`, `3.7.3` and `3.8.0-dev.20191205` on my system and our build system. I also downgraded to version `3.1.1` and also get same error.

Not sure why I started getting this error yesterday and none of the npm packages have changed in the last few weeks. Where would be the best place to look to fix this.

```
EXEC : INTERNAL error : Debug Failure. False expression: Containing file should be a module.
  stack trace:
EXEC : error : Debug Failure. False expression: Containing file should be a module.
      at checkImportMetaProperty (C:\App\node_modules\typescript\lib\typescript.js:56389:22)
      at checkMetaProperty (C:\App\node_modules\typescript\lib\typescript.js:56364:24)
      at checkExpressionWorker (C:\App\node_modules\typescript\lib\typescript.js:58452:28)
      at checkExpression (C:\App\node_modules\typescript\lib\typescript.js:58344:38)
      at checkExpressionStatement (C:\App\node_modules\typescript\lib\typescript.js:60719:13)
      at checkSourceElementWorker (C:\App\node_modules\typescript\lib\typescript.js:63129:28)
      at checkSourceElement (C:\App\node_modules\typescript\lib\typescript.js:63012:17)
      at Object.forEach (C:\App\node_modules\typescript\lib\typescript.js:304:30)
      at checkSourceFileWorker (C:\App\node_modules\typescript\lib\typescript.js:63333:20)
      at checkSourceFile (C:\App\node_modules\typescript\lib\typescript.js:63302:13)[39m[22m
```

**Comment by bdely** [comment]
I am going to close this issue because the error is caused by type definitions generated from Thrift
