### ISSUE TITLE
[3.7.3] TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#35717]
**TypeScript Version:**  3.7.3

**Code**

```ts
export class Foo extends Bar {
  global on
}
```

**Expected behavior:**

TypeScript should give a type or syntax error 

**Actual behavior:**

tsc crashes with the runtime TypeError.

**Playground Link:**

[playground](http://www.typescriptlang.org/play/?ssl=3&ssc=2&pln=1&pc=1#code/KYDwDg9gTgLgBAYwDYEMDOa4DEITqGYAOwBNMAhFKOAbwCg44BzJCAIxSTgiLoF8gA)

See the console, and try writing anything after the `global on` to trigger the error.

If you delete the word `on`, then there's no more error.

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
Full stack traces are super helpful

```
TypeError: Cannot read property 'kind' of undefined
    at transformModuleBody (tsc.js:62998:22)
    at visitModuleDeclaration (tsc.js:62974:231)
    at visitTypeScript (tsc.js:61960:28)
    at visitorWorker (tsc.js:61779:24)
    at sourceElementVisitorWorker (tsc.js:61794:28)
    at saveStateAndInvoke (tsc.js:61738:27)
    at sourceElementVisitor (tsc.js:61784:20)
    at visitNodes (tsc.js:59694:48)
    at Object.visitLexicalEnvironment (tsc.js:59722:22)
    at visitSourceFile (tsc.js:61971:53)
    at saveStateAndInvoke (tsc.js:61738:27)
    at transformSourceFile (tsc.js:61727:27)
    at transformSourceFileOrBundle (tsc.js:61712:20)
    at transformation (tsc.js:72730:24)
    at transformRoot (tsc.js:72747:82)
    at Object.map (tsc.js:337:29)
    at Object.transformNodes (tsc.js:72735:30)
    at emitJsFileOrBundle (tsc.js:73187:32)
    at emitSourceFileOrBundle (tsc.js:73143:13)
    at forEachEmittedFile (tsc.js:72910:34)
    at Object.emitFiles (tsc.js:73124:9)
    at emitWorker (tsc.js:78539:33)
    at tsc.js:78511:66
    at runWithCancellationToken (tsc.js:78587:24)
    at Object.emit (tsc.js:78511:20)
    at emitFilesAndReportErrors (tsc.js:82109:23)
    at Object.emitFilesAndReportErrorsAndGetExitStatus (tsc.js:82131:18)
    at performCompilation (tsc.js:84497:29)
    at executeCommandLineWorker (tsc.js:84384:17)
    at Object.executeCommandLine (tsc.js:84405:13)
    at Object.<anonymous> (tsc.js:84658:4)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by sandersn** [comment]
This parses as ModuleDeclaration `global` followed by ExpressionStatement `on`, as if you had written:

```ts
[declare] global [{ 
}]
on;
```

except of course neither `declare` nor the body are present.

I'm pretty sure the fix is just to handle ModuleStatements with no body in transformModuleBody or visitModuleDeclaration.
