### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mosharsky** [microsoft/TypeScript#35804]
**TypeScript Version:**  3.6.3, 3.7.2, 3.8.0-dev.20191220

**Code**
```ts
interface ITreeItem {    
    Parent?: this;    
    Expanded?: boolean;
}

type NodeWithId = ITreeItem & { Id?: number };

interface INode extends ITreeItem {
    Title: string;
}

function getMaxId(items: NodeWithId[]): number {
    return items[0].Id || 0;
}

const nodes = [] as INode[];
getMaxId(nodes);

**Comment by RyanCavanaugh** [comment]
```
RangeError: Maximum call stack size exceeded
    at C:\Users\Ryan\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:40694:106
    at step (C:\Users\Ryan\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:58:23)
    at Object.next (C:\Users\Ryan\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:39:53)
    at getUnmatchedProperty (C:\Users\Ryan\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:40725:121)
    at propertiesRelatedTo (C:\Users\Ryan\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:39395:41)
    at isRelatedTo (C:\Users\Ryan\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:38492:34)
    at isPropertySymbolTypeRelated (C:\Users\Ryan\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:39335:28)
    at propertyRelatedTo (C:\Users\Ryan\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:39375:31)
    at propertiesRelatedTo (C:\Users\Ryan\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:39479:43)
    at isRelatedTo (C:\Users\Ryan\AppData\Roaming\npm\node_modules\typescript
```

**Comment by Manu1400** [comment]
Reduce testcase:

```tsx
interface ITreeItem {    
    Parent?: this;
}

type NodeWithId = ITreeItem & { Id?: number };

function getMaxId(items: NodeWithId[]) {
}

const nodes = [] as ITreeItem[];
getMaxId(nodes);
```
