### ISSUE TITLE
emitDecoratorMetadata issues with Server-side rendering and Typeorm

### ISSUE THREAD

**Issue by hanusaj** [microsoft/TypeScript#36162]
**TypeScript Version:**  ^3.5.3

**Search Terms:** emitDecoratorMetadata, server-side rendering, React

**Scenario:**

After setting `emitDecoratorMetadata: true` in the `tsconfig.json`, our server-side code ran into the error defined below. We believe this is due to Node not having `KeyboardEvent` defined. However, this bug is directly resulting from the `emitDecoratorMetadata` flag so it seems to be a Typescript error.

**Code:**

```
// typescript code
handleEscape(e: KeyboardEvent) {
    if (this.doShow) {
        e.stopPropagation();
        e.preventDefault();
        this.forceClose();
    }
}

// javascript where error occurred after webpack
tslib_1.__decorate([
    mobx_1.action,
    tslib_1.__metadata("design:type", Function),
    tslib_1.__metadata("design:paramtypes", [KeyboardEvent]),
    tslib_1.__metadata("design:returntype", void 0)
], AssistantStore.prototype, "handleEscape", null);
```

**Expected behavior:**

We expected to be able to build our typescript code server-side with the emitDecoratorMetadata flag in the tsconfig.json set to true.

**Actual behavior:**

```
ReferenceError: KeyboardEvent is not defined
    at /Users/ajhanus/Documents/calchub2/code/.dist/math/pretty-math/src/assistant/AssistantStore.js:159:50
    at Object.<anonymous> (/Users/ajhanus/Documents/calchub2/code/.dist/math/pretty-math/src/assistant/AssistantStore.js:193:2)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ajhanus/Documents/calchub2/code/.dist/math/pretty-math/index.js:32:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ajhanus/Documents/calchub2/code/.dist/math/library/LibraryEntry.js:5:21)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ajhanus/Documents/calchub2/code/.dist/math/library/index.js:4:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
```

**Related Issues:**

**Comment by MartinJohns** [comment]
I don't think TypeScript is doing anything wrong here. You ask the compiler to emit the type data, and it does so.

It's also unclear what you expect to happen. Should TypeScript remove the questionable types? If so, how should it know what types should be removed? You have the DOM-library referenced, otherwise `KeyboardEvent` would not be usable in TypeScript, and use that library for server side code that has no DOM available.

IMO you're doing something wrong, because you use types in your code that are not available in your target environment.
