### ISSUE TITLE
TypeScript Server crashes when unable to read source files

### ISSUE THREAD

**Issue by mattilu** [microsoft/TypeScript#36236]
Issue Type: <b>Bug</b>

### Steps to reproduce:

```sh
echo "export const FOO = 1;" > foo.ts
echo "import {FOO} from './foo';" > bar.ts
chmod -r foo.ts
code . bar.ts
```

### Observed behavior

"The TypeScript language service died 5 times right after it got started. The service will not be restarted."

### Expected behavior

TS code completion works in "degraded mode", missing information only from files that cannot be read.

### Environment

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 4.19.86-gentoo

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 3223)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|11.64GB (6.94GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Thanks for the repo @mattilu!

@sheetalkamat @RyanCavanaugh I tested in with typescript@next. We're seeing a fair number of these types of crashes in VS Code but didn't have good repo steps until now. If the fix isn't terrible, could we get this scheduled for TS 3.8.x

Here's the stack trace:

```
Error: EACCES: permission denied, open '/Users/matb/projects/san/foo.ts'    at Object.openSync (fs.js:447:3)    at Object.func (electron/js2c/asar.js:140:31)    at Object.func [as openSync] (electron/js2c/asar.js:140:31)    at Object.readFileSync (fs.js:349:35)    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)    at readFileWorker (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:5601:34)    at Object.readFile (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:5627:28)    at getText (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:137130:92)    at TextStorage.getFileTextAndSize (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:137142:32)    at TextStorage.reloadWithFileText (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:137053:31)    at TextStorage.getOrLoadText (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:137166:26)    at TextStorage.getSnapshot (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:137091:57)    at ScriptInfo.getSnapshot (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:137250:41)    at InferredProject.Project.getScriptSnapshot (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:137873:39)    at HostCache.createEntry (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:133494:44)    at HostCache.getOrCreateEntryByPath (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:133517:58)    at getOrCreateSourceFileByPath (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:133856:66)    at Object.getOrCreateSourceFile [as getSourceFile] (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:133849:24)    at findSourceFile (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:98413:29)    at processImportedModules (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:98754:25)    at findSourceFile (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:98461:17)    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:98290:85    at getSourceFileFromReferenceWorker (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:98257:34)    at processSourceFile (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:98290:13)    at processRootFile (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:98113:13)    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:97079:60    at Object.forEach (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:167:30)    at Object.createProgram (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:97079:16)    at synchronizeHostData (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:133814:26)    at Proxy.getProgram (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:133906:13)    at InferredProject.Proje
```

**Comment by sheetalkamat** [comment]
Note: this isn't a regression... We have always only checked for file existance..

**Comment by mjbvz** [comment]
I think what changed is that VS Code now treats updateOpen errors as fatal and restarts the server if it hits one
