### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'exclude' of undefined

### ISSUE THREAD

**Issue by pratRockss** [microsoft/TypeScript#36326]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```
When performing the ng build, getting an error as below:
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (c:\OXEWbm_Jobs\workspace\OXEWBM-SNAPSHOT_12.0\wbm\node_modules\awesome-typescript-loader\src\instance.ts:266:72)
    at Object.ensureInstance (c:\OXEWbm_Jobs\workspace\OXEWBM-SNAPSHOT_12.0\wbm\node_modules\awesome-typescript-loader\src\instance.ts:145:5)
    at compiler (c:\OXEWbm_Jobs\workspace\OXEWBM-SNAPSHOT_12.0\wbm\node_modules\awesome-typescript-loader\src\index.ts:37:20)
    at Object.loader (c:\OXEWbm_Jobs\workspace\OXEWBM-SNAPSHOT_12.0\wbm\node_modules\awesome-typescript-loader\src\index.ts:18:18)

I am using typescript 3.7.5

**Comment by j-oliveras** [comment]
This seems a runtime error inside `awesome-typescript-loader`, not a error with typescript compiler.

**Comment by RyanCavanaugh** [comment]
The call stack indicates a different component is executing here
