### ISSUE TITLE
Debug failure on TS Server format

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#36363]
From https://github.com/microsoft/vscode/issues/88935

**TypeScript Version:**  3.8.0-dev.20200122

**Search Terms:**
- format document
- tsserver

**Repo**
Run `format` on the following TS:

```ts
function TypeAssertion<T>(x: any): T {
    return (x as T);
}

TypeAssertion<<T>() => T>(null)
```

**Bug**

```
[Trace  - 00:35:00.76] <syntax> Response received: format (137). Request took 2 ms. Success: false . Message: Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at consumeTokenAndAdvanceScanner (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:121115:30)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:121029:25)
    at processChildNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:121095:48)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:120981:21
    at visitNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:18131:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:18235:21)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:120978:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:121044:21)
    at processChildNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:121095:48)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:120981:21
    at visitNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:18131:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:18318:21)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:120978:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:121044:21)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:120979:21
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:18126:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:18377:24)
```

**Comment by sorrymeika** [comment]
Run `format` on the following JS:
```js
class A {
}
A.prototype.some = 1;
```

Bug

```
<syntax> TypeScript Server Error (3.8.3)
Debug Failure. False expression: Token end is child end
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (tsserver.js:122170:34)
    at tsserver.js:122106:21
    at visitNode (tsserver.js:18281:24)
    at Object.forEachChild (tsserver.js:18462:24)
    at processNode (tsserver.js:122105:20)
    at processChildNode (tsserver.js:122176:21)
    at tsserver.js:122106:21
    at visitNode (tsserver.js:18281:24)
    at Object.forEachChild (tsserver.js:18462:24)
    at processNode (tsserver.js:122105:20)
    at processChildNode (tsserver.js:122176:21)
    at tsserver.js:122106:21
    at visitNode (tsserver.js:18281:24)
    at Object.forEachChild (tsserver.js:18501:24)
    at processNode (tsserver.js:122105:20)
    at processChildNode (tsserver.js:122176:21)
    at tsserver.js:122106:21
    at visitNode (tsserver.js:18281:24)
    at Object.forEachChild (tsserver.js:18532:24)
    at processNode (tsserver.js:122105:20)
    at processChildNode (tsserver.js:122176:21)
    at processChildNodes (tsserver.js:122239:48)
    at tsserver.js:122108:21
    at visitNodes (tsserver.js:18286:24)
    at Object.forEachChild (tsserver.js:18523:24)
    at processNode (tsserver.js:122105:20)
    at formatSpanWorker (tsserver.js:121920:17)
    at tsserver.js:121901:208
    at Object.getFormattingScanner (tsserver.js:120526:23)
    at formatSpan (tsserver.js:121901:31)
    at Object.formatSelection (tsserver.js:121719:20)
    at Proxy.getFormattingEditsForRange (tsserver.js:135636:34)
    at IOSession.Session.getFormattingEditsForRange (tsserver.js:145360:45)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144368:61)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment]
Does not reproduce for me in TS 4.5
