### ISSUE TITLE
Formatting debug failure —  Did not expect ClassDeclaration to have an Identifier in its trivia

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#36610]
**TypeScript Version:**  3.8.0-dev.20200201

**Search Terms:**
- javascript
- format

**Repo**
Run format on the following javascript code

```ts
class A {
    get AAA() {return 'aaa'}
  }
A.prototype.XXX = 'xxx'
module.exports = A
```

**Bug**

```
TypeScript Server Error (3.8.0-dev.20200201)
Debug Failure. Did not expect ClassDeclaration to have an Identifier in its trivia
Error: Debug Failure. Did not expect ClassDeclaration to have an Identifier in its trivia
    at addSyntheticNodes (tsserver.js:134196:30)
    at createChildren (tsserver.js:134185:9)
    at NodeObject.getChildren (tsserver.js:134129:56)
    at Object.findChildOfKind (tsserver.js:105845:26)
    at spanForNode (tsserver.js:117516:36)
    at getOutliningSpanForNode (tsserver.js:117465:28)
    at visitNonImportNode (tsserver.js:117313:28)
    at addNodeOutliningSpans (tsserver.js:117287:21)
    at Object.collectElements (tsserver.js:117275:13)
    at Proxy.getOutliningSpans (tsserver.js:135491:50)
    at IOSession.Session.getOutliningSpans (tsserver.js:145163:45)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144227:61)
    at tsserver.js:145889:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145880:28)
    at IOSession.Session.executeCommand (tsserver.js:145889:33)
```

**Playground Link:** 

**Related Issues:**

**Comment by orta** [comment]
Thanks Matt!

So far I've not been able to reproduce on master, this test passes:

```ts
/// <reference path='fourslash.ts' />

// @allowNonTsExtensions: true
// @Filename: test123.js
////class A {
////  get AAA() {return 'aaa'}
////}
////A.prototype.XXX = 'xxx'
////module.exports = A

format.document();

verify.currentFileContentIs(`class A {
    get AAA() { return 'aaa' }
}
A.prototype.XXX = 'xxx'
module.exports = A`)
```

Though I see in the stack there's some reference to outline spans - I did a quick audit, and requesting the outline spans doesn't reproduce the crash either. This could  have been fixed on master. 👍

**Comment by orta** [comment]
To double check, I tested by making a JS file in the typescript repo and running the formatter on that and it formatted with no issues in the file nor the tsserver logs. I'm going to close this.

**Comment by wrogner** [comment]
I get similar errors but not regularly.

Only if the last line in the file sets a static property in the prototype.
