### ISSUE TITLE
wrong syntax crashing compiler

### ISSUE THREAD

**Issue by npenin** [microsoft/TypeScript#36707]
**TypeScript Version:**  3.7.5

**Search Terms:** compiler crash syntax

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
new Proxy({}, {
    apply?(target: T, thisArg: any, argArray?: any) {
}})
```

**Expected behavior:** compiler does not crash

**Actual behavior:** compiler crashes with the following error message
```
c:\Dev\akala\commands\node_modules\typescript\lib\tsc.js:78602
                throw e;
                ^

TypeError: Cannot set property 'typeParameters' of undefined
    at assignContextualParameterTypes (c:\Dev\akala\commands\node_modules\typescript\lib\tsc.js:47037:38)
    at contextuallyCheckFunctionExpressionOrObjectLiteralMethod (c:\Dev\akala\commands\node_modules\typescript\lib\tsc.js:47426:29)
    at checkFunctionExpressionOrObjectLiteralMethod (c:\Dev\akala\commands\node_modules\typescript\lib\tsc.js:47404:13)
    at checkObjectLiteralMethod (c:\Dev\akala\commands\node_modules\typescript\lib\tsc.js:48453:38)
    at checkObjectLiteral (c:\Dev\akala\commands\node_modules\typescript\lib\tsc.js:44299:29)
    at checkExpressionWorker (c:\Dev\akala\commands\node_modules\typescript\lib\tsc.js:48678:28)
    at checkExpression (c:\Dev\akala\commands\node_modules\typescript\lib\tsc.js:48607:38)
    at checkExpressionWithContextualType (c:\Dev\akala\commands\node_modules\typescript\lib\tsc.js:48347:24)
    at getSignatureApplicabilityError (c:\Dev\akala\commands\node_modules\typescript\lib\tsc.js:45693:35)
    at chooseOverload (c:\Dev\akala\commands\node_modules\typescript\lib\tsc.js:46111:29)
```

**Playground Link:** http://www.typescriptlang.org/play/index.html#code/HYUw7gBACgTg9gDwJ4AoDeBfANBNAoCQiAQwAdSAbJAfhQBdiYBzEOgLggBUc6ALASwDOAQWYdiwJDkZNRMYjXGSAlLgJENAMwAmmigGtig3fopHt+4AFtjmgMwAWAEwByADpuQLp3ZfO3Li54GBjKQA

**Related Issues:**

**Comment by elibarzilay** [comment]
@npenin, I can't reproduce this crash --- I tried it with the current tree, with 3.7.5, in the playground, and with a `-t es6`.  Maybe there's something else to get the bug to happen?

**Comment by RyanCavanaugh** [comment]
Working as of 3.9
