### ISSUE TITLE
JSDOC @type tag crashes with simple export

### ISSUE THREAD

**Issue by rchl** [microsoft/TypeScript#36830]
**TypeScript Version:**  3.9.0-dev.20200215 (also tested 3.7.5)

(the last one that doesn't crash is `v3.7.1-rc`. `v3.7.2` crashes)

**Search Terms:**

`Maximum call stack size exceeded`
`getTypeOfFuncClassEnumModule`

**Code**

`/lib/index.js`:
```js
/** @type {import('../types/index').xxx} */
function xxx() {
    return null;
}
```

`/types/index.d.ts`:
```ts
export function xxx(): string;
```

`/tsconfig.json`:
```js
{
    "compilerOptions": {
        "target": "esnext",
        "module": "commonjs",
        "esModuleInterop": true,
        "lib": [
            "dom",
            "esnext"
        ],
        "allowJs": true,
        "checkJs": true,
        "noEmit": true,
        "resolveJsonModule": true,
        "strict": true,
        "moduleResolution": "node",
        "baseUrl": ".",
    }
}
```

**Expected behavior:**

No crash.
Typescript error about function returning wrong error type.

**Actual behavior:**

Crash.

```
/me/ts-crash-test/node_modules/typescript/lib/tsc.js:81193
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at getSymbolLinks (/me/ts-crash-test/node_modules/typescript/lib/tsc.js:28829:32)
    at getTypeOfFuncClassEnumModule (/me/ts-crash-test/node_modules/typescript/lib/tsc.js:33936:25)
    at getTypeOfSymbol (/me/ts-crash-test/node_modules/typescript/lib/tsc.js:34045:24)
    at getTypeFromJSDocValueReference (/me/ts-crash-test/node_modules/typescript/lib/tsc.js:36634:33)
    at getTypeReferenceType (/me/ts-crash-test/node_modules/typescript/lib/tsc.js:36620:33)
    at getTypeFromJSDocValueReference (/me/ts-crash-test/node_modules/typescript/lib/tsc.js:36648:36)
    at getTypeReferenceType (/me/ts-crash-test/node_modules/typescript/lib/tsc.js:36620:33)
    at getTypeFromJSDocValueReference (/me/ts-crash-test/node_modules/typescript/lib/tsc.js:36648:36)
    at getTypeReferenceType (/me/ts-crash-test/node_modules/typescript/lib/tsc.js:36620:33)
    at getTypeFromJSDocValueReference (/me/ts-crash-test/node_modules/typescript/lib/tsc.js:36648:36)
```

**Playground Link:** 

https://github.com/rchl/ts-crash-test

**Related Issues:**

**Comment by orta** [comment]
Cool, reproduced with:

```ts
// @allowJs: true
// @noEmit: true
// @checkJs: true

// @filename: lib/index.js
/** @type {import('../folder/index').zzz} */
function xxx() {
  return null;
}

// @filename: folder/index.d.ts
export function zzz(): string;
```


In normal TypeScript code, you wouldn't write `import('../folder/index').zzz` - but would write `typeof import('../folder/index').zzz` to get to the type `() => string` - doing this doesn't cause the loop in the code.

Which I think leads to another question, what _should_ be the behavior here in JSDoc world? Do we assume we want the `typeof` or does it still represent the export-ed identifier of `zzz`?

**Comment by orta** [comment]
Asked around, and the opinion is yes - we want to pretend there's a `typeof` before the import in this case - gonna pair on it next week

**Comment by orta** [comment]
A fix for this got merged yesterday: https://github.com/microsoft/TypeScript/pull/39770
