### ISSUE TITLE
`Cannot read property 'flags' of undefined` when assigning tuple to class with private property

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#36871]
**TypeScript Version:**  3.9.0-dev.20200215

**Code**

```ts
class C {
	#x = 0
}

function f(x: [number]): C {
	return x
}
```

**Expected behavior:**

No crash

**Actual behavior:**

```
TypeError: Cannot read property 'flags' of undefined
    at reportUnmatchedProperty (.../typescript/lib/tsc.js:40770:38)
    at propertiesRelatedTo (.../typescript/lib/tsc.js:40815:25)
    at structuredTypeRelatedTo (.../typescript/lib/tsc.js:40501:34)
    at recursiveTypeRelatedTo (.../typescript/lib/tsc.js:40248:53)
    at isRelatedTo (.../typescript/lib/tsc.js:39930:38)
    at checkTypeRelatedTo (.../typescript/lib/tsc.js:39638:26)
    at checkTypeRelatedToAndOptionallyElaborate (.../typescript/lib/tsc.js:38950:24)
    at checkTypeAssignableToAndOptionallyElaborate (.../typescript/lib/tsc.js:38944:20)
    at checkReturnStatement (.../typescript/lib/tsc.js:52933:25)
    at checkSourceElementWorker (.../typescript/lib/tsc.js:54384:28)
```

**Related Issues:** https://github.com/microsoft/TypeScript/issues/36677

**Comment by RyanCavanaugh** [comment]
Tracking at #37014
