### ISSUE TITLE
TypeError: Cannot read property 'checkJsDirective' of undefined

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#36984]
From https://github.com/microsoft/vscode/issues/91247

**TypeScript Version:**  3.8.2

**Search Terms:**
- updateOpened
- applyChangesInOpenFiles

**Crash**
We saw a user report this crash in VS Code:

```
TypeError: Cannot read property 'checkJsDirective' of undefined
    at ProjectService.telemetryOnOpenFile (tsserver.js:143789:79)
    at tsserver.js:143868:76
    at Array.forEach (<anonymous>)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143868:37)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144722:46)
    at tsserver.js:146465:88
    at IOSession.Session.executeWithRequestId (tsserver.js:146456:28)
    at IOSession.Session.executeCommand (tsserver.js:146465:33)
    at IOSession.Session.onMessage (tsserver.js:146489:35)
    at Interface.<anonymous> (tsserver.js:147804:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment]
@selfrefactor Can you share a project the causes this issue?

**Comment by mjbvz** [comment]
Also @RyanCavanaugh, marking this as priority since it causes VS Code to restart the TS server. Another one for a 3.8.x recovery build

**Comment by selfrefactor** [comment]
@mjbvz I am unsure about which project caused it. 
I think it was https://github.com/selfrefactor/on as I was surprised as the project has `jsconfig.json` but it is Javascript, not Typescript, type of project.

**Comment by RyanCavanaugh** [comment]
@mjbvz ported to 3.8 branch 👍
