### ISSUE TITLE
Maximum call stack size exceeded when strictNullChecks is enabled.

### ISSUE THREAD

**Issue by ad0ran** [microsoft/TypeScript#37008]
**TypeScript Version:**  3.8.2

**Search Terms:** 
strictNullChecks, maximum call stack exceeded

**Code**

```
tsc --project tsconfig.json
```

**Expected behavior:**
The tsc cli to execute without exception

**Actual behavior:**
```
RangeError: Maximum call stack size exceeded
    at checkGrammarForDisallowedTrailingComma (C:\Users\adria\Projects\website-fe\node_modules\typescript\lib\tsc.js:55992:56)
    at checkGrammarTypeArguments (C:\Users\adria\Projects\website-fe\node_modules\typescript\lib\tsc.js:56129:20)
    at checkCallExpression (C:\Users\adria\Projects\website-fe\node_modules\typescript\lib\tsc.js:48028:18)
    at checkExpressionWorker (C:\Users\adria\Projects\website-fe\node_modules\typescript\lib\tsc.js:50181:28)
    at checkExpression (C:\Users\adria\Projects\website-fe\node_modules\typescript\lib\tsc.js:50098:38)
    at checkTruthinessExpression (C:\Users\adria\Projects\website-fe\node_modules\typescript\lib\tsc.js:52215:42)
    at checkConditionalExpression (C:\Users\adria\Projects\website-fe\node_modules\typescript\lib\tsc.js:49778:13)
    at checkExpressionWorker (C:\Users\adria\Projects\website-fe\node_modules\typescript\lib\tsc.js:50213:28)
    at checkExpression (C:\Users\adria\Projects\website-fe\node_modules\typescript\lib\tsc.js:50098:38)
    at removeOptionalityFromDeclaredType (C:\Users\adria\Projects\website-fe\node_modules\typescript\lib\tsc.js:44129:33)
```

Not sure why, but when I disable `strictNullChecks`, the tsc cli seems to work just fine. But as soon as i set it to true, I get these maximum call stack size exceeded errors.
Here's my config:

```json
{
  "compilerOptions": {
    "incremental": false,
    "target": "es5",
    "module": "commonjs",
    "lib": ["dom", "es2020", "esnext"], 
    "allowJs": false,
    "checkJs": false,
    "jsx": "react",
    "noEmit": true,
    "downlevelIteration": true,
    "isolatedModules": true,
    "noImplicitAny": false,
    "strictNullChecks": true,               
    "strictFunctionTypes": true,            
    "strictBindCallApply": true,            
    "strictPropertyInitialization": true,   
    "noImplicitThis": true,                 
    "alwaysStrict": true,                   
    "noUnusedLocals": true,                 
    "noUnusedParameters": true,
    "moduleResolution": "node",
    "baseUrl": "./",
    "typeRoots": [
      "node_modules/@types",
      "@types"
    ],
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipLibCheck": true
  },
  "include": [
    "src/**/*"
  ]
}
```

**Comment by RyanCavanaugh** [comment]
Some code that repros this *or* a taller call stack would be very helpful, if possible

**Comment by RyanCavanaugh** [comment]
Based on the call stack I think you're looking for *something* like this, where there's a parameter with a default:
```
function fn(x: string | undefined = "hello") {
  
}
```

**Comment by ad0ran** [comment]
> Based on the call stack I think you're looking for _something_ like this, where there's a parameter with a default:
> 
> ```
> function fn(x: string | undefined = "hello") {
>   
> }
> ```

Thanks, that'll help a lot actually.
Also, you mentioned something about producing a taller call stack -- is there a way to expand it? Would I have to build typescript from source and attach a node debugger or something?

**Comment by RyanCavanaugh** [comment]
Never mind, found it:
```ts
function fn(x: boolean | undefined = x > 0) { }
```

**Comment by ad0ran** [comment]
> Never mind, found it:
> 
> ```ts
> function fn(x: boolean | undefined = x > 0) { }
> ```

yes, i found similar code to this that was causing the problem:
`fn fn(x?: string = someCondition ? 'value1' : x)`

It's odd since it's not being reported as an error to me through vscode.

**Comment by RyanCavanaugh** [comment]
FYI it's a TDZ error to access 'x' here, so this will be flagged as an error when we stop crashing 🙂
