### ISSUE TITLE
TypeScript Fatal Error: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#37368]
**TypeScript Version:**  3.8.3

**Search terms**
- fatal error
- applyChangesInOpenFiles
- updateOpen

**Error Stack**

```
TypeError: Cannot read property 'path' of undefined
    at addReferencedFilesToTypeDirective (tsserver.js:66268:46)
    at tsserver.js:66103:21
    at Map.forEach (<anonymous>)
    at createResolver (tsserver.js:66096:49)
    at Object.createTypeChecker (tsserver.js:34243:28)
    at Object.getTypeChecker (tsserver.js:98416:79)
    at synchronizeHostData (tsserver.js:135228:21)
    at Proxy.getProgram (tsserver.js:135310:13)
    at ConfiguredProject.Project.updateGraphWorker (tsserver.js:139786:53)
    at ConfiguredProject.Project.updateGraph (tsserver.js:139729:42)
    at ConfiguredProject.updateGraph (tsserver.js:140654:63)
    at updateProjectIfDirty (tsserver.js:141076:45)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:143114:29)
    at tsserver.js:143396:107
    at Object.mapDefined (tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143396:48)
...
```

**Comment by mjbvz** [comment]
Fairly small number of hits for this issue so far but worth looking into what is going on
