### ISSUE TITLE
Debug assertion failure in nav tree

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#37520]
```ts
/*start*/(async () => {
    const lol = 10;
    lol;
})/*end*/
```

1. Select the range from `start` to `end`.
1. Delete the range

**Expected:** All good
**Actual:**

```
[Trace  - 01:29:40.569] <syntax> Response received: navtree (511). Request took 3 ms. Success: false . Message: Error processing request. Debug Failure. False expression: Expected line to be non-zero
Error: Debug Failure. False expression: Expected line to be non-zero
    at failIfInvalidLocation (C:\Users\Daniel\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-3.9.20200322\node_modules\typescript\lib\tsserver.js:141032:22)
    at ScriptInfo.positionToLineOffset (C:\Users\Daniel\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-3.9.20200322\node_modules\typescript\lib\tsserver.js:141005:17)
    at toProtocolTextSpan (C:\Users\Daniel\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-3.9.20200322\node_modules\typescript\lib\tsserver.js:148208:35)
    at C:\Users\Daniel\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-3.9.20200322\node_modules\typescript\lib\tsserver.js:147739:68
    at Array.map (<anonymous>)
    at IOSession.Session.toLocationNavigationTree (C:\Users\Daniel\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-3.9.20200322\node_modules\typescript\lib\tsserver.js:147739:39)
    at IOSession.Session.getNavigationTree (C:\Users\Daniel\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-3.9.20200322\node_modules\typescript\lib\tsserver.js:147750:32)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (C:\Users\Daniel\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-3.9.20200322\node_modules\typescript\lib\tsserver.js:146597:61)
    at C:\Users\Daniel\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-3.9.20200322\node_modules\typescript\lib\tsserver.js:148134:88
    at IOSession.Session.executeWithRequestId (C:\Users\Daniel\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-3.9.20200322\node_modules\typescript\lib\tsserver.js:148125:28)
    at IOSession.Session.executeCommand (C:\Users\Daniel\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-3.9.20200322\node_modules\typescript\lib\tsserver.js:148134:33)
    at IOSession.Session.onMessage (C:\Users\Daniel\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-3.9.20200322\node_modules\typescript\lib\tsserver.js:148158:35)
    at Interface.<anonymous> (C:\Users\Daniel\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-3.9.20200322\node_modules\typescript\lib\tsserver.js:149474:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by DanielRosenwasser** [comment]
I guess this is a dupe of #36977 which seems like a high hitter.
