### ISSUE TITLE
TSServer raises exception in semantic highlighting check in formatDiag

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript#37557]
**TypeScript Version:**  typescript-next-3.9.20200323

**Search Terms:** TSServer semantic error  formatDiag expected position undefined to be a number

**Code** 

```sh
git clone https://github.com/orta/31465.git
cd 31465
code .
```

Then open `testutils.ts` and see the log.

```ts
Info 89   [17:21:56.407] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"/Users/ortatherox/dev/typescript/repros/31465/test/testutils.ts","diagnostics":[]}}
Err 90    [17:21:56.438] Exception on executing command semanticDiag:

    Debug Failure. False expression: Expected position undefined to be a number.

    Error: Debug Failure. False expression: Expected position undefined to be a number.
        at failIfInvalidPosition (/Users/ortatherox/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.9.20200323/node_modules/typescript/lib/tsserver.js:141026:22)
        at ScriptInfo.positionToLineOffset (/Users/ortatherox/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.9.20200323/node_modules/typescript/lib/tsserver.js:141003:17)
        at formatDiag (/Users/ortatherox/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.9.20200323/node_modules/typescript/lib/tsserver.js:145949:35)
        at /Users/ortatherox/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.9.20200323/node_modules/typescript/lib/tsserver.js:146914:100
        at Array.map (<anonymous>)
        at IOSession.Session.sendDiagnosticsEvent (/Users/ortatherox/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.9.20200323/node_modules/typescript/lib/tsserver.js:146914:71)
        at IOSession.Session.semanticCheck (/Users/ortatherox/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.9.20200323/node_modules/typescript/lib/tsserver.js:146904:22)
        at /Users/ortatherox/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.9.20200323/node_modules/typescript/lib/tsserver.js:146959:31
        at MultistepOperation.executeAction (/Users/ortatherox/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.9.20200323/node_modules/typescript/lib/tsserver.js:146060:25)
        at /Users/ortatherox/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.9.20200323/node_modules/typescript/lib/tsserver.js:146041:100
        at IOSession.Session.executeWithRequestId (/Users/ortatherox/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.9.20200323/node_modules/typescript/lib/tsserver.js:148125:28)
        at Object.executeWithRequestId (/Users/ortatherox/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.9.20200323/node_modules/typescript/lib/tsserver.js:146699:87)
        at Immediate._onImmediate (/Users/ortatherox/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.9.20200323/node_modules/typescript/lib/tsserver.js:146041:41)
        at processImmediate (internal/timers.js:439:21)
Info 91   [17:21:56.441] event:
    {"seq":0,"type":"event","event":"suggestionDiag","body":{"file":"/Users/ortatherox/dev/typescript/repros/31465/test/testutils.ts","diagnostics":[{"start":{"line":1,"offset":10},"end":{"line":1,"offset":27},"text":"'ReactTestInstance' is declared but its value is never read.","code":6133,"category":"suggestion","reportsUnnecessary":true}]}}
```

**Expected behavior:**

No TSServer exception

**Playground Link:** No semantic highlighting in the playground

**Comment by sheetalkamat** [comment]
#37545 should fix this ?

**Comment by orta** [comment]
Confirmed it is fixed - thanks!
