### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by cadupedroni** [microsoft/TypeScript#37759]
**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (tsserver.js:101865:22)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (tsserver.js:101901:25)
    at Map.forEach (<anonymous>)
    at Object.clearPerDirectoryResolutions [as startCachingPerDirectoryResolution] (tsserver.js:101661:50)
    at ConfiguredProject.Project.updateGraphWorker (tsserver.js:139785:38)
    at ConfiguredProject.Project.updateGraph (tsserver.js:139729:42)
    at ConfiguredProject.updateGraph (tsserver.js:140654:63)
    at updateProjectIfDirty (tsserver.js:141076:45)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:143114:29)
    at tsserver.js:143396:107
    at Object.mapDefined (tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment]
Same error as #37358

@cadupedroni Do you remember what you were doing when this error occurred?

**Comment by playerx** [comment]
@mjbvz I've the same error when I try to run custom angular schematics, using nrwl's nx workspace

**Steps to reproduce crash**
1. Create new nx workspace
2. Generate `@nrwl/workspace - library` schematics
3. Try to generate library using newly created schematics

**Comment by playerx** [comment]
I had the same problem and it was happening when `tsc` was processing file like this:

```
import { Component } from '@angular/core'<% if (routePath) { %>
import { ActivatedRoute } from '@angular/router'<% } %>
import { localTranslateProviders } from '@jok/shared'
import lang from './<%= dasherize(name) %>.lang'

@Component({
  selector: '<%= selector %>',
  templateUrl: './<%= dasherize(name) %>.page.html',
  styleUrls: ['./<%= dasherize(name) %>.page.<%= styleext %>'],
  providers: localTranslateProviders(lang),
})
export class <%= classify(name) %>Page {

  constructor(<% if (routePath) { %> private route: ActivatedRoute <% } %>) { }

}
```
After excluding this file, everything works good

**Comment by sheetalkamat** [comment]
@cadupedroni  @playerx  are you still seeing this. Can you please provide tsserver log when this happens.. This seems more state dependent so just file that was being processed doesnt help with it as its more to do with what files were open. which projects it belonged etc. 
You can upload logs by following these steps:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. In vscode or vscode insiders, run the `TypeScript: Open TS Server log` command
5. This should open a large file called `tsserver.log`. Please share this file. Additionally you can also share file `ti.log` created next to it.

**Comment by Bosch-Eli-Black** [comment]
I just ran into this while using Visual Studio 2019.

I was working in Visual Studio, and then my laptop went to sleep due to inactivity. I woke the laptop, logged in to Windows, logged back on to the company VPN, and opened Visual Studio, where I had the following error:
```
[ProjectHost] Automatic Type Acquisition failed to install some or all of the following packages. This might cause poor IntelliSense in your JavaScript/TypeScript files. See https://aka.ms/jstsata for more information. Package list: @types/ajv-errors@ts4.2,@types/ansi-styles@ts4.2,@types/arr-union@ts4.2,@types/array-find-index@ts4.2,@types/asn1@ts4.2,@types/bonjour@ts4.2,@types/boolbase@ts4.2,@types/cacache@ts4.2,@types/compression@ts4.2,@types/connect-history-api-fallback@ts4.2,@types/convert-source-map@ts4.2,@types/cross-spawn@ts4.2,@types/css-tree@ts4.2,@types/csso@ts4.2,@types/dashdash@ts4.2,@types/deep-extend@ts4.2,@types/default-gateway@ts4.2,@types/err-code@ts4.2,@types/expand-tilde@ts4.2,@types/express@ts4.2,@types/extsprintf@ts4.2,@types/fs-extra@ts4.2,@types/get-caller-file@ts4.2,@types/get-value@ts4.2,@types/getpass@ts4.2,@types/glob@ts4.2,@types/graceful-fs@ts4.2,@types/hosted-git-info@ts4.2,@types/http-proxy@ts4.2,@types/humanize-ms@ts4.2,@types/ignore-walk@ts4.2,@types/imurmurhash@ts4.2,@types/inherits@ts4.2,@types/inquirer@ts4.2,@types/interpret@ts4.2,@types/ip@ts4.2,@types/is-finite@ts4.2,@types/jsbn@ts4.2,@types/json-schema@ts4.2,@types/loader-utils@ts4.2,@types/lru-cache@ts4.2,@types/make-fetch-happen@ts4.2,@types/memory-fs@ts4.2,@types/merge-stream@ts4.2,@types/micromatch@ts4.2,@types/mkdirp@ts4.2,@types/ms@ts4.2,@types/node-forge@ts4.2,@types/normalize-path@ts4.2,@types/os-homedir@ts4.2,@types/parse-passwd@ts4.2,@types/pify@ts4.2,@types/promise-retry@ts4.2,@types/punycode@ts4.2,@types/range-parser@ts4.2,@types/rechoir@ts4.2,@types/repeating@ts4.2,@types/require-directory@ts4.2,@types/retry@ts4.2,@types/semver@ts4.2,@types/serve-index@ts4.2,@types/set-value@ts4.2,@types/signal-exit@ts4.2,@types/sockjs@ts4.2,@types/sockjs-client@ts4.2,@types/spdx-correct@ts4.2,@types/spdx-expression-parse@ts4.2,@types/spdy@ts4.2,@types/ssri@ts4.2,@types/supports-color@ts4.2,@types/validate-npm-package-license@ts4.2,@types/verror@ts4.2,@types/webpack-sources@ts4.2,@types/ws@ts4.2,@types/yargs@ts4.2,@types/yargs-parser@ts4.2,@types/spdx-satisfies@ts4.2
The JavaScript and TypeScript language service has been disabled due to an error. You may see reduced IntelliSense support for your project. Please try reloading your solution to reenable the language service.
Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at watchFailedLookupLocationOfResolution (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.2\tsserver.js:110952:22)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.2\tsserver.js:110987:29)
    at Map.forEach (<anonymous>)
    at Object.clearPerDirectoryResolutions [as startCachingPerDirectoryResolution] (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.2\tsserver.js:110724:50)
    at ExternalProject.Project.updateGraphWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.2\tsserver.js:154074:38)
    at ExternalProject.Project.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.2\tsserver.js:154005:42)
    at ExternalProject.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.2\tsserver.js:155156:59)
    at ProjectService.openExternalProject (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.2\tsserver.js:158257:41)
    at ProjectService.openExternalProjects (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.2\tsserver.js:158072:26)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.2\tsserver.js:159034:46)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.2\tsserver.js:160947:88
    at IOSession.Session.executeWithRequestId (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.2\tsserver.js:160938:28)
    at IOSession.Session.executeCommand (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.2\tsserver.js:160947:33)
    at IOSession.Session.onMessage (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.2\tsserver.js:160973:35)
    at Interface.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.2\tsserver.js:163634:31)
    at Interface.emit (events.js:314:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

I originally filed at https://developercommunity.visualstudio.com/t/the-javascript-and-typescript-language-service-has-6/1439010 but they've asked me to refile here, since this appears to be a TypeScript issue 🙂

**Comment by Bosch-Eli-Black** [comment]
I think this probably has something to do with NodeJS and my laptop's VPN/proxy interaction. Normally everything works fine. Maybe it sometimes happens when NodeJS is trying to do something and the user logs in to the VPN at the same time, which breaks name server lookup resolution?

**Comment by sheetalkamat** [comment]
we would need logs to be able to investigate this. As it is dependent on the state of server rather than single command..
