### ISSUE TITLE
TypeScript Server Error (3.8.3) Debug Failure. False expression.

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/TypeScript#37810]
https://github.com/JacksonKearl/vscode-triage-github-actions/blob/b4b9c04366668e4b68145674e6070bed98fff7f7/needs-more-info-closer/NeedsMoreInfoCloser.test.ts#L86

```
declare const expect; 
[].map(
  (issue) =>
    expect(issue.issue?.open, issue.comments?.map((comment) => comment.body).join(',')).to.be
      .true,
)  
```

attempt an "add braces to arrow function"

<semantic> TypeScript Server Error (3.8.3)
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at getPos (tsserver.js:123278:22)
    at assignPositionsToNode (tsserver.js:124064:27)
    at visitNode (tsserver.js:72887:23)
    at Object.visitEachChild (tsserver.js:73104:117)
    at assignPositionsToNode (tsserver.js:124061:30)
    at Object.visitNodes (tsserver.js:72938:48)
    at assignPositionsToNodeArray (tsserver.js:124069:30)
    at Object.visitEachChild (tsserver.js:73116:156)
    at assignPositionsToNode (tsserver.js:124061:30)
    at visitNode (tsserver.js:72887:23)
    at Object.visitEachChild (tsserver.js:73106:54)
    at assignPositionsToNode (tsserver.js:124061:30)
    at visitNode (tsserver.js:72887:23)
    at Object.visitEachChild (tsserver.js:73106:54)
    at assignPositionsToNode (tsserver.js:124061:30)
    at visitNode (tsserver.js:72887:23)
    at Object.visitEachChild (tsserver.js:73106:54)
    at assignPositionsToNode (tsserver.js:124061:30)
    at visitNode (tsserver.js:72887:23)
    at Object.visitEachChild (tsserver.js:73188:46)
    at assignPositionsToNode (tsserver.js:124061:30)
    at Object.visitNodes (tsserver.js:72938:48)
    at assignPositionsToNodeArray (tsserver.js:124069:30)
    at Object.visitEachChild (tsserver.js:73166:45)
    at assignPositionsToNode (tsserver.js:124061:30)
    at getNonformattedText (tsserver.js:124045:56)
    at getFormattedTextOfNode (tsserver.js:124026:26)
    at format (tsserver.js:124009:52)
    at computeNewText (tsserver.js:124012:23)
    at tsserver.js:123982:89
    at Array.map (<anonymous>)
    at tsserver.js:123981:50
    at Array.map (<anonymous>)
    at Object.getTextChangesFromChanges (tsserver.js:123967:86)
    at ChangeTracker.getChanges (tsserver.js:123935:45)
    at Function.ChangeTracker.with (tsserver.js:123414:32)
    at Object.getEditsForAction (tsserver.js:133493:62)
    at Object.getEditsForRefactor (tsserver.js:124598:41)
    at Proxy.getEditsForRefactor (tsserver.js:135907:32)
    at IOSession.Session.getEditsForRefactor (tsserver.js:145708:59)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144531:61)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)

**Comment by DanielRosenwasser** [comment]
Not seeing a repro in nighty. Are you running with the [VS Code Nightly JavaScript/TypeScript extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)?

**Comment by RyanCavanaugh** [comment]
Same
