### ISSUE TITLE
'Debug Failure. Invalid cast.' for convert import quick fix

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#38081]
From https://github.com/microsoft/vscode/issues/95398

**TypeScript Version:**  3.9.0-dev.20200420

**Search Terms:**
- quick fix
- code action

**Code**
For the TS:

```ts
const { foo } = require('bar');
```

1. Notice a suggestion to convert to an import.
1. Try triggering quick fixes for this suggestion

**Bug**
Exception:

```
[Trace  - 23:23:03.487] <semantic> Response received: getCodeFixes (211). Request took 1 ms. Success: false . Message: Error processing request. Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isIdentifier'.
Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isIdentifier'.
    at Object.cast (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:1375:25)
    at getInfo (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:133111:95)
    at doChange (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:133101:22)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:133094:96
    at Function.ChangeTracker.with (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:125643:17)
    at Object.getCodeActions (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:133094:64)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:126791:77
    at Object.flatMap (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:465:25)
    at Object.getFixes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:126791:23)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:138580:35
    at Object.flatMap (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:465:25)
    at Proxy.getCodeFixesAtPosition (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:138578:23)
    at IOSession.Session.getCodeFixes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:148674:64)
```

**Comment by a-tarasyuk** [comment]
@andrewbranch Can I take this issue? Or have you started work on it?

**Comment by andrewbranch** [comment]
@a-tarasyuk Go for it!
