### ISSUE TITLE
running tsc, cannot read porperty kind of undefined at getErrorSpanForNode

### ISSUE THREAD

**Issue by jayshah123** [microsoft/TypeScript#38190]
node v10.15.0
npm  v6.4.1
**TypeScript Version:**  3.8.3

**Search Terms:** getErrorSpanForNode, createDiagnosticForNode

**Code** `npm run tsc`

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```
```

> MyApp@0.0.1 type-check /Users/jay.shah/Documents/detoxandroidsetup/mypartner
> tsc

/Users/jay.shah/Documents/detoxandroidsetup/mypartner/node_modules/typescript/lib/tsc.js:81040
                throw e;
                ^

TypeError: Cannot read property 'kind' of undefined
    at getErrorSpanForNode (/Users/jay.shah/Documents/detoxandroidsetup/mypartner/node_modules/typescript/lib/tsc.js:10218:22)
    at Object.createDiagnosticForNodeInSourceFile (/Users/jay.shah/Documents/detoxandroidsetup/mypartner/node_modules/typescript/lib/tsc.j
s:10180:20)
    at createDiagnosticForNode (/Users/jay.shah/Documents/detoxandroidsetup/mypartner/node_modules/typescript/lib/tsc.js:81273:31)
    at walk (/Users/jay.shah/Documents/detoxandroidsetup/mypartner/node_modules/typescript/lib/tsc.js:81132:50)
    at visitNode (/Users/jay.shah/Documents/detoxandroidsetup/mypartner/node_modules/typescript/lib/tsc.js:14633:24)
    at Object.forEachChild (/Users/jay.shah/Documents/detoxandroidsetup/mypartner/node_modules/typescript/lib/tsc.js:14969:21)
    at walk (/Users/jay.shah/Documents/detoxandroidsetup/mypartner/node_modules/typescript/lib/tsc.js:81186:24)
    at walkArray (/Users/jay.shah/Documents/detoxandroidsetup/mypartner/node_modules/typescript/lib/tsc.js:81243:25)
    at visitNodes (/Users/jay.shah/Documents/detoxandroidsetup/mypartner/node_modules/typescript/lib/tsc.js:14638:24)
    at Object.forEachChild (/Users/jay.shah/Documents/detoxandroidsetup/mypartner/node_modules/typescript/lib/tsc.js:14861:24)
```

**Expected behavior:** Should run the typescript compiler

**Actual behavior:** Does not runt typescript compiler

**Playground Link:** 

**Related Issues:**  None

**Comment by jayshah123** [comment]
By putting a log in `tsc.js` 
I was able to find the culprit file,
But it should probably add some error like:
```js
       // getErrorSpanForNode function
        if(!node || !node.kind) {
            console.error('kind not found, problem in : ', sourceFile.fileName);
        }
```
So that end user can find out the culprit file.
