### ISSUE TITLE
Checker crash in isWeakType

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#38369]
Reported by @wycats, but no repro available

```
TypeError: Cannot read property 'length' of undefined
    at isWeakType (/home/wycats/Code/hbs-parser/node_modules/.pnpm/registry.npmjs.org/typescript/4.0.0-dev.20200506/node_modules/typescript/lib/tsc.js:42173:48)
    at isRelatedTo (/home/wycats/Code/hbs-parser/node_modules/.pnpm/registry.npmjs.org/typescript/4.0.0-dev.20200506/node_modules/typescript/lib/tsc.js:40927:58)
    at checkTypeRelatedTo (/home/wycats/Code/hbs-parser/node_modules/.pnpm/registry.npmjs.org/typescript/4.0.0-dev.20200506/node_modules/typescript/lib/tsc.js:40657:26)
    at isTypeRelatedTo (/home/wycats/Code/hbs-parser/node_modules/.pnpm/registry.npmjs.org/typescript/4.0.0-dev.20200506/node_modules/typescript/lib/tsc.js:40621:24)
    at isTypeSubtypeOf (/home/wycats/Code/hbs-parser/node_modules/.pnpm/registry.npmjs.org/typescript/4.0.0-dev.20200506/node_modules/typescript/lib/tsc.js:39909:20)
    at getNarrowedType (/home/wycats/Code/hbs-parser/node_modules/.pnpm/registry.npmjs.org/typescript/4.0.0-dev.20200506/node_modules/typescript/lib/tsc.js:45275:24)
    at narrowTypeByTypePredicate (/home/wycats/Code/hbs-parser/node_modules/.pnpm/registry.npmjs.org/typescript/4.0.0-dev.20200506/node_modules/typescript/lib/tsc.js:45295:36)
    at getTypeAtFlowCall (/home/wycats/Code/hbs-parser/node_modules/.pnpm/registry.npmjs.org/typescript/4.0.0-dev.20200506/node_modules/typescript/lib/tsc.js:44715:61)
    at getTypeAtFlowNode (/home/wycats/Code/hbs-parser/node_modules/.pnpm/registry.npmjs.org/typescript/4.0.0-dev.20200506/node_modules/typescript/lib/tsc.js:44590:32)
    at getFlowTypeOfReference (/home/wycats/Code/hbs-parser/node_modules/.pnpm/registry.npmjs.org/typescript/4.0.0-dev.20200506/node_modules/typescript/lib/tsc.js:44550:51)
```

**Comment by DanielRosenwasser** [comment]
This seems to happen because the evolving array type doesn't have any resolved properties.

```ts
export function unsafeCast<T>(_value: unknown): asserts _value is T { }

function yadda() {
    let out = [];

    out.push(100)

    unsafeCast<any>(out);
    return out;
}
```
