### ISSUE TITLE
Error: Debug Failure. False expression.  at Object.first

### ISSUE THREAD

**Issue by minestarks** [microsoft/TypeScript#38408]
**Repo Name**: https://github.com/nylas/nylas-mail.git

**Revision**: e16cb1982e944ae7edb69b1abef1436dd16b442d

**TypeScript Version**: 4.0.0-dev.20200507

**Commands**: 

```
{"response":[],"responseRequired":true}
{"command":"definition-full","arguments":{"position":7100,"file":"D:/local/Temp/fuzzerWorkingDir/nylas-mail/packages/client-app/build/tasks/docs-render-task.js"},"type":"request","seq":42}
{"response":[],"responseRequired":true}
{"command":"quickinfo-full","arguments":{"position":3,"file":"D:/local/Temp/fuzzerWorkingDir/nylas-mail/packages/client-app/build/tasks/docs-render-task.js"},"type":"request","seq":42}
{"responseRequired":true}
{"command":"quickinfo-full","arguments":{"position":7100,"file":"D:/local/Temp/fuzzerWorkingDir/nylas-mail/packages/client-app/build/tasks/docs-render-task.js"},"type":"request","seq":42}
{"response":{"kind":"var","kindModifiers":"","textSpan":{"start":7091,"length":9},"displayParts":[{"text":"var","kind":"keyword"},{"text":" ","kind":"space"},{"text":"undefined","kind":"propertyName"}],"documentation":[]},"responseRequired":true}
{"command":"references-full","arguments":{"position":3,"file":"D:/local/Temp/fuzzerWorkingDir/nylas-mail/packages/client-app/build/tasks/docs-render-task.js"},"type":"request","seq":42}
{"response":[{"definition":{"containerKind":"","containerName":"","fileName":"D:/local/Temp/fuzzerWorkingDir/nylas-mail/packages/client-app/build/tasks/docs-render-task.js","kind":"const","name":"const path: any","textSpan":{"start":6,"length":4},"displayParts":[{"text":"const","kind":"keyword"},{"text":" ","kind":"space"},{"text":"path","kind":"localName"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"any","kind":"keyword"}],"contextSpan":{"start":0,"length":29}},"references":[{"textSpan":{"start":6,"length":4},"fileName":"D:/local/Temp/fuzzerWorkingDir/nylas-mail/packages/client-app/build/tasks/docs-render-task.js","contextSpan":{"start":0,"length":29},"isWriteAccess":true,"isDefinition":true},{"textSpan":{"start":1322,"length":4},"fileName":"D:/local/Temp/fuzzerWorkingDir/nylas-mail/packages/client-app/build/tasks/docs-render-task.js","isWriteAccess":false,"isDefinition":false},{"textSpan":{"start":2577,"length":4},"fileName":"D:/local/Temp/fuzzerWorkingDir/nylas-mail/packages/client-app/build/tasks/docs-render-task.js","isWriteAccess":false,"isDefinition":false},{"textSpan":{"start":3981,"length":4},"fileName":"D:/local/Temp/fuzzerWorkingDir/nylas-mail/packages/client-app/build/tasks/docs-render-task.js","isWriteAccess":false,"isDefinition":false},{"textSpan":{"start":4157,"length":4},"fileName":"D:/local/Temp/fuzzerWorkingDir/nylas-mail/packages/client-app/build/tasks/docs-render-task.js","isWriteAccess":false,"isDefinition":false},{"textSpan":{"start":6012,"length":4},"fileName":"D:/local/Temp/fuzzerWorkingDir/nylas-mail/packages/client-app/build/tasks/docs-render-task.js","isWriteAccess":false,"isDefinition":false},{"textSpan":{"start":6651,"length":4},"fileName":"D:/local/Temp/fuzzerWorkingDir/nylas-mail/packages/client-app/build/tasks/docs-render-task.js","isWriteAccess":false,"isDefinition":false}]}],"responseRequired":true}
{"command":"references-full","arguments":{"position":7100,"file":"D:/local/Temp/fuzzerWorkingDir/nylas-mail/packages/client-app/build/tasks/docs-render-task.js"},"type":"request","seq":42}
(Showing last 10 of 45 commands)
```

**Code** ([`packages\client-app\build\tasks\docs-render-task.js`](https://github.com/nylas/nylas-mail/blob/e16cb1982e944ae7edb69b1abef1436dd16b442d/packages/client-app/build/tasks/docs-render-task.js)):

```js
  
  function __guard__(value, transform) {
    return (typeof value !== 'undefined' && value !== null) ? transform(value) : undefined;
//                                                                                        ^
  }
  
```

**Hash**: 501532cb5a8efbfb07926374dce5b001
**Stack trace**: 
```
Error: Debug Failure. False expression.
    at Object.first (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:1173:18)
    at D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:116426:68
    at definitionToReferencedSymbolDefinitionInfo (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:116459:15)
    at D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:116348:113
    at Object.runWithCancellationToken (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:35406:28)
    at D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:116348:41
    at Object.mapDefined (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:712:30)
    at Object.findReferencedSymbols (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:116344:85)
    at Object.findReferences (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:139821:41)
    at D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:148010:68
```

_Originally posted by @typescript-bot in https://github.com/microsoft/tsserverfuzzer/issues/225#issuecomment-625423202_

**Comment by minestarks** [comment]
Note - this hasn't reproed since 4.0.0-dev.20200508  - would be good to confirm it was actually fixed.
