### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by hackers267** [microsoft/TypeScript#38789]
Issue Type: <b>Bug</b>

**TypeScript Version:** 4.0.0-dev.20200525
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at tryReuseStructureFromOldProgram (c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:100890:22)
    at Object.createProgram (c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:100509:30)
    at synchronizeHostData (c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:139751:26)
    at Object.getProgram (c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:139843:13)
    at InferredProject.Project.updateGraphWorker (c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:144334:53)
    at InferredProject.Project.updateGraph (c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:144277:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:146173:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:147667:26)
    at c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:147924:97
    at Object.flatMap (c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:482:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:147924:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:148787:46)
    at c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:150550:88
    at IOSession.Session.executeWithRequestId (c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:150541:28)
    at IOSession.Session.executeCommand (c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:150550:33)
    at IOSession.Session.onMessage (c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:150574:35)
    at Interface.<anonymous> (c:\Users\silen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.0.20200525\node_modules\typescript\lib\tsserver.js:151890:27)
    at Interface.emit (events.js:210:5)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
```

Extension version: 4.0.20200525
VS Code version: Code - Insiders 1.46.0-insider (2591ede95a52400d5d22989b16706f9b8b4831da, 2020-05-22T21:13:15.709Z)
OS version: Windows_NT x64 10.0.19628

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (7.32GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Similar call stack to #38559

@hackers267 Can you share a project or steps to reproduce the problem?

**Comment by mjbvz** [comment]
Closing as not actionable without more information

If you see this again with VS Code 1.53+ and TypeScript 4.15+, please let us know
