### ISSUE TITLE
JSX Format: Debug Failure. False expression: Token end is child end

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#38799]
**TypeScript Version:**  4.0.20200526

**Search Terms:**
- format
- jsx
- react

**Code**
For the tsx:

```tsx
const a = <div>
    // <a />
</div>
```

Run format

**Bug**

```
<syntax> TypeScript Server Error (4.0.0-dev.20200526)
Debug Failure. False expression: Token end is child end
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125554:34)
    at /Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125490:21
    at visitNode (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:18933:24)
    at Object.forEachChild (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:19342:24)
    at processNode (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125489:20)
    at processChildNode (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125560:21)
    at processChildNodes (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125623:48)
    at /Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125492:21
    at visitNodes (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:18938:24)
    at Object.forEachChild (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:19334:21)
    at processNode (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125489:20)
    at processChildNode (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125560:21)
    at /Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125490:21
    at visitNode (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:18933:24)
    at Object.forEachChild (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:19027:21)
    at processNode (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125489:20)
    at processChildNode (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125560:21)
    at processChildNodes (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125623:48)
    at /Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125492:21
    at visitNodes (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:18938:24)
    at Object.forEachChild (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:19187:24)
    at processNode (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125489:20)
    at formatSpanWorker (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125302:17)
    at /Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125283:208
    at Object.getFormattingScanner (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:123902:23)
    at formatSpan (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125283:31)
    at Object.formatSelection (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:125101:20)
    at Proxy.getFormattingEditsForRange (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:140173:34)
    at IOSession.Session.getFormattingEditsForRange (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:149899:45)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:148896:61)
    at /Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:150551:88
    at IOSession.Session.executeWithRequestId (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:150542:28)
    at IOSession.Session.executeCommand (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:150551:33)
    at IOSession.Session.onMessage (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:150575:35)
    at Interface.<anonymous> (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200526/node_modules/typescript/lib/tsserver.js:151891:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by orta** [comment]
It looks like the `//` in the JSX text is being interpreted as a comment in the JSX formatting scanner
