### ISSUE TITLE
TSX: "TypeError: Cannot read property 'flags' of undefined"

### ISSUE THREAD

**Issue by bluekeyes** [Microsoft/TypeScript#3903]
Compiling the following TSX code crashes `tsc` (1.5.3, revision 01244d60):

```typescript
/// <reference path="typings/react/react.d.ts" />
import React = require('react');

declare module BaseComponent {
    var base : React.Component<any, {}>;
    export = base;
}

class TestComponent extends React.Component<any, {}> {
    render() {
        return <BaseComponent />;
    }
}
```

```
$ tsc --module commonjs --jsx react test.tsx
/path/to/TypeScript/built/local/tsc.js:34402
                throw e;
                      ^
TypeError: Cannot read property 'flags' of undefined
    at getApparentType (/path/to/TypeScript/built/local/tsc.js:15667:21)
    at getPropertyOfType (/path/to/TypeScript/built/local/tsc.js:15750:20)
    at getTypeOfPropertyOfType (/path/to/TypeScript/built/local/tsc.js:14696:24)
    at getJsxElementAttributesType (/path/to/TypeScript/built/local/tsc.js:19383:46)
    at checkJsxOpeningLikeElement (/path/to/TypeScript/built/local/tsc.js:19458:40)
    at checkJsxSelfClosingElement (/path/to/TypeScript/built/local/tsc.js:19110:13)
    at checkExpressionWorker (/path/to/TypeScript/built/local/tsc.js:21715:28)
    at checkExpression (/path/to/TypeScript/built/local/tsc.js:21621:42)
    at checkExpressionCached (/path/to/TypeScript/built/local/tsc.js:21568:38)
    at /path/to/TypeScript/built/local/tsc.js:20877:32
```

Environment:
- tsc 1.5.3 (01244d60)
- React 0.13.3
- DefinitelyTyped React definitions (borisyankov/DefinitelyTyped@71abea7)
- node v0.10.38

I discovered this issue while trying to write type definitions for the [Griddle](http://griddlegriddle.github.io/Griddle/index.html) library. I'm new to TypeScript/TSX/React, so I apologize in advance if this is actually a problem with my code or with the React typings. The fact that the compiler crashed (and this is a new feature) suggested reporting here first.

**Comment by RyanCavanaugh** [comment]
Slightly confused on the posted repro. It's illegal to use `export = ` in an internal module, and it's illegal to have a `declare module "BaseComponent" {` in a file that contains imports/exports.

**Comment by RyanCavanaugh** [comment]
Got a working repro

**Comment by bluekeyes** [comment]
Sorry for the confusion - the `BaseComponent` module was originally in a `.d.ts` file and then the main file imported the defined object.
