### ISSUE TITLE
No auto-complete suggestions showing up, but Quick Fix has the correct import

### ISSUE THREAD

**Issue by drj17** [microsoft/TypeScript#39048]
Issue Type: <b>Bug</b>

1. Start adding React component tag. 
2. No suggestions show up
3. Right click to quick fix and correct import shows up

Example:
 ![example](https://user-images.githubusercontent.com/13426126/84402837-fb8c9e00-abd2-11ea-8dea-dfdf499080e7.gif)

I've tried on both the stable branch and the insider branch.  I've reinstalled vscode a couple times, removed all extensions, created a fresh tsconfig, nothing has seemed to work.

On every keypress I get this error in the developer console: 
```
  ERR <semantic> TypeScript Server Error (3.9.4)
Debug Failure.
Error: Debug Failure.
    at Object.getNameForExportedSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:110394:70)
    at pushSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113377:40)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113360:28
    at Map.forEach (<anonymous>)
    at getSymbolsFromOtherSourceFileExports (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113358:54)
    at getGlobalCompletions (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113117:49)
    at tryGetGlobalSymbols (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113028:25)
    at getCompletionData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:112804:17)
    at Object.getCompletionsAtPosition (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:112166:34)
    at Proxy.getCompletionsAtPosition (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138870:35)
    at IOSession.Session.getCompletions (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:148949:64)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:147886:61)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149517:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149526:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149550:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:150866:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17): Error: <semantic> TypeScript Server Error (3.9.4)
Debug Failure.
```

VS Code version: Code - Insiders 1.47.0-insider (6efc0b6950cef0dbed0a59c23c656a3f2cfb6403, 2020-06-11T05:45:05.735Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (3.65GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
@drj17 Can you please share steps to reproduce this (including example code as text)?

**Comment by DanielRosenwasser** [comment]
It's not reproing for me. We need more info on this (minimal repro, maybe some idea of how `Button` was declared

**Comment by jtsom** [comment]
For what it's worth I'm seeing the same problem with a all but stock Angular 10 application. The auto-imports are not working, and the quick-fix's don't even offer to add an import.

I have a simple class file:

```
export class Contact {
  name: string;
}
```

and am trying to use it:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/13488/86180831-e08abb00-bafa-11ea-9d0e-6f0158b9ec55.png">


My error indicated Typescript 4.0 dev, even though I have VSCode set to use 3.9.5
```
[2020-06-30 17:37:02.038] [renderer1] [error] <semantic> TypeScript Server Error (4.0.0-dev.20200629)
No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:145281:23)
    at ScriptInfo.getDefaultProject (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:146062:46)
    at ProjectService.doEnsureDefaultProjectForFile (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:148858:48)
    at ProjectService.ensureDefaultProjectForFile (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:148853:75)
    at IOSession.Session.getFileAndProjectWorker (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:152892:87)
    at IOSession.Session.getFileAndProject (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:152875:29)
    at IOSession.Session.getApplicableRefactors (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:153331:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:152122:61)
    at /Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:153634:88
    at IOSession.Session.executeWithRequestId (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:153625:28)
    at IOSession.Session.executeCommand (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:153634:33)
    at IOSession.Session.onMessage (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:153658:35)
    at Interface.<anonymous> (/Users/john/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.0.20200629/node_modules/typescript/lib/tsserver.js:155873:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17): Error: <semantic> TypeScript Server Error (4.0.0-dev.20200629)
```

**Comment by DanielRosenwasser** [comment]
@jtsom I think that might pertain more to #39488 since you're seeing a different call stack.

**Comment by jtsom** [comment]
I actually haven't seen this exception recently. Not sure what changed to fix/stop it. Still seeing the referenced missing auto-complete / fixes.

**Comment by logicbomb421** [comment]
I'm getting this pretty regularly now. I've had to restart the extension host probably 25+ times today, as this seems to crash the host, which doesn't auto-recover for some reason.

<details>
<summary>Here is the full error message I get</summary>

```
[2020-07-27 22:24:38.691] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2020-07-27 22:24:38.691] [exthost] [error] Error: <semantic> TypeScript Server Error (3.9.6)
Debug Failure.
Error: Debug Failure.
    at Object.getNameForExportedSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:110421:70)
    at pushSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113404:40)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113387:28
    at Map.forEach (<anonymous>)
    at getSymbolsFromOtherSourceFileExports (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113385:54)
    at getGlobalCompletions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113144:49)
    at tryGetGlobalSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113055:25)
    at getCompletionData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:112849:22)
    at Object.getCompletionsAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:112193:34)
    at Proxy.getCompletionsAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138897:35)
    at IOSession.Session.getCompletions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:148976:64)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:147913:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149553:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149544:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149553:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149577:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:150893:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
	at Function.create (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:55161)
	at h.dispatchResponse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:227777)
	at h.dispatchMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:226697)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:226173
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
	at l.onLengthData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:235493)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:235141)
	at Socket.emit (events.js:203:13)
	at Socket.EventEmitter.emit (domain.js:476:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```
</details>

I am using a `tsconfig.json` that lives in the root of my project. Not sure if this is the same `semantic` being mentioned in the error, but I also have the following semantic syntax highlighting settings set (user level):

```
"editor.semanticTokenColorCustomizations": {
  "enabled": true, // enable semantic highlighting for all themes
  "rules": {
    "property.readonly": "#C364FF",
    "*.modification": { "bold": true },
    "*.declaration": { "underline": true },
    "parameter": { "italic": true },
    "enum": "#CCFF00",
    "enumMember": { "foreground": "#ccff00" }
  }
}
```

#### VSCode Info
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z (1 wk ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

My current workaround is `Cmd+Shift+P -> Developer: Reload Window`, which, while works, really isn't fun to have to do every 10-15m.

Please let me know if I can provide anymore diagnostic info. Thanks!

**Comment by andrewbranch** [comment]
@logicbomb421 if you have exact steps that can reproduce this, and/or if you can share the repo you’re working in, that would be great. I’m 99% sure the problem depends on the declaration of something that auto-import sees elsewhere in your program, so note that the steps you take in a particular file probably aren’t enough to reproduce it. We need to know what other modules are in your program (including node_modules), which is why this will be tricky to reproduce without sharing a full project.

**Comment by andrewbranch** [comment]
Assuming this has been fixed unknowingly in the last 2 years. New reports always welcome in a new issue.
