### ISSUE TITLE
Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isLeftHandSideExpression'.

### ISSUE THREAD

**Issue by minestarks** [microsoft/TypeScript#39192]
**Repo Name**: https://github.com/facebook/react.git

**Revision**: 6ba25b96df5d4179bf8aba3c3fe1ace3dce28234

**TypeScript Version**: 4.0.0-dev.20200622

**Commands**: 

```
{"responseRequired":false}
{"command":"quickinfo-full","arguments":{"position":1023,"file":"D:/local/Temp/fuzzerWorkingDir/react/fixtures/dom/src/components/fixtures/date-inputs/switch-date-test-case.js"},"type":"request","seq":7}
{"response":{"kind":"method","kindModifiers":"declare","textSpan":{"start":1014,"length":11},"displayParts":[{"text":"(","kind":"punctuation"},{"text":"method","kind":"text"},{"text":")","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"Date","kind":"localName"},{"text":".","kind":"punctuation"},{"text":"toISOString","kind":"methodName"},{"text":"(","kind":"punctuation"},{"text":")","kind":"punctuation"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"string","kind":"keyword"}],"documentation":[{"text":"Returns a date as a string value in ISO format.","kind":"text"}]},"responseRequired":true}
{"command":"quickinfo-full","arguments":{"position":471,"file":"D:/local/Temp/fuzzerWorkingDir/react/fixtures/dom/src/components/fixtures/date-inputs/switch-date-test-case.js"},"type":"request","seq":8}
{"response":{"kind":"","kindModifiers":"","textSpan":{"start":471,"length":1},"displayParts":[{"text":"any","kind":"keyword"}]},"responseRequired":true}
{"command":"definition-full","arguments":{"position":1023,"file":"D:/local/Temp/fuzzerWorkingDir/react/fixtures/dom/src/components/fixtures/date-inputs/switch-date-test-case.js"},"type":"request","seq":9}
{"response":[{"fileName":"D:/home/site/wwwroot/node_modules/typescript/lib/lib.es5.d.ts","textSpan":{"start":37072,"length":11},"kind":"method","name":"toISOString","containerName":"Date","contextSpan":{"start":37072,"length":22},"isLocal":false}],"responseRequired":true}
{"command":"definition-full","arguments":{"position":471,"file":"D:/local/Temp/fuzzerWorkingDir/react/fixtures/dom/src/components/fixtures/date-inputs/switch-date-test-case.js"},"type":"request","seq":10}
{"response":[],"responseRequired":true}
{"command":"references-full","arguments":{"position":1023,"file":"D:/local/Temp/fuzzerWorkingDir/react/fixtures/dom/src/components/fixtures/date-inputs/switch-date-test-case.js"},"type":"request","seq":11}
(Showing last 10 of 499 commands)
```

**Code** ([`fixtures\dom\src\components\fixtures\date-inputs\switch-date-test-case.js`](https://github.com/facebook/react/blob/6ba25b96df5d4179bf8aba3c3fe1ace3dce28234/fixtures/dom/src/components/fixtures/date-inputs/switch-date-test-case.js)):

```js
        return {
          type: 'datetime-local',
          value: this.state.date.toISOString().replace(/\..*Z/, ''),
//                                        ^
        };
      } else {
```

**Hash**: b5872fd7b1bdd15e2a1ef4359314b5b3
**Stack trace**: 
```
Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isLeftHandSideExpression'.
    at Object.cast (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:1554:25)
    at Object.parenthesizeLeftSideOfAccess (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:19311:73)
    at Object.createElementAccessExpression (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:21125:52)
    at getSyntheticElementAccess (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:48818:70)
    at getFlowTypeOfDestructuring (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:48809:29)
    at getTypeForBindingElement (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:48892:28)
    at getTypeForVariableLikeDeclaration (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:48967:24)
    at getWidenedTypeForVariableLikeDeclaration (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:49419:56)
    at getTypeOfVariableOrParameterOrPropertyWorker (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:49551:24)
    at getTypeOfVariableOrParameterOrProperty (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:49456:28)
```

_Originally posted by @typescript-bot in https://github.com/microsoft/tsserverfuzzer/issues/238#issuecomment-647426426_

**Comment by minestarks** [comment]
Duplicated the other bug by accident.. closing

**Comment by minestarks** [comment]
Closed the wrong issue by accident... reactivating

**Comment by minestarks** [comment]
FYI the last time this reproed was on 4.0.0-dev.20200707 . It may have been fixed.

**Comment by minestarks** [comment]
OK got a repro again - https://github.com/microsoft/tsserverfuzzer/issues/282
