### ISSUE TITLE
[Emitter] Cannot read property 'kind' of undefined 

### ISSUE THREAD

**Issue by pcan** [Microsoft/TypeScript#3932]
I'm trying to emit metadata for the following class:

```
@Component()
export class MyClass {

    constructor(test: string, test2: string) {

    }

    @log
    doSomething() {

    }
}


function log(target: Object, key: string, value: any) {
    return {
        value: function(...args: any[]) {
            var a = args.map(a => JSON.stringify(a)).join();
            var result = value.value.apply(this, args);
            var r = JSON.stringify(result);
            console.log(`Call: ${key}(${a}) => ${r}`);
            return result;
        }
    };
}

function Component(name?: string) {
    return (target: any) => {
        target.__name__ = name;
    }
}
```

I'm getting the error when compiling; the issue seems related to a missing null-check [here](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/emitter.ts#L4846).
I looked at this in debug mode, and the "type" member of the outer node object is missing [here](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/emitter.ts#L5013)

The full stack:

```
 TypeError: Cannot read property 'kind' of undefined
  at emitSerializedTypeNode (typescriptServices.js:32336:29)
  at emitSerializedReturnTypeOfNode (typescriptServices.js:32477:21)
  at emitSerializedTypeMetadata (typescriptServices.js:32513:25)
  at emitDecoratorsOfMembers (typescriptServices.js:32219:21)
  at emitDecoratorsOfClass (typescriptServices.js:32082:17)
  at emitClassLikeDeclarationBelowES6 (typescriptServices.js:32042:17)
  at emitClassLikeDeclaration (typescriptServices.js:31833:21)
  at emitClassDeclaration (typescriptServices.js:31829:24)
  at emitJavaScriptWorker (typescriptServices.js:34050:32)
  at emitNodeWithoutSourceMap (typescriptServices.js:33860:17)
  at emitNodeWithSourceMap (typescriptServices.js:28602:29)
  at emitLinesStartingAt (typescriptServices.js:28757:21)
  at emitAMDModule (typescriptServices.js:33629:17)
  at emitSourceFileNode (typescriptServices.js:33826:25)
  at emitJavaScriptWorker (typescriptServices.js:34068:32)
  at emitNodeWithoutSourceMap (typescriptServices.js:33860:17)
```

**Comment by mhegazy** [comment]
@pcan please feel free to send a PR for this.

**Comment by mhegazy** [comment]
thanks @pcan
