### ISSUE TITLE
The Playground website appears to be broken

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#3958]
http://www.typescriptlang.org/Playground

Here's a small sample of the errors being thrown when loading the page:
```
GET http://www.typescriptlang.org/Script/vs/base/collections.js 404 (Not Found)
editor.main.js:51 Loading "vs/languages/typescript/typescriptWorker2.nls" failede._consoleLog @ editor.main.js:51e._onmessage @ editor.main.js:51e._onSerializedMessage @ editor.main.js:51(anonymous function) @ editor.main.js:51h.worker.onmessage @ editor.main.js:51
editor.main.js:51 ["Detail: ", Object]e._consoleLog @ editor.main.js:51e._onmessage @ editor.main.js:51e._onSerializedMessage @ editor.main.js:51(anonymous function) @ editor.main.js:51h.worker.onmessage @ editor.main.js:51
editor.main.js:51 Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://www.typescriptlang.org/Script/vs/base/collections.js' failed to load.
    at Error (native)
    at e._load (http://www.typescriptlang.org/Script/vs/loader.js:4:23421)
    at http://www.typescriptlang.org/Script/vs/loader.js:4:23251e._consoleLog @ editor.main.js:51e._onmessage @ editor.main.js:51e._onSerializedMessage @ editor.main.js:51(anonymous function) @ editor.main.js:51h.worker.onmessage @ editor.main.js:51
editor.main.js:51 Here are the modules that depend on it:e._consoleLog @ editor.main.js:51e._onmessage @ editor.main.js:51e._onSerializedMessage @ editor.main.js:51(anonymous function) @ editor.main.js:51h.worker.onmessage @ editor.main.js:51
editor.main.js:51 ["===anonymous14==="]
```

**Comment by RyanCavanaugh** [comment]
Working fine for me. Try doing a cache clear / hard reload?

**Comment by jonathandturner** [comment]
What browser are you using?

You may need to clear your browser cache and reload, as I recently updated the browser to the newest version.

**Comment by sccolbert** [comment]
Hard reloading worked. Running on Chrome, where I usually only get stale cache for localhost. Weird.

Thanks, and sorry for the noise!
