### ISSUE TITLE
Property 'raw' does not exist on type

### ISSUE THREAD

**Issue by lygstate** [microsoft/TypeScript#39714]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

const x =String.raw`ALLUSERSPROFILE=C:\ProgramData`

```

**Expected behavior:**
Run
**Actual behavior:**
```

[Running] ts-node "e:\CI-Cor-Ready\study\cmake-test\gen-env.ts"

C:\Users\lygstate\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
gen-env.ts(2,17): error TS2339: Property 'raw' does not exist on type 'StringConstructor'.

    at createTSError (C:\Users\lygstate\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:434:12)
    at reportTSError (C:\Users\lygstate\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:438:19)
    at getOutput (C:\Users\lygstate\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:578:36)
    at Object.compile (C:\Users\lygstate\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:775:32)
    at Module.m._compile (C:\Users\lygstate\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\lygstate\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/mo
```
**Playground Link:** 

**Related Issues:**

**Comment by IllusionMH** [comment]
Looks like you don't have proper target, This should work with `"target": "es2015"` or higher (default is `es3` if omitted)

[Playground](https://www.staging-typescript.org/play?target=2#code/MYewdgzgLgBAHgLhtATgSzAcxgXhgZSnSwDoUBDAdwAMBBAGXoFV8BRAJXwAV2B5AMQCS9VjgDCCADpcUITBQC2AEXJRy1ANwBYAFBA)

**Comment by lygstate** [comment]
gotcha.
