### ISSUE TITLE
TypeError: Cannot read property 'exportSymbol' of undefined     at getTypeOfSymbolAtLocation

### ISSUE THREAD

**Issue by minestarks** [microsoft/TypeScript#39835]
**Repo Name**: https://github.com/carbon-app/carbon.git

**Revision**: 00dac2dbb804f587655a78212f2a9d5f6f5efa9b

**TypeScript Version**: 4.0.0-dev.20200724

**Commands**: 

```
{"responseRequired":true}
{"command":"definition-full","arguments":{"position":127,"file":"D:/local/Temp/fuzzerWorkingDir/carbon/components/Slider.js"},"type":"request","seq":9}
{"response":[{"fileName":"D:/local/Temp/fuzzerWorkingDir/carbon/components/Slider.js","textSpan":{"start":118,"length":12},"kind":"property","name":"defaultProps","containerName":"Slider","contextSpan":{"start":111,"length":95},"isLocal":true}],"responseRequired":true}
{"command":"definition-full","arguments":{"position":1960,"file":"D:/local/Temp/fuzzerWorkingDir/carbon/components/Slider.js"},"type":"request","seq":10}
{"response":[],"responseRequired":true}
{"command":"references-full","arguments":{"position":127,"file":"D:/local/Temp/fuzzerWorkingDir/carbon/components/Slider.js"},"type":"request","seq":11}
{"response":[{"definition":{"containerKind":"","containerName":"","fileName":"D:/local/Temp/fuzzerWorkingDir/carbon/components/Slider.js","kind":"property","name":"(property) Slider.defaultProps: {\n    onMouseDown: () => void;\n    onMouseUp: () => void;\n    unit: string;\n}","textSpan":{"start":118,"length":12},"displayParts":[{"text":"(","kind":"punctuation"},{"text":"property","kind":"text"},{"text":")","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"Slider","kind":"className"},{"text":".","kind":"punctuation"},{"text":"defaultProps","kind":"propertyName"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"{","kind":"punctuation"},{"text":"\n","kind":"lineBreak"},{"text":"    ","kind":"space"},{"text":"onMouseDown","kind":"propertyName"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"(","kind":"punctuation"},{"text":")","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"=>","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"void","kind":"keyword"},{"text":";","kind":"punctuation"},{"text":"\n","kind":"lineBreak"},{"text":"    ","kind":"space"},{"text":"onMouseUp","kind":"propertyName"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"(","kind":"punctuation"},{"text":")","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"=>","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"void","kind":"keyword"},{"text":";","kind":"punctuation"},{"text":"\n","kind":"lineBreak"},{"text":"    ","kind":"space"},{"text":"unit","kind":"propertyName"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"string","kind":"keyword"},{"text":";","kind":"punctuation"},{"text":"\n","kind":"lineBreak"},{"text":"}","kind":"punctuation"}],"contextSpan":{"start":111,"length":95}},"references":[{"textSpan":{"start":118,"length":12},"fileName":"D:/local/Temp/fuzzerWorkingDir/carbon/components/Slider.js","contextSpan":{"start":111,"length":95},"isWriteAccess":true,"isDefinition":true}]}],"responseRequired":true}
{"command":"references-full","arguments":{"position":1960,"file":"D:/local/Temp/fuzzerWorkingDir/carbon/components/Slider.js"},"type":"request","seq":12}
{"response":[],"responseRequired":true}
{"command":"completions-full","arguments":{"position":127,"file":"D:/local/Temp/fuzzerWorkingDir/carbon/components/Slider.js","includeExternalModuleExports":true,"includeInsertTextCompletions":true},"type":"request","seq":13}
(Showing last 10 of 15039 commands)
```

**Code** ([`components\Slider.js`](https://github.com/carbon-app/carbon/blob/00dac2dbb804f587655a78212f2a9d5f6f5efa9b/components/Slider.js)):

```js
                height: 33px;
                width: 100%;
                background: ${COLORS.DARK_GRAY};
//           ^
              }
            `}
```

**Hash**: 5d7e1bb7851b8c2056b436ceeed65053
**Stack trace**: 
```
TypeError: Cannot read property 'exportSymbol' of undefined
    at getTypeOfSymbolAtLocation (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:62492:29)
    at Object.getTypeOfSymbolAtLocation (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:42570:35)
    at D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:117157:130
    at Object.flatMap (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:707:25)
    at tryGetClassLikeCompletionSymbols (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:117155:42)
    at tryGetGlobalSymbols (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:116518:24)
    at getCompletionData (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:116314:22)
    at Object.getCompletionsAtPosition (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:115656:34)
    at Object.getCompletionsAtPosition (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:143958:35)
    at Session.getCompletions (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:154335:64)
```

_Originally posted by @typescript-bot in https://github.com/microsoft/tsserverfuzzer/issues/223#issuecomment-663653640_

**Comment by WilcoKruijer** [comment]
I think I found the same or a similar issue. Stacktrace:

```
TypeError: Cannot read property 'exportSymbol' of undefined
    at getExport (/usr/local/lib/node_modules/typescript/lib/tsserver.js:126701:28)
    at Object.getImportOrExportSymbol (/usr/local/lib/node_modules/typescript/lib/tsserver.js:126696:53)   
    at getImportOrExportReferences (/usr/local/lib/node_modules/typescript/lib/tsserver.js:128302:56)
    at getReferencesAtLocation (/usr/local/lib/node_modules/typescript/lib/tsserver.js:128232:17)
    at getReferencesInContainer (/usr/local/lib/node_modules/typescript/lib/tsserver.js:128172:21)
    at getReferencesInSourceFile (/usr/local/lib/node_modules/typescript/lib/tsserver.js:128159:24)
    at searchForName (/usr/local/lib/node_modules/typescript/lib/tsserver.js:127953:21)
    at getReferencesInContainerOrFiles (/usr/local/lib/node_modules/typescript/lib/tsserver.js:127724:25)  
    at getReferencedSymbolsForSymbol (/usr/local/lib/node_modules/typescript/lib/tsserver.js:127708:21)
    at Object.getReferencedSymbolsForNode (/usr/local/lib/node_modules/typescript/lib/tsserver.js:127474:34)
    at Object.findReferencedSymbols (/usr/local/lib/node_modules/typescript/lib/tsserver.js:127073:42)
    at Object.findReferences (/usr/local/lib/node_modules/typescript/lib/tsserver.js:153497:41)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:163017:68
    at callbackProjectAndLocation (/usr/local/lib/node_modules/typescript/lib/tsserver.js:163121:13)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:163058:24
    at forEachProjectInProjects (/usr/local/lib/node_modules/typescript/lib/tsserver.js:163040:17)
    at combineProjectOutputWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:163055:13)
    at combineProjectOutputForReferences (/usr/local/lib/node_modules/typescript/lib/tsserver.js:162999:13)
    at IOSession.Session.getReferences (/usr/local/lib/node_modules/typescript/lib/tsserver.js:164340:34)  
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:163349:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:165211:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:165202:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:165211:33) 
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:165237:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:167834:31)
    at Interface.emit (events.js:375:28)
    at Interface._onLine (readline.js:364:10)
    at Interface._normalWrite (readline.js:509:12)
    at Socket.ondata (readline.js:216:10)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
    at handleResponse (/home/wkruijer/mt/code/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48) 
    at processMessageQueue (/home/wkruijer/mt/code/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
    at Immediate.<anonymous> (/home/wkruijer/mt/code/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
    at processImmediate (internal/timers.js:464:21)
```

Not sure what the exact reproduction is but it seems to happen (sometimes) in some source files of NodeJS.

Seems to happen on lines that mostly look like: `const { Buffer } = require('buffer');`. 

Subset of files that include the above line of code and result in this stacktrace (in the NodeJS source):

- lib/internal/streams/writable.js
- lib/internal/streams/readable.js
- internal/streams/from.js
- internal/streams/buffer_list.js
- lib/internal/source_map/source_map_cache.js
- ...

I know this is a bit vague, but I hope it can help someone looking into this in the future.

**Comment by RyanCavanaugh** [comment]
I believe this was fixed. If not, please open a new issue. Thanks!
