### ISSUE TITLE
Debug Failure. Did not expect SourceFile to have an Identifier in its trivia  at addSyntheticNodes

### ISSUE THREAD

**Issue by minestarks** [microsoft/TypeScript#39854]
**Repo Name**: https://github.com/babel/babel.git

**Revision**: 231328aafcb49bccada97bd6407fa66dd4235af3

**TypeScript Version**: 4.0.0-dev.20200731

**Commands**: 

```
{"response":{"canRename":false,"localizedErrorMessage":"You cannot rename this element."},"responseRequired":true}
{"command":"rename-full","arguments":{"position":3,"file":"D:/local/Temp/fuzzerWorkingDir/babel/packages/babel-plugin-transform-for-of/test/fixtures/loose/member-expression/input.js"},"type":"request","seq":22}
{"response":{"canRename":false,"localizedErrorMessage":"You cannot rename this element."},"responseRequired":true}
{"command":"rename-full","arguments":{"position":23,"file":"D:/local/Temp/fuzzerWorkingDir/babel/packages/babel-plugin-transform-for-of/test/fixtures/loose/member-expression/input.js"},"type":"request","seq":24}
{"response":{"canRename":false,"localizedErrorMessage":"You cannot rename this element."},"responseRequired":true}
{"command":"rename-full","arguments":{"position":23,"file":"D:/local/Temp/fuzzerWorkingDir/babel/packages/babel-plugin-transform-for-of/test/fixtures/loose/member-expression/input.js"},"type":"request","seq":25}
{"response":{"canRename":false,"localizedErrorMessage":"You cannot rename this element."},"responseRequired":true}
{"command":"rename-full","arguments":{"position":7,"file":"D:/local/Temp/fuzzerWorkingDir/babel/packages/babel-plugin-transform-for-of/test/fixtures/loose/member-expression/input.js"},"type":"request","seq":22}
{"response":{"canRename":true,"kind":"let","displayName":"obj","fullDisplayName":"obj","kindModifiers":"","triggerSpan":{"start":5,"length":3}},"responseRequired":true}
{"command":"renameLocations-full","arguments":{"position":7,"file":"D:/local/Temp/fuzzerWorkingDir/babel/packages/babel-plugin-transform-for-of/test/fixtures/loose/member-expression/input.js"},"type":"request","seq":23}
(Showing last 10 of 3561 commands)
```

**Code** ([`packages\babel-plugin-transform-for-of\test\fixtures\loose\member-expression\input.js`](https://github.com/babel/babel/blob/231328aafcb49bccada97bd6407fa66dd4235af3/packages/babel-plugin-transform-for-of/test/fixtures/loose/member-expression/input.js)):

```js
  for (obj.prop of arr) {
//       ^
  
  }
```

**Hash**: 9f2f5f508e08c87fe57f2334abecc90b
**Stack trace**: 
```
Error: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
    at addSyntheticNodes (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:142954:30)
    at createSyntaxList (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:142970:13)
    at processNodes (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:142933:27)
    at visitNodes (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:27020:24)
    at Object.forEachChild (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:27262:24)
    at SourceFileObject.NodeObject.forEachChild (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:142910:23)
    at createChildren (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:142942:14)
    at SourceFileObject.NodeObject.getChildren (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:142887:56)
    at getTokenAtPositionWorker (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:112212:43)
    at getTouchingToken (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:112199:16)
```

_Originally posted by @typescript-bot in https://github.com/microsoft/tsserverfuzzer/issues/243#issuecomment-667161331_

**Comment by mosesoak** [comment]
Hi, I can report at least one case of this happening in the wild. 

These errors are thrown by a VS Code extension running on Windows WSL Ubuntu:
```
[Error - 11:13:49 AM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
  Code: -32603 
[Error - 11:13:49 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
  Code: -32603 
[Error - 11:13:49 AM] Request textDocument/colorPresentation failed.
  Message: Request textDocument/documentColor failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
  Code: -32603 
[Error - 11:13:49 AM] Request textDocument/colorPresentation failed.
  Message: Request textDocument/documentColor failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
  Code: -32603 
[Error - 11:13:50 AM] (node:1558) UnhandledPromiseRejectionWarning: Error: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
    at addSyntheticNodes (/home/mg/.vscode-server/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/node_modules/typescript/lib/typescript.js:134835:30)
    at createChildren (/home/mg/.vscode-server/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/node_modules/typescript/lib/typescript.js:134824:9)
    at SourceFileObject.NodeObject.getChildren (/home/mg/.vscode-server/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/node_modules/typescript/lib/typescript.js:134768:56)
    at walk (/home/mg/.vscode-server/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-utils.js:47:14)
    at findStyledJsxTaggedTemplate (/home/mg/.vscode-server/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-utils.js:73:5)
    at Object.getStyledJsx (/home/mg/.vscode-server/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-utils.js:127:40)
    at /home/mg/.vscode-server/extensions/southclaws.vscode-styled-jsx-languageserver-1.1.2/server/out/styled-jsx-server-main.js:128:44
[Error - 11:13:50 AM] (node:1558) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 11:13:50 AM] (node:1558) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 11:13:50 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
  Code: -32603 
[Error - 11:13:52 AM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
  Code: -32603 
[Error - 11:13:52 AM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
  Code: -32603 
[Error - 11:13:52 AM] Request textDocument/colorPresentation failed.
  Message: Request textDocument/documentColor failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
  Code: -32603 
[Error - 11:13:58 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
  Code: -32603 
```

The phrase `Did not expect SourceFile to have an Identifier in its trivia` is opaque, so it's unclear whether this is a potential error in the extension or directly relates to this Typescript issue. [Here's a link to the TS version in their package.json.](https://github.com/Southclaws/vscode-styled-jsx-languageserver/blob/master/package.json#L46)

**Comment by andrewbranch** [comment]
@mosesoak this error usually occurs when trying to perform actions on a file that contains syntax errors. Do you happen to have the contents of the file you were editing when this error was logged?

**Comment by andrewbranch** [comment]
My fix for Mine’s repro involves a parser/scanner change, which I don’t want to do after the beta period, so I’m bumping this to 4.2.

**Comment by Divlo** [comment]
@andrewbranch The errors occurs even if i'm performing action on a file that doesn't contains syntax errors.
I'm developing the `vscode-styled-jsx` extensions and the error happens when I add an `interface` declaration.

As you can see on that gif, if there isn't `interface`, everything works fine, I can hover my css attributes and get mdn documentation for example (since it's how the extension works) but as soon as I add an interface, I've got that error :
![Peek 2020-10-15 14-40](https://user-images.githubusercontent.com/25207499/96128470-ae5c6800-0ef5-11eb-9098-b535f84a60c3.gif)

The errors occurs when I'm executing something like this :
```ts
const source = ts.createSourceFile(
  'tmp',
  textDocument.getText(),
  ts.ScriptTarget.Latest,
  true,
  ts.ScriptKind.JSX | ts.ScriptKind.TSX
)

source.getChildren()
```

I hope this can help.

**Comment by andrewbranch** [comment]
@Divlo can you paste the exact source file text that triggers the error? I think you’ve cracked the case wide open 🕵️ 

> The errors occurs even if i'm performing action on a file that doesn't contains syntax errors.

Ah, but it _does_ contain syntax errors, because `ts.ScriptKind` is not a bitmask—you should just be using `ts.ScriptKind.TSX`. The result is that we are not expecting to parse JSX, so there are all sorts of syntax errors that are not visible to you.

**Comment by Divlo** [comment]
Thank you very much @andrewbranch, that solved my issue.
Instead of `ts.ScriptKind.JSX | ts.ScriptKind.TSX` it's only `ts.ScriptKind.TSX`.

**Comment by andrewbranch** [comment]
@Divlo yes, but we still should not have _crashed_ when you send the wrong ScriptKind, so can you post the whole text of that source file where you reproduced the crash so we can fix the bug? 🙏

**Comment by Divlo** [comment]
Sure, here it is :
```tsx
interface Test {}

const Header = () => (
  <div>
    <h1>Header</h1>
    <style jsx>
      {`
        h1 {
          color: red;
        }
      `}
    </style>
    <div>
      <h1>Header</h1>
      <style jsx>{`
        .root {
          max-width: 760px;
          padding-top: 5px;
        }
      `}</style>
    </div>
  </div>
)```

**Comment by andrewbranch** [comment]
Perfect, all I needed was the file content itself, but this is great. Thanks @Divlo!

**Comment by nonara** [comment]
Not sure if this should be expected behaviour, but I ran into this with the compiler API too.

```ts
const transformFactory = ts.createNodeFactory(NodeFactoryFlags.NoNodeConverters, ts.createBaseNodeFactory());

const f = ts.createSourceFile('abc.ts', `export type A = string;`, ScriptTarget.ES5, true);
const { transformed: [ transformedFile ]} = ts.transformNodes(
  /* resolver */ undefined,
  /* host */ undefined,
  transformFactory,
  /* options */ {},
  /* nodes */ [f],
  /* transformers */ [ ts.transformTypeScript ],
  false
);

transformedFile.getChildren() // throws Error: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
```

Adding / changing resolver, host, and transformers do not appear to make a difference. Should `getChildren` et al be able to be used with transformed nodes?

**Comment by andrewbranch** [comment]
No, because `getChildren()` calls the scanner on the source file text in order to fill in token information that otherwise doesn’t need to be represented in the parse tree. For synthesized nodes, you should use `ts.forEachChild` instead.

**Comment by nonara** [comment]
@andrewbranch Got it! Thanks.

**Comment by mosesoak** [comment]
@andrewbranch sorry I missed your message back in September -- glad you guys found a fix for this!
