### ISSUE TITLE
VS 2015 RTM crash on opening ts file

### ISSUE THREAD

**Issue by ChrisTorng** [Microsoft/TypeScript#4011]
VS 2015 RTM crash on opening ts file. A lot of following errors in ActivityLog.xml:

System.Runtime.InteropServices.COMException (0x80020006): 不明的名稱。 (Exception from HRESULT: 0x80020006 (DISP_E_UNKNOWNNAME))
at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.Reflection.InvokeMethod[T](Object languageService, String methodName, Object[] arguments)
at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.AbstractProxy'1.InvokeShimMethod[T](String methodName, Object[] arguments)
at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.ClassifierProxy.GetLexicalClassifications(String text, Int32 lexState)
at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetLexicalClassifications(ClassifierProxy classifier, String text, Int32 lineNum)
at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetClassifications(NormalizedSnapshotSpanCollection spans, List'1 result)
at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Classifier.GetTags(NormalizedSnapshotSpanCollection spans)
at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator'1.<GetTagsForBuffer>d__38.MoveNext()

I have uninstall all old TS versions (1.3/1.4), install TS 1.5.2.0 for 2013, then upgrade VS 2015 RC to VS 2015 RTM, it installs TS 1.5.3.0 for 2015. This problem happens only in VS 2015. I've repair TS 1.5.3.0 for 2015, with no luck. Had forgotten when upgrade VS 2013 Update 5. Maybe around install TS 1.5.2.0 for 2013.

**Comment by vladima** [comment]
@ChrisTorng   can you share typescriptServices.js file from your machine? It should be located in `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript\typescriptServices.js`

**Comment by ChrisTorng** [comment]
It's created date is 2015/7/15, size is 2,446,477 bytes.
https://onedrive.live.com/redir?resid=7E615CF7BC5DB818!44822&authkey=!AHJ1BSZURjoa4oo&ithint=file%2czip

**Comment by elitecoder74** [comment]
Any movement on this issue?

**Comment by elitecoder74** [comment]
I'm not sure which key in the registry fixed this issue for me, but I deleted both of the following:
HKEY_CURRENT_USER\Software\Microsoft\VisualStudio
[HKEY_CURRENT_USER\Software\Microsoft\VSCommon

Therefore the issue appears to be profile related.  I hope this helps.

**Comment by ChrisTorng** [comment]
As the information @elitecoder74 provided, I found the solution.

In HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\TypeScriptLanguageService, there are three keys:
CustomTypeScriptServicesFileLocation=C:\Users\xxx\Source\Repos\ngconf2015demo\tsc\typescriptServices.js
CustomDefaultLibraryLocation=C:\Users\xxx\Source\Repos\ngconf2015demo\tsc\lib.d.ts
CustomDefaultES6LibraryLocation"=C:\Users\xxx\Source\Repos\ngconf2015demo\tsc\lib.es6.d.ts

That is setted by https://github.com/Microsoft/ngconf2015demo 's https://github.com/Microsoft/ngconf2015demo/blob/master/vs/VSDevMode.ps1 .

Just delete these keys makes VS alive!

I didn't see "EnableDevMode" key setted by VSDevMode.ps1 in regedit. Maybe just been deleted by VS 2015 RTM's installer.
