### ISSUE TITLE
TypeScript 4.0 broken on Node.js 6

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#40166]
```
> volta install node@6
success: installed and set node@6.17.1 (with npm@3.10.10) as default                                                                                                      
> tsc
\tsc.js:5962
    var textToKeyword = new ts.Map(ts.getEntries(textToKeywordObj));
                        ^

TypeError: Iterator value undefined is not an entry object
    at new Map (native)
    at ts (tsc.js:5962:25)
    at Object.<anonymous> (tsc.js:7884:3)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
```

**Comment by RyanCavanaugh** [comment]
It doesn't seem like anyone cares and this is even further out of the support window; closing.
