### ISSUE TITLE
NullReferenceException when the project only contains definitions

### ISSUE THREAD

**Issue by chilversc** [Microsoft/TypeScript#4017]
If a project only contains definition files and the option "Redirect JavaScript output to a directory" is set then VsTsc fails with a NullReferenceException.

    The "VsTsc" task failed unexpectedly.
    System.NullReferenceException: Object reference not set to an instance of an object.
       at TypeScript.Tasks.VsTsc.ComputeCommonDirectoryPath()
       at TypeScript.Tasks.VsTsc.GenerateOutputPaths()
       at TypeScript.Tasks.VsTsc.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
       at Microsoft.Build.Utilities.ToolTask.Execute()
       at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
       at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()

# Steps to repoduce
1. Create a new TypeScript project.
2. Set "Redirect JavaScript output to directory" to "Compiled".
3. Delete all TypeScript  files in the project.
4. Create a single, empty file named `test.d.ts`
5. Build the project.

See https://gist.github.com/chilversc/4de3f276615982982849

**Comment by aleksey-bykov** [comment]
can't help it, get that non-nullable types request done already or go functional

**Comment by paulvanbrenk** [comment]
@chilversc Which version of VS are you using?

**Comment by chilversc** [comment]
VS 2013, I think it's SP3. Though I left SP4 installing the other day so unfortunately can't confirm that.

**Comment by chilversc** [comment]
Oh, out by 1, was probably SP4, and just installed SP5

**Comment by paulvanbrenk** [comment]
Noticed this also happens in VS 2015. Checked in a fix for both.
