### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined (at checkFunctionOrConstructorSymbol)

### ISSUE THREAD

**Issue by bagbag** [microsoft/TypeScript#40261]
**TypeScript Version:** 3.2 to 4.1.0-dev.20200826

Last working version is 3.1.6. All tested versions after that (several from 3.2 to latest nightly) have this issue.

**Search Terms:**
Cannot read property 'kind' of undefined
checkFunctionOrConstructorSymbol

**Code**

```ts
/// <reference types="video.js" />

declare function videojs(id: any): any;
```

[https://github.com/bagbag/tsc-crash](https://github.com/bagbag/tsc-crash)

**Expected behavior:**
Compiles without problems

**Actual behavior:**

```
/home/patrick/projects/tsc-crash/node_modules/typescript/lib/tsc.js:84928
                throw e;
                ^

TypeError: Cannot read property 'kind' of undefined
    at checkFunctionOrConstructorSymbol (/home/patrick/projects/tsc-crash/node_modules/typescript/lib/tsc.js:59270:63)
    at checkFunctionOrMethodDeclaration (/home/patrick/projects/tsc-crash/node_modules/typescript/lib/tsc.js:59848:21)
    at checkFunctionDeclaration (/home/patrick/projects/tsc-crash/node_modules/typescript/lib/tsc.js:59741:17)
    at checkSourceElementWorker (/home/patrick/projects/tsc-crash/node_modules/typescript/lib/tsc.js:62600:28)
    at checkSourceElement (/home/patrick/projects/tsc-crash/node_modules/typescript/lib/tsc.js:62486:17)
    at Object.forEach (/home/patrick/projects/tsc-crash/node_modules/typescript/lib/tsc.js:130:30)
    at checkSourceFileWorker (/home/patrick/projects/tsc-crash/node_modules/typescript/lib/tsc.js:62798:20)
    at checkSourceFile (/home/patrick/projects/tsc-crash/node_modules/typescript/lib/tsc.js:62768:13)
    at getDiagnosticsWorker (/home/patrick/projects/tsc-crash/node_modules/typescript/lib/tsc.js:62848:17)
    at Object.getDiagnostics (/home/patrick/projects/tsc-crash/node_modules/typescript/lib/tsc.js:62837:24)
```

**Playground Link:** 

How to add @types dependencies?

**Related Issues:** 
Some with the same error message, but completely different stacktrace, so I don't think they are related.

**Comment by a-tarasyuk** [comment]
```ts
// @Filename: types.d.ts
declare function foo(props: any): any;
export default foo;
export as namespace foo;

// @Filename: foo.ts
/// <reference path="types.d.ts" />
declare function foo(): any;
```

The method declaration Symbol contains two declarations

```shell
0: SourceFileObject {pos: 0, end: 84, flags: 8388608, modifierFlagsCache: 0, transformFlags: 1}
1: NodeObject {pos: 0, end: 64, flags: 8388608, modifierFlagsCache: 536870914, transformFlags: 1}
length:2
```

One of them refers to SourceFile (includes entire `types.d.ts`) which doesn't have a parent

```ts
const node = <SignatureDeclaration | ClassDeclaration | ClassExpression>current;
const inAmbientContext = node.flags & NodeFlags.Ambient;
const inAmbientContextOrInterface = node.parent.kind === SyntaxKind.InterfaceDeclaration || node.parent.kind === SyntaxKind.TypeLiteral || inAmbientContext;
                                         ^^^^^^
```
Is it an issue with the symbol declarations or in `checkFunctionOrConstructorSymbol` should handle SourceFile declaration and skip it, or check existence parent?

cc @weswigham @sandersn

**Comment by RyanCavanaugh** [comment]
My unverified opinion is that a `SourceFile` is not a valid declaration for a method and that the first declaration for the symbol should have pointed to the `declare function foo(props: any): any;` node instead.

**Comment by weswigham** [comment]
> My unverified opinion is that a SourceFile is not a valid declaration for a method and that the first declaration for the symbol should have pointed to the declare function foo(props: any): any; node instead.

The "first" declaration is just the first one we encounter by check order - there's no smart logic there  The check in question just needs to handle the source file merge case (which is rare, since it needs a global function to merge with an `export as namespace` of the same name).
