### ISSUE TITLE
Debug Failure. Illegal value: 200 in signatureToSignatureDeclarationHelper

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#40301]
**TypeScript Version:**  4.0.2, 4.1.0-dev.20200828

**Search Terms:** Debug Failure Illegal value 200

**Code**

1. clone https://github.com/AlCalzone/node-zwave-js/tree/cd98592f082c769a517606065b242468cf8b0fa4
2. `npm ci`
3. `npm run lint:wotan`

**Expected behavior:**
no crash

**Actual behavior:**

4.0.2:
```
Error: Debug Failure. Illegal value: 200
    at signatureToSignatureDeclarationHelper (C:\Repositories\node-zwave-js\node_modules\typescript\lib\typescript.js:46902:82)
    at C:\Repositories\node-zwave-js\node_modules\typescript\lib\typescript.js:46107:106
    at withContext (C:\Repositories\node-zwave-js\node_modules\typescript\lib\typescript.js:46151:37)
    at Object.signatureToSignatureDeclaration (C:\Repositories\node-zwave-js\node_modules\typescript\lib\typescript.js:46107:28)
    at Rule.checkInferredTypeParameters (C:\Repositories\node-zwave-js\node_modules\@fimbul\mimir\src\rules\no-uninferred-type-parameter.js:129:44)
    at Rule.checkCallExpression (C:\Repositories\node-zwave-js\node_modules\@fimbul\mimir\src\rules\no-uninferred-type-parameter.js:93:29)
    at Rule.apply (C:\Repositories\node-zwave-js\node_modules\@fimbul\mimir\src\rules\no-uninferred-type-parameter.js:35:26)
    at Linter.applyRules (C:\Repositories\node-zwave-js\node_modules\@fimbul\wotan\src\linter.js:209:31)
    at Linter.getFindings (C:\Repositories\node-zwave-js\node_modules\@fimbul\wotan\src\linter.js:125:25)
    at Runner.lintProject (C:\Repositories\node-zwave-js\node_modules\@fimbul\wotan\src\runner.js:91:47)
```

4.1.0-dev.20200828:
```
Error: Debug Failure. Illegal value: 200
    at signatureToSignatureDeclarationHelper (C:\Repositories\node-zwave-js\node_modules\typescript\lib\typescript.js:46997:82)
    at C:\Repositories\node-zwave-js\node_modules\typescript\lib\typescript.js:46202:106
    at withContext (C:\Repositories\node-zwave-js\node_modules\typescript\lib\typescript.js:46246:37)
    at Object.signatureToSignatureDeclaration (C:\Repositories\node-zwave-js\node_modules\typescript\lib\typescript.js:46202:28)
    at Rule.checkInferredTypeParameters (C:\Repositories\node-zwave-js\node_modules\@fimbul\mimir\src\rules\no-uninferred-type-parameter.js:129:44)
    at Rule.checkCallExpression (C:\Repositories\node-zwave-js\node_modules\@fimbul\mimir\src\rules\no-uninferred-type-parameter.js:93:29)
    at Rule.apply (C:\Repositories\node-zwave-js\node_modules\@fimbul\mimir\src\rules\no-uninferred-type-parameter.js:35:26)
    at Linter.applyRules (C:\Repositories\node-zwave-js\node_modules\@fimbul\wotan\src\linter.js:209:31)
    at Linter.getFindings (C:\Repositories\node-zwave-js\node_modules\@fimbul\wotan\src\linter.js:125:25)
    at Runner.lintProject (C:\Repositories\node-zwave-js\node_modules\@fimbul\wotan\src\runner.js:91:47)
```

**Playground Link:** N/A

**Related Issues:** none

**Comment by RyanCavanaugh** [comment]
This is an invalid Compiler API call rather than a TypeScript compiler crash. With TypeScript 4.0.2, `checker.signatureToSignatureDeclaration` requires a signature-declaration `SyntaxKind`. `@fimbul/mimir` 0.21.0 passed `ts.SyntaxKind.CallExpression` (200), which produces `Debug Failure. Illegal value: 200`.

`@fimbul/mimir` 0.22.0 corrects the call to use `ts.SyntaxKind.CallSignature`. With that kind, TypeScript 4.0.2 returns a `CallSignature` declaration without throwing. Upgrading Mimir to a version containing that correction resolves the failure.
