### ISSUE TITLE
crash in async from #40228

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#40513]
Declaring `exports.apply = apply` is now marked an alias, but now calls `getTextOfNode`, which tries to walk up the tree to get the sourcefile in order to get a substring from it. This fails because parent pointers aren't set yet in the binder.

```
../../../built/local/tsc.js:13400
        return getTextOfNodeFromSourceText(sourceFile.text, node, includeTrivia);
                                                      ^

TypeError: Cannot read property 'text' of undefined
    at getSourceTextOfNodeFromSourceFile (../../../built/local/tsc.js:13400:55)
    at getTextOfNode (../../../built/local/tsc.js:13425:16)
    at Object.declarationNameToString (../../../built/local/tsc.js:13737:66)
    at getDisplayName (../../../built/local/tsc.js:39792:53)
    at declareSymbol (../../../built/local/tsc.js:39906:111)
    at bindExportsPropertyAssignment (../../../built/local/tsc.js:42016:17)
    at bindWorker (../../../built/local/tsc.js:41712:29)
    at bind (../../../built/local/tsc.js:41601:13)
    at bindExpressionStatement (../../../built/local/tsc.js:40666:13)
    at bindChildren (../../../built/local/tsc.js:40151:21)
```

I'll add a repro when I get one.

**Comment by sandersn** [comment]
Also crashes chrome-devtools

**Comment by sandersn** [comment]
Crashes trying to issue error on duplicate exports, like

```ts
exports.apply = apply
exports.apply = apply
```

Although the actual code from async was

```js
exports.apply = undefined
// lots of code ...
exports.apply = _apply2.default
```

**Comment by sandersn** [comment]
Adding the missing `setParent(node.left, node)` fixes the crash because it allows the error to be correctly reported.

**Comment by minestarks** [comment]
https://github.com/microsoft/tsserverfuzzer/issues/295
