### ISSUE TITLE
assert in uglify-js from #40228

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#40512]
Can't get the declaration of a symbol marked as an alias.

```
Error: Debug Failure.
    at resolveAlias (/home/nathansa/ts/built/local/tsc.js:45400:37)
    at symbolIsValue (/home/nathansa/ts/built/local/tsc.js:46120:98)
    at /home/nathansa/ts/built/local/tsc.js:46186:50
    at Map.forEach (<anonymous>)
    at getNamedMembers (/home/nathansa/ts/built/local/tsc.js:46185:21)
    at setStructuredTypeMembers (/home/nathansa/ts/built/local/tsc.js:46194:74)
    at resolveAnonymousTypeMembers (/home/nathansa/ts/built/local/tsc.js:52117:17)
    at resolveStructuredTypeMembers (/home/nathansa/ts/built/local/tsc.js:52384:25)
    at getPropertiesOfObjectType (/home/nathansa/ts/built/local/tsc.js:52402:24)
    at getPropertiesOfType (/home/nathansa/ts/built/local/tsc.js:52446:17)
```

I'll add a repro when I get one.

**Comment by sandersn** [comment]
The binder marks element access expression as export aliases, but the checker doesn't recognise them as alias declarations.

tools/exports.js:

```js
exports["Dictionary"] = Dictionary;
```

**Comment by minestarks** [comment]
https://github.com/microsoft/tsserverfuzzer/issues/297
