### ISSUE TITLE
Casting to a type generated from an @enum => Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sbrunner** [microsoft/TypeScript#40767]
**TypeScript Version:**  4.0.2 and next

**Search Terms:** @enum Maximum call stack size exceeded

**Code**

[typetest.zip](https://github.com/microsoft/TypeScript/files/5282727/typetest.zip)

and run `./run`

**Expected behavior:**

I don't exactly known, but at least a comprehensible error...

**Actual behavior:**

Getting:
```
/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:78602
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at getTypeOfFuncClassEnumModule (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:32607:25)
    at getTypeOfSymbol (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:32716:24)
    at getTypeFromJSDocValueReference (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35320:29)
    at getTypeReferenceType (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35308:33)
    at getTypeFromJSDocValueReference (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35335:32)
    at getTypeReferenceType (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35308:33)
    at getTypeFromJSDocValueReference (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35335:32)
    at getTypeReferenceType (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35308:33)
    at getTypeFromJSDocValueReference (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35335:32)
    at getTypeReferenceType (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35308:33)
```

**Playground Link:** 

**Related Issues:** https://github.com/microsoft/TypeScript/issues/18161?

**Comment by andrewbranch** [comment]
@sbrunner did you happen to observe whether this happens with older versions of TypeScript? I.e., is this a regression in 4.0, or did you just happen to discover it in 4.0?

**Comment by sbrunner** [comment]
@andrewbranch I find it in 4.0 by changing some things in typing, then I don't know for previous versions.
