### ISSUE TITLE
What is `project.addMissingFileRoot` actually do?

### ISSUE THREAD

**Issue by CGQAQ** [microsoft/TypeScript#40824]
What is `project.addMissingFileRoot` actually do? can I use it to add d.ts file to the project?
If I can, how to remove d.ts from the project?  I tried `project.removeFile`
And I keep getting this error, what does it mean? how can I fix it?
```
    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at ProjectService.forEachConfigFileLocation (c:\Users\mjaso\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150617:26)
        at ProjectService.stopWatchingConfigFilesForInferredProjectRoot (c:\Users\mjaso\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150592:22)
        at InferredProject.removeRoot (c:\Users\mjaso\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:148914:37)
        at InferredProject.Project.removeFile (c:\Users\mjaso\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:148159:26)
        at Timeout._onTimeout (Z:\contrib\vscode_deno\typescript-deno-plugin\out\typescript-deno-plugin\src\plugin.js:25:26)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7
```

```ts
this.project.getScriptInfo(getDenoDts(true))?.detachAllProjects();
```
```
    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at ProjectService.forEachConfigFileLocation (c:\Users\mjaso\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150617:26)
        at ProjectService.stopWatchingConfigFilesForInferredProjectRoot (c:\Users\mjaso\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:150592:22)
        at InferredProject.removeRoot (c:\Users\mjaso\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:148914:37)
        at InferredProject.Project.removeFile (c:\Users\mjaso\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:148159:26)
        at ScriptInfo.detachAllProjects (c:\Users\mjaso\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147141:23)
        at Timeout._onTimeout (Z:\contrib\vscode_deno\typescript-deno-plugin\out\typescript-deno-plugin\src\plugin.js:26:112)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7)
```

**Comment by RyanCavanaugh** [comment]
@sheetalkamat any advice?

**Comment by sheetalkamat** [comment]
addRoot and addMissingRoot are suppose to be internal but must have missed.. They will not help you with adding roots to the project. The roots of projects are managed by configurations internally and you cannot change them. External projects specify way to create project with known set of roots and compiler options or plugins can add external files as root through `getExternalFiles` though.

**Comment by alfredsgenkins** [comment]
@sheetalkamat I have had a need to add more source files to the project recently. When working with plugin system, plugin targets had to be manually included. I tried using `getExternalFiles` in plugin, specifying the array of all files I intend to include, but `program.getSourceFile(fileName)` resulted in `undefined`.

I ended up using following function to add file to project dynamically:
```ts
 getSourceFileByPath(fileName: string, tryCount = 0): ts.SourceFile | undefined {
      // TODO: optimize this function (it is very slow)

      const program = this.ctx.info.project.getLanguageService().getProgram();

      if (!program || tryCount > 1) {
          // ^^^ Allow only 2 tries to get the source file
          return;
      }

      const sourceFile = program.getSourceFile(fileName);

      if (sourceFile) {
          return sourceFile;
      }

      // vvv Add file as new source file
      this.ctx.info.project.addMissingFileRoot(fileName as ts.server.NormalizedPath);

      return this.getSourceFileByPath(fileName, tryCount + 1);
  }
```

Any suggestion for me here?

**Comment by sheetalkamat** [comment]
Did you look into why `getExternalFiles` didnt work? It seems like that should work.. Did you try checking if its contents are queried.. Did you check result of `program.getSourceFiles().map(f => f.fileName)`

**Comment by alfredsgenkins** [comment]
@sheetalkamat I have retried the approach with `getExternalFiles`, and it now works as expected. Sorry for false alarm! :)
