### ISSUE TITLE
Nested JSON makes tsc throw RangeError with no culprit

### ISSUE THREAD

**Issue by robpalme** [microsoft/TypeScript#40873]
**TypeScript Version:**  4.1.0-dev.20201001

**Search Terms:** RangeError JSON deep nested

**Code**

```json5
// test.json
{
"c":[{
  "c":[{
    "c":[{
// ~150 more levels of nesting
      }]
    }]
  }]
}
```

```ts
// @resolveJsonModule: true
// @declaration: true
export { default } from "./test.json";
```

**Expected behavior:**

A regular TypeScript error saying `"ts1234: Can't type-check file 'foo.json', nesting is too deep"`.  The key is that it should indicate where the problem comes from.

**Actual behavior:**

TypeScript itself blows up and does **not** tell you which of your source files is at fault.

```
C:\dev\temp\deep-json>tsc
C:\Users\u\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:81155
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at commitPendingMapping (C:\Users\u\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:62604:29)
    at Object.addMapping (C:\Users\u\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:62502:17)
```

**Playground Link:** 

[Browser repro](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201001#code/N4KARAxmBcDaKkjeipweNLPI09quhBOJ+25eWVRpF1x9tljNZDdbT7zHLnrQQOH9Rfcb0k9p3WV3lCxUuYokyFItSs3KNS9at2GDOk-u3m9Wq0dMXrx+7cuObZh3bdP3zjy8+ugQHB-qF+4b6RPtHesV7xQWFRca4gALogAL7pWTnZGfm5BXklxWVFFYVVpZU11eX1tQ11Lc1tTR2NXa2dPd3t-b0DfSPDY0MTg1OjkzPT4-OzC3Mry2tLG4tbq5t1QA)

Please look into the browser console to see the error.

**Related Issues:** None

---

Whilst this error can happen in TS/JS files, I'd suggest this limit is most likely to be hit in JSON because they are often machine generated and so the user is not always in control of the format.

Our current workaround is to add a non-typechecked re-exporting wrapper .js + wrapper.d.ts in front of the JSON so the typechecker doesn't need to generate types for the JSON.

**Comment by robpalme** [comment]
Are we sure there is no easy way to do file tracking?  e.g. a global variable that tracks `currentFile`.  Then it can still throw the RangeError, and enrich it to log "Error occurred when processing foo.json".  That's the only info needed.

Otherwise the user will probably find the culprit by bisecting or intuition.  It just takes time.

If there's no easy answer, it's fine to close this as Won't Fix.

**Comment by RyanCavanaugh** [comment]
I wouldn't be opposed to something like that with ~zeroish performance cost.

**Comment by pipobscure** [comment]
Or maybe just fix it by not typing imports that have a .json extension and import them as `any`? Possibly behind a config flag `typeJSON`?

When importing that kind of structure you usually know the shape and can manually cast it, or you don't know in which case `any` or `unknown` would be fine.

**Comment by RyanCavanaugh** [comment]
This is fixed in the current native TypeScript implementation.

With a generated 500-level recursive `{"c":[...]}` JSON shape, `resolveJsonModule`, CommonJS interop, and `--declaration --emitDeclarationOnly`, TypeScript 4.1.0-dev.20201001 and final classic TypeScript 6.0.3 both throw `RangeError: Maximum call stack size exceeded`. Current native TypeScript 7.1.0-dev.20260905.1 emits the declaration successfully.

There is no classic fixing commit to attribute; the issue remains reproducible in final classic TypeScript.
