### ISSUE TITLE
crash in new addImplementationSuccessElaboration

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#41015]
Crashes 44 packages in DT.

```
✔ ~/DefinitelyTyped/types/agent-base [master|✔] 
09:28 $ tsc
/home/nathansa/ts/built/local/tsc.js:105472
                throw e;
                ^

TypeError: Cannot read property 'length' of undefined
    at getSignatureFromDeclaration (/home/nathansa/ts/built/local/tsc.js:53357:89)
    at addImplementationSuccessElaboration (/home/nathansa/ts/built/local/tsc.js:67988:37)
    at resolveCall (/home/nathansa/ts/built/local/tsc.js:67955:25)
    at resolveCallExpression (/home/nathansa/ts/built/local/tsc.js:68284:20)
    at resolveSignature (/home/nathansa/ts/built/local/tsc.js:68657:28)
    at getResolvedSignature (/home/nathansa/ts/built/local/tsc.js:68688:26)
    at checkCallExpression (/home/nathansa/ts/built/local/tsc.js:68814:29)
    at checkExpressionWorker (/home/nathansa/ts/built/local/tsc.js:71378:28)
    at checkExpression (/home/nathansa/ts/built/local/tsc.js:71287:38)
    at checkExpressionStatement (/home/nathansa/ts/built/local/tsc.js:73819:13)
```

Added in #41001

**Comment by weswigham** [comment]
The crash is just because of an unchecked cast - turns out having a `.body` member isn't enough to guarantee the declaration is function-like, since namespaces also have a `.body` 😛  - PR is up: https://github.com/microsoft/TypeScript/pull/41017

**Comment by minestarks** [comment]
https://github.com/microsoft/tsserverfuzzer/issues/301
