### ISSUE TITLE
Re-exporting class on commonjs - JS code + declaration emit leads to tsc crash

### ISSUE THREAD

**Issue by Bnaya** [microsoft/TypeScript#41182]
**TypeScript Version:**  4.1.0-dev.20201021

**Search Terms:**
Unhandled alias declaration kind in symbol serializer

**Code**
https://gist.github.com/Bnaya/ccb802d892508f3f4ebd81e3350eea05
run `yarn tsc4p1`

**Expected behavior:**
Should compile and emit types

**Actual behavior:**
tsc crash with:
```
/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:86657
                throw e;
                ^

Error: Debug Failure. Unhandled alias declaration kind in symbol serializer!
Node 198 was unexpected.
    at serializeAsAlias (/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:40361:45)
    at serializeSymbolWorker (/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:40082:25)
    at serializeSymbol (/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:39987:38)
    at /Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:39972:29
    at Map.forEach (<anonymous>)
    at visitSymbolTable (/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:39971:81)
    at symbolTableToDeclarationStatements (/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:39847:17)
    at /Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:38395:106
    at withContext (/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:38422:37)
    at Object.symbolTableToDeclarationStatements (/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:38395:28)
error Command failed with exit code 1.
```
**Related Issues:** 
#37832

**Comment by Bnaya** [comment]
@weswigham can you take a look also on the repro here:
https://github.com/microsoft/TypeScript/issues/37832#issuecomment-713549167
#37832 is not 100% fixed
Thanks! :))
