### ISSUE TITLE
Annotated dynamic import should not cause crash package name resolving

### ISSUE THREAD

**Issue by villelaitila** [microsoft/TypeScript#41332]
This issue is originated from `madge` https://github.com/pahen/madge/issues/211

mangeScopedPackageName function crashes when madge is running ` classicNameResolver  (typescript/lib/typescript.js:27324:24)` for a TypeScript file that contains annotated dynamic imports such as

**TypeScript Version: 4.0.5** 

Fails also with 3.9.5 that is the one that the most recent madge uses.

**Search Terms: annoted dynamic imports**

**Code**

Create a `testfile.ts` with following content:
```ts
const Graph =  React.lazy(() => import(/* webpackChunkName: 'react-graph-vis' */ `react-graph-vis`))
```

Initiate classicNameResolver of TypeScritp by running `madge` this way:   `cd madge && node bin/cli.js ../testfile.ts`

**Expected behavior: Program completes without error**

**Actual behavior:  Program crashes with TypeError: Cannot read property 'lastIndexOf' of undefined **

Below traceback is from TypeScript 3.9.5 version but the behavior is similar in the 4.0.5 version. Line numbers in the call stack do differ.

```
✖ TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.startsWith (/usr/lib/node_modules/madge/node_modules/typescript/lib/typescript.js:2060:20)
    at mangleScopedPackageName (/usr/lib/node_modules/madge/node_modules/typescript/lib/typescript.js:30544:16)
    at mangleScopedPackageNameWithTrace (/usr/lib/node_modules/madge/node_modules/typescript/lib/typescript.js:30530:23)
    at loadModuleFromImmediateNodeModulesDirectory (/usr/lib/node_modules/madge/node_modules/typescript/lib/typescript.js:30461:83)
    at /usr/lib/node_modules/madge/node_modules/typescript/lib/typescript.js:30438:39
    at Object.forEachAncestorDirectory (/usr/lib/node_modules/madge/node_modules/typescript/lib/typescript.js:6786:26)
    at loadModuleFromNearestNodeModulesDirectoryWorker (/usr/lib/node_modules/madge/node_modules/typescript/lib/typescript.js:30432:19)
    at loadModuleFromNearestNodeModulesDirectoryTypesScope (/usr/lib/node_modules/madge/node_modules/typescript/lib/typescript.js:30428:16)
    at tryResolve (/usr/lib/node_modules/madge/node_modules/typescript/lib/typescript.js:30609:28)
    at classicNameResolver (/usr/lib/node_modules/madge/node_modules/typescript/lib/typescript.js:30585:24)
```

**Playground Link:** 

**Related Issues:** 
Nothing found from TypeScript repo, but this one is the relevant related in the madge repository.
https://github.com/pahen/madge/issues/211

See also comment 
https://github.com/pahen/madge/issues/211#issuecomment-718266982 that demonstrates how mangeScopedPackageName could be changed to avoid the crash.

**Comment by sheetalkamat** [comment]
Not sure why this is typescript issue. module name resolver always expects string so passing it undefined is going to lead to crash.

**Comment by villelaitila** [comment]
I cannot reproduce this anymore with madge 4.0.0 that has typescript version 3.9.9. Probably the issue has been fixed as a side-effect of some other work.
