### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by roblourens** [microsoft/TypeScript#41484]
Issue Type: <b>Bug</b>

**TypeScript Version:** 4.2.0-dev.20201104

**Steps to reproduce crash**
1. Open VS Code
2. Check out this PR https://github.com/microsoft/vscode/pull/108401
3. It crashed

**TS Server Log**
[tsserver.log](https://github.com/microsoft/vscode/files/5519121/tsserver.log)

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at ProjectService.applyChangesInOpenFiles (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:155575:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:156608:46)
    at /Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:158481:88
    at IOSession.Session.executeWithRequestId (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:158472:28)
    at IOSession.Session.executeCommand (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:158481:33)
    at IOSession.Session.onMessage (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:158505:35)
    at Interface.<anonymous> (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:160715:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

VS Code version: Code - Insiders 1.52.0-insider (65f805d98e798b979901b74d4c8810c05455b792, 2020-11-10T09:49:58.382Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.0.0-1027-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv|-psn_0_13774114 --crash-reporter-id a2c1d522-e9f0-4e3f-b78a-9253f1c2d2d3|
|Screen Reader|no|
|VM|17%|

|Item|Value|
|---|---|
|Remote|SSH: robfast|
|OS|Linux x64 5.0.0-1027-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (3.95GB free)|
|VM|0%|

**Comment by mjbvz** [comment]
Thanks @roblourens for the logs!

Here's the first error I see:

```
nfo 5443 [09:30:39.842] Open files: 
Info 5443 [09:30:39.842] 	FileName: ^pr:/Users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchView.ts?{"baseCommit":"35c3949d46ef81d5823f350759a2fff67307db9e","headCommit":"c79c26babeba5ebe121c684bc54147bd579ee681","isBase":false,"fileName":"src/vs/workbench/contrib/search/browser/searchView.ts","prNumber":108401,"status":3,"remoteName":"origin"} ProjectRootPath: undefined
Info 5443 [09:30:39.842] 		Projects: /dev/null/inferredProject3*
Err 5443  [09:30:39.843] Could not find file "/Users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchView.ts".
All files are: [{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es5.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es5.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.core.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.core.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.collection.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.collection.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.iterable.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.iterable.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.symbol.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.symbol.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.generator.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.generator.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.promise.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.promise.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.proxy.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.proxy.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.reflect.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.reflect.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.array.include.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.array.include.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.dom.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.dom.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.dom.iterable.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.dom.iterable.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.webworker.importscripts.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.webworker.importscripts.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.full.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.full.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.scripthost.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.scripthost.d.ts"},{"path":"/^pr:/users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchview.ts?{\"basecommit\":\"35c3949d46ef81d5823f350759a2fff67307db9e\",\"headcommit\":\"c79c26babeba5ebe121c684bc54147bd579ee681\",\"isbase\":false,\"filename\":\"src/vs/workbench/contrib/search/browser/searchview.ts\",\"prnumber\":108401,\"status\":3,\"remotename\":\"origin\"}","fileName":"^pr:/Users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchView.ts?{\"baseCommit\":\"35c3949d46ef81d5823f350759a2fff67307db9e\",\"headCommit\":\"c79c26babeba5ebe121c684bc54147bd579ee681\",\"isBase\":false,\"fileName\":\"src/vs/workbench/contrib/search/browser/searchView.ts\",\"prNumber\":108401,\"status\":3,\"remoteName\":\"origin\"}"}]
Err 5444  [09:30:39.843] Could not find file "/Users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchView.ts".
All files are: [{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es5.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es5.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.core.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.core.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.collection.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.collection.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.iterable.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.iterable.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.symbol.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.symbol.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.generator.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.generator.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.promise.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.promise.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.proxy.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.proxy.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.reflect.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.reflect.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.array.include.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.array.include.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.dom.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.dom.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.dom.iterable.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.dom.iterable.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.webworker.importscripts.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.webworker.importscripts.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.full.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.full.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.scripthost.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.scripthost.d.ts"},{"path":"/^pr:/users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchview.ts?{\"basecommit\":\"35c3949d46ef81d5823f350759a2fff67307db9e\",\"headcommit\":\"c79c26babeba5ebe121c684bc54147bd579ee681\",\"isbase\":false,\"filename\":\"src/vs/workbench/contrib/search/browser/searchview.ts\",\"prnumber\":108401,\"status\":3,\"remotename\":\"origin\"}","fileName":"^pr:/Users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchView.ts?{\"baseCommit\":\"35c3949d46ef81d5823f350759a2fff67307db9e\",\"headCommit\":\"c79c26babeba5ebe121c684bc54147bd579ee681\",\"isBase\":false,\"fileName\":\"src/vs/workbench/contrib/search/browser/searchView.ts\",\"prNumber\":108401,\"status\":3,\"remoteName\":\"origin\"}"}]
Err 5445  [09:30:39.843] Exception on executing command {"seq":55,"type":"request","command":"projectInfo","arguments":{"file":"/Users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchView.ts","needFileNameList":false}}:

    No Project.

    Error: No Project.
        at Object.ThrowNoProject (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:149812:23)
        at ProjectService.doEnsureDefaultProjectForFile (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:153530:131)
        at ProjectService.ensureDefaultProjectForFile (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:153525:75)
        at IOSession.Session.getFileAndProjectWorker (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:157684:87)
        at IOSession.Session.getProjectInfoWorker (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:157532:36)
        at IOSession.Session.getProjectInfo (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:157529:29)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:156848:61)
        at /Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:158481:88
        at IOSession.Session.executeWithRequestId (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:158472:28)
        at IOSession.Session.executeCommand (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:158481:33)
        at IOSession.Session.onMessage (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:158505:35)
        at Interface.<anonymous> (/Users/roblou/code/vscode/node_modules/typescript/lib/tsserver.js:160715:27)
        at Interface.emit (events.js:223:5)
        at Interface._onLine (readline.js:315:10)
        at Interface._normalWrite (readline.js:460:12)
        at Socket.ondata (readline.js:172:10)
        at Socket.emit (events.js:223:5)
        at addChunk (_stream_readable.js:309:12)
        at readableAddChunk (_stream_readable.js:290:11)
        at Socket.Readable.push (_stream_readable.js:224:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```


Looks like this is for an in-memory file from a pull request

**Comment by sheetalkamat** [comment]
@mjbvz this seems like vscode issue.: The opened file name (` ^pr:/Users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchView.ts?{"baseCommit":"35c3949d46ef81d5823f350759a2fff67307db9e","headCommit":"c79c26babeba5ebe121c684bc54147bd579ee681","isBase":false,"fileName":"src/vs/workbench/contrib/search/browser/searchView.ts","prNumber":108401,"status":3,"remoteName":"origin"}`) is different from file (`"/Users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchView.ts"`) on which projectInfo is invoked.

```
Info 5429 [09:30:39.840] request:
    {"seq":55,"type":"request","command":"projectInfo","arguments":{"file":"/Users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchView.ts","needFileNameList":false}}
Info 5430 [09:30:39.840] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 5431 [09:30:39.841] DirectoryWatcher:: Close:: WatchInfo: /^pr: 1 undefined Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
Info 5432 [09:30:39.841] Elapsed:: 0.006659984588623047ms DirectoryWatcher:: Close:: WatchInfo: /^pr: 1 undefined Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
Info 5433 [09:30:39.841] DirectoryWatcher:: Close:: WatchInfo: /node_modules 1 undefined Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
Info 5434 [09:30:39.841] Elapsed:: 0.0031321048736572266ms DirectoryWatcher:: Close:: WatchInfo: /node_modules 1 undefined Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
Info 5435 [09:30:39.842] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 3 structureChanged: true Elapsed: 1.5765080451965332ms
Info 5436 [09:30:39.842] Project '/dev/null/inferredProject1*' (Inferred)
Info 5437 [09:30:39.842] 	Files (0)

Info 5438 [09:30:39.842] -----------------------------------------------
Info 5439 [09:30:39.842] Scheduling throttled operation:
    {"projectName":"/dev/null/inferredProject1*","fileNames":[],"compilerOptions":{"module":1,"target":3,"jsx":1,"strictNullChecks":true,"strictFunctionTypes":true,"sourceMap":true,"allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true,"resolveJsonModule":true,"noEmitForJsFiles":true},"typeAcquisition":{"enable":true,"include":[],"exclude":[]},"unresolvedImports":[],"projectRootPath":"/","kind":"discover"}
Info 5440 [09:30:39.842] Scheduling request for: /dev/null/inferredProject1*
Info 5441 [09:30:39.842] Before ensureProjectForOpenFiles:
Info 5442 [09:30:39.842] Project '/dev/null/inferredProject1*' (Inferred)
Info 5442 [09:30:39.842] 	Files (0)

Info 5442 [09:30:39.842] -----------------------------------------------
Info 5442 [09:30:39.842] Project '/dev/null/inferredProject3*' (Inferred)
Info 5442 [09:30:39.842] 	Files (19)

Info 5442 [09:30:39.842] -----------------------------------------------
Info 5442 [09:30:39.842] Open files: 
Info 5442 [09:30:39.842] 	FileName: ^pr:/Users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchView.ts?{"baseCommit":"35c3949d46ef81d5823f350759a2fff67307db9e","headCommit":"c79c26babeba5ebe121c684bc54147bd579ee681","isBase":false,"fileName":"src/vs/workbench/contrib/search/browser/searchView.ts","prNumber":108401,"status":3,"remoteName":"origin"} ProjectRootPath: undefined
Info 5442 [09:30:39.842] 		Projects: /dev/null/inferredProject3*
Info 5442 [09:30:39.842] After ensureProjectForOpenFiles:
Info 5443 [09:30:39.842] Project '/dev/null/inferredProject1*' (Inferred)
Info 5443 [09:30:39.842] 	Files (0)

Info 5443 [09:30:39.842] -----------------------------------------------
Info 5443 [09:30:39.842] Project '/dev/null/inferredProject3*' (Inferred)
Info 5443 [09:30:39.842] 	Files (19)

Info 5443 [09:30:39.842] -----------------------------------------------
Info 5443 [09:30:39.842] Open files: 
Info 5443 [09:30:39.842] 	FileName: ^pr:/Users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchView.ts?{"baseCommit":"35c3949d46ef81d5823f350759a2fff67307db9e","headCommit":"c79c26babeba5ebe121c684bc54147bd579ee681","isBase":false,"fileName":"src/vs/workbench/contrib/search/browser/searchView.ts","prNumber":108401,"status":3,"remoteName":"origin"} ProjectRootPath: undefined
Info 5443 [09:30:39.842] 		Projects: /dev/null/inferredProject3*
Err 5443  [09:30:39.843] Could not find file "/Users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchView.ts".
All files are: [{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es5.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es5.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.core.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.core.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.collection.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.collection.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.iterable.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.iterable.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.symbol.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.symbol.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.generator.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.generator.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.promise.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.promise.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.proxy.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.proxy.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.reflect.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.reflect.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.array.include.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.array.include.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.dom.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.dom.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.dom.iterable.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.dom.iterable.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.webworker.importscripts.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.webworker.importscripts.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.full.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.es2016.full.d.ts"},{"path":"/users/roblou/code/vscode/node_modules/typescript/lib/lib.scripthost.d.ts","fileName":"/Users/roblou/code/vscode/node_modules/typescript/lib/lib.scripthost.d.ts"},{"path":"/^pr:/users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchview.ts?{\"basecommit\":\"35c3949d46ef81d5823f350759a2fff67307db9e\",\"headcommit\":\"c79c26babeba5ebe121c684bc54147bd579ee681\",\"isbase\":false,\"filename\":\"src/vs/workbench/contrib/search/browser/searchview.ts\",\"prnumber\":108401,\"status\":3,\"remotename\":\"origin\"}","fileName":"^pr:/Users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchView.ts?{\"baseCommit\":\"35c3949d46ef81d5823f350759a2fff67307db9e\",\"headCommit\":\"c79c26babeba5ebe121c684bc54147bd579ee681\",\"isBase\":false,\"fileName\":\"src/vs/workbench/contrib/search/browser/searchView.ts\",\"prNumber\":108401,\"status\":3,\"remoteName\":\"origin\"}"}]
Err 5444  [09:30:39.843] Could not find file "/Users/roblou/code/vscode/src/vs/workbench/contrib/search/browser/searchView.ts".
```
