### ISSUE TITLE
TypeScript Server Error ERR <semantic> when export group in literal obj !

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/TypeScript#41630]
**TypeScript Version:**  vscode tell me is Version 3.7.5
![image](https://user-images.githubusercontent.com/24865815/100017924-9ce66580-2da9-11eb-8894-f1c132533ffe.png)

**Search Terms:** - TypeScript Server Error ERR <semantic>

**Code**

```js

//plugins folder
//file-0  (index.js)
export { File0_render as RENDER } from './File0.render';
export { File0_data as DATA } from './File0.data';
export { File0_store as STORE } from './File0.store';
```
```js
//file-1  (index.js)
export { File1_render as RENDER } from './File1.render';
export { File1_data as DATA } from './File1.data';
export { File1_store as STORE } from './File1.store';
```
```js
//parentFolder  (index.js)
import * as File0 from './plugins/File0/index.js';
import * as File1 from './plugins/File1/index.js';
// literal export as object make crazy vscode and crash
// is work only for Array ! of if we have one prop
export const PLUGINS = {
	File0,
	File1,
};
Object.values(PLUGINS).map((plugin, k) => plugin.DATA.DEFAULT); // crash ts-servor on fetch intellisence !
```

**Expected behavior:**
Intellisence should show me the list of export * inside literal obj 

**Actual behavior:**
Intellisence broke and send a Error, but all work fine in app

**Playground Link:** 
Cant really replicate without multiple file system and my project is not in ts but js
https://www.typescriptlang.org/play?#code/PTAOBsFcHMEsDsDOACAZge3AEwKYCcBYAKBFVnBwFoAGYnAD1HTwBdkBvZAMXJ2oH08OeLjzIAhigBKAUQByAERlTkAXzR50AW2QByAHTAeFavqEj8ugNx1GzNp2N9+WcS3ESUCgIIAVb2oa2nqGTqau7ta2TKwc3LwCiCzMOJ7IAMq+APKygaiaOgZGCfpJKVEkwGQUlACM0fZxTrWCwqJpsorKeQUhxRS1Zm2WNkQMMQ7xAy5uHpLIPv49wUXN+hHiFeONjrwtZUJpmTkyy4Whe6XJQhXEIKDi5ixcmKLE70QfsFoTyABUaTCQXOYCgcCQ-T4FW+vwB82awL6EBgCEQkNqFRAyHAsBY+HE4GQ21i83QACMAFY4ADGbC04gA1qlqXhxAAvACeyAAbohqehcBIRMgWZIABZ3YDIWAoADuzAZyHQ8HAXIwYm8eFZXIA2mEADTNAC6yAAhEqxLBUMhZakxeJuallalQJpQBwwqoGrF+Ug2AAFAAyAFUAOIASTk6WQAF4OMQAJAGxPNfXEVSjLKUmksfTcgmQHCIAAUQbDkfSAEp9PTQMXi8jwfrkAzK7GAHzIRsIfSLby9mRcbzBwO+StWIA

**Related Issues:** 

---

Hi i have a strange bug in intellisence from vscode when i try export a group of module inside a literal object.

If i using array everithing is fine and i get types
here 
![image](https://user-images.githubusercontent.com/24865815/99888511-6844a380-2c1b-11eb-8519-cb3cd3b7be0b.png)
But if i use literal object , type is broken !
![image](https://user-images.githubusercontent.com/24865815/99888589-f91b7f00-2c1b-11eb-9082-19cce28f7a49.png)
But strange, is get correct type after !
![image](https://user-images.githubusercontent.com/24865815/99888611-181a1100-2c1c-11eb-860f-0c4463280e75.png)
If i only add one key in the literal is work fine ! 
![image](https://user-images.githubusercontent.com/24865815/99888795-519f4c00-2c1d-11eb-951e-d91aa40570ef.png)

---

here the log i get , sorry if is long 
```ts
  ERR <semantic> TypeScript Server Error (4.0.3)
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:125712:34
    at Object.forEach (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at getSymbolKindOfConstructorPropertyMethodAccessorFunctionOrVar (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:125706:48)
    at Object.getSymbolKind (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:125636:26)
    at createCompletionEntry (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115303:40)
    at getCompletionEntriesFromSymbols (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115350:29)
    at completionInfoFromData (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115188:17)
    at Object.getCompletionsAtPosition (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115142:28)
    at Proxy.getCompletionsAtPosition (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143489:35)
    at c:\Users\InformatiqueLepage\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.10\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:2281
    at Object.r.getCompletionsAtPosition (c:\Users\InformatiqueLepage\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.10\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:6454)
    at IOSession.Session.getCompletions (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154328:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:153212:61)
    at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154962:88
    at IOSession.Session.executeWithRequestId (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154953:28)
    at IOSession.Session.executeCommand (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154962:33)
    at IOSession.Session.onMessage (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154986:35)
    at Interface.<anonymous> (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:157202:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23): Error: <semantic> TypeScript Server Error (4.0.3)
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:125712:34
    at Object.forEach (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:188:30)
    at getSymbolKindOfConstructorPropertyMethodAccessorFunctionOrVar (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:125706:48)
    at Object.getSymbolKind (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:125636:26)
    at createCompletionEntry (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115303:40)
    at getCompletionEntriesFromSymbols (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115350:29)
    at completionInfoFromData (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115188:17)
    at Object.getCompletionsAtPosition (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:115142:28)
    at Proxy.getCompletionsAtPosition (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143489:35)
    at c:\Users\InformatiqueLepage\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.10\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:2281
    at Object.r.getCompletionsAtPosition (c:\Users\InformatiqueLepage\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.10\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:6454)
    at IOSession.Session.getCompletions (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154328:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:153212:61)
    at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154962:88
    at IOSession.Session.executeWithRequestId (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154953:28)
    at IOSession.Session.executeCommand (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154962:33)
    at IOSession.Session.onMessage (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:154986:35)
    at Interface.<anonymous> (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:157202:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
	at Function.create (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:76476)
	at dispatchResponse (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:70351)
	at dispatchMessage (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:69210)
	at c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:68720
	at l.fire (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at g.onLengthData (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:45:60018)
	at Socket.<anonymous> (c:\Users\InformatiqueLepage\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:45:59666)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

any tips or help, is a know issue ? thanks all

**Comment by djmisterjon** [comment]
ok so i found a solution, but i feel sad thats i cant proceed the way i like for my architecture.
I don't think the first way is bad, it from taste of spirit of each one, but here the way who is work fine
//plugins folder
```js
//file-0
import { File0_render as RENDER } from './File0.render';
import { File0_data as DATA } from './File0.data';
import { File0_store as STORE } from './File0.store';
export const File0 = { RENDER, DATA, STORE }; // pack here and export
```
```js
//file-1
import { File1_render as RENDER } from './File1.render';
import { File1_data as DATA } from './File1.data';
import { File1_store as STORE } from './File1.store';
export const File1= { RENDER, DATA, STORE };  // pack here and export
```
//parentFolder
```js
// now we import like that
import {File0} from './plugins/File0';
import {File1} from './plugins/File1';
export const PLUGINS = { File0, File1}; // hey , no more crash error. from ts-servor and intellisense work ! 

```
![image](https://user-images.githubusercontent.com/24865815/100016062-db2e5580-2da6-11eb-831c-20e447b11b2c.png)

Am not big fan on this way because it requires a different discipline and logic for my project, but for the moment these preferable against coding blind.
Hope this help, feel free to close , i understand that this is the kind of error that is difficult to isolate and explain. :)

**Comment by armanio123** [comment]
@djmisterjon try using `typescript@next` and see if that solves the problem. I wasn't able to reproduce it. If it works, the fix will be available on an oncoming release.

**Comment by DanielRosenwasser** [comment]
Looks like we haven't seen a crash in a while as per https://github.com/microsoft/TypeScript/issues/41650. Should this and the other issue be closed?
