### ISSUE TITLE
Crash with Error: Debug Failure. False expression. at getConstructorDefinedThisAssignmentTypes

### ISSUE THREAD

**Issue by Marik-D** [microsoft/TypeScript#41749]
**TypeScript Version:**  4.1.2, 4.2.0-dev.20201201

**Search Terms:**
Crash, @types/node, symbol, async method
**Code**
Trying to compile this code, while having `@types/node@14.0.13` installed and composite flag enabled causes a crash.
```ts
const symbol = Symbol('foo')

class Foo {
  constructor() {

    this[symbol] = this[symbol].bind(this)
  }

  async [symbol] () {
    
  }
}
```

**Expected behavior:**

Not crash

**Actual behavior:**

Crashes with:
```
Error: Debug Failure. False expression.
    at getConstructorDefinedThisAssignmentTypes (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:41664:22)
    at getWidenedTypeForAssignmentDeclaration (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:41515:67)
    at getTypeOfVariableOrParameterOrPropertyWorker (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:41822:24)
    at getTypeOfVariableOrParameterOrProperty (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:41775:28)
    at getTypeOfSymbol (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:42079:24)
    at getPropertyTypeForIndexType (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:46121:36)
    at getIndexedAccessTypeOrUndefined (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:46427:20)
    at checkElementAccessExpression (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:56168:37)
    at checkIndexedAccess (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:56146:17)
    at checkExpressionWorker (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:60004:28)
```

**Reproduction repo:** https://github.com/Marik-D/typescript-bug

**Related Issues:**

**Comment by bradharms** [comment]
I'm having a similar problem while using Typescript 4.1.3, Webpack 5.11.1 and ts-loader 8.0.12. My Webpack entry point only contains the code:

```
export {};
```

**Comment by minestarks** [comment]
Here's a repro https://github.com/microsoft/tsserverfuzzer/issues/302
