### ISSUE TITLE
TypeScript Server Error: "Debug Failure. False expression: Token end is child end"

### ISSUE THREAD

**Issue by quantumsheep** [microsoft/TypeScript#41925]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.2.0-dev.20201210

**Search Terms**
- format
- jsx
- react

---

- VSCode Version: 1.51.1
- OS Version: macOS 11.0.1 (20B50)

Steps to Reproduce:
- Create a `.tsx` file containing the following code (wrong indentation is intentional to demonstrate the formatter's issue):
```tsx
function App() {
  const value = "Oh no";

  return (
  <div>"{value}"</div>
  )
}
```

The `const value = "Oh no";` line can be replace or even erased without any change concerning the issue.

- Use the [`Format Document`](https://code.visualstudio.com/docs/editor/codebasics#_formatting) or `Format Selection` action.

- It doesn't work and outputs the following error in the `Log (Extension Host)` part of the `Output` logs.
```
[2020-12-10 23:31:42.444] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2020-12-10 23:31:42.444] [exthost] [error] Error: <syntax> TypeScript Server Error (4.0.3)
Debug Failure. False expression: Token end is child end
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128163:38)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128095:21
    at visitNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26834:24)
    at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:27255:21)
    at processNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128094:20)
    at processChildNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128170:21)
    at processChildNodes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128233:48)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128097:21
    at visitNodes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26839:24)
    at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:27235:21)
    at processNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128094:20)
    at processChildNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128170:21)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128095:21
    at visitNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26834:24)
    at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:27042:24)
    at processNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128094:20)
    at processChildNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128170:21)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128095:21
    at visitNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26834:24)
    at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:27119:24)
    at processNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128094:20)
    at processChildNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128170:21)
    at processChildNodes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128233:48)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128097:21
    at visitNodes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26839:24)
    at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:27079:24)
    at processNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128094:20)
    at processChildNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128170:21)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128095:21
    at visitNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26834:24)
    at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26964:21)
    at processNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128094:20)
    at processChildNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128170:21)
    at processChildNodes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128233:48)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128097:21
    at visitNodes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26839:24)
    at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:27081:24)
    at processNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128094:20)
    at formatSpanWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:127907:17)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:127888:208
    at Object.getFormattingScanner (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:126494:23)
    at formatSpan (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:127888:31)
    at Object.formatSelection (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:127706:20)
    at Proxy.getFormattingEditsForRange (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143766:34)
    at IOSession.Session.getFormattingEditsForRange (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154253:45)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:153197:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154962:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154953:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154962:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154986:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:157202:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
	at Function.create (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:76476)
	at dispatchResponse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:70351)
	at dispatchMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:69210)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:68720
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
	at g.onLengthData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:45:60018)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:45:59666)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

The issue is happening when there is JS/TS code inside any quote format (`"`, `'` and `), in TSX code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Error stack from latest TS nightly:

```
[Trace  - 23:47:01.943] <syntax> Response received: format (29). Request took 1 ms. Success: false . Message: Error processing request. Debug Failure. False expression: Token end is child end
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131845:38)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131777:21
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:27821:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:28247:21)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131776:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131852:21)
    at processChildNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131915:48)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131779:21
    at visitNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:27826:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:28227:21)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131776:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131852:21)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131777:21
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:27821:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:28030:24)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131776:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131852:21)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131777:21
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:27821:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:28107:24)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131776:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131852:21)
    at processChildNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131915:48)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131779:21
    at visitNodes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:27826:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:28067:24)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131776:20)
    at processChildNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131852:21)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131777:21
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:27821:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:27951:21)
    at processNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131776:20)
    at formatSpanWorker (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131589:17)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131570:208
    at Object.getFormattingScanner (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:130176:23)
    at formatSpan (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131570:31)
    at Object.formatSelection (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:131388:20)
    at Proxy.getFormattingEditsForRange (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:148025:34)
    at Proxy.<anonymous> (/Users/matb/.vscode-insiders/extensions/bierner.lit-html-1.11.1/node_modules/typescript-template-language-service-decorator/lib/template-language-service-decorator.js:120:20)
    at IOSession.Session.getFormattingEditsForRange (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:158660:45)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:157603:61)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:159369:88
    at IOSession.Session.executeWithRequestId (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:159360:28)
    at IOSession.Session.executeCommand (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:159369:33)
    at IOSession.Session.onMessage (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:159395:35)
    at Interface.<anonymous> (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:162037:31)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```
