### ISSUE TITLE
TypeError: host.isKnownTypesPackageName is not a function

### ISSUE THREAD

**Issue by edsrzf** [microsoft/TypeScript#41962]
**TypeScript Version:**  4.1.3

**Search Terms:** `getTypesPackageNameToInstall`, `isKnownTypesPackageName`

**Code**

Because this happens while using the API, I've created a GitHub repo that reproduces this issue: https://github.com/edsrzf/ts-codefix-repro

Note that I have not been able to reproduce it within an editor, such as VSCode.

**Expected behavior:**

`LanguageService.getCodeFixesAtPosition` returns code fixes and does not throw an exception when passed valid parameters.

**Actual behavior:**

`LanguageService.getCodeFixesAtPosition` throws an exception with this stack trace:

```
TypeError: host.isKnownTypesPackageName is not a function
    at getTypesPackageNameToInstall (/Users/edsrzf/projects/ts-new-repro/node_modules/typescript/lib/typescript.js:138180:25)
    at Object.getCodeActions (/Users/edsrzf/projects/ts-new-repro/node_modules/typescript/lib/typescript.js:138144:40)
    at /Users/edsrzf/projects/ts-new-repro/node_modules/typescript/lib/typescript.js:134099:77
    at Object.flatMap (/Users/edsrzf/projects/ts-new-repro/node_modules/typescript/lib/typescript.js:707:25)
    at Object.getFixes (/Users/edsrzf/projects/ts-new-repro/node_modules/typescript/lib/typescript.js:134099:23)
    at /Users/edsrzf/projects/ts-new-repro/node_modules/typescript/lib/typescript.js:147608:35
    at Object.flatMap (/Users/edsrzf/projects/ts-new-repro/node_modules/typescript/lib/typescript.js:707:25)
    at Object.getCodeFixesAtPosition (/Users/edsrzf/projects/ts-new-repro/node_modules/typescript/lib/typescript.js:147606:23)
    at main (/Users/edsrzf/projects/ts-new-repro/script.js:9:37)
```

**Playground Link:** No playground link, but again there's this GitHub repo: https://github.com/edsrzf/ts-codefix-repro

**Related Issues:** https://github.com/microsoft/TypeScript/issues/18217

**Comment by chenjigeng** [comment]
@edsrzf This PR fixes the problem of error reporting, but if you want to return code fixes correctly, You should ask the author 
of @ts-morph to add the isKnownTypesPackageName function.
