### ISSUE TITLE
Auto-import crash in find all references

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#41971]
An internal user is hitting this when running find all references.  They're using a forked version of 4.1.2 but I'm 99% sure the code changes do not affect the repro (though they might affect the line numbers).

```
Error: AutoImportProviderProject language service should never be used. To get the program, use `project.getCurrentProgram()`.
    at AutoImportProviderProject.getLanguageService (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:152355:23)
    at isLocationProjectReferenceRedirect (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:156266:35)
    at callbackProjectAndLocation (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:156283:17)
    at combineProjectOutputWorker (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:156248:24)
    at combineProjectOutputForReferences (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:156176:13)
    at IOSession.Session.getReferences (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:157478:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:156513:61)
    at D:\code\Midgard\node_modules\typescript\lib\tsserver.js:158331:88
    at IOSession.Session.executeWithRequestId (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:158322:28)
    at IOSession.Session.executeCommand (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:158331:33)
    at IOSession.Session.onMessage (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:158355:35)
    at Interface.<anonymous> (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:160565:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by amcasey** [comment]
I'm able to repro in (patched) 4.1.2 but not in (patched) master (78ded6577e05a7cb52acf6b9550f9c060ecab316).

**Comment by andrewbranch** [comment]
Reading through the code in the stack trace, I’m not sure how this is possible—AutoImportProviderProjects should be excluded from everything returned by `Session#getProjects` because `AutoImportProviderProject#isOrphan` always returns true, and those get filtered out along the way. But, I also don’t know what could have happened between 4.1.2 and now that would have changed anything around this behavior 🤔

**Comment by amcasey** [comment]
As of yesterday, I could repro at will.  Let me know if you want me to try again while screensharing.
