### ISSUE TITLE
test262 : Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by jsjzgy** [microsoft/TypeScript#42088]
# Bug Report

```
language\statements\for\S12.6.3_A2.1.js
language\statements\for\S12.6.3_A2.2.js
language\statements\for\S12.6.3_A2.js
```

When using tsc to execute the above three 262 use cases, the following error will be reported. 
How can I fix this problem

```
throw err;
^
TypeError: Cannot read property '0' of undefined
at isReachableFlowNodeWorker (/home/share/ts2panda/script-application-engine/ts2panda/node_modules/typescript/lib/typescript.js:53339:44)
at isReachableFlowNode (/home/share/ts2panda/script-application-engine/ts2panda/node_modules/typescript/lib/typescript.js:53290:26)
at checkSourceElementWorker (/home/share/ts2panda/script-application-engine/ts2panda/node_modules/typescript/lib/typescript.js:66495:106)
at checkSourceElement (/home/share/ts2panda/script-application-engine/ts2panda/node_modules/typescript/lib/typescript.js:66472:17)
at Object.forEach (/home/share/ts2panda/script-application-engine/ts2panda/node_modules/typescript/lib/typescript.js:317:30)
at checkBlock (/home/share/ts2panda/script-application-engine/ts2panda/node_modules/typescript/lib/typescript.js:63707:20)
at checkSourceElementWorker (/home/share/ts2panda/script-application-engine/ts2panda/node_modules/typescript/lib/typescript.js:66590:28)
at checkSourceElement (/home/share/ts2panda/script-application-engine/ts2panda/node_modules/typescript/lib/typescript.js:66472:17)
at checkForStatement (/home/share/ts2panda/script-application-engine/ts2panda/node_modules/typescript/lib/typescript.js:64183:13)
at checkSourceElementWorker (/home/share/ts2panda/script-application-engine/ts2panda/node_modules/typescript/lib/typescript.js:66602:28)
```

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template (which unfortunately is now filled with emojis).

**Comment by RyanCavanaugh** [comment]
Here's the code from the 262 testcase, which indeed throws
```js
try {
        for((function(){throw "NoInExpression";})(); (function(){throw "FirstExpression";})(); (function(){throw "SecondExpression";})()) {
                var in_for = "reached";
        }
        $ERROR('#1: (function(){throw "NoInExpression";})() lead to throwing exception');
} catch (e) {
        if (e !== "NoInExpression") {
                $ERROR('#1: When for (ExpressionNoIn ; Expression ; Expression) Statement is evaluated ExpressionNoIn evaluates first');
        }
}
```
