### ISSUE TITLE
Exception thrown in completion entry details on tuple index

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#42278]
```ts
const a: [x: number, y: number] = [1, 1];

a./**/
```

Looks like there is actually an exception being thrown here:

```
[Trace  - 20:32:35.228] <semantic> Sending request: completionEntryDetails (24). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/x.ts",
    "line": 2,
    "offset": 6,
    "entryNames": [
        "0"
    ]
}
[Trace  - 20:32:35.234] <semantic> Response received: completionEntryDetails (24). Request took 6 ms. Success: false . Message: Error processing request. Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:147561:96
    at Object.forEachUnique (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:116062:34)
    at getDocumentationComment (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:147560:16)
    at SymbolObject.getDocumentationComment (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:147352:49)
    at SymbolObject.getContextualDocumentationComment (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:147375:33)
    at Object.getSymbolDisplayPartsDocumentationAndSymbolKind (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:130237:40)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:119357:41
    at Object.runWithCancellationToken (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:44040:28)
    at createCompletionDetailsForSymbol (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:119356:30)
    at Object.getCompletionEntryDetails (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:119338:28)
    at Proxy.getCompletionEntryDetails (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:148356:35)
    at Proxy.<anonymous> (/Users/matb/.vscode-insiders/extensions/bierner.lit-html-1.11.1/node_modules/typescript-template-language-service-decorator/lib/template-language-service-decorator.js:96:24)
    at Proxy.<anonymous> (/Users/matb/.vscode-insiders/extensions/bierner.lit-html-1.11.1/node_modules/typescript-template-language-service-decorator/lib/template-language-service-decorator.js:96:24)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:159447:57
    at Object.mapDefined (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:612:30)
    at IOSession.Session.getCompletionEntryDetails (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:159445:33)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:158306:61)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:160051:88
    at IOSession.Session.executeWithRequestId (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:160042:28)
    at IOSession.Session.executeCommand (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:160051:33)
    at IOSession.Session.onMessage (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:160077:35)
    at Interface.<anonymous> (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:162729:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

_Originally posted by @mjbvz in https://github.com/microsoft/TypeScript/issues/42206#issuecomment-754202466_

**Comment by krishnaanaril** [comment]
@DanielRosenwasser How to reproduce this error?

**Comment by DanielRosenwasser** [comment]
`/**/` usually a marker for some specific action in our test suite. In this context, I meant to trigger completions.

However, it looks like this isn't repro'ing in the last few releases, so I'll close the issue.
