### ISSUE TITLE
Compiler crash on `exports.fn` pattern

### ISSUE THREAD

**Issue by mihailik** [microsoft/TypeScript#42350]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.0.5 and 4.1.3

### ⏯ Playground Link

[2-line example](https://www.typescriptlang.org/play?ts=4.1.3&useJavaScript=true#code/KYDwDg9gTgLgzgOgGYDsCMAKAlAbgFCiSyKoBMABALzkCyAhjABYIC2AlivkA)

### 💻 Code

```ts
exports.fn1();
exports.fn2 = Math.min;

```

### 🙁 Actual behavior

Crashing:
```
TypeError: Cannot read property 'length' of undefined
    at getPropertyOfType (C:\Users\mihai\danfo\node_modules\typescript\lib\tsc.js:44083:45)
    at getTypeOfDottedName (C:\Users\mihai\danfo\node_modules\typescript\lib\tsc.js:52423:44)
    at getEffectsSignature (C:\Users\mihai\danfo\node_modules\typescript\lib\tsc.js:52436:32)
    at getTypeAtFlowCall (C:\Users\mihai\danfo\node_modules\typescript\lib\tsc.js:52755:33)
    at getTypeAtFlowNode (C:\Users\mihai\danfo\node_modules\typescript\lib\tsc.js:52636:32)
    at getFlowTypeOfReference (C:\Users\mihai\danfo\node_modules\typescript\lib\tsc.js:52593:51)      
    at checkIdentifier (C:\Users\mihai\danfo\node_modules\typescript\lib\tsc.js:53580:28)
    at checkExpressionWorker (C:\Users\mihai\danfo\node_modules\typescript\lib\tsc.js:59973:28)       
    at checkExpression (C:\Users\mihai\danfo\node_modules\typescript\lib\tsc.js:59928:38)
    at checkNonNullExpression (C:\Users\mihai\danfo\node_modules\typescript\lib\tsc.js:55612:37)      
```

This is running `tsc.js` with: `node --inspect-brk node_modules\typescript\lib\tsc.js repor.js --out repor.out.js --allowJs` and some state in context:

![image](https://user-images.githubusercontent.com/4041967/104656418-2bdf7200-56b7-11eb-84ed-f3979a36f3de.png)

### 🙂 Expected behavior

Transpile, don't crash. Can produce errors/warnings, but not crash.

### Background

This happened when I tried to run TypeScript over the latest CodeMirror, and stumbled upon the file [runmode.node.js (see on unpkg)](https://unpkg.com/browse/codemirror@5.59.1/addon/runmode/runmode.node.js). Then, simplified to the minimal reproduction case.

As you can see from the caught error above,  `resolved.callSignatures` is `undefined` and that causes throw here.

I assume this happens because `exports` isn't treated as a normal global variable even in a variable position. But in variable position it should be treated as a variable.

**Note:** can't simplify any more, both lines are necessary. Which means it's not just bad handling of `exports`, but something more conspiratorial.

**Comment by mihailik** [comment]
Sorry, I think it really should be more urgent than `4.3.0`.

It's not an obscure bug,  TypeScript currently crashes on **CodeMirror** -- arguably the most basic core library on the web, everyone on here touches it daily in Sources and Console tab of DevTools.

**Comment by RyanCavanaugh** [comment]
Is the regression information accurate? 4.1 came out two months ago and this is the first we've heard of it, which would indicate this isn't as critical as you're describing.

**Comment by eventualbuddha** [comment]
I don't have much to contribute in terms of helping identify why this happens, but I ran into it while trying to move from yarn to pnpm: https://github.com/votingworks/vxsuite/pull/146. Downgrading to TS 4.0.5 fixed it.

**Comment by minestarks** [comment]
Already fixed, but repro at https://github.com/microsoft/tsserverfuzzer/issues/299
