### ISSUE TITLE
Debug Failure

### ISSUE THREAD

**Issue by nuanyang233** [microsoft/TypeScript#43011]
# Bug Report

Upgrade in `v4.2.2` (also an issue in `v4.2.1-rc`, tsc fail to compile with an error ` Debug Failure.`
### 🕗 Version & Regression Information

* This is a crash
* This changed between versions v4.2.1-beta and v4.2.2-rc
* This is the behaviour in every version I tried, and I reviewed the FAQ for entries about "Debug Failure."

### 💻 Code

[Maskbook](https://github.com/DimensionDev/Maskbook/tree/feature/upgrade-typescript)

### 🙁 Actual behavior

```
Error: Debug Failure.
    at Object.getModuleSpecifiers (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:91587:30)
    at getSpecifierForModuleSymbol (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:39998:62)
    at createExpressionFromSymbolChain (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:40172:63)
    at symbolToExpression (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:40159:24)
    at /Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:38966:106
    at withContext (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:39005:37)
    at symbolToExpression (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:38966:28)
    at symbolToStringWorker (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:38886:30)
    at Object.usingSingleLineStringWriter (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:10151:13)
    at symbolToString (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:38884:73)


```

### 🙂 Expected behavior

It should compile.

**Comment by Jack-Works** [comment]
I have done a simple debug. Here is some useful information:

1.  The crash happens at the type checking stage. For file (packages\theme\src\Components\ErrorBoundary\CrashUI.tsx)
2. Current type checking node is at line 68, `<code>{error.stack}</code>`
3. Here is the longer version of the call stack

![image](https://user-images.githubusercontent.com/5390719/109476669-20eb7000-7ab2-11eb-89f3-8fcd2bcc8694.png)

**Comment by Jack-Works** [comment]
Seems like it failed to `createSignatureForJSXIntrinsic` (`<code>`) in our codebase

**Comment by divdavem** [comment]
I have a similar `Debug Failure` error when upgrading `typescript` from version `4.1.5` to `4.2.2` in [assistive-webdriver](https://github.com/AmadeusITGroup/Assistive-Webdriver).

I have reproduced the error in [this simple repository](https://github.com/divdavem/typescriptUpgradeIssue).
The [only typescript code](https://github.com/divdavem/typescriptUpgradeIssue/blob/master/src/index.ts) is:

```ts
import { format } from "winston";

export const messageId = format((info) => info);
```

Note that the error seems to only happen when dependencies are installed with [pnpm](https://pnpm.js.org/), but not when they are installed with npm.

To reproduce the issue:

```
git clone https://github.com/divdavem/typescriptUpgradeIssue.git
cd typescriptUpgradeIssue
pnpm install
```

Here is the error I am getting:

```[!] (plugin typescript) Error: Debug Failure.
Error: Debug Failure.
    at Object.getModuleSpecifiers (/tmp/typescriptUpgradeIssue/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/typescript.js:111579:30)
    at getSpecifierForModuleSymbol (/tmp/typescriptUpgradeIssue/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/typescript.js:48852:62)
    at /tmp/typescriptUpgradeIssue/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/typescript.js:48710:39
    at Array.map (<anonymous>)
    at getSymbolChain (/tmp/typescriptUpgradeIssue/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/typescript.js:48708:58)
    at lookupSymbolChainWorker (/tmp/typescriptUpgradeIssue/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/typescript.js:48692:51)
    at lookupSymbolChain (/tmp/typescriptUpgradeIssue/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/typescript.js:48685:24)
    at symbolToTypeNode (/tmp/typescriptUpgradeIssue/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/typescript.js:48859:29)
    at typeToTypeNodeHelper (/tmp/typescriptUpgradeIssue/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/typescript.js:47937:28)
    at /tmp/typescriptUpgradeIssue/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/typescript.js:47740:106

**Comment by Jack-Works** [comment]
Interesting point. IIRC typescript has fixed a bug for pnpm  auto import caching recently

**Comment by divdavem** [comment]
With Typescript 4.2.3, it works fine for me now!
@andrewbranch Thank you for fixing this bug. :+1:

**Comment by rhyek** [comment]
So glad this was fixed. You guys are great. I'd been following the updates for pnpm on 4.2 before its release and recently hit this issue on a private repo and couldn't reproduce it on a separate public one so wasn't sure how to report it.
