### ISSUE TITLE
Cannot read property 'pos' of undefined

### ISSUE THREAD

**Issue by kenobi-io** [microsoft/TypeScript#43479]
# Bug Report
virsion 4.1.5

  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2017", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": "./",
    "paths": {
      "@local/core": ["../core/src/index.ts"]
    }
  },
  "exclude": ["node_modules", "tmp"]

```ts
> ng build 

An error occurred during the build:
TypeError: Cannot read property 'pos' of undefined
    at createFileDiagnosticAtReference (/node_modules/typescript/lib/typescript.js:107529:68)
    at addProgramDiagnosticAtRefPath (/node_modules/typescript/lib/typescript.js:107547:93)
    at checkSourceFilesBelongToPath (/node_modules/typescript/lib/typescript.js:107208:25)
    at Object.getCommonSourceDirectory (/ode_modules/typescript/lib/typescript.js:105612:40)
    at Object.getDeclarationEmitOutputFilePath (/node_modules/typescript/lib/typescript.js:17179:125)
    at getOutputPathsFor (/node_modules/typescript/lib/typescript.js:99488:112)
    at forEachEmittedFile (/node_modules/typescript/lib/typescript.js:99425:41)
    at Object.emitFiles (/node_modules/typescript/lib/typescript.js:99654:9)
    at emitWorker (/node_modules/typescript/lib/typescript.js:106125:33)
    at /node_modules/typescript/lib/typescript.js:106102:72
    at runWithCancellationToken (/node_modules/typescript/lib/typescript.js:106205:24)
    at Object.emit (node_modules/typescript/lib/typescript.js:106102:26)
    at getFileEmitOutput (/node_modules/typescript/lib/typescript.js:108003:26)
    at updateShapeSignature (/node_modules/typescript/lib/typescript.js:108239:36)
    at getFilesAffectedByUpdatedShapeWhenModuleEmit (/node_modules/typescript/lib/typescript.js:108442:46)
    at Object.getFilesAffectedBy (/node_modules/typescript/lib/typescript.js:108194:144)
Cannot read property 'pos' of undefined
```

**Comment by RyanCavanaugh** [comment]
Please try again with 4.2

**Comment by shyamal890** [comment]
@RyanCavanaugh I upgraded to typescript version 4.2.4 and still it didn't solve the issue. 

This is the error I get:
```
@demo/core-app: TypeError: Cannot read property 'pos' of undefined
@demo/core-app:     at Object.getReferencedFileLocation (E:\Dropbox\SmartTask\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:106394:61)
@demo/core-app:     at Object.fileIncludeReasonToDiagnostics (E:\Dropbox\SmartTask\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:112245:40)
@demo/core-app:     at processReason (E:\Dropbox\SmartTask\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:108744:75)
@demo/core-app:     at Array.forEach (<anonymous>)
@demo/core-app:     at createDiagnosticExplainingFile (E:\Dropbox\SmartTask\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:108730:91)
@demo/core-app:     at addProgramDiagnosticExplainingFile (E:\Dropbox\SmartTask\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:108767:36)
@demo/core-app:     at checkSourceFilesBelongToPath (E:\Dropbox\SmartTask\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:108415:25)
@demo/core-app:     at E:\Dropbox\SmartTask\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:106886:295
@demo/core-app:     at Object.getCommonSourceDirectory (E:\Dropbox\SmartTask\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:100686:105)
@demo/core-app:     at Object.getCommonSourceDirectory (E:\Dropbox\SmartTask\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:106886:44)
```

I am attaching an example Github repo - https://github.com/shyamal890/mono-demo which you can try.

I have also created a [stackoverflow question](https://stackoverflow.com/questions/67553770/mono-repo-accessing-typescript-file-outside-of-project-gives-pos-undefined-er) which hasn't received any answers yet.  

I hope the typescript team can look into this issue and help us solve it.

**Comment by shyamal890** [comment]
@RyanCavanaugh I upgraded to typescript version 4.2.4 and still it didn't solve the issue.

This is the error I get:

```
@demo/core-app: TypeError: Cannot read property 'pos' of undefined
@demo/core-app:     at Object.getReferencedFileLocation (E:\Dropbox\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:106394:61)
@demo/core-app:     at Object.fileIncludeReasonToDiagnostics (E:\Dropbox\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:112245:40)
@demo/core-app:     at processReason (E:\Dropbox\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:108744:75)
@demo/core-app:     at Array.forEach (<anonymous>)
@demo/core-app:     at createDiagnosticExplainingFile (E:\Dropbox\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:108730:91)
@demo/core-app:     at addProgramDiagnosticExplainingFile (E:\Dropbox\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:108767:36)
@demo/core-app:     at checkSourceFilesBelongToPath (E:\Dropbox\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:108415:25)
@demo/core-app:     at E:\Dropbox\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:106886:295
@demo/core-app:     at Object.getCommonSourceDirectory (E:\Dropbox\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:100686:105)
@demo/core-app:     at Object.getCommonSourceDirectory (E:\Dropbox\Temp\packages\core-app\node_modules\typescript\lib\typescript.js:106886:44)
```

I am attaching an example Github repo - https://github.com/shyamal890/mono-demo which you can try.

I have also created a stackoverflow question which hasn't received any answers yet.

I hope the typescript team can look into this issue and help us solve it.

**Comment by FinnStutzenstein** [comment]
I got this error, too. I resolved it in this way:
- I added some debug statements into the `createFileDiagnosticAtReference ` function to log `message` and `args`
- In the message I got the code 6095 and the file with the error
- It was a libraray laying next to the source and it wasn't included in `rootDir` in the tsconfig.json

I modified the `rootDir` to also include the libraray and the error is gone.

**Comment by andrewbranch** [comment]
I can’t repro any of these; closing as stale. Please open a new issue if the problem persists with `typescript@next` and you have repro steps. Thanks!
