### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined at Object.getJSXImplicitImportBase

### ISSUE THREAD

**Issue by salik1992** [microsoft/TypeScript#44024]
# Bug Report

### 🔎 Search Terms

ts getJSXImplicitImportBase
ts jest getJSXImplicitImportBase
ts file.pragmas

### 🕗 Version & Regression Information

4.2.4

- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about everything but it hasn't been covered.

### ⏯ Playground Link

I can't provide a link to a playground as this issue seems to be tied to the structure of the repository and dependencies.
I have tried to reproduce a minimal example but without luck for now.

### 💻 Code

This seems to be tied to the structure of the repository and dependencies:

- There are 2 monorepositories - `core` and `product`
- One of the packages in `core` is `toast`
- In `product` there are `ui` and `services`
- Both`ui` and `services` are dependent on `toast` which is installed as an external dependency from npmjs registry in both of them
- `ui` is dependent on `services`
```txt
     toast   <-- external dependency (core monorepo)
      |  |
services |  <-- product monorepo
     \   |       
       ui   <-- product monorepo
```
In `ui` there is a `Toast` with custom visual implementations for the `toast` from `core` with its own tests.

### 🙁 Actual behavior

Running tests with `npx jest packages/ui/src/components/Toast/__tests__/Toast.spec.tsx` crashes with:
```
TypeError: Cannot read property 'get' of undefined

      at Object.getJSXImplicitImportBase (../../node_modules/typescript/lib/typescript.js:19175:95)
      at transformSourceFile (../../node_modules/typescript/lib/typescript.js:88624:51)
      at transformSourceFileOrBundle (../../node_modules/typescript/lib/typescript.js:82540:57)
      at transformation (../../node_modules/typescript/lib/typescript.js:100190:24)
      at transformRoot (../../node_modules/typescript/lib/typescript.js:100217:82)
      at Object.transformNodes (../../node_modules/typescript/lib/typescript.js:100201:78)
      at emitJsFileOrBundle (../../node_modules/typescript/lib/typescript.js:100852:32)
      at emitSourceFileOrBundle (../../node_modules/typescript/lib/typescript.js:100799:13)
      at forEachEmittedFile (../../node_modules/typescript/lib/typescript.js:100520:34)
      at Object.emitFiles (../../node_modules/typescript/lib/typescript.js:100779:9)
```

when inspecting the issue I have noticed this behaviour:
- The file that causes the crash is `packages/ui/node_modules/@private/core-toast/src/index.ts`
- `SourceFileObject` of this file is missing `pragmas` map
- But it contains `redirectInfo` with `redirectTarget`: `packages/ui/node_modules/@private/product-services/node_modules/@private/core-toast/src/index.ts`
- The `SourceFileObject` from this `redirectInfo` contains `pragmas` map

This happens during local development as well as in travis CI.

### 🙂 Expected behavior

The jest tests run without crashing.

### Maybe related issue
[#43373](43373)

**Comment by weswigham** [comment]
Hm, this is difficult to verify without a repro, but I _think_ the problem lies in `ts-jest` using our transformation API with a preTransform and our factory not retaining information.... maybe. In fact, looking over `ts-jest`'s source code, I fully believe that, given how they implement [their visitors](https://github.com/kulshekhar/ts-jest/blob/master/src/transformers/hoist-jest.ts#L162) - by using object spread and not our factory API, they're un-setting node prototypes. You can try to see if [this build](https://github.com/microsoft/TypeScript/pull/44064#issuecomment-840084206) helps, but since `ts-build` doesn't use our factory to manufacture the nodes, I don't think it'll help. If you can locate [this transform](https://github.com/kulshekhar/ts-jest/blob/master/src/transformers/path-mapping.ts) and [this transform](https://github.com/kulshekhar/ts-jest/blob/master/src/transformers/hoist-jest.ts) in your install of `ts-jest`, and modify them so that every spread is wrapped like `Object.setPrototypeOf({ ... }, Object.getPrototypeOf(original))`, and that fixes the crash, that change to `ts-jest` may be the solution.

Ofc, this is only the case because our internal `RedirectedFile` construct relies on prototypical inheritance to function, which makes maintaining prototypes a quiet requirement of a transformer...

**Comment by salik1992** [comment]
Sorry for getting back to this now. I was blocked by some other work.

I have tried that specific build but no luck.

I have found those two transforms in generated js files inside node_modules. However, I haven't managed to fix it by wrapping those spreads. Just out of curiosity I have tried to set pragmas if it was undefined from that `redirectTarget` and it crashes further down the line on `text` being undefined in `computeLineStarts` so I feel like your belief is correct.

Should I open an issue in ts-jest or do you want to do it since you know a lot more about the specifics?

**Comment by ahnpnl** [comment]
> Hm, this is difficult to verify without a repro, but I _think_ the problem lies in `ts-jest` using our transformation API with a preTransform and our factory not retaining information.... maybe. In fact, looking over `ts-jest`'s source code, I fully believe that, given how they implement [their visitors](https://github.com/kulshekhar/ts-jest/blob/master/src/transformers/hoist-jest.ts#L162) - by using object spread and not our factory API, they're un-setting node prototypes. You can try to see if [this build](https://github.com/microsoft/TypeScript/pull/44064#issuecomment-840084206) helps, but since `ts-build` doesn't use our factory to manufacture the nodes, I don't think it'll help. If you can locate [this transform](https://github.com/kulshekhar/ts-jest/blob/master/src/transformers/path-mapping.ts) and [this transform](https://github.com/kulshekhar/ts-jest/blob/master/src/transformers/hoist-jest.ts) in your install of `ts-jest`, and modify them so that every spread is wrapped like `Object.setPrototypeOf({ ... }, Object.getPrototypeOf(original))`, and that fixes the crash, that change to `ts-jest` may be the solution.
> 
> Ofc, this is only the case because our internal `RedirectedFile` construct relies on prototypical inheritance to function, which makes maintaining prototypes a quiet requirement of a transformer...

Hi, I guess migrating to factory API should be the right direction?

**Comment by weswigham** [comment]
That's what I'd assume would fix the issue, yeah.

**Comment by RyanCavanaugh** [comment]
This is fixed by [#48862](https://github.com/microsoft/TypeScript/pull/48862). The two copies of the same package containing emitted `.ts` files crashed in 4.2.4 with `computeLineStarts` reading redirected source text; the same project emits successfully in 6.0.3 and the current native compiler. The PR base commit reproduces the crash and its merged commit does not.
