### ISSUE TITLE
TS Server fatal error:  Debug Failure. Expected 159 <= 158

### ISSUE THREAD

**Issue by JounQin** [microsoft/TypeScript#44051]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.3.0-dev.20210510

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️ Please review and upload this log file to help us diagnose this crash:
`/Users/JounQin/Library/Application Support/Code/logs/20210511T152509/exthost2/vscode.typescript-language-features/tsserver-log-2rKk3e/tsserver.log`
The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. Expected 159 <= 158
    at attachFileToDiagnostic (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:18945:30)
    at Object.attachFileToDiagnostics (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:18959:42)
    at parseSourceFileWorker (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:29786:46)
    at Object.parseSourceFile (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:29609:26)
    at Object.createSourceFile (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:29407:29)
    at Object.createLanguageServiceSourceFile (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:152856:29)
    at acquireOrUpdateDocument (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:126153:37)
    at Object.acquireDocumentWithKey (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:126119:20)
    at getOrCreateSourceFileByPath (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:153259:41)
    at Object.getOrCreateSourceFile [as getSourceFile] (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:153206:24)
    at findSourceFileWorker (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:110858:29)
    at findSourceFile (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:110768:26)
    at processImportedModules (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:111142:25)
    at findSourceFileWorker (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:110907:17)
    at findSourceFile (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:110768:26)
    at /Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:110720:85
    at getSourceFileFromReferenceWorker (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:110687:34)
    at processSourceFile (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:110720:13)
    at processRootFile (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:110530:13)
    at /Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:109397:67
    at Object.forEach (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:190:30)
    at Object.createProgram (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:109397:16)
    at synchronizeHostData (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:153136:26)
    at Proxy.getProgram (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:153268:13)
    at Proxy.proxy.<computed> (/Users/JounQin/.vscode/extensions/asvetliakov.snapshot-tools-0.4.0/node_modules/typescript-snapshots-plugin/out/index.js:38:33)
    at ConfiguredProject.Project.updateGraphWorker (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:158216:53)
    at ConfiguredProject.Project.updateGraph (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:158144:42)
    at ConfiguredProject.updateGraph (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:159105:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:160820:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:161858:44)
    at /Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:162198:97
    at Object.flatMap (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:515:25)
    at ProjectService.applyChangesInOpenFiles (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:162198:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:163253:46)
    at /Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:165170:88
    at IOSession.Session.executeWithRequestId (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:165161:28)
    at IOSession.Session.executeCommand (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:165170:33)
    at IOSession.Session.onMessage (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:165196:35)
    at Interface.<anonymous> (/Users/JounQin/.vscode/extensions/ms-vscode.vscode-typescript-next-4.3.20210510/node_modules/typescript/lib/tsserver.js:167798:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|64.00GB (38.70GB free)|
|Process Argv|--crash-reporter-id 69822cf1-3df3-4a81-aff5-09461f9c510d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
aixcoder|aix|3.0.12
jest-snippets|and|1.8.0
vscode-apollo|apo|1.19.1
snapshot-tools|asv|0.4.0
markdown-preview-github-styles|bie|0.2.0
better-toml|bun|0.3.2
multi-cursor-case-preserve|Car|1.0.5
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.26.0
plantuml|jeb|2.14.5
vscode-todo-highlight|jgc|2.0.1
Angular2|joh|11.0.0
alauda-snippets|Jou|0.3.0
vscode-mdx|Jou|0.2.3
intellij-idea-keybindings|k--|1.4.4
restart-your-ts-server|kin|0.0.3
kite|kit|0.142.0
graphql-for-vscode|kum|1.15.3
vscode-language-babel|mgm|0.0.31
Angular-BeastCode|Mik|10.0.3
vscode-language-pack-zh-hans|MS-|1.56.2
typescript-javascript-grammar|ms-|0.0.55
vscode-typescript-next|ms-|4.3.20210510
vscode-typescript-tslint-plugin|ms-|1.3.3
color-highlight|nau|2.3.0
vetur|oct|0.33.1
vscode-yaml|red|0.18.0
LiveServer|rit|5.6.1
indenticator|Sir|0.7.0
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.86.0
svelte-vscode|sve|104.12.0
tabnine-vscode|Tab|3.4.4
vscode-icons|vsc|11.4.0
codetour|vsl|0.0.52
vscode-wakatime|Wak|8.0.0
change-case|wma|1.0.0
yao-translate|Yao|1.0.1
dictionary-completion|yzh|1.1.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
bridgeflightcf:30299255

```

</details>

**Comment by mjbvz** [comment]
Please try to fill in the issue template

**Comment by RyanCavanaugh** [comment]
That link doesn't work - can you update?

**Comment by JounQin** [comment]
@RyanCavanaugh Oh, sorry, that branch has been merged and deleted.

https://github.com/rx-ts/babel-preset-proposal-typescript

**Comment by RyanCavanaugh** [comment]
I need the log content or some other clue to know which file to start with. Any pointers?

**Comment by JounQin** [comment]
Maybe https://github.com/rx-ts/babel-preset-proposal-typescript/blob/master/test/class-static-block.ts

I'm not on a computer, sorry.

That repo aims ES proposals which are not supported by TypeScript yet. But I expect it reports errors, not crash.
