### ISSUE TITLE
Support node es modules resolution

### ISSUE THREAD

**Issue by tsapko3628** [microsoft/TypeScript#44342]
# Bug Report

### 🕗 Version & Regression Information

Versions:
* 4.3.2
* 4.1.2

- This is a crash
- This is the behavior in every version I tried

### ⏯ Playground Link

[Minimal repoducible example](https://github.com/tsapko3628/Support-node-es-modules-resolution-example)

### 💻 Code

Run tsc (yarn tsc, yarn exec tsc, npx tsc, ./node_modules/.bin/tsc) with nodejs flag --experimental-specifier-resolution=node (NODE_OPTIONS="--experimental-specifier-resolution=node" tsc)

### 🙁 Actual behavior

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "file:///path/to/project/node_modules/typescript/bin/tsc" 
    at Loader.getFormat (internal/modules/esm/loader.js:117:13)
    at async Loader.getModuleJob (internal/modules/esm/loader.js:242:20)
    at async Loader.import (internal/modules/esm/loader.js:176:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_INVALID_MODULE_SPECIFIER'
}
```

### 🙂 Expected behavior
Build without errors

**Comment by tsapko3628** [comment]
also, it's not so important, add building to native modules and add path to alternative dist in package.json. Thank you

**Comment by dansaper** [comment]
I assume this is related to https://gist.github.com/weswigham/22a064ffa961d5921077132ae2f8da78?

**Comment by tsapko3628** [comment]
Not, it's not.
This problem because of bin script definition.
Bin scripts defined as
```json

    {
        "tsc": "./bin/tsc.js",
        "tsserver": "./bin/tsserver"
    }
```
And when I call `yarn tsc`, nodejs trying to run `node_modules/typescript/bin/tsc`. This file hasn't extension and nodejs throws an error.
Why it works in Jest?
Because it use another `bin` declaration like this:
```json
{
"jest": "./bin/jest.js"
}
```
For package manager, this script has link with name jest, but nodejs run jest.js, file with extension.
So, solving my problem is adding `.js` in bin files and in paths in `package.json` bin. It won't change behavior for exists project by help projects with configurations like mine.

As you can see, another experimental flags for native modules aren't change behavior (Now I run tsc without `--experimental-specifier-resolution`, but with all another flags in scripts and it works)

**Comment by tsapko3628** [comment]
I created pull request with resolution. Can somebody approve it?
