### ISSUE TITLE
TSService got killed 

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/TypeScript#44590]
# Bug Report

When I was testing my code-completion extension, tsservice got killed. Here is the log:
```
[Info  - 06:08:42.89] Starting TS Server 
[Info  - 06:08:42.90] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 06:08:42.93] <syntax> Forking...
[Info  - 06:08:42.102] <syntax> Starting...
[Info  - 06:08:42.102] <semantic> Forking...
[Info  - 06:08:42.108] <semantic> Starting...
[Info  - 06:37:48.947] Killing TS Server
[Info  - 06:37:49.752] TSServer exited
[Info  - 06:37:49.753] Starting TS Server 
[Info  - 06:37:49.753] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 06:37:49.756] <syntax> Forking...
[Info  - 06:37:49.762] <syntax> Starting...
[Info  - 06:37:49.763] <semantic> Forking...
[Info  - 06:37:49.766] <semantic> Starting...
[Info  - 07:09:20.668] TSServer exited
[Info  - 07:09:20.669] Starting TS Server 
[Info  - 07:09:20.669] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 07:09:20.672] <syntax> Forking...
[Info  - 07:09:20.675] <syntax> Starting...
[Info  - 07:09:20.676] <semantic> Forking...
[Info  - 07:09:20.677] <semantic> Starting...
```

and the trace:

```
A non-recoverable error occurred while executing tsserver command: updateOpen
/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js:5
Error processing request. Cannot read property 'path' of undefined
TypeError: Cannot read property 'path' of undefined
    at ConfiguredProject.Project.isRoot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158095:79)
    at ConfiguredProject.Project.containsScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:158079:26)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:159269:34
    at Object.forEachEntry (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:13586:26)
    at ConfiguredProject.hasOpenRef (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:159267:86)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:162084:33
    at Map.forEach (<anonymous>)
    at ProjectService.removeOrphanConfiguredProjects (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:162082:41)
    at ProjectService.cleanupAfterOpeningFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:162037:22)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:162241:26)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:163288:46)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165205:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165196:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165205:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165231:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:167833:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js:5
A non-recoverable error occurred while executing tsserver command: updateOpen
/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js:5
```

**Comment by RyanCavanaugh** [comment]
We'd need some way to reproduce this

**Comment by HaoboGu** [comment]
I don't know how to reproduce it, it occurs randomly when I'm testing my extension by calling `vscode.commands.executeCommand<vscode.CompletionList>('vscode.executeCompletionItemProvider', uri, pos)` a lot of times in a large project.
