### ISSUE TITLE
Crash in inlay hints

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#44960]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash

### 💻 Code

```
Cannot read property 'flags' of undefined

    TypeError: Cannot read property 'flags' of undefined
        at Object.getCheckFlags (D:\opensource\TypeScript\built\local\tsserver.js:18790:23)
        at getTypeOfSymbol (D:\opensource\TypeScript\built\local\tsserver.js:53579:33)
        at getTypeOfNode (D:\opensource\TypeScript\built\local\tsserver.js:81541:24)
        at Object.getTypeAtLocation (D:\opensource\TypeScript\built\local\tsserver.js:45590:31)
        at visitVariableLikeDeclaration (D:\opensource\TypeScript\built\local\tsserver.js:135281:47)
        at visitor (D:\opensource\TypeScript\built\local\tsserver.js:135213:21)
        at visitNodes (D:\opensource\TypeScript\built\local\tsserver.js:29204:30)
        at Object.forEachChild (D:\opensource\TypeScript\built\local\tsserver.js:29450:24)
        at visitor (D:\opensource\TypeScript\built\local\tsserver.js:135232:27)
        at visitNode (D:\opensource\TypeScript\built\local\tsserver.js:29195:24)
        at Object.forEachChild (D:\opensource\TypeScript\built\local\tsserver.js:29448:21)
        at visitor (D:\opensource\TypeScript\built\local\tsserver.js:135232:27)
        at visitNodes (D:\opensource\TypeScript\built\local\tsserver.js:29204:30)
        at Object.forEachChild (D:\opensource\TypeScript\built\local\tsserver.js:29441:24)
        at visitor (D:\opensource\TypeScript\built\local\tsserver.js:135232:27)
        at visitNode (D:\opensource\TypeScript\built\local\tsserver.js:29195:24)
        at Object.forEachChild (D:\opensource\TypeScript\built\local\tsserver.js:29325:21)
        at visitor (D:\opensource\TypeScript\built\local\tsserver.js:135232:27)
        at visitNode (D:\opensource\TypeScript\built\local\tsserver.js:29195:24)
        at Object.forEachChild (D:\opensource\TypeScript\built\local\tsserver.js:29289:21)
        at visitor (D:\opensource\TypeScript\built\local\tsserver.js:135232:27)
        at visitNodes (D:\opensource\TypeScript\built\local\tsserver.js:29204:30)
        at Object.forEachChild (D:\opensource\TypeScript\built\local\tsserver.js:29450:24)
        at visitor (D:\opensource\TypeScript\built\local\tsserver.js:135232:27)
        at visitNode (D:\opensource\TypeScript\built\local\tsserver.js:29195:24)
        at Object.forEachChild (D:\opensource\TypeScript\built\local\tsserver.js:29448:21)
        at visitor (D:\opensource\TypeScript\built\local\tsserver.js:135232:27)
        at visitNodes (D:\opensource\TypeScript\built\local\tsserver.js:29204:30)
        at Object.forEachChild (D:\opensource\TypeScript\built\local\tsserver.js:29443:24)
        at visitor (D:\opensource\TypeScript\built\local\tsserver.js:135232:27)
        at Object.provideInlayHints (D:\opensource\TypeScript\built\local\tsserver.js:135189:13)
        at Proxy.provideInlayHints (D:\opensource\TypeScript\built\local\tsserver.js:155768:34)
```

**Comment by Kingwl** [comment]
Well. It somes with destructions.

**Comment by mjbvz** [comment]
Also ran into this. Simple repo :

```js
const { requestId } = { requestId: 123 };
```
