### ISSUE TITLE
Compiler API : Allow virtual files in virtual directories to be imported by other files 

### ISSUE THREAD

**Issue by craigphicks** [microsoft/TypeScript#44974]
# Suggestion

## 🔍 Search Terms

Couldn't find anything related.

## ✅ Viability Checklist

My suggestion meets these guidelines:

[* ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
[* ] This wouldn't change the runtime behavior of existing JavaScript code
[* ] This could be implemented without emitting different JS based on the types of the expressions
[* ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
[* ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

In a test program (posted in the next comment) , I am compiling some real files and some virtual files.
The virtual files are `ts.SourceFile`s with a virtual path, supplied via a `ts.compilerHost` with a patched `getSourceFile()` and a patched `fileExists()`.  The virtual files are imported via relative paths by other files.

If all of the imported virtual files have directory paths that really exist, then the compiler succeeds, otherwise it fails.

The test program has two iterations.  

One the first iteration it creates real directories for the virtual files and the compile succeeds.
```
/tmp/testRyVRx3
├── dist
│   ├── gen
│   │   ├── bdir
│   │   │   └── b.js
│   │   └── cdir
│   │       └── c.js
│   └── src
│       └── a1.js
├── gen
│   ├── bdir
│   └── cdir
└── src
    └── a1.ts
```
The created directories are 
```
├── gen
│   ├── bdir
│   └── cdir
```
and as you can see they contain no real files.  However there are virtual files `gen/bdir/b.ts` and `gen/cdir/c.ts`

One the second iteration it does NOT create real directories for the virtual files and the compiler fails with errors like this -
```
../../../../tmp/testRyVRx3/gen/bdir/b.ts:1:20 - error TS2307: Cannot find module '../cdir/c' or its corresponding type declarations.

1 import * as c from '../cdir/c'
                     ~~~~~~~~~~~
../../../../tmp/testRyVRx3/src/a1.ts:1:20 - error TS2307: Cannot find module '../gen/bdir/b' or its corresponding type declarations.

1 import * as b from '../gen/bdir/b'
                     ~~~~~~~~~~~~~~~
../../../../tmp/testRyVRx3/src/a1.ts:2:20 - error TS2307: Cannot find module '../gen/cdir/c' or its corresponding type declarations.

2 import * as c from '../gen/cdir/c'
                     ~~~~~~~~~~~~~~~
```

## ⭐ Suggestion

It seems likely that when deciding  whether an module to be imported exists, the code checks whether the path really exists as a pre-condition, even in the case of a virtual file.  The suggestion is to remove that pre-condition.

A lesser help would be an error message that says the directory doesn't exist, rather than saying the file doesn't exist.

## 💻 Use Cases

Semantic transforms.

**Comment by craigphicks** [comment]
```
import ts from 'typescript';
import _ from 'lodash';
import dedent from 'ts-dedent';
import fs from 'fs';
import path from 'path';
import cp from 'child_process';
import os from 'os';
import {} from 'ts-expose-internals';

export class CompilerX {
  private readonly host: ts.CompilerHost;
  private _program: ts.Program | undefined;
  private _typeChecker: ts.TypeChecker | undefined;
  private readonly compilerOptions: ts.CompilerOptions;
  constructor(compilerOptionsIn: ts.CompilerOptions = {}) {
    this.compilerOptions = _.cloneDeep(compilerOptionsIn);
    this.host = ts.createCompilerHost(this.compilerOptions, true);
  }
  private static createHostWithCache(
    hostOrig: ts.CompilerHost,
    newFileCache: Map<string, ts.SourceFile>
  ): ts.CompilerHost {
    const origFileCache = new Map<string, ts.SourceFile>(newFileCache);
    return {
      ...hostOrig,
      getSourceFile: (fileName: string, languageVersion: ts.ScriptTarget) => {
        let sourceFile: undefined | ts.SourceFile;
        fileName = ts.normalizePath(fileName);
        let fromCache = false;
        if (newFileCache.has(fileName)) {
          sourceFile = newFileCache.get(fileName);
          //newFileCache.delete(fileName); // delete it so that hereafter program will use it's own cache
          fromCache = true;
        } else sourceFile = hostOrig.getSourceFile(fileName, languageVersion);
        if (origFileCache.has(fileName))
          console.log(
            `${fromCache ? 'cache, ' : 'notcache'}getSourceFile(${fileName})`
          );
        return sourceFile;
      },
      fileExists: (filename: string) => {
        let exists = hostOrig.fileExists(filename);
        if (origFileCache.has(filename)) {
          const existsOrig = exists;
          exists = true;
          console.log(`fileExists(${filename})= ${existsOrig}=>${exists}`);
        }
        return exists;
      },
    };
  }
  get program(): ts.Program {
    if (!this._program) throw new Error('program undefined');
    return this._program;
  }
  get typeChecker(): ts.TypeChecker {
    if (!this._typeChecker) throw new Error('typeChecker undefined');
    return this._typeChecker;
  }
  compileProgram(
    newSourceFiles: ReadonlyArray<[string, ts.SourceFile]> | undefined,
    filepaths: ReadonlyArray<string>,
    emit: boolean
  ): void {
    let host = this.host;
    if (newSourceFiles) {
      filepaths = [...newSourceFiles.map(([fp, _]) => fp), ...filepaths];
      const cache = new Map<string, ts.SourceFile>(newSourceFiles);
      host = CompilerX.createHostWithCache(this.host, cache);
    }
    this._program = ts.createProgram(
      filepaths,
      this.compilerOptions,
      host,
      this._program
    );
    this._typeChecker = this._program.getTypeChecker();
    if (this._program!.getGlobalDiagnostics().length) {
      console.error(
        ts.formatDiagnosticsWithColorAndContext(
          this._program!.getGlobalDiagnostics(),
          this.host
        )
      );
      throw new Error('this.program.getGlobalDiagnostics()');
    }
    if (ts.getPreEmitDiagnostics(this._program!).length) {
      console.error(
        ts.formatDiagnosticsWithColorAndContext(
          ts.getPreEmitDiagnostics(this._program!),
          this.host
        )
      );
      throw new Error('ts.getPreEmitDiagnostics(this.program)');
    }
    filepaths.forEach((fp) => {
      const sourceFile = this._program!.getSourceFile(fp);
      if (!sourceFile) {
        throw new Error(`sourceFile for ${fp} not found`);
      }
      if (ts.getPreEmitDiagnostics(this._program!, sourceFile).length) {
        console.error(
          ts.formatDiagnosticsWithColorAndContext(
            ts.getPreEmitDiagnostics(this._program!, sourceFile),
            this.host
          )
        );
        throw new Error('ts.getPreEmitDiagnostics(this.program, sourceFile)');
      }
    });
    if (emit) {
      const emitres = this._program.emit();
      if (emitres.diagnostics.length) {
        console.error(
          ts.formatDiagnosticsWithColorAndContext(
            emitres.diagnostics,
            this.host
          )
        );
      }
    }
  }
  emit(sourceFile: ts.SourceFile): void {
    if (!this._program) {
      throw new Error('this._program is undefined');
    }
    const emitres = this._program!.emit(sourceFile);
    if (emitres.diagnostics.length) {
      console.error(
        ts.formatDiagnosticsWithColorAndContext(emitres.diagnostics, this.host)
      );
    }
  }
}

const projdir = fs.mkdtempSync(path.join(os.tmpdir(), 'test'));
console.log(`project dir is ${projdir}`)
//const projdir = path.resolve('./tmp/test');

const scriptTarget = ts.ScriptTarget.ES2020;
const defaultCompilerOptions = {
  lib: ['lib.es2020.d.ts'],
  module: ts.ModuleKind.CommonJS,
  target: scriptTarget,
  noEmit: false, // for transformer with output, it must be false
  strict: true,
  esModuleInterop: true,
  skipLibCheck: true,
  forceConsistentCasingInFileNames: true,
  declaration: false,
  configDirPath: path.join(projdir, 'tsconfig.json'),
  outDir: path.join(projdir, 'dist'), // internally convert to full path
  rootDir: path.join(projdir, ''), // internally convert to full path
};

const files = [
  {
    virtual: false,
    basename: 'src/a1.ts',
    text: dedent`
      import * as b from '../gen/bdir/b'
      import * as c from '../gen/cdir/c'
      b.name;
      c.name;

      `,
  },
  {
    virtual: true,
    basename: 'gen/bdir/b.ts',
    text: dedent`
    import * as c from '../cdir/c'
    export const name = 'my name is b'
    c.name;

    `,
  },
  {
    virtual: true,
    basename: 'gen/cdir/c.ts',
    text: dedent`
      export const name = 'my name is c'
      `,
  },
];
for (let iter = 0; iter < 2; iter++) {
  fs.rmdirSync(projdir, {recursive: true});
  fs.mkdirSync(projdir, {recursive: true});
  if (iter === 0)
    console.log('iter 0, create real directories for the virtual files - OK');
  else
    console.log(
      'iter 1, do not create real directories for the virtual files - NG'
    );
  const virtual: [string, ts.SourceFile][] = [];
  const real: string[] = [];
  files.forEach((s) => {
    const fpath = path.join(projdir, s.basename);
    if (s.virtual) {
      if (iter === 0) fs.mkdirSync(path.dirname(fpath), {recursive: true});
      const sourceFile = ts.createSourceFile(
        fpath,
        s.text,
        defaultCompilerOptions.target!
      );
      virtual.push([fpath, sourceFile]);
    } else {
      fs.mkdirSync(path.dirname(fpath), {recursive: true});
      fs.writeFileSync(fpath, s.text);
      real.push(fpath);
    }
  });

  const cx = new CompilerX(defaultCompilerOptions);
  cx.compileProgram(virtual, real, true);

  console.log(cp.execSync(`tree ${projdir}`).toString());
}

```

**Comment by craigphicks** [comment]
Entire example output from above program - 
```
$ npx ts-node test/demo-prob-cmp.ts 
project dir is /tmp/testRyVRx3
iter 0, create real directories for the virtual files - OK
cache, getSourceFile(/tmp/testRyVRx3/gen/bdir/b.ts)
fileExists(/tmp/testRyVRx3/gen/cdir/c.ts)= false=>true
cache, getSourceFile(/tmp/testRyVRx3/gen/cdir/c.ts)
fileExists(/tmp/testRyVRx3/gen/bdir/b.ts)= false=>true
fileExists(/tmp/testRyVRx3/gen/cdir/c.ts)= false=>true
/tmp/testRyVRx3
├── dist
│   ├── gen
│   │   ├── bdir
│   │   │   └── b.js
│   │   └── cdir
│   │       └── c.js
│   └── src
│       └── a1.js
├── gen
│   ├── bdir
│   └── cdir
└── src
    └── a1.ts

9 directories, 4 files

iter 1, do not create real directories for the virtual files - NG
cache, getSourceFile(/tmp/testRyVRx3/gen/bdir/b.ts)
cache, getSourceFile(/tmp/testRyVRx3/gen/cdir/c.ts)
../../../../tmp/testRyVRx3/gen/bdir/b.ts:1:20 - error TS2307: Cannot find module '../cdir/c' or its corresponding type declarations.

1 import * as c from '../cdir/c'
                     ~~~~~~~~~~~
../../../../tmp/testRyVRx3/src/a1.ts:1:20 - error TS2307: Cannot find module '../gen/bdir/b' or its corresponding type declarations.

1 import * as b from '../gen/bdir/b'
                     ~~~~~~~~~~~~~~~
../../../../tmp/testRyVRx3/src/a1.ts:2:20 - error TS2307: Cannot find module '../gen/cdir/c' or its corresponding type declarations.

2 import * as c from '../gen/cdir/c'
                     ~~~~~~~~~~~~~~~


/mnt/common/github/tscapi/test/demo-prob-cmp.ts:94
      throw new Error('ts.getPreEmitDiagnostics(this.program)');
            ^
Error: ts.getPreEmitDiagnostics(this.program)
    at CompilerX.compileProgram (/mnt/common/github/tscapi/test/demo-prob-cmp.ts:94:13)
    at Object.<anonymous> (/mnt/common/github/tscapi/test/demo-prob-cmp.ts:215:6)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/mnt/common/github/tscapi/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/mnt/common/github/tscapi/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at main (/mnt/common/github/tscapi/node_modules/ts-node/src/bin.ts:198:14)

```

**Comment by craigphicks** [comment]
Solved by also patching the host.readDirectory() function as follows:
```
      directoryExists: (dirpath: string) => {
        let exists = hostOrig.directoryExists!(dirpath);
        if (!exists) {
          exists = ![...origFileCache.keys()].every(fp=>{
            return !path.dirname(fp).startsWith(dirpath)
          })
          if (exists && logLevel>=2)
            console.log(`directoryExists(${dirpath})= false=>${exists}`);
        }
        return exists;
      },
```
The patch is easy.  Knowing that it needs to be done is harder.
