### ISSUE TITLE
Generating routes error "No matching model found for referenced type ... x more" when returning long const assertion types

### ISSUE THREAD

**Issue by tbf-siteimprove** [microsoft/TypeScript#45008]
# Bug Report

### 🔎 Search Terms

- No matching model found for referenced type
- const assertion types

### 🕗 Version & Regression Information
```
tsoa: 3.8.0
typescript: 4.1.5
```
- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ____x_____
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

None

### 💻 Code

I created a ts `const` assertion type like this:
```
const foo = [
  "foofoofoofoofoofoofoofoofoofoofoofoo01",
  "foofoofoofoofoofoofoofoofoofoofoofoo02",
  "foofoofoofoofoofoofoofoofoofoofoofoo03",
  "foofoofoofoofoofoofoofoofoofoofoofoo04",
  "foofoofoofoofoofoofoofoofoofoofoofoo05",
  "foofoofoofoofoofoofoofoofoofoofoofoo06",
  "foofoofoofoofoofoofoofoofoofoofoofoo07",
  "foofoofoofoofoofoofoofoofoofoofoofoo08",
  "foofoofoofoofoofoofoofoofoofoofoofoo09",
] as const
export type Foo = typeof foo[number]
```

Then use it in my controller endpoint as return type:
```
 @Get("foo")
  public getFoo (): Foo {
    return "foo1"
  }
```

### 🙁 Actual behavior

When generating routes via `tsoa spec-and-routes`, I get the following error:
```
There was a problem resolving type of 'Foo'.
Generate routes error.
 Error: No matching model found for referenced type ... 4 more .... If ... 4 more ... comes from a dependency, please create an interface in your own code that has the same structure. Tsoa can not utilize interfaces from external dependencies. Read more at https://github.com/lukeautry/tsoa/blob/master/docs/ExternalInterfacesExplanation.MD
    at new GenerateMetadataError (/home/tbf/Git/xxx/apps/xxx/node_modules/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/exceptions.js:22:28)
    at TypeResolver.getModelTypeDeclaration (/home/tbf/Git/xxx/apps/xxx/node_modules/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:730:19)
    at TypeResolver.typeArgumentsToContext (/home/tbf/Git/xxx/apps/xxx/node_modules/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:844:32)
    at TypeResolver.getReferenceType (/home/tbf/Git/xxx/apps/xxx/node_modules/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:526:14)
    at TypeResolver.resolve (/home/tbf/Git/xxx/apps/xxx/node_modules/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:360:34)
    at /home/tbf/Git/xxx/apps/xxx/node_modules/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:114:95
    at Array.map (<anonymous>)
    at TypeResolver.resolve (/home/tbf/Git/xxx/apps/xxx/node_modules/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:113:45)
    at TypeResolver.resolve (/home/tbf/Git/xxx/apps/xxx/node_modules/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:289:166)
    at TypeResolver.getTypeAliasReference (/home/tbf/Git/xxx/apps/xxx/node_modules/tsoa/node_modules/@tsoa/cli/dist/metadataGeneration/typeResolver.js:569:353)
```

I do NOT get the error, when my `const` foo contains less characters. Like e.g.
```
const foo = [
  "foofoofoofoofoofoofoofoofoofoofoofoo01",
  "foofoofoofoofoofoofoofoofoofoofoofoo02",
  "foofoofoofoofoofoofoofoofoofoofoofoo03",
  "foofoofoofoofoofoofoofoofoofoofoofoo04",
  "foofoofoofoofoofoofoofoofoofoofoofoo05",
  "foofoofoofoofoofoofoofoofoofoofoofoo06",
  "foofoofoofoofoofoofoofoofoofoofoofoo07",
  "foofoofoofoofoofoofoofoofoofoofoofoo08",
] as const
```
The issue seems to be related to a truncation issue also mentioned here https://github.com/lukeautry/tsoa/issues/749.

### 🙂 Expected behavior

Routes are generated without error

**Comment by tbf-siteimprove** [comment]
posted it here: https://github.com/lukeautry/tsoa/issues/1033
