### ISSUE TITLE
autocomplete stop working and vscode.typescript.features has crash

### ISSUE THREAD

**Issue by victorfernandesraton** [microsoft/TypeScript#45030]
*TS Template added by @mjbvz*

**TypeScript Version**: typescript-next-4.4.20210713

**Search Terms**
- debug failure

---

Issue Type: <b>Bug</b>

when open my code everything seens to be normal , but i try using autocomplete once, it's stop working.
After that ,when i see terminal Extensions Log, i find this log

```
[2021-07-14 01:13:01.180] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2021-07-14 01:13:01.181] [exthost] [error] Error: <semantic> TypeScript Server Error (4.4.0-dev.20210713)
Debug Failure.
Error: Debug Failure.
    at rehydrateCachedInfo (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:123196:66)
    at Array.map (<anonymous>)
    at /home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:123141:33
    at Map.forEach (<anonymous>)
    at Object.forEach (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:123139:28)
    at /home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:126829:32
    at resolvingModuleSpecifiers (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:125450:26)
    at collectAutoImports (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:126828:17)
    at getGlobalCompletions (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:126740:17)
    at tryGetGlobalSymbols (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:126646:25)
    at getCompletionData (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:126418:22)
    at Object.getCompletionsAtPosition (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:125515:34)
    at Proxy.getCompletionsAtPosition (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:156208:35)
    at /home/victor/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.14/node_modules/@vsintellicode/typescript-intellicode-plugin/lib/index.js:2:3222
    at Object.l.getCompletionsAtPosition (/home/victor/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.14/node_modules/@vsintellicode/typescript-intellicode-plugin/lib/index.js:2:8139)
    at IOSession.Session.getCompletions (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:167632:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:166483:61)
    at /home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:168281:88
    at IOSession.Session.executeWithRequestId (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:168272:28)
    at IOSession.Session.executeCommand (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:168281:33)
    at IOSession.Session.onMessage (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:168307:35)
    at Interface.<anonymous> (/home/victor/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210713/node_modules/typescript/lib/tsserver.js:170906:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
    at Function.create (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:75833)
    at dispatchResponse (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:69697)
    at dispatchMessage (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:68556)
    at /usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:68046
    at d.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)
    at g.onLengthData (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:434643)
    at Socket.<anonymous> (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:434291)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:53:55.113Z)
OS version: Linux x64 5.4.0-77-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2567)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|7.66GB (0.60GB free)|
|Process Argv|--unity-launch --crash-reporter-id c2847dae-fa16-42a5-9b24-009e909c7c5d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.8.0
vscode-node-debug-process-picker|apr|1.0.0
path-intellisense|chr|2.3.0
gitignore|cod|0.7.0
vscode-markdownlint|Dav|0.42.1
vscode-eslint|dba|2.1.23
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.0.1
auto-rename-tag|for|0.1.7
vscode-pull-request-github|Git|0.28.0
go|gol|0.26.0
vscode-graphql|Gra|0.3.16
json2ts|Gre|0.0.6
vscode-test-explorer|hbe|2.20.4
npm-dependency-links|her|1.2.0
vscode-jest-test-adapter|kav|0.8.1
git-graph|mhu|1.30.0
gitignore|mic|1.0.1
vscode-bicep|ms-|0.4.63
vscode-docker|ms-|1.14.0
vscode-dotnet-runtime|ms-|1.2.0
cpptools|ms-|1.5.1
js-debug-nightly|ms-|2021.7.917
live-server|ms-|0.2.2
test-adapter-converter|ms-|0.0.13
vscode-github-issue-notebooks|ms-|0.0.102
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4568
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.5.2
vscode-jest|Ort|4.0.3
material-icon-theme|PKi|4.8.0
typescript-hero|rbb|3.0.0
LiveServer|rit|5.6.1
move-ts|str|1.12.0
vscodeintellicode|Vis|1.2.14
vscode-arduino|vsc|0.4.3
glean|wix|5.2.2
stylable-intelligence|wix|0.7.5
vscode-import-cost|wix|2.15.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by andrewbranch** [comment]
@victorfernandesraton @fsevenm can either of you provide a repository where this crash is happening?

**Comment by andrewbranch** [comment]
Short of a whole repo, providing a list of your `package.json` dependencies would be a helpful start. Thanks!

**Comment by fsevenm** [comment]
Here is my package.json.
```json
{
  "name": "backend-endpoint-test",
  "version": "1.0.0",
  "description": "Endpoint test",
  "main": "index.ts",
  "author": "Ayub Aswad",
  "private": true,
  "scripts": {
    "test": "cross-env ENV=Local ./node_modules/.bin/jest --testTimeout=30000 --maxWorkers=1",
    "test:dev": "cross-env ENV=Dev ./node_modules/.bin/jest --testTimeout=30000",
    "test:uat": "cross-env ENV=Uat ./node_modules/.bin/jest --testTimeout=30000"
  },
  "dependencies": {
    "@types/faker": "^5.5.5",
    "@types/form-data": "^2.5.0",
    "@types/humps": "^2.0.0",
    "@types/jest": "^26.0.22",
    "@types/lodash": "^4.14.168",
    "@types/mongodb": "^3.6.15",
    "axios": "^0.21.1",
    "cross-env": "^7.0.3",
    "dayjs": "^1.10.4",
    "dotenv": "^8.2.0",
    "eslint": "^7.25.0",
    "faker": "^5.5.3",
    "form-data": "^4.0.0",
    "http-status": "^1.5.0",
    "humps": "^2.0.1",
    "jest": "^26.6.3",
    "lodash": "^4.17.21",
    "mongodb": "^3.6.7",
    "mongoose": "^5.12.13",
    "pluralize": "^8.0.0",
    "prettier": "^2.2.1",
    "ts-jest": "^26.5.5",
    "ts-node": "^9.1.1",
    "typescript": "^4.2.4"
  },
  "devDependencies": {
    "@types/pluralize": "^0.0.29"
  }
}
```
Idk if providing my tsconfig.json would be helpful, but let me know if it is.

**Comment by andrewbranch** [comment]
I got a reproduction from this, thanks @fsevenm!

**Comment by victorfernandesraton** [comment]
i use this repo

https://github.com/victorfernandesraton/control-warehouse.git

and i use this package.json dependencies 

```json
{
  "name": "control-wharehouse",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "jest"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "4.28.2",
    "@typescript-eslint/parser": "4.28.2",
    "eslint": "^7.30.0",
    "nodemon": "2.0.9",
    "prettier": "2.3.2",
    "ts-node": "10.0.0",
    "typescript": "4.3.4",
    "@types/date-fns": "^2.6.0",
    "@types/express": "4.17.13",
    "@types/jest": "26.0.24",
    "@types/uuid": "8.3.1"
  },
  "dependencies": {
    "date-fns": "^2.22.1",
    "express": "4.17.1",
    "jest": "27.0.6",
    "ts-jest": "27.0.3",
    "uuid": "8.3.2"
  }
}
```

**Comment by andrewbranch** [comment]
ts-node is what’s triggering the crash—fix coming up shortly. Thanks!
