### ISSUE TITLE
Crash on file consisting of `#`

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#45114]
**input.ts**

```ts
#
```

**Expected**: I dunno, some useful error.
**Actual**:

```
[Trace  - 22:55:38.318] <syntax> Response received: getOutliningSpans (9). Request took 3 ms. Success: false . Message: Error processing request.
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.escapeLeadingUnderscores (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:12314:28)
    at createBaseIdentifier (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:21916:35)
    at Object.createIdentifier (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:21928:24)
    at createIdentifier (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:31047:43)
    at createIdentifier (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:31051:24)
    at parseIdentifier (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:31071:20)
    at parsePrimaryExpression (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:34314:20)
    at parseMemberExpressionOrHigher (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:33783:30)
    at parseLeftHandSideExpressionOrHigher (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:33727:92)
    at parseUpdateExpression (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:33662:30)
    at parseUnaryExpressionOrHigher (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:33537:40)
    at parseBinaryExpressionOrHigher (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:33414:31)
    at parseAssignmentExpressionOrHigher (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:33047:24)
    at parseExpression (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:32994:24)
    at doOutsideOfContext (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:30577:20)
    at allowInAnd (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:30599:20)
    at parseExpressionOrLabeledStatement (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:34732:30)
    at parseStatement (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:34975:20)
    at parseListElement (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:31427:20)
    at parseList (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:31412:31)
    at parseSourceFileWorker (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:30380:30)
    at Object.parseSourceFile (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:30214:26)
    at Object.updateSourceFile (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:36913:31)
    at Object.updateSourceFile (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:30050:47)
    at updateLanguageServiceSourceFile (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:155933:40)
    at SyntaxTreeCache.getCurrentSourceFile (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:155882:30)
    at Proxy.getOutliningSpans (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:156623:46)
    at IOSession.Session.getOutliningSpans (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:167636:45)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:166593:61)
    at c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:168443:88
    at IOSession.Session.executeWithRequestId (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:168434:28)
    at IOSession.Session.executeCommand (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:168443:33)
    at IOSession.Session.onMessage (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:168469:35)
    at Interface.<anonymous> (c:\Users\drosen\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.4.20210715\node_modules\typescript\lib\tsserver.js:171068:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by meissnere** [comment]
Are you saying that you put just a `#` into a Typescript file, and the compiler output this bizarre error with such an extensive stack trace? Goodness gracious!
