### ISSUE TITLE
Fatal Error parsing JSDoc @link

### ISSUE THREAD

**Issue by jsbrain** [microsoft/TypeScript#45248]
# Bug Report

I have a project with a wallaby.js config file at the project root. Just after adding some JSDoc comments in said file the tsc crashes with:

```
 Error  Cannot read property 'text' of undefined
```

After fiddling around a bit I noticed, that it fails when I use {@link IWallabyConfig} in the JSDoc comment. Without the {@link} it compiles just fine.

My file looks like this:

```ts
// @ts-check
/**
 * @typedef { import("wallabyjs").IWallaby } IWallaby
 * @typedef { import("wallabyjs").IWallabyConfig } IWallabyConfig
 */
/**
 * @typedef AdditionalWallabyConfig Additional valid Wallaby config properties
 * that aren't defined in {@link IWallabyConfig}.                <---- adding this will cause the error.
 * @property {boolean} autoDetect
 */
/**
 * @typedef {Partial<IWallabyConfig> & AdditionalWallabyConfig} FullWallabyConfig
 * Full Wallaby config.
 */
/**
 *
 * @param {IWallaby} wallaby
 * @returns {FullWallabyConfig}
 */
module.exports = function (wallaby) {
  return {
    autoDetect: true,
    compilers: {
      '**/*.ts?(x)': wallaby.compilers?.typeScript({
        module: 'commonjs',
        jsx: 'React',
      }),
    },
  };
};


```

When I add the {@link} when the compiler is already running, I get the following stack trace:

```
/my-project/node_modules/typescript/lib/typescript.js:110417
                throw e;
                ^

TypeError: Cannot read property 'text' of undefined
    at getSourceTextOfNodeFromSourceFile (/my-project/node_modules/typescript/lib/typescript.js:14134:55)
    at getTextOfNode (/my-project/node_modules/typescript/lib/typescript.js:14159:16)
    at Object.entityNameToString (/my-project/node_modules/typescript/lib/typescript.js:14590:69)
    at /my-project/node_modules/typescript/lib/typescript.js:12631:91
    at Array.map (<anonymous>)
    at Object.getTextOfJSDocComment (/my-project/node_modules/typescript/lib/typescript.js:12630:73)
    at serializeTypeAlias (/my-project/node_modules/typescript/lib/typescript.js:50923:42)
    at serializeSymbolWorker (/my-project/node_modules/typescript/lib/typescript.js:50734:25)
    at serializeSymbol (/my-project/node_modules/typescript/lib/typescript.js:50694:38)
    at /my-project/node_modules/typescript/lib/typescript.js:50669:25
error Command failed with exit code 1.
```

- ts:        v4.3.5
- node:   v16.4.2

**Comment by DanielRosenwasser** [comment]
I also found #45254.

**Comment by sandersn** [comment]
@jsbrain I'm fairly certain that #45312 fixes your crash. Do you mind testing with typescript@next tomorrow (5 August)?

Instructions are here: https://code.visualstudio.com/docs/typescript/typescript-compiling
But I think most people use the JS&TS Nightly extension these days: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next

**Comment by jsbrain** [comment]
Hey @sandersn.

Tested with `4.5.0-dev.20210808` and it works!

Thanks 😊
