### ISSUE TITLE
Quick info crashes on '@typedef'

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#45254]
```ts
/**
 * @typedef AdditionalWallabyConfig Additional valid Wallaby config properties
 * that aren't defined in {@link IWallabyConfig}.
 * @property {boolean} autoDetect
 */
```

Request info on `AdditionalWallabyConfig`

```
[Trace  - 22:53:10.810] <semantic> Response received: quickinfo (6). Request took 25 ms. Success: false . Message: Error processing request. Cannot read property 'parent' of undefined
TypeError: Cannot read property 'parent' of undefined
    at getSymbolAtLocation (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:80604:38)
    at Object.getSymbolAtLocation (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:45024:31)
    at Object.buildLinkParts (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120133:84)
    at c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130137:131
    at Object.flatMap (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:515:25)
    at getDisplayPartsFromComment (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130137:23)
    at c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130097:36
    at Object.forEachUnique (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119892:34)
    at Object.getJsDocCommentsFromDeclarations (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130092:16)
    at getDocumentationComment (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152533:28)
    at SymbolObject.getDocumentationComment (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152320:49)
    at SymbolObject.getContextualDocumentationComment (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:152340:33)
    at Object.getSymbolDisplayPartsDocumentationAndSymbolKind (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:134875:40)
    at c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:153400:41
    at Object.runWithCancellationToken (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:45254:28)
    at Proxy.getQuickInfoAtPosition (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:153399:34)
    at IOSession.Session.getQuickInfoWorker (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:164458:62)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:163368:61)
    at c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165210:88
    at IOSession.Session.executeWithRequestId (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165201:28)
    at IOSession.Session.executeCommand (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165210:33)
    at IOSession.Session.onMessage (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165236:35)
    at Interface.<anonymous> (c:\Users\drosen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167833:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

Weirdly, if you request quick info after that, it'll give you the right result!

**Comment by sandersn** [comment]
To repro this, you need

1. Not to have `@types/wallabyjs` installed; 
2. To be using an editor that includes links in quickinfo.
