### ISSUE TITLE
Loading TypeScript files crashes Visual Studio 2015 (TypeScript 1.5 beta)

### ISSUE THREAD

**Issue by AlexAugot** [Microsoft/TypeScript#4528]
I'm having an issue where any time a TypeScript file or definition is loaded in Visual Studio 2015, devenv.exe crashes.  At one point in time it was working fine, but now it's happening consistently.  I've uninstalled all extensions, typescript and visual studio 2015 and reinstalled both TypeScript and Visual Studio 2015 with no luck.

Event Log:
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Instances of abstract classes cannot be created.
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.JsonHelpers.<ConvertNavigationBarItemArray>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.JsonHelpers.ParseNavigationBarItems(String encoded, SourceText text)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.LanguageServiceProxy.GetNavigationBarItems(ProjectDataCache project, Document document, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.NavigationBar.TypeScriptNavigationBarItemService.<>c__DisplayClass0.<GetItemsAsync>b__1(LanguageServiceProxy proxy, ProjectDataCache cache, ScriptContext context)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.ComputeValue[T](ProjectDataCache cache, LanguageServiceOperation`1 operation)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.<>c__DisplayClass0`1.<PerformOperation>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.<PerformSyntacticFeatureOperationAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.NavigationBar.NavigationBarController.<ComputeModelAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Instances of abstract classes cannot be created.
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.JsonHelpers.<ConvertNavigationBarItemArray>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.JsonHelpers.ParseNavigationBarItems(String encoded, SourceText text)
   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.LanguageServiceProxy.GetNavigationBarItems(ProjectDataCache project, Document document, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.NavigationBar.TypeScriptNavigationBarItemService.<>c__DisplayClass0.<GetItemsAsync>b__1(LanguageServiceProxy proxy, ProjectDataCache cache, ScriptContext context)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.ComputeValue[T](ProjectDataCache cache, LanguageServiceOperation`1 operation)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.<>c__DisplayClass0`1.<PerformOperation>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.TaskHandler.<PerformSyntacticFeatureOperationAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.NavigationBar.NavigationBarController.<ComputeModelAsync>d__30.MoveNext()<---
```

**Comment by mhegazy** [comment]
What version of TypeScipt do you have installed? do you have a registry key: HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\TypeScriptLanguageService\CustomTypeScriptServicesFileLocation? does it happen on any TS file? or a specific file/project?

**Comment by AlexAugot** [comment]
I'm using Visual Studio 2015 Professional and the [TypeScript Tools 1.5 beta](https://visualstudiogallery.msdn.microsoft.com/3e5ba71c-abea-4d00-b81b-a62de3ad3d53) extension.  

I don't seem to have any TypeScriptLangageService folder under that registry path.  I was looking at #4011 earlier, but couldn't apply the fix.

It seems to happen on every .ts or .d.ts file.

**Comment by mhegazy** [comment]
Why are you using 1.5 beta if i may ask? i do not think this can even work with VS2015 RTM. the API's that we depend on from Roslyn have changed in between the two versions.

Please install TypeScript 1.5.4: http://www.microsoft.com/en-us/download/details.aspx?id=48593&WT.mc_id=rss_alldownloads_devresources

**Comment by AlexAugot** [comment]
I'm using the 1.5 beta because that's all that seems to come up when searching for typescript in the Visual Studio Extensions UI.

![typescript_ui](https://cloud.githubusercontent.com/assets/1377361/9580059/1004104e-4fc5-11e5-8dc8-440120e88042.png)

I will give 1.5.4 a shot, thanks for the direct link.

**Comment by AlexAugot** [comment]
1.5.4 fixes the issue, Typescript files now load fine.  Thanks for all your help!
