### ISSUE TITLE
'TypeError: hosts.fileExists is not a function'

### ISSUE THREAD

**Issue by LPGhatguy** [Microsoft/TypeScript#4565]
This is an error I'm getting in an existing build system moving from TypeScript 1.5.3 to 1.6/1.7 to take advantage of the new typing changes.

The issue did not occur in `1.6.0-dev.20150817`, but occurs in `1.6.0-dev.20150818` and onward. Sadly, none of the builds that work have the core changes we're looking for. I'm installing TypeScript locally using `npm install typescript@X` and using it with Browserify via TSify. Nothing in the stack trace mentions any modules except `typescript` however.

Here's a stack trace I'm getting:

```
/Users/luciengreathouse/Documents/projects/skeleton/node_modules/typescript/lib/typescript.js:34876
                if (host.fileExists(candidate)) {
                         ^

TypeError: host.fileExists is not a function
    at /Users/luciengreathouse/Documents/projects/skeleton/node_modules/typescript/lib/typescript.js:34876:26
    at Object.forEach (/Users/luciengreathouse/Documents/projects/skeleton/node_modules/typescript/lib/typescript.js:875:30)
    at legacyNameResolver (/Users/luciengreathouse/Documents/projects/skeleton/node_modules/typescript/lib/typescript.js:34869:39)
    at resolveModuleName (/Users/luciengreathouse/Documents/projects/skeleton/node_modules/typescript/lib/typescript.js:34855:16)
    at /Users/luciengreathouse/Documents/projects/skeleton/node_modules/typescript/lib/typescript.js:35014:48
    at Object.map (/Users/luciengreathouse/Documents/projects/skeleton/node_modules/typescript/lib/typescript.js:940:29)
    at resolveModuleNamesWorker (/Users/luciengreathouse/Documents/projects/skeleton/node_modules/typescript/lib/typescript.js:35013:31)
    at processImportedModules (/Users/luciengreathouse/Documents/projects/skeleton/node_modules/typescript/lib/typescript.js:35435:35)
    at findSourceFile (/Users/luciengreathouse/Documents/projects/skeleton/node_modules/typescript/lib/typescript.js:35395:25)
    at processSourceFile (/Users/luciengreathouse/Documents/projects/skeleton/node_modules/typescript/lib/typescript.js:35333:27)
```

**Comment by vladima** [comment]
what do you use to build the project: is it gulp or something else?

**Comment by LPGhatguy** [comment]
@vladima Yes, we're using gulp. I can try to put together a small reproduction project after I get off work if it would help.

**Comment by mhegazy** [comment]
@vladima you had a change to help gulp work with latest changes correct?

**Comment by vladima** [comment]
gulp-typescript already has [all necessary changes](https://github.com/ivogabe/gulp-typescript/commit/05485a3bd2d9e62b85a733e117b0ed8e35ce8ab4). I guess it is just not published yet

**Comment by mhegazy** [comment]
//CC: @ivogabe for this one then.

**Comment by ivogabe** [comment]
Which version of gulp-typescript are you using? The fix @vladima is referring to is released in v2.8.1.

**Comment by LPGhatguy** [comment]
I do appear to be `gulp-typescript@2.8.1` it appears; my `package.json` is pinned at `^2.8.1`.

**Comment by ivogabe** [comment]
I saw in the first post that you're using Browserify with tsify too, could it be an issue of tsify? Do you use gulp-typescript or tsify to compile TypeScript?

Pinging @smrq, it looks like tsify doesn't have support (yet) for the new apis.

**Comment by LPGhatguy** [comment]
I'm compiling TS in this particular case using tsify.

**Comment by smrq** [comment]
Sounds like probably a tsify problem then, although it's weird that the stack trace doesn't mention it at all...

**Comment by smrq** [comment]
Try tsify v0.11.11

**Comment by LPGhatguy** [comment]
tsify 0.11.11 seems to have fixed it. Only a couple more issues and we'll have `typescript@next` integrated!
