### ISSUE TITLE
Maximum call stack size exceeded if the variable is used in a condition before its declaration using property access

### ISSUE THREAD

**Issue by hikiko4ern** [microsoft/TypeScript#45830]
# Bug Report

### 🔎 Search Terms

- Maximum call stack size exceeded
- property access call

### 🕗 Version & Regression Information

Works on `4.3.5`, crashes on `4.4.0-beta`, `4.4.1-rc`, `4.4.2`, `4.4.3`, `4.5.0-dev.20210910`.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBCBGArGBeGBvAsAKBnmAZmAFwwAUAlKgHwxQBOArgKY4C+A3DjgJYHkBDKuhhsYAenExg9ARAAWzCDD4wABgLUrljCMwAmKsHUXTw+nlB7hu2UJFgDUcJADoilLtiA)

### 💻 Code

```ts
const obj = {
    fn: () => true
};

if (a) { } // crashes if `a` is used in the condition

const a = obj.fn();
```

There will be no crash if `a` is declared without accessing the `obj` property

```ts
const obj = {
    fn: () => true
};

const callFn = () => obj.fn();

if (a) { } // now it doesn't crash

const a = callFn();
```

### 🙁 Actual behavior

```
$ yarn tsc test.ts

/project/node_modules/typescript/lib/tsc.js:92656
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at /project/node_modules/typescript/lib/tsc.js:9125:63
    at getCombinedFlags (/project/node_modules/typescript/lib/tsc.js:9103:21)
    at Object.getCombinedNodeFlags (/project/node_modules/typescript/lib/tsc.js:9125:16)
    at getDeclarationNodeFlagsFromSymbol (/project/node_modules/typescript/lib/tsc.js:59070:44)
    at checkIdentifier (/project/node_modules/typescript/lib/tsc.js:56890:46)
    at checkExpressionWorker (/project/node_modules/typescript/lib/tsc.js:63702:28)
    at checkExpression (/project/node_modules/typescript/lib/tsc.js:63657:38)
    at checkNonNullExpression (/project/node_modules/typescript/lib/tsc.js:59167:37)
    at checkPropertyAccessExpression (/project/node_modules/typescript/lib/tsc.js:59212:85)
    at checkExpressionWorker (/project/node_modules/typescript/lib/tsc.js:63734:28)
```

### 🙂 Expected behavior

Should report the error `Block-scoped variable 'a' used before its declaration.`

**Comment by dperetti** [comment]
It's crashing on my project with a similar log (since 4.4), but I have not been able to narrow down the exact cause.

```
/Users/dom/Documents/dev/codestory/node_modules/typescript/lib/tsc.js:92656
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at isInJSFile (/Users/dom/Documents/dev/codestory/node_modules/typescript/lib/tsc.js:12238:24)
    at Object.getEffectiveTypeAnnotationNode (/Users/dom/Documents/dev/codestory/node_modules/typescript/lib/tsc.js:14116:14)
    at getContextualTypeForVariableLikeDeclaration (/Users/dom/Documents/dev/codestory/node_modules/typescript/lib/tsc.js:57485:31)
    at getContextualTypeForObjectLiteralElement (/Users/dom/Documents/dev/codestory/node_modules/typescript/lib/tsc.js:57811:78)
    at getContextualType (/Users/dom/Documents/dev/codestory/node_modules/typescript/lib/tsc.js:57972:28)
    at hasNonBindingPatternContextualTypeWithNoGenericTypes (/Users/dom/Documents/dev/codestory/node_modules/typescript/lib/tsc.js:56836:17)
    at getNarrowableTypeForReference (/Users/dom/Documents/dev/codestory/node_modules/typescript/lib/tsc.js:56842:59)
    at checkIdentifier (/Users/dom/Documents/dev/codestory/node_modules/typescript/lib/tsc.js:56961:20)
    at checkExpressionWorker (/Users/dom/Documents/dev/codestory/node_modules/typescript/lib/tsc.js:63702:28)
    at checkExpression (/Users/dom/Documents/dev/codestory/node_modules/typescript/lib/tsc.js:63657:38)
```

**Comment by ahejlsberg** [comment]
Looks to be caused by an infinite loop in the logic that inlines conditional expressions during control flow analysis.
