### ISSUE TITLE
Auto import working inconsistently after updating to v1.60.1

### ISSUE THREAD

**Issue by IHIutch** [microsoft/TypeScript#45921]
> @IHIutch Please open a separate issue with a minimal repo so we can investigate separately?

_Originally posted by @mjbvz in https://github.com/microsoft/vscode/issues/132299#issuecomment-921091709_

**Comment by mjbvz** [comment]
The error actually occurs in `completionEntryDetails` which prevents the import from being resolved properly:

```
Info 146  [15:08:47.870] request:
    {"seq":26,"type":"request","command":"completionEntryDetails","arguments":{"file":"/Users/matb/projects/san/auto-import-test/index.js","line":12,"offset":18,"entryNames":[{"name":"GridItem","source":"@chakra-ui/layout","data":{"exportName":"GridItem","fileName":"/Users/matb/projects/san/auto-import-test/node_modules/@chakra-ui/layout/dist/types/index.d.ts","moduleSpecifier":"@chakra-ui/layout"}}]}}
Err 147   [15:08:47.974] Exception on executing command {"seq":26,"type":"request","command":"completionEntryDetails","arguments":{"file":"/Users/matb/projects/san/auto-import-test/index.js","line":12,"offset":18,"entryNames":[{"name":"GridItem","source":"@chakra-ui/layout","data":{"exportName":"GridItem","fileName":"/Users/matb/projects/san/auto-import-test/node_modules/@chakra-ui/layout/dist/types/index.d.ts","moduleSpecifier":"@chakra-ui/layout"}}]}}:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at getCompletionEntryCodeActionsAndSourceDisplay (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:126516:22)
        at Object.getCompletionEntryDetails (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:126472:30)
        at Proxy.getCompletionEntryDetails (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:156798:35)
        at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:168262:57
        at Object.mapDefined (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:616:30)
        at IOSession.Session.getCompletionEntryDetails (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:168260:33)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:167087:61)
        at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:168880:88
        at IOSession.Session.executeWithRequestId (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:168871:28)
        at IOSession.Session.executeCommand (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:168880:33)
        at IOSession.Session.onMessage (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:168906:35)
        at Interface.<anonymous> (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:171511:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

File text of /Users/matb/projects/san/auto-import-test/index.js:
    import React from "react";
    
    import { Grid } from "@chakra-ui/react";
    import { useForm } from "react-hook-form";
    
    export default function index() {
      const form = useForm();
    
      return (
        <Box>
          <Grid>
            <GridItem></GridItem>
          </Grid>
        </Box>
      );
    }
```

**Comment by andrewbranch** [comment]
I would guess that #45792 fixes this, but it will be a bit before I can check.

**Comment by andrewbranch** [comment]
@IHIutch can you see if this is fixed in the nightly for you?
