### ISSUE TITLE
Maximum call stack size exceeded when compiling tsx

### ISSUE THREAD

**Issue by martind-gmc** [microsoft/TypeScript#46021]
# Bug Report

Compilation of tsx file throws generic error `RangeError: Maximum call stack size exceeded`. When the file doesn't contain any tsx element the compilation works as expected.

Possible duplicate of:
#45632

### 🔎 Search Terms

Maximum call stack size exceeded

### 🕗 Version & Regression Information

4.3 and newer (also tested on 4.5.0-dev.20210923)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?declaration=false&jsx=1&ts=4.4.2#code/JYOwLgpgTgZghgYwgAgJIBE5jgHgLIQgCuqkAtgGpxTBzjIQAekIAJgM7IAyw7YpEStVr0AvN179yVGnTAA6APIgIPFQD5kAbwCwAKGSHkZQiXLsZIsAH4AXMgLEBQ2eADc+gL779MIiAQwYAB7EAdTfFNnSzkGZkIOCT5o4VjxHmTpVPAlFTUIdQAKfSNkViw4ewwKyKcs1zB1fQBKbRKjBFC+ZAAbSRSG5HFy7HkTOsELbLBka2skqUEYnOVVUAgPPXbDAHod5AA5UIBaMHZGZAA3aHYQsM6yAAdgHohOMGDkACt2HZ+LuCcJiPCCBCCsbbIPZQCBgIhQMIZRZkQpaS7Tex9TJLaaeZqbSF7ZBnC7XKC3UJlYJvEAAchmD2er2QdFYxIAFlBggB3IFQLlQFmcBB0ZAAIxQ7AghGQoDKEEuH2CPV+nRA7GVEEhMLhCOQOCRziu01EWixyOWYE8UPUm28Wz0YAAniC0IbyJhsENtMaGvZ3TiGvIAILo7BQNzIa0AHx96L9CwGVlyaxUkc8BL0pjIifqVjaBiMq3yABpIaGKlAy3p7b5-IE7rnBIUAPojSpu-oeiqtXSFww6+FhYg9HqRrz6IA)

### 🙁 Actual behavior

RangeError: Maximum call stack size exceeded
    at Object.isFunctionLikeOrClassStaticBlockDeclaration (\node_modules\typescript\lib\tsc.js:9813:27)
    at isBlockScope (\node_modules\typescript\lib\tsc.js:11161:28)
    at \node_modules\typescript\lib\tsc.js:11242:73
    at Object.findAncestor (\npm\node_modules\typescript\lib\tsc.js:9189:26)
    at Object.getEnclosingBlockScopeContainer (\npm\node_modules\typescript\lib\tsc.js:11242:19)
    at checkNestedBlockScopedBinding (\npm\node_modules\typescript\lib\tsc.js:57015:32)
    at checkIdentifier (\npm\node_modules\typescript\lib\tsc.js:56921:13)
    at checkExpressionWorker (\npm\node_modules\typescript\lib\tsc.js:63702:28)
    at checkExpression (\npm\node_modules\typescript\lib\tsc.js:63657:38)
    at checkJsxExpression (\npm\node_modules\typescript\lib\tsc.js:59059:28)

### 🙂 Expected behavior

compilation with no error

**Comment by sandersn** [comment]
Broken by https://github.com/microsoft/TypeScript/pull/43183
