### ISSUE TITLE
TypeError: Cannot read property 'valueDeclaration' of undefined

### ISSUE THREAD

**Issue by huan** [microsoft/TypeScript#46223]
## Reproduce steps

```sh
$ git clone git@github.com:huan/clone-class.git
$ cd clone-class
$ git checkout f87276a443eb5d11e78d0ce21819b89ac16452d1
$ npm install
$ npx tsc --version
Version 4.4.3

$ npx tsc 
/Users/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:92656
                throw e;
                ^

TypeError: Cannot read property 'valueDeclaration' of undefined
    at checkIndexConstraints (/Users/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:66778:47)
    at checkClassLikeDeclaration (/Users/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:67070:17)
    at checkClassDeclaration (/Users/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:66966:13)
    at checkSourceElementWorker (/Users/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:68323:28)
    at checkSourceElement (/Users/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:68165:17)
    at Object.forEach (/Users/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:132:30)
    at checkBlock (/Users/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:65555:20)
    at checkSourceElementWorker (/Users/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:68286:28)
    at checkSourceElement (/Users/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:68165:17)
    at checkFunctionOrMethodDeclaration (/Users/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:65253:13)
```

## Related Issue

- https://github.com/huan/clone-class/issues/58

**Comment by DanielRosenwasser** [comment]
There's a lot of files in this repo; would you be able to help us narrow down the issue more quickly by providing a minimal repro with just 1-2 files?

**Comment by huan** [comment]
@DanielRosenwasser I have tried to make this issue reproducible with fewer files, however, I can only point out that this problem is related to the [following lines](https://github.com/huan/clone-class/blob/d3333b4385e006e7a15c658bd0a11387fb9865c8/src/constructor.ts#L33-L39):

```ts
type Constructor<I extends Object> = InstanceInterface<I>

/**
 * Huan(202110): TypeError: Cannot read property 'valueDeclaration' of undefined #58
 *  https://github.com/huan/clone-class/issues/58
 */
// type Constructor<I extends Object, C = any> = ClassInterface<C> & InstanceInterface<I>
```

If I uncomment the bottom line, then this issue will appear.

However, if I only get this file out of the whole repo, then this issue will disappear. It seems it's related to this line, plus some other unknown files.

-----

@andrewbranch Yes, this issue still reproduces with `typescript@next` version 4.5.0-dev

```sh
$ npx tsc --version
Version 4.5.0-dev.20211006

$ npx tsc
/home/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:94207
                throw e;
                ^

TypeError: Cannot read property 'valueDeclaration' of undefined
    at checkIndexConstraints (/home/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:67995:47)
    at checkClassLikeDeclaration (/home/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:68287:17)
    at checkClassDeclaration (/home/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:68183:13)
    at checkSourceElementWorker (/home/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:69606:28)
    at checkSourceElement (/home/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:69444:17)
    at Object.forEach (/home/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:132:30)
    at checkBlock (/home/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:66768:20)
    at checkSourceElementWorker (/home/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:69569:28)
    at checkSourceElement (/home/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:69444:17)
    at checkFunctionOrMethodDeclaration (/home/huan/git/huan/clone-class/node_modules/typescript/lib/tsc.js:66466:13)
```

**Comment by DanielRosenwasser** [comment]
Here's the repro

```ts

export type ClassInterface<C> = {
    [key in keyof C]: C[key];
}

type InstanceInterface<I> = {
    new(...args: any[]): I
    prototype: I
}

type Constructor<I extends Object, C = any> = ClassInterface<C> & InstanceInterface<I>

function cloneClass<T extends Constructor<{}>>(OriginalClass: T): T {
    class AnotherOriginalClass extends OriginalClass {
        constructor(...args: any[]) {
            
            super(...args)
        }
    }

    return AnotherOriginalClass
}
```
