### ISSUE TITLE
After Array.shift, [0] not change type

### ISSUE THREAD

**Issue by ZhukDima** [microsoft/TypeScript#46286]
# Bug Report

### 🔎 Search Terms

ts array shift auto type error

### 🕗 Version & Regression Information

- This is a crash `TS2367`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.5.0-beta#code/MYGwhgzhAEBqYCcCWYBGICm0DeBYAUAJAB2YAthgFzQQAuyxA5gNwEGHAD2xdCArsFqcEAClIVqvJEwCUOdoVoALJBAB04rAF5om1kQC+bIkIDK9aYxFy8RQggy0+CYtGWqN5DPsJH8fglBIGABhbjowYlp5IgA3MBA+KhoLJn12Lh56ASFReMTkqVkYwkUVdXyk6B1K73YAk05zBisbBQcnFzdytVqfPwagqGgwrP5BYRLNSVSWYw4ogEEERghqYj4yVAwEdKJEVeoRUd4cyYAfEfDaSOjL+GQ0TBkAbQBdPY5r8dyxLxmWgAaaDAJYrNa6TbbBCAhRqeEHCHHb5nBDQS4nG5RdFwRAodAYV5vNp2dzqTTVXReHxlDyg2jLVaU+mMiA0slqRGUxH9eZmWbWEr2RzOVwAAwAJNgOZoDCIpRzEWoAFacaQiADkwI1MgMMjFvP8xkydGg8QQADkvDAdMQMAB3aCmRwAHiKjAAfNZ9Cbor7bjbdA6na73V6ZD7riCURNLdbKXbHQBZMAABzds2BmJ+wnDe190AAqhbFgAhAAyAFEAPoAFQA8tXiwBJABiAE1KZWEAhhJrC6QCW5ONA+MQkAAzACeOvzUdTiAgGExt0pIgwAA9UwDLO85FoPSUC8BKZvU2oICoJ7RvfNJ9ARABCYAk0rKXuO4tlqt1xstjuGuw95Pv6UTqEokAiC+r5lB+QaOt2vaiGKA4ANbEJw9quKB0RSsABhihG9TzB0orwVcWS3FBRH+HOWTQAuCBLg8+KYGuZ47kwe7VIetiEMBZ5qJgTDKNUWg6AADDB76YUWJYVjWDZNhabbtoBRAFrEp5bheV43nIkApC0PjAY+5pWhQ4GQbEMjSUocGJtAiF9ihxDoZhrjmqxWBSrEBE0b4JEil0jksU8GAiDZ+gGHRpqMUu2aouxW6cYwe7UIlsY8SUAk6cJjCieJkl2XBX4Kb+ymqepXz0b6OZxhQ2mpi8EkfEBE4Ps+Ma5BZGBWRAUHdcIvW2UKMmOo5znIWhGFYdGYxJXhQ0NRg-mGoQgmXpO+mfLlzWtdAj7idAGqajY0AAPQXdA0gTpw1A7Eh0AgJwjBICeEQINEZLQAo43kVNIhihaI6cKmGCuKgCBgMAqGONAd1onVqLUEtC2xr1a3EUQm16be+AZFGXI6O8PhKqmfCXiI8UYLWOxkOuW62T4V3QGeLVvNAADUOgahqzCXddt33QjSAbmzPbCOw9oqGxjP7ZzRUnYCOo4ILEtIdQgC0IIAQiCAHwg0CAMIggCCIIA3CB64ATCCABwggCsINAFvGzbgDMIIALCCAAwg0CAIwghsuzbOv23rgDsIBbgACIG7gCSIG7OuADIg0AAEQTgkS5x8COtu4AXCDQOnGfQDrVuAPwggDSIPHcciHHcfQFbJeAuX0CALwgdv5zbIc2+nIeFxbbuAHIgOvG4A8iBqG4A0AEwAMwAGwAOwyAouPbfjpTk5TSjU4utP0-LzPY+1D7swdR28zIqvYOrj3CNr+tG2blu2-bjuux73u+-7FtB6HEdR7HcfZBgKe5zn2dM55yLiXMuFcq7lxkLXBu0Am4tzbh3buvcB60BHhPaef17KyUmpLZCIMQQvSXNAKGMM4bRERvNU4sZUbYGRhjLwWNDA7xEEqfKokD6UOyPQyyahGCOEGujHqXgZAAH41AsnBCVbBwZAZigAOq9iYNAcgnAxzRE4B1LkFC6G5BoTo4aDDCLVTnteBepEQrBkyr8fRK1gSsIhgVJQwJ4SckkdFWK0QaZ0wQGQZK24jK7mJNlPie0hIOMKsdKSY0sGfnkj+JS-41Lbw0lGYAzg0Q6D3m1AmRAID2iQLQYASgHw-xgsASAWBzLWjUBBAaaSewyEoAoYUnRXA0zCgSTeNJylEJwv1KC6TGnNPMW0teK4ohdIUD0rANjer9PqQgIZdgWlkRplYvsZ4AqEAACYYETnwEAtAmnLP+jgpCmpmzEHyEgbZbMtwOCgEgbgs5sYxSAA)

### 💻 Code

```ts repro
class Variable {
	name: string;

	constructor(name: string) {
		this.name = name;
	}

	toString() {
		return this.name;
	}
}

class Constant {
	value: string;

	constructor(value: string) {
		this.value = value;
	}

	toString() {
		return this.value;
	}
}

class Constructor {
	name: string;

	cntArgs: number;

	args: (Constructor | Constant | Variable)[];

	constructor(name: string, cntArgs: number,
		...args: (Constructor | Constant | Variable)[]) {
		this.name = name;
		this.cntArgs = cntArgs;
		this.args = args;
	}

	toString() {
		return `${this.name}(${this.args.join(', ')})`;
	}
}

const varNames = new Set<string>();
const constants = new Set<string>();
const constructorNames = new Map<string, Constructor>();

const UNABLE_TO_UNIFY = Error('Unable to unify');

const parseConstant = (exp: string[]) => {
	const c = exp.shift();

	if (!c) {
		throw UNABLE_TO_UNIFY;
	}

	if (!constants.has(c)) {
		throw new Error(`Unknown constant ${c}`);
	}

	return new Constant(c);
};

const parseVariable = (exp: string[]) => {
	if (exp.length === 0) {
		throw UNABLE_TO_UNIFY;
	}

	const v = exp.shift() as string;
	if (!varNames.has(v)) {
		throw new Error(`Unknown variable ${v}`);
	}

	return new Variable(v);
};

const parseConstructor = (exp: string[]): Constructor => {
	if (exp.length === 0) {
		throw UNABLE_TO_UNIFY;
	}

	const constructorName = exp[0];
	if (!constructorNames.has(constructorName)) {
		throw new Error(`Unknown constructor ${constructorName}`);
	}
	exp.shift();

	if (exp[0] !== '(') { // info: error logic start this 
		throw new Error(`No open bracket for constructor: ${constructorName}`);
	}
	exp.shift(); // info: exp[0] change, but ts ignore this

	const args = [];
	args.push(parseTerm(exp));
	// exp[0] += ''; // info: fix error
	while (exp[0] === ',') { // error: This condition will always return 'false' since the types '"("' and '","' have no overlap. ts(2367)
		exp.shift();
		args.push(parseTerm(exp));
	}

	if (exp[0] !== ')') { // error: This condition will always return 'true' since the types '"("' and '")"' have no overlap. ts(2367)
		throw new Error(`No close bracket for constructor: ${constructorName}`);
	}
	if (args.length !== constructorNames.get(constructorName)?.cntArgs) {
		throw new Error(`Wrong amount of args for constructor: ${constructorName}`);
	}

	exp.shift();
	return new Constructor(constructorName, args.length, ...args);
};

const parseTerm = (exp: string[]) => {
	if (exp.length === 0) {
		throw UNABLE_TO_UNIFY;
	}

	const curr = exp[0];

	switch (true) {
		case varNames.has(curr):
			return parseVariable(exp);
		case constants.has(curr):
			return parseConstant(exp);
		case constructorNames.has(curr):
			return parseConstructor(exp);
		default:
			throw new Error('Invalid expression');
	}
};
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.5.0-beta#code/MYGwhgzhAEBqYCcCWYBGICm0DeBYAUAJAB2YAthgFzQQAuyxA5gNwEGHAD2xdCArsFqcEAClIVqvJEwCUOdoVoALJBAB04rAF5om1kQC+bIkIDK9aYxFy8RQggy0+CYtGWqN5DPsJH8fglBIGABhbjowYlp5IgA3MBA+KhoLJn12Lh56ASFReMTkqVkYwkUVdXyk6B1K73YAk05zBisbBQcnFzdytVqfPwagqGgwrP5BYRLNSVSWYw4ogEEERghqYj4yVAwEdKJEVeoRUd4cyYAfEfDaSOjL+GQ0TBkAbQBdPY5r8dyxLxmWgAaaDAJYrNa6TbbBCAhRqeEHCHHb5nBDQS4nG5RdFwRAodAYV5vNp2dzqTTVXReHxlDyg2jLVaU+mMiA0slqRGUxH9eZmWbWEr2RzOVwAAwAJNgOZoDCIpRzEWoAFacaQiADkwI1MgMMjFvP8xkydGg8QQADkvDAdMQMAB3aCmRwAHiKjAAfNZ9Cbor7bjbdA6na73V6ZD7riCURNLdbKXbHQBZMAABzds2BmJ+wnDe190AAqhbFgAhAAyAFEAPoAFQA8tXiwBJABiAE1KZWEAhhJrC6QCW5ONA+MQkAAzACeOvzUdTiAgGExt0pIgwAA9UwDLO85FoPSUC8BKZvU2oICoJ7RvfNJ9ARABCYAk0rKXuO4tlqt1xstjuGuw95Pv6UTqEokAiC+r5lB+QaOt2vaiGKA4ANbEJw9quKB0RSsABhihG9TzB0orwVcWS3FBRH+HOWTQAuCBLg8+KYGuZ47kwe7VIetiEMBZ5qJgTDKNUWg6AADDB76YUWJYVjWDZNhabbtoBRAFrEp5bheV43nIkApC0PjAY+5pWhQ4GQbEMjSUocGJtAiF9ihxDoZhrjmqxWBSrEBE0b4JEil0jksU8GAiDZ+gGHRpqMUu2aouxW6cYwe7UIlsY8SUAk6cJjCieJkl2XBX4Kb+ymqepXz0b6OZxhQ2mpi8EkfEBE4Ps+Ma5BZGBWRAUHdcIvW2UKMmOo5znIWhGFYdGYxJXhQ0NRg-mGoQgmXpO+mfLlzWtdAj7idAGqajY0AAPQXdA0gTpw1A7Eh0AgJwjBICeEQINEZLQAo43kVNIhihaI6cKmGCuKgCBgMAqGONAd1onVqLUEtC2xr1a3EUQm16be+AZFGXI6O8PhKqmfCXiI8UYLWOxkOuW62T4V3QGeLVvNAADUOgahqzCXddt33QjSAbmzPbCOw9oqGxjP7ZzRUnYCOo4ILEtIdQgC0IIAQiCAHwg0CAMIggCCIIA3CB64ATCCABwggCsINAFvGzbgDMIIALCCAAwg0CAIwghsuzbOv23rgDsIBbgACIG7gCSIG7OuADIg0AAEQTgkS5x8COtu4AXCDQOnGfQDrVuAPwggDSIPHcciHHcfQFbJeAuX0CALwgdv5zbIc2+nIeFxbbuAHIgOvG4A8iBqG4A0AEwAMwAGwAOwyAouPbfjpTk5TSjU4utP0-LzPY+1D7swdR28zIqvYOrj3CNr+tG2blu2-bjuux73u+-7FtB6HEdR7HcfZBgKe5zn2dM55yLiXMuFcq7lxkLXBu0Am4tzbh3buvcB60BHhPaef17KyUmpLZCIMQQvSXNAKGMM4bRERvNU4sZUbYGRhjLwWNDA7xEEqfKokD6UOyPQyyahGCOEGujHqXgZAAH41AsnBCVbBwZAZigAOq9iYNAcgnAxzRE4B1LkFC6G5BoTo4aDDCLVTnteBepEQrBkyr8fRK1gSsIhgVJQwJ4SckkdFWK0QaZ0wQGQZK24jK7mJNlPie0hIOMKsdKSY0sGfnkj+JS-41Lbw0lGYAzg0Q6D3m1AmRAID2iQLQYASgHw-xgsASAWBzLWjUBBAaaSewyEoAoYUnRXA0zCgSTeNJylEJwv1KC6TGnNPMW0teK4ohdIUD0rANjer9PqQgIZdgWlkRplYvsZ4AqEAACYYETnwEAtAmnLP+jgpCmpmzEHyEgbZbMtwOCgEgbgs5sYxSAA)

### 🙁 Actual behavior
```
/usr/local/lib/node_modules/node/lib/node_modules/ts-node/src/index.ts:618  
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
z1/index.ts(99,9): error TS2367: This condition will always return 'false' since the types '"("' and '","' have no overlap.
z1/index.ts(104,6): error TS2367: This condition will always return 'true' since the types '"("' and '")"' have no overlap.

    at createTSError (/usr/local/lib/node_modules/node/lib/node_modules/ts-node/src/index.ts:618:12)
    at reportTSError (/usr/local/lib/node_modules/node/lib/node_modules/ts-node/src/index.ts:622:19)
    at getOutput (/usr/local/lib/node_modules/node/lib/node_modules/ts-node/src/index.ts:809:36)
    at Object.compile (/usr/local/lib/node_modules/node/lib/node_modules/ts-node/src/index.ts:1111:30)
    at Module.m._compile (/usr/local/lib/node_modules/node/lib/node_modules/ts-node/src/index.ts:1224:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)    
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/node/lib/node_modules/ts-node/src/index.ts:1228:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)      
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)

    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at /mnt/c/Users/zhukd/OneDrive/Рабочий стол/МГТУ/ТФЯ/lab1/z1/test/test.ts:8:12
    at Array.map (<anonymous>)
    at Object.<anonymous> (/mnt/c/Users/zhukd/OneDrive/Рабочий стол/МГТУ/ТФЯ/lab1/z1/test/test.ts:7:4)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/usr/local/lib/node_modules/node/lib/node_modules/ts-node/src/index.ts:1225:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)    
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/node/lib/node_modules/ts-node/src/index.ts:1228:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```
### 🙂 Expected behavior

`exp.shift` - changes state `exp[0]`

**Comment by MartinJohns** [comment]
Duplicate of #31334. Used search terms: `array.shift in:title`

> This is a crash TS2367

It's not a crash, it's a plain regular error.
