### ISSUE TITLE
Crash on incomplete import assertion

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#46364]
```js
import thing from "thing" assert
```

Expected: TypeScript goes 🤨

Actual: TypeScript goes ☠

```
[Trace  - 18:31:41.424] <syntax> Response received: navtree (223). Request took 4 ms. Success: false . Message: Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.updateSourceFile (USER_ROOT\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211013\node_modules\typescript\lib\tsserver.js:37236:22)
    at Object.updateSourceFile (USER_ROOT\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211013\node_modules\typescript\lib\tsserver.js:30262:47)
    at updateLanguageServiceSourceFile (USER_ROOT\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211013\node_modules\typescript\lib\tsserver.js:159109:40)
    at SyntaxTreeCache.getCurrentSourceFile (USER_ROOT\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211013\node_modules\typescript\lib\tsserver.js:159058:30)
    at Proxy.getNavigationTree (USER_ROOT\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211013\node_modules\typescript\lib\tsserver.js:159771:71)
    at IOSession.Session.getNavigationTree (USER_ROOT\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211013\node_modules\typescript\lib\tsserver.js:171194:44)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (USER_ROOT\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211013\node_modules\typescript\lib\tsserver.js:169952:61)
    at USER_ROOT\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211013\node_modules\typescript\lib\tsserver.js:171658:88
    at IOSession.Session.executeWithRequestId (USER_ROOT\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211013\node_modules\typescript\lib\tsserver.js:171649:28)
    at IOSession.Session.executeCommand (USER_ROOT\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211013\node_modules\typescript\lib\tsserver.js:171658:33)
    at IOSession.Session.onMessage (USER_ROOT\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211013\node_modules\typescript\lib\tsserver.js:171684:35)
    at Interface.<anonymous> (USER_ROOT\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.5.20211013\node_modules\typescript\lib\tsserver.js:174289:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by DanielRosenwasser** [comment]
Apparently this is the 1000th non-design meeting-notes issue I've ever filed!
