### ISSUE TITLE
JS Code with static block exposes 3 issues: Crashes TypeScript language service, ErrorReporter typescript version bug, & lingering `bash.exe` processes leading to "console allocation failure"

### ISSUE THREAD

**Issue by DerekZiemba** [microsoft/TypeScript#46468]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `1.61.2 (system setup)` & maybe?  `1.61.0 (system setup)`
- OS Version: `Win10 Education 20H2 (OS Build 19042.1237)`

This was occurring on an earlier version which prompted me to finally click `Help -> Install Update`.   The new version exhibits the same issue.  I did not make a note of the version I was coming from, but I can't recall doing an update in the last 7 days so it might be earlier than `1.61.1`.

Steps to Reproduce:

1. Create a javascript file anywhere, or not, this will crash the TypeScript language service even in an unsaved new tab.
2. Paste the following code:  **[BUG # 1]:**
    ```js
    class ElementsArray extends Array {
      static {
        const superisArray = super.isArray;
        const customIsArray = (arg)=> superisArray(arg);
        this.isArray = customIsArray;
      }
    }
    ```
   * The TypeScript language service should now crash.
   * You may have to  `Reload Window` or close vscode and relaunch it. This may only occur if a tab is open with the above code on vscode statup or Typescript Language Service startup. I can't check now because of bash.exe side-effect _([BUG # 3] further down)_ caused by this bug. 

3.  With the TypeScript language service now crashed > 5 times. The ErrorReporter will prompt you to report the error.
     *  **[BUG # 2]:** The ErrorReporter  is unable to report issue because it says the TypeScript version is out of date, even if it is actually the latest version. 
![image](https://user-images.githubusercontent.com/7283693/138336430-9aa20b28-4054-4ab6-aaa6-0b9f0dc4c60b.png)

4. **[BUG # 3]:** The TypeScript Server crashing is resulting in lingering `bash` shells and apparently there is a limit of 32.  
![image](https://user-images.githubusercontent.com/7283693/138342003-f790b5a2-db72-4180-9ff5-2d3b965c5256.png)

  * * **EDIT:**  This actually brings about yet another bug:    
   **[BUG # 4]:** VSCode refuses to display the `PROBLEMS    OUTPUT    DEBUG CONSOLE   TERMINAL` panel if the terminal can't be started. 

------------------------------------

**EDIT2:**   
I failed to mention the issue with the TypeScript language service crashing has existed for well over a month, maybe months even.  Until this point I would just ignore it and try not to open the file that causes the crash.  I never tried to report the issue in the past because I was in fact using an older TypeScript version.
    
Today I finally became annoyed enough to look into it after running into and impeded for the n-th time by the `fatal error - console device allocation failure`  - which breaks things unrelated things system wide.   
I slowly removed code from that 1600 line file until I was left with only the code that would cause the crash, then simplified it further to the 7 line snippet above.   
After finding the root cause, I updated my typescript version to latest so that I could submit the issue.  Then the rabbit hole got deeper.

**Comment by mjbvz** [comment]
Confirmed with 4.5.0-dev.20211021. Here's the error stack:

```
  ERR <syntax> TypeScript Server Error (4.5.0-dev.20211021)
Debug Failure. Unexpected node.
Node ClassStaticBlockDeclaration was unexpected.
Error: Debug Failure. Unexpected node.
Node ClassStaticBlockDeclaration was unexpected.
    at bindThisPropertyAssignment (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:45720:30)
    at bindWorker (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:45337:29)
    at bind (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:45208:13)
    at bindExpressionStatement (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:44254:13)
    at bindChildren (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:43721:21)
    at bind (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:45219:21)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:43657:94
    at Object.forEach (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:197:30)
    at bindEach (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:43664:16)
    at bindEachFunctionsFirst (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:43657:13)
    at bindChildren (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:43774:21)
    at bind (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:45219:21)
    at visitNode (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:29626:24)
    at Object.forEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:29760:21)
    at bindEachChild (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:43667:16)
    at bindChildren (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:43788:21)
    at bindContainer (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:43613:17)
    at bind (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:45222:21)
    at Object.forEach (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:197:30)
...
```

**Comment by DerekZiemba** [comment]
@DanielRosenwasser  Thanks for addressing this so quickly!

I was actually impatient so I cloned the repo, pulled this branch, built it, then hackily pasted the `lib` folder over `C:\Users\Derek\AppData\Local\Volta\tools\image\packages\typescript\node_modules\typescript\lib`. 

Everything's been working fine.
