### ISSUE TITLE
"Debug Failure. False expression." after each change with ts-loader and webpack-dev-server

### ISSUE THREAD

**Issue by 0x53A** [microsoft/TypeScript#46555]
# Bug Report

I have a setup with webpack, ts-loader and typescript where after a single change typescript errors out and I have to restart WDS.

```
ERROR in ./src/index.tsx
Module build failed (from ../node_modules/ts-loader/index.js):
Error: Debug Failure. False expression.
    at updateRedirectsMap (C:\temp\repro_for_ts_loader_issue\TestApps\avicadYC\node_modules\typescript\lib\typescript.js:41751:22)
    at Object.update (C:\temp\repro_for_ts_loader_issue\TestApps\avicadYC\node_modules\typescript\lib\typescript.js:41844:13)
    at Object.createProgram (C:\temp\repro_for_ts_loader_issue\TestApps\avicadYC\node_modules\ts-loader\dist\servicesHost.js:419:91)
    at createProgram (C:\temp\repro_for_ts_loader_issue\TestApps\avicadYC\node_modules\typescript\lib\typescript.js:121308:28)
    at executeSteps (C:\temp\repro_for_ts_loader_issue\TestApps\avicadYC\node_modules\typescript\lib\typescript.js:121469:25)
    at Object.done (C:\temp\repro_for_ts_loader_issue\TestApps\avicadYC\node_modules\typescript\lib\typescript.js:121274:13)
    at buildNextInvalidatedProject (C:\temp\repro_for_ts_loader_issue\TestApps\avicadYC\node_modules\typescript\lib\typescript.js:122055:32)
    at Object.buildReferences (C:\temp\repro_for_ts_loader_issue\TestApps\avicadYC\node_modules\ts-loader\dist\servicesHost.js:520:13)
    at buildSolutionReferences (C:\temp\repro_for_ts_loader_issue\TestApps\avicadYC\node_modules\ts-loader\dist\instances.js:324:38)
    at Object.loader (C:\temp\repro_for_ts_loader_issue\TestApps\avicadYC\node_modules\ts-loader\dist\index.js:21:45)
```

I'm reporting this here as the callstack points to typescript, though the root cause may as well be either in webpack or ts-loader.

### 🔎 Search Terms

```
Debug Failure. False expression.
updateRedirectsMap
```

### 🕗 Version & Regression Information

This was tested with ``4.5.0-dev.20211006``

### ⏯ Sample Repo

I'm currently in the process of reducing my project down to a manageable repro

### 👀 Details

This is with a typescript project reference, and the crash only occurs when editing a file in the linked project, not when updating a file in the main project.

**Comment by andrewbranch** [comment]
I’m pretty sure this is due to a misuse of the module resolution cache within ts-loader.
