### ISSUE TITLE
Incorrect assertion in quick fix code

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#46615]
Extracted from https://github.com/microsoft/TypeScript/issues/38062

```ts
// @noImplicitAny: true

type Rest = (...string) => void;
type Public = (public string) => void;
```

Request quick fixes for this code snippet.

**Expected** Correct quick fixes

**Actual**

```
Error: Debug Failure. add-name-to-nameless-parameter operates on identifiers, but got a DotDotDotToken
    at makeChange (TYPESCRIPT_DIR\lib\tsserver.js:145716:33)
    at TYPESCRIPT_DIR\lib\tsserver.js:145707:96
    at Function.ChangeTracker.with (TYPESCRIPT_DIR\lib\tsserver.js:143896:17)
    at Object.getCodeActions (TYPESCRIPT_DIR\lib\tsserver.js:145707:64)
    at TYPESCRIPT_DIR\lib\tsserver.js:145087:77
    at Object.flatMap (TYPESCRIPT_DIR\lib\tsserver.js:522:25)
    at Object.getFixes (TYPESCRIPT_DIR\lib\tsserver.js:145087:23)
    at TYPESCRIPT_DIR\lib\tsserver.js:159943:35
    at Object.flatMap (TYPESCRIPT_DIR\lib\tsserver.js:522:25)
    at Proxy.getCodeFixesAtPosition (TYPESCRIPT_DIR\lib\tsserver.js:159941:23)
    at IOSession.Session.getCodeFixes (TYPESCRIPT_DIR\lib\tsserver.js:171425:64)
```

```
Error: Debug Failure. add-name-to-nameless-parameter operates on identifiers, but got a PublicKeyword
    at makeChange (TYPESCRIPT_DIR\lib\tsserver.js:145716:33)
    at TYPESCRIPT_DIR\lib\tsserver.js:145707:96
    at Function.ChangeTracker.with (TYPESCRIPT_DIR\lib\tsserver.js:143896:17)
    at Object.getCodeActions (TYPESCRIPT_DIR\lib\tsserver.js:145707:64)
    at TYPESCRIPT_DIR\lib\tsserver.js:145087:77
    at Object.flatMap (TYPESCRIPT_DIR\lib\tsserver.js:522:25)
    at Object.getFixes (TYPESCRIPT_DIR\lib\tsserver.js:145087:23)
    at TYPESCRIPT_DIR\lib\tsserver.js:159943:35
    at Object.flatMap (TYPESCRIPT_DIR\lib\tsserver.js:522:25)
    at Proxy.getCodeFixesAtPosition (TYPESCRIPT_DIR\lib\tsserver.js:159941:23)
    at IOSession.Session.getCodeFixes (TYPESCRIPT_DIR\lib\tsserver.js:171425:64)
```

**Comment by a-tarasyuk** [comment]
```ts
type Rest = (...string) => void;
```
@DanielRosenwasser Should TS suggest `Parameter has name but no type. Did you mean 'arg0: string'?` for _rest_ params?
