### ISSUE TITLE
tsc crash

### ISSUE THREAD

**Issue by Petah** [Microsoft/TypeScript#4674]
tsc crashed:

```
C:\Users\dneilsen\AppData\Roaming\npm\node_modules\typescript\bin\tsc.js:16437
              if (baseType.symbol !== resolveEntityName(baseTypeNode.expressio
                                                                    ^
TypeError: Cannot read property 'expression' of undefined
    at checkClassDeclaration (C:\Users\dneilsen\AppData\Roaming\npm\node_modules\typescript\bin\tsc.js:16437:75)
    at checkSourceElement (C:\Users\dneilsen\AppData\Roaming\npm\node_modules\typescript\bin\tsc.js:17151:28)
    at Object.forEach (C:\Users\dneilsen\AppData\Roaming\npm\node_modules\typescript\bin\tsc.js:67:30)
    at checkBlock (C:\Users\dneilsen\AppData\Roaming\npm\node_modules\typescript\bin\tsc.js:15718:16)
    at checkSourceElement (C:\Users\dneilsen\AppData\Roaming\npm\node_modules\typescript\bin\tsc.js:17114:28)
    at checkModuleDeclaration (C:\Users\dneilsen\AppData\Roaming\npm\node_modules\typescript\bin\tsc.js:16885:13)
    at checkSourceElement (C:\Users\dneilsen\AppData\Roaming\npm\node_modules\typescript\bin\tsc.js:17159:28)
    at checkModuleDeclaration (C:\Users\dneilsen\AppData\Roaming\npm\node_modules\typescript\bin\tsc.js:16885:13)
    at checkSourceElement (C:\Users\dneilsen\AppData\Roaming\npm\node_modules\typescript\bin\tsc.js:17159:28)
    at Object.forEach (C:\Users\dneilsen\AppData\Roaming\npm\node_modules\typescript\bin\tsc.js:67:30)
```

Running versions:
tsc 1.5.3
node v0.12.7
windows 7

(sorry if not enough info)

**Comment by mhegazy** [comment]
@Petah, this code has changed significantly in the last release, [1.6-beta](http://blogs.msdn.com/b/typescript/archive/2015/09/02/announcing-typescript-1-6-beta-react-jsx-better-error-checking-and-more.aspx). can you give latest a try?

**Comment by Petah** [comment]
Yea will try :)
