### ISSUE TITLE
BUG: vscode / Object not Implemented as InstallPackage

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/TypeScript#46932]
# Bug Report

### 🕗 Version & Regression Information

4.3 + current master

"Bugs" that have existed in TS for a long time are very likely to be FAQs; refer to
  https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs

If possible, please try testing the nightly version of TS to see if it's already been fixed.
For npm: `typescript@next`
This is also the 'Nightly' version in the playground: http://www.typescriptlang.org/play/?ts=Nightly

Note: The TypeScript Playground can be used to try older versions of TypeScript.

Please keep and fill in the line that best applies:
-->
- This is a crash
- This changed between versions 1.5.9 +
- I was unable to test this on prior versions because as this is a system wide installed package i did only test it with newer versions till current master

### ⏯ Playground Link
 Does not Apply for this Bug 

### 💻 Code

```ts
import http from 'https';
```

### 🙁 Actual behavior

```
<semantic> TypeScript Server Error (4.4.3)
Not implemented
Error: Not implemented
    at Object.notImplemented [as installPackage] (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:1567:15)
    at TypingsCache.installPackage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160811:39)
    at ConfiguredProject.Project.installPackage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:161065:42)
    at applySingleCodeActionCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:157139:24)
    at Proxy.applyCodeActionCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:157133:125)
    at IOSession.Session.applyCodeActionCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168600:50)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:167217:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168880:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168871:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168880:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:168906:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:171511:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

### 🙂 Expected behavior

Install @types/node

**Comment by frank-dspeed** [comment]
not solve able
