### ISSUE TITLE
Add circular import check at compile time

### ISSUE THREAD

**Issue by Kangaroux** [microsoft/TypeScript#47099]
Repo with an example to reproduce: https://github.com/Kangaroux/ts-circular-import

There is a circular import between `a.ts` and `b.ts`. There's no error when running `tsc`.

```
$ yarn run tsc --noEmit a.ts
Done in 1.27s.

$ yarn run tsc --noEmit b.ts
Done in 1.29s.
```

When running `ts-node` there is only an error when the entry point is `b.ts`:

```
$ yarn run ts-node a.ts
Done in 0.73s.

$ yarn run ts-node b.ts
/home/jessie/code/projects/ts-issue/a.ts:3
foo();
   ^
TypeError: (0 , b_1.foo) is not a function
    at Object.<anonymous> (/home/jessie/code/projects/ts-issue/a.ts:3:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/home/jessie/code/projects/ts-issue/node_modules/ts-node/src/index.ts:1371:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/home/jessie/code/projects/ts-issue/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/jessie/code/projects/ts-issue/b.ts:1:1)
error Command failed with exit code 1.
```

The error message isn't incorrect, but it would be helpful to catch this at compile time vs. runtime, and provide a more useful message.

**Comment by nmain** [comment]
The mechanics of circular imports are well defined in ECMAScript and not necessarily an error, so isn't this better suited to [linters](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md)?

**Comment by Kangaroux** [comment]
@nmain I was in the process of converting an existing project from JS to TS and didn't have eslint setup yet, it's entirely possible eslint would have caught this.

I guess then my question is, where is the distinction being made for errors caught by `tsc` vs. errors caught by a linter?

**Comment by AlCalzone** [comment]
Since this has bitten me before multiple times, getting an error or warning on circular value imports would be something I'd welcome.
Especially classes inheriting from imported classes seem to be affected by this.

**Comment by RyanCavanaugh** [comment]
See #4058

Disallowing circular imports is more of a style thing than a correctness thing, so we think this belongs as part of a linter check (especially since it can be done without semantic analysis)
