### ISSUE TITLE
Project build fails with tsc 4.5.x - Could not read properties of undefined (reading 'impliedNodeFormat') because file is null

### ISSUE THREAD

**Issue by TheArcaneBrony** [microsoft/TypeScript#47251]
# Bug Report

### 🔎 Search Terms

impliedNodeFormat

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.1.2 and 4.5.0
- I was unable to test this on prior versions because build works fine on 4.1.2, before updating any other packages

### ⏯ Playground Link

[Github repo](https://github.com/TheArcaneBrony/fosscord-server/tree/package-updates)
What I will try next: isolate the issue down to typescript, though I'm fairly certain the issue lies here.

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior

Build errors out:
```js
[2/2] Compiling src files ...
C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:114715
                throw e;
                ^

TypeError: Cannot read properties of undefined (reading 'impliedNodeFormat')
    at Object.getModeForUsageLocation (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:113495:18)
    at resolveExternalModule (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:49827:90)
    at resolveExternalModuleNameWorker (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:49803:19)
    at getExternalModuleFileFromDeclaration (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:85176:32)
    at Object.getExternalModuleFileFromDeclaration (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:85015:36)
    at tryGetModuleNameFromDeclaration (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:29324:59)
    at Object.getExternalModuleNameLiteral (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:29288:20)
    at createRequireCall (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:102502:33)
    at visitImportDeclaration (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:102462:80)
    at topLevelVisitor (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:102111:28)
node:child_process:903
    throw err;
    ^

Error: Command failed: node "C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js" -p "C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle"
C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:114715
                throw e;
                ^

TypeError: Cannot read properties of undefined (reading 'impliedNodeFormat')
    at Object.getModeForUsageLocation (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:113495:18)
    at resolveExternalModule (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:49827:90)
    at resolveExternalModuleNameWorker (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:49803:19)
    at getExternalModuleFileFromDeclaration (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:85176:32)
    at Object.getExternalModuleFileFromDeclaration (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:85015:36)
    at tryGetModuleNameFromDeclaration (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:29324:59)
    at Object.getExternalModuleNameLiteral (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:29288:20)
    at createRequireCall (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:102502:33)
    at visitImportDeclaration (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:102462:80)
    at topLevelVisitor (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\node_modules\typescript\lib\tsc.js:102111:28)

    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at Object.<anonymous> (C:\Users\TheArcaneBrony\Desktop\fosscord-arcane\bundle\scripts\build.js:58:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [
    null,
    '',
    'C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:114715\r\n' +
      '                throw e;\r\n' +
      '                ^\r\n' +
      '\r\n' +
      "TypeError: Cannot read properties of undefined (reading 'impliedNodeFormat')\r\n" +
      '    at Object.getModeForUsageLocation (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:113495:18)\r\n' +
      '    at resolveExternalModule (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:49827:90)\r\n' +
      '    at resolveExternalModuleNameWorker (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:49803:19)\r\n' +
      '    at getExternalModuleFileFromDeclaration (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:85176:32)\r\n' +
      '    at Object.getExternalModuleFileFromDeclaration (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:85015:36)\r\n' +
      '    at tryGetModuleNameFromDeclaration (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:29324:59)\r\n' +
      '    at Object.getExternalModuleNameLiteral (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:29288:20)\r\n' +
      '    at createRequireCall (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:102502:33)\r\n' +
      '    at visitImportDeclaration (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:102462:80)\r\n' +
      '    at topLevelVisitor (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:102111:28)\r\n'
  ],
  pid: 2492,
  stdout: '',
  stderr: 'C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:114715\r\n' +
    '                throw e;\r\n' +
    '                ^\r\n' +
    '\r\n' +
    "TypeError: Cannot read properties of undefined (reading 'impliedNodeFormat')\r\n" +
    '    at Object.getModeForUsageLocation (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:113495:18)\r\n' +
    '    at resolveExternalModule (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:49827:90)\r\n' +
    '    at resolveExternalModuleNameWorker (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:49803:19)\r\n' +
    '    at getExternalModuleFileFromDeclaration (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:85176:32)\r\n' +
    '    at Object.getExternalModuleFileFromDeclaration (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:85015:36)\r\n' +
    '    at tryGetModuleNameFromDeclaration (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:29324:59)\r\n' +
    '    at Object.getExternalModuleNameLiteral (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:29288:20)\r\n' +
    '    at createRequireCall (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:102502:33)\r\n' +
    '    at visitImportDeclaration (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:102462:80)\r\n' +
    '    at topLevelVisitor (C:\\Users\\TheArcaneBrony\\Desktop\\fosscord-arcane\\bundle\\node_modules\\typescript\\lib\\tsc.js:102111:28)\r\n'
}
```

### 🙂 Expected behavior

Build succeeds

**Comment by blutorange** [comment]
Just one note since we discussed this on discord: The project from the linked repo seems to be using `ts-patch`, so the error might be caused by that or some transformer. Perhaps it would help to try and reproduce this without `ts-patch` first?

**Comment by RyanCavanaugh** [comment]
```
C:\Throwaway\fosscord-server\bundle>tsc -p tsconfig.json
error TS18003: No inputs were found in config file 'C:/Throwaway/fosscord-server/bundle/tsconfig.json'. Specified 'include' paths were '["dist/**/*.ts"]' and 'exclude' paths were '[]'.
```

Can you please provide complete steps?
