### ISSUE TITLE
createProgarm with @typescript/vfs fails for target ES2021

### ISSUE THREAD

**Issue by dpilch** [microsoft/TypeScript#47273]
# Bug Report

`createProgram` fails with internal error when using @typescript/vfs and setting compiler option target to ES2021. This issue only happens for `ES2021`, all other targets work fine.

### 🔎 Search Terms

ES2021, createProgram, @typescript/vfs, vfs

### 🕗 Version & Regression Information

- This changed between versions 4.4.x and 4.5.x

Full version information:
- typescript@4.6.0-dev.20211230
- @typescript/vfs@1.3.5

### ⏯ Playground Link

Reproduction requires import of `typescript` and `@typescript/vfs`. Playground doesn't appear to support this.

### 💻 Code

```ts
import ts, { createProgram, ScriptTarget } from 'typescript';
import { createDefaultMapFromNodeModules, createSystem, createVirtualCompilerHost } from '@typescript/vfs';

const compilerOptions = { target: ScriptTarget.ES2021 };
const code = 'export default "foo"';

const fsMap = createDefaultMapFromNodeModules(compilerOptions, ts);
fsMap.set('index.tsx', code);
const host = createVirtualCompilerHost(createSystem(fsMap), compilerOptions, ts);

const program = createProgram({
  rootNames: [...fsMap.keys()],
  options: compilerOptions,
  host: host.compilerHost,
});
```

### 🙁 Actual behavior

Above snippet fails with following error:

```
/local/home/dppilche/typescript-vfs-bug/node_modules/typescript/lib/typescript.js:10460
        scan: while (pos >= 0 && pos < text.length) {
                                            ^
TypeError: Cannot read property 'length' of undefined
    at iterateCommentRanges (/local/home/dppilche/typescript-vfs-bug/node_modules/typescript/lib/typescript.js:10460:45)
    at reduceEachLeadingCommentRange (/local/home/dppilche/typescript-vfs-bug/node_modules/typescript/lib/typescript.js:10551:16)
    at Object.getLeadingCommentRanges (/local/home/dppilche/typescript-vfs-bug/node_modules/typescript/lib/typescript.js:10566:16)
    at Object.getJSDocCommentRanges (/local/home/dppilche/typescript-vfs-bug/node_modules/typescript/lib/typescript.js:15263:16)
    at addJSDocComment (/local/home/dppilche/typescript-vfs-bug/node_modules/typescript/lib/typescript.js:30878:42)
    at parseSourceFileWorker (/local/home/dppilche/typescript-vfs-bug/node_modules/typescript/lib/typescript.js:30851:34)
    at Object.parseSourceFile (/local/home/dppilche/typescript-vfs-bug/node_modules/typescript/lib/typescript.js:30683:26)
    at Object.createSourceFile (/local/home/dppilche/typescript-vfs-bug/node_modules/typescript/lib/typescript.js:30481:29)
    at Object.getSourceFile (/local/home/dppilche/typescript-vfs-bug/node_modules/@typescript/vfs/src/index.ts:504:16)
    at findSourceFileWorker (/local/home/dppilche/typescript-vfs-bug/node_modules/typescript/lib/typescript.js:115369:29)
```

### 🙂 Expected behavior

`createProgram` does not crash.

**Comment by suin** [comment]
This issue occurs because `lib.es2021.intl.d.ts` is missing in `knownLibFilesForCompilerOptions` of vfs.

https://github.com/microsoft/TypeScript-Website/blob/c1050864dbc359cfa957aa8b52db624cd379ddcf/packages/typescript-vfs/src/index.ts#L154-L160

We can work around this problem by manually adding  `lib.es2021.intl.d.ts`  to the `fsMap`.

```diff
import ts, { createProgram, ScriptTarget } from 'typescript';
import { createDefaultMapFromNodeModules, createSystem, createVirtualCompilerHost } from '@typescript/vfs';

const compilerOptions = { target: ScriptTarget.ES2021 };
const code = 'export default "foo"';

const fsMap = createDefaultMapFromNodeModules(compilerOptions, ts);
+fsMap.set(
+  "/lib.es2021.intl.d.ts",
+  fs.readFileSync(require.resolve("typescript"), "utf8") +
+    "/lib.es2021.intl.d.ts"
+);
fsMap.set('index.tsx', code);
const host = createVirtualCompilerHost(createSystem(fsMap), compilerOptions, ts);

const program = createProgram({
  rootNames: [...fsMap.keys()],
  options: compilerOptions,
  host: host.compilerHost,
});
```

**Comment by dpilch** [comment]
Thanks, this suggestion worked! I just needed to wrap `require.resolve('typescript')` with `path.dirname` as done here: https://github.com/microsoft/TypeScript-Website/blob/fa4d8d29eaa2046a9c68234b3728c9cb69078045/packages/typescript-vfs/src/index.ts#L200

**Comment by Matsuuu** [comment]
Submitted a relating issue to this to the vfs project https://github.com/microsoft/TypeScript-Website/issues/2801

**Comment by RyanCavanaugh** [comment]
The failure was in `@typescript/vfs`'s library map: it omitted `lib.es2021.intl.d.ts` for an ES2021 target, leaving the virtual host with a source file whose text was undefined. The reported program throws with `@typescript/vfs@1.3.5`, and creates the program successfully with `@typescript/vfs@1.5.0` and `1.6.4`. [TypeScript-Website PR #2802](https://github.com/microsoft/TypeScript-Website/pull/2802) fixed the map by enumerating installed `lib.*.d.ts` files.
