### ISSUE TITLE
Incremental compile is getting "TypeError" periodically

### ISSUE THREAD

**Issue by chuckjaz** [microsoft/TypeScript#47286]
# Bug Report

### 🔎 Search Terms
TypeError 'kind' undefined emitEmbeddedStatement

### 🕗 Version & Regression Information
Version 4.5.2

Incremental compile will periodically crash with the following exception:

```
./typescript/lib/tsc.js:94427
                throw e;
                ^

TypeError: Cannot read property 'kind' of undefined
    at Object.isBlock (./typescript/lib/tsc.js:22599:21)
    at emitEmbeddedStatement (./typescript/lib/tsc.js:91284:20)
    at emitForStatement (./typescript/lib/tsc.js:90210:13)
    at pipelineEmitWithHintWorker (./typescript/lib/tsc.js:88994:32)
    at pipelineEmitWithHint (./typescript/lib/tsc.js:88855:17)
    at pipelineEmitWithSourceMaps (./typescript/lib/tsc.js:92391:13)
    at pipelineEmitWithComments (./typescript/lib/tsc.js:92106:13)
    at pipelineEmit (./typescript/lib/tsc.js:88799:13)
    at emit (./typescript/lib/tsc.js:88772:13)
    at emitNodeList (./typescript/lib/tsc.js:91463:25)
```

No clear steps to reproduce as I notice this periodically have during a programming session. I am willing to narrow this down if you have not seen this before. It happens at least once a day to me and the stack is different than I found in the other TypeError reports.

### Steps

1. npx tsc -w
2. modify files in the directory

### 🙁 Actual behavior

Crashes with a TypeError

### 🙂 Expected behavior

Continues incremental compiling

**Comment by RyanCavanaugh** [comment]
We haven't seen this before. A repro or general hint would be great -- the call stack might be amenable to debugging-by-staring but I'm not super hopeful given that it's intermittent.

**Comment by chuckjaz** [comment]
I haven't seen this in a few days. It seems to be related to what I was doing at the time. My best guess is that it is related to moving an renaming files but I will try to narrow it down.

**Comment by chuckjaz** [comment]
I still don't have concrete steps but it seems to be related to renaming files. Simply just renaming a file is not good enough, it might require renaming a file while the server is busy and then tries to pick of the renamed file after it finishes its current task.
