### ISSUE TITLE
Code fix crash with incorrect JSDoc assertion

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#47415]
```js
// @ts-check

let x = /** @type {string} */ (100);
```

```
Response received: getCodeFixes (204). Request took 11 ms. Success: false . Message: Error processing request. Debug Failure. Expected to find an assertion expression
Error: Debug Failure. Expected to find an assertion expression
    at makeChange ([USERDIR]\TypeScript\built\local\tsserver.js:146006:38)
    at [USERDIR]\TypeScript\built\local\tsserver.js:145998:96
    at Function.ChangeTracker.with ([USERDIR]\TypeScript\built\local\tsserver.js:144689:17)
    at Object.getCodeActionsToAddConvertToUnknownForNonOverlappingTypes [as getCodeActions] ([USERDIR]\TypeScript\built\local\tsserver.js:145998:64)
    at [USERDIR]\TypeScript\built\local\tsserver.js:145922:77
    at Object.flatMap ([USERDIR]\TypeScript\built\local\tsserver.js:486:25)
    at Object.getFixes ([USERDIR]\TypeScript\built\local\tsserver.js:145922:23)
    at [USERDIR]\TypeScript\built\local\tsserver.js:160825:35
    at Object.flatMap ([USERDIR]\TypeScript\built\local\tsserver.js:486:25)
    at Object.getCodeFixesAtPosition ([USERDIR]\TypeScript\built\local\tsserver.js:160823:23)
    at IOSession.Session.getCodeFixes ([USERDIR]\TypeScript\built\local\tsserver.js:172312:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([USERDIR]\TypeScript\built\local\tsserver.js:170948:61)
    at [USERDIR]\TypeScript\built\local\tsserver.js:172625:88
    at IOSession.Session.executeWithRequestId ([USERDIR]\TypeScript\built\local\tsserver.js:172616:28)
    at IOSession.Session.executeCommand ([USERDIR]\TypeScript\built\local\tsserver.js:172625:33)
    at IOSession.Session.onMessage ([USERDIR]\TypeScript\built\local\tsserver.js:172651:35)
    at Interface.<anonymous> ([USERDIR]\TypeScript\built\local\tsserver.js:175256:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

Found from https://github.com/microsoft/TypeScript/issues/38062#issuecomment-1008905855

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
