### ISSUE TITLE
Code fix crash  in JSDoc with strictPropertyInitialization

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#47417]
```ts
// @strictPropertyInitialization: true

////// @ts-check
////
////class C {
////    /** @type {string} */
////    foo;
////
////    constructor() {
////        
////    }
////}
```

Request code actions.

```
Response received: getCodeFixes (73). Request took 3 ms. Success: false . Message: Error processing request. Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at Object.isUnionTypeNode ([USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:27948:21)
    at addUndefinedType ([USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:153377:28)
    at [USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:153371:92
    at Function.ChangeTracker.with ([USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144341:17)
    at getActionForAddMissingUndefinedType ([USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:153371:60)
    at Object.getCodeActions ([USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:153326:21)
    at [USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145527:77
    at Object.flatMap ([USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:522:25)
    at Object.getFixes ([USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145527:23)
    at [USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160394:35
    at Object.flatMap ([USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:522:25)
    at Object.getCodeFixesAtPosition ([USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160392:23)
    at IOSession.Session.getCodeFixes ([USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:171880:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170516:61)
    at [USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId ([USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172184:28)
    at IOSession.Session.executeCommand ([USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172193:33)
    at IOSession.Session.onMessage ([USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172219:35)
    at Interface.<anonymous> ([USERDIR]\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by DanielRosenwasser** [comment]
Haven't been able to get this one to test correctly. Maybe you can give a shot at getting fourslash to work @RyanCavanaugh. Here's what I managed to put together.

```
/// <reference path="./fourslash.ts" />

// @checkJs: true
// @strictPropertyInitialization: true

// @Filename: /foo.js
//// //start
//// class C {
////     /** @type {string} */
////     foo/*$*/;
//// 
////     constructor() {}
//// }

goTo.marker("$");
verify.codeFixAll({
    fixId: "addMissingPropertyUndefinedType",
    fixAllDescription: "Add undefined type to all uninitialized properties",
    newFileContent: `//start
class C {
    /** @type {string | undefined} */
    foo/*$*/;

    constructor() {}
}
`,
});
```

**Comment by a-tarasyuk** [comment]
`fixStrictClassInitialization` doesn't support JavaScript files. 
It contains three code actions `addMissingPropertyDefiniteAssignmentAssertions`, `addMissingPropertyUndefinedType`, `addMissingPropertyInitializer`. 

`addMissingPropertyDefiniteAssignmentAssertions` added `!` token which is not valid in JavaScript. 
`addMissingPropertyUndefinedType` doesn't support JSDoc types, only TypeScript. Do we need to support it in JavaScript?
`addMissingPropertyInitializer` can be used in JavaScript, however, need to fix the resolving type from JSDoc tags, only question is - do we need to check the target version?

/cc @DanielRosenwasser @RyanCavanaugh

**Comment by DanielRosenwasser** [comment]
Like the other issue, I could go either way on either supporting this or not supporting this.

The crash seems to be coming from the `addMissingPropertyUndefinedType`, and it's easy enough to get the effective type annotation for JSDoc (using `getEffectiveTypeAnnotationNode`), so making it work in JS is easy in theory.

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser The main issue to support `addMissingPropertyUndefinedType` in JS will be replacing the JSDoc type. 

> For addMissingPropertyInitializer, either works - though I don't know how useful the fix even is today.

We can try to support `addMissingPropertyUndefinedType` and `addMissingPropertyInitializer` and completely disable `addMissingPropertyDefiniteAssignmentAssertions`. Or omit QF in JS.

**Comment by DanielRosenwasser** [comment]
Here's my preference:

* Disable `addMissingPropertyDefiniteAssignmentAssertions` in JS
* Disable `addMissingPropertyInitializer` in JS
* Support `addMissingPropertyUndefinedType` in JS by using `getEffectiveTypeAnnotationNode`

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!

**Comment by DanielRosenwasser** [comment]
Cherry-pick didn't go through.
