### ISSUE TITLE
Crash in completionEntryDetails with existing `require("...").foo`

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#47428]
```ts
// @allowJs: true
// @Filename: library.js
export function aaa() {}
export function bbb() {}

// @Filename: foo.js
var a = require("./library").aaa
/**/
```

Go to the marker `/**/` and request completion details on `bbb`.

```
Response received: completionEntryDetails (523). Request took 5 ms. Success: false . Message: Error processing request. Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at getModuleSpecifierExpression ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:137533:93)
    at compareImportsOrRequireStatements ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:137555:44)
    at binarySearchKey ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:1200:21)
    at Object.binarySearch ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:1178:16)
    at Object.getImportDeclarationInsertionIndex ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:137545:28)
    at Object.insertImports ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:124647:57)
    at codeActionForFixWorker ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:148939:24)
    at [NODE_MODULES_PATH]/typescript/lib/tsserver.js:148911:24
    at Function.ChangeTracker.with ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:144341:17)
    at codeActionForFix ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:148910:60)
    at Object.getImportCompletionAction ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:148426:55)
    at getCompletionEntryCodeActionsAndSourceDisplay ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:129176:33)
    at Object.getCompletionEntryDetails ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:129120:30)
    at Object.getCompletionEntryDetails ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:160080:35)
    at [NODE_MODULES_PATH]/typescript/lib/tsserver.js:171575:57
    at Object.mapDefined ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:619:30)
    at IOSession.Session.getCompletionEntryDetails ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:171573:33)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:170398:61)
    at [NODE_MODULES_PATH]/typescript/lib/tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:172184:28)
    at IOSession.Session.executeCommand ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:172193:33)
    at IOSession.Session.onMessage ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:172219:35)
    at Interface.<anonymous> ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by DanielRosenwasser** [comment]
Can't seem to reproduce it with this fourslash test.

```ts
/// <reference path="./fourslash.ts" />

// @allowJs: true
// @module: commonjs
// @Filename: /library.js
//// export function aaa() {}
//// export function bbb() {}

// @Filename: /foo.js
//// var a = require("./library").aaa;
//// /*$*/

goTo.marker("$");
verify.completions({
    includes: [
        {
            name: "bbb",
            hasAction: true,
            source: "./library",
            sortText: completion.SortText.AutoImportSuggestions,
            
        }
    ],
    preferences: {
        includeCompletionsForModuleExports: true,
        includeCompletionsForImportStatements: true,
        includeCompletionsWithInsertText: true,
        allowIncompleteCompletions: true,
        includeCompletionsWithSnippetText: true,
    }
});

verify.applyCodeActionFromCompletion("$", {
    name: "bbb",
    source: "./library",
    description: "Import 'bbb' from module \"./library\"",
    preferences: {
        includeCompletionsForModuleExports: true
    },
});


```
