### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by jsobus-neurosys** [microsoft/TypeScript#47429]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.4

**Steps to reproduce crash**
Was making a global find and replace on solution.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at _loop_2 (c:\Users\jsobu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167154:34)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\jsobu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167162:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\jsobu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168828:26)
    at c:\Users\jsobu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169102:97
    at Object.flatMap (c:\Users\jsobu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\jsobu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169102:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\jsobu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170260:46)
    at c:\Users\jsobu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId (c:\Users\jsobu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172184:28)
    at IOSession.Session.executeCommand (c:\Users\jsobu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172193:33)
    at IOSession.Session.onMessage (c:\Users\jsobu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172219:35)
    at Interface.<anonymous> (c:\Users\jsobu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|3.1.2
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.7.0
vscode-yarn|gam|2.0.0
csharpfixformat|Leo|0.0.84
vscode-docker|ms-|1.18.0
remote-containers|ms-|0.209.6
remote-wsl|ms-|0.63.13
angular-console|nrw|17.13.6
vscode-commons|red|0.0.6
vscode-yaml|red|1.2.2
vscode-import-cost|wix|2.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by mjbvz** [comment]
Can you reliably reproduce this issue? If show, can you share step to reproduce the problem

**Comment by jsobus-neurosys** [comment]
I was just making a solution wide search and replace, while going file by file checking if replacement is ok this error appeared a few times. Solution is not that big and specific, we are using nx for monorepo if that is important.

**Comment by RyanCavanaugh** [comment]
We'll definitely need a repro or at least a TS server log

**Comment by jsobus-neurosys** [comment]
Enabled server logging and trying to report issue i am getting this:
![image](https://user-images.githubusercontent.com/12592482/149561248-c3dee478-90f9-4f04-957d-037c0f9e0c3d.png)

Reproduction steps:
1. Search specific string in solution - found 115 results in 43 files in my case.
2. Navigate through files to see diff with after replace result.
3. After few minutes VS code notification appears that ts is not working with a button to submit this ticket.

**Comment by jsobus-neurosys** [comment]
Info from log - removed my code and path inside solution, can not share it here:
```
Err 2207  [18:45:46.609] Exception on executing command {"seq":11,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":["removed my path#replacePreview","removed my path"],"openFiles":[{"file":"removed my code","fileContent":"removed my code","scriptKindName":"TS"}]}}:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at _loop_2 (c:\Users\Kuba\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167154:34)
        at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\Kuba\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167162:25)
        at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Kuba\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:168828:26)
        at c:\Users\Kuba\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169102:97
        at Object.flatMap (c:\Users\Kuba\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:522:25)
        at ProjectService.applyChangesInOpenFiles (c:\Users\Kuba\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:169102:41)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\Kuba\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:170260:46)
        at c:\Users\Kuba\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172193:88
        at IOSession.Session.executeWithRequestId (c:\Users\Kuba\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172184:28)
        at IOSession.Session.executeCommand (c:\Users\Kuba\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172193:33)
        at IOSession.Session.onMessage (c:\Users\Kuba\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172219:35)
        at Interface.<anonymous> (c:\Users\Kuba\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174824:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Info 2208 [18:45:46.609] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":11,"success":false,"performanceData":{"updateGraphDurationMs":770.5351999998093},"message":"Error processing request. Debug Failure. False expression.\nError: Debug Failure. False expression.\n    at _loop_2 (c:\\Users\\Kuba\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:167154:34)\n    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\\Users\\Kuba\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:167162:25)\n    at ProjectService.assignProjectToOpenedScriptInfo (c:\\Users\\Kuba\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:168828:26)\n    at c:\\Users\\Kuba\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:169102:97\n    at Object.flatMap (c:\\Users\\Kuba\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:522:25)\n    at ProjectService.applyChangesInOpenFiles (c:\\Users\\Kuba\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:169102:41)\n    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\\Users\\Kuba\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:170260:46)\n    at c:\\Users\\Kuba\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:172193:88\n    at IOSession.Session.executeWithRequestId (c:\\Users\\Kuba\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:172184:28)\n    at IOSession.Session.executeCommand (c:\\Users\\Kuba\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:172193:33)\n    at IOSession.Session.onMessage (c:\\Users\\Kuba\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:172219:35)\n    at Interface.<anonymous> (c:\\Users\\Kuba\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:174824:31)\n    at Interface.emit (events.js:315:20)\n    at Interface._onLine (readline.js:337:10)\n    at Interface._normalWrite (readline.js:482:12)\n    at Socket.ondata (readline.js:194:10)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)"}
```
