### ISSUE TITLE
Debug assertion violation for extract type refactoring

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#47582]
Manifestation of https://github.com/microsoft/TypeScript/issues/45744

```ts
export declare function yadda<T extends { next?: /*$*/T }>(): void;
```

Request the "extract type" refactoring at `/*$*/`.

```
[Trace  - 20:42:59.406] <semantic> Response received: getEditsForRefactor (827). Request took 3 ms. Success: false . Message: Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at consumeTokenAndAdvanceScanner ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143766:30)
    at processChildNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143679:25)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143629:21
    at visitNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:29727:24)
    at Object.forEachChild ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:29807:21)
    at processNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143628:20)
    at processChildNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143696:21)
    at processChildNodes ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143743:48)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143631:21
    at visitNodes ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:29732:24)
    at Object.forEachChild ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:29872:24)
    at processNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143628:20)
    at processChildNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143696:21)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143629:21
    at visitNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:29727:24)
    at Object.forEachChild ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:29773:21)
    at processNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143628:20)
    at processChildNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143696:21)
    at processChildNodes ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143743:48)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143631:21
    at visitNodes ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:29732:24)
    at Object.forEachChild ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:30065:21)
    at processNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143628:20)
    at formatSpanWorker ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143429:17)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143393:140
    at Object.getFormattingScanner ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:142020:23)
    at Object.formatNodeGivenIndentation ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143393:31)
    at getFormattedTextOfNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145776:45)
    at format ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145747:52)
    at computeNewText ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145750:23)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145714:39
    at Object.mapDefined ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:599:30)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145712:42
    at Object.mapDefined ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:599:30)
    at Object.getTextChangesFromChanges ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145698:27)
    at ChangeTracker.getChanges ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145637:45)
    at Function.ChangeTracker.with ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145067:32)
    at Object.getRefactorEditsToExtractType [as getEditsForAction] ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:157447:62)
    at Object.getEditsForRefactor ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:146362:41)
    at Object.getEditsForRefactor ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:161707:32)
    at IOSession.Session.getEditsForRefactor ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:172742:59)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:171446:61)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:173105:88
    at IOSession.Session.executeWithRequestId ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:173096:28)
    at IOSession.Session.executeCommand ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:173105:33)
    at IOSession.Session.onMessage ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:173131:35)
    at Interface.<anonymous> ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:175736:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
