### ISSUE TITLE
Crash in extract function due to non-null assertion

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#47782]
Repro for https://github.com/microsoft/TypeScript/issues/36710 due to

https://github.com/microsoft/TypeScript/blob/14feed97a04e29ab8fdeb6c3671a1f4473a7c0b2/src/services/refactors/extractSymbol.ts#L484-L494

```ts
[|super()|]
```

Request refactorings (specifically extract constant/function).

```
[Trace  - 19:48:27.4] <semantic> Response received: getApplicableRefactors (26). Request took 2 ms. Success: false . Message: Error processing request. Cannot read property 'pos' of undefined
TypeError: Cannot read property 'pos' of undefined
    at visit ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:155280:59)
    at visitNode ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:29689:24)
    at Object.forEachChild ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:29890:24)
    at visit ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:155390:36)
    at visitNode ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:29689:24)
    at Object.forEachChild ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:29951:24)
    at visit ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:155390:36)
    at checkNode ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:155248:21)
    at getRangeToExtract ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:155154:53)
    at Object.getAvailableActions ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:154890:38)
    at [WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:145583:30
    at getIterator ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:576:23)
    at Object.next ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:571:35)
    at Object.arrayFrom ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:1316:88)
    at Object.getApplicableRefactors ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:145579:23)
    at Object.getApplicableRefactors ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:160857:32)
    at IOSession.Session.getApplicableRefactors ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:171827:53)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:170536:61)
    at [WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:172195:88
    at IOSession.Session.executeWithRequestId ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:172186:28)
    at IOSession.Session.executeCommand ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:172195:33)
    at IOSession.Session.onMessage ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:172221:35)
    at Interface.<anonymous> ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:174826:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)```

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
