### ISSUE TITLE
Crash after `case` keyword outside of `switch` statement

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#47783]
Repro of https://github.com/microsoft/TypeScript/issues/36715

```
case /**/
```

Request completions

```
[Trace  - 20:04:35.678] <semantic> Response received: completionInfo (535). Request took 26 ms. Success: false . Message: Error processing request. Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isCaseClause'.
Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isCaseClause'.
    at Object.cast ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:1507:25)
    at getContextualType ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:129228:50)
    at getCompletionData ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:129531:51)
    at Object.getCompletionsAtPosition ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:128325:34)
    at Object.getCompletionsAtPosition ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:160077:35)
    at IOSession.Session.getCompletions ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:171546:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:170391:61)
    at [WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:172195:88
    at IOSession.Session.executeWithRequestId ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:172186:28)
    at IOSession.Session.executeCommand ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:172195:33)
    at IOSession.Session.onMessage ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:172221:35)
    at Interface.<anonymous> ([WORKSPACE_DIR]\node_modules\typescript\lib\tsserver.js:174826:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
