### ISSUE TITLE
TypeError: path.indexOf is not a function in github actions

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#47921]
https://github.com/bluelovers/ws-rest/runs/5221176096?check_suite_focus=true

```
/home/runner/.config/yarn/global/node_modules/typescript/lib/typescript.js:7690
        var index = path.indexOf("\\");
                         ^
TypeError: path.indexOf is not a function
    at normalizeSlashes (/home/runner/.config/yarn/global/node_modules/typescript/lib/typescript.js:7690:26)
    at Object.combinePaths (/home/runner/.config/yarn/global/node_modules/typescript/lib/typescript.js:7756:28)
    at /home/runner/.config/yarn/global/node_modules/typescript/lib/typescript.js:41927:40
    at Object.firstDefined (/home/runner/.config/yarn/global/node_modules/typescript/lib/typescript.js:407:26)
    at primaryLookup (/home/runner/.config/yarn/global/node_modules/typescript/lib/typescript.js:41926:27)
    at Object.resolveTypeReferenceDirective (/home/runner/.config/yarn/global/node_modules/typescript/lib/typescript.js:41885:24)
    at /home/runner/.config/yarn/global/node_modules/ts-node/src/resolver-functions.ts:135:14
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/home/runner/.config/yarn/global/node_modules/ts-node/src/resolver-functions.ts:133:33)
    at actualResolveTypeReferenceDirectiveNamesWorker (/home/runner/.config/yarn/global/node_modules/typescript/lib/typescript.js:11[49](https://github.com/bluelovers/ws-rest/runs/5221176096?check_suite_focus=true#step:5:49)19:163)
    at resolveTypeReferenceDirectiveNamesWorker (/home/runner/.config/yarn/global/node_modules/typescript/lib/typescript.js:11[51](https://github.com/bluelovers/ws-rest/runs/5221176096?check_suite_focus=true#step:5:51)85:26)
    at processTypeReferenceDirectives (/home/runner/.config/yarn/global/node_modules/typescript/lib/typescript.js:116660:31)
    at findSourceFileWorker (/home/runner/.config/yarn/global/node_modules/typescript/lib/typescript.js:116[54](https://github.com/bluelovers/ws-rest/runs/5221176096?check_suite_focus=true#step:5:54)5:21)
    at findSourceFile (/home/runner/.config/yarn/global/node_modules/typescript/lib/typescript.js:116407:26)
    at processImportedModules (/home/runner/.config/yarn/global/node_modules/typescript/lib/typescript.js:116806:25)
    at findSourceFileWorker (/home/runner/.config/yarn/global/node_modules/typescript/lib/typescript.js:116[55](https://github.com/bluelovers/ws-rest/runs/5221176096?check_suite_focus=true#step:5:55)1:17)
```

https://github.com/bluelovers/idea-l10n-zht/runs/5216786455?check_suite_focus=true

```
/home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/typescript/lib/typescript.js:7690
        var index = path.indexOf("\\");
                         ^
TypeError: path.indexOf is not a function
    at normalizeSlashes (/home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/typescript/lib/typescript.js:7690:26)
    at Object.combinePaths (/home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/typescript/lib/typescript.js:7756:28)
    at /home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/typescript/lib/typescript.js:41927:40
    at Object.firstDefined (/home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/typescript/lib/typescript.js:407:26)
    at primaryLookup (/home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/typescript/lib/typescript.js:41926:27)
    at Object.resolveTypeReferenceDirective (/home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/typescript/lib/typescript.js:41885:24)
    at /home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/ts-node/src/resolver-functions.ts:135:14
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/ts-node/src/resolver-functions.ts:133:33)
    at actualResolveTypeReferenceDirectiveNamesWorker (/home/runner/work/idea-l10n-zht/idea-l10n-zht/node_modules/typescript/lib/typescript.js:114919:163)
```

**Comment by jakebailey** [comment]
I was able to reproduce it by using the latter of the above repos and just tweaking the typescript version; the issue was introduced in between `4.7.0-dev.20220215` and `4.7.0-dev.20220216`.

**Comment by RyanCavanaugh** [comment]
The call stack points to https://github.com/microsoft/TypeScript/pull/47732

**Comment by weswigham** [comment]
Whilst I can technically fix this by making `resolveTypeReferenceDirective` accept a `FileReference` just like `resolveTypeReferenceDirectives` does now due to the structure of the code in `ts-node`, the issue is actually in `ts-node` - we changed the signature of `resolveTypeReferenceDirectives` and their override signature has yet to be updated to match.
