### ISSUE TITLE
Inappropriate assertion failure in 'getFixesInfoForNonUMDImport'

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#48008]
```ts
export { /**/default };
```

Request code fixes on `/**/`

```
<semantic> Response received: getCodeFixes (64). Request took 13 ms. Success: false . Message: Error processing request. Debug Failure. False expression: 'default' isn't a legal identifier and couldn't occur here
Error: Debug Failure. False expression: 'default' isn't a legal identifier and couldn't occur here
    at getFixesInfoForNonUMDImport ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:150288:22)
    at getFixesInfo ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:150156:24)
    at Object.getCodeActions ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:149633:28)
    at [USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:146935:77
    at Object.flatMap ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:508:25)
    at Object.getFixes ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:146935:23)
    at [USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:162162:35
    at Object.flatMap ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:508:25)
    at Object.getCodeFixesAtPosition ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:162160:23)
    at IpcIOSession.Session.getCodeFixes ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:173727:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:172360:61)
    at [USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:174040:88
    at IpcIOSession.Session.executeWithRequestId ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:174031:28)
    at IpcIOSession.Session.executeCommand ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:174040:33)
    at IpcIOSession.Session.onMessage ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:174066:35)
    at process.<anonymous> ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:176701:31)
    at process.emit (node:events:394:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by DanielRosenwasser** [comment]
Thanks to @amcasey for finding the original repro of

```ts
export { default: someVar };
```

**Comment by jakebailey** [comment]
This traces back to #17376-ish. I _think_ the right thing is to just drop the assertion and just return `undefined` here, but I haven't yet gone to verify that it's not a parser/etc problem that there's an identifier called `default` in the tree:

![image](https://user-images.githubusercontent.com/5341706/155452557-f2fed823-afac-4f58-b27b-9a6e99f170c3.png)
