### ISSUE TITLE
webpack ts-loader error using TS 4.7

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#48020]
# Bug Report

### 🔎 Search Terms
- webpack
- ts-loader
- `@types`

### 🕗 Version & Regression Information

- This changed between versions TS 4.6-1-rc and 4.7.0-dev.20220223

### 💻 Code

Clone https://github.com/mjbvz/ts-47-webpack-error

In the project run:

```
npm i
npm run build
```

### 🙁 Actual behavior

The presence of `@types/dompurify` in the project triggers the following error:

```
ERROR in ./src/index.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: path.indexOf is not a function
    at normalizeSlashes (/Users/matb/projects/san/ts-webpack/node_modules/typescript/lib/typescript.js:7691:26)
    at Object.combinePaths (/Users/matb/projects/san/ts-webpack/node_modules/typescript/lib/typescript.js:7757:28)
    at /Users/matb/projects/san/ts-webpack/node_modules/typescript/lib/typescript.js:41922:40
    at Object.firstDefined (/Users/matb/projects/san/ts-webpack/node_modules/typescript/lib/typescript.js:407:26)
    at primaryLookup (/Users/matb/projects/san/ts-webpack/node_modules/typescript/lib/typescript.js:41921:27)
    at Object.resolveTypeReferenceDirective (/Users/matb/projects/san/ts-webpack/node_modules/typescript/lib/typescript.js:41880:24)
    at /Users/matb/projects/san/ts-webpack/node_modules/ts-loader/dist/servicesHost.js:713:18
    at /Users/matb/projects/san/ts-webpack/node_modules/ts-loader/dist/servicesHost.js:128:141
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/Users/matb/projects/san/ts-webpack/node_modules/ts-loader/dist/servicesHost.js:128:124)
```

### 🙂 Expected behavior

This example builds under TS 4.6-rc and TS 4.5. I'm guessing something about the TS internal APIs that ts-loader depends on has changed

**Comment by mjbvz** [comment]
This seems to be caused by this directive at the top of `@types/dompurify`:

```
/// <reference types="trusted-types"/>
```

**Comment by fatcerberus** [comment]
Callstack looks the same as https://github.com/microsoft/TypeScript/issues/47921, but that one was tagged `External`.

**Comment by RyanCavanaugh** [comment]
See e.g. https://github.com/TypeStrong/ts-node/issues/1647

**Comment by RyanCavanaugh** [comment]
Logged https://github.com/TypeStrong/ts-loader/issues/1421

**Comment by johnnyreilly** [comment]
I've put together a speculative fix for this issue in `ts-loader`.  @mjbvz would you care to give it a test?  It appears to work, but my testing is purely based on your repro repo; I haven't encountered this issue directly myself. 

https://github.com/TypeStrong/ts-loader/pull/1422
