### ISSUE TITLE
False expression: Token end is child end 【I don't know what to call this issue]】

### ISSUE THREAD

**Issue by Judu233** [microsoft/TypeScript#48139]
# Bug Report
```ts
 [error] <semantic> TypeScript Server Error (4.6.2)
Debug Failure. False expression: Token end is child end
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144315:38)
    at e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144255:21
    at visitNode (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:29849:24)
    at Object.forEachChild (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:29972:21)
    at processNode (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144254:20)
    at formatSpanWorker (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144055:17)
    at e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144019:140
    at Object.getFormattingScanner (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:142646:23)
    at Object.formatNodeGivenIndentation (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144019:31)
    at e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129984:46
    at Object.flatMap (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:508:25)
    at getEntryForMemberCompletion (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129982:38)
    at createCompletionEntry (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129802:23)
    at getCompletionEntriesFromSymbols (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130166:29)
    at completionInfoFromData (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129620:17)
    at Object.getCompletionsAtPosition (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129481:36)
    at Object.getCompletionsAtPosition (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:161847:35)
    at IpcIOSession.Session.getCompletions (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:173395:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:172237:61)
    at e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174044:88
    at IpcIOSession.Session.executeWithRequestId (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174035:28)
    at IpcIOSession.Session.executeCommand (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174044:33)
    at IpcIOSession.Session.onMessage (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:174070:35)
    at process.<anonymous> (e:\vs code\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:176705:31)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21): Error: <semantic> TypeScript Server Error (4.6.2)
```

### 🔎 Search Terms

N/A since I'm not sure how to describe it.
It suddenly appeared at a certain moment. I don't know how to trigger it. I tried to reinstall vscode, but it didn't work

### 🕗 Version & Regression Information
vscode version:
![image](https://user-images.githubusercontent.com/45262390/156912394-909fb8e5-958f-4ac9-934e-be8d57d20b4b.png)
ts version: 4.6.2

### ⏯ Playground Link
In playground link, it is normal

### 💻 Code
```ts
class A {
    $a(){

    }

    b(){

    }
}

class B extends A{
   //As long as there is input here, an error will be reported, and there is no type prompt
}
```
### 🙁 Actual behavior
![sp20220306_144311_603](https://user-images.githubusercontent.com/45262390/156912359-94d2bbd6-1a3c-42e0-91c0-743fa4f8e2a6.png)

### 🙂 Expected behavior
It should prompt the $a method and the b method

**Comment by a-tarasyuk** [comment]
`escapeSnippetText` adds `\` for all `$`
https://github.com/microsoft/TypeScript/blob/a4f5555e09862d442185c09cb0b0630f6c06fbd0/src/services/completions.ts#L1070-L1077

`formatting` doesn't handle escaping `\` because `\$a` (or `\$\$a`) is not a valid identifier.

https://github.com/microsoft/TypeScript/blob/a4f5555e09862d442185c09cb0b0630f6c06fbd0/src/services/completions.ts#L995-L1001

+1  related https://github.com/microsoft/TypeScript/issues/48215 issue 

Should TS Server return escaped snippet `\$0`? Or should only names be escaped `\$\$a`? I think we can call `escapeSnippetText` after formatting, just need to be sure that snippets `\$0` have to be escaped too.

/cc @andrewbranch

**Comment by andrewbranch** [comment]
Oh good find @a-tarasyuk, I think it makes sense to do the escaping after formatting. If we really needed to, we could have the formatter ignore snippet nodes (there’s a property on the attached EmitNode IIRC) but if the simple solution of swapping the order of operations works, that’s great.

**Comment by a-tarasyuk** [comment]
> If we really needed to, we could have the formatter ignore snippet nodes (there’s a property on the attached EmitNode IIRC)

Currently, the `insertText` response looks like this

```json
"\\$\\$b(): `test\\${string}` {\n    $0\n}"
```

`$0` is not escaped. And this source text breaks `formatting`. If we apply `escapeSnippetText` here 

https://github.com/microsoft/TypeScript/blob/a4f5555e09862d442185c09cb0b0630f6c06fbd0/src/services/completions.ts#L1013

```ts
return { insertText: escapeSnippetText(insertText), isSnippet, importAdder, replacementSpan };
```

the response will be changed to 

```json
"\\$\\$b(): `test\\${string}` {\n    \\$0\n}"
```

> Should TS Server return escaped snippet \$0? Or should only names be escaped \$\$a?

Not sure if escaped snippets (`\\$0`) affect VSCode (or other clients) or not.

**Comment by andrewbranch** [comment]
Oh, right. The `$0` placeholder needs to reach VS Code unescaped. So maybe the formatter does need to be aware of these snippet nodes.
