### ISSUE TITLE
tsc should give an error if "typings" in package.json is not a string

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4828]
Courtesy of [a long troubleshooting session](https://gitter.im/Microsoft/TypeScript?at=55f9e4b26f976dff036ed21c) with @kataras [on September 16, 2015](https://gitter.im/Microsoft/TypeScript?at=55f9e4b26f976dff036ed21c).

If you have `"typings"` in `package.json` as an array or something instead of a string, we will crash hard:

```
C:\Users\Makis-PC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:483
if (path.charCodeAt(0) === 47) {
^
TypeError: path.charCodeAt is not a function
at getRootLength (C:\Users\Makis-PC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:483:18)
at Object.combinePaths (C:\Users\Makis-PC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:643:13)
at loadNodeModuleFromDirectory (C:\Users\Makis-PC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:29439:73)
at loadModuleFromNodeModules (C:\Users\Makis-PC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:29462:26)
at nodeModuleNameResolver (C:\Users\Makis-PC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:29405:20)
at resolveModuleName (C:\Users\Makis-PC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:29385:28)
at C:\Users\Makis-PC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:29636:115
at Object.map (C:\Users\Makis-PC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:155:29)
at resolveModuleNamesWorker (C:\Users\Makis-PC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:29636:67)
at processImportedModules (C:\Users\Makis-PC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:30013:35)
```

**Comment by mhegazy** [comment]
PRs are welcomed.

**Comment by mhegazy** [comment]
thanks @pimterry!

**Comment by DanielRosenwasser** [comment]
I don't think this was the correct fix. We silently do the *wrong thing*. We should be giving an error message.

**Comment by vladima** [comment]
one aspect that will be added in [this PR](https://github.com/Microsoft/TypeScript/pull/5728) is ability to trace module resolution process so we can record the fact that type of `typings` is incorrect. Raising errors at this point is bit complicated because currently resolvers simply don't have this ability and it will require changes on the managed side to add it (since module resolution happens on the preprocess step where we don't have the way to report errors and propagate them back).

**Comment by mhegazy** [comment]
@vladima has another validation tool that we should publish, the tool is geared towards package authors, this is where we should report the error.
