### ISSUE TITLE
Crash on 'extract type' for deep recursive mapped type

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#48405]
Probably the same as https://github.com/microsoft/TypeScript/issues/47887

```ts
type Expand<T> = T extends any
    ? { [K in keyof T]: Expand<T[K]> }
    : never;
```

Select `{ [K in keyof T]: Expand<T[K]> }` and try to apply the extract type refactoring.

```
<semantic> Response received: getEditsForRefactor (502). Request took 2 ms. Success: false . Message: Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at getPos ([node_modules_dir]/typescript/lib/tsserver.js:146622:22)
    at assignPositionsToNodeArray ([node_modules_dir]/typescript/lib/tsserver.js:147588:46)
    at Object.visitEachChild ([node_modules_dir]/typescript/lib/tsserver.js:88571:399)
    at assignPositionsToNode ([node_modules_dir]/typescript/lib/tsserver.js:147574:30)
    at visitNode ([node_modules_dir]/typescript/lib/tsserver.js:88235:23)
    at Object.visitEachChild ([node_modules_dir]/typescript/lib/tsserver.js:88762:300)
    at assignPositionsToNode ([node_modules_dir]/typescript/lib/tsserver.js:147574:30)
    at getNonformattedText ([node_modules_dir]/typescript/lib/tsserver.js:147558:56)
    at getFormattedTextOfNode ([node_modules_dir]/typescript/lib/tsserver.js:147529:26)
    at format ([node_modules_dir]/typescript/lib/tsserver.js:147516:52)
    at computeNewText ([node_modules_dir]/typescript/lib/tsserver.js:147519:23)
    at [node_modules_dir]/typescript/lib/tsserver.js:147483:39
    at Object.mapDefined ([node_modules_dir]/typescript/lib/tsserver.js:605:30)
    at [node_modules_dir]/typescript/lib/tsserver.js:147481:42
    at Object.mapDefined ([node_modules_dir]/typescript/lib/tsserver.js:605:30)
    at Object.getTextChangesFromChanges ([node_modules_dir]/typescript/lib/tsserver.js:147467:27)
    at ChangeTracker.getChanges ([node_modules_dir]/typescript/lib/tsserver.js:147406:45)
    at Function.ChangeTracker.with ([node_modules_dir]/typescript/lib/tsserver.js:146826:32)
    at Object.getRefactorEditsToExtractType [as getEditsForAction] ([node_modules_dir]/typescript/lib/tsserver.js:159543:62)
    at Object.getEditsForRefactor ([node_modules_dir]/typescript/lib/tsserver.js:148131:41)
    at Object.getEditsForRefactor ([node_modules_dir]/typescript/lib/tsserver.js:163864:32)
    at IpcIOSession.Session.getEditsForRefactor ([node_modules_dir]/typescript/lib/tsserver.js:174980:59)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([node_modules_dir]/typescript/lib/tsserver.js:173616:61)
    at [node_modules_dir]/typescript/lib/tsserver.js:175363:88
    at IpcIOSession.Session.executeWithRequestId ([node_modules_dir]/typescript/lib/tsserver.js:175354:28)
    at IpcIOSession.Session.executeCommand ([node_modules_dir]/typescript/lib/tsserver.js:175363:33)
    at IpcIOSession.Session.onMessage ([node_modules_dir]/typescript/lib/tsserver.js:175389:35)
    at process.<anonymous> ([node_modules_dir]/typescript/lib/tsserver.js:178024:31)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by DanielRosenwasser** [comment]
Actually, here's a simpler one:

```ts
type Deep<T> = { [K in keyof T]: Deep<T[K]> };
```

Run "extract type" on `{ [K in keyof T]: Deep<T[K]> }`.
