### ISSUE TITLE
Crash in signature help in declaration list contextually typed by union

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#48542]
Repro for https://github.com/microsoft/TypeScript/issues/46898

```ts
declare const doIt: (fn?: ((x: string) => string) | ((y: number) => number)) => void;

doIt((/*$*/) => {
    return undefined;
});
```

Request signature help at `/*$*/`

```
Response received: signatureHelp (1956). Request took 2 ms. Success: false . Message: Error processing request. Cannot read properties of undefined (reading 'name')
TypeError: Cannot read properties of undefined (reading 'name')
    at chooseBetterSymbol ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:142314:22)
    at tryGetParameterInfo ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:142283:120)
    at getImmediatelyContainingArgumentOrContextualParameterInfo ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:142265:20)
    at _loop_9 ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:142438:36)
    at getContainingArgumentInfo ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:142444:31)
    at Object.getSignatureHelpItems ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:142043:32)
    at Object.getSignatureHelpItems ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:163690:37)
    at IpcIOSession.Session.getSignatureHelpItems ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:175198:62)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:173939:61)
    at [NODE_MODULES_DIR]/typescript/lib/tsserver.js:175829:88
    at IpcIOSession.Session.executeWithRequestId ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:175820:28)
    at IpcIOSession.Session.executeCommand ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:175829:33)
    at IpcIOSession.Session.onMessage ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:175855:35)
    at process.<anonymous> ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:178490:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by DanielRosenwasser** [comment]
Thank you @a-tarasyuk!
