### ISSUE TITLE
Crash in "convert to default export" when using an import(...) type

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#48544]
```ts
// @filename: element.ts
export default class /*$*/Element {}

// @filename: consumer.ts
import Element from "./element";
export type Uhoh = typeof import("./element").default;
```

Apply the "Convert default export to named export" refactoring at `/*$*/`.

```
Response received: getEditsForRefactor (1456). Request took 2 ms. Success: false . Message: Error processing request. Debug Failure. Unexpected node.
Node ImportType was unexpected.
Error: Debug Failure. Unexpected node.
Node ImportType was unexpected.
    at changeDefaultToNamedImport ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:157539:30)
    at [NODE_MODULES_DIR]/typescript/lib/tsserver.js:157494:21
    at Object.eachExportReference ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:136321:29)
    at changeImports ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:157491:39)
    at doChange ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:157444:13)
    at [NODE_MODULES_DIR]/typescript/lib/tsserver.js:157379:94
    at Function.ChangeTracker.with ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:147251:17)
    at Object.getRefactorEditsToConvertBetweenNamedAndDefaultExports [as getEditsForAction] ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:157379:62)
    at Object.getEditsForRefactor ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:148557:41)
    at Object.getEditsForRefactor ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:164314:32)
    at IpcIOSession.Session.getEditsForRefactor ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:175446:59)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:174066:61)
    at [NODE_MODULES_DIR]/typescript/lib/tsserver.js:175829:88
    at IpcIOSession.Session.executeWithRequestId ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:175820:28)
    at IpcIOSession.Session.executeCommand ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:175829:33)
    at IpcIOSession.Session.onMessage ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:175855:35)
    at process.<anonymous> ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:178490:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by DanielRosenwasser** [comment]
Thank you @a-tarasyuk!
