### ISSUE TITLE
Crash in "convert to default export" when using import(...) type and separate 'export default'

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#48591]
Apparently https://github.com/microsoft/TypeScript/issues/48544 was separate.

```ts
// @filename: element.ts
export default class /*$*/Element {}

// @filename: consumer.ts
import Element from "./element";
type Other = typeof import("./other").default;

// @filename: other.ts
class Other {}
export default Other;
```

Apply the "Convert default export to named export" refactoring at `/*$*/`.

```
Response received: getEditsForRefactor (71). Request took 26 ms. Success: false . Message: Error processing request. Debug Failure. Unexpected node.
Node ImportType was unexpected.
Error: Debug Failure. Unexpected node.
Node ImportType was unexpected.
    at changeDefaultToNamedImport (node_modules/typescript/lib/tsserver.js:157575:30)
    at node_modules/typescript/lib/tsserver.js:157530:21
    at Object.eachExportReference (node_modules/typescript/lib/tsserver.js:136347:29)
    at changeImports (node_modules/typescript/lib/tsserver.js:157527:39)
    at doChange (node_modules/typescript/lib/tsserver.js:157480:13)
    at node_modules/typescript/lib/tsserver.js:157415:94
    at Function.ChangeTracker.with (node_modules/typescript/lib/tsserver.js:147283:17)
    at Object.getRefactorEditsToConvertBetweenNamedAndDefaultExports [as getEditsForAction] (node_modules/typescript/lib/tsserver.js:157415:62)
    at Object.getEditsForRefactor (node_modules/typescript/lib/tsserver.js:148589:41)
    at Object.getEditsForRefactor (node_modules/typescript/lib/tsserver.js:164351:32)
    at IpcIOSession.Session.getEditsForRefactor (node_modules/typescript/lib/tsserver.js:175483:59)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (node_modules/typescript/lib/tsserver.js:174103:61)
    at node_modules/typescript/lib/tsserver.js:175866:88
    at IpcIOSession.Session.executeWithRequestId (node_modules/typescript/lib/tsserver.js:175857:28)
    at IpcIOSession.Session.executeCommand (node_modules/typescript/lib/tsserver.js:175866:33)
    at IpcIOSession.Session.onMessage (node_modules/typescript/lib/tsserver.js:175892:35)
    at process.<anonymous> (node_modules/typescript/lib/tsserver.js:178527:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by DanielRosenwasser** [comment]
Wrong; needed to wait for the next nightly.
