### ISSUE TITLE
noResolve no longer respected?

### ISSUE THREAD

**Issue by JKillian** [Microsoft/TypeScript#4859]
When using the language services, I find that it is trying to follow imports/requires even when `noResolve: true` is set as a compiler option. I ran a git bisect and found that this started in [this commit][0].

In the example below, `main.ts` processes `resolve.ts` using the language services. In older versions of TS, the language services would only try to open `resolve.ts` and the default library file, as expected. Since the commit mentioned above, it tries to open `resolve.ts` and then its import, `foo.ts`, which it shouldn't be doing.

*main.ts*
```typescript
/// <reference path="typings/node/node.d.ts"/>
/// <reference path="typings/ts/typescript.d.ts"/>
import ts = require("typescript");
import fs = require("fs");

const fileName = "resolve.ts";

const host: ts.LanguageServiceHost = {
	getScriptFileNames: () => [fileName],
	getScriptVersion: (name) => "1",
	getScriptSnapshot: (FILE_NAME) => {
		console.log(FILE_NAME);
		return ts.ScriptSnapshot.fromString(fs.readFileSync(FILE_NAME).toString());
	},
	getCurrentDirectory: () => process.cwd(),
	getCompilationSettings: () => ({target: ts.ScriptTarget.ES5, noResolve: true}),
	getDefaultLibFileName: (options) => ts.getDefaultLibFilePath(options)
}

const services = ts.createLanguageService(host);
```

*resolve.ts*
```typescript
import foo = require("foo");
import bar = require("bar");

foo.whatever();
bar.baz();
```

*Current Output*
```
resolve.ts
foo.ts
Error: ENOENT, no such file or directory 'foo.ts'
```

*Output from any TS version before [this commit][0]*
```
resolve.ts
/path/to/node_modules/typescript/lib/lib.d.ts
```

[0]: https://github.com/Microsoft/TypeScript/commit/f9c3adeae04dbc42ee10242d7286705f82448be7

**Comment by mhegazy** [comment]
//cc: @vladima

**Comment by frankwallis** [comment]
FYI - I'm also seeing new errors when isolatedModules and noResolve are true but the compiler host has ```resolveModuleNames``` defined.

```
1) Transpiler ES6 transpile transpiles successfully:
     TypeError: Cannot read property 'replace' of undefined
      at normalizeSlashes (node_modules/typescript/lib/typescript.js:1292:20)
      at normalizeKey (node_modules/typescript/lib/typescript.js:859:41)
      at Object.get (node_modules/typescript/lib/typescript.js:846:26)
      at Object.getSourceFile (node_modules/typescript/lib/typescript.js:35615:32)
      at resolveExternalModuleName (node_modules/typescript/lib/typescript.js:13761:53)
      at getExternalModuleMember (node_modules/typescript/lib/typescript.js:13574:32)
      at getTargetOfImportSpecifier (node_modules/typescript/lib/typescript.js:13592:20)
      at getTargetOfAliasDeclaration (node_modules/typescript/lib/typescript.js:13611:28)
      at resolveAlias (node_modules/typescript/lib/typescript.js:13627:30)
      at checkAliasSymbol (node_modules/typescript/lib/typescript.js:24806:26)
      at checkImportBinding (node_modules/typescript/lib/typescript.js:24822:13)
      at Object.forEach (node_modules/typescript/lib/typescript.js:880:30)
      at checkImportDeclaration (node_modules/typescript/lib/typescript.js:24843:32)
      at checkSourceElement (node_modules/typescript/lib/typescript.js:25094:28)
      at Object.forEach (node_modules/typescript/lib/typescript.js:880:30)
      at checkSourceFileWorker (node_modules/typescript/lib/typescript.js:25237:20)
      at checkSourceFile (node_modules/typescript/lib/typescript.js:25219:13)
      at Object.forEach (node_modules/typescript/lib/typescript.js:880:30)
      at getDiagnosticsWorker (node_modules/typescript/lib/typescript.js:25282:16)
      at getDiagnostics (node_modules/typescript/lib/typescript.js:25270:24)
      at Object.getEmitResolver (node_modules/typescript/lib/typescript.js:13052:13)
      at emitWorker (node_modules/typescript/lib/typescript.js:35608:69)
      at node_modules/typescript/lib/typescript.js:35591:66
      at runWithCancellationToken (node_modules/typescript/lib/typescript.js:35644:24)
      at Object.emit (node_modules/typescript/lib/typescript.js:35591:20)
      at Transpiler.transpile (lib/transpiler.js:32:28)
```

**Comment by vladima** [comment]
semantic of `noResolve` was not clearly defined before. Primary motivation of having it was ability to control if imported\referenced files are included in program or program contains only files that were supplied as a list of root files. Implementation wise it was done by just ignoring imports and tripleslash references. Recent updates to module resolution that have consolidated it into one place (which is `createProgram`) have changed this part - after all module names are resolved they are stored on the `SourceFile` so `resolveModuleName` can get an answer by querying the internal map. This means that if we keep ignoring imports then internal map `module name -> resolved module file` will never be populated and imports will be marked as unresolved even if imported file exists in the set of root files. In order to avoid this when `noResolve` is specified we'll still try to resolve imported module names (that is why we'll try to find `foo.ts`) but this file will not be added to the list of files in program (preserving the original meaning of `noResolve`). In language service case if host does not have `resolveModuleNames` method it is [shimmed](https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L2640-L2648) with existing functionality

**Comment by vladima** [comment]
@frankwallis can you share a repro?

**Comment by frankwallis** [comment]
I have put in a workaround [here](https://github.com/frankwallis/plugin-typescript/blob/master/lib/transpiler.js#L24) so if you comment that out and run the tests (with ```npm test```) then you should see it.

**Comment by frankwallis** [comment]
Also it wasn't happening in 1.6.0-beta.

**Comment by vladima** [comment]
ok, I can see what is going on. 
- custom resolution logic implemented via [CompilerHost.resolvedModuleNames](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L2320) supposed to return [ResolvedModule] (https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L2287)

- [resolveModuleName] (https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L39) (which is default implementation of module resolution in the compiler) returns [ResolvedModuleWithFailedLookupLocations](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L2298).

The motivation of such distinction: compiler is only interested in properties exposed by `ResolvedModule`. `resolvedModuleNames` in turn can be used by the custom resolution host and this function returns `ResolvedModule` + list of locations where resolver tried to find a file but failed. Host can monitor these locations and provide different resolution results in case of changes.

Implementation of [Compiler.resolvedModuleNames](https://github.com/frankwallis/plugin-typescript/blob/master/lib/compiler-host.js#L92) supposed to return `ResolvedModule` but on the last line it calls global `resolveModuleNames` which returns `ResolvedModuleNamesWithFailedLookupLocations` and this messes up everything. The fix is 
```ts
return ts.resolveModuleName(modName, containingFile, this._options, this).resolvedModule;
```

**Comment by mhegazy** [comment]
looks like an issue that the typescript compiler would have caught at design time :wink:

**Comment by frankwallis** [comment]
ah ok, sorry about that. 

I'm not sure if this addresses the original issue from @JKillian though. I think I have just hijacked this thread...
