### ISSUE TITLE
TSC crashes when reexporting CommonJS exports

### ISSUE THREAD

**Issue by Daninet** [microsoft/TypeScript#48655]
# Bug Report

### 🔎 Search Terms

`TypeError: Cannot read properties of undefined (reading 'flags')`

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.5.5 and 4.6.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?allowJs=true&ts=4.7.0-dev.20220408#code/PTAEAEDMEsBsFMB2BDAtvAXKW0BGwBjAe0QGcAXZRc0gOgCtSAoVIgEwFcFb4APAByIAnGqAC8oAN5NQoCkKwByXooA0TAL4BuJkxAQYCFOiykhBQiQpUatGk2ipBI0ACpQyUqBoBhK5WovSCEiVFAAIlpaYBx8YjIAmnCdPmdyKW9SPwSbL21dIA)

### 💻 Code

```ts repro
// @showEmit: true
// @showEmittedFile: src/constants.js

// @filename: lib/constants.js
module.exports = {
  str: 'x',
};

// @filename: src/constants.ts
import * as tsConstants from "../lib/constants";
export { tsConstants };
```

### 🙁 Actual behavior

TSC crashes with this error message:
```
TypeError: Cannot read properties of undefined (reading 'flags')
    at isAliasResolvedToValue (https://typescript.azureedge.net/cdn/4.6.2/monaco/dev/vs/language/typescript/tsWorker.js:70191:26)
    at isValueAliasDeclaration (https://typescript.azureedge.net/cdn/4.6.2/monaco/dev/vs/language/typescript/tsWorker.js:70166:32)
    at Object.isValueAliasDeclaration (https://typescript.azureedge.net/cdn/4.6.2/monaco/dev/vs/language/typescript/tsWorker.js:70471:27)
    at visitExportSpecifier (https://typescript.azureedge.net/cdn/4.6.2/monaco/dev/vs/language/typescript/tsWorker.js:75498:45)
    at Object.visitNodes (https://typescript.azureedge.net/cdn/4.6.2/monaco/dev/vs/language/typescript/tsWorker.js:72290:41)
    at visitNamedExports (https://typescript.azureedge.net/cdn/4.6.2/monaco/dev/vs/language/typescript/tsWorker.js:75488:28)
    at visitNamedExportBindings (https://typescript.azureedge.net/cdn/4.6.2/monaco/dev/vs/language/typescript/tsWorker.js:75495:76)
    at https://typescript.azureedge.net/cdn/4.6.2/monaco/dev/vs/language/typescript/tsWorker.js:75483:18
    at Object.visitNode (https://typescript.azureedge.net/cdn/4.6.2/monaco/dev/vs/language/typescript/tsWorker.js:72253:21)
    at visitExportDeclaration (https://typescript.azureedge.net/cdn/4.6.2/monaco/dev/vs/language/typescript/tsWorker.js:75482:32)
```

### 🙂 Expected behavior

TSC should not crash.

**Comment by mohd-akram** [comment]
I'm amazed that there's no test case for this.

**Comment by andrewbranch** [comment]
That’s odd. The bug workbench shows the crash.
