### ISSUE TITLE
Debug assertion in parseSourceFileWorker on broken code after #48493

### ISSUE THREAD

**Issue by jakebailey** [microsoft/TypeScript#48993]
# Bug Report

### 🔎 Search Terms

parseSourceFileWorker debug assert

### 🕗 Version & Regression Information

I bisected this to #48493.

### 💻 Code

```ts
// @allowJs: true
// @filename: a.js
export=    forexport=(letexport=timerexport== 0; timerexport=< N; timerexport=+= 1) 
```

### 🙁 Actual behavior

```
Error: Debug Failure. False expression.
 at parseSourceFileWorker (src\compiler\parser.ts:1119:19)
 at Object.parseSourceFile (src\compiler\parser.ts:935:28)
 at Object.createSourceFile (src\compiler\parser.ts:720:29)
```

### 🙂 Expected behavior

No crash.

**Comment by jakebailey** [comment]
Reduced:

```ts
// @allowJs: true
// @filename: a.js
( y = 1 ; 2 )
```

**Comment by DanielRosenwasser** [comment]
Posting a fuller call stack for the incremental case in case anyone runs into it

```
Debug Failure. False expression.
    at parseSourceFileWorker
    at parseSourceFile
    at createSourceFile
    at createLanguageServiceSourceFile
    at updateLanguageServiceSourceFile
    at acquireOrUpdateDocument
    at updateDocumentWithKey
    at getOrCreateSourceFileByPath
    at tryReuseStructureFromOldProgram
    at createProgram
```
