### ISSUE TITLE
Crash when find-all-references/rename finds no references

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#49217]
```ts
/**/
```

(yes, this is a blank file)

_____

```ts
const s: string = "some /**/ string";
```

_____

```ts
const obj = {}/**/;
```

_____

Request find-all-references at any `/**/`.

**Expected**: Gracefully return no results
**Actual**:

```
Debug Failure. False expression.
    at getPerProjectReferences (tsserverlibrary.js:175187:26)
    at getReferencesWorker (tsserverlibrary.js:174990:37)
    at Session.getReferences (tsserverlibrary.js:176595:34)
    at _a.<computed> (tsserverlibrary.js:175434:61)
    at <anonymous> (tsserverlibrary.js:177566:88)
    at Session.executeWithRequestId (tsserverlibrary.js:177557:28)
    at Session.executeCommand (tsserverlibrary.js:177566:33)
    at unknown (suppressed.js:6:28)
    at unknown (suppressed.js:41:45)
    at unknown (suppressed.js:137:18)
```

Similar call stack if you try to rename in this example

```ts
const s: string = "some /**/ string";
```

```
Debug Failure. False expression.
    at getPerProjectReferences (tsserverlibrary.js:175187:26)
    at getRenameLocationsWorker (tsserverlibrary.js:174964:37)
    at Session.getRenameLocations (tsserverlibrary.js:176563:33)
    at _a.<computed> (tsserverlibrary.js:175440:61)
    at <anonymous> (tsserverlibrary.js:177566:88)
    at Session.executeWithRequestId (tsserverlibrary.js:177557:28)
    at Session.executeCommand (tsserverlibrary.js:177566:33)
    at unknown (suppressed.js:6:28)
    at unknown (suppressed.js:41:45)
    at unknown (suppressed.js:39:18)
```

**Comment by DanielRosenwasser** [comment]
Likely introduced by https://github.com/microsoft/TypeScript/pull/48619

**Comment by amcasey** [comment]
I was suspicious when I didn't need to make the same fix as for 4.7 (not assuming the list had elements), but the regression test passed.  Looks like I need to add another one. 😄

**Comment by amcasey** [comment]
Well, fourslash tests for all three pass.  Time to repro manually, I guess.

**Comment by DanielRosenwasser** [comment]
IIRC, when I searched for these functions, they were only visible to me in `tsserverlibrary.js`, not `tsserver.js`. Doesn't make much sense that I can repro them, so I assume it has something to do with the session implementation.

**Comment by DanielRosenwasser** [comment]
`typescript@4.8.0-dev.20220523` gives

```
<semantic> Response received: references (9). Request took 34 ms. Success: false . Message: Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at getPerProjectReferences (.../ms-vscode.vscode-typescript-next-4.8.20220523/node_modules/typescript/lib/tsserver.js:175031:26)
    at getReferencesWorker (.../ms-vscode.vscode-typescript-next-4.8.20220523/node_modules/typescript/lib/tsserver.js:174834:37)
    at IpcIOSession.Session.getReferences (.../ms-vscode.vscode-typescript-next-4.8.20220523/node_modules/typescript/lib/tsserver.js:176439:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (.../ms-vscode.vscode-typescript-next-4.8.20220523/node_modules/typescript/lib/tsserver.js:175278:61)
    at .../ms-vscode.vscode-typescript-next-4.8.20220523/node_modules/typescript/lib/tsserver.js:177410:88
    at IpcIOSession.Session.executeWithRequestId (.../ms-vscode.vscode-typescript-next-4.8.20220523/node_modules/typescript/lib/tsserver.js:177401:28)
    at IpcIOSession.Session.executeCommand (.../ms-vscode.vscode-typescript-next-4.8.20220523/node_modules/typescript/lib/tsserver.js:177410:33)
    at IpcIOSession.Session.onMessage (.../ms-vscode.vscode-typescript-next-4.8.20220523/node_modules/typescript/lib/tsserver.js:177436:35)
    at process.<anonymous> (.../ms-vscode.vscode-typescript-next-4.8.20220523/node_modules/typescript/lib/tsserver.js:180071:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```
