### ISSUE TITLE
Compile time error 

### ISSUE THREAD

**Issue by Y0geshsharma** [microsoft/TypeScript#49240]
With latest build started receiving this error:
`Compilation error in /usr/src/app/index.ts
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferen
ceDirectives` signature. This is probably not a problem in TS itself.
    at Object.<anonymous> (/usr/src/app/index.ts:1:7)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/usr/src/app/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-19614766771346104.js:69:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-19614766771346104.js:71:20)
    at Object.nodeDevHook [as .ts] (/usr/src/app/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)`

**Comment by RyanCavanaugh** [comment]
See e.g. #47921
