### ISSUE TITLE
4.7 regression: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by vilic** [microsoft/TypeScript#49258]
# Bug Report

Encountered `RangeError: Maximum call stack size exceeded` during build.

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.6.4 and 4.7 (4.7 beta ~ 4.8 nightly)

### 💻 Code

Not sure whether a minimal repro is feasible for crashes like this.

The project is private and has 55 (1 + 54) typescript projects. The crash happens when building the root typescript project referencing the rest 54, and directly building any of the 54 typescript projects (with `--build` flag) would be fine.

Please let me know if you want to access the repository, or to have me provide a minimal repro.

**Comment by DanielRosenwasser** [comment]
What is the call stack?

**Comment by vilic** [comment]
@DanielRosenwasser call stacks of 3 crashes:

<details>
  <summary>Call stacks</summary>
  
```
/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:96964
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at inferFromTypes (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:56965:163)
    at inferFromProperties (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57381:25)
    at inferFromObjectTypes (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57369:21)
    at invokeOnce (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57103:21)
    at inferFromTypes (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57073:25)
    at inferFromTypes (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57056:25)
    at inferFromProperties (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57381:25)
    at inferFromObjectTypes (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57369:21)
    at invokeOnce (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57103:21)
    at inferFromTypes (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57073:25)
```

```
/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:96964
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at instantiateTypes (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:52418:34)
    at instantiateTypeWorker (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:52753:48)
    at instantiateTypeWithAlias (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:52739:26)
    at instantiateType (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:52725:37)
    at resolveObjectTypeMembers (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:47681:87)
    at resolveTypeReferenceMembers (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:47699:13)
    at resolveStructuredTypeMembers (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:48372:25)
    at getPropertiesOfObjectType (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:48398:24)
    at getPropertiesOfType (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:48437:17)
    at getPropertiesOfUnionOrIntersectionType (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:48416:43)
```

```
/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:96964
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at Object.next (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:45:53)
    at getUnmatchedProperty (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:56772:121)
    at typesDefinitelyUnrelated (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:56782:19)
    at inferFromObjectTypes (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57314:22)
    at invokeOnce (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57103:21)
    at inferFromTypes (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57073:25)
    at inferFromTypes (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57056:25)
    at inferFromProperties (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57381:25)
    at inferFromObjectTypes (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57369:21)
    at invokeOnce (/Users/vilicvane/Projects/digshare-packages/node_modules/typescript/lib/tsc.js:57103:21)
```
</details>

**Comment by RyanCavanaugh** [comment]
Unfortunately these stacks don't give much hint as to what the problem is.

**Comment by vilic** [comment]
The codebase in this issue is no longer maintained. Closing.
