### ISSUE TITLE
Debug Failure. Parameter symbol already has a cached type which differs from newly assigned type.

### ISSUE THREAD

**Issue by denis-sokolov** [microsoft/TypeScript#49383]
# Bug Report

### 🔎 Search Terms

Error: Debug Failure. Expected [object Object] === [object Object]. Parameter symbol already has a cached type which differs from newly assigned type

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.6.4 and 4.7.2
- This is still happening with the currently latest 4.8.0-dev.20220603

### ⏯ Playground Link

Does not reproduce [in the playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAdwE4EMAOAeAgqgcwGdEBTADylLABMTwBrMOZMAbQF0A+ACgH0AXIh4A6MekJEh+YgEpEAXi6IAbnBg15AbwC+AKDRYePLYgjpIpADboARldKIdixLvlLXO2QG49QA), only reproduces in CLI. To reproduce, run `tsc code.ts` with the code below.

### 💻 Code

```ts
function wrap<Args extends unknown[]>(_: (...args: Args) => void) {}
wrap(({ cancelable } = {}) => {});
```

### 🙁 Actual behavior

```
Error: Debug Failure. Expected [object Object] === [object Object]. Parameter symbol already has a cached type which differs from newly assigned type
    at assignParameterType (node_modules/typescript/lib/tsc.js:64861:26)
    at assignContextualParameterTypes (node_modules/typescript/lib/tsc.js:64826:21)
    at contextuallyCheckFunctionExpressionOrObjectLiteralMethod (node_modules/typescript/lib/tsc.js:65228:29)
    at checkFunctionExpressionOrObjectLiteralMethod (node_modules/typescript/lib/tsc.js:65207:13)
    at checkExpressionWorker (node_modules/typescript/lib/tsc.js:66804:28)
    at checkExpression (node_modules/typescript/lib/tsc.js:66706:38)
    at checkExpressionWithContextualType (node_modules/typescript/lib/tsc.js:66395:28)
    at inferTypeArguments (node_modules/typescript/lib/tsc.js:62905:39)
    at chooseOverload (node_modules/typescript/lib/tsc.js:63565:53)
    at resolveCall (node_modules/typescript/lib/tsc.js:63402:26)
```

### 🙂 Expected behavior

No crash.

(Ideally an error about an implicit any)

**Comment by jakebailey** [comment]
Unfortunately this bisected to #43845, which introduced the debug message, so that's no indication other than that this has to do with parameter fixing (a la #43835).

This same error had been showing up a lot in fuzzer runs; I think @weswigham said to ping if this sort of thing continued?

**Comment by albertodvc** [comment]
I'm still having this issue with v4.8.3.

**Comment by jakebailey** [comment]
@albertodvc If you have a case that is still broken, I'd certainly appreciate a new issue with the code snippet.

**Comment by TrySpace** [comment]
I 'fixed' this by updating yarn, I was running an old version (1.x). Then I deleted `node_modules` and `yarn.lock` and reinstalled. 

Not really a fix though, because I think typescript should give some indication of which code is giving the error.

**Comment by gaitho** [comment]
In my case, I had a dev-dependency of @types/node that was not matching the version of node ( ^20 vs ^16 ). Downgradeing @node/types to 16 resolved it for me
