### ISSUE TITLE
Assertion failure on "convert to default export" on interface in module augmentation

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#49421]
Related to #47821.

```ts
// bar.ts
export {};
```

```ts
// foo.ts
import "./bar.js";
declare module "./bar.js" {
    export interface ComponentCustomOptions {
    }
}
```

```
<semantic> Response received: getEditsForRefactor (51). Request took 40 ms. Success: false . Message: Error processing request. Debug Failure. Unexpected parent kind 258 SyntaxKind: InterfaceDeclaration
Error: Debug Failure. Unexpected parent kind 258 SyntaxKind: InterfaceDeclaration
    at changeNamedToDefaultImport (UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:159481:30)
    at UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:159403:21
    at Object.eachExportReference (UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:138053:29)
    at changeImports (UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:159397:39)
    at doChange (UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:159350:13)
    at UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:159285:94
    at Function.ChangeTracker.with (UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:149136:17)
    at Object.getRefactorEditsToConvertBetweenNamedAndDefaultExports [as getEditsForAction] (UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:159285:62)
    at Object.getEditsForRefactor (UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:150445:41)
    at Object.getEditsForRefactor (UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:166246:32)
    at IpcIOSession.Session.getEditsForRefactor (UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:177697:59)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:176170:61)
    at UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:178080:88
    at IpcIOSession.Session.executeWithRequestId (UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:178071:28)
    at IpcIOSession.Session.executeCommand (UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:178080:33)
    at IpcIOSession.Session.onMessage (UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:178106:35)
    at process.<anonymous> (UserHome/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220606/node_modules/typescript/lib/tsserver.js:180741:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by RyanCavanaugh** [comment]
Closing language service bugs related to the 6.0 implementation. For more information, see #62827
