### ISSUE TITLE
RangeError: Maximum call stack size exceeded when seeding Prisma database

### ISSUE THREAD

**Issue by GitMarijn** [microsoft/TypeScript#49620]
# Bug Report

### 🔎 Search Terms

RangeError: Maximum call stack size exceeded Prisma TypeScript
RangeError: Maximum call stack size exceeded Prisma seeding

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about exceeding stack size

### 💻 Code

```ts
 "db:seed": "NODE_ENV=test NODE_PATH='.' dotenv -e .env.local -- ts-node-dev db/seeds/seed.ts",
    "db:reset-and-seed": "NODE_ENV=test NODE_PATH='.' dotenv -e .env.local -- prisma migrate reset --force --skip-generate",
    "db:migrate": "NODE_ENV=test NODE_PATH='.' dotenv -e .env.local prisma migrate dev",
```

### 🙁 Actual behavior

This occurs on my Macbook m1 pro. Weird thing is it doesn't occur on machines running Linux.
Tried downgrading TypeScript, node and ts-node. Unfortunately this didn't help.

```
/node_modules/typescript/lib/typescript.js:68629
                        invokeOnce(source, target, inferFromObjectTypes);
                        ^
RangeError: Maximum call stack size exceeded
    at inferFromTypes (/node_modules/typescript/lib/typescript.js:68629:25)
    at inferFromTypes (/node_modules/typescript/lib/typescript.js:68449:25)
    at inferFromTypes (/node_modules/typescript/lib/typescript.js:68449:25)
    at inferFromProperties (/node_modules/typescript/lib/typescript.js:68992:25)
    at inferFromObjectTypes (/node_modules/typescript/lib/typescript.js:68980:21)
    at invokeOnce (/node_modules/typescript/lib/typescript.js:68661:21)
    at inferFromTypes (node_modules/typescript/lib/typescript.js:68629:25)
    at inferFromTypes (/node_modules/typescript/lib/typescript.js:68449:25)
    at inferFromProperties (/node_modules/typescript/lib/typescript.js:68992:25)
    at inferFromObjectTypes (/node_modules/typescript/lib/typescript.js:68980:21)
```

### 🙂 Expected behavior

Running the `db:seed` command without errors.

**Comment by MartinJohns** [comment]
Sounds like an issue with Prisma. There's an open issue in the Prisma repository: https://github.com/prisma/prisma/issues/13938

**Comment by Josh-Cena** [comment]
> There's an open issue in the Prisma repository: [prisma/prisma#13938](https://github.com/prisma/prisma/issues/13938)

Except it's filed by the same person 😄
