### ISSUE TITLE
RangeError: Maximum call stack size exceeded at getAwaitedTypeNoAlias

### ISSUE THREAD

**Issue by jakebailey** [microsoft/TypeScript#49723]
# Bug Report

Moved from https://github.com/microsoft/TypeScript/issues/47208#issuecomment-1014128087

### 🔎 Search Terms

RangeError Maximum call stack size exceeded getAwaitedTypeNoAlias

### 🕗 Version & Regression Information

- This is the behavior in every version I tried.

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKlC8UCMUA+UAKAnA9gWwEsBnCAHhgD41YBtAXQG4AoJiADzBy2CgDMBXAHYBjYARyCoeEADEho8YIAUYAIZZVeAFywAlFADeTKFGESiPVQHdVBYBAAmCKNds81GvEwC+QA)

### 💻 Code

```ts
type T = 1 | Promise<T> | T[];

export function myFunction(param: T) {
  const awaited = await param
}
```

### 🙁 Actual behavior

```
     RangeError: Maximum call stack size exceeded
      at getAwaitedTypeNoAlias (src\compiler\checker.ts:36632:70)
      at mapper (src\compiler\checker.ts:36628:71)
      at mapType (src\compiler\checker.ts:23959:95)
      at getAwaitedTypeNoAlias (src\compiler\checker.ts:36629:60)
      at getAwaitedTypeNoAlias (src\compiler\checker.ts:36678:37)
      at mapper (src\compiler\checker.ts:36628:71)
      at mapType (src\compiler\checker.ts:23959:95)
      at getAwaitedTypeNoAlias (src\compiler\checker.ts:36629:60)
      at getAwaitedTypeNoAlias (src\compiler\checker.ts:36678:37)
      at mapper (src\compiler\checker.ts:36628:71)
      at mapType (src\compiler\checker.ts:23959:95)
      at getAwaitedTypeNoAlias (src\compiler\checker.ts:36629:60)
      at getAwaitedTypeNoAlias (src\compiler\checker.ts:36678:37)
      at mapper (src\compiler\checker.ts:36628:71)
      at mapType (src\compiler\checker.ts:23959:95)
      at getAwaitedTypeNoAlias (src\compiler\checker.ts:36629:60)
      at getAwaitedTypeNoAlias (src\compiler\checker.ts:36678:37)
```

### 🙂 Expected behavior

No crash.

**Comment by jakebailey** [comment]
Actually, this is a dupe of #49646 and should be fixed by #49677.

**Comment by jakebailey** [comment]
It's just circular; there's an error message for types like these that can't be resolved (see the linked PR).

**Comment by fatcerberus** [comment]
That's what I thought; I guess I'm just confused because I thought when TS produced an error for a circular type it subsequently treated the type as `any`, which should be enough to prevent the crash on `await`... I guess the bug is that this case isn't being detected as circular

**Comment by Andarist** [comment]
> I guess the bug is that this case isn't being detected as circular

Yep, notice how I've fixed this by just adding the circularity tracking~ here:
https://github.com/microsoft/TypeScript/pull/49677/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R36628
