### ISSUE TITLE
Typescript getCodeFixes failure: Error processing request. Debug Failure. False expression.

### ISSUE THREAD

**Issue by kevindqc** [microsoft/TypeScript#49812]
Issue Type: <b>Bug</b>

Was writing this line of code:
`.pipe(takeUntil(this._destroy$))`

Actual: Then I put my cursor on the squiggly line for takeUntil to import it, it tells me there are no code actions available.

Expected: It should show me the option to import `takeUntil` from `rxjs/operators`

I have tried with VSCode 1.68.1, with VSCode 1.68.1 with all extensions disabled, and a brand new installation of Insiders. All fail to suggest me the import.

This stacktrace is from Insiders:
```
Info 1218 [10:21:48.856] response:
    {"seq":0,"type":"response","command":"getCodeFixes","request_seq":14,"success":false,"message":"Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.setTextPos (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:12103:22)
    at Object.skipToEndOf (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:145431:25)
    at processChildNodes (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:146926:47)
    at c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:146843:21
    at visitNodes (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:30474:24)
    at Object.forEachChild (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:30665:21)
    at processNode (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:146840:20)
    at processChildNode (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:146911:21)
    at c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:146841:21
    at visitNode (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:30469:24)
    at Object.forEachChild (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:30628:21)
    at processNode (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:146840:20)
    at formatSpanWorker (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:146640:17)
    at c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:146603:140
    at Object.getFormattingScanner (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:145230:23)
    at Object.formatNodeGivenIndentation (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:146603:31)
    at getFormattedTextOfNode (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:149034:45)
    at format (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:149005:52)
    at computeNewText (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:149008:23)
    at c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:148972:39
    at Object.mapDefined (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:605:30)
    at c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:148970:42
    at Object.mapDefined (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:605:30)
    at Object.getTextChangesFromChanges (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:148956:27)
    at ChangeTracker.getChanges (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:148895:45)
    at Function.ChangeTracker.with (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:148315:32)
    at Object.getCodeActions (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:154025:68)
    at c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:149562:77
    at Object.flatMap (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:508:25)
    at Object.getFixes (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:149562:23)
    at c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:164962:35
    at Object.flatMap (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:508:25)
    at Object.getCodeFixesAtPosition (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:164960:23)
    at IpcIOSession.Session.getCodeFixes (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:176859:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:175242:61)
    at c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:177172:88
    at IpcIOSession.Session.executeWithRequestId (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:177163:28)
    at IpcIOSession.Session.executeCommand (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:177172:33)
    at IpcIOSession.Session.onMessage (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:177198:35)
    at process.<anonymous> (c:\\Users\\Kevin.Doyon\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:179833:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)"}
```

VS Code version: Code - Insiders 1.69.0-insider (0b3574dcef8f35fec4ee4f83dc958c1f16ef6fce, 2022-07-01T05:17:04.343Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (3.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30496796
vsclangdf:30492506

```

</details>

**Comment by moczix** [comment]
i have also the same issue, Ubuntu 1.68.1

**Comment by moczix** [comment]
i repro code is like : 
`  public test() {
    this.appService.test()
    .pipe(takeUntil(this._destroy$))
    .subscribe(() => {

    });
  }`

but if you changed to

`  public test() {
    takeUntil
    this.appService.test()
    .pipe(takeUntil(this._destroy$))
    .subscribe(() => {

    });
  }`

and tried to import first takeUntil, it will show import info and it works. So maybe te functions in `pipe` is readed wrong?

**Comment by moczix** [comment]
also, if you have code like this:
public test() {
this.appService.test()
.pipe(takeUntil)
.subscribe(() => {

});
}

and you click on takeUntil it will show up import. So it has to do something with functions in pipe

**Comment by moczix** [comment]
it has to do something with this: https://github.com/microsoft/TypeScript/commit/e73d7556688977405f0397665d7634673f88bd26
when i commented the code block:

                    if (!ts.rangeOverlapsWithStartEnd(originalRange, nodes.pos, nodes.end)) {
                        if (nodes.end < originalRange.pos) {
                            formattingScanner.skipToEndOf(nodes);
                        }
                        return;
                    }

it started to work again

**Comment by axmad386** [comment]
I think I have similar problem. I use neovim with `coc-tsserver`. I just install package called `objection`. Just write this and the error is thrown
```js
import {Model} from "objection";

class User extends Model {
// type anything here and errors will thrown
}
```

The funny thing is this issue only occured on typescript version v4.6.0 and above. I tested in v4.5.0 and the errors is gone. Sorry for my english
