### ISSUE TITLE
"Fix all" on "add `extends constraint" creates overlapping ranges, fails

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#50048]
Found from Vue Core at https://github.com/vuejs/core/blob/a95554d35c65e5bfd0bf9d1c5b908ae789345a6d/packages/runtime-core/src/vnode.ts#L166 (https://github.com/microsoft/TypeScript/issues/50028)

```ts
export interface RendererElement {
    [key: string]: any
}

export interface VNode<HostElement extends RendererElement> {
    target: HostElement | null;
}

export function cloneVNode<U>(vnode: VNode<U>): VNode<U> {
    const cloned: VNode<RendererElement> = {
        target: vnode.target,
    }
    return cloned;
}
```

Perform the ` `"Add `extends` constraint to all type parameters" `` quick fix.

```
Error: Debug Failure. False expression: Changes overlap
Verbose Debug Information: {"pos":359,"end":360} and {"pos":359,"end":360}
    at _loop_10 (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:150980:34)
    at c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:150986:25
    at Object.mapDefined (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:622:30)
    at Object.getTextChangesFromChanges (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:150974:27)
    at ChangeTracker.getChanges (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:150913:45)
    at Function.ChangeTracker.with (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:150333:32)
    at Object.getAllCodeActions (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:155392:91)
    at Object.getAllFixes (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:151585:81)
    at Object.getCombinedCodeFix (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:167119:31)
    at IpcIOSession.Session.getCombinedCodeFix (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:179359:56)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:177725:61)
    at c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:179652:96
    at IpcIOSession.Session.executeWithRequestId (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:179643:28)
    at IpcIOSession.Session.executeCommand (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:179652:41)
    at IpcIOSession.Session.onMessage (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:179680:35)
    at process.<anonymous> (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220723/node_modules/typescript/lib/tsserver.js:183846:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by weswigham** [comment]
cc @a-tarasyuk who may be slightly interested

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
