### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by andrewbober** [microsoft/TypeScript#50129]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.7.3

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. False expression.
    at _loop_3 (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:171897:34)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:171905:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:173574:26)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:173848:97
    at Object.flatMap (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:508:25)
    at ProjectService.applyChangesInOpenFiles (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:173848:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:174983:46)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177172:88
    at IpcIOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177163:28)
    at IpcIOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177172:33)
    at IpcIOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177198:35)
    at process.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:179833:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:14:10.636Z)
OS version: Linux x64 5.14.0-1045-oem
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|31.09GB (0.34GB free)|
|Process Argv|. --crash-reporter-id 8d6c64c5-fafd-487f-8ae6-6f3dd88411df|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|14.1.0
nestjs|ash|1.4.2
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
vscode-jest-runner|fir|0.4.48
codetogether|gen|2022.2.1
go|gol|0.35.1
jenkinsfile-support|ivo|1.1.0
dotenv|mik|1.0.1
HTMLHint|mka|0.10.0
vscode-docker|ms-|1.22.1
hexeditor|ms-|1.9.8
vscode-typescript-tslint-plugin|ms-|1.3.4
angular-console|nrw|17.19.0
addDocComments|ste|0.0.8
vscode-icons|vsc|11.13.0
codetour|vsl|0.0.58
wallaby-vscode|Wal|1.0.345

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdf:30486550
c4g48928:30535728

```

</details>

**Comment by tcampbPPU** [comment]
I am facing the same issue when also running Ubuntu but I am on TS version `4.7.4`

**Comment by tcampbPPU** [comment]
It also tells me I am not running the latest version, when its configured to to 4.7.4
![image](https://user-images.githubusercontent.com/25044744/182457818-5aa3a2fd-9cf7-4de3-a068-f4dae8ed14a7.png)
![image](https://user-images.githubusercontent.com/25044744/182457865-d038c3c1-0c38-4b49-838e-772403b6f086.png)

**Comment by DanielRosenwasser** [comment]
We believe this that the issue was fixed by https://github.com/microsoft/TypeScript/pull/50042 and others have reported it as fixed (https://github.com/microsoft/TypeScript/issues/49986).

[If you use the nightly TypeScript extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next), do you still see the same behavior?
