### ISSUE TITLE
No Project error during getOutliningSpans

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#50131]
Present in 4.7.4. and `main`.

1. `git clone https://github.com/facebook/docusaurus`
2. `cd docusaurus`
3. `git reset --hard 9150c7aefc7bd871f449145bee5bc70767d09eca`
4. `cd ..`
5. `npm install @typescript/server-replay`
6. Download replay.txt
7. `npx tsreplay ./docusaurus path/to/replay.txt path/to/tsserver.js`

<details>
<summary>replay.txt</summary>

```json
{"rootDirPlaceholder":"@PROJECT_ROOT@","serverArgs":["--disableAutomaticTypingAcquisition"]}
{"seq":1,"type":"request","command":"configure","arguments":{"preferences":{"includePackageJsonAutoImports":"off"},"watchOptions":{"excludeDirectories":["**/node_modules"]}}}
{"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"@PROJECT_ROOT@/packages/docusaurus-module-type-aliases/src/index.d.ts","projectRootPath":"@PROJECT_ROOT@"}]}}
{"seq":3,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":["@PROJECT_ROOT@/packages/docusaurus-module-type-aliases/src/index.d.ts"],"openFiles":[]}}
{"seq":4,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"@PROJECT_ROOT@/packages/docusaurus-plugin-client-redirects/src/__tests__/redirectValidation.test.ts","projectRootPath":"@PROJECT_ROOT@"}]}}
{"seq":5,"type":"request","command":"getOutliningSpans","arguments":{"file":"@PROJECT_ROOT@/packages/docusaurus-plugin-client-redirects/src/__tests__/redirectValidation.test.ts"}}
```

</details>

```
Error: No Project.
    at Object.ThrowNoProject (typescript/built/local/tsserver.js:167629:23)
    at IOSession.Session.getFileAndLanguageServiceForSyntacticOperation (typescript/built/local/tsserver.js:176275:42)
    at IOSession.Session.getOutliningSpans (typescript/built/local/tsserver.js:176288:31)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (typescript/built/local/tsserver.js:175074:61)
    at typescript/built/local/tsserver.js:177179:88
    at IOSession.Session.executeWithRequestId (typescript/built/local/tsserver.js:177170:28)
    at IOSession.Session.executeCommand (typescript/built/local/tsserver.js:177179:33)
    at IOSession.Session.onMessage (typescript/built/local/tsserver.js:177205:35)
```

**Comment by amcasey** [comment]
Here's the unreduced repro, which is more realistic, in that it doesn't open and close files without performing operations on them. 

[fullreplay.txt](https://github.com/microsoft/TypeScript/files/9237436/fullreplay.txt)

**Comment by amcasey** [comment]
Hmm, you probably want to be at 9150c7aefc7bd871f449145bee5bc70767d09eca in docusaurus.  I'll have to figure out if there's a git one-liner for that.

**Comment by amcasey** [comment]
This repro from [Vite](https://github.com/vitejs/vite/commit/364aae13f0826169e8b1c5db41ac6b5bb2756958) is very likely a dup:

<details>
<summary>replay.vite.txt</summary>

```json
{"rootDirPlaceholder":"@PROJECT_ROOT@","serverArgs":["--disableAutomaticTypingAcquisition"]}
{"seq":1,"type":"request","command":"configure","arguments":{"preferences":{"includePackageJsonAutoImports":"off"},"watchOptions":{"excludeDirectories":["**/node_modules"]}}}
{"seq":4772,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"@PROJECT_ROOT@/playground/test-utils.ts","projectRootPath":"@PROJECT_ROOT@"}]}}
{"seq":4811,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":["@PROJECT_ROOT@/playground/test-utils.ts"],"openFiles":[]}}
{"seq":4811,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"@PROJECT_ROOT@/playground/tsconfig-json/__tests__/tsconfig-json.spec.ts","projectRootPath":"@PROJECT_ROOT@"}]}}
{"seq":4812,"type":"request","command":"getOutliningSpans","arguments":{"file":"@PROJECT_ROOT@/playground/tsconfig-json/__tests__/tsconfig-json.spec.ts"}}
```

</details>
