### ISSUE TITLE
No Project error during references request

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#50144]
Present in 4.7.4. and `main`.

1. `git clone https://github.com/mui/material-ui`
2. `cd material-ui`
3. `git reset --hard 89617ef683d2bcd2c870e9c1bd58ad4d55247fd5`
4. `cd ..`
5. `npm install @typescript/server-replay`
6. Download replay.txt
7. `npx tsreplay ./material-ui path/to/replay.txt path/to/tsserver.js`

<details>
<summary>replay.txt</summary>

```json
{"rootDirPlaceholder":"@PROJECT_ROOT@","serverArgs":["--disableAutomaticTypingAcquisition"]}
{"seq":1,"type":"request","command":"configure","arguments":{"preferences":{"includePackageJsonAutoImports":"off"},"watchOptions":{"excludeDirectories":["**/node_modules"]}}}
{"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"@PROJECT_ROOT@/examples/gatsby/src/components/ProTip.js","projectRootPath":"@PROJECT_ROOT@"}]}}
{"seq":3,"type":"request","command":"references","arguments":{"file":"@PROJECT_ROOT@/examples/gatsby/src/components/ProTip.js","line":2,"offset":19}}
```

</details>

```
Error: No Project.
    at Object.ThrowNoProject (built/local/tsserver.js:167629:23)
    at IOSession.Session.getProjects (built/local/tsserver.js:176152:42)
    at IOSession.Session.getReferences (built/local/tsserver.js:176207:37)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (built/local/tsserver.js:175048:61)
    at built/local/tsserver.js:177179:88
    at IOSession.Session.executeWithRequestId (built/local/tsserver.js:177170:28)
    at IOSession.Session.executeCommand (built/local/tsserver.js:177179:33)
    at IOSession.Session.onMessage (built/local/tsserver.js:177205:35)
```

**Comment by amcasey** [comment]
On opening the example file, we walk up to the root tsconfig.json, which doesn't obviously exclude the examples file.  Even if it did, it should be in an inferred project?

**Comment by amcasey** [comment]
Fascinating: it _is_ in the root project but the root project's LS is disabled (found more than 20MB of JS?).  Unclear whether there'd be any UI indicator for this state (VS Code might detect it and fall back to partial mode?).

**Comment by amcasey** [comment]
Presumably, it's indicated by this dialog
![image](https://user-images.githubusercontent.com/10508071/182463350-e1c2c731-c16b-4e60-9abf-5a838585ce46.png)

**Comment by amcasey** [comment]
This is an unhelpful error message, but things are otherwise working as expected.
