### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by MiladSadinam** [microsoft/TypeScript#50195]
# Bug Report

### 🔎 Search Terms

Maximum call stack size exceeded, 

### 🕗 Version & Regression Information
I tried it on the following versions, all with the same error:

4.7.4
3.9.7
typescript@next

Please keep and fill in the line that best applies:
- This is a crash

### 💻 Code

The error only occurs for the "whole" project. Compiling single files do not crash. Thus, I have removed some part of the project, still ensuring that the error still occurs. I hope it is ok that I upload part of our repo. I had a hard time reducing the problem to smaller code.

[reproduction.zip](https://github.com/microsoft/TypeScript/files/9268935/reproduction.zip)

To reproduce it, go into the folder `reproduction` and execute `tsc --project tsconfig.json`.

### 🙁 Actual behavior

The typescript compiler crashes with the error `Maximum call stack size exceeded`. 

Some Background information:
We use a generator to generate typescript code. It produces multiple large files (~20K lines) and some heavily interconnected objects. This was ok until now. We changed the objects to use generic types, and from there the problem started.

I don't think the "structure" is the main problem, because some smaller generated files compile fine. It is just the largest of the files which is creating the problem. When I delete that one file, it compiles again.

### 🙂 Expected behavior

Compiler shows a specific error instead of crashing.

**Comment by MartinJohns** [comment]
You're advised to host the reproduction example on GitHub in a repository instead of uploading a sketchy zip file.

**Comment by MiladSadinam** [comment]
You can now find the code also in https://github.com/MiladSadinam/Maximum-call-stack-size-exceeded

This is the problematic file (though the whole project is needed, so the crash occurs):
https://github.com/MiladSadinam/Maximum-call-stack-size-exceeded/blob/main/src/shared/api/scheduling-api/scheduling-api.service.ag.ts

**Comment by MiladSadinam** [comment]
We would appreciate that - if possible - this issue get prioritized as it is blocking for us.

**Comment by axefrog** [comment]
Also experiencing this. It only happens for incremental compilation. The initial build always works. TypeScript version is 4.9.4. My project is big and complex and I'm having trouble figuring out what's causing the problem.

Stack trace:

```
[10:11:45 am] File change detected. Starting incremental compilation...

D:\salix\modelling-tool\node_modules\typescript\lib\tsc.js:99606
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at typeToTypeNodeWorker (D:\salix\modelling-tool\node_modules\typescript\lib\tsc.js:44213:42)
    at typeToTypeNodeHelper (D:\salix\modelling-tool\node_modules\typescript\lib\tsc.js:44209:32)
    at mapToTypeNodes (D:\salix\modelling-tool\node_modules\typescript\lib\tsc.js:44969:40)
    at typeReferenceToTypeNode (D:\salix\modelling-tool\node_modules\typescript\lib\tsc.js:44747:49)
    at typeToTypeNodeWorker (D:\salix\modelling-tool\node_modules\typescript\lib\tsc.js:44361:95)
    at typeToTypeNodeHelper (D:\salix\modelling-tool\node_modules\typescript\lib\tsc.js:44209:32)
    at serializeReturnTypeForSignature (D:\salix\modelling-tool\node_modules\typescript\lib\tsc.js:45666:24)      
    at signatureToSignatureDeclarationHelper (D:\salix\modelling-tool\node_modules\typescript\lib\tsc.js:45050:42)
    at createTypeNodesFromResolvedType (D:\salix\modelling-tool\node_modules\typescript\lib\tsc.js:44811:43)      
    at createTypeNodeFromObjectType (D:\salix\modelling-tool\node_modules\typescript\lib\tsc.js:44665:35)

Node.js v17.4.0
```

**Comment by alireza12prom** [comment]
Hello everyone,

I hope this message finds you well. I'm currently encountering an issue while attempting to build multiple TypeScript projects using Docker Compose. Each project has its own Dockerfile, and building them independently works without any problems. However, the problem comes in when I try to build them collectively using the `docker-compose build` command.

To provide more context:

- I have three TypeScript projects, each with its own Dockerfile.
- Building each project independently is successful.
- The issue arises when using docker-compose build to build all projects together.

Error Message:
```
13.69 undefined:23
13.69 if(_err0) {
13.69 ^
13.69
13.69 RangeError: Maximum call stack size exceeded
13.69     at eval (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
13.69     at /node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:152:17
13.69     at /node_modules/enhanced-resolve/lib/Resolver.js:518:24
13.69     at eval (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
13.69     at /node_modules/enhanced-resolve/lib/Resolver.js:518:24
13.69     at eval (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
13.69     at /node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:90:10
13.69     at /node_modules/enhanced-resolve/lib/Resolver.js:518:24
13.69     at eval (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
13.69     at /node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:152:17
13.69
13.69 Node.js v21.6.1
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
```

**Comment by RyanCavanaugh** [comment]
The only linked repro here is enormous and doesn't seem to crash in 7.0+, plus encounters config errors in 6.0. Other similar call stacks are likely a different issue. Please log new issues with self-contained and isolated repros so we can investigate those. Thanks
