### ISSUE TITLE
Parameter decorator doesn't work when applying to symbol methods

### ISSUE THREAD

**Issue by CMCDragonkai** [microsoft/TypeScript#50305]
# Bug Report

I find that I cannot use parameter decorators on symbol methods. In `ts-node` it results in `target[key]` being `undefined`, while on the playground it just results in a error involving the JS, as in the code generated is incorrect.

### 🔎 Search Terms

* symbol
* parameter decorator

### 🕗 Version & Regression Information

* 4.6.4 to 4.7.4

### ⏯ Playground Link

* https://www.typescriptlang.org/play?noImplicitAny=false&target=99&ts=4.7.4#code/GYVwdgxgLglg9mABBBUCmAPKAKKBDAJwHM0oAuRAeQCMArNaAGkQGs0BPCgZygJjCKIAPoi7sAttTgAbZvwAmmCmBCS0BAJSIA3gChEyBFxloAdNLhFchElADabdgF0NAbl0BfXbpRgeoxABeRABlCSlpbAByPGoIKLdvCGk8Li5EAGEdfUQABxBqaRgIRDsuJ2wAAV90LDzuXn4iLT0DA19jaTMLKyj5BDQE9wMvLx8jKGQgxDA0AHdM7ESIMoqYuKGgA

### 💻 Code

```ts
function context(target: Object, key: string | symbol, index: number) {
  console.log(target[key]);
}

const s = Symbol('abc');

class C {
  public [s](@context p: string) {
    console.log('done');
  }
}

const c = new C();
c[s]('abc');
```

### 🙁 Actual behavior

On my `ts-node` on `4.6.4` it shows `undefined` for `target[key]`, but on playground the code it shows as:

```
[ERR]: "Executed JavaScript Failed:" 
[ERR]: _a is not defined 
```

However upon trying again, I'm getting:

```
[nix-shell:~/Projects/Polykey]$ npm run ts-node -- ./src/test-dec2.ts 

> polykey@1.0.0 ts-node
> ts-node "./src/test-dec2.ts"

undefined
/home/cmcdragonkai/Projects/Polykey/src/test-dec2.ts:14
c[s]('abc');
    ^
TypeError: c[s] is not a function
    at Object.<anonymous> (/home/cmcdragonkai/Projects/Polykey/src/test-dec2.ts:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/home/cmcdragonkai/Projects/Polykey/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/home/cmcdragonkai/Projects/Polykey/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at phase4 (/home/cmcdragonkai/Projects/Polykey/node_modules/ts-node/src/bin.ts:649:14)
    at bootstrap (/home/cmcdragonkai/Projects/Polykey/node_modules/ts-node/src/bin.ts:95:10)
```

### 🙂 Expected behavior

I would have thought that parameter decorators work fine with symbol methods.

**Comment by MartinJohns** [comment]
Just FYI, playground and ts-node will behave the same when configured the same.

**Comment by CMCDragonkai** [comment]
I would have thought so as well, but since both are failing atm, I left it as a above.

**Comment by alokeutpal** [comment]
Hi> # Bug Report
> 
> I find that I cannot use parameter decorators on symbol methods. In `ts-node` it results in `target[key]` being `undefined`, while on the playground it just results in a error involving the JS, as in the code generated is incorrect.
> 
> ### 🔎 Search Terms
> 
> * symbol
> * parameter decorator
> 
> ### 🕗 Version & Regression Information
> 
> * 4.6.4 to 4.7.4
> 
> ### ⏯ Playground Link
> 
> * https://www.typescriptlang.org/play?noImplicitAny=false&target=99&ts=4.7.4#code/GYVwdgxgLglg9mABBBUCmAPKAKKBDAJwHM0oAuRAeQCMArNaAGkQGs0BPCgZygJjCKIAPoi7sAttTgAbZvwAmmCmBCS0BAJSIA3gChEyBFxloAdNLhFchElADabdgF0NAbl0BfXbpRgeoxABeRABlCSlpbAByPGoIKLdvCGk8Li5EAGEdfUQABxBqaRgIRDsuJ2wAAV90LDzuXn4iLT0DA19jaTMLKyj5BDQE9wMvLx8jKGQgxDA0AHdM7ESIMoqYuKGgA
> 
> ### 💻 Code
> 
> ```ts
> function context(target: Object, key: string | symbol, index: number) {
>   console.log(target[key]);
> }
> 
> const s = Symbol('abc');
> 
> class C {
>   public [s](@context p: string) {
>     console.log('done');
>   }
> }
> 
> const c = new C();
> c[s]('abc');
> ```
> 
> ### 🙁 Actual behavior
> 
> On my `ts-node` on `4.6.4` it shows `undefined` for `target[key]`, but on playground the code it shows as:
> 
> ```
> [ERR]: "Executed JavaScript Failed:" 
> [ERR]: _a is not defined 
> ```
> 
> However upon trying again, I'm getting:
> 
> ```
> [nix-shell:~/Projects/Polykey]$ npm run ts-node -- ./src/test-dec2.ts 
> 
> > polykey@1.0.0 ts-node
> > ts-node "./src/test-dec2.ts"
> 
> undefined
> /home/cmcdragonkai/Projects/Polykey/src/test-dec2.ts:14
> c[s]('abc');
>     ^
> TypeError: c[s] is not a function
>     at Object.<anonymous> (/home/cmcdragonkai/Projects/Polykey/src/test-dec2.ts:14:5)
>     at Module._compile (node:internal/modules/cjs/loader:1105:14)
>     at Module.m._compile (/home/cmcdragonkai/Projects/Polykey/node_modules/ts-node/src/index.ts:1618:23)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
>     at Object.require.extensions.<computed> [as .ts] (/home/cmcdragonkai/Projects/Polykey/node_modules/ts-node/src/index.ts:1621:12)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
>     at phase4 (/home/cmcdragonkai/Projects/Polykey/node_modules/ts-node/src/bin.ts:649:14)
>     at bootstrap (/home/cmcdragonkai/Projects/Polykey/node_modules/ts-node/src/bin.ts:95:10)
> ```
> 
> ### 🙂 Expected behavior
> 
> I would have thought that parameter decorators work fine with symbol methods.
