### ISSUE TITLE
"experimentalDecorators": true doesn't work

### ISSUE THREAD

**Issue by khteh** [microsoft/TypeScript#50316]
# Bug Report

### 🕗 Version & Regression Information
"typescript": "^4.7.4"
Node: v18.7.0
NPM: 8.15.0

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

I have the following `EntityBase` class:
```
import { PrimaryGeneratedColumn, Column } from "typeorm"
/*
* Use Data Mapper pattern: https://typeorm.io/active-record-data-mapper
*/
export abstract class EntityBase {
    @PrimaryGeneratedColumn()
    public id: number
    @Column()
    public created: Date
    @Column()
    public modified: Date
}
```
And I would like to create a many-to-many relationships table between `Student` and `Teacher` table. However, when I define the following classes in 2 `.ts` files:
```
import { Entity, Column, ManyToMany, JoinTable } from "typeorm"
import { EntityBase } from "./EntityBase"
import { Teacher } from "./Teacher"
@Entity()
export class Student extends EntityBase {
    @Column()
    public firstName: string

    @Column()
    public lastName: string

    @Column({ unique: true })
    public email: string

    @Column()
    public isSuspended: boolean

    @ManyToMany(() => Teacher)
    @JoinTable()
    public teacher: Teacher[]

    constructor(first: string, last: string, email: string, isSuspended?: boolean) {
        super();
        this.firstName = first;
        this.lastName = last;
        this.email = email;
        this.isSuspended = isSuspended ?? false;
        this.teacher = [];
    }
}
```
```
import { Entity, Column, JoinTable, ManyToMany } from "typeorm"
import { EntityBase } from "./EntityBase"
import { Student } from "./Student"
@Entity()
export class Teacher extends EntityBase {
    @Column()
    public firstName: string

    @Column()
    public lastName: string

    @Column({ unique: true })
    public email: string

    @ManyToMany(() => Student)
    @JoinTable()
    public student: Student[]

    constructor(first: string, last: string, email: string) {
        super();
        this.firstName = first;
        this.lastName = last;
        this.email = email;
        this.student = [];
    }
}
```
It result in the following error:
```
build/index.d.ts → build/index.d.ts...
[!] (plugin dts) Error: Syntax not yet supported

  2 | import { EntityBase } from "./EntityBase"
  3 | import { Student } from "./Student"
> 4 | declare @Entity()
    | ^^^^^^^
  5 | class Teacher extends EntityBase {
  6 |     @Column()
  7 |     public firstName: string
Domain/Entities/Teacher.ts
Error: Syntax not yet supported

  2 | import { EntityBase } from "./EntityBase"
  3 | import { Student } from "./Student"
> 4 | declare @Entity()
    | ^^^^^^^
  5 | class Teacher extends EntityBase {
  6 |     @Column()
  7 |     public firstName: string
    at Transformer.convertStatement (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1248:19)
    at new Transformer (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1177:18)
    at convert (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1168:25)
    at Object.transform (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1484:31)
    at transformFile (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1588:50)
    at Object.transform (/usr/src/Node.JSRestAPI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1601:24)
    at /usr/src/Node.JSRestAPI/node_modules/rollup/dist/shared/rollup.js:22840:40

npm ERR! Lifecycle script `rollup` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: core@1.0.0 
npm ERR!   at location: /usr/src/Node.JSRestAPI/src/core 
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: core@1.0.0 
npm ERR!   at location: /usr/src/Node.JSRestAPI/src/core 
```
I have set the `"experimentalDecorators": true` in tsconfig.json but to no avail
How to define the many-to-many relationship table between these 2 classes? Thanks.
https://github.com/typeorm/typeorm/issues/9285

**Comment by fatcerberus** [comment]
> Error: Syntax not yet supported

This isn’t a TypeScript error.  It looks like whatever third-party tool you’re using to process your TS code doesn’t support the decorator syntax.  You’ll need to figure out which tool that is; this is the wrong place to report the issue.

**Comment by khteh** [comment]
[rollup-plugin-dts](https://github.com/Swatinem/rollup-plugin-dts) error! Switching over to https://github.com/wessberg/rollup-plugin-ts resolves the problem.
