### ISSUE TITLE
"used before its declaration" errors not reported when variable/enum/class is used as decorator parameter on class member

### ISSUE THREAD

**Issue by zivarah** [microsoft/TypeScript#50349]
# Bug Report

### 🔎 Search Terms
decorator
enum
used before its declaration
TS2448, TS2449, TS2450
isolatedModules
preserveConstEnums

### 🕗 Version & Regression Information

- This is a crash: In the transpiled JavaScript, not in tsc itself.
- This is the behavior in every version I tried (3.1 through 4.7), and I reviewed the FAQ for entries about decorators (https://github.com/Microsoft/TypeScript/wiki/FAQ#decorators)

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?target=1&ssl=18&ssc=2&pln=3&pc=1#code/PTAEAEFMA8AdIE4EsC2kB2AXAhgGwCKQDGA9gtpmQM4BcomCArpALABQ7AZo+kZkiXSg0mABYkAJoVLlKCABQA3PMzpUGSdAHMAlHWzoAnqADe7AJAJImRgiHydoALwA+UwF8A3O3ft2qWDJMU2FrcSliMgoyUHdQTgQSFFAAIgA6YBFw6Si5FO8ONhBwLMkc2TJ5AFlDAFF0RhQ05VxmAEZHEFAAYTIrPlxjK0CETCpQesbQAHIayZRp0EYqSAlQACNITjJIUCQx0AliXGxZAXsAFQBlACYAFgBWAAYddhgR4KITqnGa7u-xmY2KAQRBShEZNEFHMGk0Wu1OmAAHIkUCIRIIUDDIKrdig0CwRjrXBIIjxEgkBx0RQkJBrIH43xsJlvWGgGFTBmg+GQNrOVI8topAA0PiAA)

### 💻 Code

```ts repro
// @experimentalDecorators: true

function methodDecorator(value: string): any {
	return () => {};
}

//@methodDecorator(MyEnum.value1) // Correctly reports Enum 'MyEnum' used before its declaration (TS2450)
export class MyClass {
    @methodDecorator(MyEnum.value1) // No error reported
    public foo(): void {
    }
}

enum MyEnum {
    value1 = "value1",
}
```

### 🙁 Actual behavior

- No TS2450 "Enum 'MyEnum' used before its declaration" is reported.
- At runtime, this code crashes during the initial script execution:
```
C:\repos\TS2450_decorator_repro\program.js:19
        methodDecorator(MyEnum.value1) // No error reported
                               ^

TypeError: Cannot read properties of undefined (reading 'value1')
    at C:\repos\TS2450_decorator_repro\program.js:19:32
    at Object.<anonymous> (C:\repos\TS2450_decorator_repro\program.js:22:2)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

### 🙂 Expected behavior

TS2450 (and other similar errors like 2448 for Block-scoped variables or 2449 for classes) should be correctly reported.

**Comment by zivarah** [comment]
This issue caught us off guard when we switched to using isolatedModules. This causes const enums to be preserved as if preserveConstEnums was set, which meant that a value that used to compile in stopped doing so, and no error was raised during build due to this issue.

In the code example given in the issue above, using 4.7:

Before isolatedModules:
```js
var MyClass = /** @class */ (function () {
    function MyClass() {
    }
    MyClass.prototype.foo = function () {
    };
    __decorate([
        methodDecorator("value1" /* MyEnum.value1 */)
    ], MyClass.prototype, "foo");
    return MyClass;
}());
exports.MyClass = MyClass;

```

After isolatedModules:
```js
var MyClass = /** @class */ (function () {
    function MyClass() {
    }
    MyClass.prototype.foo = function () {
    };
    __decorate([
        methodDecorator(MyEnum.value1)
    ], MyClass.prototype, "foo");
    return MyClass;
}());
exports.MyClass = MyClass;
var MyEnum;
(function (MyEnum) {
    MyEnum["value1"] = "value1";
})(MyEnum || (MyEnum = {}));

```
