### ISSUE TITLE
tsc does not report error for invalid tsconfig.json

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#50496]
# Bug Report

### 🕗 Version & Regression Information

- It's a crash

### 💻 Code

> cat ./tsconfig.json

```
{
        "a": 1 + 1
}
```

> tsc -p ./tsconfig.json

hangs up for at least 1 minute

```
typescript@4.8.2\node_modules\typescript\lib\tsc.js:98394
                throw e;
                ^

TypeError: Cannot read properties of undefined (reading 'get')
    at getTypeAliasInstantiation (typescript\lib\tsc.js:50492:54)
    at createMarkerType (typescript\lib\tsc.js:56473:17)
    at _loop_23 (typescript\lib\tsc.js:56438:45)
    at getVariancesWorker (typescript\lib\tsc.js:56459:21)
    at getVariances (typescript\lib\tsc.js:56416:17)
    at inferFromObjectTypes (typescript\lib\tsc.js:58153:96)
    at invokeOnce (typescript\lib\tsc.js:57916:21)
    at inferFromTypes (typescript\lib\tsc.js:57874:25)
    at inferTypes (typescript\lib\tsc.js:57721:13)
    at inferTypeArguments (typescript\lib\tsc.js:63789:25)

Node.js v18.7.0
```

### 🙁 Actual behavior

Crashes

### 🙂 Expected behavior

Report an error message

**Comment by MartinJohns** [comment]
?

**Comment by Jack-Works** [comment]
Never mind, a bad report
