### ISSUE TITLE
Implement interface is not working  when the interface has some params

### ISSUE THREAD

**Issue by pdecarcer** [microsoft/TypeScript#50570]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: Versión: 1.70.2 (Universal)
- OS Version:Mac os Monterrey 12.5.1

Issue Type: Bug

(Typescript)
I have an interface I defined call IFinancingProvider, and I am creating a class called MockRemoteInstance for testing purposes. For some reason the UI refuses to implement interface with the usual stubs. If I remove some params it works.

Always when I use `Partial<T>` doenst work

Here is code for the interface:

```
type SimulateCreditParams = {
  downPayment: string;
};
type Credit = {
  downPayment: string;
};

export interface IFinancingProviderRemoteData {
  simulateCredit(params: SimulateCreditParams): Promise<boolean>;
  requestCredit(): Promise<void>;
  getCreditProducts(): Promise<void>;
  getCreditStatus(): Promise<void>;
  updateCredit(params: Credit): Promise<Credit>;
}
```

And here for the class:

```
import { IFinancingProviderRemoteData } from '@core/interfaces/IFinancingProviderRemoteData';
import { AxiosInstance } from 'axios';
import { inject } from 'tsyringe';

export class MockRemoteInstance implements IFinancingProviderRemoteData {
  constructor(
    @inject('CrediNissanRemoteInstance') private instance: AxiosInstance,
  ) {}
}
```

It not offer me the implementation.

<img width="720" alt="Screen Shot 2022-08-30 at 18 25 22" src="https://user-images.githubusercontent.com/298465/187554408-64056f88-1382-421d-abaa-d9aea638c954.png">

**Comment by mjbvz** [comment]
Thanks. Here's the full error text:

```
Error: Debug Failure. False expression.
    at consumeTokenAndAdvanceScanner (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149367:30)
    at processChildNode (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149274:25)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149220:21
    at visitNode (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:30901:24)
    at Object.forEachChild (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:31008:21)
    at processNode (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149219:20)
    at processChildNode (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149291:21)
    at processChildNodes (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149346:48)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149222:21
    at visitNodes (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:30906:24)
    at Object.forEachChild (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:31127:24)
    at processNode (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149219:20)
    at processChildNode (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149291:21)
    at processChildNodes (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149346:48)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149222:21
    at visitNodes (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:30906:24)
    at Object.forEachChild (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:31118:21)
    at processNode (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149219:20)
    at processChildNode (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149291:21)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149220:21
    at visitNode (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:30901:24)
    at Object.forEachChild (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:30996:21)
    at processNode (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149219:20)
    at processChildNode (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149291:21)
    at processChildNodes (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149346:48)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149222:21
    at visitNodes (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:30906:24)
    at Object.forEachChild (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:31056:21)
    at processNode (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:149219:20)
    at formatSpanWorker (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:148998:17)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:148960:140
    at Object.getFormattingScanner (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:147587:23)
    at Object.formatNodeGivenIndentation (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:148960:31)
    at getFormattedTextOfNode (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:151433:45)
    at format (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:151404:52)
    at computeNewText (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:151407:23)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:151371:39
    at Object.mapDefined (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:622:30)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:151369:42
    at Object.mapDefined (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:622:30)
    at Object.getTextChangesFromChanges (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:151355:27)
    at ChangeTracker.getChanges (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:151294:45)
    at Function.ChangeTracker.with (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:150714:32)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:154566:68
    at Object.mapDefined (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:622:30)
    at Object.getCodeActions (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:154565:27)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:151961:77
    at Object.flatMap (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:525:25)
    at Object.getFixes (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:151961:23)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:167597:35
    at Object.flatMap (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:525:25)
    at Object.getCodeFixesAtPosition (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:167595:23)
    at IpcIOSession.Session.getCodeFixes (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:179827:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:178207:61)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:180140:96
    at IpcIOSession.Session.executeWithRequestId (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:180131:28)
    at IpcIOSession.Session.executeCommand (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:180140:41)
    at IpcIOSession.Session.onMessage (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:180168:35)
    at process.<anonymous> (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:184334:31)
    at process.emit (node:events:526:28)
    at process.emit (/Users/matb/projects/vscode/node_modules/source-map-support/source-map-support.js:395:21)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
	at TypeScriptServerError.create (/Users/matb/projects/vscode/extensions/typescript-language-features/out/tsServer/serverError.js:20:16)
	at ProcessBasedTsServer.dispatchResponse (/Users/matb/projects/vscode/extensions/typescript-language-features/out/tsServer/server.js:133:66)
	at ProcessBasedTsServer.dispatchMessage (/Users/matb/projects/vscode/extensions/typescript-language-features/out/tsServer/server.js:69:30)
	at ChildProcess.<anonymous> (/Users/matb/projects/vscode/extensions/typescript-language-features/out/tsServer/server.js:41:18)
	at ChildProcess.emit (node:events:526:28)
	at emit (node:internal/child_process:938:14)
	at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by kamweti** [comment]
Commenting this block in `src/compiler/checker.ts` seems to temporarily fix it, 
``` ....
                    if (cachedResult) {
                        if (cachedResult.truncating) {
                            context.truncating = true;
                        }
                        context.approximateLength += cachedResult.addedLength;
                        return deepCloneOrReuseNode(cachedResult) as TypeNode as T;
                    }
```

seems issue loosely related to caching known types

**Comment by RyanCavanaugh** [comment]
Closing language service bugs related to the 6.0 implementation. For more information, see #62827
