### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Page-** [microsoft/TypeScript#50591]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.6.4 and 4.7.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEoQI4FcIGczIDeAsAFACQARgPYAmAngFzJwj1kC+ZZC1I+yAB7NCyANpYswWs3xRQAcwC6zEFgC2laMg7IAvEQ4BubqQAUUTM3TY8YAJT6AfETLlBEqbSUBqHydI3Xn4CSWl9ZEsMADoaBmjedXU+AH0QOHUIAK5SIA)

### 💻 Code

```ts
interface Request {
	body: any
}

const x: { [uuid: string]: number } = {};

(req: Request) => {
	x[uuid]++;

	const uuid = req.body.common_name;
}
```

### 🙁 Actual behavior

RangeError: Maximum call stack size exceeded
    at resolveNameHelper (C:\ts-test\node_modules\typescript\lib\tsc.js:41378:21)
    at resolveName (C:\ts-test\node_modules\typescript\lib\tsc.js:41165:20)
    at resolveEntityName (C:\ts-test\node_modules\typescript\lib\tsc.js:42315:42)
    at tryGetElementAccessExpressionName (C:\ts-test\node_modules\typescript\lib\tsc.js:58553:30)
    at getAccessedPropertyName (C:\ts-test\node_modules\typescript\lib\tsc.js:58533:24)
    at isMatchingReference (C:\ts-test\node_modules\typescript\lib\tsc.js:58516:78)
    at getTypeAtFlowAssignment (C:\ts-test\node_modules\typescript\lib\tsc.js:59549:21)
    at getTypeAtFlowNode (C:\ts-test\node_modules\typescript\lib\tsc.js:59476:32)
    at getFlowTypeOfReference (C:\ts-test\node_modules\typescript\lib\tsc.js:59440:51)
    at getFlowTypeOfAccessExpression (C:\ts-test\node_modules\typescript\lib\tsc.js:63184:28)  

### 🙂 Expected behavior

The error message:
```
Block-scoped variable 'uuid' used before its declaration.ts(2448)
```

**Comment by q42jaap** [comment]
I found this too:
```
function fn(propsStrings: Record<string, unknown>) {
  for (const key of Object.keys(propsStrings)) {
    const value = propsStrings[value];
  }
}
```
Seems to be the same issue?

**Comment by jakebailey** [comment]
Yes, that appears to be the same thing.
