### ISSUE TITLE
Maximum call stack size exceeded when type references a recursive type

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#5080]
Another one of these :)

```typescript
declare module Test {
    export type Container<T> = T | {
        [i: string]: Container<T>;
    };

    export type IStringContainer = Container<string>;
}
```

Error in tsc version 1.6.2:
```
C:\Users\jogol\Desktop\Test>tsc TestFile.d.ts
C:\Users\jogol\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:29825
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at createObjectType (C:\Users\jogol\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:11093:34)
    at instantiateAnonymousType (C:\Users\jogol\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13789:26)
    at instantiateType (C:\Users\jogol\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13810:25)
    at instantiateList (C:\Users\jogol\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13666:33)
    at instantiateType (C:\Users\jogol\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13819:41)
    at instantiateAnonymousType (C:\Users\jogol\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13797:42)
    at instantiateType (C:\Users\jogol\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13810:25)
    at instantiateList (C:\Users\jogol\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13666:33)
    at instantiateType (C:\Users\jogol\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13819:41)
    at instantiateAnonymousType (C:\Users\jogol\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13797:42)
```

Seems to be a duplicate of #4443.

**Comment by RyanCavanaugh** [comment]
Confirmed repro in master branch

**Comment by mhegazy** [comment]
@ahejlsberg wanna take a look?

**Comment by JoshuaKGoldberg** [comment]
Found a one line fix, am currently wrestling with the jake tests to make a test for it.

In checker.ts > `instantiateAnonymousType`, the `mapper.instantiations[type.id] = result` line should be before the `stringIndexType` and `numberIndexType` calls to `instantiateType`.

**Comment by ahejlsberg** [comment]
@JoshuaKGoldberg Thanks for looking at this. That does indeed fix the issue for your example, but unfortunately it still blows up if you modify it slightly:

```typescript
declare module Test {
    export type Container<T> = T | {
        [i: string]: Container<T>[];  // Added [] here
    };

    export type IStringContainer = Container<string>;
}
```

The root problem is that we're too eager in our instantiation of members of instantiated anonymous types (yes, bit of a mouthful). I'll be putting up a PR that properly defers instantiation of members shortly. It handles both your example and the example above.

BTW, regarding tests, the workflow is:

* Add tests somewhere in `ts/tests/cases/conformance` or `ts/test/cases/compiler`.
* Run `jake runtests`.
* Compare `ts/tests/baseline/reference` folder to `ts/tests/baseline/local` to verify new test results.
* Once you're satisfied with tests, run `jake baseline-accept`.
* Commit the changes.

**Comment by JoshuaKGoldberg** [comment]
@ahejlsberg Ok, thanks for the fix & clarification!

**Comment by mhegazy** [comment]
@JoshuaKGoldberg the fix should be in `typescript@next` tonight.
