### ISSUE TITLE
Assert in addIndirectUser in FAR in microsoft/playwright

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#50867]
[microsoft/playwright](https://github.com/microsoft/playwright) the file being passed to `addIndirectUser` is [here](https://github.com/microsoft/playwright/blob/ee83694372e2cd8a03131c042189a5359504f1b6/packages/playwright-core/src/utilsBundle.ts).  The assert is that `isAvailableThroughGlobal` is false, which it's not because `debug` is exported globally [here](https://unpkg.com/@types/debug@4.1.7/index.d.ts).

_Originally posted by @amcasey in https://github.com/microsoft/TypeScript/issues/50835#issuecomment-1251698702_

**Comment by amcasey** [comment]
## [microsoft/playwright](https://github.com/microsoft/playwright)

<details>
<summary>:warning: Note that typescript-4.8.3 also had errors :warning:</summary>

```
Req #6501 - references
    at addIndirectUser (/typescript-4.8.3/lib/tsserver.js:138032:26)
    at handleDirectImports (/typescript-4.8.3/lib/tsserver.js:137990:37)
    at getImportersForExport (/typescript-4.8.3/lib/tsserver.js:137912:13)
    at State.importTracker (/typescript-4.8.3/lib/tsserver.js:137888:26)
    at State.getImportSearches (/typescript-4.8.3/lib/tsserver.js:139444:33)
    at searchForImportsOfExport (/typescript-4.8.3/lib/tsserver.js:139493:32)
    at getImportOrExportReferences (/typescript-4.8.3/lib/tsserver.js:139986:21)
    at getReferencesAtLocation (/typescript-4.8.3/lib/tsserver.js:139906:17)
    at getReferencesInContainer (/typescript-4.8.3/lib/tsserver.js:139840:21)
    at getReferencesInContainerOrFiles (/typescript-4.8.3/lib/tsserver.js:139339:21)
    at getReferencedSymbolsForSymbol (/typescript-4.8.3/lib/tsserver.js:139330:21)
    at getReferencedSymbolsForModuleIfDeclaredBySourceFile (/typescript-4.8.3/lib/tsserver.js:139147:67)
    at Object.getReferencedSymbolsForNode (/typescript-4.8.3/lib/tsserver.js:139073:40)
    at Object.findReferencedSymbols (/typescript-4.8.3/lib/tsserver.js:138661:42)
    at Object.findReferences (/typescript-4.8.3/lib/tsserver.js:167440:41)
    at /typescript-4.8.3/lib/tsserver.js:177595:53
    at searchPosition (/typescript-4.8.3/lib/tsserver.js:177792:38)
    at getPerProjectReferences (/typescript-4.8.3/lib/tsserver.js:177760:42)
    at getReferencesWorker (/typescript-4.8.3/lib/tsserver.js:177592:37)
    at IOSession.Session.getReferences (/typescript-4.8.3/lib/tsserver.js:179195:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/typescript-4.8.3/lib/tsserver.js:178032:61)
    at /typescript-4.8.3/lib/tsserver.js:180166:96
    at IOSession.Session.executeWithRequestId (/typescript-4.8.3/lib/tsserver.js:180157:28)
    at IOSession.Session.executeCommand (/typescript-4.8.3/lib/tsserver.js:180166:41)
    at IOSession.Session.onMessage (/typescript-4.8.3/lib/tsserver.js:180194:35)
    at Interface.<anonymous> (/typescript-4.8.3/lib/tsserver.js:184330:31)
```

</details>



```
Req #6501 - references
    at addIndirectUser (/typescript-4.9.0-dev.20220918/lib/tsserver.js:139048:26)
    at handleDirectImports (/typescript-4.9.0-dev.20220918/lib/tsserver.js:139006:37)
    at getImportersForExport (/typescript-4.9.0-dev.20220918/lib/tsserver.js:138928:13)
    at State.importTracker (/typescript-4.9.0-dev.20220918/lib/tsserver.js:138904:26)
    at State.getImportSearches (/typescript-4.9.0-dev.20220918/lib/tsserver.js:140462:33)
    at searchForImportsOfExport (/typescript-4.9.0-dev.20220918/lib/tsserver.js:140511:32)
    at getImportOrExportReferences (/typescript-4.9.0-dev.20220918/lib/tsserver.js:141004:21)
    at getReferencesAtLocation (/typescript-4.9.0-dev.20220918/lib/tsserver.js:140924:17)
    at getReferencesInContainer (/typescript-4.9.0-dev.20220918/lib/tsserver.js:140858:21)
    at getReferencesInContainerOrFiles (/typescript-4.9.0-dev.20220918/lib/tsserver.js:140357:21)
    at getReferencedSymbolsForSymbol (/typescript-4.9.0-dev.20220918/lib/tsserver.js:140348:21)
    at getReferencedSymbolsForModuleIfDeclaredBySourceFile (/typescript-4.9.0-dev.20220918/lib/tsserver.js:140165:67)
    at Object.getReferencedSymbolsForNode (/typescript-4.9.0-dev.20220918/lib/tsserver.js:140091:40)
    at Object.findReferencedSymbols (/typescript-4.9.0-dev.20220918/lib/tsserver.js:139679:42)
    at Object.findReferences (/typescript-4.9.0-dev.20220918/lib/tsserver.js:168560:41)
    at /typescript-4.9.0-dev.20220918/lib/tsserver.js:178715:53
    at searchPosition (/typescript-4.9.0-dev.20220918/lib/tsserver.js:178912:38)
    at getPerProjectReferences (/typescript-4.9.0-dev.20220918/lib/tsserver.js:178880:42)
    at getReferencesWorker (/typescript-4.9.0-dev.20220918/lib/tsserver.js:178712:37)
    at IOSession.Session.getReferences (/typescript-4.9.0-dev.20220918/lib/tsserver.js:180315:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/typescript-4.9.0-dev.20220918/lib/tsserver.js:179152:61)
    at /typescript-4.9.0-dev.20220918/lib/tsserver.js:181286:96
    at IOSession.Session.executeWithRequestId (/typescript-4.9.0-dev.20220918/lib/tsserver.js:181277:28)
    at IOSession.Session.executeCommand (/typescript-4.9.0-dev.20220918/lib/tsserver.js:181286:41)
    at IOSession.Session.onMessage (/typescript-4.9.0-dev.20220918/lib/tsserver.js:181314:35)
    at Interface.<anonymous> (/typescript-4.9.0-dev.20220918/lib/tsserver.js:185436:31)
```


<details>
<summary><h3>Last few requests</h3></summary>

```json
{"seq":6498,"type":"request","command":"completionInfo","arguments":{"file":"@PROJECT_ROOT@/packages/playwright-core/src/utilsBundle.ts","line":6,"offset":32,"includeExternalModuleExports":false,"includeInsertTextCompletions":true,"triggerKind":2,"triggerCharacter":" "}}
{"seq":6499,"type":"request","command":"completionInfo","arguments":{"file":"@PROJECT_ROOT@/packages/playwright-core/src/utilsBundle.ts","line":20,"offset":7,"includeExternalModuleExports":false,"includeInsertTextCompletions":true,"triggerKind":2,"triggerCharacter":" "}}
{"seq":6500,"type":"request","command":"definitionAndBoundSpan","arguments":{"file":"@PROJECT_ROOT@/packages/playwright-core/src/utilsBundle.ts","line":21,"offset":66}}
{"seq":6501,"type":"request","command":"references","arguments":{"file":"@PROJECT_ROOT@/packages/playwright-core/src/utilsBundle.ts","line":21,"offset":66}}

```

</details>

<details>
<summary><h3>Repro Steps</h3></summary>
<ol>
<li><code>git clone https://github.com/microsoft/playwright</code></li>
<li>In dir <code>playwright</code>, run <code>git reset --hard ee83694372e2cd8a03131c042189a5359504f1b6</code></li>
<li><details><summary>Install packages</summary><ol>
  <li>In dir <code>playwright/examples/components-vue</code>, run <code>npm ci --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/examples/github-api</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/examples/mock-battery</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/examples/mock-filesystem</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/examples/svgomg</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/examples/todomvc</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright</code>, run <code>npm ci --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/html-reporter</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright-chromium</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright-core/bundles/utils</code>, run <code>npm ci --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright-core/bundles/zip</code>, run <code>npm ci --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright-core</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright-ct-react</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright-ct-solid</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright-ct-svelte</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright-ct-vue</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright-ct-vue2</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright-firefox</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright-test/bundles/babel</code>, run <code>npm ci --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright-test/bundles/expect</code>, run <code>npm ci --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright-test/bundles/utils</code>, run <code>npm ci --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright-test</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright-webkit</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/playwright</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/recorder</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/packages/trace-viewer</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/tests/components/ct-react-vite</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/tests/components/ct-react</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/tests/components/ct-solid</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/tests/components/ct-svelte-vite</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/tests/components/ct-svelte</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/tests/components/ct-vue-cli</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/tests/components/ct-vue-vite</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/tests/components/ct-vue2-cli</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/tests/playwright-test/stable-test-runner</code>, run <code>npm ci --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>playwright/utils/flakiness-dashboard</code>, run <code>npm ci --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
</ol></details>
<li>Download <code>RepoResults1/microsoft.playwright.replay.txt</code> from the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=134550&view=artifacts&type=publishedArtifacts">artifact folder</a></li>
<li><code>npm install --no-save @typescript/server-replay</code></li>
<li><code>npx tsreplay ./playwright ./microsoft.playwright.replay.txt path/to/tsserver.js</code></li>
</ol>
</details>
