### ISSUE TITLE
Assert in organizeImports in babel/babel

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#50866]
[babel/babel](https://github.com/babel/babel) - the assert is that [this](https://github.com/babel/babel/blob/aad7eb743d1354a5475f9d43226bfedc5f149e4b/packages/babel-generator/test/fixtures/flow/declare-exports/output.js#L25) `declare` is missing `__pos` and `__end`.

_Originally posted by @amcasey in https://github.com/microsoft/TypeScript/issues/50835#issuecomment-1251553909_

**Comment by amcasey** [comment]
## [babel/babel](https://github.com/babel/babel)

<details>
<summary>:warning: Note that typescript-4.8.3 also had errors :warning:</summary>

```
Req #292 - organizeImports
    at getPos (/typescript-4.8.3/lib/tsserver.js:150536:22)
    at assignPositionsToNode (/typescript-4.8.3/lib/tsserver.js:151494:44)
    at visitArrayWorker (/typescript-4.8.3/lib/tsserver.js:90473:48)
    at Object.visitNodes (/typescript-4.8.3/lib/tsserver.js:90436:23)
    at assignPositionsToNodeArray (/typescript-4.8.3/lib/tsserver.js:151499:30)
    at Object.visitEachChild (/typescript-4.8.3/lib/tsserver.js:90985:62)
    at assignPositionsToNode (/typescript-4.8.3/lib/tsserver.js:151491:30)
    at getNonformattedText (/typescript-4.8.3/lib/tsserver.js:151472:56)
    at getFormattedTextOfNode (/typescript-4.8.3/lib/tsserver.js:151443:26)
    at format (/typescript-4.8.3/lib/tsserver.js:151430:52)
    at /typescript-4.8.3/lib/tsserver.js:151432:78
    at computeNewText (/typescript-4.8.3/lib/tsserver.js:151432:36)
    at /typescript-4.8.3/lib/tsserver.js:151397:39
    at Object.mapDefined (/typescript-4.8.3/lib/tsserver.js:622:30)
    at /typescript-4.8.3/lib/tsserver.js:151395:42
    at Object.mapDefined (/typescript-4.8.3/lib/tsserver.js:622:30)
    at Object.getTextChangesFromChanges (/typescript-4.8.3/lib/tsserver.js:151381:27)
    at ChangeTracker.getChanges (/typescript-4.8.3/lib/tsserver.js:151320:45)
    at Object.organizeImports (/typescript-4.8.3/lib/tsserver.js:143322:34)
    at Object.organizeImports (/typescript-4.8.3/lib/tsserver.js:167640:39)
    at IOSession.Session.organizeImports (/typescript-4.8.3/lib/tsserver.js:179805:60)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/typescript-4.8.3/lib/tsserver.js:178260:61)
    at /typescript-4.8.3/lib/tsserver.js:180166:96
    at IOSession.Session.executeWithRequestId (/typescript-4.8.3/lib/tsserver.js:180157:28)
    at IOSession.Session.executeCommand (/typescript-4.8.3/lib/tsserver.js:180166:41)
    at IOSession.Session.onMessage (/typescript-4.8.3/lib/tsserver.js:180194:35)
    at Interface.<anonymous> (/typescript-4.8.3/lib/tsserver.js:184330:31)
```

</details>



```
Req #292 - organizeImports
    at getPos (/typescript-4.9.0-dev.20220918/lib/tsserver.js:151596:22)
    at assignPositionsToNode (/typescript-4.9.0-dev.20220918/lib/tsserver.js:152554:44)
    at visitArrayWorker (/typescript-4.9.0-dev.20220918/lib/tsserver.js:91123:48)
    at Object.visitNodes (/typescript-4.9.0-dev.20220918/lib/tsserver.js:91087:23)
    at assignPositionsToNodeArray (/typescript-4.9.0-dev.20220918/lib/tsserver.js:152559:30)
    at visitEachChildOfExportDeclaration (/typescript-4.9.0-dev.20220918/lib/tsserver.js:91627:66)
    at Object.visitEachChild (/typescript-4.9.0-dev.20220918/lib/tsserver.js:91267:42)
    at assignPositionsToNode (/typescript-4.9.0-dev.20220918/lib/tsserver.js:152551:30)
    at getNonformattedText (/typescript-4.9.0-dev.20220918/lib/tsserver.js:152532:56)
    at getFormattedTextOfNode (/typescript-4.9.0-dev.20220918/lib/tsserver.js:152503:26)
    at format (/typescript-4.9.0-dev.20220918/lib/tsserver.js:152490:52)
    at /typescript-4.9.0-dev.20220918/lib/tsserver.js:152492:78
    at computeNewText (/typescript-4.9.0-dev.20220918/lib/tsserver.js:152492:36)
    at /typescript-4.9.0-dev.20220918/lib/tsserver.js:152457:39
    at Object.mapDefined (/typescript-4.9.0-dev.20220918/lib/tsserver.js:621:30)
    at /typescript-4.9.0-dev.20220918/lib/tsserver.js:152455:42
    at Object.mapDefined (/typescript-4.9.0-dev.20220918/lib/tsserver.js:621:30)
    at Object.getTextChangesFromChanges (/typescript-4.9.0-dev.20220918/lib/tsserver.js:152441:27)
    at ChangeTracker.getChanges (/typescript-4.9.0-dev.20220918/lib/tsserver.js:152380:45)
    at Object.organizeImports (/typescript-4.9.0-dev.20220918/lib/tsserver.js:144344:34)
    at Object.organizeImports (/typescript-4.9.0-dev.20220918/lib/tsserver.js:168760:39)
    at IOSession.Session.organizeImports (/typescript-4.9.0-dev.20220918/lib/tsserver.js:180925:60)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/typescript-4.9.0-dev.20220918/lib/tsserver.js:179380:61)
    at /typescript-4.9.0-dev.20220918/lib/tsserver.js:181286:96
    at IOSession.Session.executeWithRequestId (/typescript-4.9.0-dev.20220918/lib/tsserver.js:181277:28)
    at IOSession.Session.executeCommand (/typescript-4.9.0-dev.20220918/lib/tsserver.js:181286:41)
    at IOSession.Session.onMessage (/typescript-4.9.0-dev.20220918/lib/tsserver.js:181314:35)
    at Interface.<anonymous> (/typescript-4.9.0-dev.20220918/lib/tsserver.js:185436:31)
```


<details>
<summary><h3>Last few requests</h3></summary>

```json
{"seq":289,"type":"request","command":"organizeImports","arguments":{"scope":{"type":"file","args":{"file":"@PROJECT_ROOT@/packages/babel-generator/test/fixtures/edgecase/unary-op/input.js"}},"skipDestructiveCodeActions":false}}
{"seq":290,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":["@PROJECT_ROOT@/packages/babel-generator/test/fixtures/compact/while/output.js"],"openFiles":[]}}
{"seq":291,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"@PROJECT_ROOT@/packages/babel-generator/test/fixtures/flow/declare-exports/output.js","projectRootPath":"@PROJECT_ROOT@"}]}}
{"seq":292,"type":"request","command":"organizeImports","arguments":{"scope":{"type":"file","args":{"file":"@PROJECT_ROOT@/packages/babel-generator/test/fixtures/flow/declare-exports/output.js"}},"skipDestructiveCodeActions":true}}

```

</details>

<details>
<summary><h3>Repro Steps</h3></summary>
<ol>
<li><code>git clone https://github.com/babel/babel</code></li>
<li>In dir <code>babel</code>, run <code>git reset --hard aad7eb743d1354a5475f9d43226bfedc5f149e4b</code></li>
<li>Download <code>RepoResults1/babel.babel.replay.txt</code> from the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=134550&view=artifacts&type=publishedArtifacts">artifact folder</a></li>
<li><code>npm install --no-save @typescript/server-replay</code></li>
<li><code>npx tsreplay ./babel ./babel.babel.replay.txt path/to/tsserver.js</code></li>
</ol>
</details>
