### ISSUE TITLE
StackOverflow during completion in TryGhost/Ghost

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#50928]
[TryGhost/Ghost](https://github.com/TryGhost/Ghost)

```
typeToString (e:\ts_gh\src\compiler\checker.ts:4859)
reportNonexistentProperty (e:\ts_gh\src\compiler\checker.ts:29577)
checkPropertyAccessExpressionOrQualifiedName (e:\ts_gh\src\compiler\checker.ts:29360)
checkPropertyAccessExpression (e:\ts_gh\src\compiler\checker.ts:29132)
checkExpressionWorker (e:\ts_gh\src\compiler\checker.ts:35165)
checkExpression (e:\ts_gh\src\compiler\checker.ts:35074)
checkExpressionCached (e:\ts_gh\src\compiler\checker.ts:34711)
getTargetOfAliasLikeExpression (e:\ts_gh\src\compiler\checker.ts:3138)
getTargetOfAccessExpression (e:\ts_gh\src\compiler\checker.ts:3147)
getTargetOfAliasDeclaration (e:\ts_gh\src\compiler\checker.ts:3177)
getTypeOfAlias (e:\ts_gh\src\compiler\checker.ts:9969)
getTypeOfSymbol (e:\ts_gh\src\compiler\checker.ts:10083)
getNonMissingTypeOfSymbol (e:\ts_gh\src\compiler\checker.ts:10089)
addPropertyToElementList (e:\ts_gh\src\compiler\checker.ts:5776)
createTypeNodesFromResolvedType (e:\ts_gh\src\compiler\checker.ts:5741)
createTypeNodeFromObjectType (e:\ts_gh\src\compiler\checker.ts:5536)
createAnonymousTypeNode (e:\ts_gh\src\compiler\checker.ts:5394)
typeToTypeNodeWorker (e:\ts_gh\src\compiler\checker.ts:5214)
typeToTypeNodeHelper (e:\ts_gh\src\compiler\checker.ts:4996)
<anonymous> (e:\ts_gh\src\compiler\checker.ts:4905)
withContext (e:\ts_gh\src\compiler\checker.ts:4951)
typeToTypeNode (e:\ts_gh\src\compiler\checker.ts:4905)
typeToString (e:\ts_gh\src\compiler\checker.ts:4859)
reportNonexistentProperty (e:\ts_gh\src\compiler\checker.ts:29577)
checkPropertyAccessExpressionOrQualifiedName (e:\ts_gh\src\compiler\checker.ts:29360)
checkPropertyAccessExpression (e:\ts_gh\src\compiler\checker.ts:29132)
checkExpressionWorker (e:\ts_gh\src\compiler\checker.ts:35165)
checkExpression (e:\ts_gh\src\compiler\checker.ts:35074)
checkExpressionCached (e:\ts_gh\src\compiler\checker.ts:34711)
getTargetOfAliasLikeExpression (e:\ts_gh\src\compiler\checker.ts:3138)
getTargetOfAccessExpression (e:\ts_gh\src\compiler\checker.ts:3147)
getTargetOfAliasDeclaration (e:\ts_gh\src\compiler\checker.ts:3177)
resolveAlias (e:\ts_gh\src\compiler\checker.ts:3205)
skipAlias (e:\ts_gh\src\compiler\utilities.ts:5588)
add (e:\ts_gh\src\services\exportInfoMap.ts:135)
<anonymous> (e:\ts_gh\src\services\exportInfoMap.ts:415)
<anonymous> (e:\ts_gh\src\compiler\checker.ts:3918)
forEachExportAndPropertyOfModule (e:\ts_gh\src\compiler\checker.ts:3916)
<anonymous> (e:\ts_gh\src\services\exportInfoMap.ts:413)
<anonymous> (e:\ts_gh\src\services\exportInfoMap.ts:351)
forEachExternalModule (e:\ts_gh\src\services\exportInfoMap.ts:369)
forEachExternalModuleToImportFrom (e:\ts_gh\src\services\exportInfoMap.ts:351)
getExportInfoMap (e:\ts_gh\src\services\exportInfoMap.ts:395)
collectAutoImports (e:\ts_gh\src\services\completions.ts:2702)
getGlobalCompletions (e:\ts_gh\src\services\completions.ts:2602)
tryGetGlobalSymbols (e:\ts_gh\src\services\completions.ts:2494)
getCompletionData (e:\ts_gh\src\services\completions.ts:2212)
getCompletionsAtPosition (e:\ts_gh\src\services\completions.ts:299)
getCompletionsAtPosition (e:\ts_gh\src\services\services.ts:1645)
Session.getCompletions (e:\ts_gh\src\server\session.ts:2073)
Session.handlers.ts.Map.ts.getEntries._a.<computed> (e:\ts_gh\src\server\session.ts:3102)
<anonymous> (e:\ts_gh\src\server\session.ts:3348)
Session.executeWithRequestId (e:\ts_gh\src\server\session.ts:3338)
Session.executeCommand (e:\ts_gh\src\server\session.ts:3348)
Session.onMessage (e:\ts_gh\src\server\session.ts:3382)
```

The top two calls to `typeToString` have the same arguments (chiefly, type and flags)

<details>
<summary><h3>Repro Steps</h3></summary>
<ol>
<li><code>git clone https://github.com/TryGhost/Ghost</code></li>
<li>In dir <code>Ghost</code>, run <code>git reset --hard 72a08f4901c25e798abb13c99b3491ee1d99412a</code></li>
<li>In dir <code>Ghost</code>, run <code>yarn install --ignore-scripts --ignore-engines</code></li>
<li>Create `TryGhost.Ghost.replay.txt` with the contents below</li>
<li><code>npm install --no-save @typescript/server-replay</code></li>
<li><code>npx tsreplay ./Ghost ./TryGhost.Ghost.replay.txt path/to/tsserver.js</code> (note that you can use <code>-i</code> to open an inspect port on the tsserver process)</li>
</ol>
</details>

TryGhost.Ghost.replay.txt
```json
{"rootDirPlaceholder":"@PROJECT_ROOT@","serverArgs":["--disableAutomaticTypingAcquisition"]}
{"seq":1,"type":"request","command":"configure","arguments":{"preferences":{"includePackageJsonAutoImports":"off"},"watchOptions":{"excludeDirectories":["**/node_modules"]}}}
{"seq":7471,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"@PROJECT_ROOT@/ghost/core/core/frontend/meta/get-meta.js","projectRootPath":"@PROJECT_ROOT@"}]}}
{"seq":7480,"type":"request","command":"completionInfo","arguments":{"file":"@PROJECT_ROOT@/ghost/core/core/frontend/meta/get-meta.js","line":59,"offset":46,"includeExternalModuleExports":true,"includeInsertTextCompletions":true,"triggerKind":1}}
```

From #50799

**Comment by amcasey** [comment]
I put my breakpoint in `reportNonexistentProperty` and caught the cycle without having to do too much stepping.

**Comment by DanielRosenwasser** [comment]
I'm not sure if this is the same as https://github.com/microsoft/TypeScript/issues/51857#issuecomment-1345665094, but here's a minimal repro.

```ts
module.exports = function httpError() {

};

// backwards-compatibility
exports["I'mateapot"] = exports.ImATeapot
```

```ts
var bar = require("./bar");
bar./**/
```

Request completions.

<details>
<summary>Crash</summary>

```
<semantic> Response received: completionInfo (624). Request took 171 ms. Success: false . Message: Error processing request. Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at resolveEntityName ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45513:29)
    at resolveEntityName ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45529:23)
    at getTargetOfAliasLikeExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45311:23)
    at getTargetOfAccessExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45322:12)
    at getTargetOfAliasDeclaration ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45351:16)
    at getTypeOfAlias ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:50668:51)
    at getTypeOfSymbol ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:50756:14)
    at getNonMissingTypeOfSymbol ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:50761:30)
    at addPropertyToElementList ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47416:97)
    at createTypeNodesFromResolvedType ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47397:11)
    at createTypeNodeFromObjectType ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47214:25)
    at createAnonymousTypeNode ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47110:18)
    at typeToTypeNodeWorker ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46966:16)
    at typeToTypeNodeHelper ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46766:24)
    at [homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46668:134
    at withContext ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46724:29)
    at Object.typeToTypeNode ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46668:71)
    at typeToString ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46631:34)
    at reportNonexistentProperty ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:65509:27)
    at checkPropertyAccessExpressionOrQualifiedName ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:65343:11)
    at checkPropertyAccessExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:65158:94)
    at checkExpressionWorker ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:69785:16)
    at checkExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:69710:32)
    at checkExpressionCached ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:69447:28)
    at getTargetOfAliasLikeExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45315:5)
    at getTargetOfAccessExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45322:12)
    at getTargetOfAliasDeclaration ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45351:16)
    at getTypeOfAlias ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:50668:51)
    at getTypeOfSymbol ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:50756:14)
    at getNonMissingTypeOfSymbol ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:50761:30)
    at addPropertyToElementList ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47416:97)
    at createTypeNodesFromResolvedType ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47397:11)
    at createTypeNodeFromObjectType ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47214:25)
    at createAnonymousTypeNode ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47110:18)
    at typeToTypeNodeWorker ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46966:16)
    at typeToTypeNodeHelper ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46766:24)
    at [homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46668:134
    at withContext ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46724:29)
    at Object.typeToTypeNode ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46668:71)
    at typeToString ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46631:34)
    at reportNonexistentProperty ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:65509:27)
    at checkPropertyAccessExpressionOrQualifiedName ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:65343:11)
    at checkPropertyAccessExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:65158:94)
    at checkExpressionWorker ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:69785:16)
    at checkExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:69710:32)
    at checkExpressionCached ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:69447:28)
    at getTargetOfAliasLikeExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45315:5)
    at getTargetOfAccessExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45322:12)
    at getTargetOfAliasDeclaration ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45351:16)
    at getTypeOfAlias ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:50668:51)
    at getTypeOfSymbol ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:50756:14)
    at getNonMissingTypeOfSymbol ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:50761:30)
    at addPropertyToElementList ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47416:97)
    at createTypeNodesFromResolvedType ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47397:11)
    at createTypeNodeFromObjectType ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47214:25)
    at createAnonymousTypeNode ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47110:18)
    at typeToTypeNodeWorker ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46966:16)
    at typeToTypeNodeHelper ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46766:24)
    at [homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46668:134
    at withContext ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46724:29)
    at Object.typeToTypeNode ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46668:71)
    at typeToString ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46631:34)
    at reportNonexistentProperty ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:65509:27)
    at checkPropertyAccessExpressionOrQualifiedName ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:65343:11)
    at checkPropertyAccessExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:65158:94)
    at checkExpressionWorker ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:69785:16)
    at checkExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:69710:32)
    at checkExpressionCached ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:69447:28)
    at getTargetOfAliasLikeExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45315:5)
    at getTargetOfAccessExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45322:12)
    at getTargetOfAliasDeclaration ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45351:16)
    at getTypeOfAlias ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:50668:51)
    at getTypeOfSymbol ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:50756:14)
    at getNonMissingTypeOfSymbol ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:50761:30)
    at addPropertyToElementList ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47416:97)
    at createTypeNodesFromResolvedType ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47397:11)
    at createTypeNodeFromObjectType ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47214:25)
    at createAnonymousTypeNode ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47110:18)
    at typeToTypeNodeWorker ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46966:16)
    at typeToTypeNodeHelper ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46766:24)
    at [homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46668:134
    at withContext ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46724:29)
    at Object.typeToTypeNode ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46668:71)
    at typeToString ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:46631:34)
    at reportNonexistentProperty ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:65509:27)
    at checkPropertyAccessExpressionOrQualifiedName ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:65343:11)
    at checkPropertyAccessExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:65158:94)
    at checkExpressionWorker ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:69785:16)
    at checkExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:69710:32)
    at checkExpressionCached ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:69447:28)
    at getTargetOfAliasLikeExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45315:5)
    at getTargetOfAccessExpression ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45322:12)
    at getTargetOfAliasDeclaration ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:45351:16)
    at getTypeOfAlias ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:50668:51)
    at getTypeOfSymbol ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:50756:14)
    at getNonMissingTypeOfSymbol ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:50761:30)
    at addPropertyToElementList ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47416:97)
    at createTypeNodesFromResolvedType ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47397:11)
    at createTypeNodeFromObjectType ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47214:25)
    at createAnonymousTypeNode ([homedir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202212110/node_modules/typescript/lib/tsserver.js:47110:18)
```

</details>
