### ISSUE TITLE
Completions in object type argument fails in JSDoc comment

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#51054]
This one is similar to #50750.

Found from https://github.com/microsoft/TypeScript/issues/50950#issuecomment-1257290448, and the [actual code is here](https://github.com/nocodb/nocodb/blob/69ba15e4e58993ec3fefd777365830942121221a/packages/nocodb/src/lib/db/sql-client/lib/mysql/MysqlClient.ts#L2012).

In a TypeScript file:

```ts
interface Yadda<T> { }

/**
 * @type {Yadda<{ $ }>}
 */
```

Request completions at `$`.

```
TypeError: Cannot read properties of undefined (reading 'flags')
    at getMembersOfSymbol (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:58932:27)
    at getTypeFromTypeLiteralOrFunctionOrConstructorTypeNode (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:63962:21)
    at getTypeFromTypeNodeWorker (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:64357:28)
    at getTypeFromTypeNode (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:64281:49)
    at Object.map (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:460:29)
    at typeArgumentsFromTypeReferenceNode (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:61704:23)
    at getTypeFromClassOrInterfaceReference (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:61387:103)
    at getTypeReferenceType (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:61503:24)
    at getTypeFromTypeReference (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:61689:32)
    at getTypeParametersForTypeReference (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:82079:24)
    at getTypeArgumentConstraint (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:82120:34)
    at Object.getTypeArgumentConstraint (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:49503:32)
    at getConstraintOfTypeArgumentProperty (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:138015:32)
    at tryGetObjectTypeLiteralInTypeArgumentCompletionSymbols (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:136991:45)
    at tryGetGlobalSymbols (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:136537:30)
    at getCompletionData (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:136289:22)
    at Object.getCompletionsAtPosition (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:134871:34)
    at Object.getCompletionsAtPosition (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:168444:35)
    at Session.getCompletions (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:180576:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:179249:61)
    at c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:181309:96
    at Session.executeWithRequestId (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:181300:28)
    at Session.executeCommand (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:181309:41)
    at Session.onMessage (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:181337:35)
    at process.<anonymous> (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20220919/node_modules/typescript/lib/tsserver.js:185489:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by RyanCavanaugh** [comment]
Closing language service bugs related to the 6.0 implementation. For more information, see #62827
