### ISSUE TITLE
Namespace import in esm for cjs module described by `any` type leads to debug failure

### ISSUE THREAD

**Issue by dsherret** [microsoft/TypeScript#51099]
# Bug Report

Namespace importing a cjs module described with an `any` type from an es module leads to a debug failure.

### 🔎 Search Terms

Debug Failure. Unhandled type 1

### 🕗 Version & Regression Information

- This is a crash in 4.9.0-dev.20221007 and 4.8.4

### ⏯ Playground Link

Can't because it's multiple files.

### 💻 Code

*package.json*

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "module": "index.mjs",
  "dependencies": {
    "typescript": "^4.9.0-dev.20221007"
  }
}
```

*tsconfig.json*

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "NodeNext",
    "strict": true
  }
}
```

*index.mts*

```ts
import * as namespaceImport from "./other.cjs";
console.log(namespaceImport);
```

*other.cjs*

```js
// note: this is described by other.d.cts
module.exports.test = () => 5;
```

*other.d.cts*

```ts
declare const __: any;
export = __;
```

### 🙁 Actual behavior

Running `tsc`:

```
V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:99472
                throw e;
                ^

Error: Debug Failure. Unhandled type 1
    at resolveStructuredTypeMembers (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:49660:30)
    at cloneTypeAsModuleType (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:43230:38)
    at resolveESModuleSymbol (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:43209:36)
    at getTargetOfNamespaceImport (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:42412:28)
    at getTargetOfAliasDeclaration (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:42640:28)
    at resolveAlias (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:42681:30)
    at checkAliasSymbol (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:72981:26)
    at checkImportBinding (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:73096:13)
    at checkImportDeclaration (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:73147:29)
    at checkSourceElementWorker (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:73614:28)
```

Note: type 1 is `TypeFlags.Any`

### 🙂 Expected behavior

Should pass type checking.

### Why?

We use the file with `declare const __: any; export = __` in Deno in order to give certain modules an any type. Now when adding `impliedNodeFormat` when creating a source file in order to allow importing npm packages, I had to make this module CJS because it has `export =` and that surfaced this issue.

**Comment by jakebailey** [comment]
I can reproduce this, but the bisect will certainly show this to be #49943 where I added the assert.

`any` is not a `StructuredType` so it's not right for `any` to be there; `cloneTypeAsModuleType` casts the module type to `StructuredType` so this fits with the bug. Probably, it should check if the export is actually a structured type; it only cares because it aims to remove the call signatures from said type but that's not helpful when the type is already `any`.

**Comment by jakebailey** [comment]
Also, the same thing happens when the export is `unknown`, `symbol`, etc, for the same reason.

**Comment by jakebailey** [comment]
I opened #51136 since I had the code, but I think someone with better knowledge about the workings of these kinds of imports should weigh in. (I'm getting to this pre-triage, sorry!)
