### ISSUE TITLE
Start < 0 in BuilderIO/qwik

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#51221]
Issue in [BuilderIO/qwik](https://github.com/BuilderIO/qwik) found in #51218

`Error: start < 0`

```
Req #6872 - references
    at createTextSpan (/typescript-4.9.0-dev.20221018/lib/tsserver.js:12557:19)
    at Object.createTextSpanFromBounds (/typescript-4.9.0-dev.20221018/lib/tsserver.js:12566:16)
    at getTextSpan (/typescript-4.9.0-dev.20221018/lib/tsserver.js:140296:23)
    at entryToDocumentSpan (/typescript-4.9.0-dev.20221018/lib/tsserver.js:140193:32)
    at toReferenceEntry (/typescript-4.9.0-dev.20221018/lib/tsserver.js:140179:32)
    at toReferencedSymbolEntry (/typescript-4.9.0-dev.20221018/lib/tsserver.js:140173:34)
    at /typescript-4.9.0-dev.20221018/lib/tsserver.js:140033:70
    at /typescript-4.9.0-dev.20221018/lib/tsserver.js:140033:44
    at Object.mapDefined (/typescript-4.9.0-dev.20221018/lib/tsserver.js:621:30)
    at Object.findReferencedSymbols (/typescript-4.9.0-dev.20221018/lib/tsserver.js:140028:85)
    at Object.findReferences (/typescript-4.9.0-dev.20221018/lib/tsserver.js:169125:41)
    at /typescript-4.9.0-dev.20221018/lib/tsserver.js:179297:53
    at searchPosition (/typescript-4.9.0-dev.20221018/lib/tsserver.js:179494:38)
    at getPerProjectReferences (/typescript-4.9.0-dev.20221018/lib/tsserver.js:179462:42)
    at getReferencesWorker (/typescript-4.9.0-dev.20221018/lib/tsserver.js:179294:37)
    at IOSession.Session.getReferences (/typescript-4.9.0-dev.20221018/lib/tsserver.js:180901:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/typescript-4.9.0-dev.20221018/lib/tsserver.js:179734:61)
    at /typescript-4.9.0-dev.20221018/lib/tsserver.js:181869:96
    at IOSession.Session.executeWithRequestId (/typescript-4.9.0-dev.20221018/lib/tsserver.js:181860:28)
    at IOSession.Session.executeCommand (/typescript-4.9.0-dev.20221018/lib/tsserver.js:181869:41)
    at IOSession.Session.onMessage (/typescript-4.9.0-dev.20221018/lib/tsserver.js:181897:35)
    at Interface.<anonymous> (/typescript-4.9.0-dev.20221018/lib/tsserver.js:186023:31)
```

<details>
<summary><h3>Last few requests</h3></summary>

```json
{"seq":6869,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"@PROJECT_ROOT@/packages/qwik/src/core/render/ssr/render-ssr.unit.tsx","projectRootPath":"@PROJECT_ROOT@"}]}}
{"seq":6870,"type":"request","command":"organizeImports","arguments":{"scope":{"type":"file","args":{"file":"@PROJECT_ROOT@/packages/qwik/src/core/render/ssr/render-ssr.unit.tsx"}},"skipDestructiveCodeActions":true}}
{"seq":6871,"type":"request","command":"getOutliningSpans","arguments":{"file":"@PROJECT_ROOT@/packages/qwik/src/core/render/ssr/render-ssr.unit.tsx"}}
{"seq":6872,"type":"request","command":"references","arguments":{"file":"@PROJECT_ROOT@/packages/qwik/src/core/render/ssr/render-ssr.unit.tsx","line":1,"offset":31}}

```

</details>

<details>
<summary><h3>Repro Steps</h3></summary>
<ol>
<li><code>git clone https://github.com/BuilderIO/qwik --recurse-submodules</code></li>
<li>In dir <code>qwik</code>, run <code>git reset --hard c41b93e6df23a72ab03eca29b44adbe94716c836</code></li>
<li>Back in the initial folder, download <code>RepoResults4/BuilderIO.qwik.replay.txt</code> from the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=136652&view=artifacts&type=publishedArtifacts">artifact folder</a></li>
<li><code>npm install --no-save @typescript/server-replay</code></li>
<li><code>npx tsreplay ./qwik ./BuilderIO.qwik.replay.txt path/to/tsserver.js</code></li>
<li><code>npx tsreplay --help</code> to learn about helpful switches for debugging, logging, etc</li>
</ol>
</details>

**Comment by DanielRosenwasser** [comment]
Okay, I have it exactly. One sec.

**Comment by DanielRosenwasser** [comment]
Basically, this is an issue with us trying to perform find-all-refs on a synthetic import.

```ts
// @filename: project/src/foo.ts
import * as x from "@foo/dir/jsx-runtime";

// @filename: project/src/dir/jsx-runtime.ts
export {}

// @filename: tsconfig.json
{
    "compilerOptions": {
        "moduleResolution": "node",
        "module": "es2020",
        "jsx": "react-jsx",
        "jsxImportSource": "@foo/dir",
        "paths": {
            "@foo/dir/jsx-runtime": ["./src/dir/jsx-runtime"]
        }
    }
}

```
