### ISSUE TITLE
Code transpilation does not work with any target later than es5.

### ISSUE THREAD

**Issue by WillooWisp** [microsoft/TypeScript#51801]
# Bug Report

Typescript transpiles the attached code into something not possible to execute in browser, when targeting later versions than es5.

ng_reflect.ts:24        
ERROR TypeError: X is not a constructor
    at e.t (oidc-client.min.js:1:12082)
    at new e (oidc-client.min.js:49:27046)
    at new e (oidc-client.min.js:49:9187)
    at new AppComponent (app.component.ts? [sm]:51:25)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (app.component.ts? [sm]:52:2)
    at getNodeInjectable (di.ts:642:17)
    at createRootComponent (component_ref.ts:426:4)
    at ComponentFactory.create (component_ref.ts:262:10)
    at ApplicationRef.bootstrap (application_ref.ts:1126:4)
    at eval (application_ref.ts:623:1)

### 🔎 Search Terms

Transpile, error, es5, es2015

### 🕗 Version & Regression Information

```ts
class ResponseValidatorCtor {
  private _settings: any;

  constructor(
    settings,
    metadataServiceCtor?: MetadataServiceCtor,
    userInfoServiceCtor?: any
  ) {
    this._settings = settings;
  }

  public validateSigninResponse(state, response) {
    response.state = state._data;
    return response;
  }

  public validateSignoutResponse(state, response) {
    // validation goes here
    return Promise.resolve(response);
  }
}

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  private userManagerSettings: UserManagerSettings = {
    ResponseValidatorCtor: (settings, metadata, userInfo) =>
      new ResponseValidatorCtor(settings),
    authority: 'https://login.microsoftonline.com/common/v2.0',
    client_id: '',
    redirect_uri: `${window.location.origin}/login/oidc/azure`,
    silent_redirect_uri: `${window.location.origin}/login/oidc/azure`,
    post_logout_redirect_uri: `${window.location.origin}/login`,
    response_type: 'id_token',
    scope: 'openid email profile',
  };
  private userManager = new UserManager(this.userManagerSettings);
}
```

### 🙁 Actual behavior

Website fails loading due to error in code.

### 🙂 Expected behavior

Expects website to load without failures.

**Comment by RyanCavanaugh** [comment]
To look at this we'd need a repro that doesn't involve Angular, alongside an actual "This line in particular is wrong and should be this other ting instead" statement. People have been using > ES5 class transforms for 8+ years without issue so the burden of proof is entirely on the position that it's never worked.

**Comment by WillooWisp** [comment]
Okay, I understand, I will try to make a reproduction without angular then.

/ Joel Fjordén
________________________________

**Comment by WillooWisp** [comment]
@MartinJohns and @RyanCavanaugh here is a clean TypeScript sample illustrating the same problem, where it works targeting ES5, but not anything above.

https://stackblitz.com/edit/typescript-acmvrk

**Comment by RyanCavanaugh** [comment]
Again, you'll need to tell me which line of code in the generated output is wrong, and why.
