### ISSUE TITLE
"Extract to function" refactoring triggers an assertion failure

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#51827]
```ts
export function f() {
    let g = [|<B>(x: B) => x|];
    return g;
}
```

Run some sort of extract function on that range. It'll crash with:

```
Debug Failure. Did not expect FunctionDeclaration to have an Identifier in its trivia
    at addSyntheticNodes (tsserverlibrary.js:168341:30)
    at createSyntaxList (tsserverlibrary.js:168357:13)
    at processNodes (tsserverlibrary.js:168320:27)
    at visitNodes (tsserverlibrary.js:31219:24)
    at forEachChildInFunctionDeclaration (tsserverlibrary.js:31404:17)
    at forEachChild (tsserverlibrary.js:31997:47)
    at NodeObject.forEachChild (tsserverlibrary.js:168295:23)
    at createChildren (tsserverlibrary.js:168329:14)
    at NodeObject.getChildren (tsserverlibrary.js:168272:56)
    at find (tsserverlibrary.js:130979:30)
```

Found from [this code in storybook](https://github.com/storybookjs/storybook/blob/ee0d2a128243974c95a821e6e4ae2618bc075d09/code/lib/core-common/src/utils/satisfies.ts):

```ts
export function satisfies<A>() {
  return <T extends A>(x: T) => x;
}
```

**Comment by a-tarasyuk** [comment]
Do we need to keep the type argument for the extracted function?

```ts
export function f() {
    let g = [|<B>(x: B) => x|];
    return g;
}
```

```ts
function newFunction<B>() {
    return <B>(x: B) => x; // syntax error
}
```

---

```ts
export function f() {
    let g = [|function <B>(x: B) { return x }|];
    return g;
}
```

```ts
function newFunction<B>() {
    return function <B>(x: B) { return x; };
}
```

----

```ts
export function f() {
    [|function fn<T>(t: T) {
        return t;
    }|]
}
```

```ts
function newFunction<T>() {
    function fn<T>(t: T) {
        return t;
    }
}
```

**Comment by DanielRosenwasser** [comment]
The new function shouldn't capture any type parameters that were declared inside within the expressions being extracted.


In the case of something like

```ts
export function satisfies<A>() {
  return [|<T extends A>(x: T) => x|];
}
```

the new function should be generic (because `A` needs to be funneled through):

```ts
export function satisfies<A>() {
  return newFunction<A>();
}

function newFunction<A>() {
  return <T extends A>(x: T) => x;
}
```

______

Also, I wonder if we have any tests for generic arrow functions being generated in a `.tsx` file, since

```ts
const id = <T>(x: T) => x
```

is not allowed without some disambiguating syntax like `,` or `extends`.

```ts
const id = <T,>(x: T) => x
//           ^ - required in a `.tsx` file.
```
