### ISSUE TITLE
Invalid property read for find-all-references when exporting non-existent binding

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#51963]
```ts
// @filename: ./bar.ts
import { Foo/**/ } from "./foo";
```

```ts
// @filename: ./foo.ts
export { Foo }
```

```json5
{
    "compilerOptions": {
        "module": "commonjs"
    }
}
```

Find all references on `Foo` at `/**/`

```
TypeError: Cannot read properties of undefined (reading 'escapedName')
    at getImport ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:137739:24)
    at getImportOrExportSymbol ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:137672:58)
    at getImportOrExportReferences ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:139039:28)
    at getReferencesAtLocation ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:138981:5)
    at getReferencesInContainer ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:138928:7)
    at getReferencesInContainerOrFiles ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:138557:7)
    at getReferencedSymbolsForSymbol ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:138550:7)
    at Object.getReferencedSymbolsForNode ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:138346:24)
    at Object.findReferencedSymbols ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:137952:34)
    at Object.findReferences ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:122190:41)
    at [WORKSPACE]/node_modules/typescript/lib/tsserver.js:158208:43
    at searchPosition ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:158351:28)
    at getPerProjectReferences ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:158326:32)
    at getReferencesWorker ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:158201:29)
    at IpcIOSession.getReferences ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:159748:24)
    at references ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:158579:43)
    at [WORKSPACE]/node_modules/typescript/lib/tsserver.js:160677:69
    at IpcIOSession.executeWithRequestId ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:160669:14)
    at IpcIOSession.executeCommand ([WORKSPACE]/node_modules/typescript/lib/tsserver.js:160677:29)
```

Related: 

* https://github.com/microsoft/TypeScript/issues/38070#issuecomment-1357727518

**Comment by a-tarasyuk** [comment]
The following test works as expected

```
// @Filename: /tsconfig.json
//// { "compilerOptions": { "module": "commonjs" } }

// @filename: /bar.ts
////import { Foo } from "./foo";

// @filename: /foo.ts
////export { Foo/**/ }
```

**Comment by DanielRosenwasser** [comment]
Whoops! Try it on the import, not the export.
