### ISSUE TITLE
Debug Failure. False expression: type provided should not be a non-generic 'promise'-like.

### ISSUE THREAD

**Issue by yume-chan** [microsoft/TypeScript#51984]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.7.4 and 4.8.4

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?target=99&ts=4.8.4#code/IYZwngdgxgBAZgV2gFwJYHsICp4B4AqMApgB7JEQAmIMACgE7oC2qIRuERAbkfQHx8AFAEoAXDACC4aAHEKvYMnT0CAGhhd0qSus3a+MAN4wAvkA)

### 💻 Code

```ts
async function* f<T extends Promise<never>>(): AsyncGenerator<T, void, void> { }
```

### 🙁 Actual behavior

```text
<redacted>\node_modules\.pnpm\typescript@4.8.4\node_modules\typescript\lib\tsc.js:98439
                throw e;
                ^

Error: Debug Failure. False expression: type provided should not be a non-generic 'promise'-like.
    at createAwaitedTypeIfNeeded (<redacted>\node_modules\.pnpm\typescript@4.8.4\node_modules\typescript\lib\tsc.js:69048:22)
    at Object.getAwaitedType [as resolveIterationType] (<redacted>\node_modules\.pnpm\typescript@4.8.4\node_modules\typescript\lib\tsc.js:69053:35)
    at getIterationTypesOfIterableFast (<redacted>\node_modules\.pnpm\typescript@4.8.4\node_modules\typescript\lib\tsc.js:70682:111)
    at getIterationTypesOfIterableWorker (<redacted>\node_modules\.pnpm\typescript@4.8.4\node_modules\typescript\lib\tsc.js:70612:21)
    at getIterationTypesOfIterable (<redacted>\node_modules\.pnpm\typescript@4.8.4\node_modules\typescript\lib\tsc.js:70545:40)
    at getIterationTypesOfGeneratorFunctionReturnType (<redacted>\node_modules\.pnpm\typescript@4.8.4\node_modules\typescript\lib\tsc.js:70884:20)
    at getIterationTypeOfGeneratorFunctionReturnType (<redacted>\node_modules\.pnpm\typescript@4.8.4\node_modules\typescript\lib\tsc.js:70875:34)
    at checkSignatureDeclarationDiagnostics (<redacted>\node_modules\.pnpm\typescript@4.8.4\node_modules\typescript\lib\tsc.js:68004:54)
    at addLazyDiagnostic (<redacted>\node_modules\.pnpm\typescript@4.8.4\node_modules\typescript\lib\tsc.js:73139:56)
    at checkSignatureDeclaration (<redacted>\node_modules\.pnpm\typescript@4.8.4\node_modules\typescript\lib\tsc.js:67982:13)
```

### 🙂 Expected behavior

No crash.

**Comment by jedwards1211** [comment]
Seems to have something to do with running `ts-node --transpileOnly` on a script
