### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by eduardogmisiuk** [microsoft/TypeScript#52046]
# Bug Report

### 🔎 Search Terms

Maximum call stack size, allocation failed

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

Couldn't isolate the problem.

### 🙁 Actual behavior

I've switched to Typescript after beginning the project with CRA (without ejecting) in plain-JS. After some development, we began to experience some memory-related errors in the checking phase of TS when running on both dev and prod builds. When we were trying to solve this problem, we came to the version `v3.7.2`, which apparently solved the issue, but now the same error is appearing again.
In the versions `v3.7.2` up to `v3.7.7`, the error we are given is the following (this output was given by `v3.7.7`):

```
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
at recursiveTypeRelatedTo (/project/node_modules/typescript/lib/typescript.js:46761:44)
at isRelatedTo (/project/node_modules/typescript/lib/typescript.js:46389:38)
at typeRelatedToEachType (/project/node_modules/typescript/lib/typescript.js:46662:35)
at isRelatedTo (/project/node_modules/typescript/lib/typescript.js:46364:34)
at typeRelatedToSomeType (/project/node_modules/typescript/lib/typescript.js:46562:35)
at isRelatedTo (/project/node_modules/typescript/lib/typescript.js:46353:34)
at eachTypeRelatedToType (/project/node_modules/typescript/lib/typescript.js:46689:35)
at isRelatedTo (/project/node_modules/typescript/lib/typescript.js:46349:25)
at isPropertySymbolTypeRelated (/project/node_modules/typescript/lib/typescript.js:47377:28)
at propertyRelatedTo (/project/node_modules/typescript/lib/typescript.js:47418:31)
```

In this version, I tried to increase the node stack up to 10MB, without success.

When changing to newer versions, the error changes to (using v4.8.4):

```
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...

<--- Last few GCs --->

[23483:0x61f1d10]    35690 ms: Mark-sweep (reduce) 2031.9 (2046.5) -> 2031.9 (2046.0) MB, 348.9 / 0.0 ms  (average mu = 0.155, current mu = 0.000) last resort GC in old space requested
[23483:0x61f1d10]    36039 ms: Mark-sweep (reduce) 2031.9 (2042.0) -> 2031.8 (2042.0) MB, 349.4 / 0.0 ms  (average mu = 0.082, current mu = 0.000) last resort GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
1: 0xa3ac30 node::Abort() [/.nvm/versions/node/v14.21.2/bin/node]
2: 0x970199 node::FatalError(char const*, char const*) [/.nvm/versions/node/v14.21.2/bin/node]
3: 0xbba76e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/.nvm/versions/node/v14.21.2/bin/node]
4: 0xbbaae7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/.nvm/versions/node/v14.21.2/bin/node]
5: 0xd76d05  [/.nvm/versions/node/v14.21.2/bin/node]
6: 0xd89321 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/.nvm/versions/node/v14.21.2/bin/node]
7: 0xd4ea5d v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/.nvm/versions/node/v14.21.2/bin/node]
8: 0xd4acb9 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [/.nvm/versions/node/v14.21.2/bin/node]
9: 0xd4ad74 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/.nvm/versions/node/v14.21.2/bin/node]
10: 0xf9248e v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate(v8::internal::Isolate*, int, v8::internal::AllocationType) [/.nvm/versions/node/v14.21.2/bin/node]
11: 0xf92626 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/.nvm/versions/node/v14.21.2/bin/node]
12: 0x1083e28 v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/.nvm/versions/node/v14.21.2/bin/node]
13: 0x14491d9  [/.nvm/versions/node/v14.21.2/bin/node]
RpcIpcMessagePortClosedError: Process 23483 exited [SIGABRT].
Issues checking service aborted - probably out of memory. Check the `memoryLimit` option in the ForkTsCheckerWebpackPlugin configuration.
If increasing the memory doesn't solve the issue, it's most probably a bug in the TypeScript or EsLint.
```

Both errors were given using the same node version. I even tried to use other versions, such as v18.7.0, v14.8.0.

When trying to build in production, the error given is (node `v14.21.2`, TS `v4.8.4`):
```
#18 2.204 Creating an optimized production build...
#18 114.0 
#18 114.0 <--- Last few GCs --->
#18 114.0 
#18 114.0 [46:0x5ecb0e0]   109298 ms: Mark-sweep (reduce) 2028.8 (2039.3) -> 2028.8 (2039.3) MB, 2468.2 / 0.0 ms  (average mu = 0.142, current mu = 0.000) last resort GC in old space requested
#18 114.0 [46:0x5ecb0e0]   111674 ms: Mark-sweep (reduce) 2028.8 (2036.3) -> 2028.7 (2037.3) MB, 2376.2 / 0.0 ms  (average mu = 0.075, current mu = 0.000) last resort GC in old space requested
#18 114.0 
#18 114.0 
#18 114.0 <--- JS stacktrace --->
#18 114.0 
#18 114.0 FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
#18 114.0  1: 0xa3ac30 node::Abort() [/usr/local/bin/node]
#18 114.0  2: 0x970199 node::FatalError(char const*, char const*) [/usr/local/bin/node]
#18 114.0  3: 0xbba76e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
#18 114.1  4: 0xbbaae7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
#18 114.1  5: 0xd76d05  [/usr/local/bin/node]
#18 114.1  6: 0xd89321 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
#18 114.1  7: 0xd4ea5d v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/local/bin/node]
#18 114.1  8: 0xd4acb9 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [/usr/local/bin/node]
#18 114.1  9: 0xd4ad74 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/usr/local/bin/node]
#18 114.1 10: 0xf9248e v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate(v8::internal::Isolate*, int, v8::internal::AllocationType) [/usr/local/bin/node]
#18 114.1 11: 0xf92626 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/usr/local/bin/node]
#18 114.1 12: 0x1083e28 v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
#18 114.1 13: 0x14491d9  [/usr/local/bin/node]
#18 114.5 /opt/app/node_modules/react-scripts/scripts/build.js:19
#18 114.5   throw err;
#18 114.5   ^
#18 114.5 
#18 114.5 RpcIpcMessagePortClosedError: Process 46 exited [SIGABRT].
#18 114.5     at /opt/app/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:19:23
#18 114.5     at Generator.next (<anonymous>)
#18 114.5     at /opt/app/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:8:71
#18 114.5     at new Promise (<anonymous>)
#18 114.5     at __awaiter (/opt/app/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:4:12)
#18 114.5     at ChildProcess.handleExit (/opt/app/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:18:42)
#18 114.5     at ChildProcess.emit (events.js:400:28)
#18 114.5     at Process.ChildProcess._handle.onexit (internal/child_process.js:[285](https://github.com/Gradus-softwares/gradus-remuneratio/actions/runs/3801103084/jobs/6465219668#step:5:287):12) {
#18 114.5   code: null,
#18 114.5   signal: 'SIGABRT'
#18 114.5 }
#18 114.7 error Command failed with exit code 1.
#18 114.7 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#18 ERROR: executor failed running [/bin/sh -c yarn build]: exit code: 1
```

I've searched for solutions to this problem, but nothing worked and I can't find where the problem might be.

Any help would be really appreciated!

### 🙂 Expected behavior

To run/build the project without problems.

**Comment by RyanCavanaugh** [comment]
There are some debugging instructions here to try to identify where things are going wrong https://github.com/microsoft/TypeScript/issues/40819#issuecomment-700379873
