### ISSUE TITLE
Debug failure at resolveExternalModule after allowArbitraryExtensions

### ISSUE THREAD

**Issue by jakebailey** [microsoft/TypeScript#52182]
As of https://github.com/microsoft/TypeScript/commit/89e928e8b41368bb0888c6d399854c53a2dbf3d4 (#51435), the perf runner is Debug asserting: https://typescript.visualstudio.com/TypeScript/_build/results?buildId=142178&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b

```
>> /home/setup/vsts-agent/_work/7/s/built/local/tsc.js:109755
>>       throw e;
>>       ^
>> 
>> Error: Debug Failure.
>>     at resolveExternalModule (/home/setup/vsts-agent/_work/7/s/built/local/tsc.js:44740:35)
>>     at resolveExternalModuleNameWorker (/home/setup/vsts-agent/_work/7/s/built/local/tsc.js:44702:61)
>>     at resolveExternalModuleName (/home/setup/vsts-agent/_work/7/s/built/local/tsc.js:44699:12)
>>     at checkImportDeclaration (/home/setup/vsts-agent/_work/7/s/built/local/tsc.js:76954:35)
>>     at checkSourceElementWorker (/home/setup/vsts-agent/_work/7/s/built/local/tsc.js:77425:16)
>>     at checkSourceElement (/home/setup/vsts-agent/_work/7/s/built/local/tsc.js:77244:7)
>>     at forEach (/home/setup/vsts-agent/_work/7/s/built/local/tsc.js:37:22)
>>     at checkSourceFileWorker (/home/setup/vsts-agent/_work/7/s/built/local/tsc.js:77608:7)
>>     at checkSourceFile (/home/setup/vsts-agent/_work/7/s/built/local/tsc.js:77575:5)
>>     at checkSourceFileWithEagerDiagnostics (/home/setup/vsts-agent/_work/7/s/built/local/tsc.js:77669:5
```

This seems to be carried through to PRs too (like https://typescript.visualstudio.com/TypeScript/_build/results?buildId=142192&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=fb1961db-d514-5215-fe81-a42cdc309f86 😢)

cc @weswigham

**Comment by jakebailey** [comment]
This `checkDefined` is what's failing:

```ts
            else if (resolvedModule.resolvedUsingTsExtension && !shouldAllowImportingTsExtension(compilerOptions, currentSourceFile.fileName)) {
                const tsExtension = Debug.checkDefined(tryExtractTSExtension(moduleReference));
                error(errorNode, Diagnostics.An_import_path_can_only_end_with_a_0_extension_when_allowImportingTsExtensions_is_enabled, tsExtension);
            }
```

**Comment by jakebailey** [comment]
And `moduleReference` is `'@angular/core'`, yet it was resolved using a TS extension?

**Comment by jakebailey** [comment]
Minimal repro:


```ts
// @filename: tsconfig.json
{
  "compilerOptions": {
    "paths": {
      "@angular/*": ["./@angular/*"]
    }
  }
}

// @filename: @angular/core/package.json
{
    "name": "@angular/core",
    "typings": "index.d.ts"
}

// @filename: @angular/core/index.ts
export * from "./src/core";

// @filename: @angular/core/src/core.ts
export {};

// @filename: @angular/core/testing/test.ts
import "@angular/core";
```

**Comment by jakebailey** [comment]
The general pattern seems to be:

- `loadNodeModuleFromDirectory` finds index.d.ts, then calls `loadNodeModuleFromDirectoryWorker` with `tests/cases/@angular/core/index.d.ts`
- `nodeLoadModuleByRelativeName` is then called on `tests/cases/@angular/core/index.d.ts`, which then eventually calls `loadModuleFromFileNoImplicitExtensions`, which used to return `undefined`, but now returns a result that says "I found a match and it was resolved using a ts extension"
- Things fall apart because a non-file import was resolved using a ts extension.

**Comment by Tenuka22** [comment]
```
PS D:\PROJECTS\siyathra> pnpm tsc
D:\PROJECTS\siyathra\node_modules\.pnpm\typescript@5.7.3\node_modules\typescript\lib\_tsc.js:121835
      throw e;
      ^

Error: Debug Failure.
    at resolveExternalModule (D:\PROJECTS\siyathra\node_modules\.pnpm\typescript@5.7.3\node_modules\typescript\lib\_tsc.js:48958:37)
    at resolveExternalModuleNameWorker (D:\PROJECTS\siyathra\node_modules\.pnpm\typescript@5.7.3\node_modules\typescript\lib\_tsc.js:48914:61)       
    at resolveExternalModuleName (D:\PROJECTS\siyathra\node_modules\.pnpm\typescript@5.7.3\node_modules\typescript\lib\_tsc.js:48911:12)
    at checkImportDeclaration (D:\PROJECTS\siyathra\node_modules\.pnpm\typescript@5.7.3\node_modules\typescript\lib\_tsc.js:84711:30)
    at checkSourceElementWorker (D:\PROJECTS\siyathra\node_modules\.pnpm\typescript@5.7.3\node_modules\typescript\lib\_tsc.js:85200:16)
    at checkSourceElement (D:\PROJECTS\siyathra\node_modules\.pnpm\typescript@5.7.3\node_modules\typescript\lib\_tsc.js:85009:7)
    at forEach (D:\PROJECTS\siyathra\node_modules\.pnpm\typescript@5.7.3\node_modules\typescript\lib\_tsc.js:32:22)
    at checkSourceFileWorker (D:\PROJECTS\siyathra\node_modules\.pnpm\typescript@5.7.3\node_modules\typescript\lib\_tsc.js:85413:7)
    at checkSourceFile (D:\PROJECTS\siyathra\node_modules\.pnpm\typescript@5.7.3\node_modules\typescript\lib\_tsc.js:85373:69)
    at checkSourceFileWithEagerDiagnostics (D:\PROJECTS\siyathra\node_modules\.pnpm\typescript@5.7.3\node_modules\typescript\lib\_tsc.js:85499:5)    

Node.js v22.12.0
PS D:\PROJECTS\siyathra>
```

I get the same error what should I  do
