### ISSUE TITLE
`switch`/`case` completions fail when has a negative literal type

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#52277]
Found from https://github.com/microsoft/TypeScript/issues/52253#issuecomment-1383261940

```ts
export function foo(position: -1 | 0 | 1) {
  switch (position) {
    /**/
  }
}
```

Request completions with snippet text (`includeInsertTextCompletions`) at `/**/`

This currently errors:

```
Response received: completionInfo (2114). Request took 186 ms. Success: false . Message: Error processing request.
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (/typescript-5.0.0-dev.20230115/lib/tsserver.js:165065:17)
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:164996:9
    at visitNode2 (/typescript-5.0.0-dev.20230115/lib/tsserver.js:29188:18)
    at forEachChildInCaseClause (/typescript-5.0.0-dev.20230115/lib/tsserver.js:29453:12)
    at forEachChild (/typescript-5.0.0-dev.20230115/lib/tsserver.js:29701:35)
    at processNode (/typescript-5.0.0-dev.20230115/lib/tsserver.js:164993:5)
    at formatSpanWorker (/typescript-5.0.0-dev.20230115/lib/tsserver.js:164801:5)
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:164741:105
    at getFormattingScanner (/typescript-5.0.0-dev.20230115/lib/tsserver.js:163557:15)
    at Object.formatNodeGivenIndentation (/typescript-5.0.0-dev.20230115/lib/tsserver.js:164741:10)
    at Object.printAndFormatNode (/typescript-5.0.0-dev.20230115/lib/tsserver.js:147969:43)
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:147313:57
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:147318:17
    at map (/typescript-5.0.0-dev.20230115/lib/tsserver.js:2896:19)
    at getExhaustiveCaseSnippets (/typescript-5.0.0-dev.20230115/lib/tsserver.js:147314:24)
    at completionInfoFromData (/typescript-5.0.0-dev.20230115/lib/tsserver.js:147240:19)
    at Object.getCompletionsAtPosition (/typescript-5.0.0-dev.20230115/lib/tsserver.js:146995:24)
    at Object.getCompletionsAtPosition2 [as getCompletionsAtPosition] (/typescript-5.0.0-dev.20230115/lib/tsserver.js:134099:35)
    at IOSession.getCompletions (/typescript-5.0.0-dev.20230115/lib/tsserver.js:176530:54)
    at completionInfo (/typescript-5.0.0-dev.20230115/lib/tsserver.js:174929:43)
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:177294:69
    at IOSession.executeWithRequestId (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177286:14)
    at IOSession.executeCommand (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177294:29)
    at IOSession.onMessage (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177336:51)
    at Interface.<anonymous> (/typescript-5.0.0-dev.20230115/lib/tsserver.js:178787:14)
```

**Comment by DanielRosenwasser** [comment]
Thank you @a-tarasyuk!
