### ISSUE TITLE
Could not find source file error in find all references in 'remotion'

### ISSUE THREAD

**Issue by gabritto** [microsoft/TypeScript#52316]
Issue found in https://github.com/microsoft/TypeScript/issues/52253#issuecomment-1383261965.

```
Error: Could not find source file: '/mnt/ts_downloads/remotion/packages/core/src/loading-indicator.tsx'.
```

</details>

```
Req #524 - references
    at getValidSourceFile (/typescript-5.0.0-dev.20230115/lib/tsserver.js:133833:21)
    at Object.findReferences (/typescript-5.0.0-dev.20230115/lib/tsserver.js:134267:117)
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:174396:43
    at searchPosition (/typescript-5.0.0-dev.20230115/lib/tsserver.js:174538:28)
    at getPerProjectReferences (/typescript-5.0.0-dev.20230115/lib/tsserver.js:174515:32)
    at getReferencesWorker (/typescript-5.0.0-dev.20230115/lib/tsserver.js:174388:29)
    at IOSession.getReferences (/typescript-5.0.0-dev.20230115/lib/tsserver.js:176278:24)
    at references (/typescript-5.0.0-dev.20230115/lib/tsserver.js:174810:43)
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:177294:69
    at IOSession.executeWithRequestId (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177286:14)
    at IOSession.executeCommand (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177294:29)
    at IOSession.onMessage (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177336:51)
    at Interface.<anonymous> (/typescript-5.0.0-dev.20230115/lib/tsserver.js:178787:14)
```
That is a filtered view of the text. To see the raw error text, go to RepoResults3/remotion-dev.remotion.rawError.txt</code> in the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=142763&view=artifacts&type=publishedArtifacts">artifact folder</a></li>

<details>
<summary><h3>Last few requests</h3></summary>

```json
{"seq":521,"type":"request","command":"organizeImports","arguments":{"scope":{"type":"file","args":{"file":"@PROJECT_ROOT@/packages/cli/src/editor/components/MenuBuildIndicator.tsx"}},"skipDestructiveCodeActions":false}}
{"seq":522,"type":"request","command":"getOutliningSpans","arguments":{"file":"@PROJECT_ROOT@/packages/cli/src/editor/components/MenuBuildIndicator.tsx"}}
{"seq":523,"type":"request","command":"updateOpen","arguments":{"changedFiles":[{"fileName":"@PROJECT_ROOT@/packages/cli/src/editor/components/MenuBuildIndicator.tsx","textChanges":[{"newText":" //comment","start":{"line":1,"offset":50},"end":{"line":1,"offset":50}}]}],"closedFiles":[],"openFiles":[]}}
{"seq":524,"type":"request","command":"references","arguments":{"file":"@PROJECT_ROOT@/packages/cli/src/editor/components/MenuBuildIndicator.tsx","line":4,"offset":2}}

```

</details>

<details>
<summary><h3>Repro Steps</h3></summary>
<ol>
<li><code>git clone https://github.com/remotion-dev/remotion --recurse-submodules</code></li>
<li>In dir <code>remotion</code>, run <code>git reset --hard 170c45549eef651cc3c4796ab36ebbbbe25ad394</code></li>
  <li>In dir <code>remotion</code>, run <code>pnpm install --no-frozen-lockfile --prefer-offline --ignore-scripts --reporter=silent</code></li>
<li>Back in the initial folder, download <code>RepoResults3/remotion-dev.remotion.replay.txt</code> from the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=142763&view=artifacts&type=publishedArtifacts">artifact folder</a></li>
<li><code>npm install --no-save @typescript/server-replay</code></li>
<li><code>npx tsreplay ./remotion ./remotion-dev.remotion.replay.txt path/to/tsserver.js</code></li>
<li><code>npx tsreplay --help</code> to learn about helpful switches for debugging, logging, etc</li>
</ol>
</details>

**Comment by gabritto** [comment]
Note: I couldn't reproduce it with fewer commands.
