### ISSUE TITLE
"TypeError: array is not iterable" in `getSuggestedLibForNonExistentProperty`

### ISSUE THREAD

**Issue by gabritto** [microsoft/TypeScript#52334]
Found at https://github.com/microsoft/TypeScript/issues/52253#issuecomment-1383261962.

## [pubkey/rxdb](https://github.com/pubkey/rxdb)

```
Req #1598 - completionInfo
    at contains (/typescript-5.0.0-dev.20230115/lib/tsserver.js:2826:21)
    at getSuggestedLibForNonExistentProperty (/typescript-5.0.0-dev.20230115/lib/tsserver.js:72354:50)
    at reportNonexistentProperty (/typescript-5.0.0-dev.20230115/lib/tsserver.js:72303:31)
    at checkPropertyAccessExpressionOrQualifiedName (/typescript-5.0.0-dev.20230115/lib/tsserver.js:72136:11)
    at checkPropertyAccessExpression (/typescript-5.0.0-dev.20230115/lib/tsserver.js:71927:94)
    at checkExpressionWorker (/typescript-5.0.0-dev.20230115/lib/tsserver.js:77122:16)
    at checkExpression (/typescript-5.0.0-dev.20230115/lib/tsserver.js:77047:32)
    at checkExpressionForMutableLocation (/typescript-5.0.0-dev.20230115/lib/tsserver.js:76810:18)
    at checkPropertyAssignment (/typescript-5.0.0-dev.20230115/lib/tsserver.js:76826:12)
    at checkObjectLiteral (/typescript-5.0.0-dev.20230115/lib/tsserver.js:71023:71)
    at checkExpressionWorker (/typescript-5.0.0-dev.20230115/lib/tsserver.js:77120:16)
    at checkExpression (/typescript-5.0.0-dev.20230115/lib/tsserver.js:77047:32)
    at checkExpressionWithContextualType (/typescript-5.0.0-dev.20230115/lib/tsserver.js:76703:18)
    at getSignatureApplicabilityError (/typescript-5.0.0-dev.20230115/lib/tsserver.js:73067:25)
    at chooseOverload (/typescript-5.0.0-dev.20230115/lib/tsserver.js:73525:13)
    at resolveCall (/typescript-5.0.0-dev.20230115/lib/tsserver.js:73384:16)
    at resolveCallExpression (/typescript-5.0.0-dev.20230115/lib/tsserver.js:73800:12)
    at resolveSignature (/typescript-5.0.0-dev.20230115/lib/tsserver.js:74183:16)
    at getResolvedSignature (/typescript-5.0.0-dev.20230115/lib/tsserver.js:74203:20)
    at getContextualTypeForArgumentAtIndex (/typescript-5.0.0-dev.20230115/lib/tsserver.js:70051:112)
    at getContextualTypeForArgument (/typescript-5.0.0-dev.20230115/lib/tsserver.js:70042:39)
    at getContextualType2 (/typescript-5.0.0-dev.20230115/lib/tsserver.js:70479:16)
    at getApparentTypeOfContextualType (/typescript-5.0.0-dev.20230115/lib/tsserver.js:70415:120)
    at getContextualTypeForObjectLiteralElement (/typescript-5.0.0-dev.20230115/lib/tsserver.js:70276:18)
    at getContextualType2 (/typescript-5.0.0-dev.20230115/lib/tsserver.js:70487:16)
    at Object.getContextualType (/typescript-5.0.0-dev.20230115/lib/tsserver.js:46825:14)
    at getContextualType (/typescript-5.0.0-dev.20230115/lib/tsserver.js:148459:19)
    at getCompletionData (/typescript-5.0.0-dev.20230115/lib/tsserver.js:148690:43)
    at Object.getCompletionsAtPosition (/typescript-5.0.0-dev.20230115/lib/tsserver.js:146977:26)
    at Object.getCompletionsAtPosition2 [as getCompletionsAtPosition] (/typescript-5.0.0-dev.20230115/lib/tsserver.js:134099:35)
    at IOSession.getCompletions (/typescript-5.0.0-dev.20230115/lib/tsserver.js:176530:54)
    at completionInfo (/typescript-5.0.0-dev.20230115/lib/tsserver.js:174929:43)
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:177294:69
    at IOSession.executeWithRequestId (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177286:14)
    at IOSession.executeCommand (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177294:29)
    at IOSession.onMessage (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177336:51)
    at Interface.<anonymous> (/typescript-5.0.0-dev.20230115/lib/tsserver.js:178787:14)
```
That is a filtered view of the text. To see the raw error text, go to RepoResults3/pubkey.rxdb.rawError.txt</code> in the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=142763&view=artifacts&type=publishedArtifacts">artifact folder</a></li>

<details>
<summary><h3>Last few requests</h3></summary>

```json
{"seq":1595,"type":"request","command":"definitionAndBoundSpan","arguments":{"file":"@PROJECT_ROOT@/dist/es/rx-query.js","line":180,"offset":34}}
{"seq":1596,"type":"request","command":"completionInfo","arguments":{"file":"@PROJECT_ROOT@/dist/es/rx-query.js","line":184,"offset":6,"includeExternalModuleExports":false,"includeInsertTextCompletions":true,"triggerKind":1}}
{"seq":1597,"type":"request","command":"completionEntryDetails","arguments":{"file":"@PROJECT_ROOT@/dist/es/rx-query.js","line":184,"offset":6,"entryNames":["@abstract"]}}
{"seq":1598,"type":"request","command":"completionInfo","arguments":{"file":"@PROJECT_ROOT@/dist/es/rx-query.js","line":188,"offset":11,"includeExternalModuleExports":false,"includeInsertTextCompletions":true,"triggerKind":1}}

```

</details>

<details>
<summary><h3>Repro Steps</h3></summary>
<ol>
<li><code>git clone https://github.com/pubkey/rxdb --recurse-submodules</code></li>
<li>In dir <code>rxdb</code>, run <code>git reset --hard 2196f118285768022b7ca79f7931ecd4c94d1750</code></li>
<li><details><summary>Install packages (exact steps are below, but it might be easier to follow the repo readme)</summary><ol>
  <li>In dir <code>rxdb/docs-src/files/logo</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/docs/files/files/logo</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/docs/files/logo</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/angular</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/electron</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/flutter/javascript</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/graphql</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/ionic2</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/node</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/react-native</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/react</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/supabase</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/svelte</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/vanilla</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/vite-vanilla-ts</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/vue</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/attachments</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/backup</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/cleanup</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/crdt</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/dev-mode</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/electron</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/encryption</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/flutter</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/json-dump</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/key-compression</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/leader-election</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/local-documents</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/migration</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/query-builder</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/replication-couchdb-new</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/replication-couchdb</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/replication-firestore</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/replication-graphql</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/replication-p2p</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/replication-websocket</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/replication</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/server-couchdb</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/storage-dexie</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/storage-foundationdb</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/storage-lokijs</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/storage-memory</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/storage-remote-websocket</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/storage-remote</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/update</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/utils</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/validate-ajv</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/validate-is-my-json-valid</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/validate-z-schema</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/test/tutorials</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
</ol></details>
<li>Back in the initial folder, download <code>RepoResults3/pubkey.rxdb.replay.txt</code> from the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=142763&view=artifacts&type=publishedArtifacts">artifact folder</a></li>
<li><code>npm install --no-save @typescript/server-replay</code></li>
<li><code>npx tsreplay ./rxdb ./pubkey.rxdb.replay.txt path/to/tsserver.js</code></li>
<li><code>npx tsreplay --help</code> to learn about helpful switches for debugging, logging, etc</li>
</ol>
</details>

**Comment by gabritto** [comment]
This reproduces under `tsreplay --superSimple`.
