### ISSUE TITLE
Typescript crashes in VS Code insiders latest build with all extensions disabled and TypeScript Nightly extension

### ISSUE THREAD

**Issue by bennyk8y** [microsoft/TypeScript#52353]
Hi, in our company we are working in relatively big TS monorepo.
For all our developers TS crashes few times a day.
My setup:
1. Visual Studio Code - **Insiders** - 1.75.0
2. JavaScript and TypeScript Nightly extension - latest
3. All extensions are disabled.

Another thing that we've tried is excluding from File Watcher `node_modules/**` and `node_modules` but i see its still being watched under, but i guess its a different thing.
# Bug Report

### 🔎 Search Terms

typescript crash, typescript plugin loading infinitely

### 🕗 Version & Regression Information

```
Version: 1.75.0-insider
Commit: 243854703b7fa371abb752ec0df7817a615a308b
Date: 2023-01-13T08:04:47.712Z (1 wk ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 21.3.0
Sandboxed: Yes 
```

The indications for this crash are 
1. Typescript icon loading infinitely
2. Hovering on any code have a ("loading...") indication
3. All Typescript features aren't working

**Comment by bennyk8y** [comment]
setting this in `tsconfig.json`
```
"exclude": ["**/node_modules", "node_modules"]
```

in every package in the monorepo should help?

**Comment by DanielRosenwasser** [comment]
Would you be able to provide us with a TSServer log from VS Code?

To do this, you'd need to:

1. Open up your command palette and either
    * open your global settings by entering `Preferences: Open User Settings`
    * open your local project by entering `Preferences: Open Workspace Settings`
1. Set the option `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open the `tsserver.log` file.

⚠ Warning: A TSServer log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on GitHub, let us know and you can share the details privately.

**Comment by bennyk8y** [comment]
@DanielRosenwasser Hi!
Can i share it privately?

**Comment by DanielRosenwasser** [comment]
Sure, email my Firstname dot Lastname at microsoft dot com

(capitalization unfortunately matters)

**Comment by DanielRosenwasser** [comment]
Just to clarify, this is more of a suspiciously long-running thing/a startup hang - it's not causing an actual crash, right?

**Comment by bennyk8y** [comment]
Yes, VSCode itself is not crashing, just TS features stop working after this happens, sometimes an error message pops with the message
```
typescript service crashed more than 5 times
```

**Comment by bennyk8y** [comment]
Just to clarify, all our development team that works on that repo (the main monorepo of the company) suffers from it, TS crashes few times a day.
Really not sure how can help VSCode understand not to watch `node_modules`, which i suspect affects the performance and maybe this somehow related to TS crashes.
But maybe the issue is not related to FileWatcher...

**Comment by bennyk8y** [comment]
@DanielRosenwasser did you get the email?

**Comment by sheetalkamat** [comment]
@bennyk8y can you please try with latest vscode and nightly and see if this still repros and if yes please share the verbose log and way to repro this to investigate this. Thanks

**Comment by tomitrescak** [comment]
Hi, I am using the latest VSCODE and typescript constantyl crashes in my monorepo. It works flawlesly with other non monorepo projects.

I followed your instructions, but the TS Log even after few minutes is huge. I scanned it and this is the error that keep repeating:

```
Err 15216 [14:58:30.541] Exception on executing command delayed processing of request 1542:

    Cannot read properties of undefined (reading 'updateFromProject')

    TypeError: Cannot read properties of undefined (reading 'updateFromProject')
        at synchronizeHostData (/Users/30031005/Github/skillpies/node_modules/.pnpm/typescript@5.5.1-rc/node_modules/typescript/lib/typescript.js:148905:14)
        at Object.getProgram (/Users/30031005/Github/skillpies/node_modules/.pnpm/typescript@5.5.1-rc/node_modules/typescript/lib/typescript.js:149084:5)
        at getSource (/Users/30031005/Github/skillpies/node_modules/.pnpm/next@15.0.0-rc.0_@babel+core@7.24.7_babel-plugin-macros@3.1.0_react-dom@19.0.0-rc-c21bcd627b-_czrxpi2kri5ztqn2ft65hk2xum/node_modules/next/dist/server/typescript/utils.js:98:69)
        at proxy.getSemanticDiagnostics (/Users/30031005/Github/skillpies/node_modules/.pnpm/next@15.0.0-rc.0_@babel+core@7.24.7_babel-plugin-macros@3.1.0_react-dom@19.0.0-rc-c21bcd627b-_czrxpi2kri5ztqn2ft65hk2xum/node_modules/next/dist/server/typescript/index.js:103:49)
        at TemplateLanguageServiceProxy.adaptDiagnosticsCall (/Users/30031005/.vscode/extensions/styled-components.vscode-styled-components-1.7.8/node_modules/typescript-template-language-service-decorator/lib/template-language-service-decorator.js:288:33)
        at Proxy.<anonymous> (/Users/30031005/.vscode/extensions/styled-components.vscode-styled-components-1.7.8/node_modules/typescript-template-language-service-decorator/lib/template-language-service-decorator.js:54:25)
        at IpcIOSession.semanticCheck (/Users/30031005/Github/skillpies/node_modules/.pnpm/typescript@5.5.1-rc/node_modules/typescript/lib/typescript.js:189731:125)
        at /Users/30031005/Github/skillpies/node_modules/.pnpm/typescript@5.5.1-rc/node_modules/typescript/lib/typescript.js:189792:14
        at MultistepOperation.executeAction (/Users/30031005/Github/skillpies/node_modules/.pnpm/typescript@5.5.1-rc/node_modules/typescript/lib/typescript.js:188448:9)
        at /Users/30031005/Github/skillpies/node_modules/.pnpm/typescript@5.5.1-rc/node_modules/typescript/lib/typescript.js:188421:71
        at IpcIOSession.executeWithRequestId (/Users/30031005/Github/skillpies/node_modules/.pnpm/typescript@5.5.1-rc/node_modules/typescript/lib/typescript.js:191498:14)
        at Object.executeWithRequestId (/Users/30031005/Github/skillpies/node_modules/.pnpm/typescript@5.5.1-rc/node_modules/typescript/lib/typescript.js:189477:57)
        at Immediate._onImmediate (/Users/30031005/Github/skillpies/node_modules/.pnpm/typescript@5.5.1-rc/node_modules/typescript/lib/typescript.js:188421:28)
        at process.processImmediate (node:internal/timers:480:21)
```

I can give you priveate access to my repo if needed. I would love to see where the error might originate ?

**Comment by sheetalkamat** [comment]
it seems like some plugin you have thats not handling things correctly as i dont see why you should run into this as its guarded correctly.
https://github.com/microsoft/TypeScript/blob/3163fe7e3898c1f48cd9bc097b96e3426cd2a453/src/services/services.ts#L1683

**Comment by baptisteArno** [comment]
Getting this same error:

```
Err 11766 [10:56:57.937] Exception on executing command {
  "seq": 8722,
  "type": "request",
  "command": "definitionAndBoundSpan",
  "arguments": {
    "file": "/Users/baptistearno/Dev/typebot.io/apps/builder/src/features/blocks/logic/webhook/components/WebhookSettings.tsx",
    "line": 93,
    "offset": 43
  }
}:

    Cannot read properties of undefined (reading 'updateFromProject')

    TypeError: Cannot read properties of undefined (reading 'updateFromProject')
        at synchronizeHostData (/Users/baptistearno/Dev/typebot.io/node_modules/typescript/lib/typescript.js:149767:14)
        at Object.getProgram (/Users/baptistearno/Dev/typebot.io/node_modules/typescript/lib/typescript.js:149951:5)
        at getSource (/Users/baptistearno/Dev/typebot.io/node_modules/next/dist/server/typescript/utils.js:98:69)
        at getEntryInfo (/Users/baptistearno/Dev/typebot.io/node_modules/next/dist/server/typescript/utils.js:137:20)
        at proxy.getDefinitionAndBoundSpan (/Users/baptistearno/Dev/typebot.io/node_modules/next/dist/server/typescript/index.js:190:55)
        at IpcIOSession.getDefinitionAndBoundSpan (/Users/baptistearno/Dev/typebot.io/node_modules/typescript/lib/typescript.js:191122:73)
        at definitionAndBoundSpan (/Users/baptistearno/Dev/typebot.io/node_modules/typescript/lib/typescript.js:190048:43)
        at /Users/baptistearno/Dev/typebot.io/node_modules/typescript/lib/typescript.js:192655:15
        at IpcIOSession.executeWithRequestId (/Users/baptistearno/Dev/typebot.io/node_modules/typescript/lib/typescript.js:192644:14)
        at IpcIOSession.executeCommand (/Users/baptistearno/Dev/typebot.io/node_modules/typescript/lib/typescript.js:192653:29)
        at IpcIOSession.onMessage (/Users/baptistearno/Dev/typebot.io/node_modules/typescript/lib/typescript.js:192701:68)
        at process.<anonymous> (/Users/baptistearno/Dev/typebot.io/node_modules/typescript/lib/tsserver.js:525:14)
        at process.emit (node:events:519:28)
        at emit (node:internal/child_process:951:14)
        at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Typescript v5.6.2

The file content where it fails:

```tsx
import { CopyButton } from "@/components/CopyButton";
import { TableList, type TableListItemProps } from "@/components/TableList";
import { TextLink } from "@/components/TextLink";
import { CodeEditor } from "@/components/inputs/CodeEditor";
import { useUser } from "@/features/account/hooks/useUser";
import { DataVariableInputs } from "@/features/blocks/integrations/httpRequest/components/ResponseMappingInputs";
import { getDeepKeys } from "@/features/blocks/integrations/httpRequest/helpers/getDeepKeys";
import { useTypebot } from "@/features/editor/providers/TypebotProvider";
import {
  Accordion,
  AccordionButton,
  AccordionIcon,
  AccordionItem,
  AccordionPanel,
  Button,
  FormControl,
  FormHelperText,
  Input,
  InputGroup,
  InputRightElement,
  Stack,
  Tab,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
  Text,
} from "@chakra-ui/react";
import type { ResponseVariableMapping } from "@typebot.io/blocks-integrations/httpRequest/schema";
import type { WebhookBlock } from "@typebot.io/blocks-logic/webhook/schema";
import { env } from "@typebot.io/env";
import usePartySocket from "partysocket/react";
import { useMemo, useState } from "react";

type Props = {
  blockId: string;
  options: WebhookBlock["options"];
  onOptionsChange: (options: WebhookBlock["options"]) => void;
};

export const WebhookSettings = ({
  blockId,
  options,
  onOptionsChange,
}: Props) => {
  const { typebot } = useTypebot();
  const { user } = useUser();
  const [receivedData, setReceivedData] = useState<string>();
  const [websocketStatus, setWebsocketStatus] = useState<"closed" | "opened">(
    "closed",
  );
  const [responseKeys, setResponseKeys] = useState<string[]>([]);

  const updateResponseVariableMapping = (
    responseVariableMapping: ResponseVariableMapping[],
  ) => onOptionsChange({ ...options, responseVariableMapping });

  const ws = usePartySocket({
    host: env.NEXT_PUBLIC_PARTYKIT_HOST,
    room: `${user?.id}/${typebot?.id}/webhooks`,

    onMessage(e) {
      setReceivedData(e.data);
      setResponseKeys(getDeepKeys(JSON.parse(e.data)));
      setWebsocketStatus("closed");
      ws.close();
    },
    onError(e) {
      console.log("error", e);
    },
    startClosed: true,
  });

  const listenForTestEvent = () => {
    ws.reconnect();
    setWebsocketStatus("opened");
  };

  const ResponseMappingInputs = useMemo(
    () =>
      function Component(props: TableListItemProps<ResponseVariableMapping>) {
        return <DataVariableInputs {...props} dataItems={responseKeys} />;
      },
    [responseKeys],
  );

  const urlBase = typebot
    ? `${env.NEXT_PUBLIC_VIEWER_URL[0]}/api/v1/typebots/${typebot.id}/blocks/${blockId}/executeWebhook`
    : "";

  return (
    <Stack>
      <Tabs size="sm" isFitted variant="">
        <TabList>
          <Tab>Test URL</Tab>
          <Tab>Production URL</Tab>
        </TabList>

        <TabPanels>
          <TabPanel>
            {typebot && (
              <FormControl as={Stack}>
                <InputGroup size="sm">
                  <Input type={"text"} defaultValue={urlBase} />
                  <InputRightElement width="60px">
                    <CopyButton size="sm" textToCopy={urlBase} />
                  </InputRightElement>
                </InputGroup>
              </FormControl>
            )}
          </TabPanel>
          <TabPanel>
            {typebot && (
              <FormControl as={Stack}>
                <InputGroup size="sm">
                  <Input
                    type={"text"}
                    defaultValue={`${urlBase}/<result_id>`}
                  />
                  <InputRightElement width="60px">
                    <CopyButton
                      size="sm"
                      textToCopy={`${urlBase}/<result_id>`}
                    />
                  </InputRightElement>
                </InputGroup>
                <FormHelperText mt="0">
                  You can easily get the Result ID{" "}
                  <TextLink
                    isExternal
                    href="https://docs.typebot.io/editor/blocks/logic/set-variable#result-id"
                  >
                    with a Set variable block
                  </TextLink>
                  .
                </FormHelperText>
              </FormControl>
            )}
          </TabPanel>
        </TabPanels>
      </Tabs>

      <Button
        onClick={listenForTestEvent}
        colorScheme="blue"
        isLoading={websocketStatus === "opened"}
      >
        Listen for test event
      </Button>
      {websocketStatus === "opened" && (
        <Stack borderWidth="1px" p="4" borderRadius="md" spacing="3">
          <Text fontSize="sm">
            Waiting for an{" "}
            <TextLink
              href={"https://docs.typebot.io/api-reference/authentication"}
              isExternal
            >
              authenticated
            </TextLink>
            POST request to the Test URL...
          </Text>
        </Stack>
      )}
      {receivedData && (
        <CodeEditor isReadOnly lang="json" value={receivedData} />
      )}
      {(receivedData ||
        (options?.responseVariableMapping &&
          options.responseVariableMapping.length > 0)) && (
        <Accordion allowMultiple>
          <AccordionItem>
            <AccordionButton justifyContent="space-between">
              Save in variables
              <AccordionIcon />
            </AccordionButton>
            <AccordionPanel pt="4">
              <TableList<ResponseVariableMapping>
                initialItems={options?.responseVariableMapping}
                onItemsChange={updateResponseVariableMapping}
                addLabel="Add an entry"
              >
                {(props) => <ResponseMappingInputs {...props} />}
              </TableList>
            </AccordionPanel>
          </AccordionItem>
        </Accordion>
      )}
    </Stack>
  );
};

```

This happens when I try to trigger the autocomplete drodown on in `variant=""`. It didn't display anything so I checked the logs and saw that error

**Comment by kekswar** [comment]
Hi! Have the same problem. 
Work in  monorepo and typescript constantyl crashes in my monorepo
Very annoying and I seem to have tried everything but can't seem to solve this problem. Only restarting ts server helps :( 

```
 Err 78525 [23:48:06.354] Exception on executing command delayed processing of request 1216:

    Cannot read properties of undefined (reading 'updateFromProject')

    TypeError: Cannot read properties of undefined (reading 'updateFromProject')
        at synchronizeHostData (/Users/kekswar/frontend/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/typescript.js:151370:14)
        at Object.getProgram (/Users/kekswar/frontend/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/typescript.js:151555:5)
        at getSource (/Users/kekswar/frontend/node_modules/.pnpm/next@15.1.2_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-dom@19._e4gvlxth7dn5lhvsn23imq3fai/node_modules/next/dist/server/typescript/utils.js:98:69)
        at proxy.getSemanticDiagnostics (/Users/kekswar/frontend/node_modules/.pnpm/next@15.1.2_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-dom@19._e4gvlxth7dn5lhvsn23imq3fai/node_modules/next/dist/server/typescript/index.js:103:49)
        at IpcIOSession.semanticCheck (/Users/kekswar/frontend/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/typescript.js:193371:125)
        at doSemanticCheck (/Users/kekswar/frontend/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/typescript.js:193444:12)
        at /Users/kekswar/frontend/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/typescript.js:193492:49
        at MultistepOperation.executeAction (/Users/kekswar/frontend/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/typescript.js:192055:9)
        at /Users/kekswar/frontend/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/typescript.js:192028:71
        at IpcIOSession.executeWithRequestId (/Users/kekswar/frontend/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/typescript.js:195207:14)
        at Object.executeWithRequestId (/Users/kekswar/frontend/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/typescript.js:193102:74)
        at Immediate._onImmediate (/Users/kekswar/frontend/node_modules/.pnpm/typescript@5.7.2/node_modules/typescript/lib/typescript.js:192028:28)
        at process.processImmediate (node:internal/timers:485:21)
```

**Comment by felixSchober** [comment]
Can confirm - Have exactly the same issue and need to restart TS server every 5 - 10 minutes.

**Comment by antoinerousseau** [comment]
same here :(
```
2025-07-22 16:51:09.685 [error] [vscode.typescript-language-features] provider FAILED
2025-07-22 16:51:09.685 [error] Error: <semantic> TypeScript Server Error (5.8.3)
Cannot read properties of undefined (reading 'updateFromProject')
TypeError: Cannot read properties of undefined (reading 'updateFromProject')
    at synchronizeHostData (/Users/antoine/Code/shotgun/node_modules/.pnpm/typescript@5.8.3/node_modules/typescript/lib/typescript.js:151808:14)
    at Object.getProgram (/Users/antoine/Code/shotgun/node_modules/.pnpm/typescript@5.8.3/node_modules/typescript/lib/typescript.js:151993:5)
    at getSource (/Users/antoine/Code/shotgun/node_modules/.pnpm/next@15.3.4_@babel+core@7.27.4_@opentelemetry+api@1.9.0_@playwright+test@1.52.0_react-dom@19._7qsh2nnwenwndufkwnvwcfa2u4/node_modules/next/dist/server/typescript/utils.js:154:69)
    at getMetadataExport (/Users/antoine/Code/shotgun/node_modules/.pnpm/next@15.3.4_@babel+core@7.27.4_@opentelemetry+api@1.9.0_@playwright+test@1.52.0_react-dom@19._7qsh2nnwenwndufkwnvwcfa2u4/node_modules/next/dist/server/typescript/rules/metadata.js:18:41)
    at Object.getCompletionEntryDetails (/Users/antoine/Code/shotgun/node_modules/.pnpm/next@15.3.4_@babel+core@7.27.4_@opentelemetry+api@1.9.0_@playwright+test@1.52.0_react-dom@19._7qsh2nnwenwndufkwnvwcfa2u4/node_modules/next/dist/server/typescript/rules/metadata.js:278:22)
    at proxy.getCompletionEntryDetails (/Users/antoine/Code/shotgun/node_modules/.pnpm/next@15.3.4_@babel+core@7.27.4_@opentelemetry+api@1.9.0_@playwright+test@1.52.0_react-dom@19._7qsh2nnwenwndufkwnvwcfa2u4/node_modules/next/dist/server/typescript/index.js:88:70)
    at Proxy.<anonymous> (/Users/antoine/.cursor/extensions/styled-components.vscode-styled-components-1.7.8/node_modules/typescript-template-language-service-decorator/lib/template-language-service-decorator.js:97:24)
    at /Users/antoine/Code/shotgun/node_modules/.pnpm/typescript@5.8.3/node_modules/typescript/lib/typescript.js:194945:43
    at mapDefined (/Users/antoine/Code/shotgun/node_modules/.pnpm/typescript@5.8.3/node_modules/typescript/lib/typescript.js:2606:22)
    at IpcIOSession.getCompletionEntryDetails (/Users/antoine/Code/shotgun/node_modules/.pnpm/typescript@5.8.3/node_modules/typescript/lib/typescript.js:194943:20)
    at completionEntryDetails (/Users/antoine/Code/shotgun/node_modules/.pnpm/typescript@5.8.3/node_modules/typescript/lib/typescript.js:193184:43)
    at /Users/antoine/Code/shotgun/node_modules/.pnpm/typescript@5.8.3/node_modules/typescript/lib/typescript.js:195676:15
    at IpcIOSession.executeWithRequestId (/Users/antoine/Code/shotgun/node_modules/.pnpm/typescript@5.8.3/node_modules/typescript/lib/typescript.js:195665:14)
    at IpcIOSession.executeCommand (/Users/antoine/Code/shotgun/node_modules/.pnpm/typescript@5.8.3/node_modules/typescript/lib/typescript.js:195674:29)
    at IpcIOSession.onMessage (/Users/antoine/Code/shotgun/node_modules/.pnpm/typescript@5.8.3/node_modules/typescript/lib/typescript.js:195722:68)
    at process.<anonymous> (/Users/antoine/Code/shotgun/node_modules/.pnpm/typescript@5.8.3/node_modules/typescript/lib/_tsserver.js:519:14)
    at process.emit (node:events:524:28)
    at emit (node:internal/child_process:950:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
	at n.create (/Applications/Cursor.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:2:494958)
	at y.dispatchResponse (/Applications/Cursor.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:2:488928)
	at y.dispatchMessage (/Applications/Cursor.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:2:487726)
	at ChildProcess.<anonymous> (/Applications/Cursor.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:2:487219)
	at ChildProcess.emit (node:events:524:28)
	at ChildProcess.emit (node:domain:489:12)
	at emit (node:internal/child_process:950:14)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```
