### ISSUE TITLE
Internal compiler error: "DataCloneError: Function object could not be cloned."

### ISSUE THREAD

**Issue by evanw** [microsoft/TypeScript#52463]
# Bug Report

### 🔎 Search Terms

DataCloneError: Function object could not be cloned.

### 🕗 Version & Regression Information

- This crashes all versions of TypeScript on the playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBAglC8UBCUIA9gQHYBMDOUAwlAPxQAMUAXFAIxA)

### 💻 Code

```ts
type A = B extends C ? 0 : 1
```

### 🙁 Actual behavior

Firefox:

```
DataCloneError: Function object could not be cloned.
```

Chrome:

```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': function(Kr){return void(Kr.externalModuleIndicator=dn(Kr))} could not be cloned.
    at https://typescript.azureedge.net/cdn/4.9.4/monaco/min/vs/base/worker/workerMain.js:11:383
    at Object.sendMessage (https://typescript.azureedge.net/cdn/4.9.4/monaco/min/vs/base/worker/workerMain.js:22:17680)
    at L._send (https://typescript.azureedge.net/cdn/4.9.4/monaco/min/vs/base/worker/workerMain.js:22:15521)
    at https://typescript.azureedge.net/cdn/4.9.4/monaco/min/vs/base/worker/workerMain.js:22:14591
```

Safari:

```
Unhandled Promise Rejection: DataCloneError: The object can not be cloned.
```

### 🙂 Expected behavior

I expected the TypeScript compiler to not crash.

**Comment by evanw** [comment]
I can also get the TypeScript compiler to crash in a different way with [the following code](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBAglC8UBCUIA9gQHYBMDOUAllgGYQBOUAwqhtvlACJQD8UADFAFxQCMQA):

```ts
type A = B extends infer C extends D ? 0 : 1
```

This crashes with the following error message:

```
tsMode.js:8 Uncaught (in promise) Error: Debug Failure. This is unknown parent for type parameter: 192
    at le (tsWorker.js:243:36992)
    at L (tsWorker.js:243:40249)
    at i (tsWorker.js:243:51044)
    at Ln (tsWorker.js:243:55268)
    at q (tsWorker.js:241:572774)
    at o.<computed> (tsWorker.js:241:576871)
    at Object.oe [as visitEachChild] (tsWorker.js:241:576325)
    at Ln (tsWorker.js:243:57168)
    at q (tsWorker.js:241:572774)
    at o.<computed> (tsWorker.js:241:581513)
```

**Comment by DanielRosenwasser** [comment]
This is a playground error, right? Just validating that you can't get this locally.

I've been meaning to file an issue about this. The playground and monaco predate TSServer, even though they passes messages back and forth in a similar manner that requires basic serializing.

My guess based on prior issues (and issues I've hit recently) is that we haven't "sanitized" diagnostic objects that refer back to a source file object when we send them across workers.

**Comment by evanw** [comment]
Yes, I can't get this locally. So that means it's playground-only.

I can reproduce the other crash I reported in https://github.com/microsoft/TypeScript/issues/52463#issuecomment-1406792138 locally, although it looks like that was fixed two weeks ago: https://github.com/microsoft/TypeScript/pull/52032. So never mind about that one.

**Comment by fatcerberus** [comment]
I’m not seeing this error on iOS Safari - the playground seems to operate normally.  Is this browser-specific?

**Comment by RyanCavanaugh** [comment]
The Playground now handles the original example without a worker cloning failure. The current Nightly build (6.0.0-dev.20260416) reports the expected TS2304 diagnostics for `B` and `C`; no `DataCloneError` or `postMessage` cloning error occurs.
