### ISSUE TITLE
JSX comments break Transformer API in TS 5.0 beta

### ISSUE THREAD

**Issue by zOadT** [microsoft/TypeScript#52479]
# Bug Report

### 🔎 Search Terms

transformer jsx comment 5.0

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.9.4 and 5.0.0-beta
- Still present in @next

### ⏯ Playground Link

Not available because Playground has not transformer options

### 💻 Code

Given the following file:

```typescript
// src/index.tsx
function test () {
  return <>
    {/* This comment breaks the transformer */}
  </>
}
```

and the following transformer

```javascript
// transformer.js
const ts = require('typescript');

// noop transformer
module.exports = (context) => {
  function visitor(node) {
    return ts.visitEachChild(node, visitor, context);
  }
  return (node) => {
    return ts.visitNode(node, visitor, context);
  };
}
```

TypeScript throws this Error when compiling

```
Error: Debug Failure.
    at visitEachChildOfJsxExpression (/.../node_modules/typescript/lib/typescript.js:85838:19)
    at Object.visitEachChild (/.../node_modules/typescript/lib/typescript.js:84879:35)
    at visitor (/.../transformer.js:6:13)
    [...]
```

To run this I used this setup with Webpack and ts-loader: (I tried to keep it as short as possible)

```javascript
// package.json
{
  "name": "ts-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack --mode production"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^18.2.0",
    "ts-loader": "^9.4.2",
    "typescript": "^5.0.0-beta",
    "webpack": "^5.75.0",
    "webpack-cli": "^5.0.1"
  }
}
```

```javascript
// webpack.config.js
const transformer = require('./transformer');

module.exports = {
  resolve: {
    extensions: [".tsx", ".ts", ".js"],
  },
  module: {
    rules: [{
      test: /\.tsx?$/,
      use: {
        loader: 'ts-loader',
        options: {
          getCustomTransformers: (program) => ({
            before: [transformer],
          }),
        },
      },
    }]
  },
}
```

```javascript
// tsconfig.json
{
    "compilerOptions": {
        "jsx": "react-jsx"
    }
}
```

### 🙁 Actual behavior

Running `npm run build` throws the described error

### 🙂 Expected behavior

No error is thrown

**Comment by jakebailey** [comment]
This looks like a bug I introduced in #49929.

I'll send a PR to fix it.
