### ISSUE TITLE
Assertion failure on completions for derived class with computed base property name

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#52664]
```ts
export const SOME_CONSTANT = 'SOME_TEXT';

export class Base {
    [SOME_CONSTANT]: boolean;
}

export class Derived extends Base {
    /*$*/
}
```

Request class snippet completions at `/*$*/`.

```
Message: Error processing request. Debug Failure.
Error: Debug Failure.
    at Object.getTextOfPropertyName (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:15429:25)
    at Object.getMemberOverrideModifierStatus (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:86231:63)
    at /vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:135765:32
    at Object.addNewNodeForMemberSymbol (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:161425:21)
    at getEntryForMemberCompletion (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:135751:24)
    at createCompletionEntry (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:135603:23)
    at getCompletionEntriesFromSymbols (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:136106:29)
    at completionInfoFromData (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:135415:31)
    at Object.getCompletionsAtPosition (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:135275:36)
    at Object.getCompletionsAtPosition (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:169151:35)
    at IpcIOSession.Session.getCompletions (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:181300:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:179973:61)
    at /vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:182034:96
    at IpcIOSession.Session.executeWithRequestId (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:182025:28)
    at IpcIOSession.Session.executeCommand (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:182034:41)
    at IpcIOSession.Session.onMessage (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:182062:35)
    at process.<anonymous> (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:186218:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by DanielRosenwasser** [comment]
Thank you @a-tarsyuk!
