### ISSUE TITLE
Assertion failure when class member snippet relies on default-exported type

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#52662]
```ts
// @filename: other.ts
export default class Other {}

// @filename: base.ts
import Other from "./other";

export class Base {
    foo(): Other {
        throw new Error("");
    }
}

// @filename: derived.ts
import { Base } from "./base";

export class Derived extends Base {
    /*$*/
}
```

Request completions with class member snippets and snippet completions enabled.

```
Message: Error processing request. Debug Failure.
Error: Debug Failure.
    at Object.addImportFromExportedSymbol (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:156324:70)
    at /vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:161889:63
    at Array.forEach (<anonymous>)
    at importSymbols (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:161889:21)
    at createSignatureDeclarationFromSignature (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:161567:25)
    at outputMethod (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:161495:30)
    at Object.addNewNodeForMemberSymbol (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:161474:25)
    at getEntryForMemberCompletion (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:135751:24)
    at createCompletionEntry (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:135603:23)
    at getCompletionEntriesFromSymbols (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:136106:29)
    at completionInfoFromData (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:135415:31)
    at Object.getCompletionsAtPosition (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:135275:36)
    at Object.getCompletionsAtPosition (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:169151:35)
    at IpcIOSession.Session.getCompletions (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:181300:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:179973:61)
    at /vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:182034:96
    at IpcIOSession.Session.executeWithRequestId (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:182025:28)
```

**Comment by DanielRosenwasser** [comment]
Probably all related:

* https://github.com/microsoft/TypeScript/issues/52509
* https://github.com/microsoft/TypeScript/issues/52163
* https://github.com/microsoft/TypeScript/issues/52163
* https://github.com/microsoft/TypeScript/issues/51959
* https://github.com/microsoft/TypeScript/issues/51957
* https://github.com/microsoft/TypeScript/issues/51956
* https://github.com/microsoft/TypeScript/issues/48361
* https://github.com/microsoft/TypeScript/issues/43019

I'll try closing these and we'll revisit if they pop back up.
