### ISSUE TITLE
Assertion failure in derived class completion 

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#52749]
<details>
<summary>:warning: Note that typescript-4.9.5 also had errors :warning:</summary>

```
Req #5981 - completionInfo
    at processChildNode (/typescript-4.9.5/lib/tsserver.js:150877:38)
    at /typescript-4.9.5/lib/tsserver.js:150813:21
    at visitNode (/typescript-4.9.5/lib/tsserver.js:31215:24)
    at forEachChildInTypeReference (/typescript-4.9.5/lib/tsserver.js:31433:20)
    at Object.forEachChild (/typescript-4.9.5/lib/tsserver.js:31998:47)
    at processNode (/typescript-4.9.5/lib/tsserver.js:150812:20)
    at processChildNode (/typescript-4.9.5/lib/tsserver.js:150884:21)
    at processChildNodes (/typescript-4.9.5/lib/tsserver.js:150939:48)
    at /typescript-4.9.5/lib/tsserver.js:150815:21
    at visitNodes (/typescript-4.9.5/lib/tsserver.js:31220:24)
    at forEachChildInUnionOrIntersectionType (/typescript-4.9.5/lib/tsserver.js:31915:16)
    at Object.forEachChild (/typescript-4.9.5/lib/tsserver.js:31998:47)
    at processNode (/typescript-4.9.5/lib/tsserver.js:150812:20)
    at processChildNode (/typescript-4.9.5/lib/tsserver.js:150884:21)
    at /typescript-4.9.5/lib/tsserver.js:150813:21
    at visitNode (/typescript-4.9.5/lib/tsserver.js:31215:24)
    at forEachChildInMethodDeclaration (/typescript-4.9.5/lib/tsserver.js:31364:17)
    at Object.forEachChild (/typescript-4.9.5/lib/tsserver.js:31998:47)
    at processNode (/typescript-4.9.5/lib/tsserver.js:150812:20)
    at formatSpanWorker (/typescript-4.9.5/lib/tsserver.js:150591:17)
    at /typescript-4.9.5/lib/tsserver.js:150553:140
    at Object.getFormattingScanner (/typescript-4.9.5/lib/tsserver.js:149173:23)
    at Object.formatNodeGivenIndentation (/typescript-4.9.5/lib/tsserver.js:150553:31)
    at /typescript-4.9.5/lib/tsserver.js:135982:42
    at Object.flatMap (/typescript-4.9.5/lib/tsserver.js:524:25)
    at Object.printAndFormatSnippetList (/typescript-4.9.5/lib/tsserver.js:135980:34)
    at getEntryForMemberCompletion (/typescript-4.9.5/lib/tsserver.js:135784:42)
    at createCompletionEntry (/typescript-4.9.5/lib/tsserver.js:135603:23)
    at getCompletionEntriesFromSymbols (/typescript-4.9.5/lib/tsserver.js:136106:29)
    at completionInfoFromData (/typescript-4.9.5/lib/tsserver.js:135415:31)
    at Object.getCompletionsAtPosition (/typescript-4.9.5/lib/tsserver.js:135275:36)
    at Object.getCompletionsAtPosition (/typescript-4.9.5/lib/tsserver.js:169151:35)
    at IOSession.Session.getCompletions (/typescript-4.9.5/lib/tsserver.js:181300:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/typescript-4.9.5/lib/tsserver.js:179973:61)
    at /typescript-4.9.5/lib/tsserver.js:182034:96
    at IOSession.Session.executeWithRequestId (/typescript-4.9.5/lib/tsserver.js:182025:28)
    at IOSession.Session.executeCommand (/typescript-4.9.5/lib/tsserver.js:182034:41)
    at IOSession.Session.onMessage (/typescript-4.9.5/lib/tsserver.js:182062:35)
    at Interface.<anonymous> (/typescript-4.9.5/lib/tsserver.js:186188:31)
```

</details>

```
Req #5981 - completionInfo
    at processChildNode (/typescript-5.0.0-dev.20230206/lib/tsserver.js:165869:17)
    at /typescript-5.0.0-dev.20230206/lib/tsserver.js:165800:9
    at visitNode2 (/typescript-5.0.0-dev.20230206/lib/tsserver.js:29285:18)
    at forEachChildInTypeReference (/typescript-5.0.0-dev.20230206/lib/tsserver.js:29391:12)
    at forEachChild (/typescript-5.0.0-dev.20230206/lib/tsserver.js:29799:35)
    at processNode (/typescript-5.0.0-dev.20230206/lib/tsserver.js:165797:5)
    at processChildNode (/typescript-5.0.0-dev.20230206/lib/tsserver.js:165876:7)
    at processChildNodes (/typescript-5.0.0-dev.20230206/lib/tsserver.js:165919:32)
    at /typescript-5.0.0-dev.20230206/lib/tsserver.js:165813:9
    at visitNodes (/typescript-5.0.0-dev.20230206/lib/tsserver.js:29290:14)
    at forEachChildInUnionOrIntersectionType (/typescript-5.0.0-dev.20230206/lib/tsserver.js:29746:10)
    at forEachChild (/typescript-5.0.0-dev.20230206/lib/tsserver.js:29799:35)
    at processNode (/typescript-5.0.0-dev.20230206/lib/tsserver.js:165797:5)
    at processChildNode (/typescript-5.0.0-dev.20230206/lib/tsserver.js:165876:7)
    at /typescript-5.0.0-dev.20230206/lib/tsserver.js:165800:9
    at visitNode2 (/typescript-5.0.0-dev.20230206/lib/tsserver.js:29285:18)
    at forEachChildInMethodDeclaration (/typescript-5.0.0-dev.20230206/lib/tsserver.js:29364:321)
    at forEachChild (/typescript-5.0.0-dev.20230206/lib/tsserver.js:29799:35)
    at processNode (/typescript-5.0.0-dev.20230206/lib/tsserver.js:165797:5)
    at formatSpanWorker (/typescript-5.0.0-dev.20230206/lib/tsserver.js:165605:5)
    at /typescript-5.0.0-dev.20230206/lib/tsserver.js:165545:105
    at getFormattingScanner (/typescript-5.0.0-dev.20230206/lib/tsserver.js:164361:15)
    at Object.formatNodeGivenIndentation (/typescript-5.0.0-dev.20230206/lib/tsserver.js:165545:10)
    at /typescript-5.0.0-dev.20230206/lib/tsserver.js:148618:36
    at flatMap (/typescript-5.0.0-dev.20230206/lib/tsserver.js:2555:17)
    at Object.printAndFormatSnippetList (/typescript-5.0.0-dev.20230206/lib/tsserver.js:148616:21)
    at getEntryForMemberCompletion (/typescript-5.0.0-dev.20230206/lib/tsserver.js:148386:28)
    at createCompletionEntry (/typescript-5.0.0-dev.20230206/lib/tsserver.js:148247:64)
    at getCompletionEntriesFromSymbols (/typescript-5.0.0-dev.20230206/lib/tsserver.js:148786:19)
    at completionInfoFromData (/typescript-5.0.0-dev.20230206/lib/tsserver.js:147856:23)
    at Object.getCompletionsAtPosition (/typescript-5.0.0-dev.20230206/lib/tsserver.js:147678:24)
    at Object.getCompletionsAtPosition2 [as getCompletionsAtPosition] (/typescript-5.0.0-dev.20230206/lib/tsserver.js:134786:35)
    at IOSession.getCompletions (/typescript-5.0.0-dev.20230206/lib/tsserver.js:178387:54)
    at completionInfo (/typescript-5.0.0-dev.20230206/lib/tsserver.js:176798:43)
    at /typescript-5.0.0-dev.20230206/lib/tsserver.js:179151:69
    at IOSession.executeWithRequestId (/typescript-5.0.0-dev.20230206/lib/tsserver.js:179143:14)
    at IOSession.executeCommand (/typescript-5.0.0-dev.20230206/lib/tsserver.js:179151:29)
    at IOSession.onMessage (/typescript-5.0.0-dev.20230206/lib/tsserver.js:179193:51)
    at Interface.<anonymous> (/typescript-5.0.0-dev.20230206/lib/tsserver.js:180737:14)
```
That is a filtered view of the text. To see the raw error text, go to RepoResults2/angular.angular-cli.rawError.txt</code> in the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=145768&view=artifacts&type=publishedArtifacts">artifact folder</a></li>

<details>
<summary><h3>Last few requests</h3></summary>

```json
{"seq":5978,"type":"request","command":"references","arguments":{"file":"@PROJECT_ROOT@/packages/angular_devkit/core/src/logger/logger.ts","line":2,"offset":4}}
{"seq":5979,"type":"request","command":"definitionAndBoundSpan","arguments":{"file":"@PROJECT_ROOT@/packages/angular_devkit/core/src/logger/logger.ts","line":10,"offset":23}}
{"seq":5980,"type":"request","command":"completionInfo","arguments":{"file":"@PROJECT_ROOT@/packages/angular_devkit/core/src/logger/logger.ts","line":27,"offset":34,"includeExternalModuleExports":false,"triggerKind":1}}
{"seq":5981,"type":"request","command":"completionInfo","arguments":{"file":"@PROJECT_ROOT@/packages/angular_devkit/core/src/logger/logger.ts","line":33,"offset":49,"includeExternalModuleExports":false,"triggerKind":1}}

```

</details>

<details>
<summary><h3>Repro Steps</h3></summary>
<ol>
<li><code>git clone https://github.com/angular/angular-cli --recurse-submodules</code></li>
<li>In dir <code>angular-cli</code>, run <code>git reset --hard bf3be56db8b3a1ef8a0e02dfc5de914651d8ec93</code></li>
<li><details><summary>Install packages (exact steps are below, but it might be easier to follow the repo readme)</summary><ol>
  <li>In dir <code>angular-cli</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/legacy-cli/e2e/assets/13.0-project</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/legacy-cli/e2e/assets/add-collection-peer-bad</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/legacy-cli/e2e/assets/add-collection-peer-good</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/legacy-cli/e2e/assets/add-collection</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/legacy-cli/e2e/assets/nested-schematic-dependency</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/legacy-cli/e2e/assets/nested-schematic-main</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/legacy-cli/e2e/assets/schematic-allow-scripts</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/legacy-cli/e2e/assets/schematic-boolean-option-negated</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/legacy-cli/e2e/assets/webpack/test-app</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/legacy-cli/e2e/ng-snapshot</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/schematics/update/packages/update-base</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/schematics/update/packages/update-migrations-external</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/schematics/update/packages/update-migrations</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/schematics/update/packages/update-package-group-1</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/schematics/update/packages/update-package-group-2</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/schematics/update/packages/update-peer-dependencies-1</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/schematics/update/packages/update-peer-dependencies-2</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/schematics/update/packages/update-peer-dependencies-angular-5-2</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
  <li>In dir <code>angular-cli/tests/schematics/update/packages/update-peer-dependencies-angular-5</code>, run <code>yarn install --ignore-engines --ignore-scripts --silent</code></li>
</ol></details>
<li>Back in the initial folder, download <code>RepoResults2/angular.angular-cli.replay.txt</code> from the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=145768&view=artifacts&type=publishedArtifacts">artifact folder</a></li>
<li><code>npm install --no-save @typescript/server-replay</code></li>
<li><code>npx tsreplay ./angular-cli ./angular.angular-cli.replay.txt path/to/tsserver.js</code></li>
<li><code>npx tsreplay --help</code> to learn about helpful switches for debugging, logging, etc</li>
</ol>
</details>

_Originally posted by @typescript-bot in https://github.com/microsoft/TypeScript/issues/52645#issuecomment-1419980275_

**Comment by DanielRosenwasser** [comment]
I was able to get this in an empty class that derives from `Observable<any>` from RxJS. You can pare down the entirety of `Observable` to just the `pipe` overloads, and this will repro:

```ts
// @filename: 

// @filename: node_modules/rxjs/internal/Observable.d.ts
export class Observable<T> {
    pipe(): Observable<T>;
    pipe<A>(): Observable<A>;
    pipe<A, B>(): Observable<B>;
    pipe<A, B, C>(): Observable<C>;
    pipe<A, B, C, D>(): Observable<D>;
    pipe<A, B, C, D, E>(): Observable<E>;
    pipe<A, B, C, D, E, F>(): Observable<F>;
    pipe<A, B, C, D, E, F, G>(): Observable<G>;
    pipe<A, B, C, D, E, F, G, H>(): Observable<H>;
    pipe<A, B, C, D, E, F, G, H, I>(): Observable<I>;
    pipe<A, B, C, D, E, F, G, H, I>(): Observable<unknown>;
}
```

**However**, I didn't manage to quickly get a fast/easy actual repro. So there's likely more going on here.
