### ISSUE TITLE
'Extract type' from property signature with erroneous initializer causes assertion failure

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#52751]
```ts
type Foo = [|{
    x: string = someString;
}|]
```

Request an "extract to type alias" refactoring on the specified `[|range|]`:

```
 Debug Failure. False expression: Token end is child end
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (typescript/lib/tsserver.js:165873:17)
    at typescript/lib/tsserver.js:165804:9
    at visitNode2 (typescript/lib/tsserver.js:29284:18)
    at forEachChildInPropertySignature (typescript/lib/tsserver.js:29340:167)
    at forEachChild (typescript/lib/tsserver.js:29798:35)
    at processNode (typescript/lib/tsserver.js:165801:5)
    at processChildNode (typescript/lib/tsserver.js:165880:7)
    at processChildNodes (typescript/lib/tsserver.js:165923:32)
    at typescript/lib/tsserver.js:165817:9
    at visitNodes (typescript/lib/tsserver.js:29289:14)
    at forEachChildInTypeLiteral (typescript/lib/tsserver.js:29399:12)
    at forEachChild (typescript/lib/tsserver.js:29798:35)
    at processNode (typescript/lib/tsserver.js:165801:5)
    at processChildNode (typescript/lib/tsserver.js:165880:7)
    at typescript/lib/tsserver.js:165804:9
    at visitNode2 (typescript/lib/tsserver.js:29284:18)
    at forEachChildInTypeAliasDeclaration (typescript/lib/tsserver.js:29575:144)
    at forEachChild (typescript/lib/tsserver.js:29798:35)
    at processNode (typescript/lib/tsserver.js:165801:5)
    at formatSpanWorker (typescript/lib/tsserver.js:165609:5)
    at typescript/lib/tsserver.js:165549:105
    at getFormattingScanner (typescript/lib/tsserver.js:164365:15)
    at Object.formatNodeGivenIndentation (typescript/lib/tsserver.js:165549:10)
    at getFormattedTextOfNode (typescript/lib/tsserver.js:163762:43)
    at format (typescript/lib/tsserver.js:163742:27)
    at computeNewText (typescript/lib/tsserver.js:163743:219)
    at typescript/lib/tsserver.js:163704:25
    at mapDefined (typescript/lib/tsserver.js:2627:22)
    at typescript/lib/tsserver.js:163702:28
    at mapDefined (typescript/lib/tsserver.js:2627:22)
    at Object.getTextChangesFromChanges (typescript/lib/tsserver.js:163696:12)
    at ChangeTracker.getChanges (typescript/lib/tsserver.js:163585:35)
    at ChangeTracker.with (typescript/lib/tsserver.js:163083:20)
    at Object.getRefactorEditsToExtractType [as getEditsForAction] (typescript/lib/tsserver.js:156988:60)
    at Object.getEditsForRefactor (typescript/lib/tsserver.js:156469:31)
    at Object.getEditsForRefactor2 [as getEditsForRefactor] (typescript/lib/tsserver.js:135592:32)
    at IpcIOSession.getEditsForRefactor (typescript/lib/tsserver.js:178779:49)
    at getEditsForRefactor (typescript/lib/tsserver.js:177034:43)
```

**Comment by DanielRosenwasser** [comment]
As usual, this has to do with the visitor with `visitEachChild` not actually visiting the `initializer` property on `PropertySignature`s, even though `forEachChild` does.

And as usual, it's awkward because `updatePropertySignature` doesn't give control over it. It really should either drop the property signature entirely or provide a mechanism to update it. I'd probably lean towards the latter

**Comment by rbuckton** [comment]
`initializer` on a property signature is a grammar error and isn't part of a syntactically valid AST. Supporting it in `visitEachChild` would require adding it to the `updatePropertySignature` factory method, which I'm not a fan of. I may look into an alternate approach, as I'd eventually like to find a way to remove these grammar-error-only node properties from nodes to reduce memory overhead.

**Comment by rbuckton** [comment]
I don't think the issue is with `visitEachChild`, since new positions are assigned by the printer via a `TextChangesWriter`.

**Comment by rbuckton** [comment]
> I don't think the issue is with `visitEachChild`, since new positions are assigned by the printer via a `TextChangesWriter`.

Ah, never mind. Both the emitter and `visitEachChild` need to be fixed for this to work.
