### ISSUE TITLE
Error: Debug Failure. False expression.

### ISSUE THREAD

**Issue by calebpitan** [microsoft/TypeScript#52952]
# Bug Report

### 🔎 Search Terms
debug failure, false expression, at object.first

### 🕗 Version & Regression Information

- This is a crash
- This is the behavior in every version I tried, 4.9.5, and I reviewed the FAQ for entries about it
- I was unable to test this on prior versions because I had other issues with prior versions that made me update to a later version

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

**stack trace:**
```bash
/Users/calebpitan/source/work/zendwa/emailing-service/node_modules/typescript/lib/tsc.js:99615
                throw e;
                ^

Error: Debug Failure. False expression.
    at Object.first (/Users/calebpitan/source/work/zendwa/emailing-service/node_modules/typescript/lib/tsc.js:990:18)
    at getSpecifierForModuleSymbol (/Users/calebpitan/source/work/zendwa/emailing-service/node_modules/typescript/lib/tsc.js:45313:36)
    at serializeAsAlias (/Users/calebpitan/source/work/zendwa/emailing-service/node_modules/typescript/lib/tsc.js:46419:107)
    at serializeSymbolWorker (/Users/calebpitan/source/work/zendwa/emailing-service/node_modules/typescript/lib/tsc.js:46084:25)
    at serializeSymbol (/Users/calebpitan/source/work/zendwa/emailing-service/node_modules/typescript/lib/tsc.js:45978:25)
    at /Users/calebpitan/source/work/zendwa/emailing-service/node_modules/typescript/lib/tsc.js:45963:29
    at Map.forEach (<anonymous>)
    at visitSymbolTable (/Users/calebpitan/source/work/zendwa/emailing-service/node_modules/typescript/lib/tsc.js:45962:81)
    at symbolTableToDeclarationStatements (/Users/calebpitan/source/work/zendwa/emailing-service/node_modules/typescript/lib/tsc.js:45847:17)
    at /Users/calebpitan/source/work/zendwa/emailing-service/node_modules/typescript/lib/tsc.js:44127:106

Node.js v18.11.0
```

**source: node_modules/typescript/lib/tsc.js**
```js
ts.firstOrUndefined = firstOrUndefined;
first(array) {
    ts.Debug.assert(array.length !== 0);
    return array[0];
}
ts.first = first;
```

**tsconfig.json:**
```json
{
  "compilerOptions": {
    "module": "ES2020",
    "moduleResolution": "node",
    "allowJs": true,
    "checkJs": false,
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "target": "ES2022",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "rootDir": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strict": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strictBindCallApply": true,
    "alwaysStrict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "paths": {
      "@/shared/*": ["backend-services-shared/src/*"], // contains .js files
      "@/utils/*": ["src/utils/*"],
      "@/modules/*": ["src/modules/*"]
    }
  },
  "exclude": ["node_modules", "test", "dist"]
}
```

### 🙁 Actual behavior

Error happens when I turn on `allowJs`

### 🙂 Expected behavior

`allowJs` shouldn't crash build process and should include the js files from the source in the build output 😔

**Comment by RyanCavanaugh** [comment]
We'd need a way to reproduce the problem. Do you have a repo we can clone, or other way to produce this crash?

**Comment by DanielRosenwasser** [comment]
To help narrow it down, you might be able to modify your `tsc.js` at `/Users/calebpitan/source/work/zendwa/emailing-service/node_modules/typescript/lib/tsc.js`

```diff
                  symbolTableToDeclarationStatements: function (symbolTable, enclosingDeclaration, flags, tracker, bundled) {
+                     console.log("FILE NAME", ts.getSourceFileOfNode(enclosingDeclaration).fileName);
                      return withContext(enclosingDeclaration, flags, tracker, function (context) { return symbolTableToDeclarationStatements(symbolTable, context, bundled); });
                  },
````

It starts at line 44125 in TypeScript 4.9.5's `tsc.js`.

**Comment by calebpitan** [comment]
Thanks to @DanielRosenwasser "debug snippet" which seems to have pointed me in the right direction. 
I inserted a console statement on that line and it was able to log the filenames till it crashed again. I inspected the last logged file before crash and found out it imported files that imported uninstalled modules/deps.

Instaliing the missing module fixed it and `tsc` could build successfully.

But this doesn't mean there's no problem. The problem is: the compiler couldn't resolve a specifier, why couldn't it just say so in an understandable, helpful error message, rather than an elusive jargon like "Error: Debug Failure. False expression."?

**Comment by fatcerberus** [comment]
> But this doesn't mean there's no problem. The problem is: the compiler couldn't resolve a specifier, why couldn't it just say so in an understandable, helpful error message, rather than an elusive jargon like "Error: Debug Failure. False expression."?

The message is cryptic because it's intended for TS developers, not end-users.  A debug assert being hit means the compiler has done something that, if it were functioning correctly, would *literally never happen* (in this case calling `first()` with an empty array); it always indicates a bug that has to be fixed elsewhere.  In this case, it sounds like there might be a missing check during module specifier resolution.

**Comment by ljharb** [comment]
I got this same error.

Specifically, it seems like I had `@types/gopd` installed, and then *also* made a `types/gopd/index.d.ts`, in which I provided my own definition that uses `export =`. @RyanCavanaugh can you reproduce it with that approach?

Note that it does not crash when my overload uses `export default`, but every CJS module's type is `export =` so I need to use that.

**Comment by ljharb** [comment]
@DanielRosenwasser when i apply that console log diff (which is slightly tricker in TS 5 beta), it's never hit - the line it dies on is `Debug.assert(node.kind !== 257 /* VariableDeclaration */);` inside `checkAliasSymbol`, and when i add a `console.log(node)` in front of it, i get:
<details>

```
<ref *2> Node4 {
  pos: 64,
  end: 88,
  kind: 257,
  id: 0,
  flags: 262144,
  modifierFlagsCache: 536875008,
  transformFlags: 0,
  parent: <ref *1> Node4 {
    pos: 59,
    end: 88,
    kind: 258,
    id: 0,
    flags: 262144,
    modifierFlagsCache: 536875008,
    transformFlags: 4194304,
    parent: Node4 {
      pos: 59,
      end: 89,
      kind: 240,
      id: 0,
      flags: 262144,
      modifierFlagsCache: 536875008,
      transformFlags: 4194304,
      parent: [Node4],
      original: undefined,
      emitNode: undefined,
      modifiers: undefined,
      declarationList: [Circular *1],
      jsDoc: undefined,
      flowNode: [Object]
    },
    original: undefined,
    emitNode: undefined,
    declarations: [
      [Circular *2],
      pos: 64,
      end: 88,
      hasTrailingComma: false,
      transformFlags: 0
    ]
  },
  original: undefined,
  emitNode: undefined,
  symbol: Symbol4 {
    flags: 2097152,
    escapedName: '$gOPD',
    declarations: [ [Circular *2] ],
    valueDeclaration: undefined,
    id: 24904,
    mergeId: 0,
    parent: undefined,
    members: undefined,
    exports: undefined,
    exportSymbol: undefined,
    constEnumOnlyModule: undefined,
    isReferenced: undefined,
    isAssigned: undefined,
    links: undefined
  },
  localSymbol: undefined,
  name: Identifier2 {
    pos: 64,
    end: 70,
    kind: 79,
    id: 0,
    flags: 262144,
    transformFlags: 0,
    parent: [Circular *2],
    original: undefined,
    emitNode: undefined,
    escapedText: '$gOPD',
    jsDoc: undefined,
    flowNode: { flags: 2064, antecedent: [Object], node: [Node4] },
    symbol: undefined
  },
  exclamationToken: undefined,
  type: undefined,
  initializer: <ref *3> Node4 {
    pos: 72,
    end: 88,
    kind: 210,
    id: 0,
    flags: 262144,
    modifierFlagsCache: 0,
    transformFlags: 0,
    parent: [Circular *2],
    original: undefined,
    emitNode: undefined,
    symbol: undefined,
    localSymbol: undefined,
    expression: Identifier2 {
      pos: 72,
      end: 80,
      kind: 79,
      id: 0,
      flags: 262144,
      transformFlags: 0,
      parent: [Circular *3],
      original: undefined,
      emitNode: undefined,
      escapedText: 'require',
      jsDoc: undefined,
      flowNode: [Object],
      symbol: undefined
    },
    questionDotToken: undefined,
    typeArguments: undefined,
    arguments: [
      [Node4],
      pos: 81,
      end: 87,
      hasTrailingComma: false,
      transformFlags: 0
    ]
  },
  jsDoc: [ jsDocCache: [] ]
}
```
</details>

Happy to debug live elsewhere, or with comments here, since it's consistently reproducible for me - just not in a branch i'm ready to share publicly.

**Comment by DanielRosenwasser** [comment]
That seems like a separate stack trace then, right? If so, what is the stack trace? And can you switch the `console.log(node)` to `console.log("FILE NAME", ts.getSourceFileOfNode(enclosingDeclaration).fileName);`?

**Comment by ljharb** [comment]
I can't, because `ts` is not defined in that function.

Stack trace:
```
$PWD/node_modules/typescript/lib/tsc.js:113967
      throw e;
      ^

Error: Debug Failure. False expression.
    at checkAliasSymbol ($PWD/node_modules/typescript/lib/tsc.js:78641:17)
    at checkVariableLikeDeclaration ($PWD/node_modules/typescript/lib/tsc.js:76204:7)
    at checkVariableDeclaration (/$PWD/node_modules/typescript/lib/tsc.js:76287:5)
    at checkSourceElementWorker ($PWD/node_modules/typescript/lib/tsc.js:79258:16)
    at checkSourceElement ($PWD/node_modules/typescript/lib/tsc.js:79089:7)
    at forEach ($PWD/node_modules/typescript/lib/tsc.js:37:22)
    at checkVariableStatement ($PWD/node_modules/typescript/lib/tsc.js:76297:5)
    at checkSourceElementWorker ($PWD/node_modules/typescript/lib/tsc.js:79227:16)
    at checkSourceElement ($PWD/node_modules/typescript/lib/tsc.js:79089:7)
    at forEach ($PWD/node_modules/typescript/lib/tsc.js:37:22)

Node.js v19.6.1
```

**Comment by ljharb** [comment]
@DanielRosenwasser actually turns out i was authoring my "declare module" incorrectly - i was doing `type x = whatever` instead of `function x`, and the `export =` with the `type` was what was crashing. Hope that helps :-)

**Comment by divmgl** [comment]
This is happening to me on version 5.3.3 of TypeScript. 

![image](https://github.com/microsoft/TypeScript/assets/5452298/626c1026-f0b5-4053-b050-14c21f7a3855)

I'm going to try 5.4.5 to see if this is resolved.

**Comment by DanielRosenwasser** [comment]
@divmgl that seems like an unrelated stack trace. Feel free to open a separate issue if you can provide a repro.

**Comment by zigcccc** [comment]
I'm getting this too after updating from `5.2.2` to `5.6.2`. Similar to others reporting this, I have `allowJs: true` set.

**Comment by Andarist** [comment]
@zigcccc could you prepare a repro case of the problem? you could try to remove as much lines from your project as possible (gradually) and bisect the problem this way to the minimal repro case

**Comment by jsnajdr** [comment]
I'm getting this error with TypeScript 5.8.2. This is how the call stack looks like:
```
Error: Debug Failure. False expression.
    at Object.isUndefinedIdentifierExpression (node_modules/typescript/lib/_tsc.js:50399:15)
    at typeFromExpression (node_modules/typescript/lib/_tsc.js:132353:22)
    at serializeTypeOfExpression (node_modules/typescript/lib/_tsc.js:132083:20)
    at Object.serializeTypeOfDeclaration (node_modules/typescript/lib/_tsc.js:132107:16)
    at serializeTypeForDeclaration (node_modules/typescript/lib/_tsc.js:52732:41)
    at serializeMaybeAliasAssignment (node_modules/typescript/lib/_tsc.js:54107:19)
    at serializeAsAlias (node_modules/typescript/lib/_tsc.js:53991:13)
    at serializeSymbolWorker (node_modules/typescript/lib/_tsc.js:53347:11)
    at serializeSymbol (node_modules/typescript/lib/_tsc.js:53211:11)
    at node_modules/typescript/lib/_tsc.js:53181:11
```
The node where this assertion fails is the `JSON` identifier in:
```ts
export default JSON;
```
where `JSON` is supposed to be the browser built-in.

The `isExpressionNode` check returns `false` because for `SyntaxKind.Identifier` the `isInExpressionContext` check return `false`. Because `SyntaxKind.ExportAssignment` is not considered an expression context. But it should, shouln't it? At least for a default export.

**Comment by RyanCavanaugh** [comment]
@jsnajdr I believe that's a different issue than this one; that one is #60692

**Comment by ernestostifano** [comment]
@RyanCavanaugh I managed to reproduce this here: https://github.com/ernestostifano/typescript-issue-1

Instructions in the README.

**Comment by SkReD** [comment]
@RyanCavanaugh Another reproduction - https://github.com/SkReD/ts-issue-repro-52952. Exception throws when one of packages is module and imports code from another which is not.

**Comment by RyanCavanaugh** [comment]
I can repro the crash in 5.8.3, but this passes in nightly, so it seems to have been fixed.
