### ISSUE TITLE
Debug assert in getAwaitedTypeNoAlias in test262 repo

### ISSUE THREAD

**Issue by jakebailey** [microsoft/TypeScript#53145]
```
/home/jabaile/work/TypeScript/src/compiler/program.ts:2734
            throw e;
            ^


Error: Debug Failure.
    at getAwaitedTypeNoAlias (/home/jabaile/work/TypeScript/src/compiler/checker.ts:39373:23)
    at Object.getAwaitedType (/home/jabaile/work/TypeScript/src/compiler/checker.ts:39252:29)
    at getIterationTypesOfMethod (/home/jabaile/work/TypeScript/src/compiler/checker.ts:41892:51)
    at getIterationTypesOfIteratorSlow (/home/jabaile/work/TypeScript/src/compiler/checker.ts:41927:13)
    at getIterationTypesOfIteratorWorker (/home/jabaile/work/TypeScript/src/compiler/checker.ts:41683:28)
    at getIterationTypesOfIterableSlow (/home/jabaile/work/TypeScript/src/compiler/checker.ts:41628:32)
    at getIterationTypesOfIterableWorker (/home/jabaile/work/TypeScript/src/compiler/checker.ts:41521:36)
    at getIterationTypesOfIterable (/home/jabaile/work/TypeScript/src/compiler/checker.ts:41396:36)
    at getIteratedTypeOrElementType (/home/jabaile/work/TypeScript/src/compiler/checker.ts:41167:36)
    at checkIteratedTypeOrElementType (/home/jabaile/work/TypeScript/src/compiler/checker.ts:41143:16)

Node.js v19.7.0
```

Using https://github.com/microsoft/typescript-error-deltas/blob/main/userTests/test262/tsconfig.json placed into the https://github.com/tc39/test262 repo. Narrowing it down to the file that's bad:

```json
    "files": [
        "test/language/expressions/async-generator/named-yield-star-async-next.js"
    ]
```

Here: https://github.com/tc39/test262/blob/main/test/language/expressions/async-generator/named-yield-star-async-next.js

**Comment by jakebailey** [comment]
It's not the only file, though. Excluding `"**/*yield*.js"` finally gets it to run.
