### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'exportSymbol') and  (reading 'flags')

### ISSUE THREAD

**Issue by gmoneh** [microsoft/TypeScript#53254]
# Bug Report

Getting an error " Cannot read properties of undefined", which usually means a failure to check for null or undefined on a variable being referenced. 

It is worth noting that this error does not occur when running a typescript build of the whole project using tsc. It only occurs when preparing deployable modules using rollup.js and the rollup-plugin-ts plugin for typescript manipulation. However, I do not think it is a rollup bug or a rollup plugin bug, since the code is deep into typescript code (see the call stacks) when the error occurs.

The call stack for the first (exportSymbol) is (line numbers are for typescript version 4.9.5):

    at checkExportsOnMergedDeclarationsWorker (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:82831:29)
    at D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:82822:52
    at addLazyDiagnostic (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87925:56)
    at checkExportsOnMergedDeclarations (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:82822:13)
    at checkTypeAliasDeclaration (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:86525:13)
    at checkSourceElementWorker (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87653:28)
    at checkSourceElement (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87476:17)
    at Object.forEach (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:181:30)
    at checkSourceFileWorker (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87851:20)
    at checkSourceFile (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87816:13)
    at checkSourceFileWithEagerDiagnostics (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87926:13)
    at getDiagnosticsWorker (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87937:17)
    at getDiagnostics (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87903:24)
    at Object.getEmitResolver (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:50022:13)
    at emitWorker (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:120247:49)
    at D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:120226:72
    at runWithCancellationToken (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:120321:24)
    at Object.emit (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:120226:26)
    at Object.emit (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:123733:57)
 
 
For the second one (flags):

    at checkVariableLikeDeclaration (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:84353:24)
    at checkVariableDeclaration (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:84433:13)
    at checkSourceElementWorker (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87645:28)
    at checkSourceElement (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87476:17)
    at Object.forEach (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:181:30)
    at checkVariableStatement (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:84444:16)
    at checkSourceElementWorker (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87614:28)
    at checkSourceElement (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87476:17)
    at Object.forEach (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:181:30)
    at checkSourceFileWorker (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87851:20)
    at checkSourceFile (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87816:13)
    at checkSourceFileWithEagerDiagnostics (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87926:13)
    at getDiagnosticsWorker (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87937:17)
    at getDiagnostics (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:87903:24)
    at Object.getEmitResolver (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:50022:13)
    at emitWorker (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:120247:49)
    at D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:120226:72
    at runWithCancellationToken (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:120321:24)
    at Object.emit (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:120226:26)
    at Object.emit (D:\src\apps\css\webapp\LSIWebCore\node_modules\typescript\lib\typescript.js:123733:57)
 

### 🔎 Search Terms

"Cannot read properties of undefined (reading 'exportSymbol')"

### 🕗 Version & Regression Information

This started when I switched to the rollup-plugin-ts rollup plugin for typescript. I have tried the nightly typescript build as of 03/13/2022 and it still happens there.

- This is a crash

### 💻 Code

The typescript that produces the error (from typescript.js 4.9.5) is:

`            var symbol = node.localSymbol;
            if (!symbol) {
                // local symbol is undefined => this declaration is non-exported.
                // however symbol might contain other declarations that are exported
                symbol = getSymbolOfNode(node);
                if (!symbol.exportSymbol) {
                    // this is a pure local symbol (all declarations are non-exported) - no need to check anything
                    return;
                }
            }
`  
The call to `getSymbolOfNode()` returns undefined, so the reference to exportSymbol blows up.

Doing a bit of sleuthing, the declaration related to the node that is erroring is:

`export type CustomerRating = 'AccountDisabled' | 'Deleted' | 'Inactive' | 'ApplicationPending' | 'AwaitingMaterials' | 'LSIProcessing' | 'PublisherAccess' | 'Unverified' | 'ApplicationOnHold';
`
As can be seen, nothing very out of the ordinary.

Similarly, the other dereferrence causing trouble occurs in the same file:

`            var symbol = getSymbolOfNode(node);
            if (symbol.flags & 2097152 /* SymbolFlags.Alias */ && ts.isVariableDeclarationInitializedToBareOrAccessedRequire(node.kind === 205 /* SyntaxKind.BindingElement */ ? node.parent.parent : node)) {
                checkAliasSymbol(node);
                return;
            }
`
Again, `getSymbolOfNode` returns undefined, causing it to crash.

The node in my source code related to this is again a very simple declaration such as:

`export const RoleGroups = {
    LSIPUB: "LSIPUB",
    LSICSR: "LSICSR",
    TITLE_VIEW: "TITLE_VIEW",
    TITLE_EDIT: "TITLE_EDIT"
}`

### 🙁 Actual behavior

Build crashes with reported error.

### 🙂 Expected behavior

It should be able to build. The code is correct, there are no syntax errors, and as mentioned, a simple tsc build finishes fine.

**Comment by RyanCavanaugh** [comment]
These are typically very hard to diagnose without a reproducing sample. It sounds like you have some pointers on the origin already - can you post a self-contained repro so we can test with it? Thanks!

**Comment by gmoneh** [comment]
Thanks for the response. Yes, I am aware that this is going to be a difficult to track down. It is not reproduceable with a simple typescript project, even a multifile one. As I mentioned, even in mine the pure typescript compilation works. 
I've been tracing down the places where it blows up, editing the typescript sources to place "undefined" guards so there are no dereferences to undefined variables, but I keep getting deeper and deeper into the code. It seems that all along it is assumed in that check that all "nodes" are always going to have a "symbol" one way or another, and there's no accounting for the possibility that there is none, as apparently is in my case. What I don't understand is whether that is a valid assumption and it is the rollup plugin who's doing something wrong to not meet that expectation.
