### ISSUE TITLE
tsc --w: Range Error: Maximum call stack size exceeded when exporting class with a reference to a self-referential static class method

### ISSUE THREAD

**Issue by mmgeorge** [microsoft/TypeScript#53263]
# Bug Report

### 🔎 Search Terms

**getAccessibleSymbolChain**, **Range Error: Maximum call stack size exceeded** -- there are several issues for similar errors (closest is https://github.com/microsoft/TypeScript/issues/22773 from 2.7?), but didn't see one that looked quite like this issue -- sorry if I missed it! 

I felt like I should still open this for tracking since it's present in the current and beta versions of typescript, but this is **no longer reproducible in 5.1** and seems like it might have gotten fixed as a side effect of something else? Please feel free to just close this.

### 🕗 Version & Regression Information

- **This is a crash** that is **NOT REPRODUCIBLE** in 5.1. Can reproduce in 5.0 and 4.9. 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?module=1&ts=4.9.5#code/LAKAxgNghgzjAEB1ATlADmgpsgPAFQD54BvUUeeAfQDcoIBXTALnj3gF54A7eiCAQgDcZEBRgAXKOICWYeAHsAZngCeWHAFUCACkri1zeBoCULfViVJUGbJqKlRFeAHpnRmJnhhYn6QnHy8MiY4vTIXPBQ8GjI8gAeKvDiABZS8ADu1v7JnmDyXBLI9GAByPCK8mUpfl7QcOROrpFcACbwLfKYCDDyALYhydJcAObwAEY+bflU5pgNFMGh4VboWMiC8A0AvqA7IKCQsAh4XeIke6CYcWiVZ4dw8ADKqS3YALLyLbyeDguYUB0uBBEvI0DJ8ghOL8nL0VAB5MHSfIsFCrbAAOiUqiw2hOEmM202IC2QA)

### 💻 Code

```ts

class Wrapper<T> {

  _value: T = null!;

  static ofType<U>(_type: U): typeof Wrapper<U> {
    // Use case is to return a proxy that wraps the constructor for this class
    // and does something based on _type
    return Wrapper; 
  }
}

class Test {}

export class ShaderModule {
  readonly options = {
    myOption: Wrapper.ofType(Test)
  } 
}
```

### 🙁 Actual behavior

Calling tsc with watch initially compiles, but on change crashes typescript with: 

```
[5:40:08 PM] File change detected. Starting incremental compilation...

/home/matt/typescript-crash/node_modules/typescript/lib/tsc.js:113234
      throw e;
      ^

RangeError: Maximum call stack size exceeded
    at getAccessibleSymbolChain (/home/matt/typescript-crash/node_modules/typescript/lib/tsc.js:45960:36)
    at isAnySymbolAccessible (/home/matt/typescript-crash/node_modules/typescript/lib/tsc.js:46122:37)
    at isSymbolAccessibleWorker (/home/matt/typescript-crash/node_modules/typescript/lib/tsc.js:46178:22)
    at isTypeSymbolAccessible (/home/matt/typescript-crash/node_modules/typescript/lib/tsc.js:46081:20)
    at typeToTypeNodeWorker (/home/matt/typescript-crash/node_modules/typescript/lib/tsc.js:46649:119)
    at typeToTypeNodeHelper (/home/matt/typescript-crash/node_modules/typescript/lib/tsc.js:46473:24)
    at mapToTypeNodes (/home/matt/typescript-crash/node_modules/typescript/lib/tsc.js:47313:28)
    at typeReferenceToTypeNode (/home/matt/typescript-crash/node_modules/typescript/lib/tsc.js:47048:33)
    at typeToTypeNodeWorker (/home/matt/typescript-crash/node_modules/typescript/lib/tsc.js:46629:83)
    at typeToTypeNodeHelper (/home/matt/typescript-crash/node_modules/typescript/lib/tsc.js:46473:24)
```

In my local code, I only get the error if I export `ShaderModule` in the definition above. 

I can reproduce this on the playground as well (no compilation output and a range error is present in the console). 

### 🙂 Expected behavior
Ideally this would not crash, or if the code has some sort of fundamental recursion in the types, then it would provide and error saying that the definition is recursive.

**Comment by DanielRosenwasser** [comment]
When you say it repros in the betas, did you check if it repros in 5.0 RC?

https://github.com/microsoft/TypeScript/issues/51202 and https://github.com/microsoft/TypeScript/issues/52757 both seem similar and have been fixed by https://github.com/microsoft/TypeScript/pull/51214.

**Comment by mmgeorge** [comment]
Oh no sorry I just checked 5.0.0-beta, 5.0.1-rc works locally for me. Thanks! 

Closing as dup of https://github.com/microsoft/TypeScript/issues/52757 and https://github.com/microsoft/TypeScript/issues/51202
