### ISSUE TITLE
The JS/TS language service immediately crashed 5 times

### ISSUE THREAD

**Issue by jclepin** [microsoft/TypeScript#53592]
JS/TS service crash and so no IntelliSense works. (keep loading after service crash)

**TypeScript Version:** 5.1.0-dev.20230329

**Steps to reproduce crash**

1. open vscode
2. vscode try to initialize js/ts service
3. service crash

**TS Server Log**

`/Users/jeancedrick/Library/Application Support/Code/logs/20230330T155122/window1/exthost/vscode.typescript-language-features/tsserver-log-ncYqXu/tsserver.log`

The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**

Server: `semantic`

```
RangeError: Maximum call stack size exceeded
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33826:13)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33764:22)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33764:22)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33792:63)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
    at parseJsxChildren (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33863:21)
    at parseJsxElementOrSelfClosingElementOrFragment (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33764:22)
    at parseJsxChild (/Users/xxxx/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230329/node_modules/typescript/lib/tsserver.js:33846:16)
```

[20230330T155122.zip](https://github.com/microsoft/vscode/files/11112467/20230330T155122.zip)

**Comment by RyanCavanaugh** [comment]
Can you post the code file that causes this?

**Comment by jclepin** [comment]
This simple code for exemple : 

import { Platform } from "react-native";

export const colors = {
  logo: "#1860ac",
  primary: "#0897E4",
  secondary: "#666666",
  black: "#000000",
  white: "#ffffff",
  light: "#e5e7eb",
  grey: "#7e7e7e",
  lightGrey: "#EEEFF2",
  darkGrey: "#333333",
  danger: "#D33535",
  success: "#16a34a",
  status1: "#008E2F",
  status5: "#6C91A5",
  status7: "#F2910A",
  status4: "#1ABC9C",
};

colors. Transparent = colors.darkGrey + "AA";
colors.transparentWhite = colors.white + "AA";
colors.transparentPrimary = colors.primary + "AA";
colors.transparentSecondary = colors.secondary + "AA";
colors.transparentDanger = colors.danger + "AA";
colors.transparentSuccess = colors.success + "AA";

export const noPhoto =
  "https://www.consortium-immobilier.fr/nxt-version/images/fichesimpression/vitrine_v2/nophoto.jpg";

export const marginPadding = {
  xs: 5,
  sm: 10,
  md: 15,
  lg: 20,
};

export const header = {
  height: 45,
};

export const fontSize = {
  xs: Platform.OS === "-android" ? 12 : 12,
  sm: Platform.OS === "-android" ? 14 : 14,
  md: Platform.OS === "-android" ? 16 : 16,
  lg: Platform.OS === "-android" ? 18 : 18,
  xl: Platform.OS === "-android" ? 20 : 20,
  xl2: Platform.OS === "-android" ? 22 : 22,
};

export const fontFamily =  Platform.OS === "android" ? "Roboto" : "Avenir";

export const iconSize = {
  xs: 20,
  sm: 25,
  md: 35,
  xl: 45,
};

export const paddingHorizontal = (padding) =>
  Platform.OS === "android" ? padding * 1 : padding;

export const defaultStyles = {
  text: {
    color: colors.darkGrey,
    fontSize: fontSize.md,
    overflow: "hidden",
  },
};


export const formValidation = {
  require: "Ce champ est requis",
  email: "L'email doit être valide",
  min: (n) => `Le champ doit contenir au moins ${n} caractères`,
  minImage: (n) => `Selectionner au moins ${n} image(s)`,
};

export const icons = {
  edit: "create-sharp",
  home: "home-sharp",
  mail: "mail-outline",
  user: "person-sharp",
  users: "people-sharp",
  list: "list-outline",
  plus: "add-outline",
  plusCircle: "add-circle-sharp",
  marker: "location-sharp",
  document: "document-sharp",
};

**Comment by cnorling** [comment]
I'm also getting this error on `5.1.0-dev.20230403`

**Comment by jclepin** [comment]
Thank you it seems to be fixed with :

JavaScript and TypeScript Nightly
v5.1.20230406
