### ISSUE TITLE
`RangeError: Maximum call stack size exceeded` on recursive conditional type with template literal string type using `infer` keyword

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#53783]
# Bug Report

### 🔎 Search Terms
RangeError: Maximum call stack size exceeded

### 🕗 Version & Regression Information
5.1.0-dev.20230414

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&noUnusedLocals=true&target=99&jsx=0&resolvePackageJsonExports=true&useUnknownInCatchVariables=true&exactOptionalPropertyTypes=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true#code/C4TwDgpgBAMhB2BzYALAIgewO7wDwFgAoKKAZWACcoIAPYBAEwGconKBLJAGiJLiVTU6jFvACuAWwBGEKgB8oU9ok7AexKAElgRAHxQAvFuBD68ZmUrbZAOmsUAhsAwVeUAPyWK9mwGExwACCwLjkFFzG+rRmFgAGACQA3pwAZrJQ8QBKEGwAvrFuJJ78yOjYeFk5alCBDAy4JagRYT4Aag4ANmIQuNq6uhF9hVAAXLAIpZg4oZQRjSjNVvQUNgAKFBAAbr3A-W5j8wDcQA)

(check the console for the error)

### 💻 Code

```ts
type LengthDown<
  Str extends string,
  Length extends number | bigint,
  It
> = It extends StrIter.Iterator
  ? StrIter.CutAt<Str, It> extends `${infer $Rest}`
    ? LengthDown<$Rest, Add<Length, StrIter.Value<It>>, It>
    : LengthDown<Str, Length, StrIter.Prev<It>>
  : Length;
```

### 🙁 Actual behavior

```
> tsc --noEmit --moduleresolution nodenext

C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:114339
      throw e;
      ^

RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at formatStringFromArgs (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:15925:15)
    at createFileDiagnostic (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:15999:12)
    at createDiagnosticForNodeInSourceFile (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:12335:10)
    at createDiagnosticForNode (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:12327:10)
    at createError (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:43554:23)
    at error (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:43557:24)
    at C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:44396:15
    at addLazyDiagnostic (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:79812:33)
    at resolveNameHelper (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:44359:9)
```

### 🙂 Expected behavior

no crash

**Comment by DetachHead** [comment]
here's a more minimal example:
```ts
type Foo<T> = T extends unknown
  ? unknown extends `${infer $Rest}`
    ? Foo<T>
    : Foo<unknown>
  : unknown;
```

but the stack trace is slightly different, so i'm not sure if it's the exact same issue:
```
RangeError: Maximum call stack size exceeded
    at resolveNameHelper (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:44106:29)
    at resolveName (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:44104:12)
    at resolveEntityName (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:45554:32)
    at getSymbolOfNameOrPropertyAccessExpression (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:80179:22)
    at getSymbolAtLocation (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:80264:18)
    at getTypeFromTypeNodeWorker (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:57735:24)
    at containsReference (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:57960:101)
    at visitNode2 (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:25417:18)
    at forEachChildInTypeReference (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:25523:12)
    at forEachChild (C:\Users\user\hotscript\node_modules\typescript\lib\tsc.js:25931:35)
```
