### ISSUE TITLE
properties are not type checked in ts file but checked in tsx

### ISSUE THREAD

**Issue by co-dh** [Microsoft/TypeScript#5380]
I noticed that the following line type checked correctly
```ts
<Login.Form foo='bar'/>
```
with error message:

 > Property 'foo' does not exist on type '{}'.

while i's ts equivalent is not type checked:
```
{
         React.createFactory(Login.Form)({ foo:'bar'})
}
```
Not sure if I should put this issue in React.d.ts

**Comment by co-dh** [comment]
command line:
 tsc --module amd public/3rd/react.d.ts test.tsx

and here is test.tsx:

/// <references path='../public/3rd/react.d.ts' />
//
import React = require('react')

let {div} = React.DOM
class A extends React.Component<{}, {}> {
    render(){
        return div()
    }
}

class B extends React.Component<{}, {}>{
    render(){
        return React.createFactory(A)({foo:1})
    }
    render1(){
        return div({foo:1})
    }
}
export =  B

**Comment by mhegazy** [comment]
//CC: @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
I'd raise this over at https://github.com/borisyankov/DefinitelyTyped. We don't do any React-specific checking of function calls, but it may be possible to set up some overloads for `createFactory` to catch this.

**Comment by co-dh** [comment]
I think I figured out the problem.
The standard reactjs way to use React.Component<{}, ...> to express an empty property in fact
is wrong in typescript. Because in typescript {} means any. so in typescript, we should use
React.Component<void, ...> to say that this component has no properties.

tsc.js have special code to handle jsx, so {} is treated as void, as proved by below stack trace.

```
    at error (/home/hao/node_modules/typescript/lib/tsc.js:10401:13)
    at checkJsxAttribute (/home/hao/node_modules/typescript/lib/tsc.js:16074:29)
    at checkJsxOpeningLikeElement (/home/hao/node_modules/typescript/lib/tsc.js:16299:21)
    at checkJsxSelfClosingElement (/home/hao/node_modules/typescript/lib/tsc.js:16009:13)
    at checkExpressionWorker (/home/hao/node_modules/typescript/lib/tsc.js:18049:28)
    at checkExpression (/home/hao/node_modules/typescript/lib/tsc.js:17960:42)
    at checkExpressionCached (/home/hao/node_modules/typescript/lib/tsc.js:17921:38)
    at getTypeForVariableLikeDeclaration (/home/hao/node_modules/typescript/lib/tsc.js:12098:24)
    at getWidenedTypeForVariableLikeDeclaration (/home/hao/node_modules/typescript/lib/tsc.js:12152:24)
    at getTypeOfVariableOrParameterOrProperty (/home/hao/node_modules/typescript/lib/tsc.js:12184:28)
 ```

**Comment by co-dh** [comment]
Here is the code sample.
```
/// <references path='../public/3rd/react.d.ts' />
//
import React = require('react')

let {div} = React.DOM

class A extends React.Component<{}, {}> {
    render(){ return div() }
}

class B extends React.Component<void, {}> {
    render(){ return div() }
}


class C extends React.Component<{}, {}>{
    render(){

        //this line compiles, but wrong
        let a = React.createFactory(A)({a:'1'})

        // error TS2345: Argument of type '{ a: string; }' is not assignable to parameter of type 'void'.
        let b = React.createFactory(B)({a:'1'})

        return div()
    }
}
export =  B
```
