### ISSUE TITLE
"Cannot read property 'flags' of undefined" error when compiling nested array destruction

### ISSUE THREAD

**Issue by seanchas116** [Microsoft/TypeScript#5389]
Hi,

I found `tsc` crashes when compiling nested array destruction in function parameter (example below).

## TypeScript version

1.8.0-dev.20151024 (installed via `npm install typescript@next`)

## Example Source

```js
const nestedArray = [[[1, 2]], [[3, 4]]];

nestedArray.forEach(([[a, b]]) => {
  console.log(a, b);
});
```

## Command

```
tsc index.ts
```

## Trace

```
/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:30338
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at getSymbolLinks (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:10715:23)
    at assignBindingElementTypes (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:17679:25)
    at assignTypeToParameterAndFixTypeParameters (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:17689:17)
    at assignContextualParameterTypes (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:17666:17)
    at checkFunctionExpressionOrObjectLiteralMethod (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:17860:29)
    at checkExpressionWorker (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:18503:28)
    at checkExpression (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:18445:42)
    at checkExpressionWithContextualType (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:18399:26)
    at checkApplicableSignature (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:17162:31)
    at chooseOverload (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:17448:30)
```

**Comment by mhegazy** [comment]
thanks @seanchas116!
