### ISSUE TITLE
Crash `Unhandled type Any` on ESM-mode namespace import of `module.exports = null`

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#54352]
# Bug Report

### 🔎 Search Terms

unhandled type any

### 💻 Code

```ts
// @module: nodenext
// @allowJs: true
// @noEmit: true

// @Filename: single-null-export.js
module.exports = null;

// @Filename: index.mts
import * as x from "./single-null-export.js";
```

### 🙁 Actual behavior

```
Error: Debug Failure. Unhandled type Any
    at resolveStructuredTypeMembers (/Users/andrew/Developer/microsoft/eg/crash/node_modules/typescript/lib/tsc.js:53313:15)
    at cloneTypeAsModuleType (/Users/andrew/Developer/microsoft/eg/crash/node_modules/typescript/lib/tsc.js:45963:32)
    at resolveESModuleSymbol (/Users/andrew/Developer/microsoft/eg/crash/node_modules/typescript/lib/tsc.js:45942:20)
    at getTargetOfNamespaceImport (/Users/andrew/Developer/microsoft/eg/crash/node_modules/typescript/lib/tsc.js:44942:22)
    at getTargetOfAliasDeclaration (/Users/andrew/Developer/microsoft/eg/crash/node_modules/typescript/lib/tsc.js:45249:16)
    at resolveAlias (/Users/andrew/Developer/microsoft/eg/crash/node_modules/typescript/lib/tsc.js:45295:22)
    at checkAliasSymbol (/Users/andrew/Developer/microsoft/eg/crash/node_modules/typescript/lib/tsc.js:78629:20)
    at checkImportBinding (/Users/andrew/Developer/microsoft/eg/crash/node_modules/typescript/lib/tsc.js:78745:5)
    at checkImportDeclaration (/Users/andrew/Developer/microsoft/eg/crash/node_modules/typescript/lib/tsc.js:78794:13)
    at checkSourceElementWorker (/Users/andrew/Developer/microsoft/eg/crash/node_modules/typescript/lib/tsc.js:79280:16)
```

### 🙂 Expected behavior

Compiles without error (and the type of `x` should be something like `{ default: null }`)

**Comment by RyanCavanaugh** [comment]
Duplicate of [#51099](https://github.com/microsoft/TypeScript/issues/51099): both reports reach the ESM namespace-import path for a CommonJS `module.exports` value with a non-structured type. That crash was fixed by merged [#51136](https://github.com/microsoft/TypeScript/pull/51136).
