### ISSUE TITLE
Move to existing file — Error: Debug Failure. at doChange4

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#54463]
# Bug Report

### 🔎 Search Terms
- refactor
- refactoring

### 🕗 Version & Regression Information
5.2.0-dev.20230530

### Repo

1. For the code:

```ts
const a = 1;
const b = 2;
console.log(a, b);
```

2. Select the first line and try running `move to existing file`
3. Select an existing file (in this case, an empty file)

### bug
See the following error for the request:

```
2023-05-30 16:26:04.698 [trace] <semantic> Sending request: getEditsForRefactor (115). Response expected: yes. Current queue length: 0 {
    "file": "/Users/matb/projects/san/x.ts",
    "startLine": 1,
    "startOffset": 1,
    "endLine": 2,
    "endOffset": 1,
    "action": "Move to file",
    "refactor": "Move to file",
    "interactiveRefactorArguments": {
        "targetFile": "/Users/matb/projects/san/other.ts"
    }
}
2023-05-30 16:26:04.700 [trace] <semantic> Response received: getEditsForRefactor (115). Request took 1 ms. Success: false . Message: Error processing request. Debug Failure.
Error: Debug Failure.
    at doChange4 (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:136527:36)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:136514:79
    at ChangeTracker.with (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:165947:5)
    at Object.getRefactorEditsToMoveToFile [as getEditsForAction] (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:136514:62)
    at Object.getEditsForRefactor (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:135602:31)
    at Object.getEditsForRefactor2 [as getEditsForRefactor] (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:142859:32)
    at IpcIOSession.getEditsForRefactor (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:182159:49)
    at getEditsForRefactor (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:180415:43)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:182543:69
    at IpcIOSession.executeWithRequestId (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:182535:14)
    at IpcIOSession.executeCommand (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:182543:29)
    at IpcIOSession.onMessage (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:182585:51)
    at process.<anonymous> (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:184165:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:939:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
