### ISSUE TITLE
"Inline variable" causes failure when variable is used as the initializer of a destructured variable declaration

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#54982]
```ts
export function Component(props: any) {
    const { thing } = /**/props;
}
```

Similarly

```ts
export function func(arr: any) {
    const [thing] = /**/arr;
}
```

or

```ts
function f() {
    const a = { prop: 123 };
    const { prop } = /**/a;
}
```

Request refactorings at any `/**/` in any of the above examples.

```
Response received: getApplicableRefactors (4649). Request took 1 ms. Success: false . Message: Error processing request. Cannot read properties of undefined (reading 'declarations')
TypeError: Cannot read properties of undefined (reading 'declarations')
    at getInliningInfo ([...]/node_modules/typescript/lib/tsserver.js:138059:55)
    at Object.getAvailableActions ([...]/node_modules/typescript/lib/tsserver.js:138004:18)
    at [...]/node_modules/typescript/lib/tsserver.js:137214:222
    at flatMapIterator ([...]/node_modules/typescript/lib/tsserver.js:2626:19)
    at flatMapIterator.next (<anonymous>)
    at arrayFrom ([...]/node_modules/typescript/lib/tsserver.js:3180:14)
    at Object.getApplicableRefactors ([...]/node_modules/typescript/lib/tsserver.js:137212:10)
    at Object.getApplicableRefactors2 [as getApplicableRefactors] ([...]/node_modules/typescript/lib/tsserver.js:144674:32)
    at IpcIOSession.getApplicableRefactors ([...]/node_modules/typescript/lib/tsserver.js:184174:41)
    at getApplicableRefactors ([...]/node_modules/typescript/lib/tsserver.js:182430:43)
    at [...]/node_modules/typescript/lib/tsserver.js:184563:69
    at IpcIOSession.executeWithRequestId ([...]/node_modules/typescript/lib/tsserver.js:184555:14)
    at IpcIOSession.executeCommand ([...]/node_modules/typescript/lib/tsserver.js:184563:29)
    at IpcIOSession.onMessage ([...]/node_modules/typescript/lib/tsserver.js:184605:51)
    at process.<anonymous> ([...]/node_modules/typescript/lib/tsserver.js:186186:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:967:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
