### ISSUE TITLE
RangeError: Maximum call stack size exceeded when compining with nodejs 16.20+

### ISSUE THREAD

**Issue by AGiorgetti** [microsoft/TypeScript#55100]
# Bug Report

RangeError: Maximum call stack size exceeded
    at checkExpression (C:\agent\sidsrl\_work\3\s\packages\Microsoft.TypeScript.MSBuild.5.1.5\tools\tsc\tsc.js:74184:27)
    at checkNonNullExpression (C:\agent\sidsrl\_work\3\s\packages\Microsoft.TypeScript.MSBuild.5.1.5\tools\tsc\tsc.js:68580:29)
    at checkPropertyAccessExpression (C:\agent\sidsrl\_work\3\s\packages\Microsoft.TypeScript.MSBuild.5.1.5\tools\tsc\tsc.js:68659:162)
    at checkExpressionWorker (C:\agent\sidsrl\_work\3\s\packages\Microsoft.TypeScript.MSBuild.5.1.5\tools\tsc\tsc.js:74269:16)
    at checkExpression (C:\agent\sidsrl\_work\3\s\packages\Microsoft.TypeScript.MSBuild.5.1.5\tools\tsc\tsc.js:74190:32)
    at resolveCallExpression (C:\agent\sidsrl\_work\3\s\packages\Microsoft.TypeScript.MSBuild.5.1.5\tools\tsc\tsc.js:70550:20)
    at resolveSignature (C:\agent\sidsrl\_work\3\s\packages\Microsoft.TypeScript.MSBuild.5.1.5\tools\tsc\tsc.js:70989:16)
    at getResolvedSignature (C:\agent\sidsrl\_work\3\s\packages\Microsoft.TypeScript.MSBuild.5.1.5\tools\tsc\tsc.js:71009:18)
    at checkCallExpression (C:\agent\sidsrl\_work\3\s\packages\Microsoft.TypeScript.MSBuild.5.1.5\tools\tsc\tsc.js:71121:23)
    at checkExpressionWorker (C:\agent\sidsrl\_work\3\s\packages\Microsoft.TypeScript.MSBuild.5.1.5\tools\tsc\tsc.js:74279:16)

I get the above error when compiling an (old) website project that uses the MSBuild.TypeScript package.

The error appear with all the nodejs versions > 16.20 (embedded in VS2022 17.7 Preview 4)

If I try to compile the same project with nodejs 16.14 it compiles without errors

this is the tsconfig.json I actually use:

`
{
	"compileOnSave": true,
	"compilerOptions": {
		"noImplicitAny": false,
		"noEmitOnError": true,
		"removeComments": false,
		"sourceMap": true,
		"target": "ES5",
		"module": "None",
		"noEmitHelpers": true,
		"importHelpers": true
	},
	"exclude": [
		"node_modules",
		"wwwroot"
	],
	"include": [
		"AngularJs/**/*",
		"Scripts/**/*",
		"JS/**/*"
	],
	"files": [
		"node_modules/moment/ts3.1-typings/moment.d.ts"
	]
}
`

### 🔎 Search Terms

RangeError: Maximum call stack size exceeded

### 🕗 Version & Regression Information

The error started to appear with Visual Studio 2022 17.7 Preview 3.0 that has nodejs16.20.

It works well with the standard community edition that has nodejs 16.14.

I've also tried several versions of the compiler (4.9.3, 5.0.4, 5.1.5, next /beta) with some nodejs versions > 16.20.
All the compilations fails with the same errors.

- This is a crash
- 
- This changed between nodejs versions 16.14 and 16.20

**Comment by RyanCavanaugh** [comment]
We'd need a way to reproduce this

**Comment by AGiorgetti** [comment]
I was able to reproduce the issue, it's related to repetitive calls of the same function in a fluent api pattern (a common pattern when configuring the router in angularjs applications for example).

To to reproduce the isse try to compile a .ts file like the following one:

`
class FluentApi {
    public callMe(): FluentApi {
        return this;
    }
}

const api = new FluentApi();
api
    .callMe()
    .callMe()

    // add 600 (or more) .callMe() invocations   

    .callMe()
    .callMe()
    ;
`

Workaround: split the calls in multiple batches.

**Comment by RyanCavanaugh** [comment]
>  // add 600 (or more) .callMe() invocations   

We're not going to trampoline the entire codebase to support patterns like this.
