### ISSUE TITLE
progress.emit() threw Error

### ISSUE THREAD

**Issue by findlay-best-wishes** [microsoft/TypeScript#55380]
### 🔎 Search Terms

"isInAppropriateContext", 
"node.parent.kind === 305"

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.7.4 and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link
[stackblitz-starters-hd5puf
](https://stackblitz.com/edit/stackblitz-starters-hd5puf?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=package.json,index.ts,node_modules%2Ftypescript%2Flib%2Ftypescript.d.ts&title=node.new%20Starter)
_No response_

### 💻 Code
``` ts
import * as ts from "typescript";

const compilerOptions = {
  declaration: true,
  emitDeclarationOnly: true
}
const host = ts.createCompilerHost(compilerOptions);
const files: Record<string, string> = {}
host.writeFile = (fileName: string, contents: string) => files[fileName] = contents
const program = ts.createProgram([], compilerOptions, host)
const sourceFileText = `import _Button from './button.vue';
  export const Button = _Button;
  export default Button
`
const sourceFile = ts.createSourceFile('button.ts', sourceFileText, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
const transformerFactory: ts.TransformerFactory<ts.SourceFile> = (context) => {
  return (sourceFile) => {
    const importNode = ts.factory.createImportDeclaration(
      undefined,
      undefined,
      ts.factory.createImportClause(true, undefined, ts.factory.createNamedImports([ts.factory.createImportSpecifier(false, undefined, ts.factory.createIdentifier('DefineComponent'))])),
      ts.createLiteral('vue')
    );
    return ts.updateSourceFileNode(sourceFile, [
      importNode,
      ...sourceFile.statements
    ])
  };
};
const transformedSourceFile = ts.transform(sourceFile, [transformerFactory]).transformed[0];
console.log(ts.createPrinter().printNode(ts.EmitHint.SourceFile, transformedSourceFile, transformedSourceFile));
program.emit(
  transformedSourceFile,
  undefined,
  undefined,
  true
)
```
## crash and errors
``` shell
pnpm mini

> @pangu/vue@0.16.0 mini /Users/guojie19/Desktop/infra/pangu/packages/vue3
> tsx ./scripts/mini.ts

import type { DefineComponent } from "vue";
import _Button from './button.vue';
export const Button = _Button;
export default Button;

/Users/guojie19/Desktop/infra/pangu/packages/vue3/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:85406
            var isInAppropriateContext = node.parent.kind === 305 /* SyntaxKind.SourceFile */ || node.parent.kind === 262 /* SyntaxKind.ModuleBlock */ || node.parent.kind === 261 /* SyntaxKind.ModuleDeclaration */;
                                                     ^

TypeError: Cannot read properties of undefined (reading 'kind')
    at checkGrammarModuleElementContext (/Users/guojie19/Desktop/infra/pangu/packages/vue3/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:85406:54)
    at checkImportDeclaration (/Users/guojie19/Desktop/infra/pangu/packages/vue3/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:85272:17)
    at checkSourceElementWorker (/Users/guojie19/Desktop/infra/pangu/packages/vue3/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:85772:28)
    at checkSourceElement (/Users/guojie19/Desktop/infra/pangu/packages/vue3/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:85597:17)
    at Object.forEach (/Users/guojie19/Desktop/infra/pangu/packages/vue3/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:377:30)
    at checkSourceFileWorker (/Users/guojie19/Desktop/infra/pangu/packages/vue3/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:85954:20)
    at checkSourceFile (/Users/guojie19/Desktop/infra/pangu/packages/vue3/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:85920:13)
    at checkSourceFileWithEagerDiagnostics (/Users/guojie19/Desktop/infra/pangu/packages/vue3/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:86026:13)
    at getDiagnosticsWorker (/Users/guojie19/Desktop/infra/pangu/packages/vue3/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:86037:17)
    at getDiagnostics (/Users/guojie19/Desktop/infra/pangu/packages/vue3/node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js:86003:24)
```

### 🙂 Expected behavior

success

**Comment by RyanCavanaugh** [comment]
Please make this a minimal repro; it's almost certain that one of the factory calls there is making an invalid tree. This should be narrowed down to a minimal failing example.

**Comment by findlay-best-wishes** [comment]
> Please make this a minimal repro; it's almost certain that one of the factory calls there is making an invalid tree. This should be narrowed down to a minimal failing example.

Okay, i has udpated the minimal example.

**Comment by jakebailey** [comment]
You're transforming a file and _then_ passing it to `program.emit`, which I don't think is expecting to be given synthesized nodes at all, only actual source files from the program. Did you mean to pass `customTransformers` into the `emit` call?
