### ISSUE TITLE
Container builds fails after upgrade to Microsoft.TypeScript.MSBuild 5.2.2

### ISSUE THREAD

**Issue by davhdavh** [microsoft/TypeScript#55886]
### 🔎 Search Terms

Microsoft.TypeScript.MSBuild  error MSB6006: "/usr/bin/nodejs" exited with code 1

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 5.0.4 and 5.2.2

### 💻 Code

```dockerfile
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        nodejs \
        npm \
    && rm -rf /var/lib/apt/lists/*
COPY ["*.csproj", "package*", "tsconfig.json", "."]
RUN --mount=type=cache,id=npm,target=/root/.npm --mount=type=cache,id=nuget,target=/root/.nuget/packages dotnet restore
RUN --mount=type=cache,id=npm,target=/root/.npm --mount=type=cache,id=nuget,target=/root/.nuget/packages npm install
```

### 🙁 Actual behavior

 > [xxx build  8/10] RUN --mount=type=cache,id=npm,target=/root/.npm --mount=type=cache,id=nuget,target=/root/.nuget/packages dotnet build:
10.86 MSBuild version 17.7.3+8ec440e68 for .NET
12.15   Determining projects to restore...
12.47   All projects are up-to-date for restore.
13.19 /root/.nuget/packages/microsoft.typescript.msbuild/5.2.2/tools/Microsoft.TypeScript.targets(485,5): error MSB6006: "/usr/bin/nodejs" exited with code 1. [/src/xxx.csproj]
13.21
13.21 Build FAILED.
13.21
13.21 /root/.nuget/packages/microsoft.typescript.msbuild/5.2.2/tools/Microsoft.TypeScript.targets(485,5): error MSB6006: "/usr/bin/nodejs" exited with code 1. [/src/xxx.csproj]
13.21     0 Warning(s)
13.21     1 Error(s)
13.21
13.21 Time Elapsed 00:00:02.13

### 🙂 Expected behavior

build success

**Comment by joj** [comment]
@davhdavh is there a way to get a binlog from that build? That error is "node failed running tsc" but I'm not getting what the actual error was from that and a binlog may be more explicit.

**Comment by davhdavh** [comment]
ran it with `-m:d` and found the error. Looks like it is assuming a newer nodejs than what the net7 base image can install.
```
	1:7>Target "CompileTypeScriptWithTSConfig" in file "/root/.nuget/packages/microsoft.typescript.msbuild/5.2.2/tools/Microsoft.TypeScript.targets" from project "/src/xxx.csproj" (target "Compile" depends on it):
	Building target "CompileTypeScriptWithTSConfig" completely.
	Output file "should_not_exist.file" does not exist.
	Using "CreateProperty" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
	Task "CreateProperty"
	Done executing task "CreateProperty".
	Task "VsTsc"
	/usr/bin/nodejs /root/.nuget/packages/microsoft.typescript.msbuild/5.2.2/tools/tsc/tsc.js --project "/src/tsconfig.json" --listEmittedFiles
	Unknown output:   for (let i = startIndex ?? 0; i < array.length; i++) {
	Unknown output:                            ^
	Unknown output:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
	Unknown output:     at Module._compile (internal/modules/cjs/loader.js:963:27)
	Unknown output:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
	Unknown output:     at Module.load (internal/modules/cjs/loader.js:863:32)
	Unknown output:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
	Unknown output:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
	Unknown output:     at internal/main/run_main_module.js:17:47
	Assembly loaded during TaskRun (TypeScript.Tasks.VsTsc): System.IO, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.IO.dll, MVID: 9c666937-f107-44b8-a0c7-76be5fb89a57, AppDomain: [Default])
	Assembly loaded during TaskRun (TypeScript.Tasks.VsTsc): System.IO.FileSystem.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.IO.FileSystem.Primitives.dll, MVID: 6260c925-d729-4995-ad7d-80f5384b53d2, AppDomain: [Default])
```

**Comment by jakebailey** [comment]
Running:

```Dockerfile
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:7.0
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        nodejs \
        npm \
    && rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["/usr/bin/nodejs", "--version"]
```

Gives:

```
v12.22.12
```

This version went EOL a year and a half ago; since you are manually installing `node` into this container, can you install a newer version instead? The current LTS is 18; though we support them, Node 14 and 16 are both EOL and should be avoided.

Note that TS dropped Node 12 support in TS 5.1, not 5.2 (so the title isn't quite right).
