### ISSUE TITLE
Inlay type hints don't work for bigint literals

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#55945]
```ts
const yadda: 1n = 1n;

export function helper(b = yadda) {
}
```

When using inlay type hints for parameters (using these settings in VS Code)

```json5
"editor.inlayHints.enabled": "on",
"typescript.inlayHints.parameterTypes.enabled": true,
```

I get the following stack trace

```
Error: Debug Failure. Unexpected node.
Node BigIntLiteral was unexpected.
    at visitForDisplayParts (.../node_modules/typescript/lib/tsserver.js:164854:17)
    at visitForDisplayParts (.../node_modules/typescript/lib/tsserver.js:164801:11)
    at typeToInlayHintParts (.../node_modules/typescript/lib/tsserver.js:164582:5)
    at getParameterDeclarationTypeHints (.../node_modules/typescript/lib/tsserver.js:164547:12)
    at visitFunctionLikeForParameterType (.../node_modules/typescript/lib/tsserver.js:164531:25)
    at visitor (.../node_modules/typescript/lib/tsserver.js:164321:9)
    at visitNodes (.../node_modules/typescript/lib/tsserver.js:30187:22)
    at forEachChildInSourceFile (.../node_modules/typescript/lib/tsserver.js:30400:12)
    at forEachChild (.../node_modules/typescript/lib/tsserver.js:30696:35)
    at visitor (.../node_modules/typescript/lib/tsserver.js:164327:12)
    at Object.provideInlayHints (.../node_modules/typescript/lib/tsserver.js:164288:3)
    at Object.provideInlayHints2 [as provideInlayHints] (.../node_modules/typescript/lib/tsserver.js:145334:34)
    at IpcIOSession.provideInlayHints (.../node_modules/typescript/lib/tsserver.js:183679:48)
    at provideInlayHints (.../node_modules/typescript/lib/tsserver.js:182838:43)
    at .../node_modules/typescript/lib/tsserver.js:184857:69
    at IpcIOSession.executeWithRequestId (.../node_modules/typescript/lib/tsserver.js:184849:14)
    at IpcIOSession.executeCommand (.../node_modules/typescript/lib/tsserver.js:184857:29)
    at IpcIOSession.onMessage (.../node_modules/typescript/lib/tsserver.js:184899:51)
    at process.<anonymous> (.../node_modules/typescript/lib/tsserver.js:186480:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by DanielRosenwasser** [comment]
The inlay hint needs to be interactive.

```ts
/// <reference path="fourslash.ts" />

////const yadda: 1n = 1n;
////
////export function helper(b = yadda) {
////}

verify.baselineInlayHints(undefined, {
    interactiveInlayHints: true,
    includeInlayFunctionParameterTypeHints: true
});
```
