### ISSUE TITLE
Inlay hints computation can't handle ObjectBindingPattern within a type

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/TypeScript#56380]
### 🔎 Search Terms

inlay hints ObjectBindingPattern

### 🕗 Version & Regression Information

TS Server version 5.3.1-rc

### 💻 Code

```ts
const Foo = ({ foo }: Foo) => {
	return 1;
};

```

### 🙁 Actual behavior

Given file 

```typescript
const Foo = ({ foo }: Foo) => {
	return 1;
};
```

TS server throws: 

```
<semantic> TypeScript Server Error (5.3.1-rc)
Debug Failure. Unexpected node.
Node ObjectBindingPattern was unexpected.
Error: Debug Failure. Unexpected node.
Node ObjectBindingPattern was unexpected.
    at visitForDisplayParts (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165390:17)
    at visitForDisplayParts (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165195:11)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165398:9
    at Array.forEach (<anonymous>)
    at visitDisplayPartList (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165394:13)
    at visitForDisplayParts (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165347:11)
    at typeToInlayHintParts (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165120:5)
    at visitVariableLikeDeclaration (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164928:23)
    at visitor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164850:7)
    at visitNodes (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30237:22)
    at forEachChildInVariableDeclarationList (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30456:12)
    at forEachChild (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30746:35)
    at visitor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164865:12)
    at visitNode2 (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30229:18)
    at forEachChildInVariableStatement (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30453:59)
    at forEachChild (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30746:35)
    at visitor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164865:12)
    at visitNodes (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30237:22)
    at forEachChildInSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30450:12)
    at forEachChild (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30746:35)
    at visitor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164865:12)
    at Object.provideInlayHints (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164826:3)
    at Object.provideInlayHints2 [as provideInlayHints] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:145851:34)
    at IpcIOSession.provideInlayHints (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:184204:48)
    at provideInlayHints (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183363:43)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185382:69
    at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185374:14)
    at IpcIOSession.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185382:29)
    at IpcIOSession.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185424:51)
    at process.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:187006:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21): Error: <semantic> TypeScript Server Error (5.3.1-rc)
Debug Failure. Unexpected node.
Node ObjectBindingPattern was unexpected.
Error: Debug Failure. Unexpected node.
Node ObjectBindingPattern was unexpected.
    at visitForDisplayParts (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165390:17)
    at visitForDisplayParts (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165195:11)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165398:9
    at Array.forEach (<anonymous>)
    at visitDisplayPartList (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165394:13)
    at visitForDisplayParts (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165347:11)
    at typeToInlayHintParts (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:165120:5)
    at visitVariableLikeDeclaration (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164928:23)
    at visitor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164850:7)
    at visitNodes (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30237:22)
    at forEachChildInVariableDeclarationList (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30456:12)
    at forEachChild (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30746:35)
    at visitor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164865:12)
    at visitNode2 (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30229:18)
    at forEachChildInVariableStatement (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30453:59)
    at forEachChild (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30746:35)
    at visitor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164865:12)
    at visitNodes (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30237:22)
    at forEachChildInSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30450:12)
    at forEachChild (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30746:35)
    at visitor (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164865:12)
    at Object.provideInlayHints (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:164826:3)
    at Object.provideInlayHints2 [as provideInlayHints] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:145851:34)
    at IpcIOSession.provideInlayHints (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:184204:48)
    at provideInlayHints (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183363:43)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185382:69
    at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185374:14)
    at IpcIOSession.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185382:29)
    at IpcIOSession.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185424:51)
    at process.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:187006:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Function.create (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:477347)
    at v.w (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:472672)
    at v.u (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:471755)
    at ChildProcess.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:471387)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Screenshot:

![Image](https://github.com/microsoft/TypeScript/assets/16353531/3ccc83be-7ebc-4d61-aab6-afcb7697a667)

Debugging this, I found out that TS inlay hint computation in `typeToInlayHintParts` can't handle ObjectBindingPattern in a type. For the code above, type of `Foo` is `({ foo }: Foo) => number`. Hence, the error

### 🙂 Expected behavior

Inlay hints do not throw

**Comment by MariaSolOs** [comment]
This was fixed in #56277.

**Comment by ulugbekna** [comment]
@MariaSolOs Hi, I see a similar error

```
<semantic> TypeScript Server Error (5.4.0-dev.20231120)
Debug Failure. Unexpected node.
Node ThisType was unexpected.
Error: Debug Failure. Unexpected node.
Node ThisType was unexpected.
    at visitForDisplayParts (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165745:17)
    at typeToInlayHintParts (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165429:5)
    at visitVariableLikeDeclaration (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165237:23)
    at visitor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165159:7)
    at visitNodes (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30254:22)
    at forEachChildInVariableDeclarationList (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30473:12)
    at forEachChild (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30763:35)
    at visitor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165174:12)
    at visitNode2 (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30246:18)
    at forEachChildInVariableStatement (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30470:59)
    at forEachChild (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30763:35)
    at visitor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165174:12)
    at visitNodes (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30254:22)
    at forEachChildInBlock (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30723:10)
    at forEachChild (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30763:35)
    at visitor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165174:12)
    at visitNode2 (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30246:18)
    at forEachChildInConstructor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30331:225)
    at forEachChild (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30763:35)
    at visitor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165174:12)
    at visitNodes (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30254:22)
    at forEachChildInClassDeclarationOrExpression (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30729:195)
    at forEachChild (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30763:35)
    at visitor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165174:12)
    at visitNodes (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30254:22)
    at forEachChildInSourceFile (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30467:12)
    at forEachChild (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30763:35)
    at visitor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165174:12)
    at Object.provideInlayHints (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165135:3)
    at Object.provideInlayHints2 [as provideInlayHints] (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:146125:34)
    at IpcIOSession.provideInlayHints (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:184639:48)
    at provideInlayHints (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:183797:43)
    at /Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:185817:69
    at IpcIOSession.executeWithRequestId (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:185809:14)
    at IpcIOSession.executeCommand (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:185817:29)
    at IpcIOSession.onMessage (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:185859:51)
    at process.<anonymous> (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:187468:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21): Error: <semantic> TypeScript Server Error (5.4.0-dev.20231120)
Debug Failure. Unexpected node.
Node ThisType was unexpected.
Error: Debug Failure. Unexpected node.
Node ThisType was unexpected.
    at visitForDisplayParts (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165745:17)
    at typeToInlayHintParts (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165429:5)
    at visitVariableLikeDeclaration (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165237:23)
    at visitor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165159:7)
    at visitNodes (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30254:22)
    at forEachChildInVariableDeclarationList (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30473:12)
    at forEachChild (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30763:35)
    at visitor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165174:12)
    at visitNode2 (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30246:18)
    at forEachChildInVariableStatement (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30470:59)
    at forEachChild (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30763:35)
    at visitor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165174:12)
    at visitNodes (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30254:22)
    at forEachChildInBlock (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30723:10)
    at forEachChild (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30763:35)
    at visitor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165174:12)
    at visitNode2 (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30246:18)
    at forEachChildInConstructor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30331:225)
    at forEachChild (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30763:35)
    at visitor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165174:12)
    at visitNodes (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30254:22)
    at forEachChildInClassDeclarationOrExpression (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30729:195)
    at forEachChild (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30763:35)
    at visitor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165174:12)
    at visitNodes (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30254:22)
    at forEachChildInSourceFile (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30467:12)
    at forEachChild (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:30763:35)
    at visitor (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165174:12)
    at Object.provideInlayHints (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:165135:3)
    at Object.provideInlayHints2 [as provideInlayHints] (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:146125:34)
    at IpcIOSession.provideInlayHints (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:184639:48)
    at provideInlayHints (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:183797:43)
    at /Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:185817:69
    at IpcIOSession.executeWithRequestId (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:185809:14)
    at IpcIOSession.executeCommand (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:185817:29)
    at IpcIOSession.onMessage (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:185859:51)
    at process.<anonymous> (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.4.20231120/node_modules/typescript/lib/tsserver.js:187468:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Function.create (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:2:473260)
    at v.w (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:2:468585)
    at v.u (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:2:467668)
    at ChildProcess.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:2:467300)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by MariaSolOs** [comment]
@ulugbekna Oh yeah, we're not handling that `ThisType` yet. Working on it.
