### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'flags')

### ISSUE THREAD

**Issue by PranavSenthilnathan** [microsoft/TypeScript#56402]
<h2>TypeError: Cannot read properties of undefined (reading 'flags')</h2>

```
Req #5859 - completionInfo
    at getSymbolLinks (/typescript-5.4.0-dev.20231105/lib/tsserver.js:49317:16)
    at runWithoutResolvedSignatureCaching (/typescript-5.4.0-dev.20231105/lib/tsserver.js:48396:32)
    at runWithInferenceBlockedFromSourceNode (/typescript-5.4.0-dev.20231105/lib/tsserver.js:48424:20)
    at Object.getContextualType (/typescript-5.4.0-dev.20231105/lib/tsserver.js:48133:16)
    at getContextualType (/typescript-5.4.0-dev.20231105/lib/tsserver.js:159233:19)
    at getCompletionData (/typescript-5.4.0-dev.20231105/lib/tsserver.js:159464:43)
    at Object.getCompletionsAtPosition (/typescript-5.4.0-dev.20231105/lib/tsserver.js:157444:26)
    at Object.getCompletionsAtPosition2 [as getCompletionsAtPosition] (/typescript-5.4.0-dev.20231105/lib/tsserver.js:145284:35)
    at IOSession.getCompletions (/typescript-5.4.0-dev.20231105/lib/tsserver.js:184857:54)
    at completionInfo (/typescript-5.4.0-dev.20231105/lib/tsserver.js:183253:43)
    at /typescript-5.4.0-dev.20231105/lib/tsserver.js:185641:69
    at IOSession.executeWithRequestId (/typescript-5.4.0-dev.20231105/lib/tsserver.js:185633:14)
    at IOSession.executeCommand (/typescript-5.4.0-dev.20231105/lib/tsserver.js:185641:29)
    at IOSession.onMessage (/typescript-5.4.0-dev.20231105/lib/tsserver.js:185683:51)
    at Interface.<anonymous> (/typescript-5.4.0-dev.20231105/lib/tsserver.js:187241:14)
```

<h4>Affected repos</h4>
<details>
<summary><a href="https://github.com/dimsemenov/PhotoSwipe">dimsemenov/PhotoSwipe</a></summary>
Raw error text: <code>RepoResults7/dimsemenov.PhotoSwipe.rawError.txt</code> in the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=158498&view=artifacts&type=publishedArtifacts">artifact folder</a>
<h4>Last few requests</h4>

```json
{"seq":5856,"type":"request","command":"completionEntryDetails","arguments":{"file":"@PROJECT_ROOT@/dist/types/core/eventable.d.ts","line":917,"offset":4,"entryNames":["@abstract"]}}
{"seq":5857,"type":"request","command":"completionInfo","arguments":{"file":"@PROJECT_ROOT@/dist/types/core/eventable.d.ts","line":917,"offset":34,"includeExternalModuleExports":false,"triggerKind":2,"triggerCharacter":" "}}
{"seq":5858,"type":"request","command":"definitionAndBoundSpan","arguments":{"file":"@PROJECT_ROOT@/dist/types/core/eventable.d.ts","line":921,"offset":4}}
{"seq":5859,"type":"request","command":"completionInfo","arguments":{"file":"@PROJECT_ROOT@/dist/types/core/eventable.d.ts","line":925,"offset":48,"includeExternalModuleExports":false,"triggerKind":1}}

```

<h4>Repro steps</h4>
<ol>
<li><code>git clone https://github.com/dimsemenov/PhotoSwipe --recurse-submodules</code></li>
<li>In dir <code>PhotoSwipe</code>, run <code>git reset --hard 2d23b36c99411d2dc45bf6610498754bf301b41c</code></li>
<li><details><summary>Install packages (exact steps are below, but it might be easier to follow the repo readme)</summary><ol>
  <li>In dir <code>PhotoSwipe/demo-docs-website</code>, run <code>npm ci --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>PhotoSwipe</code>, run <code>npm ci --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
</ol></details>
<li>Back in the initial folder, download <code>RepoResults7/dimsemenov.PhotoSwipe.replay.txt</code> from the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=158498&view=artifacts&type=publishedArtifacts">artifact folder</a></li>
<li><code>npm install --no-save @typescript/server-replay</code></li>
<li><code>npx tsreplay ./PhotoSwipe ./dimsemenov.PhotoSwipe.replay.txt path/to/tsserver.js</code></li>
<li><code>npx tsreplay --help</code> to learn about helpful switches for debugging, logging, etc</li>
</ol>
</details>

_Originally posted by @typescript-bot in https://github.com/microsoft/TypeScript/issues/56319#issuecomment-1793852077_

**Comment by jakebailey** [comment]
See https://github.com/microsoft/TypeScript/pull/56257
