### ISSUE TITLE
Having issues with ts throwing me errors in my Nx repo using TS V5.2.2

### ISSUE THREAD

**Issue by Roboromeo1** [microsoft/TypeScript#56406]
### 🔎 Search Terms

✗ nx build client --verbose            

> nx run client:build:production

(node:41284) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - Skipping linting
info  - Checking validity of types ...
 >  NX   Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at new NodeLinks (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:45676:21)
    at getNodeLinks (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:47097:56)
    at getResolvedSymbol (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:67153:21)
    at checkIdentifier (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:69385:22)
    at checkExpressionWorker (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:77867:18)
    at checkExpression (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:77822:34)
    at checkNonNullExpression (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:72124:31)
    at checkPropertyAccessExpression (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:72203:164)
    at checkExpressionWorker (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:77906:18)
    at checkExpression (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:77822:34)

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target build for project client failed

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

nx build client --verbose            

> nx run client:build:production

(node:41284) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - Skipping linting
info  - Checking validity of types ...
 >  NX   Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at new NodeLinks (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:45676:21)
    at getNodeLinks (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:47097:56)
    at getResolvedSymbol (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:67153:21)
    at checkIdentifier (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:69385:22)
    at checkExpressionWorker (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:77867:18)
    at checkExpression (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:77822:34)
    at checkNonNullExpression (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:72124:31)
    at checkPropertyAccessExpression (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:72203:164)
    at checkExpressionWorker (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:77906:18)
    at checkExpression (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:77822:34)

### 🙂 Expected behavior

nx build client --verbose            

> nx run client:build:production

(node:41284) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - Skipping linting
info  - Checking validity of types ...
 >  NX   Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at new NodeLinks (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:45676:21)
    at getNodeLinks (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:47097:56)
    at getResolvedSymbol (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:67153:21)
    at checkIdentifier (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:69385:22)
    at checkExpressionWorker (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:77867:18)
    at checkExpression (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:77822:34)
    at checkNonNullExpression (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:72124:31)
    at checkPropertyAccessExpression (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:72203:164)
    at checkExpressionWorker (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:77906:18)
    at checkExpression (/Users/aram/src/digital-forms-v3/node_modules/typescript/lib/typescript.js:77822:34)

**Comment by fatcerberus** [comment]
Your expected behavior is... to still get the crash?

At any rate you didn't properly fill out the bug report template (you just spammed some terminal output 3 times - please don't do that, once is sufficient) and you're most likely going to be asked to provide a repro.

**Comment by Roboromeo1** [comment]
solved it  worked when i did 
node --max-old-space-size=8192 ./node_modules/.bin/nx build client --verbose

**Comment by Roboromeo1** [comment]
increasing my memory to 8 worked for me 
node --max-old-space-size=8192 ./node_modules/.bin/nx build client --verbose
