### ISSUE TITLE
visitor of visitEachChild doesn't support returning InferTypeNode

### ISSUE THREAD

**Issue by marcus-sa** [microsoft/TypeScript#56480]
### 🔎 Search Terms

`False expression: Unexpected node`
`Node InferType did not pass test 'isEntityName'.`

### 💻 Code
https://github.com/marcus-sa/deepkit-framework/blob/9c9eb001459a4e1046aea94cb531ba5d8ca3b1c9/packages/type-compiler/src/compiler.ts#L2353-L2370

### 🙁 Actual behavior
Visitor callback of visitEachChild doesn't support returning InferTypeNode when the node is a TypeReferenceNode
``` 
Verbose Debug Information: Node InferType did not pass test 'isEntityName'.
           at visitNode (/Users/marcus-sa/Git/deepkit/deepkit-framework/node_modules/typescript/lib/typescript.js:87180:11)
           at visitEachChildOfTypeReferenceNode (/Users/marcus-sa/Git/deepkit/deepkit-framework/node_modules/typescript/lib/typescript.js:87589:32)
           at visitEachChild (/Users/marcus-sa/Git/deepkit/deepkit-framework/node_modules/typescript/lib/typescript.js:87421:35)
           at ReflectionTransformer.resolveTypeParameter (file:///Users/marcus-sa/Git/deepkit/deepkit-framework/packages/type-compiler/dist/esm/src/compiler.js:1910:54)
```

### 🙂 Expected behavior

For it to work

**Comment by marcus-sa** [comment]
The following patch fixes it
```patch
diff --git a/node_modules/typescript/lib/typescript.js b/node_modules/typescript/lib/typescript.js
index 86ab90b..dc72ecb 100644
--- a/node_modules/typescript/lib/typescript.js
+++ b/node_modules/typescript/lib/typescript.js
@@ -87586,7 +87586,7 @@ ${lanes.join("\n")}
         [183 /* TypeReference */]: function visitEachChildOfTypeReferenceNode(node, visitor, context, nodesVisitor, nodeVisitor, _tokenVisitor) {
           return context.factory.updateTypeReferenceNode(
             node,
-            Debug.checkDefined(nodeVisitor(node.typeName, visitor, isEntityName)),
+            Debug.checkDefined(nodeVisitor(node.typeName, visitor, node => isTypeNode(node) || isEntityName(node))),
             nodesVisitor(node.typeArguments, visitor, isTypeNode)
           );
         },
```

**Comment by marcus-sa** [comment]
@marcj does the generated code look right to you here?
Input
```ts
export function createModule<T1 extends CreateModuleDefinition>(
  options: T1,
  name: string = '',
): AppModuleClass<ExtractClassType<T1['config']>> {
  return class AnonAppModule extends AppModule<T1> {
    constructor(config?: PartialDeep<ExtractClassType<T1['config']>>) {
      super(options, name);
      if (config) {
        this.configure(config);
      }
    }
  } as any;
}
```
Output
```js
function createModule(options, name = '') {
    return class AnonAppModule extends AppModule {
        constructor(config) {
            super(options, name);
            if (config) {
                this.configure(config);
            }
        }
        static { this.__type = [() => options, () => AppModule, 'config', 'constructor', () => options, 'AnonAppModule', 'PPdi!h!!qe!!!j7"P"2#8"0$5Pdi%h!!qe!!!j6"w&']; }
    };
}
createModule.__type = ['options', 'name', () => "", () => __ΩAppModuleClass, () => __ΩExtractClassType, "config", 'createModule', 'P"2!&2">#".&fo%"o$"/\''];
```

**Comment by marcus-sa** [comment]
@andrewbranch where are we with this?

**Comment by rbuckton** [comment]
A `TypeReferenceNode` shouldn't have an `InferTypeNode` in its `typeName` property, so the error you see is correct and indicates a problem in your code. Looking at the code you linked to, I believe you are incorrectly updating the tree with a node in an invalid position. You shouldn't be replacing an `Identifier` with an `InferTypeNode`, you should be looking for the `TypeReferenceNode` *containing* that identifier and replace it instead.

```ts
const searchArgument = (node: Node): Node => {
    node = visitEachChild(node, searchArgument, this.context);

    if (isTypeReferenceNode(node) && isIdentifier(node.typeName) && node.typeName.escapedText === argumentName) {
        //transform to infer T
        found = true;
        node = this.f.createInferTypeNode(declaration);
    }

    return node;
};
```

**Comment by marcus-sa** [comment]
@rbuckton thanks a lot!
