### ISSUE TITLE
Debug Failure with `strictFunctionTypes`: type provided should not be a non-generic 'promise'-like

### ISSUE THREAD

**Issue by frigus02** [microsoft/TypeScript#56509]
### 🔎 Search Terms

type provided should not be a non-generic 'promise'-like

### 🕗 Version & Regression Information

- This is a crash
- This is the behavior in every version I tried: v5.2.2 and v5.3.2

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?&noLib=true#code/C4TwDgpgBAcg9sACgJzgWwJYGcIB4AqAfFALxT5QQAewEAdgCZbkAW9dAhgEYA2eArnQDWdOAHc6hAFBQoAfnIyoALnKUa9JlBTpsEADIYhA4aInTZCuhABuEZEtX4A3FKmhIUAEoQAxhAw7ZAJiMgAKGw4efghVeCRUTBwQgEpSYhs4DAZXKV8eDixmfDY6Tl48IigAbyVgUrCOVR9-QPtUmoBfN1kwZECOWigWDkY+Hyw4HjsCCf4eYEIwpVlkCCx54DiEHSTKuYXiAB9Wdm4+XHjdvVn1zcJCABoVqDXJ6djvPwCg243D56yNK1WSyDAAMygYTemygGDoWGAo38cEhJTOFWBL1kAHocVAAKLIVDIVQAEQgXH4AHMoAAxDgYaJrAB09KiOHUfXWWAwcDoqg80D6cBs2QgDCgWBYcHmktEwCgXGgHCgojoAFpqfR7BhfFAAOQivYGjU8IwQFnYqD1bAst5TOzXHDQu4LR6vdaOiApVygqDdWTdJR9AZDB0fZ37N2LZb+mELJylcoXfAHRaA0ERuzNb5tYJpmNPJTA7qdIA)

Note: Because this is a crash, the playground looks broken. The browser console has the stack trace.

### 💻 Code

```ts repro
// @strict
type NotPromise<T> = T extends Thennable<unknown>
  ? T
  : T extends PromiseLike<unknown>
  ? never
  : T;

type Receiver<T> = (value: NotPromise<T>) => void;

class Thennable<T> {
  then(a: Receiver<T>) {}

  private handleResolve<TResult>(
    result: NotPromise<TResult> | Thennable<NotPromise<TResult>>,
    resolve: Receiver<TResult>,
  ) {
    if (result instanceof Thennable) {
      // Error: Debug Failure. False expression: type provided should not be a non-generic 'promise'-like.
      this.resolvePromise(result, resolve);
    }
  }

  private resolvePromise<TResult>(
    result: Thennable<TResult>,
    resolve: Receiver<TResult>,
  ) {}
}
```

### 🙁 Actual behavior

```
Error: Debug Failure. False expression: type provided should not be a non-generic 'promise'-like.
    at createAwaitedTypeIfNeeded (/test-ts-debug-assert-promise-like/node_modules/typescript/lib/tsc.js:76671:11)
    at getAwaitedType (/test-ts-debug-assert-promise-like/node_modules/typescript/lib/tsc.js:76676:27)
    at getAwaitedTypeOfPromise (/test-ts-debug-assert-promise-like/node_modules/typescript/lib/tsc.js:76554:28)
    at maybeAddMissingAwaitInfo (/test-ts-debug-assert-promise-like/node_modules/typescript/lib/tsc.js:70872:13)
    at getSignatureApplicabilityError (/test-ts-debug-assert-promise-like/node_modules/typescript/lib/tsc.js:70837:11)
    at resolveCall (/test-ts-debug-assert-promise-like/node_modules/typescript/lib/tsc.js:71232:25)
    at resolveCallExpression (/test-ts-debug-assert-promise-like/node_modules/typescript/lib/tsc.js:71633:12)
    at resolveSignature (/test-ts-debug-assert-promise-like/node_modules/typescript/lib/tsc.js:72037:16)
    at getResolvedSignature (/test-ts-debug-assert-promise-like/node_modules/typescript/lib/tsc.js:72059:18)
    at checkCallExpression (/test-ts-debug-assert-promise-like/node_modules/typescript/lib/tsc.js:72171:23)
```

at the node `this.resolvePromise(result, resolve);`

### 🙂 Expected behavior

No crash.

### Additional information about the issue

Found this when migrating to `ts.transpileModule`. As far as I can tell it's triggered by 2 conditions, which all have to be true:

- `strictFunctionTypes: true`
- The type `PromiseLike` must not exist, e.g. by using `noLib: true`

**Comment by jakebailey** [comment]
FWIW I tested this and it's just always happened (as noted in the issue), so a bisect is gonna do something funky.

**Comment by andrewbranch** [comment]
The crash doesn't show up in the playground in 4.7, at least not on page load

**Comment by jakebailey** [comment]
Ah, I must have done something wrong.
