### ISSUE TITLE
Crash on 5.4.0-dev.20231206

### ISSUE THREAD

**Issue by ArnaudBarre** [microsoft/TypeScript#56688]
### 🔎 Search Terms

-

### 🕗 Version & Regression Information

It's working on 5.3
Here is the stacktrace, I hope it helps, I don't really have time to disect which part my codebase triggers this. Feel free to close if this not enough to understand the regression
 
 ```
 TypeError: Cannot read properties of undefined (reading '0')
    at removeConstrainedTypeVariables (/Users/arnaud/git/carbon-calculator/node_modules/typescript/lib/tsc.js:57118:33)
    at getUnionTypeWorker (/Users/arnaud/git/carbon-calculator/node_modules/typescript/lib/tsc.js:57215:9)
    at getUnionType (/Users/arnaud/git/carbon-calculator/node_modules/typescript/lib/tsc.js:57194:12)
    at createJsxAttributesTypeFromAttributesProperty (/Users/arnaud/git/carbon-calculator/node_modules/typescript/lib/tsc.js:69288:216)
    at checkJsxAttributes (/Users/arnaud/git/carbon-calculator/node_modules/typescript/lib/tsc.js:69353:12)
    at checkExpressionWorker (/Users/arnaud/git/carbon-calculator/node_modules/typescript/lib/tsc.js:75700:16)
    at checkExpression (/Users/arnaud/git/carbon-calculator/node_modules/typescript/lib/tsc.js:75557:32)
    at checkExpressionWithContextualType (/Users/arnaud/git/carbon-calculator/node_modules/typescript/lib/tsc.js:75203:18)
    at resolveJsxOpeningLikeElement (/Users/arnaud/git/carbon-calculator/node_modules/typescript/lib/tsc.js:72230:51)
    at resolveSignature (/Users/arnaud/git/carbon-calculator/node_modules/typescript/lib/tsc.js:72303:16)
 ```

### 🙁 Actual behavior

Crash

### 🙂 Expected behavior

No crash

**Comment by Andarist** [comment]
Does it crash on `5.4.0-dev.20231206` too?

**Comment by Andarist** [comment]
`removeConstrainedTypeVariables` was introduced in https://github.com/microsoft/TypeScript/pull/56515 . Could you confirm that `5.4.0-dev.20231130` works OK but `5.4.0-dev.20231201` is broken? Even with that confirmation - it might be hard to fix this without a repro case. If you'd be interested I could try to guide you on how to at least narrow it down to the file in which the problem occurs. With that information, you'd have an easier time dissecting this to a minimal repro case.

**Comment by ArnaudBarre** [comment]
Ok so yes it crashes starting on `20231201`.
I ran the debugger and found the file, and after few try and errors I think this is this combination:
```
// .d.ts
declare global {
  interface String {
    upperFirst<T extends string>(this: T): Capitalize<T>;
  }
}

// display.ts
const displayEnum = (value: string) => value.upperFirst();

// Component.tsx
<>{displayEnum("VALUE")}</> 
```

**Comment by jakebailey** [comment]
It's in the template, but you can also use https://www.npmjs.com/package/every-ts to narrow it down further.

I can't get your case to crash in the test suite, unfortunately.

**Comment by ArnaudBarre** [comment]
Ok this is the missing piece, the span before is strangely required:
Here is my mininal repro, I don't think my TS config should have an impact on the crash
```
declare global {
  interface String {
    upperFirst<T extends string>(this: T): Capitalize<T>;
  }
}

const displayEnum = (value: string) => value.toLowerCase().upperFirst();

console.log(
  <div>
    <span>Scope:</span> {displayEnum("VALUE")}
  </div>,
);

export {};
```
