### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/TypeScript#56697]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.3.2

**Steps to reproduce crash**

1. Sorry don't have any other than I had this project open: https://github.com/microsoft/pyrx
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `syntax`

```
Error: Debug Failure. False expression.
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\rchiodo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181346:13)
    at c:\Users\rchiodo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181577:64
    at flatMap (c:\Users\rchiodo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2597:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\rchiodo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:181577:24)
    at updateOpen (c:\Users\rchiodo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:182775:29)
    at c:\Users\rchiodo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185377:69
    at IpcIOSession.executeWithRequestId (c:\Users\rchiodo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185369:14)
    at IpcIOSession.executeCommand (c:\Users\rchiodo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185377:29)
    at IpcIOSession.onMessage (c:\Users\rchiodo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:185419:51)
    at process.<anonymous> (c:\Users\rchiodo\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:187001:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

VS Code version: Code - Insiders 1.85.0-insider (7caa3f698d26f7929822064baa1f3b23e7955c7d, 2023-12-01T14:17:40.644Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7763 64-Core Processor                 (16 x 2445)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|63.95GB (49.20GB free)|
|Process Argv|. --crash-reporter-id fb5f004c-0c45-4402-af67-bb66466f13d8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.2
prettier-vscode|esb|10.1.0
python|ms-|2023.21.13351006
vscode-pylance|ms-|2023.11.100
jupyter|ms-|2023.11.1003351000
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
a9j8j154:30646983
showlangstatbar:30737417
f8hc8238:30694864
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpsinfo:30901776
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by mjbvz** [comment]
Can you Ppease try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by rchiodo** [comment]
Unfortunately, I haven't reproduced the problem since. It happened just once.

**Comment by samschurter** [comment]
I'm able to reproduce it consistently now. I was working in a project and everything was fine, but with one particular file, IntelliSense shows one popup and then dies with the `False expression` error in the extension output. In the logs it looks like the typescript server is working and doing all the setup, but as soon as I type one character, it crashes. 

```
Info 241  [11:47:07.635] request:
    {
      "seq": 48,
      "type": "request",
      "command": "quickinfo",
      "arguments": {
        "file": "/Users/sschurter/Development/RequestRaven/frontend/src/store.js",
        "line": 1,
        "offset": 34
      }
    }
Perf 242  [11:47:07.636] 48::quickinfo: elapsed time (in milliseconds) 0.8140
Info 243  [11:47:07.636] response:
    {"seq":0,"type":"response","command":"quickinfo","request_seq":48,"success":true,"body":{"kind":"alias","kindModifiers":"export,declare","start":{"line":1,"offset":29},"end":{"line":1,"offset":34},"displayString":"(alias) function query<AppModelType, DbModelType extends DocumentData>(query: Query<AppModelType, DbModelType>, compositeFilter: QueryCompositeFilterConstraint, ...queryConstraints: QueryNonFilterConstraint[]): Query<AppModelType, DbModelType> (+1 overload)\nimport query","documentation":[{"text":"Creates a new immutable instance of ","kind":"text"},{"text":"{@link ","kind":"link"},{"text":"Query","kind":"linkName","target":{"file":"/Users/sschurter/Development/RequestRaven/frontend/node_modules/@firebase/firestore/dist/index.d.ts","start":{"line":1849,"offset":1},"end":{"line":1880,"offset":2}}},{"text":"}","kind":"link"},{"text":" that is extended to also\ninclude additional query constraints.","kind":"text"}],"tags":[{"name":"param","text":[{"text":"query","kind":"parameterName"},{"text":" ","kind":"space"},{"text":"- The ","kind":"text"},{"text":"{@link ","kind":"link"},{"text":"Query","kind":"linkName","target":{"file":"/Users/sschurter/Development/RequestRaven/frontend/node_modules/@firebase/firestore/dist/index.d.ts","start":{"line":1849,"offset":1},"end":{"line":1880,"offset":2}}},{"text":"}","kind":"link"},{"text":" instance to use as a base for the new\nconstraints.","kind":"text"}]},{"name":"param","text":[{"text":"compositeFilter","kind":"parameterName"},{"text":" ","kind":"space"},{"text":"- The ","kind":"text"},{"text":"{@link ","kind":"link"},{"text":"QueryCompositeFilterConstraint","kind":"linkName","target":{"file":"/Users/sschurter/Development/RequestRaven/frontend/node_modules/@firebase/firestore/dist/index.d.ts","start":{"line":1915,"offset":1},"end":{"line":1918,"offset":2}}},{"text":"}","kind":"link"},{"text":" to\napply. Create ","kind":"text"},{"text":"{@link ","kind":"link"},{"text":"QueryCompositeFilterConstraint","kind":"linkName","target":{"file":"/Users/sschurter/Development/RequestRaven/frontend/node_modules/@firebase/firestore/dist/index.d.ts","start":{"line":1915,"offset":1},"end":{"line":1918,"offset":2}}},{"text":"}","kind":"link"},{"text":" using ","kind":"text"},{"text":"{@link ","kind":"link"},{"text":"and","kind":"linkName","target":{"file":"/Users/sschurter/Development/RequestRaven/frontend/node_modules/@firebase/firestore/dist/index.d.ts","start":{"line":115,"offset":1},"end":{"line":115,"offset":107}}},{"text":"}","kind":"link"},{"text":" or\n","kind":"text"},{"text":"{@link ","kind":"link"},{"text":"or","kind":"linkName","target":{"file":"/Users/sschurter/Development/RequestRaven/frontend/node_modules/@firebase/firestore/dist/index.d.ts","start":{"line":1707,"offset":1},"end":{"line":1707,"offset":106}}},{"text":"}","kind":"link"},{"text":".","kind":"text"}]},{"name":"param","text":[{"text":"queryConstraints","kind":"parameterName"},{"text":" ","kind":"space"},{"text":"- Additional ","kind":"text"},{"text":"{@link ","kind":"link"},{"text":"QueryNonFilterConstraint","kind":"linkName","target":{"file":"/Users/sschurter/Development/RequestRaven/frontend/node_modules/@firebase/firestore/dist/index.d.ts","start":{"line":2017,"offset":1},"end":{"line":2017,"offset":142}}},{"text":"}","kind":"link"},{"text":"s to\napply (e.g. ","kind":"text"},{"text":"{@link ","kind":"link"},{"text":"orderBy","kind":"linkName","target":{"file":"/Users/sschurter/Development/RequestRaven/frontend/node_modules/@firebase/firestore/dist/index.d.ts","start":{"line":1720,"offset":1},"end":{"line":1720,"offset":121}}},{"text":"}","kind":"link"},{"text":", ","kind":"text"},{"text":"{@link ","kind":"link"},{"text":"limit","kind":"linkName","target":{"file":"/Users/sschurter/Development/RequestRaven/frontend/node_modules/@firebase/firestore/dist/index.d.ts","start":{"line":1338,"offset":1},"end":{"line":1338,"offset":68}}},{"text":"}","kind":"link"},{"text":").","kind":"text"}]},{"name":"throws","text":[{"text":"if any of the provided query constraints cannot be combined with the\nexisting or new constraints.","kind":"text"}]}]}}
Info 244  [11:47:08.982] request:
    {
      "seq": 49,
      "type": "request",
      "command": "updateOpen",
      "arguments": {
        "changedFiles": [
          {
            "fileName": "/Users/sschurter/Development/RequestRaven/frontend/src/store.js",
            "textChanges": [
              {
                "newText": ",",
                "start": {
                  "line": 1,
                  "offset": 34
                },
                "end": {
                  "line": 1,
                  "offset": 34
                }
              }
            ]
          }
        ],
        "closedFiles": [],
        "openFiles": []
      }
    }
Perf 245  [11:47:08.982] 49::updateOpen: elapsed time (in milliseconds) 0.3757
Info 246  [11:47:08.982] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":49,"success":true,"body":true}
Info 247  [11:47:08.983] request:
    {
      "seq": 50,
      "type": "request",
      "command": "signatureHelp",
      "arguments": {
        "file": "/Users/sschurter/Development/RequestRaven/frontend/src/store.js",
        "line": 1,
        "offset": 35,
        "triggerReason": {
          "kind": "characterTyped",
          "triggerCharacter": ","
        }
      }
    }
Err 248   [11:47:08.993] Exception on executing command {
  "seq": 50,
  "type": "request",
  "command": "signatureHelp",
  "arguments": {
    "file": "/Users/sschurter/Development/RequestRaven/frontend/src/store.js",
    "line": 1,
    "offset": 35,
    "triggerReason": {
      "kind": "characterTyped",
      "triggerCharacter": ","
    }
  }
}:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at InferredProject2.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177374:11)
        at InferredProject2.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177233:32)
        at updateProjectIfDirty (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178944:35)
        at InferredProject2.getLanguageService (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176844:7)
        at IpcIOSession.getSignatureHelpItems (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:184740:31)
        at signatureHelp (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183018:43)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185377:69
        at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185369:14)
        at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185377:29)
        at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185419:51)
        at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:187001:14)
        at process.emit (node:events:513:28)
        at emit (node:internal/child_process:937:14)
        at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

File text of /Users/sschurter/Development/RequestRaven/frontend/src/store.js:
    import { collection, where, query, } from "firebase/firestore";
    import { db, auth, collectionName } from "./services/FirebaseService";
    import { errorHandler } from "./main";
    
    export const mutations = {
      /**
       * Set requests first checks if the code calling it has designated whether we are loading
       * the archived requests or the active requests.
       * If we are loading the active requests, then isArchived has to be false.
       * If we are loading the archived requests, then isArchived has to be true.
       */
      setRequests(state, isArchived) {
        let items = [];
        query(collection(db, collectionName), where("archived", "==", isArchived))
          .onSnapshot(snapshot => {
            items = [];
            snapshot.forEach(doc => {
              items.push({
                id: doc.id,
                name: doc.data().name,
                data: doc.data()
              });
            });
            errorHandler.report(
              `setRequests: ${isArchived}, returning ${items.length} items`
            );
            if (isArchived) {
              state.archiveRequests = items;
            } else if (!isArchived) {
              state.activeRequests = items;
            }
          });
      },
    };
    
    
    
    

Info 249  [11:47:08.993] response:
    {"seq":0,"type":"response","command":"signatureHelp","request_seq":50,"success":false,"message":"Error processing request. Debug Failure. False expression.\nError: Debug Failure. False expression.\n    at InferredProject2.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177374:11)\n    at InferredProject2.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177233:32)\n    at updateProjectIfDirty (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178944:35)\n    at InferredProject2.getLanguageService (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176844:7)\n    at IpcIOSession.getSignatureHelpItems (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:184740:31)\n    at signatureHelp (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183018:43)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185377:69\n    at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185369:14)\n    at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185377:29)\n    at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185419:51)\n    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:187001:14)\n    at process.emit (node:events:513:28)\n    at emit (node:internal/child_process:937:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)"}
Info 250  [11:47:09.007] request:
    {
      "seq": 51,
      "type": "request",
      "command": "encodedSemanticClassifications-full",
      "arguments": {
        "file": "/Users/sschurter/Development/RequestRaven/frontend/src/store.js",
        "start": 0,
        "length": 207,
        "format": "2020"
      }
    }
Err 251   [11:47:09.007] Exception on executing command {
  "seq": 51,
  "type": "request",
  "command": "encodedSemanticClassifications-full",
  "arguments": {
    "file": "/Users/sschurter/Development/RequestRaven/frontend/src/store.js",
    "start": 0,
    "length": 207,
    "format": "2020"
  }
}:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at InferredProject2.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177374:11)
        at InferredProject2.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177233:32)
        at updateProjectIfDirty (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178944:35)
        at InferredProject2.getLanguageService (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176844:7)
        at IpcIOSession.getEncodedSemanticClassifications (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183735:20)
        at encodedSemanticClassifications-full (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183038:43)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185377:69
        at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185369:14)
        at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185377:29)
        at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185419:51)
        at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:187001:14)
        at process.emit (node:events:513:28)
        at emit (node:internal/child_process:937:14)
        at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

File text of /Users/sschurter/Development/RequestRaven/frontend/src/store.js:
    import { collection, where, query, } from "firebase/firestore";
    import { db, auth, collectionName } from "./services/FirebaseService";
    import { errorHandler } from "./main";
    
    export const mutations = {
      /**
       * Set requests first checks if the code calling it has designated whether we are loading
       * the archived requests or the active requests.
       * If we are loading the active requests, then isArchived has to be false.
       * If we are loading the archived requests, then isArchived has to be true.
       */
      setRequests(state, isArchived) {
        let items = [];
        query(collection(db, collectionName), where("archived", "==", isArchived))
          .onSnapshot(snapshot => {
            items = [];
            snapshot.forEach(doc => {
              items.push({
                id: doc.id,
                name: doc.data().name,
                data: doc.data()
              });
            });
            errorHandler.report(
              `setRequests: ${isArchived}, returning ${items.length} items`
            );
            if (isArchived) {
              state.archiveRequests = items;
            } else if (!isArchived) {
              state.activeRequests = items;
            }
          });
      },
    };
    
    
    
    

Info 252  [11:47:09.007] response:
    {"seq":0,"type":"response","command":"encodedSemanticClassifications-full","request_seq":51,"success":false,"message":"Error processing request. Debug Failure. False expression.\nError: Debug Failure. False expression.\n    at InferredProject2.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177374:11)\n    at InferredProject2.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177233:32)\n    at updateProjectIfDirty (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178944:35)\n    at InferredProject2.getLanguageService (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176844:7)\n    at IpcIOSession.getEncodedSemanticClassifications (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183735:20)\n    at encodedSemanticClassifications-full (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183038:43)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185377:69\n    at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185369:14)\n    at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185377:29)\n    at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185419:51)\n    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:187001:14)\n    at process.emit (node:events:513:28)\n    at emit (node:internal/child_process:937:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)"}
Info 253  [11:47:09.008] request:
    {
      "seq": 52,
      "type": "request",
      "command": "encodedSemanticClassifications-full",
      "arguments": {
        "file": "/Users/sschurter/Development/RequestRaven/frontend/src/store.js",
        "start": 512,
        "length": 641,
        "format": "2020"
      }
    }
Err 254   [11:47:09.008] Exception on executing command {
  "seq": 52,
  "type": "request",
  "command": "encodedSemanticClassifications-full",
  "arguments": {
    "file": "/Users/sschurter/Development/RequestRaven/frontend/src/store.js",
    "start": 512,
    "length": 641,
    "format": "2020"
  }
}:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at InferredProject2.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177374:11)
        at InferredProject2.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177233:32)
        at updateProjectIfDirty (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178944:35)
        at InferredProject2.getLanguageService (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176844:7)
        at IpcIOSession.getEncodedSemanticClassifications (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183735:20)
        at encodedSemanticClassifications-full (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183038:43)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185377:69
        at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185369:14)
        at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185377:29)
        at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185419:51)
        at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:187001:14)
        at process.emit (node:events:513:28)
        at emit (node:internal/child_process:937:14)
        at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

File text of /Users/sschurter/Development/RequestRaven/frontend/src/store.js:
    import { collection, where, query, } from "firebase/firestore";
    import { db, auth, collectionName } from "./services/FirebaseService";
    import { errorHandler } from "./main";
    
    export const mutations = {
      /**
       * Set requests first checks if the code calling it has designated whether we are loading
       * the archived requests or the active requests.
       * If we are loading the active requests, then isArchived has to be false.
       * If we are loading the archived requests, then isArchived has to be true.
       */
      setRequests(state, isArchived) {
        let items = [];
        query(collection(db, collectionName), where("archived", "==", isArchived))
          .onSnapshot(snapshot => {
            items = [];
            snapshot.forEach(doc => {
              items.push({
                id: doc.id,
                name: doc.data().name,
                data: doc.data()
              });
            });
            errorHandler.report(
              `setRequests: ${isArchived}, returning ${items.length} items`
            );
            if (isArchived) {
              state.archiveRequests = items;
            } else if (!isArchived) {
              state.activeRequests = items;
            }
          });
      },
    };
```

The logs continue for several thousand lines after this that look pretty much identical

**Comment by samschurter** [comment]
I'm on MacOS 14.2
```
code --version
1.85.1
0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
x64
```

**Comment by sheetalkamat** [comment]
Please share the complete tsserver log along with the steps to repro. Thanks

**Comment by samschurter** [comment]
[tsserver.log](https://github.com/microsoft/TypeScript/files/13907926/tsserver.log)

Repro steps
1. Open a Vue 2.7 project in VS Code (it's not public so I can't share the repo)
2. Open `frontend/src/store.js` (You can see the project structure and loaded files in the log, as well as the full text of `store.js`)
3. Hover over anything. Intellisense (and the language server) function properly
4. Make any change to the file
5. Hover over any item. Intellisense is down and the language server has exited with `SIGTERM`.

Other files in the project will _eventually_ crash the server, but `store.js` is very reliable and crashes the language server after exactly one character entered, anywhere in the document. 

Even though the stack trace does not point to any extension files besides the built-in TypeScript language features, I tried turning off all extensions and the crash went away. I turned them back on one at a time and narrowed it down to [TypeScript Vue Plugin (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin) from [this repo](https://github.com/vuejs/language-tools). 

Since the stack trace doesn't list any files from that extension, I'm not sure if this is on them, or the TypeScript language features

**Comment by sheetalkamat** [comment]
I think this is fixed by #56356 
Can you try nightly typescript version and see if this is fixed

**Comment by samschurter** [comment]
I haven't tested thoroughly, but it seems like that did fix it! Thanks
