### ISSUE TITLE
tsc crash with jsdoc typedef and object exported with same name.

### ISSUE THREAD

**Issue by HOnatToprak** [microsoft/TypeScript#56891]
### 🔎 Search Terms

allowJs jsdoc

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

https://github.com/HOnatToprak/tsbug

### 🙁 Actual behavior

tsc crashes when I declare object and jsdoc typedef with same name, export the object and import the object from another file with commonjs syntax.

### 🙂 Expected behavior

Expected tsc to compile

**Comment by RyanCavanaugh** [comment]
Call stack
```
Error: Debug Failure. False expression.
    at checkAliasSymbol (C:\Users\ryanca\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:80247:17)
    at checkVariableLikeDeclaration (C:\Users\ryanca\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:77778:7)
    at checkVariableDeclaration (C:\Users\ryanca\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:77883:5)
    at checkSourceElementWorker (C:\Users\ryanca\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:80861:16)
    at checkSourceElement (C:\Users\ryanca\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:80690:7)
    at forEach (C:\Users\ryanca\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32:22)
    at checkVariableDeclarationList (C:\Users\ryanca\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:77895:5)
    at checkVariableStatement (C:\Users\ryanca\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:77900:5)
    at checkSourceElementWorker (C:\Users\ryanca\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:80830:16)
    at checkSourceElement (C:\Users\ryanca\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:80690:7)
```
