### ISSUE TITLE
Typescript compile throw exception when following syntax error occurred.

### ISSUE THREAD

**Issue by yingdeng93** [Microsoft/TypeScript#5693]
In a TypeScript file:

if (...) {
   ...
} else if (...) {
  ...
// } // If missing this }, then compile throw exception without any good hint where the fault is.
if (...) {
 ...
} 

Exception throw during compile...

E:\Oslo\sources\dev\Pulse\src\PulseNext\node_modules\typescript\lib\typescript.js:35660
                throw e;
                      ^
TypeError: Cannot read property 'export=' of undefined
    at checkExternalModuleExports (E:\Oslo\sources\dev\Pulse\src\PulseNext\node_modules\typescript\lib\typescript.j
s:24974:62)
    at checkExportAssignment (E:\Oslo\sources\dev\Pulse\src\PulseNext\node_modules\typescript\lib\typescript.js:249
41:13)
    at checkSourceElement (E:\Oslo\sources\dev\Pulse\src\PulseNext\node_modules\typescript\lib\typescript.js:25100:
28)
    at Object.forEach (E:\Oslo\sources\dev\Pulse\src\PulseNext\node_modules\typescript\lib\typescript.js:880:30)
    at checkBlock (E:\Oslo\sources\dev\Pulse\src\PulseNext\node_modules\typescript\lib\typescript.js:23316:16)
    at checkSourceElement (E:\Oslo\sources\dev\Pulse\src\PulseNext\node_modules\typescript\lib\typescript.js:25047:
28)
    at checkFunctionLikeDeclaration (E:\Oslo\sources\dev\Pulse\src\PulseNext\node_modules\typescript\lib\typescript
.js:23288:13)
    at checkMethodDeclaration (E:\Oslo\sources\dev\Pulse\src\PulseNext\node_modules\typescript\lib\typescript.js:22
371:13)
    at checkSourceElement (E:\Oslo\sources\dev\Pulse\src\PulseNext\node_modules\typescript\lib\typescript.js:25020:
28)
    at Object.forEach (E:\Oslo\sources\dev\Pulse\src\PulseNext\node_modules\typescript\lib\typescript.js:880:30)

**Comment by ahejlsberg** [comment]
Can you provide an actual repro we can use? The omitted `}` causes the rest of the file to be considered part of the `if` statement but we can't see what that is.

**Comment by ahejlsberg** [comment]
The .png image didn't come through. Would be best if you could create a small repro and include it in a comment.

**Comment by mhegazy** [comment]
This is not actionable at the moment, please reopen with additional information.
