### ISSUE TITLE
Decorators missing import for globalThis properties

### ISSUE THREAD

**Issue by dardavar** [microsoft/TypeScript#57056]
### 🔎 Search Terms

decorator, libdom, globalThis 

### 🕗 Version & Regression Information

- This is a crash

### 💻 Code

```ts
@myDecorator()
onConnection(socket: WebSocket, request: Request): Promise<void> {
     // implementation goes here
}
```

### 🙁 Actual behavior

/Users/giladdar/Documents/rocket-engine/server/dist/controller/websocket_controller.js:155
    __metadata("design:paramtypes", [WebSocket, Object]),
                                     ^
ReferenceError: WebSocket is not defined
    at Object.<anonymous> (/Users/giladdar/Documents/rocket-engine/server/dist/controller/websocket_controller.js:155:38)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module.m._compile (/Users/giladdar/Documents/rocket-engine/server/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .js] (/Users/giladdar/Documents/rocket-engine/server/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at Module.Hook._require.Module.require (/Users/giladdar/Documents/rocket-engine/server/node_modules/require-in-the-middle/index.js:188:39)
    at Module.Hook._require.Module.require (/Users/giladdar/Documents/rocket-engine/server/node_modules/require-in-the-middle/index.js:188:39)

### 🙂 Expected behavior

Everything will work fine.

### Additional information about the issue

Explicitly write
```ts
@myDecorator()
onConnection(socket: globalThis.WebSocket, request: Request): Promise<void> {
     // implementation goes here
}
```
fix the issue

**Comment by vandsonfalcao** [comment]
i have same problem!
console:
```
Debugger attached.

> node20-typescript-@1.0.0 test:debug
> node --env-file=.env --import ./ts-loader.js --no-warnings --inspect --watch --test ./test/*

Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: This Environment was initialized without a V8::Inspector
Debugger attached.
SERVER: running at port 3334
SERVER: close
▶ Test Server
  ✖ Open conection with server (0.861162ms)
    ReferenceError [Error]: WebSocket is not defined
        at TestContext.<anonymous> (file:///home/vandsonfalcao/Projects/node20-typescript/test/test.test.ts:11:24)
        at Test.runInAsyncScope (node:async_hooks:206:9)
        at Test.run (node:internal/test_runner/test:618:21)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at async Suite.run (node:internal/test_runner/test:948:7)
        at async startSubtest (node:internal/test_runner/harness:216:3)

▶ Test Server (24.970355ms)

Waiting for the debugger to disconnect...
```

**engine:** node20

**to reproduce:**
on running: ```npm run dev``` and connect with index.html, wotks!
but run tests with debug on vscode receive error!

package.json
```
{
  "name": "node20-typescript-",
  "version": "1.0.0",
  "description": "Initial configuration to start Typescript projects with the nodeJS engine.",
  "main": "src/server.ts",
  "type": "module",
  "scripts": {
    "dev": "node --env-file=.env --import ./ts-loader.js --watch --no-warnings ./src/server.ts",
    "test": "node --env-file=.env --import ./ts-loader.js --test  ./test/*",
    "test:coverage": "node --env-file=.env --import ./ts-loader.js --experimental-test-coverage --test  ./test/*",
    "test:debug": "node --env-file=.env --import ./ts-loader.js --no-warnings --inspect --watch --test ./test/*"
  },
  "keywords": [],
  "author": "Vandson Falcão",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^20.11.20",
    "ts-node": "^10.9.2",
    "typescript": "^5.3.3"
  }
}
```

tsconfig.json
```
{
	"compilerOptions": {
		"target": "ESNext",
		"module": "ESNext",
		"moduleResolution": "Node",
		"paths": {
			"*": ["./node_modules/*"]
		},
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"strict": true,
		"skipLibCheck": true,
		"noEmit": true,
		"allowImportingTsExtensions": true
	},
	"ts-node": {
		"esm": true,
		"experimentalResolver": true,
		"experimentalSpecifierResolution": "node",
		"transpileOnly": true
	},
	"exclude": ["./ts-loader.js"]
}
```

ts-loader.js
```
import { register } from "node:module";
import { pathToFileURL } from "node:url";
register("ts-node/esm", pathToFileURL("./"));
```

src/server.ts
```
import { IncomingHttpHeaders, createServer } from "node:http";
import { PORT } from "./config/constants.ts";

type CustomHeaders = IncomingHttpHeaders & { "sec-websocket-key": string };
const httpServer = createServer((request, response) => {
	response.writeHead(200);
	response.end("hey there");
});
httpServer.on("connection", (event) => console.log(`SERVER: WebSocket is connected!`));
httpServer.on("error", (error) => console.log(`SERVER: Error!!!`, error));
httpServer.on("close", () => console.log("SERVER: close"));
httpServer.on("upgrade", (request, socket, head) => {
	const { "sec-websocket-key": webClientSocketKey } = request.headers as CustomHeaders;
	console.log(webClientSocketKey)
});
httpServer.listen(PORT, () => console.info(`SERVER: running at port ${PORT}`));

export { httpServer };

```

test/test.test.ts
```
import { Server } from "node:http";
import { after, before, describe, it } from "node:test";
import { PORT } from "../src/config/constants.ts";


describe("Test Server", async () => {
	let httpServer: Server = {} as Server
	before(async () => {
		httpServer = (await import("../src/server.ts")).httpServer;
		await new Promise((resolve) => httpServer.once("listening", resolve));
	});
	after((_, done) => httpServer.close(done));

	it("Open conection with server", (_, done) => {
		const client = new WebSocket(`ws://localhost:${PORT}`)
		// client.onopen = (event) => console.info(`CLIENT: WebSocket is connected!`, event);
		// client.onclose = (event) => {
		// 	console.log(`CLIENT: disconnected!`, event);
		// };
		// client.onmessage = (event) => {
		// 	console.log(`CLIENT: I got a message!`, event.data);
		// };
		// client.onerror = (error) => {
		// 	console.error(`CLIENT: Web Socket error! msg:`, error);
		// 	client.close();
		// };
	});
});
```
.vscode/launch.json
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Run Test Debugger",
			"request": "launch",
			"runtimeExecutable": "npm",
			"runtimeArgs": ["run", "test:debug"],
			"skipFiles": ["<node_internals>/**"],
			"type": "node",
			"console": "integratedTerminal",
		}
	],
	"compounds": []
}
```

src/index.html
```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Web Scket Client</title>
</head>

<body>
  <output id="messages"></output>
  <div>
    <a href="javascript:webSocketInit()">Run WebSocket</a>
  </div>
  <script type="text/javascript">
    function webSocketInit() {
      if ("WebSocket" in window) {
        alert("WebSocket is supported by your Browser!");
        const messages = document.getElementById("messages")
        const socket = new WebSocket(`ws://localhost:3334`)
        socket.onopen = (event) => console.info(`CLIENT: WebSocket is connected!`)
        socket.onmessage = (msg) => console.log(`CLIENT: I got a message!`, msg)
        socket.onerror = (error) => console.error(`CLIENT: Web Socket error`, error)
        socket.onclose = (event) => console.info(`CLIENT: Disconnected from WebScoket server.`)
      } else {
        // The browser doesn't support WebSocket
        alert("WebSocket NOT supported by your Browser!");
      }
    }
  </script>
</body>

</html>
```
