### ISSUE TITLE
Files in `outDir` don't use their respective `tsconfig.json` for go to definition when outside of included files

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#57064]
### 🔎 Search Terms

outdir declarations dts tsconfig.json moduleresolution bundler node16

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

N/A

### 💻 Code

```ts
/// <reference path="../fourslash.ts" />

// @Filename: /tsconfig.json
////{
////    "compilerOptions": {
////        "strict": true,
////        "moduleResolution": "node16",
////        "module": "node16",
////        "rootDir": "./src",
////        "outDir": "./dist",
////        "declaration": true
////    },
////    "include": ["src/*"]
////}

// @Filename: /package.json
////{
////    "name": "a",
////    "exports": {
////        ".": "./dist/index.js",
////        "./thing": "./dist/thing.js"
////    }
////}

// @Filename: /src/index.ts
////export { thing } from /*src*/"a/thing";

// @Filename: /src/thing.ts
////export const thing = "thing";

// @Filename: /dist/index.d.ts
////export { thing } from /*dist*/"a/thing";

// @Filename: /dist/thing.d.ts
////export declare const thing = "thing";

verify.baselineGoToDefinition("src", "dist");
```

### 🙁 Actual behavior

Definition for the marker `/*src*/` gets resolved correctly but the one for `/*dist*/` doesn't.The definition

### 🙂 Expected behavior

Both markers should work here. Since this repro doesn't have any source/declaration maps, I'd probably expect the `/*dist*/` marker to get resolved with `/dist/thing.d.ts`

### Additional information about the issue

I also wonder what should happen for files within `outDir` that don't map directly to source files (a common thing for libraries that don't use `tsc` for emit).

cc @andrewbranch 

It's also worth noting that the test runner crashes when no definition is found:
```
  1) fourslash-server tests
       tests/cases/fourslash/server/definitionSpan.ts
         fourslash-server test definitionSpan.ts runs correctly:
     TypeError: Cannot read properties of undefined (reading 'start')
      at SessionClient.decodeSpan (src/harness/client.ts:656:18)
      at SessionClient.getDefinitionAndBoundSpan (src/harness/client.ts:406:28)
```

**Comment by andrewbranch** [comment]
Is this a _go to definition_ problem or a _module resolution_ problem? If it’s a module resolution problem, it will show up in a normal compiler test.

**Comment by Andarist** [comment]
It's a go to definition problem - sorry if this wasn't completely clear. I only cc'ed you here since it intersects with module resolution modes.

**Comment by RyanCavanaugh** [comment]
Closing language service bugs related to the 6.0 implementation. For more information, see #62827
