### ISSUE TITLE
compiler crashes inside `checkTypeRelatedTo` after attempting to elaborate errors

### ISSUE THREAD

**Issue by vladima** [Microsoft/TypeScript#5712]
```ts
interface Ref<T> {
    prop: T;
}
interface Container<T> {
    m1: Container<Ref<T>>;
    m2: T;
}
declare function foo(x: () => Container<Ref<number>>): void;
let a: () => Container<Ref<string>>;
foo(a);
```
```
TypeError: Cannot read property 'code' of undefined
    at Object.createDiagnosticForNodeFromMessageChain (C:\Sources\TypeScript\built\local\tsc.js:4438:31)
    at checkTypeRelatedTo (C:\Sources\TypeScript\built\local\tsc.js:18365:36)
    at checkApplicableSignature (C:\Sources\TypeScript\built\local\tsc.js:21845:26)
    at resolveCall (C:\Sources\TypeScript\built\local\tsc.js:22226:17)
    at resolveCallExpression (C:\Sources\TypeScript\built\local\tsc.js:22386:20)
    at getResolvedSignature (C:\Sources\TypeScript\built\local\tsc.js:22516:47)
    at checkCallExpression (C:\Sources\TypeScript\built\local\tsc.js:22541:29)
    at checkExpressionWorker (C:\Sources\TypeScript\built\local\tsc.js:23602:28)
    at checkExpression (C:\Sources\TypeScript\built\local\tsc.js:23547:42)
    at checkExpressionStatement (C:\Sources\TypeScript\built\local\tsc.js:25118:13)
```

**Comment by sandersn** [comment]
The problem is that the initial run of `isRelatedTo` correctly finds the top-level error `'() => Container<string[]>' is not assignable to '() => Container<number[]>'`, but when `isRelatedTo` is re-run with `reportErrors: true`, it fails to find an error, setting `errorInfo` to `undefined`, which causes `createDiagnosticMessageChains` to crash.

So far I've found that `isRelatedTo` correctly identifies the type parameters `number[]` and `string[]` as not assignable, but then `objectTypeRelatedTo` says that `Container` either is or might be assignable to `Container`, which then sets `errorInfo` to undefined.

The error doesn't manifest with `() => Container<number>` vs `<string>`, so I need to compare its behaviour in `objectTypeRelatedTo`.
