### ISSUE TITLE
ts.ImportDeclaration.moduleSpecifier can`t run  getText(), because node don`t have parent.

### ISSUE THREAD

**Issue by ouyangxuxiang** [microsoft/TypeScript#57169]
### 🔎 Search Terms

ImportDeclaration.moduleSpecifier.getText()

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```ts
// Your code here
function main (){
    const sourceFile = ts.createSourceFile("test.ts",
    `
    import ts from "typescript"
    `
    ,ts.ScriptTarget.ES2022)
    
    const imports: { packageName: string, importedObjects: string[] }[] = [];

    function visit(node: ts.Node) {
        if (ts.isImportDeclaration(node)) {
            // console.log((node.moduleSpecifier as any).text )
        const packageName = node.moduleSpecifier.getText().slice(1, -1); // Remove quotes from package name
        const importedObjects: string[] = [];

        if (node.importClause && node.importClause.namedBindings && ts.isNamedImports(node.importClause.namedBindings)) {
            node.importClause.namedBindings.elements.forEach((element) => {
            importedObjects.push(element.name.getText());
            });
        }

        imports.push({ packageName, importedObjects });
        }

        ts.forEachChild(node, visit);
    }
    visit(sourceFile)
}
main();


```

### 🙁 Actual behavior

```
TypeError: Cannot read properties of undefined (reading 'text')
    at NodeObject.getText (D:\project\2\ts\node_modules\typescript\lib\typescript.js:134343:29)
    at visit (D:\project\2\ts\dist\SdkScript\index.js:56:58)
    at visitNodes (D:\project\2\ts\node_modules\typescript\lib\typescript.js:27591:24)
    at forEachChildInSourceFile (D:\project\2\ts\node_modules\typescript\lib\typescript.js:28211:18)
    at Object.forEachChild (D:\project\2\ts\node_modules\typescript\lib\typescript.js:27676:37)
    at visit (D:\project\2\ts\dist\SdkScript\index.js:65:34)
    at D:\project\2\ts\dist\SdkScript\index.js:67:9
    at Generator.next (<anonymous>)
    at D:\project\2\ts\dist\SdkScript\index.js:11:71
    at new Promise (<anonymous>)
    
```

```ts

        function getSourceFileOfNode(node) {
          while (node && node.kind !== 308 /* SourceFile */) {
          
          //error
          
            node = node.parent;
          }
          return node;
        }
        
         getSourceFile() {
          return getSourceFileOfNode(this);
        }
        
         getText(sourceFile) {
          this.assertHasRealPosition();
          if (!sourceFile) {
          // error
            sourceFile = this.getSourceFile();
          }
          return sourceFile.text.substring(this.getStart(sourceFile), this.getEnd());
        }


```

### 🙂 Expected behavior

return 'typescript'

**Comment by Andarist** [comment]
You can just call `element.name.getText(sourceFile);` to work around your problem. TS doesn't always set up `.parent` references on the parsed nodes - it usually happens in the binder.

**Comment by jakebailey** [comment]
Yeah, you either need to pass the flag to the parser to set parents, or pass in the source file. Both of these are performance related things (many transformers don't need parents, and walking up the parents every single time is slow).
