### ISSUE TITLE
"Output generation failed" when transpiling "test.d.abc.ts"

### ISSUE THREAD

**Issue by oldrich-s** [microsoft/TypeScript#58142]
### 🔎 Search Terms

"Output generation failed", "transpileModule"

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 5.0.0-dev.20230109 and 5.0.0-dev.20230110
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about file names

### 💻 Code

```ts
const TS = require('typescript')

const res = TS.transpileModule('export const x = 6;', {
    fileName: 'test.d.tsp.ts',
});

console.log(res)
```

### 🙁 Actual behavior

The Typescript compiler crashes. The compiler should allow files that contain .d. in their name.

### 🙂 Expected behavior

The compilation succeeds

### Additional information about the issue

```
c:\Users\osv\Downloads\test>npm i typescript@5.0.0-dev.20230110

changed 1 package, and audited 2 packages in 5s

found 0 vulnerabilities

c:\Users\osv\Downloads\test>node main.js
c:\Users\osv\Downloads\test\node_modules\typescript\lib\typescript.js:1772
          throw e;
          ^

Error: Debug Failure. Output generation failed
    at Object.transpileModule (c:\Users\osv\Downloads\test\node_modules\typescript\lib\typescript.js:127318:20)
    at Object.<anonymous> (c:\Users\osv\Downloads\test\main.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.11.1

c:\Users\osv\Downloads\test>npm i typescript@5.0.0-dev.20230109

changed 1 package, and audited 2 packages in 745ms

found 0 vulnerabilities

c:\Users\osv\Downloads\test>node main.js
{
  outputText: '"use strict";\r\n' +
    'Object.defineProperty(exports, "__esModule", { value: true });\r\n' +
    'exports.x = void 0;\r\n' +
    'exports.x = 6;\r\n',
  diagnostics: [],
  sourceMapText: undefined
}
```

**Comment by MartinJohns** [comment]
I can't find where it was written right now, but filenames matching `*.d.*ts` are considered declaration files. That's probably causing issues here.

**Comment by oldrich-s** [comment]
https://www.typescriptlang.org/docs/handbook/2/type-declarations.html#dts-files

should not it be *.d.ts ?

**Comment by IllusionMH** [comment]
Related #53319 and specifically https://github.com/microsoft/TypeScript/issues/53319#issuecomment-1474174018

**Comment by weswigham** [comment]
@andrewbranch Maybe we should take this as a request to make the output a bit more informative than `Debug Failure. Output generation failed`? Surely we could issue a more specific and helpful diagnostic (or, like, actually issue a diagnostic at all instead of a `Debug Failure`)?
