### ISSUE TITLE
tsc crash with "TypeError: Cannot read properties of undefined (reading 'flags')"

### ISSUE THREAD

**Issue by mirek** [microsoft/TypeScript#58371]
### 🔎 Search Terms

none

### 🕗 Version & Regression Information

- This is a crash

### 💻 Code

```ts
// Too large / internal
```

### 🙁 Actual behavior

tsc crashes

### 🙂 Expected behavior

tsc should not crash

### Additional information about the issue

```
 /home/runner/work/my-project/node_modules/.pnpm/typescript@5.4.3/node_modules/typescript/lib/tsc.js:118617
      throw e;
      ^

TypeError: Cannot read properties of undefined (reading 'flags')
    at getCheckFlags (/home/runner/work/my-project/node_modules/.pnpm/typescript@5.4.3/node_modules/typescript/lib/tsc.js:15928:17)
    at getTypeOfSymbol (/home/runner/work/my-project/node_modules/.pnpm/typescript@5.4.3/node_modules/typescript/lib/tsc.js:53259:24)
    at getParameterCount (/home/runner/work/my-project/node_modules/.pnpm/typescript@5.4.3/node_modules/typescript/lib/tsc.js:73669:24)
    at combineUnionParameters (/home/runner/work/my-project/node_modules/.pnpm/typescript@5.4.3/node_modules/typescript/lib/tsc.js:54395:23)
    at combineSignaturesOfUnionMembers (/home/runner/work/my-project/node_modules/.pnpm/typescript@5.4.3/node_modules/typescript/lib/tsc.js:54443:20)
    at /home/runner/work/my-project/node_modules/.pnpm/typescript@5.4.3/node_modules/typescript/lib/tsc.js:54359:204
    at map (/home/runner/work/my-project/node_modules/.pnpm/typescript@5.4.3/node_modules/typescript/lib/tsc.js:204:19)
    at getUnionSignatures (/home/runner/work/my-project/node_modules/.pnpm/typescript@5.4.3/node_modules/typescript/lib/tsc.js:54359:182)
    at resolveUnionTypeMembers (/home/runner/work/my-project/node_modules/.pnpm/typescript@5.4.3/node_modules/typescript/lib/tsc.js:54482:28)
    at resolveStructuredTypeMembers (/home/runner/work/my-project/node_modules/.pnpm/typescript@5.4.3/node_modules/typescript/lib/tsc.js:54946:9)

Node.js v20.9.0
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Andarist** [comment]
It's close to impossible to fix an issue like this without a repro case. https://antfu.me/posts/why-reproductions-are-required

**Comment by RyanCavanaugh** [comment]
This should be a pretty easy one to isolate based on seeing which nodes/types/symbols are in the preceding stack frames.

**Comment by mirek** [comment]
Is there a way to dump it easily? Still going through picking changes from refactor pull request that introduced it (it's quarter of a million LoC project).

**Comment by Andarist** [comment]
I'd setup a breakpoint there, like this:
```diff
 function getCheckFlags(symbol) {
+    if (!symbol) { debugger; }
     return symbol.flags & 33554432 ? symbol.links.checkFlags : 0;
 }
```

And when u get inevitably paused there you could look up the call stack, look through objects used there etc and try to narrow it down based on that information.

**Comment by Andarist** [comment]
Thanks! This can be slimmed down further to:
```ts
type T1 = "A" | "B";

type T2 = {
  C: [string];
  D: [number];
};

declare const map: {
  [K in T1 | keyof T2]: (...args: K extends keyof T2 ? T2[K] : []) => unknown;
};

for (const [key, fn] of Object.entries(map)) {
  fn(...args);
}
```

**Comment by Andarist** [comment]
@mirek could you check if [this build](https://github.com/microsoft/TypeScript/pull/58440#issuecomment-2094877890) fixes your issue?

**Comment by mirek** [comment]
@Andarist yes, this build fixes issue on my side.

There is no crash.

I can see some type errors, some look completely unrelated, some look closer to the changes introduced in the PR that was triggering the crash.

I'll assume those are irrelevant unless somebody says otherwise then I can go through them.

**Comment by Andarist** [comment]
@mirek you can check [this new build](https://github.com/microsoft/TypeScript/pull/58440#issuecomment-2097036385)

**Comment by mirek** [comment]
@Andarist looks good.

**Comment by pdhoopr** [comment]
Hi @Andarist and @RyanCavanaugh! Apologies for the tags on a months-old thread, but my team is running into this same issue on our project. We use Vue, so we're running `tsc` indirectly via `vue-tsc`. I've also opened an issue with them to see if they have any ideas: https://github.com/vuejs/language-tools/issues/4578.

I can confirm that the build above fixes it for us, so I was curious if there were any updates on this? We're totally blocked from upgrading `vue-tsc` and therefore `typescript` for now. Not a huge deal for us, but just thought I'd check in.

Thank you!!
