### ISSUE TITLE
Error: Debug Failure when importing `AssertionError` from `node:assert/strict`

### ISSUE THREAD

**Issue by rauschma** [microsoft/TypeScript#58534]
### 🔎 Search Terms

Error: Debug Failure

### 🕗 Version & Regression Information

Happened when using tsc v5.4.5 with `@types/node`. Wasn’t an issue before (older tsc and older `@types/node` v20.12.12).

### ⏯ Playground Link

https://github.com/rauschma/tsc-debug-failure

### 💻 Code

```ts
import { AssertionError } from 'node:assert/strict';
```

Some of my compilerOptions in tsconfig:

```json
"module": "NodeNext",
"moduleResolution": "NodeNext",
"isolatedModules": true,
"verbatimModuleSyntax": true,
"resolveJsonModule": true,
```

### 🙁 Actual behavior

```
Error: Debug Failure.
    at getTypeOfVariableOrParameterOrPropertyWorker (/usr/local/lib/node_modules/typescript/lib/tsc.js:53005:11)
    at getTypeOfVariableOrParameterOrProperty (/usr/local/lib/node_modules/typescript/lib/tsc.js:52974:20)
    at getTypeOfSymbol (/usr/local/lib/node_modules/typescript/lib/tsc.js:53306:14)
    at getTypeOfAlias (/usr/local/lib/node_modules/typescript/lib/tsc.js:53226:358)
    at getTypeOfSymbol (/usr/local/lib/node_modules/typescript/lib/tsc.js:53318:14)
    at getNarrowedTypeOfSymbol (/usr/local/lib/node_modules/typescript/lib/tsc.js:67681:18)
    at checkIdentifier (/usr/local/lib/node_modules/typescript/lib/tsc.js:67808:16)
    at checkExpressionWorker (/usr/local/lib/node_modules/typescript/lib/tsc.js:76261:16)
    at checkExpression (/usr/local/lib/node_modules/typescript/lib/tsc.js:76216:32)
    at checkNonNullExpression (/usr/local/lib/node_modules/typescript/lib/tsc.js:70497:29)
```

### 🙂 Expected behavior

No exception (normal operation)

### Additional information about the issue

Possibly helpful:

* I initially couldn’t tell what the problem was (in my rather large repo) but Nathan Shively-Sanders suggested I change line `tsc.js:53005` as follows. That told me that this problem was about `AssertionError`.

```diff
- Debug.assertIsDefined(symbol.valueDeclaration);
+ Debug.assertIsDefined(symbol.valueDeclaration, Debug.formatSymbol(symbol));
```

**Comment by Andarist** [comment]
It repros in the playground too: [TS playground](https://www.typescriptlang.org/play/?ts=5.5.0-dev.20240514#code/JYWwDg9gTgLgBAbzgQQM6oKa2BAdgUSimjgF84AzYkOAclwgBMMAuAQ3SxgHpUYpgAYxi0A3HG7c4MAJ5gMqFnABMABgB0ARmVblAKAMGgA). To repro you need to hover over `AssertionError`. An interesting fact is that the first hover after a source edit triggers the error but the second one doesn't and it renders a good tooltip content.

**Comment by Andarist** [comment]
Failing test case:
```ts
// @strict: true
// @moduleResolution: node
// @noEmit: true

// @filename: node_modules/@types/node/assert/strict.d.ts
declare module "node:assert/strict" {
  import { strict } from "node:assert";
  export = strict;
}

// @filename: node_modules/@types/node/assert.d.ts
declare module "assert" {
  function assert(value: unknown, message?: string | Error): asserts value;
  namespace assert {
    class AssertionError extends Error {
      actual: unknown;
      expected: unknown;
      code: "ERR_ASSERTION";
      constructor(options?: {
        message?: string | undefined;
        actual?: unknown | undefined;
        expected?: unknown | undefined;
      });
    }

    namespace strict {
      type AssertionError = assert.AssertionError;
    }

    const strict: Omit<typeof assert, "strict">;
  }
  export = assert;
}
declare module "node:assert" {
  import assert = require("assert");
  export = assert;
}

// @filename: index.ts
import { AssertionError } from 'node:assert/strict';

throw new AssertionError({
  message: 'Hello',
  actual: 3,
  expected: 3,
});

```

**Comment by jakebailey** [comment]
The above test crashes even in TS 4.5 (and back even in 4.0 though with a slightly different error). So this most definitely is not a recent regression at all.

**Comment by JulianCataldo** [comment]
Hello there,

Here is my temporary fix, it does seem to work at first glance.

Before:

```ts
import assert, { AssertionError } from 'node:assert/strict';
```

```ts
import { AssertionError } from 'node:assert';
import assert from 'node:assert/strict';
```

It looks like `assert.fail` (from `/strict`) is emitting the same `AssertionError` as the one from the regular `assert`.

After that, no problem to build with `tsc`, not `Debug Failure` anymore.

Only minor issue I have now is that ESLint will complaint:

```
'node:assert' import is restricted from being used. Use node:assert/strict instead.eslint[no-restricted-imports](https://eslint.org/docs/latest/rules/no-restricted-imports)
```

Cheers!

**Comment by tonivj5** [comment]
I can reproduce it with latest ts `5.5.3`

- package.json
```json
{
  "name": "ts-issue",
  "scripts": {
    "typecheck": "tsc --noEmit -p tsconfig.json"
  },
  "license": "ISC",
  "devDependencies": {
    "@types/node": "20.14.9",
    "typescript": "5.5.3",
    "tslib": "2.6.3"
  }
}
```
- `tsconfig.json`
```json
{
  "compileOnSave": false,
  "include": ["./src/issue.ts"],
  "compilerOptions": {
    "baseUrl": ".",
    "rootDir": ".",

    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "importHelpers": true,

    "target": "es2021",
    "module": "CommonJS",
    "moduleResolution": "Node",
    "incremental": true,
    "sourceMap": true,
    "declaration": false,
    "esModuleInterop": true,
    "useDefineForClassFields": false,
    "allowJs": true,
    "resolveJsonModule": true,
    "moduleDetection": "force",
    "isolatedModules": false,
    "lib": ["es2021", "es2022.Error", "ESNext.Disposable"],

    "strict": true,
    "noUncheckedIndexedAccess": false,
    "noImplicitOverride": false,

    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "pretty": true,

    "paths": {}
  }
}
```
- `issue.ts`
```ts
import { AssertionError } from "node:assert/strict";

throw new AssertionError({
  message: "unreachable assertion",
  operator: "unreachable",
});
```

- Output:
```
..../node_modules/typescript/lib/tsc.js:120127
      throw e;
      ^

Error: Debug Failure.
    at getTypeOfVariableOrParameterOrPropertyWorker (..../node_modules/typescript/lib/tsc.js:54702:11)
    at getTypeOfVariableOrParameterOrProperty (..../node_modules/typescript/lib/tsc.js:54674:20)
    at getTypeOfSymbol (..../node_modules/typescript/lib/tsc.js:55003:14)
    at getTypeOfAlias (..../node_modules/typescript/lib/tsc.js:54923:373)
    at getTypeOfSymbol (..../node_modules/typescript/lib/tsc.js:55015:14)
    at getNarrowedTypeOfSymbol (..../node_modules/typescript/lib/tsc.js:69744:18)
    at checkIdentifier (..../node_modules/typescript/lib/tsc.js:69883:16)
    at checkExpressionWorker (..../node_modules/typescript/lib/tsc.js:78402:16)
    at checkExpression (..../node_modules/typescript/lib/tsc.js:78356:32)
    at checkNonNullExpression (..../node_modules/typescript/lib/tsc.js:72591:29)

Node.js v20.11.0
```

**Comment by bmenant** [comment]
@JulianCataldo another workaround is to use `assert.AssertionError` instead:

```ts
import assert from 'node:assert/strict';

const { AssertionError } = assert;
new AssertionError();

// Or...
new assert.AssertionError();
```

I run into this issue while porting a project to ESM and Jest tests to native node tests. Tests were passing when running them with Webstorm (using [tsx](https://tsx.is/)), and no type error reported on the IDE. However, running tests with [borp](https://github.com/mcollina/borp) failed with a tsc Debug Failure error.

**Comment by LukeAbby** [comment]
Here's a more minimal reproduction:
```ts
// @filename: index.ts
import { AssertionError } from "./assert";
new AssertionError("assert");

// @filename: assert.d.ts
declare namespace assert {
  class AssertionError extends Error {}

  const strict: Omit<typeof assert, never>;
}

export = assert.strict;
```

You can do it in [one file](https://www.typescriptlang.org/play/?jsx=0&module=0#code/PTAECEFMGMEMFcDOlQBcAWKAOAbWBPAcwCcB7eAOwBNQBLRUUilAM1pxQ3roFstTiqBizI86QyDhYA6UAEkKoWKGKRC8PMVBYyJWGPzlQAd3I4a6WADdOp0Gw6JpAKFp8BqUAG9QAQUTIgrRMAKLEZFoAvvaioABE0sC0FFjwqHEA3M7Mxn4BkEGh4QIAFHGw+YJxAJRZzlQwmigU+pCIWLDQKBWBnl7OoKDQeAF5vcEUYRGgkAAeqJDUDFMC3pHOA0NMiJ47xLTQqABcoADyPLSoADyo+FiQpCxKlagANKDMNsQAfFnrznN+IJQABeZ69aR7A6oDJAA) if you want.

The compiler crash _is_ still around but now that my fix to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71889 is in the original snippet from the real `assert` package will no longer crash.

**Comment by RyanCavanaugh** [comment]
This is fixed in current implementations. Hovering `AssertionError` in the mapped `export = assert.strict` form crashes the TypeScript 5.4.5 language service with `Debug Failure`, while TypeScript 6.0.3 returns quick info and the current native language service completes the request without a crash.

The linked implementation proposal in https://github.com/microsoft/TypeScript/pull/63141 is closed unmerged, so it is not being attributed as the fix.
