### ISSUE TITLE
Maximum call stack size exceeded — forEachChildInBinaryExpression

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#59113]
### Acknowledgement

- [x] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

TS 5.6.0-dev.20240701

Seeing endless crashes when I opened my sandbox workspace. Log file: [tsserver.log](https://github.com/user-attachments/files/16072409/tsserver.log)

```
   Maximum call stack size exceeded

    RangeError: Maximum call stack size exceeded
        at bind (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.6.20240701/node_modules/typescript/lib/typescript.js:47520:16)
        at visitNode2 (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.6.20240701/node_modules/typescript/lib/typescript.js:31617:18)
        at forEachChildInBinaryExpression (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.6.20240701/node_modules/typescript/lib/typescript.js:31815:12)
        at forEachChild (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.6.20240701/node_modules/typescript/lib/typescript.js:32138:35)
        at bindEachChild (/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.6.20240701/node_modules/typescript/lib/typescript.js:46154:5)
        at bindChildren (/Users/matb/.vscode-insiders/extensions
```

Unsure exactly how I got into this state

**Comment by RyanCavanaugh** [comment]
We'll definitely need a repro
