### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'flags') at needsNameFromDeclaration at getNameForExportedSymbol

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#59159]
### 🔎 Search Terms

import type node class member completion parameter method

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

N/A

### 💻 Code

```ts
/// <reference path="fourslash.ts" />

// @module: nodenext

// @Filename: /generation.d.ts
//// export type GenerationConfigType = { max_length?: number };

// @FileName: /index.d.ts
//// export declare class PreTrainedModel {
////   _get_generation_config(
////     param: import("./generation.js").GenerationConfigType,
////   ): import("./generation.js").GenerationConfigType;
//// }
////
//// export declare class BlenderbotSmallPreTrainedModel extends PreTrainedModel {
////   /*1*/
//// }

verify.completions({
  marker: "1",
  includes: [
    {
      name: "_get_generation_config",
      insertText: `_get_generation_config(param: import("./generation.js").GenerationConfigType): import("./generation.js").GenerationConfigType;`,
      filterText: "_get_generation_config",
    },
  ],
  preferences: {
    includeCompletionsWithClassMemberSnippets: true,
    includeCompletionsWithInsertText: true,
  },
  isNewIdentifierLocation: true,
});
```

### 🙁 Actual behavior

crash

### 🙂 Expected behavior

no crash

### Additional information about the issue

repro based on https://github.com/microsoft/TypeScript/issues/59085#issuecomment-2198774440:
```
Req #6451 - completionInfo
    at needsNameFromDeclaration (/typescript-5.6.0-dev.20240630/lib/typescript.js:138216:19)
    at getNameForExportedSymbol (/typescript-5.6.0-dev.20240630/lib/typescript.js:138210:7)
    at visit (/typescript-5.6.0-dev.20240630/lib/typescript.js:161488:20)
    at visitNode (/typescript-5.6.0-dev.20240630/lib/typescript.js:92400:19)
    at tryGetAutoImportableReferenceFromTypeNode (/typescript-5.6.0-dev.20240630/lib/typescript.js:161481:20)
    at /typescript-5.6.0-dev.20240630/lib/typescript.js:161118:37
    at sameMap (/typescript-5.6.0-dev.20240630/lib/typescript.js:2470:22)
    at createSignatureDeclarationFromSignature (/typescript-5.6.0-dev.20240630/lib/typescript.js:161115:27)
    at outputMethod (/typescript-5.6.0-dev.20240630/lib/typescript.js:161017:20)
    at Object.addNewNodeForMemberSymbol (/typescript-5.6.0-dev.20240630/lib/typescript.js:160999:9)
    at getEntryForMemberCompletion (/typescript-5.6.0-dev.20240630/lib/typescript.js:163718:22)
    at createCompletionEntry (/typescript-5.6.0-dev.20240630/lib/typescript.js:163566:35)
    at getCompletionEntriesFromSymbols (/typescript-5.6.0-dev.20240630/lib/typescript.js:164192:19)
    at completionInfoFromData (/typescript-5.6.0-dev.20240630/lib/typescript.js:163218:23)
    at Object.getCompletionsAtPosition (/typescript-5.6.0-dev.20240630/lib/typescript.js:162764:24)
    at Object.getCompletionsAtPosition2 [as getCompletionsAtPosition] (/typescript-5.6.0-dev.20240630/lib/typescript.js:149346:35)
    at IOSession.getCompletions (/typescript-5.6.0-dev.20240630/lib/typescript.js:190799:54)
    at completionInfo (/typescript-5.6.0-dev.20240630/lib/typescript.js:189137:43)
    at /typescript-5.6.0-dev.20240630/lib/typescript.js:191603:15
    at IOSession.executeWithRequestId (/typescript-5.6.0-dev.20240630/lib/typescript.js:191592:14)
    at IOSession.executeCommand (/typescript-5.6.0-dev.20240630/lib/typescript.js:191601:29)
    at IOSession.onMessage (/typescript-5.6.0-dev.20240630/lib/typescript.js:191649:68)
    at Interface.<anonymous> (/typescript-5.6.0-dev.20240630/lib/tsserver.js:501:14)
```

**Comment by andrewbranch** [comment]
This is a 5.5 regression
