### ISSUE TITLE
Circular declarations cause infinite loops in getExportInfos since v5.5

### ISSUE THREAD

**Issue by simon-paris** [microsoft/TypeScript#59201]
### 🔎 Search Terms

infinite loop, circular, infinite loop, getExportInfos, invalid array length

### 🕗 Version & Regression Information

- This is an infinite loop in tsserver, eventually leading to a crash due to creating an infinitely sized array.
- This changed between versions 5.5.0-dev.20240508 and 5.5.0-dev.20240509
- Probably this pr: #58460 

### ⏯ Playground Link

Does not reproduce on playground

### 💻 Code

In an empty folder, place this code in `types.d.ts`
```ts
declare module "mymod" {
  import mymod from "mymod";
  export default mymod;
}
```

In another file `index.ts`, trigger an autocomplete or getCodeFixes. Typing two characters into an empty file will usually work. It will hang.

### 🙁 Actual behavior

The LSP server go into an infinite loop and hangs. After about 20 seconds it'll throw because an array gets too big.

The server log contains:

```
    RangeError: Invalid array length
        at Array.push (<anonymous>)
        at append (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:2822:6)
        at forEachNameOfDefaultExport (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:138888:13)
        at /Users/myusername/mweb/node_modules/typescript/lib/typescript.js:155493:115
        at /Users/myusername/mweb/node_modules/typescript/lib/typescript.js:138720:119
        at forEachExternalModule (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:138763:7)
        at forEachExternalModuleToImportFrom (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:138720:3)
        at getExportInfos (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:155488:3)
        at /Users/myusername/mweb/node_modules/typescript/lib/typescript.js:155424:24
        at flatMap (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:2502:17)
        at getFixesInfoForNonUMDImport (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:155418:10)
        at getFixInfos (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:155254:12)
        at Object.getCodeActions (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:154389:18)
        at /Users/myusername/mweb/node_modules/typescript/lib/typescript.js:151448:46
        at flatMap (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:2502:17)
        at Object.getFixes (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:151448:10)
        at /Users/myusername/mweb/node_modules/typescript/lib/typescript.js:149730:33
        at flatMap (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:2502:17)
        at Object.getCodeFixesAtPosition (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:149728:12)
        at IpcIOSession.getCodeFixes (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:191339:50)
        at getCodeFixes (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:189374:43)
        at /Users/myusername/mweb/node_modules/typescript/lib/typescript.js:191661:15
        at IpcIOSession.executeWithRequestId (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:191650:14)
        at IpcIOSession.executeCommand (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:191659:29)
        at IpcIOSession.onMessage (/Users/myusername/mweb/node_modules/typescript/lib/typescript.js:191707:68)
        at process.<anonymous> (/Users/myusername/mweb/node_modules/typescript/lib/tsserver.js:525:14)
        at process.emit (node:events:514:28)
        at emit (node:internal/child_process:951:14)
        at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

<img width="1800" alt="Screenshot 2024-07-09 at 10 06 41 PM" src="https://github.com/microsoft/TypeScript/assets/4035267/5f7808ad-860c-46b6-8e55-fe4e68093c12">

### 🙂 Expected behavior

Nothing should happen.

**Comment by andrewbranch** [comment]
> ```ts
> declare module "mymod" {
>   import mymod from "mymod";
>   export default mymod;
> }
> ```

What is this supposed to mean?

**Comment by simon-paris** [comment]
> What is this supposed to mean?

It's nonsense from a dev who was new to typescript, a long time ago. I'm just reporting it anyways because its a crash.

**Comment by andrewbranch** [comment]
Makes sense, I was just wondering if this was a simplification of something found in a library.
