### ISSUE TITLE
TS error moving a function to another file

### ISSUE THREAD

**Issue by connor4312** [microsoft/TypeScript#59284]
1. Try to move [this function](https://github.com/microsoft/vscode-js-debug/blob/1d104b5184736677ab5cc280c70bbd227403850c/src/targets/node/subprocessProgramLauncher.ts) to [this file](https://github.com/microsoft/vscode-js-debug/blob/1d104b5184736677ab5cc280c70bbd227403850c/src/common/processUtils.ts)
2. Get a TS error notification containing

```
<semantic> TypeScript Server Error (5.5.2) Debug Failure. Error: Debug Failure. at Object.addImportFromExportedSymbol (c:\Users\conno\Github\vscode-js-debug\node_modules\typescript\lib\typescript.js:154158:32) at c:\Users\conno\Github\vscode-js-debug\node_modules\typescript\lib\typescript.js:144203:19 at Map.forEach (<anonymous>) at addTargetFileImports (c:\Users\conno\Github\vscode-js-debug\node_modules\typescript\lib\typescript.js:144197:17) at getNewStatementsAndRemoveFromOldFile (c:\Users\conno\Github\vscode-js-debug\node_modules\typescript\lib\typescript.js:143427:3) at doChange3 (c:\Users\conno\Github\vscode-js-debug\node_modules\typescript\lib\typescript.js:143411:3) at c:\Users\conno\Github\vscode-js-debug\node_modules\typescript\lib\typescript.js:143396:79 at _ChangeTracker.with (c:\Users\conno\Github\vscode-js-debug\node_modules\typescript\lib\typescript.js:174213:5) at Object.getRefactorEditsToMoveToFile [as getEditsForAction] (c:\Users\co...
```

TS Server Log https://gist.github.com/connor4312/080949221003eaed849afa685d48c0ae

**Comment by qaws5503** [comment]
Same problem here

**Comment by sakamossan** [comment]
Here's a workaround that has worked for me.

- https://github.com/microsoft/TypeScript/issues/58897#issuecomment-2220808697

**Comment by Mobius5150** [comment]
👋 @connor4312 I'm reproing as well. Can't share source but happy to share info as needed.

Typescript 5.5.4

```
2024-09-16 09:36:15.536 [error] [vscode.typescript-language-features] provider FAILED
2024-09-16 09:36:15.537 [error] Error: <semantic> TypeScript Server Error (5.5.4)
Debug Failure.
Error: Debug Failure.
    at Object.addImportFromExportedSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:154243:32)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144288:19
    at Map.forEach (<anonymous>)
    at addTargetFileImports (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144282:17)
    at getNewStatementsAndRemoveFromOldFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:143512:3)
    at doChange4 (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144488:3)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144477:77
    at _ChangeTracker.with (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:174306:5)
    at Object.getRefactorEditsToMoveToNewFile [as getEditsForAction] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144477:60)
    at Object.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:142603:31)
    at Proxy.getEditsForRefactor2 (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:149939:32)
    at IpcIOSession.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191087:49)
    at getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:189305:43)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191491:69
    at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191483:14)
    at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191491:29)
    at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191533:51)
    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:523:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Function.create (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:474083)
    at v.dispatchResponse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:468053)
    at v.dispatchMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:466851)
    at ChildProcess.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:466344)
    at ChildProcess.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by RohovDmytro** [comment]
Same issue with typescript@5.6.2

**Comment by mchlkucera** [comment]
Same issue with Typescript 5.5.4

```
2024-09-27 09:11:34.644 [error] [vscode.typescript-language-features] provider FAILED
2024-09-27 09:11:34.644 [error] Error: <semantic> TypeScript Server Error (5.5.4)
Debug Failure.
Error: Debug Failure.
    at Object.addImportFromExportedSymbol (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:154243:32)
    at /private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144288:19
    at Map.forEach (<anonymous>)
    at addTargetFileImports (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144282:17)
    at getNewStatementsAndRemoveFromOldFile (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:143512:3)
    at doChange4 (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144488:3)
    at /private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144477:77
    at _ChangeTracker.with (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:174306:5)
    at Object.getRefactorEditsToMoveToNewFile [as getEditsForAction] (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144477:60)
    at Object.getEditsForRefactor (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:142603:31)
    at Object.getEditsForRefactor2 [as getEditsForRefactor] (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:149939:32)
    at IpcIOSession.getEditsForRefactor (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191087:49)
    at getEditsForRefactor (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:189305:43)
    at /private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191491:69
    at IpcIOSession.executeWithRequestId (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191483:14)
    at IpcIOSession.executeCommand (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191491:29)
    at IpcIOSession.onMessage (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191533:51)
    at process.<anonymous> (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:523:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
	at n.create (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:474083)
	at v.dispatchResponse (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:468053)
	at v.dispatchMessage (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:466851)
	at ChildProcess.<anonymous> (/private/var/folders/2v/x9xxx2lj6ls49kh4vrlqhlfw0000gn/T/AppTranslocation/C9D6153C-57AA-4813-A336-FD8CADBF1B20/d/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:466344)
	at ChildProcess.emit (node:events:519:28)
	at emit (node:internal/child_process:951:14)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by thSoft** [comment]
Same issue with both TypeScript 5.7.3 and 5.8.2.

**Comment by iisaduan** [comment]
@thSoft please make a new issue with a repro so we can investigate your case
