### ISSUE TITLE
Web TS Server tries watching for files outside of project root

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#59413]
### Acknowledgement

- [x] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

From https://github.com/microsoft/vscode/issues/221299

On vscode.dev, enabling project wide intellisense with TS 5.5 can cause exceptions in the developer console. Both of these are related to trying to watch/read files that are outside of the project root. We block these as these reads are invalid on web and in some cases can actually cause major perf issues

I believe there are two separate exceptions:

1. Trying to watch for `@typescript/lib-*`:

```
Error: <syntax> TypeScript Server Error (5.5.2)
Could not read file outside of project root /vscode-vfs/github/mjbvz/node_modules/@typescript/lib-es5
Error: Could not read file outside of project root /vscode-vfs/github/mjbvz/node_modules/@typescript/lib-es5
    at PathMapper.toResource (tsserver.web.js:193032:19)
    at Object.realpath (tsserver.web.js:193494:26)
    at createDirectoryWatcherForPackageDir (tsserver.web.js:129937:40)
    at setDirectoryWatcher (tsserver.web.js:129981:7)
    at watchFailedLookupLocation (tsserver.web.js:129814:9)
    at watchFailedLookupLocationOfResolution (tsserver.web.js:129827:21)
    at watchFailedLookupLocationsOfExternalModuleResolutions (tsserver.web.js:129783:9)
    at Object.resolveLibrary2 [as resolveLibrary] (tsserver.web.js:129722:7)
    at InferredProject2.resolveLibrary (tsserver.web.js:182661:33)
    at pathForLibFileWorker (tsserver.web.js:126248:24)
	at TypeScriptServerError.create (extension.js:35385:16)
	at SingleTsServer.dispatchResponse (extension.js:34850:66)
	at SingleTsServer.dispatchMessage (extension.js:34781:30)
	at eval (extension.js:34753:18)
	at WorkerServerProcess._tsserver.onmessage (extension.js:45502:17)

```

In this case, my workspace is `/vscode-vfs/github/mjbvz/vscode-markdown-footnotes`. We should not try reading anything in a parent directory of this, such as `/vscode-vfs/github/mjbvz/node_modules`

I've caught the exception as a workaround as otherwise this actually ends up being a fatal error for VS Code

2. After fixing the above, I still see normal `watchdirectory` requests for watching `/vscode-vfs/github/mjbvz/node_modules` and `/vscode-vfs/github/mjbvz/node_modules/@types`

```
Error: Could not read file outside of project root /vscode-vfs/github/mjbvz/node_modules
    at PathMapper.toResource (tsserver.web.js:193032:19)
    at FileWatcherManager.watchDirectory (tsserver.web.js:192930:35)
    at watchDirectory (tsserver.web.js:123288:67)
    at tsserver.web.js:123356:92
    at Object.watchDirectory (tsserver.web.js:123306:283)
    at ConfiguredProject2.watchDirectoryOfFailedLookupLocation (tsserver.web.js:182679:45)
    at createDirectoryWatcher (tsserver.web.js:130070:27)
    at createOrAddRefToDirectoryWatchOfFailedLookups (tsserver.web.js:129990:76)
    at createDirPathToWatcher (tsserver.web.js:129974:116)
    at createDirectoryWatcherForPackageDir (tsserver.web.js:129968:18)
``` 

If possible, we should never try accessing any files outside of the project root on web. In the `updateOpen` calls, we pass in a `projectRootPath` to try to prevent this

**Comment by sheetalkamat** [comment]
Project root though associated with open file , projects are related to multiple open files hence cannot account for project root of open file( they also stay open after the file is closed ).. this can be handled easily by checking on the web tsserver’s watch methods to never cross those boundaries and I don’t think having option in tsserver is necessary
