### ISSUE TITLE
RangeError in Array destructuring assignment

### ISSUE THREAD

**Issue by Roise-yue** [microsoft/TypeScript#59806]
### 🔎 Search Terms

RangeError, destructuring assignment

### 🕗 Version & Regression Information

- This is the behavior in every version I tried ( including V5.6Beta)

### 💻 Code

Due to the large size of the code file, I have written the structure of the program below. The complete code file is here: https://github.com/Roise-yue/tscFuzz/blob/main/file.ts
```ts
const fundSuggestList = ["string1", "string2", "string3", ... ,"stringn"];
export default fundSuggestList ; 
const [var1, var2, var3 , ... ,varn] = fundSuggestList;  // Error Location

```

### 🙁 Actual behavior

```ts
RangeError: Maximum call stack size exceeded
    at visitEachChild (/TSCFuzzer/tscFuzz/node_modules/typescript/lib/tsc.js:87924:24)
    at visitTypeScript (/TSCFuzzer/tscFuzz/node_modules/typescript/lib/tsc.js:90971:16)
    at visitorWorker (/TSCFuzzer/tscFuzz/node_modules/typescript/lib/tsc.js:90712:14)
    at saveStateAndInvoke (/TSCFuzzer/tscFuzz/node_modules/typescript/lib/tsc.js:90677:21)
    at visitor (/TSCFuzzer/tscFuzz/node_modules/typescript/lib/tsc.js:90708:12)
    at visitNode (/TSCFuzzer/tscFuzz/node_modules/typescript/lib/tsc.js:87681:19)
    at visitEachChildOfBinaryExpression (/TSCFuzzer/tscFuzz/node_modules/typescript/lib/tsc.js:88413:26)
    at visitEachChild (/TSCFuzzer/tscFuzz/node_modules/typescript/lib/tsc.js:87929:33)
    at visitTypeScript (/TSCFuzzer/tscFuzz/node_modules/typescript/lib/tsc.js:90971:16)
    at visitorWorker (/TSCFuzzer/tscFuzz/node_modules/typescript/lib/tsc.js:90712:14)

```

### 🙂 Expected behavior

This error may be caused by too many variables in the destructuring assignment statement.
expected:
no error massage or  give reminder information

### Additional information about the issue

tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "CommonJS",
    "moduleResolution": "Node",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "lib": ["es2023","dom"],
    "noEmitOnError":true,
    "force":true,
    "strict":true
  },
  "include": [
    "TScorpus/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by jcalz** [comment]
Please edit to use the conventional term “destructuring” instead of “deconstruction”, so this issue can be found via search.

**Comment by RyanCavanaugh** [comment]
TypeScript is not designed to handle degenerate cases like this.
