### ISSUE TITLE
Cannot read properties of undefined (reading 'charCount')

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/TypeScript#59956]
### 🔎 Search Terms

undefined (reading 'charCount')

### 🕗 Version & Regression Information

TS nightly v5.7.20240912

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

Error in dev console 

```
mainThreadExtensionService.ts:79 Error: <diagnostics> TypeScript Server Error (5.7.0-dev.20240912)
Cannot read properties of undefined (reading 'charCount')
TypeError: Cannot read properties of undefined (reading 'charCount')
    at _LineNode.walk (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/typescript.js:194226:30)
    at _LineIndex.edit (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/typescript.js:194126:17)
    at _ScriptVersionCache._getSnapshot (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/typescript.js:193932:31)
    at _ScriptVersionCache.lineOffsetToPosition (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/typescript.js:193951:17)
    at TextStorage.lineOffsetToPosition (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/typescript.js:183664:22)
    at ScriptInfo.lineOffsetToPosition (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/typescript.js:183979:29)
    at /Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/typescript.js:190847:40
    at mapDefinedIterator (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/typescript.js:2600:19)
    at mapDefinedIterator.next (<anonymous>)
    at _ProjectService.applyChangesToFile (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/typescript.js:189645:16)
    at _ProjectService.applyChangesInOpenFiles (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/typescript.js:189606:14)
    at updateOpen (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/typescript.js:190836:29)
    at /Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/typescript.js:193504:15
    at IpcIOSession.executeWithRequestId (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/typescript.js:193493:14)
    at IpcIOSession.executeCommand (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/typescript.js:193502:29)
    at IpcIOSession.onMessage (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/typescript.js:193550:68)
    at process.<anonymous> (/Users/ulugbekna/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.7.20240912/node_modules/typescript/lib/tsserver.js:525:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Function.create (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:473825)
    at v.dispatchResponse (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:467795)
    at v.dispatchMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:466593)
    at ChildProcess.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:466086)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.emit (node:domain:488:12)
    at emit (node:internal/child_process:951:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### 🙂 Expected behavior

Doesn't throw

**Comment by Andarist** [comment]
This is not an actionable issue. Please provide some repro case - ideally a short, self-contained, one.

**Comment by andrewbranch** [comment]
Deduping to #60118 which has repro instructions

**Comment by ulugbekna** [comment]
@Andarist 

> This is not an actionable issue.

This is a false statement. I included a stack trace for the error (accessing elements of an empty array). A bare minimum action to take is to check array length before accessing its elements.

**Comment by Andarist** [comment]
That would fix the symptom and not the root cause. It’s not unlikely that it would just move the bug to other place - and it could even still lead to a crash there as clearly some invariant is not met right now

**Comment by ulugbekna** [comment]
@Andarist 

That's why I call it bare minimum, and the statement remains false. I would at least add a `Debug.assert` with more info to debug
