### ISSUE TITLE
Node 22.9.0 tsc crash with "TypeError: Cannot read properties of undefined (reading 'flags')"

### ISSUE THREAD

**Issue by eppisapiafsl** [microsoft/TypeScript#60432]
### 🔎 Search Terms

🕗 Version & Regression Information
I found this old bug https://github.com/microsoft/TypeScript/issues/58371 ; the conversation lead me to a fix that is included in the beta version 5.7

I tried with typescript 5.7.0-dev.20241105 ; but the issue persisted

Given Node introducing "typescript support", I'm wondering, Do we need to replace tsc with tsx or send a new parameter? https://nodejs.org/api/typescript.html#full-typescript-support

```tsc log
~/project/node_modules/typescript/lib/tsc.js:56756
    if (type.flags & 524288 /* Object */) {
             ^

TypeError: Cannot read properties of undefined (reading 'flags')
    at getPropertyOfObjectType (~/project/node_modules/typescript/lib/tsc.js:56756:14)
    at getPropertyOfType (~/project/node_modules/typescript/lib/tsc.js:57400:14)
    at checkPropertyAccessExpressionOrQualifiedName (~/project/node_modules/typescript/lib/tsc.js:72922:14)
    at checkPropertyAccessExpression (~/project/node_modules/typescript/lib/tsc.js:72735:94)
    at checkExpressionWorker (~/project/node_modules/typescript/lib/tsc.js:78501:16)
    at checkExpression (~/project/node_modules/typescript/lib/tsc.js:78421:32)
    at checkExpressionCached (~/project/node_modules/typescript/lib/tsc.js:78095:28)
    at getTargetOfAliasLikeExpression (~/project/node_modules/typescript/lib/tsc.js:47623:5)
    at getTargetOfExportAssignment (~/project/node_modules/typescript/lib/tsc.js:47595:22)
    at getTargetOfAliasDeclaration (~/project/node_modules/typescript/lib/tsc.js:47650:16)

Node.js v22.9.0
```

### 🕗 Version & Regression Information

Bug happen when upgrading from Node 20.9.0 to Node 22.9.0 or to Node 21.7.3

Env

- node: v22.9.0 
- @types/node: 22.9.0
- typescript: v5.5.4
- Node engine declared in package.json: Yes

### 💻 Code

Bug happen at node_modules level

### 🙁 Actual behavior

Typescript is unable to resolve the types due to an internal issue

```tsc log
~/project/node_modules/typescript/lib/tsc.js:56756
    if (type.flags & 524288 /* Object */) {
             ^

TypeError: Cannot read properties of undefined (reading 'flags')
    at getPropertyOfObjectType (~/project/node_modules/typescript/lib/tsc.js:56756:14)
    at getPropertyOfType (~/project/node_modules/typescript/lib/tsc.js:57400:14)
    at checkPropertyAccessExpressionOrQualifiedName (~/project/node_modules/typescript/lib/tsc.js:72922:14)
    at checkPropertyAccessExpression (~/project/node_modules/typescript/lib/tsc.js:72735:94)
    at checkExpressionWorker (~/project/node_modules/typescript/lib/tsc.js:78501:16)
    at checkExpression (~/project/node_modules/typescript/lib/tsc.js:78421:32)
    at checkExpressionCached (~/project/node_modules/typescript/lib/tsc.js:78095:28)
    at getTargetOfAliasLikeExpression (~/project/node_modules/typescript/lib/tsc.js:47623:5)
    at getTargetOfExportAssignment (~/project/node_modules/typescript/lib/tsc.js:47595:22)
    at getTargetOfAliasDeclaration (~/project/node_modules/typescript/lib/tsc.js:47650:16)

Node.js v22.9.0
```

### 🙂 Expected behavior

Non errors inside the node_module package

**Comment by RyanCavanaugh** [comment]
We need a way to reproduce the issue

**Comment by eppisapiafsl** [comment]
👋 @RyanCavanaugh I was able to find the culprit in my codebase 

For anyone facing a similar issue:

Doing a bit of debug notice the function throwing the error was `getPropertyOfObjectType` when `{ type: undefined, name: console }`

```
function getPropertyOfObjectType(type, name) {   
    if (type.flags & 524288 /* Object */) {
      const resolved = resolveStructuredTypeMembers(type);
      const symbol = resolved.members.get(name);
      if (symbol && symbolIsValue(symbol)) {
        return symbol;
      }
    }
  }
```

What causes the issue? A bad jest mock 🤦 

I found this mock in the code base that replaces a `function` with an `undefined` value , once removed the code line the typescript error was fixed 👍 

` jest.spyOn(global.console, "warn").mockImplementation();`
