### ISSUE TITLE
"RangeError: Maximum call stack size exceeded" error after upgrading from 5.6.3 to 5.7.2

### ISSUE THREAD

**Issue by epmatsw** [microsoft/TypeScript#60564]
### 🔎 Search Terms

"Maximum call stack size exceeded", "getContextualTypeForObjectLiteralElement", "checkNonNullExpression"

### 🕗 Version & Regression Information

This changed between versions 5.7.0-dev.20240930 and 5.7.0-dev.20241001

I ran into this bug upgrading from 5.6.3 to 5.7.2 and bisected to that particular release.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.8.0-dev.20241122#code/KYDwDg9gTgLgBAYwgOwM7xgCwJbIOZwC8cA3gFACQAJhNjABQCUplFUwMArlMixfwG0s2VADoAhgF0AXHABEcgDSsAvgG5KK5eqA

### 💻 Code

I don't have a narrowed code example, it just crashes when running `tsc --noEmit` on our whole project.

### 🙁 Actual behavior

```
RangeError: Maximum call stack size exceeded
    at getContextualTypeForObjectLiteralElement (/Users/will/.nvm/versions/node/v22.11.0/lib/node_modules/typescript/lib/_tsc.js:71872:52)
    at getContextualTypeForObjectLiteralMethod (/Users/will/.nvm/versions/node/v22.11.0/lib/node_modules/typescript/lib/_tsc.js:71870:12)
    at getApparentTypeOfContextualType (/Users/will/.nvm/versions/node/v22.11.0/lib/node_modules/typescript/lib/_tsc.js:72086:58)
    at getContextualSignature (/Users/will/.nvm/versions/node/v22.11.0/lib/node_modules/typescript/lib/_tsc.js:72485:18)
    at getContextualThisParameterType (/Users/will/.nvm/versions/node/v22.11.0/lib/node_modules/typescript/lib/_tsc.js:71308:35)
    at tryGetThisTypeAt (/Users/will/.nvm/versions/node/v22.11.0/lib/node_modules/typescript/lib/_tsc.js:71103:33)
    at checkThisExpression (/Users/will/.nvm/versions/node/v22.11.0/lib/node_modules/typescript/lib/_tsc.js:71061:18)
    at checkExpressionWorker (/Users/will/.nvm/versions/node/v22.11.0/lib/node_modules/typescript/lib/_tsc.js:79624:16)
    at checkExpression (/Users/will/.nvm/versions/node/v22.11.0/lib/node_modules/typescript/lib/_tsc.js:79564:32)
    at checkNonNullExpression (/Users/will/.nvm/versions/node/v22.11.0/lib/node_modules/typescript/lib/_tsc.js:73599:29)
```

### 🙂 Expected behavior

No crash

**Comment by Andarist** [comment]
According to the provided bisect information it's caused by something in [this diff](https://github.com/microsoft/TypeScript/compare/2c23beae0297fe3e57868d02af8c9084b136f78c...ca18009b8bd5cea6a7fbcba3d7e4dd3c4633bc92).

To fix this a repro case has to be provided though.

**Comment by epmatsw** [comment]
Got it! https://www.typescriptlang.org/play/?ts=5.8.0-dev.20241122#code/KYDwDg9gTgLgBAYwgOwM7xgCwJbIOZwC8cA3gFACQAJhNjABQCUplFUwMArlMixfwG0s2VADoAhgF0AXHABEcgDSsAvgG5KK5eqA

**Comment by epmatsw** [comment]
It doesn't show up in the UI for some reason, but in the console you can see an uncaught promise rejection:

![Image](https://github.com/user-attachments/assets/b644158d-7dfb-4fff-ab6f-79f30a5355b6)

**Comment by Andarist** [comment]
It shouldn't happen but I'm not entirely convinced that it's a repro case for your original problem. This crashes when calling `reportNonexistentProperty` so it feels like an extra repro for https://github.com/microsoft/TypeScript/issues/60336 (that said... a new one cause your issue is pretty new and that can be reproduced with older TS versions). I assume that you've wanted to report an issue for a code that doesn't error on 5.6.3. Once we add a missing property, this repro stops crashing: [TS playground](https://www.typescriptlang.org/play/?ts=5.8.0-dev.20241122&ssl=2&ssc=11&pln=2&pc=20#code/KYDwDg9gTgLgBAYwgOwM7xgCwJbIOZwC8cA3gFBxwCGAXHAEQBmEE91qiK6ANBXACYRsMABQBKUn0pRgMAK5RkkyirgBtLNlQA6KgF069er1UBfANx9TvC2SA)

**Comment by Andarist** [comment]
The above repro is caused by the fact that `typeFromObjectLiteral` calls `inferExpressionType` nowadays despite `!canGetTypeFromObjectLiteral(objectLiteral, context)`. Previously it bailed out of this function and just returned `false` in this case.

**Comment by epmatsw** [comment]
Hmm. Interesting. It's definitely that line of code, commenting out the equivalent of `[this.a]: "",` in our codebase fixes the error. But it is puzzling that the stack is different here. Maybe it changed between 5.7 and 5.8? I can't tell with the minified stack for 5.7 in the playground :/
