### ISSUE TITLE
Performance is 3x slower in typescript@next

### ISSUE THREAD

**Issue by frankwallis** [Microsoft/TypeScript#6442]
Apologies if you are already aware of this. When running my unit tests for [plugin-typescript](https://github.com/frankwallis/plugin-typescript) against typescript@next I am seeing a ~3x performance slowdown when type-checking:

```
   git clone https://github.com/frankwallis/plugin-typescript.git
   cd plugin-typescript
   npm i
   npm test

   [see output 1]

   npm install typescript@next
   npm test

   [see output 2]
```
output 1:
```
  Type Checker ES6
    ✓ compiles successfully (164ms)
    ✓ loads lib.d.ts by default (145ms)
    ✓ uses config options (163ms)
    ✓ compiles ambient imports (150ms)
    ✓ catches type errors (174ms)
    ✓ catches nested type-checker errors (169ms)
    ✓ fetches all the files needed for compilation (196ms)
    ✓ catches syntax errors (169ms)
    ✓ catches syntax errors in reference files (171ms)
    ✓ handles ambient references when resolveAmbientRefs option is false (240ms)
    ✓ resolves ambient references when resolveAmbientRefs option is true (265ms)
    ✓ handles ambient javascript imports (179ms)
    ✓ handles circular references (167ms)
    ✓ handles ambient typescript imports (170ms)
    ✓ resolves ambient typescript imports (157ms)
    ✓ handles ambients with subset names (164ms)
    ✓ handles ambients with internal requires (150ms)
    ✓ handles external imports (155ms)
    ✓ imports .css files (155ms)
    ✓ imports .html files (168ms)
    ✓ resolves typings files from package.json when resolveTypings is true (187ms)
    ✓ doesnt resolve typings files when resolveTypings is false (163ms)
    ✓ handles missing typings field in package.json (186ms)
    ✓ handles non-relative typings field in package.json (168ms)
TypeScript unable to resolve typings for missing_package, missing_package/package.json could not be found
    ✓ handles package.json not found (164ms)
```

output 2:
```
  Type Checker ES6
    ✓ compiles successfully (639ms)
    ✓ loads lib.d.ts by default (572ms)
    ✓ uses config options (590ms)
    ✓ compiles ambient imports (586ms)
    ✓ catches type errors (549ms)
    ✓ catches nested type-checker errors (643ms)
    ✓ fetches all the files needed for compilation (760ms)
    ✓ catches syntax errors (533ms)
    ✓ catches syntax errors in reference files (452ms)
    ✓ handles ambient references when resolveAmbientRefs option is false (476ms)
    ✓ resolves ambient references when resolveAmbientRefs option is true (459ms)
    ✓ handles ambient javascript imports (470ms)
    ✓ handles circular references (483ms)
    ✓ handles ambient typescript imports (493ms)
    ✓ resolves ambient typescript imports (481ms)
    ✓ handles ambients with subset names (479ms)
    ✓ handles ambients with internal requires (496ms)
    ✓ handles external imports (475ms)
    ✓ imports .css files (485ms)
    ✓ imports .html files (474ms)
    ✓ resolves typings files from package.json when resolveTypings is true (505ms)
    ✓ doesnt resolve typings files when resolveTypings is false (735ms)
    ✓ handles missing typings field in package.json (547ms)
    ✓ handles non-relative typings field in package.json (497ms)
TypeScript unable to resolve typings for missing_package, missing_package/package.json could not be found
    ✓ handles package.json not found (436ms)
```

**Comment by mhegazy** [comment]
What version of node are you seeing this on?

**Comment by frankwallis** [comment]
I'm using v5.1.1

**Comment by mhegazy** [comment]
i am getting a lot errors running `npm test` locally.. this is what i am seeing:

```cmd
 1) Factory adds declaration files into type-checker:
     TypeError: Cannot read property 'kind' of undefined
      at checkGrammarModuleElementContext (c:\test\plugin-typescript\node_modules\typescript\lib\typescript.js:25630:28)
      at checkModuleDeclaration (c:\test\plugin-typescript\node_modules\typescript\lib\typescript.js:25438:21)
      at checkSourceElement (c:\test\plugin-typescript\node_modules\typescript\lib\typescript.js:25811:28)
      at Object.forEach (c:\test\plugin-typescript\node_modules\typescript\lib\typescript.js:887:30)
      at checkSourceFileWorker (c:\test\plugin-typescript\node_modules\typescript\lib\typescript.js:25957:20)
      at checkSourceFile (c:\test\plugin-typescript\node_modules\typescript\lib\typescript.js:25939:13)
      at getDiagnosticsWorker (c:\test\plugin-typescript\node_modules\typescript\lib\typescript.js:25999:17)
      at Object.getDiagnostics (c:\test\plugin-typescript\node_modules\typescript\lib\typescript.js:25990:24)
      at c:\test\plugin-typescript\node_modules\typescript\lib\typescript.js:36510:52
      at runWithCancellationToken (c:\test\plugin-typescript\node_modules\typescript\lib\typescript.js:36486:24)
      at getSemanticDiagnosticsForFile (c:\test\plugin-typescript\node_modules\typescript\lib\typescript.js:36506:20)
      at getDiagnosticsHelper (c:\test\plugin-typescript\node_modules\typescript\lib\typescript.js:36461:24)
      at Object.getSemanticDiagnostics (c:\test\plugin-typescript\node_modules\typescript\lib\typescript.js:36476:20)
      at ../src/type-checker.ts:250:22
      at Array.reduce (native)
      at TypeChecker.getAllDiagnostics (../src/type-checker.ts:244:15)
      at ../src/type-checker.ts:106:22
```

**Comment by mhegazy** [comment]
looks like @vladima have this repro working locally.

**Comment by frankwallis** [comment]
There was a paths issue when running the tests on windows which I have fixed now. I think there is still a paths issue causing it to type-check the default lib on windows, but I need to investigate that further.

Anyway I'm glad you were able to reproduce it and I will try out the fix when it comes through, thanks.

**Comment by frankwallis** [comment]
thanks, it's back to normal now.
