### ISSUE TITLE
tsc crashes on JS file with dynamic require() call

### ISSUE THREAD

**Issue by jeffreymorlan** [Microsoft/TypeScript#6703]
If you include the file http://momentjs.com/downloads/moment.js in a `tsc --allowJs` compilation, a TypeError is thrown:
```
TypeError: Cannot call method 'indexOf' of undefined
    at classicNameResolver (/home/jeffrey/TypeScript-1.8.0-beta/lib/tsc.js:32405:24)
    at resolveModuleName (/home/jeffrey/TypeScript-1.8.0-beta/lib/tsc.js:32308:28)
    at resolveModuleNamesWorker (/home/jeffrey/TypeScript-1.8.0-beta/lib/tsc.js:32573:40)
    at processImportedModules (/home/jeffrey/TypeScript-1.8.0-beta/lib/tsc.js:33156:35)
    at findSourceFile (/home/jeffrey/TypeScript-1.8.0-beta/lib/tsc.js:33132:17)
    at processSourceFile (/home/jeffrey/TypeScript-1.8.0-beta/lib/tsc.js:33059:27)
    at processRootFile (/home/jeffrey/TypeScript-1.8.0-beta/lib/tsc.js:32982:13)
    at /home/jeffrey/TypeScript-1.8.0-beta/lib/tsc.js:32594:60
    at Object.forEach (/home/jeffrey/TypeScript-1.8.0-beta/lib/tsc.js:98:30)
    at Object.createProgram (/home/jeffrey/TypeScript-1.8.0-beta/lib/tsc.js:32594:16)
```
This is caused by the following JS source line:
```js
require('./locale/' + name);
```
The function `isRequireCall` in utilities.ts returns true on this expression, but there are two places that assume that if `isRequireCall` returns true, then the argument must be a string literal.

**Comment by mhegazy** [comment]
@jeffreymorlan, the fix should be in tonight's `typescript@next`. please give a try and let us know how it fares.

**Comment by jeffreymorlan** [comment]
Yes, that fixed it - thanks!
