### ISSUE TITLE
TypeScript 1.8 beta throws exception with typescript.js as input

### ISSUE THREAD

**Issue by martine** [Microsoft/TypeScript#6727]
```shell
$ npm i typescript@beta
$ ./node_modules/typescript/bin/tsc --allowJs ./node_modules/typescript/lib/typescript.js --outFile test.js
.../node_modules/typescript/lib/tsc.js:32796
                throw e;
                      ^
TypeError: Cannot read property 'type' of undefined
    at getReturnTypeFromJSDocComment (.../node_modules/typescript/lib/tsc.js:19407:68)
    at getSignatureFromDeclaration (.../node_modules/typescript/lib/tsc.js:14802:36)
    at checkSpecializedSignatureDeclaration (.../node_modules/typescript/lib/tsc.js:20664:29)
    at checkSignatureDeclaration (.../node_modules/typescript/lib/tsc.js:20420:13)
    at checkFunctionOrMethodDeclaration (.../node_modules/typescript/lib/tsc.js:21170:13)
    at checkFunctionDeclaration (.../node_modules/typescript/lib/tsc.js:21161:17)
    at checkSourceElement (.../node_modules/typescript/lib/tsc.js:22800:28)
    at Object.forEach (.../node_modules/typescript/lib/tsc.js:98:30)
    at checkBlock (.../node_modules/typescript/lib/tsc.js:21207:16)
    at checkSourceElement (.../node_modules/typescript/lib/tsc.js:22803:28)
```

**Comment by RyanCavanaugh** [comment]
Same root cause as #6662
