### ISSUE TITLE
Unable to resolve alias in commonjs module with --allowJs

### ISSUE THREAD

**Issue by jden** [Microsoft/TypeScript#6775]
See this reproduction case: https://gist.github.com/jden/7cd1433497897e64af9f

Tested with same results in typescript@beta and typescript@next

```
> tsc --allowJs --outDir foo index.js
/usr/local/lib/node_modules/typescript/lib/tsc.js:33194
                throw e;
                ^

TypeError: Cannot read property 'kind' of undefined
    at getTargetOfAliasDeclaration (/usr/local/lib/node_modules/typescript/lib/tsc.js:12347:25)
    at resolveAlias (/usr/local/lib/node_modules/typescript/lib/tsc.js:12371:30)
    at resolveSymbol (/usr/local/lib/node_modules/typescript/lib/tsc.js:12363:101)
    at resolveExternalModuleSymbol (/usr/local/lib/node_modules/typescript/lib/tsc.js:12499:52)
    at resolveExternalModuleTypeByLiteral (/usr/local/lib/node_modules/typescript/lib/tsc.js:14915:44)
    at checkCallExpression (/usr/local/lib/node_modules/typescript/lib/tsc.js:19439:24)
    at checkExpressionWorker (/usr/local/lib/node_modules/typescript/lib/tsc.js:20314:28)
    at checkExpression (/usr/local/lib/node_modules/typescript/lib/tsc.js:20264:42)
    at checkExpressionCached (/usr/local/lib/node_modules/typescript/lib/tsc.js:20225:38)
    at getTypeForVariableLikeDeclaration (/usr/local/lib/node_modules/typescript/lib/tsc.js:13672:24)

```

It seems to happen when assigning to module.exports with a variable name. I do not get this error when assigning a property of module.exports (eg `module.exports.a = foo`) or when assigning a literal to module.exports (eg `module.exports = 'hi'` or `module.exports = () => 'hi'`)

**Comment by RyanCavanaugh** [comment]
Same as #6673

**Comment by mhegazy** [comment]
@RyanCavanaugh can you port the change to release-1.8 as well.
