### ISSUE TITLE
http://www.typescriptlang.org/Playground/ not working with Chrome

### ISSUE THREAD

**Issue by JohnPhilipPearson** [Microsoft/TypeScript#6816]
OS X 10.11.3
Playground works fine with Safari 9.0.3.
Playground is not working with Chrome 48.0.2564.97 (64-bit)

**Comment by RyanCavanaugh** [comment]
@billti can you confirm?

**Comment by billti** [comment]
Just tested and it's working for me, although it was reeeeeeally slow - both to load the editors, and then for first compile after I added some code.

Note I'm also on "49.0.2623.28 beta (64-bit)" (Not sure how to go back from the Beta channel, but I can try if need be).

@JohnPhilipPearson If you give it a good long time, does it eventually work?

**Comment by JohnPhilipPearson** [comment]
I am on my home network which is very fast and it is working.
Will check from home in the future.

**Comment by bbottema** [comment]
It's not working in chrome for me: Version 48.0.2564.97 m (64-bit).

```
editors rendered @ 2369ms
Playground:264 sample rendered @ 2410ms
loader.js:1 GET http://www.typescriptlang.org/Script/vs/languages/typescript/common/lib/typescriptServices.js net::ERR_CONTENT_LENGTH_MISMATCHe.load @ loader.js:1e.load @ loader.js:1i @ loader.js:1e._loadModule @ loader.js:1l @ loader.js:1e._resolveDependency @ loader.js:1e._resolve @ loader.js:1e.defineModule @ loader.js:1e._onLoad @ loader.js:1(anonymous function) @ loader.js:1e.triggerCallback @ loader.js:1(anonymous function) @ loader.js:1o @ loader.js:1
editor.main.js:9 WARNING: Promise with no error callback:2
editor.main.js:9 Object {exception: null, error: Object, promise: t.C…s.d…e._oncancel, handler: undefined, id: 2…}
editor.main.js:9 WARNING: Promise with no error callback:3
editor.main.js:9 Object {exception: null, error: Object, promise: t.C…s.d…e._oncancel, handler: undefined, id: 3…}
2editor.main.js:6 Uncaught #<Object>(anonymous function) @ editor.main.js:6
Script/vs/languages/typescript/common/lib/typescriptServices.js:1 GET http://www.typescriptlang.org/Script/vs/languages/typescript/common/lib/typescriptServices.js net::ERR_CONTENT_LENGTH_MISMATCH
editor.main.js:11 Loading "vs/languages/typescript/common/typescriptMode.nls" failede._consoleLog @ editor.main.js:11e._onmessage @ editor.main.js:11e._onSerializedMessage @ editor.main.js:11(anonymous function) @ editor.main.js:11worker.onmessage @ editor.main.js:14
editor.main.js:11 ["Detail: ", Object]e._consoleLog @ editor.main.js:11e._onmessage @ editor.main.js:11e._onSerializedMessage @ editor.main.js:11(anonymous function) @ editor.main.js:11worker.onmessage @ editor.main.js:14
editor.main.js:11 Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://www.typescriptlang.org/Script/vs/languages/typescript/common/lib/typescriptServices.js' failed to load.
    at Error (native)
    at e._load (http://www.typescriptlang.org/Script/vs/loader.js:1:28585)
    at http://www.typescriptlang.org/Script/vs/loader.js:1:28415e._consoleLog @ editor.main.js:11e._onmessage @ editor.main.js:11e._onSerializedMessage @ editor.main.js:11(anonymous function) @ editor.main.js:11worker.onmessage @ editor.main.js:14
editor.main.js:11 Here are the modules that depend on it:e._consoleLog @ editor.main.js:11e._onmessage @ editor.main.js:11e._onSerializedMessage @ editor.main.js:11(anonymous function) @ editor.main.js:11worker.onmessage @ editor.main.js:14
editor.main.js:11 ["===anonymous6==="]e._consoleLog @ editor.main.js:11e._onmessage @ editor.main.js:11e._onSerializedMessage @ editor.main.js:11(anonymous function) @ editor.main.js:11worker.onmessage @ editor.main.js:14
2editorWorkerServer.js:9 Uncaught TypeError: Cannot set property message of [object Object] which has only a gettere.onErrorEvent @ editorWorkerServer.js:9(anonymous function) @ workerServer.js:2e.emit @ workerServer.js:2e.onUnexpectedError @ workerServer.js:2c @ workerServer.js:2t.Class.define.done @ workerServer.js:1h @ workerServer.js:1H.enter @ workerServer.js:1t.Class.define._run @ workerServer.js:1t.Class.define._chainedError @ workerServer.js:1r @ workerServer.js:1h @ workerServer.js:1H.enter @ workerServer.js:1t.Class.define._run @ workerServer.js:1t.Class.define._chainedError @ workerServer.js:1r @ workerServer.js:1h @ workerServer.js:1H.enter @ workerServer.js:1t.Class.define._run @ workerServer.js:1t.Class.define._error @ workerServer.js:1e.onDependencyError @ loader.js:1e._onLoadError @ loader.js:1i @ loader.js:1(anonymous function) @ loader.js:1e.triggerErrorback @ loader.js:1(anonymous function) @ loader.js:1e._load @ loader.js:1(anonymous function) @ loader.js:1
editor.main.js:11 Object {errorCode: "load", moduleId: "vs/languages/typescript/common/lib/typescriptServices", neededBy: Array[1], detail: Object}e._consoleLog @ editor.main.js:11e._onmessage @ editor.main.js:11e._onSerializedMessage @ editor.main.js:11(anonymous function) @ editor.main.js:11worker.onmessage @ editor.main.js:14
editor.main.js:11 Object {errorCode: "load", moduleId: "vs/languages/javascript/common/javascript", neededBy: Array[1], detail: Object}e._consoleLog @ editor.main.js:11e._onmessage @ editor.main.js:11e._onSerializedMessage @ editor.main.js:11(anonymous function) @ editor.main.js:11worker.onmessage @ editor.main.js:14
editor.main.js:11 Loading "vs/languages/typescript/common/typescriptMode.nls" failede._consoleLog @ editor.main.js:11e._onmessage @ editor.main.js:11e._onSerializedMessage @ editor.main.js:11(anonymous function) @ editor.main.js:11worker.onmessage @ editor.main.js:14
editor.main.js:11 ["Detail: ", Object]e._consoleLog @ editor.main.js:11e._onmessage @ editor.main.js:11e._onSerializedMessage @ editor.main.js:11(anonymous function) @ editor.main.js:11worker.onmessage @ editor.main.js:14
editor.main.js:11 Error: Uncaught SyntaxError: Unexpected end of input
    at Error (native)
    at e._load (http://www.typescriptlang.org/Script/vs/loader.js:1:28585)
    at http://www.typescriptlang.org/Script/vs/loader.js:1:28415e._consoleLog @ editor.main.js:11e._onmessage @ editor.main.js:11e._onSerializedMessage @ editor.main.js:11(anonymous function) @ editor.main.js:11worker.onmessage @ editor.main.js:14
editor.main.js:11 Here are the modules that depend on it:e._consoleLog @ editor.main.js:11e._onmessage @ editor.main.js:11e._onSerializedMessage @ editor.main.js:11(anonymous function) @ editor.main.js:11worker.onmessage @ editor.main.js:14
editor.main.js:11 ["===anonymous6==="]e._consoleLog @ editor.main.js:11e._onmessage @ editor.main.js:11e._onSerializedMessage @ editor.main.js:11(anonymous function) @ editor.main.js:11worker.onmessage @ editor.main.js:14
editor.main.js:11 Object {errorCode: "load", moduleId: "vs/languages/typescript/common/lib/typescriptServices", neededBy: Array[1], detail: Object}e._consoleLog @ editor.main.js:11e._onmessage @ editor.main.js:11e._onSerializedMessage @ editor.main.js:11(anonymous function) @ editor.main.js:11worker.onmessage @ editor.main.js:14
editor.main.js:11 Object {errorCode: "load", moduleId: "vs/languages/javascript/common/javascript", neededBy: Array[1], detail: Object}
```

**Comment by kitsonk** [comment]
Working for me, but as noted really slow.  Chrome Version 48.0.2564.103 (64-bit) OSX 10.11.4 Beta.

```
Playground:259 editors rendered @ 10740ms
Playground:264 sample rendered @ 10753ms
Playground:268 sample colored @ 20880ms
Playground:269 starting compilation @ 20880ms
Playground:275 sample compiled @ 20881ms
Playground:280 sample compiled & colored @ 20886ms
```

I even disabled the cache and got:

```
editors rendered @ 14908ms
Playground:264 sample rendered @ 14919ms
Playground:268 sample colored @ 24713ms
Playground:269 starting compilation @ 24714ms
Playground:275 sample compiled @ 24714ms
Playground:280 sample compiled & colored @ 24721ms
```
