### ISSUE TITLE
Language service breaks compatibility at the nightly 1.9.0-dev.20160218

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#7133]
**TypeScript Version:** 

nightly (1.9.0-dev.20160218)

---

I got errors from gulp-typescript@2.11.0 with the nightly 1.9.0-dev.20160218. Nightly 1.9.0-dev.20160217 works correctly. It seems to break compatibility of language service **between 1.9.0-dev.20160217 and 1.9.0-dev.20160218**.

```
.\node_modules\gulp-typescript\release\tsapi.js:49
        result.emitErrors = emitOutput.diagnostics.length;
                                                  ^

TypeError: Cannot read property 'length' of undefined
    at Object.getDiagnosticsAndEmit (.\node_modules\gulp-typescript\release\tsapi.js:49:51)
    at ProjectCompiler.inputDone (.\node_modules\gulp-typescript\release\compiler.js:66:24)
    at CompileStream.end (.\node_modules\gulp-typescript\release\main.js:52:31)
    at DestroyableTransform.onend (.\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:523:1
0)
    at DestroyableTransform.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at DestroyableTransform.emit (events.js:179:7)
    at .\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)
```

**Comment by vladima** [comment]
Pinging @mhegazy: probably it is related to renaming `diagnostics` property in `EmitOutput`

**Comment by mhegazy** [comment]
is `getPreEmitDiagnostics` sufficient?

**Comment by mhegazy** [comment]
reverted the offending change, tonight's nightly should have it.

**Comment by falsandtru** [comment]
thanks!
