### ISSUE TITLE
Export declaration conflicts makes the compiler throw

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#7337]
**TypeScript Version:** 

 nightly (1.9.0-dev.20160217)

**Code**

```ts
export interface ColumnInfo {
}
//...
export { ColumnInfo };
```

**Expected behavior:**

a compilation that doesn't throw.

**Actual behavior:** 
```
types.ts(75,5): error TS2484: Export declaration conflicts with exported declaration of 'ColumnInfo'
C:\Users\Nino\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:33304
                throw e;
                ^

Error: Debug Failure. False expression: isDeclarationVisible unknown: SyntaxKind: 234
    at Object.assert (C:\Users\Nino\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:780:23)
    at Object.fail (C:\Users\Nino\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:785:19)
    at determineIfDeclarationIsVisible (C:\Users\Nino\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13490:34)
    at isDeclarationVisible (C:\Users\Nino\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13425:41)
    at getIsDeclarationVisible (C:\Users\Nino\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:12870:22)
    at C:\Users\Nino\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:12865:82
    at Object.forEach (C:\Users\Nino\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:113:30)
    at hasVisibleDeclarations (C:\Users\Nino\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:12865:20)
    at Object.isEntityNameVisible (C:\Users\Nino\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:12905:31)
    at emitEntityName (C:\Users\Nino\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:25313:49)```

**Comment by mhegazy** [comment]
looks fixed in latest.
