### ISSUE TITLE
Regression: Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by blakeembrey** [Microsoft/TypeScript#8053]
**TypeScript Version:** 

Introduced in `1.8.9`.

**Code**

From https://github.com/typings/core/pull/86, I tried to fix Typings to make the alias re-exports use `import = ...; export =` syntax, but it can not compile with `1.8.9` or `1.8.10`. 

```ts
// Pulling together a self-contained demo.
```

**Expected behavior:**

Compiles.

**Actual behavior:** 

```
/Users/blakeembrey/Projects/typings/core/node_modules/typescript/lib/tsc.js:33064
                throw e;
                ^

TypeError: Cannot read property 'parent' of undefined
    at appendOuterTypeParameters (/Users/blakeembrey/Projects/typings/core/node_modules/typescript/lib/tsc.js:13991:28)
    at getOuterTypeParametersOfClassOrInterface (/Users/blakeembrey/Projects/typings/core/node_modules/typescript/lib/tsc.js:14007:20)
    at getDeclaredTypeOfClassOrInterface (/Users/blakeembrey/Projects/typings/core/node_modules/typescript/lib/tsc.js:14191:43)
    at getDeclaredTypeOfSymbol (/Users/blakeembrey/Projects/typings/core/node_modules/typescript/lib/tsc.js:14263:24)
    at getTypeFromClassOrInterfaceReference (/Users/blakeembrey/Projects/typings/core/node_modules/typescript/lib/tsc.js:15148:24)
    at getTypeFromTypeReference (/Users/blakeembrey/Projects/typings/core/node_modules/typescript/lib/tsc.js:15241:52)
    at getTypeFromTypeNode (/Users/blakeembrey/Projects/typings/core/node_modules/typescript/lib/tsc.js:15535:28)
    at getTypeForVariableLikeDeclaration (/Users/blakeembrey/Projects/typings/core/node_modules/typescript/lib/tsc.js:13722:24)
    at getWidenedTypeForVariableLikeDeclaration (/Users/blakeembrey/Projects/typings/core/node_modules/typescript/lib/tsc.js:13801:24)
    at getTypeOfVariableOrParameterOrProperty (/Users/blakeembrey/Projects/typings/core/node_modules/typescript/lib/tsc.js:13844:28)
```

Edit: Can not reproduce it yet, narrowed it down to the `popsicle` typings (combined with something in the `typings-core` project and the new export format in the PR).

**Comment by blakeembrey** [comment]
I can not produce a self-contained demonstration, but all the code is open source. If you run `npm run bootstrap` and then `npm run build` in the branch with the linked PR, you'll see it occur after you build. I can delete a couple of combinations of definitions to make the error go away, but then I can't compile (because I need the definitions for the type info).

**Comment by vladima** [comment]
simplified repro

```ts
declare module '~popsicle/dist/request' {
    export default class Request {}
}

declare module '~popsicle/dist/common' {
    import Request from '~popsicle/dist/request';
    export { Request };
}

declare module 'popsicle' {
    import alias = require('~popsicle/dist/common');
    export = alias;
}

declare module 'popsicle-proxy-agent' {
    import { Request } from 'popsicle';
    function proxy(): (request: Request) => any;
    export = proxy;
}
```
