### ISSUE TITLE
Cannot get symbol inside class decorator (Cannot read property 'members' of un...)

### ISSUE THREAD

**Issue by mgechev** [microsoft/TypeScript#8136]
**TypeScript Version:** 

1.8.10

**Code**

``` ts
@Component({
  selector: SELECTOR
})
class SampleComponent {}
const SELECTOR = 'ng-demo';
```

**Expected behavior:**

With sample [`SyntaxWalker`](https://github.com/palantir/tslint/blob/master/src/language/walker/syntaxWalker.ts) based on `tslint`, once I visit the `PropertyAssignment` - `selector: SELECTOR` and invoke `typeChecker.getSymbolAtLocation(prop.initializer);` I should get the `SELECTOR` symbol.

**Actual behavior:** 

```
     TypeError: Cannot read property 'members' of undefined
      at resolveName (node_modules/typescript/lib/typescript.js:15307:73)
      at resolveEntityName (node_modules/typescript/lib/typescript.js:15725:26)
      at getSymbolOfEntityNameOrPropertyAccessExpression (node_modules/typescript/lib/typescript.js:28708:28)
      at Object.getSymbolAtLocation (node_modules/typescript/lib/typescript.js:28770:28)
```

**Comment by mhegazy** [comment]
why are you calling it on the initializer? this is the `'ng-demo'` part. you probably want `PropertyAssignment.name`

it shoudl not crash either ways, so that is a bug.

**Comment by mhegazy** [comment]
PRs are welcomed

**Comment by JoshuaKGoldberg** [comment]
Found a root cause. See ☝ linked issues!

**Comment by RyanCavanaugh** [comment]
TS 6 API won't be receiving any additional fixes.
