### ISSUE TITLE
-w and -p options do not work together

### ISSUE THREAD

**Issue by marcinnajder** [Microsoft/TypeScript#8170]
./node_modules/.bin/tsc -v
Version 1.9.0-dev.20160418

./node_modules/.bin/tsc -p . -w
fs.js:1236
    throw error;
    ^

Error: watch  ENOENT
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at addDirWatcher (/Volumes/data/gitlab/cms2/node_modules/typescript/lib/tsc.js:1072:39)
    at Object.addFile (/Volumes/data/gitlab/cms2/node_modules/typescript/lib/tsc.js:1087:21)
    at Object.watchFile (/Volumes/data/gitlab/cms2/node_modules/typescript/lib/tsc.js:1226:48)
    at Object.executeCommandLine (/Volumes/data/gitlab/cms2/node_modules/typescript/lib/tsc.js:36330:44)
    at Object.<anonymous> (/Volumes/data/gitlab/cms2/node_modules/typescript/lib/tsc.js:36692:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by zhengbli** [comment]
After #8196, this error doesn't happen anymore.
