### ISSUE TITLE
strictNullChecks with control flow in multiple loops throws TypeError

### ISSUE THREAD

**Issue by ivogabe** [Microsoft/TypeScript#8418]
**TypeScript Version:** 

nightly (1.9.0-dev.20160502)

**Code**

```ts
function test() {
	let x: number | undefined;
	while (y()) {
		while (y()) {
			while (y()) {
				x = foo(x);
			}
		}
		x = 1;
	}
}
function y(): boolean {
	return true;
}
function foo(x: number): number { return 1; }
```

**Expected behavior:**
Compile error reported on `foo(x)`, as `x` can be `undefined` on that location.

**Actual behavior:** 
Type Error:
```
$ ./node_modules/.bin/tsc --strictNullChecks test
node_modules/typescript/lib/tsc.js:35204
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at isConstEnumObjectType (node_modules/typescript/lib/tsc.js:21310:24)
    at checkExpression (node_modules/typescript/lib/tsc.js:21721:17)
    at checkExpressionWithContextualType (node_modules/typescript/lib/tsc.js:21669:26)
    at checkApplicableSignature (node_modules/typescript/lib/tsc.js:20309:31)
    at chooseOverload (node_modules/typescript/lib/tsc.js:20606:30)
    at resolveCall (node_modules/typescript/lib/tsc.js:20530:26)
    at resolveCallExpression (node_modules/typescript/lib/tsc.js:20669:20)
    at resolveSignature (node_modules/typescript/lib/tsc.js:20791:28)
    at getResolvedSignature (node_modules/typescript/lib/tsc.js:20808:26)
    at checkCallExpression (node_modules/typescript/lib/tsc.js:20824:29)
```

**Comment by ahejlsberg** [comment]
Good catch. Surprising we haven't caught this one already. An even simpler repro is:

```typescript
function test() {
    let x: number | undefined;
    x = 1;
    while (y()) {
        while (y()) {
            x = foo(x);
        }
    }
}
```

Fix is pretty easy, I will have it up soon.

**Comment by ivogabe** [comment]
Thanks for the quick fix! This shows once again that the nightly build can be very useful to find bugs 😃
