### ISSUE TITLE
Allow configuration of removing 'falsy' double slash

### ISSUE THREAD

**Issue by s7726** [Microsoft/TypeScript#8470]
Background: [StackOverflow post](http://stackoverflow.com/questions/37038412/typescript-option-to-not-remove-from-filename)

TypeScript Version: Current

core.ts:getNormalizedParts() removes 'falsy' double slashes, which breaks my application. Please allow for an option to not remove extra slashes.

`http://somewhere/directory//directory2/file.ts`

becomes

`http://somewhere/directory/directory2/file.ts`

which does not resolve in the environment in question.

**Comment by mhegazy** [comment]
so how does this manifest in your output?

**Comment by s7726** [comment]
If F12 is open I get a stop at `debugger`. Otherwise or if I continue I get:
`[object Error]`

    "Error: Debug Failure. False expression: Output generation failed
	   at assert (http://localhost:3000/Project/name//plugin/ng2qs/lib/typescript.js:1721:17)
	   at transpileModule (http://localhost:3000/Project/name//plugin/ng2qs/lib/typescript.js:48178:9)
	   at transpile (http://localhost:3000/Project/name//plugin/ng2qs/lib/typescript.js:48186:9)
	   at ZoneDelegate.prototype.invoke (https://npmcdn.com/zone.js@0.6.12?main=browser:321:14)
	   at Zone.prototype.run (https://npmcdn.com/zone.js@0.6.12?main=browser:216:18)
	   at Anonymous function (https://npmcdn.com/zone.js@0.6.12?main=browser:571:18)
	   at ZoneDelegate.prototype.invokeTask (https://npmcdn.com/zone.js@0.6.12?main=browser:354:18)
	   at Zone.prototype.runTask (https://npmcdn.com/zone.js@0.6.12?main=browser:256:22)
	Error loading http://localhost:3000/Project/name//plugin/ng2qs/app/main.ts"

**Comment by mhegazy** [comment]
sorry for the delay. should be fixed in `typescript@next` later tonight.

**Comment by s7726** [comment]
Awesome! Thanks!
