### ISSUE TITLE
Reference-types directive crashes TSServer

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#9186]
Create a TypeScript file with the following contents:
 
```ts
/// <reference types="foo" />
var x;
```

This seems to cause TSServer to crash.

**Comment by RyanCavanaugh** [comment]
What exactly is the repro for this?

**Comment by DanielRosenwasser** [comment]
So go get a clean machine.

1. Install Sublime or VS Code.
2. Install `typescript@next` globally.
3. Point your `typescript_tsdk` (if Sublime) or `typescript.tsdk` (if VS Code) variable to your TypeScript build's `lib` directory.
4. Restart your editor.
5. Add a `/// <reference types="foo" />`

**Comment by zhengbli** [comment]
FWIW now the tsserver can print exception stack trace, I do see the following stack trace for the issue:

```
Response received: completions (13). Request took 1 ms. Success: false . Message: Error processing request. No Project.
Error: No Project.
    at Errors (C:\Users\zhengbli\AppData\Roaming\nvm\v6.1.0\node_modules\typescript\lib\tsserver.js:49039:32)
    at ts.server.ts.server (C:\Users\zhengbli\AppData\Roaming\nvm\v6.1.0\node_modules\typescript\lib\tsserver.js:49040:11)
    at ts (C:\Users\zhengbli\AppData\Roaming\nvm\v6.1.0\node_modules\typescript\lib\tsserver.js:49986:7)
    at Object.<anonymous> (C:\Users\zhengbli\AppData\Roaming\nvm\v6.1.0\node_modules\typescript\lib\tsserver.js:49987:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

**Comment by mhegazy** [comment]
@zhengbli can you take a look.
