### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by t246246** [Microsoft/TypeScript#9285]
I separate this issue from [#168](https://github.com/s-panferov/awesome-typescript-loader/issues/168)

When I use awesome-typescript-loader 2.0.0-rc.6 with typescript 1.9.0-dev.20160620-1.0 on Windows, 
```
C:\work\plunk\node_modules\awesome-typescript-loader\src\host.ts:50
        return this.state.ts.ScriptSnapshot.fromString(file.text);
                                                           ^
TypeError: Cannot read property 'text' of undefined
    at Host.getScriptSnapshot (C:\work\plunk\node_modules\awesome-typescript-loader\src\host.ts:50:60)
    at HostCache.createEntry (C:\work\plunk\node_modules\typescript\lib\typescript.js:52034:44)
    at HostCache.getOrCreateEntryByPath (C:\work\plunk\node_modules\typescript\lib\typescript.js:52059:24)
    at getOrCreateSourceFileByPath (C:\work\plunk\node_modules\typescript\lib\typescript.js:53111:53)
    at Object.getOrCreateSourceFile [as getSourceFile] (C:\work\plunk\node_modules\typescript\lib\typescript.js:53104:24)
    at findSourceFile (C:\work\plunk\node_modules\typescript\lib\typescript.js:43908:29)
    at processSourceFile (C:\work\plunk\node_modules\typescript\lib\typescript.js:43856:27)
    at C:\work\plunk\node_modules\typescript\lib\typescript.js:43949:17
    at Object.forEach (C:\work\plunk\node_modules\typescript\lib\typescript.js:967:30)
    at processReferencedFiles (C:\work\plunk\node_modules\typescript\lib\typescript.js:43947:16)
    at findSourceFile (C:\work\plunk\node_modules\typescript\lib\typescript.js:43932:21)
    at processSourceFile (C:\work\plunk\node_modules\typescript\lib\typescript.js:43856:27)
    at processRootFile (C:\work\plunk\node_modules\typescript\lib\typescript.js:43760:13)
    at C:\work\plunk\node_modules\typescript\lib\typescript.js:43228:60
    at Object.forEach (C:\work\plunk\node_modules\typescript\lib\typescript.js:967:30)
    at Object.createProgram (C:\work\plunk\node_modules\typescript\lib\typescript.js:43228:16)
    at synchronizeHostData (C:\work\plunk\node_modules\typescript\lib\typescript.js:53082:33)
    at Object.getProgram (C:\work\plunk\node_modules\typescript\lib\typescript.js:53182:13)
    at State.updateProgram (C:\work\plunk\node_modules\awesome-typescript-loader\src\host.ts:142:38)
    at Compiler.<anonymous> (C:\work\plunk\node_modules\awesome-typescript-loader\src\instance.ts:380:23)
    at next (C:\work\plunk\node_modules\webpack\node_modules\tapable\lib\Tapable.js:83:14)
    at Compiler.<anonymous> (C:\work\plunk\node_modules\webpack\lib\CachePlugin.js:61:4)
    at Compiler.applyPluginsAsync (C:\work\plunk\node_modules\webpack\node_modules\tapable\lib\Tapable.js:85:13)
    at Compiler.<anonymous> (C:\work\plunk\node_modules\webpack\lib\Compiler.js:434:9)
    at Compilation.<anonymous> (C:\work\plunk\node_modules\webpack\lib\Compilation.js:577:13)
    at Compilation.applyPluginsAsync (C:\work\plunk\node_modules\webpack\node_modules\tapable\lib\Tapable.js:73:70)
    at Compilation.<anonymous> (C:\work\plunk\node_modules\webpack\lib\Compilation.js:572:10)
    at Compilation.applyPluginsAsync (C:\work\plunk\node_modules\webpack\node_modules\tapable\lib\Tapable.js:73:70)
    at Compilation.<anonymous> (C:\work\plunk\node_modules\webpack\lib\Compilation.js:567:9)
    at Compilation.applyPluginsAsync (C:\work\plunk\node_modules\webpack\node_modules\tapable\lib\Tapable.js:73:70)
```
 Other setting is same as #168.

**Comment by t246246** [comment]
Sorry, I wrote to wrong github.

**Comment by troywweber7** [comment]
I'm having this issue as well... What github did you post to? That would kine of be helpful...

**Comment by troywweber7** [comment]
@t246246 So I found the issue that was resulting on my end. I had some template files in a folder named `plop/` that ended in `.ts` and once I deleted that directory (or changed the ending to `.txt`) the error went away. Oddly, my `tsconfig.json` had a specified `rootDir` and `outDir` and therefore should not have even been looking at that `plop/` folder in the first place...
