### ISSUE TITLE
Can't install typescript via nodejs

### ISSUE THREAD

**Issue by diogoca** [Microsoft/TypeScript#9292]
Hi there,

I'm don't know why, but the typescript is not allowed to install. Should I remove grunt-penthouse to install typescript? 

```
C:\Users\dalves>npm install -g typescript
C:\Users\dalves\AppData\Roaming\npm\tsserver -> C:\Users\dalves\AppData\Roaming\
npm\node_modules\typescript\bin\tsserver
C:\Users\dalves\AppData\Roaming\npm\tsc -> C:\Users\dalves\AppData\Roaming\npm\n
ode_modules\typescript\bin\tsc
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "typescript"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peer
Dependencies requirements!
npm ERR! peerinvalid Peer grunt-penthouse@0.3.0 wants grunt@~0.4.2

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\dalves\npm-debug.log
```

**npm-debug.log**

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'typescript' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose install initial load of C:\Users\dalves\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\dalves\AppData\Roaming\npm\package.json
6 silly cache add args [ 'typescript', null ]
7 verbose cache add spec typescript
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'typescript',
8 silly cache add   scope: null,
8 silly cache add   name: 'typescript',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed typescript@latest
10 verbose addNamed "latest" is being treated as a dist-tag for typescript
11 info addNameTag [ 'typescript', 'latest' ]
12 silly mapToRegistry name typescript
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'typescript',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'typescript',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/typescript
17 verbose addNameTag registry:https://registry.npmjs.org/typescript not in flight; fetching
18 verbose request uri https://registry.npmjs.org/typescript
19 verbose request no auth needed
20 info attempt registry request try #1 at 8:14:58 AM
21 verbose request id fda3622f605b157d
22 verbose etag "4WN7PT456MQNCXD0JTWT2O0JZ"
23 http request GET https://registry.npmjs.org/typescript
24 http 200 https://registry.npmjs.org/typescript
25 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
25 verbose headers   etag: '"7ZUQ1648WT73G4C5MQ85MM0KK"',
25 verbose headers   'content-type': 'application/json',
25 verbose headers   'content-encoding': 'gzip',
25 verbose headers   'cache-control': 'max-age=300',
25 verbose headers   'content-length': '51045',
25 verbose headers   'accept-ranges': 'bytes',
25 verbose headers   date: 'Tue, 21 Jun 2016 13:14:58 GMT',
25 verbose headers   via: '1.1 varnish',
25 verbose headers   age: '40',
25 verbose headers   connection: 'keep-alive',
25 verbose headers   'x-served-by': 'cache-ord1725-ORD',
25 verbose headers   'x-cache': 'HIT',
25 verbose headers   'x-cache-hits': '1',
25 verbose headers   'x-timer': 'S1466514898.452202,VS0,VE0',
25 verbose headers   vary: 'Accept-Encoding' }
26 silly get cb [ 200,
26 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
26 silly get     etag: '"7ZUQ1648WT73G4C5MQ85MM0KK"',
26 silly get     'content-type': 'application/json',
26 silly get     'content-encoding': 'gzip',
26 silly get     'cache-control': 'max-age=300',
26 silly get     'content-length': '51045',
26 silly get     'accept-ranges': 'bytes',
26 silly get     date: 'Tue, 21 Jun 2016 13:14:58 GMT',
26 silly get     via: '1.1 varnish',
26 silly get     age: '40',
26 silly get     connection: 'keep-alive',
26 silly get     'x-served-by': 'cache-ord1725-ORD',
26 silly get     'x-cache': 'HIT',
26 silly get     'x-cache-hits': '1',
26 silly get     'x-timer': 'S1466514898.452202,VS0,VE0',
26 silly get     vary: 'Accept-Encoding' } ]
27 verbose get saving typescript to C:\Users\dalves\AppData\Roaming\npm-cache\registry.npmjs.org\typescript\.cache.json
28 verbose correctMkdir C:\Users\dalves\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
29 silly addNameTag next cb for typescript with tag latest
30 silly addNamed typescript@1.8.10
31 verbose addNamed "1.8.10" is a plain semver version for typescript
32 silly cache afterAdd typescript@1.8.10
33 verbose afterAdd C:\Users\dalves\AppData\Roaming\npm-cache\typescript\1.8.10\package\package.json not in flight; writing
34 verbose correctMkdir C:\Users\dalves\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
35 verbose afterAdd C:\Users\dalves\AppData\Roaming\npm-cache\typescript\1.8.10\package\package.json written
36 silly install resolved [ { name: 'typescript',
36 silly install resolved     author: { name: 'Microsoft Corp.' },
36 silly install resolved     homepage: 'http://typescriptlang.org/',
36 silly install resolved     version: '1.8.10',
36 silly install resolved     license: 'Apache-2.0',
36 silly install resolved     description: 'TypeScript is a language for application scale JavaScript development',
36 silly install resolved     keywords: [ 'TypeScript', 'Microsoft', 'compiler', 'language', 'javascript' ],
36 silly install resolved     bugs: { url: 'https://github.com/Microsoft/TypeScript/issues' },
36 silly install resolved     repository:
36 silly install resolved      { type: 'git',
36 silly install resolved        url: 'git+https://github.com/Microsoft/TypeScript.git' },
36 silly install resolved     main: './lib/typescript.js',
36 silly install resolved     typings: './lib/typescript.d.ts',
36 silly install resolved     bin: { tsc: './bin/tsc', tsserver: './bin/tsserver' },
36 silly install resolved     engines: { node: '>=0.8.0' },
36 silly install resolved     devDependencies:
36 silly install resolved      { jake: 'latest',
36 silly install resolved        mocha: '2.3.4',
36 silly install resolved        chai: 'latest',
36 silly install resolved        browserify: 'latest',
36 silly install resolved        istanbul: 'latest',
36 silly install resolved        'mocha-fivemat-progress-reporter': 'latest',
36 silly install resolved        tslint: 'next',
36 silly install resolved        typescript: 'next',
36 silly install resolved        tsd: 'latest' },
36 silly install resolved     scripts:
36 silly install resolved      { pretest: 'jake tests',
36 silly install resolved        test: 'jake runtests',
36 silly install resolved        build: 'npm run build:compiler && npm run build:tests',
36 silly install resolved        'build:compiler': 'jake local',
36 silly install resolved        'build:tests': 'jake tests',
36 silly install resolved        clean: 'jake clean',
36 silly install resolved        jake: 'jake',
36 silly install resolved        lint: 'jake lint',
36 silly install resolved        'setup-hooks': 'node scripts/link-hooks.js' },
36 silly install resolved     browser: { buffer: false, fs: false, os: false, path: false },
36 silly install resolved     gitHead: '794c57478ec2a44ee15fb3e245a4c5d2d1612375',
36 silly install resolved     _id: 'typescript@1.8.10',
36 silly install resolved     _shasum: 'b475d6e0dff0bf50f296e5ca6ef9fbb5c7320f1e',
36 silly install resolved     _from: 'typescript@latest',
36 silly install resolved     _npmVersion: '2.14.2',
36 silly install resolved     _nodeVersion: '5.9.0',
36 silly install resolved     _npmUser: { name: 'typescript', email: 'typescript@microsoft.com' },
36 silly install resolved     maintainers: [ [Object] ],
36 silly install resolved     dist:
36 silly install resolved      { shasum: 'b475d6e0dff0bf50f296e5ca6ef9fbb5c7320f1e',
36 silly install resolved        tarball: 'https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz' },
36 silly install resolved     _npmOperationalInternal:
36 silly install resolved      { host: 'packages-12-west.internal.npmjs.com',
36 silly install resolved        tmp: 'tmp/typescript-1.8.10.tgz_1460493736776_0.9304528103675693' },
36 silly install resolved     directories: {},
36 silly install resolved     _resolved: 'https://registry.npmjs.org/typescript/-/typescript-1.8.10.tgz',
36 silly install resolved     readme: 'ERROR: No README data found!' } ]
37 info install typescript@1.8.10 into C:\Users\dalves\AppData\Roaming\npm
38 info installOne typescript@1.8.10
39 verbose installOne of typescript to C:\Users\dalves\AppData\Roaming\npm not in flight; installing
40 verbose correctMkdir C:\Users\dalves\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
41 verbose lock using C:\Users\dalves\AppData\Roaming\npm-cache\_locks\typescript-df9e71e86be00960.lock for C:\Users\dalves\AppData\Roaming\npm\node_modules\typescript
42 silly install write writing typescript 1.8.10 to C:\Users\dalves\AppData\Roaming\npm\node_modules\typescript
43 verbose unbuild node_modules\typescript
44 info preuninstall typescript@1.8.10
45 info uninstall typescript@1.8.10
46 verbose unbuild rmStuff typescript@1.8.10 from C:\Users\dalves\AppData\Roaming\npm\node_modules
47 silly gentlyRm C:\Users\dalves\AppData\Roaming\npm\tsc.cmd is being gently removed
48 silly gentlyRm verifying C:\Users\dalves\AppData\Roaming\npm is an npm working directory
49 silly gentlyRm C:\Users\dalves\AppData\Roaming\npm\tsserver.cmd is being gently removed
50 silly gentlyRm verifying C:\Users\dalves\AppData\Roaming\npm is an npm working directory
51 silly gentlyRm containing path C:\Users\dalves\AppData\Roaming\npm is under npm's control, in C:\Users\dalves\AppData\Roaming\npm
52 silly gentlyRm deletion target C:\Users\dalves\AppData\Roaming\npm\tsc.cmd is under C:\Users\dalves\AppData\Roaming\npm
53 verbose gentlyRm vacuuming from C:\Users\dalves\AppData\Roaming\npm\tsc.cmd up to C:\Users\dalves\AppData\Roaming\npm
54 silly gentlyRm containing path C:\Users\dalves\AppData\Roaming\npm is under npm's control, in C:\Users\dalves\AppData\Roaming\npm
55 silly gentlyRm deletion target C:\Users\dalves\AppData\Roaming\npm\tsserver.cmd is under C:\Users\dalves\AppData\Roaming\npm
56 verbose gentlyRm vacuuming from C:\Users\dalves\AppData\Roaming\npm\tsserver.cmd up to C:\Users\dalves\AppData\Roaming\npm
57 silly vacuum-fs removing C:\Users\dalves\AppData\Roaming\npm\tsc.cmd
58 silly vacuum-fs removing C:\Users\dalves\AppData\Roaming\npm\tsserver.cmd
59 silly vacuum-fs finished vacuuming up to C:\Users\dalves\AppData\Roaming\npm
60 silly gentlyRm C:\Users\dalves\AppData\Roaming\npm\tsc is being gently removed
61 silly gentlyRm verifying C:\Users\dalves\AppData\Roaming\npm is an npm working directory
62 silly gentlyRm containing path C:\Users\dalves\AppData\Roaming\npm is under npm's control, in C:\Users\dalves\AppData\Roaming\npm
63 silly gentlyRm deletion target C:\Users\dalves\AppData\Roaming\npm\tsc is under C:\Users\dalves\AppData\Roaming\npm
64 verbose gentlyRm vacuuming from C:\Users\dalves\AppData\Roaming\npm\tsc up to C:\Users\dalves\AppData\Roaming\npm
65 silly vacuum-fs finished vacuuming up to C:\Users\dalves\AppData\Roaming\npm
66 silly gentlyRm C:\Users\dalves\AppData\Roaming\npm\tsserver is being gently removed
67 silly gentlyRm verifying C:\Users\dalves\AppData\Roaming\npm is an npm working directory
68 silly gentlyRm containing path C:\Users\dalves\AppData\Roaming\npm is under npm's control, in C:\Users\dalves\AppData\Roaming\npm
69 silly gentlyRm deletion target C:\Users\dalves\AppData\Roaming\npm\tsserver is under C:\Users\dalves\AppData\Roaming\npm
70 verbose gentlyRm vacuuming from C:\Users\dalves\AppData\Roaming\npm\tsserver up to C:\Users\dalves\AppData\Roaming\npm
71 silly vacuum-fs removing C:\Users\dalves\AppData\Roaming\npm\tsc
72 silly vacuum-fs removing C:\Users\dalves\AppData\Roaming\npm\tsserver
73 silly vacuum-fs finished vacuuming up to C:\Users\dalves\AppData\Roaming\npm
74 silly vacuum-fs finished vacuuming up to C:\Users\dalves\AppData\Roaming\npm
75 info postuninstall typescript@1.8.10
76 silly gentlyRm C:\Users\dalves\AppData\Roaming\npm\node_modules\typescript is being purged from base C:\Users\dalves\AppData\Roaming\npm
77 verbose gentlyRm don't care about contents; nuking C:\Users\dalves\AppData\Roaming\npm\node_modules\typescript
78 silly vacuum-fs purging C:\Users\dalves\AppData\Roaming\npm\node_modules\typescript
79 silly vacuum-fs quitting because other entries in C:\Users\dalves\AppData\Roaming\npm\node_modules
80 verbose tar unpack C:\Users\dalves\AppData\Roaming\npm-cache\typescript\1.8.10\package.tgz
81 verbose tar unpacking to C:\Users\dalves\AppData\Roaming\npm\node_modules\typescript
82 silly gentlyRm C:\Users\dalves\AppData\Roaming\npm\node_modules\typescript is being purged
83 verbose gentlyRm don't care about contents; nuking C:\Users\dalves\AppData\Roaming\npm\node_modules\typescript
84 silly gunzTarPerm modes [ '777', '666' ]
85 silly gunzTarPerm extractEntry package.json
86 silly gunzTarPerm extractEntry .npmignore
87 silly gunzTarPerm extractEntry README.md
88 silly gunzTarPerm extractEntry ThirdPartyNoticeText.txt
89 silly gunzTarPerm extractEntry AUTHORS.md
90 silly gunzTarPerm extractEntry CONTRIBUTING.md
91 silly gunzTarPerm extractEntry CopyrightNotice.txt
92 silly gunzTarPerm extractEntry LICENSE.txt
93 silly gunzTarPerm extractEntry bin/tsc
94 silly gunzTarPerm extractEntry bin/tsserver
95 silly gunzTarPerm extractEntry lib/README.md
96 silly gunzTarPerm extractEntry lib/typescript.js
97 silly gunzTarPerm extractEntry lib/tsserver.js
98 silly gunzTarPerm extractEntry lib/tsc.js
99 silly gunzTarPerm extractEntry lib/typescriptServices.js
100 silly gunzTarPerm extractEntry lib/lib.d.ts
101 silly gunzTarPerm extractEntry lib/lib.dom.d.ts
102 silly gunzTarPerm extractEntry lib/lib.es7.d.ts
103 silly gunzTarPerm extractEntry lib/lib.core.d.ts
104 silly gunzTarPerm extractEntry lib/lib.webworker.d.ts
105 silly gunzTarPerm extractEntry lib/lib.es6.d.ts
106 silly gunzTarPerm extractEntry lib/lib.core.es7.d.ts
107 silly gunzTarPerm extractEntry lib/typescript.d.ts
108 silly gunzTarPerm extractEntry lib/lib.core.es6.d.ts
109 silly gunzTarPerm extractEntry lib/typescriptServices.d.ts
110 silly gunzTarPerm extractEntry lib/lib.scriptHost.d.ts
111 silly gunzTarPerm extractEntry test.config
112 verbose write writing to C:\Users\dalves\AppData\Roaming\npm\node_modules\typescript\package.json
113 info preinstall typescript@1.8.10
114 verbose readDependencies loading dependencies from C:\Users\dalves\AppData\Roaming\npm\node_modules\typescript\package.json
115 verbose readDependencies loading dependencies from C:\Users\dalves\AppData\Roaming\npm\node_modules\typescript\package.json
116 silly install resolved []
117 verbose about to build C:\Users\dalves\AppData\Roaming\npm\node_modules\typescript
118 info build C:\Users\dalves\AppData\Roaming\npm\node_modules\typescript
119 info linkStuff typescript@1.8.10
120 silly linkStuff typescript@1.8.10 has C:\Users\dalves\AppData\Roaming\npm\node_modules as its parent node_modules
121 silly linkStuff typescript@1.8.10 is part of a global install
122 silly linkStuff typescript@1.8.10 is installed into a global node_modules
123 silly linkStuff typescript@1.8.10 is installed into the top-level global node_modules
124 verbose linkBins typescript@1.8.10
125 verbose link bins [ { tsc: './bin/tsc', tsserver: './bin/tsserver' },
125 verbose link bins   'C:\\Users\\dalves\\AppData\\Roaming\\npm',
125 verbose link bins   true ]
126 verbose linkMans typescript@1.8.10
127 verbose rebuildBundles typescript@1.8.10
128 info install typescript@1.8.10
129 info postinstall typescript@1.8.10
130 verbose unlock done using C:\Users\dalves\AppData\Roaming\npm-cache\_locks\typescript-df9e71e86be00960.lock for C:\Users\dalves\AppData\Roaming\npm\node_modules\typescript
131 verbose validateInstall loading C:\Users\dalves\AppData\Roaming\npm\package.json for validation
132 verbose stack Error: The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!
132 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:125:32
132 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:268:7
132 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:142:5
132 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
132 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
132 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
132 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
132 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
132 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
132 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
133 verbose cwd C:\Users\dalves
134 error Windows_NT 6.1.7601
135 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "typescript"
136 error node v4.4.3
137 error npm  v2.15.1
138 error code EPEERINVALID
139 error peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!
139 error peerinvalid Peer grunt-penthouse@0.3.0 wants grunt@~0.4.2
140 verbose exit [ 1, true ]
```

**Comment by kitsonk** [comment]
This has nothing to do with TypeScript.  You have installed `grunt-penthouse` (likely globally) which has a peer dependency of `grunt@~0.4.2` but you have `grunt@1.0.1` installed.

Do a `npm ls --global` and you should see the dependency graph of your packages.  You will notice [`typescript` has no dependencies](https://www.npmjs.com/package/typescript).

**Comment by Smithahd** [comment]
I am also facing the same error . what should be done for that

**Comment by Shridhara53** [comment]
I'm facing the similar issue. Could I get any solution for this issue.
