### ISSUE TITLE
Cannot build on OS X

### ISSUE THREAD

**Issue by billti** [Microsoft/TypeScript#9553]
I just did a fresh sync of `master` on my Mac, did an `npm install -g gulp` and `npm install`, now trying to run `gulp local` I get the below. Any idea what's going on here? 

I do see a comment at that line stating "*// This is silly. We include Q because orchestrator (a part of gulp) depends on it, but its not included.*", but I assume it's supposed to work. It looks like whatever `ts-node` is using doesn't understanding the `/// <reference types="q" />` line and the new `@types` support.

CC @weswigham and @mhegazy 

```
MacBook-Pro-2:TypeScript bill$ gulp local
[09:47:58] Requiring external module ts-node/register

/Users/bill/src/TypeScript/node_modules/ts-node/src/index.ts:280
        throw new TSError(diagnosticList)
              ^
TSError: ⨯ Unable to compile TypeScript
Gulpfile.ts (26,23): Identifier 'Q' must be imported from a module (2686)
    at getOutput (/Users/bill/src/TypeScript/node_modules/ts-node/src/index.ts:280:15)
    at compile (/Users/bill/src/TypeScript/node_modules/ts-node/src/index.ts:289:14)
    at loader (/Users/bill/src/TypeScript/node_modules/ts-node/src/index.ts:304:23)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/bill/src/TypeScript/node_modules/ts-node/src/index.ts:321:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:193:16)
```

**Comment by weswigham** [comment]
This isn't OSX-specific. We republished Q yesterday and changed it so it had to be used as a module, rather than a `reference types`. I'll open a PR to fix it.
