### ISSUE TITLE
tsserver rename command throws exception

### ISSUE THREAD

**Issue by ananthakumaran** [Microsoft/TypeScript#9808]
**TypeScript Version:**  2.0.0-beta

**Stacktrace**

```
Err 191   Exception on executing command {"command":"rename","seq":"55","arguments":{"file":"\/Users\/ananthakumaran\/work\/veritrans\/rubicon\/vendor\/rubicon-react\/src\/js\/components\/kioson\/instruction.jsx","line":7,"offset":7}}:
Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at walk (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:59060:25)
    at visitEachNode (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:9054:30)
    at Object.forEachChild (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:9424:24)
    at walk (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:59078:24)
    at visitNode (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:9042:20)
    at Object.forEachChild (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:9422:21)
    at walk (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:59078:24)
    at visitEachNode (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:9054:30)
    at Object.forEachChild (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:9408:24)
    at walk (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:59082:32)
Info 192  response: {"seq":0,"type":"response","command":"rename","request_seq":"55","success":false,"message":"Error processing request. Cannot read property 'kind' of undefined\nTypeError: Cannot read property 'kind' of undefined\n    at walk (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:59060:25)\n    at visitEachNode (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:9054:30)\n    at Object.forEachChild (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:9424:24)\n    at walk (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:59078:24)\n    at visitNode (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:9042:20)\n    at Object.forEachChild (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:9422:21)\n    at walk (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:59078:24)\n    at visitEachNode (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:9054:30)\n    at Object.forEachChild (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:9408:24)\n    at walk (/Users/ananthakumaran/work/repos/tide/tsserver/tsserver.js:59082:32)"}
```

**Code**

``` ts
var React = require('react');

var Instruction = require('../instruction');
var Translation = require('../translation');
var InstructionItem = require('../instruction-item');

var KiosonInstruction = React.createClass({
  render() {
  }
})

module.exports = KiosonInstruction;
```

**Comment by andy-ms** [comment]
@ananthakumaran We've rewritten this functionality since this issue was first created. Are you still seeing this problem?

**Comment by mhegazy** [comment]
@ananthakumaran please reopen if you are still running into issues.
