### ISSUE TITLE
TS2.0.0: --allowJs option throws an error, when not in the same dir as the file

### ISSUE THREAD

**Issue by cebor** [Microsoft/TypeScript#9888]
**TypeScript Version:** 2.0.0-beta

Compiling .js files from outside of a folder throws an error:

```bash
# this works fine inside dist/
$ tsc --outFile bundle.js --target es5 --allowJs bundle.es2015.js
```

```bash
$ cd ..

# this throws an error
$ tsc --outFile dist/bundle.js --target es5 --allowJs dist/bundle.es2015.js

/usr/local/lib/node_modules/typescript/lib/tsc.js:36920
                throw e;
                ^

TypeError: Cannot read property 'id' of undefined
    at getNodeId (/usr/local/lib/node_modules/typescript/lib/tsc.js:13014:18)
    at getNodeLinks (/usr/local/lib/node_modules/typescript/lib/tsc.js:13402:26)
    at checkExpressionCached (/usr/local/lib/node_modules/typescript/lib/tsc.js:22848:25)
    at /usr/local/lib/node_modules/typescript/lib/tsc.js:15426:94
    at Object.map (/usr/local/lib/node_modules/typescript/lib/tsc.js:199:29)
    at getTypeOfVariableOrParameterOrProperty (/usr/local/lib/node_modules/typescript/lib/tsc.js:15426:44)
    at getTypeOfSymbol (/usr/local/lib/node_modules/typescript/lib/tsc.js:15561:24)
    at checkPropertyAccessExpressionOrQualifiedName (/usr/local/lib/node_modules/typescript/lib/tsc.js:21042:28)
    at checkPropertyAccessExpression (/usr/local/lib/node_modules/typescript/lib/tsc.js:21007:20)
    at checkExpressionWorker (/usr/local/lib/node_modules/typescript/lib/tsc.js:22937:28)
```

```javascript
// bundle.es2015.js
let a = "s";
```

With TS1.8.10 all works fine.

**Comment by andy-ms** [comment]
I haven't reproduced this error in `typescript@next`.

Here's what I did:

    mkdir repro; cd repro
    npm install typescript@next
    mkdir dist
    echo 'let a = "s";' > dist/bundle.es2015.js
    node node_modules/typescript/bin/tsc --outFile dist/bundle.js --target es5 --allowJs dist/bundle.es2015.js

Can you try the same?

**Comment by frankwallis** [comment]
FYI - I am seeing a similar error in typescript@2.0.0 and typescript@next, it does not happen in typescript@1.8.10

```
TypeError: Cannot read property 'id' of undefined
    at Object.getNodeId (C:\Users\Developer\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13122:18)
    at getGeneratedNameForNode (C:\Users\Developer\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:30150:29)
    at emitClassLikeDeclarationForES6AndHigher (C:\Users\Developer\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:33703:37)
    at emitClassLikeDeclaration (C:\Users\Developer\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:33661:21)
    at emitClassExpression (C:\Users\Developer\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:33651:24)
    at emitJavaScriptWorker (C:\Users\Developer\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35761:32)
    at emitNodeWithoutSourceMap (C:\Users\Developer\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35569:21)
    at emitNodeWithSourceMap (C:\Users\Developer\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35563:21)
    at emitNodeConsideringCommentsOption (C:\Users\Developer\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35554:21)
    at emit (C:\Users\Developer\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35537:17)                                    
    at emitOptional (C:\Users\Developer\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:30208:21)
    at emitReturnStatement (C:\Users\Developer\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32418:17)
```

tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es6", // for async/await support
    "jsx": "react",
    "declaration": false,
    "moduleResolution": "classic", // to enable paths mappings
    "module": "commonjs", // so we can run the code in nodejs when testing
    "experimentalDecorators": true, // decorator support
    "inlineSourceMap": true, // pass source maps to babel
    "inlineSources": false,
    "noImplicitAny": false
  },
  "baseUrl": ".",
  "compileOnSave": true
}
```

**Comment by andy-ms** [comment]
@frankwallis: I notice that your `tsconfig.json` does not have `allowJs`, so you are likely reproducing the error in a different way. Could you provide some sample code along with the particular compile command (likely `tsc -p src`) that will help to reproduce your error?

**Comment by cebor** [comment]
@andy-ms 

typescript@next: no error

typescript@beta: erros

**Comment by andy-ms** [comment]
@cebor The instructions I gave above still work on my machine even when replacing `npm install typescript@next` with `npm install typescript@beta`. Does it break for you? If not, can you provide some sample code for which it does break?

**Comment by cebor** [comment]
@andy-ms 

```bash
npm clean
rm -rf node_modules
npm i
```

fixed it for me!

**Comment by frankwallis** [comment]
@andy-ms I have found that you can reproduce it by compiling this code with target es6:

```
function enhance(clazz: typeof Function) {
	return class extends clazz {
		static instances: number = 0;
	}
}
```

**Comment by andy-ms** [comment]
@frankwallis Thanks! I've created a new issue: #9966
